### ISSUE TITLE
Jupyterhub cant connect kernels and terminal

### ISSUE THREAD

**Issue by penumbra-** [jupyterhub/jupyterhub#1000]
Hi all,

Im trying to set up jupyterhub server on remote machine with ssh.
I installed anaconda with
`bash Anaconda3......`
and get in the anaconda enviroment with
`source ~/anaconda3/bin/activate`

Also, i installed jupyterhub via pip inside anaconda enviroment and command `which jupyterhub` returns `/home/lzivadinovic/anaconda3/bin/jupyterhub`

I set my jupyterhub_config.py file and i CAN acces the server via web browser and log in as multiple users. I executed jupyterhub with

`sudo ~/anaconda3/bin/jupyterhub -f ~/anaconda3/jupyterhub_anaconda/jupyterhub_config.py`

The problem is when i go to new then terminal i get black empty screen. Also, when i run new notebook i get icon in right corrner saying `No connection to kernel` and a grayed out python3 text.

So my jupyterhub log is something like

> # lzivadinovic @ titan in ~/anaconda3/jupyterhub_anaconda [21:25:03] 
> $ sudo ../bin/jupyterhub -f ./jupyterhub_config.py                     
> [I 2017-02-24 21:27:11.438 JupyterHub app:724] Loading cookie_secret from /home/lzivadinovic/anaconda3/jupyterhub_anaconda/jupyterhub_cookie_secret
> [W 2017-02-24 21:27:11.460 JupyterHub app:365] 
>     Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
>     Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
>     
> [W 2017-02-24 21:27:11.462 JupyterHub app:864] No admin users, admin interface will be unavailable.
> [W 2017-02-24 21:27:11.462 JupyterHub app:865] Add any administrative users to `c.Authenticator.admin_users` in config.
> [I 2017-02-24 21:27:11.462 JupyterHub app:892] Not using whitelist. Any authenticated user will be allowed.
> [I 2017-02-24 21:27:11.473 JupyterHub app:1453] Hub API listening on http://127.0.0.1:8081/hub/
> [W 2017-02-24 21:27:11.475 JupyterHub app:1174] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
> [I 2017-02-24 21:27:11.475 JupyterHub app:1176] Starting proxy @ http://MYSERVER/
> 21:27:11.533 - info: [ConfigProxy] Proxying http://MYSERVERto http://127.0.0.1:8081
> 21:27:11.534 - info: [ConfigProxy] Proxy API at http://127.0.0.1:444/api/routes
> [I 2017-02-24 21:27:11.578 JupyterHub app:1485] JupyterHub is now running at http://MYSERVER/
> [I 2017-02-24 21:27:15.154 JupyterHub log:100] 200 GET /hub/login (@currentIP) 20.23ms
> Last login: Fri Feb 24 21:13:35 CET 2017
> Welcome to Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-49-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com/
> 
> [I 2017-02-24 21:27:19.846 JupyterHub spawner:783] Spawning jupyterhub-singleuser '--user="lzivadinovic"' '--cookie-name="jupyter-hub-token-lzivadinovic"' '--base-url="/user/lzivadinovic"' '--hub-host=""' '--hub-prefix="/hub/"' '--hub-api-url="http://127.0.0.1:8081/hub/api"' '--ip="127.0.0.1"' --port=51983
> [W 2017-02-24 21:27:20.285 lzivadinovic login:222] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
> [I 2017-02-24 21:27:20.288 lzivadinovic notebookapp:1201] Serving notebooks from local directory: /home/lzivadinovic
> [I 2017-02-24 21:27:20.288 lzivadinovic notebookapp:1201] 0 active kernels 
> [I 2017-02-24 21:27:20.288 lzivadinovic notebookapp:1201] The Jupyter Notebook is running at: http://127.0.0.1:51983/user/lzivadinovic/
> [I 2017-02-24 21:27:20.288 lzivadinovic notebookapp:1202] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
> [I 2017-02-24 21:27:20.345 lzivadinovic log:47] 302 GET /user/lzivadinovic (127.0.0.1) 1.67ms
> [I 2017-02-24 21:27:20.348 JupyterHub base:322] User lzivadinovic server took 0.767 seconds to start
> [I 2017-02-24 21:27:20.349 JupyterHub orm:188] Adding user lzivadinovic to proxy /user/lzivadinovic => http://127.0.0.1:51983
> [I 2017-02-24 21:27:20.363 JupyterHub log:100] 302 POST /hub/login?next= (@currentIP) 789.09ms
> [I 2017-02-24 21:27:20.363 JupyterHub login:91] User logged in: lzivadinovic
> [I 2017-02-24 21:27:20.402 JupyterHub log:100] 302 GET /hub/ (lzivadinovic@currentIP) 9.65ms
> [I 2017-02-24 21:27:20.418 lzivadinovic log:47] 302 GET /user/lzivadinovic (@currentIP) 0.97ms
> [I 2017-02-24 21:27:20.462 JupyterHub log:100] 200 GET /hub/api/authorizations/cookie/jupyter-hub-token-lzivadinovic/[secret] (lzivadinovic@127.0.0.1) 12.74ms
> [I 2017-02-24 21:27:25.430 lzivadinovic kernelmanager:89] Kernel started: 7b86b887-0e0b-4d08-af05-9c9a65c180a9
> [W 2017-02-24 21:27:25.464 lzivadinovic log:47] 404 GET /user/lzivadinovic/nbextensions/widgets/notebook/js/extension.js?v=20170224212720 (91.187.128.232) 4.04ms referer=http://titan.aob.rs:443/user/lzivadinovic/notebooks/Untitled.ipynb
> [I 2017-02-24 21:31:54.371 lzivadinovic management:304] New terminal with automatic name: 1
> 

is i can see, kernel is started, but jupyterhub can not connect to it for some reason. Also, black screen when i try to open terminal.

Can someone help me? #

EDIT:
When i run server on localhost IP and do a ssh port forward from remote to local machine i can in local browser to run localhost:8000 and to login and use terminal and everything.

**Comment by minrk** [comment]
> When i run server on localhost IP and do a ssh port forward from remote to local machine i can in local browser to run localhost:8000 and to login and use terminal and everything.

This indicates that a proxy and/or firewall is blocking websockets. Do you know of any proxy or firewall between you and the server?

**Comment by penumbra-** [comment]
Yeah, there is like our academy network proxy at `proxy.academy_network:8080`
I asked our network admins to open port 443, and i set our jupyterhub on that port. How can I fix this? Any suggestions?

**Comment by penumbra-** [comment]
@minrk Yeah, there is like our academy network proxy at `proxy.academy_network:8080`
I asked our network admins to open port 443, and i set our jupyterhub on that port. How can I fix this? Any suggestions?

**Comment by willingc** [comment]
@penumbra I hope you were able to resolve the proxy/firewall config and get things working. If not, please let us know what we can do to assist. Thanks.

**Comment by penumbra-** [comment]
> @penumbra I hope you were able to resolve the proxy/firewall config and get things working. If not, please let us know what we can do to assist. Thanks.

I didn't manage to resolve the issue. Our academy network managers are very strict so i hosted on localhost:8000 and i am just port forwarding via SSH/Putty to use it at home.

Security concern question, is it OK to use only http behind SSH tunnel or should i switch to self signed ssl keys (server are used by max 20 people on 3 different accounts; like "student", "admin1", "admin2")?

**Comment by willingc** [comment]
@rgbkrk @minrk Tossing this security question to you for the best approach. It seems at minimum SSL would be prudent.

**Comment by minrk** [comment]
I can't speak with authority, but tunneling loopback to loopback interfaces should be okay because it is rather difficult to spy on localhost connections without root permissions on one machine or the other. Since the Hub itself is using localhost HTTP internally between the proxy and the Hub/single-user servers, the only increase in attack surface is localhost on your home computer.

**Comment by willingc** [comment]
Closing this issue as answered for JupyterHub's current implementation. If you have further questions, please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!
