### ISSUE TITLE
suggest using s or srv instead of services in jupyterhub service url

### ISSUE THREAD

**Issue by cailiang9** [jupyterhub/jupyterhub#1004]
otherwise it will be too long when there is a long path after the service url:
jhub.prod.xxxx.com/services/pubnb/notebooks/path/to/notebook.ipynb
to
jhub.prod.xxxx.com/srv/pubnb/notebooks/path/to/notebook.ipynb would be better.

Or it is even better that we can configure http proxy like 
pubnb.prod.xxxx.com/notebooks/path/to/notebook.ipynb.

Because of some reasons we want the pubnb service run with jupyterhub (on same machine/OS)

**Comment by minrk** [comment]
I don't think a few characters makes a significant difference here, and I would prefer to keep the clearer URL parts.

**Comment by cailiang9** [comment]
User content would be a more important part to be clear in URL.

**Comment by willingc** [comment]
@cailiang9 Perhaps you could clarify what you mean by a *pubnb service*. While we do strive for user customization where possible, there will be cases where a user request is highly specific and custom. In this case, the request would fall outside our present development plan.

In this particular case, based on my understanding, I believe that you could develop a custom proxy with aliases to meet your needs.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!
