### ISSUE TITLE
Dynamic whitelist not possible

### ISSUE THREAD

**Issue by stefanoborini** [jupyterhub/jupyterhub#1012]
I need a dynamic whitelist, possibly from a file. Currently, the only way to modify the whitelist is to restart jupyterhub. It would be better if one could change the whitelist without having to do so.

I tried to override whitelist in my authenticator with a property, but the application tries to set the normalized usernames back into the whitelist. This operation is clearly not possible if I am generating the whitelist from a file or db. I am working around this by planting a fake setter method, but it is suboptimal.

**Comment by barrachri** [comment]
What about leaving the whitelist empty inside the config and create a dynamic_whitelist using the Authenticator ?

**Comment by minrk** [comment]
You should be able to do this with a custom Authenticator that overrides `check_whitelist`:

```python
class WhitelistAuthenticator(Authenticator):
    whitelist_file = Unicode(config=True)

    def check_whitelist(self, username):
        whitelist = set()
        with open(self.whitelist_file) as f:
            for line in f:
                whitelist.add(line.strip())
        return username in whitelist
```

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!
