### ISSUE TITLE
Jupyterhub with AFS home directories

### ISSUE THREAD

**Issue by JMurph2015** [jupyterhub/jupyterhub#1019]
I would like to set up JupyterHub for use on a system where most users have home directories on an AFS system.
How to reproduce: attempt to log in to a Jupyterhub using an account which has an AFS directory as its home directory, and this directory is not writable by the local root.

**What you expected to happen**
Expected the write access to be delegated to the user login, and in theory the AFS tokens would be obtained and everything would be happy because the PAM magic used for this process in SSH works.
**What actually happens**
The spawner appears to run as root which has write access to a shockingly small number of things on this server, and it gets confused and throws the error 
`IPython parent '/afs/<my home dir>' is not a writable location, using a temp directory.`

`# jupyterhub --version
0.7.2
`

```
# jupyterhub troubleshoot
[I 2017-03-11 19:03:33.449 JupyterHub app:724] Loading cookie_secret from /root/jupyterhub_cookie_secret
[W 2017-03-11 19:03:33.482 JupyterHub app:365] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[W 2017-03-11 19:03:33.485 JupyterHub app:864] No admin users, admin interface will be unavailable.
[W 2017-03-11 19:03:33.485 JupyterHub app:865] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2017-03-11 19:03:33.485 JupyterHub app:892] Not using whitelist. Any authenticated user will be allowed.
[I 2017-03-11 19:03:33.496 JupyterHub app:1453] Hub API listening on http://127.0.0.1:8081/hub/
[I 2017-03-11 19:03:33.498 JupyterHub app:1176] Starting proxy @ http://*:8000/
19:03:33.563 - info: [ConfigProxy] Proxying https://*:8000 to http://127.0.0.1:8081
19:03:33.564 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[I 2017-03-11 19:03:33.601 JupyterHub app:1485] JupyterHub is now running at http://127.0.0.1:8000/```

**Comment by minrk** [comment]
There might be something wrong in how we handle PAM sessions for this use case. Something in the [kerberos example repo](https://github.com/jupyterhub/jupyterhub-example-kerberos) may prove helpful. It has a few tweaks with respect to PAM for kerberos to work.

> The spawner appears to run as root

This is concerning. Where is the indication that it is root?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for over a month. Please leave us a note with the additional information requested and we will be happy to reopen this issue. Thanks! :sunflower:

**Comment by JMurph2015** [comment]
Sorry this got left so long.  The workstation I was setting this up on promptly got package conflicted after this issue, so I hadn't gotten around to this since.  I'll let you guys know if I try again, I think some tweaks to the PAM loading process may make it workable.
