### ISSUE TITLE
PAM Authentication errors on RHEL

### ISSUE THREAD

**Issue by Alexanderallenbrown** [jupyterhub/jupyterhub#1023]
Similar to Issue #323 , I am getting PAM authentication errors when multiple users attempt to sign in.

Version is Jupyterhub 0.7.2

Workaround was commenting everything related to SELinux in /etc/pam.d/ but this seems like a dirty hack. Issue #323 was closed due to commenters using an older version of Jupyterhub, but because I'm using the latest version, I thought I'd reopen.

**Comment by willingc** [comment]
Hi @Alexanderallenbrown,

Would you mind sharing bit of information such as a traceback of the errors, the version of RHEL that you are using, and your jupyterhub_config.py? It would help us solve your issue.

Thanks!

**Comment by minrk** [comment]
@Alexanderallenbrown does it work with this config:

```python
c.PAMAuthenticator.open_sessions = False
```

?

**Comment by csbrown** [comment]
I am having a similar issue related to pamela.  c.PAMAuthenticator.open_sessions = False works for me, python3 -m pamela -a '[other_user]' fails with [PAM Error 7] Authentication failure
, but python3 -m pamela -a '[current_user]' succeeds, and this is affecting jupyterhub.  This whole thread seems to be a problem with pamela, not with jupyterhub.  Gonna open a thread on the pamela github which, it seems to me, is where this belongs.

**Comment by csbrown** [comment]
@Alexanderallenbrown is the user you're running jupyterhub under in the shadow group?  That cleared all of this up for me.

**Comment by laurikoobas** [comment]
I finally managed to make it work under Debian (#1026), maybe the same thing works for you.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all! :sunflower:
