### ISSUE TITLE
Dead kernel

### ISSUE THREAD

**Issue by barrachri** [jupyterhub/jupyterhub#1031]
I am playing with JupyterHub using Docker Swarm, everything works fine apart from this:

```
[I 01:44:25.150 NotebookApp] Kernel started: f241fe18-8b34-43bf-8e3a-5b31ecd93b7f
[I 01:44:28.148 NotebookApp] KernelRestarter: restarting kernel (1/5)
[I 01:44:31.156 NotebookApp] KernelRestarter: restarting kernel (2/5)
[I 01:44:34.167 NotebookApp] KernelRestarter: restarting kernel (3/5)
[W 01:44:35.650 NotebookApp] Timeout waiting for kernel_info reply from f241fe18-8b34-43bf-8e3a-5b31ecd93b7f
[I 01:44:37.173 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel f241fe18-8b34-43bf-8e3a-5b31ecd93b7f restarted
[W 01:44:40.180 NotebookApp] KernelRestarter: restart failed
[W 01:44:40.180 NotebookApp] Kernel f241fe18-8b34-43bf-8e3a-5b31ecd93b7f died, removing from map.
ERROR:root:kernel f241fe18-8b34-43bf-8e3a-5b31ecd93b7f restarted failed!
[W 01:44:40.797 NotebookApp] Kernel deleted before session
```

<img width="1165" alt="screen shot 2017-03-21 at 02 46 40" src="https://cloud.githubusercontent.com/assets/4802083/24129126/b130363e-0de0-11e7-944c-1afb142de267.png">

From the terminal I can see the process of the kernel, but then it dies.

What is strange for me is that the R-Kernel works fine and I can use IPython from the terminal.

**Comment by willingc** [comment]
@barrachri Thanks for the question. Just an FYI, I edited the log to display a bit cleaner. If you use 3 backticks (```) before and after the log text GitHub will render the log nicely :cookie:

**Comment by barrachri** [comment]
Thanks @willingc!

I resolved the issue.

If you run the Docker service specifying a command like `'command' : 'start-singleuser.sh` the IPython kernel crashes, if you put the command inside the image it works.

is this issue more related to IPython or IPykernel ?

**Comment by minrk** [comment]
I don't really understand how specifying the command when starting vs in the image could make a difference. Maybe there is another option that's implicitly different when specifying the command in two different places? My guess is it has something to do with the allocated terminal.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!
