### ISSUE TITLE
Uploading Notebook to all Users

### ISSUE THREAD

**Issue by JoshuaC3** [jupyterhub/jupyterhub#1033]
Is it possible to upload an .ipynb, or even better a file containing some .ipynb and data, such that it goes into each users directory?

It is a similar request to this question [this question](https://github.com/jupyterhub/jupyterhub/issues/631) but I feel this is more about sharing live/custom notebooks. My aim is for each users to have the same notebook in the beginning and then to be able to edit their version of this independently of one another, with no need to share (though that will be nice). I am currently using PAM login.

**Comment by willingc** [comment]
Hi @JoshuaC3,

One way that people teaching courses accomplish this is by using [nbgrader](https://github.com/jupyter/nbgrader). Here's an [example workflow from the docs](https://nbgrader.readthedocs.io/en/stable/user_guide/creating_and_grading_assignments.html#workflow-example-instructor-generating-an-assignment-release).

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!
