### ISSUE TITLE
Daily Log Files

### ISSUE THREAD

**Issue by hani1814** [jupyterhub/jupyterhub#1038]
Hi,

Is it possible to create daily jupyterhub log files. At the moment we direct the log >file when we start the hub.

Thank you

**Comment by minrk** [comment]
Yes, you can do this with [logrotate](http://www.linuxcommand.org/man_pages/logrotate8.html), or pipe to `logger` to use syslog instead of directly to a file.

For example, with this logrotate config file:

```
/var/log/jupyterhub.log {
  copytruncate
  daily
}
```

and run this daily by putting a script in `/etc/cron.daily/`:

```bash
logrotate /path/to/above-config
```

Or use syslog:

    jupyterhub | logger -t jupyterhub
