### ISSUE TITLE
JupyterHub 404 error

### ISSUE THREAD

**Issue by Anishkumarv** [jupyterhub/jupyterhub#1042]
Hi Team,

I am new to jupyterhub, i hav configured jupyterhup in Redhat 6.6

root@HKLVADRDA01[bin] # ./jupyterhub --version
0.7.2

root@HKLVADRDA01[bin] # node --version
v6.10.1

root@HKLVADRDA01[bin] # ./python --version
Python 3.6.0 :: Anaconda 4.3.1 (64-bit)

root@HKLVADRDA01[bin] # ./configurable-http-proxy  --version
1.3.1

After started the proxy and jupyterhub when i tried to access jupyterhub I am getting 404 "no service registered for this URL" error.

Jupyterbhub Startup log:

root@HKLVADRDA01[bin] # ./jupyterhub   --no-ssl
[I 2017-03-26 23:57:50.985 JupyterHub app:724] Loading cookie_secret from /data/21MAR2017/anaconda3/bin/jupyterhub_cookie_secret
[W 2017-03-26 23:57:51.020 JupyterHub app:365]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[W 2017-03-26 23:57:51.024 JupyterHub app:864] No admin users, admin interface will be unavailable.
[W 2017-03-26 23:57:51.024 JupyterHub app:865] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2017-03-26 23:57:51.024 JupyterHub app:892] Not using whitelist. Any authenticated user will be allowed.
[I 2017-03-26 23:57:51.038 JupyterHub app:1453] Hub API listening on http://127.0.0.1:8081/hub/
[I 2017-03-26 23:57:51.054 JupyterHub app:1143] Proxy already running at: http://*:8000/
[I 2017-03-26 23:57:51.058 JupyterHub app:1485] JupyterHub is now running at http://127.0.0.1:8000/

Proxy startup log:

root@HKLVADRDA01[bin] # ./configurable-http-proxy
23:57:40.377 - warn: [ConfigProxy] REST API is not authenticated.
23:57:40.389 - info: [ConfigProxy] Proxying http://*:8000 to (no default)
23:57:40.389 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
**23:58:08.660 - error: [ConfigProxy] 404 GET /
23:58:12.183 - error: [ConfigProxy] 404 GET /**

Error message:
![image](https://cloud.githubusercontent.com/assets/19161748/24332865/86b910f2-1280-11e7-82a3-22aa821af44c.png)

**Comment by minrk** [comment]
Looks like there might already be a proxy running that isn't set up correctly. Is that expected? If not, look for and shutdown any `configurable-http-proxy` instances and relaunch jupyterhub.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
