### ISSUE TITLE
JupyterHub with Jupyter Kernel Gateway

### ISSUE THREAD

**Issue by tguillemot** [jupyterhub/jupyterhub#1045]
Hi and thanks for your job in JupyterHub. It's awesome !!!

Do you think it is possible to use JupyterHub with Jupyter Kernel Gateway instead of Jupyter Notebook ?
Maybe do you have an example ?

**Comment by willingc** [comment]
Hi @tguillemot,

Thanks for the kind words :-) I'm going to pass along your question to @parente for his thoughts.

**Comment by minrk** [comment]
If KernelGateway can use HubAuth for login, this should be possible. @ryanlovett has a tool for deploying ~any web application (RStudio, specifically) with JupyterHub.

@ryanlovett would you be interested in making your hub-auth-proxy tool a standalone project on the JupyterHub org? I think that would be generally useful.

**Comment by ryanlovett** [comment]
Sure, however:

-  I'm basically its only user at the moment so it might not be especially robust,
-  It is a notebook extension rather than the server substitute that @tguillemot was inquiring about, 
-  It doesn't proxy web sockets.

[nbserverproxy](https://github.com/ryanlovett/nbserverproxy) - proxies arbitrary web services. Used by pycortex and nbrsessionproxy.
 
[nbrsessionproxy](https://github.com/ryanlovett/nbrsessionproxy) - extension that launches RStudio's rsession via notebook menu item.

**Comment by tguillemot** [comment]
Thanks you for sharing your work @ryanlovett. I will have a look to your code tomorrow.

> It is a notebook extension rather than the server substitute that @tguillemot was inquiring about.

If I understand well the jupyterhub code, it seems that I need to define a new `SingleUserNotebookApp` which will inherit from `KernelGatewayApp` instead of `NotebookApp` but I have just begun the investigation so maybe I'm wrong.

**Comment by minrk** [comment]
@ryanlovett I think it's generally useful, and I'd like to make some demos out of it. I think we can make it work as a standalone layer in addition to the notebook extension

**Comment by ryanlovett** [comment]
Okay, sounds interesting. Just let me know if I can help with the demos or the standalone layer.

**Comment by willingc** [comment]
@ryanlovett :smile: @minrk Any thoughts on when we should move the repos under JupyterHub org? I think there are a number of folks that would make use of the RStudio goodness 👍

**Comment by cbienpourtoi** [comment]
That would be a great feature to add!

**Comment by minrk** [comment]
> Any thoughts on when we should move the repos under JupyterHub org?

I'm fine with doing this now, if @ryanlovett would like to

**Comment by ryanlovett** [comment]
Yes, that'd be great!

**Comment by tguillemot** [comment]
Just some news of what I've done. 
I have modified `single_user.py` to use the `KernelGatewayApp` instead of a `NotebookApp` (see [single-user.py](https://github.com/tguillemot/jupyterhub/blob/kernel-gateway/jupyterhub/singleuser.py#L575)) and even if the code needs to be clean it seems to work.

Not sure if it is the best way but it can be useful for #1052.

**Comment by willingc** [comment]
@minrk I'm not seeing a specific next action on this issue. Perhaps it would make sense to close it.
