### ISSUE TITLE
Raise 403 on authenticated user without access to single-user server

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#1049]
Right now, when a user is logged-in and visits another user's server, they start the login redirect process. This can result in a redirect loop if the user shouldn't have access to the server.

Instead, if a user is identified and doesn't have access, the user should get a 403 instead of redirecting back to login.

The tricky bit is that 'authenticated' is generally determined by `if get_current_user()` returns anything, and we should return None for not authenticated. Just raising 403 doesn't work because `get_current_user` may be called again when rendering the error page, for instance, preventing the page from rendering.

**Comment by willingc** [comment]
@minrk Does https://github.com/jupyterhub/jupyterhub/pull/1170 close this issue?

**Comment by minrk** [comment]
It does!
