### ISSUE TITLE
Problems with c.spawner.default_url and {username} when 'USER' <> PW_NAME

### ISSUE THREAD

**Issue by Paperone80** [jupyterhub/jupyterhub#1051]
Hi,

I am on a RHEL 7 server and the users are linked to a global active directory. I am using the Intel Python Distribution 3.5 with JupyterHub version 0.7.2.

It is setup in a way that any user can login with either "u+ID" or "U+ID" and PW, so the first letter can be lower or upper case. However, the $HOME is always /home/**U+ID**, ie upper case letter. 

On the system with via

```
$ su u+ID (even su with lower case)
$ printenv 
```

my environment variables are as follows and all start with upper case:

```
$USER=U+ID
$HOME=/home/U+ID
$LOGNAME=U+ID
```

Now I am login into JupyterHub via U+ID and PW.  And the following line shows up:

```
Spawning /.../jupyterhub-singleuser '--user="u+ID"' '--cookie-name="jupyter-hub-token-u+ID"' '--base-url="/user/u+ID"' '--hub-host=""' '--hub-prefix="/hub/"' '--hub-api-url="http://127.0.0.1:80/hub/api"' '--ip="127.0.0.1"' --port=48775 --debug
```

which works fine.

The URL shows up as http://server:port/user/u+ID. 

When I activate c.Spawner.notebook_dir = '/' I can navigate into my home folder which is the following URL http://server:port/user/u+ID/tree/home/U+ID. All fine.

Now, I wanted that every user can navigate the full directory but when I add
`c.Spawner.default_url = 'tree/home/{username}` the opening URL becomes
http://server:port/user/u+ID/tree/home/**u+ID**? which does not exist.  

I would have expected {username} returns in the U+ID format but it doesn't which causes the confusion. JupyterHub also seems to use the correct $HOME:

```
[Timestamp **u+ID** application:178] Searching ['/home/**U+ID**', '/home/**U+ID**/.jupyter', '/opt/intel/intelpython35/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
```

Is there any other variable than {username} which could be used? Or supporting {home} = $HOME?

Output in a JupyterHub Notebook looks like this:

```python
import pwd, os
print(pwd.getpwuid(os.getuid()).pw_name)
print(os.path.expanduser('~'))
    U+ID
    /home/U+ID

import os
print(os.environ.get('USER'))
    u+ID

import os
print(os.environ.get('HOME'))
    /home/U+ID
```

Thanks in advance for any help!

**Comment by minrk** [comment]
Perhaps the simplest solution would be to change the username normalization to ensure uppercase instead of the default lowercase:

```python
from jupyterhub.auth import PAMAuthenticator

class UpperCaseAuthenticator(PAMAuthenticator):
    def normalize_username(self, username):
        return username.upper()

c.JupyterHub.authenticator_class = UpperCaseAuthenticator
```

Does that work?

**Comment by Paperone80** [comment]
Thanks for the quick reply! Yes, it worked like a charm! 
Enabled in jupyterhub_config.py
```
c.Spawner.default_url = 'tree/home/{username}'
c.Spawner.notebook_dir = '/'
```
and copied your code at the end of the **PAMAuthenticator configuration** part.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!
