### ISSUE TITLE
JupyterHub as a backend only

### ISSUE THREAD

**Issue by tguillemot** [jupyterhub/jupyterhub#1052]
This issue is related to #1045 but I prefer open another issue to not pollute the previous one.

My plan is to use JupyterHub as a back-end to create / manage the `kernel_gateway` with a homemade notebooks front-end.

To do that, I want to :
1. modify JupyterHub to spawn `kernel_gateway` for each authenticated users
2. authenticate the users with foreign JWT tokens
3. define a REST API to launch and talk with the `kernel_gateway`s 

For 1) I have opened #1045. For now, I have modified `single_user.py` to use the `KernelGatewayApp` instead of a `NotebookApp` (see [single-user.py](https://github.com/tguillemot/jupyterhub/blob/kernel-gateway/jupyterhub/singleuser.py#L575)) and even if the code needs to be cleanned it seems to work.

For 2) I want to use JWT (with a `username` field) created outside. JupyterHub will decode / validate the token and create a specific kernel-gateway for the specific `username`. To solve that I have created my own Authenticator with specific handlers. It is not finish yet but the first tests seems to work too.

For 3) I want to define a REST API into a unique endpoint. Thus a user can launch / access / stop the kernel gateway from a unique route. Nevertheless, the actual code of JupyterHub launches a notebook to the url `user/[username]` only and I don't find a way to change that. 
Do you think it's possible to change the route `user/[username]/` into `user/` only ? Maybe by modifying, the proxy ???

Maybe this project can be interested by the JupyterHub community, if you want I can share it.

**Comment by minrk** [comment]
> Do you think it's possible to change the route user/[username]/ into user/ only ? Maybe by modifying, the proxy ???

They can only have the same URL if all users should be sharing the same kernel_gateway instance (one route can only have one destination). If that's true, then they should all really be the same user as far as JupyterHub is concerned, and use a different bit of metadata to differentiate them.

**Comment by willingc** [comment]
Closing this issue since it appears to be have no further development action. Please feel free to leave questions on the JupyterHub gitter channel. Thanks to all! :sunny:
