### ISSUE TITLE
Mayavi extension in Jupyterhub 

### ISSUE THREAD

**Issue by jan-janssen** [jupyterhub/jupyterhub#1053]
Hello, 

I run jupyter server 4.4.1  on Python 3.5 and I managed to setup mayavi in jupyter following their explanations: http://docs.enthought.com/mayavi/mayavi/tips.html 

Now I try to use the same extension inside Jupyterhub, but I get the following error messages: 
`[W 2017-04-04 14:08:44.347 JupyterHub log:100] 404 GET /hub/nbextensions/mayavi/x3d/x3dom.js?v=20170404140114 (username@127.0.0.1) 4.32ms`

Maybe you guys can help me, as I am not so familiar with extensions inside jupyterhub. 

best regards 

Jan

**Comment by minrk** [comment]
I've opened https://github.com/enthought/mayavi/pull/498 to fix this upstream. The short of it is that it should be `"nbextensions/...` not `"/nbextensions...`, which lets requirejs load the right prefix.

**Comment by kwotuveang3k4bk** [comment]
Unfortunately, that is not working for me, which version do you use? I get:
`/user/username/notebooks/path/to/my/notebook/and/notebook/name/nbextensions/mayavi/x3d/x3dom.js`
but it should be:
`/user/username/nbextensions/mayavi/x3d/x3dom.js`
and previously it was:
`/nbextensions/mayavi/x3d/x3dom.js `

**Comment by willingc** [comment]
This PR https://github.com/enthought/mayavi/pull/498 merged on May 6.

Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!
