### ISSUE TITLE
use environment variables to configure single-user server

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#1058]
Right now, we have a mixture of environment variables and command-line arguments to configure the single-user server.  After working with deployments based on docker and kubernetes, and considering alternate single-user implementations based on JupyterLab, KernelGateway, etc. I think moving most, if not all, single-user inputs to environment variables from CLI args would make things simpler.

There's no need to delete the CLI support from the singleuser entrypoint, just change how the spawner passes the args by default.

**Comment by manics** [comment]
This was done in 2.0.0!
