### ISSUE TITLE
Proxy failed to start with exit code 8

### ISSUE THREAD

**Issue by ramnavan** [jupyterhub/jupyterhub#1059]
Jupyterhub version 0.7.2
Configurable-Http-Proxy version 2.0.0

I've been getting the error failed to start proxy since this morning. The same scripts I have been using for deployment has been working till this morning.

Jupyterhub Log Info:

```
[[32m[I 2017-04-05 19:57:06.010 JupyterHub app:745]^[[0;10m Writing cookie_secret to /mnt/jupyterhub/jupyterhub_c$
^[[33m[W 2017-04-05 19:57:06.099 JupyterHub app:365]^[[0;10m
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

^[[32m[I 2017-04-05 19:57:06.111 JupyterHub app:892]^[[0;10m Not using whitelist. Any authenticated user will be a$
^[[32m[I 2017-04-05 19:57:06.133 JupyterHub app:1453]^[[0;10m Hub API listening on http://127.0.0.1:8081/hub/
^[[32m[I 2017-04-05 19:57:06.137 JupyterHub app:1176]^[[0;10m Starting proxy @ http://*:8001/
[C 2017-04-05 19:57:07.157 JupyterHub app:1459] Failed to start proxy
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/site-packages/jupyterhub/app.py", line 1457, in start
        yield self.start_proxy()
      File "/usr/local/lib/python3.4/site-packages/jupyterhub/app.py", line 1197, in start_proxy
        _check()
      File "/usr/local/lib/python3.4/site-packages/jupyterhub/app.py", line 1193, in _check
        raise e
    RuntimeError: Proxy failed to start with exit code 8
```

**Comment by willingc** [comment]
@minrk There's some additional detail on the gitter channel.

**Comment by willingc** [comment]
@ramnavan https://github.com/jupyterhub/jupyterhub/issues/237#issuecomment-95594644 is an older issue with a similar error that seems to resolve by uninstalling and reinstalling globally.

**Comment by willingc** [comment]
Looks like this is the case of an old version of node. What is odd is that the same works with CHP 1.3.1. 

From gitter: 

node is v0.10.46
Using Amazon Linux AMI. AWS EMR uses this as default when spinning up an EMR cluster
Jupyterhub was working till yesterday evening for me though. Same OS image and same scripts.

**Comment by minrk** [comment]
CHP 2.0 drops support for versions of node unsupported by node itself. The base version is the oldest currently-active LTS version (4.0).  https://github.com/jupyterhub/configurable-http-proxy/pull/98 should get a better error message on attempted installation with unsupported versions of node.

**Comment by willingc** [comment]
Closing this issue. Thanks for the quick addition @minrk.

@ramnavan Thanks for the report yesterday. If you with to use CHP 2.0.1, the Amazon Linux AMI will need to have a more recent version of node.
