### ISSUE TITLE
Deleting OS users causes Jupyterhub server to fail to start

### ISSUE THREAD

**Issue by jstaf** [jupyterhub/jupyterhub#1060]
Jupyterhub does not properly check if a user exists when it attempts to start. If an OS user is deleted, Jupyterhub will crash until those users have been removed from Jupyterhub's database. 

**How to reproduce the issue**

* Install Jupyterhub according to https://github.com/jupyterhub/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges. 
* Create a test user (`useradd test`). 
* Log in, make a notebook or three with said test user. 
* Delete test user (`userdel -r test`).
* Restart jupyterhub.

**What you expected to happen**

Jupyterhub should start successfully.

**What actually happens**

Jupyterhub will now crash on start.

**Share what version of JupyterHub you are using**

0.7.2

**HOW TO FIX**

Check for non-existent users on Jupyterhub initialization, delete them from Jupyterhub's `users` table.

```
sqlite3 jupyterhub.sqlite
DELETE FROM users WHERE name LIKE 'test%';
.quit
# jupyterhub now starts normally
```

**Logs (from a jupyterhub systemd service)**

Apr 06 14:00:07 some_host.ca sudo[8433]: jupyterhub : unknown user: testme
Apr 06 14:00:07 some_host.ca jupyterhub[8429]: sudo: unknown user: testme
Apr 06 14:00:07 some_host.ca jupyterhub[8429]: sudo: unable to initialize policy plugin
Apr 06 14:00:07 some_host.ca jupyterhub[8429]: [E 2017-04-06 14:00:07.756 JupyterHub app:1527]
Apr 06 14:00:07 some_host.ca jupyterhub[8429]: Traceback (most recent call last):
Apr 06 14:00:07 some_host.ca jupyterhub[8429]: File "/opt/python/anaconda3/lib/python3.6/site-packages/jupyterhub/app.py", line 1524, in launch_instance_async
Apr 06 14:00:07 some_host.ca jupyterhub[8429]: yield self.initialize(argv)
Apr 06 14:00:07 some_host.ca jupyterhub[8429]: File "/opt/python/anaconda3/lib/python3.6/types.py", line 184, in throw
Apr 06 14:00:07 some_host.ca jupyterhub[8429]: return self.__wrapped.throw(tp, *rest)
Apr 06 14:00:07 some_host.ca jupyterhub[8429]: File "/opt/python/anaconda3/lib/python3.6/site-packages/jupyterhub/app.py", line 1315, in initialize
Apr 06 14:00:07 some_host.ca jupyterhub[8429]: yield self.init_spawners()
Apr 06 14:00:07 some_host.ca jupyterhub[8429]: File "/opt/python/anaconda3/lib/python3.6/site-packages/jupyterhub/app.py", line 1087, in init_spawners
Apr 06 14:00:07 some_host.ca jupyterhub[8429]: status = yield spawner.poll()
Apr 06 14:00:07 some_host.ca jupyterhub[8429]: File "/opt/python/anaconda3/lib/python3.6/site-packages/jupyterhub/spawner.py", line 834, in poll
Apr 06 14:00:07 some_host.ca jupyterhub[8429]: alive = yield self._signal(0)
Apr 06 14:00:07 some_host.ca jupyterhub[8429]: File "/opt/python/anaconda3/lib/python3.6/site-packages/sudospawner/spawner.py", line 90, in _signal
Apr 06 14:00:07 some_host.ca jupyterhub[8429]: reply = yield self.do('kill', pid=self.pid, signal=sig)
Apr 06 14:00:07 some_host.ca jupyterhub[8429]: File "/opt/python/anaconda3/lib/python3.6/site-packages/sudospawner/spawner.py", line 69, in do
Apr 06 14:00:07 some_host.ca jupyterhub[8429]: data_str = data_str[data_str.index('{'):data_str.rindex('}')+1]
Apr 06 14:00:07 some_host.ca jupyterhub[8429]: ValueError: substring not found
Apr 06 14:00:07 some_host.ca systemd[1]: jupyterhub.service: main process exited, code=exited, status=1/FAILURE

**Comment by willingc** [comment]
Hi @jstaf,

Thanks for the well detailed issue report. Sorry you ran into this.

Currently, JupyterHub does not check for this use case which is described in the [documentation](https://jupyterhub.readthedocs.io/en/latest/g.tting-started.html#add-or-remove-users-from-the-hub) and summarized below:

> After starting the Hub once, it is not sufficient to remove a user from the whitelist in your config file. You must also remove the user from the Hub’s database, either by deleting the user from the admin page, or you can clear the jupyterhub.sqlite database and start fresh.

I'm going to go ahead and label this as an "enhancement" for better "user experience".

**Comment by minrk** [comment]
The severity of the failure is specific to sudospawner, which relies on becoming the user in order to check if the user is running. Other Spawners, such as the default one, ought to have no such problems.

If SudoSpawner checked for user existence before`.poll()`, it would also have no such issue.

During JupyterHub startup, the following happens:

- iterate through users in db, check their validity
  - LocalAuthenticators check if corresponding system users exist
  - if it doesn't:
    - if create_system_users: create system user
    - else: *warn* that system user doesn't exist ⬅️
  - instantiate a Spawner and call `.poll()` to check if each user's server is still running. ⬅️ this is where SudoSpawner fails

At the first arrow, users could be deleted if they don't exist, instead of a simple warning. I'm hesitant to do that by default, because a bug in user configuration could trigger deleting a bunch of users from the database. But there should be an easy way, perhaps opt-in like `create_system_users`, to cleanup the users that should no longer exist.

**Comment by jstaf** [comment]
Hmmmmm... although you do have documentation buried rather deeply saying what needs to happen (also, that's a broken link), Jupyterhub needs to be able to gracefully handle normal sysadmin activities like deleting users, regardless of which spawner gets used. 

I think opt-in user removal is a good suggestion (and the default behavior of sudospawner, where failure to delete users results in a crash).

**Comment by willingc** [comment]
@jstaf Sorry about the copy-pasta error in the link. I've fixed it above. 

>I think opt-in user removal is a good suggestion (and the default behavior of sudospawner, where failure to delete users results in a crash).

Yeah, I think this suggestion from @minrk makes good sense. Thanks for sharing your experience with us too.

**Comment by minrk** [comment]
#1069 adds the opt-in (`Authenticator.delete_invalid_users`) and fixes the bug where errors in Spawner.poll could prevent Hub startup.
