### ISSUE TITLE
Investigate Travis settings for passing test suite

### ISSUE THREAD

**Issue by willingc** [jupyterhub/jupyterhub#1070]
There are a number of times that Travis fails on only one Python version level (3.4, 3.5, 3.6). See if it is possible to configure Travis to pass if 2 of 3 versions pass and one fails due to spurious errors. @minrk Thoughts on this?

**Comment by minrk** [comment]
I don't think Travis has any way of knowing if an error is spurious or not. A failure on one version of Python could just as easily be an actual incompatibility (e.g. using something new in 3.5). These spurious failures are ~always bugs in the tests themselves, often relating somehow to threadsafety, so they should be able to be fixed.

**Comment by willingc** [comment]
> spurious failures are ~always bugs in the tests themselves, often relating somehow to threadsafety

Got it. I'll keep an eye out for any patterns in failures. Closing this. Thanks @mirnk.
