### ISSUE TITLE
Come up with a list of common packages used for different scientific fields

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/jupyterhub#1073]
Per conversations with @yuvipanda, we'd like to get a list of packages that are commonly used in particular subdomains. This could be used to build "base stacks" for each domain that users could specify, which would alleviate some of the headache of listing dependencies etc.

We should:

* Figure out if such lists already exist.
* If not, put together a survey to ask people about their most commonly-used packages as well as their domain

**Comment by willingc** [comment]
@choldgraf I would recommend checking out [jupyter/docker-stacks](https://github.com/jupyter/docker-stacks) as they provide a broad selection of commonly used package bundles.

**Comment by choldgraf** [comment]
Thanks for the suggestion! I think docker stacks is a great first start - I know Yuvi is trying to put together base images that are much more lightweight than this, and then have some dependency trees that are based on field. So a user could say "generate this jupyterhub and give me the python 3 stack + geosciences stack" or something like this.

**Comment by willingc** [comment]
@choldgraf Since we have this similar issue on the Binder repos, I'm going to close it here. :sunny:

**Comment by choldgraf** [comment]
+1
