### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS when authenticating an extension.

### ISSUE THREAD

**Issue by Bamieh** [jupyterhub/jupyterhub#1079]
hello,

I am trying to authenticate my own extension, i tried two main things, basically hitting the API, or using the authentication mixin, i would appreciate any help!

I registered an extension, and it works fine unauthenticated, but when i try to use the authentication mixin i get a 302 error on the routes with `ERR_TOO_MANY_REDIRECTS` in console. the authentication only works for services and not extensions??
also i try to use the cookie-name/cookie-value API, but it gives me 404 for some reason.

```
c.HubAuth.cookie_name = str('jupyterhub-services')
c.JupyterHub.cookie_secret = bytes.fromhex('096eee20d1b8a859e9d7460c8f92cff40b8510844f6c498b6d68071f6bf12624')

i try to hit the API with the `Authorization` header: 
`../hub/api/authorizations/cookie/jupyterhub-services/096eee20d1b8a859e9d7460c8f92cff40b8510844f6c498b6d68071f6bf12624`

i dont get a 403, i get a 404, means i get authorized based on token, but the api doesnt hit anything?

```
here is my extension code:

```py
from notebook.utils import url_path_join
from notebook.base.handlers import IPythonHandler

from getpass import getuser

import tornado.ioloop
from tornado.web import RequestHandler, Application, authenticated
from jupyterhub.services.auth import HubAuthenticated


class HelloWorldHandler(HubAuthenticated, RequestHandler):
    # if left undefined, it allows any authenticated user.
    # hub_users = {'bamieh'}
    # hub_users = {getuser()}

    @authenticated
    def get(self):
        self.write('hi mom!')

def load_jupyter_server_extension(nb_app):
    web_app = nb_app.web_app
    host_pattern = '.*$'
    route_pattern = url_path_join(web_app.settings['base_url'], '/hello')
    web_app.add_handlers(host_pattern, [(route_pattern, HelloWorldHandler)])
```

when i try to access the url it sends back to the login, i believe here is where the problem, it goes from login to next then back to login,, causing too many redirects, but im not sure why my user doesnt get authenticated?

**Comment by Bamieh** [comment]
What im trying to achieve from all of this is to  **add some pages** to the hub that uses the authentication of jupyterhub.

I have tried extensions and services:

1. **with services** i was able to easily authenticate the user but i was unable to achieve is creating multiple routes per service, i add as many routes as i want, with prefixes and all, but only the route with `/` is reachable.
```
@app.route(prefix + '/hi')
@authenticated
def hi_route(user):
    return render_template ...
# Cant reach this route. (services/serviceName/test/ gives 404)
@app.route(prefix + '/test/')
def hi_route(user):
    return render_template ...
```

2. **with extensions**  i was able to achieve multiple routes via tornado, but i was not able to get the cookie value as mentioned in the original post.

i hope this clarifies my intent. thanks alot for your time!

**Comment by minrk** [comment]
@Bamieh try inheriting from IPythonHandler directly. The JupyterHub single-user server wrapper should take care of authenticating with the Hub.

**Comment by Bamieh** [comment]
@minrk thanks, i got all 1 and 2 and 3 working now (3 with tokens instead of cookies)!

**Comment by Bamieh** [comment]
@minrk i can submit a pull request adding examples with authentication for the 3 cases, what do you think?

**Comment by minrk** [comment]
@Bamieh please do!
