### ISSUE TITLE
Spawner failed to start on PBS cluster

### ISSUE THREAD

**Issue by krak3nnn** [jupyterhub/jupyterhub#1081]
**How to reproduce the issue**
Install the batchspawner plug-in and specify the Torque class.

**What you expected to happen**
After authentication, submit a single user notebook to the cluster and relay back the hub.

**What actually happens**
Job gets submitted and job id is seen in qstat but Jupyterhub returns this error:
"JUPYTERHUB_API_TOKEN env is required to run jupyterhub-singleuser. Did you launch it manually?"

**Share what version of JupyterHub you are using**
Jupyterhub 0.7.2
batchspawner 0.0.1.dev0

**Comment by minrk** [comment]
cc @mbmilligan @zonca any idea for a cause for batchspawner to be failing to set env variables?

**Comment by mbmilligan** [comment]
It would be helpful if we could see the configuration file as well and let us know the Torque version being used. My guess is that either you customized the submit script (as most sites will) and omitted the keepvars line, or else your version of Torque uses a different option for passing environment variables into the job environment.

**Comment by zonca** [comment]
@minrk actually I have the same problem on Comet, I fixed it with this commit:

https://github.com/zonca/batchspawner/commit/a7449e388e06ae6c0b487d7fef29e53c0eefb305

I thought it was something wrong with my environment but it looks like it might be a larger issue.

**Comment by krak3nnn** [comment]
@mbmilligan You pointed me in the right direction. I was missing the PBS -V option.

@zonca I was going through your commits and did run into this. Fortunately, I cloned your git well after that commit date.

At this point in time, the issue as been resolved. Thank you everyone for your help!

**Comment by prateekpg2455** [comment]
@krak3nnn 
I am having the same issue. Can you tell me where did you use PBS -V option? 
This is what I have been using:

` /anaconda/envs/py35/bin/python /anaconda/envs/py35/bin/jupyterhub-singleuser --port=50387 --notebook-dir="~/notebooks" --config=/etc/jupyterhub/jupyter_config.py
`
