### ISSUE TITLE
DockerSpawner Spawner Failed to Start

### ISSUE THREAD

**Issue by tjcrone** [jupyterhub/jupyterhub#1083]
Hello I am having trouble starting a notebook using dockerspawner. I am getting a Spawner failed to start message. Here are the log messages and the docker logs output:

[I 2017-04-15 11:09:41.720 JupyterHub dockerspawner:449] Starting container 'jupyter-tjc' (id: ba60216)
[W 2017-04-15 11:09:51.721 JupyterHub web:1545] 500 GET /hub/user/tjc (::ffff:64.145.79.220): Spawner failed to start [status=ExitCode=127, Error='', FinishedAt=2017-04-15T15:09:42.017134584Z]

```
root@berna:/etc/jupyterhub# docker logs jupyter-tjc
/usr/local/bin/start-singleuser.sh: 13: exec: jupyterhub-singleuser: not found
/usr/local/bin/start-singleuser.sh: 13: exec: jupyterhub-singleuser: not found
/usr/local/bin/start-singleuser.sh: 13: exec: jupyterhub-singleuser: not found
```

Any idea what is going on? Thanks!

```

$PATH:
        /usr/local/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin

sys.path:
        /usr/local/bin
        /usr/lib/python2.7
        /usr/lib/python2.7/plat-x86_64-linux-gnu
        /usr/lib/python2.7/lib-tk
        /usr/lib/python2.7/lib-old
        /usr/lib/python2.7/lib-dynload
        /usr/local/lib/python2.7/dist-packages
        /usr/lib/python2.7/dist-packages

sys.executable:
        /usr/bin/python2

sys.version:
        2.7.13 (default, Jan 19 2017, 14:48:08) 
        [GCC 6.3.0 20170118]

platform.platform():
        Linux-4.9.0-2-amd64-x86_64-with-debian-9.0

which -a jupyter:
        /usr/local/bin/jupyter
        /usr/local/bin/jupyter

pip list:
        acme (0.10.2)
        backports-abc (0.5)
        backports.shutil-get-terminal-size (1.0.0)
        certbot (0.10.2)
        certbot-apache (0.10.2)
        certifi (2017.1.23)
        chardet (2.3.0)
        ConfigArgParse (0.11.0)
        configobj (5.0.6)
        cryptography (1.7.1)
        decorator (4.0.11)
        dnspython (1.15.0)
        enum34 (1.1.6)
        funcsigs (1.0.2)
        gpg (1.8.0)
        gyp (0.1)
        httplib2 (0.9.2)
        idna (2.2)
        ipaddress (1.0.17)
        ipykernel (4.6.1)
        ipython (5.3.0)
        ipython-genutils (0.2.0)
        jupyter-client (5.0.1)
        jupyter-core (4.3.0)
        keyring (10.1)
        keyrings.alt (1.3)
        mercurial (4.0)
        mock (2.0.0)
        parsedatetime (2.1)
        pathlib2 (2.2.1)
        pbr (1.10.0)
        pexpect (4.2.1)
        pickleshare (0.7.4)
        pip (9.0.1)
        prompt-toolkit (1.0.14)
        psutil (5.0.1)
        ptyprocess (0.5.1)
        pyasn1 (0.1.9)
        pycrypto (2.6.1)
        pycurl (7.43.0)
        Pygments (2.2.0)
        pygobject (3.22.0)
        PyICU (1.9.5)
        pyOpenSSL (16.2.0)
        pyRFC3339 (1.0)
        python-apt (1.4.0b2)
        python-augeas (0.5.0)
        python-dateutil (2.6.0)
        python-debian (0.1.30)
        python-debianbts (2.6.1)
        pytz (2016.7)
        pyxdg (0.25)
        pyzmq (16.0.2)
        reportbug (6.6.6)
        requests (2.12.4)
        scandir (1.5)
        SecretStorage (2.3.1)
        setuptools (33.1.1)
        simplegeneric (0.8.1)
        singledispatch (3.4.0.3)
        six (1.10.0)
        tornado (4.4.3)
        traitlets (4.3.2)
        urllib3 (1.19.1)
        wcwidth (0.1.7)
        wheel (0.29.0)
        zope.component (4.3.0)
        zope.event (4.2.0)
        zope.hookable (4.0.4)
        zope.interface (4.3.2)

```

**Comment by tjcrone** [comment]
Logging in to the jupyterhub/singleuser image, it looks like jupyterhub is not installed. Is this possible?

root@berna:/etc/jupyterhub# docker run -i -t -u 0 jupyterhub/singleuser /bin/bash
root@ca18f43f8648:~/work# find / -name "*jupyter*"
/home/jovyan/.jupyter
/home/jovyan/.jupyter/jupyter_notebook_config.py
/usr/local/share/jupyter
root@ca18f43f8648:~/work# 

root@berna:/etc/jupyterhub# docker pull jupyterhub/singleuser
Using default tag: latest
latest: Pulling from jupyterhub/singleuser
Digest: sha256:542a61e9a35cfb63c8fed940c91585b0238a237bc9bf88a3e534fd9d5cb672b1
Status: Image is up to date for jupyterhub/singleuser:latest

**Comment by minrk** [comment]
@tjcrone that's very odd. When I run those commands I get *loads* of results for `find`. What do you see in `/opt/conda` in the container? Or from `conda list`?

**Comment by tjcrone** [comment]
@minrk, well, what is more odd is that after removing the image and repulling it, everything seems to be where I expect it! Maybe there was something wrong with my image? Strange. Anyway, now it appears that a container is created and the server starts but there is some sort of redirect loop:

[I 2017-04-18 07:19:01.545 JupyterHub log:100] 302 GET /user/tjcrone (@216.151.180.169) 0.52ms
[I 2017-04-18 07:19:01.581 JupyterHub dockerspawner:363] Container 'jupyter-tjcrone' is gone
[W 2017-04-18 07:19:01.582 JupyterHub dockerspawner:334] container not found
[I 2017-04-18 07:19:01.641 JupyterHub dockerspawner:363] Container 'jupyter-tjcrone' is gone
[I 2017-04-18 07:19:01.723 JupyterHub dockerspawner:432] Created container 'jupyter-tjcrone' (id: 95126fa) from image jupyterhub/singleuser
[I 2017-04-18 07:19:01.723 JupyterHub dockerspawner:449] Starting container 'jupyter-tjcrone' (id: 95126fa)
[I 2017-04-18 07:19:03.363 JupyterHub base:319] User tjcrone server took 1.781 seconds to start
[I 2017-04-18 07:19:03.363 JupyterHub orm:198] Adding user tjcrone to proxy /user/tjcrone => http://127.0.0.1:32768
[I 2017-04-18 07:19:03.373 JupyterHub log:100] 302 GET /hub/user/tjcrone (tjcrone@216.151.180.169) 1793.21ms
[W 2017-04-18 07:19:03.589 JupyterHub pages:42] Redirecting /hub/?next=%2Fuser%2Ftjcrone%2Ftree%3F to /hub/user/tjcrone/tree?. For sharing public links, use /user-redirect/
[I 2017-04-18 07:19:03.593 JupyterHub log:100] 302 GET /hub/?next=%2Fuser%2Ftjcrone%2Ftree%3F (tjcrone@216.151.180.169) 0.80ms
[I 2017-04-18 07:19:03.637 JupyterHub log:100] 302 GET /hub/user/tjcrone/tree? (tjcrone@216.151.180.169) 6.56ms
[W 2017-04-18 07:19:03.725 JupyterHub pages:42] Redirecting /hub/?next=%2Fuser%2Ftjcrone%2Ftree%3F to /hub/user/tjcrone/tree?. For sharing public links, use /user-redirect/
[I 2017-04-18 07:19:03.728 JupyterHub log:100] 302 GET /hub/?next=%2Fuser%2Ftjcrone%2Ftree%3F (tjcrone@216.151.180.169) 0.74ms
[I 2017-04-18 07:19:03.787 JupyterHub log:100] 302 GET /hub/user/tjcrone/tree? (tjcrone@216.151.180.169) 6.59ms

**Comment by minrk** [comment]
Can you restart the Hub and the proxy? Something's not right if the Hub is receiving requests at `/hub/user/tjcrone` after `Adding user tjcrone to proxy ...`

**Comment by tjcrone** [comment]
I stopped the server, removed the database file, cleared my cookies, and I am still getting this error. Any other information I can provide to help fix this? Thank you!

**Comment by tjcrone** [comment]
@minrk I would be quite happy to try and fix this in my own fork if you think it is a bug. Can you suggest  the package/file that is likely to be the issue? I am new to jupyterhub development so I'm still learning where everything is. Thanks!

**Comment by minrk** [comment]
Let's get some details for debugging Can you show the whole log of JupyterHub and the proxy, ideally after staring with `--debug` and `c.JupyterHub.debug_proxy = True`? What version of JupyterHub?

What URL are you visiting to connect to the Hub? Is it perhaps `localhost:8080` instead of `localhost:8000`? If so, make sure to use the *public* URL and not the Hub's internal URL.

**Comment by tjcrone** [comment]
```
root@berna:/etc/jupyterhub# jupyterhub --version
0.8.0.dev
```
I am connecting on port 443, but I have JupyterHub behind nginx, listening on 127.0.0.1:8000. I have the same issues when I take JupyterHub out from behind nginx, so I don't think this has anything to do with it. Here is my nginx config:


```
# HTTPS server to handle JupyterHub
server {
    listen 443;
    ssl on;

    server_name ---;

    ssl_certificate /etc/letsencrypt/live/---/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/---/privkey.pem;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_dhparam /etc/ssl/certs/dhparam.pem;
    ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_stapling on;
    ssl_stapling_verify on;
    add_header Strict-Transport-Security max-age=15768000;

    # Managing literal requests to the JupyterHub front end
    location / {
        proxy_pass https://127.0.0.1:8000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Managing WebHook/Socket requests between hub user servers and external proxy
    location ~* /(api/kernels/[^/]+/(channels|iopub|shell|stdin)|terminals/websocket)/? {
        proxy_pass https://127.0.0.1:8000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        #proxy_set_header Connection $connection_upgrade;
        proxy_set_header Connection "upgrade";

    }
    # Managing requests to verify letsencrypt host
    location ~ /.well-known {
        allow all;
    }
}
```
I will send the log file in a separate message if that's okay. Thank you!

**Comment by minrk** [comment]
> root@berna:/etc/jupyterhub# jupyterhub --version
0.8.0.dev

I think this is it. The recent OAuth changes in master mean that JupyterHub 0.8 is going to need JupyterHub 0.8 *inside the container* for the single-user entrypoint. I would recommend running with the current stable version (0.7.x), but if you want to stick with master, you are going to need to install jupyterhub master inside your image, as well, to get the latest version of jupyterhub-singleuser.

**Comment by tjcrone** [comment]
Okay I think I will try the latter. I upgraded to master primarily because the last stable release would not properly log users out when they requested it. I'll let you know if I am able to fix this by installing master in the image. Thanks!

**Comment by dmvieira** [comment]
Hey guys! It's just conda path that's not in path. Add it at jupyterhub_config.py:

`c.DockerSpawner.extra_create_kwargs = {"command": 'env PATH="/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" /usr/local/bin/start-singleuser.sh'}
`
Solved for me

**Comment by willingc** [comment]
Thanks @dmvieira for passing along your tip.

In `jupyterhub_config.py`, add:

```
c.DockerSpawner.extra_create_kwargs = {
    "command": 'env PATH="/opt/conda/bin:$PATH" /usr/local/bin/start-singleuser.sh',
}
```

I'm going to close this issue. @tjcrone, please let me know if you would like us to reopen.

**Comment by NicWayand** [comment]
@willingc and @dmvieira, where in the `jupyterhub_config.py` should that line be added? (New to `jupyterhub_config.py` syntax). Do you have an example config file you could share? Thanks!

**Comment by dmvieira** [comment]
jupyterhub_config.py is a python file and these lines can be included everywhere

**Comment by NicWayand** [comment]
Thanks @dmvieira, I understand now it can also be set in a .yaml file as well, which is why I was asking about placement. Here is [my yaml config file](https://github.com/NicWayand/example.pangeo.io-deploy/blob/26601742938ae486bf5ea0fb84086f492a610461/deployments/polar.pangeo.io/config/staging.yaml#L42) where I think it is in the correct place?
