### ISSUE TITLE
notebook 5.0 favicon / favicon-busy fail to load

### ISSUE THREAD

**Issue by parente** [jupyterhub/jupyterhub#1086]
**How to reproduce the issue**

Use notebook 5.0 with jupyterhub 0.7.2.

**What you expected to happen**

favicon.ico and favicon-busy.ico load properly and tab icon changes like when notebook 5.0 runs standalone.

**What actually happens**

404 Not Found hub/static/base/images/favicon.ico and hub/static/base/images/favicon-busy.ico

**Share what version of JupyterHub you are using**

0.7.2

**Comment by minrk** [comment]
Fixed by https://github.com/jupyter/notebook/issues/2430
