### ISSUE TITLE
Jupyterhub 0.7.2 does not work with a MySQL backend

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#1088]
**How to reproduce the issue**

1. Setup a JupyterHub with mysql database backend, pointing to an empty database

**What you expected to happen**

2. JupyterHub creates the required tables in the database on start

**What actually happens**

It fails to start, with:

```
    sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1071, 'Specified key was too long; max key length is 767 bytes') [SQL: '\nCREATE TABLE groups (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tname VARCHAR(1023), \n\tPRIMARY KEY (id), \n\tUNIQUE (name)\n)\n\n']
```

I think the group name needs to be smaller.

**Comment by ckbhatt** [comment]
Adding following to my.cnf
innodb_file_format = Barracuda
innodb_file_per_table = 1
innodb_large_prefix
and restarting MySQL changes allowed length and works as a workaround for now
