### ISSUE TITLE
Can jupyterhub installed under the normal user?

### ISSUE THREAD

**Issue by qingzhouzhen** [jupyterhub/jupyterhub#1091]
Can jupyterhub installed under the normal user? How can I do it? custom the Authenticator?

**Comment by willingc** [comment]
Hi @qingzhouzhen,

I don't fully understand your question. Are you asking if you can run jupyterhub without being a privileged user (i.e. root)? If so, this [section of the documentation](https://jupyterhub.readthedocs.io/en/latest/quickstart.html#start-the-hub-server) and the following [wiki page on running JupyterHub without root privileges](https://github.com/jupyterhub/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges) should help.

Please let me know if you have additional questions.

**Comment by qingzhouzhen** [comment]
No. I mean can I install jupyterhub when I login my PC as a normal user? not root user, i mean install , not run it. The document tells me to install jupyterhub with root user, but I want use normal user

**Comment by willingc** [comment]
You can install as a user; however, you will need the SudoSpawner described in the above wiki page.

**Comment by qingzhouzhen** [comment]
Do you mean I need to custom the spawnner?

**Comment by willingc** [comment]
You would use SudoSpawner https://github.com/jupyterhub/sudospawner which is one of several spawners that are available for JupyterHub. As an FYI, there will be a new release of sudospawner in the next day or two. Feel free to ask questions on the gitter channel for JupyterHub too.

**Comment by qingzhouzhen** [comment]
Thanks a lot, my aim is to install jupyterhub under normal user and run it under normal user. I can install jupyterhub under normal user with SudoSpawner and run it under the same user, is that right?

**Comment by minrk** [comment]
>  I can install jupyterhub under normal user with SudoSpawner and run it under the same user, is that right?

Yes, you can install jupyterhub and sudospawner as a normal user. To use SudoSpawner, though, you need root permissions to configure sudo to grant jupyterhub specific permission to become other users, as described in the doc @willingc linked.

If you want to install and run *entirely without elevated permissions*, you need to select an Authenticator and Spawner that do not need elevated permissions. Using OAuth, for instance, requires no extra permissions. Similarly, the Docker or Kubernetes Spawners need only permission to talk to those services (which may vary, depending on the system).

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave questions on the JupyterHub gitter channel or leave a comment requesting this issue be reopened. Thanks to all! :sunny:
