### ISSUE TITLE
allow Authenticators to invalidate cookies

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#1099]
Some Authenticators need to **temporarily** store information such as credentials that should be passed to the Spawner environment. This is complicated by the fact that login, when the Authenticator may retrieve this info, and spawn, when the Spawner needs it, happen at different times and with different frequencies. For instance, there is not one login event per spawn, so the Authenticator cannot retrieve a new token for the Spawner because the JupyterHub cookie may still be around from a previous session.

This appears to drive much of the requests for `auth_state`, but `auth_state` **must never be used to store credentials**, because that would put credential information in a long-lived cleartext at-rest location, which is a big no-no. So auth_state doesn't actually help solve this problem in an acceptable way. Because of this confusion, I'm tempted to *remove* `auth_state`, because it seems to be encouraging an insecure antipattern in authenticators (https://github.com/jupyterhub/oauthenticator/pull/75). Storing the credentials only in memory is a better pattern, but suffers from one failing: restarting the Hub loses the in-memory state, but the cookies remain valid. In both cases, token storage has the wrong lifetime.

## Proposal

If Authenticators were given the chance to check if they still have whatever it is they need and force re-login if not, it seems the problem would be solved in a more secure *and* more reliable way.

If this works, in combination with the fact that `auth_state` seems to have been effectively inaccessible thus far (#1063), I may go with *removing* auth_state from the database instead of implementing #1063 for 0.8, to avoid giving the false impression that auth_state is there to store credentials.

cc @yuvipanda

**Comment by yuvipanda** [comment]
(lots of thoughts! Will respond in detail on Monday)

What do you think of just encrypting auth_state instead? We should attempt
to do a more detailed security analysis of when that will be a problem, and
I think with encryption it will be significantly better than without. I am
willing to write the code for this too.

We restart our hub a few times a day almost these days, and want to move
towards a continuous deployment model that will cause more frequent
restarts. Right now there is nothing in memory that will cause lots of
problems when we restart and I would really really like to keep it that way.

So the problem you are trying to protect against is when an attacker has
arbitrary access to the database but not arbitrary code execution in the
compromised machine, right? Or if the DB is at rest and 'found' much later?

**Comment by yuvipanda** [comment]
Securing data at rest is also a fairly common problem with fairly common
solutions (https://www.owasp.org/index.php/Cryptographic_Storage_Cheat_Sheet
lists some guidelines and there are others around). I would definitely like
to take this on and do it the right way rather than throw the whole thing
out.

**Comment by minrk** [comment]
> What do you think of just encrypting auth_state instead?

I'd rather avoid being responsible for doing this robustly. Right now, we store zero retrievable sensitive data in JupyterHub, and I have been hoping to keep it that way. Making the leap from zero to any is a big deal, and I'd rather not make it when we don't have to. The biggest thing for me from what you linked is "Only store sensitive data that you need". We simply don't need to persist that data, because it can be retrieved from the provider on spawn. The problem I see is that we don't expose the right hooks to retrieve it at the right time, so that's the problem I would rather solve.

With GitHub OAuth, at least, this should be transparent to the user - they may go through an extra redirect or two on launch when the Hub has been reset, but be faced with no actual pages, because the JupyterHub application has already been authorized.

**Comment by minrk** [comment]
Invalidating auth state is still a problem we need to solve if a token is in the database or in memory, because you can't know that it's still a valid token without checking upstream. So the same problem needs to be solved whether auth state is persisted for a short or long time: it needs to be checked and re-fetched on spawn. Since that needs to happen anyway, I'd like to start by addressing that and seeing if it helps address the use cases without introducing new security features.

If auth state does really need to be persisted, encrypting it is definitely the right call and I'd love your help with that. I'd just like to be sure it is needed before taking that step.

**Comment by yuvipanda** [comment]
I agree we need to do both - and we shouldn't store it at rest if we can't guarantee we've used the absolute best practices for protecting it (including not storing when not required). I'll start doing a threat model + propose solutions in an issue next week for it. I think it might not be needed for GitHub, but it is for the MediaWiki one afaict (and probably for other ones too) - there's always an interstitial asking for manual approval, and you then end up with a flow where you are doing this approval *twice*. 

Can you do a test implementation of how this would work with the GitHub Authenticator so I can get a better sense of how this would work? I too would love it if we don't have to store the creds, just want to make sure if we have to we can.

**Comment by minrk** [comment]
I will do a test implementation with GitHub, but I'm pretty consumed by OpenDreamKit grant review this week, so probably won't do too much before next week (possibly this Friday). It sounds like encrypting auth_state is the right thing to do (and dropping auth_state is out).

It's quite reasonable if other OAuth providers don't do the same thing as GitHub, which remembers that users have authorized a given application, so don't need to interrupt the user for subsequent already-authorized requests.

**Comment by minrk** [comment]
This is implemented in #2142
