### ISSUE TITLE
How to disable all authentication?

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [jupyterhub/jupyterhub#1102]
This is more a question than an issue, although an entry in the docs would be great.

I'd like to disable the login of JupyterHub, in order to use its facilities without the need to login. For example visitors could spawn docker containers with notebooks running in them and I don't care, what their user name is, since they are anonymous test users. However, they should still have their separate environments (containers). I'd probably want to map an IP address to a container name or something similar.

**Comment by betatim** [comment]
Have a look at #1065 and pointers in it. The issues is about automatically logging people in without password etc.

**Comment by ZelphirKaltstahl** [comment]
@betatim Looks exactly like what I am looking for. I'll investigate that, thank you.

**Comment by willingc** [comment]
Hi @ZelphirKaltstahl, 

This may be helpful as well: https://github.com/yuvipanda/jupyterhub-dummy-authenticator I would not use it for anything serious though.

Thanks @betatim.

**Comment by mxjeff** [comment]
Hi @ZelphirKaltstahl,

Not tested yet but [tmpauthenticator](https://github.com/jupyterhub/tmpauthenticator) might be useful in that case.

Cheers

**Comment by ZelphirKaltstahl** [comment]
@mxjeff Thanks for the response. Indeed I did use tmpauthenticator in the end : )

**Comment by KamalPatel365** [comment]
> @mxjeff Thanks for the response. Indeed I did use tmpauthenticator in the end : )

Did it worked ???
