### ISSUE TITLE
/etc/shadow - proper permissions 0440 ?

### ISSUE THREAD

**Issue by xhudik** [jupyterhub/jupyterhub#1103]
https://github.com/jupyterhub/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges#linux - is written that:
```
 sudo chmod g+r /etc/shadow
```
which will make
```
$ ls -l /etc/shadow
-rw-r-----  1 root shadow   2197 Jul 21 13:41 shadow
```

However, https://linux-audit.com/file-permissions-of-the-etc-shadow-password-file/ says /etc/shadow can be read only by root (600) only 

Isn't your implementation dangerous?

**Comment by minrk** [comment]
> Isn't your implementation dangerous?

It is not. Giving a very specific group (the `shadow` group) access to the password database is common, as described in the doc you linked:

> The group is often set to an administrative group, like shadow

The default permissions on `/etc/shadow` on Ubuntu are `640`:

```
$ docker run -it --rm ubuntu:17.04 ls -l /etc/shadow
-rw-r----- 1 root shadow 501 Apr 21 00:57 /etc/shadow
```

Our docs only cover how to get other distros into Ubuntu's default state.
