### ISSUE TITLE
Passwords beginning or ending with a whitespace are not supported

### ISSUE THREAD

**Issue by bneijt** [jupyterhub/jupyterhub#1105]
Due to POST argument stripping, passwords with a beginning or ending whitespace are not allowed.

**How to reproduce the issue**
Set up a user password with an ending or beginning whitespace.

**What you expected to happen**
The user should be allowed to login with the password, given that the password should be any complicated sequence of characters the user can reproduce.

**What actually happens**
The user is denied access, because the LoginHandler will strip all posted values before considering the password for authentication (line 81, get_argument has a default "strip=True")

**Share what version of JupyterHub you are using**
HEAD (006488fc749923851df97d47d8850bdf5fd157cf)

**Comment by minrk** [comment]
Good catch. Fixed by #1111
