### ISSUE TITLE
User cookie not being created?

### ISSUE THREAD

**Issue by Spritekin** [jupyterhub/jupyterhub#1106]
Hi,
First, I apologize because I'm jumping from repo to repo. Its just because I'm new to this and I'm not sure about the code. I posted the base of my issue in the dockerspawner repo (https://github.com/jupyterhub/dockerspawner/issues/155) but now I think the problem might not be there. 

Please bear with me as I try to analyse code that I don't fully understand. Correct me as much as you like.

In a nutshell. My problem is that I login to jupyterhub using the ldapauthenticator. All goes ok and jupyterhub spawns a notebook in swarm. The notebook is created but it reports it can't find a cookie so it enters an eternal redirection. When jupyterhub creates the notebook, it passes the cookie name as jupyter-hub-token-grodriguez (with the username)

I don't have logs to compare so I went through some other issues in the repo to find similar cases and I noticed this on issue 1026 (https://github.com/jupyterhub/jupyterhub/issues/1026)

```
[D 2017-03-17 14:43:11.142 JupyterHub orm:146] Fetching POST http://127.0.0.1:8001/api/routes/jupyter/user/jupyterhub
[D 2017-03-17 14:43:11.145 JupyterHub base:236] Setting cookie for jupyterhub: jupyter-hub-token-jupyterhub, {}
[D 2017-03-17 14:43:11.148 JupyterHub base:236] Setting cookie for jupyterhub: jupyter-hub-token, {}
[I 2017-03-17 14:43:11.151 JupyterHub log:100] 302 POST /jupyter/hub/login?next= (@127.0.0.1) 1221.47ms
```

Notice in this log, jupyterhub sets two cookies, one for jupyter-hub-token and other for jupyter-hub-token-username. 

And the following issue 742 (https://github.com/jupyterhub/jupyterhub/issues/742) also sets the username cookie:
```
[D 2016-09-12 14:22:44.054 JupyterHub base:231] Setting cookie for username1: jupyter-hub-token-username1, {}
```

But for me it looks like:
```
[D 2017-04-26 10:29:09.687 JupyterHub orm:154] Fetching POST http://172.31.45.116:8001/api/routes/user/grodriguez
[D 2017-04-26 10:29:09.705 JupyterHub base:240] Setting cookie for grodriguez: jupyter-hub-token, {}
```

So my hub is not setting the username cookie, only the server cookie.

So I went into the code to locate where the cookie is set. I found it it set in this function:

https://github.com/jupyterhub/jupyterhub/blob/703ed7d21ef822d0dbde4b91c1dd7b2ccabee188/jupyterhub/handlers/base.py
In function set_login_cookie (Line 259)
...
L271: # create and set a new cookie token for the hub
        if not self.get_current_user_cookie():
            self.set_hub_cookie(user)

So it checks if there is a cookie and is not it calls set_hub_cookie function which allegedly sets the cookies. However this function only calls:
```
        self._set_user_cookie(user, self.hub.server)
```

Which is defined as:
```
def _set_user_cookie(self, user, server):
        # tornado <4.2 have a bug that consider secure==True as soon as
        # 'secure' kwarg is passed to set_secure_cookie
        if  self.request.protocol == 'https':
            kwargs = {'secure': True}
        else:
            kwargs = {}
        if self.subdomain_host:
            kwargs['domain'] = self.domain
        self.log.debug("Setting cookie for %s: %s, %s", user.name, server.cookie_name, kwargs)
        self.set_secure_cookie(
            server.cookie_name,
            user.cookie_id,
            path=server.base_url,
            **kwargs
        )
```

Which always sets the server.cookie_name, but it doesn't set the username cookie. This means the Dockerspawner will never find the username cookie because it doesn't exist.

So after doing a search, I found the _set_user_cookie function is being called only from this base.py file and it is always setting only one cookie for the server. It never sets the cookie for the user.

This is paradoxical because the clear_login_cookie function is still trying to delete two cookies, one for the user and one for the server:
```
       if user and user.server:
            self.clear_cookie(user.server.cookie_name, path=user.server.base_url, **kwargs)
        self.clear_cookie(self.hub.server.cookie_name, path=self.hub.server.base_url, **kwargs)
```

So I think the _set_user_cookie should also be initializing the user cookie, not just the hub cookie.

Not sure if I'm wrong in this analysis. As I said this is the first time I see this code.

Luck!
Guimo

**Comment by Spritekin** [comment]
I'm reading the dockerspawner code and found that it uses the self.user.server.cookie_name which is the same cookie used here. So it should be the same name and it should work.
```
env.update(dict(
            JPY_USER=self.user.name,
            JPY_COOKIE_NAME=self.user.server.cookie_name,
            JPY_BASE_URL=self.user.server.base_url,
            JPY_HUB_PREFIX=self.hub.server.base_url
        ))
```

 Now I really don't understand anything... sorry...

**Comment by Spritekin** [comment]
Maybe its a problem with my versions?
```
FROM jupyterhub/jupyterhub-onbuild:latest

# Install dockerspawner and oauthenticator
RUN pip install git+git://github.com/jupyterhub/dockerspawner.git@0.7.0
RUN pip install jupyterhub-ldapauthenticator

# Add variable to allow connecting to the docker swarm
ENV DOCKER_HOST https://swarm.marathon.mesos:2376
```

Is that correct? Maybe I should use the onbuild 7.2?

**Comment by Spritekin** [comment]
Yes it was indeed... sorry for all the trouble.

**Comment by willingc** [comment]
Hi @Spritekin,

I'm glad that you resolved the issue. No trouble at all. We hope you enjoy using JupyterHub too.
