### ISSUE TITLE
Jupyterhub Not Recognizing Users' Groups

### ISSUE THREAD

**Issue by evandam** [jupyterhub/jupyterhub#1107]
I'm running Jupyterhub on RHEL 6.8, and facing permission issues when trying to read files from outside of a user's home directory.

The directory I'm trying to reach is `/data/lake/plds`, and it's permissions are `d---rwx---`. All users in the group that owns it should have full access, and no one else, but trying to read a file or even run `os.chdir(/data/lake/plds`)` results in a permission denied error.

I noticed a few things that might be contributing to the issue:
* Running `getpass.getuser()` returns `root`. My Jupyterhub is launched as root, but individual notebook servers should be running as individual users.
* Running `os.getlogin()` does return the correct user ID. I'm assuming this uses the effective user id instead.
* `os.getgroups()` only returns a single group ID, which I'm guessing is one that root belongs to. 

I only have issues accessing the directory through Jupyterhub. I can navigate to it through SSH or even a regular Jupyter Notebook not managed through the Hub.

Please let me know if I can do anything to help out on this issue.

Thanks in advance!

**Comment by willingc** [comment]
Hi @evandam,

Thanks for the detailed report. In your `jupyterhub_config.py` file, what are your settings for `notebook_dir` and `default_url`? The example below gives users access to the full tree:

```
c.Spawner.notebook_dir = '/'
c.Spawner.default_url = '/home/%U' # %U will be replaced with the username
```

Thanks!

**Comment by evandam** [comment]
Hi @willingc,

I just made the changes and restarted the hub, but still no luck. I'm able to navigate to `/data/lake` in JupyterHub, but the `plds` directory I'm trying to view is hidden.

I am able to see another directory in `/data/lake`, though. The only difference I can see is that it's permissions are 755 compared to 070. Could it be that it's using permissions of the root user instead of the user logged in?

Thanks!
Evan

**Comment by minrk** [comment]
@evandam are you using the default Spawner or another one? What version of JupyterHub?

**Comment by evandam** [comment]
Hi @minrk 

I'm using a custom spawner that sources a shell script for environment variables, and then calls jupyterhub's:

```
source /usr/app/profiles/myprofile
exec /usr/app/anaconda_3/bin/jupyterhub-singleuser $@
```
I'm on JupyterHub version 0.7.1

Thanks!

**Comment by minrk** [comment]
@evandam The group ids are assigned [here](https://github.com/jupyterhub/jupyterhub/blob/0.7.1/jupyterhub/spawner.py#L650-L661). If you've chosen a different Spawner, this step may be skipped. It's also possible it's failing for some reason, in which case you should see a "Failed to set groups" message on stderr of the affected single-user server.

You might also do some checking to verify that we're getting the right info by running this block:

```python
import grp, pwd
username = 'evandam'

user = pwd.getpwnam(username)
uid = user.pw_uid
gid = user.pw_gid
home = user.pw_dir
gids = [ g.gr_gid for g in grp.getgrall() if username in g.gr_mem ]
```

And verify that you get all of the correct group IDs.

**Comment by evandam** [comment]
Thanks @minrk. I ran the code block you sent in both a notebook through JupyterHub and a Python shell from the command line and noticed the same thing: Only one group is listed. However, I should have many more groups (seen through `os.getgroups()`)

I'm hoping to avoid a totally custom spawner, which is why my "custom" spawner just sources a script and then calls `jupyterhub-singleuser`. However, it seems like a different function needs to be used to get my groups for some reason. Any thoughts?

Thanks!
Evan

**Comment by evandam** [comment]
Hi @minrk, just wondering if you had any updates or ideas on how to proceed on this one. As far as I can tell, my custom spawner is really just a small wrapper around `jupyterhub-singleuser`, but if there's another way I should be doing things like sourcing a shell script, I'm happy to try it out.

Thanks again!

**Comment by minrk** [comment]
I'm not sure. If you can poke around and find a call that gives you all of the desired gids for a given user when run as root, we can see if something needs to be updated. I'm not sure why/how you aren't getting the right group listing through the calls we currently use, but there may be something more robust we can try.

The short-term workaround, especially if you happen to know *a priori* what groups you should be in, is to subclass `LocalProcessSpawner` and override the [`make_preexec_fn` method](https://github.com/jupyterhub/jupyterhub/blob/0.7.2/jupyterhub/spawner.py#L722) to return an alternate implementation of [`set_user_setuid`](https://github.com/jupyterhub/jupyterhub/blob/0.7.2/jupyterhub/spawner.py#L642) that sets the right groups somehow.

**Comment by evandam** [comment]
Hi @minrk 

Closing this issue out - I followed your idea of subclassing `LocalProcessSpawner` and used another function to set gids and it worked like a charm! Here are my changes in case it's of any use to others down the road. I'm assuming it breaks the idea of keeping things platform-independent, but it works for my case on RHEL and likely other Linux/Mac systems.
jupyterhub_config.py:
```
c.JupyterHub.spawner_class = 'my_spawner.MySpawner'
```
my_spawner.py
```
import os
import sys
import pwd
from subprocess import check_output
from jupyterhub.spawner import LocalProcessSpawner, _try_setcwd

def set_user_setuid(username):
    user = pwd.getpwnam(username)
    uid = user.pw_uid
    gid = user.pw_gid
    home = user.pw_dir
    gids = [gid]

    try:
        groupnames = check_output(['groups', username]).split()[2:]
        ents = (check_output(['getent', 'group'] + groupnames)
            .decode('utf-8')
            .split('\n'))
        gids = [int(g.split(':')[2]) for g in ents if g]
        print('Set gids for %s to %s' % (username, gids), file=sys.stderr)
    except Exception as e:
        print('Could not get groups for user: %s' % username, file=sys.stderr)

    def preexec():
        os.setgid(gid)
        try:
            os.setgroups(gids)
            print('User = %s, Gid = %s, gids = %s' % (username, gid, gids), file=sys.stderr)
        except Exception as e:
            print('Failed to set groups for user %s' % username, file=sys.stderr)

        os.setuid(uid)

        _try_setcwd(home)

    return preexec

class MySpawner(LocalProcessSpawner):
    def make_preexec_fn(self, name):
        return set_user_setuid(name)
```

**Comment by willingc** [comment]
Thanks @evandam for sharing your solution with all. :cake:

**Comment by alexanderhaensch** [comment]
@evandam Thank you for sharing your spawner. This enables us to use groups from AD.
I had to slightly change the spawner, because some of our groups have spaces in the name. This breaks your script(user gets ALL groups). My script uses wbinfo from the samba suite.

`import os
import sys
import pwd
from subprocess import check_output
from jupyterhub.spawner import LocalProcessSpawner, _try_setcwd

def set_user_setuid(username):
    user = pwd.getpwnam(username)
    uid = user.pw_uid
    gid = user.pw_gid
    home = user.pw_dir
    gids = [gid]

    try:
        gids = check_output(['wbinfo', '-r', username]).decode("utf-8").split('\n')
        while '' in gids:
            gids.remove('')
        print(gids)
        gids = list(map(int, gids))
        print('Set gids for %s to %s' % (username, gids), file=sys.stderr)
    except Exception as e:
        print('Could not get groups for user: %s' % username, file=sys.stderr)
        print(e)
    def preexec():
        os.setgid(gid)
        try:
            os.setgroups(gids)
            print('User = %s, Gid = %s, gids = %s' % (username, gid, gids), file=sys.stderr)
        except Exception as e:
            print('Failed to set groups for user %s' % username, file=sys.stderr)
            print(e)

        os.setuid(uid)

        _try_setcwd(home)

    return preexec

class ADSpawner(LocalProcessSpawner):
    def make_preexec_fn(self, name):
        return set_user_setuid(name)
`

**Comment by evandam** [comment]
Happy to help @alexanderhaensch! I'll be sure to update to yours as well if I come across groups with spaces in the name.

Thanks!

**Comment by hurajt** [comment]
Hi @evandam @alexanderhaensch 
Thank you for your posts, it looks like this is exactly what I need - ability to use AD groups inside notebooks.  However, one bit puzzles me and that is, how to actually install the .py file you provided.  Simply locating it in the same directory as jupyterhub_config.py and then referring to it from jupyterhub_config.py doesn't work - I'm getting:

 The 'spawner_class' trait of <jupyterhub.app.JupyterHub object at 0x7f3dc829c1d0> instance must be a type, but 'adspawner.MySpawner' could not be imported

Many thanks!

**Comment by evandam** [comment]
@hurajt it's been a while and I'm not able to check how it's set up, but I believe it just needs to be somewhere `$PYTHONPATH` can find it.

**Comment by atnjqt** [comment]
@hurajt were you able to figure out configuring the additional .py spawner? I'm stuck on this step, we are also using AD which of course has groups w/ spaces in the names...

Instead of using the WBInfo as suggested by @alexanderhaensch given I'm using **realm** for domain join I went through and cleaned up the group names w/ spaces in them. I can run the code successfully, but I'm stuck on integrating this in my jupyterhub_config.py ... Does anyone know if this could be a pre_spawn_hook instead of a spawner class?

**Comment by hurajt** [comment]
@atnjqt I'm afraid not.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/failed-pam-auth/10388/1
