### ISSUE TITLE
How to pass user password to spawner?

### ISSUE THREAD

**Issue by yhtang** [jupyterhub/jupyterhub#1112]
Hi,

I am trying to modify the DockerSpawner to mount owncloud WebDAV path. I have set up an OpenLDAP server, and use LDAP authenticator for both jupyterhub and owncloud. As such I am wondering what is the 'correct' way to allow a user to enter password only once, for both authenticating into jupyterhub as well as for mounting the owncloud share within his docker container?

**Comment by surma-lodur** [comment]
Hi,

a little guide would be great.
This could also be genius, to tunnel for Example Bearer-OpenID Token.
That will make it easy for non Developer End-User to use different API's without direct Authentification.

**Comment by minrk** [comment]
Authenticators can pass info to Spawners by defining the `Authenticator.pre_spawn_start` method. This can do things like specify environment variables, etc.

As for storage, the only real option is to keep these tokens in memory only with current JupyterHub. Starting with the upcoming `0.8` release, `auth_state` is what should be used for this, and @yuvipanda will be working on this (https://github.com/jupyterhub/jupyterhub/issues/1117).
