### ISSUE TITLE
jupyterhub

### ISSUE THREAD

**Issue by johnbotsis** [jupyterhub/jupyterhub#1116]
[New Text Document.txt](https://github.com/jupyterhub/jupyterhub/files/969379/New.Text.Document.txt)

**Comment by johnbotsis** [comment]
500 : Internal Server Error 

Spawner failed to start [status=1]

**Comment by johnbotsis** [comment]
Hi Carol,

What information do you need?

**Comment by willingc** [comment]
Hi @johnbotsis,

I usually don't open files so I missed that you provided some debug output. Thanks for passing along. The 500 errors are usually caused by a network configuration issue or an invalid token.

The [troubleshooting docs](https://jupyterhub.readthedocs.io/en/latest/troubleshooting.html#error-after-spawning-my-single-user-server) give more information about 500 errors. Make sure that your setting for `c.JupyterHub.hub_ip` in `jupyterhub_config.py` is an IP address that all single user notebook servers can connect to.

**Comment by minrk** [comment]
@johnbotsis what's `python3 -m pip list`?

**Comment by johnbotsis** [comment]
alembic (0.9.1)
appdirs (1.4.3)
bleach (2.0.0)
boto3 (1.4.4)
botocore (1.5.37)
chardet (2.3.0)
click (6.7)
cloudpickle (0.2.2)
command-not-found (0.3)
dask (0.14.1)
decorator (4.0.11)
distributed (1.16.1)
docutils (0.13.1)
entrypoints (0.2.2)
HeapDict (1.0.0)
html5lib (0.999999999)
ipykernel (4.6.1)
ipyparallel (6.0.2)
ipython (6.0.0)
ipython-genutils (0.2.0)
ipywidgets (6.0.0)
jedi (0.10.2)
Jinja2 (2.9.6)
jmespath (0.9.2)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (5.0.1)
jupyter-console (5.1.0)
jupyter-core (4.3.0)
jupyterhub (0.7.2)
language-selector (0.1)
locket (0.2.0)
Mako (1.0.6)
MarkupSafe (1.0)
mistune (0.7.4)
msgpack-python (0.4.8)
nbconvert (5.1.1)
nbformat (4.3.0)
notebook (5.0.0)
numpy (1.12.1)
packaging (16.8)
pamela (0.3.0)
pandas (0.19.2)
pandocfilters (1.4.1)
partd (0.3.7)
pexpect (4.2.1)
pickleshare (0.7.4)
pip (8.1.1)
prompt-toolkit (1.0.14)
psutil (5.2.1)
ptyprocess (0.5.1)
pycurl (7.43.0)
Pygments (2.2.0)
pygobject (3.20.0)
pyparsing (2.2.0)
python-apt (1.1.0b1)
python-dateutil (2.6.0)
python-debian (0.1.27)
python-editor (1.0.3)
python-systemd (231)
pytz (2017.2)
pyzmq (16.0.2)
qtconsole (4.3.0)
requests (2.13.0)
s3fs (0.0.9)
s3transfer (0.1.10)
scipy (0.17.0)
setuptools (35.0.2)
simplegeneric (0.8.1)
six (1.10.0)
sortedcollections (0.5.3)
sortedcontainers (1.5.7)
SQLAlchemy (1.1.9)
ssh-import-id (5.5)
tblib (1.3.1)
terminado (0.6)
testpath (0.3)
toolz (0.8.2)
tornado (4.5.1)
traitlets (4.3.2)
ufw (0.35)
unattended-upgrades (0.1)
urllib3 (1.13.1)
wcwidth (0.1.7)
webencodings (0.5.1)
wheel (0.29.0)
widgetsnbextension (2.0.0)
zict (0.1.1)

**Comment by minrk** [comment]
Hm, it's weird that there's no output from the single-user subprocess. Can you launch JupyterHub by hand outside systemd and see if you get the same errors? It's possible that you need to set PATH or some other environment variables in the systemd config.

**Comment by johnbotsis** [comment]
Hi Min

Here is the results

---------------------------------------------------------
[I 2017-05-03 08:55:53.548 JupyterHub app:724] Loading cookie_secret from /root/jupyterhub_cookie_secret
[W 2017-05-03 08:55:53.745 JupyterHub app:365]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[W 2017-05-03 08:55:53.916 JupyterHub app:864] No admin users, admin interface will be unavailable.
[W 2017-05-03 08:55:53.916 JupyterHub app:865] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2017-05-03 08:55:53.916 JupyterHub app:892] Not using whitelist. Any authenticated user will be allowed.
[I 2017-05-03 08:55:53.944 JupyterHub app:1453] Hub API listening on http://127.0.0.1:8081/hub/
[W 2017-05-03 08:55:53.950 JupyterHub app:1174] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2017-05-03 08:55:53.951 JupyterHub app:1176] Starting proxy @ http://147.27.48.3:8000/
08:55:54.766 - info: [ConfigProxy] Proxying http://147.27.48.3:8000 to http://127.0.0.1:8081
08:55:54.772 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[I 2017-05-03 08:55:54.814 JupyterHub app:1485] JupyterHub is now running at http://147.27.48.3:8000/
[I 2017-05-03 08:58:43.417 JupyterHub log:100] 302 GET / (@147.27.14.71) 1.97ms
[I 2017-05-03 08:58:43.429 JupyterHub log:100] 302 GET /hub (@147.27.14.71) 0.67ms
[I 2017-05-03 08:58:43.446 JupyterHub log:100] 302 GET /hub/ (@147.27.14.71) 1.34ms
[I 2017-05-03 08:58:43.454 JupyterHub log:100] 302 GET /login (@147.27.14.71) 1.13ms
[I 2017-05-03 08:58:43.631 JupyterHub log:100] 200 GET /hub/login (@147.27.14.71) 170.36ms
Last login: Tue May  2 12:56:19 EEST 2017

|_   _|   _  ___   | | | |  _ \ / ___|
  | || | | |/ __|  | |_| | |_) | |
  | || |_| | (__   |  _  |  __/| |___
  |_| \__,_|\___|  |_| |_|_|    \____|


Welcome to High Performance Computing system at Technical University of Crete

Powered by Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-75-generic x86_64)

Supported by ** Torque 6.0.2 **
             ** Open MPI 2.0.0 **
             ** Jupyter **
             ** Spark 2.0.2 **
             ** Dask 0.11.0 **

*** Documentation:  www.grid.tuc.gr ***

System information as of: Wed May  3 08:58:58 EEST 2017

System Load:    0.76    IP Address:     147.27.48.3
Memory Usage:   13.3%   System Uptime:  6 days
Usage On /:     6%      Swap Usage:     5.1%
Local Users:    2       Processes:      192


19 packages can be updated.
0 updates are security updates.

[I 2017-05-03 08:59:00.109 JupyterHub spawner:783] Spawning jupyterhub-singleuser '--user="jb"' '--cookie-name="jupyter-hub-token-jb"' '--base-url="/user/jb"' '--hub-host=""' '--hub-prefix="/hub/"' '--hub-api-url="http://127.0.0.1:8081/hub/api"' '--ip="127.0.0.1"' --port=43454
Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 3, in <module>
    from jupyterhub.singleuser import main
**_# ImportError: No module named 'jupyterhub.singleuser'_**
[W 2017-05-03 08:59:15.810 JupyterHub web:1587] 500 POST /hub/login?next= (147.27.14.71): Spawner failed to start [status=1]
[E 2017-05-03 08:59:15.826 JupyterHub log:99] {
      "X-Forwarded-For": "147.27.14.71",
      "Accept-Encoding": "gzip, deflate",
      "X-Forwarded-Host": "se01.grid.tuc.gr:8000",
      "X-Forwarded-Proto": "http",
      "Content-Type": "application/x-www-form-urlencoded",
      "Accept-Language": "el-GR",
      "Accept": "text/html, application/xhtml+xml, image/jxr, */*",
      "Referer": "http://se01.grid.tuc.gr:8000/hub/login",
      "Host": "se01.grid.tuc.gr:8000",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko",
      "Connection": "close",
      "Cache-Control": "no-cache",
      "X-Forwarded-Port": "8000",
      "Content-Length": "28",
      "Cookie": "PHPSESSID=10bl5jck9cvn6071p9ouuc85u3"
    }
[E 2017-05-03 08:59:15.826 JupyterHub log:100] 500 POST /hub/login?next= (@147.27.14.71) 18347.54ms
[W 2017-05-03 08:59:34.549 JupyterHub user:278] jb's server never showed up at http://127.0.0.1:43454/user/jb after 30 seconds. Giving up
[E 2017-05-03 08:59:36.705 JupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at 0x7fbac8c04358> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 294, in spawn
        raise e
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 270, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/orm.py", line 108, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/utils.py", line 94, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://127.0.0.1:43454/user/jb didn't respond in 30 seconds

**Comment by minrk** [comment]
Indeed, this looks like the issue:

> ```
> Traceback (most recent call last):
>  File "/usr/local/bin/jupyterhub-singleuser", line 3, in <module>
>    from jupyterhub.singleuser import main
>  ImportError: No module named 'jupyterhub.singleuser'
> ```

What is `head -n1 /usr/local/bin/jupyterhub-singleuser` ? Is it the Python you expect it to be? From the looks of your other tracebacks, it should be `#!/usr/bin/python3.5`. You may need to reinstall the jupyterhub package.

**Comment by johnbotsis** [comment]
Hi Min

root@se01:~# head -n1 /usr/local/bin/jupyterhub-singleuser
#!/usr/bin/python3
------------------------------------------------
Any suggestion about reinstalling....

"pip3 install --ignore-installed  jupyterhub"   is enough

and what about configurable-http-proxy which is installed with npm ?

Thanks....

**Comment by minrk** [comment]
> and what about configurable-http-proxy which is installed with npm ?

You can remove CHP with `npm remove -g configurable-http-proxy`, but it doesn't look like that's the issue here.

**Comment by johnbotsis** [comment]
Hi Min,

I reinstall jupyterhub but the problem still remain....
--------------------------------------------------------------------------------
Traceback (most recent call last):
 File "/usr/local/bin/jupyterhub-singleuser", line 3, in <module>
   from jupyterhub.singleuser import main
 ImportError: No module named 'jupyterhub.singleuser'
--------------------------------------------------------------------------------


It seems to be permissions problem, because every time i reinstall jupyterhub

ls -l looks like this....

-rwxrwx--x 1 root root   59 May  4 12:09 jupyterhub
-rwxrwx--x 1 root root   98 May  4 12:09 jupyterhub-singleuser

and the error i get is 

Spawning jupyterhub-singleuser '--user="jb"' '--cookie-name="jupyter-hub-token-jb"' '--base-url="/user/jb"' '--hub-host=""' '--hub-prefix="/hub/"' '--hub-api-url="http://127.0.0.1:8081/hub/api"' '--ip="127.0.0.1"' --port=39290
/usr/bin/python3: can't open file '/usr/local/bin/jupyterhub-singleuser': [Errno 13] **_Permission denied_**
[W 2017-05-05 08:15:08.375 JupyterHub web:1587] 500 POST /hub/login?next= (::ffff:147.27.14.71): Spawner failed to start [status=2]
-------------------------------------------------------------------------------------------

I chmod 775 

-rwxrwxr-x 1 root root   59 May  4 12:09 jupyterhub
-rwxrwxr-x 1 root root   98 May  4 12:09 jupyterhub-singleuser

and i get 

-----------------------------------------------------------------------------------
 Spawning jupyterhub-singleuser '--user="jb"' '--cookie-name="jupyter-hub-token-jb"' '--base-url="/user/jb"' '--hub-host=""' '--hub-prefix="/hub/"' '--hub-api-url="http://127.0.0.1:8081/hub/api"' '--ip="127.0.0.1"' --port=35728
Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 3, in <module>
    from jupyterhub.singleuser import main
ImportError: No module named 'jupyterhub.singleuser'
[W 2017-05-05 08:18:04.997 JupyterHub web:1587] 500 POST /hub/login?next= (::ffff:147.27.14.71): Spawner failed to start [status=1]
---------------------------------------------------------------------------------------------

**Comment by johnbotsis** [comment]
Hi Min

Finally the problem was permissions. All the files in the /usr/local/lib/python3.5/dist-packages had no  access to others. I changed directories to 775 and files to 664 and everything works fine now.

Maybe it was python and ubuntu installation issue.

Anyway thanks for your help.

jb

**Comment by coolteddy** [comment]
Thanks all, chmod solve the issue. python3 installation was something went wrong.

**Comment by andybala** [comment]
**I** have installed Jupyterhub on windows 10 using anaconda3.7 base. Not sure how to handle this error 

(base) C:\Users\ahb>jupyterhub
[I 2019-03-25 12:49:45.005 JupyterHub app:1673] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.4
[I 2019-03-25 12:49:45.005 JupyterHub app:1673] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.4
[I 2019-03-25 12:49:45.020 JupyterHub app:1016] Loading cookie_secret from C:\Users\ahbalasubramanian\jupyterhub_cookie_secret
[I 2019-03-25 12:49:45.036 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[E 2019-03-25 12:49:45.036 JupyterHub app:1958]
    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\jupyterhub\app.py", line 1955, in launch_instance_async
        await self.initialize(argv)
      File "C:\Anaconda3\lib\site-packages\jupyterhub\app.py", line 1684, in initialize
        await self.init_users()
      File "C:\Anaconda3\lib\site-packages\jupyterhub\app.py", line 1148, in init_users
        if self.authenticator.enable_auth_state:
      File "C:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
        return self.get(obj, cls)
      File "C:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 535, in get
        value = self._validate(obj, dynamic_default())
      File "C:\Anaconda3\lib\site-packages\jupyterhub\app.py", line 675, in _authenticator_default
        return self.authenticator_class(parent=self, db=self.db)
      File "C:\Anaconda3\lib\site-packages\jupyterhub\auth.py", line 604, in __init__
        raise _pamela_error from None
      File "C:\Anaconda3\lib\site-packages\jupyterhub\auth.py", line 14, in <module>
        import pamela
    ModuleNotFoundError: No module named 'pamela'

**Comment by rjolicoe** [comment]
I am having the same issue on my computer.  I have blown away anaconda and reinstalled and can't access Jupyter Hub.
