### ISSUE TITLE
async syntax

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#1118]
We're using tornado as our async runner and `@gen.coroutine` all over the place.

We could be using Python 3.5's `async def` and `await` syntax instead of `@gen.coroutine` and `yield`. There's no practical change in behavior that I know of (we'd still use tornado, just not tornado's Python 2-compatible syntax). I don't have a good sense for how many folks are relying on Python 3.4 to run JupyterHub, though (current minimum Python is officially 3.3).

**Comment by barrachri** [comment]
Could we put this change in 0.8 and put Python 3.5 as requirement?
As they say on the website (http://www.tornadoweb.org/en/stable/guide/coroutines.html) we should see speed improvements.

**Comment by minrk** [comment]
Potentially. What I don't know (and don't know how to discern) is how many people are running with 3.4 or earlier who would have difficulty upgrading to 3.5. In the context of JupyterHub, the performance difference should be pretty negligible, given that database operations and the like will generally dominate any Python call overhead.

I think marking this for 0.9 probably makes sense.

**Comment by willingc** [comment]
We'll likely get info about 3.4/3.5 usage at PyCon. I doubt many folks are using 3.3 still. I think 0.9 makes sense with an open door to pull into 0.8 if it simplifies reliability and testing during development and production.

**Comment by dhirschfeld** [comment]
I'd be happy with 3.5 being the minimum requirement for 0.8... but that's because I've already moved to 3.6 so it's easy for me to say.

I think there are still packages which don't work for 3.6 which is holding back adoption but the same isn't true for 3.5 - it's probably the best supported version currently so I don't see that there's much barrier to anyone upgrading from 3.4 --> 3.5.

**Comment by yuvipanda** [comment]
I think 0.9 is the minimum we should do (and ideally I'd prefer 0.10). Debian Jessie ships with 3.4 (not 3.5), and so does EPEL for Centos 7 (last time I checked). We aren't using any of the 3.5 syntaxes now, and we're pretty close to 0.8. Let's defer the decision until after 0.8? :)

**Comment by zsluedem** [comment]
agree with @yuvipanda

**Comment by minrk** [comment]
👍 to setting minimum to 3.4 for 0.8 and re-evaluating 3.5 in a release or two. While it would have been nice to have async/await from the beginning, now that the Hub is ~all written, they honestly don't provide much benefit over `@coroutine` and `yield`. So we can wait for a more compelling reason to come along and trigger the next transition.
