### ISSUE TITLE
Jupyterhub doesn't have an extra_template_paths?

### ISSUE THREAD

**Issue by dsblank** [jupyterhub/jupyterhub#112]
It appears that jupyterhub doesn't support an extra_templates_path parameter like NotebookApp does. This makes it difficult to easily customize the pages.

Also, it would be nice if there were additional blocks defined in the provided html to allow places for custom code.

**Comment by elgalu** [comment]
How do you guys customize the classic notebook templates via JupyterHub these days?

I've tried `c.NotebookApp.extra_template_paths` within a `jupyter_notebook_config.py` in the singleuser docker image with no luck.

Is it somehow related to this hub `page_template` customization?
https://github.com/jupyterhub/jupyterhub/blob/d962e8bcbcb23e21f8c5292092a2c0b04662d5d9/jupyterhub/singleuser.py#L141

**Comment by elgalu** [comment]
To expand on my previous comment; I'm able to extend any notebook page:
- tree.html via `{% extends "templates/tree.html" %}`
- edit.html via `{% extends "templates/edit.html" %}`
- etc...

Except page.html and I suspect it has to do with this:
https://github.com/jupyterhub/jupyterhub/blob/d962e8bcbcb23e21f8c5292092a2c0b04662d5d9/jupyterhub/singleuser.py#L480-L482
