### ISSUE TITLE
Conflicting Sphinx Min Version

### ISSUE THREAD

**Issue by charnpreetsingh** [jupyterhub/jupyterhub#1125]
I was trying to run the JupyterHub docs locally but came across conflicting Sphinx minimum versions.
Both `requirements.txt` and `environment.yml` had a minimum version of 1.3.6 while `conf.py` was enforcing a min version of 1.4

https://github.com/jupyterhub/jupyterhub/blob/master/docs/source/conf.py#L16

**Comment by willingc** [comment]
The minimum version in conf.py means that the version is guaranteed to be 1.4 or above not pinned to 1.4. We should be using one of the most recent builds of Sphinx 1.5.x.

**Comment by willingc** [comment]
As an FYI, @charnpreetsingh, to use recommonmark (https://github.com/rtfd/recommonmark/blob/master/recommonmark/__init__.py#L9) you must have 1.4 or above for Sphinx.

**Comment by willingc** [comment]
Do you want to submit a PR to update the requirements.txt and environment.yml?

**Comment by charnpreetsingh** [comment]
Yep, I can do that. I see that recommonmark is pinned to version 0.4.0 . Should that be updated too?

**Comment by willingc** [comment]
Let's leave recommonmark pinned. There's some nasty dependency stuff there with commonmark and markdown so let's keep it where it is for now. :-)
