### ISSUE TITLE
Setting up Jupyterhub with SSL and passphrase on Debian-based Linux os

### ISSUE THREAD

**Issue by jonny86** [jupyterhub/jupyterhub#1134]
Hello Everyone,
Thats my first github post !

I use Ubuntu 16.04 LTS and jupyterhub 0.7.2

I like to set up Jupyterhub with ssl support.
My ssl certicate needs a passphrase.

Previously i have set up the same configuration on an oracle linux system.
Once I executed the command
jupyterhub 
A message prompted "Enter PEM pass phrase:"
I entered the passphrase 
The jupyterhub server started succesfully 
and everything worked fine

Now i want to do the same thing on ubuntu server / kubuntu.
I used completely used the same configuration but when i execute
jupyterhub
No message prompted "Enter PEM pass phrase:" 
Instead I get the following error message

```
_tls_common.js:87
        c.context.setKey(options.key);
                  ^

Error: error:0906A068:PEM routines:PEM_do_header:bad password read
    at Error (native)
    at Object.createSecureContext (_tls_common.js:87:19)
    at Server (_tls_wrap.js:736:25)
    at new Server (https.js:17:14)
    at Object.exports.createServer (https.js:37:10)
    at new ConfigurableProxy (/usr/local/lib/node_modules/configurable-http-proxy/lib/configproxy.js:174:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy:202:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
check2
1
[C 2017-05-10 13:41:57.536 JupyterHub app:1462] Failed to start proxy
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/app.py", line 1460, in start
        yield self.start_proxy()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/app.py", line 1200, in start_proxy
        _check()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/app.py", line 1194, in _check
        raise e
    RuntimeError: Proxy failed to start with exit code 1
```
The error is independent whether I run jupyterhub with sudo or not.
If I dont use ssl jupyterhub starts and runs successfully.

Here is the result of `jupyter troubleshoot`

```
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
$PATH:
        /usr/local/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /usr/games
        /usr/local/games
        /snap/bin

sys.path:
        /usr/local/bin
        /usr/lib/python35.zip
        /usr/lib/python3.5
        /usr/lib/python3.5/plat-x86_64-linux-gnu
        /usr/lib/python3.5/lib-dynload
        /usr/local/lib/python3.5/dist-packages
        /home/{my name}/Downloads/pylearn2-master
        /usr/lib/python3/dist-packages

sys.executable:
        /usr/bin/python3

sys.version:
        3.5.2 (default, Nov 17 2016, 17:05:23) 
        [GCC 5.4.0 20160609]

platform.platform():
        Linux-4.4.0-72-generic-x86_64-with-Ubuntu-16.04-xenial

which -a jupyter:
        /usr/local/bin/jupyter
        /usr/local/bin/jupyter

pip list:
        alabaster (0.7.10)
        alembic (0.9.1)
        appdirs (1.4.3)
        apturl (0.5.2)
        astroid (1.4.9)
        Babel (2.3.4)
        beautifulsoup4 (4.5.3)
        bleach (2.0.0)
        bs4 (0.0.1)
        chardet (2.3.0)
        command-not-found (0.3)
        cycler (0.9.0)
        Cython (0.25.2)
        decorator (4.0.11)
        defer (1.0.6)
        Django (1.10.5)
        django-auth-ldap (1.2.8)
        django-bower (5.2.0)
        django-npm (1.0.0)
        djangoajax (2.3.6)
        docutils (0.13.1)
        entrypoints (0.2.2)
        flake8 (2.5.5)
        flake8-docstrings (1.0.2)
        fuzzywuzzy (0.14.0)
        hacking (0.12.0)
        html5lib (0.999999999)
        httpie (0.9.9)
        imagesize (0.7.1)
        ipykernel (4.5.2)
        ipython (5.3.0)
        ipython-genutils (0.2.0)
        ipywidgets (5.2.2)
        isort (4.2.5)
        jedi (0.9.0)
        Jinja2 (2.9.5)
        jsonschema (2.6.0)
        jupyter (1.0.0)
        jupyter-client (5.0.0)
        jupyter-console (5.0.0)
        jupyter-core (4.3.0)
        jupyterhub (0.7.2)
        jupyterhub-ldapauthenticator (1.1)
        language-selector (0.1)
        lazy-object-proxy (1.2.2)
        ldap3 (2.1.0)
        lxml (3.5.0)
        Mako (1.0.6)
        MarkupSafe (1.0)
        matplotlib (1.5.1)
        mccabe (0.6.1)
        mistune (0.7.4)
        mod-wsgi (4.5.13)
        mpld3 (0.3)
        mysqlclient (1.3.9)
        nbconvert (5.1.1)
        nbformat (4.3.0)
        nltk (3.2.1)
        notebook (4.3.0)
        numexpr (2.4.3)
        numpy (1.12.1)
        numpydoc (0.6.0)
        packaging (16.8)
        pamela (0.3.0)
        pandas (0.20.1)
        pandocfilters (1.4.1)
        patsy (0.4.1)
        pbr (1.10.0)
        pep8 (1.7.0)
        pexpect (4.2.1)
        pickleshare (0.7.4)
        Pillow (3.1.2)
        pip (9.0.1)
        pip-review (0.5.2)
        prompt-toolkit (1.0.13)
        protobuf (3.1.0.post1)
        psutil (5.2.0)
        psycopg2 (2.6.1)
        ptyprocess (0.5.1)
        py4j (0.10.4)
        pyasn1 (0.1.9)
        pycodestyle (2.2.0)
        pycups (1.9.73)
        pycurl (7.43.0)
        pydocstyle (1.1.1)
        pyflakes (1.5.0)
        pygermanet (1.0.1)
        Pygments (2.2.0)
        pygobject (3.20.0)
        pyldap (2.4.25.1)
        pylearn2 (0.1.dev0, /home/{my name}/Downloads/pylearn2-master)
        pylint (1.6.5)
        pymongo (3.3.1)
        PyMySQL (0.7.9)
        pyparsing (2.2.0)
        PyQt5 (5.7)
        python-apt (1.1.0b1)
        python-dateutil (2.6.0)
        python-editor (1.0.3)
        python-Levenshtein (0.12.0)
        python-pptx (0.6.1)
        python-systemd (231)
        pytz (2017.2)
        PyYAML (3.12)
        pyzmq (16.0.2)
        QtAwesome (0.4.4)
        qtconsole (4.2.1)
        QtPy (1.2.1)
        redis (2.10.5)
        reportlab (3.3.0)
        repoze.lru (0.6)
        requests (2.13.0)
        roman (2.0.0)
        rope-py3k (0.9.4.post1)
        scikit-learn (0.18.1)
        scipy (0.18.1)
        setuptools (34.3.2)
        simplegeneric (0.8.1)
        simplejson (3.10.0)
        sip (4.18.1)
        six (1.10.0)
        snowballstemmer (1.2.1)
        Sphinx (1.5.3)
        sphinx-rtd-theme (0.1.9)
        spyder (3.1.3)
        SQLAlchemy (1.1.3)
        statsmodels (0.6.1)
        tables (3.2.2)
        tensorflow (0.12.1)
        terminado (0.6)
        testpath (0.3)
        textblob (0.11.1)
        textblob-de (0.4.2)
        Theano (0.8.2)
        tornado (4.4.2)
        traitlets (4.3.2)
        ubuntu-drivers-common (0.0.0)
        ufw (0.35)
        unattended-upgrades (0.1)
        urllib3 (1.13.1)
        virtualenv (15.1.0)
        wcwidth (0.1.7)
        webencodings (0.5)
        wheel (0.29.0)
        widgetsnbextension (1.2.6)
        wrapt (1.10.10)
        xkit (0.0.0)
        xlrd (1.0.0)
        XlsxWriter (0.9.3)
```
The issue appears both on ubuntu server as well as on kubuntu
Thanks in advance for helping me,
Jonny

**Comment by willingc** [comment]
Welcome @jonny86. 

Would you mind sharing the results of `configurable-http-proxy --version`? Thanks.

**Comment by jonny86** [comment]
Hello willingc

Here are the requested results
configurable-http-proxy --version
2.0.1 (Kubuntu & Ubuntu Server doesnt work)
1.1.0(Oracle Linux works)

node --version
v4.2.6 (Kubuntu & Ubuntu Server doesnt work)
v0.10.42 (Oracle linux works)

**Comment by jonny86** [comment]
I updated my node version on Oracle linux to the latest package that yum provides (v6.10.1)
and now i get the same error on oracle linux

**Comment by willingc** [comment]
Hi @jonny86, We're very close to releasing JupyterHub 0.8. Please try your configuration with JupyterHub master. If you are still having logged errrors, please let us know. Thanks. :sunny:

**Comment by jonny86** [comment]
Thank you very much for addressing my issue. Currently i am on vacation. When i am back on 14.08.2017 i will recheck with up to date node.js and jupyterhub 0.8
Kind regards,Jonathan 


Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Carol Willing <notifications@github.com> Datum: 07.08.17  18:35  (GMT+01:00) An: jupyterhub/jupyterhub <jupyterhub@noreply.github.com> Cc: jonny86 <je86@gmx.net>, Mention <mention@noreply.github.com> Betreff: Re: [jupyterhub/jupyterhub] Setting up Jupyterhub with SSL and passphrase on Debian-based Linux os (#1134) 
Hi @jonny86, We're very close to releasing JupyterHub 0.8. Please try your configuration with JupyterHub master. If you are still having logged errrors, please let us know. Thanks. ☀️

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jupyterhub/jupyterhub","title":"jupyterhub/jupyterhub","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jupyterhub/jupyterhub"}},"updates":{"snippets":[{"icon":"PERSON","message":"@willingc in #1134: Hi @jonny86, We're very close to releasing JupyterHub 0.8. Please try your configuration with JupyterHub master. If you are still having logged errrors, please let us know. Thanks. :sunny:"}],"action":{"name":"View Issue","url":"https://github.com/jupyterhub/jupyterhub/issues/1134#issuecomment-320714105"}}}

**Comment by willingc** [comment]
Thanks @jonny86. I hope you have a lovely vacation :smile:

**Comment by christophelec** [comment]
Hi,

I am hit by the same issue as well, using Jupyterhub 0.8.0b2 (version of the master this afternoon) :

```
[user@host context]$ jupyterhub --version
0.8.0.b2
[user@host context]$ jupyterhub
[W 2017-08-21 17:17:46.219 JupyterHub app:390] JupyterHub.proxy_api_ip is deprecated in JupyterHub 0.8, use ConfigurableHTTPProxy.api_url
[I 2017-08-21 17:17:46.223 JupyterHub app:843] Loading cookie_secret from /home/user/jupyterhub/context/jupyterhub_cookie_secret
[I 2017-08-21 17:17:46.292 JupyterHub app:988] Not using whitelist. Any authenticated user will be allowed.
[I 2017-08-21 17:17:46.314 JupyterHub app:1531] Hub API listening on http://ip.ip.ip.ip:8081/hub/
[I 2017-08-21 17:17:46.316 JupyterHub proxy:457] Starting proxy @ https://*:8000/
_tls_common.js:105
      c.context.setKey(options.key, options.passphrase);
                ^

Error: error:0906A068:PEM routines:PEM_do_header:bad password read
    at Object.createSecureContext (_tls_common.js:105:17)
    at Server (_tls_wrap.js:794:25)
    at new Server (https.js:54:14)
    at Object.createServer (https.js:76:10)
    at new ConfigurableProxy (.../node_modules/configurable-http-proxy/lib/configproxy.js:175:35)
    at Object.<anonymous> (.../node_modules/configurable-http-proxy/bin/configurable-http-proxy:202:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```
The key is valid/cert should both be valid as demonstrated with a quick OpenSSL check :

```
from OpenSSL import crypto

pkey_obj = crypto.load_privatekey(crypto.FILETYPE_PEM, private_key_text)
# Here, I get asked for my passphrase

cert_obj = crypto.load_certificate(crypto.FILETYPE_PEM, certificate_text)

import OpenSSL
ctx = OpenSSL.SSL.Context(OpenSSL.SSL.TLSv1_METHOD)
ctx.use_privatekey(pkey_obj)
ctx.use_certificate(cert_obj)
ctx.check_privatekey()
```

It works fine with a passphrase-less private key.

I am available if you need more tests, but I think the cause of the issue is the missing passphrase : could it be passed by other means ? (parameters or others)

**Comment by jonny86** [comment]
Hello everyone,
This problem remains.
However I have modified:
app.py and proxy.py of jupterhub 
as well as configproxy.js of configurable-http-proxy
such that it works !

I am familiar with git however maybe someone can help with my first open source contribution ?

**Comment by amellnik** [comment]
Would it be possible to pass a `SSLContext` as described [here](https://github.com/tornadoweb/tornado/issues/2113)?  This issue continues to exist on released 0.8 and 0.9 master.

**Comment by Mereep** [comment]
Having the very same problem. Are there any updates on this?

**Comment by minrk** [comment]
https://github.com/jupyterhub/configurable-http-proxy/pull/175 adds support to pull this from the environment in configurable-http-proxy. There shouldn't be anything to do on this repo for this issue, since the Python process doesn't set up SSL.

**Comment by Heerpa** [comment]
It looks like this merge solved my current issue: I am trying to have my jupyter notebook use https with a passphrase-protected certfile/keyfile. I am running it in a docker container via docker-compose, with the following command

````
        environment:
            USE_HTTPS: "yes"
            PASSWORD: ${PASSWORD}
        command: >
            bash -c "
            cp -R /usr/src/introducing_versions /data &&
            start-notebook.sh
            --NotebookApp.certfile=/usr/src/Docker_env/certfiles/certfile.pem
            --NotebookApp.keyfile=/usr/src/Docker_env/certfiles/keyfile.pem
            --NotebookApp.password=${PASSWORD}
            --NotebookApp.allow_remote_access=True
            "
````
When running this, I get
````
-notebook    | Enter PEM pass phrase:
````
in my console when I navigate to the respective url in my browser, but there is no way to enter the pass phrase. I expect that I need to somehow add the pass phrase as an argument, but the closest I can find is NotebookApp.ssl_optionsDict (https://jupyter-notebook.readthedocs.io/en/stable/config.html). However, how can I make a dict in bash?

The second end I found was in the merge: https://github.com/jupyterhub/configurable-http-proxy/commit/19528a10e87490b019a17feb87eeb2ba8aac88c1
I need to get my pass phrase into process.env.CONFIGPROXY_SSL_KEY_PASSPHRASE, but how do I do that?

Thanks!
