### ISSUE TITLE
run a single shared notebook server using oauth

### ISSUE THREAD

**Issue by ryantuck** [jupyterhub/jupyterhub#1136]
I've been running a shared juypterhub server using an image from https://github.com/jupyter/docker-stacks

The nice thing about running a single jupyter notebook server is that people can easily share notebooks, and I don't want to give that up.

I'd like to use Google oauth for authentication instead of the password auth provided in that other repo, just like jupyterhub provides. But I *don't* want to spawn an individual server per user.

Is this possible using jupyterhub? Or should I file an issue over at the `oauthenticator` repo, or the `docker-stacks` repo?

**Comment by minrk** [comment]
If you want to use a single notebook server, you can have a single user as far as JupyterHub is concerned, and map any OAuth user to that JupyterHub user. There is a method that transforms the upstream username into the JupyterHub username (normally, this just does `name.lower()`), but you could use it to transform allowed names into a single 'user' name:

```python
class SharedUserAuthenticator(GoogleOAuthenticator):
    shared_users = {'you', 'me', 'other'}
    # only the magic 'shared' user is allowed in JupyterHub
    whitelist = {'shared'}
    
    def normalize_username(username):
        username = username.lower()
        if username in self.shared_users:
            # all authenticated users are 'shared' to JupyterHub
            return 'shared'
        else:
            return 'notallowed'
```


Alternately, since you only want one notebook server, you could write a custom LoginHandler that does the OAuth for the single-user server and skip JupyterHub entirely.

**Comment by attardi** [comment]
I have a similar question.
I am using GoogleOAuthenticator to authenticate users in my university, including students.
However I don't want to create hundreds of linux accounts on the server running Jupyterhub.
I could use the suggested solution to map them all to the same account, but I would like each one to have a different notebook directory, so they don't step on each other.
How can I do that?

**Comment by attardi** [comment]
BTW, normalize should have as first argument self.

**Comment by attardi** [comment]
I have added this to GoogleOAuthenticator (better to create a subclass, though):

    defaultUsername = 'jupyter'

    def normalize_username(self, username):
	"""Specialization that maps all users to a single account (jupyter),                        
        unless mapped differently by Authenticator.username_map.                                    
        """
        username = username.lower()
        return self.username_map.get(username, self.defaultUsername)

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!
