### ISSUE TITLE
Using pyspark2 / spark2 in jupyterhub

### ISSUE THREAD

**Issue by SteveFelker** [jupyterhub/jupyterhub#1149]
Hello again, Guys,

  Well, sadly, I am stumped again.  I am trying to use pyspark2 from jupyterhub and am running into problems.  I am able to use it when I launch a standalone jupyter notebook, however.  So clearly, I am missing a setting or an environment variable, but it is eluding me.

When I launch the standalone notebook, I issue these commands:

```bash
export PATH=/opt/anaconda3-4.2.0/bin:$PATH
export PYSPARK_DRIVER_PYTHON=/opt/anaconda3-4.2.0/bin/jupyter
export PYSPARK_DRIVER_PYTHON_OPTS="notebook --NotebookApp.open_browser=False --NotebookApp.ip='*' --NotebookApp.port=8777"
pyspark2
```

Then I open a browser page and point to to the right place.  I then start a new python notebook and enter the following commands:

```python
from pyspark.sql.functions import *
from pyspark.sql.types import *
df1 = sqlContext.sql("select * from myDB where day > '151031' ") 
df1.count()
```

And as expected, I get the count.

Now, the problem...

To launch jupyterhub, I logged in as root, and issued the following commands:

```bash
export PATH=/opt/anaconda3-4.2.0/bin:$PATH
export PYSPARK_DRIVER_PYTHON=/opt/anaconda3-4.2.0/bin/jupyter
jupyterhub
```

I know from many web searches that things are a little different when using jupyterhub, so following the instructions I found online, I issue the following commands, again in a new python notebook:

```python
import os
import sys
os.environ["JAVA_HOME"] = "/usr/java/jdk1.7.0_67-cloudera"
os.environ["SPARK_HOME"] = "/opt/cloudera/parcels/SPARK2/lib/spark2"
os.environ["PYLIB"] = os.environ["SPARK_HOME"] + "/python/lib"
sys.path.insert(0, os.environ["PYLIB"] +"/py4j-0.10.4-src.zip")
sys.path.insert(0, os.environ["PYLIB"] +"/pyspark.zip")
```

Then on to the same commands from before:

```python
from pyspark.sql.functions import *
from pyspark.sql.types import *
df1 = sqlContext.sql("select * from myDB where day > '151031' ") 
```

at which point I get the error:

```python
NameError                                 Traceback (most recent call last)
<ipython-input-19-df0c62c88869> in <module>()
----> 1 df1 = sqlContext.sql("select * from myDB where day > '151031' ")

NameError: name 'sqlContext' is not defined
```

myDB is a hive table on the cluster.  Anybody have any idea what I am missing here, and how to fix it?

Thanks!
Steve

**Comment by minrk** [comment]
When using pyspark as a library, the `sqlContext` is not created automatically, you have to create it yourself:

```python
import pyspark
sqlContext = pyspark.SQLContext(pyspark.SparkContext())
```

This is true in any Python context where pyspark hasn't automatically injected its setup, such as a plain Python script or normal Jupyter notebook server.

**Comment by SteveFelker** [comment]
Thanks for the reply, @minrk .

When I issue the command `sqlContext = pyspark.SQLContext(pyspark.SparkContext())` I get the following error:

`Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: org.apache.spark.SparkException: Yarn application has already ended! It might have been killed or unable to launch application master.`

It sounds like I have missed a configuration setting.  Any idea?

Thanks!
Steve

--

Here is the full error:

`---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-10-ca4650d3e68b> in <module>()
----> 1 sqlContext = pyspark.SQLContext(pyspark.SparkContext())

/opt/cloudera/parcels/SPARK2/lib/spark2/python/lib/pyspark.zip/pyspark/context.py in __init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls)
    116         try:
    117             self._do_init(master, appName, sparkHome, pyFiles, environment, batchSize, serializer,
--> 118                           conf, jsc, profiler_cls)
    119         except:
    120             # If an error occurs, clean up in order to allow future SparkContext creation:

/opt/cloudera/parcels/SPARK2/lib/spark2/python/lib/pyspark.zip/pyspark/context.py in _do_init(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, jsc, profiler_cls)
    180 
    181         # Create the Java SparkContext through Py4J
--> 182         self._jsc = jsc or self._initialize_context(self._conf._jconf)
    183         # Reset the SparkConf to the one actually used by the SparkContext in JVM.
    184         self._conf = SparkConf(_jconf=self._jsc.sc().conf())

/opt/cloudera/parcels/SPARK2/lib/spark2/python/lib/pyspark.zip/pyspark/context.py in _initialize_context(self, jconf)
    247         Initialize SparkContext in function to allow subclass specific initialization
    248         """
--> 249         return self._jvm.JavaSparkContext(jconf)
    250 
    251     @classmethod

/opt/cloudera/parcels/SPARK2/lib/spark2/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1399         answer = self._gateway_client.send_command(command)
   1400         return_value = get_return_value(
-> 1401             answer, self._gateway_client, None, self._fqn)
   1402 
   1403         for temp_arg in temp_args:

/opt/cloudera/parcels/SPARK2/lib/spark2/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    317                 raise Py4JJavaError(
    318                     "An error occurred while calling {0}{1}{2}.\n".
--> 319                     format(target_id, ".", name), value)
    320             else:
    321                 raise Py4JError(

Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: org.apache.spark.SparkException: Yarn application has already ended! It might have been killed or unable to launch application master.
	at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.waitForApplication(YarnClientSchedulerBackend.scala:85)
	at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:62)
	at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:171)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:509)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:236)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by SteveFelker** [comment]
Thank you @minrk!  That was the trick!  Ignore the last comment I sent on this.  My problem was due to access restrictions on the cluster.

Steve

**Comment by minrk** [comment]
Glad you worked it out!

**Comment by rao-abdul-mannan** [comment]
I have created a public gist to configure spark2.x, jupyterhub & cdh5.13 cluster. It may help you [here](https://gist.github.com/rao-abdul-mannan/30708e85ac56d5d8e2f3b019d4e96f05)
