### ISSUE TITLE
IOPub limits setting to jupyterhub

### ISSUE THREAD

**Issue by BoomBidiBuyBuy** [jupyterhub/jupyterhub#1152]
Hello,

I'm integrating jupyterhub with plotly (https://plot.ly/), and for python it works fine, but for R it returns the following error on the simple example from the plotly documentation:

> IOPub data rate exceeded.
> The notebook server will temporarily stop sending output
> to the client in order to avoid crashing it.
> To change this limit, set the config variable
> `--NotebookApp.iopub_data_rate_limit`.

I have found the solution for jupyter (it's setting corresponding parameter as an arugment upyter notebook --NotebookApp.iopub_data_rate_limit=10000000000), but don't know where I could set that limit to jupyterhub. I've tried to set this variable in config file, like:

c.NotebookApp.iopub_data_rate_limit=10000000000

But without success. I've tried to set it right as an argument to jupyterhub 'jupyterhub --NotebookApp.iopub_data_rate_limit=10000000000', it it hasn't resolved the issue too. 
I wonder where I could specify it to overcome this limitation?

Thanks,
With best regards,
Ruslan Galinsky

**Comment by BoomBidiBuyBuy** [comment]
I've resolved it with passing corresponding argument to spawner. Sorry fro the bothering!

**Comment by patrickfuller** [comment]
For those of you googling around for this:

```
c.Spawner.args = ['--NotebookApp.iopub_data_rate_limit=1000000000']
```

**Comment by shilpam11** [comment]
Seemed to me that the error is thrown when the internet is active and the command is used. However it executed when there was no internet connected.

**Comment by Prettyfield** [comment]
I didn't have access to the server, but I was able to work around this by simply setting a list index in the list I was trying to display.  In other words,
 `print state_list` would generate 

> IOPub data rate exceeded...
but
`print state_list[:10000]`
would generate the first 10k items in the list.
Not perfect, but useful as a work-around.
