### ISSUE TITLE
jupyterlab-hub isn't getting passed the port argument from DockerSpawner?

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterhub/jupyterhub#1154]
When using a container with the notebook command JupyterHub correctly spawns my container on the remote host and I get a working Notebook instanct

If all I change is the command from `jupyter notebook ...` to `jupyter labhub ...` I get the below error about the port not being passed as an argument:
```
[W 2017-05-25 14:25:52.555 SingleUserLabApp configurable:168] Config option `open_browser` not recognized by `SingleUserLabApp`.  Did you mean `browser`?
[W 2017-05-25 14:25:52.556 SingleUserLabApp configurable:168] Config option `token` not recognized by `SingleUserLabApp`.
[W 2017-05-25 14:25:53.106 SingleUserLabApp configurable:168] Config option `open_browser` not recognized by `SingleUserLabApp`.  Did you mean `browser`?
[W 2017-05-25 14:25:53.107 SingleUserLabApp configurable:168] Config option `token` not recognized by `SingleUserLabApp`.
[W 2017-05-25 14:25:53.112 SingleUserLabApp configurable:168] Config option `open_browser` not recognized by `SingleUserLabApp`.  Did you mean `browser`?
[W 2017-05-25 14:25:53.113 SingleUserLabApp configurable:168] Config option `token` not recognized by `SingleUserLabApp`.
[W 2017-05-25 14:25:53.115 SingleUserLabApp configurable:168] Config option `open_browser` not recognized by `SingleUserLabApp`.  Did you mean `browser`?
[W 2017-05-25 14:25:53.115 SingleUserLabApp configurable:168] Config option `token` not recognized by `SingleUserLabApp`.
[W 2017-05-25 14:25:53.160 SingleUserLabApp login:225] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[C 2017-05-25 14:25:53.172 SingleUserLabApp application:90] Bad config encountered during initialization:
[C 2017-05-25 14:25:53.173 SingleUserLabApp application:91] The 'port' trait of a SingleUserLabApp instance must be an int, but a value of None <class 'NoneType'> was specified.
Single-user server for JupyterHub. Extends the Jupyter Notebook server.
```

NB: I'm running JupyterHub master on the Ubuntu JupyterHub server but `0.7.2` on the Windows `DOCKER_HOST`

**Comment by ellisonbg** [comment]
Can you post your config?

**Comment by dhirschfeld** [comment]
I'm starting the app with:
```
jupyter labhub --NotebookApp.ip=$env:COMPUTERNAME --NotebookApp.base_url=$env:JPY_BASE_URL --KernelSpecManager.ensure_native_kernel=False --NotebookApp.allow_origin=* --NotebookApp.open_browser=False --NotebookApp.token='' --NotebookApp.password=''
```
I'm having issues copying from my VM but the rest of the config looks like:
![image](https://cloud.githubusercontent.com/assets/881019/26436868/fafa7ec8-415c-11e7-9ded-1f242ddc09d5.png)

The same config works correctly when `labhub` is substituted with `notebook`

**Comment by dhirschfeld** [comment]
As another data point starting the app with `jupyter lab ...` also works

**Comment by ellisonbg** [comment]
The singleuser and labhub subclasses of `NotebookApp` make some properties non-configurable:

https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/singleuser.py#L248

This includes `open_browser` and `token`. I would remove those from your config (probably password as well). And you will also need to pass the port.

**Comment by minrk** [comment]
Can you show the command-line and environment variables that the container attempts to launch with?

**Comment by dhirschfeld** [comment]
I tried `labhub` with the below command:
```
jupyter labhub --NotebookApp.port=8888 --NotebookApp.ip=$env:COMPUTERNAME --NotebookApp.base_url=$env:JPY_BASE_URL --KernelSpecManager.ensure_native_kernel=False --NotebookApp.allow_origin=*;
```
...but JupyterHub then sends me into an endless redirect loop:
![image](https://cloud.githubusercontent.com/assets/881019/26477401/ceafc682-4208-11e7-9415-ce1f6c3d8d4e.png)

To try and make sure it wasn't a separate issue I tried the same twice from an incognito window after deleting the cookie secret, and restartig JupyterHub with the same result: endless redirect loop.

**Comment by dhirschfeld** [comment]
Reverting to the previous command gets rid of the redirect loop so it looks like there's some issue with `jupyterlab-hub`... or at least my installation of it :/
```
jupyter lab --NotebookApp.port=8888 --NotebookApp.ip=$env:COMPUTERNAME --NotebookApp.base_url=$env:JPY_BASE_URL --KernelSpecManager.ensure_native_kernel=False --NotebookApp.allow_origin=* --NotebookApp.open_browser=False --NotebookApp.token='' --NotebookApp.password='';
```

**Comment by dhirschfeld** [comment]
Is the some way to completely nuke the existing `jupyterlab-hub` installation so I can try again (and record the build output)?

**Comment by Analect** [comment]
@dhirschfeld 

For what it's worth, I managed to get things working with jupyerlab 0.22.1 and the labhub extension.  I generate a docker image for running on the hub that installs, among other things, jupyterhub 0.72 and jupyerlab 0.22.1 (using conda-forge) and the labhub extension.

This is the command for starting a notebook server instance that I include at the end of the image.  Some of those parameters may be overkill ... so perhaps `--SingleUserNotebookApp.default_url=/lab` is no longer needed ... and I had just added things like `--allow-root` as I was experimenting with something ... but these additional parameters don't seem to affect it working.  I'm running the hub on kubernetes ... so the various hub* parameters may not apply in your instance.

```
CMD jupyter labhub \
  --allow-root \
  --port=8888 \
  --ip=0.0.0.0 \
  --user="$JPY_USER" \
  --cookie-name=$JPY_COOKIE_NAME \
  --base-url=$JPY_BASE_URL \
  --hub-prefix=$JPY_HUB_PREFIX \
  --hub-api-url=$JPY_HUB_API_URL \
  --HubAuth.api_token=$JPY_API_TOKEN \
  --notebook-dir="/home/jovyan/work" \
  --SingleUserNotebookApp.default_url=/lab
```

This compares to your command, as per the thread above.
```
jupyter labhub 
--NotebookApp.port=8888 
--NotebookApp.ip=$env:COMPUTERNAME 
--NotebookApp.base_url=$env:JPY_BASE_URL 
--KernelSpecManager.ensure_native_kernel=False 
--NotebookApp.allow_origin=*
```

By the way, I too am seeing `Welcome to webpack.config.js (v0.22.1)` in the about page, as per https://github.com/jupyterlab/jupyterlab/issues/2272 ... but it doesn't seem to be affecting things working.

**Comment by dhirschfeld** [comment]
Thanks @Analect - I'll try playing around with the parameters - the `--SingleUserNotebookApp.default_url=/lab` seems a likely candidate!

**Comment by dhirschfeld** [comment]
...unfortunately, no joy with using `--SingleUserNotebookApp.default_url=/lab` it still endlessly redirects :/

**Comment by willingc** [comment]
@dhirschfeld What version of dockerspawner are you using? [ref](https://github.com/jupyterhub/jupyterhub-deploy-docker/issues/34#issuecomment-305767760)

**Comment by willingc** [comment]
Hi @dhirschfeld,

I'm doing some triaging of open issues.  I am going to go ahead and close this issue since it's been open for a while. If the reference did not resolve your issue, I'm happy to reopen this issue and continue helping with troubleshooting.

FYI, we have recently put together some documentation about deploying JupyterHub with Kubernetes which others have found helpful: https://zero-to-jupyterhub.readthedocs.io/en/latest/

Thanks! :sunny:
