### ISSUE TITLE
npm local install suggestion

### ISSUE THREAD

**Issue by adrinjalali** [jupyterhub/jupyterhub#1155]
Hi,

This is not a bug, it's a suggestion for occasional python users like me, who are not familiar with node.js and npm related commands.

Every single time when I start a new virtualenv, and install jupyterhub, runnung `jupyterhub` tells me: 

    Failed to find proxy ['configurable-http-proxy']
    The proxy can be installed with `npm install -g configurable-http-proxy`
 
Which is fair enough, except since many of us, non node.js users, don't have a local copy of node in our environment, and npm is installed globally. This means running `npm install -g configurable-http-proxy` returns errors complaining about file/folder access permissions, which is again, fair enough since the npm is installed globally.

This means every time I need to search for the error online, and try to fix it somehow. After a few times doing it, it's not too hard to find the answer, but still annoying, since what I really expect, is to install my python package (jupyterhub in this case) and use it. And I'm certain many other users encounter the same problem.

So my suggestion is to include something along the lines:

    You need to set these two environment variables to install npm packages locally:
    $ PATH="$HOME/.node_modules/bin:$PATH"
    $ export npm_config_prefix=~/.node_modules

Thanks for the greate work BTW.

**Comment by willingc** [comment]
@adrinjalali Thanks for the suggestion. We'll see what we can do to make this more helpful. Thanks for the kind words too.

**Comment by minrk** [comment]
Like Python, there are a dozen different ways to install npm packages, with different permissions requirements.

We can link to [npm's own docs](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory) on this topic, which include something similar to the above.

**Comment by adrinjalali** [comment]
That would help, since for a non-npm user finding that page is not trivial.

**Comment by minrk** [comment]
it certainly is!

**Comment by willingc** [comment]
@minrk @adrinjalali Would you prefer updating the message or docs?

**Comment by adrinjalali** [comment]
I'd update the message if I had to choose.

**Comment by willingc** [comment]
Next action: Update the message when displayed when node is not installed.
