### ISSUE TITLE
Support JWT based authentication for JupyterHub

### ISSUE THREAD

**Issue by mogthesprog** [jupyterhub/jupyterhub#1174]
Hey guys.

I'm interested in getting your thoughts on support JWT/Token authentication for juptyerhub? This would allow us to stand jupyterhub up in an env where there are either no local users, or no ldap based auth and have proper authentication. One option is to support OAuth, but this would be simple and some other OAuth tool could be used... 

To give this a bit of context. Internally we have an authenticating Gateway (soon to be open sourced) which supports JWT forwarding as an `Authorization: bearer <token>` header. Then jupyterhub would be configured to take in the JWT and the public key of a singing certificate (likely dot delimited base64), decode it, and verify the signature on the token, before un-marshalling claims (upn, role, groups, email etc..). These claims can then be used as necessary by the app (i think only upn is necessary in the case of jupyterhub, but down the line RBAC in jhub would be easier to implement.

For deployments to environments where the use of AD or PAM isn't ideal (i.e. a single tenant cloud environment, or a kubernetes cluster, for instance), this would be really helpful.

**Comment by minrk** [comment]
JupyterHub should be able to support just about any authentication scheme via a custom Authenticator. PAM's just the default. Any other authentication scheme is provided by external packages. There are [several already](https://github.com/jupyterhub/jupyterhub/wiki/Authenticators). OAuth is commonly used with JupyterHub via [oauthenticator](http://github.com/jupyterhub/oauthenticator). A JWTAuthenticator should be doable, as well. The mediawiki OAuthenticator uses jwt tokens internally. Check out [the docs](http://jupyterhub.readthedocs.io/en/latest/authenticators.html) on writing a custom Authenticator, and feel free to ask questions here if you need a hand figuring it out.

**Comment by mogthesprog** [comment]
@minrk 

lightning response as usual ;)

So i've had a bash at an initial implementation (untested as yet). Will get around to testing it tomorrow. You can find it [here](https://github.com/mogthesprog/jwtauthenticator/tree/morganj/initiail-implementation). I've never published a package before (bit new to this). I used yuvipandas oauthenticator and the RemoteUserAuthenticators as a starting point... hopefully i've not too far off. 

Will keep you posted

**Comment by minrk** [comment]
cool!

**Comment by mogthesprog** [comment]
I do have a question around user provisioning. With the Remote_User example, if the local user in the linux box doesn't exist, will it be created? That's the behaviour i'm looking to have with the jwt authenticator, if possible.

**Comment by minrk** [comment]
That's a feature of LocalAuthenticator. If you set:

    c.LocalAuthenticator.create_system_users = True

then users that don't exist will be created on successful authentication.

**Comment by mogthesprog** [comment]
So I've got this all working. Currently working on adding tests but it seems to do exactly what I want. Thanks for your help! Is it worth adding a link to the authenticator list that you have in the wiki? [code here](https://github.com/mogthesprog/jwtauthenticator/tree/morganj/initiail-implementation).

**Comment by minrk** [comment]
Great! Feel free to add a link on the wiki.

**Comment by willingc** [comment]
Thanks for the info @mogthesprog. Please let me know if you have any difficulty adding the link to the wiki. :cake:

**Comment by mogthesprog** [comment]
will definitely do this, just trying to finalise the setup instructions, then i'll add the link :) might take a few days

**Comment by willingc** [comment]
Thanks @mogthesprog :-)

**Comment by mogthesprog** [comment]
All done. Thanks for your help guys :)

**Comment by Jnchi** [comment]
> For deployments to environments where the use of AD or PAM isn't ideal (i.e. a single tenant cloud environment, or a kubernetes cluster, for instance), this would be really helpful.

You should also take a look at some of the different PAM modules out there. The whole purpose of PAM is to allow for customizable authentication flows. For example, one could use [pam_aad](https://github.com/CyberNinjas/pam_aad) to authenticate with Azure Active Directory, or [pam_duo](https://github.com/duosecurity/duo_unix) to authenticate with Duo.

Note: I wrote pam_aad, so I may be a bit biased about using a PAM-based solution.

Resources:

- https://cyberninjas.github.io/aad-for-linux
- https://duo.com/docs/duounix
