### ISSUE TITLE
Make sure pluggable proxy config supports user per-domain

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#1175]
We currently support this, and should continue to in a way that works across implementations!

**Comment by minrk** [comment]
We know it works with CHP, at least, because some of the tests are run in this mode. We can look at it again to see if we should clarify the API, though.

**Comment by yuvipanda** [comment]
Yeah, we should. Right now I see:

```
            routespec (str): A specification for which this route will be matched.
                Could be either a url_prefix or a fqdn.
```

in `add_route`. I think we should explicitly make it a routespec named tuple that has domain and path_prefix parts.

**Comment by minrk** [comment]
Indeed, and the API currently assumes CHP's own spec for this (host as first URL part). #1177 adds the RouteSpec namedtuple, separating the host from path at the API level.
