### ISSUE TITLE
Correct dead links in the doc.

### ISSUE THREAD

**Issue by lncrd** [jupyterhub/jupyterhub#1188]
All of the internal links in [the github doc](https://github.com/jupyterhub/jupyterhub/tree/master/docs/source) are dead. They link to an `.html` file instead of the `.md` file, like [this one](https://github.com/jupyterhub/jupyterhub/blob/master/docs/source/getting-started.html#technical-overview) instead of [that](https://github.com/jupyterhub/jupyterhub/blob/master/docs/source/getting-started.md#technical-overview) on [this page](https://github.com/jupyterhub/jupyterhub/blob/master/docs/source/getting-started.md).

**Comment by prasadkatti** [comment]
I think what you are looking at is the source for this - https://jupyterhub.readthedocs.io/en/latest/

So the links rightly point to the .html files.

**Comment by lncrd** [comment]
Ok, then it was a misunderstanding from me. I thought it was supposed to be usable from Github too.
