### ISSUE TITLE
Jupyterhub Url is not coming up.

### ISSUE THREAD

**Issue by uday2002** [jupyterhub/jupyterhub#1190]
Hi,

We have Jupyterhub installed on one node in our cluster. I have start the Jupyterhub and checked it is up and running. But when I was checking the url it says.

This site can’t be reached

dmzchodswstg01 refused to connect.
Search Google for dmzchodswstg01 hub login
ERR_CONNECTION_REFUSED

Please help how to get this fixed. 

udayn@DMZCHODSWSTG01:~$ sudo service jupyterhub start
jupyterhub start/running, process 21649
udayn@DMZCHODSWSTG01:~$ ps -ef | grep jupyterhub
udayn    21681 21478  0 03:07 pts/0    00:00:00 grep --color=auto jupyterhub

Thanks,
Uday

**Comment by minrk** [comment]
That `ps` output suggests that JupyterHub is not running. How are you startig JupyterHub? Can you check its log output?

**Comment by uday2002** [comment]
Hi Min,

Thanks for looking into this. I have solved this, by restaring the proxy from /opt/anaconda3/bin where Jupyterhub is installed and logged with url : http://localhost:8000.

Thanks,
Uday

**Comment by willingc** [comment]
Closing as resolved. Glad you were able to get it solved @uday2002.
