### ISSUE TITLE
How to Disable terminal

### ISSUE THREAD

**Issue by qinghanmeng** [jupyterhub/jupyterhub#1195]
HI,

I want to know how to disable the terminal.

Thanks

**Comment by willingc** [comment]
Hi @qinghanmeng,

We would like to help you with your question, but I'm not clear on what you wish to do. Can you provide a bit more detail. Thanks!

**Comment by qinghanmeng** [comment]
Users can create  terminals to execute system commands. 

Is there any way I can disable the terminal and hide it ?

![image](https://user-images.githubusercontent.com/1555861/27776161-b626503c-5fda-11e7-8b2d-8b13bf69c146.png)

**Comment by parente** [comment]
@qinghanmeng I don't believe there's an explicit setting to disable the terminal. Even if there was, keep in mind there are many other ways for users to execute system commands through Jupyter:

* A user could open a Python notebook and use the `%%bash` or `!` shell magics.
* A user could open a Python notebook, import subprocess, and execute arbitrary commands.
* A user could open a notebook for pretty much any other language and execute a shell child process (e.g., `s"ls -l" !` in Scala).

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Thanks to all!

**Comment by matteoipri** [comment]
I am also interested in this from a security point of view. @parente is right, there are several ways to do bad things.

I think there should be some listings somewhere on ways to protect the environment from bad guys. Obviously it can not be 100% complete and exhaustive, security is a continuous effort and tradeoffs are to be made. Moreover, every language has its own nuances.
What do you think about it? Is there something like this already that I am missing?

For example, I see that [try.jupyter.org](https://try.jupyter.org/) restricts the user from creating new text files or folders and click on "New > Terminal" does nothing.
Is this documented somewhere?

Thanks :)

**Comment by minrk** [comment]
> For example, I see that try.jupyter.org restricts the user from creating new text files or folders and click on "New > Terminal" does nothing.
Is this documented somewhere?

Where do you see this? I can create new text files and terminals on try.jupyter.org. These features shouldn't be disabled there, and can't be to my knowledge.

Running a shell provides no additional security vulnerability to running a Jupyter notebook with an IPython kernel, which can do exactly what a shell can do.

Since much of the point of IPython and Jupyter is arbitrary code execution, the security model for deploying Jupyter ought to be applying restrictions at the process/container level, rather than limiting some UI for running commands, but not others.

I believe you can disable terminals by setting the SHELL of the user or process to `/bin/false`, which will prevent any shell from launching, but not remove the UI for *requesting* a shell.

**Comment by matteoipri** [comment]
Thanks, I see your point in putting the security at a lower level than Jupyter.
Anyway I just tried again on https://try.jupyter.org/ and click on New > Terminal does absolutely nothing visible.
Clicking on New > {File, Folder, Notebook} gives me a forbidden error. I attach the screenshots.

![forbidden-file](https://user-images.githubusercontent.com/695348/31968865-d685e9a0-b912-11e7-85ab-ed204482d4ed.png)
![forbidden-folder](https://user-images.githubusercontent.com/695348/31968881-db46236a-b912-11e7-8d4c-0870b7ba07e1.png)
![forbidden-notebook](https://user-images.githubusercontent.com/695348/31968884-ddc868f0-b912-11e7-9a88-c3d9269e6bf6.png)

**Comment by ppLorins** [comment]
I have the same question .

**Comment by lbiemans** [comment]
@ppLorins if you uninstall the terminado package terminals will be disabled.

**Comment by shizl92** [comment]
you can install jupyter notebook in docker container

**Comment by transfluxus** [comment]
That would indeed be a very useful feature, as for the others I see it as a security requirement.
A 1gb container isn't really a useful solution :). 
Issue doesn't seem resolved at all. @willingc

**Comment by lbiemans** [comment]
@transfluxus You can also use systemdspawner and set the shell to e.g. /bin/false terminals are then sort of disabled

**Comment by weisong82** [comment]
#  Terminals may also be automatically disabled if the terminado package is not
#  available.  去掉shell权限
c.NotebookApp.terminals_enabled = False

**Comment by ztd-creator** [comment]
i just open my config and set bool enabled terminal in jupyter
my code jupyter notebook --NotebookApp.terminals_enabled=False

**Comment by HankZMH** [comment]
As @lbieman say, uninstall terminado package will disable terminal. Just run
``pip uninstall -y terminal`

**Comment by Bon-jour** [comment]
pip uninstall -y terminado   is valid
