### ISSUE TITLE
JupyterHub Kerberos

### ISSUE THREAD

**Issue by Nocturnal316** [jupyterhub/jupyterhub#1197]
I'm attempting to kerberize jupyterhub but I'm running into this issue.

[C 2017-06-29 10:41:33.542 JupyterHub application:90] Bad config encountered during initialization:
[C 2017-06-29 10:41:33.544 JupyterHub application:91] The 'authenticator_class' trait of <jupyterhub.app.JupyterHub object at 0x7f89175432e8> instance must be a type, but 'jupyterhub-kdcauthenticator.kdcauthenticator.KDCAuthenticator' could not be imported

I've tried everything except taking all the code from the kdc and pasting it on the config file.... anyone know the soluton to this problem?

**Comment by willingc** [comment]
Hi @Nocturnal316,

Please make sure that you have completed the steps [here]( https://github.com/bloomberg/jupyterhub-kdcauthenticator/blob/master/README.md).  Which versions of JupyterHub and traitlets are you using?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Thanks! 🌻
