### ISSUE TITLE
Failure communicating with the proxy at 100 simultaneous logins

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#1203]
As part of stress-testing our JupyterHub setup, I'm running simple stress test. It tries to start 1000 servers, 100 at a time. The 100 servers, 100 at a time test went great, but after that hub talking to the proxy started breaking down with:

```
[E 2017-07-08 05:03:58.934 JupyterHub concurrent:344] Future <tornado.concurrent.Future object at 0x7f2f881675f8> exception was never retrieved: Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/orm.py", line 201, in add_user
        client=client,
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
```

We should allow and document how people can use pycurl, and also tune timeouts. Both of those should help.

**Comment by yuvipanda** [comment]
nchp had a 2.6% failure rate at this, chp had a 24% failure rate :D

**Comment by zsluedem** [comment]
what is nchp and chp? just curious...

**Comment by ryanlovett** [comment]
[chp](https://github.com/jupyterhub/configurable-http-proxy) is the default proxy server for JupyterHub, and [nchp](https://github.com/yuvipanda/jupyterhub-nginx-chp) is an alternative based on nginx and lua.

**Comment by zsluedem** [comment]
@ryanlovett thanks a lot!

**Comment by yuvipanda** [comment]
https://github.com/jupyterhub/helm-chart/commit/9f2666b735bcac90033bbf8954e8bfa0ee595eec makes this work with CHP! The test isn't good enough yet, IMO - it needs to actually open a websocket and execute some code (currently it only makes sure that it can get a 200 in `/tree` for the user). The tests have already been useful, however!

**Comment by minrk** [comment]
@yuvipanda I'm a bit baffled at how the proxy implementation could even enter into the failure rate on this, but it's awesome that you are testing this stuff! Where's the test code? I'd love to figure these things out.

We can definitely use pycurl by default if it's installed, that's no problem.

**Comment by minrk** [comment]
Oh, if pycurl fixes it, then it's probably a concurrent connections limit. If CHP fails more, that probably just means it's a bit slower, so there are more concurrent open connections.

**Comment by minrk** [comment]
Found it: https://github.com/yuvipanda/jupyterhub-loadtest cool!

**Comment by yuvipanda** [comment]
Awesome! Going to close this now, since we're doing way more than that now :) There's also https://github.com/jupyterhub/helm-chart/issues/46 with more info.
