### ISSUE TITLE
Memory and CPU limit per user

### ISSUE THREAD

**Issue by nicolairiis** [jupyterhub/jupyterhub#1205]
Hi,

I think a memory limit and CPU limit could be great for the LocalProcessSpawner, since I have been unable to find one that works without docker. (systemd.spawner seem to have an issue with the memory limit)

In addition, these limits could be added as UI feature in the admin control panel for servers that run for a longer period of time and thus need to have their configurations updated periodically.

**Comment by zsluedem** [comment]
why not docker?

**Comment by minrk** [comment]
It's pretty tricky to apply these limits in general, because you need access to things like cgroups or similar. Spawners that expose such APIs (DockerSpawner, SystemdSpawner) expose these limits because the services they wrap have such controls.

**Comment by nicolairiis** [comment]
Just realised there is a SystemUserSpawner for the docker spawner that spawns as system users.

This was my biggest reason for not going the docker way. I will give it a try!

**Comment by willingc** [comment]
Hi @nicolairiis,

Based on @minrk's response, I'm closing this issue. Feel free to reach out here or on Gitter if you have additional questions.
