### ISSUE TITLE
How to create user?

### ISSUE THREAD

**Issue by kiwi0217** [jupyterhub/jupyterhub#1210]
Sorry, i'm a beginner. i installed jupyterhub, and run it successfully. But i can't find the place to creat account in the login interface. And i have read the "Getting started with JupyterHub" but still don't understand how to creat account to login.

**Comment by zsluedem** [comment]
the default authenticator is PAMAuthenticator.
PAMAuthenticator means it uses the account in the linux system.

suposed you have an account in your linux named "Robert", and the password is "123456"
just use the "Robert" for username, and "123456" for password.

in short words, use the account you login in you linux system!!!!

**Comment by minrk** [comment]
JupyterHub doesn't itself allow creation of user accounts. That's generally handled by the outside system that the Hub uses for authentication, such as PAM (system users) or GitHub, etc.

JupyterHub's only sense of users is a *whitelist* of users you want to allow access to your Hub, in case you only want a subset of the users in your authentication service to have access to your Hub (e.g. you don't want to grant all GitHub users access to your Hub). For this, you use the `c.Authenticator.whitelist` configurable in `jupyterhub_config.py`:

    c.Authenticator.whitelist = {'me', 'you', 'other'}

**Comment by willingc** [comment]
Hi @kiwi0217,

I hope @minrk's response helped you. As a beginner, you may find the [Zero to JupyterHub guide](https://zero-to-jupyterhub.readthedocs.io/en/latest/) helpful too.

**Comment by shannonls** [comment]
how about I run jupyterhub in docker caontainners, then what is my pam account?
@zsluedem

**Comment by zsluedem** [comment]
@shannonls I am not sure. It depends on how you build the image. If you use the official docker image, you can check [here](https://github.com/jupyterhub/jupyterhub/blob/master/dockerfiles/Dockerfile.alpine). The user is `nobody`, maybe the password is blank

**Comment by soerendip** [comment]
Where can I find this jupyterhub_config.py file?

**Comment by vKredGod** [comment]
you need to run the command jupyterhub --generate-config

**Comment by Tehami** [comment]
> how about I run jupyterhub in docker caontainners, then what is my pam account?
> @zsluedem

I have the same problem. I want to use Linux users but jupyterhub is running inside a docker container. Can anyone suggest a solution please? thanks

**Comment by stefaneidelloth** [comment]
Open a second console and run
docker container ls
to see the existing containers and their ids. Then run
`docker exec -it $containerid$ bash`
To show a bash console. (First few characters of container id are enough to identify it)
In order to create a new linux user:
```
useradd $username$
passwd $username$
```
Then you will be asked for the password. 
Afterwards you are able to login with the just created login credentials. 

(Spwaning server does not work for me, yet. However, that's another issue.)

**Comment by debajyotin16** [comment]
I am trying to add a new user and a new admin  by `c.Authenticator.allowed_users = {'user1'}` and `c.Authenticator.admin_users = {'user1'}` respectively. I comment out this 2 lines from the `jupyterhub_config.py`file too. But sill I am getting "Invalid username or password ". Regarding the password, I think for the first time "user1" will generate the password. Is it right?
