### ISSUE TITLE
Error messages about managed cull-idle server

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#1215]
Lots of messages in log about 
```
[E 2017-07-14 03:18:49.501 JupyterHub proxy:319] Service <Service(name=cull-idle managed)> has no server, but wasn't filtered out.
```

Not sure why - the cull-idle service doesn't make an entry into the proxy...

**Comment by minrk** [comment]
Finally tracked this down. Should have been using `!=` instead of `is not` for filtering out services with no endpoint.
