### ISSUE TITLE
Put a spinner in the 'your server is starting up' page

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#1226]
@choldgraf mentioned this would make things a lot less confusing! Just a simple CSS animator, perhaps with some silly messages.

**Comment by choldgraf** [comment]
+1 !! People like moving things :-)

**Comment by dhirschfeld** [comment]
**xref:** the jupyterlab loader:
https://gitter.im/jupyterlab/jupyterlab?at=595186fe3230e14f3afa220d

**Comment by choldgraf** [comment]
very pretty!
