### ISSUE TITLE
When to drop Python 3.3 support

### ISSUE THREAD

**Issue by willingc** [jupyterhub/jupyterhub#1229]
Initially released in 2012, Python 3.3 reaches EOL on 09-29-2017.

[python-dev mailing list reference](https://mail.python.org/pipermail/python-dev/2017-July/148584.html)

I would recommend officially dropping Python 3.3 support for installation in JupyterHub 0.8.

**Comment by yuvipanda** [comment]
+1!

**Comment by minrk** [comment]
Dropping for 0.8 sounds great
