### ISSUE TITLE
Problems runin Jupyterhub

### ISSUE THREAD

**Issue by NervenCid** [jupyterhub/jupyterhub#1230]
Hello:

I installed Jupyterhub as showed here:

https://jupyterhub.readthedocs.io/en/latest/quickstart.html

My system configuration is:

OS: Windows 10
Python: 3.6
Installation via: pip

When i run the command:

jupyterhub

I got:

"jupyterhub" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

(It isn't recoignicing jupyterhub)

The script file was created but no as .py file...

Thank you

**Comment by minrk** [comment]
JupyterHub does not support Windows. You will need to run JupyterHub on a Linux server, Docker container, or Virtual Machine.
