### ISSUE TITLE
mysql performance

### ISSUE THREAD

**Issue by zsluedem** [jupyterhub/jupyterhub#1233]
If i use mysql as my database, the performance would be very slow.
Because of Tornado Framework, i suppose ever operation on the database would block if i use mysql. That's really slow.
Am i right about it ?
If yes, how would i improve the performance

**Comment by minrk** [comment]
The Hub itself does very little. It's only involved in the initial login, and then the Hub and its db do not participate after that, so a relatively slow db shouldn't be a big issue. Where are you seeing significant slow performance?

**Comment by zsluedem** [comment]
@minrk yeah.It happened in the initial login.I waited for about 3-5 seconds. After the login ,it works fine.

**Comment by zsluedem** [comment]
But when multiple users try to  login, the performance problem seems more severe. Because I deploy my jupyter in a cluster. Is there a better performance solutions for multiple jupyterhub using the same database to share state?

**Comment by minrk** [comment]
When users login, it also triggers spawning of their server. This is typically the slow part, and is asynchronous, so doesn't slow down much when you have several users doing it at once (unless it's *a lot* of users logging in at once). How long do you see login taking if your server is already running (login, start your server, logout, log back in)?

**Comment by zsluedem** [comment]
I am going to close it now, It is not the mysql performance . It really doesn't take lone
