### ISSUE TITLE
Where to put the py file to override authentication function

### ISSUE THREAD

**Issue by lesiano** [jupyterhub/jupyterhub#1237]
Hi,

I'm trying to override the authentication function, creating my own authentication function. I'm trying to check where to put the file but don't see it. Can someone help me?

What I want to do is connect to jupyer notebook without any login. For example go directly to the page
https://10.x.y.r.t/user/user1/notebooks/Untitled.ipynb without enter any username and password. 
Btw... is that possible? :)

Thanks.

**Comment by minrk** [comment]
You can use [tmpauthenticator](https://github.com/jupyterhub/tmpauthenticator) to allow anonymous login. You would set this in your `jupyterhub_config.py`.

**Comment by willingc** [comment]
Hi @lesiano, I'm going to close this issue as resolved. If you have any questions about installing tmpauthenticator, please ask us on the Gitter channel. Thanks!
