### ISSUE TITLE
Sharing notebooks in JupyterHub

### ISSUE THREAD

**Issue by rs2** [jupyterhub/jupyterhub#1238]
<sub>A workflow question, please feel free to close/move to Google groups/gitter</sub>

### TL;DR
I'm looking for a workflow where master copies of notebooks can be shared. Should I be looking into `JupyterHub`, `tmpnb`, or, perhaps, another tool?

### Details

1. A user opens a page with a list of notebooks.
1. The user clicks on a notebook of interest.
1. The user gets a new kernel running a copy of that notebook.
1. The user is not able to mutate the state of the master copy of that notebook. If he/she wants to save a copy then he/she can download that notebook.

**Comment by ryanlovett** [comment]
Some relevant projects:

- [HubShare](https://github.com/jupyterhub/hubshare) (not functional yet)
- [nbgrader](https://github.com/jupyter/nbgrader)
- [nbpuller](https://github.com/data-8/nbpuller) (notebook list and notebooks are not part of hub)

**Comment by willingc** [comment]
Thanks @ryanlovett for sharing these links. @rs2, I'm going to close this issue. Please feel free to follow development on HubShare or ask questions on our gitter channel. Thanks!
