### ISSUE TITLE
create server for new users

### ISSUE THREAD

**Issue by lesiano** [jupyterhub/jupyterhub#1247]
Hi,

Sorry to bore you guys again!

I'm trying to create new users via REST API and after that they will be able to connect to Jupyterhub,

The problem is that I'm able to create a new user, but then when I access with the new username I receive a 500 error.

My jupyert_config.py is:

> c.JupyterHub.tornado_settings = {
>     'headers': {
>         'Content-Security-Policy': "frame-ancestors *"
>   }
> }
> c.JupyterHub.authenticator_class = 'dummyauthenticator.DummyAuthenticator'
> from IPython.utils.localinterfaces import public_ips
> c.JupyterHub.hub_ip = public_ips()[0]
> c.Authenticator.admin_users = {'user'}
> c.JupyterHub.api_tokens = {
> 'aeb48889c93645b4b6d64f0ee5fad5e4' : 'user',
> }
> c.JupyterHub.allow_named_servers = True
> c.LocalAuthenticator.create_system_users = True
> 

The error I receive is:

> [E 2017-07-21 09:58:21.399 JupyterHub user:251] Unhandled error starting user1's server: 'getpwnam(): name not found: user1'
> [E 2017-07-21 09:58:21.562 JupyterHub web:1548] Uncaught exception POST /hub/login?next= (::ffff:213.127.105.131)
>     HTTPServerRequest(protocol='http', host='104.40.154.246:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::ffff:213.127.105.131', headers={'Cookie': '_xsrf=2|8a5948c7|fdf75f790af2102633fc4ee203baa4a5|1499939213; username-104-40-154-246-8888="2|1:0|10:1500542173|28:username-104-40-154-246-8888|44:OWI5YmYxNzNjZDBlNDgxYWJkZDBhYWYxMGNjZTEyY2M=|660b8cc80ea6178520ce9b2941b0f4a5c69cef7b537415be860d2f1670886def"', 'Origin': 'http://104.40.154.246:8000', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'pt-PT,pt;q=0.8,en-US;q=0.6,en;q=0.4', 'Upgrade-Insecure-Requests': '1', 'X-Forwarded-Host': '104.40.154.246:8000', 'X-Forwarded-For': '::ffff:213.127.105.131', 'Host': '104.40.154.246:8000', 'X-Forwarded-Port': '8000', 'X-Forwarded-Proto': 'http', 'Referer': 'http://104.40.154.246:8000/hub/login', 'Content-Length': '26', 'Connection': 'close', 'Cache-Control': 'max-age=0'})
>     Traceback (most recent call last):
>       File "/opt/conda/lib/python3.5/site-packages/tornado/web.py", line 1469, in _execute
>         result = yield result
>       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 84, in post
>         yield self.spawn_single_user(user)
>       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 328, in spawn_single_user
>         yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
>       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 261, in spawn
>         raise e
>       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 229, in spawn
>         ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
>       File "/opt/conda/lib/python3.5/types.py", line 243, in wrapped
>         coro = func(*args, **kwargs)
>       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/spawner.py", line 778, in start
>         env = self.get_env()
>       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/spawner.py", line 770, in get_env
>         env = self.user_env(env)
>       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/spawner.py", line 757, in user_env
>         home = pwd.getpwnam(self.user.name).pw_dir
>     KeyError: 'getpwnam(): name not found: user1j'

I'm using the "DummyAuthenticator" that allow the user access to jupyterhub without password. 

Is there something more I have to add to the config file for when I create a new user it also create the server? If I run this command in the server it start to work: "sudo useradd user1" but I want that it do it automatically.

Thanks

**Comment by minrk** [comment]
I think DummyAuthenticator doesn't create users on your system. With DummyAuthenticator, you generally want to use a Spawner that doesn't map onto system users, such as DockerSpawner.

Alternatively, you can make a LocalUser version of DummyAuthenticator:

```python
from dummyauthenticator import DummyAuthenticator
from jupyterhub.auth import LocalAuthenticator

class LocalDummyAuthenticator(DummyAuthenticator, LocalAuthenticator):
    pass

c.JupyterHub.authenticator_class = LocalDummyAuthenticator
```

and then it should create local users.

**Comment by lesiano** [comment]
Hi Minrk,
Thanks for the answer. Where I put this code? in the jupyter_config.py file?

**Comment by minrk** [comment]
Yes, in your `jupyterhub_config.py`.

**Comment by lesiano** [comment]
Hi

> c.JupyterHub.tornado_settings = {
>     'headers': {
>         'Content-Security-Policy': "frame-ancestors *"
>   }
> }
> 
> #c.JupyterHub.authenticator_class = 'dummyauthenticator.DummyAuthenticator'
> #c.JupyterHub.authenticator_class = 'tmpauthenticator.TmpAuthenticator'
> 
> from IPython.utils.localinterfaces import public_ips
> c.JupyterHub.hub_ip = public_ips()[0]
> 
> c.Authenticator.admin_users = {'user'}
> 
> c.JupyterHub.api_tokens = {
> 
> 'aeb48889c93645b4b6d64f0ee5fad5e4' : 'user',
> }
> 
> c.JupyterHub.allow_named_servers = True
> 
> c.LocalAuthenticator.create_system_users = True
> 
> 
> from dummyauthenticator import DummyAuthenticator
> from jupyterhub.auth import LocalAuthenticator
> 
> class LocalDummyAuthenticator(DummyAuthenticator, LocalAuthenticator):
>     pass
> 
> c.JupyterHub.authenticator_class = LocalDummyAuthenticator
> 

This is what I have in the jupyterhub_config.py, and its still giving the same error :(

**Comment by minrk** [comment]
Sorry, subtleties of multiple inheritance. I think it needs to be:

```python
class LocalDummyAuthenticator(LocalAuthenticator, DummyAuthenticator):
    pass
```

(Local first)

And if you see an error again, can you include the full log output of `jupyterhub --debug`, up to the error?

**Comment by lesiano** [comment]
Hi Minrk,

Thanks for helping me.

still the same problem. Config file:

> c.JupyterHub.tornado_settings = {
>     'headers': {
>         'Content-Security-Policy': "frame-ancestors *"
>   }
> }
> 
> #c.JupyterHub.authenticator_class = 'dummyauthenticator.DummyAuthenticator'
> #c.JupyterHub.authenticator_class = 'tmpauthenticator.TmpAuthenticator'
> 
> from IPython.utils.localinterfaces import public_ips
> c.JupyterHub.hub_ip = public_ips()[0]
> 
> c.Authenticator.admin_users = {'user'}
> 
> c.JupyterHub.api_tokens = {
> 
> 'aeb48889c93645b4b6d64f0ee5fad5e4' : 'user',
> }
> 
> c.JupyterHub.allow_named_servers = True
> 
> c.LocalAuthenticator.create_system_users = True
> 
> 
> from dummyauthenticator import DummyAuthenticator
> from jupyterhub.auth import LocalAuthenticator
> 
> class LocalDummyAuthenticator(LocalAuthenticator, DummyAuthenticator):
>     pass
> 
> c.JupyterHub.authenticator_class = LocalDummyAuthenticator
> 

output error:

> [D 2017-07-21 13:40:03.420 JupyterHub application:550] Looking for jupyterhub_config in None
> /opt/conda/lib/python3.5/site-packages/IPython/utils/localinterfaces.py:3: UserWarning: IPython.utils.localinterfaces has moved to jupyter_client.localinterfaces
>   warn("IPython.utils.localinterfaces has moved to jupyter_client.localinterfaces")
> [D 2017-07-21 13:40:04.637 JupyterHub application:572] Loaded config file: /etc/jupyterhub/jupyterhub_config.py
> [W 2017-07-21 13:40:04.646 JupyterHub configurable:168] Config option `allow_named_servers` not recognized by `JupyterHub`.
> [W 2017-07-21 13:40:04.646 JupyterHub app:428] JupyterHub.api_tokens is pending deprecation.  Consider using JupyterHub.service_tokens.  If you have a use case for services that identify as users, let us know: https://github.com/jupyterhub/jupyterhub/issues
> [I 2017-07-21 13:40:04.647 JupyterHub app:724] Loading cookie_secret from /etc/jupyterhub/jupyterhub_cookie_secret
> [D 2017-07-21 13:40:04.648 JupyterHub app:796] Connecting to db: sqlite:///jupyterhub.sqlite
> [W 2017-07-21 13:40:04.716 JupyterHub app:365]
>     Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
>     Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
> 
> [I 2017-07-21 13:40:04.730 JupyterHub app:892] Not using whitelist. Any authenticated user will be allowed.
> [I 2017-07-21 13:40:04.738 JupyterHub auth:424] Creating user: adduser -q --gecos '""' --disabled-password user1
> [E 2017-07-21 13:40:04.745 JupyterHub app:916] Error adding user 'user1' already in db
>     Traceback (most recent call last):
>       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/app.py", line 911, in init_users
>         yield gen.maybe_future(self.authenticator.add_user(user))
>       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/auth.py", line 401, in add_user
>         yield gen.maybe_future(self.add_system_user(user))
>       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/auth.py", line 429, in add_system_user
>         raise RuntimeError("Failed to create system user %s: %s" % (name, err))
>     RuntimeError: Failed to create system user robertj: adduser: invalid option -- 'q'
>     Usage: adduser [options] LOGIN
>            adduser -D
>            adduser -D [options]
> 
>     Options:
>       -b, --base-dir BASE_DIR       base directory for the home directory of the
>                                     new account
>       -c, --comment COMMENT         GECOS field of the new account
>       -d, --home-dir HOME_DIR       home directory of the new account
>       -D, --defaults                print or change default useradd configuration
>       -e, --expiredate EXPIRE_DATE  expiration date of the new account
>       -f, --inactive INACTIVE       password inactivity period of the new account
>       -g, --gid GROUP               name or ID of the primary group of the new
>                                     account
>       -G, --groups GROUPS           list of supplementary groups of the new
>                                     account
>       -h, --help                    display this help message and exit
>       -k, --skel SKEL_DIR           use this alternative skeleton directory
>       -K, --key KEY=VALUE           override /etc/login.defs defaults
>       -l, --no-log-init             do not add the user to the lastlog and
>                                     faillog databases
>       -m, --create-home             create the user's home directory
>       -M, --no-create-home          do not create the user's home directory
>       -N, --no-user-group           do not create a group with the same name as
>                                     the user
>       -o, --non-unique              allow to create users with duplicate
>                                     (non-unique) UID
>       -p, --password PASSWORD       encrypted password of the new account
>       -r, --system                  create a system account
>       -R, --root CHROOT_DIR         directory to chroot into
>       -s, --shell SHELL             login shell of the new account
>       -u, --uid UID                 user ID of the new account
>       -U, --user-group              create a group with the same name as the user
>       -Z, --selinux-user SEUSER     use a specific SEUSER for the SELinux user mapping
> 
> 
> 
> [D 2017-07-21 13:40:04.772 JupyterHub app:983] Not duplicating token <APIToken('aeb4...', user='user')>
> [D 2017-07-21 13:40:04.791 JupyterHub app:1085] Loading state for user from db
> [D 2017-07-21 13:40:04.791 JupyterHub app:1097] user not running.
> [D 2017-07-21 13:40:04.799 JupyterHub app:1085] Loading state for user1from db
> [D 2017-07-21 13:40:04.800 JupyterHub app:1097] user1 not running.
> [D 2017-07-21 13:40:04.806 JupyterHub app:1102] Loaded users:
>        user admin
>      user1
>   [E 2017-07-21 13:40:04.823 JupyterHub app:1450] Failed to bind hub to http://10.0.1.4:8081/hub/
> [E 2017-07-21 13:40:04.823 JupyterHub app:1527]
>     Traceback (most recent call last):
>       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/app.py", line 1525, in launch_instance_async
>         yield self.start()
>       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/app.py", line 1448, in start
>         self.http_server.listen(self.hub_port, address=self.hub_ip)
>       File "/opt/conda/lib/python3.5/site-packages/tornado/tcpserver.py", line 126, in listen
>         sockets = bind_sockets(port, address=address)
>       File "/opt/conda/lib/python3.5/site-packages/tornado/netutil.py", line 194, in bind_sockets
>         sock.bind(sockaddr)
>     OSError: [Errno 98] Address already in use

Thanks

**Comment by lesiano** [comment]
Hi @minrk ,

Good morning. :)

Any thoughts about this? :)

Thanks!!

**Comment by willingc** [comment]
Hi @lesiano,

When you start JupyterHub, make sure that there are no other stale `jupyterhub` or `configurable-http-proxy` processes running.

Which version of jupyterhub and configurable-http-proxy are you running?
```
jupyterhub --version
configurable-http-proxy --version
```

**Comment by lesiano** [comment]
Hi @willingc 

Thanks for helping me.

I'm using 0.7.2 jupyterhub version and 2.0.4 configurable-http-proxy version.

Best regards.

**Comment by lesiano** [comment]
Hi @willingc 

Do I need to update something? :)
Thanks

Best regards

**Comment by willingc** [comment]
@lesiano Those versions should be fine.

Before you launch `jupyterhub`, make sure that there are no stale processes of the configurable-http-proxy running. `ps -ax | grep configurable-http-proxy` will let you know. If there are stale processes you will need to remove them.

Can you post the contents of `jupyterhub_config.py`? [Note: putting text output between "```" triple backticks will render the contents nicely here. Please avoid using ">". Thanks.]

Then run `jupyterhub` using `--debug` option and post the output here.

**Comment by lesiano** [comment]
Hi @willingc 

Yes, there is no processes running. 
Sorry for the quote.
My jupyterhub_config.py file is:
```
c.JupyterHub.tornado_settings = {
    'headers': {
        'Content-Security-Policy': "frame-ancestors *"
  }
}

#c.JupyterHub.authenticator_class = 'dummyauthenticator.DummyAuthenticator'
#c.JupyterHub.authenticator_class = 'tmpauthenticator.TmpAuthenticator'

from IPython.utils.localinterfaces import public_ips
c.JupyterHub.hub_ip = public_ips()[0]
c.Authenticator.admin_users = {'user'}
c.JupyterHub.api_tokens = {

'aeb48889c93645b4b6d64f0ee5fad5e4' : 'user',
}
c.JupyterHub.allow_named_servers = True
c.LocalAuthenticator.create_system_users = True
from dummyauthenticator import DummyAuthenticator
from jupyterhub.auth import LocalAuthenticator

class LocalDummyAuthenticator(LocalAuthenticator, DummyAuthenticator):
    pass

c.JupyterHub.authenticator_class = LocalDummyAuthenticator

```
The output created is:

```
[D 2017-07-27 07:05:34.095 JupyterHub application:550] Looking for /etc/jupyterhub/jupyterhub_config in None
/opt/conda/lib/python3.5/site-packages/IPython/utils/localinterfaces.py:3: UserWarning: IPython.utils.localinterfaces has moved to jupyter_client.localinterfaces
  warn("IPython.utils.localinterfaces has moved to jupyter_client.localinterfaces")
[D 2017-07-27 07:05:35.249 JupyterHub application:572] Loaded config file: /etc/jupyterhub/jupyterhub_config.py
[W 2017-07-27 07:05:35.259 JupyterHub configurable:168] Config option `allow_named_servers` not recognized by `JupyterHub`.
[W 2017-07-27 07:05:35.260 JupyterHub app:428] JupyterHub.api_tokens is pending deprecation.  Consider using JupyterHub.service_tokens.  If you have a use case for services that identify as users, let us know: https://github.com/jupyterhub/jupyterhub/issues
[I 2017-07-27 07:05:35.261 JupyterHub app:724] Loading cookie_secret from /etc/jupyterhub/jupyterhub_cookie_secret
[D 2017-07-27 07:05:35.261 JupyterHub app:796] Connecting to db: sqlite:///jupyterhub.sqlite
[W 2017-07-27 07:05:35.331 JupyterHub app:365]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[I 2017-07-27 07:05:35.345 JupyterHub app:892] Not using whitelist. Any authenticated user will be allowed.
[I 2017-07-27 07:05:35.353 JupyterHub auth:424] Creating user: adduser -q --gecos '""' --disabled-password user1
[E 2017-07-27 07:05:35.362 JupyterHub app:916] Error adding user 'user1' already in db
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/app.py", line 911, in init_users
        yield gen.maybe_future(self.authenticator.add_user(user))
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/auth.py", line 401, in add_user
        yield gen.maybe_future(self.add_system_user(user))
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/auth.py", line 429, in add_system_user
        raise RuntimeError("Failed to create system user %s: %s" % (name, err))
    RuntimeError: Failed to create system user robertj: adduser: invalid option -- 'q'
    Usage: adduser [options] LOGIN
           adduser -D
           adduser -D [options]

    Options:
      -b, --base-dir BASE_DIR       base directory for the home directory of the
                                    new account
      -c, --comment COMMENT         GECOS field of the new account
      -d, --home-dir HOME_DIR       home directory of the new account
      -D, --defaults                print or change default useradd configuration
      -e, --expiredate EXPIRE_DATE  expiration date of the new account
      -f, --inactive INACTIVE       password inactivity period of the new account
      -g, --gid GROUP               name or ID of the primary group of the new
                                    account
      -G, --groups GROUPS           list of supplementary groups of the new
                                    account
      -h, --help                    display this help message and exit
      -k, --skel SKEL_DIR           use this alternative skeleton directory
      -K, --key KEY=VALUE           override /etc/login.defs defaults
      -l, --no-log-init             do not add the user to the lastlog and
                                    faillog databases
      -m, --create-home             create the user's home directory
      -M, --no-create-home          do not create the user's home directory
      -N, --no-user-group           do not create a group with the same name as
                                    the user
      -o, --non-unique              allow to create users with duplicate
                                    (non-unique) UID
      -p, --password PASSWORD       encrypted password of the new account
      -r, --system                  create a system account
      -R, --root CHROOT_DIR         directory to chroot into
      -s, --shell SHELL             login shell of the new account
      -u, --uid UID                 user ID of the new account
      -U, --user-group              create a group with the same name as the user
      -Z, --selinux-user SEUSER     use a specific SEUSER for the SELinux user mapping



[D 2017-07-27 07:05:35.388 JupyterHub app:983] Not duplicating token <APIToken('aeb4...', user='user')>
[D 2017-07-27 07:05:35.407 JupyterHub app:1085] Loading state for user from db
[D 2017-07-27 07:05:35.407 JupyterHub app:1097] usernot running.
[D 2017-07-27 07:05:35.413 JupyterHub app:1085] Loading state for user1 from db
[D 2017-07-27 07:05:35.413 JupyterHub app:1097] user1 not running.
[D 2017-07-27 07:05:35.413 JupyterHub app:1102] Loaded users:
       user admin
     user1
[I 2017-07-27 07:05:35.438 JupyterHub app:1453] Hub API listening on http://10.0.1.4:8081/hub/
[W 2017-07-27 07:05:35.446 JupyterHub app:1174] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2017-07-27 07:05:35.448 JupyterHub app:1176] Starting proxy @ http://*:8000/
[D 2017-07-27 07:05:35.448 JupyterHub app:1177] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--default-target', 'http://10.0.1.4:8081', '--error-target', 'http://10.0.1.4:8081/hub/error']
07:05:35.775 - info: [ConfigProxy] Adding route / -> http://10.0.1.4:8081
07:05:35.785 - info: [ConfigProxy] Proxying http://*:8000 to http://10.0.1.4:8081
07:05:35.786 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[D 2017-07-27 07:05:35.859 JupyterHub app:1205] Proxy started and appears to be up
[I 2017-07-27 07:05:35.860 JupyterHub app:1485] JupyterHub is now running at http://127.0.0.1:8000/
```

For the spawer I'm using the SystemUserSpawner. 
Thanks a lot.

**Comment by manics** [comment]
Closing, if you're still having problems please post on the Discourse forum.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/running-dummy-authenticator-on-jupyterhub/10814/1
