### ISSUE TITLE
custom_html for Authenticator is escaped in template

### ISSUE THREAD

**Issue by ihleonard-c3** [jupyterhub/jupyterhub#1252]
Hi,

I'm trying to make a custom login form using `custom_html` on an Authenticator extension, but I can't seem to render an html form as I would like, and instead just get the raw string that I assign to `custom_html`. I think that the problem is that in the `login.html` [template](https://github.com/jupyterhub/jupyterhub/blob/master/share/jupyter/hub/templates/login.html#L11), the `custom_html` is not given a `safe` marker (as it is in, for example, the spawner custom options template). Therefore, whatever string you put in `custom_html` will be escaped and displayed as a raw string, instead of an html form. Please let me know if I'm just doing something incorrectly and/or if there's a workaround available.

Thanks,
Isaiah

**Comment by willingc** [comment]
Hi @ihleonard-c3.

Sorry that we missed responding to this issue. You may wish to take a look at the [work done by others on a custom template](https://github.com/jupyterhub/jupyterhub/issues/1385#issuecomment-326966823)

Closing this issue and recommending future comments/discussion on custom templates to continue on #1385.
