### ISSUE TITLE
Move hash calculations of tokens off to a threadpool

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#1254]
I've been doing lots of performance profiling!

You can see a nice graph here: http://vmprof.com/#/c38b9baf-cc0e-4790-a571-ffdc0e65bf20

This is from a 100 user run. This is a sampling profiler (vmprof), which is different from a deterministic profiler like cProfile. It samples the python stack about 300times / sec (I think) and uses that to build a profile. It's only profiling the main thread, which we should leave unblocked as much as possible.

I'm trying to attack all of the things that block the main thread. Hashing for passwords seems to be at top of the list. There's a related ticket in #1253. But this is different - I wanna move it to a threadpool. My understanding of the GIL is that hashlib will drop the GIL, so moving it to a threadpool will actually help us here.

This is all using an up to date pypy. A flamegraph from cpython based run also showed similar results, however.

**Comment by yuvipanda** [comment]
http://vmprof.com/#/82b60d7d-4bcb-4347-944b-7c59d97cbb7b is another profile, this time with 1000 users. hashlib's update is again the most expensive.

**Comment by yuvipanda** [comment]
I now understand better why we do all the prefix matching stuff. It does become a bit of a linear issue over time tho, even with the prefixes. However, because we are only doing this to UUIDs, it might be possible we can get away with not using a salt and just plain hashing it! See https://security.stackexchange.com/a/151262

**Comment by yuvipanda** [comment]
We got rid of most of this by just hashing the tokens once (see #1258).

**Comment by minrk** [comment]
Since we reduced the hashing of internally-generated tokens, it's probably not worth doing this anymore, since it would significantly increase the time of authenticating every individual request to at least one extra IOLoop tic.

**Comment by willingc** [comment]
@yuvipanda Are you cool with closing this?

**Comment by willingc** [comment]
Closing this. Please reopen if needed. Thanks.

**Comment by yuvipanda** [comment]
Yeah, profiling now shows hashing to be an insignificant part of our cpu time, so this is ok to close :)
