### ISSUE TITLE
Bad link on JupyterHub Code tab

### ISSUE THREAD

**Issue by ssackett** [jupyterhub/jupyterhub#1265]
Hi,

On the Jupyterhub Code tab under the heading Configuration the getting started link is broken.

Steve

**Comment by willingc** [comment]
Hi @ssackett,

I've changed the link in the README to direct correctly to the documentation. Thanks for the report. Just let me know if you see anything else. Thanks :cake:

**Comment by ssackett** [comment]
Carol,

Thanks for the quick work.  I found broken links on other pages but didn't report them mainly because it was shy about posting to the forum.  As near as I remember they all pointed to the repartitioned documentation.  If you step through the pages you should be able to spot them easily.

Steve

**Comment by ssackett** [comment]
Carol,

BTW: The link posted on your GitHub profile to your web site doesn't work.  The link specifies https and there must be something wrong with the certificate.

Steve

**Comment by willingc** [comment]
Thanks @ssackett. Yeah my personal site has to have new cert loaded.

We're refactoring the docs at the moment so I welcome your input on any dead links or other errors. Thanks for helping and contributing. We appreciate it :sunrise:

**Comment by ssackett** [comment]
Carol,

I am writing software for the science team of the InSight Mars mission and find that the functionality of Jupyter and JupyterHub is almost a perfect fit for our purposes.  What I am planning is to design a custom interface that suits our needs and fold in some other functionality to aid data retrieval.

Are you able to give me some advice as to the best approach to accomplish the task?  If so it would save me a lot of work and be very helpful to prevent missteps.  If it is ok I would like to speak to you about the issues I am facing and get your opinion on my ideas.

Thanks,

Steve

**Comment by willingc** [comment]
Hi @ssackett,

Cool application. If you can ask your questions in the [gitter channe](https://gitter.im/jupyterhub/jupyterhub)l for JupyterHub or on the Jupyter mailing list, you will likely get a richer response. I'm more a backend developer, and other team members would be better able to give you guidance on the custom interface. Min and others are super helpful. So are folks on the mailing list. Feel free to mention that I asked you to post your questions there :smile:

**Comment by ssackett** [comment]
Carol,

Thanks, this is a big help.

Steve
