### ISSUE TITLE
Jupyter Hub won't open my notebook in /opt/x/y/z/Welcome.ipynb

### ISSUE THREAD

**Issue by iamjeet** [jupyterhub/jupyterhub#1271]
Hi,

I have tried to configure jupyter hub to open my notebook in a common location ex /tmp/x/y/z/Welcome.ipynb for all users, however, I keep getting 404 error. Also the hub automatically adds /user/user_name even if it's not configured?

-Jeet

**Comment by minrk** [comment]
Can you share your JupyterHub configuration and what you are trying to accomplish?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. If you are still having difficulty, please feel free to request that we reopen this issue. Thanks! 🌻
