### ISSUE TITLE
Allow hub to be listening on a unix domain socket

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#1283]
If there's a frontend proxy (*not* CHP!) doing the http heavy lifting in front of tornado, there's performance to be gained from using a unix domain socket for tornado to listen on rather than a TCP socket - see https://stackoverflow.com/questions/14973942/performance-tcp-loopback-connection-vs-unix-domain-socket.

Right now since we ask for a bind 'IP' and 'port' we can't use a unix domain socket.

**Comment by yuvipanda** [comment]
Not a blocker for 0.8 tho.

**Comment by zsluedem** [comment]
wow~! interesting to know

**Comment by Carreau** [comment]
See #1287, as far as I can tell from "The Internet" http-proxy should "just work" if you pass it a socket instead of `ip:port` though I was unable to.

**Comment by yuvipanda** [comment]
Am going to close this in favor of the more overaching #1289
