### ISSUE TITLE
JupyterHub, PySpark issue

### ISSUE THREAD

**Issue by uditabose** [jupyterhub/jupyterhub#1295]
Hi,
I am running `JupyterHub (0.7.2)`, `Jupyter (4.3.0)`. `Python (3.4)`, `node (v6.9.4)`, `npm (3.10.10)`. I use kinit. My PySpark kernel looks like 
```
{
 "display_name": "PySpark",
 "language": "python",
 "argv": [
  "/bin/python3",
  "-m",
  "ipykernel",
  "-f",
  "{connection_file}"
 ],
 "env": {
  "SPARK_HOME": "/usr/iop/4.2.0.0/spark",
  "PYTHONPATH": "/usr/iop/4.2.0.0/spark/python/:/usr/iop/4.2.0.0/spark/python/lib/py4j-0.9-src.zip",
  "PYTHONSTARTUP": "/usr/iop/4.2.0.0/spark/python/pyspark/shell.py",
  "PYSPARK_PYTHON": "/bin/python3",
  "PYSPARK_SUBMIT_ARGS": "--master yarn --deploy-mode client --executor-memory 512m --num-executors 2 --executor-cores 1 --keytab=<keytab> --principal=<principal> --conf spark.executor.extraClassPath=/var/installers/db2jcc.jar:/var/installers/nosqljson.jar --driver-class-path /var/installers/db2jcc.jar:/var/installers/nosqljson.jar --jars /var/installers/db2jcc.jar:/var/installers/nosqljson.jar pyspark-shell"
 }
}
```

When I run a standalone notebook server, say with user `a500`, it works fine, it can connect to Yarn, and SaprkContext gets initialized. But when I run JupyterHub, user notebook fails to connect to the kernel, with the same user.

In `ps -eaf`, I can see the process creation for single-notebook (hub) server vs stand-alone are practically same - both are like 

```
/bin/python3 -m ipykernel -f /home/users/a500/.local/share/jupyter/runtime/kernel-<string>.json
```
In Chrome inspect tool, I see that the WebSocket to connect to the kernel is failing.
The JupyterHub one throws a **302** error, the socket URL is like - 
```
wss://a1-c972-jupyterhub.tenant.tunnel.whac-r.us/user/a500/api/kernels/2ae7…d19-8a9e-bc6e866cb85f/channels?session_id=510B49F0C1E8446C817FFCD3148BBE78

WebSocket connection to 'wss://a1-c972-jupyterhub.tenant.tunnel.whac-r.us/user/a500/api/kernels/2ae7…d19-8a9e-bc6e866cb85f/channels?session_id=510B49F0C1E8446C817FFCD3148BBE78' failed: Error during WebSocket handshake: Unexpected response code: 302
Kernel.start_channels @ kernel.js:461
```
The stand-alone notebook worked, the URL was - 
```
wss://a1-c972-jupyter.tenant.tunnel.whac-r.us/api/kernels/e2b59611-58d0-4602-bb92-9218641561c7

Session: kernel_created (da3459f1-5ebb-4bdf-bf23-79ec73811531)
main.min.js:23933 Starting WebSockets: wss://a1-c972-jupyter.tenant.tunnel.whac-r.us/api/kernels/e2b59611-58d0-4602-bb92-9218641561c7
```
In JupyterHub debug log I see this error, and nothing else - 

```
[IPKernelApp] WARNING | Unknown error in handling PYTHONSTARTUP file /usr/iop/4.2.0.0/spark/python/pyspark/shell.py:
```
Please suggest some clue where to look further.

**Comment by davidXire** [comment]
Hi, have you tried to define JAVA_HOME in your kernel file ?

**Comment by uditabose** [comment]
JAVA_HOME is defined in environment variables. Weirdly, this issue does not appear in Firefox ESR 52.2.1 (64-bit). I can't find any websocket calls in Firefox, but Chrome shows websocket calls to connect to kernel. 

Is there any difference in how `kernel.js` tries to communicate with back-end based on browser type or version?

Our servers are CentOS 7 and testing on Mac.

**Comment by willingc** [comment]
Just an FYI, there is a beta release of JupyterHub 0.8.0b4 if you would like to see if that resolves the original issue.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
