### ISSUE TITLE
DockerSpawner and DNS server problem

### ISSUE THREAD

**Issue by mikecokina** [jupyterhub/jupyterhub#1304]
Hi,

I am using DockerSpawner with JupyterHub and I am not able to install any other packages inside of docker because DNS server do not responding. If I try ping 8.8.8.8 or any valid IP, everything is going but when I would like to install e.g. pip3 install any-python-package, server cannot be resolved. Also ping by name of domain doesn't work. I don't what's wrong.

Thanks for help.

**Comment by minrk** [comment]
That sounds like the DNS configuration inside the image isn't working. Perhaps you need to specify that configuration explicitly. You can check the documentation for DNS configuration for the linux distro on which your images are based.

**Comment by GeorgianaElena** [comment]
Closing this issue as it hasn't been active for a long time. Please feel free to open a new one if there are other questions/issues :four_leaf_clover: .
