### ISSUE TITLE
SingleUserNotebookApp always uses hub_prefix/login for login URL

### ISSUE THREAD

**Issue by ssanderson** [jupyterhub/jupyterhub#131]
Jupyterhub supports the ability to configure the URL used for login by overriding `Authenticator.login_url`, but `SingleUserNotebookApp` always redirects to `url_path_join(self.hub_prefix, 'login')`, which means that if the user has a running server but loses their cookie for the single user server, they're redirected to a broken or non-existent page.

A simple workaround for this is to redirect /login to Authenticator's overridden login URL, but that's forcing more HTTP requests to happen than are necessary.  The right fix for this is probably to forward `login_url` or somesuch as a parameter on SU server startup.

**Comment by minrk** [comment]
Makes sense. Same probably goes for logout.

**Comment by consideRatio** [comment]
issue triaging: closing as a stale issue that isn't verified to be relevant still
