### ISSUE TITLE
Use of scoped_session instead of plain session

### ISSUE THREAD

**Issue by d21d3q** [jupyterhub/jupyterhub#1315]
Since `jupyterhub` uses only one instance of session [produced by](https://github.com/jupyterhub/jupyterhub/blob/0b34e13dd48bc73c8696eb63cde11b318b8f05a5/jupyterhub/app.py#L883) `scoped_session`, why not to use plain session produced by `session_maker`? 
@zzzeek in [this](https://stackoverflow.com/questions/8674984/sqlalchemytornado-how-to-create-a-scopefunc-for-sqlalchemys-scopedsession/8705676#comment10785115_8674984) comment dissuades using `scoped_session`s if not needed.

**Comment by minrk** [comment]
This was added purely because the JupyterHub tests were running in a different thread and also talking to the database. scoped_session was used to ensure that sessions were thread-local. That was just reverted in #1281, so we no longer need scoped_session.

**Comment by d21d3q** [comment]
That makes sense. (i was thinking about it since yesterday :) )
You were talking to (sqlite) database from other thread with same connection? As far I was reading it is not so safe (with sqilte)
