### ISSUE TITLE
Proper way of installing jupyterhub with system users

### ISSUE THREAD

**Issue by swigicat** [jupyterhub/jupyterhub#1324]
I'm following the guide at https://github.com/jupyterhub/jupyterhub/wiki/Installation-of-Jupyterhub-on-remote-server

I managed to get the hub visible over https with a custom certificate and key, and to log in using a registered system user (i.e. created with adduser), but I'm stuck at actually spawning a notebook.

The issue is that `pip3 install jupyterhub` installs the jupyterhub package inside ~/.local/bin, including jupyterhub-singleuser. This is a problem if I have need to start the notebook with other users - every single user needs execution rights to the directory in which the -singleuser binary is (my home directory), in order to run the notebook. Is this the proper way of installing the hub? Can I install it in another location that is accessible to all users, e.g. /usr/bin ? Is this recommended?

Thanks.

**Comment by minrk** [comment]
How have you installed Python? It is not pip's normal behavior to put executables in ~/.local/bin. In most cases, `pip3 install jupyterhub notebook` with a system-installed Python is enough to do a system-wide install of JupyterHub. But if executables are going in ~, that means that either you have a user-local Python installation or env, or perhaps some non-default pip configuration that is getting picked up that you need to override.

**Comment by swigicat** [comment]
Thanks for the quick reply, indeed that was the issue, python was installed locally. I removed and re-installed it system wide and the spawner appears to be starting. Now I'm facing another problem though, the spawner cannot start the actual server.

The error I'm getting right after I log in:

```
[I 2017-08-10 13:54:25.040 JupyterHub spawner:783] Spawning jupyterhub-singleuser '--user="student"' '--cookie-name="jupyter-hub-token-student"' '--base-url="/user/student"' '--hub-host=""' '--hub-prefix="/hub/"' '--hub-api-url="http://127.0.0.1:8081/hub/api"' '--ip="127.0.0.1"' --port=45459
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/jupyterhub/singleuser.py", line 16, in <module>
    import notebook
  File "/usr/local/lib/python3.5/dist-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 23, in <module>
    from jupyter_core.paths import (
ImportError: No module named 'jupyter_core'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 3, in <module>
    from jupyterhub.singleuser import main
  File "/usr/local/lib/python3.5/dist-packages/jupyterhub/singleuser.py", line 18, in <module>
    raise ImportError("JupyterHub single-user server requires notebook >= 4.0")
ImportError: JupyterHub single-user server requires notebook >= 4.0
[W 2017-08-10 13:54:35.117 JupyterHub web:1587] 500 POST /hub/login?next= (::ffff:127.0.0.1): Spawner failed to start [status=1]
[E 2017-08-10 13:54:35.132 JupyterHub log:99] {
      "Content-Type": "application/x-www-form-urlencoded",
      "Referer": "http://127.0.0.1:8000/hub/login",
      "X-Forwarded-Proto": "http",
      "Cookie": "_xsrf=2|56f836ed|4ce81762e6fae3af257ab02838724b77|1501073611",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Connection": "close",
      "Accept-Encoding": "gzip, deflate",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0",
      "Upgrade-Insecure-Requests": "1",
      "X-Forwarded-Host": "127.0.0.1:8000",
      "X-Forwarded-Port": "8000",
      "Host": "127.0.0.1:8000",
      "Content-Length": "38",
      "X-Forwarded-For": "::ffff:127.0.0.1"
    }
[E 2017-08-10 13:54:35.132 JupyterHub log:100] 500 POST /hub/login?next= (@::ffff:127.0.0.1) 10554.78ms
```

I'm running the hub on my system (not from the docker image), with `sudo jupyterhub`, after generating the default configuration file (no modifications from the defaults). 

I'm able to import the `notebook` and `jupyter_core` packages from python/python3 command line, started with/without `sudo`.

**Comment by kingaj12** [comment]
Did you solve this issue?  I am having the same problem

**Comment by jhermann** [comment]
The recommendation to avoid this and other problems is to use a virtualenv for installation, which makes things much more reproducible / robust against e.g. shell environment changes.
