### ISSUE TITLE
0.8 prerelease

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#1334]
We should probably ship 0.8b1 soon. I think the codebase is ready to go, and we could probably do this today.

Things we should do before a final release, but not necessarily before the beta:

- [x] test lots of new deployments
- [x] release oauthenticator 0.6.1 with better 0.8 support
- [x] build jupyterhub/singleuser images with JupyterHub master in them ([ref](https://github.com/jupyterhub/dockerspawner/pull/179))
- [x] do lots of doc review and improvements (yay @willingc!)
- [x] release DockerSpawner that will pick default images compatible with latest JupyterHub
- [x] highlight-level and comprehensive docs of upgrading from 0.7

Anything people think we should do prior to cutting the beta, other than notifying mailing lists?

cc @yuvipanda @willingc ?

**Comment by willingc** [comment]
Looks good to me. I will create a draft skeleton document about upgrading from 0.7 to 0.8 that others can add to as needed.

Great work @minrk! :ship:

**Comment by minrk** [comment]
I just pushed 0.8.0b1 to PyPI

**Comment by minrk** [comment]
We've gone through 0.8b5 and things are going pretty well! We keep finding little issues, but I think we are in good shape for a release candidate. I think we can do that early next week when the most recent little fixes are merged, focus on upgrade docs for a week or so and then release 0.8 by the end of September.

**Comment by yuvipanda** [comment]
0.8 has been released, so am going to close this one :)

Great work, @minrk, @willingc and others! <3

**Comment by willingc** [comment]
Thanks @yuvipanda. It was an awesome team effort by everyone. Thanks to all in the community who tested the betas and release candidates too. :tada:
