### ISSUE TITLE
What URLs need to be exposed for the singleuser instances

### ISSUE THREAD

**Issue by DeepHorizons** [jupyterhub/jupyterhub#1351]
Hey all. I'm running into a problem with communication between JupyterHub and the singleuser instances. I know the singleuser instance needs access to the hub API, but it seems it cannot communicate with it.

I am trying to run JupyterHub behind a reverse proxy (Apache2) with authentication (Shibboleth). The spawner, however, spawns the singleuser instances on different servers than the hub and needs to talk to it over a public address. If I run an unauthenticated version of the hub, everything works just fine. But if I run it behind the authenticated version the singleuser instance fails to communicate to the hub with the error `...Failed to connect to Hub API...`

The authenticated version allows all access to `/hub/api.*` and I have verified that the servers can access it with `curl` without authentication but I am still getting an error. I do see some requests to `/user/<username>/api` in the log on the singleuser instance, are there any other URLs that need to be excluded from authentication?

**Comment by minrk** [comment]
They should only communicate on `/hub/api`

**Comment by DeepHorizons** [comment]
After further evaluation, it seems it may be a problem with SSL/TLS. If I point the spawner to `http`, I see a 301 in the apache logs, which is expected. Apache is configured to redirect all http traffic to the https interface. But I never see anything after that. And if I point the spawner to `https`, nothing shows up either.

Maybe this is because it is failing the identification of the address? My cert is signed by someone who isn't in the default trusted root certificates. But I added the intermediate cert to the store. Will Jupyter use the system CA store? Or do I need to manually specify that.

**Comment by minrk** [comment]
It's using `requests` right now, so I would expect it would find your system-installed certs.

**Comment by minrk** [comment]
I opened #1353 to avoid hiding the original error when this happens. But if you reach into jupyterhub on the node and modify the same block to raise the original connection error instead, you might get a better hint at what's going wrong.

**Comment by DeepHorizons** [comment]
It does seem to be a certificate issue.
```
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
```

After doing some reading on `requests`, it seems it does not in fact use the system certs.

http://docs.python-requests.org/en/master/user/advanced/#ca-certificates

"By default, Requests bundles a set of root CAs that it trusts, sourced from the Mozilla trust store... From Requests version 2.4.0 onwards, Requests will attempt to use certificates from certifi if it is present on the system..."

So it only uses trusted certs, not any you add. You can apparently use the `verify` argument to pass in a folder to certs to use, but I'm not familiar enough with Jupyterhub to say if this is viable.

**Comment by DeepHorizons** [comment]
It seems a temporary workaround is to set the `REQUESTS_CA_BUNDLE` environmental variable.

https://stackoverflow.com/questions/42982143/python-requests-how-to-use-system-ca-certificates-debian-ubuntu

I'll see if this works when I have some free time

**Comment by DeepHorizons** [comment]
Setting `REQUESTS_CA_BUNDLE` seems to fix my communication problem

**Comment by minrk** [comment]
Cool! I didn't know about that. You should be able to add that to `c.Spawner.environment` to make sure it gets set for your servers.

**Comment by willingc** [comment]
Hi @DeepHorizons, Is this issue resolved or would you like it to remain open? Thanks.

**Comment by DeepHorizons** [comment]
Nope, It's resolved, thanks for the reminder.
