### ISSUE TITLE
orm.User.spawner attribute doesn't exist?

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterhub/jupyterhub#1358]
On master 58751067dbb3c4a0e9726f3e27456b3bfb502b84, I'm seeing the below error immediately after login:
```
   Traceback (most recent call last):
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\web.py", line 1511, in _execute
        result = yield result
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 1055, in run
        value = future.result()
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 1069, in run
        yielded = self.gen.send(value)
      File "c:\dev\src\jupyterhub\jupyterhub\handlers\login.py", line 87, in post
        if user.spawner:
      File "c:\dev\src\jupyterhub\jupyterhub\user.py", line 225, in __getattr__
        raise AttributeError(attr)
    AttributeError: spawner
```
On `user.User` the `spawner` attr is present:
https://github.com/jupyterhub/jupyterhub/blob/58751067dbb3c4a0e9726f3e27456b3bfb502b84/jupyterhub/user.py#L211-L218

..but apparently not the [`orm.User`](https://github.com/jupyterhub/jupyterhub/blob/58751067dbb3c4a0e9726f3e27456b3bfb502b84/jupyterhub/orm.py#L106-L171):
https://github.com/jupyterhub/jupyterhub/blob/58751067dbb3c4a0e9726f3e27456b3bfb502b84/jupyterhub/user.py#L220-L225

**Comment by minrk** [comment]
It shouldn't be present on orm.User. The presence of the `user.spawner` property should prevent `.__getattr__` from being called. I suspect that there's a bug somewhere else preventing the property retrieval from working, and instead of raising it falls back on `__getattr__`. That's a total guess, though.

Do you see this error if you run with a fresh, empty database?

**Comment by dhirschfeld** [comment]
Yep, I'm always starting with a fresh database

**Comment by dhirschfeld** [comment]
Will revert the change (locally) and try to get to the bottom of it in PyCharm...

**Comment by minrk** [comment]
Great, thanks! This particular case ought to be exercised pretty thoroughly already in the tests, so I think it might be a weird artifact of something in your config.

My first thought would be to run it with pdb / IPython.embed and inspect the state of `self.spawners`. It should always have at least one key: `''`.

**Comment by dhirschfeld** [comment]
Looks like a Heisenbug - I can no longer reproduce the error. As you say it makes no sense so I've no idea how it happened in the first place.

Will close as it was probably just something weird with my config/system :|
