### ISSUE TITLE
Blocking Cross Origin API request

### ISSUE THREAD

**Issue by krak3nnn** [jupyterhub/jupyterhub#1363]
**Error Output**
[W 2017-08-24 15:13:05.651 JupyterHub base:39] Blocking Cross Origin API request.  Referer: https://www.mydomain.com/hub/home, Host: 10.1.1.0:8000/hub/
[W 2017-08-24 15:13:05.659 JupyterHub base:39] Blocking Cross Origin API request.  Referer: https://www.mydomain.com/hub/home, Host: 10.1.1.0:8000/hub/

**How to reproduce the issue**
After a user logs in, a batch job is submitted to the queue and resources are allocated. When the user finished and uses the "Stop My Server" button to kill the job, Jupyterhub shows the error above and the job termination request is ignored.

**What you expected to happen**
For Jupyterhub to acknowledge the request and terminate the job.

**What actually happens**
Request is ignored and the "Blocking Cross Origin API request" is displayed.

**Share what version of JupyterHub you are using**
JupyterHub 0.7.2 with batchspawner

**Comment by minrk** [comment]
Do you have an additional proxy in front of your Hub?

**Comment by krak3nnn** [comment]
Yes, I'm using an apache proxy. Initially I had an issue where the kernel and terminals would not connect due to web socket issues but after adjusting the proxy config setting according to a close case I found, everything worked fine with the exception of stopping servers.

**Comment by willingc** [comment]
@minrk Thoughts?

**Comment by minrk** [comment]
I think you want to set [`ProxyPreserveHost on`](https://httpd.apache.org/docs/current/mod/mod_proxy.html#proxypreservehost) in apache to preserve the original Host header.

**Comment by krak3nnn** [comment]
Adding that config parameter breaks the proxy. Terminal no longer loads properly.

**Comment by minrk** [comment]
>  Terminal no longer loads properly.

What terminal doesn't load, and what is the error?

**Comment by atullo2** [comment]
I think I have the same error. I also have JupyterHub configured behind an Apache proxy, in order to use our local auth system. Clicking "Stop My Server" produces a popup with "403 Forbidden" and a message similar to the above in the logs:

[W 2018-01-11 12:54:52.269 JupyterHub base:47] Blocking Cross Origin API request.  Referer: https://xxxx/hub/home, Host: xxxx:8000/hub/
[W 2018-01-11 12:54:52.271 JupyterHub base:47] Blocking Cross Origin API request.  Referer: https://xxxx/hub/home, Host: xxxx:8000/hub/
[W 2018-01-11 12:54:52.271 JupyterHub log:122] 403 DELETE /hub/api/users/xxxx/server (@::ffff:ip) 3.13ms

With ProxyPreserveHost enabled:

* no files / directories appear in the list after login
* no notebook types appear in the "New" menu (just Terminal or Text File)

Happy to do more digging, let me know what to look for.

**Comment by Luke035** [comment]
+1

**Comment by prateek2408** [comment]
Facing the exact same issue

**Comment by willingc** [comment]
Hi @prateek2408 and @Luke035, Typically this error means that there is something amiss in the Apache configuration. Here's a link to an Apache configuration that we know works with JupyterHub http://jupyterhub.readthedocs.io/en/latest/reference/config-examples.html#apache Feel free to follow up if you still have questions after looking through the example.

**Comment by thankit** [comment]
> Hi @prateek2408 and @Luke035, Typically this error means that there is something amiss in the Apache configuration. Here's a link to an Apache configuration that we know works with JupyterHub http://jupyterhub.readthedocs.io/en/latest/reference/config-examples.html#apache Feel free to follow up if you still have questions after looking through the example.

Did any one found the issue for this, having same issues!

**Comment by hg77** [comment]
I also ran into this issue (note http vs https):
```
Blocking Cross Origin API request.  Referer: https://example.com/jupyter/hub/spawn-pending/myuser,
Host: example.com, Host URL: http://example.com/jupyter/hub/
```
I stumbled upon https://github.com/jupyterhub/jupyterhub/pull/3701#issuecomment-1002750092 and then understood that I was missing 
```
    # Without the following it does not work at all
    ProxyPreserveHost on
    # Without the following I sometimes get above Blocking Cross Origin API 
    RequestHeader     set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
```
from https://jupyterhub.readthedocs.io/en/latest/reference/config-proxy.html .

So RTFM solved it for me.

**Comment by portega-inbrain** [comment]
I'm running into the same issue @hg77 but don't use Apache nor nginx. Is there a solution for this when your proxy is an aws-load-balancer? Thanks!

**Comment by hg77** [comment]
@portega-inbrain have a look how to set X-forward-poto in aws here: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/x-forwarded-headers.html

I don’t have any experience with it though.

**Comment by schepuri2012** [comment]
@portega-inbrain I am running into the same problem with the AWS load balancer. Were you able to resolve this? Appreciate any leads :) Thanks!

**Comment by minrk** [comment]
JupyterHub 4.0 should no longer have issues with proxy headers, since they are no longer involved in CORS checks.

**Comment by portega-inbrain** [comment]
> @portega-inbrain I am running into the same problem with the AWS load balancer. Were you able to resolve this? Appreciate any leads :) Thanks!

Unfortunately I haven't, but maybe @minrk  last comment helps now.
