### ISSUE TITLE
Remove `redirect=` from the URL on error pages

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#1365]
We now track redirect count to get a better error in the event of redirect loops. One problem is that we leave the `?redirect=5` in the URL when we render the error page. This results in refreshing the page after a failure *appearing* to have a redirect loop, but it's reusing the value from the previous failure.

When rendering the error page, we should remove the `redirect=` part from the URL so that refreshing the page doesn't preserve the value.

This would probably be best done in [`share/jupyter/hub/templates/page.html`](https://github.com/jupyterhub/jupyterhub/blob/master/share/jupyter/hub/templates/page.html)

We have similar query removal in jupyter/notebook to remove `token=` [here](https://github.com/jupyter/notebook/blob/5.0.0/notebook/templates/page.html#L160-L182).

**Comment by smiller5678** [comment]
Hi! I'm at PyCon Canada and thinking about looking into this issue for the sprints

**Comment by Andy-Doddington** [comment]
Is this change likely to fixed my issue (#1551)? If so, when is it likely to be released?

**Comment by jzf2101** [comment]
@minrk @Carreau @willingc any thoughts on @Andy-Doddington 's question?
