### ISSUE TITLE
stress test in CI

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#1371]
@yuvipanda's been doing some great stress tests, which have found bugs and race conditions. It would be great if we can find a way to run these in CI, so that we have a harder time introducing regressions.

It might even be cool to hook up [asv](https://asv.readthedocs.io/en/latest/) for performance regressions, but that might be harder to do.

**Comment by yuvipanda** [comment]
would we just run this with DummyAuthenticator + SimpleLocalProcessSpawner equivalent? If so, IMO we need to make LocalProcessSpawner use tornado.subprocess, since the blocking behavior of subprocess doesn't really let us test anything here.

**Comment by minrk** [comment]
Starting with DummyAuthenticator + LocalProcessSpawner seems like an okay start. I might be inclined to run an instrumented spawner that can add some artificial delays in the spawn process.

> IMO we need to make LocalProcessSpawner use tornado.subprocess, since the blocking behavior of subprocess doesn't really let us test anything here.

I don't think tornado.subprocess is any less blocking than what we have in LocalProcessSpawner. All it does is call `Popen` and then attach streams, which we wouldn't use. It does have a handy feature for being notified about process shutdown via SIGCHLD, which would let us drop polling except when resuming for the db. That would be handy.

LocalProcessSpawner is only blocking on the calls:

- Popen, which only waits for a process to exist, not start (tornado Subprocess is blocking on the same call in `__init__`). `Popen(['jupyterhub-singleuser'])` takes 4ms on my laptop.
- os.kill, which is pretty immediate (tornado exposes no such functionality, so this code would be the same)

I think local is fine, but we could also use KubeSpawner, since that's what we've been using for the stress tests already, and would allow us to run them across machines without changes if so desired.

**Comment by manics** [comment]
I think this has been done in various places (probably Z2JH?).
