### ISSUE TITLE
Run R kernels on a different server

### ISSUE THREAD

**Issue by lrob** [jupyterhub/jupyterhub#1376]
Hi,
this is my setup.

There are two servers:
* **Server A**: a server running jupyterhub
* **Server B**: a server with an installation of R

I would like the instances of jupyter notebook started by jupyterhub on  **Server A** to start R kernels on **Server B** is it possible?

Thanks in advance

**Comment by minrk** [comment]
It's technically possible, but it's not super easy. The level you would need to do this at is the `KernelManager` in the notebook server. You will need to write a custom KernelManager that starts r kernels remotely instead of locally, and then retrieves the connection info.

**Comment by lrob** [comment]
Thanks, for your answer.

It sounds complicated... I will probably install a new instance of jupyterhub on the server with the installation of R

**Comment by minrk** [comment]
That's probably a simpler solution right now.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
