### ISSUE TITLE
jupyterhub terminals fail to run

### ISSUE THREAD

**Issue by jiancai1992** [jupyterhub/jupyterhub#1387]
Hi, I just installed JupyterHub using anaconda3.

This is a vanilla install, no reserve proxy.

Everything look fine(python3 is running) but when i start terminals:
![image](https://user-images.githubusercontent.com/31533464/29960258-87127410-8f2d-11e7-9c5e-6cc5939e4fc2.png)

Error:
```
[I 2017-09-01 15:45:08.031 JupyterHub log:100] 200 GET /hub/api/authorizations/cookie/jupyter-hub-token-hduser/[secret] (hduser@127.0.0.1) 12.74ms
[E 2017-09-01 15:45:08.256 hduser web:1590] Uncaught exception GET /user/hduser/terminals/websocket/1 (::ffff:192.168.1.119)
    HTTPServerRequest(protocol='http', host='192.168.1.217', method='GET', uri='/user/hduser/terminals/websocket/1', version='HTTP/1.1', remote_ip='::ffff:192.168.1.119', headers={'X-Forwarded-Port': '80', 'Sec-Websocket-Key': 'AOKMadTEN/fluE8xkNeQgg==', 'Upgrade': 'websocket', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36', 'Pragma': 'no-cache', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-US,en;q=0.8', 'Sec-Websocket-Version': '13', 'Cache-Control': 'no-cache', 'Sec-Websocket-Extensions': 'permessage-deflate; client_max_window_bits', 'X-Forwarded-Proto': 'ws', 'Connection': 'Upgrade', 'Origin': 'http://192.168.1.217', 'Host': '192.168.1.217', 'Cookie': 'jupyter-hub-token-hduser="2|1:0|10:1504251907|24:jupyter-hub-token-hduser|44:ZDZmN2U0NWI5OTRhNDBlNGIzMGZlNDhlZmFkMGJkNjU=|bf2241e811aab6a16ea3089bef0f1cab3c4ae854a6076ada8a3f67459e2fc827"', 'X-Forwarded-For': '::ffff:192.168.1.119'})
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/opt/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 1669, in wrapper
        result = method(self, *args, **kwargs)
      File "/opt/anaconda3/lib/python3.5/site-packages/tornado/websocket.py", line 196, in get
        self.ws_connection.accept_connection()
      File "/opt/anaconda3/lib/python3.5/site-packages/tornado/websocket.py", line 619, in accept_connection
        self._accept_connection()
      File "/opt/anaconda3/lib/python3.5/site-packages/tornado/websocket.py", line 681, in _accept_connection
        self.handler.finish()
      File "/opt/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 993, in finish
        self._log()
    TypeError: 'Logger' object is not callable
[E 2017-09-01 15:45:08.259 hduser web:1015] Cannot send error response after headers written
[E 2017-09-01 15:45:08.259 hduser web:1025] Failed to flush partial response
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/opt/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 1669, in wrapper
        result = method(self, *args, **kwargs)
      File "/opt/anaconda3/lib/python3.5/site-packages/tornado/websocket.py", line 196, in get
        self.ws_connection.accept_connection()
      File "/opt/anaconda3/lib/python3.5/site-packages/tornado/websocket.py", line 619, in accept_connection
        self._accept_connection()
      File "/opt/anaconda3/lib/python3.5/site-packages/tornado/websocket.py", line 681, in _accept_connection
        self.handler.finish()
      File "/opt/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 993, in finish
        self._log()
    TypeError: 'Logger' object is not callable

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 1022, in send_error
        self.finish()
      File "/opt/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 993, in finish
        self._log()
    TypeError: 'Logger' object is not callable
```

Version
OS, CentOS Linux release 7.2.1511 (Core)   
npm, 5.3.0
nodejs, v8.4.0
jupyter, 4.3.0
anaconda, Anaconda3-4.0.0-Linux-x86_64.sh

**Comment by minrk** [comment]
What version of the `jupyterhub`, `notebook` and `tornado` packages? Try `conda list` or `pip list`?

**Comment by yoryicopo** [comment]
Hi,
I have the same problem:
jupyterhub 0.2.0
notebook 5.0.0
tornado 4.5.1

Best regards,
Jorge

**Comment by willingc** [comment]
@yoryicopo The currently released version of JupyterHub is 0.7.2 and beta 0.8.0b5. 0.2.0 is a very old version. I recommend upgrading.

**Comment by jiancai1992** [comment]
The installation environment is offline so i pack the lib using /opt/anaconda3/bin/pip download jupyterhub to currently dir

then i run  /opt/anaconda3/bin/pip install * <---- this is the command that cause the problem, appearancely this cause the tornado error

to resolve i run this:
/opt/anaconda3/bin/pip install SimpleJupyterHub/jupyterlib/Mako-1.0.7.tar.gz
/opt/anaconda3/bin/pip install SimpleJupyterHub/jupyterlib/python-editor-1.0.3.tar.gz
/opt/anaconda3/bin/pip install SimpleJupyterHub/jupyterlib/alembic-0.9.5.tar.gz
/opt/anaconda3/bin/pip install SimpleJupyterHub/jupyterlib/pamela-0.3.0-py2.py3-none-any.whl
/opt/anaconda3/bin/pip install SimpleJupyterHub/jupyterlib/jupyterhub-0.7.2-py3-none-any.whl

![image](https://user-images.githubusercontent.com/31533464/30330577-0cbc6264-9808-11e7-8761-4ddbdc7737e1.png)

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻

**Comment by jakepaw** [comment]
Having this issue on Jupyterhub 1.0.0 with systemdspawner .13 and notebook 5.0.0 

Terminal is blank when trying to access..

**Comment by willingc** [comment]
@jakepaw The first thing that I would try would be to update all of your installed packages. Feel free to post the output of `jupyterhub --debug` after startup.

**Comment by jakepaw** [comment]
I updated all my packages, thanks for the response!

Here is my output, i took out all sensitive data..

Note: I also replaced the file (systemdspawner.systemd.py) with this file https://raw.githubusercontent.com/jupyterhub/systemdspawner/master/systemdspawner/systemd.py because of an issue i was having using systemd 219, this allowed me to view my files in jupyterhub on the UI

[terminal_error.txt](https://github.com/jupyterhub/jupyterhub/files/3653377/terminal_error.txt)
