### ISSUE TITLE
Shared session proposal

### ISSUE THREAD

**Issue by ckald** [jupyterhub/jupyterhub#139]
Hello,

Yeah, I know that Jupyter is designed to spawn single-user notebooks, but I think it might be not so hard to implement a limited use case for collaboration. 

The backstory: currently I use Jupyter to analyse some datasets and then present the results to my colleagues. First problem on my way were the isolated user folders in Jupyter. This was rather easy to fix — I just added a symlink to other user's home dir. Now other people can see my notebooks and run them in their own sessions. I create one notebook that analyses data and saves it to the DB and the other one to share with data presentation.

This is quite good, but it would be excellent to be able to share the session with another user and run the notebook in one context. It should work just like a regular ipython notebook (i.e., running 1 cell at a time, etc.) — it will just receive orders from multiple users (this does not seem to be technically difficult to implement on the ipython side, just merge 2 sessions' tasks queues).

Of course, this requires some google-drive-like interface extension to allow users seeing each others cursors and to merge their command flows. But I think there are many successful examples of collaboratory editors, so this problem can be solved with existing tools.

At the very least read-only sharing of some notebook is very welcome — such that someone could take a look at the status of my computation, cell outputs, etc.

**Comment by willingc** [comment]
I'm going to close this issue and label it as `reference` since the next actions are captured in other projects.
