### ISSUE TITLE
Whitelist for login with Github auth allows any (?) Github user in?

### ISSUE THREAD

**Issue by arokem** [jupyterhub/jupyterhub#1396]
Using Github auth, following instructions from z2jh (k8s/AWS). I have configured the cluster with a whitelist of Github user names, and can monitor who is logging in by running a `kubectl get pod`. I just had a pod with a name `jupyter-uname` appear, where `uname` is the name of a Github user that is not on the whitelist. Should that be happening? Does this mean that this user managed to get through the auth despite not being on the whitelist?

**Comment by arokem** [comment]
More info: the pod existed for more than half an hour, but is now gone.

**Comment by minrk** [comment]
How did you set the whitelist and what do you see in the logs? I'm guessing that the whitelist did not end up getting specified in the Hub. If this is the case, you should see this in the logs when JupyterHub starts:

> Not using whitelist. Any authenticated user will be allowed.

**Comment by arokem** [comment]
You're right. I am getting this in the logs:

    [W 2017-09-06 12:37:32.129 arokem login:225] All authentication is
disabled.  Anyone who can connect to this server will be able to run code.
I am setting up authentication following the instructions here:

https://zero-to-jupyterhub.readthedocs.io/en/latest/
extending-jupyterhub.html#authenticating-with-oauth2

But I think that I put the whitelist in the wrong part of my config (under
the "auth" section, instead of under the "hub" section).

Closing for now.

**Comment by minrk** [comment]
I think whitelist isn't supported in v4 of the helm chart (it just landed in master today). I think you need to use the `extraConfig` escape hatch for this.

**Comment by arokem** [comment]
Just to be clear: does this mean that the documentation in the z2jh page that I referred to is incorrect?

**Comment by minrk** [comment]
Ah, no. That `hub.extraConfig` should be correct. What's new is specifying directly `hub.whitelist.users` in the yaml.
