### ISSUE TITLE
Is oauth2 a required dependency?

### ISSUE THREAD

**Issue by Siecje** [jupyterhub/jupyterhub#1397]
**How to reproduce the issue**

I'm trying to run `jupyterhub` without having `oauth2` installed.

**What you expected to happen**

`jupyterhub` to run, unless `oauth2` is required.

**What actually happens**

I get a traceback on the oauth2 import in `apihandlers.auth.py`

```
Traceback (most recent call last):
  File "./jupyterhub", line 3, in <module>
    from jupyterhub.app import main
  File "/tmp/pip-build-2d1es345/jupyterhub/jupyterhub/app.py", line 45, in <module>
  File "/tmp/pip-build-2d1es345/jupyterhub/jupyterhub/apihandlers/__init__.py", line 2, in <module>
  File "/tmp/pip-build-2d1es345/jupyterhub/jupyterhub/apihandlers/auth.py", line 9, in <module>
ModuleNotFoundError: No module named 'oauth2'
```

**Share what version of JupyterHub you are using**

0.8.0b4

**Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.**

I get the same traceback when I run `jupyter troubleshoot`.

**Details**

`oauth2` is not listed in [requirements.txt](https://github.com/jupyterhub/jupyterhub/blob/4692d6638dd7af6605a75001c4a48ad3136b83a3/requirements.txt)

Is `oauth2` required for `jupyterhub`?

I'm using the [remote_user authenticator](https://github.com/cwaldbieser/jhub_remote_user_authenticator) and don't have pamela installed, which is okay because of https://github.com/jupyterhub/jupyterhub/commit/6713277f33feef43ad211c0b1f813eafe53a6d96.

Perhaps `oauth2` could be treated the same.

**Comment by willingc** [comment]
Hi @Siecje,

With version 0.8, JupyterHub is an oauth2 provider. [ref: changelog](https://jupyterhub.readthedocs.io/en/latest/changelog.html#unreleased-0-8).

> ... the biggest change is the use of OAuth to negotiate authentication between the Hub and single-user services.

The confusingly named [`python-oauth2` is found in `requirements.txt`](https://github.com/jupyterhub/jupyterhub/blob/master/requirements.txt#L6). For 0.8, `python-oauth2` is required.

**Comment by minrk** [comment]
Yup, oauth is how the single-user servers and Hub communicate, so oauth2 is indeed a requirement to run JupyterHub, regardless of the Authenticator in use.
