### ISSUE TITLE
jquery not found issue in 0.8b4

### ISSUE THREAD

**Issue by harschware** [jupyterhub/jupyterhub#1401]
Issue in hub 0.8b4. 
I think I'm on 5.1.0RC2 of jupyter.

I see this in logs:
```
 [E 2017-09-06 15:16:28.687 JupyterHub web:2746] Could not open static file '/usr/share/jupyter/hub/static/components/jquery/jquery.min.js'
```
when using curl against /hub/login

It should be .../jquery/src/jquery.min.js

I see this when using browser:
```
[W 2017-09-06 15:35:00.727 JupyterHub log:122] 404 GET /hub/static/components/jquery/jquery.min.js (@::ffff:76.126.228.250) 0.55ms
[W 2017-09-06 15:35:00.884 JupyterHub log:122] 404 GET /hub/static/components/jquery/jquery.min.js (@::ffff:76.126.228.250) 0.67ms
[W 2017-09-06 15:35:02.212 JupyterHub log:122] 404 GET /hub/static/components/jquery/jquery.min.js?v=(& (@::ffff:76.126.228.250) 0.67ms
```

**Comment by minrk** [comment]
How did you install jupyterhub?

**Comment by harschware** [comment]
I downloaded from GitHub and checkedout the 0.8.0b4 tag and did a "pip install ."

**Comment by harschware** [comment]
Maybe this is the problem code, I see it does not have "src" in the path:

https://github.com/jupyterhub/jupyterhub/blob/e7a0556118b6699cd4fc5d7bcc38bf0970f75e97/share/jupyter/hub/templates/page.html#L38

**Comment by minrk** [comment]
Try doing:

    pip uninstall jupyerhub
    pip install jupyterhub==0.8.0b4

to install from PyPI instead of the git repo.

**Comment by yuvipanda** [comment]
Is this still present when you do an install from pypi, after 0.8 final release?

**Comment by harschware** [comment]
I'll try to check soon

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
