### ISSUE TITLE
Uploaded files always get 644

### ISSUE THREAD

**Issue by bribroder** [jupyterhub/jupyterhub#1402]
**How to reproduce the issue**
Upload a file using the Upload button, and its permissions will always be set to 644, even if the original file had more restrictive *or* more lenient permissions.

**What you expected to happen**
The file should retain the permissions it had on upload, or permissions should obey a user's umask, or there should be a global jupyterhub umask

**Share what version of JupyterHub you are using**
0.8.0b4 (installed via pip)

**Comment by minrk** [comment]
I don't believe that web form uploads have any way of knowing what the original file ownership or permissions are. The default permissions are governed by umask of the notebook server process, though.

If you set the umask during process startup, e.g. in `/etc/jupyter/jupyter_notebook_config.py`:

```python
import os
os.umask(0o066) # default to 0600
```

then this will set the default permissions of all new files created by the notebook server, including file uploads and new notebooks.

**Comment by bribroder** [comment]
marvelous!

**Comment by dclong** [comment]
@minrk 
I following your instructions to configure Jupyter Notebook. The option I used was
```
import os
os.umask(0o002)
```
The newly created notebooks have the right permission (664), however the `.ipy_checkpoints` folders do not. Do you have any idea how to make the `.ipy_checkpoints` folders respect the umask as well?
