### ISSUE TITLE
GitHub OAuthenticator throwing an error: getpwnam(): name not found

### ISSUE THREAD

**Issue by mmchougule** [jupyterhub/jupyterhub#1405]
I am trying to use LocalGitHubOAuthenticator as mentioned in the documentation on here: https://github.com/jupyterhub/oauthenticator

I created a GitHub OAuth application and added lines as mentioned in `jupyterhub_config.py`. I am able to login from GitHub to Jupyter Hub but when I click on "Start my server", I keep getting this error that says `getpwnam(): name not found: mmchougule`.
```
# jupyterhub_config.py
c = get_config()

from oauthenticator.github import LocalGitHubOAuthenticator
c.JupyterHub.authenticator_class = LocalGitHubOAuthenticator

c.LocalAuthenticator.create_system_users = True

// commented out these two lines since I was getting 'mmchougule' already exists in db
c.Authenticator.whitelist = {'mmchougule'}
c.Authenticator.admin_users = {'mmchougule'}
```
I couldn't find a solution to why is it not able to create a server.

In the admin portal, I get the same error when I try to start the server. I used the REST API to call /users endpoint and I can see my user. 

I also saw this error: `I don't know how to create users on OS X` in `jupyterhub/jupyterhub/blob/master/jupyterhub/auth.py`

Can anyone please help me understand / fix this issue?

**Comment by willingc** [comment]
@mmchougule What versions of `oauthenticator` and JupyterHub are you using?

**Comment by mmchougule** [comment]
@willingc 
I just installed Jupyterhub and oauthenticator today. The latest version of oauthenticator.

Jupyterhub --version: 0.7.2

**Comment by minrk** [comment]
LocalGitHubOAuthenticator is a subclass of GitHubOAuthenticator that maps github usernames to local system usernames. To use it, the relevant GitHub usernames must exist as users on your system, or be created via `create_system_users`. JupyterHub doesn't know how to create users on OS X, so the `.create_system_users` flag doesn't work there.

If you use the base `GitHubOAuthenticator`, then users aren't required to exist on the system, but you must also use a Spawner that doesn't require local users (e.g. DockerSpawner)

A third case is: you already have users on your system, but GitHub usernames don't match. For this, you can use `c.LocalGitHubOAuthenticator.username_map`:

```python
# leave this as the default (False)
# c.LocalAuthenticator.create_system_users = False
c.LocalGitHubOAuthenticator.username_map = {
    'my-github-name': 'my-unix-name',
}
```

**Comment by mmchougule** [comment]
@minrk thank you so much for the response.

I quickly tried adding the username_map attribute and it worked. I would have to create users on OS X ahead of time, add the mapping and then restart Jupyterhub. As you mentioned, maybe it's a better idea to use a DockerSpawner in my case.

I am guessing it's the same case if I use any other authentication service. We are using  [Okta](https://developer.okta.com/standards/OAuth/) for authentication so I would like to use this service. It seems like it would be very similar to the Auth0 implementation.

**Comment by brayanrodbajo** [comment]
Hi. 

Is there anyway to do authentication and creating users with an external API without Local authentication?

Thanks in advance.
