### ISSUE TITLE
Automatically export a notebook as a script upon saving

### ISSUE THREAD

**Issue by arthur-gouveia** [jupyterhub/jupyterhub#1412]
Hi! I'm using Jupyterhub 0.7.2 with Python 3 and R kernels. I'd like to automatically export the script (.py or .r) upon saving the .ipynb.

I already do it on Jupyter following the instructions found here https://github.com/ipython/ipython/issues/8009 but I'd like to have the same behaviour on Jupyterhub. How can I do it?

As I said it's Jupyterhub 0.7.2, multiple users, PAM authentication and default spawner.

**Comment by Carreau** [comment]
JupyterHub is mostly a proxy to single user servers. 
If you want to export for each user then you need to configure this functionality for each users. 
You can either do it by modifying the configuration files for each user, or using system wide configuration files which will affect all users.

**Comment by arthur-gouveia** [comment]
Thank you @Carreau! Could you please help me making the system wide configuration? Is it an option on jupyterhub_config.py?

**Comment by Carreau** [comment]
No, you need to configure independently the notebooks servers themseleves. 

Think of it this way: 

The hub does not know, care, or should try to be made to by Jupyter Specific. The only thing it does  is start a process on behalf of the user. This process happen to be, most of the time, Jupyter Notebook.  Now Hub _could_ launch for example R-studio. 

Jupyter Notebook search for config in various path that can be per-system and per user. 
You can find the paths it searches [here](http://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html#configuration-files). 

So if you put a configuration file in these locations, they should apply to all users; unless users have themselves configuration that overwrite this in their home directory. 

So if you simply move your local files to (I believe) `/usr/share/jupyter/`, then this should apply to all users.  If you are spawning notebook in docker containers, then you need to make sure these files are in the docker containers that spawn the notebook servers. 

Now you can, if you wish, have the hub pass extra configuration flags on the command line to the notebook, but that seem overcomplicated, and not what you wish if I understand correctly.

Does that make sens ?

**Comment by arthur-gouveia** [comment]
Perfect! I could do it.

For future references, that's what I did:

I found Jupyter config paths by using `jupyter --paths`.

Then I created the `jupyter_notebook_config.py` file in one of those paths. The contents of 
`jupyter_notebook_config.py` is:

```
import os
from subprocess import check_call

def post_save(model, os_path, contents_manager):
    """post-save hook for converting notebooks to .py scripts"""
    if model['type'] != 'notebook':
        return # only do this for notebooks
    d, fname = os.path.split(os_path)
    check_call(['ipython', 'nbconvert', '--to', 'script', fname], cwd=d)
```

**Comment by Carreau** [comment]
great ! 

If the subprocess call is too slow you can also instanciate a `ScriptExporter` manually:

```
from nbconvert import ScriptExporter
exporter = ScriptExporter(config=...) # like set cwd
```

Then use the  `exporter.from_notebook_node(model)` to convert in-memory. The exporter should be stateless and can be reused for many conversions. You should be able to find the details in nbconvert documentation, if not feel free to ping us.

**Comment by jinjiren** [comment]
Thanks to @Carreau's suggestion, I wrote [this](https://gist.github.com/jinjiren/29244faa896ac788357a46338f78b580) with an additional change to avoid automatically create `Untitled.txt` files. 

```Python
import io
import os
import re
from nbconvert.exporters.script import ScriptExporter
from notebook.utils import to_api_path


def script_post_save(model, os_path, contents_manager, **kwargs):
    """Save a copy of notebook to the corresponding language source script.
    For example, when you save a `foo.ipynb` file, a corresponding `foo.py`
    python script will also be saved in the same directory.
    However, existing config files I found online (including the one written in
    the official documentation), will also create an `Untitile.txt` file when
    you create a new notebook, even if you have not pressed the "save" button.
    This is annoying because we usually will rename the notebook with a more
    meaningful name later, and now we have to rename the generated script file,
    too!
    Therefore we make a change here to filter out the newly created notebooks
    by checking their names. For a notebook which has not been given a name,
    i.e., its name is `Untitled.*`, the corresponding source script will not be
    saved. Note that the behavior also applies even if you manually save an
    "Untitled" notebook. The rationale is that we usually do not want to save
    scripts with the useless "Untitled" names.
    """
    # only process for notebooks
    if model["type"] != "notebook":
        return

    script_exporter = ScriptExporter(parent=contents_manager)
    base, __ = os.path.splitext(os_path)

    # do nothing if the notebook name ends with `Untitled[0-9]*`
    regex = re.compile(r"Untitled[0-9]*$")
    if regex.search(base):
        return

    script, resources = script_exporter.from_filename(os_path)
    script_fname = base + resources.get('output_extension', '.txt')

    log = contents_manager.log
    log.info("Saving script at /%s",
             to_api_path(script_fname, contents_manager.root_dir))

    with io.open(script_fname, "w", encoding="utf-8") as f:
        f.write(script)

c.FileContentsManager.post_save_hook = script_post_save
```

**Comment by ThibTrip** [comment]
> Thanks to @Carreau's suggestion, I wrote [this](https://gist.github.com/jinjiren/29244faa896ac788357a46338f78b580) with an additional change to avoid automatically create `Untitled.txt` files.
> 
> ```python
> import io
> import os
> import re
> from nbconvert.exporters.script import ScriptExporter
> from notebook.utils import to_api_path
> 
> 
> def script_post_save(model, os_path, contents_manager, **kwargs):
>     """Save a copy of notebook to the corresponding language source script.
>     For example, when you save a `foo.ipynb` file, a corresponding `foo.py`
>     python script will also be saved in the same directory.
>     However, existing config files I found online (including the one written in
>     the official documentation), will also create an `Untitile.txt` file when
>     you create a new notebook, even if you have not pressed the "save" button.
>     This is annoying because we usually will rename the notebook with a more
>     meaningful name later, and now we have to rename the generated script file,
>     too!
>     Therefore we make a change here to filter out the newly created notebooks
>     by checking their names. For a notebook which has not been given a name,
>     i.e., its name is `Untitled.*`, the corresponding source script will not be
>     saved. Note that the behavior also applies even if you manually save an
>     "Untitled" notebook. The rationale is that we usually do not want to save
>     scripts with the useless "Untitled" names.
>     """
>     # only process for notebooks
>     if model["type"] != "notebook":
>         return
> 
>     script_exporter = ScriptExporter(parent=contents_manager)
>     base, __ = os.path.splitext(os_path)
> 
>     # do nothing if the notebook name ends with `Untitled[0-9]*`
>     regex = re.compile(r"Untitled[0-9]*$")
>     if regex.search(base):
>         return
> 
>     script, resources = script_exporter.from_filename(os_path)
>     script_fname = base + resources.get('output_extension', '.txt')
> 
>     log = contents_manager.log
>     log.info("Saving script at /%s",
>              to_api_path(script_fname, contents_manager.root_dir))
> 
>     with io.open(script_fname, "w", encoding="utf-8") as f:
>         f.write(script)
> 
> c.FileContentsManager.post_save_hook = script_post_save
> ```

Hello,

I am very interested in this topic and I want to use your function but I could not figure out how it works. Could you provide a usage example?

Also it tells me that "c" is not defined (last line):
![error_c_not_defined](https://user-images.githubusercontent.com/40694343/45473475-780cf700-b737-11e8-9998-42c7d7b64751.png)

Let's say I put your code in a .py file. I then import this module in a jupyter notebook. How do I use it then?
![save_to_py](https://user-images.githubusercontent.com/40694343/45473488-7e9b6e80-b737-11e8-94fa-cb42e78620e8.png)

Sorry if I'm asking dumb questions and thanks in advance!

Cheers, Thibault

**Comment by jinjiren** [comment]
@ThibTrip Hi, I'm glad that it can be helpful :)

Actually, this script is not intended to be used in your notebook. Instead, please add it to your jupyter notebook config file.

For example, you can add it to `~/.jupyter/jupyter_notebook_config.py`. (just copy and paste it into the file)
Note that you may need to restart the jupyter notebook / lab for it to work.

**Comment by ThibTrip** [comment]
> @ThibTrip Hi, I'm glad that it can be helpful :)
> 
> Actually, this script is not intended to be used in your notebook. Instead, please add it to your jupyter notebook config file.
> 
> For example, you can add it to `~/.jupyter/jupyter_notebook_config.py`. (just copy and paste it into the file)
> Note that you may need to restart the jupyter notebook / lab for it to work.

Hi! Thank you! I deleted my post because I found this out right after, sorry :(!!!

So I could not find the file you mentionned at first when using this command:
!jupyter --paths
    ...\.jupyter # the first result is where the file was supposed to be

If there is not a config file I found out you have to use this command, that will create the jupyter_notebook_config.py file for you:
!jupyter notebook --generate-config

I tested it and it works like a charm! Thanks a lot :)!

I am probably going to try to add a functionality to change the directory it goes to. I'd like to export to .py to a github folder for versioning.

Cheers, Thibault

**Comment by ThibTrip** [comment]
> > @ThibTrip Hi, I'm glad that it can be helpful :)
> > Actually, this script is not intended to be used in your notebook. Instead, please add it to your jupyter notebook config file.
> > For example, you can add it to `~/.jupyter/jupyter_notebook_config.py`. (just copy and paste it into the file)
> > Note that you may need to restart the jupyter notebook / lab for it to work.
> 
> Hi! Thank you! I deleted my post because I found this out right after, sorry :(!!!
> 
> So I could not find the file you mentionned at first when using this command:
> !jupyter --paths
> ....jupyter # the first result is where the file was supposed to be
> 
> If there is not a config file I found out you have to use this command, that will create the jupyter_notebook_config.py file for you:
> !jupyter notebook --generate-config
> 
> I tested it and it works like a charm! Thanks a lot :)!
> 
> I am probably going to try to add a functionality to change the directory it goes to. I'd like to export to .py to a github folder for versioning.
> 
> Cheers, Thibault

I tried editing your code to be able to change the directory and it just won't work after multiple attempts. I saved the config and restarted the kernel of course but it does not seem to work.

```
	# this should save to another directory
	# to_directory is a keyword argument I added, in this case: O:/Thibault/
	script_fname = os.path.join(to_directory, script_fname.split('\\')[-1]) 

    with io.open(script_fname, "w", encoding="utf-8") as f:
        f.write(script)

c.FileContentsManager.post_save_hook = script_post_save
```

**Comment by ThibTrip** [comment]
Hello, 

so I finally managed to save to another folder by changing the function a little bit :). I added the argument custom_path.

```
import io
import os
import re
from nbconvert.exporters.script import ScriptExporter
from notebook.utils import to_api_path


def script_post_save(model, os_path, contents_manager,custom_path = 'O:/Github/', **kwargs):
```

[...]

```
    script_exporter = ScriptExporter(parent=contents_manager)
    
    if custom_path is None:
        base, __ = os.path.splitext(os_path)
    else:
        name_ext = os.path.basename(os_path)
        name_only = os.path.splitext(name_ext)[0]
        base = os.path.join(custom_path,name_only) 
        print(base)
```
[...]

Another thing I want to do now is that instead of saving every notebook to .py I'll only save those in a specific folder. If anyone is interested I can post the code here when I get it right.

Cheers, Thibault

**Comment by dwy904** [comment]
Are we able to do it only on the selected notebooks?

**Comment by skandagnprodapt** [comment]
> Perfect! I could do it.
> 
> For future references, that's what I did:
> 
> I found Jupyter config paths by using `jupyter --paths`.
> 
> Then I created the `jupyter_notebook_config.py` file in one of those paths. The contents of
> `jupyter_notebook_config.py` is:
> 
> ```
> import os
> from subprocess import check_call
> 
> def post_save(model, os_path, contents_manager):
>     """post-save hook for converting notebooks to .py scripts"""
>     if model['type'] != 'notebook':
>         return # only do this for notebooks
>     d, fname = os.path.split(os_path)
>     check_call(['ipython', 'nbconvert', '--to', 'script', fname], cwd=d)
> ```

I changed it in the config file and restarted the notebook. Where does it save the created file? I dont see any file being created.

**Comment by Bubblbu** [comment]
> Are we able to do it only on the selected notebooks?

Are there any leads on this by any chance?
