### ISSUE TITLE
LocalProcessSpawner tries to stop notebooks using SIGINT first

### ISSUE THREAD

**Issue by danfike** [jupyterhub/jupyterhub#1419]
When a user's notebook server is being shut down by JupyterHub (e.g. via control panel UI or `cull-idle` service), JupyterHub's `LocalProcessSpawner` attempts a `SIGINT` before sending `SIGTERM`.

But Jupyter Notebook does not actually register a `SIGINT` handler at all when spawned via JupyterHub (see [`notebook/notebookapp.py`](https://github.com/jupyter/notebook/blob/3543f79254b9c5a6a0fb3bf86b5585f9394c0291/notebook/notebookapp.py#L1232) )

It seems that me that `LocalProcessSpawner` should just skip the `SIGINT` altogether and go straight to `SIGTERM`. It looks like we thought about this at some point (see [`spawner.py`](https://github.com/jupyterhub/jupyterhub/blob/3b07bd286b301b96ebb7b177bdae4ac6d1add42a/jupyterhub/spawner.py#L1062-L1064)), but aren't quite taking the code path we should be?

Should we add a `now=True` over to [`user.py`](https://github.com/jupyterhub/jupyterhub/blob/3b07bd286b301b96ebb7b177bdae4ac6d1add42a/jupyterhub/user.py#L499)?

The consequence of this as written is that it always takes at least [`INTERRUPT_TIMEOUT`](https://github.com/jupyterhub/jupyterhub/blob/3b07bd286b301b96ebb7b177bdae4ac6d1add42a/jupyterhub/spawner.py#L842-L848) (default `10`) seconds for a notebook to be shut down.

Maybe there's some nuance to this driven by an effort to accommodate other `Spawner` implementations? I admit I don't have a strong grasp on these other use cases so I'm not confident I can evaluate what's best here. But for out-of-the-box behavior, this is annoying.

Note that I attempted to mitigate this in some way by configuring `LocalProcessSpawner.INTERRUPT_TIMEOUT` to a very small value, but I received this error on startup and don't know enough about `traitlets` yet to know what it means.
```
      File ".../jupyterhub_config.py", line 45, in <module>
        c.LocalProcessSpawner.INTERRUPT_TIMEOUT = 1
      File ".../site-packages/traitlets/config/loader.py", line 287, in __setattr__
        self.__setitem__(key, value)
      File ".../site-packages/traitlets/config/loader.py", line 272, in __setitem__
        'char must be Config instances: %r, %r' % (key, value))
    ValueError: values whose keys begin with an uppercase char must be Config instances: 'INTERRUPT_TIMEOUT', #1
```

**Comment by yuvipanda** [comment]
This is true for all spawners - I just observed this behavior in kubespawner.

**Comment by minrk** [comment]
The default Python handler of SIGINT raises KeyboardInterrupt, which is handled [here](https://github.com/jupyter/notebook/blob/5.1.0/notebook/notebookapp.py#L1493) for prompt cleanup and shutdown. I've just confirmed at least that LocalProcessSpawner and DockerSpawner stop promptly before SIGTERM is issued when I test, at least.

Only if something *else* registers a SIGINT handler will the clean shutdown not occur. How are you starting JupyterHub? What version of python, jupyterhub, and notebook? Maybe some process runner is consuming SIGINT.

**Comment by danfike** [comment]
> The default Python handler of SIGINT raises KeyboardInterrupt

^ Derp. Good point.

Now, I've confirmed that the `KeyboardInterrupt` handler is not being called for when I send a `SIGINT` signal. But If I go manually add a simple handler for `SIGINT` and register it in [`notebookapp.py init_signal`](https://github.com/jupyter/notebook/blob/3543f79254b9c5a6a0fb3bf86b5585f9394c0291/notebook/notebookapp.py#L1231), I can verify the handler _is_ called. This suggests to me that I don't have my process runner eating the `SIGINT`, but that maybe there's something else going on that's eating my `KeyboardInterrupt` before it reaches the handler you linked above. Let me investigate furthe and see what I can find.

We're running Python 3.5 with `jupyterhub 0.7.2` and `notebook 5.0.0`. 

(PS Thanks @minrk for the quick fix @ https://github.com/jupyterhub/jupyterhub/pull/1422)

**Comment by danfike** [comment]
Well despite what I wrote above, I do think this might be caused by my process runner. Not 100% confirmed yet though; I bet we're all on the edge of our seats.

**Comment by danfike** [comment]
Yeah, OK, I've confirmed the behavior is correct (`SIGINT` -> `KeyboardInterrupt` -> Exit) when I spawn JupyterHub exactly the same as my process runner does, but without the process runner. The process runner is opaque to me atm, but I'm convinced it's responsible for the difference.

Thanks again @minrk for #1422 because it allows me to move to a `0` timeout as a hack around the process runner's behavior, and we'll just go direct to `SIGTERM`. 

Going to close the issue; nothing to see here.
