### ISSUE TITLE
Customizing Dockerfile

### ISSUE THREAD

**Issue by dlsun** [jupyterhub/jupyterhub#1425]
I followed the [Zero to JupyterHub tutorial](http://zero-to-jupyterhub.readthedocs.io/en/latest/) and was able to get a running instance of JupyterHub on Google Cloud. Thanks so much for this awesome tutorial. It was very easy to follow for a complete novice like me.

I'm now trying to customize the image. I would like to pull Python code from Github and install the package. I tried creating a Dockerfile with the following contents:

```
FROM jupyter/scipy-notebook:2d878db5cbff

RUN conda install --quiet --yes \
  'setuptools=36.4.0'

RUN cd /tmp && \
    git clone https://github.com/dlsun/symbulate.git && \
    python symbulate/setup.py install && \
    rm -rf symbulate
```

The Dockerfile builds without any problem. I'm even able to apply the config changes using helm. The problem comes when I actually try to log in to JupyterHub (I'm using Github authentication) and start up my server. I get the error:

```
oci runtime error: container_linux.go:247: starting container process caused \"chdir to cwd (\\\"/home/jovyan/work\\\") set in config.json failed: no such file or directory
```

Any ideas on what I should do?

**Comment by Analect** [comment]
@dlsun 
Perhaps I can help.

So the default image in the helm-chart (zero-to-jupyterhub) is this one built with this Dockerfile here:  https://github.com/jupyterhub/helm-chart/blob/master/images/singleuser-sample/Dockerfile

You will need to structure your own image in a broadly similar way ... in terms of installing jupyterhub on the image itself (you'll probably need version 0.7.2).  Also note the creation of user jovyan and exposing port 8888 etc, as per that default Dockerfile.  Try to align your Dockerfile structure as much to this default one as you can, allowing for the fact that you may be building from a different base and installing other packages.

You will then have to over-ride the default helm-chart with your new image.  To do that, you add it to your `config.yaml` file (the one where you added a client-id and secret).  The `deployment.yaml` in the helm-chart will know to look there for any new image.

https://github.com/jupyterhub/helm-chart/blob/master/jupyterhub/templates/hub/deployment.yaml#L56

So your config.yaml file will have a section something like this:

```
singleuser:
  image:
    name: your-image-registry/your-image-name
    tag: your-image-tag    
```

**Comment by yuvipanda** [comment]
@dlsun that error indicates that you are probably using a really old version of docker-stacks as base. https://github.com/jupyter/docker-stacks/commit/2d878db5cbffae92b96f5e8922e9bdb28ed692b5 looks like it's from mid-2016. Can you use a newer base image? docker-stacks images older than a few months will give this error.

**Comment by dlsun** [comment]
@Analect Since my base is jupyter/scipy-notebook, shouldn't I already have everything that is in that default Dockerfile? 

@yuvipanda I changed to jupyter/scipy-notebook:latest and I'm getting the same error. :-(

**Comment by yuvipanda** [comment]
Can you add a 'WORKDIR $HOME' to the end of your Dockerfile?

**Comment by dlsun** [comment]
@yuvipanda I'm still getting the same error message.

**Comment by dlsun** [comment]
To be clear, my Dockerfile now looks like:

```
FROM jupyter/scipy-notebook:latest

RUN conda install --quiet --yes \
  'setuptools=36.4.0'

RUN cd /tmp && \
    git clone https://github.com/dlsun/symbulate.git && \
    python symbulate/setup.py install && \
    rm -rf symbulate

WORKDIR $HOME
```

**Comment by yuvipanda** [comment]
hmm, can you share your config.yaml? Also are you sure the new docker image is being used? Did you build and push a new tag with it?

**Comment by dlsun** [comment]
@yuvipanda Thanks for helping me with this. 

I ran the following command (from the directory with the Dockerfile) to build the image: `docker build . -t us.gcr.io/stat-350/symbulate`

Then I pushed the image to Google Cloud Registry: `gcloud docker -- push us.gcr.io/stat-350/symbulate`

Here is the `singleuser` part of my config.yaml file:
```
singleuser:
  image:
    name: us.gcr.io/stat-350/symbulate
    tag: latest
  memory:
    limit: 2G
    guarantee: 2G
```

which I upgrade by running the following command (from the directory containing config.yaml): `helm upgrade stat350-jupyterhub jupyterhub/jupyterhub --version=v0.4 -f config.yaml`

**Comment by yuvipanda** [comment]
Can you try using an explicit tag instead of 'latest'? so you'd do:

docker build . -t us.gcr.io/stat-350/symbulate:<some-tag>

and then gcloud docker -- push us.gcr.io/stat-350/symbulate:<some-tag>

and put that tag in singleuser.image instead of 'latest'?

Also can you try running the image manually after building it to see if that works? You can do that with:

`docker run -it us.gcr.io/stat-350/symbulate:<some-tag> /bin/bash`

and tell me what that produces?

**Comment by dlsun** [comment]
Thanks for all the help. I ended up deleting my Google Cloud container and making it from scratch, and that seems to have fixed the problem.
