### ISSUE TITLE
Cookie passing for Jupyter Notebook APIs

### ISSUE THREAD

**Issue by mrunmayeejog** [jupyterhub/jupyterhub#1431]
Currently using jupyterhub 0.7.0 I am facing the similar issue #1078. I can't upgrade to 0.8.0 version as of now.
I created a new API token using "jupyterhub token username" and added it jupyterhub configs file. With this I am able to access jupyterhub REST APIs. Same token can not be used for accessing jupyter notebook apis as in #1078 

Regarding authentication using cookies I have tried the following. I am testing APIs using Python's requests package. eg:
url = "http://127.0.0.1:8000/user/username/api/contents"
req = requests.get(url=url, cookies=<cookie_secret>)

This cookie_secret I am currently reading from the cookie_secret_file. But still unable to retrieve information. So is there a specific format for passing this cookie? I tried passing the value directly. I added it as dictionary 
{"cookie_name": "jupyter-hub-token-name"} but still got html content for login page. 
Now I am not sure of how to pass the cookie for these APIs.

**Comment by minrk** [comment]
The cookie_secret is an encryption key used for encrypting access tokens stored in cookies. It is not itself useful for authentication.

To login via the Hub, you have to submit the login form. Assuming you are using the default username+password authenticator, this is:

```python
login_url =  "http://127.0.0.1:8000/hub/login"
r = requests.post(login_url, data={'username': 'xxx', 'password': 'yyy'}, allow_redirects=False)
r.raise_for_status()
cookies = r.cookies
# now make a request to the user's server with the new cookies
url = "http://127.0.0.1:8000/user/username/api/contents"
r = requests.get(url, cookies=cookies)
```

Or, you can use `requests.Session` to preserve the cookies across requests for a given session.

**Comment by mrunmayeejog** [comment]
Thank you for helping me out.

**Comment by mrunmayeejog** [comment]
Using above I am able to make get requests. For post requests it says _xsrf token missing. I refered to [this post](https://blog.jupyter.org/2016/12/21/jupyter-notebook-4-3-1/) regarding _xsrf token which needs to be sent back for which I need to add to my headers. For this I checked, the cookies that I am preserving has no _xsrf. Whereas in browser I am able to see the _xsrf token.

**Comment by minrk** [comment]
Ah, yes. The xsrf token is a cross-site protection to verify that cookie-authenticated requests originate on pages served by the notebook server. You can disable this (not recommended), or you can fetch the xsrf cookie by requesting a human page:

```python
r = requests.get('http://127.0.0.1:8000/user/username/tree/', cookies=cookies)
xsrf_cookie = r.cookies['_xsrf']
cookies['_xsrf'] = xsrf_cookie
```

and then include this in the `X-XSRF-Token` header:

```python
url = "http://127.0.0.1:8000/user/username/api/contents"
r = requests.get(url, cookies=cookies, headers={'X-XSRF-Token': cookies['_xsrf']})
```

In general, this is pointing to the fact that it will be really nice to have true token authentication with JupyterHub 0.8, which doesn't have to deal with any of this.

**Comment by mrunmayeejog** [comment]
Thank you. And yes soon shall upgrade to 0.8 version :)
