### ISSUE TITLE
Opening terminal fails with "OSError('out of pty devices')" error

### ISSUE THREAD

**Issue by astrodb** [jupyterhub/jupyterhub#1440]
I'm running a Jupyerhub server and using the Systemd spawner on a baremetal setup.  The hub works, and users can login and create/run notebooks without issue, as well as work with files and folders.  But anytime they try to open a terminal through the Jupyterhub interface the new browser tab never appears, and I see the error below in the syslog.  The Jupyterhub logs don't show any errors.  

**How to reproduce the issue**
Login, select "New" -> "Terminal"

**What you expected to happen**
Terminal tab opens in browser.

**What actually happens**
Nothing in browser, error in syslog on server.  No errors in Jupyterhub log (even with debug turned on).

**Share what version of JupyterHub you are using**
jupyter (1.0.0)
jupyter-client (5.0.1)
jupyter-console (5.1.0)
jupyter-core (4.3.0)
jupyterhub (0.7.2)
jupyterhub-systemdspawner (0.9.10)

Authentication is PAM and I'm using the configurable-http-proxy.  

'cat /proc/sys/kernel/pty/max' produces '4096', and there aren't that many terminals, so it must be an error in my setup or elsewhere.  

```

Sep 21 11:57:48 lsstuk3 bash[4619]: [E 2017-09-21 11:57:48.329 msh handlers:527] Unhandled error in API request
Sep 21 11:57:48 lsstuk3 bash[4619]:     Traceback (most recent call last):
Sep 21 11:57:48 lsstuk3 bash[4619]:       File "/opt/anaconda/lib/python3.6/site-packages/notebook/base/handlers.py", line 516, in wrapper
Sep 21 11:57:48 lsstuk3 bash[4619]:         result = yield gen.maybe_future(method(self, *args, **kwargs))
Sep 21 11:57:48 lsstuk3 bash[4619]:       File "/opt/anaconda/lib/python3.6/site-packages/tornado/web.py", line 2897, in wrapper
Sep 21 11:57:48 lsstuk3 bash[4619]:         return method(self, *args, **kwargs)
Sep 21 11:57:48 lsstuk3 bash[4619]:       File "/opt/anaconda/lib/python3.6/site-packages/notebook/terminal/api_handlers.py", line 18, in post
Sep 21 11:57:48 lsstuk3 bash[4619]:         name, _ = self.terminal_manager.new_named_terminal()
Sep 21 11:57:48 lsstuk3 bash[4619]:       File "/opt/anaconda/lib/python3.6/site-packages/terminado/management.py", line 303, in new_named_terminal
Sep 21 11:57:48 lsstuk3 bash[4619]:         term = self.new_terminal()
Sep 21 11:57:48 lsstuk3 bash[4619]:       File "/opt/anaconda/lib/python3.6/site-packages/terminado/management.py", line 161, in new_terminal
Sep 21 11:57:48 lsstuk3 bash[4619]:         pty = PtyProcessUnicode.spawn(argv, env=env, cwd=options.get('cwd', None))
Sep 21 11:57:48 lsstuk3 bash[4619]:       File "/opt/anaconda/lib/python3.6/site-packages/ptyprocess/ptyprocess.py", line 220, in spawn
Sep 21 11:57:48 lsstuk3 bash[4619]:         pid, fd = pty.fork()
Sep 21 11:57:48 lsstuk3 bash[4619]:       File "/opt/anaconda/lib/python3.6/pty.py", line 96, in fork
Sep 21 11:57:48 lsstuk3 bash[4619]:         master_fd, slave_fd = openpty()
Sep 21 11:57:48 lsstuk3 bash[4619]:       File "/opt/anaconda/lib/python3.6/pty.py", line 29, in openpty
Sep 21 11:57:48 lsstuk3 bash[4619]:         master_fd, slave_name = _open_terminal()
Sep 21 11:57:48 lsstuk3 bash[4619]:       File "/opt/anaconda/lib/python3.6/pty.py", line 59, in _open_terminal
Sep 21 11:57:48 lsstuk3 bash[4619]:         raise OSError('out of pty devices')
Sep 21 11:57:48 lsstuk3 bash[4619]:     OSError: out of pty devices


```

**Comment by willingc** [comment]
Hi @astrodb, Can you post the output of `conda list`? Thanks.

**Comment by astrodb** [comment]
`# packages in environment at /opt/anaconda:
#
_license                  1.1                      py36_1
alabaster                 0.7.10                   py36_0
alembic                   0.9.5                     <pip>
anaconda                  4.4.0               np112py36_0
anaconda-client           1.6.3                    py36_0
anaconda-navigator        1.6.2                    py36_0
anaconda-project          0.6.0                    py36_0
asn1crypto                0.22.0                   py36_0
astroid                   1.4.9                    py36_0
astropy                   1.3.2               np112py36_0
babel                     2.4.0                    py36_0
backports                 1.0                      py36_0
beautifulsoup4            4.6.0                    py36_0
bitarray                  0.8.1                    py36_0
blaze                     0.10.1                   py36_0
bleach                    1.5.0                    py36_0
bokeh                     0.12.5                   py36_1
boto                      2.46.1                   py36_0
bottleneck                1.2.1               np112py36_0
cairo                     1.14.8                        0
cffi                      1.10.0                   py36_0
chardet                   3.0.3                    py36_0
click                     6.7                      py36_0
cloudpickle               0.2.2                    py36_0
clyent                    1.2.2                    py36_0
colorama                  0.3.9                    py36_0
conda                     4.3.21                   py36_0
conda-env                 2.6.0                         0
contextlib2               0.5.5                    py36_0
cryptography              1.8.1                    py36_0
curl                      7.52.1                        0
cycler                    0.10.0                   py36_0
cython                    0.25.2                   py36_0
cytoolz                   0.8.2                    py36_0
dask                      0.14.3                   py36_1
datashape                 0.5.4                    py36_0
dbus                      1.10.10                       0
decorator                 4.0.11                   py36_0
distributed               1.16.3                   py36_0
docutils                  0.13.1                   py36_0
entrypoints               0.2.2                    py36_1
et_xmlfile                1.0.1                    py36_0
expat                     2.1.0                         0
fastcache                 1.0.2                    py36_1
flask                     0.12.2                   py36_0
flask-cors                3.0.2                    py36_0
fontconfig                2.12.1                        3
freetype                  2.5.5                         2
get_terminal_size         1.0.0                    py36_0
gevent                    1.2.1                    py36_0
glib                      2.50.2                        1
greenlet                  0.4.12                   py36_0
gst-plugins-base          1.8.0                         0
gstreamer                 1.8.0                         0
h5py                      2.7.0               np112py36_0
harfbuzz                  0.9.39                        2
hdf5                      1.8.17                        1
heapdict                  1.0.0                    py36_1
html5lib                  0.999                    py36_0
icu                       54.1                          0
idna                      2.5                      py36_0
imagesize                 0.7.1                    py36_0
ipyaladin                 0.1.0                     <pip>
ipykernel                 4.6.1                    py36_0
ipython                   5.3.0                    py36_0
ipython_genutils          0.2.0                    py36_0
ipywidgets                6.0.0                    py36_0
isort                     4.2.5                    py36_0
itsdangerous              0.24                     py36_0
jbig                      2.1                           0
jdcal                     1.3                      py36_0
jedi                      0.10.2                   py36_2
jinja2                    2.9.6                    py36_0
jpeg                      9b                            0
jsonschema                2.6.0                    py36_0
jupyter                   1.0.0                    py36_3
jupyter_client            5.0.1                    py36_0
jupyter_console           5.1.0                    py36_0
jupyter_core              4.3.0                    py36_0
jupyterhub                0.7.2                     <pip>
jupyterhub-systemdspawner 0.9.10                    <pip>
lazy-object-proxy         1.2.2                    py36_0
libffi                    3.2.1                         1
libgcc                    4.8.5                         2
libgfortran               3.0.0                         1
libiconv                  1.14                          0
libpng                    1.6.27                        0
libsodium                 1.0.10                        0
libtiff                   4.0.6                         3
libtool                   2.4.2                         0
libxcb                    1.12                          1
libxml2                   2.9.4                         0
libxslt                   1.1.29                        0
llvmlite                  0.18.0                   py36_0
locket                    0.2.0                    py36_1
lxml                      3.7.3                    py36_0
Mako                      1.0.7                     <pip>
markupsafe                0.23                     py36_2
matplotlib                2.0.2               np112py36_0
mistune                   0.7.4                    py36_0
mkl                       2017.0.1                      0
mkl-service               1.1.2                    py36_3
mpmath                    0.19                     py36_1
msgpack-python            0.4.8                    py36_0
multipledispatch          0.4.9                    py36_0
navigator-updater         0.1.0                    py36_0
nbconvert                 5.1.1                    py36_0
nbformat                  4.3.0                    py36_0
networkx                  1.11                     py36_0
nltk                      3.2.3                    py36_0
nose                      1.3.7                    py36_1
notebook                  5.0.0                    py36_0
numba                     0.33.0              np112py36_0
numexpr                   2.6.2               np112py36_0
numpy                     1.12.1                   py36_0
numpydoc                  0.6.0                    py36_0
odo                       0.5.0                    py36_1
olefile                   0.44                     py36_0
openpyxl                  2.4.7                    py36_0
openssl                   1.0.2l                        0
packaging                 16.8                     py36_0
pamela                    0.3.0                     <pip>
pandas                    0.20.1              np112py36_0
pandocfilters             1.4.1                    py36_0
pango                     1.40.3                        1
partd                     0.3.8                    py36_0
path.py                   10.3.1                   py36_0
pathlib2                  2.2.1                    py36_0
patsy                     0.4.1                    py36_0
pcre                      8.39                          1
pep8                      1.7.0                    py36_0
pexpect                   4.2.1                    py36_0
pickleshare               0.7.4                    py36_0
pillow                    4.1.1                    py36_0
pip                       9.0.1                    py36_1
pixman                    0.34.0                        0
ply                       3.10                     py36_0
prompt_toolkit            1.0.14                   py36_0
psutil                    5.2.2                    py36_0
ptyprocess                0.5.1                    py36_0
py                        1.4.33                   py36_0
pycosat                   0.6.2                    py36_0
pycparser                 2.17                     py36_0
pycrypto                  2.6.1                    py36_6
pycurl                    7.43.0                   py36_2
pyflakes                  1.5.0                    py36_0
pygments                  2.2.0                    py36_0
pylint                    1.6.4                    py36_1
pyodbc                    4.0.16                   py36_0
pyopenssl                 17.0.0                   py36_0
pyparsing                 2.1.4                    py36_0
pyqt                      5.6.0                    py36_2
pytables                  3.3.0               np112py36_0
pytest                    3.0.7                    py36_0
python                    3.6.1                         2
python-dateutil           2.6.0                    py36_0
python-editor             1.0.3                     <pip>
pytz                      2017.2                   py36_0
pywavelets                0.5.2               np112py36_0
pyyaml                    3.12                     py36_0
pyzmq                     16.0.2                   py36_0
qt                        5.6.2                         4
qtawesome                 0.4.4                    py36_0
qtconsole                 4.3.0                    py36_0
qtpy                      1.2.1                    py36_0
readline                  6.2                           2
requests                  2.14.2                   py36_0
rope                      0.9.4                    py36_1
ruamel_yaml               0.11.14                  py36_1
scikit-image              0.13.0              np112py36_0
scikit-learn              0.18.1              np112py36_1
scipy                     0.19.0              np112py36_0
seaborn                   0.7.1                    py36_0
setuptools                27.2.0                   py36_0
simplegeneric             0.8.1                    py36_1
singledispatch            3.4.0.3                  py36_0
sip                       4.18                     py36_0
six                       1.10.0                   py36_0
snowballstemmer           1.2.1                    py36_0
sortedcollections         0.5.3                    py36_0
sortedcontainers          1.5.7                    py36_0
sphinx                    1.5.6                    py36_0
spyder                    3.1.4                    py36_0
sqlalchemy                1.1.9                    py36_0
sqlite                    3.13.0                        0
statsmodels               0.8.0               np112py36_0
sympy                     1.0                      py36_0
tblib                     1.3.2                    py36_0
terminado                 0.6                      py36_0
testpath                  0.3                      py36_0
tk                        8.5.18                        0
toolz                     0.8.2                    py36_0
tornado                   4.5.1                    py36_0
traitlets                 4.3.2                    py36_0
unicodecsv                0.14.1                   py36_0
unixodbc                  2.3.4                         0
wcwidth                   0.1.7                    py36_0
werkzeug                  0.12.2                   py36_0
wheel                     0.29.0                   py36_0
widgetsnbextension        2.0.0                    py36_0
wrapt                     1.10.10                  py36_0
xlrd                      1.0.0                    py36_0
xlsxwriter                0.9.6                    py36_0
xlwt                      1.2.0                    py36_0
xz                        5.2.2                         1
yaml                      0.1.6                         0
zeromq                    4.1.5                         0
zict                      0.1.2                    py36_0
zlib                      1.2.8                         3
`

**Comment by willingc** [comment]
@astrodb Could you try upgrading `ptyprocess` to 0.5.2?

[ref](https://github.com/jupyterhub/jupyterhub/issues/1108)

cc/@minrk

**Comment by astrodb** [comment]
I've tried this, but it complains about the fact that ptyprocess is part of a distutils installed project:

`root@host3:~# pip install ptyprocess-0.5.2-py2.py3-none-any.whl
Processing ./ptyprocess-0.5.2-py2.py3-none-any.whl
Installing collected packages: ptyprocess
  Found existing installation: ptyprocess 0.5.1
    DEPRECATION: Uninstalling a distutils installed project (ptyprocess) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling ptyprocess-0.5.1:
      Successfully uninstalled ptyprocess-0.5.1
Successfully installed ptyprocess-0.5.2`

It appears to have installed the new version but kept the old as well:
`root@host3:~# conda list | grep ptyprocess
ptyprocess                0.5.2                     <pip>
ptyprocess                0.5.1                    `py36_0`

And after restarting the Jupyterhub the problem persists, but I can't tell if that's due to it using the old version or not (since the old version is still installed).  Any suggestions on how to fully remove the old version without breaking things?

**Comment by willingc** [comment]
I would uninstall:
`pip uninstall -f ptyprocess==0.5.1`

Then:
`pip install --force-reinstall ptyprocess==0.5.2`

**Comment by astrodb** [comment]
Tried that, but no luck.  I restarted jupyterhub but the same thing happens.

`root@lsstuk3:~# pip uninstall -f ptyprocess==0.5.1

Usage:
  pip uninstall [options] <package> ...
  pip uninstall [options] -r <requirements file> ...

no such option: -f
root@lsstuk3:~# pip uninstall  ptyprocess==0.5.1
Uninstalling ptyprocess-0.5.2:
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess-0.5.2.dist-info/INSTALLER
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess-0.5.2.dist-info/LICENSE
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess-0.5.2.dist-info/METADATA
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess-0.5.2.dist-info/RECORD
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess-0.5.2.dist-info/WHEEL
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess/__init__.py
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess/__pycache__/__init__.cpython-36.pyc
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess/__pycache__/_fork_pty.cpython-36.pyc
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess/__pycache__/ptyprocess.cpython-36.pyc
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess/__pycache__/util.cpython-36.pyc
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess/_fork_pty.py
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess/ptyprocess.py
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess/util.py
Proceed (y/n)? y
  Successfully uninstalled ptyprocess-0.5.2
root@lsstuk3:~# pip uninstall  ptyprocess==0.5.1
Cannot uninstall requirement ptyprocess, not installed
root@lsstuk3:~# pip install --force-reinstall ptyprocess==0.5.2
Collecting ptyprocess==0.5.2
  Downloading ptyprocess-0.5.2-py2.py3-none-any.whl
Installing collected packages: ptyprocess
Successfully installed ptyprocess-0.5.2
root@lsstuk3:~# conda list | grep ptyprocess
ptyprocess                0.5.2                     <pip>
ptyprocess                0.5.1                    py36_0
`

**Comment by willingc** [comment]
Try:
`python3 -m pip uninstall ptyprocess==0.5.1`

**Comment by astrodb** [comment]
Same as before:
`root@lsstuk3:~# python3 -m pip uninstall ptyprocess==0.5.1
Uninstalling ptyprocess-0.5.2:
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess-0.5.2.dist-info/INSTALLER
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess-0.5.2.dist-info/LICENSE
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess-0.5.2.dist-info/METADATA
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess-0.5.2.dist-info/RECORD
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess-0.5.2.dist-info/WHEEL
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess/__init__.py
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess/__pycache__/__init__.cpython-36.pyc
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess/__pycache__/_fork_pty.cpython-36.pyc
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess/__pycache__/ptyprocess.cpython-36.pyc
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess/__pycache__/util.cpython-36.pyc
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess/_fork_pty.py
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess/ptyprocess.py
  /opt/anaconda/lib/python3.6/site-packages/ptyprocess/util.py
Proceed (y/n)? Y
  Successfully uninstalled ptyprocess-0.5.2
`

Which does seem to imply it is using the latest version.

**Comment by willingc** [comment]
I think that you have now uninstalled 0.5.2.

```
python3 -m pip uninstall ptyprocess
python3 -m pip install ptyprocess==0.5.2
```

**Comment by astrodb** [comment]
All the different "uninstall" commands report removing 0.5.2, and then after that I reinstall it.  I'm guessing that that's the version that is installed and operating, and the 0.5.1 reference is residual and not applicable to the the environment anymore (but is leftover as part of the distributils packaging).

**Comment by willingc** [comment]
Sure. I'm unsure of other reasons that you may be seeing the error. @minrk thoughts?

**Comment by astrodb** [comment]
Yes, Juptyerhub launches at boot.  But I've restarted it after boot and the problem persists, so I don't think the pty setup is causing the issue.

**Comment by minrk** [comment]
I've no idea what could be causing something like this. Since systemd is being used, my only guess is that there might be other limits applied to the systemd processes somewhere. I only found [this](https://stackoverflow.com/questions/8561121/troubleshooting-oserror-out-of-pty-devices). Do you happen to be launching jupyterhub at boot? If so, maybe it's running too early before pty things are setup correctly?

**Comment by haasad** [comment]
Had the same problem. Do you use `c.SystemdSpawner.isolate_devices=True` in your config? Setting it to False made jupyterhub work as expected in my case.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻

**Comment by lucidsushi** [comment]
The fastest way to reproduce this may be:
`import pty`
`pty.fork()`
Which should yield the errors listed above.

And `grep --color devpts /proc/mounts` in a terminal may show `devpts` is not mounted, not not mounted as `gid=5`
