### ISSUE TITLE
Server can't start and error is: subprocess.SubprocessError: Exception occurred in preexec_fn

### ISSUE THREAD

**Issue by jm2004** [jupyterhub/jupyterhub#1444]
I am new on Jupyterhub. 
Details please refer below details.

**Comment by jm2004** [comment]
I follow this wiki for install jupyterhub in AWS, and adapt some names on my application:
https://github.com/jupyterhub/jupyterhub/wiki/Installation-of-Jupyterhub-on-remote-server

Everything  works fine, until when I login as admin then want to start server from admin page.
----------- Error ----------------------------------------------------------------------------
[E 2017-09-22 23:22:25.625 JupyterHub web:1590] Uncaught exception GET /hub/user/jm2004 (::ffff:50.131.113.235)
    HTTPServerRequest(protocol='https', host='54.83.184.142:8000', method='GET', uri='/hub/user/jm2004', version='HTTP/1.1', remote_ip='::ffff:50.131.113.235', headers={'Accept-Encoding': 'gzip, deflate, br', 'Cookie': 'jupyter-hub-token="2|1:0|10:1506122379|17:jupyter-hub-token|44:OTdmYjBiY2QyMzgxNGQxNDg5ODJiYjZmMDVhOGU4NzE=|82df2c3160fd95b41b4e05d53e719b7255114ed338d22769e3fb88adac29b9ca"', 'Host': '54.83.184.142:8000', 'X-Forwarded-Proto': 'https', 'X-Forwarded-For': '::ffff:50.131.113.235', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Referer': 'https://54.83.184.142:8000/hub/home', 'Connection': 'close', 'Accept-Language': 'en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4', 'X-Forwarded-Host': '54.83.184.142:8000', 'Upgrade-Insecure-Requests': '1', 'X-Forwarded-Port': '8000', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36'})
    Traceback (most recent call last):
      File "/home/ubuntu/.local/lib/python3.5/site-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/home/ubuntu/.local/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 535, in get
        yield self.spawn_single_user(current_user)
      File "/home/ubuntu/.local/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 328, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/home/ubuntu/.local/lib/python3.5/site-packages/jupyterhub/user.py", line 261, in spawn
        raise e
      File "/home/ubuntu/.local/lib/python3.5/site-packages/jupyterhub/user.py", line 229, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/lib/python3.5/types.py", line 243, in wrapped
        coro = func(*args, **kwargs)
      File "/home/ubuntu/.local/lib/python3.5/site-packages/jupyterhub/spawner.py", line 787, in start
        start_new_session=True, # don't forward signals
      File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.5/subprocess.py", line 1552, in _execute_child
        raise child_exception_type(err_msg)
    subprocess.SubprocessError: Exception occurred in preexec_fn.
----------------------- Error ends -----------------------

What did I miss?

**Comment by misolietavec** [comment]
Maybe you can get some AWS-specific information also from `https://github.com/jupyterhub/jupyterhub/wiki/Deploying-JupyterHub-on-AWS`?

**Comment by willingc** [comment]
Hi @jm2004, I'm not sure why you are receiving the error. I would recommend using the [Zero to JupyterHub guide](http://zero-to-jupyterhub.readthedocs.io/en/latest/) and [its AWS section](http://zero-to-jupyterhub.readthedocs.io/en/latest/create-k8s-cluster.html#setting-up-kubernetes-on-amazon-web-services-aws) instead of the wiki instructions.

**Comment by jm2004** [comment]
@willingc  Thanks! I will check out the doc. BTW, it turns out there are some files/folders' access were not set correctly. And I also successfully start the jupyterhub with "sudo".

@misolietavec  Thanks! I find the instructions are very useful!

**Comment by shreeishitagupta** [comment]
I am getting the same error while i am using native authenticator and trying to add user from the signup page. The server is not spawning for them. So i added this in my jupyter_config file:
c.Authenticator.admin_users = {'admin'}
c.Authenticator.open_signup = True
c.LocalAuthenticator.create_system_users = True
from jupyterhub.auth import LocalAuthenticator
from nativeauthenticator import NativeAuthenticator
class LocalNativeAuthenticator(NativeAuthenticator, LocalAuthenticator):
  pass
c.JupyterHub.authenticator_class = LocalNativeAuthenticator
c.Spawner.default_url = '/lab'

But now i am getting different error 
Traceback (most recent call last):
      File "/home/fkuser/.local/lib/python3.7/site-packages/jupyterhub/app.py", line 1741, in init_users
        await maybe_future(f)
      File "/home/fkuser/.local/lib/python3.7/site-packages/jupyterhub/auth.py", line 829, in add_user
        await maybe_future(self.add_system_user(user))
      File "/home/fkuser/.local/lib/python3.7/site-packages/jupyterhub/auth.py", line 895, in add_system_user
        raise RuntimeError("Failed to create system user %s: %s" % (name, err))
    RuntimeError: Failed to create system user test: adduser: Only root may add a user or group to the system.
    
and when i am logging in to jupyter notebook upon starting the server i am getting 
500 : Internal Server Error
Error in Authenticator.pre_spawn_start: SubprocessError Exception occurred in preexec_fn.
