### ISSUE TITLE
+1 On blog post for the release.

### ISSUE THREAD

**Issue by Carreau** [jupyterhub/jupyterhub#1447]
Not sure on how to comment on the draft submitted by MinRK on Medium, so just adding +1 here. 

Just one sentence may need rework, but it's early here, so reading is hard:

> CHP can handle a lot of concurrent users (at least several thousand), but for larger scale deployments, Hub deployments may want to use a more scalable and/or robust proxy implementation 

That's a repetition of deployment that feel weird. Also `CHP` is undefined, but I guess people who will read that will know what it is.

**Comment by willingc** [comment]
@minrk Comments left on draft. +1 to the post and @Carreau's suggested changes.

**Comment by yuvipanda** [comment]
Where is this draft?

**Comment by Carreau** [comment]
> Where is this draft?

https://medium.com/jupyter-blog/stories/submissions

**Comment by Carreau** [comment]
Hum, you don't seem to be admin. I'll try to add you.

**Comment by Carreau** [comment]
You should have access now.

**Comment by yuvipanda** [comment]
Cool! I also left some comments!

**Comment by minrk** [comment]
I was going to ping people for comments, but you got there first! This is planned to go up when the final release is out, so in a week or two.

**Comment by willingc** [comment]
@minrk Thanks! Congrats everyone on the release :tada:
