### ISSUE TITLE
jupyterhub extra log

### ISSUE THREAD

**Issue by kiwi0217** [jupyterhub/jupyterhub#1450]
how can i write all log appear on the screen into "extra_log_file"
i found lots of log appear on the screen but not write into file

**Comment by kiwi0217** [comment]
i resolved by using "nohup jupyterhub > /var/log/jupyter_screen.log" in terminal
hope can help somebody.

**Comment by minrk** [comment]
I would generally recommend running jupyterhub with

    jupyterhub &>> /var/log/jupyterhub.log

to capture log output and *not* extra_log_file, which only captures a fraction of jupyterhub output. The docs should now reflect this.
