### ISSUE TITLE
Use different alembic.ini file.

### ISSUE THREAD

**Issue by Siecje** [jupyterhub/jupyterhub#1451]
I need to use a different `alembic.ini` file. For me I need to set `sourceless = true`.

I've been monkey patching `jupyterhub.dbutil.ALEMBIC_INI_TEMPLATE_PATH` with a different path.

It would be nice if this was available in the `jupyterhub_config.py` file.

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue with full details of your use-case, so we can understand why it's needed. Thanks!

**Comment by Siecje** [comment]
The action point is to support sourceless installs.
