### ISSUE TITLE
Release 0.8

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#1464]
I think we are ready for releasing 0.8!

I think we can push the release out after the team meeting today.

# Release checklist

- [x] Upgrade Docs prior to Release

    - [x] Change log
    - [x] New features documented
    - [x] Update the contributor list - thank you page @willingc ?

- [x] Upgrade and test Reference Deployments

- [x] Release software

    - [x] Make sure 0 issues in milestone
    - [x] Follow release process steps
    - [x] Send builds to PyPI (Warehouse) and Conda Forge

- [x] Blog post and/or release note (drafted on Medium, will post when release is live)

- [x] Notify users of release

    - [x] Email Jupyter and Jupyter In Education mailing lists 
    - [x] Tweet (optional)

- [x] Increment the version number for the next release

- [x] Update roadmap

**Comment by willingc** [comment]
@minrk Updated contributors 2 weeks ago. No new faces since that commit 👍

**Comment by minrk** [comment]
Pushed to PyPI, published [blog](https://blog.jupyter.org/jupyterhub-0-8-19b00b75e3df), spreading via other channels over the next few minutes. Yay!
