### ISSUE TITLE
Bad config encountered during initialization - Spawner failed to start [status=1] on ubuntu

### ISSUE THREAD

**Issue by mmchougule** [jupyterhub/jupyterhub#1467]
I created a module okta.py which looks similar to /oauthenticator/auth0.py. This helped me login to JupyterHub from Okta. But when I click on "Start my server" I get this error:

When I try to enter my credentials instead of using an OAuthenticator module, I am still getting the same error.

```
JupyterHub base:345] User logged in: mayur
JupyterHub log:122] 302 GET /hub/oauth_callback?code=fk06WF4m0r1y-2bl93KT&state=eyJuZXh0X3VybCI6ICIiLCAic3RhdGVfaWQiOiAiNTZmYzVhMDA1ZTJmNGZhNWFkODI1NjFkMWFhZDRiZTgifQ%3D%3D → /hub/ (@::ffff:63.118.133.42) 370.54ms
JupyterHub log:122] 302 GET /hub/ → /hub/home (mayur@::ffff:63.118.133.42) 1.69ms
JupyterHub log:122] 200 GET /hub/home (mayur@::ffff:63.118.133.42) 6.20ms
JupyterHub log:122] 302 GET /hub/spawn → /user/mayur/ (mayur@::ffff:63.118.133.42) 2.60ms
JupyterHub log:122] 302 GET /user/mayur/ → /hub/user/mayur/ (@::ffff:63.118.133.42) 0.45ms
JupyterHub spawner:978] Spawning jupyterhub-singleuser --port=60097
Single-user server for JupyterHub. Extends the Jupyter Notebook server.

Meant to be invoked by JupyterHub Spawners, and not directly.

Then a bunch of options 

SingleUserNotebookApp application:90] Bad config encountered during initialization:
SingleUserNotebookApp application:91] The 'ip' trait of a SingleUserNotebookApp instance must be a unicode string, but a value of None <class 'NoneType'> was specified.
JupyterHub web:1587] 500 GET /hub/user/mayur/ (::ffff:63.118.133.42): Spawner failed to start [status=1]. The logs for mayur may contain details.

JupyterHub log:122] 500 GET /hub/user/mayur/ (mayur@::ffff:63.118.133.42) 10059.42ms
JupyterHub user:458] mayur's server never showed up at http://127.0.0.1:60097/user/mayur/ after 30 seconds. Giving up
JupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at 0x7f1e79c15e48> after timeout

```

My 'jupyterhub_config.py' looks like this:

```
c = get_config()
from oauthenticator.okta import *

c.JupyterHub.authenticator_class = 'oauthenticator.okta.OktaOAuthenticator'
c.OktaOAuthenticator.create_system_users = True
c.OktaOAuthenticator.whitelist = {'mayurchougule1@gmail.com', 'mayur'}
c.OktaOAuthenticator.admin_users = {'mayur'}

```

I am trying to figure out what the "Bad configuration" message is.

Can anyone please help me understand if I am doing anything wrong when starting my server?

```
jupyter troubleshoot

DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
$PATH:
	/usr/local/bin
	/home/ubuntu/bin
	/home/ubuntu/.local/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin

sys.path:
	/usr/local/bin
	/usr/lib/python35.zip
	/usr/lib/python3.5
	/usr/lib/python3.5/plat-x86_64-linux-gnu
	/usr/lib/python3.5/lib-dynload
	/home/ubuntu/.local/lib/python3.5/site-packages
	/home/ubuntu/play_jupyter/oauthenticator
	/usr/local/lib/python3.5/dist-packages
	/usr/lib/python3/dist-packages

sys.executable:
	/usr/bin/python3

sys.version:
	3.5.2 (default, Sep 14 2017, 22:51:06) 
	[GCC 5.4.0 20160609]

platform.platform():
	Linux-4.4.0-1022-aws-x86_64-with-Ubuntu-16.04-xenial

which -a jupyter:
	/usr/local/bin/jupyter
	/usr/local/bin/jupyter

pip list:
	backports-abc (0.5)
	backports.shutil-get-terminal-size (1.0.0)
	bleach (2.1)
	certifi (2017.7.27.1)
	configparser (3.5.0)
	decorator (4.1.2)
	entrypoints (0.2.3)
	enum34 (1.1.6)
	functools32 (3.2.3.post2)
	gyp (0.1)
	html5lib (1.0b10)
	ipykernel (4.6.1)
	ipython (5.5.0)
	ipython-genutils (0.2.0)
	Jinja2 (2.9.6)
	jsonschema (2.6.0)
	jupyter-client (5.1.0)
	jupyter-core (4.3.0)
	MarkupSafe (1.0)
	mistune (0.7.4)
	nbconvert (5.3.1)
	nbformat (4.4.0)
	notebook (5.1.0)
	pandocfilters (1.4.2)
	pathlib2 (2.3.0)
	pexpect (4.2.1)
	pickleshare (0.7.4)
	pip (9.0.1)
	prompt-toolkit (1.0.15)
	ptyprocess (0.5.2)
	Pygments (2.2.0)
	python-dateutil (2.6.1)
	pyzmq (16.0.2)
	scandir (1.6)
	scour (0.32)
	setuptools (36.5.0)
	simplegeneric (0.8.1)
	singledispatch (3.4.0.3)
	six (1.11.0)
	terminado (0.6)
	testpath (0.3.1)
	tornado (4.5.2)
	traitlets (4.3.2)
	wcwidth (0.1.7)
	webencodings (0.5.1)
	wheel (0.29.0)


```

**Comment by minrk** [comment]
What version of JupyterHub is this? I don't see jupyterhub in pip list.

**Comment by mmchougule** [comment]
jupyterhub --version: 0.8.0
<img width="388" alt="screen shot 2017-10-05 at 12 42 47 pm" src="https://user-images.githubusercontent.com/18723323/31239425-077f3f36-a9cb-11e7-96f6-9250f91e161a.png">

I am on an AWS EC2 instance. This worked on my Mac as a localhost.

**Comment by mmchougule** [comment]
@minrk something looks different? I changed some code for OAuthenticator but I just followed the steps mentioned on the main repo to install jupyterhub.

**Comment by minrk** [comment]
What's `pip3 list` just to be sure?

**Comment by mmchougule** [comment]
pip3 list shows this:

ubuntu@ip:~/jhubtest$ pip3 list
alembic (0.9.5)
apparmor (2.10.95)
bleach (2.1)
blinker (1.3)
certifi (2017.7.27.1)
chardet (3.0.4)
cloud-init (0.7.9)
command-not-found (0.3)
configobj (5.0.6)
cryptography (1.2.3)
decorator (4.1.2)
entrypoints (0.2.3)
html5lib (1.0b10)
idna (2.6)
ipykernel (4.6.1)
ipython (6.2.0)
ipython-genutils (0.2.0)
jedi (0.11.0)
Jinja2 (2.9.6)
jsonpatch (1.10)
jsonpointer (1.9)
jsonschema (2.6.0)
jupyter-client (5.1.0)
jupyter-core (4.3.0)
jupyterhub (0.8.0)
language-selector (0.1)
LibAppArmor (2.10.95)
Mako (1.0.7)
MarkupSafe (1.0)
mistune (0.7.4)
nbconvert (5.3.1)
nbformat (4.4.0)
notebook (5.1.0)
oauthenticator (0.8.0.dev0, /home/ubuntu/play_jupyter/oauthenticator)
oauthlib (1.0.3)
pamela (0.3.0)
pandocfilters (1.4.2)
parso (0.1.0)
pexpect (4.2.1)
pickleshare (0.7.4)
pip (8.1.1)
prettytable (0.7.2)
prompt-toolkit (1.0.15)
ptyprocess (0.5.2)
pyasn1 (0.1.9)
pycurl (7.43.0)
Pygments (2.2.0)
pygobject (3.20.0)
PyJWT (1.3.0)
pyserial (3.0.1)
python-apt (1.1.0b1)
python-dateutil (2.6.1)
python-debian (0.1.27)
python-editor (1.0.3)
python-oauth2 (1.0.1)
python-systemd (231)
PyYAML (3.11)
pyzmq (16.0.2)
requests (2.18.4)
setuptools (36.5.0)
simplegeneric (0.8.1)
six (1.11.0)
SQLAlchemy (1.1.14)
ssh-import-id (5.5)
terminado (0.6)
testpath (0.3.1)
tornado (4.5.2)
traitlets (4.3.2)
ufw (0.35)
unattended-upgrades (0.1)
urllib3 (1.22)
wcwidth (0.1.7)
webencodings (0.5.1)
wheel (0.29.0)

**Comment by minrk** [comment]
That's very strange. What happens if you set:

```python
c.Spawner.ip = '127.0.0.1'
```

in your jupyterhub_config.py?

**Comment by mmchougule** [comment]
I added that line to my jupyterhub_config.py

This is what I am seeing, which is strange. pip3 list shows the right version.

> 500 : Internal Server Error
> Redirect loop detected. Notebook has jupyterhub version unknown (likely < 0.8), but the Hub expects 0.8.0. Try installing jupyterhub==0.8.0 in the user environment if you continue to have problems.
> You can try restarting your server from the home page.

If I remove that line, then I get the same error as before. 

> Spawner failed to start [status=1]
> Bad config encountered during initialization

I also tried to remove my OktaOAuthenticator and the new jupyterhub_config.py looks like this:

```
c = get_config()
c.Authenticator.admin_users = {'mayur', 'mayurnew'}
# c.Spawner.ip = '127.0.0.1'

```

I still see the same error.

**Comment by minrk** [comment]
What do you get from `which -a jupyterhub-singleuser`? Do you have any other Python installations?

**Comment by mmchougule** [comment]
For this: which -a jupyterhub-singleuser

> ubuntu@ip:/usr/bin$ which -a jupyterhub-singleuser
> /home/ubuntu/.local/bin/jupyterhub-singleuser
> /usr/local/bin/jupyterhub-singleuser


And I have python 2.7.12 and 3.5.2 installed.
 
> /usr/bin$ ls -ls /usr/bin/python*
   0 lrwxrwxrwx 1 root root       9 Dec 10  2015 /usr/bin/python -> python2.7
   0 lrwxrwxrwx 1 root root       9 Dec 10  2015 /usr/bin/python2 -> python2.7
3464 -rwxr-xr-x 1 root root 3546104 Nov 19  2016 /usr/bin/python2.7
   0 lrwxrwxrwx 1 root root      33 Nov 19  2016 /usr/bin/python2.7-config -> x86_64-linux-gnu-python2.7-config
   0 lrwxrwxrwx 1 root root      16 Dec 10  2015 /usr/bin/python2-config -> python2.7-config
   0 lrwxrwxrwx 1 root root       9 Mar 23  2016 /usr/bin/python3 -> python3.5
4352 -rwxr-xr-x 2 root root 4456240 Sep 18 15:59 /usr/bin/python3.5
   0 lrwxrwxrwx 1 root root      33 Sep 18 15:59 /usr/bin/python3.5-config -> x86_64-linux-gnu-python3.5-config
4352 -rwxr-xr-x 2 root root 4456240 Sep 18 15:59 /usr/bin/python3.5m
   0 lrwxrwxrwx 1 root root      34 Sep 18 15:59 /usr/bin/python3.5m-config -> x86_64-linux-gnu-python3.5m-config
   0 lrwxrwxrwx 1 root root      16 Mar 23  2016 /usr/bin/python3-config -> python3.5-config
   4 -rwxr-xr-x 1 root root     976 Nov 27  2015 /usr/bin/python3-jsondiff
   4 -rwxr-xr-x 1 root root    3662 Nov 27  2015 /usr/bin/python3-jsonpatch
   4 -rwxr-xr-x 1 root root    1342 Oct 24  2015 /usr/bin/python3-jsonpointer
   0 lrwxrwxrwx 1 root root      10 Mar 23  2016 /usr/bin/python3m -> python3.5m
   0 lrwxrwxrwx 1 root root      17 Mar 23  2016 /usr/bin/python3m-config -> python3.5m-config
   0 lrwxrwxrwx 1 root root      16 Dec 10  2015 /usr/bin/python-config -> python2.7-config

**Comment by mmchougule** [comment]
Also, to test on another machine, I deployed it on another EC2 instance. It is working on that instance correctly except for one issue.
When I try to login as "ubuntu" user which has root permissions, I am able to start a server. But if I try to create a new user as "sudo adduser mayur" -> Enter password. It cannot start a server for new users, it throws this error: 

> subprocess.SubprocessError: Exception occurred in preexec_fn.

It is probably not related to the current issue I asked but I thought I would mention it.

**Comment by minrk** [comment]
@mmchougule okay! I think I know the issue. In general, you do not want to have jupyterhub installed `--user` because *all* users need to have access to jupyterhub to run their servers. You have two installations: one in `/usr/local/bin` and one in `/home/ubuntu/.local/bin`. My guess is that one of these is the version of the Hub you are launching (0.8) and the other gets launched by the single-user process, likely due to a change in PATH for the subprocess.

The course of action I would recommend:

1. remove the installation in `/home/ubuntu`. This is probably `pip uninstall jupyterhub` as the `ubuntu` user.
2. make sure the system-wide installation is up-to-date. `sudo pip install 'jupyterhub==0.8.*'`
3. double check that you only have one jupyterhub: `which -a jupyterhub` should only return one result, and it should be accessible by all users (e.g. in `/usr/local`)

**Comment by mmchougule** [comment]
@minrk thank you so much. I will try and update here.

**Comment by mmchougule** [comment]
@minrk 
Thank you, again! It worked on both machines. I had to uninstall everything from /home/ubuntu/.local/lib/python3.5/site-packages and install jupyter, notebook, jupyterhub in /usr/local. I am able to login and start servers now.

**Comment by ihleonard-c3** [comment]
@mmchougule How difficult was adding Okta OAuth support? Did you use OpenID Connect or SAML? Thanks in advance

**Comment by mmchougule** [comment]
@ihleonard-c3 It was easy, I used auth0 as a reference and modified generic authenticator a little bit. I used OpenID Connect basic flow. I can maybe create a pull request so we can have an example on OAuthenticator.

**Comment by ihleonard-c3** [comment]
I'd really appreciate it @mmchougule. Thanks!

**Comment by tyrsius** [comment]
@mmchougule Are you still planning to open a PR for that okta module?
