### ISSUE TITLE
Jupyterhub latex template file

### ISSUE THREAD

**Issue by mjsir911** [jupyterhub/jupyterhub#1468]
I need to be able to export notebooks to pdfs without numbering the sections. I've found documentation with nbconvert to set a template file, and I found this [post](https://stackoverflow.com/a/20275438) to set the template file to not number sections.

Now I need to be able to export to pdf through the web interface without numbering. I have tried configuring jupyterhub to use a different default template. This does not seem to work, and as a quick fix I had to change the nbconvert source code to use my template instead of the article template.

**How to reproduce the issue**
Create file `/usr/local/lib/python3.4/dist-packages/nbconvert/templates/latex/secnum.tplx`
```
((* extends 'article.tplx' *))

((* block commands *))
\setcounter{secnumdepth}{0} % Turns off numbering for sections
((( super() )))
((* endblock commands *))
```

I got this from [here](https://stackoverflow.com/a/20275438)

-----------------
In the jupyterhub `config.py` 
``` python
c.LatexExporter.template_file = 'secnum'
```

**What you expected to happen**
When downloading a notebook as pdf, the sections are not numbered

**What actually happens**
The sections are numbered, makes me think the secnum.tplx file is not being used

**Share what version of JupyterHub you are using**
``` bash
$ jupyterhub --version
0.7.2
```

``` bash
$ jupyter troubleshoot
$PATH:
	/usr/local/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin

sys.path:
	/usr/local/bin
	/usr/lib/python3.4
	/usr/lib/python3.4/plat-x86_64-linux-gnu
	/usr/lib/python3.4/lib-dynload
	/usr/local/lib/python3.4/dist-packages
	/usr/lib/python3/dist-packages

sys.executable:
	/usr/bin/python3

sys.version:
	3.4.2 (default, Oct  8 2014, 10:45:20) 
	[GCC 4.9.1]

platform.platform():
	Linux-4.9.36-x86_64-linode85-x86_64-with-debian-8.9

which -a jupyter:
	/usr/local/bin/jupyter
	/usr/local/bin/jupyter
```

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
