### ISSUE TITLE
JupyterHub PAM authentication with google two-factor login

### ISSUE THREAD

**Issue by gryslik** [jupyterhub/jupyterhub#1469]
This is for the default install of Jupyterhub. I'm setting this up on a linux AMI .

The login requires both a username and a google-authenticator time based token. When I ssh in it asks for both.

When I installed RStudio server-- it just automagically asks for the username and not the token. 

When I run Jupyterhub it always fails to authenticate against the user -- I believe it's because of the two factor authnetication.

Is there a way to get Jupyterhub to just use the password (like RStudio does) or ask for both the username and password?

I tried copying the entry in `/etc/pam.d` for rstudio into jupyterhub but that wasn't effective. For reference, here's the rstudio `/etc/pam.d/rstudio` file:
```
#%PAM-1.0
auth      requisite      pam_succeed_if.so uid >= 500 quiet
auth      required       pam_unix.so nodelay

account   required       pam_unix.so
```

Perhaps I need to restart a service after creating `/etc/pam.d/jupyterhub`?

**Comment by willingc** [comment]
Thanks for the question @gryslik.

@minrk Thoughts? Would this be a good use case for nbrsessionproxy and nbserverproxy?

**Comment by minrk** [comment]
That's an excellent question! I haven't tried PAM with 2fa before. How did the 2FA get setup in the first place?

**Comment by darth-veitcher** [comment]
I'd be interested in this also having in the past used `libpam-google-authenticator` to configure 2FA

Happy to share the Ansible stub I've used successfully to provision users and edit `/etc/pam.d/` to force usage if it'll help?

**Comment by saransha** [comment]
so is it possible to use jupyterhub with google authenticator pam module? I tried to add
"auth required pam_google_authenticator.so nullok" to pam.d login but it just fails to authenticate.
Is there anywat to get the jupyterhub webapp to ask for verification code as well? what code will i have to change? Thank you.

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!
