### ISSUE TITLE
JupyterHub app:924] **Proxy appears to be running at http://*:8000/, but I can't access it (HTTP 403: Forbidden)** on Jupyter startup

### ISSUE THREAD

**Issue by lucy-itjob** [jupyterhub/jupyterhub#1470]
Hi Willingc,

We I try to restart the Jupyther Hub, Here is the error

########Error########
 [I 2017-10-06 10:13:34.703 JupyterHub app:622] Loading cookie_secret from /root/jupyterhub_cookie_secret
 [W 2017-10-06 10:13:34.732 JupyterHub app:304]
 Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
 Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[W 2017-10-06 10:13:34.736 JupyterHub app:757] No admin users, admin interface will be unavailable.
 [W 2017-10-06 10:13:34.736 JupyterHub app:758] Add any administrative users to  c.Authenticator.admin_users  in config.
 [I 2017-10-06 10:13:34.736 JupyterHub app:785] Not using whitelist. Any authenticated user will be allowed.
 [I 2017-10-06 10:13:34.753 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
 [E 2017-10-06 10:13:34.768 JupyterHub app:924] **Proxy appears to be running at http://*:8000/, but I can't access it (HTTP 403: Forbidden)**
 Did CONFIGPROXY_AUTH_TOKEN change?

################
After I log into Jupyter hub http://vcld005276.rw.discoverfinancial.com:8000/hub/login,

I got the blank screen, then Service Unavailable.

**Comment by lucy-itjob** [comment]
[jupyterhub_config.py.txt](https://github.com/jupyterhub/jupyterhub/files/1363304/jupyterhub_config.py.txt)
jupyterhub_config.py attached.

Thank you for your quick response

**Comment by lucy-itjob** [comment]
I also attaché the jupyter troubleshoot result here
[5276_jupyter_t.txt](https://github.com/jupyterhub/jupyterhub/files/1363443/5276_jupyter_t.txt)

Can someone help it out here? Thank you for your quick response

**Comment by lucy-itjob** [comment]
I result this issue

**Comment by willingc** [comment]
Hi @lucy-itjob, 

Sorry for the delay in responding. I've been traveling for work.

From your `jupyter troubleshoot` file, it looks as if you are running Python 3.3 and JupyterHub 0.6.1. Both of these are old versions. Python 3.3 reached end of life last month [ref](https://docs.python.org/devguide/#status-of-python-branches) and the current rele
