### ISSUE TITLE
Implement activity tracking as an external service

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#1471]
Most distributed custom proxy implementations can not support last_activity_timestamp recording. While we could just implement this directly in JupyterHub, that just adds another pseudo-process running in-process inside JupyterHub with its own loop. 

Instead, I propose we have an external service whose sole job is to poll notebook servers and update the last_activity_timestamp in JupyterHub via an API call. This gives us a bunch of advantages:

1. Code is cleaner & super de-coupled from JupyterHub itself. Is probably just a single standalone file
2. Scales better, since the JupyterHub process is making less network requests that scale linearly with total number of users.
3. Provides a nice framework for doing similar things in the future.

We could also write this in a way that it runs in-process by default, but can run as a separate process if needed. That might allow us to spin out several other similar processes (such as the proxy route checker) if necessary for scaling, while still keeping them in process for ease of deployment for smaller installations.

**Comment by manics** [comment]
Is this still desired?

**Comment by yuvipanda** [comment]
Notebook servers now report their activity to JupyterHub, which solves this problem
