### ISSUE TITLE
jupyterhub 0.8.0 admin button missing

### ISSUE THREAD

**Issue by bbrauns** [jupyterhub/jupyterhub#1472]
Hey there, since jupyterhub 0.8.0 the admin button in my control panel is missing...however manually navigating to /hub/admin works.
![image](https://user-images.githubusercontent.com/6813310/31338838-248e9fb6-ad01-11e7-901c-3f48f6cf9e12.png)

then

![image](https://user-images.githubusercontent.com/6813310/31338890-47e8b492-ad01-11e7-8cc3-c0ac74ea2aad.png)

**Share what version of JupyterHub you are using**
0.8.0

Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.

```
root@93b2c665f483:/srv/jupyterhub# jupyterhub troubleshoot
[W 2017-10-09 12:40:13.608 JupyterHub app:387] JupyterHub.proxy_auth_token is deprecated in JupyterHub 0.8, use ConfigurableHTTPProxy.auth_token
[W 2017-10-09 12:40:13.609 JupyterHub app:509] JupyterHub.api_tokens is pending deprecation since JupyterHub version 0.8.  Consider using JupyterHub.service_tokens.  If you have a use case for services that identify as users, let us know: https://github.com/jupyterhub/jupyterhub/issues
[I 2017-10-09 12:40:13.710 JupyterHub app:994] Not using whitelist. Any authenticated user will be allowed.
[W 2017-10-09 12:40:13.754 JupyterHub dockerspawner:125] DockerSpawner.container_image is deprecated in dockerspawner 0.9.  Use DockerSpawner.image
[W 2017-10-09 12:40:13.770 JupyterHub dockerspawner:125] DockerSpawner.container_image is deprecated in dockerspawner 0.9.  Use DockerSpawner.image
[I 2017-10-09 12:40:13.794 JupyterHub app:1234] bbrauns still running
[W 2017-10-09 12:40:13.809 JupyterHub dockerspawner:125] DockerSpawner.container_image is deprecated in dockerspawner 0.9.  Use DockerSpawner.image
```

My Dockerfile.jupyterhub: 

```
root@jupyter-master:~/gwdg-jupyter# cat Dockerfile.jupyterhub
FROM jupyterhub/jupyterhub-onbuild:0.8.0

# Install dockerspawner and its dependencies
RUN /opt/conda/bin/pip install \
    oauthenticator==0.7.* \
    dockerspawner==0.9.* \
    python-dateutil==2.6.*

RUN apt-get update; apt-get install -y nano

COPY ./cull_idle_servers.py /srv/jupyterhub/cull_idle_servers.py

RUN pip install jupyterhub-dummyauthenticator
```

My jupyterhub_config.py

```
root@jupyter-master:~/gwdg-jupyter# cat jupyterhub_config.py
... 
# Whitlelist users and admins
c.Authenticator.admin_users = admin = set()
c.JupyterHub.admin_access = True
admin.add('bbrauns')
```

**Comment by minrk** [comment]
The admin button is gone. It is now in the header:

<img width="529" alt="screen shot 2017-10-10 at 13 01 45" src="https://user-images.githubusercontent.com/151929/31383402-35e5c54a-adbb-11e7-952d-2ee6baccb923.png">

It looks like you have a custom header that's overriding the defaults. That appears to be the culprit. If you want to add to a block in a custom template, make sure to include

```
{% block x %}
custom  before
{{ super() }}
custom after
{% endblock x %}
```

to include the original block in your custom bit.

**Comment by bbrauns** [comment]
Ah my fault. Thank you very much!

**Comment by bbrauns** [comment]
@minrk Sorry to bother you again, but is there an easy way to customize the page.html template? My org requires additional links for example a privacy page

**Comment by minrk** [comment]
The page templates are not well designed for customization at this point.

I opened #1481 to make extending the templates a bit easier, but for now I think you are going to have to copy the page.html template wholesale to modify it.

**Comment by SaiAparna1** [comment]
Could you please let me know how to log in as admin for jupyterhub, I mean what are the credentials. I have been trying so many times but still not able to log in as admin even changed the  jupyter_config.py file.

**Comment by abinshihab** [comment]
Hi I have the same issue and I need your help please
