### ISSUE TITLE
Make logout more configurable

### ISSUE THREAD

**Issue by NickolausDS** [jupyterhub/jupyterhub#1476]
Currently, for custom OAuthenticators, it is difficult to modify the default logout behavior. Two configurable changes would be desired:

1. Modify `auth_state` on logout (Such as revoking user tokens).
2. Change logout redirect URL, for logging users out of their identity providers. 

Currently, the [Logout Handler](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/handlers/login.py#L25) clears user tokens and calls `redirect()` within the single `get()` function. `redirect()` can't be called twice, so `get()` can't be directly overridden. 

I propose the redirect URL is made configurable within the Logout Handler:

    class LogoutHandler(BaseHandler):
        redirect_url = self.settings['login_url']
        def get(self):
            ...
            self.redirect(redirect_url, permanent=False)

Additionally, Logout Handler already performs a check to get the user before clearing their cookie. It would be convenient if there was also a hook allowing custom logout handlers to modify `auth_state`:

    class LogoutHandler(BaseHandler):
        def get(self):
            user = self.get_current_user()
            if user:
                post_user_logout(user)
                self.clear_login_cookie()
            ...

        def post_user_logout(self, user):
            """Override this to revoke user tokens in auth_state"""
            pass

**Comment by minrk** [comment]
Considering this one addressed by #2534. I think there's still room for hooks to provide some of this functionality without resorting to subclassing (#2288), but at least it's easier now to modify and especially add LogoutHandler functionality.
