### ISSUE TITLE
Secure cookies not working behind AWS ALB

### ISSUE THREAD

**Issue by psyvision** [jupyterhub/jupyterhub#1477]
Hello,

I'm running with the following version:

JupyterHub 0.8
Notebook 5.1.0

In a custom Docker container in AWS Container Service.

Jupyterhub is configured with SSL and in AWS it runs behind an AWS application load balancer using SSL.

If I send a request to login direct to the server running the Docker container (e.g. https://10.2.0.10:33212/jupyterhub/hub/login) then I get a "jupyter-hub-token" cookie back marked as Secure:

```
set-cookie:jupyter-hub-token="2|1:0|10:1507813141|17:jupyter-hub-token|44:......"; expires=Sat, 11 Nov 2017 12:59:01 GMT; HttpOnly; Path=/jupyterhub/hub/; Secure
```

However, if I navigate to the same page via the AWS application load balancer's DNS (e.g. https://jupyterhub.internal/jupyterhub/hub/login) then I do not get a secure cookie:

```
set-cookie:jupyter-hub-token="2|1:0|10:1507812660|17:jupyter-hub-token|44:......"; expires=Sat, 11 Nov 2017 12:51:00 GMT; HttpOnly; Path=/jupyterhub/hub/
```

I've added some extra logging and observe the following, this happens with a direct request:

```
[I 2017-10-12 12:58:31.058 JupyterHub jwtauthenticator:15] Protocol: https
[I 2017-10-12 12:58:31.058 JupyterHub jwtauthenticator:16] X-Forwarded-Proto: https
```

The following is observed when going via the AWS ALB:

```
[I 2017-10-12 12:50:59.977 JupyterHub jwtauthenticator:15] Protocol: http
[I 2017-10-12 12:50:59.977 JupyterHub jwtauthenticator:16] X-Forwarded-Proto: https,https
```

The code for logging these is:
```
self.log.info("Protocol: %s", self.request.protocol)
self.log.info("X-Forwarded-Proto: %s", self.request.headers.get("X-Forwarded-Proto", ""))
```

The Secure flag is added to the cookie if `self.request.protocol=="https"`.

The AWS ALB will only accept requests on https/443 and the Docker container will also only accept requests via port 443.  I note that in `app.py` the tornado HTTPServer is started with `xheaders` set to `True` so it should work, as per http://www.tornadoweb.org/en/stable/httpserver.html#http-server:

```
If xheaders is True, we support the X-Real-Ip/X-Forwarded-For and X-Scheme/X-Forwarded-Proto headers, which override the remote IP and URI scheme/protocol for all requests.
```

Does anyone know why I'm not getting a Secure cookie in this instance?

**Comment by psyvision** [comment]
This may be an issue with the underlying tornado:

https://github.com/tornadoweb/tornado/blob/d4094a0c2a7cddc654381c162ee7786d4bf8453b/tornado/httpserver.py#L286

It doesn't seem to be able to handle the (valid) scenario of X-Forwarded-Proto containing multiple values.

**Comment by willingc** [comment]
To recap:
- JupyterHub 0.8
- Notebook 5.1
- Authenticator: jwtauthenticator (I'm assuming @psyvision that you are using this: https://github.com/mogthesprog/jwtauthenticator which is a third party authenticator maintained by a community member not Project Jupyter)
- Cloud: AWS and ALB (Application Load Balancer)

Looking at the logs that you shared, it appears that the `jwtauthenticator` is authenticating the users. I suspect that the configuration of `c.LocalAuthenticator.audience = 'https://myApp.domain.local/'` only has one of the two URLs listed and so no validation is taking place (see https://github.com/mogthesprog/jwtauthenticator#required-configuration). That said, I'm not familiar with the details of the `jwtauthenticator`.

cc/ @mirnk thoughts?

**Comment by psyvision** [comment]
@willingc yes we are using the jwt auth.  I've actually modified it and the very first thing it does in the auth cycle is log the X-Forwarded-Proto which is where I'm seeing `https,https`.  

I've now logged an issue with Tornado as I believe the issue is there (https://github.com/tornadoweb/tornado/issues/2161).  ASP.NET had a similar issue at one point, only being able to recognise a single value in the header when many are technically valid.

The JWT audience validation is actually just checking a certain value in the JWT token has an expected value.  In our case this is coming from AWS and the audience isn't a domain name at all (it doesn't have to be according to the JWT spec).

**Comment by minrk** [comment]
I opened https://github.com/tornadoweb/tornado/pull/2162 which should fix this upstream. If it's urgent, we can add our workaround to handle this case in the meantime.

**Comment by psyvision** [comment]
Thank you @minrk!  It's not super urgent, I'll try and pull your tornado into the app to confirm that it does indeed resolve the secure flag being set.

**Comment by psyvision** [comment]
I can confirm that it works with your modification to tornado.

I now have:

```
jupyter-hub-token => secure and http only
jupyter-hub-token-richardc => not secure and not http only
user-richardc => secure and http only
```

Where does the `jupyter-hub-token-username` cookie get set?  I haven't managed to find the code for it, wondering why it doesn't get either flag set.

**Comment by minrk** [comment]
> jupyter-hub-token-richardc

That is likely an old cookie from jupyterhub 0.7. Can you clear the cookies and login again, and tell me if you still see it?

**Comment by psyvision** [comment]
You're right, it's gone.  I was mistaking the path restriction in Chrome causing the cookies to hide with it removing them.  Thank you.

**Comment by willingc** [comment]
Thanks @minrk and @psyvision.

**Comment by Analect** [comment]
@psyvision 
>  I've actually modified it and the very first thing it does in the auth cycle is log the X-Forwarded-Proto which is where I'm seeing https,https

I was interested in getting this JWT authentication running for jupyterhub in an app that is using Firebase for authentication ... ie. I'm hoping to use the same JWT for jupyterhub.

You mentioned above that you had to modify the [jwtauthenticator](https://github.com/mogthesprog/jwtauthenticator).  Could you elaborate on what you had to do and why?  Also, would you be able to share the relevant code you ended up adding to the `jupyterhub_config.py` file to handle this JWT authentication?

Thanks v. much

**Comment by psyvision** [comment]
`jupyterhub_config.py`:

```
c.JupyterHub.authenticator_class = MyAuthenticator
c.MyAuthenticator.signing_certificate = '/etc/jupyterhub/jwt.crt' # RSA Auth
c.MyAuthenticator.username_claim_field = 'username'
c.MyAuthenticator.expected_audience = 'audience'
c.MyAuthenticator.param_name = 'jwtparam' # URL param that contains JWT token
c.MyAuthenticator.create_system_users = True
c.MyAuthenticator.whitelist = whitelist = set()
```

`MyAuthenticator` inherits from `JSONWebTokenLocalAuthenticator` and does some special work for us that you don't need so just replace it.

I think I modified this line in the authenticator -> https://github.com/mogthesprog/jwtauthenticator/blob/master/jwtauthenticator/jwtauthenticator.py#L26 so that Bearer could be upper or lowecase.

**Comment by Analect** [comment]
Thanks alot @psyvision

**Comment by Analect** [comment]
@psyvision 
Could I trouble you briefly once more.
I'm trying to get this jwtauthenticator working against a JWT Token that has been generated by firebase (see [here](https://firebase.google.com/docs/auth/admin/verify-id-tokens)). On user login from a node.js app, a JWT Token ends up getting copied across to session storage in the browser and looks something like this:
```
{"uid":"xxx",email":"xxx@xyz.com","emailVerified":false,"phoneNumber":null,"isAnonymous":false,"providerData":[{"uid":"xxx@xyz.com","email":"xxx@xyz.com","providerId":"password"}],"apiKey":"xxxx","appName":"[DEFAULT]","authDomain":"xxx.firebaseapp.com","stsTokenManager":{"apiKey":"xxxx","refreshToken":"xxx-xxx-xxx-xxx-xxx","accessToken":"eyJhbGc...<big long string> ...rqdADh25g","expirationTime":1513791174750},"redirectEventId":null,"lastLoginAt":"1513787572000","createdAt":"1461253358000"}
```
For the jwtauthenticator, I'm using the following settings:
```
c.JupyterHub.authenticator_class = 'jwtauthenticator.jwtauthenticator.JSONWebTokenLocalAuthenticator'
c.JSONWebTokenLocalAuthenticator.signing_certificate = 'https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com'
c.JSONWebTokenLocalAuthenticator.username_claim_field = 'email'
c.JSONWebTokenLocalAuthenticator.expected_audience = 'my-firebase-aud-field '
c.JSONWebTokenLocalAuthenticator.param_name = 'accessToken'
c.JSONWebTokenLocalAuthenticator.create_system_users = True
c.JSONWebTokenLocalAuthenticator.header_name = 'Authorization'
```
The JWT Token coming from firebase doesn't have a username field as part of the payload, so I end up doing a bit more work to use the email and then find the username from a firebase realtime database, which is fine.  The main problem I have though is accessing the `accessToken` from the JWT Token that has got pushed to session storage from the instance running jupyterhub (where `jupyterhub_config.py` is getting executed).  

I'm not familiar enough with how these things work, but is it possible that my set-up needs something like a reverse-proxy (https://github.com/DaveWillkomm/jwtap) to square away my added requirement to use the same JWT Token for the purposes of authenticating to jupyterhub?  

Could I ask what set-up you are using to generate and serve the initial token?  

I'm feeling around here for a possible solution, but not really sure if I'm looking in the right places!  Thanks.

**Comment by psyvision** [comment]
@Analect 

`signing_certificate` doesn't look right to me (as it should be a path to the certificate, I don't think it will load from HTTP?

`param_name` is what it looks for in the URL to get the JWT.

I'm also not sure what your exact error message/problem is?

All you need to do is get a JWT token from whatever source, it doesn't matter.  Pass the encoded JWT to jupyterhub, I'm guessing you're doing this on the url (/jupyterhub/?accessToken=...).  

You will then be authorised with usernames of email (given the config youve specified).  I'm not sure if this will work as it creates system users (can unix usernames be emails?).

With expected audience set it will look for the audience field in your JWT, I can't see it myself so I would suggest removing this from code.

**Comment by manics** [comment]
Closing since the PR mentioned in https://github.com/jupyterhub/jupyterhub/issues/1477#issuecomment-336403620 was merged
