### ISSUE TITLE
Proposal: Doc Page for "Configuring IPython/Jupyter, for JupyterHub Admins"

### ISSUE THREAD

**Issue by ssanderson** [jupyterhub/jupyterhub#1478]
We've gotten a few issues in https://github.com/quantopian/pgcontents and https://github.com/quantopian/qgrid asking how to use those tools with JupyterHub.  The "technically correct but unhelpful" response to these questions is that they're actually questions about how to configure the notebook, not about how to configure JupyterHub. Giving an actually helpful answer requires explaining the relationships between the Jupyter subsystems that the user cares about, explaining where each subsystem looks for configuration, and explaining how to ensure that the configuration the user cares about gets found by the appropriate subsystem (and, of course, this part varies depending on the user's particular JupyterHub installation). All of this information is individually well-documented, but pulling it all together into a holistic picture of how the systems interact is pretty challenging. 

I think many JupyterHub users would benefit from a page titled something like "Configuring Jupyter and IPython, for JupyterHub Admins", which describes, in a JupyterHub-focused way, the various subsystems that admins might want to configure, and what the options are for configuring them.

@willingc pointed me at https://jupyterhub.readthedocs.io/en/latest/troubleshooting.html#how-do-i-use-jupyterlab-s-prerelease-version-with-jupyterhub and https://github.com/jupyterhub/jupyterhub/issues/305#issuecomment-182854604 as existing places where there's been some discussion of this issue.

Reference Issues:
- https://github.com/quantopian/pgcontents/issues/39
- https://github.com/quantopian/qgrid/issues/85
- https://github.com/jupyterhub/jupyterhub/issues/305

**Comment by minrk** [comment]
Good idea. I think we should have in the JupyterHub docs explanations of system-wide configuration directories, such as `/etc/jupyter` and `/etc/ipython`, which is generally where JupyterHub admins should put things. We should probably cover:

- Quick overview of what configuration is part of JupyterHub and what is configuration of the single-user Jupyter instances
- where to put config files for Jupyter and IPython
- system-wide kernel installation
- how some of these can change for different Spawners (basically containers vs host systems)
