### ISSUE TITLE
jupyterhub's terminal

### ISSUE THREAD

**Issue by kiwi0217** [jupyterhub/jupyterhub#1480]
How does jupytethub's terminal work?
Is jupyterhub's terminal like opening a thread like ssh or bash?

**Comment by minrk** [comment]
It opens a pty on the server, which in turn launches a shell such as `bash`. It used [terminado](https://github.com/takluyver/terminado) to connect the webpage to the server and [ptyprocess](http://ptyprocess.readthedocs.io/en/latest/) to manage the pty. It should be just like having a shell on the server.
