### ISSUE TITLE
Make html templates more extensible

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#1481]
There are a few things we can do to make custom templates a more pleasant experience

1. always include the default templates dir and data_files_dir in the template path, so that custom templates can extend them with `{% extend "templates/page.html" %}`
2. make sure that all of our blocks use `{{ super() }}` as appropriate. Right now, many blocks in `page.html` cannot be overridden in a useful way because `{{ super() }}` is not called on the pages.
3. look for potential additional places for blocks that would be useful

**Comment by minrk** [comment]
#1601 begins implementing this

**Comment by manics** [comment]
I think this is done (or is at least happening gradually).
