### ISSUE TITLE
DB Connection Times out and JH Fails to Recover

### ISSUE THREAD

**Issue by ichasepucks** [jupyterhub/jupyterhub#1482]
**How to reproduce the issue**
I've created a very simple repro option, https://github.com/ichasepucks/docker-jupyterhub.
Simply clone it and run `docker-compose up --build` and wait.  If you do not do anything but start the server and wait, the very first call to `/api/routes` should cause a connection failure.

**What you expected to happen**
I expect the stale connection to not be used since the default value for `pool_recycle` is set to 60 by default in JH 0.8.0.  However, it clearly attempts to use the stale connection and fails.

**What actually happens**
If the connection is idle (120s in this particular case) long enough the DB will drop the connection.  This is normal behavior for MySQL.  However, JH/SQLAlchemy is not detecting the stale connection and is either not honoring the `pool_recycle` value or the connection is never returned to the pool, so it has no chance to invalidate it.  I was not able to debug that far into the problem.

**Share what version of JupyterHub you are using**
0.8.0

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
