### ISSUE TITLE
Debugging SSL issues

### ISSUE THREAD

**Issue by hannorein** [jupyterhub/jupyterhub#1483]
I'm trying to enable SSL on jupyterhub. The documentation suggests that all I have to do is provide a certificate and key. I've done that. jupyterhub starts and says that it is listening for connections, yet all attempts to connect to it time out. I don't get any messages on the terminal that are related to SSL (even with the `--debug` option). If I simple comment out the certificate and key lines in the configuration file, everything works (without SSL of course). 

How can I debug this issue?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
