### ISSUE TITLE
Time out Error while connecting to server

### ISSUE THREAD

**Issue by uday2002** [jupyterhub/jupyterhub#1484]
Hi,

I'm trying to run the jupyterhub as a single user. Login was success, while I clicke myserver, it is throwing time out error while connecting to server. Please let me know the possible resolution:

Please find the output of the log:

 2017-10-13 11:25:44.113 JupyterHub log:100] 302 GET /hub/ (@::ffff:172.22.25.35) 1.65ms
[I 2017-10-13 11:25:44.122 JupyterHub log:100] 200 GET /hub/login (@::ffff:172.22.25.35) 2.64ms
[I 2017-10-13 11:26:44.101 JupyterHub log:100] 302 GET / (@::ffff:172.22.25.35) 1.97ms
[I 2017-10-13 11:26:44.104 JupyterHub log:100] 302 GET /hub (@::ffff:172.22.25.35) 0.79ms
[I 2017-10-13 11:26:44.114 JupyterHub log:100] 302 GET /hub/ (@::ffff:172.22.25.35) 1.39ms
[I 2017-10-13 11:26:44.122 JupyterHub log:100] 200 GET /hub/login (@::ffff:172.22.25.35) 2.52ms
[I 2017-10-13 11:27:44.645 JupyterHub spawner:363] Spawning /opt/anaconda3/bin/jupyterhub-singleuser --user=udayn --port=49579 --cookie-name=jupyter-hub-token-udayn --base-url=/user/udayn --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api --ip=localhost --notebook-dir=/var/ds/workspace
[W 2017-10-13 11:28:42.036 JupyterHub orm:408] udayn's server never showed up at http://localhost:49579/user/udayn after 30 seconds. Giving up
[E 2017-10-13 11:28:42.074 JupyterHub gen:871] Exception in Future <tornado.concurrent.Future object at 0x7fc7d68c84e0> after timeout
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 867, in error_callback
        future.result()
      File "/opt/anaconda3/lib/python3.5/site-packages/jupyterhub/orm.py", line 424, in spawn
        raise e
      File "/opt/anaconda3/lib/python3.5/site-packages/jupyterhub/orm.py", line 400, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/opt/anaconda3/lib/python3.5/site-packages/jupyterhub/orm.py", line 111, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/opt/anaconda3/lib/python3.5/site-packages/jupyterhub/utils.py", line 82, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://localhost:49579/user/udayn didn't respond in 30 seconds

Thanks,
Uday

**Comment by willingc** [comment]
Hi @uday2002. Sorry about the delay in responding.

Which version of JupyterHub are you running? We recommend running the latest stable https://github.com/jupyterhub/jupyterhub/releases/tag/0.8.0

A good starting point for getting JupyterHub running is the [Zero to JupyterHub guide](https://zero-to-jupyterhub.readthedocs.io/en/v0.4-doc/)

**Comment by uday2002** [comment]
Hi wiilingc,

Thanks for the response. I got this worked to changing parameter in sudospawner. I will look into the upgrading of jupyterhub to the latest version as suggested. Have a great day.

Thanks
Uday

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻

**Comment by AshishSingh-Reflektion** [comment]
> changing parameter in sudospawner

I am also facing the same issue. What is the change you made?
