### ISSUE TITLE
Configuration for using Content Manager API(PgContent)

### ISSUE THREAD

**Issue by ayushiagarwal** [jupyterhub/jupyterhub#1487]
Hi ,

I am using pgcontent API to use postgres as storage for  notebooks. 
I made the following changes to jupyterhub_config.py 

`from pgcontents import PostgresContentsManager
import getpass
c = get_config()
c.NotebookApp.contents_manager_class = PostgresContentsManager
c.PostgresContentsManager.db_url = 'postgresql://postgresurl/pgcontents'
c.PostgresContentsManager.user_id = getpass.getuser()
c.PostgresContentsManager.max_file_size_bytes = 1000000
`

When I start my jupyterhub by using this configuration, it does not save notebooks in postgres db, it still uses the local directory to save notebooks.

Command used to run jupyterhub :   
`jupyterhub --ip ip_name --port no --no-ssl --config /path/to/jupyterhub/config/jupyterhub_config.py`

Where as when I am starting my jupyter notebooks for single user with same  config changes in jupyter_notebook_config.py and starting a notebook using command it saves successfully to postgres db.
`jupyter notebook --ip=no --port no`

I raised the issue on pgcontent repo [https://github.com/quantopian/pgcontents/issues/39](url) also I was pointed that it might be an issue with jupyterhub configs. Do we need to provide any other config level to jupyterhub for pgcontent (I am using default config for local spawner and PAM authentication). Or does jupyterhub bychance for single user notebooks use jupyer_notebook_config. Do we need to change that somehow?

Any quick help would be appreciated.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
