### ISSUE TITLE
wrong redirects in 0.8 on distributed setup

### ISSUE THREAD

**Issue by Jibbow** [jupyterhub/jupyterhub#1488]
Hi, after upgrading to Jupyterhub 0.8 I face some issues with the communication between the Hub and the singleuser instances. Similar to issue #1449 the problem is as follows:
I am running a distributed setup of Jupyterhub in AWS based on [cloudJHub](https://github.com/harvard/cloudJHub). The Jupyterhub and the Proxy are running on one manager instance and the spawner starts a new ec2 instance for every notebook.

Jupyterhub is running on port 10001 and the singleuser notebooks on 12000. `c.JupyterHub.hub_ip = '0.0.0.0'` is set and the communication generally works (and has worked in 0.7).
When spawning a new singleuser notebook everything works fine except that I can not connect to it any more.

In the singleuser logs I can find the following redirect loop after spawning the notebook server. This corresponds to the message "the page isn't redirecting properly" I can see in the browser.

**Singleuser Notebook**
```
[I 2017-10-17 12:53:09.714 SingleUserNotebookApp notebookapp:1366] The Jupyter Notebook is running at: http://10.10.221.232:12000/
[I 2017-10-17 12:53:09.715 SingleUserNotebookApp notebookapp:1367] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2017-10-17 12:53:31.934 SingleUserNotebookApp log:122] 302 GET /user/admin/ → /user/admin (@10.10.0.239) 0.56ms
[I 2017-10-17 12:53:32.106 SingleUserNotebookApp log:122] 302 GET /user/admin/?redirects=1 → /user/admin/?redirects=1 (@::ffff:127.23.43.200) 0.48ms
[I 2017-10-17 12:53:32.124 SingleUserNotebookApp log:122] 302 GET /user/admin/?redirects=1 → /user/admin/?redirects=1 (@::ffff:127.23.43.200) 0.39ms
[I 2017-10-17 12:53:32.140 SingleUserNotebookApp log:122] 302 GET /user/admin/?redirects=1 → /user/admin/?redirects=1 (@::ffff:127.23.43.200) 0.37ms
[I 2017-10-17 12:53:32.155 SingleUserNotebookApp log:122] 302 GET /user/admin/?redirects=1 → /user/admin/?redirects=1 (@::ffff:127.23.43.200) 0.38ms
[I 2017-10-17 12:53:32.171 SingleUserNotebookApp log:122] 302 GET /user/admin/?redirects=1 → /user/admin/?redirects=1 (@::ffff:127.23.43.200) 0.38ms
[I 2017-10-17 12:53:32.197 SingleUserNotebookApp log:122] 302 GET /user/admin/?redirects=1 → /user/admin/?redirects=1 (@::ffff:127.23.43.200) 0.37ms
[I 2017-10-17 12:53:32.215 SingleUserNotebookApp log:122] 302 GET /user/admin/?redirects=1 → /user/admin/?redirects=1 (@::ffff:127.23.43.200) 0.37ms
[I 2017-10-17 12:53:32.232 SingleUserNotebookApp log:122] 302 GET /user/admin/?redirects=1 → /user/admin/?redirects=1 (@::ffff:127.23.43.200) 0.38ms
[I 2017-10-17 12:53:32.249 SingleUserNotebookApp log:122] 302 GET /user/admin/?redirects=1 → /user/admin/?redirects=1 (@::ffff:127.23.43.200) 0.37ms
```
Whereas **Jupyterhub and the proxy** have to following related logs:
```
[I 2017-10-17 12:53:33.073 JupyterHub log:122] 302 GET /hub/user/admin/ → /user/admin/?redirects=1 (admin@::ffff:127.23.43.200) 6785.59ms
12:53:33.093 - debug: [ConfigProxy] PROXY WEB /user/admin/?redirects=1 to http://10.10.221.232:12000
12:53:33.112 - debug: [ConfigProxy] PROXY WEB /user/admin/?redirects=1 to http://10.10.221.232:12000
12:53:33.127 - debug: [ConfigProxy] PROXY WEB /user/admin/?redirects=1 to http://10.10.221.232:12000
12:53:33.144 - debug: [ConfigProxy] PROXY WEB /user/admin/?redirects=1 to http://10.10.221.232:12000
12:53:33.160 - debug: [ConfigProxy] PROXY WEB /user/admin/?redirects=1 to http://10.10.221.232:12000
12:53:33.184 - debug: [ConfigProxy] PROXY WEB /user/admin/?redirects=1 to http://10.10.221.232:12000
12:53:33.203 - debug: [ConfigProxy] PROXY WEB /user/admin/?redirects=1 to http://10.10.221.232:12000
...
```
The redirections look quite different from a local (and working) setup of Jupyterhub 0.8 which gives the hint that there might something wrong here.

When directly accessing `/user/admin/` another interesting thing happens which might be related to the new OAuth mechanism:
```
[I 2017-10-17 12:53:53.562 SingleUserNotebookApp log:122] 302 GET /user/admin/ → /user/admin (@::ffff:82.113.113.80) 0.50ms
[D 2017-10-17 12:53:53.605 SingleUserNotebookApp auth:378] No user identified
[D 2017-10-17 12:53:53.606 SingleUserNotebookApp handlers:210] Using contents: services/contents
...
```
Accessing `/user/admin` finally results in a 404 error.  
In the spawner I pass `self.oauth_client_id` and `self.api_token` as `HubOAuth.oauth_client_id` and `HubOAuth.api_token` respectively.

I would be really happy if you could give me some hints how to resolve this issue because the logs are not that verbose on this topic.   
Thank you! 

*(The IP address 127.23.43.200 is a replacement for the real address)*

**Comment by mmacny** [comment]
Having the same issue on a recent install. Same setup. Ubuntu 16.04

**Comment by Jibbow** [comment]
The first `.../redirects=1` happens in [UserSpawnHandler](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/handlers/base.py#L671). In the local setup a `.../redirects=1` never shows up.

But I am not sure if this helps a lot.

**Comment by gouthambs** [comment]
I am noticing a similar issue. I am trying to setup Jupyterhub on AWS but I keep running into an issue where the notebook server is spawned correctly. The IP published on the logs are correct and I am able to visit the public port of the notebook server. But the url `/user/<username>/` doesn't forward to the notebook server correctly. I am wondering what else I am missing here. 
```

[I 2017-10-18 12:13:27.930 JupyterHub base:446] User gbalaraman took 3.381 seconds to start
[I 2017-10-18 12:13:27.931 JupyterHub proxy:231] Adding user gbalaraman to proxy /user/gbalaraman/ => http://<public_instance_ip>:32773
12:13:27.971 - info: [ConfigProxy] Adding route /user/gbalaraman -> http://<public_instance_ip>:32773
12:13:27.972 - info: [ConfigProxy] 201 POST /api/routes/user/gbalaraman 
[I 2017-10-18 12:13:27.976 JupyterHub log:122] 302 GET /hub/user/gbalaraman/ → /user/gbalaraman/?redirects=1 (gbalaraman@::ffff:4**.1*8.**7.**1) 3428.58ms 
[I 2017-10-18 12:17:33.139 JupyterHub log:122] 302 GET /static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=d172b560b073f3bc42fea160bbff96a2 → /hub/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=d172b560b073f3bc42fea160bbff96a2 (@::ffff:4**.1*8.**7.**1) 0.55ms
[I 2017-10-18 12:17:33.145 JupyterHub log:122] 302 GET /static/style/style.min.css?v=fd2220be4cc17416b538bf7fb9ae2339 → /hub/static/style/style.min.css?v=fd2220be4cc17416b538bf7fb9ae2339 (@::ffff:4**.1*8.**7.**1) 0.41ms
[I 2017-10-18 12:17:33.146 JupyterHub log:122] 302 GET /static/custom/custom.css?v=900035aa0c126bb85df55c5b3e51b6f1 → /hub/static/custom/custom.css?v=900035aa0c126bb85df55c5b3e51b6f1 (@::ffff:4**.1*8.**7.**1) 0.35ms
[I 2017-10-18 12:17:33.148 JupyterHub log:122] 302 GET /static/components/requirejs/require.js?v=07d7db4d3fd6519996822665e4239282 → /hub/static/components/requirejs/require.js?v=07d7db4d3fd6519996822665e4239282 (@::ffff:4**.1*8.**7.**1) 0.35ms
[W 2017-10-18 12:17:33.222 JupyterHub log:122] 404 GET /hub/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=d172b560b073f3bc42fea160bbff96a2 (@::ffff:4**.1*8.**7.**1) 0.63ms
[W 2017-10-18 12:17:33.226 JupyterHub log:122] 404 GET /hub/static/style/style.min.css?v=fd2220be4cc17416b538bf7fb9ae2339 (@::ffff:4**.1*8.**7.**1) 0.43ms
```

I think there is an issue with the way proxy server is configured. Not sure how to address it. Would appreciate any help with this.


`

**Comment by ianabc** [comment]
I'm seeing this as well with v0.8.0 and dockerspawner (0.9.1), proxying through apache.

**Comment by ianabc** [comment]
For me at least this seems to have been related to https://github.com/jupyterhub/dockerspawner/issues/202. 

Specifically I had a customized launch script which was passing environment variables that were no longer defined (or needed). Some of the variables were empty which was preventing my containers from talking back to the Hub API
```
...
[I 2017-11-02 00:15:35.528 SingleUserNotebookApp log:122] 302 GET /jupyter/user/ianatr/?redirects=1 → /jupyter/user/ianatr/?redirects=1 (@127.0.0.1) 0.85ms
[E 2017-11-02 00:15:35.879 SingleUserNotebookApp singleuser:354] Failed to connect to my Hub at  (attempt 3/5). Is it running?
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 351, in check_hub_version
        resp = yield client.fetch(self.hub_api_url)
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/opt/conda/lib/python3.6/site-packages/tornado/simple_httpclient.py", line 217, in __init__
        self.request.url)
    ValueError: Unsupported url scheme: 
...
```
Among other things, I was explicitly setting --hub-api-url to an empty value, so I was getting `Failed to connect to my Hub at  (attempt 3/5). Is it running?`, along with the corresponding `ERR_TOO_MANY_REDIRECTS` in the browser (Chrome).

Removing the explicit variables from the script got things working again because dockerspawner was already setting the necessary values for jupyterhub-singleuser.

I don't think the redirect loop should happen even with my broken script, so I'll keep the images around for testing to see if I can help fix that.

**Comment by Andy-Doddington** [comment]
Suspect I am suffering the same issue, on #1551 :-(

**Comment by grbinho** [comment]
Hi everyone. Did anyone get this issue resolved? I'm having the same problem as explained by @Jibbow.

I have a custom spawner starting ECS tasks in AWS. I'm also using GitHub OAuthenticator to authenticate users. 
ECS tasks run jupyter/scipy-notebook:8ccdfc1da8d5 with following parameters passed to it:
```
"start-singleuser.sh","--hub-api-url=\"http://somerandomsubdomain.ngrok.io/hub/api\"","--debug","--ip=0.0.0.0","--port=8888","--user=\",myuser\""
```
and environment variables
```
JPY_API_TOKEN=20e811cacc884650b54b91d3e3a4d214
JPY_USER=myuser
JUPYTERHUB_CLIENT_ID=jupyterhub-user-myuser
JUPYTERHUB_HOST=''
JUPYTERHUB_OAUTH_CALLBACK_URL = /user/myuser/oauth_callback
JUPYTERHUB_USER=myuser
NB_USER=myuser
```
When i navigate to `http://somerandomsubdomain.ngrok.io`, i get presented with login with GitHub button. After logging in, I get redirected to "Your server is starting up" and I can see that spawner is starting the ECS task.
When task is started, I can see in the log that IP and port combination is registered with the proxy.
But after that, it ends up in the redirect loop.

If i try to access the link directly `http://somerandomsubdomain.ngrok.io/user/myuser`
I get `No user identified` in the log of the ECS Task ( Jupyter single user server).

I use ngrok to expose my local machine to ECS Task, so `somerandomsubdomain.ngrok.io` is forwarding to localhost:8000 which is the port proxy is exposed on.

Proxy logs:

```
[I 2018-09-02 13:23:33.958 JupyterHub proxy:562] Starting proxy @ http://:8000
[D 2018-09-02 13:23:33.959 JupyterHub proxy:563] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--error-target', 'http://127.0.0.1:8081/hub/error', '--log-level', 'debug']
```

What I noticed is that there are only two cookies stored for `somerandomsubdomain.ngrok.io/user/myuser`. 

```
jupyterhub-hub-login
jupyterhub-session-id
```

If I navigate directly to the AWS ECS Task IP address, i can find another cookie..
`jupyterhub-user-myuser-oauth-state`
And i get redirected to
```
http://34.242.249.124:8888/hub/api/oauth2/authorize?client_id=jupyterhub-user-myuser&redirect_uri=%2Fuser%2Fmyuser%2Foauth_callback&response_type=code&state=eyJ1dWlkIjogImIwYmU3ZDhjNTQwMTQ1NTg5MmZhYmJhYTZiYmY3N2JkIiwgIm5leHRfdXJsIjogIi90cmVlPyJ9
```

I'm running the following versions
JupyterHub 0.9.2
Configurable Http Proxy 3.1.1
OAuthenticator (with Github) 0.8.0

Any ideas?

I found that people had similar issues when versions were not matched between hub and the single user server, but does not look to be the case here since I see this in the log:
```
[D 2018-09-02 14:07:40.736 JupyterHub _version:53] jupyterhub and jupyterhub-singleuser both on version 0.9.2
```

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!
