### ISSUE TITLE
Jupyterhub in a Resource Constrained Environment

### ISSUE THREAD

**Issue by ixxie** [jupyterhub/jupyterhub#1490]
I am planning to install Jupyterhub on the smallest Digital Ocean droplet, which has a single thread and only 512mb of memory. This will be for use by myself and a few friends, so I don't expect heavy compute loads or much simultaneous computation.

I am wondering if there are any ideas about the general minimal requirements for Jupyterhub, and also minimal requirements per simultaneous user. I understand this depends largely on what the user will do, and that limits can be set by the spawner, but I want to understand what suffices to cover the overhead + some minimal working resources.

**Comment by yuvipanda** [comment]
Heya!

I think the overhead will be fairly minimal, compared to what your users are doing. It also heavily depends on what spawner & environment you will be using. 

From an example deployment I have, I see that the hub process is using 77M of RAM and the proxy about 18M of RAM. This is a somewhat large installation (several thousand users), and these RAM estimates also don't count shared library use (so the 77M of RAM for the hub is probably shared with many of the python processes already running).

Hope that's helpful, and good luck for your deployment!
