### ISSUE TITLE
server size question.

### ISSUE THREAD

**Issue by achapkowski** [jupyterhub/jupyterhub#1499]
Hello,

I want to use JupyterHub with OAuth, but I have some questions before I start:

1. Does the user data persist?  So if ```user1``` creates a new notebook, then logs off, can they re-log back in and pick up where they left off?
2. Do users see everyone's work, or are items isolated to that user?
3. Can you limit amount of space a user gets?
4. Is there any documentation on scale/server size needed based on number of users?

Can you please point to the location of documentation for these issue is the answer is yes for any of this?

Thank you,

Andrew

**Comment by minrk** [comment]
The answer to all of these questions will depend on which Spawner you are using.

For the default LocalProcessSpawner, each JupyterHub user is a real unix user with their own home directory, permissions, etc. The notebook is just another process as that user which can create files, navigate the filesystem, etc. do anything that unix user can do. So their files persist and users are as isolated (or not) as any unix users on a shared machine. Space quotas are more difficult to enforce in this case, but not impossible.

I would recommend looking at [zero to jupyterhub](https://zero-to-jupyterhub.readthedocs.io/en/latest/), which is a step-by-step guide for deploying JupyterHub with Kubernetes, and includes things like resource estimators, and allow resource limits on disk space, CPU, and memory.

> Is there any documentation on scale/server size needed based on number of users?

This is *highly* variable, depending on what your users are going to do. In most cases, the limiting factor is the amount of RAM you allocate to each user. If you are doing heavy-weight data analysis, this could be several gigabytes per user. If it's an extremely light work (e.g. teaching basic Python syntax), then half a GB might be enough, but probably not less. And these 

The [z2jh cost estimator](https://zero-to-jupyterhub.readthedocs.io/en/latest/cost.html#interactive-cost-estimator) lets you explore this using Google's cloud pricing.
