### ISSUE TITLE
Want to create new notebook within the jupyterhub using API.

### ISSUE THREAD

**Issue by arkroop** [jupyterhub/jupyterhub#1504]
Hi,

I am a developer and doing some R&D with jupyterhub and jupyter note book.
I want to create new notebook with the help of API with in the Jupyterhub. Is there any provision to do the same and what type of configuration required to do in the jupyterhub to achieve the same.

Thanks,
Arkroop

**Comment by minrk** [comment]
Assuming you have JupyterHub 0.8, you can do this with a JupyterHub API token.

You can request a personal token from the web UI (there is a 'token' link in the navbar). This token will give you access to the JupyterHub API as you, and access to your own notebook server.

For both JupyterHub and the notebook, send API requests with the `Authorization` header:

    Authorization: token abc123...

If you want to access any user's notebook server as an admin, then this same scheme will work if you are an administrator and the `JupyterHub.admin_access = True` config is set.

If you want this to be set up as a dedicated service, then you can allocate these tokens as part of JupyterHub services configuration. This will also need `admin_access = True` and a service with admin permissions:

```python
c.JupyterHub.admin_access = True
c.JupyterHub.services = [
  {
    'name': 'my-service',
    'admin': True,
    'api_token': 'abc123...',
  },
]
```
