### ISSUE TITLE
The single-user server identifies the user with the Hub via OAuth make me redirect to /hub/login twice

### ISSUE THREAD

**Issue by rydeng** [jupyterhub/jupyterhub#1505]
in version jupyterhub 0.8.0
I customized my login authentication， so `/hub/login` will redirect to my authetication to visit a login page, but after spawn a single notebook server, It will visit `/hub/api/oauth2/authorize?response_type=code&client_id=user-rydeng&redirect_uri=%2Fuser%2Frydeng%2Foauth_callback&state=eyJ1dWlkIjogImUxYzIzMzFiMzllMDQ1MzQ4M2JkYmUyZmNkY2E5NzBmIiwgIm5leHRfdXJsIjogIi91c2VyL3J5ZGVuZy9sYWI_cmVkaXJlY3RzPTEifQ `, and then it go to `/hub/login` again, so it go to the login page **twice**, How can I avoid this:
```
User rydeng took 2.620 seconds to start
[I 2017-10-26 16:11:47.163 BigJupyterHub proxy:231] Adding user rydeng to proxy /user/rydeng/ => http://127.0.0.1:32794
16:11:47.166 - debug: [ConfigProxy] POST /user/rydeng target=http://127.0.0.1:32794, jupyterhub=true, server_name=, user=rydeng
[I 2017-10-26 16:11:47.174 BigJupyterHub log:122] 302 GET /hub/user/rydeng/ → /user/rydeng/?redirects=1 (rydeng@139.207.71.206) 2648.20ms
16:11:47.272 - debug: [ConfigProxy] PROXY WEB /user/rydeng/?redirects=1 to http://127.0.0.1:32794
16:11:47.384 - debug: [ConfigProxy] PROXY WEB /user/rydeng/lab?redirects=1 to http://127.0.0.1:32794
16:11:47.483 - debug: [ConfigProxy] PROXY WEB /hub/api/oauth2/authorize?response_type=code&client_id=user-rydeng&redirect_uri=%2Fuser%2Frydeng%2Foauth_callback&state=eyJ1dWlkIjogImUxYzIzMzFiMzllMDQ1MzQ4M2JkYmUyZmNkY2E5NzBmIiwgIm5leHRfdXJsIjogIi91c2VyL3J5ZGVuZy9sYWI_cmVkaXJlY3RzPTEifQ to http://172.26.63.144:8081
[I 2017-10-26 16:11:47.492 BigJupyterHub log:122] 302 GET /hub/api/oauth2/authorize?response_type=code&client_id=user-rydeng&redirect_uri=%2Fuser%2Frydeng%2Foauth_callback&state=eyJ1dWlkIjogImUxYzIzMzFiMzllMDQ1MzQ4M2JkYmUyZmNkY2E5NzBmIiwgIm5leHRfdXJsIjogIi91c2VyL3J5ZGVuZy9sYWI_cmVkaXJlY3RzPTEifQ → /hub/login?next=%2Fhub%2Fapi%2Foauth2%2Fauthorize%3Fresponse_type%3Dcode%26client_id%3Duser-rydeng%26redirect_uri%3D%252Fuser%252Frydeng%252Foauth_callback%26state%3DeyJ1dWlkIjogImUxYzIzMzFiMzllMDQ1MzQ4M2JkYmUyZmNkY2E5NzBmIiwgIm5leHRfdXJsIjogIi91c2VyL3J5ZGVuZy9sYWI_cmVkaXJlY3RzPTEifQ (@139.207.71.206) 5.55ms
16:11:47.592 - debug: [ConfigProxy] PROXY WEB /hub/login?next=%2Fhub%2Fapi%2Foauth2%2Fauthorize%3Fresponse_type%3Dcode%26client_id%3Duser-rydeng%26redirect_uri%3D%252Fuser%252Frydeng%252Foauth_callback%26state%3DeyJ1dWlkIjogImUxYzIzMzFiMzllMDQ1MzQ4M2JkYmUyZmNkY2E5NzBmIiwgIm5leHRfdXJsIjogIi91c2VyL3J5ZGVuZy9sYWI_cmVkaXJlY3RzPTEifQ to http://172.26.63.144:8081
[I 2017-10-26 16:11:47.594 BigJupyterHub cas:42] cas redirect: 'https://bigquant.com/account/cas/login?service=https%3A%2F%2Ftesti.bigquant.com%2Fhub%2Fcas_callback%3Fnext%3D%252Fhub%252Fapi%252Foauth2%252Fauthorize%253Fresponse_type%253Dcode%2526client_id%253Duser-rydeng%2526redirect_uri%253D%25252Fuser%25252Frydeng%25252Foauth_callback%2526state%253DeyJ1dWlkIjogImUxYzIzMzFiMzllMDQ1MzQ4M2JkYmUyZmNkY2E5NzBmIiwgIm5leHRfdXJsIjogIi91c2VyL3J5ZGVuZy9sYWI_cmVkaXJlY3RzPTEifQ'
[I 2017-10-26 16:11:47.596 BigJupyterHub log:122] 302 GET /hub/login?next=%2Fhub%2Fapi%2Foauth2%2Fauthorize%3Fresponse_type%3Dcode%26client_id%3Duser-rydeng%26redirect_uri%3D%252Fuser%252Frydeng%252Foauth_callback%26state%3DeyJ1dWlkIjogImUxYzIzMzFiMzllMDQ1MzQ4M2JkYmUyZmNkY2E5NzBmIiwgIm5leHRfdXJsIjogIi91c2VyL3J5ZGVuZy9sYWI_cmVkaXJlY3RzPTEifQ → https://bigquant.com/account/cas/login?service=https%3A%2F%2Ftesti.bigquant.com%2Fhub%2Fcas_callback%3Fnext%3D%252Fhub%252Fapi%252Foauth2%252Fauthorize%253Fresponse_type%253Dcode%2526client_id%253Duser-rydeng%2526redirect_uri%253D%25252Fuser%25252Frydeng%25252Foauth_callback%2526state%253DeyJ1dWlkIjogImUxYzIzMzFiMzllMDQ1MzQ4M2JkYmUyZmNkY2E5NzBmIiwgIm5leHRfdXJsIjogIi91c2VyL3J5ZGVuZy9sYWI_cmVkaXJlY3RzPTEifQ (@139.207.71.206) 2.57ms

**Comment by rydeng** [comment]
everytime when I respawn a docker, it will add a record in table `oauth_access_tokens`
```
id |  client_id  |     grant_type     | expires_at | refresh_token | refresh_expires_at | user_id |                                                                           hashed                                                                           | prefix 
----+-------------+--------------------+------------+---------------+--------------------+---------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------
 10 | user-rydeng | authorization_code |            |               |                    |    4344 | sha512:1:bd717059bcb0e846:f680864978c466db8efecc1a757063ec3d7cec6a0153f1d56161c990c26bc67f92d143d40f364f3c72edba93f81078e1aa3b38aa6e9a46a0d457031de727b307 | 4c5c
 11 | user-rydeng | authorization_code |            |               |                    |    4344 | sha512:1:8a36befc6a12a291:ed115b2181e3c7e24009bafe87cb0282b92dcec10c42f6678ebafd1487536090f0a91928418c9a3cb828debfd4826a6accf8e3e48f71ea5001654bab091abccc | 9595
(2 rows)

**Comment by rydeng** [comment]
@minrk  , is the `login_url` can be my authenticate login url?
```
def init_oauth(self):
        base_url = self.hub.base_url
        self.oauth_provider = make_provider(
            lambda : self.db,
            url_prefix=url_path_join(base_url, 'api/oauth2'),
            login_url=url_path_join(base_url, 'login')
        )

**Comment by minrk** [comment]
Can you provide some details about how you have customized your login? I suspect that's where it's going awry. Did the same custom auth work in 0.7?

This is how the sequence *should* occur, from a fresh browser:

1. visit Hub, not logged in
2. Hub login process begins with Authenticator provider (e.g. oauth or form).
3. Authentication succeeds, Hub sets cookie for future requests. Auth provider should be irrelevant from this point forward until Hub cookies are reset.
4. notebook server is spawned
5. user visits notebook server, has no cookie set for single-user server
6. **notebook redirects to *Hub* OAuth url (upstream auth is irrelevant here)**
7. notebook oauth checks cookie, sees user is logged in, redirects back to single-user server.
8 notebook gets oauth redirect, sets second cookie only for use when talking to the notebook

The step that appears to be going wrong is 6., where you should already be logged into the Hub during the internal OAuth. Since it's a 302 to `/hub/login`, that suggests that this handler is not identifying your browser as being already logged in. This suggests to me that cookies were not set correctly, which makes me suspect that your custom authentication is bypassing the correct cookie-setting logic of the Hub.

**Comment by rydeng** [comment]
# CAS
#   https://gist.github.com/siteshen/8278913
#   https://gist.github.com/Qingcong/4115580
from jupyterhub.auth import Authenticator
from jupyterhub.handlers import BaseHandler, web
from jupyterhub.utils import url_path_join
from jupyterhub.oauth.store import make_provider
import hashlib
from tornado import gen
from tornado.httputil import url_concat
from traitlets import Unicode
import os
from urllib.parse import urlencode
from urllib.request import urlopen


class CASBaseHandler(BaseHandler):
    def redirect_next_or_url(self, url):
        next_url = self.get_argument('next', None)
        if not next_url:
            next_url = url
        self.redirect(next_url)

    def redirect_next_or_spawn(self):
        next_url = self.get_argument('next', None)
        if not next_url:
            next_url = '/hub/spawn'
        self.redirect(next_url)

    def try_append_next_url(self, url):
        next_url = self.get_argument('next', None)
        if next_url:
            url = url_concat(url, {'next': next_url})
        return url


class CASLoginHandler(CASBaseHandler):
    def get(self):
        if self.current_user:
            self.redirect_next_or_spawn()
        callback_url = self.try_append_next_url(self.authenticator.cas_callback_url)
        redirect_uri = url_concat('%s/login' % self.authenticator.cas_server, {'service': callback_url})
        self.log.info('cas redirect: %r', redirect_uri)
        self.redirect(redirect_uri)


class CASCallbackHandler(CASBaseHandler):
    @gen.coroutine
    def get(self):
        user_name = yield self.authenticator.get_authenticated_user(self, None)
        ssid = self.request.cookies.get('__bqssid', None)
        if ssid:
            ssid = ssid.value
        if not ssid:
            raise web.HTTPError(403)

        if user_name:
            user = self.user_from_username(user_name['name'])
            self.set_login_cookie(user)
            self.set_cookie('__bqasid', CASCallbackHandler.hash_ssid(ssid), expires_days=30, secure=self.request.protocol=='https')
            self.bq_protected_bqssid_verified = True
            self.redirect_next_or_spawn()
        else:
            # todo: custom error page?
            raise web.HTTPError(403)

    def set_secure_cookie(self, name, value, expires_days=30, version=None, **kwargs):
        if not 'httponly' in kwargs:
            kwargs['httponly'] = True
        return super().set_secure_cookie(name, value, expires_days, version, **kwargs)

    @staticmethod
    def hash_ssid(ssid):
        salt = 'E2323FDF3423FWFSDFSDFSF'
        return hashlib.md5((ssid + salt).encode('utf-8')).hexdigest()


class CASLogoutHandler(CASBaseHandler):
    @gen.coroutine
    def post(self):
        if self.current_user:
            self.clear_login_cookie()
        self.clear_cookie('__bqssid', domain='.xs.com')
        self.clear_cookie('__bqasid')
        self.redirect_next_or_url(self.authenticator.cas_logout_url)


class CASAuthenticator(Authenticator):
    login_service = 'CAS'

    cas_server = Unicode(
        os.getenv('CAS_SERVER', ''),
        config=True,
        help="""CAS Server"""
    )

    cas_callback_url = Unicode(
        os.getenv('CAS_CALLBACK_URL', ''),
        config=True,
        help="""Callback URL to use.
        Typically `https://{host}/hub/cas_callback`"""
    )

    cas_logout_url = Unicode(
        os.getenv('CAS_LOGOUT_URL', ''),
        config=True,
        help="""Single logout URL"""
    )

    def login_url(self, base_url):
        return url_path_join(base_url, 'cas_login')

    def get_handlers(self, app):
        return [
            (r'/login', CASLoginHandler),
            (r'/logout', CASLogoutHandler),
            (r'/cas_login', CASLoginHandler),
            (r'/cas_callback', CASCallbackHandler),
        ]

    @gen.coroutine
    def authenticate(self, handler, data=None):
        ticket = handler.get_argument('ticket', None)
        if not ticket:
            raise web.HTTPError(400, "CAS callback made without a ticket")
        # not use handler.request.full_url(): be careful: it's not https
        user_name, attributes = self.verify_cas(ticket, self.cas_callback_url)
        return self._get_notebook_user(user_name)

    def verify_cas(self, *args, **kwargs):
        return self._verify_cas3(*args, **kwargs)

    # https://bitbucket.org/cpcc/django-cas/src/default/django_cas/backends.py
    def _verify_cas3(self, ticket, service):
        """Verifies CAS 3.0+ XML-based authentication ticket and returns extended attributes.
        Returns username on success and None on failure.
        """

        from xml.etree import ElementTree

        params = {'ticket': ticket, 'service': service}
        url = '%s/proxyValidate?%s' % (self.cas_server, urlencode(params))
        page = urlopen(url)
        try:
            user = None
            attributes = {}
            response = page.read()
            tree = ElementTree.fromstring(response)
            if tree[0].tag.endswith('authenticationSuccess'):
                for element in tree[0]:
                    if element.tag.endswith('user'):
                        user = element.text
                    elif element.tag.endswith('attributes'):
                        for attribute in element:
                            attributes[attribute.tag.split("}").pop()] = attribute.text

            return user, attributes
        finally:
            page.close()

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
