### ISSUE TITLE
Not working after upgrade 0.7.2 to 0.8

### ISSUE THREAD

**Issue by dennisverspuij** [jupyterhub/jupyterhub#1508]
I have had JupyterHub 0.7.2 running correctly using a.o. the following settings:
```
c.JupyterHub.hub_ip = '127.0.0.1'
c.JupyterHub.hub_port = 9999
c.JupyterHub.port = 10000
```
When starting the hub a.o. the following was logged:
```
[I 2017-10-27 12:44:32.946 JupyterHub app:1453] Hub API listening on http://127.0.0.1:9999/jupyterhub/hub/
[I 2017-10-27 12:44:32.949 JupyterHub app:1176] Starting proxy @ http://*:10000/jupyterhub/
12:44:33.074 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:9999
12:44:33.091 - info: [ConfigProxy] Proxying https://*:10000 to http://127.0.0.1:9999
12:44:33.091 - info: [ConfigProxy] Proxy API at http://127.0.0.1:10001/api/routes
[I 2017-10-27 12:44:33.153 JupyterHub app:1485] JupyterHub is now running at http://127.0.0.1:10000/jupyterhub/
```

Now I have upgraded to 0.8 (pip upgrade --install jupyterhub ; cd /etc/jupyterhub ; jupyterhub upgrade-db) the following is logged upon startup:
```
[I 2017-10-27 12:50:34.818 JupyterHub app:1539] Hub API listening on http://127.0.0.1:9999/jupyterhub/hub/
[I 2017-10-27 12:50:34.819 JupyterHub proxy:458] Starting proxy @ https://*:10000/jupyterhub/
12:50:34.958 - info: [ConfigProxy] Proxying https://*:10000 to (no default)
12:50:34.961 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
```

Three things are different. First the proxy default-target is not set to http://127.0.0.1:9999 (the command line of the running configurable-http-proxy does not include a default-target option). Second the Proxy API uses port 8001 instead of 10001 (which probably doesn't matter). Third, it does not log ```JupyterHub is now running at```. And indeed JupyterHub cannot be reached.

If I put the following in the settings most logging becomes identical, except for that JupyterHub is running eventually...:
```
c.ConfigurableHTTPProxy.api_url = u'http://127.0.0.1:10001'
c.JupyterHub.proxy_cmd = ['configurable-http-proxy','--default-target','http://127.0.0.1:9999']
```

What should I do to make JupyterHub available again?

**Comment by minrk** [comment]
Proxy default target is no longer used because JupyterHub adds itself as the route at `/`:

    Adding route / -> http://127.0.0.1:9999

This is equivalent, as far as CHP is concerned, but is more generic as non-CHP proxies can now be used.

What's peculiar, and perhaps the key, is that `now running at` is still in the logs. That suggests that something might be hanging in your hub startup. Is there a chance that any hanging processes are still around, e.g. proxy or hub instances?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
