### ISSUE TITLE
Spawning fails: why ? and why sudospawner not detected ? 

### ISSUE THREAD

**Issue by appgar** [jupyterhub/jupyterhub#1515]
I have been running jupyterhub with the default spawner and able to spawn the server of the user that is launching the hub. 

Q1: When I create another user on the system ( sudo useradd foo), and using the default spawner, the spawning fails, essentially raising here: 
```
    (...)/jupyterhub/handlers/login.py", line 93, in post
        yield self.spawn_single_user(user)
```
and failing: 
```
    subprocess.SubprocessError: Exception occurred in preexec_fn.
```
the user foo is authenticated, since I can see the " start server" prompt. 

Q2: I have tried to install sudospawner since I understand it could solve the problem. Ran `pip3 install sudospawner` + sudoer settings + edit of the config file to specify the path:
```
c.JupyterHub.spawner_class = 'sudospawner.SudoSpawner'
c.SudoSpawner.sudospawner_path = '/usr/local/bin/sudospawner'
```
but it seems that the sudospawner install is not detected: 
```
The 'spawner_class' trait of <jupyterhub.app.JupyterHub object at 0x7ff7124f6080> instance must be a type, but 'sudospawner.SudoSpawner' could not be imported
```

using jupyterhub 0.8.0

Great project, Thanks for your help!

**Comment by minrk** [comment]
What do you get from 

    python -c 'from sudospawner import SudoSpawner'

?

Also `pip3 list`?

**Comment by appgar** [comment]
```
$ pip3 list | grep sudospawner
sudospawner (0.5.1)
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
looks like it is here, but:
```
$ python -c 'from sudospawner import SudoSpawner'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'sudospawner'
```
maybe not in python path ?

**Comment by appgar** [comment]
```
>>> sys.path.append("/usr/local/bin/sudospawner")
>>> from sudospawner import SudoSpawner
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'sudospawner'
```
adding path does not change

**Comment by appgar** [comment]
I am using the jupyter-tutorial environment, and for some reason installing it with pip3 while this env is activated, does not install it in the scope of the env. 
I am trying to cherry pick that package manually int the env, no luck using a .pth file, will explore other things. 

Any clue on how to install that sudospawner package into this env ? (it is not on conda or anaconda obv)

**Comment by appgar** [comment]
update: installed the sudospawner package and it is now detected, and I have the following in my config: 
```
c.JupyterHub.spawner_class = 'sudospawner.SudoSpawner'
c.SudoSpawner.sudospawner_path = '/usr/local/bin/sudospawner'
```
when I run jupyterhub, it seems that there is still a mistake for where to lookup the spawner: 
```
[I 171104 21:30:49 mediator:89] Spawning /usr/local/bin/jupyterhub-singleuser --port=53979
[E 171104 21:30:49 mediator:43] mediator result: {'ok': False, 'error': "[Errno 2] No such file or directory: '/usr/local/bin/jupyterhub-singleuser'"}
```
I would expect this to be the path to my sudospawner, ie: `/usr/local/bin/sudospawner` ?
(I tried to force the path with `c.Spawner.cmd = '/usr/local/bin/sudospawner' but no luck)

**Comment by appgar** [comment]
actually, when I remove the force to sudospawner but keep the force to the spawner, it works: 
```
c.JupyterHub.spawner_class = 'sudospawner.SudoSpawner'
#c.SudoSpawner.sudospawner_path = '/usr/local/bin/sudospawner'
c.Spawner.cmd = '/usr/local/bin/sudospawner'
```
by work I mean moving on to the next problem :)

**Comment by appgar** [comment]
I think that issue is closed, will open alt issue if can't resolve other stuff
