### ISSUE TITLE
Counting usage through time

### ISSUE THREAD

**Issue by takluyver** [jupyterhub/jupyterhub#1517]
We're setting up a Jupyterhub instance with tmpauthenticator to provide a demo environment, and we'd like to monitor how much usage it's getting. Not 'how many sessions are currently connected', but 'how many sessions have been started in the last month'.

What's the best way to do this? Is there some part of the API that works by publishing events, so a service could subscribe to 'login' events? Should we extend the `cull_idle_servers.py` script to track how many sessions it has closed down? Should we parse logs (I'm guessing no, unless there's some structured logging going on)?

**Comment by bbrauns** [comment]
you could use something like https://demo.piwik.org/index.php

**Comment by minrk** [comment]
JupyterHub can publish events to statsd, and might be able to be used to this effect. But I haven't used it much.

@akhmerov made a modification to cull_idle_servers to [log activity](https://pastebin.com/zPLJjKpH).

**Comment by akhmerov** [comment]
> @akhmerov made a modification to cull_idle_servers to log activity.

It's very much barebones, so I appreciate any feedback. Also FWIW we're using it in a course now, and it seems to work.

**Comment by yuvipanda** [comment]
statsd should be able to give what you want. Depending on the spawner you use, you can use other monitoring setups too. For example, with kubespawner we just directly monitor kubernetes & derive metrics from there...

**Comment by takluyver** [comment]
Thanks. I've set up statsd using the docker image [from here](https://github.com/graphite-project/docker-graphite-statsd).

This URL on graphite ([API docs](http://graphite-api.readthedocs.io/en/latest/api.html#)) seems to give me more or less what I want:
http://localhost:8180/render?target=stats_counts.jupyterhub.login.request&format=json&from=-1mon&noNullPoints=true

**Comment by akhmerov** [comment]
I'm confused by how jupyterhub activity monitoring works. After processing the dataset during the course I saw [this](http://nbviewer.jupyter.org/url/antonakhmerov.org/misc/programming_activity.ipynb) (only the plot matters).

As you see, there are several servers that report activity throughout the night. What could cause it? How to eliminate these false positives?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻

**Comment by minrk** [comment]
Activity throughout the night suggests that someone might have left a notebook open in their browser, which olds an open connection indefinitely.

**Comment by akhmerov** [comment]
Thanks @minrk! Is there a way to distinguish "open connection and nothing happening" from "user does things"?

**Comment by minrk** [comment]
The notebook knows these things, but the proxy doesn't. Using the notebook's own internal activity monitoring and self-shutdown can make smarter decisions.

**Comment by akhmerov** [comment]
So this would need to be done as a notebook server extension rather than a hub service, right?
