### ISSUE TITLE
500 : Internal Server Error Spawner failed to start [status=1] in only one user

### ISSUE THREAD

**Issue by dmceballosg** [jupyterhub/jupyterhub#1518]
Hello, one users has problem when he tries to login to jupyetrhub, he gets the error message - '500 : Internal Server Error'.The other users doesn't have any problem to access, help me please, I reviewed the local address c.JupyterHub.hub_ip = ''  in the config file, I already tried to follow the instruction in this link:
http://jupyterhub.readthedocs.io/en/latest/troubleshooting.html#error-after-spawning-my-single-user-server
Thanks so much. 
```

**Comment by willingc** [comment]
Hi @dmceballosg,

If the user clears their cookie and the cache in their browser, does the user still see this behavior?

**Comment by dmceballosg** [comment]
Hi @willingc thanks a lot for answer me, I really appreciate your help, but unfortunately I don't think that this is the problem because I already tried to access from other browsers and even others computers, the problem is weird, I fond something similar in this thread but I could not figure out it.

**Comment by willingc** [comment]
Since the problem is only happening with one user, are the permissions for that user's directory on the system different than the rest of the users?

**Comment by dmceballosg** [comment]
All users have the same permission, is super weird hehehe IDk what can be happen. I forgot put the link of the thread 

https://github.com/jupyterhub/jupyterhub/issues/638

Thank :)

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
