### ISSUE TITLE
Question: OAuth state missing from cookies

### ISSUE THREAD

**Issue by grant-guo** [jupyterhub/jupyterhub#1519]
I set up a jupyterhub server with Google authentication support in company's private cloud. The host VM has private ip(10.*) and public IP(142.*).  

However I always got the error "OAuth state missing from cookies" after choosing my google account to log in. 

If I set up the similar env on my local laptop, it works. 

What could be the issue? 

Thanks

**Comment by grant-guo** [comment]
@willingc 
I cleared all of the cookies from my laptop, the error was still there. 
I tried to visit the server from different machines, the error was still there.

The only difference I found is when I ran the server on my local, "redirect_url" is set as "http://localhost:8000/hub/oauth_callback". Instead on could VM, url is "http://jupyterhub.com:8000/hub/oauth_callback". In /etc/hosts file, "jupyterhub.com" points to the public IP address

**Comment by grant-guo** [comment]
solved. Add the hostname in redirect URI to the DNS

**Comment by minrk** [comment]
For future reference if anyone comes by this Issue, some background on how the OAuth process works for a fresh login:

1. user visits Hub with no credentials
2. **Hub sets state cookie** (cookies are confined to the current page's host)
3. Hub redirects to OAuth provider (Google) with state in the URL parameter
4. User logs in with OAuth provider
5. OAuth provider redirects back to Hub (via pre-registered OAuth callback URL)
6. **Hub validates OAuth state**, comparing cookie value to URL value
7. Hub completes OAuth

The relevant steps are in bold. In order for the state validation to work, the cookie set when redirected away from the Hub must be readable on the redirect back to the Hub. Among other things, this means the hostname of the initial URL at which the user visited the Hub must be the same hostname registered with the OAuth provider for the callback, otherwise the cookie set in step 2. won't be part of the request in step 6, causing the "OAuth state missing from cookies" error.

**Comment by umar-sik** [comment]
I am using kubernetes with jupyterhub. When I use Auth0 as an authentication API, I always get the error "OAuth state missing from cookies" after choosing my google account to log in. 

What could be the issue?

Thanks

**Comment by tankeryang** [comment]
@grant-guo would you tell me add the hostname to which machine's DNS? laptop?

**Comment by lgc019** [comment]
I got the same issue when it redirects back from identity provider (Azure AD), the request url looks like below, I delete code value only for readable.
http://[ipaddress]/hub/oauth_callback?code=AQABAAIAAADX8GCi6Js6SK82TsD2Pb7rwp...&state=eyJzdGF0ZV9pZCI6ICJkZTgwZWFmYzUzZDE0M2ZlODA5MmJmOGI4ZTkyNWQxNCIsICJuZXh0X3VybCI6ICIifQ%3d%3d&session_state=de5058a6-2815-4fc1-9ca3-01ffbe9971b9

the response header related to cookies look like below:
set-cookie: oauthenticator-state=""; expires=Tue, 20 Jun 2017 02:36:03 GMT; Path=/

**Comment by lgc019** [comment]
I am sure the ip address of the initial URL at which the user visited the Hub is the same ip address registered with the OAuth provider (Azure AD) for the callback.

I appreciate if someone could help me on this issue. thanks!

**Comment by lgc019** [comment]
let me paste the request cookie as below:

oauthenticator-state="2|1:0|10:1529472512|20:oauthenticator-state|120:ZXlKemRHRjBaVjlwWkNJNklDSTFNbU0wWVRKalptSmxNVE0wTjJJNE9XRTRaVFkyT0RreVpXRXlZak0yWVNJc0lDSnVaWGgwWDNWeWJDSTZJQ0lpZlE9PQ==|19baefda0a20053944c100ff3881cb1df2a8c8622e5b62674712e935d6c20c12"

**Comment by lgc019** [comment]
I found my authorize url is generated as below:
https://login.microsoftonline.com/<tenant>/oauth2/authorize?redirect_uri=http%3A%2F%2F<ipaddress>%2Fhub%2Foauth_callback&client_id=eebb162d-c55f-43fc-b009-93915cb393a9&response_type=code&state=eyJzdGF0ZV9pZCI6ICJlNmUwNGRkY2RjNzk0YTRlYTkxNmQ2NDZhZDlkMGI2OSIsICJuZXh0X3VybCI6ICIifQ%3D%3D

but from microsoft documentation, it requires the parameter as following, it seems 'nonce' and 'scope' are missing here. Is there any other configuration I have to provide in the helm config file?
GET https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize?
client_id=6731de76-14a6-49ae-97bc-6eba6914391e
&response_type=id_token
&redirect_uri=http%3A%2F%2Flocalhost%2Fmyapp%2F
&response_mode=form_post
&scope=openid
&state=12345
&nonce=678910 
·	The request must include the openid scope in the scope parameter.  
·	The response_type parameter must include id_token.  
·	The request must include the nonce parameter.

**Comment by abdollahiazam** [comment]
Hi, 
I want to sign in with JupyterHub, I have this error:
"400 : Bad Request  OAuth state missing from cookies"

https://jupyter.designsafe-ci.org/hub/oauth_callback?state=eyJuZXh0X3VybCI6ICIiLCAic3RhdGVfaWQiOiAiMjQ0OTQ0YmRlODRkNDc3NThjZjhiNGI1NGRkZDExYzQifQ%3D%3D&code=5485ee20d2b5e427acb99a29f0ab92aa

I appreciate if someone could help me on this issue. 
thanks

**Comment by divatemangesh** [comment]
-----------------------------------------------------third attempt ---------------------------------------------------------

cleared browser cookies and cache and any saved data and in New Tab opened https://localhost
security warning came  like site is not safe  I clicked on proceed safely 
In chrome  ctrl+shift+C>> application >> cookies I can see following entries 
Sign in with gitlab page

Name:- xsrf
Value:- 2|d6b491b6|bf36d80df77faf9466583355e204eb77|1550066103
Expires:-  2020-03-15T13:55:03.000Z

Name:- username-localhost-8888
Value:-"2|1:0|10:1551431956|23:username-localhost-8888|44:MmU4ZDlmY2JkMzRkNDNjNWJhOTJiNmQ4NzNmYjA4NDA=|d5174b5df574432e334f4733f11943c12caf3cf3e05c4b47c7c962937c2a8960"
Expires:- 2020-03-31T09:19:16.000Z
-------------------------------- Once Clicked on Sign in with gitlab  button ----------------------------
additional one entry came and disappered in less than half second and I landed to GitLab-CE login page but I screen recorded it  to see the disappred entry 

The one which disappeared was 

Name :- oauthenticator-state 
Value:- "2|1:0|10:1552127982|20:oauthenticator-state|120:Z... was not able to see comple value as it was partialy visiable in recording
expires :- 2019-03-10T1 ...

-------------------Once landed on gitlab-CE login-----------------------------------

Name:- _gitlab_session
Value:- ba46390addc98a11c22e4cd4dd064fdb
Expires:- 2019-03-09T12:39:42.873Z

---------------------loged in to gitlab with username-----------------------------
_gitlab_session
6dc3812c2eb2a0593ed8cb6c4f4f12b6
1969-12-31T23:59:59.000Z

--------------------Once Clicked on authosise in gitlab------------
Name:- _xsrf
Value :- 2|d6b491b6|bf36d80df77faf9466583355e204eb77|1550066103
Expireds:- 2020-03-15T13:55:03.000Z

Name:- username-localhost-8888
Value:- "2|1:0|10:1551431956|23:username-localhost-8888|44:MmU4ZDlmY2JkMzRkNDNjNWJhOTJiNmQ4NzNmYjA4NDA=|d5174b5df574432e334f4733f11943c12caf3cf3e05c4b47c7c962937c2a8960"
Expires:- 2020-03-31T09:19:16.000Z

GOT 500 INTERNAL SERVER ERROR

**Comment by dharif23** [comment]
why this issue is closed? I have checked the request and response both has the same url yet i have the error

**Comment by akaszynski** [comment]
Had the exact same issue and fixed it by modifying
```
oauth_callback_url: "https:/website-dev.com/hub/oauth_callback"
```
to
```
oauth_callback_url: "https://www.website-dev.com/hub/oauth_callback"
```

Issue was related to the domain name records.

**Comment by stephen-a2z** [comment]
I solve the error by the following command:
```
sudo tljh-config set hub.db.upgrade Ture
```
hope it's helpful for you

**Comment by bstrdsmkr** [comment]
Just ran into this error message today and wanted to post my solution for others that land here. Based on @minrk 's comment:

> For future reference if anyone comes by this Issue, some background on how the OAuth process works for a fresh login:
> 
> 1. user visits Hub with no credentials
> 2. **Hub sets state cookie** (cookies are confined to the current page's host)
> 3. Hub redirects to OAuth provider (Google) with state in the URL parameter
> 4. User logs in with OAuth provider
> 5. OAuth provider redirects back to Hub (via pre-registered OAuth callback URL)
> 6. **Hub validates OAuth state**, comparing cookie value to URL value
> 7. Hub completes OAuth
> 
> The relevant steps are in bold. In order for the state validation to work, the cookie set when redirected away from the Hub must be readable on the redirect back to the Hub. Among other things, this means the hostname of the initial URL at which the user visited the Hub must be the same hostname registered with the OAuth provider for the callback, otherwise the cookie set in step 2. won't be part of the request in step 6, causing the "OAuth state missing from cookies" error.

It became apparent that the client had cookies blocked in their browser which caused this error message even though login appeared to work fine and nothing useful showed up in the pod logs

**Comment by MaisamMD** [comment]
I have the same issue. If the problem comes from cookies in the browser, is there any solution to tackle this issue?

**Comment by bstrdsmkr** [comment]
@MaisamMD not from the server (jupyterhub) side, it's a client side issue. Look for anything that would block cookies and allow the jupyterhub cookie

**Comment by MaisamMD** [comment]
> @MaisamMD not from the server (jupyterhub) side, it's a client side issue. Look for anything that would block cookies and allow the jupyterhub cookie

I did a test with Chrome on a different machine (Windows OS) and it worked. But with firefox on my ubuntu machine, it does not work. I cleared the saved cookies from the browser but did not help. Is there any idea?

**Comment by luweizheng** [comment]
Almost same with @MaisamMD 
JupyterHub does not work on Chrome and Firefox on my mac, but works fine on Safari.
If I add https support, should it be better ？

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/keycloak-identity-management-500-internal-server-error/12263/9

**Comment by iiiok** [comment]
I fixed the issue by changing 
NEXTAUTH_URL="http://localhost:3000" in .env
to NEXTAUTH_URL=http://localhost:3000
// remove the "  "

**Comment by paulwrath1223** [comment]
I got this because I registered my app as using `http://localhost:8000`, but was viewing from `127.0.0.1:8000`, simply visiting it from localhost solved the issue.
