### ISSUE TITLE
save logs of the single-user server

### ISSUE THREAD

**Issue by disimone** [jupyterhub/jupyterhub#1522]
Dear all,

first of all, thanks for providing this software.

I am having a issue with notebooks not being autosaved. The log of the hub itself has no relevant information, so I want to access the logs of the single-user servers.

Is there an option to save these logs somewhere on disk? Ideally I would like to add some output redirection to c.Spawner.args (possibly to user-specific files), but all attempts have failed, due to extra quotes being added in a way that (to me) looks quite unpredictable.

For example:

`c.Spawner.args=['--someOption=someValue','--anotherOption=andItsValue']
`
results, as expected, in

`jupyterhub-singleuser --someOption=someValue --anotherOption=andItsValue
`
but

`c.Spawner.args=['--someOption=someValue','--anotherOption=andItsValue >/tmp/aLogFile.log 2>&1']
`
results in
`
jupyterhub-singleuser --someOption=someValue '--anotherOption=andItsValue >/tmp/aLogFile.log 2>&1'`

What is the recommended way to save the servers logs?

Thanks for your help,

Andrea.

**Comment by minrk** [comment]
It will depend on your Spawner where the logs go. For the default LocalProcessSpawner, single-user logs go to the same stdout/stderr as the Hub itself, so if you are capturing the Hub logs, the single-user logs will be in the same place.

**Comment by disimone** [comment]
Hi @minrk , thanks for the answer. I am confused, though, probably because I did not give enough information here. In the hub configuration, I am using the extra_log_file option to log the hub-related events.

According to the documentation, this should not include the single-user logs, which AFAICT is indeed what is happening.

So how do I trap the single-user logs in a separate file? Or how to I redirect also the single-user logs to extra_log_file? Separate log files per user also seem like something one would need, in particular in a scenario when many users use the hub at the same time.

I understand I could implement my own spawner, but logging seems like that kind of basic feature that one would expect to work out-of-the-box, so I thought I'd rather ask here before.

Thanks for your help,

Andrea.

**Comment by minrk** [comment]
Ah. `extra_log_file` explicitly separates the Hub logs from the single-user logs, which are still being sent to stdout/stderr of the Hub's process. For this reason, I don't really recommend that anyone use `extra_log_file` unless you are sure that you *don't* want to see the logs of the proxy or single-user servers, or have already ensured they are captured elsewhere.

If you want logging to a file, output redirection is a more robust approach that works for JupyterHub, as well as every other program:

    jupyterhub &>> /var/log/jupyterhub.log

This will capture all output from jupyterhub and its subprocesses, including the proxy and single-user servers.

Or, if you are using systemd/supervisor/etc. to launch your process, there is always a stdout/stderr capture option, which is the right way to go.

**Comment by disimone** [comment]
Hi @minrk , thanks for the reply. I will use redirection then. And reopen in case I still have difficulties.

Cheers,

Andrea.

**Comment by dado0583** [comment]
I have a question on the above. My Spawner uses jupyterhub-singleuser, so I set up my config like this:

c.Spawner.cmd = ['jupyterhub-singleuser &>> /apps/valrs/services/jupyter-notebook/logs/jupyterhub-singleuser.log']

However I get this error:

FileNotFoundError: [Errno 2] No such file or directory: 'jupyterhub-singleuser &>> /apps/valrs/services/jupyter-notebook/logs/jupyterhub-singleuser.log'

When I run it directly from the shell it works okay. Am I being silly?

**Comment by minrk** [comment]
The `&>>` is interpreted by the shell program itself, and is not part of the system command that is executed. The Python equivalent would be:

```python
from subprocess import Popen, STDOUT
logfile = open('/.../singleuser.log', 'wb')
Popen(['jupyterhub-singleuser'], stdout=logfile, stderr=STDOUT)
```

If you want to do shell-y stuff, you could write your own entrypoint that calls jupyterhub-singleuser, e.g.

```bash
#!/bin/bash -l
export MYVARIABLE=foo
exec jupyterhub-singleuser "$@" &>> /var/log/jupyterhub/$USER.log
```

and tell the Spawner to use that:

```python
c.Spawner.cmd = 'my-jupyterhub-singleuser'
```
