### ISSUE TITLE
alpine hub-only docker image

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#1523]
It would probably be nice to have an official hub-only docker image based on alpine, for a minimal image for use in cluster deployments where the proxy is run in another container (e.g. the helm chart).

A starting point that gets most of the way there:

```dockerfile
FROM alpine:3.6
RUN apk add --no-cache python3 && \
    pip3 install --no-cache jupyterhub==0.8.0
ENV LANG=en_US.UTF-8
CMD ["jupyterhub"]
```

is only 88MB (smaller than `python:3.6-alpine`). Our jessie-based images are *much* bigger than that.

In particular, this image should:

1. lack nodejs, configurable-http-proxy
2. launch jupyterhub as the default command (or entrypoint?)
3. probably run as `nobody`

@jzf2101 this might be a good sprint topic for anyone interested in Docker

**Comment by betatim** [comment]
Could this replace https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/master/images/hub?

**Comment by minrk** [comment]
@betatim not replace, because that one installs several authenticators, and this one should be a bare starting point. But it could serve as its base (or reference).

**Comment by yuvipanda** [comment]
yeah, plus we have a very custom jupyterhub_config.py there.

**Comment by ankitml** [comment]
@minrk I am in PyConCA sprints right now and would like to claim it. I have started with following this tutorial http://jupyterhub.readthedocs.io/en/latest/quickstart-docker.html to replicate the current status quo of dockerfile. cc @betatim @yuvipanda

**Comment by jzf2101** [comment]
@choldgraf ?

**Comment by ankitml** [comment]
Hi @choldgraf, I am trying to run jupyterhub without the nodejs based configurable proxy. Looks like you are the best person for knowing how to do it. 
What I have is 
```ConfigurableHTTPProxy.should_start=False``` in the config. 
But running jupyterhub cases connection error while doing 
```self.proxy.check_routes``` in app.py

**Comment by choldgraf** [comment]
Hmmm, I think probably @minrk or @yuvipanda would know this better than I, actually!

**Comment by minrk** [comment]
The proxy has to be running already in order to do this. You'll need to:

1. start configurable-http-proxy in another container
2. specify `CONFIGPROXY_AUTH_TOKEN` env in both containers
3. put both containers on the same network (e.g. `docker create network jupyterhub; docker run ... --net jupyterhub`)
4. tell jupyterhub where CHP is (e.g. `c.ConfigurableHTTPProxy.api_url = 'http://chp:8001'`)
5. tell jupyterhub not to start the proxy itself (`c.ConfigurableHTTPProxy.should_start = False)

**Comment by ankitml** [comment]
Work in Progress PR is here https://github.com/jupyterhub/jupyterhub/pull/1555.

**Comment by ankitml** [comment]
@minrk This issue can be closed now. The related PR is merged.  Is there anything more left to be desired? If not, then I intend to work on few examples and docker related documentations  in the coming weeks.

**Comment by minrk** [comment]
Examples would be great!
