### ISSUE TITLE
Jupyterhub 0.8.0 radio buttons unclickable or ugly due to form-control class

### ISSUE THREAD

**Issue by alex1x** [jupyterhub/jupyterhub#1524]
```
jupyterhub --version
0.8.0
```

I have some radio buttons in my spawner's `_option_form_default`:

```
return """<label for="type">Which type of instance do you want to launch?</label>
        <table>
        <tr>
        <td><input type="radio" name="type" value="c4.8xlarge" checked="checked"></td>
        <td>&nbsp;c4.8xlarge (36 CPU, 60GB RAM, $1.591/h)</td>
        </tr>
        <tr>
        <td><input type="radio" name="type" value="r4.8xlarge"></td>
        <td>&nbsp;r4.8xlarge (32 CPU, 244GB RAM, $2.341/h)</td>
        </tr>
        </table><br>
        """
```

In `0.8.0` version these are unclickable. Removing `form-control` class introduced [here](https://github.com/jupyterhub/jupyterhub/blob/master/share/jupyter/hub/templates/spawn.html) fixes the issue for me. 

I also tried buttons like this:

```
        <tr>
        <td><label>
        <input type="radio" name="type" value="c4.8xlarge">
        &nbsp;c4.8xlarge (36 CPU, 60GB RAM, $1.591/h)
        </label></td>
        </tr>
```

These are clickable but look ugly with the `form-control` class. 

Removing the `form-control` class makes them both clickable and pretty :)

**Comment by minrk** [comment]
Agreed, we shouldn't be messing with your HTML like that. #1526 should fix it.
