### ISSUE TITLE
Toree SparkR integration

### ISSUE THREAD

**Issue by hani1814** [jupyterhub/jupyterhub#1530]
Hi,

I've got Microsoft Open R, SparkR and toree spark kernel configured. 

I can retrieve data into a dataframe if I run SparkR command line but it fails in the notebook. with the following error

name: org.apache.toree.interpreter.broker.BrokerExceptionMessage: Error: is.character(x) is not TRUE

Simple R code works.

**Comment by mariusvniekerk** [comment]
I'd recommend asking this on the Toree mailing list

**Comment by willingc** [comment]
Thanks @hani1814 for the question and @mariusvniekerk for the response. I agree that asking on the Toree mailing list would be a good next step.
