### ISSUE TITLE
Please reopen #1087

### ISSUE THREAD

**Issue by lphk92** [jupyterhub/jupyterhub#1537]
There are several users (myself included) for which the workaround outlined in Issue #1087 does not work any more.

Could you reopen that issue and either provide more reasoning as to why allowing cross origin websocket request is strictly prohibited, or why using `c.Spawner.args = ['--NotebookApp.allow_origin=*']` no longer works?

**Comment by willingc** [comment]
cc @minrk

@lphk92 I've reopened #1087. I'm going to close this one and let #1087 continue this discussion.

**Comment by minrk** [comment]
I think there's some confusion. Cross-origin websockets are certainly not strictly prohibited, and the config given does enable cross-origin access to a running notebook server with current versions of the notebook and jupyterhub. If it doesn't there is likely a bug where the argument is not actually getting passed to the notebook server, which could be a bug in the Spawner. Which Spawner are you using?

#1087 is *not* about cross-origin access to the notebook, which works, but cross-origin access to the Hub's API itself, which does not.
