### ISSUE TITLE
Couldnt configure Jupyterhub (in AWS EMR) notebook_dir to s3 location

### ISSUE THREAD

**Issue by raksja** [jupyterhub/jupyterhub#1538]
Jupyterhub is configured in AWS EMR using this as a reference
https://aws.amazon.com/blogs/big-data/running-jupyter-notebook-and-jupyterhub-on-amazon-emr/
I used these options on when we bootstrap EMR 
```--jupyterhub,--jupyterhub-port,8002,--cached-install,--notebook-dir,s3://mynotebookbucket/notebooks/```

I noticed the following on our master node. 

1. A notebook process
2. Jupyterhub process
3. Configurable http proxy
4.  For every user, it spins a singleuser process using LocalProcessSpawner. 

And for every user the notebook directory is by default goes to their home directory. 
I added a new file (.jupyter/jupyter_notebook_config.py) under one of the user's home and specified an s3 location as a notebook_dir using 

```
c.NotebookApp.contents_manager_class = 's3contents.S3ContentsManager'.
c.S3ContentsManager.bucket_name = 'mynotebookbucket'
#c.S3ContentsManager.prefix = '${username}/notebooks'
c.S3ContentsManager.prefix = '/notebooks'
```

However the server start failed with exception, but couldn't find any user logs.

```"API request failed (500): Spawner failed to start [status=1]. The logs for <user> may contain details."  ```

This could be a bug, because above mentioned process no.1 which is not accessible through jupyterhub have the same s3 configuration and it works, i can see the notebook created through that in s3 location. 

Is there a way I can provide an s3 location as mentioned above?

**Comment by minrk** [comment]
I would expect this to work, as long as S3ContentsManager works. What do you see in the user's logs when they launch?

For shared configuration, you may want to put it in `/etc/jupyter/jupyter_notebook_config.py` which is loaded by all users, instead of copying a file to everyone's `~/.jupyter/` directory.

**Comment by ksraja** [comment]
I couldn't find the user logs, where should I be looking? Even in localprocessspawner there is no log file location mentioned.
I see only jupyterhub.log and jupyter.log.

With shared configuration, can I create a folder with user name on it?

**Comment by raksja** [comment]
@minrk looks like there are no logs being setup for localprocessspawner when single user instances are launched. is there a quick way to figure what went wrong?

**Comment by raksja** [comment]
@minrk, finally i did some other way to get all the standard log of jupyterhub and this is what i get, any thoughts??


```
[I 2017-11-17 19:39:32.430 JupyterHub spawner:978] Spawning jupyterhub-singleuser --port=32794
[D 2017-11-17 19:39:32.456 JupyterHub spawner:727] Polling subprocess every 30s
[D 2017-11-17 19:39:32.469 JupyterHub base:427] 0/100 concurrent spawns
[D 2017-11-17 19:39:32.469 JupyterHub base:430] 1 active servers
[C 2017-11-17 19:39:33.052 SingleUserNotebookApp application:90] Bad config encountered during initialization:
[C 2017-11-17 19:39:33.052 SingleUserNotebookApp application:91] The 'contents_manager_class' trait of <jupyterhub.singleuser.SingleUserNotebookApp object at 0x7f12e346dda0> instance must be a type, but 's3contents.S3ContentsManager' could not be imported
Single-user server for JupyterHub. Extends the Jupyter Notebook server.

Meant to be invoked by JupyterHub Spawners, and not directly.
```

**Comment by gbrahmi** [comment]
I had similar problems I fixed it by running the setup.py install for Python3 along with Python which the script performs.

**Comment by willingc** [comment]
Thanks @gbrahmi

**Comment by liusztc09** [comment]
@gbrahmi Could you please provide the scripts you ran to get rid of the problem? Thanks a lot!

**Comment by gbrahmi** [comment]
I used the same script which was shared in the EMR blog. The change was in the line where s3content is installed. So the following lines:

```
      git clone https://github.com/tomz/s3contents.git
      cd s3contents
      sudo python setup.py install
```

Is changed to the following:

```
      git clone https://github.com/tomz/s3contents.git
      cd s3contents
      sudo python setup.py install
      sudo python3 setup.py install
```

**Comment by liusztc09** [comment]
@gbrahmi Will give it a try, thanks a lot!
