### ISSUE TITLE
Release in Windows 

### ISSUE THREAD

**Issue by yougha54** [jupyterhub/jupyterhub#1544]
Hello, 
I would like to know if a release of JupyterHub  will be available for Windows

**Comment by willingc** [comment]
Hi @yougha54,

It is not officially available for Windows. Please refer to the [platform support documentation](http://jupyterhub.readthedocs.io/en/latest/installation-basics.html#platform-support) for full details. Thanks!

**Comment by ociule** [comment]
FWIW, using [jupyterhub-winauthenticator](https://github.com/ni/jupyterhub-winauthenticator) and [jupyterhub-winlocalprocessspawner](https://github.com/ni/jupyterhub-winlocalprocessspawner) works fine on Windows, with jupyterhub master.
