### ISSUE TITLE
login jupyterhub with token

### ISSUE THREAD

**Issue by gaorongchao** [jupyterhub/jupyterhub#1546]
I embed jupyterhub in flask,
now when i open jupyterhub from flask app,I have to use username and password in web page.
I want to people who has already login flask app open jupyterhub automatic。

now I can got token use rest api. Is there anyway to do like this?

**Comment by minrk** [comment]
Yes, you can use tokens with JupyterHub. If you have an admin API token already in your application, you can request a token with:

    POST /hub/api/authorizations/token
    headers:
        Authorization: token <admin-api-token>
    body:
        {'username': 'theirname'}

**Comment by gaorongchao** [comment]
Thank You very much ,I can get the token now!

**Comment by minrk** [comment]
Access tokens cannot be transformed into full logins without a custom Authenticator or LoginHandler. They can only be used for API access e.g. via the Authorization header. Access tokens may have reduced permissions relative to a full login, so that should be taken into account.
