### ISSUE TITLE
Doc Requirements are Incomplete

### ISSUE THREAD

**Issue by jzf2101** [jupyterhub/jupyterhub#1549]
@syutbai also noticed this bug as well

**Comment by willingc** [comment]
The doc requirements.txt are found in the docs directory. The dependencies should match watch is in the environment.yml.

We use conda in the readthedocs.yml to build the docs on ReadTheDocs.

**Comment by willingc** [comment]
What is missing @jzf2101?

**Comment by jzf2101** [comment]
jupyter-alabaster-theme==0.4.0

**Comment by willingc** [comment]
I'm cool with that addition in #1550. Thanks @syutbai for noticing and for the PR.

@jzf2101 As an FYI, we use conda and the environment.yml to build docs on Read The Docs. I'm fine with updating any of the pip installation stuff in requirements.txt but don't want to move the actual documentation on RTD to pip. It would be cool to test them on Travis using make linkcheck as well as make html though I would initially not fail Travis if the docs don't build.

I'm heading for a flight in a few minutes. I'll check back when in the airport.
