### ISSUE TITLE
Redirect loop detected on login with JupyterHub 0.8.1, on AWS/Ubuntu using SSL tunnel

### ISSUE THREAD

**Issue by Andy-Doddington** [jupyterhub/jupyterhub#1551]
As detailed above, I am trying to run a copy of JupyterHub on a single Amazon EC2 instance, running Ubuntu 16.04. I manually installed all components, using a combination of Anaconas and apt-get/pip. I have generated a self-signed certificate, since that is all that is available under AWS. I am using SSL tunnelling to connect from my OS X client to the server.

I have discovered that I have to run jupyterhub as root for the PAMAuthenticator to work properly, which is something that I'd like to address in the future. However, for now, the bigger issue is that I am getting "Redirect Loop Detected" error, whenever I try to log in from my client. This occurs with Safari, Firefox and Chrome.

The "troubleshoot" log output is as shown below:

[jupyterhub.log](https://github.com/jupyterhub/jupyterhub/files/1492095/jupyterhub.log)

pip list | grep jupy gives the following output:

jupyter-client (5.1.0)
jupyter-console (5.2.0)
jupyter-core (4.3.0)
jupyterhub (0.8.1)
jupyterlab (0.27.0)
jupyterlab-launcher (0.4.0)

Using Python 3.6.3

Any help will be gratefully received - I'm tearing my hair out on this one :-(

**Comment by minrk** [comment]
Can you include the logs from the single-user server as well? I only see the Hub's own output. If you are starting jupyterhub in a terminal, these will be all together. If you are starting jupyterhub with a service, make sure to capture the Hub's stdout and stderr, e.g.

    jupyterhub &>> /var/log/jupyterhub.log

If you are using the `extra_log_file` configuration, *please don't*, and if some docs suggested this to you, can you point them out so they can be updated?

**Comment by Andy-Doddington** [comment]
ubuntu@ip-172-31-39-148:~$ ##################################################
ubuntu@ip-172-31-39-148:~$ ##################################################
ubuntu@ip-172-31-39-148:~$ ##################################################
ubuntu@ip-172-31-39-148:~$ grep extra jupyterhub_config.py
#c.JupyterHub.extra_log_file = '/var/log/jupyterhub.log'
#c.JupyterHub.extra_log_file = ''
#c.JupyterHub.extra_log_handlers = []
## Supply extra arguments that will be passed to Jinja environment.
#  Admin users have extra privileges:
ubuntu@ip-172-31-39-148:~$ ##################################################
ubuntu@ip-172-31-39-148:~$ ##################################################
ubuntu@ip-172-31-39-148:~$ sudo /home/ubuntu/anaconda3/bin/jupyterhub troubleshoot
[W 2017-11-22 16:15:58.891 JupyterHub proxy:415]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

16:15:59.016 - info: [ConfigProxy] Proxying https://*:8000 to (no default)
16:15:59.019 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[W 2017-11-22 16:15:59.360 JupyterHub proxy:304] Adding missing default route
16:15:59.360 - info: [ConfigProxy] 200 GET /api/routes
16:15:59.365 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
16:15:59.366 - info: [ConfigProxy] 201 POST /api/routes/

# <<< My comment: Connect from remote client at this point >>>
# <<< Client displayed button for me to restart server, which I did

Last login: Wed Nov 22 11:21:12 UTC 2017
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-1038-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

31 packages can be updated.
0 updates are security updates.


*** System restart required ***
[I 2017-11-22 16:17:31.867 SingleUserNotebookApp extension:46] JupyterLab alpha preview extension loaded from /home/ubuntu/anaconda3/lib/python3.6/site-packages/jupyterlab
JupyterLab v0.27.0
Known labextensions:
[I 2017-11-22 16:17:31.868 SingleUserNotebookApp extension:93] Running the core application with no additional extensions or settings
[I 2017-11-22 16:17:31.871 SingleUserNotebookApp singleuser:365] Starting jupyterhub-singleuser server version 0.8.1
[I 2017-11-22 16:17:31.875 SingleUserNotebookApp notebookapp:1366] Serving notebooks from local directory: /home/andy_d
[I 2017-11-22 16:17:31.875 SingleUserNotebookApp notebookapp:1366] 0 active kernels
[I 2017-11-22 16:17:31.875 SingleUserNotebookApp notebookapp:1366] The Jupyter Notebook is running at: http://127.0.0.1:49740/user/andy_d/
[I 2017-11-22 16:17:31.875 SingleUserNotebookApp notebookapp:1367] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2017-11-22 16:17:31.973 SingleUserNotebookApp log:122] 302 GET /user/andy_d/ → /user/andy_d/tree? (@127.0.0.1) 0.47ms
16:17:31.976 - info: [ConfigProxy] Adding route /user/andy_d -> http://127.0.0.1:49740
16:17:31.977 - info: [ConfigProxy] 201 POST /api/routes/user/andy_d
[W 2017-11-22 16:17:32.199 JupyterHub base:794] Redirect loop detected on /hub/user/andy_d/?redirects=1
[W 2017-11-22 16:17:34.514 JupyterHub base:794] Redirect loop detected on /hub/user/andy_d/?redirects=2
[W 2017-11-22 16:17:38.709 JupyterHub base:794] Redirect loop detected on /hub/user/andy_d/?redirects=3
[W 2017-11-22 16:17:47.013 JupyterHub web:1587] 500 GET /hub/user/andy_d/?redirects=4 (127.0.0.1): Redirect loop detected.
[E 2017-11-22 16:17:47.020 JupyterHub log:114] {
      "Host": "localhost:6565",
      "Connection": "keep-alive",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "Referer": "http://localhost:6565/hub/home",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
      "Cookie": "jupyter-hub-token=\"2|1:0|10:1511207549|17:jupyter-hub-token|44:MDFkOWIyOGZhZjAzNDg1YjlkZjlmYzk2YWIzN2NjMGE=|e6badb437c37c4af9ab438c17cc0dd3a9b8061cb09429f51704861b2f145bfa0\""
    }
[E 2017-11-22 16:17:47.021 JupyterHub log:122] 500 GET /hub/user/andy_d/?redirects=4 (andy_d@127.0.0.1) 8.07ms
^C     <<<=== I manually killed it here >>>
Interrupted
[I 2017-11-22 16:17:56.624 SingleUserNotebookApp notebookapp:1308] Shutting down kernels
ubuntu@ip-172-31-39-148:~$

**Comment by willingc** [comment]
@minrk FYI. I checked (did a search on the jupyterhub org for `extra_log_file`) and only reference at the moment is the deprecation in the latest jupyterhub config docs. I didn't see it used anywhere else here.

**Comment by Andy-Doddington** [comment]
@willingc , yes, I only set this option because I happened to find it in the config file (not marked as deprecated). I had the hope that "more would be better" ;-) I have now commented it back out again as evidenced by the grep in my earlier post, above.

**Comment by willingc** [comment]
Yes, you are correct @Andy-Doddington. My post to Min was just a followup to the PR that we just merged to deprecate `extra_log_file` in the next version. Thanks for flagging this for us. It's something that we have been meaning to deprecate and it fell through the cracks.

**Comment by minrk** [comment]
@Andy-Doddington did you mean to close the issue? Did you figure it out? The loop looks like the proxy is being bypassed, such as would happen if you visited port 8081 instead of port 8000. What's the URL you are using to access the Hub?

**Comment by Andy-Doddington** [comment]
@minrk - Ugh, sorry - didn't mean to close it.

I am using a URL of the form: http://localhost:6543, based on an ssh tunnel command of the form:

aaa
`ssh -i foobar.pem -N -f -L 6543:localhost:80 ubuntu@<ec2-public-url>`

**Comment by minrk** [comment]
That line looks like it's forwarding to port 80. But the proxy is on port 8000 and the hub is on port 8081. What port are your forwarding to? Make sure it's 8000 and not 8081.

**Comment by Andy-Doddington** [comment]
OK, apologies for the delay over the weekend - grandson's birthday!

To play safe, I created a totally new AWS instance in installed Jupyterhub, starting with the anacondas bundle before finishing off with the instructions detailed on the project GitHub. I created a tunnel forwarding from port localhost:7777 to 8000 on the Jupyterhub server. To further keep things as simple as possible, I didn't add much to the jupyterhub_config, apart from making me (andy_d) an admin, and activating the PAMAuthenticator. In particular, I didn't specify either a key or certificate - the interface seems to work just as well without this so I'm not sure why I originally felt I needed it (apart from wanting to get rid of the SSL warning on the logon screen).

This time around, there was no sign of redirect loops, which is an improvement of sorts - although I cannot imagine why things have changed to such an extent. I'm pretty sure (i.e. 99%) that I was tunnelling to port 8000 previously.

The attached logs show all of the grisly details - the root cause apparently being:

` FileNotFoundError: [Errno 2] No such file or directory: 'jupyterhub-singleuser'`

Which has the feel of something that ought to be simple to fix (laughing optimistically to myself)

With apologies for dragging this one out so long - I'll do some googling around the File Not Found and see what I can come up with. Meantime, if you have any thoughts then please let me know ;-)

[jupyterhub_new.log](https://github.com/jupyterhub/jupyterhub/files/1507057/jupyterhub_new.log)

**Comment by Andy-Doddington** [comment]
**### Success at last!**

As you are no doubt aware, the previous issue (FileNotFound) was because the jupyterhub-singleuser application was not on my path.

I resolved the issue by doing the following:

1) Creating a fresh user, just for running jupyterhub
2) Installing all libs etc from that user account, including adding an anaconda3 directory under this user's home directory.
3) Creating a config file in /etc/jupyterhub and making that owned by the jupyterhub user.
4) Running jupyterhub from that user's home directory.

After that, it all seemed to work!

Minor issues are that:

a) I seem the to have to run in the same directory as the sqlite database file (although it may be that I just need to have rw ccess to this file - which would make sense).
b) My python libraries don't seem to be visible to my jupyter notebook. I'm guessing this is something I can set in the config file.

Anyhoo - all the big issues seem to be sorted now. The rest I *think* I can sort myself. Thanks once again for your patience and responsiveness.
