### ISSUE TITLE
413 Request Entity Too Large error when saving a not very large notebook

### ISSUE THREAD

**Issue by rydeng** [jupyterhub/jupyterhub#1569]
413 Request Entity Too Large error when saving a not very large notebook，How can I save a larger notebook？

**Comment by mklan** [comment]
how did you managed to get it working? I have the same issue

**Comment by rkdarst** [comment]
Wow, I just had the same problem.

Basically, notebook/jupyterlab was trying to POST/PUT a notebook that was larger than its configured maximum body size.  The server returns 413 before it made it to the applicaiton.

In my case, we were using kubernetes nginx ingress which has nginx default of 1M.  I increased it to 20M.  The relevant setting for me was `proxy-body-size: 20m` in kubernetes nginx ingress.  The nginx option is `client_max_body_size`.

You probably need to check your HTTP server (all layers if there are different proxies) and find the config option you need.  Luckily there was enough info searching for jupyter+server+413 Request Entity Too Large.
