### ISSUE TITLE
Opening a PDF results in "Error! (file) is not UTF-8 encoded"

### ISSUE THREAD

**Issue by rcthomas** [jupyterhub/jupyterhub#1572]
I have a PDF file that I can't open via JupyterHub.  I click on the PDF but I get a text file tab that says

    Error! /path/to/file.pdf is not UTF-8 encoded
    Saving disabled.
    See console for more details.

The console log says we got a 400 bad format error.  I am not sure if all PDFs do this.  I haven't seen one work yet.  Now I don't personally do this a lot, I am "asking for a friend" (one of my users), but I understand that one should be able to view PDFs in JupyterHub this way.  We're running JupyterHub 0.8.0.rc1; I might upgrade that it it sounds like it could matter but I haven't seen any related issues.

**Comment by minrk** [comment]
What's the version of the notebook package (`pip list | grep notebook` in the user env)?

**Comment by draker42** [comment]
I just discovered the same problem. I have a recent install of jupyterhub on an updated Ubuntu 16.04 LTS.
pip3 list | grep notebook
notebook (5.2.2)
I was testing with a simple python3 notebook and "jupyter nbconvert <notebook> --to pdf".
The resulting PDF is fine; I've downloaded it with scp and viewed it locally. But if I click on it in the jupyterhub tree, I get what rcthomas described. 
I notice that jupyterhub is trying to EDIT the pdf. The URL is:
https://myhostname/user/myuser/edit/notebook-test.pdf
If I manually change the URL from /edit/ to /view/, the PDF opens and is viewed fine. If I select the PDF checkbox, then click 'view', it is fine. If I select the checkbox next to another file, such as a PNG, then click the 'edit' button, I can replicate the above error message. 
So the problem is that jupyterhub is not recognizing .pdf files as 'view-only'. I played around a bit with file extensions. Jupyterhub is not using /etc/magic?
Thanks for help.

**Comment by rcthomas** [comment]
Thanks.  The notebook is version 5.2.1:

    conda list | grep notebook
    notebook                  5.2.1            py36h690a4eb_0    defaults

**Comment by rcthomas** [comment]
Thanks for the tip @draker42.  I tried changing the URL from `/edit/` to `/view/` but that did not work in my case.  Clicking the checkbox and then clicking the view button seems to work.  Note that the resulting URL there has `/files/` in it, and if I manually change `/edit/` to `/files/` then it does work.

**Comment by willingc** [comment]
@rcthomas Which version of nbconvert is installed?

**Comment by rcthomas** [comment]
Hi @willingc!  That's:

    conda list | grep nbconvert
    nbconvert                 5.1.1                    py36_0    defaults

**Comment by willingc** [comment]
Thanks @rcthomas.

@minrk I tried loading a repo with PDFs on mybinder.org and found two different messages (including one with the UTF-8) so we can replicate though I have not isolated cause yet:

<img width="1238" alt="screenshot 2017-12-11 11 40 05" src="https://user-images.githubusercontent.com/2680980/33846650-552e5d1c-de6d-11e7-8801-593b688d9229.png">
<img width="1200" alt="screenshot 2017-12-11 11 40 21" src="https://user-images.githubusercontent.com/2680980/33846651-5552051e-de6d-11e7-9736-bb777de0e34c.png">

**Comment by willingc** [comment]
Needs testing to see if this is still an issue.

**Comment by markm42** [comment]
I am the 'user' mentioned in the first post, and I can confirm I no longer have this problem with pdf files.

**Comment by minrk** [comment]
Thanks!

**Comment by rjinka** [comment]
> I am the 'user' mentioned in the first post, and I can confirm I no longer have this problem with pdf files.

@markm42 Hello, how did this issue got resolved? I too have same issue, Appreciate any help on this.

**Comment by markm42** [comment]
> > I am the 'user' mentioned in the first post, and I can confirm I no longer have this problem with pdf files.
> 
> @markm42 Hello, how did this issue got resolved? I too have same issue, Appreciate any help on this.

@rjinka, do you get the same error message as above? I haven't actively done anything that resolved this problem (as far as I remember), I think it was just a Jupyter update that vanished it.
However, ironically, I haven't been able to open pdf files again recently; I see a blank gray screen though, no error message.

**Comment by rjinka** [comment]
> > > I am the 'user' mentioned in the first post, and I can confirm I no longer have this problem with pdf files.
> > 
> > 
> > @markm42 Hello, how did this issue got resolved? I too have same issue, Appreciate any help on this.
> 
> @rjinka, do you get the same error message as above? I haven't actively done anything that resolved this problem (as far as I remember), I think it was just a Jupyter update that vanished it.
> However, ironically, I haven't been able to open pdf files again recently; I see a blank gray screen though, no error message.

@markm42 Thanks for the update and I will let you know if i find any solutions to this.

**Comment by Neyt** [comment]
Hi! so what was the solution? I just reinstalled jupyter a couple of weeks ago. found the same problem.

**Comment by denson** [comment]
> Hi! so what was the solution? I just reinstalled jupyter a couple of weeks ago. found the same problem.

I think the solution is that often the file is really written correctly, you just can not view it in Jupyter. I had the same problem but I was able to load the saved parquet file back in perfectly in the same notebook.

**Comment by Olyapyramid** [comment]
I have the same problem with xlsx file) still can't figure what to do?

**Comment by will-austin** [comment]
I'm still having the same issue.

**Comment by Elidor00** [comment]
I have the same problem also with the ".pth" files to save the PyTorch models.
Notebook version: 6.0.3

**Comment by SUNDAR2397** [comment]
how to fix it please help.

**Comment by Arjun-Deshwal** [comment]
I am getting these errors when I am trying to dump my model using `joblib.dump()`. It created a 38 mb file and when I opened it, There was written the same error described above. Is anyone out there. Help
