### ISSUE TITLE
Jupyter cannot find Three.Js files - URL redirection not working *updated*

### ISSUE THREAD

**Issue by mzilinski** [jupyterhub/jupyterhub#1574]
Hello Jupyter Team. 

System configuration:
Debian 8 with SageMath packages installed. 
Manually started JupyterNotebook does not suffer from the following problem.
Jupyterhub is up and running. 
Sage and Python works quite fine but

**What happened: 
trying to create a 3D graphic with threejs as renderer, nothing shows up. 

Example Code: 
```
x, y = var('x y')
W = plot3d(sin(pi*((x)^2+(y)^2))/2,(x,-1,1),(y,-1,1), frame=False, color='purple', opacity=0.8)
S = sphere((0,0,0),size=0.3, color='red', aspect_ratio=[1,1,1])
show(W + S, figsize=8,viewer='threejs')
```

Analyzing the webpage, it shows, up that it tries to load: 
```
https://<myurl>/hub/nbextensions/threejs/three.min.js 
https://<myurl>/hub/nbextensions/threejs/examples/js/controls/OrbitControls.js
```
I managed to locate the files at a different location (in fact they are available):
```
https://<myurl>/user/<user>/nbextensions/threejs/three.min.js 
https://<myurl>/user/<user>/nbextensions/threejs/examples/js/controls/OrbitControls.js
```

**Share what version of JupyterHub you are using**
I'm using the current version of pip3. It should be 0.8.1.

`jupyter troubleshoot` reports no errors.

Syslog
```
jupyterhub[26980]: Message: '404 GET /hub/nbextensions/threejs/examples/js/controls/OrbitControls.js
```

**Update**
The output is generated by the file:
`/usr/lib/python2.7/dist-packages/sage/repl/rich_output/backend_ipython.py`
At the end of the file there is following code:
```
            sage: from sage.repl.rich_output.backend_ipython import BackendIPythonNotebook
            sage: backend = BackendIPythonNotebook()
            sage: backend.threejs_offline_scripts()
            '...<script src="/nbextensions/threejs/three.min...</script>...'
        """
        return """
<script src="/nbextensions/threejs/three.min.js"></script>
<script src="/nbextensions/threejs/examples/js/controls/OrbitControls.js"></script>
        """
```
Removing the leading / leads to the URL:
`https://<url>/user/<user>/notebooks/nbextensions/threejs/three.min.js`
Which will result in 404 error again. 

Help is really appreciated. Thank you very much for your work. 

Best regards
M. Zilinski

**Comment by minrk** [comment]
This is likely a bug somewhere requesting `/nbextensions/threejs/...` Absolute URLs shouldn't be used to load nbextensions. If it's loading with require, omit the leading slash: `nbextensions/...` instead of `/nbextensions/...`.

**Comment by mzilinski** [comment]
Thanks for the comment. I dug a little deeper and updated the issue. I still don't have an idea on how to fix.

**Comment by mzilinski** [comment]
There is a possible workaround to this issue. While serving with Apache 2 (Nginx will work similarly).

Modification to Apache 2 config e.g. `sage.conf`
```
 DocumentRoot /var/www/html/sage
                SSLProxyEngine on
                ServerName <PublicWebServerDNSName>
                ProxyPass /hub/nbextensions !
                ProxyPass / http://<LocalSageServerIP>:9876/
                ProxyPassReverse / http://<LocalSageServerIP>:9876/

                Header edit Origin "<PublicWebServerDNSName>" <LocalSageServerIP>:9876
                RequestHeader edit Origin "<PublicWebServerDNSName>" <LocalSageServerIP>:9876

                Header edit Referer "<PublicWebServerDNSName>" <LocalSageServerIP>:9876
                RequestHeader edit Referer "<PublicWebServerDNSName>" <LocalSageServerIP>:9876
                <Location ~ "/(user/[^/]*)/(api/kernels/[^/]+/channels|terminals/websocket)/?">
                    ProxyPass ws://<LocalSageServerIP>:9876
                    ProxyPassReverse ws://<LocalSageServerIP>:9876
                </Location>

```
Modification to `/var/www/html/sage`
Create folder` /hub/nbextensions` serve missing files.

It's not beautiful, but easy to do and it will help until there is a better fix.

**Comment by micahscopes** [comment]
I'm also experiencing this issue :cry:

**Comment by bryangingechen** [comment]
I'm running into this issue as well except that a manually started `jupyter notebook` also has 404 errors as well. 

My configuration is different: I'm running the anaconda distribution of jupyter on macOS and I installed the SageMath kernel into it manually [following these instructions](https://stackoverflow.com/questions/39296020/how-to-install-sagemath-kernel-in-jupyter/41595015#41595015).

**Comment by willingc** [comment]
I'm closing this and marking as reference.

**Comment by saraedum** [comment]
https://trac.sagemath.org/ticket/26434 is trying to fix this issue.
