### ISSUE TITLE
LocalAuthenticator question

### ISSUE THREAD

**Issue by tk3369** [jupyterhub/jupyterhub#1579]
I hope I'm posting to the right place.  Can someone enlighten me please?  I don't fully understand the statement below.  If the purpose is to make it easy to add new users and it uses the `adduser` command (which add users to the system's UNIX users) then why isn't it recommended when the users are mapped directly to the system's UNIX users?  

**From the doc:**
Adding a user to the Hub that doesn't already exist on the system will result in the Hub creating that user via the system adduser command line tool. This option is typically used on hosted deployments of JupyterHub, to avoid the need to manually create all your users before launching the service. **_This approach is not recommended when running JupyterHub in situations where JupyterHub users map directly onto the system's UNIX users._**

**Comment by shalan7** [comment]
This has been written because of the same issue I think as is mentioned here

[Issue with local users](https://github.com/jupyterhub/ldapauthenticator#configuration-note-on-local-user-creation
)

**Comment by willingc** [comment]
ping @minrk

**Comment by minrk** [comment]
Tracked it down to 491ee38a3768ad0220a3600bd2696d85486d61d6, which introduced confusion.

The original text was

> It is not recommended when running JupyterHub on 'real' machines with regular users.

which reminds me what I wanted to communicate.

The point to get across is mainly: if it's a real machine with existing user accounts, granting jupyterhub the ability to create arbitrary new accounts is probably not desirable. Typically, create_system_users is only used on machines that are wholly dedicated to jupyterhub.

@willingc do you want to take a stab at writing something that communicates that clearly? I haven't had much success.

**Comment by willingc** [comment]
Will do @minrk.

**Comment by manics** [comment]
I'm closing this as it's quite old and the docs have most likely been updated at some point.
