### ISSUE TITLE
Specify Kubernetes volume claims in Jupyterhub spawner

### ISSUE THREAD

**Issue by jlewi** [jupyterhub/jupyterhub#1580]
I'm running Jupyterhub on Kubernetes via [google/kubeflow](http://github.com/kubeflow).

In the UI to spawn my notebook server, I'd like an option to specify K8s volumes that should be attached to my notebook. This would allow me to attach volumes (e.g. NFS volumes) containing data that I want to work with.

/cc @foxish @yuvipanda (Is this the right place for this issue?)

**Comment by yuvipanda** [comment]
Hey @jlewi!

For KubeFlow, the form that lets you specify parameters is configured in https://github.com/google/kubeflow/blob/master/components/jupyterhub/manifests/config.yaml#L23. You can add a volume claim setup there and connect that to the `volumes` and `volume_mounts` traitlets (similar to how https://github.com/google/kubeflow/blob/master/components/jupyterhub/manifests/config.yaml#L53 wires up image).

http://github.com/jupyterhub/kubespawner is usually a better place for these questions!

Welcome to the community! :)

**Comment by jlewi** [comment]
Thanks. Opened up some issues in the Kubeflow repo.
