### ISSUE TITLE
Jupyterhub shared service error

### ISSUE THREAD

**Issue by prabhu1984** [jupyterhub/jupyterhub#1582]
Hi,

As per https://github.com/jupyterhub/jupyterhub/blob/master/examples/service-notebook/managed/jupyterhub_config.py instructions, I tried to enable shared service for a group of 3 members. 

But, when I try to open `http://hostname:8444/services/bdpe-users-notebooks/`, I'm getting the below 404 error. Provided log below.

Please let me know how to fix the issue.

Error Screenshot:

![Error Screenshot](https://github.com/prabhu1984/sparkmagic/blob/master/examples/images/Jupyterhub%20Shared%20Services.png?raw=true)

Jupyterhub Log: 
```
[I 2017-12-10 17:03:28.673 SingleUserNotebookApp notebookapp:1128] The Jupyter Notebook is running at: http://0.0.0.0:8444/services/bdpe-users-notebooks/
[I 2017-12-10 17:03:28.673 SingleUserNotebookApp notebookapp:1129] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2017-12-10 17:05:06.771 SingleUserNotebookApp log:122] 302 GET /services/bdpe-users-notebooks/ → /services/bdpe-users-notebooks/tree (@10.196.177.146) 0.55ms
[W 2017-12-10 17:05:09.082 SingleUserNotebookApp log:122] 404 GET /hub/logo (@10.196.177.146) 0.82ms
[E 2017-12-10 17:06:28.757 JupyterHub app:1567] Cannot connect to managed service bdpe-users-notebooks at https://0.0.0.0:8444. Is it running?
[I 2017-12-10 17:06:28.757 JupyterHub app:1544]
```

Thanks!

**Comment by sigurdurb** [comment]
What is your authentication method?
Jupyterhub should proxy the services on startup, do you see that in your logs?

**Comment by prabhu1984** [comment]
Hi @sigurdurb,

Thanks for checking it out. Please find the details below and help me to fix the issue.

I'm using default spawner and default authenticator. I'm starting Jupyterhub on 8443 port using CA cert, and configuring shared services to start on 8444 port using below configuration.

jupyterhub_config.py
```
#----------- Adding Shared Services

#-- Team
c.Authenticator.whitelist = [
    'prabhu',
    'prabhu'
]

#-- Team Shared Group
c.JupyterHub.load_groups = {
    'team': [
        'prabhu',
        'praveen'
    ]
}

service_name = 'team-users-notebooks'
service_port = 8444
group_name = 'users'

#-- Jupyterhub Services
c.JupyterHub.services = [
    {
        'name': service_name,
        'url': 'https://jupyterhub.myhost.com:{}'.format(service_port),
        'command': [
            'jupyterhub-singleuser',
            '--group=users',
        ],
    }
]
```

Log File:
```
[19:44]:[root@jupyterhub.myhost.com:jupyterhub]# cat logs/jupyterhub.jupyterhub.myhost.com.log 
....
[I 2017-12-16 19:44:10.258 JupyterHub app:1530] Hub API listening on http://127.0.0.1:8081/hub/
[I 2017-12-16 19:44:10.258 JupyterHub proxy:458] Starting proxy @ https://0.0.0.0:8443/
[I 2017-12-16 19:44:10.640 JupyterHub app:1546] Starting managed service team-users-notebooks at https://jupyterhub.myhost.com:8444
[I 2017-12-16 19:44:10.640 JupyterHub service:266] Starting service 'team-users-notebooks': ['jupyterhub-singleuser', '--group=users']
[I 2017-12-16 19:44:10.645 JupyterHub service:109] Spawning jupyterhub-singleuser --group=users
[D 2017-12-16 19:44:10.649 JupyterHub spawner:727] Polling subprocess every 30s
[I 2017-12-16 19:44:11.841 SingleUserNotebookApp singleuser:365] Starting jupyterhub-singleuser server version 0.8.1
[I 2017-12-16 19:44:11.846 SingleUserNotebookApp notebookapp:1128] Serving notebooks from local directory: /opt/jupyterhub
[I 2017-12-16 19:44:11.846 SingleUserNotebookApp notebookapp:1128] 0 active kernels 
[I 2017-12-16 19:44:11.846 SingleUserNotebookApp notebookapp:1128] The Jupyter Notebook is running at: http://jupyterhub.myhost.com:8444/services/team-users-notebooks/
[I 2017-12-16 19:44:11.846 SingleUserNotebookApp notebookapp:1129] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[19:44]:[root@jupyterhub.myhost.com:jupyterhub]# 
```

When I hit `http://jupyterhub.myhost.com:8444/` on browser, I'm getting below error.
```
404 : Not Found
You are requesting a page that does not exist!
```

Let me know what I'm doing wrong to fix the issue. Thanks!

Prabhu

**Comment by sigurdurb** [comment]
Yes, instead of 
```
 'url': 'https://jupyterhub.myhost.com:{}'.format(service_port),
```
try 
```
'url': 'http://127.0.0.1:{}'.format(service_port),
```

Also your '--group=users' should be '--group=team' if you want it to match the group 'team' in the c.JupyterHub.load_groups variable you have.

**Comment by sigurdurb** [comment]
@prabhu1984 
You also need to add where you are running the service from into the dict in c.Jupyterhub.Services
'user': '{your–user}',
'cwd': '/home/{your-user}'

replace {your-user} with your system username

**Comment by sigurdurb** [comment]
Also make sure the .jupyter/nbgrader_config.py is executable
You can do that by running this while being in that users home directory.
```
chmod 700  .jupyter/nbgrader_config.py
```

**Comment by prabhu1984** [comment]
Thanks @sigurdurb for the details. Let me try it out and update you.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻

**Comment by limbuu** [comment]
> @prabhu1984
> You also need to add where you are running the service from into the dict in c.Jupyterhub.Services
> 'user': '{your–user}',
> 'cwd': '/home/{your-user}'
> 
> replace {your-user} with your system username

when i used this i got user not found as :

File "/opt/conda/lib/python3.6/site-packages/jupyterhub/spawner.py", line 1069, in user_env
        home = pwd.getpwnam(self.user.name).pw_dir
    KeyError: 'getpwnam(): name not found: test-user'

**Comment by sukhjitsehra** [comment]
I also struggled with the same problem while installing the jupyter and nbgrader packages using conda. But, I solved this by installing the jupyter and nbgrader using following as discussed at https://jupyterhub.readthedocs.io/en/stable/installation-guide-hard.html:
 
> sudo /opt/jupyterhub/bin/python3 -m pip install jupyter
> sudo /opt/jupyterhub/bin/python3 -m pip install nbgrader 
> sudo /opt/jupyterhub/bin/python3 -mpip install jupyter_contrib_nbextensions

That solves the issue for me. 

Restart the jupyterhub service and reload the pages
