### ISSUE TITLE
config c.LocalProcessSpawner.mem_limit Issue

### ISSUE THREAD

**Issue by prabhu1984** [jupyterhub/jupyterhub#1584]
Hi,

As per http://jupyterhub.readthedocs.io/en/latest/api/spawner.html instructions, I've set config c.LocalProcessSpawner.mem_limit to 15GB as below on jupyterhub_config.py.

```
c.LocalProcessSpawner.mem_limit = 15728640
c.LocalProcessSpawner.mem_guarantee = 1048576
c.LocalProcessSpawner.cpu_limit = 2.0
c.LocalProcessSpawner.cpu_guarantee = 0.5
```

But, when I tried to test by loading some test file to cross the 15gb boundary, process didn't fail. Actually, I am able to load some 48GB data into memory and stopped the test. 

![Image](https://github.com/prabhu1984/sparkmagic/blob/master/examples/images/Testing_MEM_CPU_Limit.png?raw=true)

Please let me know, what I'm doing wrong. Why is memory limit not applied?

Thanks!

**Comment by minrk** [comment]
LocalProcessSpawner doesn't implement mem_limit because it needs to be able to create cgroups and that isn't implemented. You will have to use a Spawner that supports these, such as DockerSpawner or KubeSpawner. For non-containerized servers, I believe SystemdSpawner implements mem_limit.

**Comment by willingc** [comment]
Thanks @minrk for the explanation. 

Documentation recommendation: Let's highlight (bold) the sentence in the docs re: spawner must support... http://jupyterhub.readthedocs.io/en/latest/reference/spawners.html#spawners-resource-limits-and-guarantees-optional

**Comment by Siecje** [comment]
In case this might help someone I've implemented a crude limit with this code. https://github.com/jupyterhub/sudospawner/pull/47

**Comment by ixjlyons** [comment]
In addition to @willingc's comment above, I think the spawner docstrings should mention whether or not these features are supported. For example, the [`LocalProcessSpawner` documentation](https://jupyterhub.readthedocs.io/en/latest/api/spawner.html#localprocessspawner) says "This needs to be supported by your spawner for it to work." This seems to be because it doesn't override the `mem_limit` trait so the generic string comes from the base `Spawner` class. You'd have to dig into the source code to determine whether or no the `mem_limit` option is implemented. If overriding a trait attribute just to modify the documentation is an antipattern, maybe it could just be mentioned in the top-level portion of the docstring.

**Comment by prabhu1984** [comment]
Hi @minrk/@willingc, 

Thanks for checking it out.

I didn't change anything on config other than mem_limit option and so, I'm using the default spawner. 

Do you mean that default spawner doesn't support memlimit/cpulimit? But, the [document](https://jupyterhub.readthedocs.io/en/latest/api/spawner.html#localprocessspawner) says LocalProcessSpawner supports mem_limit.

```
config c.LocalProcessSpawner.mem_limit = ByteSpecification(None)
Maximum number of bytes a single-user notebook server is allowed to use.
Allows the following suffixes:
K -> Kilobytes
M -> Megabytes
G -> Gigabytes
T -> Terabytes
If the single user server tries to allocate more memory than this, it will fail. There is no guarantee that the single-user notebook server will be able to allocate this much memory - only that it can not allocate more than this.
This needs to be supported by your spawner for it to work.
```

My apologies, if I understood incorrectly. Is there any way I can enforce mem/cpu limit using default spawner?

Thanks
Prabhu

**Comment by minrk** [comment]
@prabhu1984 no, there is no way to enforce mem/cpu limit with the default spawner. It does not support these limits. You must use something like systemdspawner to get these limits.
