### ISSUE TITLE
Starting the JupyterHub on the Linux server

### ISSUE THREAD

**Issue by vpvijay87** [jupyterhub/jupyterhub#1591]
Hi,

I have installed JupterHub on the Linux 6, able to start the services as sudo jupyterhub, however when ever I close the SSH session, JupyterHub also gets terminated.
Is there any command to start/stop  jupyterhub on the linux machine.

**Comment by whositwhatnow** [comment]
I used this procedure to run jupyterhub as a service.  I am on CentOS7 and this worked perfectly.
https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service
