### ISSUE TITLE
PAM Authentication failed

### ISSUE THREAD

**Issue by kevkid** [jupyterhub/jupyterhub#1592]
**How to reproduce the issue**
Install jupyterhub as shown here:
https://jupyterhub.readthedocs.io/en/latest/quickstart.html#prerequisites
start jupyterhub:
`$jupyterhub`
login with user running the jupyterhub instance
log out
log back in with another user on the system

**What you expected to happen**
I expect any user that has an account on the system to be able to log in to jupyterhub
**What actually happens**
I can log in with the user that is running the instance of jupyterhub
When trying to login with another user that I created via `adduser` from terminal
I get the following:
`[W 2017-12-19 22:18:50.419 JupyterHub auth:563] PAM Authentication failed (test@::ffff:127.0.0.1): [PAM Error 7] Authentication failure
[W 2017-12-19 22:18:50.419 JupyterHub base:351] Failed login for test
[I 2017-12-19 22:18:50.447 JupyterHub log:122] 200 POST /hub/login?next= (@::ffff:127.0.0.1) 2543.74ms
`
**Share what version of JupyterHub you are using**
0.8.1
Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.

```

Insert jupyter troubleshoot output here
jupyterhub@jupyterhub-VirtualBox:~$ jupyter troubleshoot
$PATH:
	/usr/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin

sys.path:
	/usr/lib/python3/dist-packages
	/usr/bin
	/usr/lib/python36.zip
	/usr/lib/python3.6
	/usr/lib/python3.6/lib-dynload
	/home/jupyterhub/.local/lib/python3.6/site-packages
	/usr/local/lib/python3.6/dist-packages
	/usr/lib/python3.6/dist-packages

sys.executable:
	/usr/bin/python3

sys.version:
	3.6.3 (default, Oct  3 2017, 21:45:48) 
	[GCC 7.2.0]

platform.platform():
	Linux-4.13.0-16-generic-x86_64-with-Ubuntu-17.10-artful

which -a jupyter:
	/usr/bin/jupyter
	/usr/bin/jupyter


```

**Comment by kevkid** [comment]
Apparently one can start it as root and it will allow all of the users on the system to login. I reinstalled everything as root and it worked.

[Source](https://github.com/jupyterhub/jupyterhub/issues/993)

**Comment by willingc** [comment]
@kevkid Closing since you seem to have resolved the original issue.
