### ISSUE TITLE
ModuleNotFoundError: No module named 'pysqlite2'

### ISSUE THREAD

**Issue by ormskirk77** [jupyterhub/jupyterhub#1594]
Dear All, 

I'm on a mac using OS 10. I have downloaded Miniconda and installed it to the default location. I then installed jupyter, but I get the following error when I run `jupyter notebook` :

> ModuleNotFoundError: No module named 'pysqlite2'

Running:
`pip install pysqlite`

Gives the error:

> pysqlite is not supported on Python 3. When using Python 3, use the sqlite3 module from the standard library. 

`which python`
> /Users/timfernandez/miniconda3/bin/python

`python --version`
> Python 3.6.3 :: Anaconda, Inc.

`which sqlite3`
> /Users/timfernandez/miniconda3/bin/sqlite3 

`sqlite3 --version`
>3.20.1 2017-08-24 16:21:36

I'm not sure where to go from here. Any help would be much appreciated.

**Comment by willingc** [comment]
Hi @ormskirk77,

Your miniconda installation looks correct to me. How were you installing Jupyter Notebook? I recommend:
```
conda install jupyter
```

Here's an output from macOS 10.13:

```
carol@cw-pro ~> which python
/Users/carol/miniconda3/bin/python
carol@cw-pro ~> clear
carol@cw-pro ~> which python
/Users/carol/miniconda3/bin/python
carol@cw-pro ~> python --version
Python 3.6.3 :: Anaconda, Inc.
carol@cw-pro ~> which sqlite3
/Users/carol/miniconda3/bin/sqlite3
carol@cw-pro ~> sqlite3 --version
3.20.1 2017-08-24 16:21:36 8d3a7ea6c5690d6b7c3767558f4f01b511c55463e3f9e64506801fe9b74dce34
carol@cw-pro ~> conda install jupyter
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /Users/carol/miniconda3:

The following NEW packages will be INSTALLED:

    appnope:            0.1.0-py36_0          conda-forge
    bleach:             2.0.0-py36_0          conda-forge
    decorator:          4.1.2-py36_0          conda-forge
    entrypoints:        0.2.3-py36_1          conda-forge
    html5lib:           1.0.1-py_0            conda-forge
    icu:                58.2-0                conda-forge
    ipykernel:          4.7.0-py36_0          conda-forge
    ipython:            6.2.1-py36_0          conda-forge
    ipython_genutils:   0.2.0-py36_0          conda-forge
    ipywidgets:         7.0.5-py36_0          conda-forge
    jedi:               0.10.2-py36_0         conda-forge
    jinja2:             2.10-py36_0           conda-forge
    jpeg:               9b-2                  conda-forge
    jsonschema:         2.6.0-py36_0          conda-forge
    jupyter:            1.0.0-py36_0          conda-forge
    jupyter_client:     5.2.0-py36_0          conda-forge
    jupyter_console:    5.2.0-py36_0          conda-forge
    jupyter_core:       4.4.0-py_0            conda-forge
    libpng:             1.6.34-0              conda-forge
    libsodium:          1.0.15-1              conda-forge
    markupsafe:         1.0-py36_0            conda-forge
    mistune:            0.8.3-py_0            conda-forge
    nbconvert:          5.3.1-py_1            conda-forge
    nbformat:           4.4.0-py36_0          conda-forge
    notebook:           5.2.2-py36_1          conda-forge
    pandoc:             2.0.5-0               conda-forge
    pandocfilters:      1.4.1-py36_0          conda-forge
    pexpect:            4.3.1-py36_0          conda-forge
    pickleshare:        0.7.4-py36_0          conda-forge
    prompt_toolkit:     1.0.15-py36_0         conda-forge
    ptyprocess:         0.5.2-py36_0          conda-forge
    pygments:           2.2.0-py36_0          conda-forge
    pyqt:               5.6.0-py36_4          conda-forge
    python-dateutil:    2.6.1-py36_0          conda-forge
    pyzmq:              16.0.2-py36_2         conda-forge
    qt:                 5.6.2-h9e3eb04_4      conda-forge
    qtconsole:          4.3.1-py36_0          conda-forge
    simplegeneric:      0.8.1-py36_0          conda-forge
    sip:                4.18-py36_1           conda-forge
    terminado:          0.8.1-py36_0          conda-forge
    testpath:           0.3.1-py36_0          conda-forge
    tornado:            4.5.2-py36_0          conda-forge
    traitlets:          4.3.2-py36_0          conda-forge
    wcwidth:            0.1.7-py36_0          conda-forge
    webencodings:       0.5-py36_0            conda-forge
    widgetsnbextension: 3.0.8-py36_0          conda-forge
    zeromq:             4.2.1-1               conda-forge

The following packages will be SUPERSEDED by a higher-priority channel:

    conda:              4.3.30-py36h173c244_0             --> 4.3.29-py36_0 conda-forge
    conda-env:          2.6.0-h36134e3_0                  --> 2.6.0-0       conda-forge

Proceed ([y]/n)? y

conda-env-2.6. 100% |################################| Time: 0:00:00 711.38 kB/s
icu-58.2-0.tar 100% |################################| Time: 0:00:06   3.79 MB/s
jpeg-9b-2.tar. 100% |################################| Time: 0:00:00  26.03 MB/s
libsodium-1.0. 100% |################################| Time: 0:00:00   2.78 MB/s
pandoc-2.0.5-0 100% |################################| Time: 0:00:06   3.56 MB/s
libpng-1.6.34- 100% |################################| Time: 0:00:00   3.45 MB/s
zeromq-4.2.1-1 100% |################################| Time: 0:00:00   4.84 MB/s
qt-5.6.2-h9e3e 100% |################################| Time: 0:00:10   6.78 MB/s
appnope-0.1.0- 100% |################################| Time: 0:00:00   5.69 MB/s
entrypoints-0. 100% |################################| Time: 0:00:00   7.31 MB/s
jedi-0.10.2-py 100% |################################| Time: 0:00:00   2.89 MB/s
jsonschema-2.6 100% |################################| Time: 0:00:00  15.57 MB/s
mistune-0.8.3- 100% |################################| Time: 0:00:00  11.81 MB/s
pandocfilters- 100% |################################| Time: 0:00:00   8.26 MB/s
pickleshare-0. 100% |################################| Time: 0:00:00   6.03 MB/s
ptyprocess-0.5 100% |################################| Time: 0:00:00   7.04 MB/s
pyzmq-16.0.2-p 100% |################################| Time: 0:00:00   4.48 MB/s
simplegeneric- 100% |################################| Time: 0:00:00   6.49 MB/s
sip-4.18-py36_ 100% |################################| Time: 0:00:00   3.02 MB/s
testpath-0.3.1 100% |################################| Time: 0:00:00  24.86 MB/s
wcwidth-0.1.7- 100% |################################| Time: 0:00:00   8.06 MB/s
webencodings-0 100% |################################| Time: 0:00:00  10.15 MB/s
html5lib-1.0.1 100% |################################| Time: 0:00:00  16.60 MB/s
pexpect-4.3.1- 100% |################################| Time: 0:00:00  21.59 MB/s
pyqt-5.6.0-py3 100% |################################| Time: 0:00:00   5.89 MB/s
terminado-0.8. 100% |################################| Time: 0:00:00   8.09 MB/s
bleach-2.0.0-p 100% |################################| Time: 0:00:00  16.87 MB/s
jupyter_core-4 100% |################################| Time: 0:00:00  15.80 MB/s
pygments-2.2.0 100% |################################| Time: 0:00:00   4.78 MB/s
jupyter_client 100% |################################| Time: 0:00:00  23.48 MB/s
nbformat-4.4.0 100% |################################| Time: 0:00:00  24.61 MB/s
prompt_toolkit 100% |################################| Time: 0:00:00  26.44 MB/s
ipython-6.2.1- 100% |################################| Time: 0:00:00   3.03 MB/s
nbconvert-5.3. 100% |################################| Time: 0:00:00   3.38 MB/s
ipykernel-4.7. 100% |################################| Time: 0:00:00   1.67 MB/s
conda-4.3.29-p 100% |################################| Time: 0:00:00   1.50 MB/s
jupyter_consol 100% |################################| Time: 0:00:00  14.29 MB/s
notebook-5.2.2 100% |################################| Time: 0:00:02   2.63 MB/s
qtconsole-4.3. 100% |################################| Time: 0:00:00  25.36 MB/s
widgetsnbexten 100% |################################| Time: 0:00:00   3.89 MB/s
ipywidgets-7.0 100% |################################| Time: 0:00:00  11.43 MB/s
jupyter-1.0.0- 100% |################################| Time: 0:00:00   2.25 MB/s
carol@cw-pro ~> jupyter notebook --version
5.2.2
carol@cw-pro ~>
```

Your results should be similar.

**Comment by ormskirk77** [comment]
Thank you willingc for replying on Boxing day (Merry Christmas!). 

At the end of my .bash_profile is:

> added by Miniconda3 installer
export PATH="/Users/timfernandez/miniconda3/bin:$PATH"

If I : `conda install jupyter` I get: 

> **Tims-MacBook-Pro:~ timfernandez$ conda install jupyter
Solving environment: done
All requested packages already installed.** 

I really can't see where I'm going wrong. Everything seems to point to the Miniconda installation but if I `jupyter notebook` the full error is:

> Tims-MacBook-Pro:~ timfernandez$ jupyter notebook
Traceback (most recent call last):
  File "/Users/timfernandez/miniconda3/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 10, in <module>
    import sqlite3
  File "/Users/timfernandez/miniconda3/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/Users/timfernandez/miniconda3/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: dlopen(/Users/timfernandez/miniconda3/lib/python3.6/lib-dynload/_sqlite3.cpython-36m-darwin.so, 2): Symbol not found: _sqlite3_enable_load_extension
  Referenced from: /Users/timfernandez/miniconda3/lib/python3.6/lib-dynload/_sqlite3.cpython-36m-darwin.so
  Expected in: /usr/lib/libsqlite3.dylib
 in /Users/timfernandez/miniconda3/lib/python3.6/lib-dynload/_sqlite3.cpython-36m-darwin.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/timfernandez/miniconda3/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/Users/timfernandez/miniconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 81, in <module>
    from .services.sessions.sessionmanager import SessionManager
  File "/Users/timfernandez/miniconda3/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 13, in <module>
    from pysqlite2 import dbapi2 as sqlite3
ModuleNotFoundError: No module named 'pysqlite2'

Is this a true bug???
Or am I missing something?

**Comment by minrk** [comment]
pysqlite is only used as a fallback when stdlib sqlite is unavailable, which normally only happens when Python has itself not been built properly. Miniconda Python includes sqlite, so the fact that it cannot load indicates that something is wrong with either the install or the environment, causing it to try to load the wrong sqlite, or perhaps that sqlite has been broken. If this is a fresh install of miniconda, it suggests to me that something in the environment is causing it to load unexpected libraries.

Do you perhaps have DYLD_LIBRARY_PATH defined? Or any other environment variables with `PATH` in them (other than PATH itself)?

**Comment by ormskirk77** [comment]
Thanks minrk, 

$DYLD_LIBRARY_PATH is set to:
`Tims-MacBook-Pro:~ timfernandez$ echo $DYLD_LIBRARY_PATH
/usr/lib/:
`

$PATH is set to:
 ```
Tims-MacBook-Pro:~ timfernandez$ echo $PATH
/Users/timfernandez/anaconda3/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/git/bin
```
$LD_LIBRARY_PATH is not set, and I don't know of any more PATH type environment variables?? sqlite is listed as a package in Anaconda Navigator as installed (v 3.2).

Since there was no response to the question I ended up removing both Anaconda and MiniConda and installing jupyter using the system pip3, and python3. This worked! However, I'd like to use the Anaconda version rather than the mac system version. Any other suggestions? Or should I post this on to an Anaconda message board?

**Comment by minrk** [comment]
DYLD_LIBRARY_PATH is the cause, then. You can fix this with `unset DYLD_LIBRARY_PATH`.

DYLD_LIBRARY_PATH should approximately never be set, and if set, only to *non-default* paths, such as `~/work/mystuff/lib`, and only for temporary working environments (e.g. never in ~/.bashrc). The cause is that you have told the system that any library found in `/usr/lib` should be loaded (in this case sqlite) in preference to other locations, e.g. `...conda/lib/`, which is where the sqlite that Python requires is located.

**Comment by ormskirk77** [comment]
YES!  That was it. Many thanks minrk. Thank you for the explanation as well.

**Comment by gavin971** [comment]
@minrk  Do you have better permanent solution to solve the problem? Now I just can open and browse  ipynb files, but the temporary solution “unset DYLD_LIBRARY_PATH” causes many packages cannot be   loaded in the envs.

**Comment by minrk** [comment]
@gavin971 DYLD_LIBRARY_PATH is a major source of problems because it affects all library loading, rather than just the libraries that need it. In general, the long-term fix is to set the RPATH in the libraries as you compile them, rather than ever rely on DYLD_LIBRARY_PATH. If you are stuck with DYLD_LIBRARY_PATH, the solution is to make sure that you *never* point DYLD_LIBRARY_PATH to a location that has libraries that you don't want to load. The only safe way to do this is to install libraries that are to be loaded with it to their own paths. That means that, among other things, DYLD_LIBRARY_PATH should almost never point to a conda env.

But in general, DYLD_LIBRARY_PATH is itself only ever a temporary solution for libraries that have not been correctly compiled with RPATH (e.g. `-Wl,-rpath,$PREFIX/lib`) and/or install_name.
