### ISSUE TITLE
Best practice for limit memory and CPU usage in Docker

### ISSUE THREAD

**Issue by dclong** [jupyterhub/jupyterhub#1595]
I have a JupyterHub server deployed via Docker. I tried to use SystemdSpawner to limit memory and CPU usage but failed. @yuvipanda told me that systemd doesn't work well inside docker. I'm wondering what's the best practice to limit memory and CPU usage if JupyterHub itself is deployed via Docker? I know there's DockerSpawner which I hasn't tried. I wonder how well it works if have Docker inside Docker.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
