### ISSUE TITLE
Post new group using Rest API interface

### ISSUE THREAD

**Issue by sangramga** [jupyterhub/jupyterhub#1602]
In order to add a group, POST method of `/hub/api/groups/{name}` URI  is to be called. But as per general standards of writing REST API services, we should call POST method of `/hub/api/groups` and mention group name only in the JSON body of POST request and not in URI.
Hence there should be a `post(self)` method in `GroupListAPIHandler`.

As these standards are followed while calling POST method in adding users `/hub/api/users` (usernames is mentioned in JSON body) but not in groups.  It would be better to follow same standards in all API's!!

**Comment by minrk** [comment]
> there should be a post(self) method in GroupListAPIHandler.


Indeed there should be. Would you like to make a PR?

**Comment by sangramga** [comment]
@minrk Ok. Just took a look at the code. I would make a PR.

**Comment by sangramga** [comment]
@minrk We need to also change the API Documentation to include this feature.

**Comment by minrk** [comment]
@sangramga good catch. Would you like to make a PR?

**Comment by sangramga** [comment]
@minrk I would be glad. I'll take a look and get back to you.
