### ISSUE TITLE
Allow new user request to access and allow multiple login options

### ISSUE THREAD

**Issue by zero-88** [jupyterhub/jupyterhub#1616]
Hi Jupyter team,
I'm working on Jupyter hub + notebook with auto scaling by Docker/k8s.
I would like to submit new request (or question if it already existed, but I didn't find it, sorry about that)

**What you expected to happen**

1. JupyterHub has option to allow new user request to access his notebook.
- After that, new one click send "access request" on login screen, it will notify to admin group via email that includes accept link page. Admin just click open page to review account, this page should have 2 buttons: accept or deny (may contains reason).

2. JupyterHub has option to enable multiple login method with OAuth.
- It is flexible option for group user, someone use gmail, someone use GitHub, Bitbucket and so on.

**Share what version of JupyterHub you are using**
JupyterHub v0.8.1

Thanks

**Comment by willingc** [comment]
@zero-88 Thanks for the question. I'm a little confused about what your use case is.

In Item 1, can you clarify what you mean? Are you talking about a "new user" getting a jupyterhub account? Or a notebook exists for user #1 and then user #2 requests access to user #1's notebook?

**Comment by zero-88** [comment]
Hi, @willingc 
Thanks for your response. I'm late to track it on time.
- My request is new person, comes to organization that using JupyterHub, wants to open his work-space with *new notebook*. He has google/github account, however, not yet allocated a seat in hub admin. So Hub Admin must be notified offline then add user first, after that new user can open his notebook. I would like to change this way a little bit, new user can request online and admin can add him in list. Do you get my idea?

- About your point, user 2 wants to access user 1 notebook, seem jupyterhub also doesn't support it. I also have a ticket same like that. And I'm using git to share notebook between them.

Thank

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
