### ISSUE TITLE
Accessing Notebook API through the JupyterHub API

### ISSUE THREAD

**Issue by MaximMoinat** [jupyterhub/jupyterhub#1620]
Similar to closed issues #1431 and #1078, but both (outdated?) solutions do not work for me.

**Background**
From a javascript application, that generates a piece of R script, I want to be able to create a Jupyter Notebook into a specific directory. Users can then open the file and execute it. This is possible via the Jupyter Notebook API, with a PUT request on `/api/content/<filename>.ipynb?token=xxx` and a body containing the notebook content.

**Problem**
I want to do the same via the JupyterHub API. And according to the the [REST API documentation](https://jupyterhub.readthedocs.io/en/stable/reference/rest.html), it should be possible to send a request to the Notebook API:

> The same API token can also authorize access to the Jupyter Notebook REST API provided by notebook servers managed by JupyterHub if one of the following is true: 
The token is for the same user as the owner of the notebook
The token is tied to an admin user or service and c.JupyterHub.admin_access is set to True

Can the JupyterHub API indeed be used for what I am trying to achieve? 
Or is there maybe a much easier solution?

Note:
I tried requests to `localhost:8081/user/<username>/api/content/<filename>.ipynb` and `localhost:8081/hub/user/<username>/api/content/<filename>.ipynb` already, but both give a redirect response referring to the other url.
What does work, is to look up the port of the spawned notebook and send a request there (e.g. `localhost:49581/user/<username>/api/content/<filename>.ipynb`. However, this is not practical as the port is generated randomly and can't be retrieved via the JupyterHub API.

**Comment by sigurdurb** [comment]
There was a similar question I answered on StackOverflow 

[Maybe it can be of some assistance](https://stackoverflow.com/a/48224603/7267340)

**Comment by MaximMoinat** [comment]
Thanks for your answer, I already tried without success:
`curl -X GET http://<DOMAIN>:<PORT>/user/<username>/api/contents/<filename>.ipnb -H 'Authorization: Token <token>' -H "Content-Type: application/json"`

Any other suggestions?

**Comment by sigurdurb** [comment]
If there is nothing downloaded then you probably have to access the server first to start it. Like it said in my answer for /user notebooks the user has to start it by himself or admin has to go into the control panel.

**Comment by willingc** [comment]
@MaximMoinat Let me see if I understand your desired use:

1. You have a code snippet that you wish to use to create a new Notebook.
2. You wish to have the newly created Notebook placed in a specific user's directory tree at a specific directory.
3. You wish to do this programmatically using the JupyterHub and Jupyter APIs.

Double check that you are fulfilling the requirements that you mentioned:

> The same API token can also authorize access to the Jupyter Notebook REST API provided by notebook servers managed by JupyterHub if one of the following is true:

> - The token is for the same user as the owner of the notebook
> - The token is tied to an `admin` user or service **and** `c.JupyterHub.admin_access` is set to `True`

The second bullet is the case that you should verify and configure as needed. Both conditions of the second bullet would need to be satisfied.

cc/ @minrk

**Comment by MaximMoinat** [comment]
That is indeed my use-case and I satisfy all conditions under the bullets (both same user and admin user). The server is also started.

To iterate: The JupyterHub API itself works (i.e. the paths given [here](https://jupyterhub.readthedocs.io/en/latest/_static/rest-api/index.html)).

As a test, I tried a simple get of a file: `curl -X GET http://127.0.0.1:8081/user/maxim/api/contents/datasources.json -H 'Authorization: Token <token_of_maxim>' -H "Content-Type: application/json"`
Result:
`302 GET /user/maxim/api/contents/datasources.json → /hub/user/maxim/api/contents/datasources.json (maxim@127.0.0.1) 0.47ms`

When I try the redirect url, the server again responds with a redirect (to /user/maxim/...).

**Comment by minrk** [comment]
Yes, you can definitely do this. However, the server must be running in order for it handle the request correctly. The redirect from /user to /hub/user indicates that maxim's server is not running when the request is received.

I don't recall if the token header is case sensitive, but the docs do specify that the `token` part is lowercase. It probably should be case-insensitive but it may not be, and that could be relevant, so use `token` instead of `Token`.

**Comment by MaximMoinat** [comment]
Thanks everyone for your help. 

I got it to work by changing some settings of the server on which Jupyterhub runs. Somehow curl still gives me a redirect, but the request works from Postman.

**Comment by willingc** [comment]
@MaximMoinat I'm glad you were able to get it working. If you have suggestions on improving the documentation, please leave them here or perhaps open a PR. Thanks.

**Comment by joshtemple** [comment]
I was struggling to accomplish the same thing here, but with Python requests. The solution was to use the correct port. It seems that 8081 is the port for JupyterHub API, not the port for Jupyter Notebook API.  I was able to get that port in Python with `list_running_servers`. Here's my code using requests module.

```
import requests
from notebook.notebookapp import list_running_servers

base_url = next(list_running_servers())['url']
r = requests.get(
    url=base_url + 'api/sessions',
    headers={'Authorization': 'token {}'.format(TOKEN),})

r.raise_for_status()
r.json()
```

**Comment by willingc** [comment]
@joshtemple Thanks for sharing your sample code. If you would like to suggest something for future users to add to the docs [here](https://jupyterhub.readthedocs.io/en/latest/reference/rest.html#use-requests), we would appreciate the addition.
