### ISSUE TITLE
docker: host does not create user container (invalid reference format)

### ISSUE THREAD

**Issue by inkrement** [jupyterhub/jupyterhub#1630]
I basically, tried to run the [Jupyterhub/docker-demo](https://github.com/jupyterhub/jupyterhub-deploy-docker), but upgraded to the newest docker-versions.

The server itself and Github-OAuth work fine, but when I get redirected from Github (right after authentication) I get the following error (and an uncaught exception):

```
jupyterhub | [I 2018-01-24 07:20:32.789 JupyterHub log:124] 302 GET /user/inkrement/ -> /hub/user/inkrement/ (@::ffff:137.208.40.78) 1.14ms
jupyterhub | [I 2018-01-24 07:20:32.888 JupyterHub dockerspawner:373] Container 'jupyter-inkrement' is gone
jupyterhub | [E 2018-01-24 07:20:32.911 JupyterHub user:427] Unhandled error starting inkrement's server: 500 Server Error: Internal Server Error ("invalid reference format")
jupyterhub | [I 2018-01-24 07:20:32.918 JupyterHub dockerspawner:373] Container 'jupyter-inkrement' is gone
jupyterhub | [W 2018-01-24 07:20:32.918 JupyterHub dockerspawner:344] container not found
```

I checked all running and stoped docker containers, but there is no container named "jupyter-inkrement". It seems like it was not able to spawn the docker container, but I do not know what to do. Any suggestions? 

The container-docker is linked to the host-docker via volume as in the demo and I am using a quite new docker version:  17.05.0-ce, build 89658be

**Comment by willingc** [comment]
This issue was moved to jupyterhub/jupyterhub-deploy-docker#62
