### ISSUE TITLE
hello Team,   i was trying to take mksysb from ansible server .. and recevied error ..

### ISSUE THREAD

**Issue by sadanand25** [jupyterhub/jupyterhub#1635]
Hi! Thanks for using JupyterHub.

If you are reporting an issue with JupyterHub:

- Please use the [GitHub issue](https://github.com/jupyterhub/jupyterhub/issues)
  search feature to check if your issue has been asked already. If it has,
  please add your comments to the existing issue.

- Where applicable, please fill out the details below to help us troubleshoot
  the issue that you are facing. Please be as thorough as you are able to
  provide details on the issue.

**How to reproduce the issue**

**What you expected to happen**

**What actually happens**

**Share what version of JupyterHub you are using**

Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.

```

Insert jupyter troubleshoot output here


```

**Comment by sadanand25** [comment]
Hello Team,


Please help on the ansible issue .. i was tring to take mksysb from ansible server and received below error.





The full traceback is:
  File "/tmp/ansible_xjyh0uzu/ansible_modlib.zip/ansible/module_utils/basic.py", line 2762, in run_command
    cmd = subprocess.Popen(args, **kwargs)
  File "/opt/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/opt/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)

fatal: [XXX]: FAILED! => {
    "changed": false,
    "cmd": "/usr/bin/mksysb -X -e -G -p -a -i /imagebkp/xxc",
    "invocation": {
        "module_args": {
            "backup_crypt_files": true,
            "backup_dmapi_fs": true,
            "create_map_files": false,
            "exclude_files": true,
            "exclude_wpar_files": true,
            "extended_attrs": true,
            "name": "xxx",
            "new_image_data": true,
            "software_packing": false,
            "storage_path": "/imagebkp",
            "use_snapshot": false
        }
    },
    "msg": "[Errno 13] The file access permissions do not allow the specified action.",
    "rc": 13
}

**Comment by willingc** [comment]
Hi @sadanand25,

As this is an Ansible question and not directly a JupyterHub question, I recommend asking on the Ansible support channels. The actor of the command does not have sufficient privileges to execute the command.

A similar issue is found on the Ansible GitHub site: https://github.com/ansible/ansible/issues/17908#issuecomment-333384732

One troubleshooting tip with ansible is to make sure that you can execute the command directly without Ansible. Good luck.
