### ISSUE TITLE
Jupyter Notebook and Cython - unable to execute 'gcc': No such file or directory

### ISSUE THREAD

**Issue by ndandanov** [jupyterhub/jupyterhub#1640]
Hi,

Thank you for the overall great JupyterHub!

I am experiencing an issue with `Jupyterhub` installed with `Anaconda3` and `systemdspawner`. `Jupyterhub` runs as a systemd service.

When I try to run any `Cython` code, I am presented with the error message `unable to execute 'gcc': No such file or directory`.

- Where applicable, please fill out the details below to help us troubleshoot
  the issue that you are facing. Please be as thorough as you are able to
  provide details on the issue.

**How to reproduce the issue**

You can try to reproduce it by downloading [this Notebook](http://jakevdp.github.io/downloads/notebooks/CythonIsingModel.ipynb) from this [article](http://jakevdp.github.io/blog/2017/12/11/live-coding-cython-ising-model/) and try to run it.

**What you expected to happen**

I had an older Jupyterhub installation for testing purposes where [the Notebook](http://jakevdp.github.io/downloads/notebooks/CythonIsingModel.ipynb) works flawlessly as described in the [article](http://jakevdp.github.io/blog/2017/12/11/live-coding-cython-ising-model/).

**What actually happens**

The following exception occurs:
![image](https://user-images.githubusercontent.com/17270267/35634605-bf06a0ea-06b4-11e8-8914-436ee5e006a1.png)

[Here I uploaded the Notebook.](https://github.com/ndandanov/test-jupyter-cython/blob/master/CythonIsingModel.ipynb) Please check it for the full stack trace.

**Share what version of JupyterHub you are using**

`jupyterhub` is version **0.8.1**.
`gcc` is version `6.3.0 20170516 (Debian 6.3.0-18)`.

I would be glad if anyone could point me in a direction for debugging before I reproduce my setup and debug it step by step.
The older setup which works flawlessly has the same version of `jupyterhub` but `gcc` is version `4.9.2 (Debian 4.9.2-10)`.

Thank you in advance!

**Comment by willingc** [comment]
Hi @ndandanov,

FYI (mostly for others reading this later):

You can run this notebook on mybinder.org by clicking this link: https://mybinder.org/v2/gh/jakevdp/jakevdp.github.io-source/master

Once the notebook browser opens, the notebook is in `content/downloads/notebook` directory. You will need to install numpy, pillow, and cython. This can be done by adding a cell and using the %%bash magic to then pip install the packages.
---
Back to your original question why is the system not finding gcc. I suspect that the newer Debian system does not have its path configured to find gcc. How did you install Cython, numpy, and pillow?

**Comment by ndandanov** [comment]
Hi Carol,

Thank you for your fast response!

I installed the mentioned packages using `conda`:

| Name        | Version           | Build  | Channel |
| ------------- |:-------------:| -----:| -----:|
| cython      | 0.27.3 | py36h1860423_0 | anaconda |
| numpy      | 1.13.3      |   py36h3dfced4_2 | |
| pillow | 4.2.1      |   py36h9119f52_0  | |

**Comment by willingc** [comment]
@ndandanov If I do `conda info <package-name`, it doesn't appear that any of the 3 are loading gcc as a dependency. Would you try doing a `conda install gcc` as well. Thanks!

**Comment by ndandanov** [comment]
Hi Carol,

Thank you for your time and assistance!
Sorry to respond so late - I am living in quite a different time zone :)

First, here is the output of `conda info <package-name>` for the three packages in question:

```bash
cython 0.27.3 py36h1860423_0
----------------------------
file name   : cython-0.27.3-py36h1860423_0.tar.bz2
name        : cython
version     : 0.27.3
build string: py36h1860423_0
build number: 0
channel     : https://repo.continuum.io/pkgs/main
size        : 3.1 MB
arch        : None
constrains  : ()
license     : Apache-2.0
md5         : 7067368d70b8d88315e383e73288430d
platform    : None
subdir      : linux-64
timestamp   : 1512030347046
url         : https://repo.continuum.io/pkgs/main/linux-64/cython-0.27.3-py36h1860423_0.tar.bz2
dependencies:
    libgcc-ng 7.2.0.*
    python >=3.6,<3.7.0a0
    setuptools
```

```bash
numpy 1.13.3 py36h3dfced4_2
---------------------------
file name   : numpy-1.13.3-py36h3dfced4_2.tar.bz2
name        : numpy
version     : 1.13.3
build string: py36h3dfced4_2
build number: 2
channel     : https://repo.continuum.io/pkgs/main
size        : 3.9 MB
arch        : None
constrains  : ()
license     : BSD 3-Clause
md5         : 3dcc264ebd4aa68f02b1e865b32e59a6
platform    : None
subdir      : linux-64
timestamp   : 1516836903302
url         : https://repo.continuum.io/pkgs/main/linux-64/numpy-1.13.3-py36h3dfced4_2.tar.bz2
dependencies:
    libgcc-ng >=7.2.0
    libgfortran-ng >=7,<8.0a0
    mkl
    python >=3.6,<3.7.0a0
```
```bash
pillow 4.2.1 py36h9119f52_0
---------------------------
file name   : pillow-4.2.1-py36h9119f52_0.tar.bz2
name        : pillow
version     : 4.2.1
build string: py36h9119f52_0
build number: 0
channel     : https://repo.continuum.io/pkgs/main
size        : 548 KB
arch        : None
constrains  : ()
license     : PIL
md5         : 2aba6aa29792720fac27ebdc26d0b439
platform    : None
subdir      : linux-64
timestamp   : 1505744519253
url         : https://repo.continuum.io/pkgs/main/linux-64/pillow-4.2.1-py36h9119f52_0.tar.bz2
dependencies:
    freetype >=2.8,<2.9.0a0
    jpeg >=9b,<10a
    libgcc-ng >=7.2.0
    libtiff >=4.0.8,<5.0a0
    olefile
    python >=3.6,<3.7.0a0
    zlib >=1.2.11,<1.3.0a0
```

On the machine which works, I have the following `gcc`-relevant packages installed:

| Name        | Version           | Build  | Channel |
| ------------- |:-------------:| -----:| -----:|
| libgcc-ng      | 7.2.0 | h7cc24e2_2 |  |
                                 

And on the one which does not execute Cython code properly:

| Name        | Version           | Build  | Channel |
| ------------- |:-------------:| -----:| -----:|
| libgcc      | 7.2.0 | h69d50b8_2  |  |
| libgcc-ng      | 7.2.0      |   h7cc24e2_2  | |


I followed your advice and did `conda install gcc`. The installed version is:

| Name        | Version           | Build  | Channel |
| ------------- |:-------------:| -----:| -----:|
| gcc      | 4.8.5 | 7 |  |


However, this resulted in a non-booting Python3 kernel:

```bash
Feb 01 10:25:35 server systemd[1]: Started /bin/bash -c cd /home/nikolay && exec jupyterhub-singleuser --port=33181 '--notebook-dir="~/jupyter_notebooks"'.
Feb 01 10:25:35 server bash[19005]: Traceback (most recent call last):
Feb 01 10:25:35 server bash[19005]:   File "/opt/anaconda/anaconda3/bin/jupyterhub-singleuser", line 3, in <module>
Feb 01 10:25:35 server bash[19005]:     from jupyterhub.singleuser import main
Feb 01 10:25:35 server bash[19005]:   File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 34, in <module>
Feb 01 10:25:35 server bash[19005]:     from notebook.notebookapp import (
Feb 01 10:25:35 server bash[19005]:   File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 44, in <module>
Feb 01 10:25:35 server bash[19005]:     from zmq.eventloop import ioloop
Feb 01 10:25:35 server bash[19005]:   File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 34, in <module>
Feb 01 10:25:35 server bash[19005]:     from zmq import backend
Feb 01 10:25:35 server bash[19005]:   File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
Feb 01 10:25:35 server bash[19005]:     reraise(*exc_info)
Feb 01 10:25:35 server bash[19005]:   File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
Feb 01 10:25:35 server bash[19005]:     raise value
Feb 01 10:25:35 server bash[19005]:   File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
Feb 01 10:25:35 server bash[19005]:     _ns = select_backend(first)
Feb 01 10:25:35 server bash[19005]:   File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
Feb 01 10:25:35 server bash[19005]:     mod = __import__(name, fromlist=public_api)
Feb 01 10:25:35 server bash[19005]:   File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
Feb 01 10:25:35 server bash[19005]:     from . import (constants, error, message, context,
Feb 01 10:25:35 server bash[19005]: ImportError: /opt/anaconda/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `GLIBCXX_3.4.20' not found (
Feb 01 10:25:35 server systemd[1]: jupyter-nikolay-singleuser.service: Main process exited, code=exited, status=1/FAILURE
Feb 01 10:25:35 server systemd[1]: jupyter-nikolay-singleuser.service: Unit entered failed state.
Feb 01 10:25:35 server systemd[1]: jupyter-nikolay-singleuser.service: Failed with result 'exit-code'.
```

However, `libstdc++.so.6` was there:
```bash
root@server ~# ls /opt/anaconda/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6 -la
lrwxrwxrwx 1 root root 19 Feb  1 10:19 /opt/anaconda/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6 -> libstdc++.so.6.0.19*
root@server ~# ls /opt/anaconda/anaconda3/lib/libstdc++.so.6 -la
lrwxrwxrwx 1 root root 19 Feb  1 10:19 /opt/anaconda/anaconda3/lib/libstdc++.so.6 -> libstdc++.so.6.0.19*
```

I tried `conda update --all` which updated the following packages:


```bash
    asn1crypto:   0.22.0-py36h265ca7c_1           --> 0.24.0-py36_0         
    cffi:         1.10.0-py36had8d393_1           --> 1.11.4-py36h9745a5d_0 
    conda-build:  3.0.27-py36h940a66d_0           --> 3.4.0-py36_0          
    cryptography: 2.0.3-py36ha225213_1            --> 2.1.4-py36hd09be54_0  
    cython:       0.27.3-py36h1860423_0  anaconda --> 0.27.3-py36h1860423_0 
    cytoolz:      0.8.2-py36h708bfd4_0            --> 0.9.0-py36h14c3975_0  
    filelock:     2.0.12-py36hacfa1f5_0           --> 2.0.13-py36h646ffb5_0 
    glob2:        0.5-py36h2c1b292_1              --> 0.6-py36he249c77_0    
    pyopenssl:    17.2.0-py36h5cc804b_0           --> 17.5.0-py36h20ba746_0 
    ruamel_yaml:  0.11.14-py36ha2fb22d_2          --> 0.15.35-py36h14c3975_1
    toolz:        0.8.2-py36h81f2dff_0            --> 0.9.0-py36_0          
    yaml:         0.1.7-h96e3832_1                --> 0.1.7-had09818_2      
```

The kernel would still not launch. I ran `conda update -n base conda` as well, but no updates were necessary.

I had to remove `gcc` with `conda uninstall gcc` in order to have the kernel start properly.

Could it be some misconfiguration of Anaconda and/or Jupyter and/or Jupyterhub?

Thanks in advance!

**Comment by willingc** [comment]
@minrk have you seen any issues like this with gcc? I'm wondering if using conda-forge channel would be better than default.

**Comment by minrk** [comment]
gcc isn't a dependency of the conda Cython package because it's typically used with the system compiler. My guess is that's the issue you are encountering with glibc versions. Try removing the `gcc` conda package and go back to using the gcc on your system. The No such file errors suggests that gcc is not on your PATH. If you check in a terminal and see that you have gcc installed, then try checking $PATH in the notebook itself, since that's what is relevant. You can also try compiling something with Cython outside the notebook. In Python, you can run `shutil.which('gcc')` as one way to find gcc on your PATH.

**Comment by ndandanov** [comment]
Dear @willingc and @minrk,

Thank you for the advice!

There is something wrong with the production environment I use.
Here is an example of the output when I tried to get the current `PATH` in a Python3 notebook:
https://github.com/ndandanov/test-jupyter-cython/blob/master/path-not_working.ipynb

And here is the same notebook executed on the older test server:
https://github.com/ndandanov/test-jupyter-cython/blob/master/path-working.ipynb

I guess there is some misconfiguration (could it be Jupyterhub?) or there is some more general issue with the system or the packages installed.

Any help would be appreciated! Thank you!

**Comment by minrk** [comment]
Indeed, that looks like PATH is not what it should be. What is `os.getenv('PATH')`?

PATH is generally set by the Spawner, and the default is to inherit from the parent env via `.env_keep`. Do you perhaps have Spawner.env_keep configuration?

**Comment by ndandanov** [comment]
Dear @minrk,

Thank you for your advice!

The output of 
```python
import os
os.getenv('PATH')
```
is indeed
```python
'$PATH:/opt/anaconda/anaconda3/bin'
```

which seems to be quite wrong.
For reference, on the working test machine, the `PATH` is

```python
'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/jupyconda/anaconda3/bin'
```

So it seems that the `$PATH` variable is not being expanded properly.

Thank you very much for your advice regarding the `env_keep` configuration. I added the following configurations for Jupyterhub:

```bash
c.Spawner.env_keep = ['PATH', 'PYTHONPATH', 'CONDA_ROOT', 'CONDA_DEFAULT_ENV', 'VIRTUAL_ENV', 'LANG', 'LC_ALL']
```

as well as this one for using `bash` by default in the terminal:

```bash
c.SystemdSpawner.default_shell = '/bin/bash'
```

However, this did not solve the problem.
One of the main differences between my test and production environments is using a `systemd` service for managing `Jupyterhub`. I checked the `systemd` service definition carefully:

```bash
[Unit]
Description=Jupyterhub
After=syslog.target network.target

[Service]
User=root
Environment="PATH=$PATH:/opt/anaconda/anaconda3/bin"
ExecStart=/opt/anaconda/anaconda3/bin/jupyterhub -f /etc/jupyterhub/jupyterhub_config.py

[Install]
WantedBy=multi-user.target
```

And then found on various sources (below I am referring to [this one](https://unix.stackexchange.com/questions/347873/set-path-for-a-systemd-unit)) that:

> Alternatives such as using Environment=PATH=/new/path:$PATH will not work as systemd will not expand the $PATH.

So I replaced the `$PATH` variable with the actual `PATH` I want to have in `Jupyterhub`:

```bash
Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/anaconda/anaconda3/bin"
```

Then I restarted the service and everything, including `Cython` compilation, seems to work well. And the `PATH` is of course correct:

```python
'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/anaconda/anaconda3/bin'
```

Thank you again, @willingc  and @minrk, for your time and kind assistance!
My issue seems to be now solved, but you may want to include some of these findings in the official documentation regarding `systemd` services.

**Comment by minrk** [comment]
Glad you found it out! If there's an obvious place for this in the docs, that would be a great addition.

**Comment by willingc** [comment]
Thanks @minrk and @ndandanov. I'm glad you have it up and running.

As for docs, perhaps something related to PATH in the spawner reference section would make good sense:

>PATH is generally set by the Spawner, and the default is to inherit from the parent env via .env_keep.

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!
