### ISSUE TITLE
Feature Request: Jupyter Themes

### ISSUE THREAD

**Issue by strin** [jupyterhub/jupyterhub#1641]
https://github.com/dunovank/jupyter-themes

**Comment by minrk** [comment]
Thanks! Since that repo exists, I'm not sure what there is to do on jupyterhub. Are you asking how to install that extension with jupyterhub?

**Comment by sabyasm** [comment]
Yes - it would be really helpful to have guide to integrate jupyter themes with Jupyter Hub.

**Comment by uphy** [comment]
We can execute shell command with prefix "!" in Jupyter notebook.

```bash
!jt -t oceans16 -tf merriserif -tfs 10 -nf ptsans -nfs 13
```

Although, I don't know how to apply theme on setup.

**Comment by nikolayvoronchikhin** [comment]
@uphy Your execution step worked for me. After reloading the notebook, I can view the new theme. Thank you!

**Comment by ebauch** [comment]
that doesn't seem to work; I am getting the following error

![image](https://user-images.githubusercontent.com/3758223/54461890-4d324880-4744-11e9-83c3-08936209378a.png)

I am running juptyerhub in the docker file jupyterhub

**Comment by willingc** [comment]
@ebauch It looks as if the current user does not have write permission for the `/tmp` directory.

**Comment by ahmedanis03** [comment]
this doesn't work for me; 
```
!jt -t oceans16
```
opened a terminal and applied it then opened an incognito window, but also nothing.
custom folder created under .jupyter folder
