### ISSUE TITLE
How to deployed multi jupyterhub server which is statusless servers

### ISSUE THREAD

**Issue by moskiGithub** [jupyterhub/jupyterhub#1646]
Hi, jupyterhub engineer
I want to deploy three docker cluster service, first cluster will running a flask app and multi jupyterhub service, jupyterhub service will run notebook server on second cluster, third cluster is a ipyparallel cluster that will be shared by notebook server (notebook is same jupytehub startup).
flask app will be responsible for user authentication and distribution of users to jupyterhub.
In addition, I will use docker swarm to build total environment.
I search a lot of resource, but I don't get usefull information.
Can you provide me some information and resources?

**Comment by consideRatio** [comment]
Hi! I'm think that this guide http://zero-to-jupyterhub.readthedocs.io is the best starting point for you.

**Comment by willingc** [comment]
As @consideRatio has helpfully shared, the Zero to JupyterHub guide would be the best way to set up a cluster for JupyterHub.
