### ISSUE TITLE
Issue starting a new server in singleuser container

### ISSUE THREAD

**Issue by jkbach** [jupyterhub/jupyterhub#1649]
Hi!

Apologies if this is an obvious question, I'm new to both JupyterHub and Docker and having a hard time troubleshooting. I'm working on setting up JupyterHub on a server running CentOS. I'm trying to create a new container for each user by following the instructions in this video (timestamp in link) https://youtu.be/gSVvxOchT8Y?t=42m10s

I'm operating as my local user, but I have sudo permissions, so I run jupyterhub via
`sudo jupyterhub`. I get the same error if I try to run as root by running
`sudo su`

First, I installed the docker image for `jupyterhub/singleuser` with `sudo docker pull jupyterhub/singleuser`. When I tried to start my server, I got the following error:

```
[E 2018-02-06 00:52:49.115 JupyterHub user:427] Unhandled error starting jkbach's server: 404 Client Error: Not Found ("no such image: jupyterhub/singleuser:0.8: No such image: jupyterhub/singleuser:0.8")
```

To resolve this, I pulled the image it was searching for and unable to find with 
`sudo docker pull jupyterhub/singleuser:8.0`
Now, when I try to start my server, I get the following error:

```
[I 2018-02-06 01:02:38.382 JupyterHub dockerspawner:540] Created container 'jupyter-jkbach' (id: cd3ecc4) from image jupyterhub/singleuser:0.8
[I 2018-02-06 01:02:38.383 JupyterHub dockerspawner:557] Starting container 'jupyter-jkbach' (id: cd3ecc4)
[E 2018-02-06 01:02:39.274 JupyterHub user:427] Unhandled error starting jkbach's server: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"tini\": executable file not found in $PATH": unknown")
[E 2018-02-06 01:02:39.325 JupyterHub web:1591] Uncaught exception GET /hub/user/jkbach/ (::ffff:97.113.189.124)
``` 

My current versions:
- JupyterHub version: 0.8.1
- Docker version: 17.12.0-ce, build c97c6d6

Thanks so much, excited to get this working.

**Comment by jkbach** [comment]
Hi,
Wondering if anyone has had a chance to take a look at this.
Thanks!

**Comment by willingc** [comment]
@jkbach Sorry about not responding sooner. Is this still an issue for you?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for over a month. Please feel free to request that we reopen this issue or ask us a follow-up question on gitter. Thanks! 🌻
