### ISSUE TITLE
Security Requirements 

### ISSUE THREAD

**Issue by javin-gn** [jupyterhub/jupyterhub#1650]
Hi,

We have the following requirements:
- Enable HTTP Strict Transport Security 
- Enable HTTPOnly
- Enable SSL Cookie With Secure Flag
-  Set Cookie to expired immediately

Does JupyterHub supports this in Config?

Thanks

**Comment by minrk** [comment]
> - Enable HTTP Strict Transport Security

You can do this in an nginx layer in front of JupyterHub

> - Enable HTTPOnly
> - Enable SSL Cookie With Secure Flag

Yes, these are the default behavior of JupyterHub cookies

> - Set Cookie to expired immediately

I'm not quite sure what this means. Cookies that expire immediately aren't very useful. Can you explain with some more detail?

**Comment by javin-gn** [comment]
Hi,

Thank you for your reply.

For enabling of HTTP Strict Transport Securtiy Protocol. is there any other way besides using NGINX as proxy. We do have limitation if it is a paid service

For Enable HTTPOnly and Enable SSL Cookie With Secure Flag, it seems that It was not enable by default as in was detected as vulnerability. Do we have the change the jupyterhub config file?

For setting cookies to expired immediately, Persistent cookies are stored on the browsing clients hard drive even when the client is no longer browsing the Web site that set the client. Depending on what information is stored in the cookie, this could lead to security and privacy violations. It will be good to disable persistence cookies

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
