### ISSUE TITLE
jupyterhub 0.8.1 http connections are fine; but for https (ssl) not able to getthe login page

### ISSUE THREAD

**Issue by mohanamurali7** [jupyterhub/jupyterhub#1652]
Hello Team,

Able to view files and notebooks over http connections (multi user login - local centos users was also possible). But, for https connection, cannot even view the login page. Tried in two browsers - Chrome and Edge.

**_Version Information:_**
Juyterhub version 0.8.1
pip 9.0.1
Python 3.6.3

**_Console output:_**
08:59:11.570 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:443
08:59:11.571 - info: [ConfigProxy] 201 POST /api/routes/
[I 2018-02-07 08:59:11.572 JupyterHub app:1581] JupyterHub is now running at https://:8000/
08:59:29.512 - error: [ConfigProxy] 503 GET / connect ECONNREFUSED 127.0.0.1:443
08:59:29.514 - error: [ConfigProxy] Failed to get custom error page Error: connect ECONNREFUSED 127.0.0.1:443
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1194:14)
08:59:31.232 - error: [ConfigProxy] 503 GET /favicon.ico connect ECONNREFUSED 127.0.0.1:443
08:59:31.233 - error: [ConfigProxy] Failed to get custom error page Error: connect ECONNREFUSED 127.0.0.1:443
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at TCPConnectWrap.afterConnect [as oncomplete] **(net.js:1194:14)**

Following are the only changes that I have made in the **_configuration file_** which is passed when Jupyterhub is started (command:  sudo jupyterhub -f configFileLocation)

c.Application.log_level = 'DEBUG'
c.JupyterHub.cookie_secret = b'secret filelocation'
c.JupyterHub.debug_db = True
c.JupyterHub.extra_log_file = '.log location'
c.JupyterHub.hub_connect_port = 443
c.JupyterHub.ssl_cert = '.crt file location'
c.JupyterHub.ssl_key = '.key file location'
c.Spawner.debug = True
c.Spawner.notebook_dir = 'directory location'
c.PAMAuthenticator.open_sessions = False

**Comment by mohanamurali7** [comment]
Have been trying to debug this further... but haven't tasted success. I tried using curl command - first I got the message that there is error with certificate... so, I tried the insecure option.... again I end up seeing "service unavailable" - the same error that I got in the browser.

Though jupyterhub is running, I am not clear, why it is returning 503 - service unavailable... is there something that needs to be passed for getting connected... Pls. do suggest 

$ curl https://ipaddress:8000/hub/login
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

$ curl --insecure https://ipaddress:8000/hub/login
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    19    0    19    0     0      9      0 --:--:--  0:00:02 --:--:--     9**_Service Unavailable_**

**Comment by minrk** [comment]
I think you want `c.JupyterHub.port = 443`, and don't set `hub_connect_port`. `hub_connect_port` is used for internal communication only when the bind ip/port of the internal Hub process (not the public URL of the application) is different from the bind port, which is still the default of 8081 in your config. This is a rare occurrence outside the use of containers.

From JupyterHub help output:

```
JupyterHub.port=<Int>
    Default: 8000
    The public facing port of the proxy
JupyterHub.hub_connect_port=<Int>
    Default: 0
    The port for proxies & spawners to connect to the hub on.
    Used alongside `hub_connect_ip`
```

I think we could probably stand to get more detailed info in the help strings for the ip/port config.

**Comment by mohanamurali7** [comment]
Thanks a lot Benjamin. It was very very helpful. I am pretty new to Jupyterhub, but think that should have explored more... now this will help me to explore further with Jupyterhub in the coming days for more customizations.
