### ISSUE TITLE
HubOAuth service configuration example

### ISSUE THREAD

**Issue by brospars** [jupyterhub/jupyterhub#1659]
Hi !

I'm having trouble configuring the [HubOAuth service](https://jupyterhub.readthedocs.io/en/stable/api/services.auth.html#jupyterhub.services.auth.HubOAuth). I'm trying to make Jupyterhub a OAuth provider to authenticate user in a selfhosted Gitlab. I aware that it is usualy the otherway around but in my case users are already connected to Jupyterhub so it would be perfect if this work.

Could someone explain how to use it ? And I think it would be useful to have an example in the docs.

Thanks a lot

**Comment by minrk** [comment]
[Here is an example oauth service](https://github.com/jupyterhub/jupyterhub/blob/master/examples/service-whoami/whoami-oauth.py). There is another one [using flask](https://github.com/jupyterhub/jupyterhub/blob/master/examples/service-whoami-flask/whoami-oauth.py).

Note that with JupyterHub 0.8, it is required that these services reside within the Hub domain and be served on `[hub.host]/services/:service-name`, registered via the jupyterhub services configuration. External services may not use JupyterHub as an oauth provider. This will change in jupyterhub 0.9 with #1590

**Comment by brospars** [comment]
Ok so if I understand this correclty, it's not possible for now to use Jupyterhub as a auth server for Gitlab (using `omniauth-oauth2-generic` as suggested [here](https://gitlab.com/satorix/omniauth-oauth2-generic#gitlab-config-example)) but maybe will be in the next version ?

Sorry for asking but I'm quite new with the Jupyter environment and I just want to understand correctly how it works.
