### ISSUE TITLE
Add a readiness probe to singleuser server

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#1664]
From my understanding (which can be totally wrong!), a singleuser server can be considered 'ready' under the following circumstances:

1. The process is up and running
2. A user has actually made at least one properly authenticated request with Hub OAuth

If we can have a `/ready` endpoint that returns true when these are true, I think that would be very helpful for large deployments.

I'm also planning on a proxy implementation where the routespec is directly an attribute of the spawned kubernetes pod. This means there's no extra proxy add / route check step, which is a good thing for complexity / scaling reasons. However, this also means there needs to be an easy way to figure out when to start sending traffic to a pod / when to stop. Traditionally this is done with readiness probes, and lots of cluster automation tools have support for this paradigm. Adding that here would help us quite a bit I think.

**Comment by minrk** [comment]
We can definitely add this. How would the "OAuth request received" state be used, though? It won't get such a request until the proxy is sending traffic its way, so I'm not sure how it can be used as a proxy input.

**Comment by yuvipanda** [comment]
Ah, interesting. So we should just count as ready as soon as the process is up? If so we don't need anything... (I can never keep the auth workflow in my head!)

To be more exactl, what happens between poll saying 'ok server is ready!' and us adding proxy route in jupyterhub? If proxy starts sending traffic to the pod as soon as the process is up, what will we miss?

**Comment by minrk** [comment]
In JupyterHub, we:

> To be more exact, what happens between poll saying 'ok server is ready!' and us adding proxy route in jupyterhub?

1. request that process start (Spawner.start, which returns ip/port)
2. wait for ip/port to respond to http requests (any response is enough)
3. signal to proxy that it should start sending traffic to the pod
4. wait for proxy to actually be routing traffic (assuming `proxy.add_route` returns when traffic is actually directed)
5. redirect user requests that we were holding until the server was 'ready', which is: running, accepting http connections, and registered in the proxy.

> If proxy starts sending traffic to the pod as soon as the process is up, what will we miss?

Assuming the readiness probe in the proxy checks for responding to HTTP requests (to `/` ought to be good enough, which will typically 302 or 404), I don't think anything will be missed. All information passed from teh Hub to the single-user server is in the process startup (environment variables, etc.). Once it's running, it's fully ready to go. After this point, the only thing the Hub is doing is checking on it, not influencing it. I think the only thing that can happen from routing prematurely is if it starts routing after the process starts but before it has warmed up to start accepting connections, in which case you ought to get 503s from the proxy.

**Comment by yuvipanda** [comment]
Cool! So if I add a readiness probe for /, as soon as it is 'Ready' I can start routing traffic to it. I'll play with it in a few days and see where it goes!

**Comment by minrk** [comment]
Yes, I think that should work just fine. I think the greater risk with NullProxy is in being too slow, because if the Hub starts sending people to the URL but the proxy hasn't caught up, we'll get redirect loops. We have the redirect fallback you added for this case, but it would be ideal if `add_route` in  NullProxy could be used to wait until the routes have been updated, or at least make it more likely to have caught up. I'm not sure if that's possible.

**Comment by minrk** [comment]
At the very least, it could also validate that a pod with the right annotation exists, because if the annotation is wrong proxying will fail, so an error in add_route would probably be appropriate.

**Comment by manics** [comment]
Can we close this?

**Comment by manics** [comment]
No response, closing.
