### ISSUE TITLE
OAuth state missing from cookies

### ISSUE THREAD

**Issue by umar-sik** [jupyterhub/jupyterhub#1668]
I am using kubernetes with jupyterhub. When I use Auth0 as an authentication API, I always get the error "OAuth state missing from cookies" after choosing my google account to log in.

What could be the issue?

Thanks

**Comment by umar-sik** [comment]
I am using kubernetes with jupyterhub. When I use Auth0 as an authentication API, I always get the error "OAuth state missing from cookies" after choosing my google account to log in.

What could be the issue?

Thanks

**Comment by betatim** [comment]
Duplicate of #1682
