### ISSUE TITLE
Removing JupyterHub Version in server header

### ISSUE THREAD

**Issue by javin-gn** [jupyterhub/jupyterhub#1674]
Hi we have a requirement to remove JupyterHub Version in Server Header. Any guide to help us in this?

**Comment by minrk** [comment]
You could remove it in a proxy in front of jupyterhub, e.g. nginx.

**Comment by javin-gn** [comment]
We have use nginx as a proxy and we use the more headers modules to remove the server header. But the version is still being flag out on IE. Firefox is working. Is it a browser comparability issue?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
