### ISSUE TITLE
"API-only mode" where Hub is not the default route

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#1675]
Novel deployments like binder use jupyterhub to manage processes, but the logical behavior when a user visits a URL like `/user/foo` when no server is running.

The main aspect of this is to make adding the Hub itself as the default route optional. In these cases, we would still need to register the hub at `/hub/`. Secondarily, we may want to support a *different* default route, but that could also be handled in the proxy's own configuration (e.g. setting the `--default-route` arg in an externally managed CHP instance).

**Comment by manics** [comment]
Is this still on the wish-list or is there already an alternative solution?

**Comment by consideRatio** [comment]
@yuvipanda do you know if this was worked towards? I recall you deployed something like this.

I closed #3898 just now but wanted to see if there was documentation about something like this.

**Comment by yuvipanda** [comment]
I think @minrk recently implemented this right?

**Comment by minrk** [comment]
Not even that recently, but we do have [docs for this](https://jupyterhub.readthedocs.io/en/stable/howto/api-only.html)

**Comment by yuvipanda** [comment]
My sense of time seems to have completely died for what 'recently' means haha.

Thanks @minrk
