### ISSUE TITLE
JupyterHub 0.8.1 on CentOS 7.3: Logging TimeoutError, Server Error 500

### ISSUE THREAD

**Issue by renglandatsmu** [jupyterhub/jupyterhub#1679]
Hello. I am completely new to JupyterHub, but I have recently installed a JupyterHub (v0.8.1) on CentOS 7.3 running on a Lenovo x3550 M5 platform, and it has been in use by students in several classes for a little over a month. For the most part, the Hub has done what it is supposed to do, but yesterday afternoon it began logging TimeoutError messages when some students would attempt to start their personal servers, and after a while they began getting Server Error 500. After a short while longer, this began happening to all of the students. (There are about 300, total, who have access, though not all of them are using it at once.) When I was notified, I restarted the Hub, but after the service was back up and running, I continued to see the 500 error whenever I attempted to start a personal server. I also attempted rebooting the server itself, to no avail. The way I eventually restored service was to rename the jupyterhub.sqlite file and restart the Hub, thus generating a fresh database. I therefore assume that the database was somehow corrupted, though at no point was the JupyterHub unexpectedly terminated to cause such corruption. Has anyone seen anything like this?

My questions:
1. What is causing the database to become corrupted (if that is indeed what is happening)?
2. Is removing/relocating the database and starting afresh the best way to go about restoring service?
3. How can I prevent future occurrences? (Have I made some mistake in my configuration of the Hub?)

**How to reproduce the issue**
Uncertain, since I am unsure what the cause actually is.

**What you expected to happen**
Users to be able to continue starting their personal servers from the Hub.

**What actually happens**
Users begin receiving "Server Error 500" when they attempt to start personal servers.

**Share what version of JupyterHub you are using**
0.8.1, running on CentOS 7.3 on a Lenovo x3550 M5 platform.

Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.

```
The issue has, for the moment, been remediated, so I'm not sure 'jupyter troubleshoot' would do anything for us at this point. However, attached is an example of the kind of error log entries we were receiving while the incident was in progress, as well as a copy of our config.py file (modified to remove usernames and disguise IP addresses for security reasons.)

Thanks in advance,

Richard England
HPC SysAdmin
Southern Methodist University

[ErrLogExcerpt_2018-02-21.log](https://github.com/jupyterhub/jupyterhub/files/1748819/ErrLogExcerpt_2018-02-21.log)

[config.py.txt](https://github.com/jupyterhub/jupyterhub/files/1748823/config.py.txt)

```

**Comment by fakufaku** [comment]
I am having the same problem. I run Ubuntu 14.04 with anaconda and python 3.6, jupyterhub 0.8.1 installed from conda-forge.

**Comment by willingc** [comment]
Hi all, Please try the latest version JupyterHub 0.9.3.

Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
