### ISSUE TITLE
Allow configuration setting for "how" to contact admin on error messages

### ISSUE THREAD

**Issue by chicocvenancio** [jupyterhub/jupyterhub#1680]
Add the config possibility of changing the 500 error message to include admin contact information. This could start as simple string config to be added at https://github.com/jupyterhub/jupyterhub/blob/96403647132e74255f914fd54f426390cbdfc0ad/jupyterhub/handlers/base.py#L39

or a maybe  allowing for full customization of these error messages.

**Comment by willingc** [comment]
@chicocvenancio I'm going to close this as #1481 captures better customization and usability. I'll mark this as reference too.
