### ISSUE TITLE
Can't use `User.get_auth_state` to configure `Spawner.options_form`

### ISSUE THREAD

**Issue by emmanuel** [jupyterhub/jupyterhub#1681]
I'm using JupyterHub 0.8.1 (on Kubernetes). I am attempting to create a custom `Spawner.options_form` whose content is based on group membership information returned by a custom Authenticator. The groups are successfully retrieved and stored using the `auth_state` interface (introduced in 0.8.0), but I don't think it's possible to use this data to configure the form from my Spawner. The fundamental issue (as I understand it), is that the `User.get_auth_state` method is async (returns a Future), whereas the `Spawner.options_form` method is synchronous.

I've reviewed the approach linked from here: https://github.com/jupyterhub/jupyterhub/issues/1542. This Authenticator/Spawner pair is creative, interesting and useful, but it does not utilize the `auth_state` interface to store information from the Authenticator and pass that to the Spawner. 

A similar (less specific) issue is open on the `wrapspawner` project, here: https://github.com/jupyterhub/wrapspawner/issues/7. I left some remarks there about what I see and why it doesn't appear to me to be possible to use the existing interfaces to accomplish what I described. 

I have attempted to directly block and obtain the result of the Future returned from `User.get_auth_state`, but I was unsuccessful in doing so. I tried:
1. `self.user.get_auth_state().result()`, but that doesn't work: `Exception: DummyFuture does not support blocking for results`
2. `IOLoop.current().run_sync(self.user.get_auth_state)`, but that failed with: `RuntimeError: This event loop is already running`

I considered attempting to pass the information (group memberships) between Authenticator and Spawner through some other route. In the issue on `wrapspawner` I pointed out that `Authenticator.pre_spawn_start` and `Spawner.pre_spawn_hook` are both called after the `Spawner.options_form` has been rendered. Furthermore, I don't see an existing place in the interfaces that will be durable across restarts (if the timing of one of the two `pre_spawn_*` hooks was correct, I believe it could be used to pass state in-memory, but that it would not be durable across restarts). 

Based on this investigation, it appears to me that the only option is to change the interface of `Spawner.options_form` to be async (return a Future), and to introduce `yield` to the call-sites that invoke it. This does not appear to be a massive change, but it also does not seem trivial. I'm also unsure as to whether `Traitlets` properties can return Futures, or whether the change to async will require converting `options_form` away from `Traitlets`.

Have I missed something? Is there some other way to access `auth_state` from `options_form`? Is there some less invasive (localized) way to allow `options_form` to retrieve `auth_state`?

**Comment by minrk** [comment]
If we want auth_state as an input to options_form, I think we are going to have to introduce a new async API for getting the options form (e.g. `async def get_options_form(self): ...`) with a default that simply returns `self.options_form`. I think that's probably the right thing to do, as there have been several similar requests for dynamic, if not async, options form creation.

**Comment by emmanuel** [comment]
I'm glad that you agree with my understanding. I will introduce a PR that introduces the proposed API change.

One question: should I attempt to implement the new `get_options_form` method as a Traitlet property? I assume not, but please correct me if I'm wrong.

**Comment by minrk** [comment]
@emmanuel your PR works just fine. I think making get_options_form itself a callable config option vs allowing options_form to be callable is a tough choice to make, and I don't have a strong opinion. I'll let your PR decide, as you've implemented it!
