### ISSUE TITLE
Unable to run JupyterHub as a service on CentOS 7

### ISSUE THREAD

**Issue by mrkjones1979** [jupyterhub/jupyterhub#1685]
Hi

I am setting up Jupyterhub on a CentOS 7 server and I am having problems getting it to run as a service.  I can launch it fine from the command line (I am running everything as root at the minute as this is a test server - once I get everything running as root then I'll try and run it as a less priviledged user) but when running it as a service I am getting Connection reset by peer errors.

I am using Anaconda3 for Python and Jupyter Notebook.

Here are the files I think are relevant, I have redacted usernames, domains and IP addresses.

Here is the clean log from when I successfully run the command manually (jupyterhub --debug):

> [I 2018-02-27 11:55:15.245 JupyterHub app:834] Loading cookie_secret from /opt/jupyterhub/jupyterhub_cookie_secret
> [D 2018-02-27 11:55:15.245 JupyterHub app:886] Connecting to db: sqlite:////opt/jupyterhub/jupyterhub.sqlite
> [D 2018-02-27 11:55:15.267 JupyterHub orm:504] database schema version found: 3ec6993fe20c
> [I 2018-02-27 11:55:15.296 JupyterHub app:983] Not using whitelist. Any authenticated user will be allowed.
> [D 2018-02-27 11:55:15.313 JupyterHub user:184] Creating <class 'jupyterhub.spawner.LocalProcessSpawner'> for m.j@mycompany.local:
> [D 2018-02-27 11:55:15.314 JupyterHub app:1211] Loading state for m.j@mycompany.local from db
> [D 2018-02-27 11:55:15.315 JupyterHub app:1236] m.j@mycompany.local not running
> [D 2018-02-27 11:55:15.317 JupyterHub user:184] Creating <class 'jupyterhub.spawner.LocalProcessSpawner'> for m.j@mycompany.co.uk:
> [D 2018-02-27 11:55:15.319 JupyterHub app:1211] Loading state for m.j@mycompany.co.uk from db
> [D 2018-02-27 11:55:15.319 JupyterHub app:1236] m.j@mycompany.co.uk not running
> [D 2018-02-27 11:55:15.322 JupyterHub user:184] Creating <class 'jupyterhub.spawner.LocalProcessSpawner'> for j.d@mycompany.co.uk:
> [D 2018-02-27 11:55:15.323 JupyterHub app:1211] Loading state for j.d@mycompany.co.uk from db
> [D 2018-02-27 11:55:15.323 JupyterHub app:1236] j.d@mycompany.co.uk not running
> [D 2018-02-27 11:55:15.325 JupyterHub app:1241] Loaded users: 
>     m.j@mycompany.local
>     m.j@mycompany.co.uk admin
>     j.d@mycompany.co.uk
> [I 2018-02-27 11:55:15.331 JupyterHub app:1528] Hub API listening on http://127.0.0.1:8081/hub/
> [W 2018-02-27 11:55:15.332 JupyterHub proxy:415] 
>     Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
>     Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
>     
> [I 2018-02-27 11:55:15.333 JupyterHub proxy:458] Starting proxy @ https://192.X.Y.92:443/
> [D 2018-02-27 11:55:15.333 JupyterHub proxy:459] Proxy cmd: ['configurable-http-proxy', '--ip', '192.X.Y.92', '--port', '443', '--api-ip', '127.0.0.1', '--api-port', '8001', '--error-target', 'http://127.0.0.1:8081/hub/error', '--ssl-key', '/opt/jupyterhub/ssl/private_key.key', '--ssl-cert', '/opt/jupyterhub/ssl/certificate.crt']
> [D 2018-02-27 11:55:16.180 JupyterHub proxy:491] Proxy started and appears to be up
> [D 2018-02-27 11:55:16.183 JupyterHub proxy:552] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
> [W 2018-02-27 11:55:16.207 JupyterHub proxy:304] Adding missing default route
> [I 2018-02-27 11:55:16.207 JupyterHub proxy:370] Adding default route for Hub: / => http://127.0.0.1:8081
> [D 2018-02-27 11:55:16.207 JupyterHub proxy:552] Proxy: Fetching POST http://127.0.0.1:8001/api/routes/
> [I 2018-02-27 11:55:16.219 JupyterHub app:1581] JupyterHub is now running at https://192.X.Y.92:443/
> [I 2018-02-27 11:55:22.604 JupyterHub log:122] 200 GET /hub/login (@192.168.27.97) 49.63ms
> [I 2018-02-27 11:55:26.220 JupyterHub app:1399] Cleaning up single-user servers...
> [I 2018-02-27 11:55:26.221 JupyterHub proxy:496] Cleaning up proxy[3007]...
> [I 2018-02-27 11:55:26.222 JupyterHub app:1431] ...done

and here is the log when I try and run it as a service (systemctl start jupyterhub):

> [I 2018-02-27 11:53:53.226 JupyterHub app:834] Loading cookie_secret from /opt/jupyterhub/jupyterhub_cookie_secret
> [D 2018-02-27 11:53:53.227 JupyterHub app:886] Connecting to db: sqlite:////opt/jupyterhub/jupyterhub.sqlite
> [D 2018-02-27 11:53:53.247 JupyterHub orm:504] database schema version found: 3ec6993fe20c
> [I 2018-02-27 11:53:53.276 JupyterHub app:983] Not using whitelist. Any authenticated user will be allowed.
> [D 2018-02-27 11:53:53.338 JupyterHub user:184] Creating <class 'jupyterhub.spawner.LocalProcessSpawner'> for m.j@mycompany.local:
> [D 2018-02-27 11:53:53.341 JupyterHub app:1211] Loading state for m.j@mycompany.local from db
> [D 2018-02-27 11:53:53.342 JupyterHub app:1236] m.j@mycompany.local not running
> [D 2018-02-27 11:53:53.347 JupyterHub user:184] Creating <class 'jupyterhub.spawner.LocalProcessSpawner'> for m.j@mycompany.co.uk:
> [D 2018-02-27 11:53:53.354 JupyterHub app:1211] Loading state for m.j@mycompany.co.uk from db
> [W 2018-02-27 11:53:53.354 JupyterHub app:1231] m.j@mycompany.co.uk appears to have stopped while the Hub was down
> [D 2018-02-27 11:53:53.366 JupyterHub user:184] Creating <class 'jupyterhub.spawner.LocalProcessSpawner'> for j.d@mycompany.co.uk:
> [D 2018-02-27 11:53:53.369 JupyterHub app:1211] Loading state for j.d@mycompany.co.uk from db
> [D 2018-02-27 11:53:53.369 JupyterHub app:1236] j.d@mycompany.co.uk not running
> [D 2018-02-27 11:53:53.371 JupyterHub app:1241] Loaded users: 
>     m.j@mycompany.local
>     m.j@mycompany.co.uk admin
>     j.d@mycompany.co.uk
> [I 2018-02-27 11:53:53.383 JupyterHub app:1528] Hub API listening on http://127.0.0.1:8081/hub/
> [W 2018-02-27 11:53:53.385 JupyterHub proxy:415] 
>     Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
>     Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
>     
> [I 2018-02-27 11:53:53.385 JupyterHub proxy:458] Starting proxy @ https://192.X.Y.92:443/
> [D 2018-02-27 11:53:53.386 JupyterHub proxy:459] Proxy cmd: ['configurable-http-proxy', '--ip', '192.X.Y.92', '--port', '443', '--api-ip', '127.0.0.1', '--api-port', '8001', '--error-target', 'http://127.0.0.1:8081/hub/error', '--ssl-key', '/opt/jupyterhub/ssl/private_key.key', '--ssl-cert', '/opt/jupyterhub/ssl/certificate.crt']
> [D 2018-02-27 11:53:54.362 JupyterHub proxy:491] Proxy started and appears to be up
> [D 2018-02-27 11:53:54.365 JupyterHub proxy:552] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
> [E 2018-02-27 11:53:54.371 JupyterHub app:1623]
>     Traceback (most recent call last):
>       File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/app.py", line 1621, in launch_instance_async
>         yield self.start()
>       File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/app.py", line 1569, in start
>         yield self.proxy.check_routes(self.users, self._service_map)
>       File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/proxy.py", line 294, in check_routes
>         routes = yield self.get_all_routes()
>       File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/proxy.py", line 589, in get_all_routes
>         resp = yield self.api_request('', client=client)
>     tornado.curl_httpclient.CurlError: HTTP 599: Recv failure: Connection reset by peer
>     
> [D 2018-02-27 11:53:54.374 JupyterHub application:647] Exiting application: jupyterhub

Here is the systemd service config file:

> [Unit]
> Description=Jupyterhub
> 
> [Service]
> User=root
> Environment="PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/anaconda3/bin"
> ExecStart=/opt/anaconda3/bin/jupyterhub -f /opt/jupyterhub/jupyterhub_config.py --debug
> 
> [Install]
> WantedBy=multi-user.target

Here is my jupyterhub_config.py:

> # Configuration file for jupyterhub.
> 
> #------------------------------------------------------------------------------
> # JupyterHub(Application) configuration
> #------------------------------------------------------------------------------
> 
> ## File in which to store the cookie secret.
> c.JupyterHub.cookie_secret_file = '/opt/jupyterhub/jupyterhub_cookie_secret'
> 
> ## url for the database. e.g. `sqlite:///jupyterhub.sqlite`
> c.JupyterHub.db_url = '/opt/jupyterhub/jupyterhub.sqlite'
> 
> ## Send JupyterHub's logs to this file.
> #  
> #  This will *only* include the logs of the Hub itself, not the logs of the proxy
> #  or any single-user servers.
> c.JupyterHub.extra_log_file = '/opt/jupyterhub/jupyterhub.log'
> 
> ## The public facing ip of the whole application (the proxy)
> c.JupyterHub.ip = '192.X.Y.92'
> 
> ## Specify path to a logo image to override the Jupyter logo in the banner.
> c.JupyterHub.logo_file = '/opt/jupyterhub/mycompany_logo.png'
> 
> ## The public facing port of the proxy
> c.JupyterHub.port = 443
> 
> ## Path to SSL certificate file for the public facing interface of the proxy
> #  
> #  When setting this, you should also set ssl_key
> c.JupyterHub.ssl_cert = '/opt/jupyterhub/ssl/certificate.crt'
> 
> ## Path to SSL key file for the public facing interface of the proxy
> #  
> #  When setting this, you should also set ssl_cert
> c.JupyterHub.ssl_key = '/opt/jupyterhub/ssl/private_key.key'
> 
> #------------------------------------------------------------------------------
> # Authenticator(LoggingConfigurable) configuration
> #------------------------------------------------------------------------------
> 
> ## Base class for implementing an authentication provider for JupyterHub
> 
> ## Set of users that will have admin rights on this JupyterHub.
> #  
> #  Admin users have extra privileges:
> #   - Use the admin panel to see list of users logged in
> #   - Add / remove users in some authenticators
> #   - Restart / halt the hub
> #   - Start / stop users' single-user servers
> #   - Can access each individual users' single-user server (if configured)
> #  
> #  Admin access should be treated the same way root access is.
> #  
> #  Defaults to an empty set, in which case no user has admin access.
> c.Authenticator.admin_users = {'m.j@mycompany.co.uk'}

I have checked and all ports are allowed on firewalld, so I'm stumped.  When I run the command manually everything works a dream, apart from the fact I have to leave my terminal connected so that anyone can use it!

I suspect this is a network / permissions issue rather than anything with Jupyterhub but I would be very grateful of any assistance.

Many thanks,
Mark

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻.
