### ISSUE TITLE
External OAuth Client unable to access API

### ISSUE THREAD

**Issue by brospars** [jupyterhub/jupyterhub#1686]
Hi,
So I'm testing the recently merged "enable external oauth client" but unfortunately my oauth client is unable to access the API after retrieving the token and is being redirected to the login page (see logs below).

**How to reproduce the issue**
I am using my self hosted Gitlab as an external oauth client

**What you expected to happen**
The API request to  `/jupyterhub/hub/api/user` with oauth token should be able to retrieve the user info.

**What actually happens**
The request is being redirected to the login page

**Share what version of JupyterHub you are using** : latest

Jupyterhub logs

```
jupyterhub | [I 2018-02-27 16:18:07.927 JupyterHub log:124] 302 GET /jupyterhub/hub/api/oauth2/authorize?client_id=gitlab-oauth&redirect_uri=http%3A%2F%2Fhost.domain%2Fgitlab%2Fusers%2Fauth%2FJupyterhub%2Fcallback&response_type=code&state=[state] -> http://host.domain/gitlab/users/auth/Jupyterhub/callback?code=[code]&state=[state] ([user]@194.199.19.22) 14.87ms
jupyterhub | [I 2018-02-27 16:18:08.108 JupyterHub log:124] 200 POST /jupyterhub/hub/api/oauth2/token (@172.18.0.1) 40.60ms
jupyterhub | [I 2018-02-27 16:18:08.134 JupyterHub log:124] 302 GET /jupyterhub/hub/api/user -> /jupyterhub/hub/login?next=%2Fjupyterhub%2Fhub%2Fapi%2Fuser (@172.18.0.1) 4.79ms
jupyterhub | [I 2018-02-27 16:18:08.143 JupyterHub log:124] 302 GET /jupyterhub/hub/login?next=%2Fjupyterhub%2Fhub%2Fapi%2Fuser -> /jupyterhub/hub/lti/launch?next=%2Fjupyterhub%2Fhub%2Fapi%2Fuser (@172.18.0.1) 2.19ms
jupyterhub | [W 2018-02-27 16:18:08.205 JupyterHub log:124] 405 GET /jupyterhub/hub/lti/launch?next=%2Fjupyterhub%2Fhub%2Fapi%2Fuser (@172.18.0.1) 53.75ms
```

Am I missing something ?

**Comment by minrk** [comment]
Can you show how you are making the `/api/user` requests?

**Comment by minrk** [comment]
I added a 'basic' example of external oauth and found the bug you are probably hitting! Identifying oauth tokens with /api/user won't work until #1687 is merged.
