### ISSUE TITLE
[Question] Why doesn't the Quickstart guide mention required root privileges?

### ISSUE THREAD

**Issue by chack05** [jupyterhub/jupyterhub#1689]
This is about [this](https://jupyterhub.readthedocs.io/en/latest/quickstart.html) documentation.
After naming sudo in `sudo apt-get install npm nodejs-legacy` I supposed the guide would mention sudo when required. However that is not the case, it is missing in the actual installation steps, which leads to packages being installed in a user-specific directory instead of /usr/local/bin, which leads to being unable to starting the notebook for multiple users.

Is there some specific policy behind this? For example, I've seen some places that don't want to encourage using sudo unless required, but I don't see how it can't be avoided in this case.

**Comment by manics** [comment]
As far as I kniow this should work.
