### ISSUE TITLE
JupyterHub (or proxy) sometimes times out even under light load

### ISSUE THREAD

**Issue by athornton** [jupyterhub/jupyterhub#1690]
Hi! Thanks for using JupyterHub.

If you are reporting an issue with JupyterHub:

- Please use the [GitHub issue](https://github.com/jupyterhub/jupyterhub/issues)
  search feature to check if your issue has been asked already. If it has,
  please add your comments to the existing issue.

- Where applicable, please fill out the details below to help us troubleshoot
  the issue that you are facing. Please be as thorough as you are able to
  provide details on the issue.

**How to reproduce the issue**

Wish I knew.  Sometimes, even under light load, Hub in a container goes unresponsive and I get a 502 back from the nginx layer.

**What you expected to happen**

To see the login screen in my browser.

**What actually happens**

I get a 502 from nginx.

**Share what version of JupyterHub you are using**

0.9.0.dev

Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.

```

[root@jld-hub-747c5cf6b8-6kz5x /]# jupyter troubleshoot
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
$PATH:
	/usr/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin

sys.path:
	/usr/bin
	/usr/lib64/python34.zip
	/usr/lib64/python3.4
	/usr/lib64/python3.4/plat-linux
	/usr/lib64/python3.4/lib-dynload
	/usr/lib64/python3.4/site-packages
	/usr/lib/python3.4/site-packages

sys.executable:
	/usr/bin/python3.4

sys.version:
	3.4.5 (default, Dec 11 2017, 14:22:24)
	[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

platform.platform():
	Linux-4.4.86+-x86_64-with-centos-7.4.1708-Core

pip list:
	alembic (0.9.7)
	asn1crypto (0.24.0)
	backports-abc (0.5)
	bleach (2.1.2)
	cachetools (2.0.1)
	certifi (2018.1.18)
	cffi (1.11.4)
	chardet (3.0.4)
	cryptography (2.1.4)
	decorator (4.2.1)
	entrypoints (0.2.3)
	escapism (1.0.0)
	google-auth (1.3.0)
	html5lib (1.0.1)
	idna (2.6)
	ipaddress (1.0.19)
	ipykernel (4.8.0)
	ipython (6.2.1)
	ipython-genutils (0.2.0)
	jedi (0.11.1)
	Jinja2 (2.10)
	jsonschema (2.6.0)
	jupyter-client (5.2.2)
	jupyter-core (4.4.0)
	jupyterhub (0.9.0.dev0)
	jupyterhub-kubespawner (0.8.1)
	jupyterlab (0.31.1)
	jupyterlab-launcher (0.10.2)
	kubernetes (3.0.0)
	Mako (1.0.7)
	MarkupSafe (1.0)
	mistune (0.8.3)
	nbconvert (5.3.1)
	nbformat (4.4.0)
	notebook (5.3.1)
	oauthenticator (0.8.0.dev0)
	pamela (0.3.0)
	pandocfilters (1.4.2)
	parso (0.1.1)
	pexpect (4.3.1)
	pickleshare (0.7.4)
	pip (9.0.1)
	prometheus-client (0.1.1)
	prompt-toolkit (1.0.15)
	ptyprocess (0.5.2)
	pyasn1 (0.4.2)
	pyasn1-modules (0.2.1)
	pycparser (2.18)
	pycurl (7.43.0.1)
	Pygments (2.2.0)
	python-dateutil (2.6.1)
	python-editor (1.0.3)
	python-oauth2 (1.0.1)
	PyYAML (3.12)
	pyzmq (16.0.4)
	requests (2.18.4)
	rsa (3.4.2)
	Send2Trash (1.4.2)
	setuptools (38.4.0)
	simplegeneric (0.8.1)
	six (1.11.0)
	SQLAlchemy (1.2.2)
	terminado (0.8.1)
	testpath (0.3.1)
	tornado (4.5.3)
	traitlets (4.3.2)
	typing (3.6.2)
	urllib3 (1.22)
	wcwidth (0.1.7)
	webencodings (0.5.1)
	websocket-client (0.40.0)
	wheel (0.30.0)

```

** Some additional debugging notes and output...

This problem only appears intermittently.  It seems to clear itself after a little while.  I have fewer than 20 users hitting the hub when it happens.

nginx gives me errors like:
```
2018/02/28 18:24:27 [error] 21#21: *233179 upstream prematurely closed connection while reading response header from upstream, client: 10.128.0.26, server: sysengdemo.lsst.codes, request: "GET /user/simonkrughoff/api/sessions?1519842147875 HTTP/2.0", upstream: "http://10.39.243.248:8000/user/simonkrughoff/api/sessions?1519842147875", host: "sysengdemo.lsst.codes", referrer: "https://sysengdemo.lsst.codes/user/simonkrughoff/lab?redirects=1"
```

There aren't errors in the Hub logs.  Doing `curl -L -vvv http://localhost:8000` eventually returns a login screen but may take several minutes to do so.  I have not yet been able to hit port 8001 while the problem is manifesting itself to see whether it is the hub or the proxy.

It seems to be worse under heavier load: if users abandon their sessions and their backend containers are killed, so that their browser continually spams looking for a container that isn't there, this seems to happen more frequently.  That's anecdotal at this point though.

The container limits and requests are:

```
    Limits:
      cpu:     2
      memory:  2G
    Requests:
      cpu:     800m
      memory:  1G
```

Which should be plenty.  The host is 2vCPU, 7.5GB.  Nginx has its timeouts set at:

```
  proxy_read_timeout         300s;
  proxy_send_timeout         300s;
```

and is using default 75s for server keepalive.  SOMAXCONN on the Hub is 128, which isn't great but should be enough for this kind of load.

**Comment by minrk** [comment]
Isolating whether it's the Hub or the proxy does seem like it will be helpful. Identifying the memory and/or CPU usage of the two processes would probably be helpful.

If you want to do a relatively destructive action, you could kill the hub with SIGINT and see if the stack points somewhere useful. I'm working on adding a SIGINFO handler in #1694, which would let you print the stack at any time, which might be helpful for situations like this.

**Comment by athornton** [comment]
If I kill the hub with SIGINT, the container will just cease to exist, since Hub is PID 1 in the container.  However, if I set the DEBUG variable, then PID executes Hub and then sleeps for 600 seconds after Hub finishes before exiting, so I could take that approach.

A SIGINFO handler would also be appreciated.

Getting memory and CPU usage is a little tough because of containerization.  I'll see what I can do although the data may be suspect.

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!
