### ISSUE TITLE
Permission failure after start server

### ISSUE THREAD

**Issue by zeusal** [jupyterhub/jupyterhub#1697]
Hi!

I'm using jupyterhub with dockerspawned and I have a problem.

When I access the URL and identify myself with the corresponding user, starts the docker container but the following message is displayed.

> 
> 500 : Internal Server Error
> 
> The error was:
> 
> Permission failure checking authorization, I may need to be restarted

Docker log:

`{"log":"[I 2018-03-02 12:45:43.253 jupyterhub log:47] 302 GET /user/jupyterhub/ (10.x.y.z) 0.43ms\n","stream":"stderr","time":"2018-03-02T12:45:43.253393965Z"}
{"log":"[E 2018-03-02 12:45:43.318 jupyterhub jupyterhub-singleuser:69] I don't have permission to verify cookies, my auth token may have expired: [403] Forbidden\n","stream":"stderr","time":"2018-03-02T12:45:43.318252793Z"}
{"log":"[W 2018-03-02 12:45:43.318 jupyterhub web:1521] 500 GET /user/jupyterhub/tree (10.x.y.z): Permission failure checking authorization, I may need to be restarted\n","stream":"stderr","time":"2018-03-02T12:45:43.318546252Z"}
{"log":"[E 2018-03-02 12:45:43.319 jupyterhub log:46] {\n","stream":"stderr","time":"2018-03-02T12:45:43.319453098Z"}
{"log":"      \"Accept-Encoding\": \"gzip, deflate\",\n","stream":"stderr","time":"2018-03-02T12:45:43.319461034Z"}
{"log":"      \"Accept-Language\": \"es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3\",\n","stream":"stderr","time":"2018-03-02T12:45:43.319465651Z"}
{"log":"      \"Upgrade-Insecure-Requests\": \"1\",\n","stream":"stderr","time":"2018-03-02T12:45:43.319469893Z"}
{"log":"      \"X-Forwarded-Port\": \"44004\",\n","stream":"stderr","time":"2018-03-02T12:45:43.319473892Z"}
{"log":"      \"Host\": \"HOST:PORT\",\n","stream":"stderr","time":"2018-03-02T12:45:43.319478538Z"}
{"log":"      \"X-Forwarded-Proto\": \"http\",\n","stream":"stderr","time":"2018-03-02T12:45:43.319482717Z"}
{"log":"      \"Connection\": \"close\",\n","stream":"stderr","time":"2018-03-02T12:45:43.319486853Z"}
{"log":"      \"X-Forwarded-For\": \"10.x.y.z\",\n","stream":"stderr","time":"2018-03-02T12:45:43.319490628Z"}
{"log":"      \"Referer\": \"http://URL:44004/hub/home\",\n","stream":"stderr","time":"2018-03-02T12:45:43.319494893Z"}
{"log":"      \"User-Agent\": \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0\",\n","stream":"stderr","time":"2018-03-02T12:45:43.319498847Z"}
{"log":"      \"Accept\": \"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\",\n","stream":"stderr","time":"2018-03-02T12:45:43.319502655Z"}
{"log":"      \"Cookie\": \"jupyter-hub-token-jupyterhub=\\\"2|1:0|10:1519994743|32:jupyter-hub-token-jupyterhub|44:N2EzYjllZGZkOWNjNGZjZGEwZGU2NGY3MWJiNzlhZmM=|de340c465aa4b901eb8f16095b09c013cf2a6fc78e3314f8b40a5ddda00b6c6a\\\"\"\n","stream":"stderr","time":"2018-03-02T12:45:43.319506792Z"}
{"log":"    }\n","stream":"stderr","time":"2018-03-02T12:45:43.319511233Z"}
{"log":"[E 2018-03-02 12:45:43.319 jupyterhub log:47] 500 GET /user/jupyterhub/tree (10.x.y.z) 5.68ms referer=http://URL:PORT/hub/home\n","stream":"stderr","time":"2018-03-02T12:45:43.319736646Z"}`

Jupyterhub log:

`[D 2018-03-02 13:59:24.014 JupyterHub dockerspawner:346] Getting container 'jupyter-jupyterhub-custom'
[D 2018-03-02 13:59:24.018 JupyterHub dockerspawner:332] Container 2df07b9 status: {'Dead': False,
     'Error': '',
     'ExitCode': 0,
     'FinishedAt': '2018-03-02T12:44:58.108925824Z',
     'OOMKilled': False,
     'Paused': False,
     'Pid': 4959,
     'Restarting': False,
     'Running': True,
     'StartedAt': '2018-03-02T12:45:22.13897586Z'}
[D 2018-03-02 13:59:24.019 JupyterHub base:226] Setting cookie for jupyterhub: jupyter-hub-token-jupyterhub, {}
[D 2018-03-02 13:59:24.019 JupyterHub base:226] Setting cookie for jupyterhub: jupyter-hub-token, {}
[I 2018-03-02 13:59:24.022 JupyterHub log:100] 302 POST /hub/login?next=%2Fhub%2Fhome (@10.x.y.z) 17.66ms
[I 2018-03-02 13:59:24.022 JupyterHub login:79] User logged in: jupyterhub
13:59:24.069 - debug: [ConfigProxy] PROXY WEB /hub/home to http://10.x.y.b:PORT
[I 2018-03-02 13:59:24.078 JupyterHub log:100] 200 GET /hub/home (jupyterhub@10.x.y.z) 5.39ms
13:59:24.180 - debug: [ConfigProxy] PROXY WEB /favicon.ico to http://10.x.y.b:PORT
[D 2018-03-02 13:59:24.181 JupyterHub log:100] 304 GET /favicon.ico (@10.x.y.z) 0.59ms
13:59:28.261 - debug: [ConfigProxy] PROXY WEB /hub/user/jupyterhub/ to http://10.x.y.b:PORT
[D 2018-03-02 13:59:28.266 JupyterHub dockerspawner:346] Getting container 'jupyter-jupyterhub-custom'
[D 2018-03-02 13:59:28.270 JupyterHub dockerspawner:332] Container 2df07b9 status: {'Dead': False,
     'Error': '',
     'ExitCode': 0,
     'FinishedAt': '2018-03-02T12:44:58.108925824Z',
     'OOMKilled': False,
     'Paused': False,
     'Pid': 4959,
     'Restarting': False,
     'Running': True,
     'StartedAt': '2018-03-02T12:45:22.13897586Z'}
[D 2018-03-02 13:59:28.271 JupyterHub base:226] Setting cookie for jupyterhub: jupyter-hub-token-jupyterhub, {}
[I 2018-03-02 13:59:28.276 JupyterHub log:100] 302 GET /hub/user/jupyterhub/ (jupyterhub@10.x.y.z) 9.92ms
13:59:28.326 - debug: [ConfigProxy] PROXY WEB /user/jupyterhub/ to http://127.0.0.1:8900
13:59:28.382 - debug: [ConfigProxy] PROXY WEB /user/jupyterhub/tree to http://127.0.0.1:8900
[W 2018-03-02 13:59:28.388 JupyterHub base:32] Blocking API request with no referer
[W 2018-03-02 13:59:28.388 JupyterHub log:100] 403 GET /hub/api/authorizations/cookie/jupyter-hub-token-jupyterhub/[secret] (@10.x.y.b) 1.74ms
13:59:28.489 - debug: [ConfigProxy] PROXY WEB /user/jupyterhub/custom/custom.css to http://127.0.0.1:8900
13:59:28.551 - debug: [ConfigProxy] PROXY WEB /favicon.ico to http://10.x.y.b:PORT
[D 2018-03-02 13:59:28.553 JupyterHub log:100] 304 GET /favicon.ico (@10.x.y.z) 0.57ms
`

Any ideas? Can I restore the cookie or token without deleting the container?

Kind Regards

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
