### ISSUE TITLE
FreeIPA authentication support?

### ISSUE THREAD

**Issue by phibya** [jupyterhub/jupyterhub#1698]
Hi,

I am trying to install Jupyterhub on an Ubuntu server (16.04) that uses FreeIPA for authentication. Is there any support for FreeIPA ready?

**Comment by minrk** [comment]
I don't believe one exists already, but implementing a [custom authenticator](https://jupyterhub.readthedocs.io/en/latest/reference/authenticators.html#additional-authenticators) is usually not too much work if your authentication service is well documented. Feel free to ask further questions here about implementing a FreeIPAAuthenticator

**Comment by cmseal** [comment]
@hungbya You can use FreeIPA with the LDAP authenticator.  Hope this helps!

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
