### ISSUE TITLE
Update CircleCI config to 2.0

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#1699]
CircleCI, which we use to test our docker builds, has updated its config spec to 2.0. We should update our circleci config to 2.0, following [this guide](https://circleci.com/docs/2.0/migrating-from-1-2/) .

**Comment by glenak1911** [comment]
@minrk I'd like to take a stab at this.

**Comment by minrk** [comment]
@glenak1911 great! Feel free to ask questions here or on gitter if you have them.

**Comment by glenak1911** [comment]
@minrk Thanks! I've followed the Contributors Guide, as well as the mentioned documentation, and I've submitted PR #1720 for review. I'd like to test this out, but I'm not sure how to go about doing that. Any pointers would be helpful!
