### ISSUE TITLE
Public interfacing for sharing, etc.

### ISSUE THREAD

**Issue by dsblank** [jupyterhub/jupyterhub#17]
Sorry that I got cut off from the ipython-dev discussion this afternoon... my house lost internet access.

Anyway, I'll make some notes here about the public/sharing aspects of the jupyterhub:

The public handler should be able to:
1. render as html
2. give json of .ipynb
3. allow downloading .ipynb
4. allow copying from public directory to a logged in user's space

Here is a prototype of some of the ideas:

https://gist.github.com/dsblank/29fb53ff27966268208a

Basically:
- any file in /home/USER/Public/ is shared as /public/USER/
- does a directory listing if no file is requested
- serves any file in Public (zip files, images, whatever)
- default view is raw json
- can get different versions:
  - /public/USER/file.ipynb?copy
  - /public/USER/file.ipynb?download
  - /public/USER/file.ipynb?view
- no security here (allows ".." in paths)
- not sure how to handle requests for .css, .js, etc.

IPython priorities, from my perspective:
1. logout
2. sharing/distributing files to class

I have some other aspects I need to wrestle with (how do they get a kernel installed easily, how do they get some nbextensions), but that is mostly me figuring out details to instruct the class).

**Comment by boveylisi2013** [comment]
Agree. I totally hope a logged-in user can access the public files. Now, I try to read file stored in hdfs. It always try to search in the /user/myuser folder. I really hope it can get rid of the prefix which is automatically appended on.

**Comment by yuvipanda** [comment]
@dsblank your gist is 404 :) can you share any work you've done in this area? I too would like this to happen for my installation.

**Comment by yuvipanda** [comment]
I'm not sure if this should be implemented in jupyterhub itself or as a separate app. Thoughts?

**Comment by dsblank** [comment]
Here is the older gist:

https://gist.github.com/dsblank/73f5b1f812559bb99b68

and a more developed version:

https://github.com/dsblank/jupyter.brynmawr/tree/master/jupyterhub

**Comment by yuvipanda** [comment]
@dsblank that looks awesome. Do you think there's a way something similar can be merged upstream?

**Comment by minrk** [comment]
Yes, I think we do want to provide a version of this. The question is how do we do it with the current abstractions, where the Hub doesn't know anything about the single-user files. @dsblank's implementation makes convenient assumptions about the filesystem for their deployment that we can't make in general. So we need a mechanism for single-user servers to publish notebooks to the Hub, and for the Hub to store them somewhere.

If this can be done as a separate 'sharing service', I think that would be ideal, perhaps as a peer to Spawner and Authenticator.

**Comment by ssanderson** [comment]
> So we need a mechanism for single-user servers to publish notebooks to the Hub, and for the Hub to store them somewhere.

@minrk we did this on Quantopian as a server extension to the single-user servers; we add custom javascript to add a "share notebook" button that makes a post to an extra handler that runs on each single-user server.  Our implementation then uploads straight to S3, but you could forward it to the Hub easily enough if you wanted local storage.

cc @TimShawver who worked on most of this in our codebase.

**Comment by yuvipanda** [comment]
I'm experimenting with https://github.com/yuvipanda/nbserve which has a pluggable 'url to file resource' mapper, which maps something like 'YuviPanda/TeaHouse.ipynb' to '/data/project/paws/YuviPanda/public/TeaHouse.ipynb'.

**Comment by willingc** [comment]
A development note: Sharing is currently being discussed in the jupyterhub/hubshare repo https://github.com/jupyterhub/hubshare/issues/14

@minrk and others Do you mind if we close this issue on this repo and move discussions to hubshare?

**Comment by minrk** [comment]
Sure, I think that's appropriate

**Comment by willingc** [comment]
Closing this issue. Please continue discussion on sharing to https://github.com/jupyterhub/hubshare/issues/14
