### ISSUE TITLE
EnvironmentLocationNotFound

### ISSUE THREAD

**Issue by ZenRay** [jupyterhub/jupyterhub#1701]
The error reports, when I click the `conda` tab button. 
The info like that:

Error

---
	An error occurred while retrieving installed packages.
	`EnvironmentLocationNotFound: Not a conda environment: /Users/username/anaconda3/envs/anaconda3`

In the realty, I don't create the env about anaconda3. And I find that there is not anaconda3 directory in the directory `/Users/username/anaconda3/envs/`

#### The version of JupyterHub
My version is `4.4.0`

#### troubleshoot info

```
$PATH:
	/Users/username/anaconda3/bin
	/Users/username/.cargo/bin
	/Users/username/anaconda3/bin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin
	/Library/TeX/texbin

sys.path:
	/Users/username/anaconda3/bin
	/Users/username/anaconda3/lib/python36.zip
	/Users/username/anaconda3/lib/python3.6
	/Users/username/anaconda3/lib/python3.6/lib-dynload
	/Users/username/anaconda3/lib/python3.6/site-packages
	/Users/username/anaconda3/lib/python3.6/site-packages/aeosa

sys.executable:
	/Users/username/anaconda3/bin/python

sys.version:
	3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 12:04:33)
	[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

platform.platform():
	Darwin-17.4.0-x86_64-i386-64bit

which -a jupyter:
	/Users/username/anaconda3/bin/jupyter
	/Users/username/anaconda3/bin/jupyter
```

**Comment by minrk** [comment]
This seems like a bug in either the nb_conda_kernels package or its configuration. Are you using jupyterhub, or the regular Jupyter notebook server? There is no jupyterhub version 4.4 (latest is 0.8.1). Try including the full `conda list` package list. What is `conda env list`?

My guess is you should open an Issue on https://github.com/Anaconda-Platform/nb_conda_kernels

**Comment by ZenRay** [comment]
Yes, I made a mistake about the software. I check the env by using `conda env list`, but there is not `/Users/username/anaconda3/envs/anaconda3`. I'll post an issue on your link. Thank you very much.

**Comment by willingc** [comment]
Closing this issue as it seems it will be handled in the nb_conda_kernels repo. Thanks @ZenRay and @minrk.

**Comment by tjd2002** [comment]
You've hit this bug, it's actually in the nb_conda extension, not the nb_conda_kernels:
https://github.com/Anaconda-Platform/nb_conda/issues/66
