### ISSUE TITLE
Where are the JupyterHub logo files?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/jupyterhub#1703]
Is there a place where we have different versions of the JupyterHub logo? I know that https://github.com/jupyter/design exists but I didn't see anything specific to JupyterHub in there

**Comment by willingc** [comment]
Adding @tgeorgeux to the discussion (in case you have some). I think @minrk had a logo too.

**Comment by tgeorgeux** [comment]
I don't have any handy, but I'll track them down and upload them to the repo.

**Comment by choldgraf** [comment]
thanks! I really like the logo and wanna make sure I have a hi-res one for presentations :-)

**Comment by choldgraf** [comment]
ping @tgeorgeux , do we have logos for JupyterHub? (and while I'm at it, do we have logos for JupyterLab as well?)

**Comment by tgeorgeux** [comment]
The closest we have to and 'official' logo for hub is this one:
https://jupyterhub.readthedocs.io/en/stable/_static/logo.png (to my
knowledge). JupyterLab doesn't have a sanctioned Logo, the guerilla version
we've been using in the gitter channel directly violates our own brand
guidelines (as does the hub one I linked). But those brand guidelines are
OK to be changed, we just need to put in the work to change them.

**Comment by consideRatio** [comment]
What about this one?
https://jupyter.org/assets/hublogo.svg

**Comment by choldgraf** [comment]
ah yep - I think that's the vector version of the one @tgeorgeux linked above. Thanks for finding it @consideRatio ! It sounds like these will be updated sometime soon but in the meantime I'll use this one.

**Comment by willingc** [comment]
Closing as we have located the logo.

**Comment by smitooned** [comment]
The link shared by @consideRatio is no more accessible. Would you know where this is moved ?

**Comment by minrk** [comment]
The logo in the docs can be found [here](https://github.com/jupyterhub/jupyterhub/blob/5.3.0/docs/source/_static/images/logo/logo.png), or the logo used at runtime is [here](https://github.com/jupyterhub/jupyterhub/blob/5.3.0/share/jupyterhub/static/images/jupyterhub-80.png).

**Comment by smitooned** [comment]
@minrk Thanks for sharing the link. 

Actually I was looking for dark mode logo as JupyterHub now is available w/ dark mode. 

However, the  links shared above are referring to light mode logo. Also, these are PNGs, if I get vectors(.svgs) I can create a dark mode logo using Jupyter guidelines.

Created a community thread [here](https://discourse.jupyter.org/t/jupyterhub-logo-in-dark-mode/35299?u=smitooned)

**Comment by smitooned** [comment]
That's great, this is what I was looking for. Thanks a lot. 
Hoping this gets added as officially in the Jupyterhub repo soon too.
