### ISSUE TITLE
Allow services to retrieve auth_state

### ISSUE THREAD

**Issue by brospars** [jupyterhub/jupyterhub#1704]
Hi ! 
I use Jupyterhub as a mean of authentication for other services and I store some user infos in `auth_state` (username, email, access, etc).
So it could be really useful to allow services to retrieve `auth_state` to get this extra data.

**Comment by summerswallow** [comment]
Alternatively, you could allow augmented user information in the user model passed back by the API. Currently, it does not provide any mechanism for additional user information to be available to services.

**Comment by betatim** [comment]
I'd like to be able to access the `auth_state` from a service/via the API as well. What do people think of modifying the User handler approximately like so:
```python
 class UserAPIHandler(APIHandler):
     @gen.coroutine
     @admin_or_self
     def get(self, name):
         user = self.find_user(name)
         auth = yield user.get_auth_state()
         user = self.user_model(user)
         user['auth_state'] = auth
         self.log.info("user", user)
         self.write(json.dumps(user))
```

with a corresponding change in `post` to allow services to update the auth state.

**Comment by summerswallow** [comment]
If there a security concerns perhaps you can keep two sets of augmented user information: auth_state which doesn't leave the host and is for secure stuff and user_info which is accessible during authentication and via API.

**Comment by 1kastner** [comment]
At https://github.com/jupyterhub/jupyterhub-idle-culler/issues/8 @manics and I discussed that maybe adding more information could be helpful for other purposes as well. Specifically, it could be interesting to include the [state object of the server](https://jupyterhub.readthedocs.io/en/stable/_static/rest-api/index.html#/definitions/Server) that helps to automate services such as removing docker volumes of users that haven't used a JupyterHub for a long time. At https://discourse.jupyter.org/t/a-cull-idle-user-service-that-deletes-pvs/4742/10 different use case scenarios are described when the administrators might want to use such a service. This would mean that the response object in auth_state would be more than just the user, but also parts of the user's server-specific (Docker, k8s, vanilla, ...) configuration.

**Comment by manics** [comment]
Thanks @bitnik for pointing out this is already possible https://github.com/jupyterhub/jupyterhub/blob/76c9111d80660e93578f80dbe441cfb702c1b207/jupyterhub/apihandlers/users.py#L126-L138

**Comment by 1kastner** [comment]
Thank you very much @manics for showing this connection!
