### ISSUE TITLE
Remote Service uses SSL  certificate chain that has been signed using a cryptographically weak hashing algorithm

### ISSUE THREAD

**Issue by javin-gn** [jupyterhub/jupyterhub#1707]
Hi,

We have run jupyterhub as a remote behind a proxy (nginx) and run a penetration test. The test tool feedback that the Remote Service uses SSL  certificate chain that has been signed using a cryptographically weak hashing algorithm (e.g. MD2, MD4, MD5, SHA-2)

We have use a self-signed certificate to run jupyterhub on SSL. We use the same self signed certificate on another remote service which the tool never flag out the issue. We believe that the Self-signed certificate should have no issue.

We generate the self signed certificate using the step below:

1. Generate RSA private key without passphrase:
openssl genrsa -out privkey.pem 2048

2. Create self-signed cert from the private key:
openssl req -new -x509 -key privkey.pem -out server-cert.pem -days 1095

We are using RHEL7

Will appreciate your help in shedding some light on this.

Thanks :)

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
