### ISSUE TITLE
cull_users with a different timeout

### ISSUE THREAD

**Issue by gsemet** [jupyterhub/jupyterhub#1708]
If cull_users is given to cull_idle_servers.py, it basically use the same timeout value. I am wondering if a different timeout can be meaningful. For example, after 1 hours, unused servers are closed, after 7 days, innactive users get deleted.

**Comment by rkdarst** [comment]
If you are interested in this, can you comment on pull request #1834 ?  We are trying to see if this is still useful or excess complexity.

**Comment by willingc** [comment]
Closing as #1834 and #1841 have been merged. 👍
