### ISSUE TITLE
Could not upgrade form jupyterhub 0.7.2 to jupyterhub 0.8.1

### ISSUE THREAD

**Issue by farassadek** [jupyterhub/jupyterhub#1710]
Hi, 

At Harvard we wrote a jupyterhub spawner that spawn a jupyter EC2 instance per user.

Basically jupyterhub manager spawn an EC2 instance for the user and run jupyter process on that instance, and route back to the user .

- Here is the github link to the ec2-per-user jupyterhub system that being used at Harvard: https://github.com/harvard/cloudJHub and,
- here is the `jupyterhub_config.py`: https://github.com/harvard/cloudJHub/blob/master/jupyterhub_files/jupyterhub_config.py
and 
- the spawner:  https://github.com/harvard/cloudJHub/blob/master/jupyterhub_files/spawner.py

The spawner  spin up a new instance for the user (or start the user instance if the user already has one), then it run jupyterhub-singleuser command on the EC2 instance, something like this

`JUPYTERHUB_API_TOKEN=11004827088143958ef350e709462a81  /usr/bin/python3 /usr/local/bin/jupyterhub-singleuser --user="farassadek" --cookie-name="jupyter-hub-token-farassadek" --base-url="/user/farassadek" --hub-host="" --hub-prefix="/hub/" --hub-api-url=http://10.10.10.10:8081/hub/api --ip=10.10.22.22 --port=4444  --allow-root`

Where  10.10.10.10 is Jupyterhub Manager IP, and 10.10.22.22 is the user's EC2 instance IP.

## The problem
When I try to upgrade to jupyterHub 0.8.1 the system breaks. 
It is the OAuth JUPYTERHUB_CLIENT_ID and JUPYTERHUB_OAUTH_CALLBACK_URL. 
If the JUPYTERHUB_CLIENT_ID is not in  jupyterhub-singleuser, then (on the user EC2) I get the following error : 
```
  File "/usr/local/lib/python3.5/dist-packages/jupyterhub/services/auth.py", line 439, in _ensure_not_empty
    raise ValueError("%s cannot be empty." % proposal.trait.name)
ValueError: oauth_client_id cannot be empty.
```

If I add JUPYTERHUB_CLIENT_ID to jupyterhub-single, then jupyterhub-singleuser process will run on the EC2 instance. But the manager can not route to it, with an oauth call back error. 

Note that we wrote our authentication module to authenticate user through canvas. Therefore we don't use OAuth (that make the problem) and we don't need it.  

Let me know if I need to provide more details please.
Your help is much appreciated.

Faras Sadek

**Comment by willingc** [comment]
Hi @farassadek,

There were significant changes between 0.7.2 and 0.8.1 especially with authentication. Here is the changelog which has more specifics: https://github.com/jupyterhub/jupyterhub/blob/master/docs/source/changelog.md#changelog

Pinging @minrk who wrote the OAuth handling for JupyterHub for additional guidance.

**Comment by farassadek** [comment]
thanks @willingc. 
@minrk any help on this please

**Comment by farassadek** [comment]
I found the solution
 thanks

**Comment by farassadek** [comment]
solved

**Comment by leinad87** [comment]
It's a good practice to share the solution, sometimes is useful for other ;)
