### ISSUE TITLE
jupyterhub upgrade-db fails due to SQLite limitations

### ISSUE THREAD

**Issue by taschini** [jupyterhub/jupyterhub#1711]
The alembic migration 1cebaf56856c -> 56cc5a70207e fails due to the
[create_foreign_key](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/alembic/versions/56cc5a70207e_token_tracking.py#L27) statements, and SQLite does not support adding a foreign key constraint to an existing column, apparently.

```
[I 2018-03-09 09:26:51.060 JupyterHub dbutil:125] Upgrading sqlite:///data/jupyterhub.sqlite
[I 2018-03-09 09:26:51.061 JupyterHub dbutil:105] Backing up data/jupyterhub.sqlite => data/jupyterhub.sqlite.2018-03-09-092651
[I 2018-03-09 09:26:51.417 alembic.runtime.migration migration:117] Context impl SQLiteImpl.
[I 2018-03-09 09:26:51.418 alembic.runtime.migration migration:122] Will assume non-transactional DDL.
[I 2018-03-09 09:26:51.421 alembic.runtime.migration migration:327] Running upgrade 1cebaf56856c -> 56cc5a70207e, token tracking

Traceback (most recent call last):
  File "/opt/conda/bin/alembic", line 11, in <module>
...
  File "/opt/conda/lib/python3.5/site-packages/jupyterhub/alembic/versions/56cc5a70207e_token_tracking.py", line 27, in upgrade
    op.create_foreign_key(None, 'oauth_access_tokens', 'oauth_clients', ['client_id'], ['identifier'], ondelete='CASCADE')
...
  File "/opt/conda/lib/python3.5/site-packages/alembic/ddl/sqlite.py", line 34, in add_constraint
    "No support for ALTER of constraints in SQLite dialect")
NotImplementedError: No support for ALTER of constraints in SQLite dialect
```

**Comment by amit1rrr** [comment]
I am facing the same issue as well.

**Comment by amit1rrr** [comment]
From the docs, upgrade-db may not work with sqlite. I just deleted the jupyterhub.sqlite file & the new db got created next time I ran jupyterhub. All sorted now.

Source: http://jupyterhub.readthedocs.io/en/latest/reference/upgrading.html

**Comment by willingc** [comment]
We should test this as part of the 0.8 to future 0.9 upgrade.

**Comment by minrk** [comment]
This is fixed and tested now. The constraint is not added during the upgrade, but the resulting database still works.

**Comment by taschini** [comment]
Confirmed, thank you!
