### ISSUE TITLE
Unable to successfully authenticate (apparently?)

### ISSUE THREAD

**Issue by p5a0u9l** [jupyterhub/jupyterhub#1713]
Hello all, 

I have installed to Ubuntu 17 using a variety of methods from the docs (docker, bare-metal..) in each case I encounter the same problem. My host PC has two NICs, one on a small private LAN and one connected to corporate LAN. When I start jupyterhub and attempt to login from a separate machine on the private LAN, it authenticates my user with PAM and opens up my home directory, that is, everything works. When I try to login using the IP on the corporate LAN, the server process spawns jupyterhub-singleuser as if everything worked, but in the browser it simply redirects me to /hub/login with no other information. I am not using SSL if that helps...

thank oyu

**Comment by willingc** [comment]
Hi @p5a0u9l,

Sorry this initial question wasn't answered here. Hopefully, you received an answer on Gitter.

I'm going to go ahead and close this but if you still have the issue, please let me know and I will be happy to reopen it :sunny:
