### ISSUE TITLE
Loading html template for google tagging not working.

### ISSUE THREAD

**Issue by sigurdurb** [jupyterhub/jupyterhub#1714]
I want to insert a google tracker for my jupyterhub website.
So far I have put the content for that into /etc/jupyter/templates/page.html file like it is located in the jupyterhub-deploy-teaching [repo, see code here](https://github.com/jupyterhub/jupyterhub-deploy-teaching/blob/dd0bf98649bc35e8f06ca1b58dac7290f80e9d9a/roles/jupyterhub/tasks/googleanalytics.yml)
`jupyter --paths` shows that /etc/jupyter is one of the config dirs.

But I don't see any tracking activity in any of the sites for jupyterhub, like the /user /home /hub/login or any other path.
And searching for it in the Inspector does not reveal anything, so it is like it is simply not being loaded.
How do I go about getting this to work ?

This is the content of page.html, ive changed the tracker id.
```
{% extends "templates/page.html" %}
{% block script %}
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-12345-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-12345-1');
</script>

{% endblock %}

```

This is my server setup:
```Ubuntu 16.04
jupyterhub version 0.8.1
notebook version 5.4.0
jupyter version 4.4.0
nbgrader version 0.6.0.dev (Also referred to as Formgrader)
```
-----
EDIT:
I ended up putting the google tracker into the  `<head>` of the
/opt/conda/share/jupyter/hub/templates/page.html
which takes care of the /hub/* paths

and
/opt/conda/lib/python3.5/site-packages/notebook/templates/page.html
which takes care of the /user/* and /services/* paths.

It works, but it would be better if it would work as an external config.

**Comment by willingc** [comment]
I'm closing this issue and tagging as reference for future ideas.
