### ISSUE TITLE
Please integrate jupyterhub into Debian

### ISSUE THREAD

**Issue by picca** [jupyterhub/jupyterhub#1715]
Hello,

It would be great if you could  integrate jupyterhub into Debian.
It is really important to be able to maintain on a long term the full system stack (system, sofware, devices drivers like OpenCL, etc...) and providing distribution packages, seems to be the prefer way to achive this.

`apt-get dist-upgrade`

thanks for considering.

Frederic

**Comment by ryanlovett** [comment]
Someone [has requested](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=848023) that jupyterhub be packaged for Debian.

Until then you can use one of many [JupyterHub containers](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=jupyterhub&starCount=0) including [jupyter/jupyterhub](https://hub.docker.com/r/jupyter/jupyterhub/) which is based on Debian.

**Comment by minrk** [comment]
It is rare for package authors to be maintainers of debian packages, so the place to ask probalby isn't here, but rather at debian (e.g. in the request Ryan linked). If someone would like to package jupyterhub for debian, that would be great!
