### ISSUE TITLE
Get path to current notebook via Python

### ISSUE THREAD

**Issue by joshtemple** [jupyterhub/jupyterhub#1718]
I would like to be able to obtain the path to my current notebook using only Python (not Javascript) and set it to a variable.

There are a few solutions to this issue for Jupyter Notebook [here](https://github.com/jupyter/notebook/issues/1000), but the pure Python implementation doesn't work in JupyterHub as the response from `list_running_servers` is different on JupyterHub.

**Comment by joshtemple** [comment]
I was able to get my notebook path like this:

```
import requests
import ipykernel
import re
from notebook.notebookapp import list_running_servers

TOKEN = *Insert JupyterHub API token here*

base_url = next(list_running_servers())['url']
r = requests.get(
    url=base_url + 'api/sessions',
    headers={'Authorization': 'token {}'.format(TOKEN),})

r.raise_for_status()
response = r.json()

kernel_id = re.search('kernel-(.*).json', ipykernel.connect.get_connection_file()).group(1)
notebook_path = {r['kernel']['id']: r['notebook']['path'] for r in response}[kernel_id]

print(notebook_path)
```

**Comment by marcinwrochna** [comment]
The TOKEN may be retrieved from `os.environ['JUPYTERHUB_API_TOKEN']` when run from a notebook inside JupyterHub.
