### ISSUE TITLE
Can JupyterHub admin communicate directly with Notebook servers

### ISSUE THREAD

**Issue by tgamal** [jupyterhub/jupyterhub#1719]
If I am the admin of JupyterHub , I can use JupyterHub REST API but is it possible that I use this [notebook server API](https://github.com/jupyter/jupyter/wiki/Jupyter-Notebook-Server-API) to POST notebooks or GET the content of user notebooks. I want to auto-generate some notebook and post it to a specific user.  

it is similar to [this question](https://github.com/jupyterhub/jupyterhub/issues/518)

**Comment by minrk** [comment]
Yes, if you have enabled admin-access, tokens for admin users will be permitted to access single-user servers.
