### ISSUE TITLE
Update user's auth state from a running notebook server

### ISSUE THREAD

**Issue by betatim** [jupyterhub/jupyterhub#1724]
I have a hub where we forward the oauth2 token from the login to the user's notebook server ([like so](https://github.com/jupyterhub/oauthenticator/blob/master/examples/auth_state/jupyterhub_config.py)). There they can use it to make auth'ed requests to a few services.

My question is what do others do to keep the token that the notebook server has fresh? The oauth2 token is only valid for ~24h which is much shorter than the "logout time" for the hub (14days by default?).

Right now I have a nb server extension that periodically refreshes the token but as soon as you do that the auth state that the hub has is outdated (the oauth refresh token there becomes invalid). So I am thinking of writing a hub service that the nbserver extension can talk to. Once it refreshes the tokens it then uses the service to update what the hub's user object contains.

But this sounds quite convoluted so wondering what others do in this situation.

**Comment by elgalu** [comment]
+1 I'm facing the exact same use case in our corporate auth system.

**Comment by minrk** [comment]
How are you refresh the user tokens? The last time I read about refresh tokens, they required client_secret, which meant they could only be done from the Hub environment.

**Comment by elgalu** [comment]
For untrusted single page apps one can have only client_id

**Comment by betatim** [comment]
The notebook extension talks to a service started by the hub. The service has the required secrets. The idea is that the service gets the new token from the OAuth source and then stores them in the auth state maintained by the hub.

**Comment by anmtan** [comment]
Hi @betatim, If I understand correctly, the auth state can be updated by implement "refresh_user" in the authenticator. That gets called periodically by the hub. So the auth state will be updated in the database. However, how do I get the latest auth state from notebook server?

My use case is to have the OAuth accessToken in the notebook server (either environment variable or any way to pull from DB) I've already used pre_spawn_start hook to put the initial accessToken in the notebook server environment variable. That will be expired in 30 min or so. I am not sure how to update the environment variable with the latest accessToken.
