### ISSUE TITLE
This is not an issue but the question as I don't know where to put the question.

### ISSUE THREAD

**Issue by hassanmudassir-rzt** [jupyterhub/jupyterhub#1725]
I have a web application which has its own authentication for the users. Now I need to integrate Jupyter Hub with my application where for each of the user who logs into my application need to get separate Jupyter Notebook session. I need to use Jupyter Hub for that. Here I don't want to use Jupyter-Hub's Authentication. I may pass user details such as the username (and/or user ID) and my application auth token to Jupyter-Hub. Now Jupyter-Hub should spawn the Jupyter Notebook session for the user who logged in(If already spawned give me the same instance). Is that possible to do this, If yes How can I do that? If no, Any Alternate solution for this.

@minrk @willingc

**Comment by elgalu** [comment]
Hi, yes this is all possible plus this info is in the documentation:
http://jupyterhub.readthedocs.io/en/latest/reference/authenticators.html?highlight=authentication
 
```
JupyterHub’s OAuthenticator currently supports the following popular services:

Auth0
Bitbucket
CILogon
GitHub
GitLab
Globus
Google
MediaWiki
Okpy
OpenShift
A generic implementation, which you can use for OAuth authentication with any provider, is also available.
```
