### ISSUE TITLE
Jupyter crashes with 500 server error

### ISSUE THREAD

**Issue by ernestmartinez** [jupyterhub/jupyterhub#1727]
I am running on bare metal with ceph

I have been able to up until 2 days ago to manually create a PV and then be able to spawn a Jupyter notebook. I have attached syslog from the kubernetes-worker node.

Linux gpu 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Docker version 17.12.1-ce, build 7390fc6

When I spawn using the default values a PVC is created and it attaches to the PV that I had previously created. I have been unsuccessful in getting a default storage class to work. Eventually the jupyter-admin POD gets created and then it crashes. This started happening yesterday with no changes to my deployment since the last time it did work. I have noticed that it stopped working once the spawner form got drop down picks for the image.

Near the bottom of the attached log, at line 90995 you will see the following:
jupyterhub-sing[75273] trap invalid opcode ip:7f1493653040

This is where it crashes.

(https://github.com/jupyterhub/jupyterhub/files/1819837/syslog.txt)

```

**Comment by ernestmartinez** [comment]
I was able to resolve by dropping namespace and re-deploying kubeflow-core

**Comment by ernestmartinez** [comment]
I finally got default storage class to work, and jupyter successfully launches a PVC and mounts a PV. But I'm still getting the server 500 error with the same error in the logs:

traps: jupyterhub-sing[46603] trap invalid opcode ip:7fa997150cee sp:7ffcf28e0110 error:0 in libtensorflow_framework.so[7fa996cfb000+c72000]

**Comment by ernestmartinez** [comment]
Seems to be working now.

**Comment by minrk** [comment]
Does that mean there's still an issue, or can we close?

**Comment by ernestmartinez** [comment]
This one can be closed
