### ISSUE TITLE
Cannot use matplot libs

### ISSUE THREAD

**Issue by ernestmartinez** [jupyterhub/jupyterhub#1728]
When I try to run any notebooks with plots I get:

/opt/conda/lib/python3.6/site-packages/matplotlib/style/core.py:92: MatplotlibDeprecationWarning: The is_string_like function was deprecated in version 2.1.
  if cbook.is_string_like(style) or hasattr(style, 'keys'):
/opt/conda/lib/python3.6/site-packages/matplotlib/style/core.py:99: MatplotlibDeprecationWarning: The is_string_like function was deprecated in version 2.1.
  if not cbook.is_string_like(style):

and

AttributeError: module 'matplotlib.cbook' has no attribute 'popall'

From what I have read its is caused by multiple matplotlib version installed.
[jupyter.txt](https://github.com/jupyterhub/jupyterhub/files/1820264/jupyter.txt)

**Comment by ernestmartinez** [comment]
The problem lies in the default images in the spawner. I used the jupyter/tensorflow-notebook and it works fine.

**Comment by minrk** [comment]
What image were you using?

**Comment by ernestmartinez** [comment]
`![image](https://user-images.githubusercontent.com/28981612/37833356-72359de4-2e81-11e8-966d-dec60bfccbfb.png)`

**Comment by willingc** [comment]
Hi @ernestmartinez, If this is still an issue for you, please file it with the Kubeflow project [here](https://github.com/kubeflow/kubeflow)
