### ISSUE TITLE
Correct Syntax for --Spawner.args for Sudospawner

### ISSUE THREAD

**Issue by roemer2201** [jupyterhub/jupyterhub#1735]
Hi All,

I was trying the last to two hours to pass some arguments to sudospawned jupyter-singleuser processes. I tried a lot of different versions, but was not successful. Can you please give me two examples, one with one option + argument and a second one with two options and an argument each?

To give you an idea what I'm doing, here is my launch commandline (interesting part comes at the end):

    su - jupytermanager -c "jupyterhub --ip 192.168.0.x --JupyterHub.spawner_class=sudospawner.SudoSpawner --PAMAuthenticator.open_sessions=True --PAMAuthenticator.service=jupyterhub --ssl-key ~/cert/jupyterhubtest_privkey_unenc.pem --ssl-cert ~/cert/cert.pem --port 443 --Spawner.args=['--SingleUserNotebookApp.shutdown_no_activity_timeout=3600']"

And here is the actual error:

    ...
          File "/opt/jupytermanager/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 1524, in error
        raise TraitError(e)
    traitlets.traitlets.TraitError: The 'args' trait of a SudoSpawner instance must be a list, but a value of class 'str' (i.e. '[--SingleUserNotebookApp.shutdown_no_activity_timeout=3600]') was specified.

Thank you in advance!

Update 1: Specifying --LocalProcessSpawner.args instead does result in the same error.

**Comment by minrk** [comment]
Specifying list traits on the command-line is not well supported. I would recommend using a config file for that.

I think this is what you need, though:

`--Spawner.args="['--SingleUserNotebookApp.shutdown_no_activity_timeout=3600']"`

(i.e. you need to make sure that your quotes don't get interpreted by the shell, but rather get actually passed through to the Python program). This is doubly tricky when using something like su, where there can be multiple layers of shell interpretation.

Even better would be to put that config in /etc/jupyter/jupyter_notebook_config.py:

```python
c.SingleUserNotebookApp.shutdown_no_activity_timeout = 3600
```

**Comment by roemer2201** [comment]
Dear minrk,

thank you for your answer, it helped solving the problem. This is the command line I can use successfully:

    su - jupytermanager -c "jupyterhub ..... --Spawner.args=\"['--SingleUserNotebookApp.shutdown_no_activity_timeout=3600']\""

Regarding your hint about the config file: Do all instances of the different jupyterhub executables read configuration from the users home directories (~/.jupyter) as well as central central configuration under /etc/jupyter? If so, what setting is prefered if the same config is set with different values in both files?

**Comment by minrk** [comment]
~/.jupyter config files are loaded *by default*, but can be disabled if --disable-user-config is specified. /etc/jupyter config files are always loaded. But `SingleUserNotebookApp` will only affect the JupyterHub case because when individual users launch their notebooks they are `NotebookApp` instances, not `SingleUserNotebookApp` instances.
