### ISSUE TITLE
How to give the passwords for external users?

### ISSUE THREAD

**Issue by wtsyang** [jupyterhub/jupyterhub#1742]
I want to let external users to login my jupyterhub.
I have successfully login into the jupyterhub with my Root's password, and my jupyterhub works well.
But, I have a question about how to make external users to login. 
I knew to add usernames into whitelist.
But, how to set the passwords for them. 
Is it something about tokens?
I am a beginner. 
Thanks

**Comment by minrk** [comment]
JupyterHub offers no mechanism of password or user management. It exclusively links to *external* sources of users and passwords, such as the host system or an account provider such as GitHub, Google, or LDAP.

If you are running on a traditional system with users and passwords, you can create the users following standard user creation steps on the system and they will become available to JupyterHub.

Alternately, you can defer to an external service, e.g. GitHub via OAuth, and map those onto users of the system (or in containers).

**Comment by wtsyang** [comment]
Thank you very much!
I solved this problem by creating another user account in Linux.

**Comment by robomotic** [comment]
If you are using the local linux PAM module you could tell the user to run this command from the notebook:

`! echo "username:newpass"|chpasswd
`
