### ISSUE TITLE
Redirect notebook dir to S3 

### ISSUE THREAD

**Issue by anasos** [jupyterhub/jupyterhub#1744]
Hi
I'm using jupyterhub with an EC2 instance. What i really want now is to put my code in a S3 bucket.
My jupyterhub_config looks like:

```
from oauthenticator.google import GoogleOAuthenticator
c.JupyterHub.authenticator_class = GoogleOAuthenticator
c.GoogleOAuthenticator.oauth_callback_url = "http://ec2-*********:8000/hub/oauth_callback"
c.GoogleOAuthenticator.client_id = "**********"
c.GoogleOAuthenticator.client_secret = "Vn****************"

c.NotebookApp.contents_manager_class = 's3contents.S3ContentsManager'
c.S3ContentsManager.bucket_name = 'bucket_name'
c.S3ContentsManager.prefix = '/notebooks'
```
I found nothing in my S3 bucket . Did i do something wrong ? and what is the meaning of the params c.S3ContentsManager.prefix.

Thanks for the help.

**Comment by anasos** [comment]
I don't have any folder /etc/jupyter i have 2 different locations of jupyter folder 

```
/usr/local/etc/jupyter
/usr/local/share/jupyter
```
which one should i use. 

Thanks again

**Comment by minrk** [comment]
That means that the class couldn't be imported. Is it installed in the env where users will run? Is the import string correct?

**Comment by anasos** [comment]
Thanks @minrk , I passed the params as String that was the mistake.

**Comment by willingc** [comment]
@anasos This looks as if it is resolved so I'm closing. :sunny:
