### ISSUE TITLE
Proxy.check_routes causing performance issue

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#1754]
It's possible that there's a performance issue in check_routes. On investigating why we have some launch failures in Binder, I found that they correlated with windows of the Hub being nonresponsive for several seconds (often 7-10):

<img width="1031" alt="screen shot 2018-03-27 at 10 57 24" src="https://user-images.githubusercontent.com/151929/37957325-f056f0a4-31ad-11e8-909b-55442c408fb9.png">

The "Deleting stale routes" messages tell me (though not with 100% confidence) that we are in Proxy.check_routes, which could have a performance issue because it is a database lookup that checks all users and running spawners.

We need to profile this, because the recent startup optimizations may well have already alleviated the issue.

**Comment by minrk** [comment]
I ran some profiling based on the [startup perf tests](https://github.com/minrk/jupyterhub-startup-perf) and couldn't get check_routes to take more than 250 milliseconds with 5k users even on 0.8.1, so I'm not quite sure how it could take 7-10 seconds with 100-200 users like we have on mybinder.org. With 100 active users, I'm seeing check_routes take closer to 5-6 milliseconds, so I'm not quite sure what could be up. This may be correlated with #1753 where the issue only occurs for the case where check_routes and cull-idle are occurring concurrently.

**Comment by forbxy** [comment]
jupyterhub run in only one process，so if many user request check_Oauth,home page or other handler, check_routes will be slowly
