### ISSUE TITLE
Embed JupyterHub in a Java Web app and Authentication

### ISSUE THREAD

**Issue by ankit2894** [jupyterhub/jupyterhub#1756]
Hi Team,
I want to embed jupyterhub to my java web application so that users can use there own instance of jupyter notebook.The challenge is that i wish to use the login credentials of used in my application for jupyterhub login too. Please suggest me the way out!!!

**Comment by elgalu** [comment]
It's in the docs [How to write a custom authenticator](http://jupyterhub.readthedocs.io/en/latest/reference/authenticators.html#how-to-write-a-custom-authenticator)

BTW "Hi team," is not a proper issue name xD

**Comment by willingc** [comment]
Hello @ankit2894,

Thanks for the question. I recommend taking a look at the documentation on Authenticators and the linked section above.

**Comment by powerLeePlus** [comment]
@ankit2894 
Have you solved the problem？？
