### ISSUE TITLE
Using the JupyterHub API purely to provision notebook servers without the UI

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/jupyterhub#1758]
At the recent Paris / Orsay JupyterHub meeting @nthiery was asking if there's a way to just use the JupyterHub as a way to request notebook servers for users (that could then be handled via some other UI etc).

I don't remember if this conversation went anywhere, but I'm mentioning it here to see if there's a clean answer to this. In addition I'll paste his text below, but perhaps @nthiery or @minrk can jump in and explain better than I (or delete if this has already been discussed!)

<details>
<summary>His original message about this</summary>
I (Nicolas) have spent a good part of the workshop rambling on how to
empower users of JupyterHub to build their own features on top of it,
with minimal dependency on JupyterHub devs or admins.
E.g. could a web site (e.g. a course management system) use jupyterhub
as a just web-service for provisionning notebook servers.
This could help grow an ecosystem, in the same vein as the ecosystem
that grew around github (slack, RTD, Travis, ...).

I had a specific use case in mind: how to empower teachers to setup
infrastructure for their classes/students with minimal action from the
JupyterHub instance admins.

JupyterHub has a rich [API](http://jupyterhub.readthedocs.io/en/latest/api/)
which gives access to most actions. So that sounds like a good basis to work from.
However, with reasons, most of the api requests require either special priviledges (being
authenticated, being admin), and more importantly take important actions on behalf of
the user. Hence the need to protect from forged URL's from malicious sites.
In practice, cross-site checking is enabled by default, preventing an untrusted site
outside of the jupyterhub instance to make direct calls to its API. Enabling such API calls
would require to somehow explicitely register the site in jupyterhub as (partially) trusted,
and grant it special permissions (e.g. using OAuth registration mechanisms).
</details>

Here's the beginning of a proposed API for this. I think that it may also fit with the "Binder functionality within JupyterHub" stuff we've been discussing.

```
# Random notes by NT about the current / would be API
### Connect to an existing server by name

GET: /users/{name}/servers/{server_name}? 

Example: http://jupyter.u-psud.fr/users/nicolas.thiery/mpi-info-111

### Query status of server by name

### Edit existing server configuration

PATCH: /users/{name}/servers/{server_name} ?

### Shutdown server by name

DELETE: /users/{name}/servers/{server_name}? 

### Fetch list of running servers

Use cases:
- as user: give me the list of my servers
- as collaborator: give me the list of servers I have access to
- as teacher of a class, give me the list of my student's server (filtering by the computing environment)

For the servers of a user: GET /users/{name}/servers ?

Result as:
- json
- UI enabling to open/shutdown/edit whitelist when appropriate (as in the current jupyterhub admin page)

### Actions from within a container???

Use case: a user is within a container, and wants to:
- get a url to this server, typically to share with collaborators
- edit the properties of this server (shutdown, edit whitelist, ...)
- mount new volumes

- Recover credentials; use it to mount additional volumes

- Get this server name
- Get url to connect to this server (valid for anyone in the whitelist)
- Get url to connect to this server (valid for anyone with credentials for that jupyterhub)
- Edit this server whitelist

Alternative: get  a URL pointing to a "manage this server" UI that would display all of the above
```

**Comment by betatim** [comment]
The [JupyterHub REST API](http://jupyterhub.readthedocs.io/en/latest/reference/rest.html) covers a few of these things already. I think a lot of the named servers already exists as API but isn't exposed as UI anywhere yet.

The original message points to the API as well but I thought I'd highlight it again.

I think it would help to have one (or more) concrete thing that can't be done with the API. This would help disentangle "documentation needs to be clearer/needs an example" and "needs new functionality".

**Comment by nthiery** [comment]
Thanks @choldgraf for posting this here. For reference, I later wrote a related [blog post](http://opendreamkit.org/2018/03/15/jupyterhub-binder-convergence/): in short, it sounds like many of the use cases could be covered with an enriched binder-style UI.

The question remains for would-be more complex applications. The current API is presumably rich enough. The key point is how to handle privileges: which actions from JupyterHub's API shall the application be allowed to use, or not.

I have no concrete and immediate use cases though. Just exploring what we could eventually want to do with the cool tool that is JupyterHub.

**Comment by dhirschfeld** [comment]
Maybe relevant? https://github.com/jupyter/jupyter_client/pull/308

**Comment by gweis** [comment]
Quite useful in my opinion.

There is one API point missing. GET /users/{name}/server, which would return the list of active servers.

Maybe some admin only endpoint to list all active servers for all users would be good as well. With these two in place, it would be possible to create a service, which could then implement the collaborator / contributor use cases.

Starting new servers via the API is possible, but to build a useful UI, you probably need some sort of spawner options introspection as well. This is currently nowhere accessible via the API. Adding this in, looks like a fairly big change.

**Comment by manics** [comment]
This should be possible now 😄
