### ISSUE TITLE
Running JupyterHub as a system service, Spawner failed to start, can't find logs

### ISSUE THREAD

**Issue by AllenDowney** [jupyterhub/jupyterhub#1759]
When I run JupyterHub from the command line, everything works fine.  Now I want to run it as a system service.  I followed the instructions here: 

https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service

When I start the service, it seems fine:

```
$ sudo service jupyterhub restart
 * Restarting Multi-user server for Jupyter notebooks jupyterhub                                            [ OK ]
```

Then I can connect to the server and log in.  But when I press the "Start my server" button I get 

```
500 : Internal Server Error
Spawner failed to start [status=1].
```

And that's all the information I have so far, because of my other problem: I can't find the logs.  Any idea where jupyterhub is putting logging info?

Thanks!

**Comment by willingc** [comment]
Hi @AllenDowney,

Typically, log files for JupyterHub can be found in `/var/log`.

The [troubleshooting section]( https://jupyterhub.readthedocs.io/en/latest/troubleshooting.html#error-after-spawning-my-single-user-server) covers some common cases for 500 errors. If that doesn't resolve your configuration issue, please do let us know. Thanks.
