### ISSUE TITLE
jupyterhub public IP redirect issue

### ISSUE THREAD

**Issue by Srinivasb0** [jupyterhub/jupyterhub#1763]
I am using Digital Ocean VM with ubuntu 16.04 to deploy jupyterhub as per instruction is given in this link https://github.com/jupyterhub/jupyterhub-tutorial/blob/master/JupyterHub.pdf

Everything went well and jupyterhub is running properly, but when I tried to access through public IP on chrome, it takes a long time and generating the error that site cant be reached. 

Here is the config. please help me to fix this

[I 2018-03-29 13:36:42.479 JupyterHub app:834] Loading cookie_secret from /root/jupyterhub_cookie_secret
[W 2018-03-29 13:36:42.504 JupyterHub app:955] No admin users, admin interface will be unavailable.
[W 2018-03-29 13:36:42.504 JupyterHub app:956] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-03-29 13:36:42.504 JupyterHub app:983] Not using whitelist. Any authenticated user will be allowed.
[I 2018-03-29 13:36:42.538 JupyterHub app:1528] Hub API listening on http://127.0.0.1:8081/hub/
[W 2018-03-29 13:36:42.540 JupyterHub proxy:415] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[I 2018-03-29 13:36:42.541 JupyterHub proxy:458] Starting proxy @ https://*:443/
13:36:42.798 - info: [ConfigProxy] Proxying https://*:443 to (no default)
13:36:42.803 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[W 2018-03-29 13:36:43.492 JupyterHub proxy:304] Adding missing default route
[I 2018-03-29 13:36:43.493 JupyterHub proxy:370] Adding default route for Hub: / => http://127.0.0.1:8081
13:36:43.499 - info: [ConfigProxy] 200 GET /api/routes 
13:36:43.503 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
[I 2018-03-29 13:36:43.505 JupyterHub app:1581] JupyterHub is now running at https://:443/
13:36:43.506 - info: [ConfigProxy] 201 POST /api/routes/

**Comment by betatim** [comment]
Could it be that there are firewall rules in place (at Digital Ocean) that prevent you from connecting to your Digital Ocean instance?

Nothing in the log you posted suggests that JupyterHub saw your request.

**Comment by Srinivasb0** [comment]
@betatim Thank You. It's a configuration issue in the digital ocean. I have to set up a firewall by allowing ssh connections.

sudo ufw allow 443
