### ISSUE TITLE
Improve support for authenticators where the 'login page' is not GETable

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#1766]
For LTI Authenticator, the 'login page' is `/hub/lti/launch`. It expects POST requests here from the LTI Consumer (EdX, canvas, etc). There's no way to get into the hub without going through the LTI Consumer - this is a function of the LTI protocol itself.

So if we log out with LTIAuthenticator, and then click the 'jupyter' logo, we get redirected to the Login URL with a GET, which returns:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1541, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 225, in get
    raise HTTPError(405)
tornado.web.HTTPError: HTTP 405: Method Not Allowed
```

or something similar.

Not sure what the right thing to do here is.

Thanks to @willingc for finding this!

**Comment by brospars** [comment]
Couldn't ltiauthenticator accept GET requests and display a custom page (telling the user to get back to the LTI Tool Consumer) ?

**Comment by manics** [comment]
Is there anything to be done here?

**Comment by manics** [comment]
No response, closing.
