### ISSUE TITLE
proxy.check_routes can call again by timer before the last call stop

### ISSUE THREAD

**Issue by forbxy** [jupyterhub/jupyterhub#1770]
user route add is slow,so if we lost a large number of user's routes，proxy.check_routes will still running in next timer clock.

**Comment by willingc** [comment]
Hi @forbxy, Thanks for the report. Can you provide a bit more detail on this issue? Thanks.

**Comment by willingc** [comment]
@minrk, is this related to #1754 ?

**Comment by forbxy** [comment]
we have 10000 users，and 350 always online, when CHP crash, jupyterhub start new one, and call check_routes to fix routes loss.but the check_routes also registered in a timer. so some time ,2 or 3 check_routes running in one time. I think there should have a lock to make sure one check_routes one time

**Comment by minrk** [comment]
@willingc I believe so, in that a performance issue in check_routes will increase the likelihood of races like this.

>  I think there should have a lock to make sure one check_routes one time

This is a good idea.

I'm curious, though, if CHP crashing is a regular occurrence for you. That seems like an issue to investigate.
