### ISSUE TITLE
 Refusing to run JupyterHub with invalid cookie_secret_file

### ISSUE THREAD

**Issue by Srinivasb0** [jupyterhub/jupyterhub#1787]
Hello,

I installed jupyterhub through conda env create -f environment.yml and activated jupyterhub-tutorial under non-root user, but when I am trying to access jupyterhub it is generating following error.

Refusing to run JupyterHub with invalid cookie_secret_file.

Here is the log file
Loading cookie_secret from /srv/jupyterhub/jupyterhub_cookie_secret
[E 2018-04-10 17:25:47.660 JupyterHub app:634] Refusing to run JupyterHub with invalid cookie_secret_file. /srv/jupyterhub/jupyterhub_cookie_secret error was: cookie_secret_file can be read or written by anybody

Please let me know how i can solve this

**Comment by dhirschfeld** [comment]
If you delete that file before running it should work - jupyterhub will automatically recreate it.
```
rm -f  /srv/jupyterhub/jupyterhub_cookie_secret
```

**Comment by dhirschfeld** [comment]
Sorry, I'm not a linux expert. It looks like a permissions issue so maybe running as sudo would work but I'm not sure that's recommended?

Someone more experienced with linux will have to comment further...

**Comment by minrk** [comment]
@Srinivasb0 I believe this is a permissions issue. You should check the ownership and permissions with:

    ls -la /srv/jupyterhub

The cookie secret file should have permissions like `-rw------`. If it has other permissions, try `chmod 0600 jupyterhub_cookie_secret`. If jupyterhub cannot create files in `/srv/jupyterhub` that's also a problem. This directory should ideally be owned by the user running jupyterhub. It at least needs to be writable by that user.

**Comment by Srinivasb0** [comment]
@minrk thank you. On behalf wasting much time I re-installed the jupyterhub and the problem fixed

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/refusing-to-run-jupyterhub-with-invalid-cookie-secret-file/9809/1
