### ISSUE TITLE
Make culler installable

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#1791]
Summarizing from #1779:

We currently have cull_idle_servers.py as an *example* of consuming the Hub API. But this is common enough functionality that lots of (most?) deployments, including zero-to-jupyterhub, are using it. Since it's only an example script, this means copying the script into your deployment, which is not great.

Our main options are making culling a feature of JupyterHub itself and making the cull-idle-servers service a standalone package. Pros and cons

1. make it part of JupyterHub
   - pro: distributed with jupyterhub, always compatible with jupyterhub
   - pro: could be internal, not a separate process
   - con: cannot distribute fixes or improvements without making jupyterhub releases. We have regularly wanted this.
   - con: cannot be easily modified to provide alternate cull strategies (e.g. additional sources of info)
2. make it a standalone package
   - pro: easy to reuse in multiple places
   - con: another package to maintain/distribute

**Comment by minrk** [comment]
Making it a package would also facilitate testing, which would be nice since this is used in production ~everywhere

**Comment by GeorgianaElena** [comment]
The idle-culler is now a standalone package: https://github.com/jupyterhub/jupyterhub-idle-culler
Thanks @yuvipanda for taking care of this :heart: :sparkles:

Closing this :tada:
