### ISSUE TITLE
can i use jupyter rest api on jupyterhub??

### ISSUE THREAD

**Issue by whitebluecloud** [jupyterhub/jupyterhub#1798]
i want to use jupyter rest-api not jupyterhub rest-api like ‘/content/path/file’.
is available it??

**Comment by minrk** [comment]
yes, you can use the jupyter rest api with a jupyterhub token while your server is running. The URLs are like `/user/your-name/api/contents/...`. Use a jupyterhub token in the `Authorization: token my-secret-token` header.

**Comment by whitebluecloud** [comment]
@minrk Thank you for helping me :+1:
