### ISSUE TITLE
User no need to input password after Github Oauth logout 

### ISSUE THREAD

**Issue by ogre0403** [jupyterhub/jupyterhub#1805]
I follow [OAuthenticator guide](https://github.com/jupyterhub/oauthenticator/tree/master/examples/full)  to setup a dockerized JupyterHub with GitHub OAtuh . If I logout the server and click `Sign in with GitHub` button again, I can access the notebook  without input my usename and password 

I thought this issue is similar to [#1491](https://github.com/jupyterhub/jupyterhub/issues/1491), and this issue should be fixed in master branch.  So I try the master branch, but this issue seems still exist. 

**How to reproduce the issue**
Step 1: 

build jupyterhub docker image from master branch 

```
git clone https://github.com/jupyterhub/jupyterhub.git
cd jupyterhub
docker build -t ogre0403/jupyterhub:oauth .
```

Step 2: 

Use image built in previous step to create another image for OAuth

```
git clone https://github.com/jupyterhub/oauthenticator.git
cd oauthenticator/examples/full/

vim Dockerfile 
...
FROM ogre0403/jupyterhub:oauth
RUN python3 -m pip install oauthenticator notebook
...

docker build -t jupyterhub-oauth .
docker run -it -p 8000:8000 --env-file=env jupyterhub-oauth
```

**What you expected to happen**
After the user logs out, they should input password again to access notebook.

**What actually happens**
After the user logs out, user click `Sign in with GitHub` button and can access notebook without input password. 

**Share what version of JupyterHub you are using**
master branch

**Comment by minrk** [comment]
Indeed, this is because JupyterHub is still authorized with GitHub, so when you oauth with GitHub, since GitHub remembers authorizing this application for this user before, it doesn't show a confirmation dialog. Many websites that oauth with github behave a similar way - after the first login, subsequent 'login with github' will be transparent as they redirect occurs without any prompts.

If the user revokes the authorization on the GitHub side, they will need to enter their password again. Similarly, if the user is not logged in to GitHub at the time, they will need to login to GitHub as part of the oauth process.

**Comment by ogre0403** [comment]
@minrk Thanks for your explanation. So the reason is that user does not revoke their token, and Github still has the authorization. 

I check [logout handler](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/handlers/login.py#L14), and found the default logout handler doesn't revoke the token. I also find [globus logout handler](https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/globus.py#L35) and [keycloak logout handler](https://github.com/matipp/oauthenticator/blob/master/oauthenticator/keycloak.py#L37) overwrite `get()` to revoke token. 

If I want revoke token when user logout, one possible solution is extend the logout handler to revoke token. Is it possible? 

Thanks.

**Comment by minrk** [comment]
Yes, I think adding a logout hook to oauthenticators in general to allow this makes sense.

**Comment by ablekh** [comment]
@minrk Could you clarify your most recent comment above a bit more? Are you talking about introducing a logout hook in core `OAuthenticator` code or in modules specific to corresponding IdPs? If the latter, that would be `keycloak.py`, which is currently missing (@ogre0403's comment above contains a broken link and I could not find any references to `keycloak.py` in Git history), correct? An example implementation code or relevant advice would also be much appreciated.

**Comment by lakshaykc** [comment]
> Indeed, this is because JupyterHub is still authorized with GitHub, so when you oauth with GitHub, since GitHub remembers authorizing this application for this user before, it doesn't show a confirmation dialog. Many websites that oauth with github behave a similar way - after the first login, subsequent 'login with github' will be transparent as they redirect occurs without any prompts.
> 
> If the user revokes the authorization on the GitHub side, they will need to enter their password again. Similarly, if the user is not logged in to GitHub at the time, they will need to login to GitHub as part of the oauth process.

I'm seeing different behavior with GenericOAuthenticator with my custom app. If I'm logged out of my app, I'm still able to login to Jupyterhub notebook server without any sign in or credentials prompt. See my comment on #1497 [here](https://github.com/jupyterhub/jupyterhub/issues/1491#issuecomment-505147378) for more details.

**Comment by manics** [comment]
Closing, as this is related to the Authenticator (e.g. https://github.com/jupyterhub/oauthenticator) and not JupyterHub directly.
