### ISSUE TITLE
rootc++ kernel dead

### ISSUE THREAD

**Issue by mission-young** [jupyterhub/jupyterhub#1818]
I install jupyter, jupyterhub ,root(cern) on my computer. root(cern) is a frame of c++, whose kernel is supported by jupyter. [jupyter kernels](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels)

I can use jupyter with root(cern) normally. But when I try to use jupyterhub with root, it failed. Some error like 'kernel not find' or 'kernel died' appeared.

Anyone had a problem like this before? Thank you!

**Comment by minrk** [comment]
Can you share the output of the process where the kernel died?

The main difference between jupyterhub and jupyter when running locally is either the environment variables (jupyterhub does not pass many environment variables down to the subprocess) or perhaps running with a different Python (check which Python executable jupyterhub runs with and compare to `jupyter notebook`).

**Comment by willingc** [comment]
Closing this issue as it's been inactive for a couple of months. Please leave us a message if you still need assistance. Thanks! 🌻
