### ISSUE TITLE
collaboration for JupyterHub Dynamic Environment Builder

### ISSUE THREAD

**Issue by bitnik** [jupyterhub/jupyterhub#1824]
Hi,

We read [the white paper](https://docs.google.com/document/d/1Nh4ls_H-rCQgDyBH5JTpKPa4peDetnPivgEb0x1Dah0) that you wrote about `dymamic image builder` for JupyterHub and we are very pleased and interested. Because we have been planing to implement (or at least try to do it) a very similar feature for our [ORC project](https://notebooks.gesis.org/) which already hosts Jupyterhub and BinderHub separately.

We wanted to open this issue to let you know that we really like to contribute to this. And also to ask
how should we proceed to make contributions as much as possible?

Thanks a lot for your input and thoughts!

cc @arnim @choldgraf

**Comment by choldgraf** [comment]
First off, ORC looks awesome! So cool that you've got a binderhub working!

Would love to work together on this. Feel free to add comments or thoughts to that paper - these documents are semi-living and updated frequently, and they should have perspective from people who will be using these tools!

**Comment by manics** [comment]
I presume this was resolved by https://notebooks.gesis.org/binder/ 😄
