### ISSUE TITLE
Multiple syntax errors in cull_idle_servers.py

### ISSUE THREAD

**Issue by andreat** [jupyterhub/jupyterhub#1825]
Hi all,

I am trying to use cull_idle_servers.py to cull idle servers. However jupyterhub complains when I try to use it as service, giving multiple syntax errors. I have been able to remove some of them manually, but as soon as "yield" is involved, I have no idea how to proceed.

Note that these errors occur also when cull_idle_servers.py is executed from command line, so this seems to be not really depending on jupyterhub. I am not expert in python; since I am not sure whether the changes I made are correct, I decided to don't make pull requests for them.

In the following the errors I am getting and how I have tried to solve them. 

```
python cull_idle_servers.py
  File "cull_idle_servers.py", line 58
SyntaxError: Non-ASCII character '\xc3' in file cull_idle_servers.py on line 58, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
Solved by replacing `naïve` with `naive`

```
python cull_idle_servers.py
  File "cull_idle_servers.py", line 78
    return f"{h:02}:{m:02}:{seconds:02}"
                                       ^
SyntaxError: invalid syntax
```
Solved by removing `f`

```
python cull_idle_servers.py
  File "cull_idle_servers.py", line 104
    return (yield client.fetch(req))
SyntaxError: 'return' with argument inside generator
```
Solved(?) by splitting `return (yield client.fetch(req))` in two lines: the first for `yield client.fetch(req)` and the second for `return`

```
python cull_idle_servers.py
  File "cull_idle_servers.py", line 189
    resp = yield fetch(req)
SyntaxError: 'return' with argument inside generator
```
At this point I stopped as I have no idea how to proceed.

**Share what version of JupyterHub you are using**

Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.

```
$PATH:
	/usr/local/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games

sys.path:
	/usr/local/bin
	/usr/lib/python35.zip
	/usr/lib/python3.5
	/usr/lib/python3.5/plat-x86_64-linux-gnu
	/usr/lib/python3.5/lib-dynload
	/usr/local/lib/python3.5/dist-packages
	/usr/lib/python3/dist-packages

sys.executable:
	/usr/bin/python3

sys.version:
	3.5.2 (default, Nov 23 2017, 16:37:01) 
	[GCC 5.4.0 20160609]

platform.platform():
	Linux-4.4.0-119-generic-x86_64-with-Ubuntu-16.04-xenial

which -a jupyter:
	/usr/local/bin/jupyter
	/usr/local/bin/jupyter

pip list:
	alembic (0.9.9)
	backcall (0.1.0)
	bleach (2.1.3)
	chardet (2.3.0)
	command-not-found (0.3)
	decorator (4.3.0)
	docker (3.2.1)
	docker-pycreds (0.2.2)
	dockerspawner (0.9.1)
	entrypoints (0.2.3)
	escapism (1.0.0)
	html5lib (1.0.1)
	ipykernel (4.8.2)
	ipython (6.3.1)
	ipython-genutils (0.2.0)
	ipywidgets (7.2.1)
	jedi (0.12.0)
	Jinja2 (2.10)
	jsonschema (2.6.0)
	jupyter (1.0.0)
	jupyter-client (5.2.3)
	jupyter-console (5.2.0)
	jupyter-core (4.4.0)
	jupyterhub (0.8.1)
	jupyterhub-tmpauthenticator (0.5)
	language-selector (0.1)
	Mako (1.0.7)
	MarkupSafe (1.0)
	mistune (0.8.3)
	nbconvert (5.3.1)
	nbformat (4.4.0)
	netifaces (0.10.6)
	notebook (5.4.1)
	pamela (0.3.0)
	pandocfilters (1.4.2)
	parso (0.2.0)
	pexpect (4.5.0)
	pickleshare (0.7.4)
	pip (8.1.1)
	prompt-toolkit (1.0.15)
	ptyprocess (0.5.2)
	pycurl (7.43.0)
	Pygments (2.2.0)
	pygobject (3.20.0)
	python-apt (1.1.0b1+ubuntu0.16.4.1)
	python-dateutil (2.7.2)
	python-debian (0.1.27)
	python-editor (1.0.3)
	python-oauth2 (1.1.0)
	python-systemd (231)
	pyzmq (17.0.0)
	qtconsole (4.3.1)
	requests (2.9.1)
	Send2Trash (1.5.0)
	setuptools (20.7.0)
	simplegeneric (0.8.1)
	six (1.10.0)
	SQLAlchemy (1.2.7)
	ssh-import-id (5.5)
	terminado (0.8.1)
	testpath (0.3.1)
	tornado (5.0.2)
	traitlets (4.3.2)
	ufw (0.35)
	unattended-upgrades (0.1)
	urllib3 (1.13.1)
	wcwidth (0.1.7)
	webencodings (0.5.1)
	websocket-client (0.47.0)
	wheel (0.29.0)
	widgetsnbextension (3.2.1)
```

**Comment by rkdarst** [comment]
The f-string `f"blah"` is a sign that this requires Python 3.6.  It was recently heavily revised to be asynchronous, and I guess this was left there.  @minrk will need to look at the async stuff, since I'm not good at that.

As a workaround, you can try this old version: https://github.com/jupyterhub/jupyterhub/blob/7bf93cb7e69dc92ea0bdcf3d20077eb638e5dc83/examples/cull-idle/cull_idle_servers.py

**Comment by andreat** [comment]
I tried the suggested version, but it also fails on the `naïve` (easily fixed) and on the 
```
python cull_idle_servers.py 
  File "cull_idle_servers.py", line 140
    resp = yield client.fetch(req)
SyntaxError: 'return' with argument inside generator
```
as for the latest version. I am not sure whether the oldest versions are suitable for use.

**Comment by andreat** [comment]
Thanks, the older version (after fixing the `naïve` part) with python3 works, also as service in jupyterhub. It seems the instructions have to be adapted accordingly, since they mention python, not python3.

**Comment by andreat** [comment]
I am not sure whether it is better to open another issue, since I see some error from the old version which is trying to delete multiple times the same server. Suggestions?

**Comment by minrk** [comment]
I believe that's been fixed in the latest version.
