### ISSUE TITLE
How do I set up the selenium driver?

### ISSUE THREAD

**Issue by whitebluecloud** [jupyterhub/jupyterhub#1826]
webdriver.Chrome(path)

I place the webdriver in the same folder and run the code, an error occurs. It works well in a non-Jupiter environment. Do you know anyone? (I tried to copy the file /usr/bin and /home/myaccount/bin...)

**Comment by whitebluecloud** [comment]
I assume this issue concern kernel environment and security

**Comment by whitebluecloud** [comment]
I guess this problem is related to kernel environment and security

**Comment by minrk** [comment]
How is a selenium driver normally set? If it's an environment variable, you can set these in your Spawner.environment configuration.

**Comment by whitebluecloud** [comment]
thanks for your help
I k

**Comment by whitebluecloud** [comment]
Fixed by phantom js driver setting, not chrome driver. Thank you @minrk :)
