### ISSUE TITLE
Add short announcement text in templates

### ISSUE THREAD

**Issue by rkdarst** [jupyterhub/jupyterhub#1836]
I was thinking that it would be convenient to have a configure that could include a short announcement in various templates (login, spawn, maybe control panel).  It could be used for things like "maintenance on Tuesday, down 14-16", "new kernels available", and so on.  This can be done more easily with the new template inheritance, but a single way to do something more lightweight would be nice.

- Good idea, or better to just require to use the existing template system.
- Which templates should it render on?
- Should some other template magic be done instead?
- Can it be changed without restarting server (maybe templates do this)?

I started something a few week ago, but switched to template inheritance instead.  Should I fix up and submit or archive?

**Comment by rabernat** [comment]
I was just wondering if something like this existed and I found my way to this issue.

Would be very valuable for large-scale jupyterhub deployments that need to push announcements to users.

**Comment by rschroll** [comment]
Another option would be to host the announcement remotely, as JSON or similar, and use a bit of AJAX to load and display it client-side.  This way you can update the announcement without touching anything on JupyterHub.  The obvious downside is another server in the mix.
