### ISSUE TITLE
whoami service example not working

### ISSUE THREAD

**Issue by echarles** [jupyterhub/jupyterhub#1842]
**How to reproduce the issue**

+ Have a running local jupyterhub deployment
+ Validate the `examples/cull-idle` service example is working fine on your en
+ cd to `examples/service-whoami` and simply launch jupyterhub (it will pick the local `jupyterhub_config.py` with the definition of the hub managed whoami services

**What you expected to happen**

+ Authenticate on the hub for a user
+ Ensure the notebook is displayed (you are authenticated - in my case http://localhost:8000/user/datalayer/tree? shows a running notebook)
+ Go to `http://localhost:8000/services/whoami` - It should display the JSON

**What actually happens**

+ In my case, I see `403: Forbidden`

I tried with hub managed or isolated process without luck.

The log on hub side

```
[I 2018-05-01 17:56:37.352 SingleUserNotebookApp log:122] 200 GET /user/datalayer/api/sessions?_=1525189785516&redirects=1 (datalayer@::ffff:127.0.0.1) 6.95ms
[I 2018-05-01 17:56:37.374 SingleUserNotebookApp log:122] 200 GET /user/datalayer/api/contents?type=directory&_=1525189785518 (datalayer@::ffff:127.0.0.1) 5.51ms
[D 2018-05-01 17:56:56.480 JupyterHub log:122] 304 GET /favicon.ico (@::ffff:127.0.0.1) 0.69ms
[W 2018-05-01 17:57:19.430 JupyterHub log:122] 403 GET /hub/api/users (@127.0.0.1) 1.38ms
[D 2018-05-01 17:57:25.974 JupyterHub app:1182] External service whoami running at http://localhost:10101
[D 2018-05-01 17:57:25.975 JupyterHub app:1182] Managed service whoami-oauth running at http://127.0.0.1:10102
```

On service side (after digging a bit into the code, it sounds strange to me that the log says `user is not allowed` - should it not be `service` is not allowed?

```
WARNING:tornado.application:Not allowing Hub user datalayer
WARNING:tornado.general:403 GET /services/whoami (127.0.0.1): user datalayer is not allowed.
WARNING:tornado.access:403 GET /services/whoami (127.0.0.1) 9.34ms
WARNING:tornado.application:Not allowing Hub user datalayer
WARNING:tornado.general:403 GET /services/whoami (127.0.0.1): user datalayer is not allowed.
WARNING:tornado.access:403 GET /services/whoami (127.0.0.1) 14.20ms
```

**Share what version of JupyterHub you are using**

v0.8.1

```
jupyter troubleshoot
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$PATH:
	/root/miniconda3/bin
	/root/miniconda3/bin
	/src/platform/sdk/bin
	/hadoop-kerberos/bin
	/opt/jdk/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games

sys.path:
	/root/miniconda3/bin
	/root/miniconda3/lib/python36.zip
	/root/miniconda3/lib/python3.6
	/root/miniconda3/lib/python3.6/lib-dynload
	/root/miniconda3/lib/python3.6/site-packages

sys.executable:
	/root/miniconda3/bin/python

sys.version:
	3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
	[GCC 7.2.0]

platform.platform():
	Linux-4.4.0-62-generic-x86_64-with-debian-stretch-sid

which -a jupyter:
	/root/miniconda3/bin/jupyter
	/root/miniconda3/bin/jupyter
	/usr/local/bin/jupyter

pip list:
	alembic (0.9.9)
	asn1crypto (0.24.0)
	backcall (0.1.0)
	bleach (2.1.3)
	certifi (2018.4.16)
	cffi (1.11.4)
	chardet (3.0.4)
	conda (4.4.10)
	cryptography (2.1.4)
	decorator (4.3.0)
	entrypoints (0.2.3)
	html5lib (1.0.1)
	idna (2.6)
	ipykernel (4.8.2)
	ipython (6.3.1)
	ipython-genutils (0.2.0)
	ipywidgets (7.2.1)
	jedi (0.12.0)
	Jinja2 (2.10)
	jsonschema (2.6.0)
	jupyter (1.0.0)
	jupyter-client (5.2.3)
	jupyter-console (5.2.0)
	jupyter-core (4.4.0)
	jupyterhub (0.8.1)
	Mako (1.0.7)
	MarkupSafe (1.0)
	mistune (0.8.3)
	nbconvert (5.3.1)
	nbformat (4.4.0)
	notebook (5.4.1)
	pamela (0.3.0)
	pandocfilters (1.4.2)
	parso (0.2.0)
	pexpect (4.5.0)
	pickleshare (0.7.4)
	pip (9.0.1)
	prompt-toolkit (1.0.15)
	ptyprocess (0.5.2)
	pycosat (0.6.3)
	pycparser (2.18)
	pycurl (7.43.0.1)
	Pygments (2.2.0)
	pyOpenSSL (17.5.0)
	PySocks (1.6.7)
	python-dateutil (2.7.2)
	python-editor (1.0.3)
	python-oauth2 (1.1.0)
	pyzmq (17.0.0)
	qtconsole (4.3.1)
	requests (2.18.4)
	ruamel-yaml (0.15.35)
	Send2Trash (1.5.0)
	setuptools (39.1.0)
	simplegeneric (0.8.1)
	six (1.11.0)
	SQLAlchemy (1.2.7)
	terminado (0.8.1)
	testpath (0.3.1)
	tornado (5.0.2)
	traitlets (4.3.2)
	urllib3 (1.22)
	wcwidth (0.1.7)
	webencodings (0.5.1)
	wheel (0.30.0)
	widgetsnbextension (3.2.1)

conda list:
	# packages in environment at /root/miniconda3:
	#
	# Name                    Version                   Build  Channel
	alembic                   0.9.9                     <pip>
	asn1crypto                0.24.0                   py36_0  
	backcall                  0.1.0                     <pip>
	bleach                    2.1.3                     <pip>
	ca-certificates           2017.08.26           h1d4fec5_0  
	certifi                   2018.1.18                py36_0  
	certifi                   2018.4.16                 <pip>
	cffi                      1.11.4           py36h9745a5d_0  
	chardet                   3.0.4            py36h0f667ec_1  
	conda                     4.4.10                   py36_0  
	conda-env                 2.6.0                h36134e3_1  
	cryptography              2.1.4            py36hd09be54_0  
	decorator                 4.3.0                     <pip>
	entrypoints               0.2.3                     <pip>
	html5lib                  1.0.1                     <pip>
	idna                      2.6              py36h82fb2a8_1  
	ipykernel                 4.8.2                     <pip>
	ipython                   6.3.1                     <pip>
	ipython-genutils          0.2.0                     <pip>
	ipywidgets                7.2.1                     <pip>
	jedi                      0.12.0                    <pip>
	Jinja2                    2.10                      <pip>
	jsonschema                2.6.0                     <pip>
	jupyter                   1.0.0                     <pip>
	jupyter-client            5.2.3                     <pip>
	jupyter-console           5.2.0                     <pip>
	jupyter-core              4.4.0                     <pip>
	jupyterhub                0.8.1                     <pip>
	libedit                   3.1                  heed3624_0  
	libffi                    3.2.1                hd88cf55_4  
	libgcc-ng                 7.2.0                h7cc24e2_2  
	libstdcxx-ng              7.2.0                h7a57d05_2  
	Mako                      1.0.7                     <pip>
	MarkupSafe                1.0                       <pip>
	mistune                   0.8.3                     <pip>
	nbconvert                 5.3.1                     <pip>
	nbformat                  4.4.0                     <pip>
	ncurses                   6.0                  h9df7e31_2  
	notebook                  5.4.1                     <pip>
	openssl                   1.0.2n               hb7f436b_0  
	pamela                    0.3.0                     <pip>
	pandocfilters             1.4.2                     <pip>
	parso                     0.2.0                     <pip>
	pexpect                   4.5.0                     <pip>
	pickleshare               0.7.4                     <pip>
	pip                       9.0.1            py36h6c6f9ce_4  
	prompt-toolkit            1.0.15                    <pip>
	ptyprocess                0.5.2                     <pip>
	pycosat                   0.6.3            py36h0a5515d_0  
	pycparser                 2.18             py36hf9f622e_1  
	pycurl                    7.43.0.1                  <pip>
	Pygments                  2.2.0                     <pip>
	pyopenssl                 17.5.0           py36h20ba746_0  
	pysocks                   1.6.7            py36hd97a5b1_1  
	python                    3.6.4                hc3d631a_1  
	python-dateutil           2.7.2                     <pip>
	python-editor             1.0.3                     <pip>
	python-oauth2             1.1.0                     <pip>
	pyzmq                     17.0.0                    <pip>
	qtconsole                 4.3.1                     <pip>
	readline                  7.0                  ha6073c6_4  
	requests                  2.18.4           py36he2e5f8d_1  
	ruamel_yaml               0.15.35          py36h14c3975_1  
	Send2Trash                1.5.0                     <pip>
	setuptools                38.4.0                   py36_0  
	setuptools                39.1.0                    <pip>
	simplegeneric             0.8.1                     <pip>
	six                       1.11.0           py36h372c433_1  
	SQLAlchemy                1.2.7                     <pip>
	sqlite                    3.22.0               h1bed415_0  
	terminado                 0.8.1                     <pip>
	testpath                  0.3.1                     <pip>
	tk                        8.6.7                hc745277_3  
	tornado                   5.0.2                     <pip>
	traitlets                 4.3.2                     <pip>
	urllib3                   1.22             py36hbe7ace6_0  
	wcwidth                   0.1.7                     <pip>
	webencodings              0.5.1                     <pip>
	wheel                     0.30.0           py36hfd4bba0_1  
	widgetsnbextension        3.2.1                     <pip>
	xz                        5.2.3                h55aa19d_2  
	yaml                      0.1.7                had09818_2  
	zlib                      1.2.11               ha838bed_2

```

**Comment by echarles** [comment]
I now run under a normal user account (no more root) and it works fine.

To make it run under normal user account, #1026 helped me with

```
sudo usermod -a -G shadow jupyterhub
sudo usermod -a -G shadow $USER
```

It may be specific to debian/ubuntu, but I don't think I read anything about this in the docs. Should I a PR (on the ./docs folder).

Now I also find information on https://github.com/jupyterhub/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges 

What about moving all the wiki rest to https://jupyterhub.readthedocs.io ?

I will wait a few more days before closing this.

**Comment by echarles** [comment]
Big Thx @minrk for the follow-up on this issue. It now begins to make more sense. I will take more time to double check that all information are available for the next dev to try the examples (maybe same points can be raised on the whoami flask example).

Do the services support anonymous users?

To complete the story, let me give you some background on what I am willing to achieve which is registration and authentication based on email (unless this is already available in another repo?):

1. Give access to the registration page/service to anonymous users: Anonymous user has to create an account based on his email address (so service has to check via api if userid is already taken).
2. Service creates unconfirmed account via api and sends email for confirmation with link (with token).
3. Users confirm by clicking the link in his email that redirects him once again to the registration service.  Service checks if token is valid. If yes, services confirms the user as valid user and user gains access to the hub.

Should I open another issue to further discuss this as this is a generic question about services?

Even if this scenario may not be (or may be?) a candidate for the jupyterhub core source, I think it is important for everyone to understand how the services and the related authentication work.

PS: I have created  #1858 to follow-up the point I have raised about the doc/wiki.

**Comment by echarles** [comment]
btw based on @minrk description, IMHO we could even rename the `whoami` but rather `whoisthehub` or `whoareyou`. I am on my way to implement a `whoami` for every user.

**Comment by minrk** [comment]
> Do the services support anonymous users?

JupyterHub has no concept of anonymous users. Either a user is logged in or they are not, as JupyterHub is concerned. *externally*, something integrating JupyterHub can create effectively anonymous users via the API (this is how [Binder](https://mybinder.org) works, for example. As far as JupyterHub is concerned, though, these are real users.

So in that sense, you can write something that integrates JupyterHub and is in charge of user creation and management. In your example, a JupyterHub user should not be created until after your system has finished creating the account.

Services may support anonymous users, but the examples are authenticated, so they don't.

> I think it is important for everyone to understand how the services and the related authentication work

Agreed. Services are any HTTP service that is proxied via the Hub. A service *may* rely on JupyterHub for authentication, in which case it does so via OAuth. If it does so, it can limit which users should be permitted access via its own user or group whitelists. This should be [documented here](https://jupyterhub.readthedocs.io/en/stable/reference/services.html#hub-authentication-and-services). Feel free to ask more questions or open pull requests if there is more clarification to be made.

>  IMHO we could even rename the whoami but rather whoisthehub 

I don't think so. The service specifically identifies the *requester*, not the Hub. In this case, it happens to create a user whitelist that only includes the current user, so that other users are not permitted access. We could remove the whitelist check, which would allow any user. Maybe that would be more informative, and we shouldn't be trying to illustrate too many examples at once.

**Comment by echarles** [comment]
Without the `hub_users` restriction, it is indeed a `whoami` service. #1856 brings the needed information to understand the behavior.

About mixing multiple features in one example, the current folder tries to cover a lot of things: the whoami service, the hub_users parameter and the managed/external settings. I guess we could create subfolders like done in the [service-notebook example](https://github.com/jupyterhub/jupyterhub/tree/master/examples/service-notebook).

I still have some issues to solve here:

- In the managed mode, the `whoami-oauth` service loops infinitely (see logs after)
- In the external mode, I have a running `whoami` changing the jupyterhub_config.py specifying a `api_token` - I guess this is the way to go, but it would be better for newbies to have the config out of the box
- In the external mode, the `whoami-oauth` fails for me with `oauth_client_id cannot be empty` - So I tried to find inspiration the [external-oauth])https://github.com/jupyterhub/jupyterhub/tree/master/examples/external-oauth) example (side note: it looks like a duplicate to this external whoami service) but fails with another error: `AttributeError: No such service field: oauth_redirect_uri`

```
[I 2018-05-07 14:32:12.356 JupyterHub log:122] 302 GET /hub/api/oauth2/authorize?client_id=service-whoami-oauth&redirect_uri=%2Fservices%2Fwhoami-oauth%2Foauth_callback&response_type=code&state=eyJ1dWlkIjogImQ0NjNkYmYxOTlmODQ2MWViNTY4NTM0N2M0NGEzM2ZmIiwgIm5leHRfdXJsIjogIi9zZXJ2aWNlcy93aG9hbWktb2F1dGgifQ → /services/whoami-oauth/oauth_callback?code=f05fe4cb-0728-4292-a222-df9d1a0a33fc&state=eyJ1dWlkIjogImQ0NjNkYmYxOTlmODQ2MWViNTY4NTM0N2M0NGEzM2ZmIiwgIm5leHRfdXJsIjogIi9zZXJ2aWNlcy93aG9hbWktb2F1dGgifQ (echarles@::1) 20.94ms
[I 2018-05-07 14:32:12.409 JupyterHub log:122] 200 POST /hub/api/oauth2/token (whoami-oauth@127.0.0.1) 45.70ms
[I 2018-05-07 14:32:12.413 JupyterHub log:122] 200 GET /hub/api/authorizations/token/[secret] (whoami-oauth@127.0.0.1) 3.42ms
[I 2018-05-07 14:32:12.443 JupyterHub log:122] 302 GET /hub/api/oauth2/authorize?client_id=service-whoami-oauth&redirect_uri=%2Fservices%2Fwhoami-oauth%2Foauth_callback&response_type=code&state=eyJ1dWlkIjogIjljNTlkYWI1M2EwNDQyYjY5OGVjZGZmMDgwNmU4ZTU0IiwgIm5leHRfdXJsIjogIi9zZXJ2aWNlcy93aG9hbWktb2F1dGgifQ → /services/whoami-oauth/oauth_callback?code=259c8df7-c285-44f6-bcb9-8633a803a5a8&state=eyJ1dWlkIjogIjljNTlkYWI1M2EwNDQyYjY5OGVjZGZmMDgwNmU4ZTU0IiwgIm5leHRfdXJsIjogIi9zZXJ2aWNlcy93aG9hbWktb2F1dGgifQ (echarles@::1) 20.81ms
[I 2018-05-07 14:32:12.496 JupyterHub log:122] 200 POST /hub/api/oauth2/token (whoami-oauth@127.0.0.1) 45.65ms
[I 2018-05-07 14:32:12.501 JupyterHub log:122] 200 GET /hub/api/authorizations/token/[secret] (whoami-oauth@127.0.0.1) 3.48ms
[I 2018-05-07 14:32:12.529 JupyterHub log:122] 302 GET /hub/api/oauth2/authorize?client_id=service-whoami-oauth&redirect_uri=%2Fservices%2Fwhoami-oauth%2Foauth_callback&response_type=code&state=eyJ1dWlkIjogIjVkNjM0Njk5ZTc3YjQzNmM5YTU1MDBlNWU1NTFiZTIyIiwgIm5leHRfdXJsIjogIi9zZXJ2aWNlcy93aG9hbWktb2F1dGgifQ → /services/whoami-oauth/oauth_callback?code=3329ea8a-0299-4502-bbec-7489be1bdc62&state=eyJ1dWlkIjogIjVkNjM0Njk5ZTc3YjQzNmM5YTU1MDBlNWU1NTFiZTIyIiwgIm5leHRfdXJsIjogIi9zZXJ2aWNlcy93aG9hbWktb2F1dGgifQ (echarles@::1) 20.77ms
[I 2018-05-07 14:32:12.582 JupyterHub log:122] 200 POST /hub/api/oauth2/token (whoami-oauth@127.0.0.1) 45.17ms
[I 2018-05-07 14:32:12.586 JupyterHub log:122] 200 GET /hub/api/authorizations/token/[secret] (whoami-oauth@127.0.0.1) 3.30ms
```

**Comment by echarles** [comment]
Seems like most of my issues are resolved (were env releated).

You say `Services may support anonymous users` : Could you point to any example or show how to configure this?

**Comment by minrk** [comment]
I've updated #1856 based on your feedback to change the hub_users default to allow any user, and deleted the duplicate whoami-oauth implementation from external-oauth (it now uses the service-whoami example).

I'm not 100% certain what is meant by anonymous users, but if you mean the behavior of Binder, where we create users on the fly, the implementation is [here](https://github.com/jupyterhub/binderhub/blob/0bdba0fc56b4ff27f5bdebc8077a99b1fcf021ca/binderhub/launcher.py#L70). It consists of:

1. users visit an external application (binder) that has an admin API token for the Hub
2. when it is appropriate, Binder uses this token to create users and then request an API token for that user.
3. Binder launches the server via the API, then redirects the user to the running server on the Hub with the token in the URL
