### ISSUE TITLE
Add a way to add additional handlers, override handlers and specify default pages

### ISSUE THREAD

**Issue by summerswallow-whi** [jupyterhub/jupyterhub#1853]
In our application, we are making JupyterHub the center of a data science portal. As such we need the ability to control the navigation between when the user logs in and redirection to the notebook.

Specifically, we need the ability to go to a welcome page after logging in. It is also desirable serve up a static terms of service page. In this way we can use the logs to audit whether terms of service have been accepted.

Originally, I worked around this by attaching web page handlers to my SAML authenticator. However, going this route precludes me from making my SAML authenticator generic as it has our customizations for welcome and terms of service. Furthermore, a returning user may not be redirected to where we desire but to the notebook. 

To meet our needs, I propose 

1. the ability to add additional webpage handlers via the jupyterhub_config.py file
2. these handlers take precedence over existing handlers (in my case, I need to overrule '/')
3. I can specify an alternate default_page(s) in get_next_url.

I've already done the coding and will make a pull request to address this.

I open this as an issue in the event greater issues are involved.

**Comment by minrk** [comment]
merged as #1854
