### ISSUE TITLE
Persisting JupyterHub data in S3

### ISSUE THREAD

**Issue by ranjitiyer** [jupyterhub/jupyterhub#1855]
Hello,

Is there a JupyterHub plugin for persisting Hub data in S3? We are evaluating [S3Content](https://github.com/danielfrg/s3contents) for persisting notebook data to S3 but it does not cover Hub artifacts on disk like the sqllite database that contains users. 

```
-rw-r--r-- 1 94208 May  2 19:43 jupyterhub.sqlite
```
Consequently a restore wouldn't restore Hub users - but would restore only their data.

Ranjit

**Comment by minrk** [comment]
JupyterHub state uses sqlalchemy, so any sqlalchemy backend will work (sqlite, postgres, mysql, etc.). That doesn't include blob stores like S3. If you are using kubernetes or similar to deploy jupyterhub, you can mount an S3 or EBS volume to hold the jupyterhub.sqlite file, then it would be backed by S3, but still using sqlite.

**Comment by cam72cam** [comment]
If you use RDS, it will automatically take backups at set intervals which you can restore

**Comment by ranjitiyer** [comment]
Thanks for the response. Much appreciated.
