### ISSUE TITLE
Move "Running JHub without root privileges" from Wiki to Readthedocs

### ISSUE THREAD

**Issue by echarles** [jupyterhub/jupyterhub#1858]
Some important information still reside on the wiki (e.g. https://github.com/jupyterhub/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges).

What about moving all the wiki rest to https://jupyterhub.readthedocs.io ?

**Comment by willingc** [comment]
Most of the information in the wiki references information written by community members and may refer to Medium posts or content not tested by the JupyterHub team. As such, all the wiki should not move to JupyterHub readthedocs.

The specific example you mention seems a reasonable topic to write up for the readthedocs docs. I'm going to update the issue title. Do you wish to submit a PR?

**Comment by echarles** [comment]
I have opened #1864

The Wiki TOC (6 entries) only contain external links, which are good to stay.

There are in total 12 pages among which some may be interesting to migrate/prune (e.g. https://github.com/jupyterhub/jupyterhub/wiki/Debug-Jupyterhub)

**Comment by minrk** [comment]
merged #1864
