### ISSUE TITLE
Determine why docs API isn't displaying detail

### ISSUE THREAD

**Issue by willingc** [jupyterhub/jupyterhub#1862]
We recently updated the docs and they display locally but not on RTD.

**Comment by betatim** [comment]
RTD is set to show the [stable (aka last release) version](https://jupyterhub.readthedocs.io/en/stable/) of the docs. If you instead explicitly go to https://jupyterhub.readthedocs.io/en/latest/ you get the new theme.

I used to know where in the RTD docs to look for more details on this but can only find https://docs.readthedocs.io/en/latest/versions.html right now.

**Comment by echarles** [comment]
Add issue before also with this... 
https://jupyterhub.readthedocs.io/en/stable/api/app.html : Stable shows details (stable is the default view)
https://jupyterhub.readthedocs.io/en/latest/api/app.html : Lastes does not show details
Building locally ('make html') shows the details.
