### ISSUE TITLE
Unable to connect with SingleUserNotebookApp from Atom + Hydrogen or VS Code Jupyter extension

### ISSUE THREAD

**Issue by andybrnr** [jupyterhub/jupyterhub#1877]
Hi all,

I'd like to use JupyterHub as a mechanism to manage notebook servers and connect to them from either VS Code w/Jupyter plugin or Atom with the Hydrogen plugin. Use case is a data science team running Jupyterhub on a large AWS instance as a shared computing resource, but with a preference for development using desktop text editor/IDE vs the jupyter web app. This is related in spirit to #1045 and #1052, but the hope was that VS Code or Hydrogen could just talk to the notebook server rather than need to swap to kernel gateway.

I've successfully deployed JuypyterHub on our AWS instance and can access the web app from different user accounts with PAM authentication. However, I can't seem to get either VS Code or Atom + Hydrogen to connect to the notebook servers after PAM authentication and SingleUserNotebookApp launch. VS Code fails with no error message; when connecting from Atom + Hydrogen, after entering the server to connect to, I receive the prompt that authentication has failed, and try using either token or cookie. Neither pulling the token out of the jupyterhub logs or creating a new token through the webapp interface works, and pulling the value out of the cookie_secret file doesn't seem to work, either.

I've verified the ability to connect to a stand alone jupyter notebook server running on the instance, as well as a stand alone jupyter kernel gateway server. Is there some specific configuration tweak needed to make this use case work, or has something fundamental with the notebook server API been changed and this won't work without changes to the code base? 

Python version: 3.6.3
JupyterHub version: 0.8.1
Jupyter notebook version: 5.40

Thanks,
Andy

**Comment by andybrnr** [comment]
My bad - didn't fully grasp the routing and that I needed to point the connection at <<base_url>>/user/<<username>>/. Disregard, works as expected.

**Comment by andybrnr** [comment]
Screenshot of devtools in Atom Hydrogen and the server log. Looks like something's getting lost in translation between Hydrogen and the kernel service api. Since this works just fine with a normal jupyter notebook server (not behind jupyterhub), does anyone have a sense of where I might look more carefully?

<img width="1679" alt="screen shot 2018-05-08 at 1 17 30 am" src="https://user-images.githubusercontent.com/9090148/39747471-423726e4-5262-11e8-9f50-65c544d0841b.png">

**Comment by minrk** [comment]
This should work fine, but you will need to retrieve an API token for talking to JupyterHub (the same token for talking to the Hub itself and the running server). Once you get that, you should be able to use it to talk to the notebook server (and start/stop it).

**Comment by andybrnr** [comment]
Finally got to the bottom of it - the issue was proxy related. We have an NGINX proxy as a gateway routing traffic to the AWS instance hosting JupyterHub inside a VPC. I thought we'd ruled this out as the issue, but I hadn't appreciated the nuances of websocket connections with two proxies in series (NGINX gateway <-> configurable-http-proxy <-> notebook server). [This SO post](https://serverfault.com/questions/845283/nginx-reverse-proxies-with-separate-ssl-termination-and-websockets) got me sorted out. Works like a charm now!
