### ISSUE TITLE
Jupyterhub + kdcauthenticator authentication fails

### ISSUE THREAD

**Issue by cyberyor** [jupyterhub/jupyterhub#1884]
Hello, 

I posted my issue some time ago in the [plugin repo](https://github.com/bloomberg/jupyterhub-kdcauthenticator/issues/2), but haven't got any response yet. Does anyone have any ideas how to solve the problem?

**Comment by willingc** [comment]
Hi @cyberyor, I haven't used Bloomberg's kdcauthenticator so I'm unsure what it supports. I'll leave a message on your original issue on the plugin repo.

**Comment by willingc** [comment]
https://github.com/bloomberg/jupyterhub-kdcauthenticator/issues/2#issuecomment-388782205
