### ISSUE TITLE
Base url not respected in 0.9.0b1

### ISSUE THREAD

**Issue by chicocvenancio** [jupyterhub/jupyterhub#1886]
Hi! Thanks for using JupyterHub.

If you are reporting an issue with JupyterHub:

- Please use the [GitHub issue](https://github.com/jupyterhub/jupyterhub/issues)
  search feature to check if your issue has been asked already. If it has,
  please add your comments to the existing issue.

- Where applicable, please fill out the details below to help us troubleshoot
  the issue that you are facing. Please be as thorough as you are able to
  provide details on the issue.

**How to reproduce the issue**
Update to 0.9.0b1 with a `JupyterHub.bind_url` set and attempt to reach the hub at https://hostname/base_url/hub

**What you expected to happen**
Access hub home page
**What actually happens**
Redirected to https://hostname/hub/base_url/hub were an understandable 404 is given.

**Share what version of JupyterHub you are using**
0.9.0b1

It is also notable that https://hostname/hub/ does lead to the hub home page.

Seeing the introduction of `JupyterHub.bind_url`, this may be only a documentation issue, is `JupyterHub.base_url` deprecated?

**Comment by willingc** [comment]
Thanks for the report @chicocvenancio. Yes, we definitely need to improve documentation about bind_url. 

@minrk I'm doing a quick scan of issues, but this one seems like we need to look a bit closer at the behavior or tests to make sure we're catching url combinations correctly now that bind_url is introduced.

**Comment by dhirschfeld** [comment]
IIUC @athornton was having some issues with `base_url` so perhaps he can shed some light on the problem...

**Comment by minrk** [comment]
What's the exact config? Have you set *both* bind_url and base_url? and if so to what?
