### ISSUE TITLE
Restart Jupyterhub automatically

### ISSUE THREAD

**Issue by anasos** [jupyterhub/jupyterhub#1888]
Hi
Everytime after a proxy failure i need to kill jupyterhub and jupyter process and restart it manually. 
Is there a way to restart jupyterhub automatically after a proxy failure on ubuntu 14.04.
Thanks for the help.

**Comment by minrk** [comment]
Yes, if you run JupyterHub with a process manager such as docker, supervisor, systemd, etc. they all have controls for what to do when a process exits and support autorestart.

**Comment by anasos** [comment]
Thanks For the answer.
