### ISSUE TITLE
500: "failed to check authorization" on second start of single-user server

### ISSUE THREAD

**Issue by jcb91** [jupyterhub/jupyterhub#1897]
Hi there!

I have a Jupyterhub cluster I'm setting up on AWS using EC2 instances as single-user servers (using a custom spawner based on [harvard/cloudJHub/jupyterhub_files/spawner.py](https://github.com/harvard/cloudJHub/blob/5e86ec962af62bd1e97c16e226da85c16ffcdb53/jupyterhub_files/spawner.py)). 

Logging in for the first time, when the user has no instance running, everything goes fine. Problems occur when attempting to reconnect to an instance which has stopped (been shut down) and then started again. This results in an http 500 on redirect to the restarted singleuser instance, with error message "failed to check authorization".

~Below are the logs for the hub~

The logs are in this gist: https://gist.github.com/jcb91/acf8f64b0ea902eef1a1740f9abbb9f7

* [hub_initial_start.log](https://gist.github.com/jcb91/acf8f64b0ea902eef1a1740f9abbb9f7#file-hub_initial_start-log)
* [hub_first_successful_spawn_and_redirect.log](https://gist.github.com/jcb91/acf8f64b0ea902eef1a1740f9abbb9f7#file-hub_first_successful_spawn_and_redirect-log)
* [hub_second_unsuccessful_redirect.log](https://gist.github.com/jcb91/acf8f64b0ea902eef1a1740f9abbb9f7#file-hub_second_unsuccessful_redirect_log)
* [singleuser_first_successful_start.log](https://gist.github.com/jcb91/acf8f64b0ea902eef1a1740f9abbb9f7#file-singleuser_first_successful_start_log)
* [singleuser_second_unsuccessful_login.log](https://gist.github.com/jcb91/acf8f64b0ea902eef1a1740f9abbb9f7#file-singleuser_second_unsuccessful_login_log)

`jupyter troubleshoot` output:

<details>
$PATH:
	/usr/local/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin
	/home/ubuntu/.local/bin
	/home/ubuntu/bin
	/home/ubuntu/.local/bin
	/home/ubuntu/bin

sys.path:
	/usr/local/bin
	/usr/src/oauthenticator
	/usr/lib/python35.zip
	/usr/lib/python3.5
	/usr/lib/python3.5/plat-x86_64-linux-gnu
	/usr/lib/python3.5/lib-dynload
	/usr/local/lib/python3.5/dist-packages
	/usr/lib/python3/dist-packages

sys.executable:
	/usr/bin/python3

sys.version:
	3.5.2 (default, Nov 23 2017, 16:37:01) 
	[GCC 5.4.0 20160609]

platform.platform():
	Linux-4.4.0-1057-aws-x86_64-with-Ubuntu-16.04-xenial

which -a jupyter:
	/usr/local/bin/jupyter
	/usr/local/bin/jupyter

pip list:
	Package                      Version                Location               
	---------------------------- ---------------------- -----------------------
	acme                         0.22.2                 
	alembic                      0.9.9                  
	asn1crypto                   0.24.0                 
	backcall                     0.1.0                  
	bcrypt                       3.1.4                  
	bleach                       2.1.3                  
	blinker                      1.3                    
	boto3                        1.7.10                 
	botocore                     1.10.10                
	certbot                      0.22.2                 
	cffi                         1.11.5                 
	chardet                      2.3.0                  
	cloud-init                   17.2                   
	command-not-found            0.3                    
	ConfigArgParse               0.11.0                 
	configobj                    5.0.6                  
	cronutils                    0.2.0                  
	cryptography                 2.2.2                  
	decorator                    4.3.0                  
	docutils                     0.14                   
	entrypoints                  0.2.3                  
	escapism                     1.0.0                  
	Fabric3                      1.14.post1             
	funcsigs                     0.4                    
	future                       0.15.2                 
	hibagent                     1.0.1                  
	html5lib                     1.0.1                  
	idna                         2.6                    
	ipykernel                    4.8.2                  
	ipython                      6.3.1                  
	ipython-genutils             0.2.0                  
	ipywidgets                   7.2.1                  
	jedi                         0.12.0                 
	Jinja2                       2.8                    
	jmespath                     0.9.3                  
	josepy                       1.0.1                  
	jsonpatch                    1.10                   
	jsonpointer                  1.9                    
	jsonschema                   2.6.0                  
	jupyter                      1.0.0                  
	jupyter-client               5.2.3                  
	jupyter-console              5.2.0                  
	jupyter-core                 4.4.0                  
	jupyterhub                   0.8.1                  
	jupyterhub-ldapauthenticator 1.1                    
	language-selector            0.1                    
	ldap3                        2.5                    
	Mako                         1.0.7                  
	MarkupSafe                   0.23                   
	mistune                      0.8.3                  
	mock                         1.3.0                  
	nbconvert                    5.3.1                  
	nbformat                     4.4.0                  
	nbgrader                     0.5.4                  
	ndg-httpsclient              0.4.2                  
	notebook                     5.4.1                  
	oauthenticator               0.8.1.dev0             /usr/src/oauthenticator
	oauthlib                     1.0.3                  
	pamela                       0.3.0                  
	pandocfilters                1.4.2                  
	paramiko                     2.4.1                  
	parsedatetime                2.4                    
	parso                        0.2.0                  
	pbr                          1.8.0                  
	peewee                       3.3.1                  
	pexpect                      4.5.0                  
	pickleshare                  0.7.4                  
	pip                          10.0.1                 
	prettytable                  0.7.2                  
	prompt-toolkit               1.0.15                 
	ptyprocess                   0.5.2                  
	pyasn1                       0.1.9                  
	pycparser                    2.18                   
	pycurl                       7.43.0                 
	Pygments                     2.2.0                  
	pygobject                    3.20.0                 
	PyICU                        1.9.2                  
	PyJWT                        1.3.0                  
	PyNaCl                       1.2.1                  
	pyOpenSSL                    17.3.0                 
	pyRFC3339                    1.0                    
	pyserial                     3.0.1                  
	python-apt                   1.1.0b1+ubuntu0.16.4.1 
	python-dateutil              2.7.2                  
	python-debian                0.1.27                 
	python-editor                1.0.3                  
	python-oauth2                1.1.0                  
	python-systemd               231                    
	pytz                         2018.4                 
	PyYAML                       3.11                   
	pyzmq                        17.0.0                 
	qtconsole                    4.3.1                  
	raven                        6.7.0                  
	requests                     2.9.1                  
	s3transfer                   0.1.13                 
	Send2Trash                   1.5.0                  
	setuptools                   20.7.0                 
	simplegeneric                0.8.1                  
	six                          1.10.0                 
	SQLAlchemy                   1.2.7                  
	ssh-import-id                5.5                    
	terminado                    0.8.1                  
	testpath                     0.3.1                  
	tornado                      5.0.2                  
	traitlets                    4.3.2                  
	ufw                          0.35                   
	unattended-upgrades          0.1                    
	urllib3                      1.13.1                 
	virtualenv                   15.0.1                 
	wcwidth                      0.1.7                  
	webencodings                 0.5.1                  
	wheel                        0.29.0                 
	widgetsnbextension           3.2.1                  
	zope.component               4.3.0                  
	zope.event                   4.2.0                  
	zope.hookable                4.0.4                  
	zope.interface               4.3.2
</details><br />

I guess perhaps there's some cookie-related information on the single-user server which should be cleared on starting the singleuser process, but am unsure what's happening :( any help much appreciated!

**Comment by jcb91** [comment]
>  Is there a chance that the second launch is reusing environment variables from the first launch?

Yes, this is certainly possible, and I think is probably the issue. I've set the singleuser to run as a systemctl service on the worker EC2 instance, so the environment variables are set only once on instance creation, inside the service definition. For subsequent spawns, the instance is restarted, so the variables are no altered. From [will_resume in dockerspawner](https://github.com/jupyterhub/dockerspawner/blob/7ec1f3cc9c020597f2320affc81f632d0d4f1a47/dockerspawner/dockerspawner.py#L251-L255), I deduce that the normal behaviour is to clean up the API token on stopping a server, so I should set `will_resume` to prevent that, I guess. I'll report back on how that fares...

**Comment by marciocourense** [comment]
Hello @jcb91, this is quite a popular error on Jupyterhub (just look at the amount of google results).
At my current employee, me and my colleagues we did several deployments of jupyterhub in different VMs, and stumble on this error.
The main culprit is often lack of proper read+write access to the jupyterhub-user directory. In more simple terms the specif user should have r+w access to its respective directory on the hub. Once this is properly done you should be able to start your single-user server.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Thanks to all!
