### ISSUE TITLE
Oauth setting for coursera on jupyterhub

### ISSUE THREAD

**Issue by leolurunhe** [jupyterhub/jupyterhub#1898]
I created some extensions for jupyter notebook and runs them on docker. I want to create a jupyterhub for those extensions and I cloned generic.py and common.py files from https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/generic.py. I set my own jupyterhub_config.py in this way:
```c.JupyterHub.ssl_key='/etc/letsencrypt/live/jupyter.mentoracademy.org/privkey.pem' 
c.JupyterHub.ssl_cert='/etc/letsencrypt/live/jupyter.mentoracademy.org/fullchain.pem' 
c.JupyterHub.port=443

from dockerspawner import DockerSpawner 
c.JupyterHub.spawner_class=DockerSpawner
import netifaces
docker0=netifaces.ifaddresses('docker0')
docker0_ipv4=docker0[netifaces.AF_INET][0]
c.JupyterHub.hub_ip=docker0_ipv4['addr']
c.DockerSpawner.image = 'mentoracademy'

# using coursera oauth
import sys,os 
if "./" not in sys.path:
	sys.path.append("./")
from generic import GenericOAuthenticator,LocalGenericOAuthenticator
c.JupyterHub.authenticator_class= LocalGenericOAuthenticator
c.LocalGenericOAuthenticator.create_system_users=True

I can successfully use those extensions if I don't use the ouath, but when I log in jupyterhub with oauth, those extensions cannot get user cookies. How to fix that?

**Comment by willingc** [comment]
Hi @leolurunhe, I responded on the oauthenticator repo https://github.com/jupyterhub/oauthenticator/issues/170#issuecomment-390374759

**Comment by leolurunhe** [comment]
I did that, and I can successfully log in, but all my extensions don't work. It seems those extensions don't get a user cookie. But if I log in with other oauth(like github), those extensions work fine.

**Comment by willingc** [comment]
@leolurunhe I think that you may need to add some additional code to the GenericOAuthenticator as looking at the GitHubOAuthenticator and others have [`_api_headers` defined](https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/github.py#L42) and making sure that you have [stashed the `access_token`](https://github.com/jupyterhub/oauthenticator/blob/cd9043c8518b1fe96b1e0eb07858b1941425c562/oauthenticator/github.py#L154)

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
