### ISSUE TITLE
Feature ideas for jupyterhub

### ISSUE THREAD

**Issue by dsblank** [jupyterhub/jupyterhub#19]
Organizing some ideas for the jupyterhub. These are not necessarily prioritized.

1) For public served pages, it would be nice to keep track of hits over time. And the main page. This suggests persistent counts for pages. (This is useful to provide to funding agencies, to show impact for materials developed for dissemination.)

2) Logs showing referrers (like apache's). This would also be useful in reporting stats like ("our site was visited by people from 31 countries, 2.1 million pages hits from 650k unique visitors"). If the log file had the same format as other web servers, then there are already tools available for creating reports.

**Comment by TimDumol** [comment]
Broadcasts should be doable using [Server-Sent Events/EventSource](http://en.wikipedia.org/wiki/Server-sent_events). There's a library for it in Tornado [here](https://pythonhosted.org/eventsource/).

**Comment by rgbkrk** [comment]
For some reason I just now got notified of this issue again, perhaps the body text changed? :smile:

The indexing I'd like to do as a generic project on the side that allows us to index notebooks well, likely with some ability to be packaged as a notebook extension or as another webservice (that can be fed and consumed from nbviewer).

**Comment by lminer** [comment]
If I get disconnected from jupyterhub while it's running some computation, it would be great to be able to see the output when I reconnect later.

**Comment by consideRatio** [comment]
Issue triage: closing as outdated and too vague to follow up on as the issue describes multiple points and I'm not sure if something has been done to fix these points over the years.
