### ISSUE TITLE
Is it possible to add custom domain or public ip to nbviewer rendered notebook url?

### ISSUE THREAD

**Issue by Srinivasb0** [jupyterhub/jupyterhub#1901]
How can I add the custom domain to ipython notebook rendered by nbviewer.

Forex: URL for my current rendered notebook is

https://nbviewer.jupyter.org/github/Srinivasb0/Data_Science_tutorial/blob/master/Job_Analysis_for_DataScientist.ipynb

but the output I am looking for is

https://xyz.com/github/Srinivasb0/Data_Science_tutorial/blob/master/Job_Analysis_for_DataScientist.ipynb

If it possible can any one help me with the process of installation

**Comment by betatim** [comment]
This is the repository for JupyterHub. You will have more luck getting help on the nbviewer repository: https://github.com/jupyter/nbviewer
