### ISSUE TITLE
Unicode encoding error when running jupyterhub as a daemon

### ISSUE THREAD

**Issue by joingithubkor** [jupyterhub/jupyterhub#1902]
Hi all,

I've got an error when running a jupyterhub as as a service daemon.

Jupyter notebook file hasn't been displayed properly and couldn't rename files with other language rather than English.

However, it works as I run jupyterhub command like sudo jupyterhub.

I'm using python3.6. 

Has anyone have any solution?

**Comment by minrk** [comment]
This is typically due to missing environment variables such as LANG/LANGUAGE/LC_ALL. If you are running it as a service, these variables typically are not set unless you set them.

In a notebook, you can test with `sys.getpreferredencoding()` or `locale` in a shell. These should not return C.POSIX/ASCII.

**Comment by joingithubkor** [comment]
Hi minrk,

If I type locale.getpreferredencoding() in python shell, it returns 'UTF-8'. And the environment in my linux sytem such as LANG/LC_ALL is set to ko_KR.UTF-8 at the moment. 
However, locale.getpreferredencoding() in jupyter notebook shell returned 'ANSI_X3.4-1968'. 
How can I fix it? I'm fairy new to jupyter notebook and linux system. 
Thanks in advance.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Thanks to all!

**Comment by wqh17101** [comment]
> This is typically due to missing environment variables such as LANG/LANGUAGE/LC_ALL. If you are running it as a service, these variables typically are not set unless you set them.

Why ? @minrk @willingc

**Comment by wqh17101** [comment]
@joingithubkor 
i found that as a systemd service unit you can modify the service config to add the locale env.
https://coreos.com/os/docs/latest/using-environment-variables-in-systemd-units.html
Example:
create a file named locale.conf, write something below to it
```
LANGUAGE="zh_CN.UTF-8"
LANG="zh_CN.UTF-8"
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
```
modify the config
add 
EnvironmentFile=locale.conf
to [Service]

service xxx restart ,and it worked
