### ISSUE TITLE
Feedback about JupyterHub from enterprise users

### ISSUE THREAD

**Issue by Winterflower** [jupyterhub/jupyterhub#1904]
Hello team!
A few weeks back I gave a talk about deploying JupyterHub on Kubernetes at PyData London 2018 and a few enterprise data scientists and engineers came to talk to me after the talk. @willingc encouraged me to share some notes I took and am more than happy to do that to help more teams benefit from the Jupyter ecosystem.
Some of the general themes that kept coming up in the discussions

* Authentication, integrating Jupyter singleuser servers with legacy authentication systems. In particular, the problem was not with authentication in the Hub (ie whether or not a user is allowed to start a single user notebook server), but with services that a user might need to access from the notebook, so that the notebook needs to run as a particular system user to be able to talk to that service

* Data security on Kubernetes - how confident can we be that data manipulated in single user Jupyter notebooks spawned from the Hub is secure?

* Making large amounts of data accessible to Jupyter singleuser notebook servers when running on Kubernetes

* Uploading Excel sheets and CSV files to Jupyter single user servers and helping business intelligence teams transition from Excel to Jupyter

* Strategies for managing JupyterHub deployments at scale: loadbalancing users across multiple JupyterHubs.

* Capacity planning: how far can I go with a simple 3 node 1vCPU cluster? how many single user notebooks can I run on a small Kubernetes cluster? 

* Deploying JupyterHub without Kubernetes - (for example, in enterprise environments that have onprem data centers and can't run Kubernetes for whatever reason)

**Comment by willingc** [comment]
Hi @Winterflower, Thanks for taking the time to write up these notes. 👍 I'm going to label this reference and leave the issue open for a month since others may wish to comment here too.

**Comment by Winterflower** [comment]
Thank you for the responses @willingc and @minrk !
Very helpful and I'll certainly keep these mind!
Had a few more comments/questions about JupyterHub and BinderHub after a presentation at PyData Amsterdam

* tips on running JupyterHub when users are expected to carry out very CPU intensive computations in each single user notebook (case studies etc)

* running Jupyter notebooks on Windows 

* sharing large datasets among multiple Jupyter single user notebooks so that each individual user does not have to load a copy of the dataset in memory

* bootstrapping Kubernetes without a cloud provider / better ways to run Kubernetes on AWS and cost projections

* using LDAP for authentication

**Comment by elgalu** [comment]
> tips on running JupyterHub when users are expected to carry out very CPU intensive computations in each single user notebook

With the new spawner form support one can allow users to pick arbitrary CPU, Memory or whatever requirements they have before launching the notebook server. Kubernetes can take care of scheduling this hardware and reserving it for that user.

> running Jupyter notebooks on Windows

Will be as challenging as running any Python stack in Windows but is doable, lots of blog posts out there explaining this.

JupyterHub is server-side technology and probably deploying this with Windows is not something you will want to do.

> sharing large datasets among multiple Jupyter single user notebooks

One could use NFS (AWS EFS) but for large datasets it may become too expensive.

Or use Dask distributed nature to load a huge S3-based dataset [as explained in this blog](http://matthewrocklin.com/blog/work/2017/01/12/dask-dataframes).

IMHO for large datasets it might be better to have a big data SQL-friendly service like Google Big Query.

In AWS world it could be a PrestoDB layer that reads from S3 (AWS Athena / EMR / Redshift). So no need for notebooks to have all the data in the file system, they interact with big data via queries and only fetch what they need. Aggregations (group by, count, ...) can happen server side, no need to put all of it in a pandas frame to do some aggregations.

Finally there is also [PySpark DataFrames](https://spark.apache.org/docs/latest/sql-programming-guide.html) (distributed) and [HDFS](https://hortonworks.com/apache/hdfs/) (Hadoop Distributed File System).

> bootstrapping Kubernetes without a cloud provider / better ways to run Kubernetes on AWS and cost projections

At [Zalando](https://github.com/zalando) we couldn't wait for AWS to provide K8s so we have our custom implementation, most of it is [open sourced](https://github.com/zalando-incubator/kubernetes-on-aws) but would still require advanced DevOps to achieve this deployment on your own.

Cost-wise you always have a minimum K8s operational cost of keeping the cluster running. Plus your expected usage. K8s allows you to maximise hardware usage but one needs to understand the apps deployed, if I deploy an app requiring 60GB of RAM but by monitoring you observe that in practice it only uses 10GB then I should correct those requirements to avoid wasting resources. In K8s there are [requests and limits](https://kubernetes.io/docs/concepts/policy/resource-quotas/#requests-vs-limits) and one must understand these concepts before operating and properly using Kubernetes in a cost-effective way. If you need concrete numbers I've seen an AWS setup that with around 80 users per month it costs $30 per user and each user can use up to 16 CPU cores and 60GB of RAM. But you need to add the people maintaining this infrastructure, unless it's community-driven and the users organise to maintain it themselves.

> using LDAP for authentication

https://github.com/jupyterhub/ldapauthenticator

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. The discussion was definitely valuable, and many of the points have influenced multiple JupyterHub projects! If you'd like to continue the discussion please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
