### ISSUE TITLE
AzureAdOAuthenticator throwing an error: getpwnam(): name not found

### ISSUE THREAD

**Issue by sarath145p** [jupyterhub/jupyterhub#1905]
I am trying to use AzureAdOAuthenticator as mentioned in the documentation on here: [https://github.com/jupyterhub/oauthenticator](url)

I am able to login from AzureAd to Jupyter Hub but when I click on "Start my server", I keep getting this error that says getpwnam(): name not found: name. My config file is given below:

`import os
from oauthenticator.azuread import AzureAdOAuthenticator
c.JupyterHub.authenticator_class = AzureAdOAuthenticator

c.Application.log_level = 'DEBUG'

c.AzureAdOAuthenticator.tenant_id = os.environ.get('AAD_TENANT_ID')

c.AzureAdOAuthenticator.oauth_callback_url = 'http://{your-domain}/hub/oauth_callback'
c.AzureAdOAuthenticator.client_id = '{AAD-APP-CLIENT-ID}'
c.AzureAdOAuthenticator.client_secret = '{AAD-APP-CLIENT-SECRET}'

c.JupyterHub.port = ....
c.Spawner.notebook_dir = '~/notebooks'
c.Authenticator.admin_users = {}
c.Authenticator.whitelist = {}
c.LocalAuthenticator.create_system_users = True`

I couldn't find a solution to why is it not able to create a server. In the admin portal, I get the same error when I try to start the server. Can you please help me resolve this issue?

**Comment by minrk** [comment]
You must use the Local variant of the Authenticator to create local users: `c.JupyterHub.authenticator_class = LocalAzureAdOAuthenticator`

**Comment by sarath145p** [comment]
Thanks for the reply, it has indeed solved the issue

**Comment by karthisuku** [comment]
@sarath145p Could you post the `LocalAzureAdOAuthenticator` implementation.
