### ISSUE TITLE
Sensitive API token passed in URL of websocket 

### ISSUE THREAD

**Issue by lambertjosh** [jupyterhub/jupyterhub#1907]
Hi! Thanks for using JupyterHub.

If you are reporting an issue with JupyterHub:

**How to reproduce the issue**

Login to JupyterHub, start your notebook server, and create a terminal session.

**What you expected to happen**

Sensitive data should either be in cookies or in request bodies. Since this is a websocket, it should ideally be sent as a websocket message once it connects in order to authenticate itself.

**What actually happens**

The API token is passed in the GET request URL. 

Applications should not send sensitive data in the URL through GET requests. This is frowned upon because data in URL strings have a much higher chance of being logged in cleartext on the underlying system or even potentially through intermediary systems.

**Share what version of JupyterHub you are using**

0.9.0

**Comment by minrk** [comment]
What version of jupyter/notebook are you using? What's the key for the url param with sensitive info that's logged? When I create terminals with an authenticated notebook server, no GET params are passed. When I request a kernel websocket, a session_id is passed, but this isn't sensitive info, it's just a UUID for the mapping of kernel to notebook.
