### ISSUE TITLE
Open redirect during login

### ISSUE THREAD

**Issue by lambertjosh** [jupyterhub/jupyterhub#1908]
Hi! Thanks for using JupyterHub.

If you are reporting an issue with JupyterHub:

**How to reproduce the issue**

Login to JupyterHub with a URL like: https://hub.jupyter.com/hub/login?next=%2f%2fbaddomain.com

**What you expected to happen**

Parameters should be validated before sending the 302, preventing potential phishing attacks or tricking users into visiting malicious sites.

**What actually happens**

Users are redirected.

**Share what version of JupyterHub you are using**

0.9.0

**Comment by minrk** [comment]
Thanks for the test case! We do validate the login redirect target, but missed the `//` case ('http://baddomain.com' is properly blocked). I'll add a fix and test for this one.

Fixed by #1912
