### ISSUE TITLE
Redirect After Starting My Server Strips HTTPS

### ISSUE THREAD

**Issue by aperiodic** [jupyterhub/jupyterhub#1909]
**How to reproduce the issue**
Configure JupyterHub to use SSL by setting the `ssl_key` and `ssl_cert` configuration options, and to use `sudospawner.SudoSpawner` as the `spawner_class`.

Start JupyterHub and log in to the JupyterHub web UI. After logging in, hit the big green 'Start My Server' button.

**What you expected to happen**
I expect to be redirected to `https://localhost:8000/user/<username>/tree` so I can use my server.

**What actually happens**
I'm redirected to `http://localhost:8000/user/<username>/tree` (note the protocol change from `https` to `http`) and instead of a webpage I get an error from my browser that the connection was reset. If I manually change the protocol to `https`, everything works as expected.

**Share what version of JupyterHub you are using**
0.8.1

**Configuration**
Here's the contents of the config_file I'm passing to jupyterhub when I start it up:
```
c.JupyterHub.port = 8000
c.JupyterHub.ssl_key = '/etc/jupyterhub/jupyterhub.key'
c.JupyterHub.ssl_cert = '/etc/jupyterhub/jupyterhub.crt'
c.JupyterHub.cookie_secret_file = '/etc/jupyterhub/cookie_secret'
c.JupyterHub.spawner_class = 'sudospawner.SudoSpawner'
c.JupyterHub.authenticator_class = 'hashauthenticator.HashAuthenticator'
c.HashAuthenticator.secret_key = REDACTED
c.HashAuthenticator.password_length = 32
```

**Comment by minrk** [comment]
Do you have nginx or anything in front of jupyterhub?

**Comment by aperiodic** [comment]
I have nothing in front of JupyterHub, I'm connecting directly to the port configured as `c.JupyterHub.port = 8000`.

Here's JupyterHub's logs from the server start through the redirect:
```
May 22 00:16:46 c69e9c7a31d3 jupyterhub[9004]: [I 2018-05-22 00:16:45.910 SingleUserNotebookApp notebookapp:1619] Serving notebooks from local directory: /home/dlp
May 22 00:16:46 c69e9c7a31d3 jupyterhub[9004]: [I 2018-05-22 00:16:45.910 SingleUserNotebookApp notebookapp:1619] 0 active kernels
May 22 00:16:46 c69e9c7a31d3 jupyterhub[9004]: [I 2018-05-22 00:16:45.910 SingleUserNotebookApp notebookapp:1619] The Jupyter Notebook is running at:
May 22 00:16:46 c69e9c7a31d3 jupyterhub[9004]: [I 2018-05-22 00:16:45.910 SingleUserNotebookApp notebookapp:1619] http://127.0.0.1:39173/user/dlp/
May 22 00:16:46 c69e9c7a31d3 jupyterhub[9004]: [I 2018-05-22 00:16:45.910 SingleUserNotebookApp notebookapp:1620] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
May 22 00:16:46 c69e9c7a31d3 jupyterhub[9004]: [I 2018-05-22 00:16:46.493 SingleUserNotebookApp log:122] 302 GET /user/dlp/ \u2192 /user/dlp/tree? (@127.0.0.1) 0.79ms
May 22 00:16:46 c69e9c7a31d3 jupyterhub[9004]: [I 2018-05-22 00:16:46.494 JupyterHub base:447] User dlp took 1.563 seconds to start
May 22 00:16:46 c69e9c7a31d3 jupyterhub[9004]: [I 2018-05-22 00:16:46.496 JupyterHub proxy:231] Adding user dlp to proxy /user/dlp/ => http://127.0.0.1:39173
May 22 00:16:46 c69e9c7a31d3 jupyterhub[9004]: 00:16:46.498 - info: [ConfigProxy] Adding route /user/dlp -> http://127.0.0.1:39173
May 22 00:16:46 c69e9c7a31d3 jupyterhub[9004]: 00:16:46.499 - info: [ConfigProxy] 201 POST /api/routes/user/dlp
May 22 00:16:46 c69e9c7a31d3 jupyterhub[9004]: [I 2018-05-22 00:16:46.509 JupyterHub log:122] 302 GET /hub/user/dlp/ \u2192 /user/dlp/?redirects=1 (dlp@::ffff:172.17.0.1) 1578.77ms
May 22 00:16:46 c69e9c7a31d3 jupyterhub[9004]: [I 2018-05-22 00:16:46.682 SingleUserNotebookApp log:122] 302 GET /user/dlp/?redirects=1 \u2192 /user/dlp/tree?redirects=1 (@::ffff:172.17.0.1) 0.51ms
May 22 00:16:46 c69e9c7a31d3 jupyterhub[9004]: [I 2018-05-22 00:16:46.732 SingleUserNotebookApp log:122] 302 GET /user/dlp/tree?redirects=1 \u2192 /hub/api/oauth2/authorize?client_id=user-dlp&redirect_uri=%2Fuser%2Fdlp%2Foauth_callback&response_type=code&state=eyJ1dWlkIjo
gIjFjNWIzODA1MWU2MTRlN2FhZTY1ZmFiZWQ2N2EyYTMzIiwgIm5leHRfdXJsIjogIi91c2VyL2RscC90cmVlP3JlZGlyZWN0cz0xIn0 (@::ffff:172.17.0.1) 1.94ms
May 22 00:16:46 c69e9c7a31d3 jupyterhub[9004]: [I 2018-05-22 00:16:46.788 JupyterHub log:122] 302 GET /hub/api/oauth2/authorize?client_id=user-dlp&redirect_uri=%2Fuser%2Fdlp%2Foauth_callback&response_type=code&state=eyJ1dWlkIjogIjFjNWIzODA1MWU2MTRlN2FhZTY1ZmFiZWQ2N2EyYTMz
IiwgIm5leHRfdXJsIjogIi91c2VyL2RscC90cmVlP3JlZGlyZWN0cz0xIn0 \u2192 /user/dlp/oauth_callback?code=808556c7-18cb-4857-8848-596087a21a90&state=eyJ1dWlkIjogIjFjNWIzODA1MWU2MTRlN2FhZTY1ZmFiZWQ2N2EyYTMzIiwgIm5leHRfdXJsIjogIi91c2VyL2RscC90cmVlP3JlZGlyZWN0cz0xIn0 (dlp@::ffff:172.
17.0.1) 8.75ms
May 22 00:16:46 c69e9c7a31d3 jupyterhub[9004]: [I 2018-05-22 00:16:46.887 JupyterHub log:122] 200 POST /hub/api/oauth2/token (dlp@127.0.0.1) 21.71ms
May 22 00:16:46 c69e9c7a31d3 jupyterhub[9004]: [I 2018-05-22 00:16:46.893 JupyterHub log:122] 200 GET /hub/api/authorizations/token/[secret] (dlp@127.0.0.1) 4.13ms
```

**Comment by willingc** [comment]
@minrk Is this the unicode error for right arrow (->) that we fixed earlier this year https://github.com/jupyterhub/jupyterhub/commit/18e060072700cf959fcac7fceaf850bcd343d323

**Comment by aperiodic** [comment]
@willingc this seems to have different symptoms than described in #1406: there's no error in the logs, and my notebook is served after I manually correct the protocol in the URL.

**Comment by willingc** [comment]
@aperiodic Thanks for the clarification. Could you let us know which versions you are using for JupyterHub, hashauthenticator (I think there is more than one in GitHub), SudoSpawner? Thanks.

**Comment by aperiodic** [comment]
@willingc
jupyterhub: 0.8.1
jupyterhub-hashauthenticator: 0.4.0
sudospawner: 0.5.1

Versions obtained by running `pip freeze` using the `pip` from the virtual environment.

**Comment by minrk** [comment]
Where is this running? Is it perhaps on Amazon?

What I'm having trouble with is that all those redirects are path-only, so never full URLs with the protocol. I don't see how it would be changing the protocol. Does it do the same thing in multiple browsers?

**Comment by willingc** [comment]
It may also be helpful to start jupyterhub with `--debug` and post all from the start through the redirects.

**Comment by aperiodic** [comment]
The error shows up in Chrome & Firefox, but not Safari. Inspecting the responses, the 302 from JupyterHub does have only a path for the Location, not a full URL. In Chrome there's a 307 "Internal Redirect" whose Location sets the protocol to HTTP; Firefox doesn't show me anything like that but there must be something similar going on under the hood.

In conclusion, not a JupyterHub bug. Thanks for your help, and sorry for the noise.

**Comment by betatim** [comment]
If you figure out how to fix it or what caused this it would be great if you could post a resolution for visitors from the future who run into a similar problem (even though it isn't a JupyterHub bug, it is a "configuring JupyterHub thing")
