### ISSUE TITLE
How do I customize notebook ? 

### ISSUE THREAD

**Issue by sanjaydatasciencedojo** [jupyterhub/jupyterhub#1927]
I am deploying Jupyterhub using Kubernetes on Google Cloud. I was able to override the theme of hub by inserting following lines of code in config.yaml file
``` hub: 
    extraConfig: |
        import subprocess 
        subprocess.call(['git', 'clone' ,'github url of themes'])
        c.JupyterHub.data_files_path='name of themes '
```

But I am also looking to customize notebook.

**Comment by minrk** [comment]
To customize the notebook environment, you need to customize the singleuser image, as described [in the guide](https://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html?highlight=lifecycle%20hooks#customizing-the-user-environment).

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Thanks to all!
