### ISSUE TITLE
Bind user login to specific IP address.

### ISSUE THREAD

**Issue by s6007589** [jupyterhub/jupyterhub#1928]
Hello.
I'm working on jupyterhub on PAMAuthenticator and LocalProcessSpawner.
But currently I need a new feature: bind user login to specific IP address to prevent users from 'cheating'/'copying' resources in examination environment.
How should I configure it?

**Comment by minrk** [comment]
You could do this in `.authenticate()`:

```python
from tornado import web
from jupyterhub.auth import PAMAuthenticator

ip_whitelist = {'127.0.0.1'}
class MyAuthenticator(PAMAuthenticator):
    def authenticate(self, data, handler):
        if handler.request.remote_ip not in ip_whitelist:
            raise web.HTTPError(403, "Login not allowed from outside...")
        return super().authenticate(data, handler)
```

But probably better is to do access filtering at a higher level, e.g. [with nginx](http://nginx.org/en/docs/http/ngx_http_access_module.html) in front of jupyterhub.

**Comment by s6007589** [comment]
Thank you. It worked.
