### ISSUE TITLE
Is npm + node required when installing JH via anaconda?

### ISSUE THREAD

**Issue by SeaDude** [jupyterhub/jupyterhub#1936]
Following the docs [here](https://github.com/jupyterhub/jupyterhub#check-prerequisites) and [here](https://jupyterhub.readthedocs.io/en/stable/quickstart.html#prerequisites), prerequisites listed include `npm` and `nodejs-legacy`.

Before I installed these, I ran `whereis npm` and see that `npm` installed in `npm: /opt/anaconda/anaconda4/bin/npm`, the directory where I installed anaconda. Does this mean I still need to install `npm` and `nodejs-legacy`?

System is Ubuntu 17.10. Still troubleshooting this installation. 

Thanks

**Comment by SeaDude** [comment]
Thanks for the reply. My question arose because of the the paragraph **ahead** of your link which states npm and nodejs are "Prerequisites". Now I know anaconda handles ALL dep's not just `configurable-http-proxy`

```
Before installing JupyterHub, you will need:

    a Linux/Unix based system

    Python 3.4 or greater. An understanding of using pip or conda for installing Python packages is helpful.

    nodejs/npm. Install nodejs/npm, using your operating system’s package manager. For example, install on Linux Debian/Ubuntu using:...
```

**Comment by willingc** [comment]
Thanks for pointing that out @SeaDude. I've opened a PR #1949 to clarify this a bit more.
