### ISSUE TITLE
Multiple Login Options

### ISSUE THREAD

**Issue by znicholls** [jupyterhub/jupyterhub#1939]
Hi there, 

Is it possible to give users multiple options to login/authenticate? For example, they could choose to authenticate with e.g. GitHub or with GitLab (my particular hope is to allow users to authenticate with GitHub or with the Australian Access Federation Rapid Connect API).

Thanks :)

**Comment by betatim** [comment]
I think people have made good experience with https://www.keycloak.org/ or similar setups that take care of the various different auth methods and from JupyterHub you talk to it as if it is a single OAuth provider.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Thanks to all!
