### ISSUE TITLE
How to use save hook?

### ISSUE THREAD

**Issue by AlphaSRE** [jupyterhub/jupyterhub#1951]
jupyter notebook has save hook that I can save file and do other things, how I can do this by use jupyterhub?

**Comment by AlphaSRE** [comment]
save file can't  trigger the c.Spawner.post_stop_hook, so how can I do save hook?

**Comment by minrk** [comment]
You can use the same post_save_hook in jupyter_notebook_config.py. If you want to configure it for all users you can create system-wide config, e.g. in `/etc/jupyter/jupyter_notebook_config.py`

**Comment by jcunhafonte** [comment]
Can you be more clear on this @minrk? 

For instance, having this configuration on **jupyter_notebook_config.py** don't work.
```
def script_post_save(model, os_path, contents_manager, **kwargs):
    print('-----script_post_save-------')

c.FileContentsManager.post_save_hook = script_post_save
```

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
