### ISSUE TITLE
Basic installation on RHEL 7 fails with error: [ConfigProxy] 404 GET /

### ISSUE THREAD

**Issue by CordThomas** [jupyterhub/jupyterhub#1953]
I have followed the installation instructions found here and on several other sites.   I am looking to get the most basic form of the hub installed.   This is on a RHEL 7 server on our corporate Intranet.   

It appears it is not starting the entire way - i have not been able to find what a successful startup should look like.  I have tried several setup options.

A few questions - it's not clear where to start jupyterhub - seems where i start it is where the sqlite database is created as well as the cookie_secret is written, probably doing something wrong there.  So, I am starting from /etc/jupyterhub where my config is - not ideal to have the DB there though. 

Also, whether I need to create any firewall exceptions - i have opened ports 8000 and 8001 to all for now.  Doesn't seem to matter if I shut down my firewalld though.

Here is startup and below is output of jupyter troubleshoot.   The last statement in the startup is on requesting 'curl localhost:8000'

Help appreciated.
```
:/etc/jupyterhub > jupyterhub --debug --ip=0.0.0.0
[D 2018-06-06 09:04:33.802 JupyterHub application:555] Looking for jupyterhub_config in /etc/jupyterhub
[D 2018-06-06 09:04:33.803 JupyterHub application:577] Loaded config file: /etc/jupyterhub/jupyterhub_config.py
[D 2018-06-06 09:04:33.805 JupyterHub app:1343] Could not load pycurl: No module named 'pycurl'
    pycurl is recommended if you have a large number of users.
[I 2018-06-06 09:04:33.806 JupyterHub app:834] Loading cookie_secret from /etc/jupyterhub/jupyterhub_cookie_secret
[D 2018-06-06 09:04:33.807 JupyterHub app:886] Connecting to db: sqlite:///jupyterhub.sqlite
[D 2018-06-06 09:04:33.825 JupyterHub orm:504] database schema version found: 3ec6993fe20c
[W 2018-06-06 09:04:33.831 JupyterHub app:955] No admin users, admin interface will be unavailable.
[W 2018-06-06 09:04:33.831 JupyterHub app:956] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-06-06 09:04:33.831 JupyterHub app:983] Not using whitelist. Any authenticated user will be allowed.
[D 2018-06-06 09:04:33.854 JupyterHub app:1241] Loaded users:
[I 2018-06-06 09:04:33.860 JupyterHub app:1528] Hub API listening on http://127.0.0.1:8080/hub/
[W 2018-06-06 09:04:33.861 JupyterHub proxy:415]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[W 2018-06-06 09:04:33.861 JupyterHub proxy:456] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2018-06-06 09:04:33.861 JupyterHub proxy:458] Starting proxy @ http://0.0.0.0:8000/
[D 2018-06-06 09:04:33.861 JupyterHub proxy:459] Proxy cmd: ['configurable-http-proxy', '--ip', '0.0.0.0', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--error-target', 'http://127.0.0.1:8080/hub/error']
09:04:34.021 - info: [ConfigProxy] Proxying http://0.0.0.0:8000 to (no default)
09:04:34.024 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
**09:04:44.510 - error: [ConfigProxy] 404 GET /**
```
```

> jupyter troubleshoot
$PATH:
	/bin
	/sbin
	/bin
	/usr/sbin
	/usr/bin
	/usr/lib/jupyterhub

sys.path:
	/usr/bin
	/usr/lib64/python36.zip
	/usr/lib64/python3.6
	/usr/lib64/python3.6/lib-dynload
	/usr/lib64/python3.6/site-packages
	/usr/lib/python3.6/site-packages

sys.executable:
	/bin/python3

sys.version:
	3.6.3 (default, Jan  4 2018, 16:40:53)
	[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

platform.platform():
	Linux-3.10.0-862.2.3.el7.x86_64-x86_64-with-redhat-7.5-Maipo

which -a jupyter:
	/bin/jupyter
	/bin/jupyter
	/usr/bin/jupyter

pip list:
	Package           Version
	----------------- ---------
	alembic           0.9.9
	asn1crypto        0.24.0
	async-generator   1.9
	atomicwrites      1.1.5
	attrs             18.1.0
	backcall          0.1.0
	bleach            2.1.3
	certifi           2018.4.16
	cffi              1.11.5
	chardet           3.0.4
	codecov           2.0.15
	coverage          4.5.1
	cryptography      2.2.2
	decorator         4.3.0
	entrypoints       0.2.3
	html5lib          1.0.1
	idna              2.6
	ipykernel         4.8.2
	ipython           6.4.0
	ipython-genutils  0.2.0
	jedi              0.12.0
	Jinja2            2.10
	jsonschema        2.6.0
	jupyter-client    5.2.3
	jupyter-core      4.4.0
	jupyterhub        0.8.1
	Mako              1.0.7
	MarkupSafe        1.0
	mistune           0.8.3
	mock              2.0.0
	more-itertools    4.2.0
	nbconvert         5.3.1
	nbformat          4.4.0


```

**Comment by minrk** [comment]
Something's not right because jupyterhub hasn't finished starting up. The full startup logs for jupyterhub 0.8.1 end like this:

```
[I 2018-06-07 10:32:25.708 JupyterHub proxy:458] Starting proxy @ http://*:8765/
[D 2018-06-07 10:32:25.709 JupyterHub proxy:459] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8765', '--api-ip', '127.0.0.1', '--api-port', '5678', '--error-target', 'http://127.0.0.1:8081/hub/error']
10:32:27.618 - info: [ConfigProxy] Proxying http://*:8765 to (no default)
10:32:27.620 - info: [ConfigProxy] Proxy API at http://127.0.0.1:5678/api/routes
** this is where your logs stop **
[D 2018-06-07 10:32:27.753 JupyterHub proxy:491] Proxy started and appears to be up
[D 2018-06-07 10:32:27.755 JupyterHub proxy:552] Proxy: Fetching GET http://127.0.0.1:5678/api/routes
10:32:27.761 - info: [ConfigProxy] 200 GET /api/routes
** not getting to this step is why you have a 404: **
[W 2018-06-07 10:32:27.762 JupyterHub proxy:304] Adding missing default route
[I 2018-06-07 10:32:27.762 JupyterHub proxy:370] Adding default route for Hub: / => http://127.0.0.1:8081
[D 2018-06-07 10:32:27.762 JupyterHub proxy:552] Proxy: Fetching POST http://127.0.0.1:5678/api/routes/
10:32:27.768 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
10:32:27.769 - info: [ConfigProxy] 201 POST /api/routes/
** not until "JupyterHub is now running" should you expect JupyterHub to be accepting connections **
[I 2018-06-07 10:32:27.770 JupyterHub app:1581] JupyterHub is now running at http://:8765/
```

Can you start with `jupyterhub --debug` and see if you get more useful info about where it's stuck?

**Comment by CordThomas** [comment]
Thanks for response.  Here is entire debug after waiting 1 minute to make sure nothing was waiting.

> jupyterhub --debug
[D 2018-06-07 07:46:43.749 JupyterHub application:555] Looking for jupyterhub_config in /etc/jupyterhub
[D 2018-06-07 07:46:43.751 JupyterHub application:577] Loaded config file: /etc/jupyterhub/jupyterhub_config.py
[D 2018-06-07 07:46:43.754 JupyterHub app:1343] Could not load pycurl: No module named 'pycurl'
    pycurl is recommended if you have a large number of users.
[I 2018-06-07 07:46:43.755 JupyterHub app:834] Loading cookie_secret from /etc/jupyterhub/jupyterhub_cookie_secret
[D 2018-06-07 07:46:43.755 JupyterHub app:886] Connecting to db: sqlite:///jupyterhub.sqlite
[D 2018-06-07 07:46:43.779 JupyterHub orm:504] database schema version found: 3ec6993fe20c
[W 2018-06-07 07:46:43.786 JupyterHub app:955] No admin users, admin interface will be unavailable.
[W 2018-06-07 07:46:43.786 JupyterHub app:956] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-06-07 07:46:43.786 JupyterHub app:983] Not using whitelist. Any authenticated user will be allowed.
[D 2018-06-07 07:46:43.814 JupyterHub app:1241] Loaded users:
[I 2018-06-07 07:46:43.822 JupyterHub app:1528] Hub API listening on http://127.0.0.1:8080/hub/
[W 2018-06-07 07:46:43.823 JupyterHub proxy:415]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[W 2018-06-07 07:46:43.823 JupyterHub proxy:456] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2018-06-07 07:46:43.823 JupyterHub proxy:458] Starting proxy @ http://*:8000/
[D 2018-06-07 07:46:43.823 JupyterHub proxy:459] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--error-target', 'http://127.0.0.1:8080/hub/error']
07:46:43.994 - info: [ConfigProxy] Proxying http://*:8000 to (no default)
07:46:43.998 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes

So, what might stop the proxy from reporting it had started?

**Comment by minrk** [comment]
It's very strange indeed. What's `pip list`? I see the output above is truncated. I wonder if this is an issue with tornado perhaps. If you have tornado 5, try `pip install 'tornado<5'`.

**Comment by CordThomas** [comment]
I have successfully installed on a fresh new server.  Previously I was trying to install on a server with other software / services running.  There may have been some conflict. I am fairly certain not a port conflict.

I did have 	tornado           5.0.2 

Thank you.

**Comment by willingc** [comment]
Thanks @CordThomas for the update. I'm glad that you have successfully installed on a different server. I'm going to go ahead and close this issue. Please let us know if you have additional questions.

**Comment by hansen-m** [comment]
I'm running into the exact same issue on the same version of RedHat using Anaconda3. Any other ideas what this might be?

**Comment by CordThomas** [comment]
For me, I never got to root cause of original problem.   Initially I was trying to install on a server that already had a number of services running.  I was nearly 100% certain that there wasn't a port conflict but as you see in my startup script snippet, not all services started up.   How far in the startup are you getting.   Exactly what I reported or more?

**Comment by hansen-m** [comment]
`sudo /opt/anaconda3/bin/jupyterhub -f /etc/jupyterhub/jupyterhub_config.py 
[I 2018-06-25 17:13:49.631 JupyterHub app:1656] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.0
[I 2018-06-25 17:13:49.631 JupyterHub app:1656] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.0
[I 2018-06-25 17:13:49.634 JupyterHub app:1014] Loading cookie_secret from /tmp/jupyterhub_cookie_secret
[I 2018-06-25 17:13:49.655 JupyterHub proxy:429] Generating new CONFIGPROXY_AUTH_TOKEN
[I 2018-06-25 17:13:49.686 JupyterHub app:1188] Not using whitelist. Any authenticated user will be allowed.
[I 2018-06-25 17:13:49.707 JupyterHub app:1838] Hub API listening on http://127.0.0.1:8081/hub/
[I 2018-06-25 17:13:49.708 JupyterHub proxy:483] Starting proxy @ http://:8000
17:13:49.895 - info: [ConfigProxy] Proxying https://*:8000 to (no default)
17:13:49.898 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
17:13:56.183 - error: [ConfigProxy] 404 GET /`

In this state it also doesn't seem to shutdown cleanly, and starting it again gives me:

 `16:18:05.203 - error: [ConfigProxy] Uncaught Exception Error: listen EADDRINUSE 127.0.0.1:8001`.

Maybe this was related to the port conflict issues you indicated.

**Comment by hansen-m** [comment]
Still investigating but I believe the issue was a DNS/host mismatch. After updating the /etc/hosts file it seems to launch.

**Comment by CordThomas** [comment]
That's exactly the state my install got hung up in.   I don't believe mine was DNS related since this is mostly local host stuff with a proxy in front.   Curious what update you made to hosts file to correct this.

For some reason the proxy doesn't appear to have started as we both don't get this line "Proxy started and appears to be up" - though I never found anything useful in the logs as to what was failing in the proxy.
