### ISSUE TITLE
Admin user confusion with `Spawner.admin_access`

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterhub/jupyterhub#1964]
I'd like to configure my custom options form differently depending on whether or not the user is an admin user. 

The [`Spawner.admin_access`](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/spawner.py#L161) is a (non-configurable) trait which is never set in the base class. Are subclasses supposed to implement this themselves?

In my custom spawner class I'm seeing:
```python
In[10]: self.admin_access
Out[10]: False

In[11]: self.authenticator.admin_users
Out[11]: {'dhirschfeld'}

In[12]: self.user.escaped_name
Out[12]: 'dhirschfeld'

In[13]: self.user.escaped_name in self.authenticator.admin_users
Out[13]: True
```
...which doesn't seem to make sense?

**Comment by minrk** [comment]
admin_access is configured at the JupyterHub-level:

```python
c.JupyterHub.admin_access = True
```

This is passed through to the Spawner [here](https://github.com/jupyterhub/jupyterhub/blob/0.9.0b3/jupyterhub/user.py#L369).

**Comment by dhirschfeld** [comment]
I guess I'm not sure exactly what it's purpose is? It looks like that flag's sole purpose is to set a `JUPYTERHUB_ADMIN_ACCESS` env variable in the spawner?
https://github.com/jupyterhub/jupyterhub/blob/e7eb674a8964e09ad50cf1a28062733e7eebe13d/jupyterhub/spawner.py#L599-L600

What does that actually do? What behaviour is changed by having that variable in the spawner env?

What I'm after is to determine whether the user is an admin user  - i.e. is in the authenticator `admin_users` config. So I think the `Spawner.admin_access` flag is irrelevant for this purpose?

**Comment by dhirschfeld** [comment]
As mentioned, `admin_access` is a global configuration on the JupyterHub app:
https://github.com/jupyterhub/jupyterhub/blob/14c8d7dc46017100abd1ac9455d90a27b4b27367/jupyterhub/app.py#L785-L790
...which determines whether or not admin users are able to access others' servers.

So, indeed, this wasn't what I was after.

What was slightly confusing is that this app-global configuration value is also reflected in the `Spawner` class:
https://github.com/jupyterhub/jupyterhub/blob/e7eb674a8964e09ad50cf1a28062733e7eebe13d/jupyterhub/spawner.py#L161
...andis set to the global value inside the `User.spawn` method:
https://github.com/jupyterhub/jupyterhub/blob/e7eb674a8964e09ad50cf1a28062733e7eebe13d/jupyterhub/user.py#L369

**Comment by dhirschfeld** [comment]
What I was looking for was a convenience method `User.isadmin`. I think that might be pretty useful but I'll open a separate issue for it...

**Comment by minrk** [comment]
admin_access is a flag for whether single-user servers should allow admins access to servers that are not their own (i.e. you as admin have access to *all* servers, not just your own). It is not usually enabled.

>  I was looking for was a convenience method User.isadmin

admin is a boolean attribute on the user, so this should already be available as:

    self.user.admin
