### ISSUE TITLE
Polish docs for 0.9 release

### ISSUE THREAD

**Issue by willingc** [jupyterhub/jupyterhub#1968]
Open issues that we would like docs included (@minrk Please add to this list)
- [x] Merge and polish PR #1967 (Configuring user environments)

Additional 'to do' items
- [x] Update changelog
- [x] Update contributors list

Not strictly documentation
- [x] Update metadata in setup.py for pypi.org's additional display of docs now

**Comment by minrk** [comment]
What is the additional display of docs on PyPI? I can't find any information about it.

**Comment by willingc** [comment]
Sorry, I wasn't clear. There are some additional fields that are now displayed with the new PyPI UI. Just a reminder to myself to look through them.
