### ISSUE TITLE
User load conda environment

### ISSUE THREAD

**Issue by JWDobken** [jupyterhub/jupyterhub#1975]
I have miniconda globally installed (`/opt/miniconda`) and JupyterHub succesfully running!

Now, I would like specific users to create and configures their own conda environments; so at user creation (`adduser <username>`) I'll place: 

    export PATH="/opt/miniconda3/bin:$PATH"

in the `/home/<username>/.bashrc` file. If the user now creates a conda environment (`conda create --name test_env`) the environment is created in the `/home/<username>/.conda/envs/` directory as expected.

**The Question** is, how can the user load and switch between its local environments within the JupyterHub notebooks or console?

**Comment by minrk** [comment]
Switching for the notebook server is a challenge, and hopefully not needed. Switching for the kernel should be doable by registering the kernelspec after creating the env:

    ~/.conda/envs/foo/bin/ipython kernel install --name foo-env --user

which will install a kernelspec for the env foo for just that user. Then the name 'foo-env' should show up in the list when picking a kernel.

**Comment by JWDobken** [comment]
Thanks! I'm really happy so far

**Comment by willingc** [comment]
Hi @JWDobken,

To see the kernelspecs, you can use `jupyter kernelspec list`.

To delete a kernelspec, you may use `jupyter kernelspec remove {kernel_name}`

Here's the help information for the command:
```
$ jupyter kernelspec remove -h
Remove one or more Jupyter kernelspecs by name.

Options
-------

Arguments that take values are actually convenience aliases to full
Configurables, whose aliases are listed on the help line. For more information
on full configurables, see '--help-all'.

-f
    Force removal, don't prompt for confirmation.
--debug
    set log level to logging.DEBUG (maximize logging output)
--generate-config
    generate default config file
-y
    Answer yes to any questions instead of prompting.
--log-level=<Enum> (Application.log_level)
    Default: 30
    Choices: (0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL')
    Set the log level by value or name.
--config=<Unicode> (JupyterApp.config_file)
    Default: ''
    Full path of a config file.

To see all available configurables, use `--help-all`

Examples
--------

    jupyter kernelspec remove python2 [my_kernel ...]
``` 

https://jupyterhub.readthedocs.io/en/latest/reference/config-user-env.html?highlight=kernelspec#installing-kernelspecs
