### ISSUE TITLE
Jupyterhub installation problem 

### ISSUE THREAD

**Issue by robert-juang** [jupyterhub/jupyterhub#1981]
I'm using a MacOS, and I'm trying to run Jupyterhub but it's not working. When I type: "sudo jupyterhub", the following shows up:

![screen shot 2018-06-14 at 1 27 41 pm](https://user-images.githubusercontent.com/19910241/41428228-657dd61a-6fd7-11e8-81b3-75921547f574.png)

I'm not sure what's wrong. Did I forget to install a file? Am I not the admin? Plz help ;(

**Comment by minrk** [comment]
The proxy failed to start because something is already running on port 8000. Do you have anything else running, perhaps another instance of configurable-http-proxy already?

**Comment by robert-juang** [comment]
Yes! Problem was solved. Thanks!
