### ISSUE TITLE
User with a tilde in the name is being left as active without user activity

### ISSUE THREAD

**Issue by chicocvenancio** [jupyterhub/jupyterhub#1982]
**Describe the bug**
User with a tilde in the name is being left as active without user activity, preventing culling.

**To Reproduce**
1. Login with an user with a tilde 
2. Start a server, 
3. Close browser 
4. Start cull_idle_servers.py with debug logging
5. See user's server not being culled due to "being active"
**Expected behavior**
User to become inactive once browser is closed

**Additional context**
This seems related to the continous add and removal of the route to the user server by the proxy. Log excerpt:

> [I 2018-06-14 18:32:31.720 JupyterHub proxy:240] Adding user ~TestJH to proxy /paws/user/~TestJH/ => http://[REDACTED]:8888
> [I 2018-06-14 18:33:31.755 JupyterHub proxy:299] Checking routes
> [W 2018-06-14 18:33:31.755 JupyterHub proxy:322] Adding missing route for /paws/user/~TestJH/ (<jupyterhub.objects.Server object at 0x7f8d89d0a240>)
> [W 2018-06-14 18:33:31.756 JupyterHub proxy:361] Deleting stale route /paws/user/%7ETestJH/
> [I 2018-06-14 18:33:31.756 JupyterHub proxy:240] Adding user ~TestJH to proxy /paws/user/~TestJH/ => http://[REDACTED]:8888
> [I 2018-06-14 18:34:31.713 JupyterHub proxy:299] Checking routes
> [W 2018-06-14 18:34:31.714 JupyterHub proxy:322] Adding missing route for /paws/user/~TestJH/ (<jupyterhub.objects.Server object at 0x7f8d89d0a240>)
> [I 2018-06-14 18:34:31.714 JupyterHub proxy:240] Adding user ~TestJH to proxy /paws/user/~TestJH/ => http://[REDACTED]:8888
> [I 2018-06-14 18:35:31.770 JupyterHub proxy:299] Checking routes
> [W 2018-06-14 18:35:31.771 JupyterHub proxy:322] Adding missing route for /paws/user/~TestJH/ (<jupyterhub.objects.Server object at 0x7f8d89d0a240>)
> [W 2018-06-14 18:35:31.771 JupyterHub proxy:361] Deleting stale route /paws/user/%7ETestJH/
> [I 2018-06-14 18:35:31.771 JupyterHub proxy:240] Adding user ~TestJH to proxy /paws/user/~TestJH/ => http://[REDACTED]:8888
> [I 2018-06-14 18:36:31.718 JupyterHub proxy:299] Checking routes
> [W 2018-06-14 18:36:31.719 JupyterHub proxy:322] Adding missing route for /paws/user/~TestJH/ (<jupyterhub.objects.Server object at 0x7f8d89d0a240>)
> [I 2018-06-14 18:36:31.720 JupyterHub proxy:240] Adding user ~TestJH to proxy /paws/user/~TestJH/ => http://[REDACTED]:8888

**Comment by chicocvenancio** [comment]
For what its worth, chp does give us the adequate route as the api response.

> chicocvenancio@toolsbeta-paws-master-01:~$ curl http://[[REDACTED]]:8001/api/routes -H "Authorization: token [[REDACTED]]" 
> {"/":{"hub":true,"target":"http://[[REDACTED]]:8081","jupyterhub":true,"last_activity":"2018-06-14T19:53:38.683Z"},"/paws/user/chicocvenancio":{"user":"chicocvenancio","server_name":"","target":"http://[[REDACTED]]:8888","jupyterhub":true,"last_activity":"2018-06-14T19:49:08.243Z"},"/paws/user/~TestJH":{"user":"~TestJH","server_name":"","target":"http://[[REDACTED]]:8888","jupyterhub":true,"last_activity":"2018-06-14T19:53:38.164Z"}}

**Comment by willingc** [comment]
Yes, this is a bug. Thanks for catching @chicocvenancio . I've added a PR for a test case for this, now we need a fix in a second PR.
