### ISSUE TITLE
Spawn method doesn't handle timeout correctly

### ISSUE THREAD

**Issue by dhawal55** [jupyterhub/jupyterhub#1985]
**Describe the bug**
I'm using Kubespawner to spawn user notebooks in Kubernetes. When Kubespawner times out creating the notebook pod, it throws `Timeout` error (https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/utils.py#L155). The spawn method in jupyterhub catches the exception, but it looks for `gen.Timeout` in the catch block instead of `Timeout`. As a result, the exception reason is set to `error` instead of `timeout`. (https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/user.py#L465-#L477)

**To Reproduce**
 - Configure Jupyterhub to use Kubespawner and set `JUPYTERHUB_SPAWNER_START_TIMEOUT` to a few secs. 
 - Try to spin up a user notebook
 - It will timeout and jupyterHub reports it as an unhandled error and increments `spawner.failure.error` statsd counter instead of `spawner.failure.timeout` counter

**Expected behavior**
Jupyterhub should increment the correct statsd counter

**Desktop (please complete the following information):**
 - OS: linux
 - Version JupyterHub 0.9.0b3

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
