### ISSUE TITLE
JupyterHub cannot import additional Python kernels

### ISSUE THREAD

**Issue by Guo-Zhang** [jupyterhub/jupyterhub#1990]
**Describe the bug**
Hello! I have followed the document of installing the IPython kernel(https://ipython.readthedocs.io/en/latest/install/kernel_install.html) to set the Python kernels provided by the system and installed by pyenv into JupyterHub in my server. But I find that only the Python version used to install JupyterHub is available in the notebook. There are no errors even in "--debug" configure.

I have used to add the system Python 2 and 3 successfully for a short time. I have tried to repeat all the processes for several times but each time with different small problems and finally direct to the same problem. I have tried to read the source code to locate what I should configure in addition but also failed. 

**To Reproduce**
The settings in my system:
```
root@quanttide-staff:~# python --version
Python 2.7.12
root@quanttide-staff:~# python2 --version
Python 2.7.12
root@quanttide-staff:~# python3 --version
Python 3.5.2

root@quanttide-staff:~# pyenv versions
* system (set by /root/.pyenv/version)
  2.7.15
  3.6.5

root@quanttide-staff:~# jupyter kernelspec list
Available kernels:
  python3         /usr/local/lib/python3.5/dist-packages/ipykernel/resources
  python2.7.12    /root/.local/share/jupyter/kernels/python2.7.12
  python2.7.15    /root/.local/share/jupyter/kernels/python2.7.15
  python3.5.2     /root/.local/share/jupyter/kernels/python3.5.2

root@quanttide-staff:~# pyenv global 3.6.5
root@quanttide-staff:~# jupyter kernelspec list
[ListKernelSpecs] WARNING | Native kernel (python3) is not available
[ListKernelSpecs] WARNING | Native kernel (python3) is not available
Available kernels:
  python2.7.12    /root/.local/share/jupyter/kernels/python2.7.12
  python2.7.15    /root/.local/share/jupyter/kernels/python2.7.15
  python3.5.2     /root/.local/share/jupyter/kernels/python3.5.2
```

I use `sudo` folllowing the official document to support the multi-users in JupyterHub:
```
sudo jupyterhub -f /etc/jupyterhub/jupyterhub_config.py --debug
```
The same if I don't use `sudo`. 

**Expected behavior**
I am wondering what I can do to locate the problems. I really need the help. Thanks a lot!

**Screenshots**
The notebook:
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/13083271/41479198-ff45573e-70fc-11e8-8b45-a4d4078c2f40.png">

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/13083271/41479249-23e5f314-70fd-11e8-9a5c-058d87d81d0b.png">

The same even if I change the global Python version.

**Desktop (please complete the following information):**
 - OS: Ubuntu 14.0.4
 - Browser: Safari
 - Version: stable

**Comment by willingc** [comment]
Hi @Guo-Zhang,

You will need to follow the steps as described here for installing the kernels in the correct location: https://jupyterhub.readthedocs.io/en/stable/reference/config-user-env.html?highlight=kernels#configuring-user-environments

Specifically, you would install the kernels system-wide as described here: https://jupyterhub.readthedocs.io/en/stable/reference/config-user-env.html?highlight=kernels#example-installing-kernels-system-wide

Let us know if this solves your question.

**Comment by Guo-Zhang** [comment]
Thanks for the reply! 

I am still confused about this guidance. If I add the python version to /usr/local/, the different Python 3.x may conflict so I am not sure how to process, especially with pyenv.

In addition, there are already a Python 2 and Python 3 in my /usr/bin/ folder, but cannot add into the Notebook.

What can I do to find the exact problem in addition?

Thanks for your help again!

**Comment by mdivk** [comment]
can you post your kernel json file here?

**Comment by Guo-Zhang** [comment]
sorry, I have given up this project, so I deleted all the settings in my cloud server. Sorry for that!

**Comment by ibre5041** [comment]
Okay I have it. When I add a new kernel it does not appear in the list. Refresh does not help, Logoff/Logon does not help, JupyterHub restart does not help. A new kernel appears in the list only when I clear borwser's cookies.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
