### ISSUE TITLE
Notebook cannot load the environment variables aumatically 

### ISSUE THREAD

**Issue by sw-gong** [jupyterhub/jupyterhub#1993]
I set my envrionment varibale in ~/.bashrc:  export QT_API=pyqt

It shows correctly in the terminal, when I ran export.

However, if I launch Jupyter Notebook, this environment variable is not set by using ! export in side Notebook.

**Comment by minrk** [comment]
This depends on how user notebooks are started. You can start notebooks in a full shell with:


```python
c.LocalProcessSpawner.shell_cmd = ['bash', '-l', '-c']
```

which will instantiate a full bash login shell for each user. This does give users control over their own server, and can potentially modify the process that is launched, so only do this if you trust your users to not attempt malicious attacks against each other.

**Comment by sw-gong** [comment]
Hi minrk, it didn't work.

I entered it in the shell. 

`
c.LocalProcessSpawner.shell_cmd = ['bash', '-l', '-c']
zsh: bad pattern: [bash,
1

**Comment by minrk** [comment]
in `jupyterhub_config.py`, then restart jupyterhub. What is your existing jupyterhub_config.py? What Spawner are you using?

**Comment by sw-gong** [comment]
@minrk  

Hi, I don't know what do you mean of restart jupyterhub, cause I am always using jupyter notebook (or these two the same?)

I never generated jupyterhub_config.py. I just tried you generate it, but not success.
➜  ~ jupyterhub --generate-config
zsh: command not found: jupyterhub

I don't know about Spawner...

---

Let's simplify it. Generally, I only launch jupyter notebook through terminal. The problem is that environment variables activated in the terminal (or shell, or the specific environment in the terminal) are not activated in jupyter notebook.

Thanks for your help all the way.

**Comment by minrk** [comment]
Sorry, I misunderstood. I thought this was an issue about JupyterHub (the multi-user notebook server), since this is an Issue on the JupyterHub repository.

Since this is a question about the regular notebook server, the answer is different. The notebook should inherit any environment variables from the parent shell process. How are you starting the notebook? If you star the notebook in a regular terminal, the environment variables will be the same. There is one exception, which is if you only have `VARIABLE=foo` and not `export VARIABLE=foo`. Only *exported* variables are passed to subprocesses.

**Comment by sw-gong** [comment]
Thanks @minrk 

I started notebook in the **shell** as I said. Definitely, variables were **exported**. Moreover, I checked **in the shell** that the environment variables **take effect** but if I **launch jupyter notebook (through command `jupyter notebook`) at the same shell**, jupyter notebook cannot load the those variables. 

I'm not sure if I make it clear now.

**Comment by rragundez** [comment]
Hi @minrk I am running JupyterHub as a service and what I need is to load environment variables defined in the user's home directory in `.bashrc` or `.bash_profile` every time a new notebook is created or when a user logs in to JupyterHub.

What you suggested: 

`c.Spawner.shell_cmd = ['bash', '-l', '-c']`

or 

`c. LocalProcessSpawner.shell_cmd = ['bash', '-l', '-c']`

does load the environment variables but only when the service starts up. So I after that I modify `.bashrc` or `.bash_profile` with another variables (e.g. `export TEST=test`), and then open a jupyter notebooks or restart a kernel or logout and login again, that variable TEST is not present in my environment variables.

Is it possible to achieve the behaviour I describe?

the use case is JupyterHub on an EMR cluster with Spark, and the AWS credentials are valid for 8 hours only so I need to be able to re-upload the AWS credentials as environment variables while the JuoyterHub service is up.

Thanks in advance!

**Comment by manics** [comment]
I'm closing this since this is a support issue with jupyter-notebook.
