### ISSUE TITLE
Add an example image of a JupyterHub announcement

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#1994]
Where applicable, I think demonstrative images can very efficiently give relevant insights in the JupyterHub documentation.

Does it make sense to add an demonstrative image of...
- [ ] ... a page announcement in [the documentation about templates](https://jupyterhub.readthedocs.io/en/latest/reference/templates.html)

**Comment by willingc** [comment]
Sounds like a nice addition @consideRatio.

**Comment by manics** [comment]
Do you still plan to do this?

**Comment by consideRatio** [comment]
Thanks @manics for the bump! It is a valid issue with a simple and concrete action point, I added a `help wanted` for now and may very well be the person to do it the next time I configure an announcement.

**Comment by manics** [comment]
Closing as we're actively discussing moving the JupyterHub announcement extension to the org or a related org
