### ISSUE TITLE
0.8.1 -> 0.9.0 breaks login

### ISSUE THREAD

**Issue by deep-42-thought** [jupyterhub/jupyterhub#1999]
**Describe the bug**
I recently updated jupyterhub (and it's database) from 0.8.1 to 0.9.0, the login screen works, but as soon as I actually log in, I get a 500 and in the logs the following stack trace:
```
[E 2018-06-20 08:48:28.202 JupyterHub web:1591] Uncaught exception GET /hub/user/erich/ (::ffff:131.35.53.156)
HTTPServerRequest(protocol='https', host='nlopc46', method='GET', uri='/hub/user/erich/', version='HTTP/1.1', remote_ip='::ffff:131.35.53.156', headers={'X-Forwarded-Host': 'nlopc46', 'X-Forwarded-Proto': 'https>
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
result = yield result
File "<string>", line 6, in _wrap_awaitable
File "/usr/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 999, in get
await self.spawn_single_user(user)
File "/usr/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 670, in spawn_single_user
await gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future)
File "<string>", line 3, in __await__
File "/usr/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 625, in finish_user_spawn
await spawn_future
File "/usr/lib/python3.6/site-packages/jupyterhub/user.py", line 486, in spawn
raise e
File "/usr/lib/python3.6/site-packages/jupyterhub/user.py", line 406, in spawn
url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
File "<string>", line 3, in __await__
RuntimeError: Task got bad yield: <tornado.concurrent.Future object at 0x7f832d3c1d30>
```
I built jupyterhub as a package for archlinux via [this PKGBUILD](https://github.com/deep-42-thought/archlinuxewe/blob/master/jupyterhub/PKGBUILD).
Not much changed there between the two versions: the version and checksum changed and two new dependencies were added.

**To Reproduce**
1. build the packages for version 0.8.1 and 0.9.0 (e.g. revisions 5fa2efbfb3d8ef843729ecd76383ad705ae44d2e and 64ea0da177dd180ae824cce72982074e64d4c001)
2. install version 0.8.1, check that it works
3. update to version 0.9.0
4. run `jupyterhub upgrade-db` to update the database
5. start jupyterhub
6. log in
7. check system log

**Expected behavior**
Login succeeds.

**Desktop (please complete the following information):**
 - OS: archlinux
 - Browser: firefox
 - Version: 0.9.0 (reverting to 0.8.1 works again)

**Comment by minrk** [comment]
What's `pip list`? jupyterhub 0.9 requires tornado 5.0. This is enforced in setup.py, but it looks like that pkgbuild drops the version requirements from the dependencies.

**Comment by deep-42-thought** [comment]
you're absolutely right: `pip list` shows tornado 4.5.3
I wasn't expecting arch to not ship the newest versions of everything.
Why does setup.py succeed in this case?
