### ISSUE TITLE
Jupyterhub options_form is not refreshed

### ISSUE THREAD

**Issue by sdesrozis** [jupyterhub/jupyterhub#2003]
I'm working on a custom spawner similar to the multi image chooser from https://github.com/ryanlovett/imagespawner. The idea is to "dynamically" deal with available images, I mean that the spawner inspects available docker images, selects images wrt a user pattern and uses options_form to list selection. My issue is options_form is created when the server is started and never refreshed. In my case, if new images are available, options_form should be refreshed, ideally automatically and without restart the server. Any idea ? Thanks in advance for your help.

**Comment by minrk** [comment]
You might want to use the `.get_options_form` method, which lets you define a dynamic options form that is allowed to change.

**Comment by sdesrozis** [comment]
Thank you for the response, I will check that and post my feedback soon.

**Comment by sdesrozis** [comment]
I used a callable options_form and it allows dynamic behaviour. Relaoding the page (for instance) will refresh scrolling items in form. Thank you again for your help !
