### ISSUE TITLE
Redirect to login page broken when using baseUrl

### ISSUE THREAD

**Issue by betatim** [jupyterhub/jupyterhub#2005]
Freshly deployed vanilla hub using the zero2jupyterhub chart (v0.7-8b9cb79) on google cloud. None standard parts are that this uses an nginx-ingress to route traffic to the hub which is at example.com/foobar.

http://example.com/foobar redirects to http://example.com/foobar/hub/foobar but http://example.com/foobar/ redirects to http://example.com/foobar/hub/login.

Via @minrk and @chicocvenancio

> Yeah, I'm guessing it's not redirecting correctly without the trailing slash. I think there's a check for if not startswith(prefix) and it probably incorrectly returns False on the edge case where the trailing slash is missing
> I think it's PrefixRedirectHandler 
>
> `base_url` is defined as having the trailing slash https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/handlers/base.py#L63

**Comment by chaoleili** [comment]
I met the same error when using baseUrl. I think is better to ensure request URL with trailing slash when matching with base_url in PrefixRedirectHandler.  PR: #2062
