### ISSUE TITLE
Rgdal in Jupyterhub Configuration Issue

### ISSUE THREAD

**Issue by Akmoore7** [jupyterhub/jupyterhub#2006]
My team and I have been trying to install Rgdal for our jupyterhub instance thats currently running on a AWS 16.04 Ubuntu instance. We are using conda to try and install these packages, as well as through our R terminal kernel. After attempting to install Rgdal (and gdalUtils) we usually get this error:

Loading required package: rgdal
Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
“there is no package called ‘rgdal’

Rgdal is currently installed in the R kernel we have set up as well as through conda, but during notebook runtime, trying to use these packages fails consistently. Any insight on what could be causing these errors?

**Comment by willingc** [comment]
Hi @Akmoore7, Sorry for the delayed response. Many of us have been traveling. 

I'm not sure what is causing your issue but perhaps take a look at the [`.libpaths()` setting](https://www.rdocumentation.org/packages/base/versions/3.5.0/topics/libPaths)

**Comment by willingc** [comment]
Closing this issue as it's been inactive for over a month. Please feel free to request that we reopen this issue, if needed. Thanks! 🌻
