### ISSUE TITLE
docs/source/images/jhub-parts.png is misleading

### ISSUE THREAD

**Issue by BerserkerTroll** [jupyterhub/jupyterhub#2019]
From this picture one may get the impression that Hub has 2 endpoints: at the top (`/hub/`) and on the right (`/api/auth`), whilst there is only one endpoint which is at `8081` port by default.

![image](https://raw.githubusercontent.com/jupyterhub/jupyterhub/f3787dd2c885d0bd9e0f521a711cc26eff46b54b/docs/source/images/jhub-parts.png)

**Comment by willingc** [comment]
Thanks for the comment. While I could see how one could feel that way, this graphic has been used for a number of years to provide a "high-level" representation of JupyterHub.

This talk gives a few minute overview of this "high-level" view: https://youtu.be/gSVvxOchT8Y?t=4m18s

I'm going to close this issue, but will tag it as *Reference* as it's good feedback for when/if we update this graphic. Thanks!
