### ISSUE TITLE
Where can a student see their grades?

### ISSUE THREAD

**Issue by maryamdev** [jupyterhub/jupyterhub#2023]
Hello! After autograding an assignment, as the Admin, I can see the grade of each student. However, where can the student see his/her grade? Thanks!

**Comment by betatim** [comment]
I think your question is about nbgrader and not jupyterhub. I would submit your issue https://github.com/jupyter/nbgrader to their repository to increase your chances of getting hold of an expert.

**Comment by maryamdev** [comment]
OK. Done. Thanks!

**Comment by betatim** [comment]
I'll close this and #2024 which I think is also something to ask in nbgrader. If you disagree please do reopen the issues.
