### ISSUE TITLE
Scalable Jupyterhub

### ISSUE THREAD

**Issue by hani1814** [jupyterhub/jupyterhub#2026]
We have been running jupyterhub / sudospawner for over a year now on a decent size edge node (52 CPUs / 248 Gbyte RAM). Our subscriber base is increasing and we have started to face operational issues such as people running python locally and gobbling up CPU and/or memory resources at the expense of others.

What options do we have:
-limit resources per spawned notebook (we are using sudospawner, i.e. running jupyter as none root)
-distribute jupyter on more than one server with a load balancer

What are our options?

Docker is still not an approved technology unfortunately

Many thanks

**Comment by ryanlovett** [comment]
The [systemd spawner](https://github.com/jupyterhub/systemdspawner) can help with resource limiting on a single node.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Thanks to all!
