### ISSUE TITLE
How to get access-token or cookie set in browser to run apis of jupyterhub ?

### ISSUE THREAD

**Issue by saurssauravjs** [jupyterhub/jupyterhub#2029]
i want to get access-token or cookie set in browser to run apis of jupyterhub in frontend. But have no clue. Can't access a httponly cookie. New to jupyterhub

**Comment by saurssauravjs** [comment]
Got it! :+1:

**Comment by willingc** [comment]
For others with the same question, the documentation on [Using JupyterHub's REST API](https://jupyterhub.readthedocs.io/en/stable/reference/rest.html) has examples for how to get a token and use it for requests.
