### ISSUE TITLE
this project's documentation is BULLSHIT

### ISSUE THREAD

**Issue by zhangxu999** [jupyterhub/jupyterhub#2031]
If you are having issues with installation or configuration, you may ask for help on the JupyterHub gitter channel or file an issue here.

**Comment by consideRatio** [comment]
@zhangxu999 I understand that you are frustrated. I personally perceive your communication as offensive and I'm worried that you have not provided concrete enough information for someone to efficiently improve this open source project.

**Comment by willingc** [comment]
@zhangxu999 All communications about Project Jupyter are expected to be respectful. It is not appropriate to use foul or offensive language. You may review our expectations for community decorum here: https://github.com/jupyter/governance/blob/master/conduct/code_of_conduct.md Any further disrespectful comments will result in the issue being locked and closed.

Many community members have contributed to this project's documentation, and we are thankful to our contributors who have taken the time to report specific issues and continue to submit pull requests as they find items that could be improved.

If you have a specific question now or in the future, please ask respectfully. Thank you.
