### ISSUE TITLE
Numba CUDA kernel: cannot print on Jupiter notebook 

### ISSUE THREAD

**Issue by mdessole** [jupyterhub/jupyterhub#2035]
Hi! 

I am a researcher at University of Padova, and I'd like to use JupiterHub for a MOOC we're organizing.

Part of the course will be about writing CUDA kernels using Numba.

**The bug**
For debugging purpose, I want the CUDA threads to print on the notebook. What happens is that CUDA kernels fail to print on the notebook, and the output of print function goes to the terminal.
Is it possible to redirect the output so that all threads' prints are displayed on the notebook? 

**The code i tried is the following**
```
import numpy as np 
import math
import numba 
from numba import cuda 

@cuda.jit
def add_kernel(x, y, out):
    tx = cuda.threadIdx.x # this is the unique thread ID within a 1D block
    ty = cuda.blockIdx.x  # Similarly, this is the unique block ID within the 1D grid
    block_size = cuda.blockDim.x  # number of threads per block
    grid_size = cuda.gridDim.x    # number of blocks in the grid
    idx = tx + ty * block_size

    if (idx == 1):
        print("This is thead ", idx) ### THIS PRINT GOES TO TERMINAL
    
    # assuming x and y inputs are same length
    if idx < x.shape[0]:
        out[idx] = x[idx] + y[idx]

n = 1000
threads_per_block = 128
blocks_per_grid = math.ceil(n/128)

x = np.arange(n).astype(np.float32)
y = 2 * x
out = np.empty_like(x)
add_kernel[blocks_per_grid, threads_per_block](x, y, out)
```

**Expected behavior**
The function add_kernel above sums two numpy array. After executing the function, Thread 1 should print 'This is thread 1'. But nothing is printed on the notebook.
In this example the output array `out` should contain only multiples of 3, in fact I have 
```
print(out[0:10])
[ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27.]
```
so the GPU is working fine.

If I run the code on a .py script from command line I get prints from CUDA kernels. If I try to execute the code on a notebook .ipynb, CUDA print is not displayed on the notebook, it appears on the terminal from where I laughed jupyter. 

**Versions**
I use Python 3.5.2, Numba 0.38, Numpy 1.14.5. 

Thank you for your help.

**Comment by minrk** [comment]
It's probably compiling it to a lower-level printf call, which writes directly to the FDs instead of the captured sys.stdout. You can try capturing C-level output in IPython with a tool like [wurlitzer](https://github.com/minrk/wurlitzer#wurlitzer).

**Comment by mdessole** [comment]
It works, thank you!

Anyway, this solution is not too elegant to see, it'll be great if this option was integrated in Numba.
