### ISSUE TITLE
does kdcAuthenticator work?

### ISSUE THREAD

**Issue by pyjones1** [jupyterhub/jupyterhub#2047]
Has anyone tested the kdcAuthenticator for kerberos? It appears to point to a non jupyterhub project and there are no recent updates and the documentation is incomplete. Can it be managed by the Jupyterhub project after verification that it actually works?

**Comment by willingc** [comment]
Hi @pyjones1 Just to clarify that the authenticator referenced above is the  kdcAuthenticator [https://github.com/bloomberg/jupyterhub-kdcauthenticator](https://github.com/bloomberg/jupyterhub-kdcauthenticator).

Bloomberg, a supporter of Project Jupyter, created the kdcAuthenticator. It may be possible with their agreement to move the authenticator to the JupyterHub.org. 

Next steps:

- [ ] Add note in README for kdcauthenticator that it is community maintained currently
- [ ] Testing by community members to determine current state of the authenticator 
- [ ] Discussion within the JupyterHub team and community about the possibility of moving the project to the JupyterHub organization.

cc/ @minrk

**Comment by zmkhazi** [comment]
I tried configuring the KDC for JupyterHub as specified in the bloomberg link.
  https://github.com/bloomberg/jupyterhub-kdcauthenticator

 I am  getting the Kerberos.GSSErrors

kerberos.GSSError: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('No key table entry found matching HTTP\\/fully.qualified.domain.name/@', 39756033))

Is there anyother way to kerborize JupyterHub.

**Comment by willingc** [comment]
Hi @zmkhazi,

You may wish to check Tableau's troubleshooting documentation as it appears to outline a resolution for the same error code: https://onlinehelp.tableau.com/current/server/en-us/kerberos_trouble.htm See *Troubleshooting the Server -> keytable entry*

Here is an example for experimenting with JupyterHub and Kerberos: https://github.com/jupyterhub/jupyterhub-example-kerberos

**Comment by ebebpl** [comment]
I have tried to install this using the instructions at https://github.com/bloomberg/jupyterhub-kdcauthenticator . However I get the same error as referenced in the issue: https://github.com/bloomberg/jupyterhub-kdcauthenticator/issues/6 . Seems there was a recent pull request   but not sure if that fixes: https://github.com/bloomberg/jupyterhub-kdcauthenticator/pull/4 . The KDCauthenticator is useful and would be good if it anyone can suggest how to make it work. Thanks.

**Comment by titan550** [comment]
I had to change some code (pull request: https://github.com/bloomberg/jupyterhub-kdcauthenticator/pull/4) to get it to work with Windows AD. It is now functional.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
