### ISSUE TITLE
Jupyterhub with Pyspark kernel 

### ISSUE THREAD

**Issue by suman724** [jupyterhub/jupyterhub#2054]
We created a kernel with the following configuration to luanch spark context with jupyter notebook

```
{
 "display_name": "spark",
 "language": "python",
 "argv": [
  "/apps/anaconda3/bin/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "env": {
  "JAVA_HOME": "/usr/java/jdk1.8.0_60",
  "SPARK_HOME": "/opt/cloudera/parcels/CDH/lib/spark/",
  "HADOOP_CONF_PATH": "/etc/hadoop/conf",
  "PYTHONPATH": "/opt/cloudera/parcels/CDH/lib/spark/python/:/opt/cloudera/parcels/CDH/lib/spark/python/lib/py4j*src.zip",
  "PYTHONSTARTUP": "/opt/cloudera/parcels/CDH/lib/spark/python/pyspark/shell.py",
  "PYSPARK_SUBMIT_ARGS": " -v --master yarn-client  --principal user@domain.com --keytab /pathto/file.keytab --queue root.etl pyspark-shell",
  "PYSPARK_PYTHON": "/apps/anaconda3/bin/python"
 }
}
```

When launch the notebook, we are seeing the following error on jupyterhub console.
```
[IPKernelApp] WARNING | Unknown error in handling PYTHONSTARTUP file /opt/cloudera/parcels/CDH/lib/spark/python/pyspark/shell.py:
```

We are using jupyterhub 0.9.1 and python 3.6. We do not see spark context getting initialized. Is there a way to debug this issue? The issue appears similar to [1295](https://github.com/jupyterhub/jupyterhub/issues/1295) but slightly different. In the case of the other issue, the problem occurred only when using Chrome. For us the issue occurs in all browsers.

**Comment by minrk** [comment]
In general, the easiest way to try to debug issues like this is to try to bypass jupyterhub. You can try launching the process directly and see if you get better input. One way that might help is to try jupyter console: `jupyter console --kernel yourkernelname` since you can see the console output there

**Comment by SivaMaplelabs** [comment]
Working with the following config.

{
 "display_name": "PySpark/Python2 (Anaconda)",
 "language": "python",
 "argv": [
  "{{ anaconda_home }}/bin/python",
  "-m",
  "ipykernel",
  "-f",
  "{connection_file}"
 ],
 "env": {
  "HADOOP_CONF_DIR":"{{ hadoop_conf_dir }}",
  "PYSPARK_PYTHON":"{{ anaconda_home }}/bin/python",
  "SPARK_HOME": "{{ wrapper_spark_home }}",
  "WRAPPED_SPARK_HOME": "{{ spark_home }}",
  "PYTHONPATH": "{{ app_packages_home }}/lib/python2.7/site-packages:{{ jupyter_extension_venv }}/lib/python2.7/site-packages:{{ spark_home }}/python:{{ spark_home }}/python/lib/py4j-0.9-src.zip",
  "PYTHONSTARTUP": "{{ spark_home }}/python/pyspark/shell.py",
  "PYSPARK_SUBMIT_ARGS": "--master yarn-client --jars {{ spark_home }}/lib/spark-examples.jar pyspark-shell"
 }
}

**Comment by willingc** [comment]
Hi @SivaMaplelabs, Thanks for submitting additional detail. For future reference...you may render long code blocks by putting it between 3 backticks ``` 

For example:

<img width="165" alt="screen shot 2018-08-27 at 13 50 35" src="https://user-images.githubusercontent.com/2680980/44685530-81405900-aa00-11e8-8327-16bec4bdb3f7.png">


This will render as a code block:

```
print("hello world")
a = 2
print(a + 100)
```

**Comment by SivaMaplelabs** [comment]
@willingc Sure. Thanks

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. If needed, please feel free to reach out on our gitter channel or leave a comment requesting this issue be reopened. Thanks to all!
