### ISSUE TITLE
[PAM Error 14] with jupyterhub 0.9.1 (working with  jupyterhub 0.8.0)

### ISSUE THREAD

**Issue by mbuffat** [jupyterhub/jupyterhub#2056]
Hi! 
I am running Jupyterhub with nbgrader on a debian server at my university. I am using PAM authentication (with an LDAP integrated in PAM)

With JupyterHub 0.8.0, the system work and new users (i.e; without a directory) are created when they log into jupyterhub.

But with the newest version JupyterHub 0.9.1, the creation of the first new user display the following error 

```
[PAM Error 14] Cannot make/remove an entry for the specified session
 Disabling PAM sessions from now on.
```
and after no new user can log into jupyterthub.

system debian 9  uptodate with python3 3.5.3
jupyterhub 0.9.1 and Jupyterhub is running as root

Thanks ,

**Comment by willingc** [comment]
Hi @mbuffat, 

To clarify, which authenticator are you using: the default authenticator in JupyterHub or the [ldapauthenticator](https://github.com/jupyterhub/ldapauthenticator)?

**Comment by mbuffat** [comment]
Hi
I am using the default authenticator (PAM) in JupyterHub and the system PAM on linux is configured to use the LDAP of my university

**Comment by minrk** [comment]
Was `pamela` upgraded, or just jupyterhub?

**Comment by rzuidhof** [comment]
Updating libsodium from 1.0.10 to 1.0.16 fixed this issue for me.

**Comment by willingc** [comment]
Thanks for sharing @rzuidhof. We appreciate you passing this along for others.

**Comment by congfairy** [comment]
could you show me how to use the default PAM?I have to specify the auth.type(github,google) ,otherwise auth.type would come out some problem.

**Comment by rzuidhof** [comment]
> Updating libsodium from 1.0.10 to 1.0.16 fixed this issue for me. And of course the other dependencies for jupyterhub.

This information was not reproducable and I was enable to pinpoint the issue. In the end I did a full 'conda update --all' and after that enabled the conda-forge channel to update jupyterhub, notebook and configurable-http-proxy

**Comment by attardi** [comment]
I have the same problem, after upgrading from 08 to 0.9.4.
I upgraded to Ubuntu 18.04 and the problem disappeared.
