### ISSUE TITLE
On a k8s hub: `groups: cannot find name for group ID 1000`

### ISSUE THREAD

**Issue by arokem** [jupyterhub/jupyterhub#2063]
## Description:

Having set up a hub on Google Cloud using the z2jh guide, whenever I open a terminal from the launcher, I get the message `groups: cannot find name for group ID 1000` before the first prompt. 

<img width="1791" alt="screen shot 2018-07-27 at 12 56 53 pm" src="https://user-images.githubusercontent.com/118582/43345338-f94c80bc-91a1-11e8-9baf-c399dd3a673d.png">

Seems related to [this question](https://unix.stackexchange.com/questions/54953/error-message-id-cannot-find-name-for-group-id-after-logging-in) and indeed: 

```
jovyan@jupyter-arokem:~$ id jovyan
uid=1000(jovyan) gid=100(users) groups=100(users)
```

And there is no 1000 in the /etc/groups file.

**Comment by consideRatio** [comment]
fixed but not released, you can set a value in config.yaml yourself though to fix this for now though:

I dont remember the capatilization, though, but make it 100 instead of 1000.

```
singleuser:
  fsGid: 100

```

**Comment by arokem** [comment]
Thanks! This suggests you got the capitalization right: http://zero-to-jupyterhub.readthedocs.io/en/latest/reference.html#hub-fsgid

**Comment by arokem** [comment]
Yep. That works!
