### ISSUE TITLE
JupyterHub K8s has no default services - Fails with AttributeError exception

### ISSUE THREAD

**Issue by sc250024** [jupyterhub/jupyterhub#2073]
Greetings,

After following the [Zero to K8s](http://zero-to-jupyterhub.readthedocs.io/en/latest/index.html) guide for JupyterHub, I'm having trouble even getting the corresponding `hub` pods to run. They fail with the following error:

```
[E 2018-08-07 10:27:07.607 JupyterHub app:1623]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1620, in launch_instance_async
        yield self.initialize(argv)
      File "/usr/lib/python3.6/types.py", line 204, in __next__
        return next(self.__wrapped)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1358, in initialize
        self.load_config_file(self.config_file)
      File "&lt;decorator-gen-5&gt;", line 2, in load_config_file
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 598, in load_config_file
        raise_config_file_errors=self.raise_config_file_errors,
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/usr/local/lib/python3.6/dist-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/srv/jupyterhub_config.py", line 240, in &lt;module&gt;
        service.setdefault('name', name)
    AttributeError: 'NoneType' object has no attribute 'setdefault'
```

**Describe the bug**
I know **_where_** the problem lies, but I'm not sure what is required to make it functioning.

In the `configmap.yaml` template, there's this block that configures the `hub.services` part:

```yaml
  hub.services: |
    # include hub.services *except* api_tokens
    {{ range $name, $service := .Values.hub.services -}}
    {{$name}}:
      {{ range $key, $value := $service -}}
      {{ if ne $key "apiToken" -}}
      # Use toJson since values can be more than just strings
      {{$key}}: {{ toJson $value }}
      {{- end }}
      {{ end }}
    {{ end }}
  {{- end }}
  {{ if .Values.hub.extraConfig -}}
  {{ $extraConfigType := typeOf .Values.hub.extraConfig -}}
  {{ if eq $extraConfigType "string" -}}
```

The exception above clearly happens because I'm not passing any values into `hub.services` in my `config.yaml` file.

**To Reproduce**
Simply install version `v0.6` of the chart with the [secrets configured like in the documentation](http://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub.html):

```bash
helm upgrade \
--install jupyterhub \
--namespace jupyterhub \
--timeout 600 \
--values config.yaml \
--values secret.yaml \
--version=v0.6 \
--wait \
jupyterhub/jupyterhub
```

config.yaml

```yaml
hub:
  db:
    type: "sqlite-memory"
```

secret.yaml

```yaml
hub:
  cookieSecret: "<some-value>"
  services:
    binder:
      apiToken: "<some-value>"
proxy:
  secretToken: "<some-value>"
```

**Expected behavior**
JupyterHub is a large project, so naturally for everything to work "out of the box" as you need it is difficult. I would only except the basic functionality to work out of the box, for a UI to appear (through the proxy public endpoint or Ingress resource).

**Desktop (please complete the following information):**
Kuberentes cluster version: 1.9.10
JupyterHub chart version: v0.6
Helm version:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

**Comment by sc250024** [comment]
@consideRatio Thank you for the quick reply! Let me know if you need any testing done.

**Comment by sc250024** [comment]
@consideRatio Was there any discoveries on this?

**Comment by sc250024** [comment]
Thanks @willingc , you're right, we used the 0.7 version of the Helm chart, and it worked like a charm. Right now we just have JupyterHub running. Can I take the `values.yaml` file I've configured for the JupyterHub chart, and just use it verbatim the BinderHub chart nested under the `jupyterhub` key? 

Something like this?:

```yaml
jupyterhub:
  <everything-from-existing-jupyterhub-values-yaml-file>
```

**Comment by consideRatio** [comment]
@sc250024 ah great it works now! I could not see any faults with the configuration you provided.

I think you can do that, I'm not very familiar with the binderhub chart, but it relies on the jupyterhub chart I'm quite confident. If you want to provide values to a nested chart, you do exactly what you suggest to do.
