### ISSUE TITLE
Running jupyter notebook sessions as root in jupyterhub

### ISSUE THREAD

**Issue by khordadi** [jupyterhub/jupyterhub#2074]
I use a networking library (in python 2) which needs root privilege to run, I can achieve this with the jupyter notebook by running:
`sudo jupyter-notebook --allow-root`
but in jupyterhub, I don't know how to achieve this. 
Example:
**BAD**
![image](https://user-images.githubusercontent.com/30090310/43837528-0dbe96b2-9b2e-11e8-8cdf-d1bf0ac1c1b7.png)
**GOOD**
![image](https://user-images.githubusercontent.com/30090310/43837563-21c0b23a-9b2e-11e8-9ce9-4f038aaea0be.png)

**Comment by minrk** [comment]
Do you want all users to run as root? Or do you want to be able to login as root and start a server? Logging in as root should work as long as there is a root password. If you want all users (or some users) to run as root, you can customize the Spawner to change what uid is passed to setuid.

**Comment by jhermann** [comment]
> I use a networking library (in python 2) which needs root privilege to run

Which library is that? Anyway, if it uses system tools (parsing their output), then a customs sudo configuration is a better solution.

**Comment by khordadi** [comment]
> Do you want all users to run as root?

In my case, yes.



> you can customize the Spawner to change what uid is passed to setuid.

How? Should I write my own custom config file(s) or just modify existing files?

**Comment by willingc** [comment]
@khordadi This [section of the documentation](https://jupyterhub.readthedocs.io/en/stable/reference/config-sudo.html?highlight=setuid#overview)  explains how to setup users with particular privileges.

> create a dedicated user with sudo access restricted to launching and monitoring single-user servers.

**Comment by willingc** [comment]
@khordadi As an FYI, it looks like mininet's latest development release supports Python 3 https://github.com/mininet/mininet/releases/tag/2.3.0d4 https://github.com/mininet/mininet/pull/817
