### ISSUE TITLE
Storing user data inside an elastic file system

### ISSUE THREAD

**Issue by danielrychel** [jupyterhub/jupyterhub#2075]
I have implemented jupyterhub on a single instance in AWS on an Ubuntu 16.04 server and using a sudospawner. Everything was working very well, but in an attempt to reduce cost I am trying to change this implementation to use AWS auto-scaling. My first step of this process is to move my user data to an elastic file system so that multiple instances of jupyterhub can all access the same data. Originally, I copied over the /home directory which contains each user directory and all of the files they possess. It also contains all the files necessary to start jupyterhub (because those are all located in ubuntu). I mounted the EFS onto the /home directory of an empty jupyterhub instance - it contains only  the files to run jupyterhub and no user information. When I tried starting jupyterhub it told me to run `jupyterhub upgrade-db` and when I run that, I get the following output:
```
[E 2018-08-08 21:10:17.498 alembic.util.messaging messaging:56] Can't locate revision identified by '896818069c98'
  FAILED: Can't locate revision identified by '896818069c98'
[E 2018-08-08 21:10:17.548 JupyterHub app:1623]
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/jupyterhub/app.py", line 1621, in launch_instance_async
        yield self.start()
      File "/home/ubuntu/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/asyncio/futures.py", line 294, in result
        raise self._exception
      File "/home/ubuntu/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/jupyterhub/app.py", line 1511, in start
        self.subapp.start()
      File "/home/ubuntu/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/jupyterhub/app.py", line 179, in start
        dbutil.upgrade_if_needed(hub.db_url, log=self.log)
      File "/home/ubuntu/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/jupyterhub/dbutil.py", line 130, in upgrade_if_needed
        upgrade(db_url)
      File "/home/ubuntu/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/jupyterhub/dbutil.py", line 89, in upgrade
        ['alembic', '-c', alembic_ini, 'upgrade', revision]
      File "/home/ubuntu/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/subprocess.py", line 271, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['alembic', '-c', '/tmp/tmp7aen0w4y/alembic.ini', 'upgrade', 'head']' returned non-zero exit status 255
```
However, if I mount this file system in its own directory (/home/ubuntu/efs), I am able to successfully run jupyterhub from the home directory- where it already existed- AND from the efs folder but in both cases I cannot see the users from the file system because those users are not located on the home directory. How can I tell jupyterhub where to read user data? If the /home directory is the only place, then how do I resolve this error message? I'm open to any advice, thank you for your time!

**Comment by minrk** [comment]
`Can't locate revision identified by '896818069c98'` suggests that `jupyterhub upgrade-db` is being run by jupyterhub 0.8 and not 0.9. That might be a red herring. Is it possible that jupyterhub is different versions in the different places?

**Comment by danielrychel** [comment]
Yes that sounds correct- I changed it so that there is only 1 copy and it reads user files from the efs folder. I do have one more question: is it possible to run the same configuration of jupyterhub on multiple servers and route different users to different servers? I want to spawn new servers when there is heavy traffic and move those users to the new servers but I am experiencing difficulty on how I would accomplish this.

**Comment by jhermann** [comment]
@danielrychel check out https://www.youtube.com/watch?v=omxY1YsPGUc for ideas

Doing it dynamically for *existing* active users might be tricky. What you *can* do is put new users on a new server when existing servers are on the limit. Downsizing can happen via idle culling, and also routing users to the "primary" server again when load drops there. Eventually sur-plus servers will dry out can can be scrapped.

**Comment by mausch** [comment]
FWIW I set this up a couple of days ago and it was very easy to do on kubernetes using the official helm chart https://zero-to-jupyterhub.readthedocs.io/en/latest/

1. Create an EFS filesystem
1. Install https://github.com/helm/charts/tree/master/stable/efs-provisioner on your cluster linking it to the EFS filesystem you just created.
1. Make sure your kubernetes workers have the necessary permissions to access EFS
1. Configure the jupyterhub helm values with:
```
singleuser:
  storage:
    dynamic:
      storageClass: <provisionerName_configured_in_the_efs_provisioner_helm_values>
```

That's it. Of course you have to tell your users to back up their current persistent home directories before doing this.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
