### ISSUE TITLE
How to connect a user without using login interface ?

### ISSUE THREAD

**Issue by KOSSOKO** [jupyterhub/jupyterhub#2076]
Hi all, we are developing a platform for  ESA scientists. We are going to deploy jupytherhub in order to allow users to have their own workspace and do what they want inside their workspace. How could we do to allow the user of our platform to connect to their workspace without having to authenticate with the user interface of Jupyter.
We want when the user is connected to our platform to access to Jupyter with just a token for example or something like that.

Is it possible ? Do you have any solution to suggest please ? Thanks in advance

**Comment by KOSSOKO** [comment]
Up please

**Comment by willingc** [comment]
@KOSSOKO Many folks use the [OAuthenticator](https://jupyterhub.readthedocs.io/en/stable/reference/authenticators.html#the-oauthenticator) to authenticate with GitHub or Google as well as others. That allows users to quickly access their notebook environment without have to type in a login or password. 

Thanks for the question.
