### ISSUE TITLE
HTTP 599 Connection refused

### ISSUE THREAD

**Issue by Alramzey** [jupyterhub/jupyterhub#2077]
Hi,

I want to run a jupyterhub as less privileged user so people in LAN can connect. **But** , I can't get connection wherever I'm listening. If I use deprecated proxy_api_ip and proxy_api_port we could connect to it locally, after i switched to not-deprecated ConfigureHTTPProxy.api_url all I get is HTTP 599 connection refused. I have confirmed that nothing is blocking at the system firewall or network firewall/switch level.
I launch hub with : 
` sudo -u rhea jupyterhub --JupyterHub.bind_url=172.x.y.z:2222 --JupyterHub.ConfigurableHTTPProxy.api_url==172.x.y.z:2222 --JupyterHub.spawner_class=sudospawner.SudoSpawner --no-ssl --log-level=DEBUG`

And thats the output:
```
[D 2018-08-09 12:10:59.591 JupyterHub application:555] Looking for jupyterhub_config in /etc/jupyterhub
[I 2018-08-09 12:10:59.592 JupyterHub app:1667] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.1
[I 2018-08-09 12:10:59.592 JupyterHub app:1667] Using Spawner: sudospawner.spawner.SudoSpawner
[I 2018-08-09 12:10:59.595 JupyterHub app:1014] Loading cookie_secret from /etc/jupyterhub/jupyterhub_cookie_secret
[D 2018-08-09 12:10:59.595 JupyterHub app:1069] Connecting to db: sqlite:///jupyterhub.sqlite
[D 2018-08-09 12:10:59.612 JupyterHub orm:685] database schema version found: 896818069c98
[I 2018-08-09 12:10:59.616 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[W 2018-08-09 12:10:59.617 JupyterHub app:1171] No admin users, admin interface will be unavailable.
[W 2018-08-09 12:10:59.617 JupyterHub app:1172] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-08-09 12:10:59.617 JupyterHub app:1199] Not using whitelist. Any authenticated user will be allowed.
[D 2018-08-09 12:10:59.646 JupyterHub app:1487] Loaded users:

[I 2018-08-09 12:10:59.654 JupyterHub app:1849] Hub API listening on http://127.0.0.1:8081/172.x.y.z:2222/hub/
[W 2018-08-09 12:10:59.654 JupyterHub proxy:464] Found proxy pid file: /etc/jupyterhub/jupyterhub-proxy.pid
[W 2018-08-09 12:10:59.654 JupyterHub proxy:481] Proxy still running at pid=14970
[W 2018-08-09 12:11:00.656 JupyterHub proxy:496] Stopped proxy at pid=14970
[D 2018-08-09 12:11:00.656 JupyterHub proxy:512] Removing proxy pid file jupyterhub-proxy.pid
[W 2018-08-09 12:11:00.657 JupyterHub proxy:552] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2018-08-09 12:11:00.657 JupyterHub proxy:554] Starting proxy @ 172.x.y.z:2222
[D 2018-08-09 12:11:00.657 JupyterHub proxy:555] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '80', '--api-ip', '', '--api-port', '80', '--error-target', 'http://127.0.0.1:8081/172.x.y.z:2222/hub/error']
[D 2018-08-09 12:11:00.660 JupyterHub proxy:504] Writing proxy pid file: jupyterhub-proxy.pid
12:11:01.064 - info: [ConfigProxy] Proxying http://*:80 to (no default)
12:11:01.066 - info: [ConfigProxy] Proxy API at http://localhost:80/api/routes
12:11:01.068 - error: [ConfigProxy] Uncaught Exception Error: listen EADDRINUSE 127.0.0.1:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1517:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
[D 2018-08-09 12:11:01.487 JupyterHub proxy:590] Proxy started and appears to be up
[D 2018-08-09 12:11:01.488 JupyterHub proxy:296] Fetching routes to check
[D 2018-08-09 12:11:01.490 JupyterHub proxy:670] Proxy: Fetching GET 172.x.y.z:2222/api/routes
[E 2018-08-09 12:11:01.491 JupyterHub app:1952]
    Traceback (most recent call last):
      File "/usr/share/anaconda3/lib/python3.6/site-packages/jupyterhub/app.py", line 1950, in launch_instance_async
        await self.start()
      File "/usr/share/anaconda3/lib/python3.6/site-packages/jupyterhub/app.py", line 1895, in start
        await self.proxy.check_routes(self.users, self._service_map)
      File "/usr/share/anaconda3/lib/python3.6/site-packages/jupyterhub/proxy.py", line 57, in locked_method
        return await method(*args, **kwargs)
      File "/usr/share/anaconda3/lib/python3.6/site-packages/jupyterhub/proxy.py", line 297, in check_routes
        routes = await self.get_all_routes()
      File "/usr/share/anaconda3/lib/python3.6/site-packages/jupyterhub/proxy.py", line 717, in get_all_routes
        resp = await self.api_request('', client=client)
      File "/usr/share/anaconda3/lib/python3.6/site-packages/jupyterhub/proxy.py", line 678, in api_request
        result = await client.fetch(req)
    tornado.curl_httpclient.CurlError: HTTP 599: Failed to connect to 172.x.y.z port 2222: Connection refused

[D 2018-08-09 12:11:01.493 JupyterHub application:647] Exiting application: jupyterhub

```

Anyone, anything?

**Comment by YborBorn** [comment]
Hello.  I'm having this same issue.  I'm inside a corporate firewall and have a server box running Ubuntu 10.04LTS, Anaconda3, iPython, and JupyterHub.  I've configured my JupyterHub config file as (and please forgive my Philistine formatting... I'm trying to debug this so all my settings are at  the top of my config and I've anonymized some of the sensitive proxy and login terms ):

c.JupyterHub.ip = '166.17.125.77'
c.JupyterHub.port = 8000
c.JupyterHub.hub_ip = '0.0.0.0'
c.JupyterHub.hub_port = 8001
c.JupyterHub.hub_bind_url = 'http://127.0.0.1:8081'
c.JupyterHub.allow_named_servers = True
c.JupyterHub.cookie_secret_file = '/srv/jupyterhub/jupyterhub_cookie_secret'
c.JupyterHub.ssl_cert = '/home/lmco/pki/certs/MyCert.cer' 
c.JupyterHub.ssl_key = '/home/lmco/pki/certs/MyCert.pem'
c.JupyterHub.ssl_key = '/home/lmco/pki/certs/MyCert.key'
c.JupyterHub.proxy_auth_token = <a random number I generated>
c.ConfigurableHTTPProxy.should_start = False
c.ConfigureHTTPProxy.api_url=<my corporate proxy setting>
c.LocalAuthenticator.create_system_users = True
c.Authenticator.whitelist = {'user1', 'user2', 'user3', 'user4'}
c.Authenticator.admin_users = {'user1'}
c.Spawner.ip = '127.0.0.1'
c.Spawner.cmd = ['/home/user1/anaconda3/bin/jupyterhub-singleuser']
c.PAMAuthenticator.check_account = True
c.PAMAuthenticator.encoding = 'utf8'
c.PAMAuthenticator.open_sessions = True
c.PAMAuthenticator.service = 'login'

I'm launching the hub with: 
/home/user1/anaconda3/bin/jupyterhub -f /etc/jupyter/jupyterhub_config.py --no-ssl --log-level=DEBUG

Here's the error I'm seeing:
 File "/home/user1/anaconda3/lib/python3.6/site-packages/jupyterhub/proxy.py", line 694, in api_request
        result = await client.fetch(req)
    tornado.curl_httpclient.CurlError: HTTP 599: Failed to connect to 127.0.0.1 port 8001: Connection refused
[D 2018-11-23 10:28:22.327 JupyterHub application:647] Exiting application: jupyterhub

Thanks in advance!

**Comment by YborBorn** [comment]
So, I've done a bit more digging and testing.  If I comment out the c.JupyterHub.ssl_key line, the jupyterhub starts and I, as the admin, can remotely log into the server and run some iPython, BUT none of the other users can.  Here's my question: The ssl key is defined as my ssh public key, correct, or is it a .key file generated by my .cer or .pem certificates?  I'm probably a little confused here as to exactly what the ssl_key is supposed to point to. (I had tried to generate an ssl key - 'openssl x509 -outform der -in My_ssl.cer -out My_ssl.key', but that didn't get me any farther).  Thanks.
