### ISSUE TITLE
How to disable TLS 1.0?

### ISSUE THREAD

**Issue by eze1981** [jupyterhub/jupyterhub#2084]
Hi,

I'm trying to find out how to configure the configurable-http-proxy to disable support for TLS v1.0. Looks like I should use '--ssl-protocol TLSv1.2', but the proxy it's being started by the hub and I have no chance to tweak those settings in jupyterhub config file. So, what should I do to disable TLS v1.0 on JupyterHub?

Thanks,
Ezequiel

**Comment by minrk** [comment]
What version of the nodejs runtime are you using (`node -v`)?

You should be able to set the command CHP is started with via:

```python
c.ConfigurableHTTPProxy.command = ['configurable-http-proxy', '--ssl-protocol=TLSv1.2']
```

**Comment by eze1981** [comment]
Hi @minrk,

This is what I used:

`c.ConfigurableHTTPProxy.command = ['configurable-http-proxy', '--ssl-protocol', 'TLSv1_2']`

Thank you!

**Comment by suryag10** [comment]
> Hi @minrk,
> 
> This is what I used:
> 
> `c.ConfigurableHTTPProxy.command = ['configurable-http-proxy', '--ssl-protocol', 'TLSv1_2']`
> 
> Thank you!

TLSv1_2 is correct not TLSv1.2

**Comment by stevenrbrandt** [comment]
I've tried the advice I found here, but security scans say TLS 1.0 is still enabled. Any ideas?

**Comment by suryag10** [comment]
while starting the proxy, following should be the options:
  ARGS="--api-ip=0.0.0.0 --ip=0.0.0.0 --api-port=${JHUB_PROXY_API_PORT} --default-target=http://${HUB_SERVICE_HOST}:${HUB_SERVICE_PORT} --error-target=http://${HUB_SERVICE_HOST}:${HUB_SERVICE_PORT}/hub/error --port=${JHUB_PROXY_PUBLIC_PORT_HTTPS} --redirect-port=${JHUB_PROXY_PUBLIC_PORT} --redirect-to=${JHUB_PROXY_PUBLIC_PORT_HTTPS} --ssl-key=${JHUB_SSL_KEY} --ssl-cert=${JHUB_SSL_CERT} --log-level=${LOG_LEVEL} --ssl-protocol=TLSv1_2"

let me know, if u need more info.

**Comment by stevenrbrandt** [comment]
Thanks. It turns out that it did work, the program I was using to check TLS was at fault. :)
