### ISSUE TITLE
Anyway to define custom template key from pre_spawn_hook in order to be applied by default_url.

### ISSUE THREAD

**Issue by jason4zhu** [jupyterhub/jupyterhub#2087]
I intend to customize my default_url not only by {username}, but also my customized variable from pre_spawn_hook as shown below:

```
def my_hook(spawner):
    ...
    my_custom_variable=XXX
c.LocalProcessSpawner.default_url='/tree/{my_custom_variable}/{username}'
c.Spawner.pre_spawn_hook = my_hook    
```

any idea how I could implement it in jupyterhub_config.py? Thanks

**Comment by minrk** [comment]
Yes, you can set the default_url directly in pre_spawn_hook, implementing the templating yourself:

```python
def my_hook(spawner):
    spawner.default_url = '/tree/customstuff/{name}'.format(name=spawner.user.name)
```
