### ISSUE TITLE
JupyterHub Kerberos Error : kerberos.GSSError

### ISSUE THREAD

**Issue by zmkhazi** [jupyterhub/jupyterhub#2088]
I tried configuring JupyterHub using this as a reference.
https://github.com/bloomberg/jupyterhub-kdcauthenticator

I am encountering the following errors.

kerberos.GSSError: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('No key table entry found matching HTTP\\/fully.qualified.domain.name/@', 39756033))

Any help on this is appreciated.

**Comment by willingc** [comment]
Hi @zmkhazi I've responded to your issue in this message: https://github.com/jupyterhub/jupyterhub/issues/2047#issuecomment-41330002

I'm going to close this issue as a duplicate of #2047's conversation. Please continue asking questions on the existing issue. Thanks.
