### ISSUE TITLE
JupyterHub integration with Knox

### ISSUE THREAD

**Issue by zmkhazi** [jupyterhub/jupyterhub#2090]
Has anybody had success integrating JupyterHub with Knox for Hadoop access ?

**Comment by minrk** [comment]
Not to my knowledge, but this could be a cool project!

**Comment by willingc** [comment]
This would be a good project for someone looking for a more in-depth issue to work on.

**Comment by StefanPapp** [comment]
Any updates on that?

**Comment by willingc** [comment]
@StefanPapp I'm not aware of any Knox and JupyterHub integration. We recently added some additional docs about Hadoop if you are interested: https://jupyterhub-yarnspawner.readthedocs.io/en/latest/

**Comment by zoltanctoth** [comment]
As of Knox 1.3 integration doesn't seem to be feasible.

JupyterHub requires trailing slashes in URLs and Knox has a bug which makes Knox remove trailing slashes from Urls. This contradiction causes a redirect loop.

Ref: 
https://github.com/jupyterhub/jupyterhub/blob/1.1.0/jupyterhub/handlers/base.py#L1576-L1581
https://issues.apache.org/jira/browse/KNOX-799
https://issues.apache.org/jira/browse/KNOX-899

**Comment by zjffdu** [comment]
Any update on this issue ?

**Comment by manics** [comment]
Hi! Since this issue was originally started we've moved support and other general questions to the [Jupyter community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions. Hope you understand 😀.
