### ISSUE TITLE
bash_profile path is not taken by jupyterhub

### ISSUE THREAD

**Issue by Saranya411** [jupyterhub/jupyterhub#2091]
Hi Team,

We have installed  jupyterhub and trying to connect netezza from jupyterhub

we are getting below error

Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '/usr/local/nz/lib64/libnzodbc.so' : file not found (0) (SQLDriverConnect)")

I have my library path set in my bash_profile file and we are able to connect it from command line.

My jupyterhub version is 0.91. Can you please help us on this asap ?

Thanks,
Saranya

**Comment by willingc** [comment]
Hello @Saranya411,

For us to help you, we will need additional information about your jupyterhub configuration and operating environment as well as a more complete error log. Thanks!

**Comment by jhermann** [comment]
Have a launcher script and `export LD_LIBRARY_PATH=…` in it, before starting `juyterhub`.

**Comment by jhermann** [comment]
Have a launcher script and `export LD_LIBRARY_PATH=…` in it, before starting `juyterhub`. Or fix your `ld.so.conf`.

**Comment by Saranya411** [comment]
Hi All,

Thanks for all your reply. It worked by adding  the line  in the c.LocalProcessSpawner.shell_cmd = ['bash', '-l', '-c'] in jupyetrhub config file. Hence closing this issue.
