### ISSUE TITLE
Defining and Changing Storage Location and Name

### ISSUE THREAD

**Issue by AcademicAdmin** [jupyterhub/jupyterhub#2095]
Hello,

I am setting up Jupyterhub in an academic environment with Docker containers, local storage, and using LTI to authenticate. The system is up and running and the LTI connection is in place and authenticates correctly. However, the docker containers that are created aren't being named in any recognizable fashion. Each container has a long unique name, followed by the directory structure defined in the docker image.

Is there a ways to configure Jupyterhub and Docker to use a more recognizable naming scheme? I would like either the container to be named after the student login, or at least have the directory structure in the container include the student login name. Instructors will need to be able to differentiate between the student containers to distribute and collect work.

Thank you.

**Comment by AcademicAdmin** [comment]
I have been successful in creating directories for new users in a location of my choosing. The hook defined at the following URL was of great help: https://github.com/jupyterhub/jupyterhub/tree/master/examples/bootstrap-script

However, the directories created are a UUID from the LTI connection. Does anyone know the other variables available to spawner.user? I know that our LTI connection is also sending role and email data, so we should have access to those options as well, but the variable to use is not readily apparent.

Thank you.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
