### ISSUE TITLE
Singleuser services?

### ISSUE THREAD

**Issue by kalugny** [jupyterhub/jupyterhub#2099]
Hi,
First, thanks for all the great work on Jupyterhub.

Is it possible to setup single user services? i.e additional services that run on the singleuser machine and use the Hub authentication?

Specifically, I want to setup RStudio Server on the same machine.
I've managed to do it with an Nginx reverse proxy, but I can't use the Hub authentication.

Thanks a lot!

**Comment by ryanlovett** [comment]
I think you're looking for [jupyter server extensions](https://jupyter-notebook.readthedocs.io/en/stable/extending/handlers.html)? 

If so, [nbrsessionproxy](https://github.com/jupyterhub/nbrsessionproxy) may do what you want.
