### ISSUE TITLE
500 : Internal Server Error  

### ISSUE THREAD

**Issue by srican** [jupyterhub/jupyterhub#2100]
I am able to start up jupyterhub and login to it using my network username password.

However , I am greeted with the following message:

**500 : Internal Server Error 

Failed to start your server on the last attempt. Please contact admin if the issue persists. 

You can try restarting your server from the home page.** 

The unix shell shows the following:
[I 2018-08-21 11:28:09.525 JupyterHub app:1906] JupyterHub is now running at http://10.98.92.202:8000/
[I 2018-08-21 11:28:52.255 JupyterHub log:158] 302 GET / -> /hub (@10.10.3.43) 0.63ms
[I 2018-08-21 11:28:52.264 JupyterHub log:158] 302 GET /hub -> /hub/ (@10.10.3.43) 0.35ms
[W 2018-08-21 11:28:52.297 JupyterHub base:242] Invalid or expired cookie token
[I 2018-08-21 11:28:52.297 JupyterHub log:158] 302 GET /hub/ -> /hub/login (@10.10.3.43) 0.76ms
[I 2018-08-21 11:28:52.367 JupyterHub log:158] 200 GET /hub/login (@10.10.3.43) 19.66ms
[I 2018-08-21 11:28:57.621 JupyterHub base:499] User logged in: siyer
[I 2018-08-21 11:28:57.621 JupyterHub log:158] 302 POST /hub/login?next= -> /user/siyer/ (siyer@10.10.3.43) 130.42ms
[I 2018-08-21 11:28:57.707 JupyterHub log:158] 302 GET /user/siyer/ -> /hub/user/siyer/ (@10.10.3.43) 0.33ms
[W 2018-08-21 11:28:57.889 JupyterHub auth:642] Failed to open PAM session for siyer: [PAM Error 14] Cannot make/remove an entry for the specified session
[W 2018-08-21 11:28:57.889 JupyterHub auth:643] Disabling PAM sessions from now on.
[I 2018-08-21 11:28:57.894 JupyterHub spawner:1099] Spawning jupyterhub-singleuser --port=19601
Failed to set groups [Errno 1] Operation not permitted
[E 2018-08-21 11:28:57.901 JupyterHub user:474] Unhandled error starting siyer's server: [Errno 2] No such file or directory: 'jupyterhub-singleuser': 'jupyterhub-singleuser'
[E 2018-08-21 11:28:57.912 JupyterHub web:1670] Uncaught exception GET /hub/user/siyer/ (10.10.3.43)
    HTTPServerRequest(protocol='http', host='10.98.92.202:8000', method='GET', uri='/hub/user/siyer/', version='HTTP/1.1', remote_ip='10.10.3.43')
    Traceback (most recent call last):
      File "/opt/rh/rh-python36/root/lib64/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 1052, in get
        await self.spawn_single_user(user)
      File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 705, in spawn_single_user
        timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
      File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
        await spawn_future
      File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/jupyterhub/user.py", line 486, in spawn
        raise e
      File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/jupyterhub/user.py", line 406, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/jupyterhub/spawner.py", line 1109, in start
        self.proc = Popen(cmd, **popen_kwargs)
      File "/opt/rh/rh-python36/root/lib64/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/opt/rh/rh-python36/root/lib64/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'jupyterhub-singleuser': 'jupyterhub-singleuser'

**Comment by rollbackchen** [comment]
spawner can't find the _jupyterhub-singleuser.sh_ file

**Comment by srican** [comment]
I made some changes to the setup and modified the config file to start logging.

I am getting same error on restart -- but here is extract from the log

I can't figure out what is happening at 16:12:31 .. what do I need to do to fix it?

s
[C 2018-08-22 16:11:59.341 JupyterHub app:1923] Received SIGTERM, shutting down
[I 2018-08-22 16:11:59.342 JupyterHub app:1700] Cleaning up single-user servers...
[I 2018-08-22 16:11:59.343 JupyterHub proxy:619] Cleaning up proxy[277151]...
[I 2018-08-22 16:11:59.343 JupyterHub app:1733] ...done
[I 2018-08-22 16:12:26.441 JupyterHub app:1667] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.2
[I 2018-08-22 16:12:26.441 JupyterHub app:1667] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.2
[I 2018-08-22 16:12:26.442 JupyterHub app:1014] Loading cookie_secret from /opt/rh/rh-python36/root/usr/etc/jupyterhub/jupyterhub_cookie_secret
[I 2018-08-22 16:12:26.456 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[W 2018-08-22 16:12:26.457 JupyterHub app:1171] No admin users, admin interface will be unavailable.
[W 2018-08-22 16:12:26.457 JupyterHub app:1172] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-08-22 16:12:26.457 JupyterHub app:1199] Not using whitelist. Any authenticated user will be allowed.
[W 2018-08-22 16:12:26.483 JupyterHub app:1513] Deleting OAuth client jupyterhub-user-siyer
[I 2018-08-22 16:12:26.494 JupyterHub app:1849] Hub API listening on http://10.98.92.202:8081/hub/
[W 2018-08-22 16:12:26.495 JupyterHub proxy:560] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2018-08-22 16:12:26.495 JupyterHub proxy:562] Starting proxy @ http://10.98.92.202:8000/
[I 2018-08-22 16:12:26.686 JupyterHub proxy:301] Checking routes
[I 2018-08-22 16:12:26.686 JupyterHub proxy:370] Adding default route for Hub: / => http://10.98.92.202:8081
[I 2018-08-22 16:12:26.690 JupyterHub app:1906] JupyterHub is now running at http://10.98.92.202:8000/
[I 2018-08-22 16:12:31.097 JupyterHub log:158] 302 GET / -> /hub (@10.10.3.43) 0.59ms
[I 2018-08-22 16:12:31.107 JupyterHub log:158] 302 GET /hub -> /hub/ (@10.10.3.43) 0.38ms
[I 2018-08-22 16:12:31.121 JupyterHub log:158] 302 GET /hub/ -> /user/siyer/ (siyer@10.10.3.43) 5.79ms
[I 2018-08-22 16:12:31.129 JupyterHub log:158] 302 GET /user/siyer/ -> /hub/user/siyer/ (@10.10.3.43) 0.33ms
_**[W 2018-08-22 16:12:31.248 JupyterHub auth:642] Failed to open PAM session for siyer: [PAM Error 14] Cannot make/remove an entry for the specified session**_
[W 2018-08-22 16:12:31.248 JupyterHub auth:643] Disabling PAM sessions from now on.
[I 2018-08-22 16:12:31.253 JupyterHub spawner:1099] Spawning jupyterhub-singleuser --port=61755 '--notebook-dir="~/notebooks"'
[E 2018-08-22 16:12:31.260 JupyterHub user:474] Unhandled error starting siyer's server: Exception occurred in preexec_fn.
[E 2018-08-22 16:12:31.270 JupyterHub web:1670] Uncaught exception GET /hub/user/siyer/ (10.10.3.43)
    HTTPServerRequest(protocol='http', host='10.98.92.202:8000', method='GET', uri='/hub/user/siyer/', version='HTTP/1.1', remote_ip='10.10.3.43')
    Traceback (most recent call last):
      File "/opt/rh/rh-python36/root/lib64/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 1052, in get
        await self.spawn_single_user(user)
      File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 705, in spawn_single_user
        timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
      File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
        await spawn_future
      File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/jupyterhub/user.py", line 486, in spawn
        raise e
      File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/jupyterhub/user.py", line 406, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/jupyterhub/spawner.py", line 1109, in start
        self.proc = Popen(cmd, **popen_kwargs)
      File "/opt/rh/rh-python36/root/lib64/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/opt/rh/rh-python36/root/lib64/python3.6/subprocess.py", line 1345, in _execute_child
        raise child_exception_type(err_msg)
    subprocess.SubprocessError: Exception occurred in preexec_fn.

[E 2018-08-22 16:12:31.294 JupyterHub log:150] {
      "X-Forwarded-Host": "10.98.92.202:8000",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "10.10.3.43",
      "Cookie": "jupyterhub-hub-login=\"2|1:0|10:1534876179|20:jupyterhub-hub-login|44:Y2E3NGIxNGQ4ZTg4NDcwNGFlZGU1ZDM2MjkwNmIzZDY=|2e3e2ba88564281be0fcf84136bd8d2175c28a72a048869c29894e5c754d9f72\"",
      "Connection": "close",
      "Host": "10.98.92.202:8000",
      "Accept-Encoding": "gzip, deflate",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko",
      "Accept-Language": "en-US",
      "Accept": "text/html, application/xhtml+xml, */*"
    }
[E 2018-08-22 16:12:31.294 JupyterHub log:158] 500 GET /hub/user/siyer/ (siyer@10.10.3.43) 156.34ms
[I 2018-08-22 16:17:26.694 JupyterHub proxy:301] Checking routes

**Comment by willingc** [comment]
Hi @srican, I would check to see if you have a valid token and that you have OAuth set up correctly for the hub. Here is the troubleshooting section from the docs: https://jupyterhub.readthedocs.io/en/stable/troubleshooting.html#errors If you can't resolve, please post a copy of your config file (without any security items) here. Thanks.

**Comment by srican** [comment]
here are my non commented lines in the config file .. (This is behind a firewall )


c.JupyterHub.extra_log_file = '/var/log/jupyterhub/jupyterhub.log'
c.JupyterHub.ip  = '10.98.92.202'
c.JupyterHub.port = 8000
c.JupyterHub.hub_ip = '0.0.0.0'
c.JupyterHub.hub_connect_ip = '10.98.92.202'
c.ConfigurableHTTPProxy.api_url = 'http://10.98.92.202:8088'
c.Authenticator.admin_users = {'siyer'}

**Comment by srican** [comment]
I can start a notebook on the same ip and host without any issues and am able to start up python .. I just am unable to get jupyterhub going

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
