### ISSUE TITLE
Python Enviroment

### ISSUE THREAD

**Issue by weih1121** [jupyterhub/jupyterhub#2101]
Hi,
First, thanks for all the great work on Jupyterhub.

I want to use my own python package in the notebook, but i really don't know how can i config it correctly?
 
Hope for your answers!

Thanks a lot!

**Comment by willingc** [comment]
If you are using JupyterHub, you can install packages from the terminal using pip or conda. If you want the package to be available every time, you would need to add the package to the single user notebook image, https://jupyterhub.readthedocs.io/en/stable/reference/config-user-env.html

**Comment by weih1121** [comment]
en...mayby my describe leads to a fault situration, I want to use a packer which write by my self or my parterners in jupyterhub, but i didn't find a suitable method to help me solve it. conda or pip install can't help.

**Comment by willingc** [comment]
Hi @weih1121, Thanks. I'm going to close this issue as out of scope for the JupyterHub project since this seems to be a custom application.
