### ISSUE TITLE
Problems Configuring HTTPS with TLJH

### ISSUE THREAD

**Issue by jlsimms** [jupyterhub/jupyterhub#2102]
Hello all! I'm trying to configure [TLJH for SSL](https://the-littlest-jupyterhub.readthedocs.io/en/latest/howto/admin/https.html) using my own key/cert. The instructions are simple enough, but it's not working. (As an aside, this is on a DigitalOcean VM and I followed the [DO installation steps](https://the-littlest-jupyterhub.readthedocs.io/en/latest/install/digitalocean.html).) Everything works with TLJH itself, runs great and has for a while. Anyway, after I've made the configuration changes, I run `sudo tljh-config reload proxy` and it just...sits there. Forever. Like I launched a program without backgrounding it.

One problem is that I don't see that `traefik` is running on the system. I don't see any way to launch the service, or even verify that it is installed. Someone on gitter said "traefik is autostarted when HTTPS is set up" and then suggested I open an issue here.

My `config.yaml` is dead simple:
```
users:
  admin:
  - XXX
https:
  enabled: 'true'
  tls:
    key: /path/to/XXX.key
    cert: /path/to/XXX.cert
```
I would welcome any and all suggestions to troubleshoot this further. Thanks!

**Comment by yuvipanda** [comment]
@jlsimms thanks for opening this!

Can you edit the config.yaml file and remove the quotes from around 'true'? Then do the reload proxy command and see what happens?

**Comment by jlsimms** [comment]
@yuvipanda Yeah, that was one of my first thoughts, too, but it behaves the same. Those quotes are inserted automatically when setting the parameters with `tljh-config`

**Comment by minrk** [comment]
I just ran a test deployment with manual ssl in `/tmp/tljh.{key|crt} and ran into these issues:

1. followed the directions and it wasn't working
2. ran `journalctl -u traefik` to see what's up. Saw this error:
    ```
    Unable to add a certificate to the entryPoint \"https\" : unable to generate TLS certificate : tls: failed to find any PEM data in certificate input"
   ```
   which made me think it was an issue with the content of my certificate file.

It *turns out* that it seemed to be something of a permission check. By moving the certificate into a directory and making sure it's private, it worked:

```bash
mkdir /etc/tljh-ssl
# make ssl directory private
chown root /etc/tljh-ssl
chmod 0600 /etc/tljh-ssl 

# put my cert and key in there
mv my.crt /etc/tljh-ssl/
mv my.key /etc/tljh-ssl/

# make key and cert files private
chown root/etc/tljh-ssl/*
chmod 0600 /etc/tljh-ssl/*

# update config
sudo tljh-config set https.tls.key /etc/tljh-ssl/my.key
sudo tljh-config set https.tls.cert /etc/tljh-ssl/my.crt
sudo tljh-config reload proxy
```

TODO item for tljh-config: validate permissions on manual key and cert to get a better error message than traefik's. I'm not sure what exactly the check is, but it seems to not like certain paths.

You will also get this error if there is just a typo in your config and the file doesn't exist.

**Comment by jlsimms** [comment]
@minrk Thanks for the message. I tried your steps, and for some reason, when I run `tljh-config reload proxy` it still just hangs. I'm not sure what it's attempting to do. The cursory attempts I've made to look at logs aren't helpful, but perhaps you have other ideas...

**Comment by jlsimms** [comment]
Actually @minrk scratch my last - it take a bit, but it finally is working. The command, at least. When I try to connect to https://, however, it simply says the connection is refused. Thoughts?

**Comment by minrk** [comment]
The fact that quotes are inserted automatically around 'true' makes me thing that tljh-config is out-of-date.

What do you get from running these commands:

- `which -a tljh-config`
- `tljh-config set test.value true`
- `tljh-config show`

If you don't get:

```yaml
test:
  value: true
```

with no quotes, then it means that `tljh-config` is not the right version, and maybe reinstalling tljh from the beginning is what's needed.

**Comment by jlsimms** [comment]
@minrk Thanks for the reply. Two things:

First, I noticed that, despite what the documentation says, I did not have a symlink set for `/usr/bin/tljh-config`, so I manually added it to point to `/opt/tljh/hub/bin/tljh-config`. I'm unsure what that indicates, if anything, but there is at least some discord between the stated behavior and my installation. (Again, I followed the posted, latest instructions for setting up TLJH on DigitalOcean during the first week of August, and seemingly everything went well.)

Second, running the commands produced the value with quotes:
```
users:
  admin:
  - XXX
https:
  enabled: true
  tls:
    key: /path/to/my.key
    cert: /path/to/my.cert
test:
  value: 'true'
```
I wonder, then, how I might upgrade what might need to be upgraded "in place"? Whether that is `tljh-config` or anything else (e.g., components/dependencies on which it relies)?

Warmest regards,
Jason

**Comment by yuvipanda** [comment]
@jlsimms you can 'upgrade in place' by just running the installer again! Try it out? I think we definitely added a bunch of stuff since first week of august!

**Comment by jlsimms** [comment]
@yuvipanda When you say "run the installer again," do you mean that I could execute:
```
#!/bin/bash
curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py \
  | sudo python3 - \
    --admin <admin-user-name>
```
I'm concerned that doing so might blow away what I've already done - we've configured our TLJH instance with several plugins and other customizations. If I re-run that, will it nuke what we have? Or, perhaps you mean something else...

**Comment by yuvipanda** [comment]
@jlsimms can you tell me what configurations you have performed? If you're concerned you can make a copy of `/opt/tljh` before. It *should* preserve the user conda environment and config.yaml files.

**Comment by yuvipanda** [comment]
@jlsimms also, is there a reason you aren't using Let's Encrypt?

**Comment by raghav130593** [comment]
@jlsimms are you certain that the private key you are using is decrypted? That was an issue when I was setting it up with an encrypted private key. `openssl rsa -in ssl.key.secure -out ssl.key` should do the job. Also, make sure you have appropriate permissions on the file so that it is restricted to only sudo/root.

**Comment by stephen-a2z** [comment]
I have the same problem
https://github.com/jupyterhub/the-littlest-jupyterhub/issues/438

**Comment by tsiewert** [comment]
@rraghav13 I had similar problems with my tljh running on my own machine in the university network. 
Your answer helped and my tljh is now accessible with https. 

Maybe a howto about manually generating ssl certificates with openssl on the tljh page would be great.

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). If you'd like to improve the docs please open a PR on the relevant repo. Thanks!
