### ISSUE TITLE
How to set sys.path for notebooks?

### ISSUE THREAD

**Issue by Siecje** [jupyterhub/jupyterhub#2103]
I would like to set `sys.path` to a directory so that notebooks can only import additional packages from there.

I don't want notebooks to be able to `import jupyterhub`.

I know that `PYTHONPATH` can be set to add additional directories but how would you remove directories from `sys.path` for all notebooks?

**Comment by minrk** [comment]
What is the goal for removing things from `sys.path`? If you want different packages to be available for the kernel than the notebook, then I would recommend using a different conda or virtualenv for the kernel.
