### ISSUE TITLE
/metrics endpoint should be private

### ISSUE THREAD

**Issue by shreddd** [jupyterhub/jupyterhub#2105]
**Describe the bug**
Currently the /hub/metrics endpoint is public. It may be more appropriate to have these metrics be protected by a login since this is internal system information. 

**To Reproduce**
1. Go to the /hub/metrics URL on a jupyterhub server without logging in 
2. Metrics will be displayed without requiring a login

**Expected behavior**
Metrics should minimally require a login (and potentially admin access for certain metrics)

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any

**Comment by jhermann** [comment]
If you add a local SSL off-loader (e.g. nginx), then auth can be handled there, or else you can block the URL and have some local agent access port 8000 directly (i.e. no metric access from the outside).

**Comment by yuvipanda** [comment]
I'm conflicted here, since these metrics are usually collected by something like Prometheus. Adding auth to it makes that hard. However, I also recognize that this is something many installations consider private info. 

I'd recommend we make an option that lets it be authenticated or not, and turn the default to be authenticated.

**Comment by minrk** [comment]
For implementation reference, to make this authentication configurable, it should:

1. add `authenticate_prometheus = Bool(True, config=True)` trait to the JupyterHub class in `app.py`
2. define a new [auth_decorator](https://github.com/jupyterhub/jupyterhub/blob/0.9.4/jupyterhub/utils.py#L243-L248) that checks if current_user is None and raises 403 *if* current user is None and authenticate_prometheus is True. 
3. apply this new auth decorator to the `get` method on the MetricsHandler

**Comment by tuhina2020** [comment]
Hi @minrk @yuvipanda . Can I get started on this bug ?

**Comment by consideRatio** [comment]
Thanks for your work on this @tuhina2020, I'm closing this as it is my understanding that your PR resolved this issue!
