### ISSUE TITLE
JupyterHub the hard way

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#2110]
Following https://github.com/kelseyhightower/kubernetes-the-hard-way

As we are adding complete tutorial-style installations for setting up jupyterhub with zero-to-jupyterhub and the-littlest-jupyterhub, I don't want us to overshadow the fact that JupyterHub is "just another package" that can be installed and managed like any other.

I think we should have a "no helpers" tutorial in this style, which goes step-by-step through the installation process, without any magic. We have most of this already as a presentation in [jupyterhub-tutorial](https://github.com/jupyterhub/jupyterhub-tutorial), and @willingc made a great [sphinx site](https://jupyterhub-tutorial.readthedocs.io/en/latest/index.html) from the presentation. I think we can turn this into a zero-to-jupyterhub-style guide (probably a new repo, rather than changing that one), which does nothing but raw install commands and creating/editing files.

**Comment by mangecoeur** [comment]
Following my experience setting up Jupyterhub for my lab (which for various reasons didn't make sense to do either with Kubernets or TLJH), I've put together a ['Install Jupyterhub the hard way' tutorial](https://gist.github.com/mangecoeur/d1a6317985b5fa1b8bf5fa4c07da2833)


If this is interesting to people, I can offer this for inclusion to the docs and make a PR with it.

**Comment by manics** [comment]
Done in https://github.com/jupyterhub/jupyterhub/pull/2842
Though there's also https://github.com/jupyterhub/jupyterhub-the-hard-way
