### ISSUE TITLE
add systemd and supervisor examples

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#2111]
It would probably be useful to have examples for running jupyterhub (with or without a separate proxy) via things like systemd or supervisor in this repo, described in the docs.

Our [tutorial](https://github.com/jupyterhub/jupyterhub-tutorial/tree/master/supervisor) has jupyterhub+proxy in one supervisorctl entry, while tljh has [systemd units](https://github.com/jupyterhub/the-littlest-jupyterhub/tree/master/tljh/systemd-units) for separating the Hub and Proxy. Copying some of these over into jupyterhub examples and adding a page to the docs detailing the process seems like a good idea.

**Comment by rcthomas** [comment]
We have a really simple example of a JupyterHub plus nslcd in our deploy repo that we just started running in production [here](https://github.com/NERSC/jupyterhub-deploy/tree/master/jupyter-spin).  Someone could look at that and set up a really simple version or one of us here could edit that down.

cc @scanon @shreddd

**Comment by nick-brady** [comment]
I am using `supervisorctl` to run JupyterHub. I'd be happy to clean up my example a bit and make a PR to the docs. I'm looking to start contributing to JupyterHub and this is an easy first task 😄.

Right now my configuration looks like this:
```
[program:jupyterhub]
command=bash /home/jupyter/launch_hub.sh
directory=/home/jupyter
autostart=true
autorestart=true
startretries=3
exitcodes=0,2
stopsignal=TERM
redirect_stderr=true
stdout_logfile=/var/log/jupyterhub.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
user=root
```

For the PR I think it'd be worth updating:

- directory --> `/etc/jupyter` as I saw that somewhere in the docs as the recommended location to launch the process from.
- command --> get rid of the `launch_hub.sh` script and put the command directly in the conf file.
- (??) fix my environment to use `SudoSpawner` instead and update the configuration as necessary for that (I built this environment when I was still figuring out JupyterHub). Let me know if you'd prefer to use SudoSpawner in the example as opposed to launching the process with root as I am now.
  - create a `jupyter` user which has access to `/etc/jupyter` and executes the hub process

If this is something you'd like - where in the docs should this go? I think in the "Technical Reference" under "Configuration Examples" is a logical place. Lmk!

**Comment by nick-brady** [comment]
I would like to take a go at this if it is still wanted. If so, couple quick questions:

1. Where should the docs go? I'm thinking under the "Technical Reference" in "Configuration examples" (similar to "Configure GitHub OAuth").
2. Rough outline of the contents.. I'm thinking something like this:
   - why it is a good idea to use a process manager
   - supervisor install (apt get ..)
   - configuration file contents and where to put it
   - some basic how to's (e.g. restart, stop, status, etc)

**Comment by goekce** [comment]
FYI: [Run Jupyterhub as a system service](https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service)

**Comment by manics** [comment]
As pointed out in the last comment this is in the wiki https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service
There's also https://github.com/jupyterhub/the-littlest-jupyterhub which uses systemd
