### ISSUE TITLE
Possible bug? Server becomes unavailable after some time (overnight?)

### ISSUE THREAD

**Issue by mdivk** [jupyterhub/jupyterhub#2114]
I hate to report this under the "bug", but since it is the jupyterhub stops for unknown reason and it is repeating here, I feel reporting this as "bug" might be appropriate from a user's perspective, I could be wrong though, anyway, the following observations are noticed in the past two days:

1. Day 1, started the jupyterhub successfully, left it running with no one using it, the start putty session is left open on purpose hoping to catch any abnormal output;
2. Day 2, showing "Service Unavailable" when clicking on Control Panel
3. Not accessible anymore when open a new tab and browse to the same ip (tried https://192.168.100.180:443, https://192.168.100.180, http://192.168.100.180:443, http://192.168.100.180, all showing same message of "Service Unavailable"
4. The  putty session does not have any output, in fact, it stops updating since  I left work on Day1
5. I noticed the same issue for the last two days. There was no configuration change, I ended up kill the exisiting node/configurable-http-proxy in order to start a new hub

Below is the troubleshoot output from another putty session: 

> hadoopuser@hadoop02 .jupyter]$ jupyter troubleshoot
> DEPRECATION: The default format will switch to columns in the future. You can us                                                       e --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.con                                                       f under the [list] section) to disable this warning.
> You are using pip version 9.0.1, however version 18.0 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> $PATH:
>         /usr/local/bin
>         /usr/local/bin
>         /sbin
>         /bin
>         /usr/sbin
>         /usr/bin
>         /usr/local/bin
>         /usr/local/git/bin
>         /home/hadoopuser/bin
>         /home/hadoopuser/bin
> 
> sys.path:
>         /usr/local/bin
>         /usr/local/lib/python3.3/site-packages/requests-2.11.1-py3.3.egg
>         /usr/local/lib/python33.zip
>         /usr/local/lib/python3.3
>         /usr/local/lib/python3.3/plat-linux
>         /usr/local/lib/python3.3/lib-dynload
>         /usr/local/lib/python3.3/site-packages
> 
> sys.executable:
>         /usr/local/bin/python3.3
> 
> sys.version:
>         3.3.3 (default, Sep 13 2016, 13:34:44)
>         [GCC 4.4.7 20120313 (Red Hat 4.4.7-11)]
> 
> platform.platform():
>         Linux-2.6.32-504.3.3.el6.x86_64-x86_64-with-centos-6.6-Final
> 
> which -a jupyter:
>         /usr/local/bin/jupyter
>         /usr/local/bin/jupyter
>         /usr/local/bin/jupyter
> 
> pip list:
>         alembic (0.9.1)
>         aniso8601 (1.2.1)
>         backports-abc (0.4)
>         certifi (2016.9.26)
>         chardet (2.3.0)
>         click (6.7)
>         dataset (0.8.0)
>         decorator (4.0.10)
>         entrypoints (0.2.2)
>         enum34 (1.1.6)
>         Flask (0.12.2)
>         Flask-RESTful (0.3.6)
>         ipykernel (4.5.0)
>         ipyparallel (5.2.0)
>         ipython (5.1.0)
>         ipython-genutils (0.1.0)
>         ipywidgets (5.2.2)
>         itsdangerous (0.24)
>         Jinja2 (2.8)
>         jsonschema (2.5.1)
>         jupyter (1.0.0)
>         jupyter-client (4.4.0)
>         jupyter-console (5.0.0)
>         jupyter-core (4.2.0)
>         jupyterhub (0.7.2)
>         kafka (1.3.5)
>         lxml (3.6.4)
>         Mako (1.0.6)
>         MarkupSafe (0.23)
>         mistune (0.7.3)
>         munch (2.1.1)
>         nbconvert (4.2.0)
>         nbformat (4.1.0)
>         normality (0.4.0)
>         notebook (4.2.3)
>         pamela (0.3.0)
>         pathlib2 (2.1.0)
>         petname (2.0)
>         pexpect (4.2.1)
>         pickleshare (0.7.4)
>         pip (9.0.1)
>         prompt-toolkit (1.0.8)
>         ptyprocess (0.5.1)
>         Pygments (2.1.3)
>         python-dateutil (2.6.0)
>         python-editor (1.0.3)
>         pytz (2017.2)
>         PyYAML (3.12)
>         pyzmq (16.0.0)
>         qtconsole (4.2.1)
>         requests (2.11.1)
>         setuptools (28.7.1)
>         simplegeneric (0.8.1)
>         singledispatch (3.4.0.3)
>         six (1.10.0)
>         slacker (0.9.42)
>         SQLAlchemy (1.1.6)
>         terminado (0.6)
>         tornado (4.4.2)
>         traitlets (4.3.1)
>         wcwidth (0.1.7)
>         Werkzeug (0.12.2)
>         wheel (0.29.0)
>         widgetsnbextension (1.2.6)
> [hadoopuser@hadoop02 .jupyter]$

**Comment by willingc** [comment]
It looks like you are using an old Python version 3.3 which is not supported on jupyterhub. You are also using fairly old version of the notebook and tornado. I'm going to close this issue. Please file a new issue if you have difficulty with up to date versions. Thanks.
