### ISSUE TITLE
Pyspark Kernel Error : ValueError: Cannot run multiple SparkContexts at once; existing SparkContext(app=pyspark-shell, master=yarn

### ISSUE THREAD

**Issue by zmkhazi** [jupyterhub/jupyterhub#2115]
I have configured the pyspark kernel for JupyyterHub. Upon trying to test the sample code, I am getting this multi context error, even though it is set to 1.  Please advice how do I overcome this issue. How do I best validate my pyspark kernel. What code I need to submit to validate successful connectivity from pyspark notebook to spark  in a single context and multi context. Any help on  this is appreciated. 

**Following Code submitted in Jupyter Notebook with Pyspark  Kernel**
==================================================
import pyspark 
sc = pyspark.SparkContext('local[1]')
# do something to prove it works
rdd = sc.parallelize(range(1000))
rdd.takeSample(False, 5)

Details of the ERROR below
=============
ValueError: Cannot run multiple SparkContexts at once; existing SparkContext(app=pyspark-shell, master=yarn) created by <module> at /opt/oss/Anaconda3/lib/python3.6/site-packages/IPython/utils/py3compat.py:186

**Comment by zmkhazi** [comment]
This is the code that I had submitted.

import pyspark 
sc = pyspark.SparkContext('local[1]')
rdd = sc.parallelize(range(1000))
rdd.takeSample(False, 5)

**Comment by zmkhazi** [comment]
I get the same error when running this code also.
ValueError: Cannot run multiple SparkContexts at once; existing SparkContext(app=pyspark-shell, master=yarn) created by at /opt/oss/Anaconda3/lib/python3.6/site-packages/IPython/utils/py3compat.py:186

Following Code was submitted
-----------------------------------
import findspark
findspark.init()
import pyspark
import random
sc = pyspark.SparkContext(appName="Pi")
num_samples = 100000000
def inside(p):     
  x, y = random.random(), random.random()
  return x*x + y*y < 1
count = sc.parallelize(range(0, num_samples)).filter(inside).count()
pi = 4 * count / num_samples
print(pi)
sc.stop()

**Comment by SivaMaplelabs** [comment]
@zmkhazi By default SparkContext available, you no need to create.
"""
import sys
print(u'Python version ' + sys.version)
print(u'Spark version ' + sc.version)
"""

**Comment by SivaMaplelabs** [comment]
You can validate your Pyspark kernel with below code.

```
from pyspark.mllib.random import RandomRDDs
from pyspark.sql.types import *

random_rdd = RandomRDDs.normalRDD(sc, 1000, seed=1)
stats = random_rdd.stats()
print stats
random_rdd.count()


schema = StructType([
    StructField("name", StringType(), True),
    StructField("age", IntegerType(), True)])

d = [{'name': 'Alice', 'age': 10},
     {'name': 'Cooper', 'age': 65}]
rdd = sc.parallelize(d)
    
df = sqlContext.createDataFrame(rdd, schema)
df.registerTempTable("people")

df.collect()
sqlContext.sql('SELECT * FROM people WHERE age < 15').collect()
```
