### ISSUE TITLE
Integration with haveibeenpwned 

### ISSUE THREAD

**Issue by Carreau** [jupyterhub/jupyterhub#2118]
https://haveibeenpwned.com/ provide a nice API to check (anonymously and without leaking the password) whether a password have been leaked.

It is relatively trivial to implement:

compute sha1, split in PREFIX/SUFFIX. 

GET request of `https://.../api/v2//PREFIX`
Check if suffix in response.

https://haveibeenpwned.com/API/v2#SearchingPwnedPasswordsByRange

Should be relatively easy to implement either on client or server side plus makes opt-in/out as an option I guess.

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point here. It could potentially be added to one of the authenticators such as https://github.com/jupyterhub/nativeauthenticator
