### ISSUE TITLE
why can not run sudo jupyterhub in the shell script?

### ISSUE THREAD

**Issue by chaoyue729** [jupyterhub/jupyterhub#2123]
Hi! Thanks for using JupyterHub.

If you are reporting an issue with JupyterHub, please use the [GitHub issue](https://github.com/jupyterhub/jupyterhub/issues) search feature to check if your issue has been asked already. If it has, please add your comments to the existing issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

- Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.
- Running in `--debug` mode can also be helpful for troubleshooting.

**Comment by chaoyue729** [comment]
I just want connect pyspark with jupyterhub, anyone who has such need for can comment it

**Comment by chaoyue729** [comment]
@minrk i just install anaconda3 on REHL7 and install jupyterhub0.9.2, i need to run jupyterhub without using sudo and other jupyterhub users could login in. And i also need jupyterhub run as server, so i need run jupyerhub in shell script.
Now i have try the instruction of  "Run JupyterHub without root privileges using sudo"  ,but it dose work,still with PAM Authentication failed (qcy@183.128.118.135): [PAM Error 7] Authentication failure
when i use other jupyerhub user to login

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Thanks to all!
