### ISSUE TITLE
url from other user not auto redirect to current user thus '404 Not Found' complains

### ISSUE THREAD

**Issue by jason4zhu** [jupyterhub/jupyterhub#2124]
There are two users, namely user_a and user_b. when user_a trying to access user_b's url: https://jupyter-staging.corp.kuaishou.com/hub/user/user_b/notebooks/user_b/Untitled.ipynb, it complains "404 : Not Found Jupyter has lots of moons, but this is not one...", then I try to tweak the url's username to user_a explicitly, it works fine: "https://jupyter-staging.corp.kuaishou.com/hub/user/user_a/notebooks/user_b/Untitled.ipynb". Any idea how I could make jupyterhub redirect the url automatically itself to current user. Thanks.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Thanks to all!
