### ISSUE TITLE
options_form not used through API (maybe kubespawner bug)

### ISSUE THREAD

**Issue by rkdarst** [jupyterhub/jupyterhub#2126]
**Describe the bug**
I was using the API to spawn servers using kubespawner (to frame the problem: this is a different hub than my typical batchspawner setup).  My setup *needs* one of the profiles to be selected to work (yes, this isn't ideal... I changed that).

I figured out how to send options to the spawner (JSON in body of  `POST /user/{name}/server`, gets set as user_options on the spawner.  note: could be documented better).  However, I still wasn't seeing this take any effect in KubeSpawner.

In the end, I tracked things down.  I see that KubeSpawner parses the options in `KubeSpawner.options_from_form`, and doesn't use `self.user_options`.  However, it seems that `spawner.options_from_form` is only called in `jupyterhub/handlers/pages.py:141:            options = user.spawner.options_from_form(form_options)`, *not* in the API handlers.

Is this expected?  It seems the bug could be in KubeSpawner and maybe other spawners: `options_from_form` says it should convert the HTML data to usable Python objects.  It then gets stored on `spawner.user_options` eventually.  Via the API, it is expected that you put the data into a usable format yourself (I think I read this in another issue, also [related here](https://jupyterhub.readthedocs.io/en/stable/reference/spawners.html#spawner-options-from-form)) thus no need to call `spawner.options_from_form`.  

I'm posting here first to get expert JH advice, and if it's a KubeSpawner issue will move to there.

**Versions**
 - Using 0.9.1 and requests.

**Comment by minrk** [comment]
Spawning through the REST API sets `user_options` directly, not the form, so `.options_form_form` is skipped. If KubeSpawner is taking actions in options_from_form, not based on user_options in start, then it's a bug in KubeSpawner.

**Comment by willingc** [comment]
Hi folks, I'm going to close this on the JupyterHub repo. If you are still seeing issues with KubeSpawner, please file an issue in that repo. Thanks @rkdarst 👍
