### ISSUE TITLE
Cannot stop my server when a backslash is in username

### ISSUE THREAD

**Issue by Jamesits** [jupyterhub/jupyterhub#2128]
**Describe the bug**
Cannot stop my server when a backslash character is in username.

**To Reproduce**
1. Login with a user named `foo\bar`
2. start server
3. stop my server

**Expected behavior**
The server should stop.

**Screenshots**
![image](https://user-images.githubusercontent.com/1297257/45033727-e4576e80-b044-11e8-8fba-85cf66e39064.png)

**Server**
 - OS: Fedora 28
 - JupyterHub: 0.9.2

**Desktop (please complete the following information):**
 - OS: Windows 10 1803
 - Browser: Firefox
 - Version 61.0.2

**Comment by nicorikken** [comment]
I can confirm this. We use the genericOAuthenticator, resulting in usernames like `Company\UserId`. This is causing ever more issues.
As the backslash is not URL-encoded, it is replaced with a forward slash by the browser, resulting in an incorrect path and thus the error.
URL-encoding the backslash with `%5c` and repeating the call does succeed.

**Comment by nicorikken** [comment]
I think URL-encoding the `user` variable in the javascript code will solve this issue https://github.com/jupyterhub/jupyterhub/blob/38cf95523f2ec7ce553136b630c915b0395cbca2/share/jupyterhub/static/js/home.js#L61

**Comment by nicorikken** [comment]
In the templated html and the javascript the `user` is not properly URL-encoded anywhere, also causing issues when spawning a new container, so this issue is much wider than just stopping the server.

**Comment by nicorikken** [comment]
@Jamesits I proposed some UI changes to fix this. Perhaps you can test this for your use-case? https://github.com/jupyterhub/jupyterhub/pull/2640

**Comment by nicorikken** [comment]
I misinterpreted the issue. In the UI `window.jhdata.user` the user is known without the backslash, e.g. `companyuserid`. The backend is serving pages which included the backslash, so there is a mismatch between the two.
The javascript injected into the page does contain the backslash:
```
      window.jhdata = {
        base_url: "/hub/",
        prefix: "/",
        user: "company\userid",
        admin_access: false,
        options_form: true,
      }
```
So now it seems to me that the username should be properly escaped in this javascript insert.

**Comment by nicorikken** [comment]
Tornado features some escape features, like [tornado.escape.json_encode](https://www.tornadoweb.org/en/stable/escape.html#tornado.escape.json_encode} and [tornado.escape.url_escape](https://www.tornadoweb.org/en/stable/escape.html#tornado.escape.url_escape). Perhaps that will work.

It seems that should be resolved in the `handlers/pages.py`, or even in the `user.py` user class. The latter already has an `escaped_name` property, for spawning the server.

This `escaped_name` property is based on the [urllib.parse.quoteh](ttps://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote) method. I'm not sure if that is sufficient for propagating it to the frontend, as this requires a different kind of escaping (`%5u` vs `\u005u`). Perhaps the `tornado.escape.json_encode` function will do so.

**Comment by nicorikken** [comment]
So the final solution was simple, just `json.dumps()` the username to the frontend. I thought there were other issues, or more clever solutions, but that was is. The PR is ready to be merged (linked above already).

**Comment by nicorikken** [comment]
Related to this issue, I've now also proposed a fix for the spawn URL, which also fails on the backslash: https://github.com/jupyterhub/jupyterhub/pull/2648

**Comment by manics** [comment]
Is this still a problem for you in the latest JupyterHub release?

**Comment by manics** [comment]
No response, closing
