### ISSUE TITLE
JupyterHub spawns multiple server for one user

### ISSUE THREAD

**Issue by Jamesits** [jupyterhub/jupyterhub#2129]
**Describe the bug**
A Linux user with one UID but multiple username can make JupyterHub (or the systemd spawner? I'm not familiar with the spawner so not very sure if I'm reporting to the correct repository) spawn multiple servers, one per username, effectively bypass some security and resource limitations.

**To Reproduce**
1. Link a UID to multiple username
2. login using all those usernames from different browser sessions
3. try open different notebooks from different sessions
4. look at the running tab, see if they are the same server

**Expected behavior**
There should be only one server per UID.

**Screenshots**
Nope

**Server**
 - OS: Fedora 28
 - JupyterHub: 0.9.2

**Desktop (please complete the following information):**
 - OS: Windows 10 1803
 - Browser: Firefox
 - Version 61.0.2

PS: If you wonder why this kind of setup will be done in production, this is common in systems with kerberos authentication, where you might have multiple names mapped to the same uid. Users can login using `username`, `domain\username` or `username@domain`.

**Comment by minrk** [comment]
If multiple usernames map onto one user, this should be handled in `.authenticate` or possibly `.normalize_username`. What Authenticator are you using?

**Comment by willingc** [comment]
Would you be able to share your debug log with us (please remove any private information)? Thanks.

**Comment by minrk** [comment]
Since this is PAM, my first thought was to have a default normalize_username that runs through username->userid->username, which should get a deterministic answer:

```python
uid = pwd.getpwnam(username).pw_uid
username = pwd.getpwuid(uid).pw_name
```

Can you run that snippet for your deployment and see if it works?

But then I read about some use cases where different users *should* have the same UID, so I'm not sure about this as the default behavior.

Regardless of what we end up doing by default, in the meantime you can implement this as configuration for your deployment:

```python
# in jupyterhub_config.py
from jupyterhub.auth import PAMAuthenticator

class MyPAMAuthenticator(PAMAuthenticator):

    def normalize_username(self, username):
        # pass through uid to ensure that all names that
        # correspond to one uid map to the same jupyterhub user
        uid = pwd.getpwnam(username).pw_uid
        return super().normalize_username(pwd.getpwuid(uid).pw_name)

c.JupyterHub.authenticator_class = MyPAMAuthenticator
```

**Comment by Jamesits** [comment]
@minrk Sorry for the late reply, I've been on a trip for some day with no computer access.

The snippet
```python
uid = pwd.getpwnam(username).pw_uid
username = pwd.getpwuid(uid).pw_name
```
did give me a deterministic UID and username for all the usernames I tried. In my case the username returned is `user@main.upn.suffix`.

**Comment by manics** [comment]
See https://github.com/jupyterhub/jupyterhub/pull/2397
