### ISSUE TITLE
Check notebook folder existance & create it if needed

### ISSUE THREAD

**Issue by YannBrrd** [jupyterhub/jupyterhub#213]
Hi,

When launching a user notebook server, if the folder to store notebooks does not exist, the server just fails (& no error shown) which leads to never ending 302 loops.

The script should verify folder existence & grants & create it if needed...

**Comment by mfitzp** [comment]
If you're using PAM authentication you can do this by adding a custom script to the PAM `login` handler (which Jupyterhub runs through). The following script achieves this (it includes checks to remove domains from logins if you're using ADF - change the domain as required - and ensure usernames are alphanumeric for security). It also creates automatic links to a read-only folder of example scripts:

    #!/bin/bash

    if [ "$#" -eq 1 ]; then
       USER=$1
    elif ! [ -z "$PAM_USER" ]; then
       USER=$PAM_USER
    else
       echo "Need to pass a username"
       exit 1
    fi

    # Remove ADF\ if it's in the username
    USER=${USER#*\\}

    # Strip all non-alphanumeric characters before we use the input
    USER="${USER//[![:alnum:]]}"

    HOMEFOLDER="/home/"$USER

    if [ ! -d $HOMEFOLDER ]; then
        echo "Creating home folder for "$USER
        mkdir $HOMEFOLDER
        chmod 0755 $HOMEFOLDER
        chown $USER:$USER $HOMEFOLDER
    fi

    if [ ! -L $HOMEFOLDER/examples ]; then
        cd $HOMEFOLDER
        echo "Creating symlinks for "$USER
        ln -s /opt/ipython-examples/ $HOMEFOLDER/examples
    fi

    mkdir $HOMEFOLDER/.ipython
    cp -r /opt/myscripts/ipython-profile/* $HOMEFOLDER/.ipython
    chown -R $USER:$USER $HOMEFOLDER/.ipython

Then in `/etc/pam/login` you can add (at the end):

    auth    required        pam_exec.so /opt/myscripts/create_userdir_setuid.sh

If you do not need to change the ownership of  `$HOMEFOLDER` (e.g. you're setting it up with loose permissions) this will work. However, if you want to have each folder assigned to a user you need to `chown` it - but this requires root. This now becomes tricky as the login is not running as `root`. You can't `setuid` a script but you can accomplish this by writing a small wrapper in C in the same folder as the above script:

    #include <stdio.h>
    #include <stdlib.h>
    #include <sys/types.h>
    #include <unistd.h>

    int main()
    {
       setuid(0);
       system("/opt/myscripts/create_userdir.sh");
       return 0;
    }

Compile this `gcc create_userdir_setuid.c -o create_userdir_setuid` and then `chmod 4755 create_userdir_setuid` to set it for root execution.

Change `/etc/pam/login` to:

    auth    required        pam_exec.so /opt/myscripts/create_userdir_setuid

And you'll now have automatic, correctly owned, correctly typed home folders for every user that successfully logs in.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!
