### ISSUE TITLE
Troubleshooting FAQ page missing

### ISSUE THREAD

**Issue by backtrackbaba** [jupyterhub/jupyterhub#2130]
**Describe the bug**
Missing Link in the Documentation
**To Reproduce**
1. Go to the [Link on ReadTheDocs](https://jupyterhub.readthedocs.io/en/latest/getting-started/security-basics.html#ssl-encryption)
2. Click on __troubleshooting FAQ__ link
3. It leads to a 404 Page on ReadTheDocs

**Expected behavior**
Open up a Documentation page

**Screenshots**

<img width="1438" alt="screenshot at sep 05 13-55-53" src="https://user-images.githubusercontent.com/9502343/45080952-affeb380-b113-11e8-99ad-45c542c2faad.png">

**Comment by willingc** [comment]
Thanks @backtrackbaba for the report and @SivaMaplelabs.
