### ISSUE TITLE
Worker and Driver are on different python version - causing spark exception

### ISSUE THREAD

**Issue by mdivk** [jupyterhub/jupyterhub#2133]
I have jupyterhub installed in our mini cluster (5 nodes), at the moment experiencing spark exception as below. It would be greatly appreciated if anyone can enlighten me how to set the default python on driver node, detail is below (sorry it is lengthy):

1. Environment:
python3.4.8: /usr/bin/python3
Cloudera CDH 5.12
2. Kernel:
```
[hadoopuser@hadoop02 bin]$ jupyter kernelspec list
Available kernels:
  python3    /usr/local/share/jupyter/kernels/python3

[hadoopuser@hadoop02 python3]$ cat kernel.json
{
 "argv": [
  "/usr/local/bin/python3.3",
  "-m",
  "ipykernel",
  "-f",
  "{connection_file}"
 ],
 "language": "python",
 "display_name": "Python 3"
}
```

Spark configuration:
```
Spark Service Advanced Configuration Snippet (Safety Valve) for spark-conf/spark-env.sh:
Spark (Service-Wide) 
```

> PYSPARK_PYTHON=/usr/bin/python3
> PYSPARK_DRIVER_PYTHON=/usr/bin/python3
> 

```
Spark Client Advanced Configuration Snippet (Safety Valve) for spark-conf/spark-env.sh:
Gateway Default Group  
```

> HADOOP_CONF_DIR=$HADOOP_CONF_DIR:/etc/hive/conf

I already pushed the spark-env to the entire cluster;

For configuration in Spark2, 
`Spark 2 Service Advanced Configuration Snippet (Safety Valve) for spark2-conf/spark-env.sh:`

> PYSPARK_PYTHON=/usr/bin/python3
> PYSPARK_DRIVER_PYTHON=/usr/bin/python3

To start the jupyterhub:
```
[hadoopuser@hadoop02 .jupyter]$ cat start_jupyterhub.sh
export SPARK_HOME=/opt/cloudera/parcels/CDH/lib/spark
#export PYTHONPATH=/opt/cloudera/parcels/CDH/lib/spark/python/:/opt/cloudera/parcels/CDH/lib/spark/python/lib/py4j-0.9-src.zip
export PYSPARK_PYTHON=/usr/bin/python3
```

Also ran (with no result change) in shell before start the jupyterhub:
export PYSPARK_PYTHON=/usr/bin/python3
export PYSPARK_DRIVER_PYTHON=/usr/bin/python3
export PATH=/home/hadoopuser:$PATH
sudo -E jupyterhub
Starting folder is /home/hadoopus/u

Starting folder is /home/hadoopus/usr/bin/python3
Tried to trick the jupyter to bring up 3.4.8 on driver node by creating a softlink that python is linked to python3.4.8 which is /usr/bin/python3, still no luck, the notebook still picks up 3.3

The notebook:

```
import sys,os
os.environ["SPARK_HOME"] = '/opt/cloudera/parcels/CDH/lib/spark'
os.environ['PYSPARK_PYTHON'] = '/usr/bin/python3'
sys.path.append('/opt/cloudera/parcels/CDH/lib/spark/python')
sys.path.append('/opt/cloudera/parcels/CDH/lib/spark/python/lib/py4j-0.9-src.zip') 
import pyspark
from pyspark import SparkContext, SparkConf
conf = SparkConf()
conf.setMaster('yarn-client')
conf.setAppName('test')
sc = SparkContext(conf = conf)
#sc = SparkContext.getOrCreate()
rdd = sc.textFile("hdfs://hadoop02.company.com:8020/user/rxie/SR2018.csv")
rdd.take(10)
```

The error:

> Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.runJob.
> : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3, hadoop03.novantas.com, executor 1): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
>   File "/data/cloudera/parcels/CDH-5.12.0-1.cdh5.12.0.p0.29/lib/spark/python/lib/pyspark.zip/pyspark/worker.py", line 64, in main
>     ("%d.%d" % sys.version_info[:2], version))
> Exception: Python in worker has different version 3.4 than that in driver 3.3, PySpark cannot run with different minor versions

**Comment by mdivk** [comment]
Finally a critical finding:
Jupyterhub is below:
```
[hadoopuser@hadoop02 bin]$ cat jupyterhub
#!/usr/local/bin/python3

from jupyterhub.app import main
main()

```
In my cluster, /usr/local/bin/python3 is python 3.3 - this explains why the error message always indicates the driver is always 3.3 while worker are 3.4

But I cannot just simply replace #!/usr/local/bin/python3 to #!/usr/bin/python3, it will complain a new error: there is no jupyterhub.app in the new /usr/bin/python3 location.

So, how can I set the driver's python version to the needed /usr/bin/python3?

Thank you very much.

**Comment by mdivk** [comment]
Issue resolved by installing jupyterhub again on driver with the same python like workers.

**Comment by mdivk** [comment]
so disappointed no one responded but so happy to get it resolved.

**Comment by skhadrao** [comment]
Hello mdivk,

I have a cdh5.13.3 cluster (5 nodes ), I want to install a jupyterhub on the edge node for my users to access the cluster, I have added spark2 to my cluster.

I would appreciate if you can tell me how have installer correctly jupyterhub ?

Thanks very much.

**Comment by mdivk** [comment]
Hi,

Have you checked out the official document site? here is the link.

https://jupyterhub.readthedocs.io/en/stable/

**Comment by skhadrao** [comment]
Yes, 

I have read it, but there is nothing about spark_home and pyspark_home configuration on the cluster hosts ?

Also, I'm wondering if the installation will succeed, because of the link below 

https://www.cloudera.com/documentation/enterprise/5-14-x/topics/spark_ipython.html

Cloudera seems to say there is no support of Jupyter en Ipython with CDH5.x>11 ??

Can you confirm me that this will work for CDH5.12 or CDH5.13 ?

Can you share yout cluster config if it's stable for you ?

Thanks

**Comment by mdivk** [comment]
yes it works in 5.11/12, we do not have 5.13, I believe it works there too. It doesn't matter Cloudera doesn't support Jupyter.

**Comment by skhadrao** [comment]
Ok, I will try that and tell you.

Can you give me the conf you made to use pyspark from jupyter ?

**Comment by mdivk** [comment]
Hi, this is a CLOSED thread, you might want to open your question on a new thread or on stackoverflow, I will be happy to help.
