### ISSUE TITLE
Exclude admin permissions from being revoked when `--cull_users` is used with `cull_idle_servers.py`

### ISSUE THREAD

**Issue by RonanMcCarthy** [jupyterhub/jupyterhub#2150]
**Description**
When JupyterHub is configured to use the `cull_idle_servers.py` script as a service, admin users have their admin rights revoked when the `--cull-users` option is used.

**To Reproduce**

1. Configure JupyterHub with the following:

```python
c.JupyterHub.services = [
    {
        'name': 'cull-idle',
        'admin': True,
        'command': '/path/to/python /path/to/cull_idle_servers.py --timeout=86400 --cull_users --cull_every=3600'.split(),
    }
```

2. Note the logs when the admin logs in. It will show `'admin': True`.

3. Log out and wait for 24 hours, or whatever the cull timeout is.

4. Have a look at the logs when the admin logs in again. It will show `'admin': False`.

The only way to restore admin rights after this cull is by restarting JupyterHub. This behaviour goes away when `--cull-users` is not used.

**Expected behavior**
Admins should maintain their rights even if the `--cull-users` option is used.

**System**
 - OS: Ubuntu 14.04.5 LTS
 - JupyterHub Version: 0.9.2

**Comment by willingc** [comment]
Hi @RonanMcCarthy,

Are you using the exact configuration above? 
See https://github.com/jupyterhub/jupyterhub/blob/master/examples/cull-idle/jupyterhub_config.py#L6

The script only supports python3. It is not supported on Python 2.

**Comment by RonanMcCarthy** [comment]
Hi @willingc - yes, I am using python3. Note that culling works fine, no issues, except for the side effects noted in the issue description.

**Comment by minrk** [comment]
What Authenticator and authenticator configuration are you using? Adding `--cull-users` does indeed delete your admin users when they are idle. It could (and probably should!) be modified to exclude admins from candidates for user deletion.

**Comment by RonanMcCarthy** [comment]
Authenticator is the default (PAM). Here's the complete config:

```python
c.JupyterHub.ssl_key = '/path/to/ssl-key'
c.JupyterHub.ssl_cert = '/path/to/ssl-cert'
c.JupyterHub.ip = '<ip-address>'
c.JupyterHub.port = <port>
c.JupyterHub.cookie_secret_file = '/path/to/secret-file'
c.Authenticator.admin_users = {'me', 'him', 'her'}

# remove users that no longer exist
c.Authenticator.delete_invalid_users = True

# need this otherwise cannot find jupyterhub-singleuser
c.Spawner.cmd = ['/path/to/virtualenv/jupyterhub/bin/jupyterhub-singleuser']

# culling kernels that are idle for more than 86400s, 24 hours
c.MappingKernelManager.cull_idle_timeout = 86400

# culling servers that are idle for more than 86400s, 24 hours
c.JupyterHub.services = [
    {
        'name': 'cull-idle',
        'admin': True,
        'command': '/path/to/python /path/to/cull_idle_servers.py --timeout=86400 --cull_every=3600'.split(),
    }
]
```

**Comment by manics** [comment]
The culler has moved to its own repo: https://github.com/jupyterhub/jupyterhub-idle-culler
