### ISSUE TITLE
JupyterHub can't connect to LDAP

### ISSUE THREAD

**Issue by mdivk** [jupyterhub/jupyterhub#2152]
Hello all,

For unknown reason here, JupyterHub does not seem to trust LDAP certificate. 

I have a LDAP cert file from system admin and was advised to use it to communicate to LDAP server, the cert is not trusted and JupyterHub throws out error:

Can't connect to LDAP

Similar error is also reported in https://bneijt.nl/blog/post/connecting-to-ldaps-with-self-signed-cert-using-python but the solution doesn't work out here.

Configuration as below:
tried three different server_address options, same error.

> c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
> #c.LDAPAuthenticator.server_address = 'xxx.xxx.xxx.xxx'
> #c.LDAPAuthenticator.server_address = 'nydc-dc01.company.pri'
> c.LDAPAuthenticator.server_address = 'ldaps://nydc-dc01.company.pri'
> c.LDAPAuthenticator.use_ssl = True
> c.LDAPAuthenticator.server_port = 636
> 
> c.LDAPAuthenticator.bind_dn_template = []
> c.LDAPAuthenticator.user_search_base = 'OU=CompanyOU Users,DC=CompanyDC,DC=pri'
> c.LDAPAuthenticator.user_attribute = 'sAMAccountName'
> 
> c.LDAPAuthenticator.lookup_dn = True
> c.LDAPAuthenticator.lookup_dn_search_user = 'CN=ldapbind2,OU=Company Users (System),DC=CompanyDC,DC=pri'
> c.LDAPAuthenticator.lookup_dn_search_password = 'xxxxxxxxxxxxxxxxx'
> 
> 
> c.LDAPAuthenticator.allowed_groups = ['CN=wfgo-0081,OU=company Groups,DC=company,DC=pri']
> 
> 

It would be greatly appreciated if anyone can share any light here.

**Comment by willingc** [comment]
@mdivk What is the log output when running `jupyterhub --port=80 --debug`? If you give us more detail on the error message and repost the output (i.e. 20-30 lines), that would be helpful.
