### ISSUE TITLE
Documentation Error for `c.JupyterHub.authenticator_class`

### ISSUE THREAD

**Issue by coderforlife** [jupyterhub/jupyterhub#2153]
The documentation states that the Authenticator class constructor for the type given to `c.JupyterHub.authenticator_class` must take a single kwarg of `config` but instead the constructor receives `parent` and `db` kwargs.

**Comment by coderforlife** [comment]
Right here: https://github.com/jupyterhub/jupyterhub/blob/e4a64bd129c006210e9af2c3ecb50e3e0ea8a3c0/jupyterhub/app.py#L659

This documentation shows up in the generated config file when doing `jupyterhub --config`.

**Comment by manics** [comment]
This has been updated
https://github.com/jupyterhub/jupyterhub/blob/c3ca924ba896bf2da40cab29e2a08784850a945b/jupyterhub/app.py#L948-L968
