### ISSUE TITLE
Display user name in Control Panel

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#2157]
The JupyterHub Control Panel currently only shows actions for stoppin & starting servers. It would be great if it could also show the current user name, since this is not obvious with a bunch of Authenticators (such as LTI).

For reference, https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/handlers/pages.py#L43 is the handler that renders the page. You can access the page by clicking 'Control Panel' on the top right after logging in to your JupyterHub.

**Comment by sashafierce** [comment]
Hello @yuvipanda! I am an outreachy aspirant and would like to start with this task.

**Comment by minrk** [comment]
For reference, the relevant section of the template is [here](https://github.com/jupyterhub/jupyterhub/blob/0.9.3/share/jupyterhub/templates/page.html#L126)
