### ISSUE TITLE
key not found: _PYSPARK_DRIVER_CALLBACK_HOST

### ISSUE THREAD

**Issue by mdivk** [jupyterhub/jupyterhub#2158]
I understand this has been discussed before, however, now able to sort it out with suggested solution, so I decided to post here again - maybe my case is unique? Thank you very much, it is been stuck here for a week now, any help is greatly appreciated.

Environment:
I am deploying/configuring jupyterhub on another cluster by essentially following my successful implementation on a previous sandbox cluster, stuck here now due to the current environment is not clear to me.

Here is it:
spark: /opt/cloudera/parcels/CDH/lib/spark
python: /usr/bin/python, 2.7.5

Kernel (python 2): (the env part was manually added by following given working example here https://github.com/jupyterhub/jupyterhub/issues/2116), by the way, the kernel was created long time ago under Jupyter, would that be an issue? How do I know which python I was using to create the kernel?

```
{
 "display_name": "Python 2",
 "language": "python",
 "argv": [
  "python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
"env": {
  "HADOOP_CONF_DIR":"/etc/hive/conf",
  "PYSPARK_PYTHON":"/usr/bin/python",
  "SPARK_HOME": "/opt/cloudera/parcels/CDH/lib/spark",
  "WRAPPED_SPARK_HOME": "/opt/cloudera/parcels/CDH/lib/spark",
  "PYTHONPATH": "{{ app_packages_home }}/lib/python2.7/site-packages:{{ jupyter_extension_venv }}/lib/python2.7/site-packages:{{ spark_home }}/python:{{ spark_home }}/python/lib/py4j-0.10.4-src.zip",
  "PYTHONSTARTUP": "/opt/cloudera/parcels/CDH/lib/spark/python/pyspark/shell.py",
  "PYSPARK_SUBMIT_ARGS": "--master yarn-client --jars {{ spark_home }}/lib/spark-examples.jar pyspark-shell"
 }
} 
```

Notebook:

```
import sys,os
os.environ["SPARK_HOME"] = '/opt/cloudera/parcels/CDH/lib/spark'
os.environ['PYSPARK_PYTHON'] = '/usr/bin/python'
os.environ['PYSPARK_DRIVER_PYTHON'] = '/usr/bin/python'
os.environ['JAVA_HOME'] = '/usr/java/latest'
sys.path.append('/usr/bin/python')
sys.path.append('/opt/cloudera/parcels/CDH/lib/spark/python/lib/py4j-0.9-src.zip') 

import pyspark
from pyspark import SparkContext, SparkConf

conf = SparkConf()

conf.setMaster('yarn-client')
conf.setAppName('raymond - test')

sc = SparkContext(conf = conf)
```
Error:

> ERROR util.SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[main,5,main]
> java.util.NoSuchElementException: key not found: _PYSPARK_DRIVER_CALLBACK_HOST

**Comment by SivaMaplelabs** [comment]
Look at the following...
https://stackoverflow.com/questions/50987944/key-not-found-pyspark-driver-callback-host

**Comment by mdivk** [comment]
Thank you Siva, checked that already, have been tweaking the environment variables with no progressing.
I am running JHub with python 3.6.4, pyspark will be using Anaconda's python 2.7.12 across the cluster:
I highly suspect the 7 variables in env section of the kernel has issues, either not right, or conflicts.
It would be of a great help if you can provide a sample env settings here for python2 kernel:
Thank you lots in advance.

**Comment by SivaMaplelabs** [comment]
```
{
 "display_name": "PySpark/Python2 (Anaconda)",
 "language": "python",
 "argv": [
  "{{ anaconda_home }}/bin/python",
  "-m",
  "ipykernel",
  "-f",
  "{connection_file}"
 ],
 "env": {
  "HADOOP_CONF_DIR":"{{ hadoop_conf_dir }}",
  "PYSPARK_PYTHON":"{{ anaconda_home }}/bin/python",
  "SPARK_HOME": "{{ wrapper_spark_home }}",
  "WRAPPED_SPARK_HOME": "{{ spark_home }}",
  "PYTHONPATH": "{{ app_packages_home }}/lib/python2.7/site-packages:{{ jupyter_extension_venv }}/lib/python2.7/site-packages:{{ spark_home }}/python:{{ spark_home }}/python/lib/py4j-0.9-src.zip",
  "PYTHONSTARTUP": "{{ spark_home }}/python/pyspark/shell.py",
  "PYSPARK_SUBMIT_ARGS": "--master yarn-client --jars {{ spark_home }}/lib/spark-examples.jar pyspark-shell"
 }
}
```

**Comment by mdivk** [comment]
Thank you Siva, that helps, a new issue encountered though -> https://github.com/jupyterhub/jupyterhub/issues/2172

**Comment by ahshanmd** [comment]
@SivaMaplelabs @mdivk 

receiving the same error message while configuring jupyter notebook, has anyone tried with Spark2 on CDH
Env : CDH 5.15 , Spark 2.3

```
{
 "display_name": "PySpark/Python3 (Anaconda)",
 "language": "python",
 "argv": [
  "/usr/bin/python3.6",
  "-m",
  "ipykernel",
  "-f",
  "{connection_file}"
 ],
 "env": {
  "HADOOP_CONF_DIR":"/etc/hadoop/conf",
  "PYSPARK_PYTHON":"/usr/bin/python3.6",
  "PYSPARK_DRIVER_PYTHON":"jupyter",
  "SPARK_HOME": "/opt/cloudera/parcels/CDH/lib/spark",
  "spark.yarn.appMasterEnv.PYSPARK_PYTHON":"/usr/bin/python3.6",
  "spark.yarn.appMasterEnv.PYSPARK_DRIVER_PYTHON":"/usr/bin/python3.6",
  "PYTHONPATH": "/opt/cloudera/parcels/CDH/lib/spark:/opt/cloudera/parcels/SPARK2/lib/spark2/jars/py4j-0.10.7.jar"
 }
}
```

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
