### ISSUE TITLE
Move dummyauthenticator into JupyterHub

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#2169]
https://github.com/jupyterhub/dummyauthenticator is very useful when developing & debugging JupyterHub. We currently recommend using it in our CONTRIBUTING.md.

@minrk suggested that we move it into JupyterHub itself. The code is pretty small, and I think it makes a lot of sense for us to do that.

Tasks here would be:

1. Move the code for dummyauthenticator into JupyterHub
2. Write a few tests for it
3. Add some documentation for it.

**Comment by yuvipanda** [comment]
This is a good sized task for an outreachy participant.

**Comment by tuhina2020** [comment]
hi @yuvipanda @minrk. I would like to contribute as an Outreachy applicant to jupyterhub project 1 "Highly available JupyterHub proxy with Traefik".Is this issue meant for Outreachy applicants ? Can I get started on this one ?

**Comment by minrk** [comment]
@tuhina2020 hi, welcome! Oops, this task has already been completed. Please choose a different one from https://github.com/jupyterhub/outreachy/issues

**Comment by minrk** [comment]
Resolved by #2193
