### ISSUE TITLE
Add 'running_users' prometheus metric

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#2170]
We use [prometheus](https://github.com/prometheus/client_python) to expose metrics about JupyterHub operations. Currently we expose HTTP request stats and time it takes to spawn servers. We should expose more metrics!

One useful metric is 'currently running servers'. It should be a [gauge](https://github.com/prometheus/client_python#gauge) metric. Incremented when a user server starts, and decremented when it stops. We should also set it to an appropriate value when JupyterHub starts.

- [x] Declare the metric in metrics.py
- [x] Increment it when user server starts
- [x] Decrement it when user server stops
- [x] Set it to appropriate value when JupyterHub itself starts

**Comment by minrk** [comment]
closed by #2171
