### ISSUE TITLE
Redirect loop detected with JupyterHub 0.9.3 on AWS

### ISSUE THREAD

**Issue by kishitaku0630** [jupyterhub/jupyterhub#2175]
When I press the StartMyServer button on the home screen, I am having trouble outputting Internal Server Error.
So, I find a redirect loop in with JupyterHub 0.9.3 on AWS / Amazon Linux.

■AWS configuration
I am using AWS 's ALB and EC2.
I installed JupyterHub on EC2.
![aws configuration](https://user-images.githubusercontent.com/43508703/45926119-095f4300-bf5a-11e8-989b-58070e134a2c.png)

■JupyterHub log
[JupyterhubDefault-1Instance_jupiterhub.txt](https://github.com/jupyterhub/jupyterhub/files/2408570/JupyterhubDefault-1Instance_jupiterhub.txt)
[JupyterhubDefault-2Instance_jupiterhub.txt](https://github.com/jupyterhub/jupyterhub/files/2408571/JupyterhubDefault-2Instance_jupiterhub.txt)

■condaList
[condaList.txt](https://github.com/jupyterhub/jupyterhub/files/2408572/condaList.txt)

■memo
I succeed if I access EC2 's PublicIP. However, accessing ALB's DNS fails.
Also, if EC2 is one instance, it succeeds.

I look forward to your reply.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
