### ISSUE TITLE
template_paths - relative from where?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#2178]
`c.JupyterHub.template_paths` documentation could use a pointer regarding relative paths, should this be relative to the cloned repo folder?

See: https://jupyterhub.readthedocs.io/en/stable/api/app.html

**Comment by minrk** [comment]
Relative paths in JupyterHub are the same as the default interpretation in ~all contexts: relative to the current working directory. So if you run: `jupyterhub -f myconfig.py` that's loading the config `$PWD/myconfig.py`. The same is true of template_paths and any other path-related configuration. Paths are evaluated relative to $PWD, not the location of other files.

Is there any mention of relative paths there? When specifying paths in configuration, absolute paths are probably to be recommended.

**Comment by consideRatio** [comment]
Ah no, none, I lacked understanding and started guessing how things would work.

Id suggest either:
- close this
- action point, recommend usage of absolute paths

**Comment by manics** [comment]
I'll go for the first suggestion in https://github.com/jupyterhub/jupyterhub/issues/2178#issuecomment-423982518 :smile:
