### ISSUE TITLE
hub/login - breadcrumb with no content

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#2182]
On mobile, while visiting the login page, the breadcrumb can be seen at the top right corner. When clicked, it shows no content.

![breadcrumb](https://user-images.githubusercontent.com/3837114/45957014-4851cf00-c014-11e8-8fa4-984fdb04895b.gif)

**Comment by mdivk** [comment]
maybe at the very bottom of your phone screen? did you swipe your screen up and down, left and right?

**Comment by willingc** [comment]
@consideRatio Which mobile browser are you using?

**Comment by consideRatio** [comment]
This was some mobile version of Chrome on an IPhone 8.

Note that there is actually is no content to hide/show with the breadcrumb in this pre-login state, as the desktop view have no buttons etc in the header before the user has logged in. The minor bug is that the breadcrumb is showing no matter what, which gave me the false indication that there was content.

**Comment by willingc** [comment]
Yes, I was able to reproduce in Safari browser dev tools set to responsive and IPhone8.

I agree with priority and this is a minor bug that shouldn't display the hamburger unless there is content.
