### ISSUE TITLE
Add 'check_routes_duration_seconds' metric

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#2183]
We use [prometheus](https://github.com/prometheus/client_python) to expose metrics about JupyterHub operations. Currently we expose HTTP request stats and time it takes to spawn servers. We should expose more metrics!

One useful metric is 'Time taken to validate all routes in proxy'. JupyterHub occasionally checks the routes in the proxy, making sure there are no routes that shouldn't be there & that the routes that should be there are present. This happens both at application startup & at regular intervals. We should record how long it takes.

It should be a [histogram](https://github.com/prometheus/client_python#histogram) metric. We should observe the timing whenever a server is stopped. This is similar to the SERVER_SPAWN_DURATION_SECONDS metric, which is a histogram that observes the amount of time servers take to start.

- [ ] Declare the metric in metrics.py
- [ ] Observe time it takes for check_routes function in proxy.py to run

**Comment by minrk** [comment]
@kshitija08 that's great! You might want to look at [this recent PR](https://github.com/jupyterhub/jupyterhub/pull/2176) as an example for adding a new metric, and look at the SERVER_SPAWN_DURATION metric already in the code for an existing timer that is a histogram. You'll probably want to start with the [contribution guide](https://jupyterhub.readthedocs.io/en/latest/index.html#contributing) for JupyterHub.
