### ISSUE TITLE
impersonate User ?

### ISSUE THREAD

**Issue by whositwhatnow** [jupyterhub/jupyterhub#2187]
Does jupyterhub have an impersonate addon or function that will allow an administrator to impersonate the user for troubleshooting.

**Comment by mrclttnz** [comment]
Yes. If you are an afmin, you can go to Control Panel -> Admin and you have the list of users. For each user you can use the Access Server button to impersonate them.

**Comment by whositwhatnow** [comment]
I dont have the Access Server button, is it an extension i need to activate?  Running jupyterhub                   0.8.0b3

**Comment by ryanlovett** [comment]
You will also need to set [c.JupyterHub.admin_access](https://jupyterhub.readthedocs.io/en/stable/api/app.html) to True.

**Comment by whositwhatnow** [comment]
Thank you!


________________________________
