### ISSUE TITLE
Authentication with JWT posted to a call back

### ISSUE THREAD

**Issue by farzadz** [jupyterhub/jupyterhub#2189]
I am trying to make Jupyterhub use a customized authentication mechanism. The user redirects to a third party service and if authenticated, the external service makes the client submit a POST request containing a JWT to the callback URL. I went through the custom authenticators to find anything like this, however, I could not find anything. I appreciate if you suggest a way for dealing with this way of authentication.

**Comment by minrk** [comment]
This should be doable. You will need to register an additional handler for the callback. oauthenticator does this [here](https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/oauth2.py#L275).

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please leave a comment requesting this issue be reopened if there are still outstanding questions. Thanks to all!
