### ISSUE TITLE
Redirect on JavaScript request status code?

### ISSUE THREAD

**Issue by Siecje** [jupyterhub/jupyterhub#2199]
I have an authentication service in front of `JupyterHub`, so each request goes through it and only if you are authenticated will your request continue to `JupyterHub`. There is a problem when you have a notebook open, the `XHR`s will fail but you will not be redirected to login page because they are `XHR`s. Is it possible to add a handler when you get a certain status code to redirect to a specific page?

**Comment by minrk** [comment]
This wouldn't be a JupyterHub issue, I think, but one for jupyter/notebook. At the moment, I don't believe error handling of failed requests is extensible.

What is happening that is causing requests to be made to a running notebook server but no longer authenticated?

**Comment by Siecje** [comment]
Before a request reaches JupyterHub it goes through an authenticator and then I am using the `REMOTE_USER` authenticator which just trusts the `REMOTE_USER` HTTP header value. [0]

But the auth cookie/token can expire. If it expires and you make a request you will be redirected to login. 
Since every request goes through the authenticator, if a notebook is open and a JavaScript request fails, you are not redirected or prompted to login.

0: https://github.com/cwaldbieser/jhub_remote_user_authenticator

**Comment by minrk** [comment]
redirect on xhr is probably tricky and likely not what should be done anway. What probably makes more sense is to show a dialog saying "You have been logged out...click here to login again" with a link to the login page (ideally in a new tab to avoid leaving the current page). Still, I think this is an issue for jupyter/notebook in general, as there wouldn't be anything specific to jupyterhub in the implementation.
