### ISSUE TITLE
Example #3 - Run a shell script  has a bug

### ISSUE THREAD

**Issue by mdivk** [jupyterhub/jupyterhub#2202]
In the script in Example #3:

> USER=$1
> if ["$USER" == ""]; then
>     exit 1
> fi

There should be space inside the if condition. A few lines later another if condition is correct:

> if [ -d "$USER_DIRECTORY" ]; then

**Comment by minrk** [comment]
Thanks! Would you like to make a pull request to fix the issues?

**Comment by willingc** [comment]
In the file: https://github.com/jupyterhub/jupyterhub/blob/master/examples/bootstrap-script/README.md

The statement should read with spaces:

```
if [ "$USER" == "" ]; then
```
