### ISSUE TITLE
Exception in logs

### ISSUE THREAD

**Issue by katsar0v** [jupyterhub/jupyterhub#2204]
**Describe the bug**
API Exception in logs is being shown when there is an active window, but jupyter is down.

**To Reproduce**
1. Start jupyter (in my case in docker env with `dockerspawner`)
2. Leave the window open and kill the container
3. Look at the logs

**Logs**
```
[E 2018-09-28 07:50:15.367 JupyterHub web:1670] Uncaught exception GET /hub/user/admin/api/kernelspecs?1538121015219 (127.0.0.1)
    HTTPServerRequest(protocol='https', host='localhost', method='GET', uri='/hub/user/admin/api/kernelspecs?1538121015219', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 942, in get
        if "api" in user_path.split("/") and not user.active:
    AttributeError: 'NoneType' object has no attribute 'active'
```

**Comment by willingc** [comment]
@katsar0v What exactly do you mean by Jupyter being down? Can you provide more detail on which version of JupyterHub and what user you are using (it appears to be the admin user)? Thanks

**Comment by katsar0v** [comment]
Here is a further log:

```
[E 2018-10-15 15:35:45.016 JupyterHub web:1670] Uncaught exception GET /hub/user/test/api/sessions?1539617744784 (81.115.113.82)
    HTTPServerRequest(protocol='https', host='localhost.com', method='GET', uri='/hub/user/test/api/sessions?1539617744784', version='HTTP/1.1', remote_ip='81.115.113.82')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 942, in get
        if "api" in user_path.split("/") and not user.active:
    AttributeError: 'NoneType' object has no attribute 'active'
```

I think this comes when there is an active jupyter or jupyterlab window, but the kernel is down. Am not sure though. This seems to be some kind of an API Call, I also am using the cull idle script with following config:
```
c.JupyterHub.services = [
    {
        'name': 'cull-idle',
        'admin': True,
        'command': 'python /srv/jupyterhub/cull_idle_servers.py --timeout=7200'.split()
    }
]
```

JupyterHub has version `0.9.1` as well the cull idle script

**Comment by rcthomas** [comment]
We see this too, but with a slightly different setup.  We have a set up where we do upgrades by standing up a set of Docker containers in Rancher, and then we swap over the URL in our load balancer to point at the new stack.  When this happens, the new stack doesn't know all the users, but their browsers are still calling in.  I think this is why user is a `None.`

**Comment by katsar0v** [comment]
Already fixed: https://github.com/jupyterhub/jupyterhub/pull/2298
