### ISSUE TITLE
How to log to a different target?

### ISSUE THREAD

**Issue by 1kastner** [jupyterhub/jupyterhub#2209]
First of all thanks for the great project!

I wondered whether there is some config setting which allows me to control where the logs are going. I would like to push the logs to a CouchDB in JSON format. Later ELK would be rather the toolset of choice but in the meantime this is what I need to work with. At some point I would like to know what's going on on my JHub on some kind of GUI. Could I add such a thing as a kind of plugin? Did I maybe just miss it? Or is that a design decision?

When looking at https://github.com/jupyterhub/jupyterhub/tree/master/jupyterhub and https://www.tornadoweb.org/en/stable/_modules/tornado/log.html my first guess would be to directly work with the logging module. More help could come from https://pypi.org/project/json-logging/ and with some magic make everything asynchronous... I did not check in-depth whether those pieces really perfectly fit together but it is a sketch of an idea. Would that be helpful in the scope of this project?

**Comment by manics** [comment]
In general logs will go to stdout/err, and you can use a logging agent to ship them elsewhere
