### ISSUE TITLE
How to allow user to install needed libraries/packages for each notebook

### ISSUE THREAD

**Issue by mdivk** [jupyterhub/jupyterhub#2211]
We have JupyterHub set up successfully and are about to open to Data Science team for use, it is discussed and asked if they can install python libraries/packages they need for their individual notebook? could vary from notebook to notebook, from person to person, ideally they can manage that by themselve, otherwise it would become a pain for System Admin.

Thanks.

**Comment by mdivk** [comment]
Thanks. No we are not using docker, the hub will eventually be started by system admin (root) as a service. I believe this is a very common need and wonder what can we do without engaging system admin/root?

**Comment by ryanlovett** [comment]
https://jupyterhub.readthedocs.io/en/latest/reference/config-user-env.html

In most environments, users can install packages without admin privileges, e.g. `pip install --user`.

**Comment by ryanlovett** [comment]
@mdivk No, since users can usually write to their own home directory. pip and setuptools (easy_install) both support this:
https://www.python.org/dev/peps/pep-0370/

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Thanks to all!

**Comment by rchossein** [comment]
When we use DockerSpawner in JupyterHub, how can Sys Admin install a package for all the Docker containers that will be created for users? (default installation)

Also, how can one sudo inside the created Docker container (from the terminal in JupyterHub)? The password of the user does not work inside the container (to become sudo)

**Comment by sowmyar13** [comment]
I am also facing the same issue like @rchossein  , could any have response how we can have packages installed in the individual jupyterhub notebook containers

**Comment by 1kastner** [comment]
@sowmyar13 you are in the wrong github repo for that discussion. Please go to the repo of the corresponding Jupyter Notebook docker image if it is a bug. If you need advice, go to the forum. See the readme for further information.
