### ISSUE TITLE
MySQL installation for DB

### ISSUE THREAD

**Issue by whositwhatnow** [jupyterhub/jupyterhub#2212]
I'm having a heck of a time finding some info on using MySQL for the db's instead of sqlite.  has anyone used MySQL for jupyterhub deployments?

**Comment by willingc** [comment]
Hi @whositwhatnow, You can find information about using MySQL in the documentation [here](https://jupyterhub.readthedocs.io/en/stable/reference/database.html#using-an-rdbms-postgresql-mysql). We also test MySQL in our Travis tests as well for an additional example.
