### ISSUE TITLE
 traitlets.traitlets.TraitError: The 'ip' trait of a Server instance must be a unicode string, but a value of None <class 'NoneType'> was specified

### ISSUE THREAD

**Issue by lstillwe** [jupyterhub/jupyterhub#2213]
Just upgraded to latest version of JupyterHub and configurable-http-proxy and now get this error message:
 traitlets.traitlets.TraitError: The 'ip' trait of a Server instance must be a unicode string, but a value of None <class 'NoneType'> was specified

Help!

**Comment by eran-pinhas** [comment]
Happened to me too, any solutions?

**Comment by ReidWeb** [comment]
Also experiencing this issue

**Comment by eran-pinhas** [comment]
Are you using Docker spawner? Try debuging the dockerdspawner.py. I solved it using the `network_name = 'bridge'` in the config file.

See my repo at https://github.com/eran-pinhas/jupyterhub_dockerspawner_ldap/blob/master/hub/jupyterhub_config.py

**Comment by minrk** [comment]
which version of jupyterhub? Can you include your jupyterhub logs and jupyterhub_config.py? This could be a bug in the Spawner returning `None` for the ip rather than '127.0.0.1' or some such.

**Comment by eran-pinhas** [comment]
```python

import os
from jupyter_client.localinterfaces import public_ips

# Spawn single-user servers as Docker containers
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
# Spawn containers from this image
c.DockerSpawner.image = 'jupyterhub_custom_notebook' # 'jupyter/scipy-notebook'
# JupyterHub requires a single-user instance of the Notebook server, so we
# default to using the `start-singleuser.sh` script included in the
# jupyter/docker-stacks *-notebook images as the Docker run command when
# spawning containers.  Optionally, you can override the Docker run command
# using the DOCKER_SPAWN_CMD environment variable.

# c.Spawner.ip = '127.0.0.1'

spawn_cmd = "start-singleuser.sh"
c.DockerSpawner.extra_create_kwargs.update({ 'command': spawn_cmd })
# Connect containers to this Docker network
network_name = 'jupyterhub-network' 
c.DockerSpawner.use_internal_ip = True
c.DockerSpawner.network_name = network_name
ip = public_ips()[0]
c.JupyterHub.hub_ip = ip
# Pass the network name as argument to spawned containers
c.DockerSpawner.extra_host_config = { 'network_mode': network_name }
# Explicitly set notebook directory because we'll be mounting a host volume to
# it.  Most jupyter/docker-stacks *-notebook images run the Notebook server as
# user `jovyan`, and set the notebook directory to `/home/jovyan/work`.
# We follow the same convention.
notebook_dir = '/home/jovyan/work' # os.environ.get('DOCKER_NOTEBOOK_DIR') or
c.DockerSpawner.notebook_dir = notebook_dir
# Mount the real user's Docker volume on the host to the notebook user's
# notebook directory in the container
c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': notebook_dir }
# volume_driver is no longer a keyword argument to create_container()
# c.DockerSpawner.extra_create_kwargs.update({ 'volume_driver': 'local' })
# Remove containers once they are stopped
# c.DockerSpawner.remove_containers = True
# For debugging arguments passed to spawned containers
c.DockerSpawner.debug = True
```

to fix it I changed to `network_name = 'bridge'`

now I see I took it from [here](https://github.com/jupyterhub/jupyterhub-deploy-docker/blob/master/jupyterhub_config.py) and changed the network_name in the dockerfile instead of running `docker network create jupyterhub-network`

**Comment by eran-pinhas** [comment]
The version is 0.9.1, unfortunately logs are not available.

**Comment by minrk** [comment]
Can you run `docker inspect` on one of the user containers and share the NetworkSettings (`docker inspect <container-id> | jq '.[].NetworkSettings'` if you have jq), as well as any DOCKER_ environment variables (`env | grep DOCKER | sort`)?

**Comment by robnagler** [comment]
I'm running into the same issue when running `jupyter-labhub` under DockerSpawner. In looking [at labhubapp.py](https://github.com/jupyterlab/jupyterlab/blob/ef6f42a592e79b2693685895d8a654c4f8d9e166/jupyterlab/labhubapp.py), it seems that it is missing quite a bit form [singleuser.py](https://github.com/jupyterhub/jupyterhub/blob/94bb9ed00da9600e0ec2ef85cf924b9713f00ff8/jupyterhub/singleuser.py), e.g. `ip`.

Perhaps I'm not understanding how labhub is supposed to work with DockerSpawner.

**Comment by robnagler** [comment]
Red herring.  We have our own wrapper for jupyter-singleuser that needed to be updated to jupyter-labhub.

**Comment by DeoLeung** [comment]
same here with `jupyterhub==0.9.4`, try to set anything on `extra_create_args` got this error message

**Comment by Yar-R** [comment]
Same,
Not using dockerSpawner.
crashes when try to start a shared-notebook service as 
```
{
        'name': 'test',
        'url': 'http:/127.0.0.1:{port}'.format(port=10000),
        'command': ['jupyterhub-singleuser', '--group=formgrade-{name}'.format(name='test'), '--debug'],
        'user': user,
        'cwd': '/var/www/jh/grader-sity/{user}'.format(user='grader-test'),
        'api_token': '***',
    }
```

**Comment by Yar-R** [comment]
> Same,
> Not using dockerSpawner.
> crashes when trying to start a shared-notebook service as
> 
> ```
> {
>         'name': 'test',
>         'url': 'http:/127.0.0.1:{port}'.format(port=10000),
>         'command': ['jupyterhub-singleuser', '--group=formgrade-{name}'.format(name='test'), '--debug'],
>         'user': user,
>         'cwd': '/var/www/jh/grader-sity/{user}'.format(user='grader-test'),
>         'api_token': '***',
>     }
> ```
> 
> I think @minrk knows how to deal with it

Sorry figured it out

**Comment by manics** [comment]
Possible solution https://github.com/jupyterhub/dockerspawner/issues/369#issuecomment-750695646
