### ISSUE TITLE
Create an async version of options_from_form

### ISSUE THREAD

**Issue by DeepHorizons** [jupyterhub/jupyterhub#2214]
I would like to see an async version of `Spawner.options_from_form` much like what `Spawner.get_options_form` is to `Spawner.options_form`.

It looks doable, create a similar function to `get_options_form` (`process_options_form`?), then modify [L150 of pages.py](https://github.com/jupyterhub/jupyterhub/blob/bd16299ffbf58614a789ae047aab551ac056e38d/jupyterhub/handlers/pages.py#L150)

I can get the PR warmed up unless there is a reason this was not done.

**Comment by minrk** [comment]
Yeah, that makes sense! Unlike `get_options_form`, I think `options_from_form` can be made async with the appropriate addition of `utils.maybe_future`, instead of needing a new method.
