### ISSUE TITLE
Question: AD/LDAP integration and home users

### ISSUE THREAD

**Issue by rainmanh** [jupyterhub/jupyterhub#2216]
Hi,

I have currently done an AD integration of jupyterhub using as a client the classic ldap component.

After a couple of days of lot of fun, I managed to have it running but now I got some questions user home related.

While by default the  AD users got their home defined in *nix attributes as : `/home/username`

I would like to have the specific home user directory for the jupyter user somewhere else so `/opt/home/` instead.

I have spent quite a while playing around with the following directives but I am not having much luck..

```
c.LDAPAuthenticator.create_user_home_dir = True
c.LDAPAuthenticator.create_user_home_dir_cmd = ['mkhomedir_helper']
c.NotebookApp.default_url = 'tree'
```

**Comment by dhirschfeld** [comment]
If you have a problem with `LDAPAuthenticator` you're probably best to ask over at that repo:
https://github.com/jupyterhub/ldapauthenticator

Where do you see the `create_user_home_dir` configuration? AFAICS it doesn't exist in either `LDAPAuthenticator` or `JupyterHub`?

**Comment by rainmanh** [comment]
Hi,

True, apologies for posting in here.

The configuration is coming from here:

https://pypi.org/project/jupyterhub-ldap-authenticator/

**Comment by dhirschfeld** [comment]
It looks like that page isn't up to date. I'd refer to the GitHub README for the correct config.
