### ISSUE TITLE
How  can I  expose JupyterHub helm chart using NGINX ingress controllers or nodePort ? 

### ISSUE THREAD

**Issue by zmkhazi** [jupyterhub/jupyterhub#2222]
If you are having issues with installation or configuration, you may ask for help on the JupyterHub gitter channel or file an issue here.

**Comment by zmkhazi** [comment]
This type of yaml will fail on our Kubernetes cluster because it is not a cloud provider with the ability to dynamically provision load balancers.

apiVersion: v1
kind: Service
metadata:
  name: proxy-public
  labels:
    component: proxy-public
    app: jupyterhub
    release: RELEASE-NAME
    chart: jupyterhub-0.7.0
    heritage: Tiller
spec:
  selector:
    # TODO: Refactor to utilize the helpers
    component: proxy
    release: RELEASE-NAME
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
      # allow proxy.service.nodePort for http
  type: LoadBalancer

**Comment by manics** [comment]
https://zero-to-jupyterhub.readthedocs.io/en/stable/
