### ISSUE TITLE
Get individual home folder for LDAP users & with PAMauthenticator

### ISSUE THREAD

**Issue by Paperone80** [jupyterhub/jupyterhub#2228]
Hi, when non-local users access via LDAP the JupyterHub server individual home folder profiles are being fetched as well. For example:
```
/home/username
/HOME/username
/home2/username
/tmp/home/...
```

However, I only know how to make /home/username work and configured via the following which works for most: 
`--Spawner.default_url='tree/home/{username}'`

Any way of fetching the individual home folders and pass them to --Spawner.default_url or different parameter? Thanks.

**Comment by vilhelmen** [comment]
How are you connecting to LDAP? If it's SSSD, I manually override their homedir location as follows in `/etc/sssd/sssd.conf` (it also works when joined to an AD domain):

```
[domain/ldap]
override_homedir = /users/home/%u
```

(I also generally override their shell to /bin/bash (`override_shell = /bin/bash`), though I'm not sure if JH respects the default user terminal. I'm not even sure how to change that in our domain)

If you don't have access to the LDAP/AD/SSSD configuration, I believe you can use `c.Spawner.notebook_dir = /home/%U` (note this is uppercase while the SSSD configuration is lowercase), but things may break if the user every references `~` or launches a terminal. I've never tries to control it this way, so your mileage may vary.

If you have users SSHing in, they will still go to their domain-specified homedir, however, so I would _strongly_ suggest fixing it at the LDAP level.

**Comment by Paperone80** [comment]
@vilhelmen, thanks a lot for your help and pointing me in the right direction to solve it. 

For anybody else who comes across this: 
Unfortunately, sssd.service is not being used. Checked with:
`sudo systemctl status sssd.service`
> sssd.service - System Security Services Daemon
>    Loaded: loaded (/usr/lib/systemd/system/sssd.service; disabled; vendor preset: disabled)
>    Active: inactive (dead) 

However, I remembered that Quest VAS is used. Links [here](https://support.oneidentity.com/authentication-services/kb/54375/how-to-override-or-change-mutliple-users-home-directories-on-specific-machines-) and [here](https://support.oneidentity.com/authentication-services/kb/87944/user-override-options-and-sample-for-quest-authentication-services) are pointing to resources how to override.
Check examples in file via:
`sudo nano /etc/opt/quest/vas/user-override.sample`

Create or Open:
`sudo nano /etc/opt/quest/vas/user-override`
and insert the following to have any user on the system having its homedir in /home/username and /bin/bash as standard.

> *:::::/home/%s:/bin/bash

Check Active Directory (AD) settings with 
`sudo /opt/quest/bin/vastool list -f users`
-f Force vasd to update its cache 

Test override settings:
`sudo /opt/quest/bin/vastool list -o users`
-o Process override information

Exit SSH or any login and relogin
```
$ cd ~ 
$ pwd
```
and hopefully you and every other user are now in: 

> /home/username
