### ISSUE TITLE
ImportError: cannot import name 'Provider'

### ISSUE THREAD

**Issue by spiketren** [jupyterhub/jupyterhub#2229]
Dear JupyterHub developers,

I can't start jupyterhub because of an importing error:

root@hpc:~# jupyterhub
Traceback (most recent call last):
  File "/raid/opt/hpc/anaconda/python3/bin/jupyterhub", line 3, in <module>
    from jupyterhub.app import main
  File "/raid/opt/hpc/anaconda/python3/lib/python3.6/site-packages/jupyterhub/app.py", line 57, in <module>
    from .oauth.store import make_provider
  File "/raid/opt/hpc/anaconda/python3/lib/python3.6/site-packages/jupyterhub/oauth/store.py", line 13, in <module>
    from oauth2 import Provider
ImportError: cannot import name 'Provider'
root@hpc:~# 

Here are the package versions:

root@hpc:~# pip show jupyterhub
Name: jupyterhub
Version: 0.9.4
Summary: JupyterHub: A multi-user server for Jupyter notebooks
Home-page: https://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: BSD
Location: /raid/opt/hpc/anaconda/python3/lib/python3.6/site-packages
Requires: traitlets, alembic, jinja2, requests, tornado, prometheus-client, SQLAlchemy, async-generator, pamela, python-dateutil, python-oauth2
Required-by: jupyterhub-systemdspawner

root@hpc:~# pip show oauth2
Name: oauth2
Version: 1.9.0.post1
Summary: library for OAuth version 1.9
Home-page: http://github.com/joestump/python-oauth2
Author: Joe Stump
Author-email: joe@simplegeo.com
License: MIT License
Location: /raid/opt/hpc/anaconda/python3/lib/python3.6/site-packages
Requires: httplib2
Required-by: 
root@hpc:~# 

There seems to be some dependency problems here? Could you help fix it or provide a work-around, if any?

Thanks!
Tren

**Comment by willingc** [comment]
Hi @spiketren, It would be helpful if you provided information about how you are installing jupyterhub. I would recommend installing jupyterhub using conda and then jupyterhub-systemdspawner using pip. 

If you are still seeing the error, please start `jupyterhub --debug` and provide the output here. Thanks.

**Comment by uditarora** [comment]
I am facing the same issue on my system. I can't run `jupyterhub --debug` as well because it gives me the same error.

I tried upgrading jupyterhub to the latest version using pip as well, but still got the same error.

**Comment by spiketren** [comment]
root@hpc:~# jupyterhub --debug
Traceback (most recent call last):
  File "/raid/opt/hpc/anaconda/python3/bin/jupyterhub", line 3, in <module>
    from jupyterhub.app import main
  File "/raid/opt/hpc/anaconda/python3/lib/python3.6/site-packages/jupyterhub/app.py", line 57, in <module>
    from .oauth.store import make_provider
  File "/raid/opt/hpc/anaconda/python3/lib/python3.6/site-packages/jupyterhub/oauth/store.py", line 13, in <module>
    from oauth2 import Provider
ImportError: cannot import name 'Provider'
root@hpc:~# pip install Provider
Collecting Provider
  Could not find a version that satisfies the requirement Provider (from versions: )
No matching distribution found for Provider
root@hpc:~# conda install Provider
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - provider

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

root@hpc:~#

**Comment by minrk** [comment]
The package that provides this is called `python-oauth2`:

    conda install python-oauth2

or

    pip install python-oauth2

**Comment by spiketren** [comment]
"pip install python-oauth2" led to "Requirement already satisfied: python-oauth2..."
but "conda install python-oauth2" indeed solved the problem. Thanks!
