### ISSUE TITLE
Jupyterhub 403 : Forbidden Blocking request with non-local 'Host'. If the notebook should be accessible at that name, set NotebookApp.allow_remote_access to disable the check.

### ISSUE THREAD

**Issue by kide007** [jupyterhub/jupyterhub#2230]
After the install when i try to login i get  Jupyterhub 403 : Forbidden

In log, i see 
[W 2018-10-09 14:08:16.722 hbsda handlers:447] Blocking request with non-local 'Host' hbsda (hbsda:444). If the notebook should be accessible at that name, set NotebookApp.allow_remote_access to disable the check.
[W 2018-10-09 14:08:16.723 hbsda log:48] 403 GET /user/hbsda/static/style/style.min.css?v=4b4b8cb1e49605137f77fed041f8922b (::ffff:10.26.120.241) 2.01ms referer=http://hbsda:444/user/hbsda/tree?
[W 2018-10-09 14:08:16.725 hbsda handlers:447] Blocking request with non-local 'Host' hbsda (hbsda:444). If the notebook should be accessible at that name, set NotebookApp.allow_remote_access to disable the check.
[W 2018-10-09 14:08:16.727 hbsda log:48] 403 GET /user/hbsda/custom/custom.css (::ffff:10.26.120.241) 1.99ms referer=http://hbsda:444/user/hbsda/tree?

**Comment by minrk** [comment]
What version of jupyterhub? I believe this is fixed in recent JupyterHub releases. If you are pinned to an old version of jupyterhub, you can set the configuration mentioned in the message:

```python
c.NotebookApp.allow_remote_access = True
```

in `jupyter_notebook_config.py`, e.g. `/etc/jupyter/jupyter_notebook_config.py` in your user image if using container-based deployment.

**Comment by minrk** [comment]
Either one is fine. In the long run, updating JupyterHub is a good idea, but if you want to get it working right now with minimal disruption, adding a single line of config to the user env is the lowest impact.

**Comment by Blackrobe** [comment]
Hi @minrk, I ran into this exact same issue.
I'm installing a latest version of jupyterhub inside a vagrant VM (Debian 9), and then downgrade it using
```
pip3 install \
jupyterhub==0.8.1 \
jupyterhub-systemdspawner==0.9.10 \
oauthenticator==0.7.3
```
I already set up `c.NotebookApp.allow_remote_access = True` and restarted the server, but it has no effect. Still 403.
Tried killing all jupyter-related processses including the `configurable-http-proxy` process and restarting the server again, no effect.

But when upgrading those pip packages above into their original, everything works again (after running `jupyterhub update-db`)

Do you have suggestions on how to downgrade into an older version of jupyterhub?

**Comment by Blackrobe** [comment]
> Hi @minrk, I ran into this exact same issue.
> I'm installing a latest version of jupyterhub inside a vagrant VM (Debian 9), and then downgrade it using
> 
> ```
> pip3 install jupyterhub==0.8.1
> ```
> 
> Here's the log
> 
> ```
> -- Subject: Unit jupyterhub.service has finished start-up
> -- Defined-By: systemd
> -- Support: https://www.debian.org/support
> -- 
> -- Unit jupyterhub.service has finished starting up.
> -- 
> -- The start-up result is done.
> Feb 23 16:20:50 Debian-Test jupyterhub[8771]: [I 2019-02-23 16:20:50.989 JupyterHub app:1673] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.4
> Feb 23 16:20:50 Debian-Test jupyterhub[8771]: [I 2019-02-23 16:20:50.989 JupyterHub app:1673] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.4
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: [I 2019-02-23 16:20:51.001 JupyterHub app:1016] Loading cookie_secret from /opt/jupyterhub/jupyterhub_cookie_secret
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: [I 2019-02-23 16:20:51.021 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: [W 2019-02-23 16:20:51.023 JupyterHub app:1173] No admin users, admin interface will be unavailable.
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: [W 2019-02-23 16:20:51.023 JupyterHub app:1174] Add any administrative users to `c.Authenticator.admin_users` in config.
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: [I 2019-02-23 16:20:51.023 JupyterHub app:1201] Not using whitelist. Any authenticated user will be allowed.
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: [I 2019-02-23 16:20:51.061 JupyterHub app:1454] vagrant still running
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: [I 2019-02-23 16:20:51.071 JupyterHub app:1855] Hub API listening on http://127.0.0.1:8081/hub/
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: [W 2019-02-23 16:20:51.072 JupyterHub proxy:565] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: [I 2019-02-23 16:20:51.072 JupyterHub proxy:567] Starting proxy @ http://:8000
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: 16:20:51.206 - info: [ConfigProxy] Proxying http://*:8000 to (no default)
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: 16:20:51.208 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: 16:20:51.514 - info: [ConfigProxy] 200 GET /api/routes
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: [I 2019-02-23 16:20:51.515 JupyterHub proxy:301] Checking routes
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: [I 2019-02-23 16:20:51.515 JupyterHub proxy:370] Adding default route for Hub: / => http://127.0.0.1:8081
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: [W 2019-02-23 16:20:51.515 JupyterHub proxy:324] Adding missing route for /user/vagrant/ (<jupyterhub.objects.Server object at 0x7f5e317faba8>)
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: [I 2019-02-23 16:20:51.516 JupyterHub proxy:242] Adding user vagrant to proxy /user/vagrant/ => http://127.0.0.1:52171
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: 16:20:51.518 - info: [ConfigProxy] Adding route /user/vagrant -> http://127.0.0.1:52171
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: 16:20:51.520 - info: [ConfigProxy] 201 POST /api/routes/user/vagrant
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: 16:20:51.521 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: 16:20:51.522 - info: [ConfigProxy] 201 POST /api/routes/
> Feb 23 16:20:51 Debian-Test jupyterhub[8771]: [I 2019-02-23 16:20:51.523 JupyterHub app:1912] JupyterHub is now running at http://:8000
> Feb 23 16:20:52 Debian-Test jupyterhub[8715]: [W 2019-02-23 16:20:52.044 SingleUserNotebookApp handlers:442] Blocking request with non-local 'Host' 192.168.10.10 (192.168.10.10:8000). If the notebook should be accessible at that name, set NotebookApp.allow_remote_access to disable the check.
> Feb 23 16:20:52 Debian-Test jupyterhub[8715]: [W 2019-02-23 16:20:52.046 SingleUserNotebookApp log:122] 403 GET /user/vagrant/tree? (@::ffff:192.168.10.1) 2.84ms
> Feb 23 16:20:52 Debian-Test jupyterhub[8715]: [W 2019-02-23 16:20:52.147 SingleUserNotebookApp handlers:442] Blocking request with non-local 'Host' 192.168.10.10 (192.168.10.10:8000). If the notebook should be accessible at that name, set NotebookApp.allow_remote_access to disable the check.
> ```
> 
> I already set up `c.NotebookApp.allow_remote_access = True` and restarted the server, but it has no effect. Still 403.
> Tried killing all jupyter-related processses including the `configurable-http-proxy` process and restarting the server again, no effect.
> 
> But when upgrading jupyterhub pip package above into their original, everything works again (after running `jupyterhub upgrade-db`)
> 
> Was it because of the different version of PAM authenticator?
> 
> Do you have suggestions on how to downgrade into an older version of jupyterhub?

oh hey, I ran `pip3 freeze` in our production server that has older jupyterhub version installed, create a pip requirement file based on pip3 freeze result and install it on the vagrant VM. Everything works fine now.

**Comment by minrk** [comment]
Great that you figured it out!

**Comment by lmsasu** [comment]
> What version of jupyterhub? I believe this is fixed in recent JupyterHub releases. If you are pinned to an old version of jupyterhub, you can set the configuration mentioned in the message:
> 
> ```python
> c.NotebookApp.allow_remote_access = True
> ```
> 
> in `jupyter_notebook_config.py`, e.g. `/etc/jupyter/jupyter_notebook_config.py` in your user image if using container-based deployment.

In Windows, that config file is under c:\Users\your_user_name\.jupyter\jupyter_notebook_config.py
