### ISSUE TITLE
Unknown error in handling PYTHONSTARTUP file /opt/cloudera/parcels/CDH/lib/spark/python/pyspark/shell.py

### ISSUE THREAD

**Issue by mdivk** [jupyterhub/jupyterhub#2231]
Error above in the subject when starting a kernel, 
Below is my kernel spec:

```

["/opt/cloudera/parcels/Anaconda/bin/python",
 "-m", "ipykernel", "-f", "connection_file}"
],
"display_name":"PySpark-RXIE",
"language":"python",
"env": {
  "HADOOP_CONF_DIR":"{{ hadoop_conf_dir }}",
  "PYSPARK_PYTHON":"/opt/cloudera/parcels/Anaconda/bin/python",
  "SPARK_HOME": "{{ wrapper_spark_home }}",
  "WRAPPED_SPARK_HOME": "{{ spark_home }}",
  "PYTHONPATH": "{{ app_packages_home }}/lib/python2.7/site-packages:{{ jupyter_extension_venv }}/lib/python2.7/site-packages:{{ spark_home }}/python:{{ spark_home }}/python/lib/py4j-0.9-src.zip",
  "PYTHONSTARTUP": "/opt/cloudera/parcels/CDH/lib/spark/python/pyspark/shell.py",
  "PYSPARK_SUBMIT_ARGS": "--master yarn-client --jars {{ spark_home }}/lib/spark-examples.jar pyspark-shell"
 }
}


```
What is going on there in the backend? from the output I can see the following output:

> 
> [I 2018-10-09 16:32:46.388 SingleUserNotebookApp handlers:153] Creating new notebook in
> [I 2018-10-09 16:32:46.408 SingleUserNotebookApp log:122] 201 POST /user/hadoopuser/api/contents (hadoopuser@192.168.103.81) 20.92ms
> [I 2018-10-09 16:32:46.802 SingleUserNotebookApp log:122] 200 GET /user/hadoopuser/notebooks/Untitled10.ipynb?kernel_name=kernel-rxie (hadoopuser@192.168.103.81) 380.93ms
> [I 2018-10-09 16:32:47.200 SingleUserNotebookApp log:122] 200 GET /user/hadoopuser/api/config/notebook?_=1539117166770 (hadoopuser@192.168.103.81) 4.00ms
> [I 2018-10-09 16:32:47.204 SingleUserNotebookApp log:122] 200 GET /user/hadoopuser/api/config/common?_=1539117166771 (hadoopuser@192.168.103.81) 3.11ms
> [I 2018-10-09 16:32:47.271 SingleUserNotebookApp log:122] 200 GET /user/hadoopuser/api/kernelspecs (hadoopuser@192.168.103.81) 4.19ms
> [I 2018-10-09 16:32:47.286 SingleUserNotebookApp log:122] 200 GET /user/hadoopuser/api/contents/Untitled10.ipynb?type=notebook&_=1539117166772 (hadoopuser@192.168.103.81) 6.51ms
> [I 2018-10-09 16:32:47.407 SingleUserNotebookApp kernelmanager:164] Kernel started: 86ba15c1-a155-4b64-b17b-5a64d9a4dd9e
> [I 2018-10-09 16:32:47.409 SingleUserNotebookApp log:122] 201 POST /user/hadoopuser/api/sessions (hadoopuser@192.168.103.81) 28.41ms
> [I 2018-10-09 16:32:47.413 SingleUserNotebookApp log:122] 200 GET /user/hadoopuser/api/contents/Untitled10.ipynb/checkpoints?_=1539117166773 (hadoopuser@192.168.103.81) 2.04ms
> [W 2018-10-09 16:32:47.444 SingleUserNotebookApp log:122] 404 GET /user/hadoopuser/nbextensions/widgets/notebook/js/extension.js?v=20181009163240 (hadoopuser@192.168.103.81) 11.73ms
> [IPKernelApp] WARNING | Unknown error in handling PYTHONSTARTUP file /opt/cloudera/parcels/CDH/lib/spark/python/pyspark/shell.py:
> [W 2018-10-09 16:33:47.912 SingleUserNotebookApp handlers:231] Timeout waiting for kernel_info reply from 86ba15c1-a155-4b64-b17b-5a64d9a4dd9e
> [I 2018-10-09 16:33:47.913 SingleUserNotebookApp log:122] 101 GET /user/hadoopuser/api/kernels/86ba15c1-a155-4b64-b17b-5a64d9a4dd9e/channels?session_id=802db006a06445f485f0f469d9f1b967 (hadoopuser@192.168.103.81) 60006.25ms
> [I 2018-10-09 16:34:47.391 SingleUserNotebookApp log:122] 200 GET /user/hadoopuser/api/contents/Untitled10.ipynb?content=0&_=1539117166774 (hadoopuser@192.168.103.81) 2.59ms
> [I 2018-10-09 16:34:47.405 SingleUserNotebookApp handlers:164] Saving file at /Untitled10.ipynb
> [I 2018-10-09 16:34:47.422 SingleUserNotebookApp log:122] 200 PUT /user/hadoopuser/api/contents/Untitled10.ipynb (hadoopuser@192.168.103.81) 18.59ms
> 

Thank you. The kernel is adapted from working kernel found here.

**Comment by minrk** [comment]
I don't think you can use the pyspark shell as PYTHONSTARTUP with jupyter. That script is meant to start a whole interactive Python session, as I understand.

I think you have to take a different approach and use something that just locates pyspark for import, rather than doing all the extra stuff that the pyspark script does.
