### ISSUE TITLE
PAM Authentication failed (adaragso@x.x.x.x): [PAM Error 3] Error in service module

### ISSUE THREAD

**Issue by atne2008** [jupyterhub/jupyterhub#2235]
help! I am really confused what is the usename and password, I entered the username and password of my Centos, but is show me PAM authenticated failed? how could login? I just installed the jupyterhub
![screen shot 2018-10-11 at 3 41 40 pm](https://user-images.githubusercontent.com/44074149/46838456-3b501200-cd6e-11e8-9f00-56a75bce03c8.png)

tried in both root and user not working. thought I want to run it on user.

jupterhub_config.py
c.JupyterHub.admin_access = True
c.Authenticator.admin_users = {'adargaso','jupteruser'}
c.Authenticator.whitelist = {'adargaso','jupteruser','user1'}
c.LocalAuthenticator.create_system_users = True
c.JupyterHub.hub_connect_ip = 'xx:yy:zz:bb'
c.JupyterHub.hub_connect_port = xyzs
c.JupyterHub.ip = 'xx:yy:zz:bb'
c.JupyterHub.port = xyzb
c.PAMAuthenticator.open_sessions = False

and 
jupyterhub --version
0.9.4
added white listed user in host 
sudo -u adargaso python3 -c 'import pwd; print(pwd.getpwnam("jupteruser"))' 
my computer: remote centos server
edit /etc/pam.d/login and put a comment infront of the pam_loginuid.so not working
python --version
Python 2.7.5 this is default but I'm using python --version
Python 3.5 and above

[I 2018-10-11 15:20:16.782 JupyterHub app:1673] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.4
[I 2018-10-11 15:20:16.782 JupyterHub app:1673] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.4
[I 2018-10-11 15:20:16.784 JupyterHub app:1016] Loading cookie_secret from /etc/jupyterhub/jupyterhub_cookie_secret
[W 2018-10-11 15:20:16.812 JupyterHub app:1131] JupyterHub.hub_connect_port is deprecated as of 0.9. Use JupyterHub.hub_connect_url to fully specify the URL for connecting to the Hub.
[I 2018-10-11 15:20:16.813 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[I 2018-10-11 15:20:16.872 JupyterHub app:1855] Hub API listening on http://ip/hub/
[W 2018-10-11 15:20:16.874 JupyterHub proxy:565] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2018-10-11 15:20:16.875 JupyterHub proxy:567] Starting proxy @ http://ip:port/
15:20:17.060 - info: [ConfigProxy] Proxying http://ip:portto (no default)
15:20:17.062 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
15:20:17.199 - info: [ConfigProxy] 200 GET /api/routes 
[I 2018-10-11 15:20:17.200 JupyterHub proxy:301] Checking routes
[I 2018-10-11 15:20:17.201 JupyterHub proxy:370] Adding default route for Hub: / => http://ip:port
15:20:17.205 - info: [ConfigProxy] Adding route / -> http://ip:9083
15:20:17.206 - info: [ConfigProxy] 201 POST /api/routes/ 
[I 2018-10-11 15:20:17.207 JupyterHub app:1912] JupyterHub is now running at http://ip:port/
[W 2018-10-11 15:20:26.732 JupyterHub auth:618] PAM Authentication failed (host_name@10.192.68.108): [PAM Error 3] Error in service module
[W 2018-10-11 15:20:26.732 JupyterHub base:504] Failed login for host_name
[I 2018-10-11 15:20:26.763 JupyterHub log:158] 200 POST /hub/login?next= (@10.192.68.108) 1967.06ms
[W 2018-10-11 15:20:36.080 JupyterHub auth:618] PAM Authentication failed (adaragso@10.192.68.108): [PAM Error 3] Error in service module
[W 2018-10-11 15:20:36.081 JupyterHub base:504] Failed login for adaragso
[I 2018-10-11 15:20:36.082 JupyterHub log:158] 200 POST /hub/login?next= (@10.192.68.108) 1976.12ms
[W 2018-10-11 15:20:55.565 JupyterHub auth:618] PAM Authentication failed (jupteruser@10.192.68.108): [PAM Error 7] Authentication failure
[W 2018-10-11 15:20:55.565 JupyterHub base:504] Failed login for jupteruser
[I 2018-10-11 15:20:55.567 JupyterHub log:158] 200 POST /hub/login?next= (@10.192.68.108) 1584.56ms
[W 2018-10-11 15:21:03.144 JupyterHub auth:618] PAM Authentication failed (jupteruser@10.192.68.108): [PAM Error 7] Authentication failure
[W 2018-10-11 15:21:03.145 JupyterHub base:504] Failed login for jupteruser
[I 2018-10-11 15:21:03.146 JupyterHub log:158] 200 POST /hub/login?next= (@10.192.68.108) 2212.07ms
[W 2018-10-11 15:22:04.157 JupyterHub auth:618] PAM Authentication failed (adaragso@10.192.68.108): [PAM Error 3] Error in service module
[W 2018-10-11 15:22:04.157 JupyterHub base:504] Failed login for adaragso
[I 2018-10-11 15:22:04.158 JupyterHub log:158] 200 POST /hub/login?next= (@10.192.68.108) 1724.88ms
^C
Interrupted
[I 2018-10-11 15:22:31.869 JupyterHub app:1706] Cleaning up single-user servers...
[I 2018-10-11 15:22:31.869 JupyterHub proxy:627] Cleaning up proxy[28456]...
[I 2018-10-11 15:22:31.870 JupyterHub app:1739] ...done
[root@host_name jupyterhub]# su jupteruser
[jupteruser@host_name jupyterhub]$

**Comment by minrk** [comment]
PAMAuth seems to often require extra configuration with CentOS. I'm not sure what the needed changes hare, but you might check the pam logs to see if there's a hint there. Typically, sessions must be disabled, too:

```python
c.PAMAuthenticator.open_sessions = False
```

**Comment by kevin-cyx** [comment]
You can create a new user in Linux first, for example 'test0'. And then include it in c.Authenticator.whitelist = {'test0'}.
