### ISSUE TITLE
CAN'T embed jupyterhub into iframe

### ISSUE THREAD

**Issue by djknight1** [jupyterhub/jupyterhub#2238]
it always shows 
> Refused to display 'http://47.107.83.55:8000/user/testuser/tree?' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".

And I trid all the old issus's solution, none of it works fine for me.
`c.NotebookApp.tornado_settings = {
    'headers': {
        'Content-Security-Policy': "frame-ancestors 'self' http://localhost:8080 "
    }
}`
`c.JupyterHub.tornado_settings = {
    'headers': {
        'Content-Security-Policy': "frame-ancestors 'self' http://localhost:8080 "
  }
}`
These are the current config

**Comment by 2efPer** [comment]
Duplicate of #379

**Comment by betatim** [comment]
Closed in favour of the original issue #379
