### ISSUE TITLE
Different kernel not appearing for single-users

### ISSUE THREAD

**Issue by sidebo** [jupyterhub/jupyterhub#2241]
I have C++ ROOT installed and can open a jupyter-notebook and run such a notebook without problem. However, upon launching and logging into the hub this kernel is not visible. Do I need to do something  with the hub to get it to update its kernel list or something?

**Comment by sidebo** [comment]
So I got one step further by checking the documentation more carefully and realising I should put ROOT somewhere system-wide available. Previously it was only one (my) user that could launch a notebook.

I moved the program folder to the /opt directory, now non-root users can run the ROOT notebook as well. However, the kernel is not visible on the hub, even though it's listed at `jupyter kernelspec list`. I tried adding it manually with

`sudo jupyter kernelspec install $ROOTSYS/etc/notebook/kernels/root --name ROOT6`

which made a second version of the kernel appear in the list. This kernel now shows up on the hub. However, no user can successfully run the notebook: it just gets stuck at "Kernel starting, please wait..." forever, without further information (see figure). Any help is very welcome.

![screen shot 2018-10-16 at 17 34 15](https://user-images.githubusercontent.com/8863780/47028983-c82e0d80-d16a-11e8-8b79-f4b11f1fb8a8.png)

**Comment by sidebo** [comment]
UPDATE: In the jupyterhub log I have this:

`/home/linuxbrew/.linuxbrew/opt/python/bin/python3.7: Error while finding module specification for 'JupyROOT.kernel.rootkernel' (ModuleNotFoundError: No module named 'JupyROOT')`

so for some reason the kernel is not found when on the hub (but works fine on a local notebook).

**Comment by minrk** [comment]
Can you sohow the contents of kernel.json? There might be something missing such as a relative path that should be absolute.
