### ISSUE TITLE
Authentication issue caused endless Exceptions

### ISSUE THREAD

**Issue by mdivk** [jupyterhub/jupyterhub#2252]
In our current JupyterHub, it is enabled with Kerberos ticket granting mechanism, during some test it is found in the case a user failed to get a ticket, then the JupyterHub service keeps throwing out Exception below:

Oct 18 10:43:00 cedgedev03 jupyterhub[14323]: 18/10/18 10:43:00 WARN security.UserGroupInformation: PriviledgedActionException as:xxxxxxx (auth:KERBEROS) cause:java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]

Seeing this Exception is expected because no ticket in place, however, I believe the JupyterHub service 
should stop that after maybe 10 times attempts, right?

**Comment by minrk** [comment]
What Authenticator is being used? It's unclear what actions are being attempted that are triggering the warning.
