### ISSUE TITLE
GPUs with GCP Makes TLJH and Z2JH Hang?

### ISSUE THREAD

**Issue by jzf2101** [jupyterhub/jupyterhub#2256]
I've tried using GPUs with Z2JH and TLJH and on both occasions, I end up getting an IP address that never gives me the login page.  Has anyone had the same experience? I'm trying to figure out what's going on here.  Other people have used GPUs with nvidia docker #1120 and https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/795 has yet to be documented, so I don't know if this has something to do with how we're pre-configuring everything?

**Comment by minrk** [comment]
Anything related to ips is going to be purely kubernetes-related, and not anything in jupyterhub itself.

My guess is that it's something to do with not exposing http ports on the cluster, perhaps. Maybe check the firewall in the GKE cluster.
