### ISSUE TITLE
Upgrade to notebook 5.7.0 from 5.6.0 leads to HTTP 403: Forbidden error

### ISSUE THREAD

**Issue by denshe** [jupyterhub/jupyterhub#2265]
Hi,

After upgrading notebook package from 5.6.0 to 5.7.0 a jupyterhub user authenticates successfully but get error 'HTTP 403: Forbidden' when starting 'My server'. The other elements on the page are Jupyter logo and Control Panel button (that normally opens Control Panel).

Downgrading to notebook 5.6.0 executed via (note reported mismatch in lib/python3.6/site-packages/notebook/static/custom/custom.css) return to the expected behaviour. 
conda install --revision 50
Package Plan
  environment location: /opt/anaconda3
  added / updated specs: 
    - anaconda
    - bleach
    - bokeh
    - conda
    - conda-build
    - cx_oracle
    - cython
    - dask
    - dask-core
    - distributed
    - fastavro
    - imagesize
    - ipykernel
    - ipython
    - ipywidgets
    - jupyter_client
    - jupyter_console
    - jupyter_contrib_nbextensions
    - jupyter_dashboards
    - jupyterhub
    - jupyterlab
    - jupyterlab_launcher
    - kafka-python
    - libtiff
    - lxml
    - markupsafe
    - matplotlib
    - nbconvert
    - nbformat
    - notebook
    - numpy
    - pandas
    - pandoc
    - plotly
    - py
    - python-avro
    - python-confluent-kafka
    - python-dateutil
    - pyzmq
    - r-irkernel
    - scikit-learn
    - scipy
    - setuptools
    - sphinx
    - sqlalchemy
    - sqlite
    - sympy
    - tornado
    - widgetsnbextension
    - xlsxwriter
    - yapf
The following packages will be DOWNGRADED:
    notebook:               5.7.0-py36_0                      --> 5.6.0-py36_0
Proceed ([y]/n)? y
Preparing transaction: done
Verifying transaction: / 
SafetyError: The package for notebook located at /opt/anaconda3/pkgs/notebook-5.6.0-py36_0
appears to be corrupted. The path 'lib/python3.6/site-packages/notebook/static/custom/custom.css'
has a sha256 mismatch.
  reported sha256: 6660facf89a8af14b075a5d104569bcc03dfae968603f6b3b1ccd01007fd9d53
  actual sha256: 46af1b6552a8942bd58b02b2990894d3ea544d3f5b306d7a1dc19d411bfa260e
done
Executing transaction: done

### Additional details about the environment that works
_Server Information:
You are using Jupyter notebook.
The version of the notebook server is: 5.6.0
The server is running on this version of Python:
Python 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0]
Current Kernel Information:
Python 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 17:14:51) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.0.1 -- An enhanced Interactive Python. Type '?' for help._

What would be the best way to fix this and upgrade to notebook 5.7.0?

Thanks.

**Comment by denshe** [comment]
> Can you share the logs from the notebook server and jupyterhub when you see the error?
When notebook is set to 5.7.0, jupyterhub logs are as follows:
......
--successful authentication, then press on 'My Server'
....
Nov  9 16:48:05 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:05.546 JupyterHub log:122] 302 GET / → /hub (@::ffff:82.199.163.62) 0.55ms
Nov  9 16:48:05 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:05.638 JupyterHub log:122] 302 GET /hub/ → /hub/home (denshe@::ffff:82.199.163.60) 2.16ms
Nov  9 16:48:05 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:05.753 JupyterHub log:122] 200 GET /hub/home (denshe@::ffff:82.199.163.60) 5.14ms
Nov  9 16:48:07 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:07.926 JupyterHub log:122] 302 GET / → /hub (@::ffff:82.199.163.61) 0.63ms
Nov  9 16:48:10 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:10.551 JupyterHub log:122] 302 GET / → /hub (@::ffff:82.199.163.62) 0.76ms
Nov  9 16:48:12 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:12.085 JupyterHub log:122] 302 GET /hub/spawn → /user/denshe/ (denshe@::ffff:82.199.163.60) 2.79ms
Nov  9 16:48:12 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:12.198 JupyterHub log:122] 302 GET /user/denshe/ → /hub/user/denshe/ (@::ffff:82.199.163.60) 0.84ms
Nov  9 16:48:12 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:12.348 JupyterHub spawner:978] Spawning jupyterhub-singleuser --port=57619
Nov  9 16:48:12 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:12.942 JupyterHub log:122] 302 GET / → /hub (@::ffff:82.199.163.61) 0.74ms
Nov  9 16:48:13 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:13.683 SingleUserNotebookApp handlers:179] [beakerx] enabled
Nov  9 16:48:13 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:13.705 SingleUserNotebookApp __init__:259] [jupyter_nbextensions_configurator] enabled 0.4.0
Nov  9 16:48:13 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:13.740 SingleUserNotebookApp extension:161] JupyterLab extension loaded from /opt/anaconda3/lib/python3.6/site-packages/jupyterlab
Nov  9 16:48:13 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:13.740 SingleUserNotebookApp extension:162] JupyterLab application directory is /opt/anaconda3/share/jupyter/lab
Nov  9 16:48:13 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:13.742 SingleUserNotebookApp singleuser:365] Starting jupyterhub-singleuser server version 0.8.1
Nov  9 16:48:13 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:13.747 JupyterHub log:122] 200 GET /hub/api (@127.0.0.1) 0.70ms
Nov  9 16:48:13 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:13.749 SingleUserNotebookApp notebookapp:1712] Serving notebooks from local directory: /export/home/staff/denshe
Nov  9 16:48:13 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:13.749 SingleUserNotebookApp notebookapp:1712] The Jupyter Notebook is running at:
Nov  9 16:48:13 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:13.749 SingleUserNotebookApp notebookapp:1712] http://127.0.0.1:57619/user/denshe/
Nov  9 16:48:13 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:13.749 SingleUserNotebookApp notebookapp:1713] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Nov  9 16:48:14 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:14.459 JupyterHub base:447] User denshe took 2.139 seconds to start
Nov  9 16:48:14 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:14.461 JupyterHub proxy:231] Adding user denshe to proxy /user/denshe/ => http://127.0.0.1:57619
Nov  9 16:48:14 jupyterhub01 jupyterhub: 16:48:14.463 - info: [ConfigProxy] Adding route /user/denshe -> http://127.0.0.1:57619
Nov  9 16:48:14 jupyterhub01 jupyterhub: 16:48:14.463 - info: [ConfigProxy] 201 POST /api/routes/user/denshe
Nov  9 16:48:14 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:14.467 JupyterHub log:122] 302 GET /hub/user/denshe/ → /user/denshe/?redirects=1 (denshe@::ffff:82.199.163.60) 2148.36ms
Nov  9 16:48:14 jupyterhub01 jupyterhub: [W 2018-11-09 16:48:14.705 SingleUserNotebookApp handlers:447] Blocking request with non-local 'Host' jupyter.eget.fi (jupyter.eget.fi). If the notebook should be accessible at that name, set NotebookApp.allow_remote_access to disable the check.
Nov  9 16:48:14 jupyterhub01 jupyterhub: [W 2018-11-09 16:48:14.897 SingleUserNotebookApp handlers:447] Blocking request with non-local 'Host' jupyter.eget.fi (jupyter.eget.fi). If the notebook should be accessible at that name, set NotebookApp.allow_remote_access to disable the check.
Nov  9 16:48:14 jupyterhub01 jupyterhub: [W 2018-11-09 16:48:14.911 SingleUserNotebookApp handlers:447] Blocking request with non-local 'Host' jupyter.eget.fi (jupyter.eget.fi). If the notebook should be accessible at that name, set NotebookApp.allow_remote_access to disable the check.
Nov  9 16:48:14 jupyterhub01 jupyterhub: [W 2018-11-09 16:48:14.914 SingleUserNotebookApp handlers:447] Blocking request with non-local 'Host' jupyter.eget.fi (jupyter.eget.fi). If the notebook should be accessible at that name, set NotebookApp.allow_remote_access to disable the check.
Nov  9 16:48:14 jupyterhub01 jupyterhub: [W 2018-11-09 16:48:14.916 SingleUserNotebookApp handlers:447] Blocking request with non-local 'Host' jupyter.eget.fi (jupyter.eget.fi). If the notebook should be accessible at that name, set NotebookApp.allow_remote_access to disable the check.
Nov  9 16:48:14 jupyterhub01 jupyterhub: [W 2018-11-09 16:48:14.923 SingleUserNotebookApp handlers:447] Blocking request with non-local 'Host' jupyter.eget.fi (jupyter.eget.fi). If the notebook should be accessible at that name, set NotebookApp.allow_remote_access to disable the check.
Nov  9 16:48:15 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:15.554 JupyterHub log:122] 302 GET / → /hub (@::ffff:82.199.163.62) 0.92ms
Nov  9 16:48:17 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:17.890 JupyterHub log:122] 302 GET / → /hub (@::ffff:82.199.163.61) 0.59ms
Nov  9 16:48:20 jupyterhub01 jupyterhub: [I 2018-11-09 16:48:20.556 JupyterHub log:122] 302 GET / → /hub (@::ffff:82.199.163.62) 0.57ms
......

Logs suggest NotebookApp.allow_remote_access to be set to True. Currently, there is no config for jupyter-notebook defined. Am I correct that to generate such config and to make it applicable to all users I should:
```
# under my user
jupyter notebook --generate-config
mv .jupyter/jupyter_notebook_config.py /etc/jupyter/jupyter_notebook_config.py
```

**Comment by minrk** [comment]
> Am I correct that to generate such config and to make it applicable to all users I should:

yes, that's certainly one way to do it. Maybe double-check that the config is loaded. Can you share `jupyter_notebook_config.py`?
