### ISSUE TITLE
jupyterhub and source control for notebooks

### ISSUE THREAD

**Issue by karpikpl** [jupyterhub/jupyterhub#2269]
Hi,
I've been looking around for more than a week to find a source control solution for notebooks.

The scenario that I'm thinking about doesn't seem to be too far from how other people are using jupyter (I assume).

So let's say I have a team of people working on a shared collection of notebooks.
As far as I can tell, the way to go here is deploying a jupyterhub to kubernetes and configuring the spawner to use a shared persistent volume.
Using authentication options available I could set who has access to what.

The part that I'm confused about is the source control.
It feels that it would be common sense to keep notebooks in git, maybe even add some custom check in/out capabilities to avoid conflicts.

Are there any best practices on how this can be done?
Is creating custom jupyter lab widgets for managing source control the only way to go?

Or maybe most (99%) of jupyter users are technical people that manage source control completely outside of jupyter and that's the reason it's not a concern?

**Comment by jingsong-liu** [comment]
interested questions... wait for good practice

**Comment by minrk** [comment]
There is a git plugin for jupyterlab that's being worked on. There's also nbdime, which adds some nice diff/merge tools for notebooks.

But for sharing/collaboration, usually I would say that's outside the scope of Jupyter (realtime notwitstanding), and any mechanism for collaborating on files should work for notebooks (git, dropbox, shared filesystem, etc.).
