### ISSUE TITLE
How to match PID on notebook in JupyterHub (how admin)

### ISSUE THREAD

**Issue by ermakovpetr** [jupyterhub/jupyterhub#2271]
In **Jupyter** I find API for mapping PID on notebook https://github.com/jupyter/jupyter/wiki/Jupyter-Notebook-Server-API

But how mapping PID on notebook in **JupyterHub**?
For me (from the user) I can send a request to `<jupyterhub_url>/user/petr.ermakov/api/sessions`
But how to get list session for all users (but without login from each users), how admin maybe

**Comment by BertR** [comment]
Hi @ermakovpetr , admin users can use the `GET /api/users/` endpoint to get information
about all the running notebooks that Jupyterhub knowns of. 

http://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyterhub/jupyterhub/master/docs/rest-api.yml#/default/get_users

**Comment by minrk** [comment]
PIDs aren't generally known by JupyterHub, since user servers are often not on the same machine as the Hub. PIDs are considered a private implementation detail of the Spawner.

What would you be using the PID for?

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
