### ISSUE TITLE
Notebook server spawning failure

### ISSUE THREAD

**Issue by amangarg96** [jupyterhub/jupyterhub#2273]
Hey, I have an issue in using JupyterHub with using NB2KG server extension (which is used to launch jupyter kernels remotely via Jupyter Enterprise Gateway).
So I'm trying to use nb2kg with JupyterHub to launch kernels on Spark using Jupyter Enterprise Gateway.

JupyterHub spawns Notebook Servers locally using the LocalSpawner class, while Jupyter Enterprise Gateway runs on a different server.

KG_URL was set as:
export KG_URL=http://${JKG_HOST}:8888

nb2kg serverextension was activated by:
jupyter serverextension enable --py nb2kg --sys-prefix

Everything is working fine when I am launching the Jupyter Notebook servers (without using JupyterHub) - Notebook server is able to interact with the Enterprise Gateway, kernels are being launched on Spark with no known issues.
But when I try to launch the Notebook servers via JupyterHub, I get the following error log
```
[C 2018-10-26 12:13:53.576 JupyterHub app:1861] Failed to start proxy
Traceback (most recent call last):
File "/Users/aman.garg/anaconda2/envs/jupyterhub-nb/lib/python3.6/site-packages/jupyterhub/app.py", line 1859, in start
await self.proxy.start()
File "/Users/aman.garg/anaconda2/envs/jupyterhub-nb/lib/python3.6/site-packages/jupyterhub/proxy.py", line 596, in start
await server.wait_up(1)
File "/Users/aman.garg/anaconda2/envs/jupyterhub-nb/lib/python3.6/site-packages/jupyterhub/utils.py", line 165, in wait_for_server
timeout=timeout
File "/Users/aman.garg/anaconda2/envs/jupyterhub-nb/lib/python3.6/site-packages/jupyterhub/utils.py", line 155, in exponential_backoff
raise TimeoutError(fail_message)
TimeoutError: Server at <hostname>:8000 didn't respond in 1 seconds
```

**Comment by minrk** [comment]
Can you include jupyterhub_config.py? This suggests that the notebook server is expected on a public ip, but I'm guessing they should only be listening on localhost (this is ~always the case with LocalProcessSpawner).

**Comment by amangarg96** [comment]
These are the only uncommented lines of the jupyterhub_config.py file

```
c = get_config()
c.Spawner.default_url = '/lab'
c.LocalAuthenticator.create_system_users = True
c.JupyterHub.authenticator_class = 'jupyterhub.auth.PAMAuthenticator'
c.Spawner.debug = True
```

Can you elaborate on your previous comment?

**Comment by yashag66** [comment]
@amangarg96 @minrk How did you resolve this issue?

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
