### ISSUE TITLE
Using hashes as a docker image label - can we prefer version labels?

### ISSUE THREAD

**Issue by rothwewi** [jupyterhub/jupyterhub#2275]
As a consumer of JupyterHub I want to be able to download the latest image against a specific version number so that I can know what features are in it and know that it has the latest OS / Middleware versions on it. 

With a githash (as many are currently solely labelled with), it may tie neatly to source control, but it communicates little to the consumer directly. 

I want to be able to tell at a glance which version an image is, and the most recent version of a particular version.

**Comment by minrk** [comment]
The jupyterhub images are indeed tagged with the versions of jupyterhub they contain, and do not use hashes in the tags. https://hub.docker.com/r/jupyterhub/jupyterhub/tags/

**Comment by rothwewi** [comment]
Apologised mis-attributed the k8s-* images to this repo.
