### ISSUE TITLE
ImportError: No module named 'jupyterhub'

### ISSUE THREAD

**Issue by j08rebelo** [jupyterhub/jupyterhub#2276]
Hi,

I've installed jupyterhub on a server (running RHEL) following the steps provided on the installation guide:
python3 -m pip install jupyterhub
npm install -g configurable-http-proxy
python3 -m pip install notebook 

when i run jupyterhub -h i get the following error:

jupyterhub -h
Traceback (most recent call last):
  File "/usr/bin/jupyterhub", line 3, in <module>
    from jupyterhub.app import main
ImportError: No module named 'jupyterhub'

Can anyone help me with this issue?

**Comment by joergklein** [comment]
If you are using conda, the nodejs and npm dependencies will be installed for you by conda.

`conda install -c conda-forge jupyterhub`
If you plan to run notebook servers locally, install the Jupyter notebook
or JupyterLab:

```
conda install notebook
conda install jupyterlab
```

https://hub.docker.com/r/jupyterhub/jupyterhub/#installation

**Comment by minrk** [comment]
There may be some confusion about pythons and what packages are installed. You can try `python3 -m pip list` and `head -n 1 $(which jupyterhub)` and `which -a jupyterhub` and `which -a python3` to see if there could be any conflicts.

It's also a good idea to make sure that you don't have any environment variables like $PYTHONPATH defined.

**Comment by ghettosamson** [comment]
How does one go about fixing this issue. 
`[meuser@mehostname Python-3.7.4]$ head -n 1 $(which jupyterhub)
#!/bin/python3
[meuser@mehostname Python-3.7.4]$ which -a python3
/usr/bin/python3`
I installed all the site-packages in a virtual environment. How do I tell jupyterhub to use that python?

**Comment by minrk** [comment]
@ghettosamson jupyterhub doesn't create the scripts, pip does. If you've created a virtualenv, activated it, and done `python3 -mpip install jupyterhub`, the scripts should be correct. Be careful if you've done the installation several times, as there may be several pythons and/or jupyterhubs on your PATH.
