### ISSUE TITLE
Not all kernels show up in the notebook

### ISSUE THREAD

**Issue by mdivk** [jupyterhub/jupyterhub#2278]
Below is the kernels I have:

> [root@cedgedev03 jupyterhub]# jupyter kernelspec list
> Available kernels:
>   python2                   /opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/ipykernel/resources
>   ir                        /opt/cloudera/parcels/Anaconda/share/jupyter/kernels/ir
>   apache_toree_pyspark      /usr/local/share/jupyter/kernels/apache_toree_pyspark
>   apache_toree_scala        /usr/local/share/jupyter/kernels/apache_toree_scala
>   apache_toree_sparkr       /usr/local/share/jupyter/kernels/apache_toree_sparkr
>   apache_toree_sql          /usr/local/share/jupyter/kernels/apache_toree_sql
>   spark1.6_conda_python2    /usr/local/share/jupyter/kernels/spark1.6_conda_python2
>   spark16-conda             /usr/local/share/jupyter/kernels/spark16-conda
>   spark2.3_conda_python2    /usr/local/share/jupyter/kernels/spark2.3_conda_python2
>   spark23-conda             /usr/local/share/jupyter/kernels/spark23-conda
>   python3                   /usr/share/jupyter/kernels/python3

In Jupyter Notebook, the following are NOT available:
>   python2                   /opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/ipykernel/resources
>   ir                        /opt/cloudera/parcels/Anaconda/share/jupyter/kernels/ir

It is noticed both are from Conda, do I need to somehow activate the kernels like activating environment?

Thank you.

**Comment by Zsailer** [comment]
I think the `/opt/cloudera/parcels/Anaconda/...` locations are not visible to your jupyter setup. 

You can check this with by calling `jupyter --paths`  in your terminal.

To make Jupyter aware of these paths, I think you just need to add them to your `JUPYTER_PATH` environment variable (see more [here](https://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html)).
