### ISSUE TITLE
Authenticate users via email-id and automate unix user creation using unique user-name

### ISSUE THREAD

**Issue by sdandey** [jupyterhub/jupyterhub#2279]
I was able to get JupyterHub up and running by configuring LDAP using a user-name.  

Instead of username, we need them to login via there email-account i.e. firstname.lastname@mycompany.com, validate using LDAP.  Once authenticated, Jupyter-hub has to login them using a different local user-name with a common-prefix i.e. say for e.g. the technical user name should be created with format juphub_<firstname from email><First letter of last name from email>

if user john doe login via LDAP with email john.doe@mycompany.com.  Jupyter Hub has to login this user as juphub_johnd and create local-directories with name /home/juphub_johnd.

Is there a way we can automate jupyterhub to use custom unix login name using a custom-script?

**Comment by sdandey** [comment]
Figured out the setting c.Authenticator.username_map would allow username to map to different local unix user name.

**Comment by aurashn** [comment]
Does this automate anything or did you still need to aggregate all the potential users logins, apply the transformation, and set the map?
