### ISSUE TITLE
Hard to deploy jupyterhub server on LAN

### ISSUE THREAD

**Issue by tony-tian** [jupyterhub/jupyterhub#2286]
Hi! I'm deploying jupyterhub server on LAN. It's normal to block external connections when using a server with fixed ip-address(actually it's a rule to obey for a server-applicant). Right now I'm using Ubuntu 18.0 and want to deploy the jupyterhub envs on a LAN server, which don't have any external connections. 
I find it really hard to build the env not because jupyterhub was hard to install but the authorizing process made things complicated.

Above all, I once thought that what I need to config was that set up user_list and passwords, and users log in with username and password on browser. But then I found it hard to set up authorizing process because I could not use Gitlab or Github, and the users' ip address was not the same as the server but they're still belonging to a LAN.

SO WHEN a USER try to log in with unix settings, the log prints that 
> PAM Authentication failed (username@userIP): [PAM Error 7] Authentication failure
while server's ip is serverIP(not equal userIP)

Hope someone could help, and I will much appreciate all of that!

**Comment by minrk** [comment]
I'm not quite sure I understand the details of your PAM configuration. Do the users have accounts on the machine that they can login with? How do the ip restrictions work and how are they implemented?

Can you try logging in with a username+password with a few things:

1. ssh to the server
2. try `su` to another user once already logged in, and
3. try `python -m pamela -a <username>`

I'm not sure how the ip checking is implemented, but the PAM call that JupyterHub makes doesn't relay the originating IP at all. What are the use

**Comment by tony-tian** [comment]
Hi! I've tried in such way:
1. ssh to the server with root
2. su another normal user
3. try python -m pamela -a <username>
and terminal prints `/usr/bin/python: No module named pamela`

To provide more details,
what I say about users was based on Linux system users that could ssh to server.
The hub config also provided:
```python
c.JupyterHub.ip = 'serverIP'
c.JupyterHub.port = 7777
c.PAMAuthenticator.encoding = 'utf-8'
c.LocalAuthenticator.create_system_users = True
c.Authenticator.admin_users = {'me'}
c.Authenticator.admin_access = True
c.LocalAuthenticator.group_whitelist = {'stu'}
c.JupyterHub.statsd_prefix = 'jupyterhub'
c.Spawner.notebook_dir = '~/python'
```
What I need was to build a hub that any other student user permitted could log in on browser in the Campus Network. As I know, all ip was arranged to affiliate  a root ip.

**Comment by minrk** [comment]
Try `python3 -m pamela -a username` to login with usernames and passwords. This is what needs to work for PAMAuth to succeed.

**Comment by engyasin** [comment]
Hey @tony-tian 

if it works with you, can you share the steps to do this kind of deployment please.
