### ISSUE TITLE
The ports of the notebook servers are only needed to be accessible to the Hub itself, they do not need to be accessible to the outside world. In the case of a single server, these only need to be accessible on localhost / the docker virtual network. There is only one external port needed for all of JupyterHub.

### ISSUE THREAD

**Issue by IamViditAgarwal** [jupyterhub/jupyterhub#2292]
The message you describe indicates a failure to establish a websocket connection, not a connection to the notebook server as a whole (which is required to display that message). That may be due to a proxy running on your AWS instance that's preventing websocket connections.

_Originally posted by @minrk in https://github.com/jupyterhub/jupyterhub/issues/692#issuecomment-242690881_

I am running a extra service inside docker at port 8866 and want to access that service on Jupyter notebook (which is running in same docker at port 8888.) Can u suggest some ways and where I need to open port and do port config/mapping

**Comment by minrk** [comment]
From gitter: running additional processes in the notebook container can be done with https://github.com/jupyterhub/nbserverproxy.

**Comment by IamViditAgarwal** [comment]
> From gitter: running additional processes in the notebook container can be done with https://github.com/jupyterhub/nbserverproxy.
It is giving me error 404 : Page not Found even though the process is running .

**Comment by IamViditAgarwal** [comment]
I have figured out this error. Actually what I was doing is installing the extension after the docker container has started but this will not work. It has to be installed using instructions in Dockerfile and will be installed while creating the container using that Dockerfile. Else it will not work.. Thanks.. 
Closing this issue.
