### ISSUE TITLE
Exception raised during api check

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/jupyterhub#2295]
We're seeing exceptions of the form:
```
JupyterHub web:1670] Uncaught exception GET /hub/user/{username}/api/contents/foo.ipynb?content=0&_=1541561546585 (10.240.1.119)
    HTTPServerRequest(protocol='https', host='{hostname}', method='GET', uri='/hub/user/{username}/api/contents/foo.ipynb?content=0&_=1541561546585', version='HTTP/1.1', remote_ip='10.240.1.119')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 961, in get
        if "api" in user_path.split("/") and not user.active:
    AttributeError: 'NoneType' object has no attribute 'active'
```

This also occurs for users we delete via /hub/admin. Seems related to #2294.

**Additional context**
z2jh master

**Comment by katsar0v** [comment]
I think correct line would be `if "api" in user_path.split("/") and user and not user.active:`
Can you reproduce this issue if you replace "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 961 ?

**Comment by minrk** [comment]
I think that's exactly right. Would you like to make a PR?

**Comment by ryanlovett** [comment]
> Can you reproduce this issue if you replace "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 961 ?

Not easily on the hub we're running. However we're on master z2jh so once it is upstream we can bump the chart version.

**Comment by katsar0v** [comment]
Okay, made a pull request which also passes the builds, but still think that we have to make sure this fixes the issue

**Comment by ryanlovett** [comment]
Thanks! I'll let you know once I can test.

**Comment by minrk** [comment]
Merged the patch. @ryanlovett feel free to close when you confirm the fix.
