### ISSUE TITLE
BOUNTY: Help me get JupyterHub configured

### ISSUE THREAD

**Issue by SeaDude** [jupyterhub/jupyterhub#2302]
Hello,
I've hit a wall here, for a 2nd time, and cannot get JupyterHub setup in my environment. I'd like to offer a $50 bounty for someone to help me. 

[Here is where I'm at.](https://github.com/SeaDude/Azure-JupyterHub/blob/master/jupyterHubInstall.md#now-what).

Here is where I want to go:
- Correctly installed JupyterHub instance
    - I'm using Anaconda. Need to ensure JupyterHub AND ALL ITS CONFIG FILES/COOKIES/SECRETS/ETC. are installed in the correct directories
- Secure, multi-user environment
    - This instance is internet-facing. Must be secure against unauthorized access.
    - I already have an SSL cert, but can't quite get it working with JupyterHub and nginx
- Authentication
    - Basic authentication is fine for now

1. Is this ok to post in your Github Issues?
    a. If so, who can help?
    b. If not, where can I go?

Thank you

**Comment by minrk** [comment]
From your configuration, it looks like nginx isn't picking up your site configuration.

Typically, this is done by installing the configuration in `/etc/nginx/sites-enabled/jupyterhub.conf` (or sites-available/jupyterhub.config with a symlink from sites-enabled if you're fancy). And make sure to run `service nginx restart` anytime you change the nginx configuration.
