### ISSUE TITLE
How we can check how long users are working on jupyterhub. 

### ISSUE THREAD

**Issue by narala558** [jupyterhub/jupyterhub#2305]
Hi! Thanks for using JupyterHub.

If you are reporting an issue with JupyterHub, please use the [GitHub issue](https://github.com/jupyterhub/jupyterhub/issues) search feature to check if your issue has been asked already. If it has, please add your comments to the existing issue.

**Describe the bug**
We have a shared jupyter server so many people working on the server. But i want to know from how long the user is working on the server. 

Is their any process to find out on the server level

**Comment by minrk** [comment]
We don't currently measure session durations, but we do have instantaneous reports of recent activity, as well as info about when servers start and stop. You could poll this info to create a summary over time.
