### ISSUE TITLE
env: ‘/usr/local/bin/start-singleuser.sh’: No such file or directory

### ISSUE THREAD

**Issue by zmkhazi** [jupyterhub/jupyterhub#2310]
I  tried using the following in the jupyterhuv_config.py file.  Despite of this, I am still gettting the error
env: ‘/usr/local/bin/start-singleuser.sh’: No such file or directory

Setting in the connfig file below:

c.DockerSpawner.extra_create_kwargs = {"command": 'env PATH="/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" /usr/local/bin/start-singleuser.sh'}

**Comment by zmkhazi** [comment]
The following are the environment variables pulled from the container

root@37035df3d5d2:/home# whoami
root
root@37035df3d5d2:/home# env
HOSTNAME=37035df3d5d2
SHELL=/bin/bash
TERM=xterm
LC_ALL=C.UTF-8
PATH=/root/node-latest-install/node-v8.9.4-linux-x64/bin:/root/anaconda3:/usr/local/bin/jupyter:/usr/bin/python3:/usr/bin/pip3:/usr/lib/jvm/java-8-openjdk-amd64/bin:/usr/local/bin:/root/anaconda3/bin:/usr/local/bin/jupyter:/usr/bin/pip3:/usr/bin/python3:/usr/lib/jvm/java-8-openjdk-amd64/bin:/bin::::/bin:/root/node-latest-install/node-v8.9.4-linux-x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/home
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
LANG=C.UTF-8
NODE_PATH=/root/node-latest-install/node-v8.9.4-linux-x64/bin
NODE_ROOT=/root/node-latest-install/node-v8.9.4-linux-x64
INSTALL_ROOT=/root/node-latest-install
SHLVL=1
HOME=/root
JUPYTER_ROOT=/usr/local/bin/jupyter
DEBIAN_FRONTEND=noninteractive
PYTHON3_E=/usr/bin/python3
CONDA_DIR=/root/anaconda3
PIP3_E=/usr/bin/pip3
_=/usr/bin/env

**Comment by minrk** [comment]
What image are you using for usrs? Does `/usr/local/bin/start-singleuser.sh` exist in it?

I'd also recommend setting environment variables via `c.Spawner.environment` instead of in the command itself.

**Comment by zmkhazi** [comment]
Sir, I tried the following but getting this error below in my configuration for jupyterhub. I tried adding the spawner env. Not sure if I am doing it correctly. Appreciate your support. 

Snapshot of the configuration in jupyterhub_config.py
----------------------------------------------------------------
c.DockerSpawner.network_name = "jupyterhub-network"
c.Spawner.cmd = ['/usr/local/bin/start-singleuser.sh']
c.Spawner.debug=True

c.Spawner.env_keep = ['PATH']
#c.Spawner.environment = dict(PATH='/root/anaconda3/bin:$PATH')
c.Spawner.environment = { 'PATH':  os.environ.get('$PATH') }
c.DockerSpawner.extra_create_kwargs = {
    "command": 'env PATH="/root/anaconda3/bin:$PATH" /usr/local/bin/start-singleuser.sh',
}

ERROR upon running Jupyterhub
==================
     File "/opt/oss/Anaconda3-4.4.0/lib/python3.6/site-packages/docker/client.py", line 174, in _raise_for_status
        raise errors.APIError(e, response, explanation=explanation)
    docker.errors.APIError: 400 Client Error: Bad Request ("b'{"message":"OCI runtime create failed: container_linux.go:348: starting container process caused \\"exec: \\\\\\"env\\\\\\": executable file not found in $PATH\\": unknown"}'")

------------------------------------------------------------------------------------------------------
The following is from  the Container. Searched for the existence of the file and also obtaining the PATH / env vars.
----------------------------------------------------------------------------------------------------------

root@5d3410dca078:/# find . -name start-singleuser.sh 2>/dev/null
./usr/local/bin/start-singleuser.sh
root@5d3410dca078:/# env
HOSTNAME=5d3410dca078
NB_USER=maxis
SHELL=/bin/bash
TERM=xterm
LC_ALL=C.UTF-8
LD_LIBRARY_PATH=/root/anaconda3/lib
PATH=/root/anaconda3/bin::::/bin:/root/node-latest-install/node-v8.9.4-linux-x64/bin:/root/anaconda3/bin:/root/anaconda3/lib:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
LANG=C.UTF-8
NODE_PATH=/root/node-latest-install/node-v8.9.4-linux-x64/bin
NODE_ROOT=/root/node-latest-install/node-v8.9.4-linux-x64
INSTALL_ROOT=/root/node-latest-install
SHLVL=1
HOME=/home/
JUPYTER_ROOT=/usr/local/bin/jupyter
DEBIAN_FRONTEND=noninteractive
PYTHON3_E=/usr/bin/python3
NB_GID=100
CONDA_DIR=/root/anaconda3
PIP3_E=/usr/bin/pip
NB_UID=1000
OLDPWD=/home/maxis
_=/usr/bin/env
root@5d3410dca078:/#

**Comment by minrk** [comment]
That multi-statement command isn't likely to work. You cannot use a full script as the command, it must be a single system call. To set env, use `c.Spawner.environment`, not `env` in the command.
