### ISSUE TITLE
Public Key enabled login

### ISSUE THREAD

**Issue by abremirata28** [jupyterhub/jupyterhub#2311]
If you are having issues with installation or configuration, you may ask for help on the JupyterHub gitter channel or file an issue here.
I am installing jupyterhub on a server authenticated using ssh public key. However I have problems logging in to Jupyterhub. It says invalid user name and password. It gets a PAM Authentication failure in its logs.

**Comment by abremirata28** [comment]
I have this error with JupyterHub installed using sudospawner

python: pam_unix(sshd:auth): authentication failure; logname=alger.remirata uid=1007 euid=1007 tty= ruser= rhost=  user=alger.remiratapython: pam_sss(sshd:auth): authentication failure; logname=alger.remirata uid=1007 euid=1007 tty= ruser= rhost= user=alger.remiratapython: pam_sss(sshd:auth): received for user alger.remirata: 17 (Failure setting user credentials)

**Comment by minrk** [comment]
Can you run `python3 -m pamela -a <username>`? to make sure that the JupyterHub PAM library can authenticate? This should be run as the user that runs the `jupyterhub` process.

**Comment by abremirata28** [comment]
No, the PAM authentication fails. PublicKeyAuthentication is being used wherein a passphrase is asked instead of the linux passworf

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
