### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by marvin-solano** [jupyterhub/jupyterhub#2316]
**Bug description**
JupyterHub is currently suffering of xss injection attacks when opening a file that has a tag with an xss attribute as a filename.

**To Reproduce**
1. Create a file with the following name "<img src=xss onerror=alert('xss') />"
2. Open the newly created file

**Expected behavior**
The expected behavior would be that JupyterHub treats the name as a string.

**Screenshots**
![jupyterhub_xss_issue_1](https://user-images.githubusercontent.com/45104239/48640015-6cda7f80-e9a3-11e8-8a07-2e360dde3b11.png)
![jupyterhub_xss_issue_2](https://user-images.githubusercontent.com/45104239/48640021-706e0680-e9a3-11e8-9a30-609d40d50be9.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Chrome

**Comment by betatim** [comment]
Thanks for finding and reporting this! I think you should report it in https://github.com/jupyter/notebook/ which is where the UI that you see in JupyterHub lives.

You should also consider reporting via https://jupyter-notebook.readthedocs.io/en/stable/security.html#reporting-security-issues

**Comment by minrk** [comment]
This has been fixed in notebook 5.7.2.
