### ISSUE TITLE
Adding another icon in the tree in Jupyterhub

### ISSUE THREAD

**Issue by gaurcs** [jupyterhub/jupyterhub#2317]
Hello all,

So I have a very basic requirement:

1) A user logs in.
2) They have an icon and on the click of that icon, a python script is run in the server.

Now, upon reading the docs I am thinking I have to create a [service](https://github.com/jupyterhub/jupyterhub/tree/master/examples/) but I am not sure how to modify the templates. 

Let's say I create a service called /api/my_script . How do I add an icon on the top of current templates. The api needs to be called by each user and the script needs to be run on their account in the server. I am not sure I am heading in the right direction..

**Comment by minrk** [comment]
This doesn't need to be a service. To have a button do a thing on the server, you need two things:

- a notebook server extension that registers the Handler (`jupyter serverextension`), and
- a notebook frontend javascript extension to add the button (`jupyter nbextension`)

[nbrsessionproxy](https://github.com/jupyterhub/nbrsessionproxy) is one such extension that adds a Handler and an item to the `New` menu of the tree view.

**Comment by gaurcs** [comment]
Thanks thats what I figured. One more quick question. So lets say I make my own handler and button. Do I add that extension through jupyterhub_config.py or install it through notebook or package first and then install through pip?

**Comment by gaurcs** [comment]
I installed it through jupyter. Thanks for the help @minrk .
