### ISSUE TITLE
DockerSpawner.image_whitelist must be defined even if not used

### ISSUE THREAD

**Issue by robnagler** [jupyterhub/jupyterhub#2318]
**Describe the bug**
Must set `DockerSpawner.image_whitelist = []` if you set `image` (not container_image), because [line 241](https://github.com/jupyterhub/dockerspawner/blob/369d99c37ef9eea1890b9b8532f1b636158dd3de/dockerspawner/dockerspawner.py#L241) should check for truth not `len`.

https://github.com/radiasoft/rsconf/issues/54 
**To Reproduce**
1. Configure DockerSpawner.image = 'busybox'
2. Start juptyerhub
3. Login/Start server

**Expected behavior**
Shouldn't get an exception/500.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

- Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.
- Running in `--debug` mode can also be helpful for troubleshooting.

**Comment by minrk** [comment]
None shouldn't have been the default, it should have been empty. Fixed by https://github.com/jupyterhub/dockerspawner/pull/278
