### ISSUE TITLE
Issue with output returned by Jupyterhub 

### ISSUE THREAD

**Issue by hichemken** [jupyterhub/jupyterhub#2319]
Hi! Thanks for using JupyterHub.

If you are reporting an issue with JupyterHub, please use the [GitHub issue](https://github.com/jupyterhub/jupyterhub/issues) search feature to check if your issue has been asked already. If it has, please add your comments to the existing issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

- Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.
- Running in `--debug` mode can also be helpful for troubleshooting.

**Comment by betatim** [comment]
Closing as it is an empty issue. Please feel free to open a new issue if this wasn't a mistake.
