### ISSUE TITLE
Issue with output returned by Jupyterhub

### ISSUE THREAD

**Issue by hichemken** [jupyterhub/jupyterhub#2320]
Hi! Thanks for using JupyterHub.

If you are reporting an issue with JupyterHub, please use the [GitHub issue](https://github.com/jupyterhub/jupyterhub/issues) search feature to check if your issue has been asked already. If it has, please add your comments to the existing issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

- Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.
- Running in `--debug` mode can also be helpful for troubleshooting.

**Comment by hichemken** [comment]
We are using a jupyterhub server to connect to a remote EMR cluster to run spark and python. Recently we installed fbprophet, Facebook package for time series forecasting [](https://facebook.github.io/prophet/docs/quick_start.html)
While calling he fit method we have an issue with the output and it seems to break the rest of all outputs from other cells we run afterward. 
`import pandas as pd
from fbprophet import Prophet`

`#upload to s3 the csv file from the link in the page https://facebook.github.io/prophet/docs/quick_start.html
df = spark.read.option("header", "true").option("inferSchema", value=True).csv("example_wp_log_peyton_manning.csv")
`
`pdf = df.toPandas()`

`m = Prophet()`
![image](https://user-images.githubusercontent.com/17710696/48770788-791e4f80-ecb7-11e8-8404-8814ed187662.png)

![image](https://user-images.githubusercontent.com/17710696/48770822-8e937980-ecb7-11e8-8637-87b5223ab01f.png)

The same code runs perfectly when we ssh into the EMR directly   : 

![image](https://user-images.githubusercontent.com/17710696/48770863-a4a13a00-ecb7-11e8-8d5f-1694f8d0cf13.png)

Thanks for you help.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
