### ISSUE TITLE
JupyterHub Authentication with my own token system, second login fails

### ISSUE THREAD

**Issue by JPMoresmau** [jupyterhub/jupyterhub#2331]
Hello, not sure this is the best place to ask such a questions, but here goes:

- I have a web application that can authenticate users and provide JWT (tokens) that it can verify.
- I'd like to direct my users to a JupyterHub page that logs them in automatically. So I can craft a URL to the notebook I want to open, and have the token as a url parameter
- I implemented an Authenticator and a Handler on /login (I also overrode login_url() in my Authenticator but it seems to be ignored). The handler retrieves the "next" URL parameter and from this extracts the token. With the token I can verify it's valid using my app, and if it is I call user_from_username, set_login_cookie, and do the redirect.
- I've set auto_login to true, so once I've logged in, if I log out, I see a page telling me that I was logged out. So far so good.
- I then access the exact same URL as before, hoping to login again. This fails because the next parameter contains a totally different url than before, and doesn't have my token parameter. It contains a state opaque parameter, for example, and some oauth parameters. So I can't obtain my token and I fail with a 401.

So the behavior is not the same between the first and second login. If I restart the Hub the first login works again and the second fails. So what am I doing wrong? Should I do something special on logout? Should I use another method to get the extra URL info I pass? I have enable_auth_state set to False so I didn't expect anything to be kept between login and logouts.

I'm using 0.9.4 via Docker.

**Comment by JPMoresmau** [comment]
OK, so looking at the "state" parameter I get, it's a Base64 encoded JSON object that contains the next_url, so I can get my token from there.

**Comment by yugushihuang** [comment]
Hi,

I do not know if it is appropriate to ask. I want to realize the same functionality as yours. And I have no idea how to write the custom authenticator. If it is possible, can you share your authenticator? Sorry for ask that... Thank you!
