### ISSUE TITLE
quantity of data bytes conflict with kubernetes

### ISSUE THREAD

**Issue by Cas-pian** [jupyterhub/jupyterhub#2334]
**Describe the bug**
the quantity of data bytes are conflict with kubernetes.
As defined in ByteSpecification, `K, M` means `1024, 1024*1024`,  
but in kubernetes `K, M` means `1000, 1000*1000`, and `Ki, Mi` means `1024, 1024*1024`

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!
