### ISSUE TITLE
Contributing guide has gone missing

### ISSUE THREAD

**Issue by betatim** [jupyterhub/jupyterhub#2338]
The contributing guide seems to have vanished :-/

`CONTRIBUTING.md` sends you to a part of the documentation that doesn't exist and I couldn't find the text anywhere on the webpage either.

The contents of CONTRIBUTING got removed in b9331dbd57011710134302e7a4feca844492a6ce did we forget to add it to its new home?

**Comment by MubashirullahD** [comment]
Hi. Newcomer here. I checked the file CONTRIBUTING.md and it led me to a webpage that seems ok. Should I consider this issue resolved or is there something else that got removed and I am missing out? 
Thanks.
