### ISSUE TITLE
Managing user groups

### ISSUE THREAD

**Issue by DeepHorizons** [jupyterhub/jupyterhub#2339]
Is there any way to add / remove a user from a group via the UI? User groups were added back in 0.7 but I cannot find any documentation on it except that an endpoint exists on the hubs REST api. I have done some preliminarily work on a PR to add the ability to manage groups via the admin page but is it a wanted feature? Or another way to put it is are user groups going to be phased out for something more favorable? I see some discussion on User Roles in #2245 , would that supersede user groups?

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!
