### ISSUE TITLE
Insecure cookies

### ISSUE THREAD

**Issue by marvin-solano** [jupyterhub/jupyterhub#2348]
Hi guys, currently our cookies (jupyterhub-hub-login, jupyterhub-session-id, jupyterhub-user-USERNAME) are all missing the secure flag, where can we enable this?

**Comment by Shiva1789** [comment]
Hi, I am new to jupyterhub environment, I am running jupyterhub behind zuul proxy.
Jupyter running as http service. I am not able to set the secure flag for the cookies set by jupyterhub and notebook like jupyterhub-hub-login, jupyterhub-session-id, jupyterhub-user-USERNAME and _xsrf. Please need some help on this.

**Comment by bitnik** [comment]
@minrk shouldn't we set `cookie_options` in `c.JupyterHub.tornado_settings`? 
```python
c.JupyterHub.tornado_settings["cookie_options"] = dict(secure=True)
```
and same for here: https://github.com/jupyterhub/jupyterhub/issues/2277 (because maybe `cookie_options` key doesn't exist in tornado settings)
