### ISSUE TITLE
User cookie persisting after single sign off

### ISSUE THREAD

**Issue by marvin-solano** [jupyterhub/jupyterhub#2349]
**Description**
When using a single sign off method the cookie with the user info remains. This leads to mixed sessions and potential vulnerabilities, e.g.:
Admin user access JH and then single sign off, user B (with a regular account) logs from the same browser, if we do an inspect, the jupyterhub-user-USERNAME token still contains the information from the previous user (admin).

**Expected behavior**
When using sso as auth, single sign offs should delete the user cookies.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 70

**Comment by minrk** [comment]
The refresh-auth functionality in master should allow authenticators to fix this if they want. It's related to #2342

**Comment by manics** [comment]
See the above comment
