### ISSUE TITLE
HTTP 403: Forbidden error when starting jupyterhub

### ISSUE THREAD

**Issue by wangsookim** [jupyterhub/jupyterhub#2352]
Hi, 
I have updated anaconda and jupyterhub to the latest version, and the following message occurs.
Hoping you might throw some light on this issue with this.

[I 2018-12-07 02:59:42.238 JupyterHub app:1673] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.4
[I 2018-12-07 02:59:42.238 JupyterHub app:1673] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.4
[I 2018-12-07 02:59:42.240 JupyterHub app:1016] Loading cookie_secret from /root/jupyterhub_cookie_secret
[I 2018-12-07 02:59:42.254 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[W 2018-12-07 02:59:42.255 JupyterHub app:1173] No admin users, admin interface will be unavailable.
[W 2018-12-07 02:59:42.255 JupyterHub app:1174] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-12-07 02:59:42.255 JupyterHub app:1201] Not using whitelist. Any authenticated user will be allowed.
[I 2018-12-07 02:59:42.284 JupyterHub app:1855] Hub API listening on http://127.0.0.1:8081/hub/
[W 2018-12-07 02:59:42.284 JupyterHub proxy:472] Found proxy pid file: /root/jupyterhub-proxy.pid
[W 2018-12-07 02:59:42.284 JupyterHub proxy:484] Proxy no longer running at pid=51462
[I 2018-12-07 02:59:42.285 JupyterHub proxy:567] Starting proxy @ http://220.67.124.40:443/
02:59:42.294 - warn: [ConfigProxy] 403 GET /api/routes 
[E 2018-12-07 02:59:42.295 JupyterHub app:1958]
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/app.py", line 1956, in launch_instance_async
        await self.start()
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/app.py", line 1901, in start
        await self.proxy.check_routes(self.users, self._service_map)
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/proxy.py", line 57, in locked_method
        return await method(*args, **kwargs)
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/proxy.py", line 297, in check_routes
        routes = await self.get_all_routes()
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/proxy.py", line 733, in get_all_routes
        resp = await self.api_request('', client=client)
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/proxy.py", line 694, in api_request
        result = await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
    
[root@Programming:~]# 02:59:42.489 [ConfigProxy] info: Proxying https://220.67.124.40:443 to (no default)
02:59:42.492 [ConfigProxy] info: Proxy API at http://127.0.0.1:8001/api/routes
02:59:42.497 [ConfigProxy] error: Uncaught Exception
02:59:42.497 [ConfigProxy] error: Uncaught Exception

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
