### ISSUE TITLE
jupyter notebook control panel button does not redirect to default_url

### ISSUE THREAD

**Issue by danielpcs** [jupyterhub/jupyterhub#2356]
I am not sure if this is intended or not, but my team and I have found that the Control Panel button inside Jupyter Notebook does not redirect to the page set with c.JupyterHub.default_url.

It also does not seem to have an option to change that behavior, after checking the singleuser.py file we found it is hardcoded to always redirect to the home page.

Due to our client requirements, we cannot modify JupyterHub's codebase directly (they want to keep a clean clone in their git repo, updating it whenever there's a stable release so they can use it for other projects if needed).

We have tried to overwrite the HomeHandler class for our project and also set a different handler class for the home page so we could add the features from the page we currently want as default, but we could not get it to work.

Shorter version:
Are there any plans on making the Control Panel button inside the jupyter notebooks redirect to a different page?

**Comment by minrk** [comment]
I would interpret control panel to mean the specific page it currently refers to. Adding a custom default page doesn't mean that the control panel / home page is gone. But it does make sense to possibly *add* a link when default_url and control panel differ. Would that work for you?

**Comment by danielpcs** [comment]
If I understood correctly, it would be an extra option in jupyterhub_config.py for the control panel to use the same link as default_url. That would be a perfect solution for our case!

Thank you so much for the quick reply!

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!
