### ISSUE TITLE
Error  500 : Internal Server Error  Failed to start your server on the last attempt. Please contact admin if the issue persists.  

### ISSUE THREAD

**Issue by studyquant** [jupyterhub/jupyterhub#2357]
If you are having issues with installation or configuration, you may ask for help on the JupyterHub gitter channel or file an issue here.

I have setup and install jupyterhub by instuctions. 

```
root@VM-0-16-ubuntu:~# /home/admin/anaconda3/bin/jupyterhub
[I 2018-12-12 11:45:08.449 JupyterHub app:1673] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.4
[I 2018-12-12 11:45:08.450 JupyterHub app:1673] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.4
[I 2018-12-12 11:45:08.453 JupyterHub app:1016] Loading cookie_secret from /root/jupyterhub_cookie_secret
[I 2018-12-12 11:45:08.477 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[W 2018-12-12 11:45:08.479 JupyterHub app:1173] No admin users, admin interface will be unavailable.
[W 2018-12-12 11:45:08.479 JupyterHub app:1174] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-12-12 11:45:08.479 JupyterHub app:1201] Not using whitelist. Any authenticated user will be allowed.
[I 2018-12-12 11:45:08.527 JupyterHub app:1855] Hub API listening on http://127.0.0.1:8081/hub/
[W 2018-12-12 11:45:08.529 JupyterHub proxy:565] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2018-12-12 11:45:08.529 JupyterHub proxy:567] Starting proxy @ http://:8000
11:45:09.048 [ConfigProxy] info: Proxying http://*:8000 to (no default)
11:45:09.052 [ConfigProxy] info: Proxy API at http://127.0.0.1:8001/api/routes
11:45:09.260 [ConfigProxy] info: 200 GET /api/routes 
[I 2018-12-12 11:45:09.261 JupyterHub proxy:301] Checking routes
[I 2018-12-12 11:45:09.261 JupyterHub proxy:370] Adding default route for Hub: / => http://127.0.0.1:8081
11:45:09.263 [ConfigProxy] info: Adding route / -> http://127.0.0.1:8081
11:45:09.264 [ConfigProxy] info: 201 POST /api/routes/ 
[I 2018-12-12 11:45:09.265 JupyterHub app:1912] JupyterHub is now running at http://:8000
[I 2018-12-12 11:45:16.798 JupyterHub log:158] 302 GET / -> /hub (@127.0.0.1) 1.00ms
[I 2018-12-12 11:45:16.851 JupyterHub log:158] 302 GET /hub -> /hub/ (admin@127.0.0.1) 0.69ms
[I 2018-12-12 11:45:16.977 JupyterHub log:158] 302 GET /hub/ -> /user/admin/ (admin@127.0.0.1) 90.62ms
[I 2018-12-12 11:45:16.985 JupyterHub log:158] 302 GET /user/admin/ -> /hub/user/admin/ (@127.0.0.1) 0.74ms
```

After I login by a  non-root user with password,  the error shows 500: Internal Server Error  Failed to start your server on the last attempt. Please contact admin if the issue persists.  
the terminal log shows blow:

```
[I 2018-12-12 11:45:16.985 JupyterHub log:158] 302 GET /user/admin/ -> /hub/user/admin/ (@127.0.0.1) 0.74ms
Last login: Wed Dec 12 11:33:15 CST 2018
Welcome to Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-42-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed Dec 12 11:45:17 CST 2018

  System load:  0.06               Processes:           256
  Usage of /:   19.7% of 49.15GB   Users logged in:     2
  Memory usage: 31%                IP address for eth0: 172.16.0.16
  Swap usage:   0%

  => There are 2 zombie processes.

 * MicroK8s is Kubernetes in a snap. Made by devs for devs.
   One quick install on a workstation, VM, or appliance.

   - https://bit.ly/microk8s

 * Full K8s GPU support is now available! Get it in MicroK8s, CDK,
   and on GKE with Ubuntu workers.

   - https://blog.ubuntu.com/2018/12/10/using-gpgpus-with-kubernetes


 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

[I 2018-12-12 11:45:18.013 JupyterHub spawner:1100] Spawning jupyterhub-singleuser --port=60235
[E 2018-12-12 11:45:18.019 JupyterHub user:477] Unhandled error starting admin's server: [Errno 2] No such file or directory: 'jupyterhub-singleuser'
[E 2018-12-12 11:45:18.151 JupyterHub web:1670] Uncaught exception GET /hub/user/admin/ (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8081', method='GET', uri='/hub/user/admin/', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/admin/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/admin/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 1052, in get
        await self.spawn_single_user(user)
      File "/home/admin/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 705, in spawn_single_user
        timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
      File "/home/admin/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
        await spawn_future
      File "/home/admin/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 489, in spawn
        raise e
      File "/home/admin/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 409, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/home/admin/anaconda3/lib/python3.6/site-packages/jupyterhub/spawner.py", line 1110, in start
        self.proc = Popen(cmd, **popen_kwargs)
      File "/home/admin/anaconda3/lib/python3.6/subprocess.py", line 707, in __init__
        restore_signals, start_new_session)
      File "/home/admin/anaconda3/lib/python3.6/subprocess.py", line 1326, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'jupyterhub-singleuser'
    
[E 2018-12-12 11:45:18.193 JupyterHub log:150] {
      "Host": "127.0.0.1:8081",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Connection": "keep-alive",
      "Cookie": "jupyterhub-hub-login=\"2|1:0|10:1544585595|20:jupyterhub-hub-login|44:MjQ1Njg4NTZjNGVhNGYyMmFmODY2ZDQ0OWYyNTg4ZDA=|60aa780c835d46fafea0ec5392de0e61a907d660ab8f45cfa5e551c80f7398c0\"; jupyterhub-session-id=9bd6f2a39bb74c1a80de2a4de752dcef",
      "Upgrade-Insecure-Requests": "1"
    }
[E 2018-12-12 11:45:18.193 JupyterHub log:158] 500 GET /hub/user/admin/ (admin@127.0.0.1) 1202.16ms
[I 2018-12-12 11:45:27.574 JupyterHub log:158] 200 GET /hub/home (admin@127.0.0.1) 122.79ms
[I 2018-12-12 11:45:28.957 JupyterHub login:19] User logged out: admin
[I 2018-12-12 11:45:29.061 JupyterHub log:158] 302 GET /hub/logout -> /hub/login (admin@127.0.0.1) 195.74ms
[I 2018-12-12 11:45:29.074 JupyterHub log:158] 200 GET /hub/login (@127.0.0.1) 7.75ms
[W 2018-12-12 11:45:35.007 JupyterHub auth:618] PAM Authentication failed (admin@127.0.0.1): [PAM Error 7] Authentication failure
[W 2018-12-12 11:45:35.007 JupyterHub base:504] Failed login for admin
[I 2018-12-12 11:45:35.008 JupyterHub log:158] 200 POST /hub/login?next= (@127.0.0.1) 2763.83ms
^C
Interrupted
[I 2018-12-12 11:49:22.443 JupyterHub app:1706] Cleaning up single-user servers...
[I 2018-12-12 11:49:22.443 JupyterHub proxy:627] Cleaning up proxy[1312]...
[I 2018-12-12 11:49:22.446 JupyterHub app:1739] ...done
```

I have checked some solutions,
https://github.com/jupyterhub/jupyterhub/issues/794
https://github.com/jupyterhub/jupyterhub/issues/917

Still do not know how to solve it,  please help.

**Comment by minrk** [comment]
> I have setup and install jupyterhub by instuctions.

What instructions did you follow?

This is probably the key error message:

```
FileNotFoundError: [Errno 2] No such file or directory: 'jupyterhub-singleuser'
```

This means that the file `jupyterhub-singleuser` is not on PATH. Can you share what you get for `which jupyterhub-singleuser`?

I'm guessing since you have executed `/home/admin/anaconda3/bin/jupyterhub` that `/home/admin/anaconda3/bin` is not on PATH. It probably needs to be.

However, this location points to a possible issue: jupyterhub generally should not be installed in a single user's home directory, because that means that *all* users must be able to read and execute files in that user's home directory because all users must have access to the jupyterhub environment. Usually this means installing jupyterhub in a system-wide location, e.g. `/opt/conda` (the location mostly doesn't matter, it just needs to be readable and executable by all jupyterhub users and should be on PATH).

**Comment by studyquant** [comment]
hello, i have added the jupyterhub-singleuser into the path, well, the new error occur. 
500: INTERNAL SERVER ERROR  ,  REDIRECT LOOP DETECTED

i tried to restart sever, but it does not work.

[I 2018-12-13 12:05:32.468 JupyterHub app:1673] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.4
[I 2018-12-13 12:05:32.468 JupyterHub app:1673] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.4
[I 2018-12-13 12:05:32.471 JupyterHub app:1016] Loading cookie_secret from /home/admin/anaconda3/jupyterhub_cookie_secret
[I 2018-12-13 12:05:32.503 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[W 2018-12-13 12:05:32.505 JupyterHub app:1173] No admin users, admin interface will be unavailable.
[W 2018-12-13 12:05:32.505 JupyterHub app:1174] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-12-13 12:05:32.505 JupyterHub app:1201] Not using whitelist. Any authenticated user will be allowed.
[I 2018-12-13 12:05:32.558 JupyterHub app:1855] Hub API listening on http://127.0.0.1:8081/hub/
[W 2018-12-13 12:05:32.560 JupyterHub proxy:565] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2018-12-13 12:05:32.560 JupyterHub proxy:567] Starting proxy @ http://:8000
12:05:33.108 [ConfigProxy] info: Proxying http://*:8000 to (no default)
12:05:33.112 [ConfigProxy] info: Proxy API at http://127.0.0.1:8001/api/routes
12:05:33.134 [ConfigProxy] info: 200 GET /api/routes 
[I 2018-12-13 12:05:33.134 JupyterHub proxy:301] Checking routes
[I 2018-12-13 12:05:33.135 JupyterHub proxy:370] Adding default route for Hub: / => http://127.0.0.1:8081
12:05:33.137 [ConfigProxy] info: Adding route / -> http://127.0.0.1:8081
[I 2018-12-13 12:05:33.138 JupyterHub app:1912] JupyterHub is now running at http://:8000
12:05:33.141 [ConfigProxy] info: 201 POST /api/routes/ 
[I 2018-12-13 12:05:37.594 JupyterHub log:158] 302 GET / -> /hub (@127.0.0.1) 1.00ms
[W 2018-12-13 12:05:37.623 JupyterHub base:242] Invalid or expired cookie token
[I 2018-12-13 12:05:37.624 JupyterHub log:158] 302 GET /hub -> /hub/ (@127.0.0.1) 0.73ms
[W 2018-12-13 12:05:37.678 JupyterHub base:242] Invalid or expired cookie token
[I 2018-12-13 12:05:37.678 JupyterHub log:158] 302 GET /hub/ -> /hub/login (@127.0.0.1) 1.39ms
[I 2018-12-13 12:05:37.742 JupyterHub log:158] 200 GET /hub/login (@127.0.0.1) 57.36ms
[W 2018-12-13 12:05:42.384 JupyterHub auth:618] PAM Authentication failed (admin@127.0.0.1): [PAM Error 7] Authentication failure
[W 2018-12-13 12:05:42.385 JupyterHub base:504] Failed login for admin
[I 2018-12-13 12:05:42.387 JupyterHub log:158] 200 POST /hub/login?next= (@127.0.0.1) 2647.59ms
[I 2018-12-13 12:05:48.786 JupyterHub base:499] User logged in: admin
[I 2018-12-13 12:05:48.788 JupyterHub log:158] 302 POST /hub/login?next= -> /user/admin/ (admin@127.0.0.1) 102.65ms
[I 2018-12-13 12:05:48.797 JupyterHub log:158] 302 GET /user/admin/ -> /hub/user/admin/ (@127.0.0.1) 5.92ms
sh: 1: cannot create /run/motd.dynamic.new: Permission denied
Welcome to Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-42-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Thu Dec 13 10:52:41 CST 2018

  System load:  0.12               Processes:           252
  Usage of /:   19.9% of 49.15GB   Users logged in:     2
  Memory usage: 33%                IP address for eth0: 172.16.0.16
  Swap usage:   0%

  => There are 3 zombie processes.

 * MicroK8s is Kubernetes in a snap. Made by devs for devs.
   One quick install on a workstation, VM, or appliance.

   - https://bit.ly/microk8s

 * Full K8s GPU support is now available! Get it in MicroK8s, CDK,
   and on GKE with Ubuntu workers.

   - https://blog.ubuntu.com/2018/12/10/using-gpgpus-with-kubernetes


 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

[I 2018-12-13 12:05:49.073 JupyterHub spawner:1100] Spawning jupyterhub-singleuser --port=58127
Failed to set groups [Errno 1] Operation not permitted
[I 2018-12-13 12:05:50.270 SingleUserNotebookApp singleuser:406] Starting jupyterhub-singleuser server version 0.9.4
[I 2018-12-13 12:05:50.278 JupyterHub log:158] 200 GET /hub/api (@127.0.0.1) 1.84ms
[I 2018-12-13 12:05:50.280 SingleUserNotebookApp notebookapp:1712] Serving notebooks from local directory: /home/admin
[I 2018-12-13 12:05:50.281 SingleUserNotebookApp notebookapp:1712] The Jupyter Notebook is running at:
[I 2018-12-13 12:05:50.281 SingleUserNotebookApp notebookapp:1712] http://127.0.0.1:58127/user/admin/
[I 2018-12-13 12:05:50.281 SingleUserNotebookApp notebookapp:1713] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2018-12-13 12:05:50.322 SingleUserNotebookApp log:158] 302 GET /user/admin/ -> /user/admin/tree? (@127.0.0.1) 0.74ms
[I 2018-12-13 12:05:50.323 JupyterHub base:628] User admin took 1.452 seconds to start
[I 2018-12-13 12:05:50.323 JupyterHub proxy:242] Adding user admin to proxy /user/admin/ => http://127.0.0.1:58127
12:05:50.325 [ConfigProxy] info: Adding route /user/admin -> http://127.0.0.1:58127
12:05:50.326 [ConfigProxy] info: 201 POST /api/routes/user/admin 
[I 2018-12-13 12:05:50.327 JupyterHub log:158] 302 GET /hub/user/admin/ -> /user/admin/?redirects=1 (admin@127.0.0.1) 1524.74ms
[I 2018-12-13 12:05:50.332 JupyterHub log:158] 302 GET /user/admin/?redirects=1 -> /hub/user/admin/?redirects=1 (@127.0.0.1) 0.75ms
[W 2018-12-13 12:05:50.383 JupyterHub base:1101] Redirect loop detected on /hub/user/admin/?redirects=1
[I 2018-12-13 12:05:52.385 JupyterHub log:158] 302 GET /hub/user/admin/?redirects=1 -> /user/admin/?redirects=2 (admin@127.0.0.1) 2048.12ms
[I 2018-12-13 12:05:52.391 JupyterHub log:158] 302 GET /user/admin/?redirects=2 -> /hub/user/admin/?redirects=2 (@127.0.0.1) 2.15ms
[W 2018-12-13 12:05:52.434 JupyterHub base:1101] Redirect loop detected on /hub/user/admin/?redirects=2
[I 2018-12-13 12:05:56.435 JupyterHub log:158] 302 GET /hub/user/admin/?redirects=2 -> /user/admin/?redirects=3 (admin@127.0.0.1) 4037.44ms
[I 2018-12-13 12:05:56.443 JupyterHub log:158] 302 GET /user/admin/?redirects=3 -> /hub/user/admin/?redirects=3 (@127.0.0.1) 0.87ms
[W 2018-12-13 12:05:56.492 JupyterHub base:1101] Redirect loop detected on /hub/user/admin/?redirects=3
[I 2018-12-13 12:06:04.494 JupyterHub log:158] 302 GET /hub/user/admin/?redirects=3 -> /user/admin/?redirects=4 (admin@127.0.0.1) 8043.51ms
[I 2018-12-13 12:06:04.500 JupyterHub log:158] 302 GET /user/admin/?redirects=4 -> /hub/user/admin/?redirects=4 (@127.0.0.1) 0.70ms
[W 2018-12-13 12:06:04.558 JupyterHub web:1667] 500 GET /hub/user/admin/?redirects=4 (127.0.0.1): Redirect loop detected.
[E 2018-12-13 12:06:04.566 JupyterHub log:150] {
      "Host": "127.0.0.1:8081",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://127.0.0.1:8081/hub/login?next=",
      "Connection": "keep-alive",
      "Cookie": "jupyterhub-hub-login=\"2|1:0|10:1544673948|20:jupyterhub-hub-login|44:NGJiMmU1Mzg0MDhkNGQxZmI3ZjQzY2E1YzgzZmYxYjQ=|477e3840e790f4b85d8bc7193e6b065a734d5e3f75560bfc99ef23e300416b5e\"; jupyterhub-session-id=5b0f968fb5954bdc902bbac77418b9d3",
      "Upgrade-Insecure-Requests": "1"
    }
[E 2018-12-13 12:06:04.566 JupyterHub log:158] 500 GET /hub/user/admin/?redirects=4 (admin@127.0.0.1) 60.51ms
[I 2018-12-13 12:06:54.861 JupyterHub log:158] 302 GET /hub/user/admin/ -> /hub/login?next=%2Fhub%2Fuser%2Fadmin%2F (@127.0.0.1) 1.40ms
[I 2018-12-13 12:06:54.885 JupyterHub log:158] 200 GET /hub/login?next=%2Fhub%2Fuser%2Fadmin%2F (@127.0.0.1) 2.64ms

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
