### ISSUE TITLE
Redirect loop detected on login， 500: INTERNAL SERVER ERROR ,

### ISSUE THREAD

**Issue by studyquant** [jupyterhub/jupyterhub#2361]
hello, i have added the jupyterhub-singleuser into the path, well, the new error occur.
500: INTERNAL SERVER ERROR , REDIRECT LOOP DETECTED

i tried to restart sever, but it does not work.

[I 2018-12-13 12:05:32.468 JupyterHub app:1673] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.4
[I 2018-12-13 12:05:32.468 JupyterHub app:1673] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.4
[I 2018-12-13 12:05:32.471 JupyterHub app:1016] Loading cookie_secret from /home/admin/anaconda3/jupyterhub_cookie_secret
[I 2018-12-13 12:05:32.503 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[W 2018-12-13 12:05:32.505 JupyterHub app:1173] No admin users, admin interface will be unavailable.
[W 2018-12-13 12:05:32.505 JupyterHub app:1174] Add any administrative users to c.Authenticator.admin_users in config.
[I 2018-12-13 12:05:32.505 JupyterHub app:1201] Not using whitelist. Any authenticated user will be allowed.
[I 2018-12-13 12:05:32.558 JupyterHub app:1855] Hub API listening on http://127.0.0.1:8081/hub/
[W 2018-12-13 12:05:32.560 JupyterHub proxy:565] Running JupyterHub without SSL. I hope there is SSL termination happening somewhere else...
[I 2018-12-13 12:05:32.560 JupyterHub proxy:567] Starting proxy @ http://:8000
12:05:33.108 [ConfigProxy] info: Proxying http://*:8000 to (no default)
12:05:33.112 [ConfigProxy] info: Proxy API at http://127.0.0.1:8001/api/routes
12:05:33.134 [ConfigProxy] info: 200 GET /api/routes
[I 2018-12-13 12:05:33.134 JupyterHub proxy:301] Checking routes
[I 2018-12-13 12:05:33.135 JupyterHub proxy:370] Adding default route for Hub: / => http://127.0.0.1:8081
12:05:33.137 [ConfigProxy] info: Adding route / -> http://127.0.0.1:8081
[I 2018-12-13 12:05:33.138 JupyterHub app:1912] JupyterHub is now running at http://:8000
12:05:33.141 [ConfigProxy] info: 201 POST /api/routes/
[I 2018-12-13 12:05:37.594 JupyterHub log:158] 302 GET / -> /hub (@127.0.0.1) 1.00ms
[W 2018-12-13 12:05:37.623 JupyterHub base:242] Invalid or expired cookie token
[I 2018-12-13 12:05:37.624 JupyterHub log:158] 302 GET /hub -> /hub/ (@127.0.0.1) 0.73ms
[W 2018-12-13 12:05:37.678 JupyterHub base:242] Invalid or expired cookie token
[I 2018-12-13 12:05:37.678 JupyterHub log:158] 302 GET /hub/ -> /hub/login (@127.0.0.1) 1.39ms
[I 2018-12-13 12:05:37.742 JupyterHub log:158] 200 GET /hub/login (@127.0.0.1) 57.36ms
[W 2018-12-13 12:05:42.384 JupyterHub auth:618] PAM Authentication failed (admin@127.0.0.1): [PAM Error 7] Authentication failure
[W 2018-12-13 12:05:42.385 JupyterHub base:504] Failed login for admin
[I 2018-12-13 12:05:42.387 JupyterHub log:158] 200 POST /hub/login?next= (@127.0.0.1) 2647.59ms
[I 2018-12-13 12:05:48.786 JupyterHub base:499] User logged in: admin
[I 2018-12-13 12:05:48.788 JupyterHub log:158] 302 POST /hub/login?next= -> /user/admin/ (admin@127.0.0.1) 102.65ms
[I 2018-12-13 12:05:48.797 JupyterHub log:158] 302 GET /user/admin/ -> /hub/user/admin/ (@127.0.0.1) 5.92ms
sh: 1: cannot create /run/motd.dynamic.new: Permission denied
Welcome to Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-42-generic x86_64)

Documentation: https://help.ubuntu.com
Management: https://landscape.canonical.com
Support: https://ubuntu.com/advantage
System information as of Thu Dec 13 10:52:41 CST 2018

System load: 0.12 Processes: 252
Usage of /: 19.9% of 49.15GB Users logged in: 2
Memory usage: 33% IP address for eth0: 172.16.0.16
Swap usage: 0%

=> There are 3 zombie processes.

MicroK8s is Kubernetes in a snap. Made by devs for devs.
One quick install on a workstation, VM, or appliance.

https://bit.ly/microk8s
Full K8s GPU support is now available! Get it in MicroK8s, CDK,
and on GKE with Ubuntu workers.

https://blog.ubuntu.com/2018/12/10/using-gpgpus-with-kubernetes
Canonical Livepatch is available for installation.

Reduce system reboots and improve kernel security. Activate at:
https://ubuntu.com/livepatch
[I 2018-12-13 12:05:49.073 JupyterHub spawner:1100] Spawning jupyterhub-singleuser --port=58127
Failed to set groups [Errno 1] Operation not permitted
[I 2018-12-13 12:05:50.270 SingleUserNotebookApp singleuser:406] Starting jupyterhub-singleuser server version 0.9.4
[I 2018-12-13 12:05:50.278 JupyterHub log:158] 200 GET /hub/api (@127.0.0.1) 1.84ms
[I 2018-12-13 12:05:50.280 SingleUserNotebookApp notebookapp:1712] Serving notebooks from local directory: /home/admin
[I 2018-12-13 12:05:50.281 SingleUserNotebookApp notebookapp:1712] The Jupyter Notebook is running at:
[I 2018-12-13 12:05:50.281 SingleUserNotebookApp notebookapp:1712] http://127.0.0.1:58127/user/admin/
[I 2018-12-13 12:05:50.281 SingleUserNotebookApp notebookapp:1713] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2018-12-13 12:05:50.322 SingleUserNotebookApp log:158] 302 GET /user/admin/ -> /user/admin/tree? (@127.0.0.1) 0.74ms
[I 2018-12-13 12:05:50.323 JupyterHub base:628] User admin took 1.452 seconds to start
[I 2018-12-13 12:05:50.323 JupyterHub proxy:242] Adding user admin to proxy /user/admin/ => http://127.0.0.1:58127
12:05:50.325 [ConfigProxy] info: Adding route /user/admin -> http://127.0.0.1:58127
12:05:50.326 [ConfigProxy] info: 201 POST /api/routes/user/admin
[I 2018-12-13 12:05:50.327 JupyterHub log:158] 302 GET /hub/user/admin/ -> /user/admin/?redirects=1 (admin@127.0.0.1) 1524.74ms
[I 2018-12-13 12:05:50.332 JupyterHub log:158] 302 GET /user/admin/?redirects=1 -> /hub/user/admin/?redirects=1 (@127.0.0.1) 0.75ms
[W 2018-12-13 12:05:50.383 JupyterHub base:1101] Redirect loop detected on /hub/user/admin/?redirects=1
[I 2018-12-13 12:05:52.385 JupyterHub log:158] 302 GET /hub/user/admin/?redirects=1 -> /user/admin/?redirects=2 (admin@127.0.0.1) 2048.12ms
[I 2018-12-13 12:05:52.391 JupyterHub log:158] 302 GET /user/admin/?redirects=2 -> /hub/user/admin/?redirects=2 (@127.0.0.1) 2.15ms
[W 2018-12-13 12:05:52.434 JupyterHub base:1101] Redirect loop detected on /hub/user/admin/?redirects=2
[I 2018-12-13 12:05:56.435 JupyterHub log:158] 302 GET /hub/user/admin/?redirects=2 -> /user/admin/?redirects=3 (admin@127.0.0.1) 4037.44ms
[I 2018-12-13 12:05:56.443 JupyterHub log:158] 302 GET /user/admin/?redirects=3 -> /hub/user/admin/?redirects=3 (@127.0.0.1) 0.87ms
[W 2018-12-13 12:05:56.492 JupyterHub base:1101] Redirect loop detected on /hub/user/admin/?redirects=3
[I 2018-12-13 12:06:04.494 JupyterHub log:158] 302 GET /hub/user/admin/?redirects=3 -> /user/admin/?redirects=4 (admin@127.0.0.1) 8043.51ms
[I 2018-12-13 12:06:04.500 JupyterHub log:158] 302 GET /user/admin/?redirects=4 -> /hub/user/admin/?redirects=4 (@127.0.0.1) 0.70ms
[W 2018-12-13 12:06:04.558 JupyterHub web:1667] 500 GET /hub/user/admin/?redirects=4 (127.0.0.1): Redirect loop detected.
[E 2018-12-13 12:06:04.566 JupyterHub log:150] {
"Host": "127.0.0.1:8081",
"User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0",
"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,/;q=0.8",
"Accept-Language": "en-US,en;q=0.5",
"Accept-Encoding": "gzip, deflate",
"Referer": "http://127.0.0.1:8081/hub/login?next=",
"Connection": "keep-alive",
"Cookie": "jupyterhub-hub-login="2|1:0|10:1544673948|20:jupyterhub-hub-login|44:NGJiMmU1Mzg0MDhkNGQxZmI3ZjQzY2E1YzgzZmYxYjQ=|477e3840e790f4b85d8bc7193e6b065a734d5e3f75560bfc99ef23e300416b5e"; jupyterhub-session-id=5b0f968fb5954bdc902bbac77418b9d3",
"Upgrade-Insecure-Requests": "1"
}
[E 2018-12-13 12:06:04.566 JupyterHub log:158] 500 GET /hub/user/admin/?redirects=4 (admin@127.0.0.1) 60.51ms
[I 2018-12-13 12:06:54.861 JupyterHub log:158] 302 GET /hub/user/admin/ -> /hub/login?next=%2Fhub%2Fuser%2Fadmin%2F (@127.0.0.1) 1.40ms
[I 2018-12-13 12:06:54.885 JupyterHub log:158] 200 GET /hub/login?next=%2Fhub%2Fuser%2Fadmin%2F (@127.0.0.1) 2.64ms

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
