### ISSUE TITLE
Failed spawns are still added to the proxy

### ISSUE THREAD

**Issue by hhuuggoo** [jupyterhub/jupyterhub#2366]
**Describe the bug**

If a spawn fails for a named server (for example, due to a timeout), The dead server will still be added to proxy and considered `ready` 

I believe the issue is that the notion of `ready` inside jupyterhub is based on:
https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/spawner.py#L87
which defines it as not being `pending` and having a `server`.  but jupyterhub assigns servers before we even start spawning.
https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/user.py#L410
And if the spawn fails, it's no longer "pending" therefore it becomes ready as soon as it has failed.  Then we go through looking for missing routes and we add them based on this ready flag, periodically.
https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/proxy.py#L322

**To Reproduce**
- Start jupyterhub (I'm using the kubespawner jupyterhub_config)
- set the spawner timeout to be 1 second 
- create a named server
- the server will be added to the page, but that server will not work.

**Expected behavior**
-  failed spawns should not show up and be represented as valiid server

**Desktop (please complete the following information):**

**Comment by hhuuggoo** [comment]
fwiw I believe this issue impacts 0.9.4 (even without named servers).  You do get the error message in the UI that the server failed to start, but if you navigate to home, there are links for your server and stopping it.  The named server UI makes this problem worse because you don't get the visual indication that the spawn failed

**Comment by consideRatio** [comment]
I think it might also, because I recall noticing such issue, and I have not used named servers yet.

**Comment by consideRatio** [comment]
I'm quite confident servers that have not been responding correctly by the hub after spawn won't be get a route added for them in current jupyterhub.
