### ISSUE TITLE
Docker not working with asp.net core application v2.1

### ISSUE THREAD

**Issue by sreekanthmg** [jupyterhub/jupyterhub#2367]
Hi! Thanks for using JupyterHub.

If you are reporting an issue with JupyterHub, please use the [GitHub issue](https://github.com/jupyterhub/jupyterhub/issues) search feature to check if your issue has been asked already. If it has, please add your comments to the existing issue.

**Describe the bug**
Asp.Net Core v2.1 not working with dockers

**To Reproduce**
1. Created a simple asp.net core 2.1 service named service1
2. Added following steps in dockerfile 
FROM microsoft/dotnet:latest
WORKDIR /app
COPY . /app
RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]
EXPOSE 5000/tcp
ENTRYPOINT ["dotnet", "run", "--server.urls", "http://0.0.0.0:5000"]

3. If I run visual studio by selecting "DOCKER" as runtime, VS automatically run this as container and I will be able to access the url by http://ipconfig:port/api/values

But this does not work when I try to use docker commands like below

docker build -t smg/serviceapp1 .

It creates an image successfully like below
REPOSITORY                TAG                                      IMAGE ID            CREATED              SIZE
smg/serviceapp1        latest                                   67409e2f0441        About a minute ago   1.88GB

Then, run the docker like below
docker run -p 5000:5000 smg/serviceapp1 --name smg_mytesting

It creates container and it is in running state
CONTAINER ID        IMAGE                COMMAND                    CREATED             STATUS              PORTS                     NAMES
1afef969baaf        smg/serviceapp1   "dotnet run --server…"     10 minutes ago      Up 10 minutes       0.0.0.0:5000->5000/tcp    wonderful_neumann

But, when I try to use all ways it does not work like
http://localhost:5000/api/values
http://docker host ip:5000/api/values

Here, docker host ip I got it by using docker inspect command

Please help me

I am running this by using docker windows in docker windows containers as that is my requirement

**Expected behavior**
I should able to access the url like below
http://localhost:5000/api/values
http://docker host ip:5000/api/values

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Any

**Additional context**
I am using windows containers and docker for windows

- Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.
- Running in `--debug` mode can also be helpful for troubleshooting.

**Comment by rollbackchen** [comment]
I think this is not a jupyterhub issue; 
if jupyterhub and your api in the same network, you can access like below
`http://smg_mytesting(your container name):5000/api/values`

**Comment by GeorgianaElena** [comment]
Closing this as it's not a JupyterHub related issue.
