### ISSUE TITLE
[HELP]: Need to proxy to extra container in jupyter server

### ISSUE THREAD

**Issue by rushikeshraut777** [jupyterhub/jupyterhub#2369]
I am trying to run some extra containers along with the jupyter notebook container. This extra container has a flask service running inside it on port 8080.

I want to access this service via REST. I read about nbserverproxy, but it is useful to access service in the same container as notebook server. How can I tell the proxy to connect to the extra container?

I am trying to access the REST endpoint (in sidecar) from a custom jupyter extension. @yuvipanda @minrk

**Comment by Chrisjw42** [comment]
I'd also be interesting in doing this, we have a singleUser.extraContainer running Theia that we'd like to access from a user's Jupyter environment.

**Comment by manics** [comment]
@Chrisjw42 If you're using `extraContainers` in Z2JH they should be in the same pod as the singleuser server. All containers in the pod share the same network so should be accessible over localhost: https://kubernetes.io/docs/concepts/cluster-administration/networking/#the-kubernetes-network-model

**Comment by Chrisjw42** [comment]
Yup, that sounds about right! I was able to access the other container by assigning it a port in the zero-to-jupyterhub helm values file, and using jupyter-server-proxy to access that port bid the URL.

Having trouble now with Theia (running in the second container), I've connected to it, but I've got the infinite spinning wheel of death. Seems like some kind of authentication error, getting 502.

**Comment by scivm** [comment]
Can you post your config so far?  I am starting to look into this also.

**Comment by kevinevelasco** [comment]
> Yup, that sounds about right! I was able to access the other container by assigning it a port in the zero-to-jupyterhub helm values file, and using jupyter-server-proxy to access that port bid the URL.
> 
> Having trouble now with Theia (running in the second container), I've connected to it, but I've got the infinite spinning wheel of death. Seems like some kind of authentication error, getting 502.

Do you have your config.yml? I have the same use case
