### ISSUE TITLE
Why Jupyterhub is not working with conda. But its running fine with virtual env.?

### ISSUE THREAD

**Issue by II-VSB-II** [jupyterhub/jupyterhub#2374]
Jupyterhub giving 500 Error while its running fine with virtual env.

I am configuring Jupyterhub in centos docker image.

**Comment by minrk** [comment]
Can you provide more details? What is `conda list`? Can you share your Dockerfile? What are the logs for the error? Can you share your jupyterhub_config.py?

**Comment by GeorgianaElena** [comment]
Closing this as it has been inactive for a long time. @II-VSB-II, feel free to reopen it or open a new issue if you have any other question :four_leaf_clover:
