### ISSUE TITLE
Jupyter notebook timeout but showing different error

### ISSUE THREAD

**Issue by MikeSpark** [jupyterhub/jupyterhub#2379]
I'm at Jupyter hub notebook at pySpark 3.5 kernel, configured on Azure HDinsight with LDAP integration. Having successfully querying data, we found that if the same notebook opened and used, then we waited 20 minutes / reconnect the network, on Chrome the notebook will not try to reconnect; it will show still as trusted and connected. then when we execute it, it prompts below error:

=========================================
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-2-3005fca81256> in <module>()
     44 on i.ia_txn_dt = t.tx_biz_dt \
     45 
---> 46 order by 1''').show()

/usr/hdp/current/spark2-client/python/pyspark/sql/dataframe.py in show(self, n, truncate, vertical)
    348         """
    349         if isinstance(truncate, bool) and truncate:
--> 350             print(self._jdf.showString(n, 20, vertical))
    351         else:
    352             print(self._jdf.showString(n, int(truncate), vertical))

/usr/hdp/current/spark2-client/python/lib/py4j-0.10.6-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1158         answer = self.gateway_client.send_command(command)
   1159         return_value = get_return_value(
-> 1160             answer, self.gateway_client, self.target_id, self.name)
   1161 
   1162         for temp_arg in temp_args:

/usr/hdp/current/spark2-client/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/usr/hdp/current/spark2-client/python/lib/py4j-0.10.6-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    318                 raise Py4JJavaError(
    319                     "An error occurred while calling {0}{1}{2}.\n".
--> 320                     format(target_id, ".", name), value)
    321             else:
    322                 raise Py4JError(

Py4JJavaError: An error occurred while calling o93.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 38 in stage 14.0 failed 4 times, most recent failure: Lost task 38.3 in stage 14.0 (TID 2773, ., executor 63): java.io.IOException: org.apache.spark.SparkException: corrupt remote block broadcast_28_piece0 of broadcast_28: 1015480794 != -1018715957
=========================================

So the error is telling us corrupt remote block; however, actually when we reconnect the kernel, the same query could be used. We suspect the connection is broken in the backend / websocket; however, we want to know either this is actually configurable option that to prolong the session time out? or showing the jupyter notebook is disconnected?

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
