### ISSUE TITLE
set Spawner args via REST API

### ISSUE THREAD

**Issue by shibbas** [jupyterhub/jupyterhub#2383]
Hello, 

I'm trying to find if there is a way to set Spawner args like notebook_dir or --NotebookApp.default_url using the REST API, is there one? :) I've tried providing the values via the request data, but I guess its not the same. 

Thanks

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
