### ISSUE TITLE
Course wise seperation

### ISSUE THREAD

**Issue by manish0749** [jupyterhub/jupyterhub#2384]
Is there a way to separate the course wise assignments? Like only allowed students can see the assignments.

**Comment by whositwhatnow** [comment]
There is you can add an nbgrader config in each users ./jupyter folder and you can specify the only allowed course.

nbgrader_config.py

c = get_config()
c.Exchange.course_id = "COURSE"
c.Exchange.path_includes_course = True

Now you will run into a problem if that user ends up using it for anohter course in which you will have to change that config.

**Comment by manish0749** [comment]
@whositwhatnow You are right that's the main problem.
Can we not change is from the UI?
I have looked into it and get to know that each time we have to reload the jupyterhub when we change the config.
