### ISSUE TITLE
Set secure flag for cookies set by jupyter

### ISSUE THREAD

**Issue by Shiva1789** [jupyterhub/jupyterhub#2385]
Hi, I am new to jupyterhub environment, I am running jupyterhub behind zuul proxy.
Jupyter running as http service. I am not able to set the secure flag for the cookies set by jupyterhub and notebook like jupyterhub-hub-login, jupyterhub-session-id, jupyterhub-user-USERNAME and _xsrf. Please need some help on this. 
I tried setting below config in jupyterhub_config.py 
c.JupyterHub.cookie_options = dict(secure=True) still no luck.

**Comment by maluhoss** [comment]
same here. haven't been able to set cookies with the secure flag or set sameSite attribute as None.

**Comment by manics** [comment]
Hi @maluhoss 
There are some related issues here:
- https://discourse.jupyter.org/t/issue-with-chrome-80-and-samesite-cookie-changes/3757/7
- https://github.com/jupyterhub/jupyterhub/issues/3135

If you need more help please could you follow up on the [Jupyter community forum](https://discourse.jupyter.org/)? Thanks!
