### ISSUE TITLE
Is the /hub to /hub/ redirect useful?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#2388]
I get this from my hub pod of my z2jh deployment when I access `/` and have configured so I don't need to click on the "login with ..." button in order to login using `c.Authenticator.auto_login = True`.

Is the `/hub` to `/hub/` doing something for us in some way or is it a mistake to do it?

```
[I 2019-01-22 13:43:13.282 JupyterHub log:158] 302 GET / -> /hub (@194.218.xxx.xxx) 0.69ms
[I 2019-01-22 13:43:13.313 JupyterHub log:158] 302 GET /hub -> /hub/ (@194.218.xxx.xxx) 0.61ms
[I 2019-01-22 13:43:13.344 JupyterHub log:158] 302 GET /hub/ -> /hub/login (@194.218.xxx.xxx) 0.65m
```

**Comment by minrk** [comment]
Adding the slash in `/hub -> /hub/` is the right thing to do in terms of making sure things are routed to the right thing and prefix-matching is handled correctly. There was, however, a bug in the `/ -> /hub` redirect, which should have gone straight to `/hub/`. This is fixed by #2413.
