### ISSUE TITLE
Intermittent failures to connect to kernel

### ISSUE THREAD

**Issue by twiecki** [jupyterhub/jupyterhub#239]
I'm running jupyterhub quite successfully for most users but one user (on OSX 10.10.2, but not the only OSX user) is having voodoo connection problems (sometimes a NB comes up, most of the time it it doesn't). 

* In the logs I sometimes (not always) see `[ConfigProxy] Proxy error: code=ECONNRESET in the logs`
* It's not working with safari or chrome.
* Clearing the browser cache does not help.
* I can see the login working just fine on the jupyterhub logs but when the user tries to open a NB, nothing happens
* I tried the same from a different machine and browser where it works fine
* My feeling is that it fails when it tries to actually connect to the IPython kernel as the header of the page comes up but I don't see a kernel being started).

Grateful for any pointers!

**Comment by jhamrick** [comment]
I doubt the proxy error has anything to do with it, that usually just means that the connection was interrupted (e.g. someone closed their browser tab).

Are you able to open the javascript console in their browser when they try to open the notebook? If so, is there anything of interest there?

(I had a student who had a voodoo problem like this -- it was causing their browser to hang entirely -- and the reason was because (1) they had a corrupted version of Chrome, and (2) their version of Safari was too old. I doubt either of those are the case for you, because Safari on 10.10 should be fine, and if it's not working on a recent safari then it's probably something else. But maybe it's helpful to have these datapoints anyways. The solution here was to reinstall Chrome and have them use that.)

**Comment by jhamrick** [comment]
Also: it should be fine for it to load the notebook even if it can't connect to the kernel, so my suspicion would be that it's actually just having trouble loading the notebook. Another question: how large is the notebook?

**Comment by twiecki** [comment]
![image](https://cloud.githubusercontent.com/assets/674200/7301310/455adb2c-e9e2-11e4-8ce8-b436cc110783.png)

**Comment by twiecki** [comment]
on a run where it didn't open up.

**Comment by jhamrick** [comment]
Aha, so I bet it's that first error that's the problem. I don't know why loading the javascript would be timing out, though.

Do they have a firewall or anything installed that might be causing problems? Or maybe browser extensions?

@minrk have you seen this before?

**Comment by twiecki** [comment]
Yes, it does look that way. No firewall and no extensions though...

**Comment by twiecki** [comment]
Here's from another failure. 
![image](https://cloud.githubusercontent.com/assets/674200/7301752/e3af284e-e9e4-11e4-8f84-ac1a341b8b38.png)

**Comment by minrk** [comment]
I haven't personally, but @ellisonbg has. When there are slow network problems, require's timeouts are relatively aggressive, and can give up early. If I recall, his problem wasn't entirely solved by setting require's timeout to a larger value, but it did help.

**Comment by ellisonbg** [comment]
I do still see this, but haven't been able to track it down to a slow
network...

On Thu, Apr 23, 2015 at 11:59 AM, Min RK <notifications@github.com> wrote:

> I haven't personally, but @ellisonbg <https://github.com/ellisonbg> has.
> When there are slow network problems, require's timeouts are relatively
> aggressive, and can give up early. If I recall, his problem wasn't entirely
> solved by setting require's timeout to a larger value, but it did help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyterhub/issues/239#issuecomment-95686174>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by twiecki** [comment]
How can I increase the timeout?

**Comment by minrk** [comment]
Not easily. You would need to modify the `page.html` template and add `waitSeconds: 30` to The `require.config` call.

**Comment by KrishnaPG** [comment]
I am also getting this `Error: Load timeout for modules: base/js/utils`, but the list of failed modules generally vary. Will try to look into the code.

**Comment by willingc** [comment]
Hi all! I'm closing this issue as it's been inactive for a year. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or comment here if you would like me to reopen this issue. Thanks! :sunflower:
