### ISSUE TITLE
403 forbidden error after logging into jupyterhub portal.

### ISSUE THREAD

**Issue by signinred** [jupyterhub/jupyterhub#2392]
If you are having issues with installation or configuration, you may ask for help on the JupyterHub gitter channel or file an issue here.

**Comment by signinred** [comment]
![error](https://user-images.githubusercontent.com/36297257/51708136-1778b980-2049-11e9-8b53-13c2aa032ee9.JPG)

**Comment by signinred** [comment]
When i am clicking on MyServer option it is redirecting to this page.

**Comment by Zsailer** [comment]
Hi @signinred 

Are you an administrator on this jupyterhub? If so, it would help us if you provide more information about your deployment. 

Two things specifically would help us tremendously:
1. Details about your configurations (usually found in a `jupyterhub_config.py` file.
2. Any information printed by jupyterhub's logging system in your terminal.
