### ISSUE TITLE
Should JupyterHub support batch jobs?

### ISSUE THREAD

**Issue by mrocklin** [jupyterhub/jupyterhub#2394]
JupyterHub currently allows people to launch Jupyter Servers.  I believe that this is being expanded out to other systems, like RStudio.

Is it within scope to also have JupyterHub run batch jobs?  In this case a user would submit a Python script or Notebook, and it would be up to JupyterHub to run that job asynchronously without the user's further involvement.

This topic came out of a Pangeo discussion.  cc @RPrudden

**Comment by minrk** [comment]
I think at this point, it is out of scope for JupyterHub itself to introduce the concept of jobs. That said, a [service](https://jupyterhub.readthedocs.io/en/stable/api/service.html) could integrate such behavior into a given jupyterhub deployment.

1. auth with the Hub (notebook sessions already have the necessary API token, or you can use oauth)
2. mediate with the underlying system to launch jobs (e.g. kubernetes job objects)
3. track logs, events, etc.

The submit could be done via a UI extension or Python library from the notebook server session. Alternately, the wrapper API could be purely a Python API client and/or JupyterLab UI that talks directly to the underlying system (e.g. Kubernetes), depending on your credential management.
