### ISSUE TITLE
Add a discussion forum to jupyterhub for its user.

### ISSUE THREAD

**Issue by palashSharma17** [jupyterhub/jupyterhub#2395]
Hi I am new to jupyterhub. I want to know that if we can add discussion forum facility to jupyterhub so that users can post their comments

**Comment by consideRatio** [comment]
I totally agree @palashSharma17! :D Join in at https://discourse.jupyter.org

**Comment by consideRatio** [comment]
#2396

**Comment by minrk** [comment]
Closed by #2402
