### ISSUE TITLE
Let users know about our discourse forum

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#2396]
Add a link to https://discourse.jupyter.org in the README.md

We should also suggest what kind of questions etc is recommended to go to GitHub, Discourse, or Gitter.

In short, my take on it is the following:

Technical questions and a lot more: [discourse forum](https://discourse.jupyter.org)
Bugs / Feature requests: [github issues](https://github.com/jupyterhub/jupyterhub/issues)
Other aspects that is relevant only "today" or similar: [gitter chat](https://gitter.im/jupyterhub/jupyterhub)

**Comment by minrk** [comment]
Closed by #2402
