### ISSUE TITLE
Redirect loop detected with AWS Fargate

### ISSUE THREAD

**Issue by montao** [jupyterhub/jupyterhub#2398]
I get this error trying to run JupyterHub with AWS Fargate. My Dockerfile:

```
FROM jupyterhub/jupyterhub:latest
EXPOSE 8000
RUN useradd -ms /bin/bash admin
RUN echo "admin:changepassword" | chpasswd
RUN pip3 install jupyter
RUN pip3 install notebook
RUN pip3 install jupyterhub
RUN jupyterhub --generate-config
CMD ["jupyterhub"]
```

The following is the log:
```
[I 2019-01-28 12:02:35.822 JupyterHub base:499] User logged in: admin
[I 2019-01-28 12:02:35.824 JupyterHub log:158] 302 POST /hub/login?next= -> /user/admin/ (admin@::ffff:10.1.73.158) 101.42ms
[W 2019-01-28 12:02:37.165 JupyterHub auth:642] Failed to open PAM session for admin: [PAM Error 14] Cannot make/remove an entry for the specified session
[W 2019-01-28 12:02:37.166 JupyterHub auth:643] Disabling PAM sessions from now on.
[I 2019-01-28 12:02:37.214 JupyterHub spawner:1086] Spawning jupyterhub-singleuser --port=44083
[I 2019-01-28 12:02:37.513 JupyterHub log:158] 200 GET /hub/login (@::ffff:10.1.73.158) 3.74ms
[I 2019-01-28 12:02:39.038 SingleUserNotebookApp singleuser:405] Starting jupyterhub-singleuser server version 0.9.1
[I 2019-01-28 12:02:39.052 JupyterHub log:158] 200 GET /hub/api (@127.0.0.1) 0.78ms
[I 2019-01-28 12:02:39.063 SingleUserNotebookApp notebookapp:1772] Serving notebooks from local directory: /home/admin
[I 2019-01-28 12:02:39.063 SingleUserNotebookApp notebookapp:1772] The Jupyter Notebook is running at:
[I 2019-01-28 12:02:39.063 SingleUserNotebookApp notebookapp:1772] http://127.0.0.1:44083/user/admin/
[I 2019-01-28 12:02:39.064 SingleUserNotebookApp notebookapp:1773] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2019-01-28 12:02:40.359 JupyterHub log:158] 200 GET /hub/login (@::ffff:10.1.91.165) 2.55ms
[I 2019-01-28 12:02:41.955 SingleUserNotebookApp log:158] 302 GET /user/admin/ -> /user/admin/tree? (@127.0.0.1) 0.69ms
[I 2019-01-28 12:02:41.957 JupyterHub base:628] User admin took 4.862 seconds to start
[I 2019-01-28 12:02:41.957 JupyterHub proxy:242] Adding user admin to proxy /user/admin/ => http://127.0.0.1:44083
12:02:41.959 - info: [ConfigProxy] Adding route /user/admin -> http://127.0.0.1:44083
12:02:41.960 - info: [ConfigProxy] 201 POST /api/routes/user/admin
[I 2019-01-28 12:02:41.991 JupyterHub log:158] 302 GET /hub/user/admin/ -> /user/admin/?redirects=1 (admin@::ffff:10.1.73.158) 4935.35ms
[W 2019-01-28 12:02:42.140 JupyterHub base:1061] Redirect loop detected on /hub/user/admin/?redirects=1
```

**Comment by minrk** [comment]
Do you get this redirect loop several times and then a failure to load, or just this log message?

**Comment by tathagata** [comment]
Stuck with the same error. It tries 4 times and then gives up
![image](https://user-images.githubusercontent.com/68151/53269961-e4f5c700-36af-11e9-833a-d83338d8a1a7.png)
![image](https://user-images.githubusercontent.com/68151/53270027-1b334680-36b0-11e9-95c5-8da861434e94.png)
I thought it was due to HTTPS traffic being redirected to HTTP from the load balancer which is again redirected by CHP causing the loop - so downgraded to HTTP on ELB. However, same error persists.
Do we need to specify a specific CHP configuration  to get around this?

**Comment by tathagata** [comment]
Related issue #2175

**Comment by montao** [comment]
We decided to run Jupyter with Sagemaker and in EMR instead. That is an even more "managed solution" and it seems to work well. But it would be nice to also have the opportunity to use Fargate.

**Comment by tathagata** [comment]
@montao thanks for your reply. Any idea which might be a cost effective approach? Also I guess it reduces some work on setting up the auth component as well.
Will update if I get it to work somehow.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!

**Comment by tathagata** [comment]
Thanks - for anyone who ended up from google, you might need to configure the sticky sessions on your elb.
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-sticky-sessions.html
