### ISSUE TITLE
How to restart Jupyterhub

### ISSUE THREAD

**Issue by MichWeb75** [jupyterhub/jupyterhub#2399]
Hallo, I started Jupyterhub on my Centos 7 Server and I cannot close it anymore, it seems to persist and does not allow a restart. On the configuration x.x.x:8000, everything worked fine, but I also cannot restart the server here. What can I do to stop all Jupyerhub related processes ?

**Comment by 00Kai0** [comment]
If you start jupyterhub on the terminal just ctrl-C is ok. If your start
jupyterhub as the background process, the simple way is kill the process.
Use `ps aux` to find the process and use `kill PID` to kill it.This is my
suggestion.

MichWeb75 <notifications@github.com> 于2019年1月31日周四 下午8:12写道：

**Comment by whositwhatnow** [comment]
I would set this up to run as a service.  See here:

https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service

**Comment by GeorgianaElena** [comment]
Hi @MichWeb75! Do you still need help with this issue?

**Comment by GeorgianaElena** [comment]
Closing this as it seems to have been solved :sunflower: Feel free to ask on https://discourse.jupyter.org/ forum for any configuration issues or questions :heart: Thanks!
