### ISSUE TITLE
Community page link

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#2403]
Add link to the community page, https://jupyter.org/community, in the README:

See the following discussion: https://github.com/jupyterhub/jupyterhub/pull/2402#issuecomment-460076335

**Comment by mattjshannon** [comment]
Hi, I'd like to do this as my first open-source contribution if that is all right. Do I need to be assigned or just make a PR? I assume the intent is to add the link under the "Help and resources" section of the main readme. Thanks!

**Comment by betatim** [comment]
Thanks for getting involved and dipping your toes in the open-source contributor waters :)

In general opening a PR (as soon as you have something) to indicate that you are working on something and let others see what you are up to is the preferred way. I usually prefix my PRs that are not ready to be reviewed or merged (but exist to let others know what I am doing) with `[WIP] now the title of my PR`.

**Comment by mattjshannon** [comment]
@betatim Thanks for the information. I've created a PR (#2696), though there appear to be some token test failures (?) in the CircleCI log for whatever reason. I swear all I changed was the readme. :)
