### ISSUE TITLE
Configuration for jupyterhub in conda as system service

### ISSUE THREAD

**Issue by MichWeb75** [jupyterhub/jupyterhub#2405]
I usually start jupyterhub from the conda environment like this
source activate conda_env
jupyerhub -f /etc/jupyterhub_config.py
works fine!

Now I want to run this as system service:
https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service

```
[Unit]
Description=Jupyterhub

[Service]
User=root
Environment="PATH=/opt/conda/envs/ngs_py36/bin:/opt/miniconda3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
ExecStart=/opt/conda/envs/ngs_py36/bin/jupyterhub -f /etc/jupyterhub_config.py
WorkingDirectory=/etc/jupyterhub

[Install]
WantedBy=multi-user.target
```

This configuration results in a running daemon but access to the server results in error 500.
How to configure the jupyterhub server with conda properly ? Thank you for the help!

**Comment by minrk** [comment]
Change the start to a script that does something like:

```bash
#!/bin/bash -l
set -e

source /opt/conda/etc/profile.d/conda.sh
conda activate ngs_py36
exec jupyterhub -f ...
```

then make this your ExecStart instead of juypyterhub itself

**Comment by GeorgianaElena** [comment]
@MichWeb75, do you still need help with this?

**Comment by anumvarghese** [comment]
Getting Following error after login to jupyter hub and i have used dockerspwaner. I used docker to create conda enviornemnt and launch jupyterhub in openshift

Request to help to resolve 
[D 2020-04-24 10:11:00.776 JupyterHub dockerspawner:777] Getting container 'jupyter-varganu'
--
  | ERROR:asyncio:Task exception was never retrieved
  | future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /opt/app-root/conda-base/lib/python3.6/site-packages/jupyterhub/handlers/base.py:697> exception=DockerException("Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))",)>

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
