### ISSUE TITLE
jupyterhub login issue with second user

### ISSUE THREAD

**Issue by nitinkansal1984** [jupyterhub/jupyterhub#2406]
I installed jupyterhub version 0.9.4 and was successfully able to launch and login with my ntid and password, but when another user tries to login, it failed with below error. I saw few github links and blogs which suggest to comment out pam entry in /etc/pam.d/login and test. I did that, but that didn;t help. 

[W 2019-02-06 15:52:59.666 JupyterHub auth:642] Failed to open PAM session for kansan: [PAM Error 14] Cannot make/remove an entry for the specified session
[W 2019-02-06 15:52:59.666 JupyterHub auth:643] Disabling PAM sessions from now on.

I am posting my current /etc/pam.d/login file content here:

```
[root@server ~]# cat /etc/pam.d/login
#%PAM-1.0
auth [user_unknown=ignore success=ok ignore=ignore default=bad] pam_securetty.so
auth       substack     system-auth
auth       include      postlogin
account    required     pam_nologin.so
account    include      system-auth
password   include      system-auth
# pam_selinux.so close should be the first session rule
session    required     pam_selinux.so close
session    required     pam_loginuid.so
session    optional     pam_console.so
# pam_selinux.so open should only be followed by sessions to be executed in the user context
session    required     pam_selinux.so open
session    required     pam_namespace.so
session    optional     pam_keyinit.so force revoke
session    include      system-auth
session    include      postlogin
-session   optional     pam_ck_connector.so
auth    required        pam_exec.so /opt/script.sh
[root@server ~]# sestatus
SELinux status:                 disabled
[root@server ~]# cat /etc/sysconfig/selinux

# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
SELINUX=disabled
# SELINUXTYPE= can take one of three two values:
#     targeted - Targeted processes are protected,
#     minimum - Modification of targeted policy. Only selected processes are protected.
#     mls - Multi Level Security protection.
SELINUXTYPE=targeted
SELINUX=disabled


[root@server ~]#
```

I followed steps mentioned in https://github.com/jupyterhub/jupyterhub/issues/213 also but failed. 

Please help me to fix this one. I have spent 2 days on it without any luck.

**Comment by minrk** [comment]
I suspect you want to disable jupyterhub opening PAM sessions:

```python
c.PAMAuthenticator.open_sessions = False
```

**Comment by nitinkansal1984** [comment]
No that didn't help.

**Comment by gclen** [comment]
I ran into a similar error after upgrading to jupyterhub 0.9.6 from 0.8.1. I think the issue can be traced back to this [commit](https://github.com/jupyterhub/jupyterhub/pull/1691/commits/4de6b39788aa1b7597a36e7c9e3b51d498b50900) where the interaction with PAM was moved to a thread. I think having authentication in a separate thread is *probably* okay (though I haven't tested this). However, opening a PAM session should probably be done in the spawned process since they are typically setting process/thread attributes. I think taking another look at the commit above may also help with issues https://github.com/jupyterhub/jupyterhub/issues/2056 and https://github.com/jupyterhub/jupyterhub/issues/2754. Let me know if you need me to do more testing or need any other information.

**Comment by phozzy** [comment]
@gclen HI! have you managed to solve this issue or some workarounds? I have the similar problem.

**Comment by phozzy** [comment]
@nitinkansal1984 and you? did you manage to solve it?

**Comment by nitinkansal1984** [comment]
the hack was there in pam file for the issue what I was facing

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
