### ISSUE TITLE
Open .pt file results in "not UTF-8 encoded"

### ISSUE THREAD

**Issue by xysong1201** [jupyterhub/jupyterhub#2407]
I use Jupyter notebook and Pytorch, and I save the file in .pt file, but I'm not able to open it with jupyter notebook. Is there a way to open it?

**Comment by minrk** [comment]
I think pytorch .pt files are binary files that can't be read with a text editor. To open them, I think you use `torch.load` as seen [here](https://discuss.pytorch.org/t/saving-and-loading-a-model-in-pytorch/2610/2)

**Comment by xysong1201** [comment]
> I think pytorch .pt files are binary files that can't be read with a text editor. To open them, I think you use `torch.load` as seen [here](https://discuss.pytorch.org/t/saving-and-loading-a-model-in-pytorch/2610/2)

Hi, Thank you for your reply. 
In my case, my output in .pt file are results indicating the running loss of my model, so it's not a model, in this case, to plot the running loss for example in jupyter notebook, how should I load the data ?

**Comment by minrk** [comment]
I'm not sure, I think you'll have better luck asking at a pytorch user community for saving and loading data, including an example of the code that you are using to create the file and what you want to do after it's loaded. I have no experience with this, and it doesn't appear related to Jupyter or JupyterHub.
