### ISSUE TITLE
Open a specific file after starting a jupyter notebook server

### ISSUE THREAD

**Issue by BoPeng** [jupyterhub/jupyterhub#2409]
I apologize if I have missed anything obvious in the documentation but is there a way to allow users to click a link such as

```
http://server/filename.ipynb
```
and be able to edit `filename.ipynb` directly without having to browser for the file?

In our application
1. Authentication is not important so we can use [tmpauthenticator](https://github.com/jupyterhub/tmpauthenticator) to allow user to login without password.
2. We use a docker image to start single user notebook server
3. We have a large number of notebooks so it is difficult for users to browser for `filename.ipynb` after the server starts. It is therefore better if the server can open the specific notebook directly. It would be even better if the start up script can get hold of the filename so that it can provide only the specified file to the docker image.

**Comment by minrk** [comment]
There's a URL `https://hub-host/hub/user-redirect/...`  that redirects users to their own server, which allows you to share a single link that any user can open that file in their own server. e.g.

    https://myjupyterhub.biz/hub/user-redirect/notebooks/filename.ipynb

**Comment by BoPeng** [comment]
Thank you very much @minrk! Not quite sure how this magic works but I should be able to figure out the rest.
