### ISSUE TITLE
Proxy failed to start with exit code 0

### ISSUE THREAD

**Issue by himswamy** [jupyterhub/jupyterhub#2410]
If you are having issues with installation or configuration, you may ask for help on the JupyterHub gitter channel or file an issue here.

[I 2019-02-11 00:00:02.056 JupyterHub app:1673] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.4
[I 2019-02-11 00:00:02.057 JupyterHub app:1673] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.4
[I 2019-02-11 00:00:02.061 JupyterHub app:1016] Loading cookie_secret from /Users/himswamy0/jupyterhub_cookie_secret
[I 2019-02-11 00:00:02.080 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[W 2019-02-11 00:00:02.081 JupyterHub app:1173] No admin users, admin interface will be unavailable.
[W 2019-02-11 00:00:02.081 JupyterHub app:1174] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2019-02-11 00:00:02.081 JupyterHub app:1201] Not using whitelist. Any authenticated user will be allowed.
[I 2019-02-11 00:00:02.122 JupyterHub app:1855] Hub API listening on http://127.0.0.1:8081/hub/
[W 2019-02-11 00:00:02.122 JupyterHub proxy:472] Found proxy pid file: /Users/himswamy0/jupyterhub-proxy.pid
[W 2019-02-11 00:00:02.123 JupyterHub proxy:484] Proxy no longer running at pid=37126
[W 2019-02-11 00:00:02.124 JupyterHub proxy:565] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2019-02-11 00:00:02.124 JupyterHub proxy:567] Starting proxy @ http://:8000
[E 2019-02-11 00:00:02.159 JupyterHub utils:68] Unexpected error connecting to WKMIN1518755.global.publicisgroupe.net:8000 [Errno 8] nodename nor servname provided, or not known
[E 2019-02-11 00:00:02.187 JupyterHub utils:68] Unexpected error connecting to WKMIN1518755.global.publicisgroupe.net:8000 [Errno 8] nodename nor servname provided, or not known
[E 2019-02-11 00:00:02.216 JupyterHub utils:68] Unexpected error connecting to WKMIN1518755.global.publicisgroupe.net:8000 [Errno 8] nodename nor servname provided, or not known
[E 2019-02-11 00:00:02.580 JupyterHub utils:68] Unexpected error connecting to WKMIN1518755.global.publicisgroupe.net:8000 [Errno 8] nodename nor servname provided, or not known
00:00:02.668 - info: [ConfigProxy] Proxying http://*:8000 to (no default)
00:00:02.670 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
00:00:02.671 - error: [ConfigProxy] Uncaught Exception Error: listen EADDRINUSE: address already in use :::8000
    at Server.setupListenHandle [as _listen2] (net.js:1256:14)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1392:7)
    at Object.<anonymous> (/anaconda3/lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy:202:20)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
00:00:02.672 - error: [ConfigProxy] Uncaught Exception Error: listen EADDRINUSE: address already in use 127.0.0.1:8001
    at Server.setupListenHandle [as _listen2] (net.js:1256:14)
    at listenInCluster (net.js:1304:12)
    at doListen (net.js:1443:7)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
[E 2019-02-11 00:00:03.224 JupyterHub utils:68] Unexpected error connecting to WKMIN1518755.global.publicisgroupe.net:8000 [Errno 8] nodename nor servname provided, or not known
[C 2019-02-11 00:00:03.224 JupyterHub app:1867] Failed to start proxy
    Traceback (most recent call last):
      File "/anaconda3/lib/python3.7/site-packages/jupyterhub/app.py", line 1865, in start
        await self.proxy.start()
      File "/anaconda3/lib/python3.7/site-packages/jupyterhub/proxy.py", line 594, in start
        _check_process()
      File "/anaconda3/lib/python3.7/site-packages/jupyterhub/proxy.py", line 590, in _check_process
        raise e from None
    RuntimeError: Proxy failed to start with exit code 0

**Comment by himswamy** [comment]
Any help or suggestion please

**Comment by minrk** [comment]
> Uncaught Exception Error: listen EADDRINUSE: address already in use :::8000

This is the main error: another process is using port 8000. You might want to pick another port with `c.JupyterHub.port` or shutdown whatever is using that port.

Given that both 8000 and 8001 are in use, it's possible this is a previous instance of jupyterhub. Check for processes called `configurable-http-proxy` and shut them down.
