### ISSUE TITLE
matplotlib makes python kernel crash

### ISSUE THREAD

**Issue by 1kastner** [jupyterhub/jupyterhub#2411]
**Describe the bug**
When running python code, my kernel works fine. When I invoke matplotlib for plotting something, the kernel crashes and automatically restarts

**To Reproduce**
1. Create a new notebook
2. Execute the following code 

```python
import matplotlib.pyplot as plt
import numpy as np
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2*np.pi*t)
plt.plot(t, s)
```

**Expected behavior**
The plot should be visualised instead.

**Versions**
- Server-side: Based on current `jupyter/scipy-notebook` docker image
- Client-side: Firefox, Edge
- `jupyter troubleshoot` :

<details>
jovyan@0e0dae279b84:~$ jupyter troubleshoot
Traceback (most recent call last):
  File "/usr/local/bin/jupyter", line 6, in <module>
    from jupyter_core.command import main
ImportError: No module named 'jupyter_core.command'
$PATH:
        /opt/conda/bin
        /opt/conda/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin

sys.path:
        /opt/conda/bin
        /opt/conda/lib/python36.zip
        /opt/conda/lib/python3.6
        /opt/conda/lib/python3.6/lib-dynload
        /opt/conda/lib/python3.6/site-packages

sys.executable:
        /opt/conda/bin/python3.6

sys.version:
        3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
        [GCC 7.3.0]

platform.platform():
        Linux-4.4.0-138-generic-x86_64-with-debian-buster-sid

which -a jupyter:
        /opt/conda/bin/jupyter
        /opt/conda/bin/jupyter

pip list:
        Package            Version
        ------------------ ----------
        alembic            0.9.9
        asn1crypto         0.24.0
        async-generator    1.10
        attrs              18.2.0
        backcall           0.1.0
        beautifulsoup4     4.6.3
        bleach             3.0.2
        bokeh              0.13.0
        certifi            2018.11.29
        cffi               1.11.5
        chardet            3.0.4
        cloudpickle        0.5.6
        conda              4.6.3
        cryptography       2.4.2
        cycler             0.10.0
        Cython             0.28.5
        cytoolz            0.9.0.1
        dask               1.1.1
        decorator          4.3.0
        dill               0.2.9
        entrypoints        0.3
        fastcache          1.0.2
        gmpy2              2.0.8
        h5py               2.7.1
        idna               2.8
        imageio            2.4.1
        ipykernel          5.1.0
        ipython            7.2.0
        ipython-genutils   0.2.0
        ipywidgets         7.4.2
        jedi               0.13.2
        Jinja2             2.10
        jsonschema         3.0.0a3
        jupyter            1.0.0
        jupyter-client     5.2.4
        jupyter-console    6.0.0
        jupyter-core       4.4.0
        jupyterhub         0.9.4
        jupyterlab         0.35.4
        jupyterlab-server  0.2.0
        kiwisolver         1.0.1
        llvmlite           0.23.0
        Mako               1.0.7
        MarkupSafe         1.1.0
        matplotlib         2.2.3
        mistune            0.8.4
        mpmath             1.1.0
        nbconvert          5.3.1
        nbformat           4.4.0
        networkx           2.2
        notebook           5.7.2
        numba              0.38.1
        numexpr            2.6.9
        numpy              1.13.3
        olefile            0.46
        packaging          19.0
        pamela             0.3.0
        pandas             0.23.4
        pandocfilters      1.4.2
        parso              0.3.1
        patsy              0.5.1
        pexpect            4.6.0
        pickleshare        0.7.5
        Pillow             5.4.1
        pip                19.0.1
        prometheus-client  0.5.0
        prompt-toolkit     2.0.7
        protobuf           3.6.1
        ptyprocess         0.6.0
        pycosat            0.6.3
        pycparser          2.19
        pycurl             7.43.0.2
        Pygments           2.3.1
        pyOpenSSL          19.0.0
        pyparsing          2.3.1
        pyrsistent         0.14.9
        PySocks            1.6.8
        python-dateutil    2.7.5
        python-editor      1.0.3
        python-oauth2      1.0.1
        pytz               2018.9
        PyWavelets         1.0.1
        PyYAML             3.13
        pyzmq              17.1.2
        qtconsole          4.4.3
        requests           2.21.0
        ruamel-yaml        0.15.71
        scikit-image       0.14.2
        scikit-learn       0.20.2
        scipy              1.1.0
        seaborn            0.9.0
        Send2Trash         1.5.0
        setuptools         40.7.1
        six                1.12.0
        SQLAlchemy         1.2.17
        statsmodels        0.9.0
        sympy              1.1.1
        terminado          0.8.1
        testpath           0.4.2
        toolz              0.9.0
        tornado            5.1.1
        traitlets          4.3.2
        urllib3            1.24.1
        vincent            0.4.4
        wcwidth            0.1.7
        webencodings       0.5.1
        wheel              0.32.3
        widgetsnbextension 3.4.2
        xlrd               1.2.0

conda list:
        # packages in environment at /opt/conda:
        #
        # Name                    Version                   Build  Channel
        alembic                   0.9.9                      py_0    conda-forge
        asn1crypto                0.24.0                py36_1003    conda-forge
        async_generator           1.10                       py_0    conda-forge
        attrs                     18.2.0                     py_0    conda-forge
        backcall                  0.1.0                      py_0    conda-forge
        beautifulsoup4            4.6.3                 py36_1000    conda-forge
        blas                      1.1                    openblas    conda-forge
        bleach                    3.0.2                      py_1    conda-forge
        bokeh                     0.13.0                py36_1000    conda-forge
        bzip2                     1.0.6                h470a237_2    conda-forge
        ca-certificates           2018.11.29           ha4d7672_0    conda-forge
        certifi                   2018.11.29            py36_1000    conda-forge
        cffi                      1.11.5          py36h9745a5d_1001    conda-forge
        chardet                   3.0.4                 py36_1003    conda-forge
        cloudpickle               0.5.6                      py_0    conda-forge
        conda                     4.6.3                    py36_0    conda-forge
        conda-env                 2.6.0                         1    conda-forge
        configurable-http-proxy   3.1.0                   node8_1    conda-forge
        cryptography              2.4.2            py36h1ba5d50_0    defaults
        cycler                    0.10.0                     py_1    conda-forge
        cython                    0.28.5          py36hf484d3e_1000    conda-forge
        cytoolz                   0.9.0.1         py36h14c3975_1001    conda-forge
        dask-core                 1.1.1                      py_0    conda-forge
        dbus                      1.13.2               h714fa37_1    defaults
        decorator                 4.3.0                      py_0    conda-forge
        dill                      0.2.9                    py36_0    conda-forge
        entrypoints               0.3                   py36_1000    conda-forge
        expat                     2.2.5             hf484d3e_1002    conda-forge
        fastcache                 1.0.2           py36h14c3975_1001    conda-forge
        fontconfig                2.13.1            h2176d3f_1000    conda-forge
        freetype                  2.9.1             h94bbf69_1005    conda-forge
        gettext                   0.19.8.1          h9745a5d_1001    conda-forge
        glib                      2.56.2            had28632_1001    conda-forge
        gmp                       6.1.2                hfc679d8_0    conda-forge
        gmpy2                     2.0.8           py36hb20f59a_1002    conda-forge
        gst-plugins-base          1.14.0               hbbd80ab_1    defaults
        gstreamer                 1.14.0               hb453b48_1    defaults
        h5py                      2.7.1                    py36_3    conda-forge
        hdf5                      1.10.1                        2    conda-forge
        icu                       58.2              hf484d3e_1000    conda-forge
        idna                      2.8                   py36_1000    conda-forge
        imageio                   2.4.1                 py36_1000    conda-forge
        ipykernel                 5.1.0           py36h24bf2e0_1002    conda-forge
        ipython                   7.2.0           py36h24bf2e0_1000    conda-forge
        ipython_genutils          0.2.0                      py_1    conda-forge
        ipywidgets                7.4.2                      py_0    conda-forge
        jedi                      0.13.2                py36_1000    conda-forge
        jinja2                    2.10                       py_1    conda-forge
        jpeg                      9c                h14c3975_1001    conda-forge
        jsonschema                3.0.0a3               py36_1000    conda-forge
        jupyter                   1.0.0                      py_1    conda-forge
        jupyter_client            5.2.4                      py_0    conda-forge
        jupyter_console           6.0.0                      py_0    conda-forge
        jupyter_core              4.4.0                      py_0    conda-forge
        jupyterhub                0.9.4                 py36_1000    conda-forge
        jupyterlab                0.35.4                   py36_0    conda-forge
        jupyterlab_server         0.2.0                      py_0    conda-forge
        kiwisolver                1.0.1           py36h6bb024c_1002    conda-forge
        krb5                      1.16.1               h173b8e3_7    defaults
        libcurl                   7.63.0            h20c2e04_1000    defaults
        libedit                   3.1.20170329         haf1bffa_1    conda-forge
        libffi                    3.2.1                hfc679d8_5    conda-forge
        libgcc                    7.2.0                h69d50b8_2    conda-forge
        libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
        libgfortran               3.0.0                         1    conda-forge
        libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
        libiconv                  1.15              h14c3975_1004    conda-forge
        libpng                    1.6.36            h84994c4_1000    conda-forge
        libprotobuf               3.6.1             hdbcaa40_1000    conda-forge
        libsodium                 1.0.16               h470a237_1    conda-forge
        libssh2                   1.8.0                         1    conda-forge
        libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
        libtiff                   4.0.10            h648cc4a_1001    conda-forge
        libuuid                   2.32.1            h14c3975_1000    conda-forge
        libxcb                    1.13              h14c3975_1002    conda-forge
        libxml2                   2.9.8             h143f9aa_1005    conda-forge
        llvmlite                  0.23.0                   py36_1    conda-forge
        mako                      1.0.7                      py_1    conda-forge
        markupsafe                1.1.0           py36h14c3975_1000    conda-forge
        matplotlib                2.2.3            py36h8a2030e_1    conda-forge
        matplotlib-base           2.2.3            py36h60b886d_1    conda-forge
        mistune                   0.8.4           py36h14c3975_1000    conda-forge
        mpc                       1.1.0             hb20f59a_1006    conda-forge
        mpfr                      4.0.1             ha14ba45_1000    conda-forge
        mpmath                    1.1.0                      py_0    conda-forge
        nbconvert                 5.3.1                      py_1    conda-forge
        nbformat                  4.4.0                      py_1    conda-forge
        ncurses                   6.1                  hfc679d8_2    conda-forge
        networkx                  2.2                        py_1    conda-forge
        nodejs                    8.10.0                        0    conda-forge
        notebook                  5.7.2                 py36_1000    conda-forge
        numba                     0.38.1                   py36_0    conda-forge
        numexpr                   2.6.9           py36h637b7d7_1000    conda-forge
        numpy                     1.13.3          py36_blas_openblash1522bff_1201  [blas_openblas]  conda-forge
        olefile                   0.46                       py_0    conda-forge
        openblas                  0.3.3             h9ac9557_1001    conda-forge
        openssl                   1.1.1a            h14c3975_1000    conda-forge
        packaging                 19.0                       py_0    conda-forge
        pamela                    0.3.0                   py_1001    conda-forge
        pandas                    0.23.4          py36h637b7d7_1000    conda-forge
        pandoc                    2.5                           0    conda-forge
        pandocfilters             1.4.2                      py_1    conda-forge
        parso                     0.3.1                      py_0    conda-forge
        patsy                     0.5.1                      py_0    conda-forge
        pcre                      8.42                 h439df22_0    defaults
        pexpect                   4.6.0                 py36_1000    conda-forge
        pickleshare               0.7.5                 py36_1000    conda-forge
        pillow                    5.4.1           py36h00a061d_1000    conda-forge
        pip                       19.0.1                   py36_0    conda-forge
        prometheus_client         0.5.0                      py_0    conda-forge
        prompt_toolkit            2.0.7                      py_0    conda-forge
        protobuf                  3.6.1           py36hf484d3e_1001    conda-forge
        pthread-stubs             0.4               h14c3975_1001    conda-forge
        ptyprocess                0.6.0                 py36_1000    conda-forge
        pycosat                   0.6.3           py36h14c3975_1001    conda-forge
        pycparser                 2.19                       py_0    conda-forge
        pycurl                    7.43.0.2         py36h1ba5d50_0    defaults
        pygments                  2.3.1                      py_0    conda-forge
        pyopenssl                 19.0.0                   py36_0    conda-forge
        pyparsing                 2.3.1                      py_0    conda-forge
        pyqt                      5.6.0           py36h13b7fb3_1008    conda-forge
        pyrsistent                0.14.9          py36h14c3975_1000    conda-forge
        pysocks                   1.6.8                 py36_1002    conda-forge
        python                    3.6.8                h0371630_0    defaults
        python-dateutil           2.7.5                      py_0    conda-forge
        python-editor             1.0.3                      py_0    conda-forge
        python-oauth2             1.0.1                    py36_0    conda-forge
        pytz                      2018.9                     py_0    conda-forge
        pywavelets                1.0.1           py36h3010b51_1000    conda-forge
        pyyaml                    3.13            py36h14c3975_1001    conda-forge
        pyzmq                     17.1.2          py36h6afc9c9_1001    conda-forge
        qt                        5.6.3                h8bf5577_3    defaults
        qtconsole                 4.4.3                      py_0    conda-forge
        readline                  7.0                  haf1bffa_1    conda-forge
        requests                  2.21.0                py36_1000    conda-forge
        ruamel_yaml               0.15.71         py36h14c3975_1000    conda-forge
        scikit-image              0.14.2           py36hf484d3e_1    conda-forge
        scikit-learn              0.20.2          py36_blas_openblashebff5e3_1400  [blas_openblas]  conda-forge
        scipy                     1.1.0           py36_blas_openblash1522bff_1202  [blas_openblas]  conda-forge
        seaborn                   0.9.0                      py_0    conda-forge
        send2trash                1.5.0                      py_0    conda-forge
        setuptools                40.7.1                   py36_0    conda-forge
        sip                       4.18.1          py36hf484d3e_1000    conda-forge
        six                       1.12.0                py36_1000    conda-forge
        sqlalchemy                1.2.17           py36h14c3975_0    conda-forge
        sqlite                    3.26.0               hb1c47c0_0    conda-forge
        statsmodels               0.9.0           py36h3010b51_1000    conda-forge
        sympy                     1.1.1                    py36_0    conda-forge
        terminado                 0.8.1                 py36_1001    conda-forge
        testpath                  0.4.2                 py36_1000    conda-forge
        tini                      0.18.0               h470a237_1    conda-forge
        tk                        8.6.9                ha92aebf_0    conda-forge
        toolz                     0.9.0                      py_1    conda-forge
        tornado                   5.1.1           py36h14c3975_1000    conda-forge
        traitlets                 4.3.2                 py36_1000    conda-forge
        urllib3                   1.24.1                py36_1000    conda-forge
        vincent                   0.4.4                      py_1    conda-forge
        wcwidth                   0.1.7                      py_1    conda-forge
        webencodings              0.5.1                      py_1    conda-forge
        wheel                     0.32.3                   py36_0    conda-forge
        widgetsnbextension        3.4.2                 py36_1000    conda-forge
        xlrd                      1.2.0                      py_0    conda-forge
        xorg-libxau               1.0.8             h14c3975_1006    conda-forge
        xorg-libxdmcp             1.1.2             h14c3975_1007    conda-forge
        xz                        5.2.4                h470a237_1    conda-forge
        yaml                      0.1.7                h470a237_1    conda-forge
        zeromq                    4.2.5                hfc679d8_6    conda-forge
        zlib                      1.2.11               h470a237_3    conda-forge
jovyan@0e0dae279b84:~$ Traceback (most recent call last):
bash: syntax error near unexpected token `most'
jovyan@0e0dae279b84:~$   File "/usr/local/bin/jupyter", line 6, in <module>
bash: syntax error near unexpected token `newline'
jovyan@0e0dae279b84:~$     from jupyter_core.command import main
bash: from: command not found
jovyan@0e0dae279b84:~$ ImportError: No module named 'jupyter_core.command'
bash: ImportError:: command not found
jovyan@0e0dae279b84:~$
</details>

In the notebook I ran
```python
plt.get_backend()
```
and got 
`'module://ipykernel.pylab.backend_inline'` as the answer.

The same thing does not happen when I solely use the image:
```
docker pull jupyter/scipy-notebook
docker run -p 8888:8888 jupyter/scipy-notebook
```
Then everything works fine.

**Comment by minrk** [comment]
Do you see an error in the docker logs for the image? It might point to why the process is crashing. Setting the matplotlib default backend to `'module://ipykernel.pylab.backend_inline'` would allow the above code to load the inline backend by default.

**Comment by 1kastner** [comment]
I tried to turn on different kinds of debug modes.
For me the logs do not help.
I tried to figure out where such kinds of error logs might go to but I was not too successful so far.

**User Notebook**
<details>
```
[D 2019-02-11 15:50:08.895 SingleUserNotebookApp auth:263] Cache miss: token:6c5ac0fba4aa40e9b787dd1228231919:ed87e770-303d-4e22-a25c-abbac766792d
[D 2019-02-11 15:50:08.917 SingleUserNotebookApp auth:269] Received request from Hub user {'kind': 'user', 'name': 'user_z9se32srw0', 'admin': False, 'groups': [], 'server': '/user/user_z9se32srw0/', 'pending': None, 'created': '2019-02-11T15:32:08.769276Z', 'last_activity': '2019-02-11T15:50:08.911544Z', 'servers': None}
[D 2019-02-11 15:50:08.917 SingleUserNotebookApp auth:778] Allowing whitelisted Hub user user_z9se32srw0
[I 2019-02-11 15:50:08.918 SingleUserNotebookApp log:158] 200 GET /user/user_z9se32srw0/api/sessions?_=1549899121461 (user_z9se32srw0@134.28.117.8) 23.76ms
[D 2019-02-11 15:50:08.919 SingleUserNotebookApp auth:778] Allowing whitelisted Hub user user_z9se32srw0
[I 2019-02-11 15:50:08.920 SingleUserNotebookApp log:158] 200 GET /user/user_z9se32srw0/api/terminals?_=1549899121462 (user_z9se32srw0@134.28.117.8) 0.98ms
[D 2019-02-11 15:50:08.936 SingleUserNotebookApp auth:778] Allowing whitelisted Hub user user_z9se32srw0
[I 2019-02-11 15:50:08.939 SingleUserNotebookApp log:158] 200 GET /user/user_z9se32srw0/api/contents?type=directory&_=1549899121463 (user_z9se32srw0@134.28.117.8) 2.91ms
[D 2019-02-11 15:50:12.316 SingleUserNotebookApp kernelmanager:392] activity on d271a796-ff34-4c5b-a96e-fa0897bee91e: status
[D 2019-02-11 15:50:12.318 SingleUserNotebookApp kernelmanager:392] activity on d271a796-ff34-4c5b-a96e-fa0897bee91e: execute_input
[I 2019-02-11 15:50:14.370 SingleUserNotebookApp restarter:110] KernelRestarter: restarting kernel (1/5), keep random ports
kernel d271a796-ff34-4c5b-a96e-fa0897bee91e restarted
[D 2019-02-11 15:50:14.372 SingleUserNotebookApp manager:257] Starting kernel: ['/opt/conda/bin/python', '-m', 'ipykernel_launcher', '-f', '/home/jovyan/.local/share/jupyter/runtime/kernel-d271a796-ff34-4c5b-a96e-fa0897bee91e.json']
[D 2019-02-11 15:50:14.377 SingleUserNotebookApp connect:542] Connecting to: tcp://127.0.0.1:41538
[D 2019-02-11 15:50:14.884 SingleUserNotebookApp kernelmanager:392] activity on d271a796-ff34-4c5b-a96e-fa0897bee91e: status
[D 2019-02-11 15:50:14.885 SingleUserNotebookApp kernelmanager:392] activity on d271a796-ff34-4c5b-a96e-fa0897bee91e: status
[D 2019-02-11 15:50:15.061 SingleUserNotebookApp auth:778] Allowing whitelisted Hub user user_z9se32srw0
[D 2019-02-11 15:50:15.063 SingleUserNotebookApp log:158] 304 GET /user/user_z9se32srw0/static/base/images/favicon-notebook.ico (user_z9se32srw0@134.28.117.8) 4.71ms
```
</details>

**JupyterHub**
<details>
[I 2019-02-11 15:50:05.338 JupyterHub log:158] 302 GET / -> /hub (@134.28.206.130) 1.82ms
[I 2019-02-11 15:50:05.342 JupyterHub log:158] 302 GET /hub -> /hub/ (@134.28.206.130) 1.12ms
[I 2019-02-11 15:50:05.344 JupyterHub log:158] 302 GET /hub/ -> /hub/login (@134.28.206.130) 0.46ms
[I 2019-02-11 15:50:05.347 JupyterHub log:158] 200 GET /hub/login (@134.28.206.130) 1.48ms
[I 2019-02-11 15:50:08.923 JupyterHub log:158] 200 GET /hub/api/authorizations/token/[secret] (user_z9se32srw0@172.27.0.5) 16.76ms
15:52:45.901 - info: [ConfigProxy] 200 GET /api/routes
[I 2019-02-11 15:52:45.914 JupyterHub proxy:301] Checking routes
</details>

**Comment by 1kastner** [comment]
*The JupyterHub Dockerfile*
```
FROM jupyterhub/jupyterhub:0.9.1
RUN apt-get upgrade -y
ADD jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py
RUN pip install dockerspawner
```


*The Notebook File*
```
FROM jupyter/scipy-notebook
USER root
RUN sudo apt-get upgrade -y
USER $NB_UID
RUN python3 -m pip install --no-cache jupyterhub==0.9.1
COPY ./mystuff /home/jovyan/
USER root
RUN chown -R jovyan:users /home/jovyan/
USER $NB_UID
```

In "mystuff" there are some prepared files and in the config I configure that it uses dockerspawner.
It worked with normal code and with folium in the past. Now it is the first time for me to try plotting on the server.

**Comment by 1kastner** [comment]
@minrk do you have some place in mind where I could get meaningful logs for something like a traceback?

**Comment by minrk** [comment]
The relevant logs should be in `docker logs jupyter-<username>`. I'd recommend updating at least to latest-stable (0.9.4).

If things are going wrong and not showing up in the logs, you might start a terminal with ipython and try importing there. That might be the issue.

**Comment by 1kastner** [comment]
Well, it was an issue on 0.9.4 as well, I tried both. I will try the ipython console somewhen soon.

**Comment by 1kastner** [comment]
I tried to execute the same code in two different ways, first from the python command line through ssh and second from the ipython shell through the terminal interface which the web interface provides. Both times I got the same error.

```
jovyan@0a5922c8e6a5:~$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
port numpy as np
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2*np.pi*t)
plt.plot(t, s)>>> import numpy as np
>>> t = np.arange(0.0, 2.0, 0.01)
>>> s = 1 + np.sin(2*np.pi*t)
>>> plt.plot(t, s)
Illegal instruction (core dumped)
jovyan@0a5922c8e6a5:~$
```

and 

```
jovyan@0a5922c8e6a5:~$ ipython
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import matplotlib.pyplot as plt
   ...: import numpy as np
   ...: t = np.arange(0.0, 2.0, 0.01)
   ...: s = 1 + np.sin(2*np.pi*t)
   ...: plt.plot(t, s)
Illegal instruction (core dumped)
jovyan@0a5922c8e6a5:~$
```

So in fact it rather seems to be an issue of the `jupyter/scipy-notebook` image.
The only issue is that I can not reconstruct this error locally.

**Comment by 1kastner** [comment]
Thanks for the hint, @minrk. As the error can be reproduced in python and ipython on the same machine, it is in fact unrelated to the jupyterhub image. Therefore I close this conversation and continue somewhere else.

**Comment by anothershubham** [comment]
Refer https://stackoverflow.com/questions/69786885/after-conda-update-python-kernel-crashes-when-matplotlib-is-used
for the solution
