### ISSUE TITLE
Autoformat with black?

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#2416]
I'm not a fan of style-checking in CI that requires human intervention, but auto-formatters like [black](https://pypi.org/project/black/) allow us to eliminate code style as a review point, even if the auto-formatter doesn't always make the best decisions. I think projects with style-enforcement are generally contributor-hostile, but projects with auto-formatting can eliminate contributor stress about "does my style match?"

The biggest problem with adopting an auto-formatter in an existing project is that it'll make one huge PR that's not meaningful, which is a bit of a mess for version control history and understanding the code base. If we adopt black, I would aim to enable the skip-string-normalization feature, since that would cause the biggest churn (and I frankly happen to disagree with the design of black there).

What do folks think? If there's interest, I can investigate picking up https://pre-commit.com which offers some pretty handy hooks for quick fixes.

/cc @willingc

**Comment by betatim** [comment]
On a new project I started with:
```yaml
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
language_version: python3.6
```
as my pre-commit config. I think it will only check files which are involved in the commit. Which means you could restyle files "as you touch them". One downside is that I can't see how to configure it so that I get two commits: actual changes and reformatted for every commit I make that requires reformatting. That would be cool as a way to slowly transition the code base.

`black` does some "crazy" things in terms of formatting but the consistency is worth it.

**Comment by willingc** [comment]
> `black` does some "crazy" things in terms of formatting but the consistency is worth it.

We've been using black on Papermill, Scrapbook and Bookstore over at nteract. You can override how black handles quotes if desired. We've used this for 6 months with no issues. https://github.com/nteract/papermill/blob/master/pyproject.toml

In general, I would have a check on your dev system as well as on CI.

**Comment by willingc** [comment]
Instead of one big commit, I would run passing tests. Then, blacken the test files. Run cleanly. Then a commit for source. Alternatively, you run as the code is touched, but that is a bit more of a pain.

**Comment by betatim** [comment]
> We've used this for 6 months with no issues.

Nods, I've never had any syntax errors or anything like that. The "crazy" was in reference to what my inner formatting bike shedder thinks ;)

**Comment by minrk** [comment]
Since black guarantees ast consistency, I'm not at all worried about errors.

I think one big reformat commit is probably better than several slightly-less-big changes as files are touched. That gives us all the same problems as the singe change, just occurring at different points in time for different files. As you pointed out, reformat shouldn't be in the same commit as 'actual' changes, so I think a dedicated "nothing to see here" reformat step is probably the way to go so that each subsequent commit is only reformatting the new code instead of the whole file.

I *really* wish that black had something like [pep8radius](https://pypi.org/project/pep8radius/) (or that pep8radius worked at all anymore). I think that's the only really good way to do a slow transition.

**Comment by minrk** [comment]
#2418 adopts black via pre-commit (and a few other auto-fixes). Setting `skip-string-normalization = true` greatly reduces the churn
