### ISSUE TITLE
Disable webserver logging jupyterhub

### ISSUE THREAD

**Issue by palashSharma17** [jupyterhub/jupyterhub#2419]
How to disable webserver logging in jupyterhub. Also is it possible to reduce retention time.

**Comment by minrk** [comment]
What do you mean by retention time? JupyterHub doesn't retain any logs at all, it logs to stderr. It is up to your deployment if it captures logs to decide how to retain them.

You can set the minimal log-level with `jupyterhub --log-level=0` which will log very little (no errors or requests will be logged)
