### ISSUE TITLE
Add Privacy disclaimer to login page

### ISSUE THREAD

**Issue by palashSharma17** [jupyterhub/jupyterhub#2420]
How can I add a privacy disclaimer to my jupyterhub login page.

**Comment by minrk** [comment]
You can customize the `login.html` [template as described in the docs](https://jupyterhub.readthedocs.io/en/stable/reference/templates.html). The original file is [here](https://github.com/jupyterhub/jupyterhub/blob/0.9.4/share/jupyterhub/templates/login.html) for reference.
