### ISSUE TITLE
c.Authenticator.delete_invalid_users option is recommened, but doesn't work with PAMAuthenticator

### ISSUE THREAD

**Issue by mattvw** [jupyterhub/jupyterhub#2421]
**Describe the bug**
I am seeing this in the logs when JupyterHub is finding users in the db that are no longer valid on the system:

```
Feb 16 11:00:26 hostname JupyterHub: [E 2019-02-16 11:00:26.280 JupyterHub app:1220] Error adding user XXXXX already in db
Feb 16 11:00:26 hostname JupyterHub: Traceback (most recent call last):
Feb 16 11:00:26 hostname JupyterHub: File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/app.py", line 1218, in init_users
Feb 16 11:00:26 hostname JupyterHub: await maybe_future(self.authenticator.add_user(user))
Feb 16 11:00:26 hostname JupyterHub: File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/auth.py", line 525, in add_user
Feb 16 11:00:26 hostname JupyterHub: raise KeyError("User %s does not exist." % user.name)
Feb 16 11:00:26 hostname JupyterHub: KeyError: 'User XXXXX does not exist.'
Feb 16 11:00:26 hostname JupyterHub: [W 2019-02-16 11:00:26.280 JupyterHub app:1232]
Feb 16 11:00:26 hostname JupyterHub: You can set
Feb 16 11:00:26 hostname JupyterHub: c.Authenticator.delete_invalid_users = True
Feb 16 11:00:26 hostname JupyterHub: to automatically delete users from the Hub database that no longer pass
Feb 16 11:00:26 hostname JupyterHub: Authenticator validation,
Feb 16 11:00:26 hostname JupyterHub: such as when user accounts are deleted from the external system
Feb 16 11:00:26 hostname JupyterHub: without notifying JupyterHub.
```

However, it appears that the config option c.Authenticator.delete_invalid_users does not actually exist (at least for the PAMAuthenticator Authenticator that we are using). When I try to set that option in the config and restart JupyterHub, I get this error message:

```
Feb 16 11:47:11 hostname JupyterHub: [W 2019-02-16 11:47:11.141 JupyterHub configurable:168] Config option `delete_invalid_users` not recognized by `PAMAuthenticator`.
```

Is this something that can be made to work for PAMAuthenticator? I think this would be very useful to have as an option!

The only way that I know of to get rid of these messages currently is to manually delete the invalid users through the admin page of the web UI.

At the very least, it might make sense to not have that message shown about the c.Authenticator.delete_invalid_users when PAMAuthenticator is in use for the Authenticator.

Background:
We use PAMAuthenticator, as the system JupyterHub is installed on is set up to use our external authentication systems through PAM. The system passwd file contains all the valid users with accounts in the external authentication systems and gets updated whenever user accounts are added or removed from the external authentication systems.
So, whenever users get removed, we see the messages above for all the invalid users. It would be nice if these invalid users were just removed from the database automatically (with some kind of message in the logs for each user removed) using the c.Authenticator.delete_invalid_users option.

**Expected behavior**
I expect the c.Authenticator.delete_invalid_users config option to work if it is recommended to use in the log messages. I would very much like the c.Authenticator.delete_invalid_users config option to work as advertised when PAMAuthenticator is used for the Authenticator as well.

**JupyterHub Server:**
 - OS: RHEL 7
 - Version: 0.9.2; same thing with 0.9.4 as well

Let me know if there are any other details that I can provide!

Thanks!

**Comment by ccravens** [comment]
+1

**Comment by gabefair** [comment]
+1 Thanks

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
