### ISSUE TITLE
how can set the font/windoes sizes of terminal

### ISSUE THREAD

**Issue by datalee** [jupyterhub/jupyterhub#2423]
the font size is so big,i want to small it,can you help me ?thks.

**Comment by 00Kai0** [comment]
@datalee , show me a screenshot about what you want to change.

**Comment by datalee** [comment]
> @datalee , show me a screenshot about what you want to change.

Can terminal be displayed in full screen?
like this
![default](https://user-images.githubusercontent.com/13651873/52982663-4bfe4c00-3422-11e9-8dea-98f78dbdb8e9.PNG)

**Comment by datalee** [comment]
@00Kai0 hi,我怕表达不清楚,直接说中文吧.就是想把terminal的窗口调成全屏显示,窗口有点小 并且字体有点大,字体大小也可以调整吗?谢谢

**Comment by 00Kai0** [comment]
@datalee Hi,这个问题应该在[jupyternotebook](https://github.com/jupyter/notebook)提，jupyter terminal我用的也不多，好像没有这样的功能。不过你可以尝试一下定义一个custom.css来改变他的样式。
希望对你有用。
