### ISSUE TITLE
Unvalidated redirect after spawn form

### ISSUE THREAD

**Issue by dmarth** [jupyterhub/jupyterhub#2424]
**Description**
In case you have multiple profiles configured in kubespawner, a selection dialog is displayed in JupyterHub. Additionally, the parameter `next` is part of the URL. This parameter is used to redirect the user to the notebook once it is started.

Currently it is only checked whether the parameter starts with a slash:
https://github.com/jupyterhub/jupyterhub/blob/fec3d959f2210a87b301fd42c277dd5fbbfb88ba/jupyterhub/handlers/pages.py#L164
However, this is not sufficient to prevent a redirect to an external domain. For example, a protocol-relative URL bypasses this check.

**To Reproduce**
1. Start up JupyterHub with multiple profiles (e.g. via `c.KubeSpawner.profile_list`)
2. Visit `/hub/spawn?next=%2f%2fjupyter.org` on your JupyterHub instance
3. Spawn a profile

**Expected behavior**
JupyterHub should not allow a redirect to an external domain. Instead it should either show an error message or construct an absolute URL using the correct domain and process it as usual.

**Environment**
 - Browser: Tested on Firefox 65, Chrome 72
 - JupyterHub version: Current master (fec3d959f2210a87b301fd42c277dd5fbbfb88ba)
 - kubespawner version: 0.10.1

**Comment by minrk** [comment]
This is fixed in master by the reworking of redirects in #2435
