### ISSUE TITLE
Configuration of pyspark with jupyter on CDH5.13

### ISSUE THREAD

**Issue by skhadrao** [jupyterhub/jupyterhub#2425]
Hello,

I'have installed CDH5.13 using Cloudera Manager. I alos installed SPARK2.2 using CSD parcels.

Now I just installed python3.5 on all cluster nodes (hosts, 1 edge, 2 masters and 4 workers)

 I also installed jupyter on the edge node.

My question is about how to configure jupyter to use pyspark, cause until now I'm having issues with this one ?

Thanks

**Comment by skhadrao** [comment]
To complete the question above, I'm working on Linux rhel 7

I've installed python3.5 along python 2.7. I configured python35 to be default one on all the hosts of the cluster.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
