### ISSUE TITLE
Websocket connection failed on Apache reverse proxy setup

### ISSUE THREAD

**Issue by pkumar8789** [jupyterhub/jupyterhub#2426]
Went through issue #219 and related links but no success till yet.

I have a reverse proxy setup on Jupyterhub using Apache 2.4. The redirection to JupyterHUB url from Apache URL works fine but the internal Websocket connection after Kernel is created fails as it takes the Port from the Apache URL and not the redirected Port.

Apache URL: https://HOST_NAME:31000

JupyterHUB redirect URL: https://HOST_NAME:8000

but websocket connection is attempted at wss://HOST_NAME:31000 which fails. The URL redirection doesn't happen for websocket.

Apache Conf:

Listen HOST_NAME:31000

ServerName HOST_NAME

RewriteEngine On
RewriteCond %{HTTP:Connection} Upgrade [NC]
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteRule /(.*) ws://HOST_NAME:8000/$1 [P,L]

<Location ~ "/(user/[^/]*)/(api/kernels/[^/]+/channels|terminals/websocket)/?">
ProxyPreserveHost on
# proxy to JupyterHub
ProxyPass https://HOST_NAME:8000/
ProxyPassReverse ws://HOST_NAME:8000/
Note: HOST_NAME is the server on which JupyterHub is running. Apache is also running on the same server.

While trying to open Notebook session, I see Kernel Created.

Starting websockets: wss://HOST_NAME:31000/user/d12333/api/kernels/d34343/channels?session...failing to connect. if the URL re-direction for websocket uses 8000 port then this should work.

But not able to configure the redirect through apache cnfiguration.

proxy_wstunnel_module, proxy_http_module and proxy_module are all enabled.
console

**Comment by pkumar8789** [comment]
Issue#219 has screenshot of error attached from console log

**Comment by knkski** [comment]
I had a similar issue (though with nginx), and upgrading from the 0.9.4 to 1.0.0.dev Docker image fixed things for me.

**Comment by enricotagliavini** [comment]
Did you try also bypassing your apache reverse proxy? I just tried 0.9.4 and I have exactly the same error, even when totally bypassing the proxy and connecting to http://localhost:8000/

**Comment by shorif2000** [comment]
is there update on this i get same problem https://stackoverflow.com/questions/70669059/voila-static-files-not-loading-via-reverse-proxy-in-apache
