### ISSUE TITLE
Last RTD build was 2 month ago.

### ISSUE THREAD

**Issue by Carreau** [jupyterhub/jupyterhub#2427]
Readthe docs webhook need to be configures manually since late 2018. 

This likely affect all projects.

**Comment by Carreau** [comment]
In RTD: 
 - go to admin tab
 - integration section (4th from bottom)
 - Click add integration
 - "right click "copy link address" 
 - go to GH project setting, "webhook" tab. 
 - past url 
    - let me select individual events: 
      - Branch or tag deletion
      - Branch or tag creation
      - Pushes. 

- Trigger manual build on RTD to get things up to date.

**Comment by Carreau** [comment]
See https://docs.readthedocs.io/en/latest/webhooks.html

**Comment by Carreau** [comment]
Now the theme is broken, but I don't knwo when it was broken: 
![screen shot 2019-02-20 at 7 18 39 pm](https://user-images.githubusercontent.com/335567/53141286-5e70a680-3544-11e9-9d26-f1b2acdf3939.png)

**Comment by Carreau** [comment]
The API is also not generated anymore: 

![screen shot 2019-02-20 at 7 20 01 pm](https://user-images.githubusercontent.com/335567/53141336-8d871800-3544-11e9-93b7-829690de2fc5.png)

**Comment by willingc** [comment]
Yes, all repos will need to be updated with a webhook since GitHub got rid of services late last year.

**Comment by betatim** [comment]
Can we automate as part of the CI that runs on `master` a check for "RTD is up-to-date"?

**Comment by betatim** [comment]
Also: @Carreau thanks for reporting this and noticing!

**Comment by Carreau** [comment]
All should be fixed for hub. 
Maybe not for subproject of the org, so I'll let that open for now.

**Comment by consideRatio** [comment]
@Carreau I made a list in https://github.com/jupyterhub/oauthenticator/issues/347 to track this, and since its tracked there I'll go ahead and close it here.
