### ISSUE TITLE
jupyterhub kubeSpawner get ip address of notebook server only at start phase, but this address can changed in k8s, how to let jupyterhub know the change

### ISSUE THREAD

**Issue by serlina** [jupyterhub/jupyterhub#2430]
Hi! Thanks for using JupyterHub.

If you are reporting an issue with JupyterHub, please use the [GitHub issue](https://github.com/jupyterhub/jupyterhub/issues) search feature to check if your issue has been asked already. If it has, please add your comments to the existing issue.

****Describe the bug**
Spawner get ip address of notebook server only at start phase, but this address can changed in k8s----we met the issue recently,   jupyterhub+ kubespawner(k8s) + singleuser notebook servers(pod),  for unknow reason, the user's notebook pod restarted in k8s, and the pod IP address changed, but jupyterhub don't know the change, it saved the old IP address to connnet to the pod, and failed to connnet, raise 503 error
the pod 's IP changed from 172.*.*.244 to 172.*.*.245

so my question is:
1,  why jupyterhub(postgres databse) saved notebook pod's ip into database, instead of pod's hostname
2,  when the issue happened, how to let jupyterhub know the issue, and update its databse about the POD's IP**

**Comment by serlina** [comment]
looking forward to your reply, thank you

**Comment by serlina** [comment]
is there a way,  jupyterhub spawn user's notebook pod and expose the pod to service in the same time  ? while, the pod ip changed, but its service IP don't change.  is there a way, thank you

**Comment by minrk** [comment]
Thanks for the issue! This is an issue for KubeSpawner not routing to pods that have stopped and restarted somewhere else, currently open at https://github.com/jupyterhub/kubespawner/issues/223

I'm going to close this as a duplicate, but please feel free to post more info there. The gist is that a pod that stopped should not ever be restarted or relocated by kubernetes, it should register with the Hub as failed and the Hub should be responsible for restarting it.
