### ISSUE TITLE
singleuser without group

### ISSUE THREAD

**Issue by user919lx** [jupyterhub/jupyterhub#2437]
I want to create a public workspace for users to share notebook.And I found [service-notebook](https://github.com/jupyterhub/jupyterhub/tree/master/examples/service-notebook).
But single-user need to set a group in jupyterhub_config.py. I can't write all username into  config file.It's too long.

How to run a single-user without group authentication or set all user to a group conveniently?

**Comment by minrk** [comment]
Hm. The `HubOAuthenticated` mixin will allow any user if `self.allow_all` is True. I think there isn't currently an easy way to enable this on the command-line, but this entrypoint will do it:

```python
#!/usr/bin/env python
from jupyterhub import singleuser

if __name__ == '__main__':
    # configure singleuser to allow any visitor
    singleuser.HubAuthenticatedHandler.allow_all = True
    # invoke main singleuser entrypoint
    singleuser.main()
```

Then instead of `jupyterhub-singleuser` as the entrypoint, point it at this script.

**Comment by user919lx** [comment]
Thank you! It work fine.
