### ISSUE TITLE
Jupyterhub could use more logging for python crashes

### ISSUE THREAD

**Issue by joequant** [jupyterhub/jupyterhub#2445]
Hi! Thanks for using JupyterHub.

If you are reporting an issue with JupyterHub, please use the [GitHub issue](https://github.com/jupyterhub/jupyterhub/issues) search feature to check if your issue has been asked already. If it has, please add your comments to the existing issue.

**Describe the bug**

If jupyterhub loads tensorflow on a non-AVX machine, then the spawner will crash with a 500 error with status=0.  This is because python issues an illegal instruction then exits.  The issue is that this crash happens sliently and is not logged which makes it difficult to debug.

The bug is a tensorflow bug, but jupyterhub could use better error trapping and logging.

**To Reproduce**

Install an extension that requires importing tensorflow such as jupyterlab_tensorflow
Run the system on a machine that does not have AVX instructions
Python will crash on load and jupyterhub will issue a 500 [status=0] error

**Expected behavior**

If python crashes because of an illegal error or segmentation fault there should be better logging.  In particular it would be nice if jupyterub caught the signal and then logged it.

**Desktop (please complete the following information):**
 - OS:  linux running a machine without AVX instructions
 - Browser firefox
 - Version 

**Additional context**
- Having the spawner exist with status=0 indicates that python has crashed, and it might be useful to put the possibility that they are running tensorflow on a non-AVX machine in troubleshooting.  There are versions of tensorflow compiled on non-AVX.
- This is a tensorflow bug, but there is some room for better error handling.  In particularly mentioning that python has crashed and that this may be due to a bad module will help
- Another thing that would be useful is debug output that describes the modules as they are loaded.  That way it would be easier to find this and other extension related bugs

**Comment by manics** [comment]
I think this would have to be handled in Jupyter notebook or Jupyter Lab
