### ISSUE TITLE
Kernel hangs with tornado 6.0.1

### ISSUE THREAD

**Issue by daliati** [jupyterhub/jupyterhub#2451]
I am not sure if the issue is with jupyterhub, tornado, or configurable-http-proxy (probably the combination of those) but if you run into a hanging kernel issue - this is a solution:

The new tornado 6.0.1 makes the kernel hang forever in "starting the kernel". Any kernel - ipython, R. 
Downgrading tornado to 5.1.1 resolves the issue.

Jupyterhub 0.9.4

**Comment by betatim** [comment]
It seems like there is an issue in the notebook: https://github.com/jupyter/notebook/issues/2664

I think that issue is the one to track and we should close this one.

**Comment by minrk** [comment]
Yup. This is fixed in notebook 5.7.5
