### ISSUE TITLE
Explicitly declare content-language to help browsers avoid guessing language wrong?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#2453]
;D Is it only me or is this due to some metadata from JH?

![admin-is-from-norway](https://user-images.githubusercontent.com/3837114/53913352-74f62200-405b-11e9-989e-2dc3a9df9021.gif)

**Comment by mdivk** [comment]
Interesting, I do not see that here, I am from Canada. The page's source here is like below, what about yours?

```
<head>
--
  | <meta charset="utf-8">
  |  
  | <title>JupyterHub</title>
  | <meta http-equiv="X-UA-Compatible" content="chrome=1">


```

**Comment by mdivk** [comment]
Here is some discussion:
[https://stackoverflow.com/questions/2467454/why-does-chrome-incorrectly-determine-page-is-in-a-different-language-and-offer/3130857#3130857](https://stackoverflow.com/questions/2467454/why-does-chrome-incorrectly-determine-page-is-in-a-different-language-and-offer/3130857#3130857)

**Comment by minrk** [comment]
I'm guessing it's picking it up based on the fact that your email address is a large fraction of the text on the admin page. Are there more swedish.name@sandvik.com addresses?

Maybe we should set the `<meta http-equiv="Content-Language" content="en">` in the header

**Comment by manics** [comment]
Still an issue? Or shall we close this?

**Comment by consideRatio** [comment]
Yes but perhaps an edge case. Hmmm what do you think - should we pin our content-language or not? If the user provides a lot of customized templates in another language, then it suddenly would been better not to pin the content language.

**Comment by manics** [comment]
I'm inclined to ignore it, as you point out a template might be in a different language, and in future we'll hopefully eventually provide translation of all JupyterHub strings.

**Comment by consideRatio** [comment]
@manics :+1: ! Thank you for your extensive triage work!!!
