### ISSUE TITLE
Confusing warning: Cookie secret is N bytes. It should be 32.

### ISSUE THREAD

**Issue by robnagler** [jupyterhub/jupyterhub#2456]
**Describe the bug**
Getting this warning: `Cookie secret is 128 bytes. It should be 32.` 

However, app.py does not truncate the cookie_secret value, but just passes it on.

It's a confusing warning for people who try to keep their configuration up to date, i.e. eliminating warnings. If you have a longer key, it's just fine. According to [RFC2104](https://tools.ietf.org/html/rfc2104.html): "The key for HMAC can be of any length (keys longer than B bytes are first hashed using H)."

It [could be argued](https://crypto.stackexchange.com/a/34866) that a longer key increases entropy.

**To Reproduce**
c.JupyterHub.cookie_secret = binascii.a2b_hex('a' * 256)

**Expected behavior**
I don't expect a warning.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**

- Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.
- Running in `--debug` mode can also be helpful for troubleshooting.

**Comment by minrk** [comment]
It is indeed safe and harmless for it to be 128 bytes. The warning is because the digest is only 32 bytes, so a bigger key doesn't really help, provided the 32B key has full-entropy, as described in your link:

> if the key is full-entropy, there is no strong argument to use a key of more than 32 bytes.

We can soften the warning to point out that there isn't much point to a key larger than 32B but no harm done. The currently warning came from my own understanding that bigger key == better, but learning that a key bigger than the digest is not actually helping anything.

**Comment by robnagler** [comment]
The problem is that once you have a longer key, you can't git rid of the warning unless you shorten the key, which is non-obvious. The key we have is from a while ago, when the documentation recommended 128 bytes (I believe). Providing an upgrade path for people would be nice, e.g. `hashlib.sha256(old_key)`. The problem is that it reaches deep inside the layers of abstraction (assumes you know cookie_secret is used by hmac with sha256).

Just FTR, here's validation it works: 

```py
import hashlib
import hmac
old_key = b'a' * 128
x = hashlib.sha256()
x.update(old_key)
new_key = x.digest()
msg = b'a quick brown fox jumps over the lazy dog'
new = hmac.new(new_key, msg, digestmod=hashlib.sha256).digest()
old = hmac.new(old_key, msg, digestmod=hashlib.sha256).digest()
assert new == old
```

**Comment by minrk** [comment]
That's super useful! I'll see what cli-pipey command does the same thing and add that to the warning for how to replace the key with its sha256 hexdigest
