### ISSUE TITLE
Kernel's won't connect under corporate proxy from remote.

### ISSUE THREAD

**Issue by Bartket** [jupyterhub/jupyterhub#2459]
I have Jupyterhub server running on VM(Ubuntu Server 18.04) hosted by Windows 7. I've set it up to use SSL encryption signed by me using OpenSSL. When I connect from the remote connection I can log in but I can't connect to any kernel. When I turn off my company proxy settings(which gives me access to open internet) it starts to work. What's interesting is that this issue persists on Chrome and Firefox but does not happen on Internet Explorer 11 with proxy enabled.

I've tried meddling with proxy exceptions to my server with multiple ports to no effect.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
