### ISSUE TITLE
Cannot run Jupyterhub in background

### ISSUE THREAD

**Issue by thongnnguyen** [jupyterhub/jupyterhub#2461]
Hi,
I just did an upgrade for my conda, hub and lab. Now I have `conda 4.6.8` and

```
jupyter                   1.0.0                    py37_7
jupyter_client            5.2.4                    py37_0
jupyter_console           6.0.0                    py37_0
jupyter_core              4.4.0                    py37_0
jupyterhub                0.9.4                 py37_1000    conda-forge
jupyterlab                0.35.3                   py37_0
jupyterlab_launcher       0.11.2           py36h28b3542_0
jupyterlab_server         0.2.0                    py37_0
```
I follow [this](https://jupyterhub.readthedocs.io/en/stable/reference/config-sudo.html) and manage to run the hub without root, multiple user can log in to their lab workspace.

The problem now is I cannot run

```
jupyterhub &
```

in a tmux session. As soon as I try to, it kills my tmux session. I tried without tmux, it even kills my ssh session and log me out of the server.

I also tried to run Hub as service with systemd (Ubuntu) following [this wiki](https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service). But I got an error like [this comment](https://github.com/jupyterhub/jupyterhub/issues/317#issuecomment-308684135). However, I have conda path (/opt/anaconda3/bin) in `PATH`, so `configurable-http-proxy` and `jupyterhub` definitely can be found.

Any help is appreciated.

Thank you

**Comment by mgnfcnt** [comment]
I am running jupyterhuc at background with following command : 

nohup jupyterhub > /dev/null 2>&1 &

**Comment by thongnnguyen** [comment]
> I am running jupyterhuc at background with following command :
> 
> `nohup jupyterhub > /dev/null 2>&1 &`

With nohup I can keep hub alive now. Thanks much.
