### ISSUE TITLE
Redirect loop detected Jupyterhub 0.9.4 using swarmspawner

### ISSUE THREAD

**Issue by samagnew** [jupyterhub/jupyterhub#2468]
I have spent quite some time on this but I can't get further.

I have a Docker swarm stack launching my CentOS7 based docker image with JupyterHub as well as a client for our AD (SSSD via LDAP). Also in the stack is the Configurable-HTTP-Proxy image and port 8000 presented externally on 8889. In the config file we are starting services using our CentOS7 based notebook image.

Jupyterhub starts and allows user to authenticate. User gets page to start his server. Starting server page shows and service is spawned and container started for user's notebook server. But the user never gets access to his spawned notebook server because we get continuous redirect loops.

Jupyterhub is 0.9.4 on jupyterhub and notebook images. dockerspawner is 0.1.0 after I found there was a parsing error in 0.1.1. configurable-http-proxy is 4.0.1.

# Stack file:
version: '3.5'
   
services:
  proxy:
    env_file: .env
    image: jupyterhub/configurable-http-proxy:4.0.1
    networks:
      - jupyterhub
    # expose the proxy to the world
    ports:
      - "8889:8000"
    command:
      - configurable-http-proxy
      - '--error-target'
      - 'http://hub/hub/error'
  hub:
    env_file: .env
    image: registry.qatar-med.cornell.edu:5000/ac-jupyterhub:2019-03-07
    environment:
      DOCKER_NETWORK_NAME: jupyter_jupyterhub
      DOCKER_NOTEBOOK_IMAGE: registry.qatar-med.cornell.edu:5000/ac-jupyter-pyspark:2019-03-07
      JUPYTER_ENABLE_LAB: 'True'
    hostname: jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/system/docker/dockerised/jupyter/var/log:/var/log
      - /data/backups/jupyter:/backups
      - /data/home:/user
    # Ensure Hub and Notebook servers are on the same network
    networks:
      - jupyterhub
    #Ensure that we execute on a Swarm manager
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
   
networks:
  jupyterhub:

# Config on jupyterhub:
import os
import errno
import stat
import subprocess
import logging
c.JupyterHub.log_level = logging.DEBUG
c.DockerSpawner.debug = True
c.ConfigurableHTTPProxy.should_start = False
c.ConfigurableHTTPProxy.api_url = 'http://proxy:8001'
 
c = get_config() # noqa
 
pwd = os.path.dirname(__file__)
notebook_dir = os.environ.get('NOTEBOOK_DIR') or '/home/jovyan/work'
jupyter_user = os.environ.get('JUPYTERHUB_USER')
notebook_image = os.environ.get('DOCKER_NOTEBOOK_IMAGE')
docker_network = os.environ.get('DOCKER_NETWORK_NAME')
c.JupyterHub.hub_connect_ip = 'hub'
c.JupyterHub.hub_ip = '0.0.0.0'
c.JupyterHub.spawner_class = 'dockerspawner.SwarmSpawner'
c.Authenticator.admin_users = {
  'saa2012',
  'gms2003'
}
c.SwarmSpawner.network_name = docker_network
c.SwarmSpawner.start_timeout = 60 * 5
c.DockerSpawner.host_ip = '0.0.0.0'
c.DockerSpawner.use_internal_ip = True
c.DockerSpawner.hub_ip_connect = c.JupyterHub.hub_ip
 
mounts = [{'type': 'bind',
           'source': '/tmp',
           'target': notebook_dir},
          {'type': 'bind',
           'source': '/data/home',
           'target': '/home'},
          {'type': 'bind',
           'source': '/data',
           'target': '/data'}]
c.SwarmSpawner.extra_container_spec = {
    'args': ['/usr/local/bin/start-singleuser.sh'],  # (string or list)
    'image': 'registry.qatar-med.cornell.edu:5000/ac-jupyter-pyspark:2019-03-07',
    'mounts': mounts

# My modified version of start-singleuser.sh:
set -e
    
if [[ "$NOTEBOOK_ARGS $@" != *"--ip="* ]]; then
  NOTEBOOK_ARGS="--ip=0.0.0.0 $NOTEBOOK_ARGS"
fi  
    
if [ ! -z "$JUPYTERHUB_PORT" ]; then
  NOTEBOOK_ARGS="--port=$JUPYTERHUB_PORT $NOTEBOOK_ARGS"
fi  
if [ ! -z "$JUPYTERHUB_USER" ]; then
  NOTEBOOK_ARGS="--user=$JUPYTERHUB_USER $NOTEBOOK_ARGS"
fi  
if [ ! -z "$JUPYTERHUB_COOKIE_NAME" ]; then
  NOTEBOOK_ARGS="--cookie-name=$JUPYTERHUB_COOKIE_NAME $NOTEBOOK_ARGS"
fi  
if [ ! -z "$JUPYTERHUB_BASE_URL" ]; then
  NOTEBOOK_ARGS="--base-url=$JUPYTERHUB_BASE_URL $NOTEBOOK_ARGS"
fi  
if [ ! -z "$JUPYTERHUB_HUB_PREFIX" ]; then
  NOTEBOOK_ARGS="--hub-prefix=$JUPYTERHUB_HUB_PREFIX $NOTEBOOK_ARGS"
fi  
if [ ! -z "$JUPYTERHUB_HUB_API_URL" ]; then
  NOTEBOOK_ARGS="--hub-api-url=$JUPYTERHUB_HUB_API_URL $NOTEBOOK_ARGS"
fi  
if [ ! -z "$JUPYTER_ENABLE_LAB" ]; then
  NOTEBOOK_BIN="/opt/conda/bin/jupyter-labhub"
else
  NOTEBOOK_BIN="/opt/conda/bin/jupyterhub-singleuser --debug"
  [ -f /etc/supervisord.d/jupyter.ini ] && rm /etc/supervisord.d/jupyter.ini
  /opt/conda/bin/supervisord -c /etc/supervisord.conf
  sleep 10
  JUPYTERHUB_USER_UID=$(id -u $JUPYTERHUB_USER)
  JUPYTERHUB_USER_GID=$(id -g $JUPYTERHUB_USER)
  JUPYTERHUB_USER_HOME=$(eval echo ~${JUPYTERHUB_USER})
  #NOTEBOOK_DIR=${JUPYTERHUB_USER_HOME}/work
  if [ ! -z "$NOTEBOOK_DIR" ]; then
    NOTEBOOK_ARGS="--notebook-dir='$NOTEBOOK_DIR' $NOTEBOOK_ARGS"
  else
    NOTEBOOK_DIR="${JUPYTERHUB_USER_HOME}/work"
    NOTEBOOK_ARGS="--notebook-dir='$NOTEBOOK_DIR' $NOTEBOOK_ARGS"
  fi
  export JUPYTERHUB_USER_UID JUPYTERHUB_USER_GID JUPYTERHUB_USER_HOME NOTEBOOK_DIR
fi  
    
. /usr/local/bin/start.sh $NOTEBOOK_BIN $NOTEBOOK_ARGS "$@"

# Jupyterhub logs on jupyterhub container:
[I 2019-03-12 13:00:32.818 JupyterHub log:158] 302 GET /hub/user/saa2012/?redirects=1 -> /hub/login?next=%2Fhub%2Fuser%2Fsaa2012%2F%3Fredirects%3D1 (@::ffff:10.255.0.8) 2.44ms
[I 2019-03-12 13:00:32.877 JupyterHub log:158] 200 GET /hub/login?next=%2Fhub%2Fuser%2Fsaa2012%2F%3Fredirects%3D1 (@::ffff:10.255.0.8) 46.68ms
[D 2019-03-12 13:00:32.895 JupyterHub log:158] 200 GET /hub/logo (@::ffff:10.255.0.8) 1.60ms
[D 2019-03-12 13:00:38.768 JupyterHub base:357] Setting cookie jupyterhub-session-id: {'httponly': True}
[D 2019-03-12 13:00:38.768 JupyterHub base:362] Setting cookie for saa2012: jupyterhub-hub-login
[D 2019-03-12 13:00:38.768 JupyterHub base:357] Setting cookie jupyterhub-hub-login: {'httponly': True, 'path': '/hub/'}
[I 2019-03-12 13:00:38.769 JupyterHub base:499] User logged in: saa2012
[I 2019-03-12 13:00:38.769 JupyterHub log:158] 302 POST /hub/login?next=%2Fhub%2Fuser%2Fsaa2012%2F%3Fredirects%3D1 -> /hub/user/saa2012/?redirects=1 (saa2012@::ffff:10.255.0.8) 512.79ms
[D 2019-03-12 13:00:38.845 JupyterHub user:190] Creating <class 'dockerspawner.swarmspawner.SwarmSpawner'> for saa2012:
[D 2019-03-12 13:00:38.914 JupyterHub base:603] Initiating spawn for saa2012
[D 2019-03-12 13:00:38.914 JupyterHub base:609] 0/100 concurrent spawns
[D 2019-03-12 13:00:38.914 JupyterHub base:612] 0 active servers
[W 2019-03-12 13:00:39.132 JupyterHub auth:642] Failed to open PAM session for saa2012: [PAM Error 14] Cannot make/remove an entry for the specified session
[W 2019-03-12 13:00:39.133 JupyterHub auth:643] Disabling PAM sessions from now on.
[D 2019-03-12 13:00:39.204 JupyterHub dockerspawner:557] Getting container 'jupyter-saa2012'
[I 2019-03-12 13:00:39.215 JupyterHub dockerspawner:564] Service 'jupyter-saa2012' is gone
[I 2019-03-12 13:00:39.238 JupyterHub dockerspawner:698] Created service jupyter-saa2012 (id: z8awe97) from image jupyterhub/singleuser:0.9
[I 2019-03-12 13:00:39.238 JupyterHub dockerspawner:721] Starting service jupyter-saa2012 (id: z8awe97)
[D 2019-03-12 13:00:39.312 JupyterHub spawner:851] Polling subprocess every 30s
[W 2019-03-12 13:00:39.397 JupyterHub utils:192] Failed to connect to http://jupyter-saa2012:8888/user/saa2012/ ([Errno -2] Name or service not known)
[W 2019-03-12 13:00:39.525 JupyterHub utils:192] Failed to connect to http://jupyter-saa2012:8888/user/saa2012/ ([Errno -2] Name or service not known)
[W 2019-03-12 13:00:39.631 JupyterHub utils:192] Failed to connect to http://jupyter-saa2012:8888/user/saa2012/ ([Errno -2] Name or service not known)
[W 2019-03-12 13:00:40.016 JupyterHub utils:192] Failed to connect to http://jupyter-saa2012:8888/user/saa2012/ ([Errno -2] Name or service not known)
[W 2019-03-12 13:00:40.111 JupyterHub utils:192] Failed to connect to http://jupyter-saa2012:8888/user/saa2012/ ([Errno -2] Name or service not known)
[D 2019-03-12 13:00:48.920 JupyterHub swarmspawner:137] Getting task of service 'jupyter-saa2012'
[D 2019-03-12 13:00:48.920 JupyterHub dockerspawner:557] Getting container 'jupyter-saa2012'
[D 2019-03-12 13:00:48.929 JupyterHub swarmspawner:126] Service z8awe97 status: {'ContainerStatus': {'ContainerID': '0a24c6b6c2be9e3d21c588667dc4eb2329e4ce831627eafd7c196fbe251dc00b',
                         'PID': 39182},
     'Message': 'started',
     'PortStatus': {},
     'State': 'running',
     'Timestamp': '2019-03-12T10:00:42.219974542Z'}
[W 2019-03-12 13:00:48.929 JupyterHub base:734] User saa2012 is slow to become responsive (timeout=10)
[D 2019-03-12 13:00:48.929 JupyterHub base:736] Expecting server for saa2012 at: http://jupyter-saa2012:8888/user/saa2012/
[I 2019-03-12 13:00:48.929 JupyterHub base:1056] saa2012 is pending spawn
[I 2019-03-12 13:00:48.935 JupyterHub log:158] 200 GET /hub/user/saa2012/?redirects=1 (saa2012@::ffff:10.255.0.8) 10154.54ms
[D 2019-03-12 13:00:49.058 JupyterHub log:158] 304 GET /favicon.ico (@::ffff:10.255.0.8) 1.10ms
[I 2019-03-12 13:00:53.687 JupyterHub log:158] 200 GET /hub/api (@10.0.9.5) 1.01ms
[D 2019-03-12 13:00:53.793 JupyterHub utils:188] Server at http://jupyter-saa2012:8888/user/saa2012/ responded with 302
[D 2019-03-12 13:00:53.793 JupyterHub _version:53] jupyterhub and jupyterhub-singleuser both on version 0.9.4
[I 2019-03-12 13:00:53.793 JupyterHub base:628] User saa2012 took 14.879 seconds to start
[I 2019-03-12 13:00:53.793 JupyterHub proxy:242] Adding user saa2012 to proxy /user/saa2012/ => http://jupyter-saa2012:8888
[D 2019-03-12 13:00:53.793 JupyterHub proxy:686] Proxy: Fetching POST http://proxy:8001/api/routes/user/saa2012
[I 2019-03-12 13:00:53.798 JupyterHub users:533] Server saa2012 is ready
[I 2019-03-12 13:00:53.798 JupyterHub log:158] 200 GET /hub/api/users/saa2012/server/progress (saa2012@::ffff:10.255.0.8) 4736.88ms
[D 2019-03-12 13:00:53.906 JupyterHub swarmspawner:137] Getting task of service 'jupyter-saa2012'
[D 2019-03-12 13:00:53.906 JupyterHub dockerspawner:557] Getting container 'jupyter-saa2012'
[D 2019-03-12 13:00:53.914 JupyterHub swarmspawner:126] Service z8awe97 status: {'ContainerStatus': {'ContainerID': '0a24c6b6c2be9e3d21c588667dc4eb2329e4ce831627eafd7c196fbe251dc00b',
                         'PID': 39182},
     'Message': 'started',
     'PortStatus': {},
     'State': 'running',
     'Timestamp': '2019-03-12T10:00:42.219974542Z'}
[W 2019-03-12 13:00:53.914 JupyterHub base:1101] Redirect loop detected on /hub/user/saa2012/?redirects=1
[I 2019-03-12 13:00:55.917 JupyterHub log:158] 302 GET /hub/user/saa2012/?redirects=1 -> /user/saa2012/?redirects=2 (saa2012@::ffff:10.255.0.8) 2097.97ms
[D 2019-03-12 13:01:09.323 JupyterHub swarmspawner:137] Getting task of service 'jupyter-saa2012'

# Logs on notebook container:
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  Setting CWD to /home/saa2012/
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  Executing the command: /opt/conda/bin/jupyterhub-singleuser --debug --notebook-dir='/data/home/saa2012/work' --base-url=/ --user=saa2012 --ip=0.0.0.0
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [D 2019-03-12 13:00:53.351 saa2012 application:177] Searching ['/home/saa2012', '/data/home/saa2012/.jupyter', '/opt/conda/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [D 2019-03-12 13:00:53.352 saa2012 application:555] Looking for jupyter_config in /etc/jupyter
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [D 2019-03-12 13:00:53.352 saa2012 application:555] Looking for jupyter_config in /usr/local/etc/jupyter
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [D 2019-03-12 13:00:53.352 saa2012 application:555] Looking for jupyter_config in /opt/conda/etc/jupyter
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [D 2019-03-12 13:00:53.352 saa2012 application:555] Looking for jupyter_config in /data/home/saa2012/.jupyter
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [D 2019-03-12 13:00:53.353 saa2012 application:555] Looking for jupyter_config in /home/saa2012
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [D 2019-03-12 13:00:53.354 saa2012 application:555] Looking for jupyter_notebook_config in /etc/jupyter
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [D 2019-03-12 13:00:53.354 saa2012 application:577] Loaded config file: /etc/jupyter/jupyter_notebook_config.py
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [D 2019-03-12 13:00:53.355 saa2012 application:555] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [D 2019-03-12 13:00:53.355 saa2012 application:555] Looking for jupyter_notebook_config in /opt/conda/etc/jupyter
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [D 2019-03-12 13:00:53.355 saa2012 application:577] Loaded config file: /opt/conda/etc/jupyter/jupyter_notebook_config.json
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [D 2019-03-12 13:00:53.356 saa2012 application:555] Looking for jupyter_notebook_config in /data/home/saa2012/.jupyter
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [D 2019-03-12 13:00:53.356 saa2012 application:555] Looking for jupyter_notebook_config in /home/saa2012
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [W 2019-03-12 13:00:53.359 saa2012 configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [D 2019-03-12 13:00:53.630 saa2012 config_manager:98] Paths used for configuration of jupyter_notebook_config: 
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |      	/etc/jupyter/jupyter_notebook_config.json
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [D 2019-03-12 13:00:53.631 saa2012 config_manager:98] Paths used for configuration of jupyter_notebook_config: 
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |      	/usr/local/etc/jupyter/jupyter_notebook_config.json
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [D 2019-03-12 13:00:53.631 saa2012 config_manager:98] Paths used for configuration of jupyter_notebook_config: 
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |      	/opt/conda/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |      	/opt/conda/etc/jupyter/jupyter_notebook_config.json
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [D 2019-03-12 13:00:53.632 saa2012 config_manager:98] Paths used for configuration of jupyter_notebook_config: 
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |      	/data/home/saa2012/.jupyter/jupyter_notebook_config.json
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [I 2019-03-12 13:00:53.679 saa2012 extension:168] JupyterLab extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [I 2019-03-12 13:00:53.679 saa2012 extension:169] JupyterLab application directory is /opt/conda/share/jupyter/lab
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [I 2019-03-12 13:00:53.681 saa2012 singleuser:406] Starting jupyterhub-singleuser server version 0.9.4
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [D 2019-03-12 13:00:53.688 saa2012 _version:53] jupyterhub and jupyterhub-singleuser both on version 0.9.4
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [I 2019-03-12 13:00:53.688 saa2012 notebookapp:1712] Serving notebooks from local directory: /data/home/saa2012/work
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [I 2019-03-12 13:00:53.688 saa2012 notebookapp:1712] The Jupyter Notebook is running at:
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [I 2019-03-12 13:00:53.688 saa2012 notebookapp:1712] http://(0a24c6b6c2be or 127.0.0.1):8888/
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [I 2019-03-12 13:00:53.688 saa2012 notebookapp:1713] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [I 2019-03-12 13:00:53.793 saa2012 log:158] 302 GET /user/saa2012/ -> /user/saa2012 (@10.0.9.11) 0.67ms
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [I 2019-03-12 13:00:55.930 saa2012 log:158] 302 GET /user/saa2012/?redirects=2 -> /user/saa2012/?redirects=2 (@::ffff:10.255.0.8) 0.76ms
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [I 2019-03-12 13:00:55.940 saa2012 log:158] 302 GET /user/saa2012/?redirects=2 -> /user/saa2012/?redirects=2 (@::ffff:10.255.0.8) 0.55ms
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [I 2019-03-12 13:00:55.949 saa2012 log:158] 302 GET /user/saa2012/?redirects=2 -> /user/saa2012/?redirects=2 (@::ffff:10.255.0.8) 0.53ms
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [I 2019-03-12 13:00:55.959 saa2012 log:158] 302 GET /user/saa2012/?redirects=2 -> /user/saa2012/?redirects=2 (@::ffff:10.255.0.8) 0.56ms
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [I 2019-03-12 13:00:55.968 saa2012 log:158] 302 GET /user/saa2012/?redirects=2 -> /user/saa2012/?redirects=2 (@::ffff:10.255.0.8) 0.55ms
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [I 2019-03-12 13:00:55.978 saa2012 log:158] 302 GET /user/saa2012/?redirects=2 -> /user/saa2012/?redirects=2 (@::ffff:10.255.0.8) 0.55ms
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [I 2019-03-12 13:00:55.988 saa2012 log:158] 302 GET /user/saa2012/?redirects=2 -> /user/saa2012/?redirects=2 (@::ffff:10.255.0.8) 0.54ms
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [I 2019-03-12 13:00:55.997 saa2012 log:158] 302 GET /user/saa2012/?redirects=2 -> /user/saa2012/?redirects=2 (@::ffff:10.255.0.8) 0.59ms
jupyter-saa2012.1.avcuyclgmgha@achead1.advcomp.lan    |  [I 2019-03-12 13:00:56.007 saa2012 log:158] 302 GET /user/saa2012/?redirects=2 -> /user/saa2012/?redirects=2 (@::ffff:10.255.0.8) 0.59ms

# Additional notes: 
We have a central storage. User homes are at "/data/homes/{user}"

I've been through so many tweaks of parameter but I can't seem to see what I need to get the notebook page to connect. I end up with the browser saying "Too many redirects occurred trying to open 'http://acmaster02.advcomp.lan:8889/user/saa2012/?redirects=2'"

Sam

**Comment by samagnew** [comment]
I'm not sure whether my issue is something super-specific to my environment but I have been through everything I can think of. It's very frustrating because I want to roll this out to my users but this stops me. The hub is running, user login is flawless, notebook container and service starts up and runs fine but somehow it is inaccessible because of some redirect error. I'd love any clues or pointers..

Sam

**Comment by dmpe** [comment]
Facing also same issue, using nginx

**Comment by miramar-labs** [comment]
same here - using helm chart v0.8.2

**Comment by jamesthegiantpeach** [comment]
Same - also using helm chart v0.8.2 with kubespawner

**Comment by jtlz2** [comment]
@jnoatak Thanks - how do I update the image tag in the chart / do you have a fixed chart?

**Comment by jtlz2** [comment]
I fixed it by portforwarding from the proxy rather than the hub itself
