### ISSUE TITLE
wrong about configurable-http-proxy -h 

### ISSUE THREAD

**Issue by ch-liuzhide** [jupyterhub/jupyterhub#2469]
1. Go to '**configurable-http-proxy -h**'

2. See error
![image](https://user-images.githubusercontent.com/44251801/54270048-7d011500-45b9-11e9-87ed-d405bda9425b.png)

**Expected behavior**
help about confi....

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Version [node version 3.5.2]

**Comment by 00Kai0** [comment]
@ch-liuzhide Hi, your node version is to old, you can update your node to LTS version. My version is `10.13.0`

**Comment by ch-liuzhide** [comment]
@00Kai0 oh!  thank you.
