### ISSUE TITLE
Autosave Failed!

### ISSUE THREAD

**Issue by radumas** [jupyterhub/jupyterhub#2470]
I installed this on an `Ubuntu 16.04` system with nginx. When trying to save/autosave I would get `Autosave Failed!` but saw nothing of note in the logs.

After a substantial amount of debugging I eventually figured out this was due to opening very large notebooks and the browser sending >2MB of data to the server in order to trigger a save.

So I added the below to my nginx server config, and thought it should be included as a hint/information in the installation docs?

```bash
server {
  #Jupyter appears to send huge blobs between browser and server
  #to save files. Include the below parameter in the https server
  #configuration.
  client_max_body_size 60M;

}
```

**Comment by willingc** [comment]
Thanks for passing along the information @radumas. :cookie:
