### ISSUE TITLE
Jupyterhub - pyspark access to GPU enabled nodes in a cluster

### ISSUE THREAD

**Issue by GeoffDuniam** [jupyterhub/jupyterhub#2482]
Afternoon,

Apologies if this is a duplicate (we originally posted this over at https://github.com/jupyter/help but probably should have gone here first. Anyway...) 

We're running Jupyterhub on the gateway server of a Hadoop Spark cluster. The worker nodes are all GPU enabled with CUDA 9.2 installed, but the gateway server isn't. Pyspark is working fine. What we were wondering if anyone's configured jupyterhub to access the GPU worker nodes from a gateway server?

Thanks up front

**Comment by jcrist** [comment]
> What we were wondering if anyone's configured jupyterhub to access the GPU worker nodes from a gateway server?

Are you asking about running user notebook servers on the worker nodes? If so, you may be interested in https://jcrist.github.io/yarnspawner/ for spawning notebooks distributed throughout the hadoop cluster. There's more detailed installation instructions here: https://jcrist.github.io/jupyterhub-on-hadoop/.

**Comment by GeorgianaElena** [comment]
Update:
https://jcrist.github.io/yarnspawner/ is now https://github.com/jupyterhub/yarnspawner
https://jcrist.github.io/jupyterhub-on-hadoop/ is now https://github.com/jupyterhub/jupyterhub-on-hadoop

@GeoffDuniam, do you still need help with this? :)

**Comment by GeorgianaElena** [comment]
Closing this as it seems to have been solved 🌻 Feel free to ask on https://discourse.jupyter.org/ forum for any configuration issues or questions ❤️ Thanks!
