### ISSUE TITLE
Jupyterhub on windows using Anaconda

### ISSUE THREAD

**Issue by andybala** [jupyterhub/jupyterhub#2483]
Hi all,

I have install Jupyterhub on windows 10 using Anaconda3.7 -- conda forge. All the dependencises checkedout. but I am getting this error when launching 

(base) C:\Users\ahb>jupyterhub
[I 2019-03-25 13:06:19.562 JupyterHub app:1673] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.4
[I 2019-03-25 13:06:19.562 JupyterHub app:1673] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.4
[I 2019-03-25 13:06:19.594 JupyterHub app:1016] Loading cookie_secret from C:\Users\ahbalasubramanian\jupyterhub_cookie_secret
[I 2019-03-25 13:06:19.636 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[E 2019-03-25 13:06:19.636 JupyterHub app:1958]
    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\jupyterhub\app.py", line 1955, in launch_instance_async
        await self.initialize(argv)
      File "C:\Anaconda3\lib\site-packages\jupyterhub\app.py", line 1684, in initialize
        await self.init_users()
      File "C:\Anaconda3\lib\site-packages\jupyterhub\app.py", line 1148, in init_users
        if self.authenticator.enable_auth_state:
      File "C:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
        return self.get(obj, cls)
      File "C:\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 535, in get
        value = self._validate(obj, dynamic_default())
      File "C:\Anaconda3\lib\site-packages\jupyterhub\app.py", line 675, in _authenticator_default
        return self.authenticator_class(parent=self, db=self.db)
      File "C:\Anaconda3\lib\site-packages\jupyterhub\auth.py", line 604, in __init__
        raise _pamela_error from None
      File "C:\Anaconda3\lib\site-packages\jupyterhub\auth.py", line 14, in <module>
        import pamela
    ModuleNotFoundError: No module named 'pamela'

**Comment by minrk** [comment]
JupyterHub officially does not support Windows, though it can be used if you select custom non-default Spawner and Authenticator. cc @dhirschfeld and @adelcast for Windows advice.

**Comment by dhirschfeld** [comment]
The usual setup on Windows would be [`dockerspawner`](https://github.com/jupyterhub/dockerspawner) and (in an enterprise) [`ldapauthenticator`](https://github.com/jupyterhub/ldapauthenticator).

If you're not in an enterprise and using LDAP, I'm not sure which if any of the other authenticators will work on Windows.

**Comment by minrk** [comment]
I think most Authenticators talk to external services via web APIs, e.g. the various OAuthenticators, so those should work fine, I think.

**Comment by adelcast** [comment]
If using docker is an option, then yeah, dockerspawner is the way to go. In the case that's not an option, you could try a Windows based local spawner that I wrote:

https://github.com/ni/jupyterhub-winlocalprocessspawner

For authentication, LDAP might be all you need. If you don't want to go that route, you can try a native Windows authenticator:

https://github.com/ni/jupyterhub-winauthenticator

hope this helps

**Comment by neftaliw** [comment]
Is there any plan to support windows in the future? Jupyter is not only old (latest update was 5 years ago) but I get the message it will be deprecated and jupyterhub should be used, but how are we to switch if there's no support for our OS?

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
