### ISSUE TITLE
Users added with "Add Users" button are not listed in the admin page

### ISSUE THREAD

**Issue by cmd-ntrf** [jupyterhub/jupyterhub#2489]
**Describe the bug**
Since commit 81a410db91912b0e925fdc3971f46805a648bdaf, the _Add Users_ button does not add new rows in the user table. However, the users count is incremented.

**To Reproduce**
1. Go to admin page
2. Click on 'Add Users'
3. Add a username that does not exist in the list.
4. Users number is incremented, but user does not show up in the table.

**Expected behavior**
Users added with the _Add Users_ button should be present in the user table.

**Screenshots**
![image](https://user-images.githubusercontent.com/884095/55194647-b1abc980-5180-11e9-8b36-a5f7d46dd103.png)

**Desktop (please complete the following information):**
 - OS: macOS 
 - Browser: Firefox, Safari, Chrome
 - Version: 10.13.6

**Additional context**
I did a git bisect between 0.9.5 and 1.0.0b1 and found that commit 81a410db91912b0e925fdc3971f46805a648bdaf is when the button stopped working properly.

EDIT 1:
After digging a bit more, it appears that the generator `all_spawners` for users added with the _Add Users_ button is empty.

EDIT 2:
New `jupyterhub.user.User` object begin their _object life_ with 0 spawner. Therefore, `all_spawners` will always be empty for new users added with the _Add Users_ button.

A quick-and-dirty fix is to force the creation of the default spawner by adding the line
```python
self.spawner
``` 
after the creation of `self.spawners` in `jupyterhub.user.User.__init__`.

**Comment by consideRatio** [comment]
Quickly jumping in from mobile to say I think this was a very nice writeup!! :heart:

**Comment by minrk** [comment]
Thanks for testing! This should be fixed by #2496
