### ISSUE TITLE
Login redirect validation bypass

### ISSUE THREAD

**Issue by dmarth** [jupyterhub/jupyterhub#2493]
**Describe the bug**
A triple-slash can be used to bypass the login redirect validation.

**To Reproduce**
1. Start up JupyterHub
2. Visit `/hub/login?next=%2f%2f%2fjupyter.org` on your JupyterHub instance
3. Login with valid credentials

JupyterHub responds with the following HTTP header:
`location: ///jupyter.org`
Current versions of (at least) Firefox and Chrome interpret this as an absolute URL.

**Expected behavior**
Disallow the redirect to other domains than the JupyterHub server

**Desktop (please complete the following information):**
 - Browser: Tested on Firefox 66, Chrome 73
- JupyterHub: Tested with the Docker images for 0.9.5 as well as 1.0.0b1 from https://hub.docker.com/r/jupyterhub/jupyterhub

**Comment by minrk** [comment]
omg, browsers error-checking safe urls into unsafe ones is killing me. Will release a fix shortly.

**Comment by minrk** [comment]
0.9.6 released, fixed by be97a0c95b86152f38a877c3294982e38ad71ad4

**Comment by dmarth** [comment]
Thanks for the quick fix!

I know that JupyterHub offers an option to run user notebooks on a subdomain, but I am not familiar with that feature. How do these redirects look like in that case? Does blacklisting `://` break anything?
https://github.com/jupyterhub/jupyterhub/blob/0.9.6/jupyterhub/handlers/base.py#L449

**Comment by minrk** [comment]
URLs with hosts were already blacklisted (converted to local paths if the host matched the current request's host). The only case being allowed through was when url parsing gave an *empty* host, which Python's parsing assumed meant same-host, while browsers stripped all leading slashes down to two.

The subdomain redirect is actually one hop away, so this should be okay. If you share a link to a user server, e.g. `https://foo.localhost.jovyan.org:8000/user/foo/tree/stuff`, the redirects go like this:

1. https://foo.hub.tld/user/foo/tree/stuff (not logged in) -> https://hub.tld/hub/api/oauth2/authorize?client_id&redirect_url...
2. https://hub.tld/hub/api/oauth2/authorize -> /hub/login?next=/hub/api/oauth2/authorize?...jupy
3. https://hub.tld/hub/api/oauth2/authorize -> https://foo.hub.tld/user/foo/oauth_callback
4. https://foo.hub.tld/user/foo/oauth_callback -> /user/foo/tree/stuff

where step 3 is validated in the oauth database for one and only one valid redirect_uri, and step 4 (the user-provided redirect) is validated by storing the final path in oauth state, which is validated by being stored both in a cookie and param, comparing the two before consuming them.

**Comment by fphammerle** [comment]
Does this issue have a CVE number?
