### ISSUE TITLE
Potential XSS vulnerability

### ISSUE THREAD

**Issue by clancychilds** [jupyterhub/jupyterhub#2502]
My company ran an infosec scan of the JupyterHub code base and found this potential vulnerability. I thought it best to raise it here, but I don't know if it is an actual vulnerability or a false positive from the scan.

This is a potential instance of https://cwe.mitre.org/data/definitions/79

The software does not sufficiently validate, filter, escape, and/or encode user-controllable input before it is placed in output that is used as a web page that is served to other users.

https://github.com/jupyterhub/jupyterhub/blob/e89836c035f79a44cb5ebc1126e53c6f605464c1/share/jupyterhub/templates/spawn_pending.html#L48

`var evt = JSON.parse(e.data); `

**Comment by betatim** [comment]
Please report security issues to security@ipython.org.

More details and a PGP key: https://jupyter-notebook.readthedocs.io/en/stable/security.html?highlight=vulnerability#reporting-security-issues

**Comment by choldgraf** [comment]
to reiterate, it's best practice not to post security vulnerabilities in a public forum. We appreciate you taking the time to inform the community of this, but it's safest to use the suggested method for reporting vulnerabilities (here: https://jupyter-notebook.readthedocs.io/en/stable/security.html?highlight=vulnerability#reporting-security-issues)

**Comment by minrk** [comment]
This is not a security issue. These messages come from JupyterHub, so it's a self-to-self communication from a trusted source. I added security-reporting links to the docs in #2509.
