### ISSUE TITLE
Docker image should come with authentication

### ISSUE THREAD

**Issue by kevart** [jupyterhub/jupyterhub#2503]
It would be nice to include a default user+pw for the docker image (instructions here: https://hub.docker.com/r/jupyterhub/jupyterhub#configuration). Docker is an easy and quick way to test a software. Without credentials I can't log in, can't see anything, can't test and might just try something else.

**Comment by minrk** [comment]
Now that dummy auth and simple spawner are available, we should probably use those by default in the image.
