### ISSUE TITLE
Potential URl Redirector Abuse Vulnerability

### ISSUE THREAD

**Issue by clancychilds** [jupyterhub/jupyterhub#2506]
My company recently completed an infosec scan of the jupyterhub codebase. One of the items they found was a potential URI Redirector Abuse:
https://cwe.mitre.org/data/definitions/601

I have not really evaluated whether it is actually a problem or a false positive, but figured I should mention it here regardless.

A web application accepts a user-controlled input that specifies a link to an external site, and uses that link in a Redirect. This simplifies phishing attacks.
https://github.com/jupyterhub/jupyterhub/blob/e89836c035f79a44cb5ebc1126e53c6f605464c1/share/jupyterhub/static/js/admin.js#L33

https://github.com/jupyterhub/jupyterhub/blob/e89836c035f79a44cb5ebc1126e53c6f605464c1/share/jupyterhub/static/js/admin.js#L52

Recommendations:
Ideally, do not allow arbitrary URLs for redirection. Instead, create a server-side mapping from user-provided parameter values to legitimate URLs.
If it is necessary to allow arbitrary URLs:
For URLs inside the application site, first filter and encode the user-provided parameter, and then use it as a relative URL by prefixing it with the application site domain.
For URLs outside the application (if necessary), use an intermediate disclaimer page to provide users with a clear warning that they are leaving your site.

**Comment by betatim** [comment]
Please report security issues to security@ipython.org.

More details and a PGP key: https://jupyter-notebook.readthedocs.io/en/stable/security.html?highlight=vulnerability#reporting-security-issues

**Comment by minrk** [comment]
I've opened #2509 for future security reports. Thanks for reporting potential issues!

This is not a security issue. This code allows modification of the query string only (and only the sort and order fields), not the path or host, so there are no redirect issues here.

> Recommendations:
> Ideally, do not allow arbitrary URLs for redirection. 

We don't allow arbitrary URLs or user-input for redirects. The host and path are fixed, this only refreshes the current page with a new query.
