### ISSUE TITLE
Authenticate via a supplied GitHub authentication token?

### ISSUE THREAD

**Issue by plambe8** [jupyterhub/jupyterhub#2512]
Hey guys,

I am wondering if it is possible to supply an authenticated GitHub token to JupyterHub to login a user that way? 

My JupyterHub instance is being hosted as an iframe embedded inside a larger application. I am using the JupyterHub authentication service to authenticate users via GitHub. My end goal is to be able to gain access to this user information (namely, their username) in the parent application that jupyterhub is embedded in.

My thought is to authenticate via GitHub on an initial login screen, and then redirect to the main page and authenticate JupyterHub there. This way, I'll have the user information both in my application and JupyterHub.

Is this possible? Is this api endpoint something that could help? https://jupyterhub.readthedocs.io/en/stable/_static/rest-api/index.html#path--authorizations-cookie--cookie_name---cookie_value-

**Comment by ryogesh** [comment]
Can you check if the SAML2 authenticator serves your need.

https://github.com/ImperialCollegeLondon/jupyter_saml2authenticator

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
