### ISSUE TITLE
Bad config encountered during initialization:

### ISSUE THREAD

**Issue by ldnelso2** [jupyterhub/jupyterhub#2513]
I am having an issue after following the 'Deploying Jupyterhub on AWS' exactly step-by-step from a clean EC2 instance (I have done it twice with the same result).

This is the error I am getting (my username is ldnelso2, and I am using github oauth for authentication, which works fine): 

[C 2019-04-08 02:08:10.746 SingleUserNotebookApp application:90] Bad config encountered during initialization:
[C 2019-04-08 02:08:10.746 SingleUserNotebookApp application:91] No such notebook dir: '/home/ldnelso2/assignments'
[W 2019-04-08 02:08:20.164 JupyterHub web:1667] 500 GET /hub/user/ldnelso2/ (::ffff:136.56.36.206): Spawner failed to start [status=1]. The logs for ldnelso2 may contain details.
[D 2019-04-08 02:08:20.165 JupyterHub base:890] No template for 500

The web interface gives the following error: 

> 500 : Internal Server Error
> Spawner failed to start [status=1]. The logs for ldnelso2 may contain details.
> You can try restarting your server from the home page.

I have looked through the 500 error troubleshooting, and nothing there appears to be applicable.

Interestingly, the directory listed in the config from the guide (https://github.com/jupyterhub/jupyterhub/wiki/Deploying-JupyterHub-on-AWS) is shown as: 

```
c.Spawner.notebook_dir = '~/assignments'
c.Spawner.args = ['--NotebookApp.default_url=/notebooks/Welcome.ipynb']

```
But the errors indicate that the Spawner is having a problem with the notebook directory /home/ldnelso2/assignments

If I switch to user ldnelso2 in bash and type: 
`$ jupyter --paths`
I get the following, even though most of those directories don't exist: 
```
config:
    /home/ldnelso2/.jupyter
    /usr/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/ldnelso2/.local/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /home/ldnelso2/.local/share/jupyter/runtime
```
Last note is that the guide indicates that running jupyter hub as the root user avoids permissions errors.  I don't really like launching it that way, but it does avoid the errors that pop up if I launch with a non-root user.  Perhaps starting jupyterhub as root is causing the error with the Spawner.

**Comment by ryogesh** [comment]
Assuming the latest 0.9.4,  can you try if the docker spawner launches successfully if you comment the below 2 config items

c.Spawner.notebook_dir = '~/assignments'
c.Spawner.args = ['--NotebookApp.default_url=/notebooks/Welcome.ipynb']

**Comment by ldnelso2** [comment]
I will do this, and post the results.  I am working through one other unrelated error on my server that I need to fix first, so will post results by early next week.

**Comment by ldnelso2** [comment]
Hi Ryogesh -- fortunately / unfortunately, I had to re-install my instance, and I am unable to reproduce the error.  Luckily, the spawner is working.  Thank you for the help, I will go ahead and close.

**Comment by turkialjrees** [comment]
This is might Help I SOLVED and wrote about it [HERE](https://github.com/jupyterhub/jupyterhub/issues/444#issuecomment-522809168)
