### ISSUE TITLE
Creating own proxy implementation.

### ISSUE THREAD

**Issue by Mayurdoshi** [jupyterhub/jupyterhub#2516]
Hello

I am trying to create a custom proxy in jupyter and for that i had created one file with name myproxy and it has the same code as of the ConfigurableHttpProxy code and i have changed the jupyter config file to 
c.JupyterHub.proxy_class = myproxy

but while staring the jupyter hub it giving me following error what wrong am i doing:
`Apr 12 06:15:20 instance-2 jupyterhub[17709]:     TypeError: can't pickle module objects
Apr 12 06:15:20 instance-2 jupyterhub[17709]:         rv = reductor(4)
Apr 12 06:15:20 instance-2 jupyterhub[17709]:       File "/usr/lib/python3.6/copy.py", line 169, in deepcopy
Apr 12 06:15:20 instance-2 jupyterhub[17709]:         setattr(self, name, deepcopy(config_value))
Apr 12 06:15:20 instance-2 jupyterhub[17709]:       File "/usr/local/lib/python3.6/dist-packages/traitlets/config/configurable.py", line 153, in _load_config
Apr 12 06:15:20 instance-2 jupyterhub[17709]:         self._load_config(config)
Apr 12 06:15:20 instance-2 jupyterhub[17709]:       File "/usr/local/lib/python3.6/dist-packages/traitlets/config/configurable.py", line 198, in update_config
Apr 12 06:15:20 instance-2 jupyterhub[17709]:         self.update_config(new_config)
Apr 12 06:15:20 instance-2 jupyterhub[17709]:       File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 603, in load_config_file
Apr 12 06:15:20 instance-2 jupyterhub[17709]:         return method(app, *args, **kwargs)
Apr 12 06:15:20 instance-2 jupyterhub[17709]:       File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
Apr 12 06:15:20 instance-2 jupyterhub[17709]:       File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-5>", line 2, in load_config_file
Apr 12 06:15:20 instance-2 jupyterhub[17709]:         self.load_config_file(self.config_file)
Apr 12 06:15:20 instance-2 jupyterhub[17709]:       File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1639, in initialize
`

**Comment by minrk** [comment]
Can you provide more context, for example the complete `jupyterhub_config.py` with any sensitive info redacted?

**Comment by Mayurdoshi** [comment]
`
import os
import aishub
from aishub import user,myproxy
from systemdspawner import SystemdSpawner

class UserCreatingSpawner(SystemdSpawner):
    
    def start(self):
       
        # FIXME: Move this elsewhere? Into the Authenticator?
        system_username = self.generate_system_username('jupyter-' + self.user.name)

        # FIXME: This is a hack. Allow setting username directly instead
        self.username_template = system_username
        user.ensure_user(system_username)
        user.ensure_user_group(system_username, 'jupyterhub-users')
        if self.user.admin:
            user.ensure_user_group(system_username, 'jupyterhub-admins')
        else:
            user.remove_user_group(system_username, 'jupyterhub-admins')
        return super().start()

    import hashlib

    def generate_system_username(self,username):
      
       if len(username) < 26:
           return username

       userhash = hashlib.sha256(username.encode('utf-8')).hexdigest()
       return '{username_trunc}-{hash}'.format(
           username_trunc=username[:26],
           hash=userhash[:5]
       )

c.JupyterHub.spawner_class = UserCreatingSpawner

# leave users running when the Hub restarts
c.JupyterHub.cleanup_servers = False


c = get_config()  # noqa

from dummyauthenticator import DummyAuthenticator

c.JupyterHub.proxy_class = myproxy

c.JupyterHub.authenticator_class = DummyAuthenticator
c.Authenticator.auto_login = True
# Optionally set a global password that all users must use
c.DummyAuthenticator.password = "apassword"
c.SystemdSpawner.default_shell = '/bin/bash'
# Drop the '-singleuser' suffix present in the default template
c.SystemdSpawner.unit_name_template = 'jupyter-{USERNAME}'
c.Authenticator.admin_users = {'xyz'}

`

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
