### ISSUE TITLE
Notebook fails to connect to kernel

### ISSUE THREAD

**Issue by qsjiang** [jupyterhub/jupyterhub#252]
Hi there,

I am trying to setup jupyterhub on my local machine running OSX 10.10.1.
Everything seems to be working (the file system browser and the terminal they both work fine) except when I open the notebook I get the following error.  Any idea what is causing the error?
![jupyternberror](https://cloud.githubusercontent.com/assets/6367081/7657121/8b743960-fafd-11e4-8830-af1a6f99bc4b.jpg)

Here is the error message inside the Chrome JS console. 
![consoleerror](https://cloud.githubusercontent.com/assets/6367081/7658054/d4fe981c-fb04-11e4-83ee-62147e36b174.jpg)

Thanks!

**Comment by minrk** [comment]
What do you see in the server logs in the terminal?

**Comment by qsjiang** [comment]
[I 2015-05-19 11:03:02.614 JupyterHub log:100] 302 GET /user/Jim%2520Jiang/api/kernels/182f47f2-e962-43a8-9983-871bd87f4ccb/channels?session_id=6C1F73EA870544708C4041F6FB468B13 (@::1) 3.18ms
[I 2015-05-19 11:03:03.629 JupyterHub log:100] 302 GET /user/Jim%2520Jiang/api/kernels/182f47f2-e962-43a8-9983-871bd87f4ccb/channels?session_id=6C1F73EA870544708C4041F6FB468B13 (@::1) 0.88ms
[I 2015-05-19 11:03:05.649 JupyterHub log:100] 302 GET /user/Jim%2520Jiang/api/kernels/182f47f2-e962-43a8-9983-871bd87f4ccb/channels?session_id=6C1F73EA870544708C4041F6FB468B13 (@::1) 1.29ms
[I 2015-05-19 11:03:09.660 JupyterHub log:100] 302 GET /user/Jim%2520Jiang/api/kernels/182f47f2-e962-43a8-9983-871bd87f4ccb/channels?session_id=6C1F73EA870544708C4041F6FB468B13 (@::1) 1.24ms
[I 2015-05-19 11:03:17.673 JupyterHub log:100] 302 GET /user/Jim%2520Jiang/api/kernels/182f47f2-e962-43a8-9983-871bd87f4ccb/channels?session_id=6C1F73EA870544708C4041F6FB468B13 (@::1) 1.28ms

**Comment by rgbkrk** [comment]
That looks like a double URL encoded version of "Jim Jiang" in the URL.

```
urlencode(urlencode("Jim Jiang")) == urlencode("Jim%20Jiang") == urlencode("Jim%2520Jiang")

% -> 25
```

Side question: are we actually allowing spaces in usernames?

**Comment by qsjiang** [comment]
Hi @rgbkrk 
You are right the problem was cause by the space in the username. By default Jupyterhub uses the username and password from the operating system, and OS X 10.10.1 actually allows space in the username. After creating a new user on my machine(without space in username), the problem is solved. 

Thanks

**Comment by minrk** [comment]
@qsjiang are you using latest master? What do you get from `git log -1` in the jupyterhub repo? I'll have to dig around to find where I'm double-encoding.

**Comment by qsjiang** [comment]
I am running "jupyterhub-0.2.0.dev0".

The last commit is:

    commit 1ff659a847961b7fd9ff266481a08e5d5a7387eb
    Merge: 087a93f de40310
    Author: Kyle Kelley <rgbkrk@gmail.com>
    Date:   Mon May 11 15:16:45 2015 -0500

    Merge pull request #251 from minrk/version
    
    fix `jupyterhub --version` output


I installed jupyterhub using the following steps:

    sudo npm install -g configurable-http-proxy
    git clone https://github.com/jupyter/jupyterhub.git 
    cd jupyterhub
    pip install -r requirements.txt
    pip install .
    pip install "ipython[notebook]"

**Comment by willingc** [comment]
@minrk I'm going to close this since this is pretty old and many enhancements have been made in the last year.
