### ISSUE TITLE
Slow startup is back

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#2525]
We used to do a lot of work during startup that scaled by the number of users (instantiating too many Spawner objects, even when they weren't running). This was fixed a few releases ago to only instantiate Spawner objects that might be running, calling `.poll()` on them, and the startup polling is now concurrent across running Spawners.

In 1.0, #2297 adds an *http* poll for each apparently running server to protect against partially alive Spawners, verifying that the Spawners are alive at their expected URLs. As discovered on mybinder.org today, this can significantly increase Hub restart time when there are lots of running servers.

The most logical solution is to delay the correct-url check until after the Hub begins accepting connections. This sounds good, since partial launches are rare, but it would also introduce some potentially complex race conditions with launches that might start after the Hub begins accepting connections, but before it has finished recovering from the database into a consistent state.

**Comment by yuvipanda** [comment]
Do you think we can make this optional as a temporary measure?
