### ISSUE TITLE
Spawner failed to start [status=1] under MacOS

### ISSUE THREAD

**Issue by spouyllau** [jupyterhub/jupyterhub#2527]
Hello,
I install JupyterHub on MacOS (ip of the Mac : 10.0.1.4) and I have, after login : 

> 500 : Internal Server Error
> Spawner failed to start [status=1].

on the web page. I see : 

[https://jupyterhub.readthedocs.io/en/latest/troubleshooting.html#error-after-spawning-my-single-user-server](url) and many Web page about this error, but I haven't solution. I have tested with : c.JupyterHub.hub_ip = '10.0.0.4' but without solution. Can I help me ?

Best,

Stéphane.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
