### ISSUE TITLE
Django + Jupyterhub Question

### ISSUE THREAD

**Issue by swsms** [jupyterhub/jupyterhub#2528]
Hello! You'd like to use JupyterHub together with Django (especially ORM) to play with data.

Now I can start a separated Jupyter notebook for Django using this command:
`
python manage.py shell_plus --notebook
`
I also have a docker with JupyterHub and Jupyter installed inside, but do not use it yet. I'm going to deploy it on a server and provide access for some people. How can I start notebooks with django rather than simple jupyter notebooks using JupyterHub?

I need some links and tips.

Thanks!

**Comment by minrk** [comment]
You can use the jupyterhub and notebook [REST APIs](https://jupyterhub.readthedocs.io/en/stable/reference/rest.html) to spawn things. Maybe that's what you need?

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/spawn-django-notebook/9626/1
