### ISSUE TITLE
cannot import packages that installed with `!pip install --user` in the notebook

### ISSUE THREAD

**Issue by kemingy** [jupyterhub/jupyterhub#2539]
**Describe the bug**
Cannot import packages that installed with `!pip install <package_name> --user` in notebook. **Have to restart it.**

**To Reproduce**
1. Go to  a new Python3 notebook
2. `!pip install numpy --user`
3. `import numpy as np`

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-20-7dd3504c366f> in <module>
----> 1 import numpy as np

ModuleNotFoundError: No module named 'pandas'
```

**Expected behavior**
It should be OK to import the installed packages. But I have to open a new notebook/terminal to use it.

**Desktop (please complete the following information):**
 - Ubuntu 18.04 (guest OS)
 - Chrome Version 73.0.3683.103 (Official Build) (64-bit)

**Additional context**
I install the jupyterhub with virtualbox & vagrant, following the guide: [The Littlest JupyterHub](https://tljh.jupyter.org/en/latest/install/custom-server.html). The host machine is Ubuntu16.04.

**Comment by ryogesh** [comment]
Please refer: https://tljh.jupyter.org/en/latest/install/custom-server.html

If a user already had a python notebook running, they have to **restart** their notebook’s kernel to make the new libraries available.
