### ISSUE TITLE
Language: "Spawner options" too technical for the end user

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#2550]
I think that while the language "Spawner options" is very technically accurate, but not suitable to present to and end user.

![image](https://user-images.githubusercontent.com/3837114/57284525-a74eea80-70b1-11e9-979a-233d98b38f0a.png)

[The default JupyterHub spawn.html template](https://github.com/jupyterhub/jupyterhub/blob/master/share/jupyterhub/templates/spawn.html) contains two sections I'd suggest we rephrase.

1. The title "Spawner options"
2. The button action "Spawn".

I'm thinking more like "Server options" and "Start server" or similar. Thinking about it, we have the button saying "Start My Server" already...

![image](https://user-images.githubusercontent.com/3837114/57291214-49c19a80-70bf-11e9-886a-6b415c2b495f.png)

**Comment by minrk** [comment]
👍 to "Server options" and "Start"

**Comment by consideRatio** [comment]
@nikenano remember this discussion that you got going? =) Care to make a PR?

**Comment by NikeNano** [comment]
@consideRatio cool.  I would be happy to fix it :)
