### ISSUE TITLE
Deploy the customised JupyterHub

### ISSUE THREAD

**Issue by IamViditAgarwal** [jupyterhub/jupyterhub#2557]
Hi.
I  am working in a company. My company uses JupyterHub. In my company, there is a need for customizing some of the UI element of the JupyterHub. I have edited the template source code for the changes and we are using the Helm on the Kubernetes Cluster for the deployment.
**ISSUE** : I want to know how can I deploy the customized version of the JupyterHub. I m not able to find relevant documentation. Do I have to again create the Helm charts for the JupyterHub code or How can I deploy that changes ?

I have done some research and what I have found people saying that: 
- Go to the  directory where the JupyterHub is installed 
- copy the templates to another dir, 
- change the HTML's 
- Do a change in the **jupyterhub_config.py** file. 
But this is the temp solution. Bcz, If I do the new update then the older update will get removed.

So, can anyone guide me how to do this in a correct and the proper way ?
Thanks in advance
Vidit

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
