### ISSUE TITLE
Change port 8081

### ISSUE THREAD

**Issue by perlinger** [jupyterhub/jupyterhub#2561]
When I launch Jupyterhub, one of the ports Jupyterhub uses is port 8081.
Example:
jupyterhu 22043           root    8u  IPv4 71493062      0t0  TCP 127.0.0.1:8081 (LISTEN)

How do I change it from port 8081 to some other port?
Thanks

**Comment by krinsman** [comment]
Run `jupyterhub --help-all` and you should see. For the record I believe it is `--port=NEWPORTNUMBER`, the way it is for notebook/lab.

**Comment by krinsman** [comment]
See: https://jupyterhub.readthedocs.io/en/stable/getting-started/config-basics.html

**Comment by krinsman** [comment]
@perlinger If this helped you, I recommend you close this issue so you receive fewer notifications.
