### ISSUE TITLE
Visually tuning templates - Spawn.html inspirational example.

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#2563]
After #2550 I got thinking on how to make things even more clear for my endusers. They are automatically bypassing the "login" button and will arrive at this screen.

After learning how to inject some images etc. for the templates to consume, I tested inserting this image above "Server Options" in the spawning page and became quite happy with how things looked.

I will probably write a short text to onboard the user further as well, but I provide this as an example of the possebilities of tuning the default templates a bit.

![image](https://user-images.githubusercontent.com/3837114/57699440-05eb0a00-7658-11e9-9a63-56c4b681deb6.png)

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. Might be nice to add a Discourse post on this?
