### ISSUE TITLE
Feature: Manage announcements as an Admin from a UI

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#2569]
> Managing the announcements by editing templates or another service is OK, but something in the admin interface to update/change the announcement would be neat too (I know that's separate from this issue).

@rcthomas said what I also was thinking in #2566!

It would be a nice thing to be able to manage this from the UI, just like is done on Discourse and GitLab:

# Discourse Admin UI for announcements:
![image](https://user-images.githubusercontent.com/3837114/57870759-0cb87f00-7808-11e9-8b79-aab53586f2b0.png)

# GitLab Admin UI for announcements:
![image](https://user-images.githubusercontent.com/3837114/57870827-31145b80-7808-11e9-965a-57381666c693.png)

**Comment by rcthomas** [comment]
@consideRatio Have a look at [this repo?](https://github.com/rcthomas/jupyterhub-announcement)  I took the announcement service example and added some features, but the most important one is a UI and logic for maintaining the announcements.

Probably the most important thing is that the exercise highlighted to me that maintaining a consistent UI look-and-feel across such services (that can have an accessible UI) isn't easy.  It wasn't impossible but it was a lot of trial and error to discover why the logo wasn't showing up or the links back to the hub were wrong.  During the process I wondered if some of those UI elements in the code could be more easily re-used by services?

I don't have a concrete proposal on how to do that but it could be simply documenting it better might be sufficient.  Related: #2763

**Comment by consideRatio** [comment]
@rcthomas thanks for sharing this! :heart:

**Comment by manics** [comment]
Based on https://github.com/jupyterhub/jupyterhub/issues/2569#issuecomment-540053899 shall we close this?

**Comment by manics** [comment]
Closing, since there's a solution and we're also discussing moving the repo to make it more prominent.
