### ISSUE TITLE
Named Servers with Dockerspawner

### ISSUE THREAD

**Issue by mathematicalmichael** [jupyterhub/jupyterhub#2572]
I use the jupyterhub-deploy-docker set-up and just recently attempted to upgrade to 1.0.
I was able to do so successfully after deleting my database, but encountered the following problem when attempting to test out the new "Named Servers" feature.

Since dockerspawner attributes the same image name for each single-user server, attempting to run more than one named server simultaneously leads to problems due to conflicting names. Only one can be run at once. 

Apologies if this issue belongs in DockerSpawner. If so, I'll close and re-submit it there.

**Comment by krinsman** [comment]
This sounds like a DockerSpawner issue to me, at least based on [the extent of my knowledge of named servers](https://github.com/jupyterhub/jupyterhub/pull/2089). My personal recommendation, and again I'm not a JupyterHub dev, would be to re-submit it there.

**Comment by mathematicalmichael** [comment]
@krinsman my thinking was that the naming scheme for named-servers wasn’t being used by jupyterhub to pass along the message to dockerspawner. However, I will submit this there as well.

**Comment by Redhappy** [comment]
@mathematicalmichael hi.

Did you submit this issue to the Dockerspawner side? I couldn't find it.
And what kind of error did you actually get? I think I am dealing with the same kind of issue.

**Comment by mathematicalmichael** [comment]
@redhappy no, I will go do that now. The errors I got were simply that the named server couldn’t launch while the other was running, since it tried to assign the same name. 

I think if the container names expanded “hub name” as part of the convention, the conflict would be avoided.
