### ISSUE TITLE
Running JupyterHub as a system service - Ubuntu

### ISSUE THREAD

**Issue by brayanrodpr** [jupyterhub/jupyterhub#2573]
I want to create a system service to run JupyterHub. I downloaded the file from https://gist.githubusercontent.com/lambdalisue/f01c5a65e81100356379/raw/ecf427429f07a6c2d6c5c42198cc58d4e332b425/jupyterhub and located it in `/etc/init.d/jupyterhub`. Then, I modified my JupyterHub configuration file as follows: 
```
service_name = 'shared-notebook'
service_port = 8000
group_name = 'shared'


c.JupyterHub.services = [
    {
        'name': service_name,
        'url': 'http://127.0.0.1:{}'.format(service_port),
        'command': ['jupyterhub-singleuser', '--group=shared', '--debug'],
    }
]
```
I start the service: `service jupyterhub start`. 

And the status is: 
```
● jupyterhub.service - LSB: Start jupyterhub
   Loaded: loaded (/etc/init.d/jupyterhub; bad; vendor preset: enabled)
   Active: active (exited) since Sun 2019-05-19 00:14:05 UTC; 20h ago
     Docs: man:systemd-sysv-generator(8)
  Process: 19918 ExecStop=/etc/init.d/jupyterhub stop (code=exited, status=0/SUCCESS)
  Process: 25113 ExecStart=/etc/init.d/jupyterhub start (code=exited, status=0/SUCCESS)
    Tasks: 0
   Memory: 0B
      CPU: 0
```

However, when I enter to the localhost:8000 the connection is refused.

**Comment by ryogesh** [comment]
1) Can you check the syslog for details?
2) Is the port 8000 in use by another process? try ss -tan |grep 8000
3) If you run ps -ef |grep python do you see the jupyter processes?

**Comment by brayanrodpr** [comment]
Thanks for answering. 
1. The /var/log/syslog file shows me: 
```
May 20 10:54:34 localhost systemd[1]: Started LSB: Start jupyterhub.
May 20 10:55:01 localhost CRON[12910]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
```

2. The output of ss -tan |grep 8000 is empty.

3. The output of ps -ef |grep python is 
`root     13358 12622  0 11:07 pts/1    00:00:00 grep --color=auto python`

**Comment by ryogesh** [comment]
Does launching jupyterhub with the same config file from a command line work?

**Comment by brayanrodpr** [comment]
Yes, it works from command line.

**Comment by ryogesh** [comment]
Try adding '--allow-root',  to 'command': ['jupyterhub-singleuser', '--group=shared', '--debug']

'command': ['jupyterhub-singleuser', '--group=shared', '--debug', '--allow-root']

**Comment by brayanrodpr** [comment]
It works as well from Command Line, but by the service is not responding yet.

**Comment by brayanrodpr** [comment]
@ryogesh Do you know why?

**Comment by ryogesh** [comment]
start-stop-daemon with $DAEMON_ARGS is the issue

1) create the  startup script, say /etc/jupyterhub/jupyterhub.sh with 
#!/bin/bash
/opt/anaconda3/bin/jupyterhub -f /etc/jupyterhub/jupyterhub_config.py 1>/etc/jupyterhub/jhub.log 2>&1 &

2) To the jupyterhub_config.py file add 
c.JupyterHub.pid_file = '/etc/jupyterhub/jupyterhub-run.pid'

3) Refer below for updated service script, make changes as required
https://gist.github.com/ryogesh/37ee2273c5fe0d38d8128feb78d7812a

**Comment by brayanrodbajo** [comment]
Thank you very much! The issue is solved!

**Comment by brayanrodpr** [comment]
Thank you very much! The issue is solved!
