### ISSUE TITLE
permission denied when acl is configured

### ISSUE THREAD

**Issue by eylenth** [jupyterhub/jupyterhub#2576]
**Describe the bug**
Hello

When opening a session in jupyterhub, I want to create file in a directory where an acl is configured. But I get a permission denied

When I try to create a file in the same directory in my terminal session, it is working.
When I create this file in a local jupyter notebook, it is also working

**To Reproduce**

```shell
$ cd tmpetsxn/
tmpetsxn $ getfacl .
# file: .
# owner: jboss
# group: jboss
user::rwx
user:jboss:rwx
group::r-x
group:ducktales:rwx
mask::rwx
other::r-x
default:user::rwx
default:user:jboss:rwx
default:group::r-x
group:ducktales:rwx
default:mask::rwx
default:other::r-x

tmpetsxn $ touch test1
tmpetsxn $ groups $USER
etsxn : users ducktales
```

**Expected behavior**
Creating a file when executing 'touch test1'

**Screenshots**
Session in jupyterhub
https://i.imgur.com/38y3tmQ.png

Session in jupyter notebook
https://i.imgur.com/5Y8QAbu.png

Session in terminal session:
https://i.imgur.com/QvtZIqN.png

**Comment by ryogesh** [comment]
can you check env, id, user on notebook and compare against the terminal.

**Comment by eylenth** [comment]
jupyterhub:
```
id
uid=28126(etsxn) gid=920(users) groups=920(users)
```

terminal session:
```
$ id
uid=28126(etsxn) gid=920(users) groups=920(users),12937(ducktales),
```
local notebook:
```
id
uid=28126(etsxn) gid=920(users) groups=920(users),12937(ducktales),
```
so it means the ldap groups are not recognized in the session of jupyterhub. 

Configuration of /etc/jupyterhub/jupyterhub_config.py
```python
c.JupyterHub.config_file = '/etc/jupyterhub/jupyterhub_config.py'
c.JupyterHub.cookie_secret_file = '/etc/jupyterhub/jupyterhub_cookie_secret'
c.JupyterHub.db_url = '/etc/jupyterhub/jupyterhub.sqlite'
c.JupyterHub.extra_log_file = '/var/log/jupyterhub/jupyterhub.log'
c.JupyterHub.ip = '$IPADDRESS'
c.JupyterHub.pid_file = '/var/run/jupyter.pid'

import os
for var in os.environ:
  c.Spawner.env_keep.append(var)

c.Spawner.ip = '$IPADDRESS'
c.ConfigurableHTTPProxy.auth_token = '$TOKEN'
c.Spawner.notebook_dir = '$PATH/workspace/{username}/'
...
c.PAMAuthenticator.service = 'jupyterhub'
c.PAMAuthenticator.open_sessions = False
....
c.ConfigurableHTTPProxy.debug = True
c.Spawner.debug = True
c.LocalProcessSpawner.debug = True
c.ConfigurableHTTPProxy.should_start = False
c.JupyterHub.data_files_path = '$INSTALLPATH_JUPYTERHUB/share/jupyterhub'
c.JupyterHub.cleanup_proxy = True
c.Spawner.default_url = '/lab'
c.Spawner.cmd = ['jupyter-labhub']
c.JupyterHub.port = 443
```

**Comment by ryogesh** [comment]
1) Can you try with c.PAMAuthenticator.open_sessions = True? , Do you have selinux enabled, can you disable?
2) Can you also compare all the environment variables?
3) Can you launch the terminal from jupyterlab and check?

**Comment by eylenth** [comment]
1.I tried with c.PAMAuthenticator.open_sessions = True :  same behavior . 
Selinux is disabled

2. these are the differences I see between the jupyterhub environment and a local notebook environment:
jupyterhub
```sh
EBEXTSLISTJUPYTERHUB=pamela-0.3.0,SQLAlchemy-1.2.12,alembic-1.0.1,requests-2.19.1,python-oauth2-1.1.0,Mako-1.0.7,python-editor-1.0.3,urllib3-1.24,certifi-2018.10.15,chardet-3.0.4,async_generator-1.10,jupyterhub-0.9.4
JUPYTERHUB_API_TOKEN=$TOKEN
JUPYTERHUB_API_URL=http://127.0.0.1:8081/hub/api
JUPYTERHUB_BASE_URL=/
JUPYTERHUB_CLIENT_ID=jupyterhub-user-etsxn
JUPYTERHUB_HOST=
JUPYTERHUB_OAUTH_CALLBACK_URL=/user/etsxn/oauth_callback
JUPYTERHUB_SERVICE_PREFIX=/user/etsxn/
JUPYTERHUB_USER=etsxn
LOGNAME=root
LS_COLORS=
```

local jupyter notebook
```sh
DISPLAY=localhost:12.0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOSTNAME=$HOSTNAME
LANGUAGE=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_ALL=en_US.UTF-8
LC_COLLATE=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_TIME=en_US.UTF-8
LOGNAME=etsxn
MAIL=/var/spool/mail/etsxn
XDG_RUNTIME_DIR=/run/user/28126
XDG_SESSION_ID=51058
SSH_CLIENT=$IPADDRESS 59974 22
SSH_CONNECTION=$IPADDRESS 59974 $IPADDRESS 22
SSH_TTY=/dev/pts/1
TERM=xterm-256color
```

3. I have tried with a local jupyter lab instance. and I can also see the ldap groups when executing "$id"

**Comment by ryogesh** [comment]
LOGNAME=root vs LOGNAME=etsxn; have to check why to users are different.

Can you also raise this on jupyterlab

**Comment by eylenth** [comment]
LOGNAME is also 'etsxn' on my local jupyter lab instance:

https://imgur.com/a/Lp9KQ7j

**Comment by eylenth** [comment]
hi @ryogesh 

have you already checked why the users are different on a jupyterhub session vs terminal/local session ?

**Comment by eylenth** [comment]
Hi, can someone take a look at this issue again?
It is still not solved

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/permission-denied-when-acl-is-configured/13036/1
