### ISSUE TITLE
Using SwarmSpawner can't pass arguments to change NB_USER NB_UID etc

### ISSUE THREAD

**Issue by m-alekseev** [jupyterhub/jupyterhub#2580]
I want to change user's parameters in spawning containers.

docker run **--user root -e NB_USER=username -e NB_UID 1234 -e NB_GID=4321** jupyter/base-notebook

So I need to pass highlighted arguments, but in a jupyterhub config file, when I spawn my notebooks. I tried many ways to do that but couldn't solve that problem.

For example I tried to use:
- `c.SwarmSpawner.extra_container_spec = {'args': [...]}`
- `c.SwarmSpawner.args ...`
- `c.SwarmSpawner.create_extra_kwargs ...`

Also tried everything of it inside a pre spawn function.

I would appreciate any help.

**Comment by ryogesh** [comment]
Can you try 
c.DockerSpawner.client_kwargs = {'key': 'Value'}

**Comment by m-alekseev** [comment]
I tried to pass some different args to client_kwargs in a prespawn hook.
@ryogesh that didn't help.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
