### ISSUE TITLE
.options_form() needs to be a static method or take two arguments

### ISSUE THREAD

**Issue by DeepHorizons** [jupyterhub/jupyterhub#2582]
When trying out the async callable `.options_form()` I found that I needed to have a funky function signature.

```python
@staticmethod
async def options_form(self):
    ...
```
or
```python
async def options_form(self, also_self):
    ...
```

Looking into it; its being called in [spawner.py](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/spawner.py#L350) as such: `self.options_form(self)`.

This seems a bit strange, this way allows for using unbound methods (lambda functions) but is that a typical use case?

**Comment by manics** [comment]
See discussion on https://github.com/jupyterhub/jupyterhub/pull/3357
