### ISSUE TITLE
ModuleNotFoundError: No module named 'Unicode'

### ISSUE THREAD

**Issue by MohammadHeydari** [jupyterhub/jupyterhub#2585]
I already install Text_Unicode by anaconda official channel commands but it doesn't work at all.

by from text_unidecode import Unicode command, it gives me this error:
ModuleNotFoundError: No module named 'Unicode'
what do you propose me to do?

**Comment by GeorgianaElena** [comment]
Hi @MohammadHeydari! Thanks for opening this issue and sorry for the late reply. Are you still experiencing this issue?
If so, can you please provide more info about the context in which you're seeing this error?

**Comment by GeorgianaElena** [comment]
Closing this as this is quite old and no updates have been provided. If you still have problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks! :sunflower:
