### ISSUE TITLE
Which REST API to use for running a notebook on JupyterHub?

### ISSUE THREAD

**Issue by kebab-mai-haddi** [jupyterhub/jupyterhub#2587]
I have a `jhub` setup on `kubernetes` and my users have written a notebook script there. I want to run those notebooks from my Airflow. Hence, I am looking for a way to run a notebook using some API.

**Comment by ramkrishnan8994** [comment]
@avisrivastava254084 - Did you find a solution for this? We have the same scenario. I found the command that triggers the notebook server spawning, but can't find one to trigger the notebook.
Server spawning - 
`curl -X POST -H "Authorization: token <token>" "http://127.0.0.1:8081/hub/api/users/<user>/server"`

@consideRatio, @manics - Can you help?

**Comment by consideRatio** [comment]
There is a REST API to interact with jupyterhub, and JupyterHub interactions include spawning user servers. But, that is beyond whatever goes on in the user server. How to actually control what you do within the user server will relate to how the JupyterHub is deployed as well.

Assuming it was setup with zero-to-jupyterhub-k8s, then you could perhaps do a `kubectl exec` to do something, like using `nbconvert`.

To conclude, I don't know, and I think it is quite complicated to do this in a reliable manner. There are projects like Papermill to automate running of notebooks though.

https://medium.com/netflix-techblog/scheduling-notebooks-348e6c14cfd6
