### ISSUE TITLE
Named server string sanitization

### ISSUE THREAD

**Issue by vilhelmen** [jupyterhub/jupyterhub#2589]
**Describe the bug**
I unleashed a sysadmin on my 1.0 dev system and he immediately broke it. Named server name sanitization seems to be missing, resulting in all sorts of odd behavior that may be more of a Kubespawner problem.

**To Reproduce**
<img width="307" alt="image" src="https://user-images.githubusercontent.com/5308250/58509004-1ffa1180-815b-11e9-8be1-97ad29ef96eb.png">

Create a named server with symbols in the name and wait for spawn. Capital letters also throw a bit of a wrench into things name-wise (maybe just a Kubespawner setting I don't know?). You also seem to be able to submit the named server form without providing a name, resulting in an immediate 404.

**Expected behavior**
Error message forbidding the name / correct routing

**Screenshots**
<img width="397" alt="image" src="https://user-images.githubusercontent.com/5308250/58509198-939c1e80-815b-11e9-8531-fe651d99d2b2.png">

<img width="553" alt="image" src="https://user-images.githubusercontent.com/5308250/58508981-0d7fd800-815b-11e9-8376-f800dd110b4c.png">

Capital letters get formatted as hex with dashes, which is a little funky. Perhaps a lower() is called for:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/5308250/58509384-102efd00-815c-11e9-9fa5-04896ea2f749.png">

**Desktop (please complete the following information):**
 - MacOS
 - Safari
 - 12.1.1
 - not that it matters

**Comment by vilhelmen** [comment]
I think the empty name might be a bad url redirect, assuming the empty string is supposed to redirect to the default session. I'm seeing the empty string form submission directing to `hub/spawn/waskd6/` instead of `hub/spawn` which brings up the spawner page.

Perhaps the empty name submission should redirect to `hub/`, which will either jump to the spawner page or the user's default server.

I have the time now so I might try and punch together some basic name sanitization in the API layer. Any opinions on valid regex? I feel like we should support capital letters, but I'm not super familiar with how the named server system works with spawners, so maybe that's not reasonable? I'd suggest `[a-zA-Z0-9].*` but I'm suddenly aware of how English-centric that is and how it's important to try and not do that anymore. If there's a username regex, I may copy that.

**Comment by manics** [comment]
https://github.com/jupyterhub/jupyterhub/pull/2594 fixed some problems. Escaping or server names most likely needs ot be handled at the spawner level since each spawner has different requirements on valid names.
