### ISSUE TITLE
Authenticate with external REST API 

### ISSUE THREAD

**Issue by brayanrodbajo** [jupyterhub/jupyterhub#2596]
How can I authenticate with an external REST API (in this case the one from [https://orcid.org](https://orcid.org)) instead of PAM Authenticator?

I have the client_id and the api_token data. 

Thank you in advance.

**Comment by GeorgianaElena** [comment]
Hi @brayanrodbajo ! Please checkout [OAuthenticator](https://github.com/jupyterhub/oauthenticator), especially the [generic implementation](https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/generic.py) that can be used with any provider.
In the project's description you can find some example setups for the authentication services currently supported by *OAuthenticator*. The setup should be similar for *GenericOAuthenticator*.
Hope this helps.
