### ISSUE TITLE
how do you connect a javascript app to a jupyterhub kernel?

### ISSUE THREAD

**Issue by bionicles** [jupyterhub/jupyterhub#2597]
We want to embed a notebook type thing in our app but @nteract/notebook-app-component is not finished, jupyterlab is heavy and takes over the whole screen, thebelab is also heavy (1.6Mb) ... these solutions don't work for a simple web app to embed a notebook kernel right now

How do you connect a javascript app to a jupyterhub kernel? 

This might be a nice docs improvement. We can handle the ui easily, but it's not clear how to connect to the remote kernel.

**Comment by ryanlovett** [comment]
Does [nbinteract](https://www.nbinteract.com/) do what you want?

**Comment by bionicles** [comment]
it looks cool but no, we wish to allow users to edit text areas in html and send the contents to a remote kernel. Like a super minimal jupyter notebook cell built only with javascript/html/css

**Comment by bionicles** [comment]
is it possible to interact with kernels via the REST service?

**Comment by ryogesh** [comment]
Looks like you need notebook kernel APIs? 

https://github.com/jupyter/jupyter/wiki/Jupyter-Notebook-Server-API

**Comment by bionicles** [comment]
@ryogesh how do you run code with this api?

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
