### ISSUE TITLE
Dev install and pyproject.toml

### ISSUE THREAD

**Issue by jtpio** [jupyterhub/jupyterhub#2599]
In a fresh conda environment (using Python 3.7.3 and pip 19.1) after running `python -m pip install -e .`:

```
ERROR: Error installing 'file:///home/jtp/git/jupyterhub': editable mode is not
supported for pyproject.toml-style projects. pip is processing this project as
pyproject.toml-style because it has a pyproject.toml file. Since the project
has a setup.py and the pyproject.toml has no "build-backend" key for the
"build_system" value, you may pass --no-use-pep517 to opt out of
pyproject.toml-style processing. See PEP 517 for details on
pyproject.toml-style projects.
```

Using the `--no-use-pep517` flag as mentioned in the error message solves it: 

`python -m pip install -e . --no-use-pep517`

Maybe something that could be added to the dev instructions?

**Comment by manics** [comment]
This currently works.... no idea if it was fixed in JupyterHub or Python/Pip :smile:
