### ISSUE TITLE
Spawn error first installation

### ISSUE THREAD

**Issue by RevivedPicard** [jupyterhub/jupyterhub#2600]
Hello,

I'm new to this kind of things. In my company we have a unix remote server with python/anaconda installed and we would like to switch from jupyter-lab to jupyterhub to be able to let many users login and use jupyter at the same time.

I'm trying to get used to the installation using my account (taht is not admin and is accessed through cyberark).
I installed with conda jupyterhub, create the config file and set the ip address (JupyterHub.ip) and port (JupyterHub.port) so to be able to connect via web browser from the user client.
I have opened the firewall route to this port correctly.

Just to try i have set the authenticator to dummy so to be able to connect using whatever username and pwd.

Using my account i run 
`jupyterhub`

this is the ouput

`[pas.datascience_dev@devrmdatasci01 .jupyter]$ jupyterhub
[I 2019-06-04 11:43:05.522 JupyterHub app:2120] Using Authenticator: jupyterhub.auth.DummyAuthenticator-1.0.0
[I 2019-06-04 11:43:05.522 JupyterHub app:2120] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.0.0
[I 2019-06-04 11:43:05.526 JupyterHub app:1257] Loading cookie_secret from /home/pas.datascience_dev/.jupyter/jupyterhub_cookie_secret
[I 2019-06-04 11:43:05.557 JupyterHub proxy:460] Generating new CONFIGPROXY_AUTH_TOKEN
[W 2019-06-04 11:43:05.559 JupyterHub app:1532] No admin users, admin interface will be unavailable.
[W 2019-06-04 11:43:05.559 JupyterHub app:1534] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2019-06-04 11:43:05.559 JupyterHub app:1563] Not using whitelist. Any authenticated user will be allowed.
[I 2019-06-04 11:43:05.611 JupyterHub app:2337] Hub API listening on http://127.0.0.1:8081/hub/
[W 2019-06-04 11:43:05.613 JupyterHub proxy:642] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2019-06-04 11:43:05.613 JupyterHub proxy:645] Starting proxy @ http://10.207.2.10:8689/
11:43:06.217 - info: [ConfigProxy] Proxying http://10.207.2.10:8689 to (no default)
11:43:06.220 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[I 2019-06-04 11:43:06.684 JupyterHub proxy:319] Checking routes
[I 2019-06-04 11:43:06.685 JupyterHub proxy:399] Adding default route for Hub: / => http://127.0.0.1:8081
[I 2019-06-04 11:43:06.688 JupyterHub app:2422] JupyterHub is now running at http://10.207.2.10:8689/`

I copy the url and paste it to my local desktop browser and correctly get the login page.
I insert user: "aaa" and pwd "abc" (i'm using the dummy auth so it should be accepted) but i get spqwn failed with this log:

`[I 2019-06-04 11:46:11.157 JupyterHub base:663] User logged in: aaa
[I 2019-06-04 11:46:11.160 JupyterHub log:174] 302 POST /hub/login?next= -> /hub/spawn (aaa@127.0.0.1) 10.15ms
[E 2019-06-04 11:46:11.243 JupyterHub user:626] Unhandled error starting aaa's server: 'getpwnam(): name not found: aaa'
[I 2019-06-04 11:46:11.261 JupyterHub log:174] 302 GET /hub/spawn -> /hub/spawn-pending/aaa (aaa@127.0.0.1) 56.58ms
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /data/pyconda36/lib/python3.6/site-packages/jupyterhub/handlers/base.py:697> exception=KeyError('getpwnam(): name not found: aaa',)>
Traceback (most recent call last):
  File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 889, in spawn_single_user
    timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
  File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 807, in finish_user_spawn
    await spawn_future
  File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/user.py", line 642, in spawn
    raise e
  File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/user.py", line 546, in spawn
    url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
  File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/spawner.py", line 1377, in start
    env = self.get_env()
  File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/spawner.py", line 1326, in get_env
    env = self.user_env(env)
  File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/spawner.py", line 1313, in user_env
    home = pwd.getpwnam(self.user.name).pw_dir
KeyError: 'getpwnam(): name not found: aaa'
[E 2019-06-04 11:46:11.344 JupyterHub pages:284] Previous spawn for aaa failed: 'getpwnam(): name not found: aaa'
[E 2019-06-04 11:46:11.350 JupyterHub log:166] {
      "Cookie": "jupyterhub-hub-login=[secret]; user-id=[secret]; csrf-token=[secret]; _xsrf=[secret]; username-10-207-2-10-8687=[secret]; username-10-207-2-10-8686=[secret]; jupyterhub-session-id=[secret]",
      "Accept-Language": "it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://10.207.2.10:8689/hub/login",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "Cache-Control": "max-age=0",
      "Connection": "close",
      "Host": "10.207.2.10:8689"
    }
[E 2019-06-04 11:46:11.350 JupyterHub log:174] 500 GET /hub/spawn-pending/aaa (aaa@127.0.0.1) 12.16ms`

If i try to login using the username from which i'm launching the jupyterhub so user = "pas.datascience_dev" and use random pwd i get to a charging bar but then spawn failed with this error

`Spawn failed: Server at http://127.0.0.1:55345/user/pas.datascience_dev/ didn't respond in 30 seconds`

and this log

`[I 2019-06-04 11:47:16.755 JupyterHub base:663] User logged in: pas.datascience_dev
[I 2019-06-04 11:47:16.757 JupyterHub log:174] 302 POST /hub/login?next= -> /hub/spawn (pas.datascience_dev@127.0.0.1) 8.06ms
[I 2019-06-04 11:47:16.822 JupyterHub spawner:1387] Spawning jupyterhub-singleuser --port=55345
Failed to set groups [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/data/pyconda36/bin/jupyterhub-singleuser", line 8, in <module>
    from jupyterhub.singleuser import main
  File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 41, in <module>
    from notebook.notebookapp import (
  File "/data/pyconda36/lib/python3.6/site-packages/notebook/notebookapp.py", line 40, in <module>
    ioloop.install()
  File "/data/pyconda36/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'
[I 2019-06-04 11:47:17.801 JupyterHub log:174] 302 GET /hub/spawn -> /hub/spawn-pending/pas.datascience_dev (pas.datascience_dev@127.0.0.1) 1008.91ms
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /data/pyconda36/lib/python3.6/site-packages/jupyterhub/handlers/base.py:697> exception=HTTPError()>
Traceback (most recent call last):
  File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 889, in spawn_single_user
    timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 922, in spawn_single_user
    % (status, spawner._log_name),
tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=1]. The logs for pas.datascience_dev may contain details.)
[W 2019-06-04 11:47:48.040 JupyterHub user:678] pas.datascience_dev's server never showed up at http://127.0.0.1:55345/user/pas.datascience_dev/ after 30 seconds. Giving up
[E 2019-06-04 11:47:48.055 JupyterHub gen:974] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /data/pyconda36/lib/python3.6/site-packages/jupyterhub/handlers/base.py:800> exception=TimeoutError("Server at http://127.0.0.1:55345/user/pas.datascience_dev/ didn't respond in 30 seconds",)> after timeout
    Traceback (most recent call last):
      File "/data/pyconda36/lib/python3.6/site-packages/tornado/gen.py", line 970, in error_callback
        future.result()
      File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 807, in finish_user_spawn
        await spawn_future
      File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/user.py", line 654, in spawn
        await self._wait_up(spawner)
      File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/user.py", line 701, in _wait_up
        raise e
      File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/user.py", line 669, in _wait_up
        http=True, timeout=spawner.http_timeout, ssl_context=ssl_context
      File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/utils.py", line 234, in wait_for_http_server
        timeout=timeout,
      File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/utils.py", line 177, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:55345/user/pas.datascience_dev/ didn't respond in 30 seconds

[I 2019-06-04 11:47:48.058 JupyterHub log:174] 200 GET /hub/api/users/pas.datascience_dev/server/progress (pas.datascience_dev@127.0.0.1) 30176.86ms`

What I'm missing or doing wrong ?

After i'll be able to use this i will give the whole package to systems admin and make them install it as root so to be able to manage multiple users

**Comment by GeorgianaElena** [comment]
Hi @RevivedPicard ! The spawner I see in the logs is [LocalProcessSpawner](https://jupyterhub.readthedocs.io/en/stable/api/spawner.html#localprocessspawner), which is the default spawner for JupyterHub. This spawner requires the authenticated users to also exist as UNIX users (this is why the login woks, but the spawn fails).
The best spawner to use with  *DummyAuthenticator* for testing purposes is [SimpleLocalProcessSpawner](https://github.com/jupyterhub/simplespawner).
You can configure JupyterHub to use this spawner adding this line to your jupyterhub_config.py:
```
c.JupyterHub.spawner_class = 'simplespawner.SimpleLocalProcessSpawner'
```
or just
```
c.JupyterHub.spawner_class = "simple"
```
If you're using jupyterhub 1.0.0
Hope this helps.

**Comment by RevivedPicard** [comment]
> Hi @RevivedPicard ! The spawner I see in the logs is [LocalProcessSpawner](https://jupyterhub.readthedocs.io/en/stable/api/spawner.html#localprocessspawner), which is the default spawner for JupyterHub. This spawner requires the authenticated users to also exist as UNIX users (this is why the login woks, but the spawn fails).
> The best spawner to use with _DummyAuthenticator_ for testing purposes is [SimpleLocalProcessSpawner](https://github.com/jupyterhub/simplespawner).
> You can configure JupyterHub to use this spawner adding this line to your jupyterhub_config.py:
> 
> ```
> c.JupyterHub.spawner_class = 'simplespawner.SimpleLocalProcessSpawner'
> ```
> 
> or just
> 
> ```
> c.JupyterHub.spawner_class = "simple"
> ```
> 
> If you're using jupyterhub 1.0.0
> Hope this helps.

Hello and thanks.

I've tryed as you sayd, but still no luck.

`[I 2019-06-05 11:18:52.232 JupyterHub base:663] User logged in: aaa
[I 2019-06-05 11:18:52.235 JupyterHub log:174] 302 POST /hub/login?next= -> /hub/spawn (aaa@10.25.121.227) 10.23ms
[I 2019-06-05 11:18:52.287 JupyterHub spawner:1387] Spawning jupyterhub-singleuser --port=59044
Traceback (most recent call last):
  File "/data/pyconda36/bin/jupyterhub-singleuser", line 7, in <module>
    from jupyterhub.singleuser import main
  File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 41, in <module>
    from notebook.notebookapp import (
  File "/data/pyconda36/lib/python3.6/site-packages/notebook/notebookapp.py", line 40, in <module>
    ioloop.install()
  File "/data/pyconda36/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'
[I 2019-06-05 11:18:53.268 JupyterHub log:174] 302 GET /hub/spawn -> /hub/spawn-pending/aaa (aaa@10.25.121.227) 1007.86ms
[I 2019-06-05 11:18:53.323 JupyterHub pages:303] aaa is pending spawn
[I 2019-06-05 11:18:53.327 JupyterHub log:174] 200 GET /hub/spawn-pending/aaa (aaa@10.25.121.227) 9.99ms
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /data/pyconda36/lib/python3.6/site-packages/jupyterhub/handlers/base.py:697> exception=HTTPError()>
Traceback (most recent call last):
  File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 889, in spawn_single_user
    timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 922, in spawn_single_user
    % (status, spawner._log_name),
tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=1]. The logs for aaa may contain details.)
[W 2019-06-05 11:19:22.388 JupyterHub user:678] aaa's server never showed up at http://127.0.0.1:59044/user/aaa/ after 30 seconds. Giving up
[E 2019-06-05 11:19:22.423 JupyterHub gen:974] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /data/pyconda36/lib/python3.6/site-packages/jupyterhub/handlers/base.py:800> exception=TimeoutError("Server at http://127.0.0.1:59044/user/aaa/ didn't respond in 30 seconds",)> after timeout
    Traceback (most recent call last):
      File "/data/pyconda36/lib/python3.6/site-packages/tornado/gen.py", line 970, in error_callback
        future.result()
      File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 807, in finish_user_spawn
        await spawn_future
      File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/user.py", line 654, in spawn
        await self._wait_up(spawner)
      File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/user.py", line 701, in _wait_up
        raise e
      File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/user.py", line 669, in _wait_up
        http=True, timeout=spawner.http_timeout, ssl_context=ssl_context
      File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/utils.py", line 234, in wait_for_http_server
        timeout=timeout,
      File "/data/pyconda36/lib/python3.6/site-packages/jupyterhub/utils.py", line 177, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:59044/user/aaa/ didn't respond in 30 seconds`

I add on the side note that i have opened only few ports towards this machine and cannot open random port. Maybe my local web browser is trying to connect to random port that is not opened and so it does not spwan?

**Comment by RevivedPicard** [comment]
Ok managed to resolve this by reinstalling configurable-http-proxy using conda and not npm, maybe some dependencies was lacking. Thanks all

**Comment by GeorgianaElena** [comment]
Excellent! Happy it worked!

**Comment by ssharma94** [comment]
This is another solution if you are using docker image. See Dockerfile working example:

```FROM jupyterhub/jupyterhub

RUN pip install notebook

ENV USERNAME=admin
ENV PASSWORD=admin

RUN useradd -m -p $(openssl passwd -1 ${PASSWORD}) -s /bin/bash -G sudo ${USERNAME}
USER admin
WORKDIR /home/admin```

**Comment by thiagola92** [comment]
@ssharma94 thank you!
I just ran `pip install notebook` and worked

**Comment by mukhendra** [comment]
Hi All,
While acessing jupyter hub in web browser I'm also getting error "Your server is starting up.
You will be redirected automatically when it's ready for you" and "Spawn failed: Server at http://127.0.0.1:39684/user/username/ didn't respond in 30 seconds" 
Can you please help us.

**Comment by jdougal84** [comment]
I'm running JupyterHub Version 1.1.0 and these steps worked for me:
- conda install -c conda-forge jupyterhub
-  conda install notebook

Generate a config file (follow the guide for default location)
- jupyterhub --generate-config

Update these lines in the jupyterhub_config.py file
- c.Spawner.notebook_dir = '/notebooks'
- c.JupyterHub.spawner_class = 'jupyterhub.spawner.SimpleLocalProcessSpawner'

**Comment by SpecialAll** [comment]
> I'm running JupyterHub Version 1.1.0 and these steps worked for me:
> 
> * conda install -c conda-forge jupyterhub
> * conda install notebook
> 
> Generate a config file (follow the guide for default location)
> 
> * jupyterhub --generate-config
> 
> Update these lines in the jupyterhub_config.py file
> 
> * c.Spawner.notebook_dir = '/notebooks'
> * c.JupyterHub.spawner_class = 'jupyterhub.spawner.SimpleLocalProcessSpawner'

Could you please help me solve this problem？
![image](https://user-images.githubusercontent.com/46620932/112477196-b0342c80-8dad-11eb-86ec-f1a2c021eb06.png)
