### ISSUE TITLE
Redirect loop trying to oauth with ORCiD 

### ISSUE THREAD

**Issue by brayanrodbajo** [jupyterhub/jupyterhub#2602]
I am trying to authenticate with ORCiD API. So, I wrote my jupyterhub_config.py as follows: 
```
c.JupyterHub.pid_file = '/etc/jupyterhub/jupyterhub-run.pid'

service_name = 'jupyterhub'
service_port = 8000
group_name = 'shared'


c.JupyterHub.services = [
    {
        'name': service_name,
        'url': 'http://127.0.0.1:{}'.format(service_port),
        'command': ['jupyterhub-singleuser', '--group=shared', '--debug', '--allow-root'],
    }
]

from oauthenticator.generic import GenericOAuthenticator


c.JupyterHub.authenticator_class = 'oauthenticator.generic.GenericOAuthenticator'
c.OAuthenticator.client_id = '...' # oauth2 client id for your app
c.OAuthenticator.client_secret = '...' # oauth2 client secret for your app
c.GenericOAuthenticator.token_url = 'https://orcid.org/oauth/token' # oauth2 provider's token url
c.GenericOAuthenticator.userdata_url = 'https://sandbox.orcid.org/oauth/userinfo' # oauth2 provider's endpoint with user data
c.GenericOAuthenticator.userdata_method = 'GET' # method used to request user data endpoint
c.GenericOAuthenticator.userdata_params = {"Accept": "application/json"} # params to send for userdata endpoint
```
However, when I run the server, I got: 
```
[I 2019-06-06 00:05:56.600 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:181.49.81.107) 1.08ms
[I 2019-06-06 00:05:56.718 JupyterHub log:174] 302 GET /hub/ -> /hub/login (@::ffff:181.49.81.107) 0.95ms
[I 2019-06-06 00:05:56.951 JupyterHub log:174] 200 GET /hub/login (@::ffff:181.49.81.107) 8.80ms
[I 2019-06-06 00:05:58.812 JupyterHub oauth2:100] OAuth redirect: 'http://50.116.16.56:8000/hub/oauth_callback'
[I 2019-06-06 00:05:58.814 JupyterHub log:174] 302 GET /hub/oauth_login?next= -> ?state=[secret]&response_type=code&redirect_uri=http%3A%2F%2F50.116.16.56%3A8000%2Fhub%2Foauth_callback&client_id=APP-...(@::ffff:181.49.81.107) 2.20ms
[I 2019-06-06 00:05:58.946 JupyterHub oauth2:100] OAuth redirect: 'http://50.116.16.56:8000/hub/oauth_callback'
[I 2019-06-06 00:05:58.947 JupyterHub log:174] 302 GET /hub/oauth_login?state=[secret]&response_type=code&redirect_uri=http%3A%2F%2F50.116.16.56%3A8000%2Fhub%2Foauth_callback&client_id=APP-...-> ?state=[secret]&response_type=code&redirect_uri=http%3A%2F%2F50.116.16.56%3A8000%2Fhub%2Foauth_callback&client_id=APP-...(@::ffff:181.49.81.107) 1.76ms
[I 2019-06-06 00:05:59.199 JupyterHub oauth2:100] OAuth redirect: 'http://50.116.16.56:8000/hub/oauth_callback'
```

Can you help me with this redirect problem, please?

**Comment by GeorgianaElena** [comment]
@brayanrodbajo, are you setting these env vars?
``` 
OAUTH2_TOKEN_URL # the same as token_url param
OAUTH2_AUTHORIZE_URL # oauth2 provider's authorization endpoint
```
The discussion [here](https://github.com/jupyterhub/oauthenticator/issues/107) may help.

**Comment by brayanrodbajo** [comment]
Yes, I set both of them. 
The only thing I see is the use of LocalGenericOAuthenticator. When I have to use GenericOAuthenticator or LocalGenericOAuthenticator?

**Comment by GeorgianaElena** [comment]
[LocalGenericOAuthenticator](https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/generic.py#L167) lets you combine the GenericOAuthenticator with [LocalAuthenticator](https://jupyterhub.readthedocs.io/en/stable/api/auth.html#localauthenticator) (that allows local system user creation).

If you're using the latest JupyterHub version, this [Discourse thread](https://discourse.jupyter.org/t/genericoauthenticator-wont-read-env-vars-in-1-0/984) may also help.

**Comment by brayanrodbajo** [comment]
Thank you so much for responding. It works!
However, I have a problem:

I am working on a test server (without HTTPS nor DNS). I am doing it with the following userinfo endpoint: https://sandbox.orcid.org/oauth/userinfo. For this purpose, I created a Sandbox API Client and register this app: http://50.116.16.56:8000 with the following redirect_uri: http://50.116.16.56:8000/hub. 

Also, I modified the jupyterhub_config.py as follows: 

```
from oauthenticator.generic import GenericOAuthenticator



c.JupyterHub.authenticator_class = GenericOAuthenticator
c.JupyterHub.authenticator_class.login_handler._OAUTH_AUTHORIZE_URL = "https://sandbox.orcid.org/oauth/authorize"
c.JupyterHub.authenticator_class.login_handler._OAUTH_TOKEN_URL = "https://sandbox.orcid.org/oauth/token"
c.OAuthenticator.client_id = 'APP-M29Z8EEBM7HAB10J' # oauth2 client id for your app
c.OAuthenticator.client_secret = '1e49a96d-7794-41b0-b02e-b30162fd76e0' # oauth2 client secret for your app
c.GenericOAuthenticator.token_url = 'https://sandbox.orcid.org/oauth/token' # oauth2 provider's token url
c.GenericOAuthenticator.userdata_url = 'https://sandbox.orcid.org/oauth/userinfo' # oauth2 provider's endpoint with user data
c.GenericOAuthenticator.userdata_method = 'GET' # method used to request user data endpoint
c.GenericOAuthenticator.userdata_params = {"Accept": "application/json"} # params to send for userdata endpoint
c.GenericOAuthenticator.username_key = 'PRIMARY_EMAIL'
```



However, when Jupyterhub Server redirects to https://sandbox.orcid.org/oauth/authorize?state=eyJzdGF0ZV9pZCI6ICJhYzVkMzJiNGEzZjU0ODJlOTBiMGQzYjJiNzkwNGFlYSIsICJuZXh0X3VybCI6ICIifQ%3D%3D&client_id=APP-M29Z8EEBM7HAB10J&response_type=code&redirect_uri=http%3A%2F%2F50.116.16.56%3A8000%2Fhub%2Foauth_callback, I get the following error: 
There has been a problem with the server. If this problem persists, please contact support.

And when I am not logged in sandbox.orcid.org, the following: 
Please check your client id, scopes and redirect URIs.

PD: Does any of you know when the service is running in production what is the userinfo endpoint URL to connect to the ORCiD API?


Thank you in advance.

**Comment by manics** [comment]
@brayanrodbajo 
I haven't used Jupyter with ORCID, but I've got an experimental application that uses public ORCID OAuth.
These are the URLs I used https://gitlab.com/openmicroscopy/incubator/omero-oauth/blob/8251640cb9468a47191b512ff35a24ead84d87d3/multi-example.yaml#L74-89
And this is how I parsed the userinfo: https://gitlab.com/openmicroscopy/incubator/omero-oauth/blob/8251640cb9468a47191b512ff35a24ead84d87d3/omero_oauth/providers.py#L148-168
I havne't tested this recently, but maybe it will help you?

**Comment by GeorgianaElena** [comment]
Hi @brayanrodbajo! Are you still experiencing this issue?

**Comment by brayanrodbajo** [comment]
Hi, @GeorgianaElena. No, it is already solved. Thanks

**Comment by GeorgianaElena** [comment]
Awesome @brayanrodbajo :confetti_ball:. Did @manics suggestion helped? It's really useful to know how the issue was solved for folks that encounter similar problems.
I'll close this issue now, but feel free to open a new one if you have any other questions :)
