### ISSUE TITLE
JupyterHub with Lab start in ~/jupyterlab dir, but with navigation access to homedir

### ISSUE THREAD

**Issue by NumesSanguis** [jupyterhub/jupyterhub#2603]
# Situation
I want my JupyterHub to start with JupyterLab and give users access to their homedir, but the default folder should be `~/jupyterhub` (which every user has in their homedir).
Therefore, it seems like I have to set the following:
```
c.Spawner.default_url = '/lab/jupyterhub'  # start the spawner in folder jupyterhub with JupyterLab
c.Spawner.notebook_dir = '~/'  # but allow access to their homedir
```

However, that gives the error:
```
Path Not Found The path: /user/*user*/lab/jupyterhub was not found. JupyterLab redirected to: /user/*user*/
```

If I remove the `/lab` part, I get a 404 after logging in as a user. I also tried a bunch of other modifications, but those didn't work either.
# Question
**How do I set this configuration correctly?**

# System:
- Ubuntu 18.04 server
- JupyterHub: 1.0.0 at: `/opt/miniconda3/bin/jupyterhub`
- Jupyter: 4.4.0
- JuputerHub config: `/etc/jupyterhub/jupyterhub_config.py`
- Using miniconda (conda 4.6.14) at: `/opt/miniconda3`

# jupyterhub_config.py
```
## The URL the single-user server should start in.
#  
#  `{username}` will be expanded to the user's username
#  
#  Example uses:
#  
#  - You can set `notebook_dir` to `/` and `default_url` to `/tree/home/{username}` to allow people to
#    navigate the whole filesystem from their notebook server, but still start in their home directory.
#  - Start with `/notebooks` instead of `/tree` if `default_url` points to a notebook instead of a directory.
#  - You can set this to `/lab` to have JupyterLab start by default, rather than Jupyter Notebook.
c.Spawner.default_url = '/lab/jupyterhub'

...

## Path to the notebook directory for the single-user server.
#  
#  The user sees a file listing of this directory when the notebook interface is
#  started. The current interface does not easily allow browsing beyond the
#  subdirectories in this directory's tree.
#  
#  `~` will be expanded to the home directory of the user, and {username} will be
#  replaced with the name of the user.
#  
#  Note that this does *not* prevent users from accessing files outside of this
#  path! They can do so with many other means.
c.Spawner.notebook_dir = '~/'
```

**Comment by ryogesh** [comment]
Can you try

c.Spawner.default_url = '/lab

/tree launches notebook (default), /lab launches lab

Refer: https://jupyterlab.readthedocs.io/en/stable/user/jupyterhub.html

**Comment by NumesSanguis** [comment]
@ryogesh Thank you for your input.

`c.Spawner.default_url = '/lab` will indeed start the lab, but it will by default open the `~/` home directory, because of `c.Spawner.notebook_dir = '~/'`.
What I would like to know is how can I make JupyterLab start in `~/jupyterhub`, while still allowing access to the user's home directory.
Therefore, I cannot set `c.Spawner.notebook_dir = '~/jupyterhub'`, because the user won't be able to (easily) navigate to the parent directory (`~/`).

**Comment by minrk** [comment]
I think you might want `c.Spawner.default_url = '/lab/tree/jupyterhub'` That's the URL for jupyterlab to open a directory. `/lab/jupyterhub` I don't think is valid.

**Comment by NumesSanguis** [comment]
@minrk that seems to be the right setting, thank you!
