### ISSUE TITLE
access other servers

### ISSUE THREAD

**Issue by mathematicalmichael** [jupyterhub/jupyterhub#2604]
upgraded to jupyterhub 1.0 recently and discovered that some of the new authentication features don't actually allow an admin user to access other users' servers. 
1. log in as admin
2. visit admin page `/hub/admin`
3. start someone else's server
4. access server (enabled via `admin_access = True`

There's a "request permission" page that leads to a 403 error upon hitting "accept".
https://imgur.com/47C417e
![img](https://imgur.com/47C417e)

**Comment by ryogesh** [comment]
Can you add c.JupyterHub.allow_named_servers = True in your config and try

**Comment by mathematicalmichael** [comment]
I had it in there. Actually a similar problem was occurring wherein if a user made themselves a second server, the ports would conflict because the container images have the same name, and the error would show up. @ryogesh

**Comment by ryogesh** [comment]
Did you try using Docker host networking (--network host) ?

**Comment by mathematicalmichael** [comment]
I think `c.NotebookApp.allow_remote_access = True` or `c.DockerSpawner.extra_host_config = {'network_mode': network_name}` did the trick.
