### ISSUE TITLE
Downloading html file from file explorer opens file in new tab instead of downloading

### ISSUE THREAD

**Issue by kevmk04** [jupyterhub/jupyterhub#2606]
I have an .html file that was generated by the plotly offline.iplot function. My typical workflow is to create the file from a notebook and download the html file to share with colleagues.  On an existing jupyterhub/jupyterlab install this functionality works fine.  It downloads directly to my local download folder.  

I recently setup a TLJH install on a new server.  When I try to download the same .html file (or any html file for that matter), it opens the file in a new browser tab instead of downloading it.  It also seems to try to do this with other file extensions and then downloads them normally, but it does flash open a new tab briefly before downloading. The older install does not exhibit that same flash of a new tab for other files types.  

I'm using Chrome as the browser.  

**Old jupyterhub/jupyterlab setup where download works:**
jupyterhub version: 0.8.1
jupyterlab version: 0.35.4
notebook version: 5.4.1
Installed manually 

**New jupyterhub/jupyterlab setup where download does not work:**
jupyterhub version: 1.0
jupyterlab version: 0.35.4
notebook version: 5.7.8
Installed with TLJH installer

I'm unsure if this is a jupyterlab issue, something with TLJH install, or something else entirely.

**Comment by wqh17101** [comment]
why you close this? @kevmk04 
how to fix it?

**Comment by kevmk04** [comment]
I closed the issue because the problem is actually a jupyterlab problem not a hub problem.  I have an open issue in the jupyterlab GitHub for this problem.

**Comment by wqh17101** [comment]
@kevmk04 all right

**Comment by kevmk04** [comment]
@wqh17101 Release 1.0.5 of JupyterLab resolves this issue.

**Comment by wqh17101** [comment]
well , let`s see it @kevmk04

**Comment by wqh17101** [comment]
@kevmk04  all right , it works. Do you know what changes had been done to fix it?

**Comment by kevmk04** [comment]
@wqh17101 Look at pull [6686](https://github.com/jupyterlab/jupyterlab/pull/6686) in the JupyterLab repository
