### ISSUE TITLE
500: Internal server error

### ISSUE THREAD

**Issue by payal4143** [jupyterhub/jupyterhub#2608]
Hi Team,
I am trying to install jupyterhub on an ec2 instance. I have done below changes in config file:

c.JupyterHub.authenticator_class = 'oauthenticator.GitHubOAuthenticator'
c.GitHubOAuthenticator.oauth_callback_url = 'https://18.221.201.93:8000/hub/oauth_callback'
c.GitHubOAuthenticator.client_id = '3533e7b5ee337a755a50'
c.GitHubOAuthenticator.client_secret = 'd07b13374d4287a3c08c3c0975e404f1929b4446'
c.LocalAuthenticator.create_system_users = True
c.Authenticator.whitelist = {'payal4143', 'Adu'}
c.Authenticator.admin_users = {'payal4143'}
c.Spawner.notebook_dir = '/home/ubuntu/Notebooks'	
c.JupyterHub.ssl_cert = 'mycert.pem'
c.JupyterHub.ssl_key = 'mykey.key'
c.JupyterHub.cookie_secret_file = '/home/ubuntu/jupyterhub_cookie_secret'
c.JupyterHub.proxy_cmd = ['/usr/bin/configurable-http-proxy']

I have taken reference from link : https://github.com/jupyterhub/jupyterhub/wiki/Installation-of-Jupyterhub-on-remote-server

I am new to this, kindly help me to solve the issue.

**Comment by ryogesh** [comment]
Can you run in debug mode and check / share  the logs for error messages

Refer: https://github.com/jupyterhub/jupyterhub/wiki/Debug-Jupyterhub
https://jupyterhub.readthedocs.io/en/stable/api/app.html

**Comment by payal4143** [comment]
ubuntu@ip-172-31-9-59:~$ jupyterhub -f /home/ubuntu/jupyterhub_config.py --debug
[D 2019-06-13 09:32:15.059 JupyterHub application:555] Looking for /home/ubuntu/jupyterhub_config in /home/ubuntu
[D 2019-06-13 09:32:15.059 JupyterHub application:577] Loaded config file: /home/ubuntu/jupyterhub_config.py
[W 2019-06-13 09:32:15.072 JupyterHub app:626] JupyterHub.proxy_cmd is deprecated in JupyterHub 0.8, use ConfigurableHTTPProxy.command
[I 2019-06-13 09:32:15.072 JupyterHub app:2120] Using Authenticator: oauthenticator.github.GitHubOAuthenticator-0.8.2
[I 2019-06-13 09:32:15.072 JupyterHub app:2120] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.0.0
[D 2019-06-13 09:32:15.073 JupyterHub app:2073] Could not load pycurl: No module named 'pycurl'
    pycurl is recommended if you have a large number of users.
[I 2019-06-13 09:32:15.074 JupyterHub app:1257] Loading cookie_secret from /home/ubuntu/jupyterhub_cookie_secret
[D 2019-06-13 09:32:15.074 JupyterHub app:1424] Connecting to db: sqlite:///jupyterhub.sqlite
[D 2019-06-13 09:32:15.089 JupyterHub orm:749] database schema version found: 4dc2d5a8c53c
[I 2019-06-13 09:32:15.094 JupyterHub proxy:460] Generating new CONFIGPROXY_AUTH_TOKEN
[D 2019-06-13 09:32:15.131 JupyterHub app:1910] Loading state for payal4143 from db
[D 2019-06-13 09:32:15.132 JupyterHub app:1910] Loading state for adu from db
[D 2019-06-13 09:32:15.132 JupyterHub app:1926] Loaded users:
    payal4143 admin
         adu
[I 2019-06-13 09:32:15.140 JupyterHub app:2337] Hub API listening on http://127.0.0.1:8081/hub/
[W 2019-06-13 09:32:15.140 JupyterHub proxy:516] Found proxy pid file: /home/ubuntu/jupyterhub-proxy.pid
[W 2019-06-13 09:32:15.141 JupyterHub proxy:533] Proxy still running at pid=22368
[W 2019-06-13 09:32:16.144 JupyterHub proxy:553] Stopped proxy at pid=22368
[D 2019-06-13 09:32:16.144 JupyterHub proxy:569] Removing proxy pid file jupyterhub-proxy.pid
[I 2019-06-13 09:32:16.145 JupyterHub proxy:645] Starting proxy @ http://:8000
[D 2019-06-13 09:32:16.145 JupyterHub proxy:646] Proxy cmd: ['/usr/bin/configurable-http-proxy', '--ip', '', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--error-target', 'http://127.0.0.1:8081/hub/error', '--ssl-key', 'mykey.key', '--ssl-cert', 'mycert.pem']
[D 2019-06-13 09:32:16.148 JupyterHub proxy:561] Writing proxy pid file: jupyterhub-proxy.pid
09:32:16.341 [ConfigProxy] info: Proxying https://*:8000 to (no default)
09:32:16.345 [ConfigProxy] info: Proxy API at http://127.0.0.1:8001/api/routes
[D 2019-06-13 09:32:16.697 JupyterHub proxy:681] Proxy started and appears to be up
[D 2019-06-13 09:32:16.698 JupyterHub proxy:314] Fetching routes to check
[D 2019-06-13 09:32:16.702 JupyterHub proxy:765] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
[I 2019-06-13 09:32:16.718 JupyterHub proxy:319] Checking routes
[I 2019-06-13 09:32:16.718 JupyterHub proxy:399] Adding default route for Hub: / => http://127.0.0.1:8081
[D 2019-06-13 09:32:16.718 JupyterHub proxy:765] Proxy: Fetching POST http://127.0.0.1:8001/api/routes/
09:32:16.719 [ConfigProxy] info: 200 GET /api/routes 
09:32:16.722 [ConfigProxy] info: Adding route / -> http://127.0.0.1:8081
09:32:16.723 [ConfigProxy] info: Route added / -> http://127.0.0.1:8081
[I 2019-06-13 09:32:16.724 JupyterHub app:2422] JupyterHub is now running at http://:8000
09:32:16.724 [ConfigProxy] info: 201 POST /api/routes/

**Comment by ryogesh** [comment]
JupyterHub is now running at **http://:8000**

You need c.JupyterHub.bind_url in the config file, e.g. http://FQDN:PORT

**Comment by payal4143** [comment]
the issue was because of package upgradation. Now I am able to launch jupyterhub via root. 
But if I run through a user, it gives me spawn failed. Kindly Help

Configuration File:
from oauthenticator.github import LocalGitHubOAuthenticator

c.JupyterHub.authenticator_class = LocalGitHubOAuthenticator
c.LocalGitHubOAuthenticator.oauth_callback_url = 'https://3.18.101.190:8000/hub/oauth_callback'
c.LocalGitHubOAuthenticator.client_id = '04b248d260ffc4d47b6a'
c.LocalGitHubOAuthenticator.client_secret = 'f9aa2328051161ce2211879ad705910b137934e5'
c.JupyterHub.ssl_cert = "/home/ubuntu/mycert.pem"
c.JupyterHub.ssl_key = "/home/ubuntu/mykey.key"
c.LocalAuthenticator.create_system_users = True
c.Authenticator.whitelist = {'payal4143', 'adu'}
c.Authenticator.admin_users = {'payal4143'}
c.Spawner.notebook_dir = "/home/payal4143/notebooks"
c.JupyterHub.cookie_secret_file = '/home/ubuntu/jupyterhub_cookie_secret'
c.JupyterHub.proxy_cmd = ['/usr/local/bin/configurable-http-proxy']
c.JupyterHub.port = 8000

**Comment by GeorgianaElena** [comment]
Hi @payal4143! Sorry for the late reply. Are you still experiencing this issue?

I think it might be a permission issue between your *ubuntu* and *payal4143* users. Can you please share the log containing the error message?

**Comment by payal4143** [comment]
yes I am still experiencing the same issue

**Comment by GeorgianaElena** [comment]
@payal4143, the logs surrounding the error message would really help. Also, ``jupyter troubleshoot`` might also provide some useful input.
Do you mind sharing these?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to ask on the [discourse site](https://discourse.jupyter.org/c/jupyterhub/10) or request that we reopen this issue. Thanks! 🌻

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @payal4143)
