### ISSUE TITLE
jupyterhub_notebook_config.py not used in spawned servers using Dockerspawner

### ISSUE THREAD

**Issue by ashimmishra** [jupyterhub/jupyterhub#2610]
I have setup Jupyterhub and I am using Dockerspawner to start single-user servers. 
I want to add the setting as described in the resolution for Issue #379 (https://github.com/jupyterhub/jupyterhub/issues/379).

Having added the config change to both jupyterhub_config.py and jupyterhub_notebook_config.py (copied to $home/.jupyterhub/ on the docker container). I am still getting error when I embed jupyter notebook into an Iframe. 
Refused to display '<ur>/apps/work/single.ipynb?appmode_scroll=0' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".

I also checked the docker logs generated for the spawned container, couldn't find any mention of jupyterhub_notebook_config.py file. 
Is there some setting I am missing ?

**Comment by mathematicalmichael** [comment]
I’m not exactly sure how you have your folders set up, but when I was experiencing a notebook_config file not showing up in a docker container, the thing that fixed it was being explicit:
```
ADD jupyter_notebook_config.py /home/jovyan/.jupyter/jupyter_notebook_config.py
```
Full path name did it for me.

**Comment by ashimmishra** [comment]
Thanks for the reply, I checked by doing ssh into the spawned Docker container and the notebook_config.py file was there in /home/jovyan/.jupyter/ folder. So I don't think copying the file is a problem.
The server when it starts isnt picking up the notebook config. This is the log that I get, should the startup command show the config file ?

Executing the command: jupyterhub-singleuser --ip=0.0.0.0
[W 2019-06-17 07:45:17.947 SingleUserNotebookApp configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
[I 2019-06-17 07:45:19.892 SingleUserNotebookApp server_extension:147] Appmode server extension loaded.
[I 2019-06-17 07:45:19.942 SingleUserNotebookApp extension:168] JupyterLab extension loaded from /opt/conda/lib/python3.7/site-packages/jupyterlab
[I 2019-06-17 07:45:19.942 SingleUserNotebookApp extension:169] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2019-06-17 07:45:19.945 SingleUserNotebookApp singleuser:406] Starting jupyterhub-singleuser server version 0.9.6
[I 2019-06-17 07:45:19.955 SingleUserNotebookApp notebookapp:1774] Serving notebooks from local directory: /home/jovyan
[I 2019-06-17 07:45:19.955 SingleUserNotebookApp notebookapp:1774] The Jupyter Notebook is running at:
[I 2019-06-17 07:45:19.955 SingleUserNotebookApp notebookapp:1774] http://(3c20b1f687bb or 127.0.0.1):8888/user/ashim.mishra/
[I 2019-06-17 07:45:19.955 SingleUserNotebookApp notebookapp:1775] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

**Comment by ashimmishra** [comment]
It seems I needed to destroy the container and then re-create it. Now the content-security-policy: is coming as expected.
