### ISSUE TITLE
Access full public URL of user servers from Hub REST API

### ISSUE THREAD

**Issue by danielballan** [jupyterhub/jupyterhub#2611]
I have written a Hub Service that runs as `admin` and needs to make a GET request against a user server. Currently, the Hub's REST API does not give the service a way to access the user server's public URL. The server model in the response to `/users/<username>` contains a _relative_ path, as in

```
{"servers": {"<server_name>": {"url": "/user/<username>/<servername>/", ...}, ...}}
```

One might think to use the `JUPYTERHUB_API_URL`, but that is inside the proxy and leads to infinite redirect loop between `/` and `/hub/`. I believe I need the _public_ URL of the user server, outside the proxy. My current workaround involves accessing `self.request` on the `RequestHandler`. Can something to be added to `/users/<username>` to make this possible to access from the Hub REST API?

If more context for my specific use case is helpful, the relevant code snippet is https://github.com/danielballan/jupyterhub-share-link/blob/198c061cc8184793a31275af812d0e97895fa4d3/jupyterhub_share_link/run.py#L60-L63

Thanks to @yuvipanda for helping to clarify this issue.

**Comment by ian-r-rose** [comment]
I am also running into this issue, but in my case I don't have a useful `Request` object, since the request is not coming from a user server. Have you figured out any other workarounds for this @danielballan?

**Comment by danielballan** [comment]
I just ended up using the `Request` object. https://github.com/danielballan/jupyterhub-share-link/blob/b248b5a9d49b5af8c6ace4d1d47addce738ad7db/jupyterhub_share_link/run.py#L120-L123

Without that, you'd probably need to rely on an extension-specific environment variable to pass in that value.
