### ISSUE TITLE
JupyterHub Launch Server on Login

### ISSUE THREAD

**Issue by aurashn** [jupyterhub/jupyterhub#2614]
Is there a configuration option to launch the users server after they are authenticated rather than forcing them to click "Launch Server". I believe the Kubernetes JupyterHub version does this by default, but I am not sure how to do it on my local version.

**Comment by katsar0v** [comment]
https://jupyterhub.readthedocs.io/en/stable/reference/urls.html -> `redirect_to_server`
Hope this can help you
