### ISSUE TITLE
Unable to handle usernames containing spaces 

### ISSUE THREAD

**Issue by druths** [jupyterhub/jupyterhub#2616]
**Describe the bug**
When a new user is being created and the username has a space in it (as will happen with the AzureAd authentication service), the useradd command fails - users can't have spaces in them (or at least need to be handled specially).

**To Reproduce**
1. Setup AzureAd authenticator
2. Login as a new user who has a space in their name
3. Boom

**Expected behavior**
The system should replace the space with some non-whitespace character (e.g., a '.')

**Comment by katsar0v** [comment]
The usernames should be normalized and the authenticator should usually do this. In docker for example you cannot have container with spaces in the name. So I'd rather look in the authenticator, because using system accounts with system processes (which might have spaces in them) works as wished.

**Comment by druths** [comment]
Makes sense to me.  I'll take this issue there.

Derek Ruths
Associate Professor // School of Computer Science // McGill
Chief Architect // Charitable Analytics International
Chief Data Scientist // Ruths.ai
www.derekruths.com
@derekruths

------ Original Message ------
