### ISSUE TITLE
Need an explanation of how to pass custom arguments to containers in SwarmSpawner

### ISSUE THREAD

**Issue by m-alekseev** [jupyterhub/jupyterhub#2619]
How do I pass my own container parameters like `NB_USER, NB_UID, NB_GID, user=root` to spawning by jupyterhub swarmspawner containers?

I can do that via cli for a regular docker and for a swarm mode
```docker run --user root -e NB_USER=username -e NB_UID=1234 -e NB_GID=4321 jupyter/base-notebook```
```docker service create -u root -e NB_USER=username -e NB_UID=1234 -e NB_GID=4321 -p 8888:8888 jupyter/base-notebook```

How do I do the same from jupyterhub config file?

**Comment by ryogesh** [comment]
use c.Spawner.environment

e.g.
c.Spawner.environment = {'NB_USER': 'itsme', 'USER': 'notset'}

**Comment by m-alekseev** [comment]
> use c.Spawner.environment
> 
> e.g.
> c.Spawner.environment = {'NB_USER': 'itsme', 'USER': 'notset'}

Yes, I can pass environment variables but the containers has to be run as root to change those parameters inside the container, but I can't find how can I run it as root.

**Comment by ryogesh** [comment]
To run the container as root (not recommended), make sure you are not setting the user to NB_USER.

jupyter/base-notebook has USER $NB_UID , hence it will run as non-root

**Comment by m-alekseev** [comment]
> To run the container as root (not recommended), make sure you are not setting the user to NB_USER.
> 
> jupyter/base-notebook has USER $NB_UID , hence it will run as non-root

I found the solution, I needed to run container as root because inside of `start.sh` it's checking if container runs as root, so it won't change container parameters acquired from env variables until this script ran as root user.

I activated root by changing 
```
c.SwarmSpawner.extra_container_spec = {
    'user': '0',
}
```
I found that option inside the `ContainerSpec()` class from `docker.types` used inside the `SwarmSpawner`

**Comment by alexey-petrenko** [comment]
I was wondering how can I check if it's working or not?

I've just put
c.Spawner.environment = {'RPN_DEFNS': '/opt/.defns.rpn'}
into my /etc/jupyterhub/jupyterhub_config.py
restarted my jupyterhub
but if I execute "!echo $RPN_DEFNS" inside my jupyter notebooks I see an empty string :(

**Comment by ryogesh** [comment]
can you check the env variables from the notebook. (%env)

**Comment by alexey-petrenko** [comment]
> can you check the env variables from the notebook. (%env)

Strange, it works now then I tried to check %env:
{'PATH': '/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/anaconda3/bin',
 'RPN_DEFNS': '/opt/.defns.rpn',
...}

Maybe I was supposed to restart both the main server and my own user server. Before I was restarting only my user server. Sorry for bothering you!
