### ISSUE TITLE
How to set a specific port for single-user Jupyterhub server REST API calls?

### ISSUE THREAD

**Issue by Lingaraj2410** [jupyterhub/jupyterhub#2620]
I have setup Spark SQL on Jypterhub using Apache Toree SQL kernel. I wrote a Python function to update Spark configuration options in the kernel.json file for my team to change configuration based on their queries and cluster configuration. But I have to shutdown the running notebook and re-open or restart the kernel after running Python function. In this way, I'm forcing the Toree kernel to read the JSON file to pick up the new configuration.

I thought of implementing this shutdown and restart of kernel in a programmatic way. I got to know about the Jupyterhub REST API documentation and am able implement it by invoking related API's. But the problem is, the single user server API port is set randomly by the Spawner object of Jupyterhub and it keeps changing every time I spin up a cluster. I want this to be fixed before launching the Jupyterhub service.

Here is a solution I tried based on Jupyterhub docs:

```
sudo echo "c.Spawner.port = 35289
c.Spawner.ip = '127.0.0.1'" >> /etc/jupyterhub/jupyterhub_config.py
```

But this did not work as the port was again set by the Spawner randomly. I think there is a way to fix this. Any help on this would be greatly appreciated. Thanks

**Comment by ryogesh** [comment]
Are you using containers? If not, the port will be randomly set.  
Refer: https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/spawner.py

**Comment by Lingaraj2410** [comment]
No, I'm not using any containers like Docker. I'm running it on a Dataproc cluster nodes. Is there a work around for this?

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
