### ISSUE TITLE
user logout doesn't invalidate cookies with GenericOAuthenticator 

### ISSUE THREAD

**Issue by lakshaykc** [jupyterhub/jupyterhub#2622]
This is similar to #1491.

**Describe the bug**
I'm using GenericOAuthenticator to authenticate jupyterhub using a custom application and jupyterhub is run on kubernetes. When a user logs out of the jupyterhub, cookies are still valid. So now when a different user logs in the custom application, jupyterhub authenticator opens the notebook server of the previous user who was logged in. The new user is authenticated by the authenticating server but jupyterhub still uses the user information from cookies (?) and opens the previous user's notebook server. 

See [comment](https://github.com/jupyterhub/jupyterhub/issues/1491#issuecomment-505147378)

```
[I 2019-06-24 19:00:45.983 JupyterHub login:19] User logged out: lakshay
[I 2019-06-24 19:00:46.001 JupyterHub log:158] 302 GET /hub/logout -> /hub/login (lakshay@10.24.0.1) 92.66ms
[I 2019-06-24 19:01:19.431 JupyterHub proxy:301] Checking routes
[I 2019-06-24 19:02:19.383 JupyterHub proxy:301] Checking routes
[I 2019-06-24 19:02:37.098 JupyterHub log:158] 302 GET /hub/user/test_user_2 -> /hub/login?next=%2Fhub%2Fuser%2Ftest_user_2 (@10.24.0.1) 1.34ms
[I 2019-06-24 19:02:37.397 JupyterHub log:158] 200 GET /hub/login?next=%2Fhub%2Fuser%2Ftest_user_2 (@10.24.0.1) 1.85ms
[I 2019-06-24 19:02:49.131 JupyterHub oauth2:82] OAuth redirect: 'https://notebooks.example.com/hub/oauth_callback'
[I 2019-06-24 19:02:49.132 JupyterHub log:158] 302 GET /hub/oauth_login?next=%2Fhub%2Fuser%2Ftest_user_2 -> https://example.com/o/authorize/?response_type=code&redirect_uri=https%3A%2F%2Fnotebooks.example.com%2Fhub%2Foauth_callback&client_id=YF2YgTSjrcafiifph2vOsOFdspg27Tbv7fg7kaVK&state=[secret] (@10.24.0.1) 2.13ms
[I 2019-06-24 19:02:49.630 JupyterHub base:509] User logged in: lakshay
```

In the logs above, once the user is logged out, jupyterhub still has user's information.
```
/hub/logout -> /hub/login (lakshay@10.24.0.1)
```

@minrk fixed this in #1577  but I've tried different versions with that fix but I still see the same behavior. Am I missing something is testing this?

**Versions Tried**

| helm-chart repo version  | jupyterhub version |
| ------------- | ------------- |
| 0.8.2  | 0.9.6  |
|jupyterhub-0.9-445a953 (latest dev) | 1.0.0  |

**To Reproduce**
1. Enable authentication with third party application (github, custom_application, etc). I have only tried with my own custom application but should be same for others as well.
2. Login to the authenticating application (github, custom_application) and sign in to jupyterhub
3. Log out jupyterhub and the authenticating application
4. Login to the authenticating application using a different username
5. Login to jupyerhub with OAuth and you will be directed to the previous user's notebook server

**Expected behavior**
The notebook server of the new user should be openend instead of previously logged in user.

**Testing Env:**
 - OS: Linux, google cloud kubernetes engine
 - Browser : chrome
 - Version: Helm chart version - 0.8.2 (0.9.6 jupyterhub)
                 Helm Char version - 0.9-445a953 (1.0.0 jupyterhub) 
                 Helm Char version - 0.9-8463734 (0.9.4 jupyterhub)

@minrk mentioned in this [comment](https://github.com/jupyterhub/jupyterhub/issues/1491#issuecomment-381052081) that it will be fixed in the release 0.9.0. However, the session-id (#1577) changes are implemented in the versions I tested.  Can someone clarify the difference and what will change in 0.9.0 that is already not implemented in 0.8.2 or the latest dev version with respect to this issue?

Also, what is the timeline of 0.9.0 release?

**Comment by minrk** [comment]
OAuth is complicated! It's not the same as #1491, which was jupyterhub logout leaving cookies used by services in tact until the services decided to re-check with the Hub, usually a cache time of about five minutes.

I'll go through what I think is happening here, since I think some log statements aren't clear about what they mean:

```
[I 2019-06-24 19:00:45.983 JupyterHub login:19] User logged out: lakshay
[I 2019-06-24 19:00:46.001 JupyterHub log:158] 302 GET /hub/logout -> /hub/login (lakshay@10.24.0.1) 92.66ms
```

This is normal. This is user lakshay logging out. User lakshay requested `/hub/logout`, which responded with a 302 redirect back to the login page and cleared the jupyterhub cookies. The `lakshay@` in the log line only means that lakshay was authenticated at the *beginning* of the request. There is neither direct confirmation nor refutation that cookies are cleared in these logs, but that is what `User logged out: lakshay` is meant to indicate. A tricky bit about reading logs from these tornado servers is that the `200 GET` result is logged at the *end* of the request, and the actions taking during that request are logged earlier.

```
[I 2019-06-24 19:02:37.098 JupyterHub log:158] 302 GET /hub/user/test_user_2 -> /hub/login?next=%2Fhub%2Fuser%2Ftest_user_2 (@10.24.0.1) 1.34ms
```

This is where we get confirmation that cookies were cleared. The next request, made to `/hub/user/test_user_2` shows no identified user (no name `@10.24.0.1`) which would not be the case if there were leftover jupyterhub cookies. Since there is no authenticated user associated with the request, the login process begins with a redirect to the login page.

```
[I 2019-06-24 19:02:37.397 JupyterHub log:158] 200 GET /hub/login?next=%2Fhub%2Fuser%2Ftest_user_2 (@10.24.0.1) 1.85ms
[I 2019-06-24 19:02:49.131 JupyterHub oauth2:82] OAuth redirect: 'https://notebooks.example.com/hub/oauth_callback'
[I 2019-06-24 19:02:49.132 JupyterHub log:158] 302 GET /hub/oauth_login?next=%2Fhub%2Fuser%2Ftest_user_2 -> https://example.com/o/authorize/?response_type=code&redirect_uri=https%3A%2F%2Fnotebooks.example.com%2Fhub%2Foauth_callback&client_id=YF2YgTSjrcafiifph2vOsOFdspg27Tbv7fg7kaVK&state=[secret] (@10.24.0.1) 2.13ms
```

This is the login process:

1. `200 GET /hub/login` serves the page with the login button
2. Clicking the login button sends the user to `/hub/oauth_login` which begins OAuth with example.com via 302 redirect to `https://example.com/o/authorize`

This is where I believe stale cookies exist, and they aren't to do with JupyterHub: since you are still logged in to example.com (JupyterHub cannot clear cookies for another domain), the oauth redirect completes without prompt (you can check the request history in your browser network tools), immediately sending you back to `/hub/oauth_redirect` with the credentials you have stored for example.com, establishing *new* credentials with JupyterHub as user `lakshay`.

So the apparent never-logged-out state is because of two things:

1. your browser still has credentials for example.com in a cookie (not generally JupyterHub's business), and
2. example.com has stored that JupyterHub is authorized on your behalf, so it skips the "Would you like to authorize JupyterHub to..." prompt. This is a choice of OAuth providers whether they show a prompt like this every time or not, but many do not if authorization is stored.

Finally, we have:

```
[I 2019-06-24 19:02:49.630 JupyterHub base:509] User logged in: lakshay
```

which I expect is followed shortly after with `302 GET /hub/oauth_callback`, completing the login process.


## What to do

These are the things JupyterHub can do, which mostly mean taking one or more extra actions with the oauth provider upon logout from JupyterHub:

1. [revoke OAuth authorization](https://tools.ietf.org/html/rfc7009) on logout. This would bring us back to the starting point, which should result in a new prompt with your oauth provider. OAuthenticator implementations would need to implement revocation properly, which doesn't seem super standardized across providers. But we can do it. This should result in a prompt to re-authorize on next login at example.com, but you will not be logged out of example.com. There *can* be downsides of this, mainly if you have a situation like:

    1. browser A login and launch server with OAuth credentials (e.g. GitHub push)
    2. browser B login, access same server
    3. browser B logout, revokes access, now running server and browser A have invalid credentials when only browser B should have been affected.

   but it should at least be possible to enable this.
2. further redirect to example.com's logout page, to logout there as well. I don't think this is usually the right thing to do, since e.g. logging out of JupyterHub shouldn't log you out of GitHub, or whatever your provider is. There may be single-purpose login provider cases where you do want this, though.

**Comment by lakshaykc** [comment]
Ok, this makes more sense now.

So in, 
```
[I 2019-06-24 19:02:49.132 JupyterHub log:158] 302 GET /hub/oauth_login?next=%2Fhub%2Fuser%2Ftest_user_2 -> https://example.com/o/authorize/?response_type=code&redirect_uri=https%3A%2F%2Fnotebooks.example.com%2Fhub%2Foauth_callback&client_id=YF2YgTSjrcafiifph2vOsOFdspg27Tbv7fg7kaVK&state=[secret] (@10.24.0.1) 2.13ms
```

`/hub/oauth_login` redirects to `https://example.com/o/authorize` to verify `test_user_2`, but since the oauth2 provider (django-oauth-toolkit in this case) has cookies for the user `lakshay`, it redirects to `/hub/oauth_callback` with the username `lakshay` instead of `test_user_2`. Note that `test_user_2` is logged in to `example.com`.

Regarding your two points that cause the _apparent_ never logged out state
_1. your browser still has credentials for example.com in a cookie (not generally JupyterHub's business)_

Agreed, but I'm logged in as `test_user_2` at that point, wouldn't the cookies be for the logged in user. And even if the cookies have user `lakshay`'s credentials, something (oauth provider?) should check for the username. I will acknowledge I don't know much about cookies, so I might be asking the wrong question. 


_2. example.com has stored that JupyterHub is authorized on your behalf, so it skips the "Would you like to authorize JupyterHub to..." prompt. This is a choice of OAuth providers whether they show a prompt like this every time or not, but many do not if authorization is stored_

I believe this is true for django-oauth-toolkit and also I'm skipping explicit authorization so that it doesn't ask for that prompt. 


I'll try to find what is happening with cookies in django-oauth-toolkit. After your explanation, it is clear that jupyterhub indeed clears out the cookies.

My use case is more like single-purpose login provider where it would be fine to logout of example.com if the user logs out of jupyterhub. 

Regarding the downside of revoking OAuth authorization, wouldn't it better to have the user login again than to have access to another user's notebook server? Isn't this the same if I log out of google from one browser, I'm logged out of other browsers as well.

How can we add this as an option? I can work on it if you'd like.

**Comment by minrk** [comment]
It sounds like something could wrong with the cookie management on example.com from your description. In the situation we are describing, JupyterHub doesn't ask the user to login as anyone in particular. JupyterHub is asking example.com "who is this browser?" and example.com is replying with "this browser is lakshay." Then, for the given request, JupyterHub checks if lakshay has access to the requested resource. I'm not sure what state is represented by "test_user_2" is logged in, but example.com is identifying you as lakshay in the oauth process, which means that somehow, you are still logged in to example.com as lakshay.

> wouldn't it better to have the user login again than to have access to another user's notebook server?

It still doesn't sound to me like that's happening. example.com is telling jupyterhub that you are `lakshay` and jupyterhub is trusting that.

> Isn't this the same if I log out of google from one browser, I'm logged out of other browsers as well.

This is not the case. Logging out from one browser is not at all related to the sessions of other browsers. I can logout and work and still be logged in at home and vice versa.

> How can we add this as an option? I can work on it if you'd like.

That's great! As it is now, the Authenticator would need a LogoutHandler that takes whatever extra action is deemed appropriate. This recently became [more easily subclassable](https://github.com/jupyterhub/jupyterhub/pull/2534/files), but it might warrant some hooks to make it even easier. Setting up the custom LogoutHandler would likely belong in OAuthenticator classes, perhaps defining an interface like `def revoke_credentials(self, user)` and optionally calling it on logout. The main step is determining what sort of actions are there to take, and what options do we need to expose for them.

**Comment by lakshaykc** [comment]
> It sounds like something could wrong with the cookie management on example.com from your description. In the situation we are describing, JupyterHub doesn't ask the user to login as anyone in particular. JupyterHub is asking example.com "who is this browser?" and example.com is replying with "this browser is lakshay." Then, for the given request, JupyterHub checks if lakshay has access to the requested resource. I'm not sure what state is represented by "test_user_2" is logged in, but example.com is identifying you as lakshay in the oauth process, which means that somehow, you are still logged in to example.com as lakshay.
 > >wouldn't it better to have the user login again than to have access to another user's notebook server?

>It still doesn't sound to me like that's happening. example.com is telling jupyterhub that you are lakshay and jupyterhub is trusting that.

This behavior from example.com/django-oauth-toolkit is strange. I understand Jhub will trust the OAuth provider when it verifies whichever user is asked to be verified. When I print out the logged-in user for example.com (a django application), it does print out `test_user_2`. I believe the OAuth provider (django-oauth-toolkit) is messing up somewhere. I'll dig into this.

>This is not the case. Logging out from one browser is not at all related to the sessions of other browsers. I can logout and work and still be logged in at home and vice versa

Sorry, I meant different tabs within the same browser and not different browsers.

>That's great! As it is now, the Authenticator would need a LogoutHandler that takes whatever extra action is deemed appropriate. This recently became more easily subclassable, but it might warrant some hooks to make it even easier. Setting up the custom LogoutHandler would likely belong in OAuthenticator classes, perhaps defining an interface like def revoke_credentials(self, user) and optionally calling it on logout. The main step is determining what sort of actions are there to take, and what options do we need to expose for them.

Great! Let me take a closer look at the code and get familiar with it. We can then discuss the actions and options we need to implement. 

The title of this issue is incorrect now. Should I close this and open a new one with the specifics?

**Comment by lakshaykc** [comment]
I did a fresh install of JupyterHub and changed the domain from notebooks.example.com to bks.example.com and now the behavior is as expected. To propagate the DNS, I had cleared out my cookies and cache, which may be the reason for the correct behavior. Even though I have tried with two different users multiple times, the correct notebook server is launched. 

The logs for this case contain additional information after `User logged in: test_user`. `/hub/api/authorizations/token` gets the token for the right user. Now I can't remember if I had similar lines for the case posted in the issue. I'll monitor the situation and see if I can reproduce what I posted initially.
```
[I 2019-06-29 16:03:08.121 JupyterHub login:19] User logged out: lakshay
[I 2019-06-29 16:03:08.139 JupyterHub log:158] 302 GET /hub/logout -> /hub/login (lakshay@10.128.0.62) 27.42ms
[I 2019-06-29 16:03:08.256 JupyterHub log:158] 302 GET /hub/api/oauth2/authorize?client_id=jupyterhub-user-lakshay&redirect_uri=%2Fuser%2Flakshay%2Foauth_callback&response_type=code&state=[secret] -> /hub/login?next=%2Fhub%2Fapi%2Foauth2%2Fauthorize%3Fclient_id%3Djupyterhub-user-lakshay%26redirect_uri%3D%252Fuser%252Flakshay%252Foauth_callback%26response_type%3Dcode%26state%3DeyJ1dWlkIjogIjczZWJmMTRlMTc0NjQ0ZDdiZjY4OWJkOWZiMzQ3YmQ5IiwgIm5leHRfdXJsIjogIi91c2VyL2xha3NoYXkvYXBpL2NvbnRlbnRzP3R5cGU9ZGlyZWN0b3J5Jl89MTU2MTgyNDE0MjMxOSJ9 (@10.128.0.62) 4.00ms
[I 2019-06-29 16:03:32.769 JupyterHub log:158] 302 GET /hub/user/test_user -> /hub/login?next=%2Fhub%2Fuser%2Ftest_user (@10.128.0.62) 1.28ms
[I 2019-06-29 16:03:35.210 JupyterHub oauth2:82] OAuth redirect: 'https://bks.example.com/hub/oauth_callback'
[I 2019-06-29 16:03:35.212 JupyterHub log:158] 302 GET /hub/oauth_login?next=%2Fhub%2Fuser%2Ftest_user -> https://example.com/o/authorize/?response_type=code&redirect_uri=https%3A%2F%2Fbks.example.com%2Fhub%2Foauth_callback&client_id=QUnNORzRqErPgSP6SniZqe4mc9FezUPs3HWzFtJv&state=[secret] (@10.128.0.62) 2.05ms
[I 2019-06-29 16:03:35.535 JupyterHub base:499] User logged in: test_user
[I 2019-06-29 16:03:35.536 JupyterHub log:158] 302 GET /hub/oauth_callback?code=[secret]&state=[secret] -> /hub/user/test_user (@10.128.0.62) 174.21ms
[I 2019-06-29 16:03:35.583 JupyterHub log:158] 302 GET /hub/user/test_user -> /user/test_user?redirects=1 (test_user@10.128.0.62) 10.59ms
[W 2019-06-29 16:03:35.683 JupyterHub log:158] 404 GET /hub/api/authorizations/token/[secret] (test_user@10.24.0.10) 15.41ms
[I 2019-06-29 16:03:35.768 JupyterHub log:158] 302 GET /hub/api/oauth2/authorize?client_id=jupyterhub-user-test_user&redirect_uri=%2Fuser%2Ftest_user%2Foauth_callback&response_type=code&state=[secret] -> /user/test_user/oauth_callback?code=[secret]&state=[secret] (test_user@10.128.0.62) 21.26ms
[W 2019-06-29 16:03:35.829 JupyterHub log:158] 404 GET /hub/api/authorizations/token/[secret] (test_user@10.24.0.10) 14.62ms
[I 2019-06-29 16:03:35.868 JupyterHub log:158] 200 POST /hub/api/oauth2/token (test_user@10.24.0.10) 27.41ms
[I 2019-06-29 16:03:35.900 JupyterHub log:158] 200 GET /hub/api/authorizations/token/[secret] (test_user@10.24.0.10) 20.34ms
```

**Comment by lakshaykc** [comment]
I can't reproduce the issue and it seems like an install from scratch did the trick.  I'm closing the issue for now. If I see it again, I'll reopen it. I'll look into the two options that @minrk suggested regarding a custom LogoutHandler.

**Comment by jgato** [comment]
any news about how to solve this?
