### ISSUE TITLE
Jupyetrhub logs in without login prompt when user is logged out of authenticating app

### ISSUE THREAD

**Issue by lakshaykc** [jupyterhub/jupyterhub#2623]
**Describe the bug**
Once the user is authenticated using GenericOAuthenticator, jupyterhub remains logged in even if the user logs out of the authenticating app. The correct behavior as pointed out in [this comment](https://github.com/jupyterhub/jupyterhub/issues/1805#issuecomment-383117923) should be that the user is asked to login in again to the authenticating application.

**To Reproduce**
1. Setup OAuth with GenericOAuthenticator
2. Login to the authenticating app
3. Login to jupyterhub (Sign in using GenericOAuth2). Since you're already logged in the authenticating app, jupyterhub should directly open the notebook server
4. Log out of the authenticating app
5. Log out of jupyterhub
6. Login to jupyterhub without first logging to the authenticating app
7. Jupyterhub logs in without asking for credentials. So you're able to login to jupyterhub even though you're logged out of the authenticating app

**Expected behavior**
If you're logged out of the authenticating app, jupyterhub login should redirect to sign in to the authenticating app instead of directly logging in. 

**Desktop (please complete the following information):**
 - OS: jupyterhub on Linux (google cloud kubernetes engine)
 - Browser: chrome on windows
 - Version: 0.8.2

**Comment by manics** [comment]
Closing, as this is related to the Authenticator and not JupyterHub
