### ISSUE TITLE
Can't use API with referer header disabled

### ISSUE THREAD

**Issue by deepxg** [jupyterhub/jupyterhub#2624]
There's a check in the base API handler that rejects all requests without a referer header. I prefer to browse the internet with this disabled for various reasons, what's the motivation for breaking the API in this case?

**Comment by manics** [comment]
I think this only applies to the admin pages when accessed through a browser, as a mitigation against cross-site request attacks. Making an API directly with a token should not require referer.

**Comment by deepxg** [comment]
Haven't thought about this in a long time, but are you sure? I'm just looking at lines like this: https://github.com/jupyterhub/jupyterhub/blob/aa0ce1c88a8e34da1779cb13d3f36f81a6a24df7/jupyterhub/apihandlers/base.py#L70

**Comment by minrk** [comment]
[Yes](https://github.com/jupyterhub/jupyterhub/blob/aa0ce1c88a8e34da1779cb13d3f36f81a6a24df7/jupyterhub/apihandlers/base.py#L121-L122), referer is only checked for cookie auth. Token-based auth doesn't check referer.
