### ISSUE TITLE
Cannot connect to Notebook container as Jupyterhub external service

### ISSUE THREAD

**Issue by limbuu** [jupyterhub/jupyterhub#2627]
Hi,

I am using jupyterhub 0.9.2 version with notebook 5.6.0 version. I have so far used cull_idle as jupyterhub external service and its working pretty fine. Now, i am trying to use notebook running in a container within same network an external service running at 127.0.0.1:8888. But, i am facing issue while connecting the notebook container with the jupyterhub container.    

c.JupyterHub.authenticator_class = 'dummyauthenticator.DummyAuthenticator'
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
c.JupyterHub.load_groups = {
    'formgrader-course101': [
        'instructor1',
        'instructor2'
    ]
}

#### and the group has to match the name of the group defined above.
c.JupyterHub.services = [
    {
        'name': 'formgrader-course101-service',
        'url': 'http://127.0.0.1:8888',
        'api_token':'813a078505c74270d0c4e49c0ba452229063afc0f82f594c'
    }
]
c.JupyterHub.hub_ip = '0.0.0.0'
c.JupyterHub.hub_connect_ip = 'jupyterhub'
c.DockerSpawner.image = 'jupyter/base-notebook:v1'
c.DockerSpawner.network_name = 'jupyterhub'
c.DockerSpawner.remove = True
c.DockerSpawner.debug = True
notebook_dir = '/home/test-user'
c.DockerSpawner.notebook_dir = notebook_dir
c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': notebook_dir }

### Even though both notebook run as jupyterhub service and the jupyterhub are in same network, the notebook is not being connected by jupyterhub. 

![image](https://user-images.githubusercontent.com/22807324/60643848-219eaf80-9e54-11e9-8eb1-b1c4f7198a1b.png)

**Comment by GeorgianaElena** [comment]
Hi @limbuu! Thanks for opening this issue and sorry for the late reply. Are you still experiencing this issue?
I think the problem might be that there's no command describing how to launch ``formgrader-course101-service`` as an external service, so nothing is running at the specified url.
Are you trying to integrate *nbgrader* with JupyterHub? If so, you might find [this section](https://github.com/jupyter/nbgrader/blob/master/nbgrader/docs/source/configuration/jupyterhub_config.rst) useful.

**Comment by GeorgianaElena** [comment]
Closing this as it seems to have been solved 🌻 Feel free to ask on https://discourse.jupyter.org/ forum for any configuration issues or questions ❤️ Thanks!
