### ISSUE TITLE
X11 display not working via docker

### ISSUE THREAD

**Issue by casperdcl** [jupyterhub/jupyterhub#2633]
The usual docker way to get X11 windows to display (on an Ubuntu host) is:

```
docker run -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix ...
```
However running a jupyterhub server seems to have the following issues:

1. `DISPLAY` seems to be cleared for users
```python
import os
print(os.environ.get('DISPLAY', 'unset'))  # prints unset
```
2. setting it still results in an error
```python
import os
os.environ.setdefault('DISPLAY', ':0')  # echo $DISPLAY on host prints ":0"
import tkinter
tkinter.Canvas()
...
/opt/conda/lib/python3.7/tkinter/__init__.py in __init__(self, screenName, baseName, className, useTk, sync, use)
   2021                 baseName = baseName + ext
   2022         interactive = 0
-> 2023         self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
   2024         if useTk:
   2025             self._loadtk()

TclError: couldn't connect to display ":0"
```

- related: #698, #684

**Comment by casperdcl** [comment]
probably related to the fact that `--net=host` confuses `jupyterhub`

**Comment by osvaldogc** [comment]
Hi there!

This way worked for me:
docker run --rm -e DISPLAY="$(docker network inspect bridge --format='{{(index .IPAM.Config 0).Gateway}}'):0" -v LOCALPATH:DOCKER PATH ...

**Comment by casperdcl** [comment]
Thanks, but it still doesn't work. I've also tried with the gateway from `docker network inspect myproject_default`.

Just like to add that `DISPLAY` can be injected into jupyter by inserting into `jupyterhub_config.py`:
```python
c.Spawner.env_keep.append("DISPLAY")
# alternatively all env vars
import os
c.Spawner.env_keep.extend([i for i in os.environ])
```

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
