### ISSUE TITLE
JupyterLab as the Default?

### ISSUE THREAD

**Issue by blink1073** [jupyterhub/jupyterhub#2634]
Can we make `/lab` the default experience for JupyterHub?  

Short of that, I'd like to update the docs on how to use JupyterLab.  These are now out of date with the 1.0 release: https://jupyterhub.readthedocs.io/en/stable/troubleshooting.html#how-do-i-use-jupyterlab-s-prerelease-version-with-jupyterhub.

**Comment by wqh17101** [comment]
good idea

**Comment by ellisonbg** [comment]
JupyterLab 3.0 will have a full blown classic notebook mode under the URL prefix `/doc` instead of `/lab`. I believe that would make a good candidate for the default experience in JupyterHub. Thoughts?

**Comment by manics** [comment]
I think that makes sense. Related Z2JH discussion: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/776

**Comment by manics** [comment]
It's the default in 2.0.0!
