### ISSUE TITLE
Can't save notebook into NFS folder

### ISSUE THREAD

**Issue by m-alekseev** [jupyterhub/jupyterhub#2635]
Hello, in my configuration I have nfs mount in each user's container so they have persistent working directory. 

The problem is when I create notebook inside this folder and then trying to save in I have the next error:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/32710792/60887813-ee965a80-a25d-11e9-925c-b50d6479d3f1.png">

```
File Save Error for Untitled.ipynb
Unexpected error while saving file: alekseevma/Untitled.ipynb [Errno 22] Invalid argument: '/home/alekseevma/alekseevma/Untitled.ipynb'
```

Could it be somethink with NFS options while mounting? I tried to tweak some options but so far no progress. Any ideas guys?

Thank u

**Comment by manics** [comment]
Can you open a jupyter terminal and create a file from the command line, e.g.
```
echo test > /home/alekseevma/alekseevma/test.txt
```
and see if you get a similar error?

**Comment by m-alekseev** [comment]
> 
> 
> Can you open a jupyter terminal and create a file from the command line, e.g.
> 
> ```
> echo test > /home/alekseevma/alekseevma/test.txt
> ```
> 
> and see if you get a similar error?

No, there is no problem. I have problem only if I'm trying to save Jupyter Notebook. I also don't have a problem moving it to nfs folder but that isn't what I'm looking for.

**Comment by alexal** [comment]
Show the mount options for your home directory, please.

**Comment by alexal** [comment]
Also, did you try to save the notebook to a local directory?

**Comment by m-alekseev** [comment]
`'o': 'addr=s001cd-hdp-d03.dev002.local,proto=tcp,nolock,rw',` these are the options I have atm, but I tried many different combinations)

Saving to a local dir works just fine.

**Comment by m-alekseev** [comment]
FYI.
NFS share is HADOOP nfs gateway.
Each user gets his uid and gid inside its container from nfs share on a container start. When I create files locally they have correct uid and gid, but if I try to create them on nfs share they get correct uid but gid is 99 (nobody).

**Comment by alexal** [comment]
> Fixed the problem with the nobody group, error while saving stays.
Did you see any errors in /var/log/messages file?

**Comment by manics** [comment]
I've found this similar sounding Python bug: https://bugs.python.org/issue24564

**Comment by m-alekseev** [comment]
> > Fixed the problem with the nobody group, error while saving stays.
> 
> Did you see any errors in /var/log/messages file?

I don't even have this file.

**Comment by alexal** [comment]
If you are inside the container and rsyslog isn't installed, that file won't be available. Let me see what else can we do to debug it further...

**Comment by m-alekseev** [comment]
I'm attaching container logs at the moment of saving.

[jupyter-save-logs.txt](https://github.com/jupyterhub/jupyterhub/files/3451174/jupyter-save-logs.txt)

**Comment by m-alekseev** [comment]
Checked saving to a regular nfs with those parameters 
```/var/nfs *(rw,sync,no_root_squash,no_all_squash)```, works just fine.

Seems like the problem could be with **Hadoop Nfs Gateway**

**Comment by alexal** [comment]
Have you had a chance to check NFS gateway logs?

**Comment by m-alekseev** [comment]
If I didn't mention it before, the problem exists only when I try to save jupyter notebook files, if I save txt file via jupyter web interface there is no problem with saving.

**Comment by listar0810** [comment]
@m-alekseev Hello,have u sovled it?thx

**Comment by blkwtch** [comment]
I am having pretty much the same issue
Unable to create or open existing notebooks, terminal and kernel consoles are working fine though.

Here's what my `/etc/export `file look like. I don't think that it can be any looser than this.
`/var/nfsshare   *(rw,sync,no_root_squash,no_all_squash)`

And here's what the jupyter `SingleUserNotebookApp` says when i am trying to create a notebook
```
[I 2021-02-08 15:08:34.882 SingleUserNotebookApp handlers:153] Creating new notebook in
[D 2021-02-08 15:08:34.883 SingleUserNotebookApp filemanager:469] Saving /home/user1/Untitled.ipynb
15:09:34.930 [ConfigProxy] error: 503 POST /user/user1/api/contents?1612793314861 socket hang up
```
It just hangs like this for afew moments and then i start getting errors from the server

Checked the permissions:
```
drwx-----T 2 user1 domain users 120 Feb  8 15:08 .
drwx------ 4 user1 domain users  97 Feb  8 15:02 ..
-rw-r--r-- 1 user1 domain users 268 Feb  8 15:01 nbserver-32033.json
-rw-r--r-- 1 user1 domain users 565 Feb  8 15:01 nbserver-32033-open.html
-rw-r--r-- 1 user1 domain users 266 Feb  8 15:08 nbserver-528.json
-rw-r--r-- 1 user1 domain users 565 Feb  8 15:08 nbserver-528-open.html

```

**Comment by manics** [comment]
Hi! Since this discussion was started we've moved all support and general questions to the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions. Since this is related to the system configuration rather than a bug in JupyterHub I'm closing this issue. Please feel free to start a [new discussion on Discourse](https://discourse.jupyter.org/) 😀.
