### ISSUE TITLE
Is there away for Key based Login for jupyterhub

### ISSUE THREAD

**Issue by palashSharma17** [jupyterhub/jupyterhub#2642]
Hi all I have deployed jupyterhub on my server and using pam authentication. But due to security concerns I was thinking to use key based Login with jupyterhub. Is it possible.
Also I would like to know do pam authentication is concern for server security and what are the ways by which I can enhance security for Jupyterhub. 
Please help and Thanks in advance.

**Comment by GeorgianaElena** [comment]
Hi @palashSharma17! Thanks for opening this issue.

The [Security Overview section](https://jupyterhub.readthedocs.io/en/latest/reference/websecurity.html) contains useful information about security-related advices across JupyterHub.
The discussion [here](https://github.com/jupyterhub/the-littlest-jupyterhub/issues/225) might also bring some clarifications.

Hope this helps.

**Comment by sajjad207** [comment]
@palashSharma17 hi paslash  i saw your issue #2400 and you closed the issue by saying "Sorry for replying late. I have configured the passphrase and now it works for me." i am ruining into the same problem do you mind telling me where you configured the passphrase? the file name and location if possible with the excate text as well - Thank you
