### ISSUE TITLE
How to clear_login_cookie() when the new user login

### ISSUE THREAD

**Issue by UCSBGauchos** [jupyterhub/jupyterhub#2643]
Currently the clear_login_cookie() will be only called inside the logout process. 

If a new user comes in, we want it clear the old users' cookie and session. Then the new user  can login in.

Is that possible and where we should add the code like 'self.clear_login_cookie()'

Thanks!

**Comment by UCSBGauchos** [comment]
BTW, I am using the jhub_remote_user_authenticator, so I am not sure where is the entry for login and where should I add the clear_login_cookie logic.

**Comment by UCSBGauchos** [comment]
I make some modification in the jupyterhub\jupyterhub\handlers\base.py
I add a method in the class 
    def force_set_login_cookie(self):
        """Force set login cookies for the Hub and single-user server."""
        if self.subdomain_host and not self.request.host.startswith(self.domain):
            self.log.warning(
                "Possibly setting cookie on wrong domain: %s != %s",
                self.request.host,
                self.domain,
            )

        # force set single cookie for services
        self.set_service_cookie(user)

        self.set_session_cookie()

        self.set_hub_cookie(user)

And I call this method it in my authenticator. Not sure whether it's a good idea.

**Comment by UCSBGauchos** [comment]
Any comments for this one :P @GeorgianaElena. Thanks!

**Comment by GeorgianaElena** [comment]
@UCSBGauchos, take a look at [this issue](https://github.com/jupyterhub/jupyterhub/issues/154) based on which [*cookie_max_age_days*](https://jupyterhub.readthedocs.io/en/stable/api/app.html#jupyterhub.app.JupyterHub.cookie_max_age_days) was added.

Maybe finding an appropriate value for *cookie_max_age_days* might serve your purpose. What do you think?

**Comment by GeorgianaElena** [comment]
Closing this as it seems to have been solved 🌻 Feel free to ask on https://discourse.jupyter.org/ forum for any configuration issues or questions ❤️ Thanks!
