### ISSUE TITLE
Any way to get the current user inside the python job of a single jupyter notebook

### ISSUE THREAD

**Issue by UCSBGauchos** [jupyterhub/jupyterhub#2644]
Is that a way to get the current user inside the python job of a single jupyter notebook.

**Comment by GeorgianaElena** [comment]
Hi @UCSBGauchos! Thanks for opening this issue.
Can you please describe a little more the issue you're having and what you're trying to achieve?

**Comment by UCSBGauchos** [comment]
OK. Currently I use this way, is it OK?
import getpass
username = getpass.getuser()

**Comment by GeorgianaElena** [comment]
@UCSBGauchos, that's perfectly fine. :)
I will close the issue now, but feel free to open a new one if you have any other question.
