### ISSUE TITLE
Create groups and add users to the group using Admin User in JupyterHub

### ISSUE THREAD

**Issue by kipstakkr** [jupyterhub/jupyterhub#2651]
Hi team,

I'm currently using JupyterHub (which is running on Docker) as an Admin user. I'm able to create users in JupyterHub and they are able to access the Hub using their credentials. But is there a way to create a group and add users to that group inside my admin Jupyter session without sudo permissions (root access)? @minrk @willingc @yuvipanda

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
