### ISSUE TITLE
setting ssl_cert to fullchain results in expired certificate

### ISSUE THREAD

**Issue by davidedelvento** [jupyterhub/jupyterhub#2653]
I configured my jupyterhub instance as described [in the docs](https://jupyterhub.readthedocs.io/en/stable/getting-started/security-basics.html) namely utilizing the Let's Encrypt `fullchain.pem` file for `c.JupyterHub.ssl_cert`.

Before the certificate expired, I renewed it with Let's Encrypt and that worked fine -- logging into the server via ssh I can see a new certificate was there, and `fullchain.pem` has both the old and the new ones. 

However, if I point my browser to the URL of my website, it gives me the usual extremely annoying "warning" that the certificate has expired.

Back on the server, I checked the expiration dates for both the old and new certificates, as described [in the Let's Encrypt forums](https://community.letsencrypt.org/t/how-to-find-certifications-expiry-date/48661) and it seems that JupytherHub is serving the old, instead of the new certificate.

I played with the files and symbolic links, so that the `fullchain.pem` became instead the new cert (instead of the full chain) to no avail.

Is perhaps the certificate cached and can I invalidate the cache without shutting down and restarting the server?

@eshook @vanderwb

**Comment by davidedelvento** [comment]
It looks like JupyterHub caches the certificates as indicated in the config file. That means that if those files are changed, for example when a renewal happens, JupyterHub needs to be restarted. This is annoying, but valid workaround, which should be mentioned in the docs.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
