### ISSUE TITLE
login page shows "this page cannot be displayed"

### ISSUE THREAD

**Issue by lshailendra** [jupyterhub/jupyterhub#2654]
Hi,

I am a new user trying to setup the jupyterhub.

When I start the Jupyterhub process, it runs but the login page does not show up.
Below is the configurable http proxy process

> node /usr/bin/configurable-http-proxy --ip  --port 8000 --api-ip 127.0.0.1 --api-port 8001 --error-target http://xxxx:8082/hub/error --ssl-key /opt/cloudera/parcels/Anaconda3/ssl/jupyter.key --ssl-cert /opt/cloudera/parcels/Anaconda3/ssl/jupyter.pem_

I can access the login page at port 8082.

Do i need to change the parameters in the config file so that the I can access the login page at port 8000 ?

**_Note_**:  _if the jupyterhub is started without passing the config file then I can access the login page at port 8000._

Below are the parameters from the config file

> c.Application.log_datefmt = '%Y-%m-%d %H:%M:%S'
> c.Application.log_format = '[%(name)s]%(highlevel)s %(message)s'
> c.Application.log_level = 30
> c.JupyterHub.hub_ip = '0.0.0.0'
> c.JupyterHub.hub_port = 8082
> c.JupyterHub.ssl_cert = '/opt/cloudera/parcels/Anaconda3/ssl/jupyter.pem'
> c.JupyterHub.ssl_key = '/opt/cloudera/parcels/Anaconda3/ssl/jupyter.key'
> c.Spawner.debug = True
> c.Authenticator.admin_users = {'xxxx'}

Below is the log

> [I 2019-07-19 09:10:46.892 JupyterHub app:2120] Using Authenticator: jupyterhub.auth.PAMAuthenticator-1.0.0
> [I 2019-07-19 09:10:46.892 JupyterHub app:2120] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.0.0
> [I 2019-07-19 09:10:46.894 JupyterHub app:1257] Loading cookie_secret from /root/jupyterhub_cookie_secret
> [I 2019-07-19 09:10:46.907 JupyterHub proxy:460] Generating new CONFIGPROXY_AUTH_TOKEN
> [W 2019-07-19 09:10:46.908 JupyterHub app:1532] No admin users, admin interface will be unavailable.
> [W 2019-07-19 09:10:46.908 JupyterHub app:1534] Add any administrative users to `c.Authenticator.admin_users` in config.
> [I 2019-07-19 09:10:46.908 JupyterHub app:1563] Not using whitelist. Any authenticated user will be allowed.
> [I 2019-07-19 09:10:46.956 JupyterHub app:2337] Hub API listening on http://127.0.0.1:8081/hub/
> [W 2019-07-19 09:10:46.958 JupyterHub proxy:642] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
> [I 2019-07-19 09:10:46.958 JupyterHub proxy:645] Starting proxy @ http://:8000
> 09:10:47.080 - info: [ConfigProxy] **_Proxying http://*:8000 to (no default)_**
> 09:10:47.081 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
> [I 2019-07-19 09:10:47.160 JupyterHub proxy:319] Checking routes
> [I 2019-07-19 09:10:47.160 JupyterHub proxy:399] Adding default route for Hub: / => http://127.0.0.1:8081
> [I 2019-07-19 09:10:47.165 JupyterHub app:2422] JupyterHub is now running at http://:8000

**Comment by GeorgianaElena** [comment]
Hi @lshailendra. Thanks for opening this issue.

``hub_port`` is the internal port for the Hub process behind the proxy. This shouldn't be accessed directly and if there is no port conflict it's probably a good idea not to change it (by default hub_port is 8081). The public port to use when accessing jupyterhub is  ``JupyterHub.port``, which is already by default 8000.

Also, if you want to start the proxy separately from the hub, don't forget to set ``should_start`` to False (``c.ConfigurableHTTPProxy.should_start = False``) in the config file. Otherwise, should_start is by default True an there's no need to start/stop the proxy process as it will be managed by the Hub.
Hope this helps.

**Comment by lshailendra** [comment]
@GeorgianaElena Thank you for the quick response. the issue is resolved now 

Sorry for the delayed response.
