### ISSUE TITLE
No login windows shown

### ISSUE THREAD

**Issue by JulianTBZ** [jupyterhub/jupyterhub#2655]
Hi all, 
I have installed the jupyterhub now for some time. Before I made the authentication against a ldap server and everything worked great. But now I have to change the authentication to Active Directory. After binding the Server to the AD and change of the configuration file I get a strange event when I try to login. 
The authentication seems to be accepted but I just get redirected back to the login page. 
In the debug mode I see the following: 

<img width="1425" alt="61527472-cb696900-aa1c-11e9-8fe5-0b3c33988d8a" src="https://user-images.githubusercontent.com/36665360/61614042-1674bd80-ac63-11e9-80c8-3135b8177de6.png">

Seems okay for me. Or is there something wrong?

Also, the users home directory is created on the server. But the user never can pass the login page. The following is my configuration of the authenticator. Is there something missing? 

> c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
> c.LDAPAuthenticator.server_hosts = ['192.168.x.x']
> c.LDAPAuthenticator.bind_user_dn = 'CN=query,CN=users,DC=example,DC=com'
> c.LDAPAuthenticator.bind_user_password = 'passsword'
> c.LDAPAuthenticator.user_search_filter = '(&(objectCategory=person)(objectClass=user)(UserPrincipalName={username}))'
> c.LDAPAuthenticator.lookup_dn = False
> c.LDAPAuthenticator.user_search_base = 'OU=Users,DC=example,DC=com'
> c.LDAPAuthenticator.create_user_home_dir = True
> c.LDAPAuthenticator.create_user_home_dir_cmd = ['mkhomedir_helper']

Thanks for any help. 
KR, 
Julian

**Comment by GeorgianaElena** [comment]
Hi @JulianTBZ! Thanks for reporting this issue.
There are a two config related notes that I hope will help:
* According to [LDAP authenticator's docs](https://github.com/jupyterhub/ldapauthenticator#required-configuration), there are two configuration options that must be set before using the LDAP Authenticator and seem to be missing from your config. 
* Also, [``LDAPAuthenticator.user_search_base``](https://github.com/jupyterhub/ldapauthenticator#ldapauthenticatoruser_search_base) is meant to be used only with [``LDAPAuthenticator.lookup_dn = True``](https://github.com/jupyterhub/ldapauthenticator#ldapauthenticatorlookup_dn) (in your config it is set to false).

**Comment by JulianTBZ** [comment]
Hi,
Thanks for your reply. 
I tried it with this additional configuration options. 
But I still get the same problem.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
