### ISSUE TITLE
wrong version of lab in the TLJH

### ISSUE THREAD

**Issue by wqh17101** [jupyterhub/jupyterhub#2656]
i set up a TLJH , and set c.Spawner.default_url = '/lab' 

as you can see my lab verison is 1.0.2
![image](https://user-images.githubusercontent.com/26429138/61760609-aef37500-adfe-11e9-97c5-125b61a111a8.png)
but when i start hub
i got this 
![image](https://user-images.githubusercontent.com/26429138/61760651-cfbbca80-adfe-11e9-9b62-cccb855f8c7f.png)
why the version is wrong

**Comment by danielmpla** [comment]
Has anyone a solution for this?

**Comment by danielmpla** [comment]
I solved this by using the terminal from within jupyterlab. At first I did the mistake to run `sudo -E pip3 install -U jupyterlab`. This brought me to the same result, shown in the issue.
However, you have to run `sudo -E pip install -U jupyterlab`. This solved it for me today. I guess this is the only way to be in the correct environment, when installing anything to JupyterHub's Python.

**Comment by wqh17101** [comment]
@danielmpla yeah, it is the environment problem. 
https://github.com/jupyterhub/the-littlest-jupyterhub/issues/412
i found the problem and create a PR for TLJH.
If you use the TLJH , you can fix it as https://github.com/jupyterhub/the-littlest-jupyterhub/pull/413
