### ISSUE TITLE
SpawnPendingHandler doesn't seem to be working right with named servers

### ISSUE THREAD

**Issue by rcthomas** [jupyterhub/jupyterhub#2657]
In the `SpawnPendingHandler` there are places where the spawn_url is set like:

https://github.com/jupyterhub/jupyterhub/blob/24c08292899492bb0bd5e2b7fdbf7e09cf1a4057/jupyterhub/handlers/pages.py#L286

We've got a pre-spawn hook that fires to make sure the user's home directory is not over quota.  If the user's over quota then it fires and we get the `not_running` template.  The user is advised via message there they should make some room and then come back and try again.  The problem is the button points to the default server "", not the named server the user was trying to start.

Is this the desired behavior or is it maybe a bug that the `spawn_url` should be set using say, `user.server_url(server_name)`?

**Comment by GeorgianaElena** [comment]
Fixed in https://github.com/jupyterhub/jupyterhub/pull/2682
