### ISSUE TITLE
how to set the property  of file created by jupyterlab

### ISSUE THREAD

**Issue by wqh17101** [jupyterhub/jupyterhub#2659]
i found that all the file (.ipynb,.txt,and so on) created by jupyterlab have this property
![image](https://user-images.githubusercontent.com/26429138/61842984-a8cbca00-aecc-11e9-9105-31085f26b6ab.png)

so how can i set file property created by jupyterlab
we need to grant writing access to the owning group of a Notebook.

**Comment by danielmpla** [comment]
I think this is a linux related problem, but still I also would like to see an answer.

**Comment by ryogesh** [comment]
Does these help?

https://github.com/jupyter/notebook/issues/2858#issue-260020185

https://github.com/jupyter/notebook/issues/2064

**Comment by wqh17101** [comment]
No
@ryogesh i dont know to set.
When i login and set umask 000 , i can create a 777 file by terminal in the jupyterlab .
But it doest work for creating something with click on
![image](https://user-images.githubusercontent.com/26429138/62844087-5f171800-bcf1-11e9-990e-71556274b0d0.png)
these icons.

**Comment by ryogesh** [comment]
Terminals pickup the user umask defaults (or if you set one for the session).

When you save files save .ipynb file, default umask is 0022, and so the file gets created  with  644 permission.

You need to change the default umask on the jupyter notebook config file (e.g. /etc/jupyter/jupyter_notebook_config.py)  so that the owning group has +w access.
 As mentioned in https://github.com/jupyter/notebook/issues/2858#issue-260020185,

import os
os.umask(0o002)

**Comment by wqh17101** [comment]
As a jupyterhub app , do you mean i should modify the jupyterhub_config.py? Because there is no jupyter_notebook_config.py

**Comment by gaebor** [comment]
@wqh17101 Don't put this into the main `jupyterhub_config.py`.
Rather `/etc/jupyter/jupyter_notebook_config.py`, make one if not present (you have to make the intermediate directory `/etc/jupyter` too)

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!

**Comment by skokado** [comment]
@wqh17101 
Hi, I found workaround for this.

JupyterLab seems to be just using the system umask.

```shell
$ # Set umask manually
$ umask 0005
$ jupyterhub -f /path/to/jupyterhub_config.py
```

So, set umask in configuration and it worked :)

- `jupyterhub_config.py`

```python
import os

os.umask(0o0005)
...
```
