### ISSUE TITLE
Documentation theme is outdated on `stable`

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/jupyterhub#2660]
Hey all - I noticed that the JupyterHub documentation theme is buggy on the "stable" branch of readthedocs (which is also the default):

https://jupyterhub.readthedocs.io/en/stable/index.html

The theme includes forward/next buttons, but they're also hard-coded in the theme, so they become doubled-up:

![image](https://user-images.githubusercontent.com/1839645/61891536-b712e980-aebe-11e9-93a4-b03dbaefaf08.png)

"latest" does not have this problem:

https://jupyterhub.readthedocs.io/en/latest/installation-guide.html

however, it is not the default in readthedocs. I think we could fix this by either:

1. Backporting the documentation fix to the stable branch, which I guess would require updating the tag to the new commit? (I'm not actually sure how that works)
2. Making a minor release of JupyterHub so that "latest" becomes "stable" and the documentation is then updated.

What do y'all think?

**Comment by Jchappell01** [comment]
Any idea how we might go about this? I'm a bit new to this but I'd be happy to help!

**Comment by choldgraf** [comment]
I think the easiest thing to do would be to cut a new release of JupyterHub. Alternatively, we'd need to back-port the theme update to a pre-existing tag within the repository. I kinda feel like neither of these are super straightforward to do though :-/

**Comment by GeorgianaElena** [comment]
The `stable` docs are fixed with JupyterHub 1.1.0 (https://jupyterhub.readthedocs.io/en/stable/installation-guide.html) :tada: 
Closing this.
