### ISSUE TITLE
How to change the Jupyter default working directory ? 

### ISSUE THREAD

**Issue by manojs123** [jupyterhub/jupyterhub#2665]
Hello,

I'm new to python and Jupyter. I have Installed jupyterhub (Linux), and when I try to use the Jupyter Notebook (UI) it is loading the default working directory as my HOME directory, but I want to change it to something like /path/to/dir/. I tried to do the following in jupyterhub_config.py, but it still loads the default home directory but not the one I want. 

c.Spawner.notebook_dir = '/path/to/dir/'

Thank you for your help.

Thanks,
Manoj

**Comment by GeorgianaElena** [comment]
Hi @manojs123 :four_leaf_clover: 
Are you using JupyterHub to spawn a Jupyter Notebook or are you starting directly the notebook with ``jupyter notebook``?
Also, it would be really useful if you could share the logs you get when running with ``--debug`` option.

**Comment by manojs123** [comment]
Hello Elena, 

Thank you for your response. As said I have installed JupyterHub on the Linux machine. To allow multiple users to sign in to the Hub Server, I started jupyterhub as a privileged user, such as root then I visit https://localhost:8000 in my browser, and sign in with my credentials to start using Jupyter Notebook.  

Elena, I'm very new to Python and Jupyter, can you please let me know what logs you want ? Do you want me to run JupyterHub from Command line and send you the logs ?  

Thanks,
Manoj

**Comment by GeorgianaElena** [comment]
@manojs123, setting *c.Spawner.notebook_dir* should be enough for changing the notebook directory for the single-user server, so we have to see what's going on and why it's not working for you.

Can you please share your *jupyterhub_config.py* (with any sensitive info redacted)?

Also, try adding *c.Spawner.debug = True* in your config and share the output you get when running *jupyterhub -f <path_to_your_jupyterhuh_config.py>*

**Comment by manojs123** [comment]
Hello Elena, 

Yeah! But, we have installed jupyterHub so that multiple users will be using Jupyter (parallelly). Can you please share me your email (if you can), I will send you the config/log files to your email. 

Thanks,
Manoj

**Comment by GeorgianaElena** [comment]
@manojs123, if you hide the sensitive info it's ok to share the logs here.

**Comment by manojs123** [comment]
@GeorgianaElena Thank you for the help. I figured out the issue and could fix it. Sorry for the delayed response. 

Thanks,
Manoj

**Comment by GeorgianaElena** [comment]
Awesome @manojs123  :four_leaf_clover:. I'm very happy you found the solution.
(It would be really helpful for people that might encounter a similar situation if you could share how you fixed the issue.)

**Comment by MikhailSam** [comment]
I faced the same problem.
For someone who got the same one and interesting in solution:
really adding for two options in `jupyterhub_config.py` helped:

```
c.Spawner.default_url = '/data/jupyterhub/jupyterhub_notebooks'
c.Spawner.notebook_dir = '/data/jupyterhub/jupyterhub_notebooks'
```

**Comment by shahinur-17** [comment]
Its very simple for Windows 10 OS if you running Jupyter notebook on Anaconda. To change your current working directory to a new directory:
1. Just open you Ananconda prompt first
2. Secondly type on Anaconda prompt:    jupyter notebook --notebook-dir 'your desired directory 
such as D:' ,  to be clear:     jupyter notebook --notebook-dir 'D:'
3. Now the jupyter notebook will be directed to 'D:'
4. Done

**Comment by shahinur-17** [comment]
To change the working directory in Jupyter notebook, you need to follow 5 easy steps:
1. From start menu on your desktop if Anaconda is installed, just click on Anaconda folder to navigate Jupyter notebook icon.
2. Then right-click on Jupyter notebook to find the option "more" , and then click on open file location.
3. You will get again another Jupyter notebook icon with Anaconda navigator and prompt. After tha, right-click on Jupyter notebook and try to find Jupter notebook properties on Shortcut popup bar.
Then, on Target text box, remove %USERPROFILE% at the end of path, with your desired path. It looks  like:     ripts\jupyter-notebook-script.py " D:\SABRE dete. Here D:\SABRE dete is my desired path. 
4. In the Start in box, you need to put your desired path also. It looks like: Start in   "D:\SABRE detector compatibility\UV-Vis as compatibility". Then apply the changes in the Jupyter properties..
5. Then restart your computer and run your Jupyter notebook from Anaconda navigator. That's all.

**Comment by SongpengYan** [comment]
> @GeorgianaElena Thank you for the help. I figured out the issue and could fix it. Sorry for the delayed response.
> 
> Thanks,
> Manoj

Hi Manoj, I also installed jupyterhub for muti-users and I want to change the default workspace /home/{user} to /data/{user}, may I know your solutions? Thanks

**Comment by stellaYi** [comment]
> @GeorgianaElena Thank you for the help. I figured out the issue and could fix it. Sorry for the delayed response.
> 
> Thanks,
> Manoj

@manojs123  can you share how you solve the issue in RHEL server? thanks. I encountered the same issue.

**Comment by k-nayak** [comment]
Can someone help me with a similar issue i believe: I am able to open .ipynb files in Jupyter Notebook using "sudo jupyter notebook --allow-root" 
But i was able to run it with just "jupyter notebook" and now i am getting 500: internal server error without root while trying to open or create any ipynb files. Same problem with Jupyterhub as well which i installed in Linux for multi user access as intended by @manojs123.  
the logs give an error: PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter/nbconvert/templates/html/conf.json’

I am assuming it has something to do with root and user permissions but i am not much experienced with linux and would appreciate any help. 

@GeorgianaElena if you are aware of such error, it would mean a lot if there is any advice that you can give me. Thanks in advance.
