### ISSUE TITLE
Configuring tokens is quite confusing

### ISSUE THREAD

**Issue by katsar0v** [jupyterhub/jupyterhub#2668]
So i had following config with jupyterhub `0.9.4`, which worked pretty fine:

```
c.JupyterHub.service_tokens = {
    '675982d420fbed3bb6403ecd8032be284ace814fdab37815b7d24f741c84237d' : 'root'
}

c.Authenticator.admin_users = {'root'}

c.JupyterHub.services = [
    {
        'name': 'usage-monitor',
        'admin': True,
        'command': 'python /srv/jupyterhub/monitor_usage.py --every=900'.split()
    },
    {
        'name': 'cull-idle',
         'admin': True,
         'command': 'python /srv/jupyterhub/cull_idle_servers.py --cull_every=60 --timeout=691200'.split()
    }
]
```

Updating jupyterhub throws a 403, I get:
```
[W 2019-08-02 13:34:33.045 JupyterHub log:174] 403 GET /hub/api/users (root@172.18.0.1) 46.77ms
```
and response from api:
```
[ERROR]: There was an error: {"status": 403, "message": "Forbidden"})
```
The documentation for 1.0.0 is confusing or not up to date and it is not really clear how to use these tokens for accessing the api via scripts (curl, custom python requests etc ), here is a curl as well:
```
(base) katsarov@katsarov-ThinkPad-T470s:~$ curl http://172.18.0.4:8080/hub/api/users -H "Content-Type: application/json" -H "Authorization: token 675982d420fbed3bb6403ecd8032be284ace814fdab37815b7d24f741c84237d" -v
*   Trying 172.18.0.4...
* TCP_NODELAY set
* Connected to 172.18.0.4 (172.18.0.4) port 8080 (#0)
> GET /hub/api/users HTTP/1.1
> Host: 172.18.0.4:8080
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/json
> Authorization: token 675982d420fbed3bb6403ecd8032be284ace814fdab37815b7d24f741c84237d
> 
< HTTP/1.1 403 Forbidden
< Server: TornadoServer/6.0.3
< Content-Type: application/json
...
```

I think this part of the documentation or the tokens generally (https://jupyterhub.readthedocs.io/en/stable/reference/rest.html) should be updated explaining what api tokens and service tokens are and which to use when.

At the end I got the working config for my issue:
```
c.JupyterHub.services = [
    {
        'name': 'usage-monitor',
        'admin': True,
        'command': 'python /srv/jupyterhub/monitor_usage.py --every=900'.split()
    },
    {
        'name': 'cull-idle',
         'admin': True,
         'command': 'python /srv/jupyterhub/cull_idle_servers.py --cull_every=60 --timeout=691200'.split() # 8 days
    },
    {
        'name': 'restart_service',
        'api_token': '675982d420fbed3bb6403ecd803a24ace814fdab37815b7d24f741c84237d',
        'admin': True
    }
]
```
But had to create a service for this.. thought that services are "jobs" in jupyterhub that run and do something, seems that now they are used for authentication as well. So probably we habe to update a few texts here, happy to do it by myself as well, I just want to be 100% sure what services are, api tokens and service tokens and which is deprecated (and why).

**Comment by minrk** [comment]
Here's the first source of confusion:

```python
c.JupyterHub.service_tokens = {
    '675982d420fbed3bb6403ecd8032be284ace814fdab37815b7d24f741c84237d' : 'root'
}
```

creates a token for the **service** named 'root'. This service is not configured in the services list, so it has the default settings of `admin: False`.

```python
c.Authenticator.admin_users = {'root'}
```

creates a **user** named root who has admin privileges. services and users are not the same thing, so now we have a user named root is admin but not used, and a service named root that is not admin.

The documentation you linked should definitely be updated. The recommended way to create an API token to be used by an external service is as you have found, in the `services` list:

```python
c.JupyterHub.services = [
    {
        'name': 'myservice',
        'api_token': '675982d420fbed3bb6403ecd803a24ace814fdab37815b7d24f741c84237d',
        'admin': True,
    },
]
```

The two other (older) ways to register tokens are:

1. `service_tokens`, which allows you to create tokens and assign them to services (if it raised an error if the service didn't exist, this might be best). This is mostly useful for registering *additional* tokens for existing services, and probably not super useful anymore.
2. `api_tokens` which is the pre-services way, for creating tokens for *users*. If you are writing a script to consume the API, this should not run as a user. User tokens should generally be created by humans interacting with the token request page.

These are the changes I think we should make:

1. introduce *warnings* when api_tokens or service_tokens would create users or services. This should help with the confusion that they don't correspond to what the user might be expecting (@katsar0v would a message like "Warning: creating implicit service 'root' from service_tokens, not in services list. It is recommended to register services in the list." have helped you catch this more easily?)
2. update the documentation to recommend the services list with an example.
3. update the pending deprecation message in api_tokens to recommend `services` not `service_tokens`.

**Comment by katsar0v** [comment]
@minrk thank you for the detailed answer.

> Warning: creating implicit service 'root' from service_tokens, not in services list. It is recommended to register services in the list.

Would have helped me to catch the difference if I've looked in the logs, yes. From your points I'd prioritise 2. and 3. to happen first

Another question is to clarify the difference between `service_tokens` and `api_tokens` (also put some more detailed examples in the docs) - in my case I had a script which has done some job but I had to run it manually whenever I needed it, I was confused whether this was a service or I was just communicating with the api as root.

You also say: 

> creates a user named root who has admin privileges. services and users are not the same thing, so now we have a user named root is admin but not used, and a service named root that is not admin.

I didn't know (or did not understand) that `c.Authenticator.admin_users` was creating a service that wasn't root. (maybe If I've looked in the code, I could find this out). What I mean here is that for this config probably this [doc](https://jupyterhub.readthedocs.io/en/stable/getting-started/authenticators-users-basics.html) should be updated.

Thank you for the support, again. 

I will try to do some pull requests with documentation update which I think would be useful. I saw that the docs are here - https://github.com/jupyterhub/jupyterhub/tree/master/docs but is there any `CONTRIBUTE.md` file which explains how somebody could contribute to docs? (would be really useful as I haven't worked that much with sphinx)

**Comment by minrk** [comment]
> Another question is to clarify the difference between service_tokens and api_tokens

The gist is: services are programs and users are humans. service_tokens creates tokens for services (programs) and api_tokens creates tokens for users (humans), so only use api_tokens if you want to create a token that an actual human will use. If you want to add scripts that consume the API periodically, that's what services are for.

> I didn't know (or did not understand) that c.Authenticator.admin_users was creating a service that wasn't root.

I think this is a typo and you mean `c.JupyterHub.service_tokens` here, but since we're talking about confusion already, let's be extra sure: `admin_users` created the user, `service_tokens` created the service.

Re: docs contribution notes, I wouldn't create a separate file in the docs, but rather a docs section in the single top-level CONTRIBUTING.md (thoughts, @willingc?)

The gist is:

- cd to `docs`
- install dependencies with `python3 -m pip install -r requirements.txt` (or `conda env create -f environment.yml`)
- edit .rst files in `source`
- run `make html` to render docs and open `build/html/index.html` to browse the results

**Comment by katsar0v** [comment]
We are one step closer to solving this issue. For the point you wrote:

> introduce warnings when api_tokens or service_tokens would create users or services. This should help with the confusion that they don't correspond to what the user might be expecting (@katsar0v would a message like "Warning: creating implicit service 'root' from service_tokens, not in services list. It is recommended to register services in the list." have helped you catch this more easily?)

I think we need to check if the service is registered by modifying `_add_tokens`. I will make a pull request and try this.

**Comment by katsar0v** [comment]
I guess something like this would do it: https://github.com/jupyterhub/jupyterhub/pull/2704

**Comment by dmpe** [comment]
> ```python
> c.JupyterHub.services = [
>     {
>         'name': 'myservice',
>         'api_token': '675982d420fbed3bb6403ecd803a24ace814fdab37815b7d24f741c84237d',
>         'admin': True,
>     },
> ]
> ```

For anybody who is going to use jupyter helm chart: 

in kubernetes, this would translate to

```
  services:
    apikey: # any name here
      apiToken: 'd0cca762cd114793xxxxebc23'
      admin: true
```
