### ISSUE TITLE
About the deploying of large scale working platform

### ISSUE THREAD

**Issue by Ling19871017** [jupyterhub/jupyterhub#2669]
We encountered a problem that we met a bottle neck of performance of hardware. According to the documents published on the official website of JupyterHub, we need the computational resource about at least 1 core of CPU and 128 Mbytes of memory for each person programming at the same time. If we employed these configuration, each user could only open 1 or 2 ipynb files. If the users want to open more ipynb files then we need to increase the memory on the relevant settings. Now, for example, if we need to build a platform for supporting about 100 employees programming at the same time, then we need more than 100 cores of CPU and 25 Gbytes which are even not including the basic usage of the operating system. Which are too expansive. So we have some questions followed:
1. Dose JupyterHub have any load-balanced or CPU-shared, memory-shared solutions to fix our problems? 
2. If it does, how should I configure?
3. If it doesn't, can you recommend the basic requirements for supporting our scenario from perspectives either software or hardware?
We are looking forward to getting your feed back. Thank you very much!

**Comment by betatim** [comment]
For a large scale deployment of 100 concurrent users I'd look at http://z2jh.jupyter.org/ which is one of the most frequently used methods of deploying a scalable JupyterHub.

**Comment by Ling19871017** [comment]
> For a large scale deployment of 100 concurrent users I'd look at http://z2jh.jupyter.org/ which is one of the most frequently used methods of deploying a scalable JupyterHub.

Actually I would rather deploy the working platform on the local server than on the cloud. However we need to purchase a server for deploying at a limited budget, so we are looking for solutions that could allocate computational resource, such as CPU and memory, dynamically. I'd like to know whether the JupyterHub has that kind of setting or spawner could do that?

**Comment by betatim** [comment]
I don't understand what you mean with allocate CPU/memory dynamically? Do you mean you want to start new servers when the ones that are currently running have run out of free resources or do you want to limit how much CPU/memory users can use?

If you need a multi machine setup (and can't use the cloud) I'd still look at Z2JH as well as running your own, local kubernetes cluster.

If you need to limit the resources a user can use look at the docker spawner or systemd spawner.

**Comment by Ling19871017** [comment]
> I don't understand what you mean with allocate CPU/memory dynamically? Do you mean you want to start new servers when the ones that are currently running have run out of free resources or do you want to limit how much CPU/memory users can use?
> 
> If you need a multi machine setup (and can't use the cloud) I'd still look at Z2JH as well as running your own, local kubernetes cluster.
> 
> If you need to limit the resources a user can use look at the docker spawner or systemd spawner.

for example, I have 10 employees programming by using JupyterHub at the same time. If I set c.Spawner.mem_limit=256m, when one of users login on the platform, spawner will start a new process which occupies about 70m memory, right? Then this user still have 186m (256 - 70 = 186) memory space left to take, if the basic requirement of running an ipynb file costs about 50m memory, then this user can open about 3 ipynb files bacause of the limited memory. I've tried to open more than the limit, but JupyterHub will kill the process of the ipynb automatically. If I don't set c.Spawner.mem_limit, then I can't ensure that someone will take much more memory than they are supposed  to take. But when c.Spawner.mem_limit has been set, then if someone has already opened 3 ipynb files, others can't use this part of memory even that guy doesn't write even a little code. So what I wanted to ask was that whether there was any methods which can "lend" some memory to others by taking the spare occupied memory? So that the total memory taken by users would be lower than 2560m (256m * 10 users) if everyone opens 3 ipynb, and we could even increase the utilization of computational resource.

**Comment by betatim** [comment]
Thanks for the clarification. The answer depends on which spawner you are using. For a single machine setup I'd look at [systemdspawner](https://github.com/jupyterhub/systemdspawner) or [dockerspawner](https://github.com/jupyterhub/dockerspawner) (if you want to go down the container route).

I think systemdspawner supports a "soft" memory limit. Its features are mostly driven by what systemd units can do. So reading about how systemd units and cgroups work is the thing to do.

I once investigated memory limits and swap usage: all I know is in https://github.com/jupyterhub/systemdspawner/issues/39

**Comment by ryogesh** [comment]
@Ling19871017, when a new process is spawned for a user, 256m is not pre-allocated for the user. Memory will only be allocated as required.

Using your numbers, if 5 users have opened 2 notebooks and 5 users with 3 notebooks, the memory consumption calculation (roughly) is more like 5*(70 + 2*50) + 5*(70 + 3*50)  = 1,850 and not 10*256 = 2,560

**Comment by Ling19871017** [comment]
> @Ling19871017, when a new process is spawned for a user, 256m is not pre-allocated for the user. Memory will only be allocated as required.
> 
> Using your numbers, if 5 users have opened 2 notebooks and 5 users with 3 notebooks, the memory consumption calculation (roughly) is more like 5*(70 + 2_50) + 5_(70 + 3_50) = 1,850 and not 10_256 = 2,560

First of all, thank you for spending time on replying me, I had been to my business trip last month and I didn't even notice your replying.
I don't really understand how you calculate this equation: **5*(70 + 250) + 5(70 + 350) = 1,850**. Does 350 stand for the memory used by the user who has opened 2 notebooks? If so, does it mean that you haven't set parameter **c.Spawner.mem_limit** to limit the memory used by every single user? But actually I do want to set this parameter to limit it in case of some malicious user.

**Comment by ryogesh** [comment]
It should be 3 x 50 = 150, and not 350. I notice that the text appears as 2_50, 3_50 and 10_256 , don't know how * got changed to _.

So, it's more like 5(70 + 2 x 50) + 5(70 + 3 x 50) = 1,950 . I used the numbers that you had earlier.  i.e. 70M for new process and 50M for each notebook.

Setting c.Spawner.mem_limit is required to constraint memory usage as you rightly said. What i was saying is that when a new process is started, 256M will not be immediately allocated.   c.Spawner.mem_limit is the maximum memory each spawned process can get in it's lifespan. i.e. 
When user opens
 1 notebook they will be using more like 70 + 50 = 120M
2 notebooks, 70 + 2 x 50 = 170M
3 notebooks 70 + 3 x 50 = 220M
If say a user tries to open more than 3 then you will run into error. i.e. 70 + 4 x 50 = 270 > 256M. 

You can observe the memory use of a process by running top or other similar commands.

**Comment by Ling19871017** [comment]
> It should be 3 x 50 = 150, and not 350. I notice that the text appears as 2_50, 3_50 and 10_256 , don't know how * got changed to _.
> 
> So, it's more like 5(70 + 2 x 50) + 5(70 + 3 x 50) = 1,950 . I used the numbers that you had earlier. i.e. 70M for new process and 50M for each notebook.
> 
> Setting c.Spawner.mem_limit is required to constraint memory usage as you rightly said. What i was saying is that when a new process is started, 256M will not be immediately allocated. c.Spawner.mem_limit is the maximum memory each spawned process can get in it's lifespan. i.e.
> When user opens
> 1 notebook they will be using more like 70 + 50 = 120M
> 2 notebooks, 70 + 2 x 50 = 170M
> 3 notebooks 70 + 3 x 50 = 220M
> If say a user tries to open more than 3 then you will run into error. i.e. 70 + 4 x 50 = 270 > 256M.
> 
> You can observe the memory use of a process by running top or other similar commands.

I got what you meant. Thank you for your clarification. I should say that the memory used is up to 2,560 if the limit is set 256m. But by considering the worst situation, which means everybody uses 256m, my server needs to have spare 2560m memory at least before the system start to run, doesn't it?

**Comment by ryogesh** [comment]
If you are expecting maximum concurrent usage , then yes you need to plan for capacity.
Volume testing is recommended to confirm your upper bounds.
Also, setting c.DockerSpawner.remove = True  may provide some benefits.

**Comment by Ling19871017** [comment]
> If you are expecting maximum concurrent usage , then yes you need to plan for capacity.
> Volume testing is recommended to confirm your upper bounds.
> Also, setting c.DockerSpawner.remove = True may provide some benefits.

Thank you very much.
