### ISSUE TITLE
Starting Jupyterlab in jupyterhub leads to a blank screen

### ISSUE THREAD

**Issue by arinbasu** [jupyterhub/jupyterhub#2674]
Hi All,

I installed Jupyter lab on the Jupyterhub using an ansible script. 
When I start jupyter lab using 
https://xxx.xxx.xxx.xx/teaching/user/myusername/lab, instead of seeing the familiar jupyterlab screen, I see 'nothing', a blank page. It does not return a 502 or 404 error, but it displays a blank white page (see the image linked below):
[![blank-screen-jupyterlab.png](https://i.postimg.cc/QC8cqgss/blank-screen-jupyterlab.png)](https://postimg.cc/r0HdVrKY)
https://i.postimg.cc/QC8cqgss/blank-screen-jupyterlab.png

I clicked on the browser console, and a bunch of messages here:
[https://arinbasu.github.io/life_is_error/jupyterlab.txt](https://arinbasu.github.io/life_is_error/jupyterlab.txt)

I have become so used to work with Jupyter lab that I do not 'enjoy' working with jupyter notebooks, although in my case, jupyter notebooks work just fine.
I'd greatly appreciate any insight or advice as to how I can get back the jupyter lab page. I tried following the advices in a related github issue request (that was closed) but it did not work. [I also opened an issue in the jupyterlab github repo](https://github.com/jupyterlab/jupyterlab/issues/6941) as well.

Best,
Arindam Basu

p.s. If it helps, I have opened a discussion topic, here is the link: [https://discourse.jupyter.org/t/blank-browser-screen-when-i-start-jupyter-lab-on-jupyterhub-what-shall-i-do/1824?u=arinbasu](https://discourse.jupyter.org/t/blank-browser-screen-when-i-start-jupyter-lab-on-jupyterhub-what-shall-i-do/1824?u=arinbasu)

**Comment by betatim** [comment]
I am not sure but maybe the problem is that https://arinsclasses.info.tm/teaching (your host) has a self-signed certificate. I get a big warning from my browser about not visiting the page. Maybe there is something related to that which is breaking things.

I'd try using letsencrypt to (temporarily) get the certificate and once that is working see if you can debug the self-signed case.

**Comment by arinbasu** [comment]
Thanks a million for your response, @betatim ! To answer your other question, the Jupyter notebook UI works just fine.

**Comment by betatim** [comment]
If the Jupyter notebook interface works then I am a bit baffled to be honest. Because if loading other resources was the problem (because of the self-signed cert) then this would effect the classic notebook UI as well. I am out of ideas :(

**Comment by arinbasu** [comment]
:-), I too am baffled totally. Everything was working fine till Friday evening when I installed bokeh and bokeh jupyterlab extension. The installation went smoothly, and I was happily playing creating nice bokeh visualisations in jupyter lab. So far so good. Turned off computer on Friday, and reopen on Saturday morning. Jupyter lab did not load. Uninstalled the extensions, no change. Restarted jupyterhub through ansible, nothing changed. Deleted the sqlite database and started over, no change. Deleted the entire installation and started over. No difference.
At this point I gave up and raised the issue.

**Comment by manics** [comment]
Have you tried using a completely clean browser setup? Either clear all caches/cookies etc, or setup a new browser profile, or use a different browser? This would rule out some hidden caching.

**Comment by manics** [comment]
Found this potentially related issue: https://discourse.jupyter.org/t/lost-colorization-in-jupyter-notebook/1257

**Comment by arinbasu** [comment]
Hi @manics , thank you for the  suggestion. Yes, of course, that was the first thing I did; I cleared browser cache and history (everything) on all browsers in linux, mac, and windows laptops  I use and tried, no effect whatsoever. I tried using incognito mode in firefox and private mode in Chrome and Brave, no effect.

**Comment by betatim** [comment]
I'd go back to the jupyterlab devs with this question. If classic notebook works as expected and it broke after installing a lab extension it probably requires more knowledge about lab than about hub to debug.

**Comment by arinbasu** [comment]
Yes, I opened an issue with the Jupyterlab repo and also a discussion at their discourse site. A member of their developer team (I reckon) advised me to open an issue here sensing it might be something to do with self-signed SSL as opposed to something like LetsEncrypt. As this instance is hosted on a university server, I have contacted the University tech support and they promised they are looking into it. 
It's an interesting problem. At least Jupyter notebooks are working as expected, but once you get used to working with Jupyter lab, and if you have to return to jupyter notebooks, the feeling is not the same.

**Comment by carluri** [comment]
Similar issue for me,
I installed jupyterhub and jupyterhub using the ansible script and instructions provided in this repository
https://github.com/jupyterhub/jupyterhub-deploy-teaching

However, the notebook is not working either.  It looks like I lost all the styling or something similar and it now looks like this when I go to the `\tree` url.

![image](https://user-images.githubusercontent.com/3673343/63180239-b3c4d680-c002-11e9-8d01-55cc59b75d59.png)

**Comment by sigurdurb** [comment]
@carluri It looks like it is the css and javascript not loading correctly due to Mime Type or Content-Type: text/html   and not Content-Type: application/javascript


Did you find a solution for this ?

I have packages:
notebook                  6.0.3                    py37_0    conda-forge
jupyterhub                0.8.1                    pypi_0    pypi


Here are some other ones I have also that could be relevant:
```
jupyter                   1.0.0                    pypi_0    pypi
jupyter-contrib-core      0.3.3                    pypi_0    pypi
jupyter-contrib-nbextensions 0.5.1                    pypi_0    pypi
jupyter-highlight-selected-word 0.2.0                    pypi_0    pypi
jupyter-latex-envs        1.4.6                    pypi_0    pypi
jupyter-nbextensions-configurator 0.4.1                    pypi_0    pypi
jupyter-nbutils           0.1.3                    pypi_0    pypi
jupyter-require           0.6.1                    pypi_0    pypi
jupyter-telemetry         0.0.5                    pypi_0    pypi
jupyter_client            5.3.4                    py37_0
jupyter_console           6.1.0                      py_0
jupyter_core              4.6.1                    py37_0

widgetsnbextension        3.5.1                    py37_0
tornado                   5.1.1            py37h7b6447c_0
mistune                   0.8.4            py37h7b6447c_0
```

**Comment by carluri** [comment]
Hi @sigurdurb . No I still haven't found a solution for this, I've had to go back to a beta version of the jupyter lab.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/problems-when-running-julia-on-jupyterlab/4447/8
