### ISSUE TITLE
Get notebook/user context from python?

### ISSUE THREAD

**Issue by wierzba3** [jupyterhub/jupyterhub#2675]
I'm running JHub 0.8.2 on AWS EKS cluster

I would like to know if it is possible to retrieve the owner of the current notebook server.

E.g.
Let's assume I navigate to https://myjupyterhubhost.com/user/john-doe/notebooks/SampleNotebook.ipynb

In python, I want to do this:
```
user = get_current_context().get_notebook_user_owner()
print(f"The user who owns this notebook server: {user}")

# Output:
# The user who owns this notebook server: john-doe
```

**Comment by GeorgianaElena** [comment]
Hi @wierzba3! Maybe the env var *JUPYTERHUB_USER*: https://github.com/jupyterhub/jupyterhub/blob/b1606f21e6afbcce6b9fd4bbdd07b29448a8f3f5/jupyterhub/spawner.py#L716 is what you're looking for?

**Comment by wierzba3** [comment]
Yes! that is exactly what I am looking for ,thank you
