### ISSUE TITLE
Refresh token stored in auth_state before spawning notebook

### ISSUE THREAD

**Issue by guimou** [jupyterhub/jupyterhub#2676]
Some context (sorry for the length): on our datascience platform we use JupyterHub on OpenShift with KubeSpawner to launch on-demand notebooks. Users are authenticated with OAuth against Keycloak. We also have an object-based shared datalake (on Ceph), and users have S3 access keys/secrets to connect to their buckets.
As we don't want users to manipulate their keys or put them into the code (lots of sensitive data), we store them in Hashicorp Vault and inject them in the notebook as environment variable at spawn time. And to avoid using a Vault service account that has access to all keys, we use a dynamic policy in Vault that make use of user's JWT gained from Keycloak to retrieve its own and only secrets.
This is implemented in an Authenticator class:
```
class EnvGenericOAuthenticator(GenericOAuthenticator):
    @gen.coroutine
    def pre_spawn_start(self, user, spawner):
        import hvac
        import json
        import requests

        # Retrieve user authentication info
        auth_state = yield user.get_auth_state()
        if not auth_state:
            # user has no auth state
            return
        # This line for debug
        print(auth_state)

        vault_url = os.environ['VAULT_URL']
        vault_login_url = vault_url + '/v1/auth/jwt/login'
        vault_login_json = {"role":None, "jwt": auth_state['access_token']}

        # Login to Vault with JWT 
        vault_response_login = requests.post(url = vault_login_url, json = vault_login_json).json()

        # Retrieve user entity id and token
        vault_token = vault_response_login['auth']['client_token']
        vault_entity_id = vault_response_login['auth']['entity_id']
        
        # Connect to Vault and retrieve info (finally!)
        vault_client = hvac.Client(url=vault_url, token=vault_token)

        if vault_client.is_authenticated():
            secret_version_response = vault_client.secrets.kv.v2.read_secret_version(
                mount_point='valeria',
                path='users/' + vault_entity_id + '/ceph',
            )   
            AWS_ACCESS_KEY_ID = secret_version_response['data']['data']['AWS_ACCESS_KEY_ID']
            AWS_SECRET_ACCESS_KEY = secret_version_response['data']['data']['AWS_SECRET_ACCESS_KEY']
        else:
            AWS_ACCESS_KEY_ID = 'none'
            AWS_SECRET_ACCESS_KEY = 'none'
        # Retrieve S3ContentManager infomation and update env var to pass to notebooks
        s3_endpoint_url = os.environ.get('S3_ENDPOINT_URL')
        spawner.environment.update(dict(S3_ENDPOINT_URL=s3_endpoint_url,AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY))
```
The problem we have is that the JWT expires after some time and is not renewed as pre_spawn_start seems to be called only once. So when a user authenticates and comes back after a while, the expired token that has been stored in auth_state is retrieved from the database and of course Vault access fails.
I tried using something like:
c.GenericOAuthenticator.refresh_pre_spawn = True
but that does not seem to do anything. If I understand well I have to implement the method myself in GenericOAuthenticator or in my custom class. Is that right?
Is there some other way to refresh auth_state before every spawning? I thought also of using post_spawn_stop hook to clear auth_state, but how would I do that?
Thanks for any advice or any other solution!
(btw, everything about this project will be shortly released, along with a complete article if anyone is interested).

**Comment by betatim** [comment]
You have to implement `refresh_user(user)` in your authenticator. Take a look at

**Comment by guimou** [comment]
That's what I was afraid of, I had understood the code right... :-)
I'll give it a try and come back to update/close the issue.
Thanks!

**Comment by guimou** [comment]
Hi! I have implemented the function and made this PR: https://github.com/jupyterhub/oauthenticator/pull/287
And as promised, here is the link to the story I published about our project: https://medium.com/@guillaume.moutier/deploying-a-scalable-shared-data-science-platform-at-universit%C3%A9-laval-b26e7e02cba4

**Comment by kimsk** [comment]
I tried to set `c.Auth0OAuthenticator.refresh_pre_spawn = True`, but I keep getting something like 

> Config option `refresh_pre_spawn` not recognized by `Auth0Authenticator`.

And I don't see my customized `refresh_user` get called. Do you know what I am missing? This is the K8s setup.
Thanks!
