### ISSUE TITLE
user's jupyterlab instance stuck in hub

### ISSUE THREAD

**Issue by yee379** [jupyterhub/jupyterhub#2680]
i use kubespawner in jupyterhub. jupyterhub is using the sqlite backend. sometimes the instances die to resource limitations on the k8s minions and sometimes as a result the hub appears to be out of sync with what jupyterlab pods are actually running.

the user typically get's a 502 or 503 in the cases where there is a mismatch between the running instances and what the hub thinks is running.

normally, this is not an issue as i am able to just 'delete user' in the admin page and then the user can spawn another instance. however, in this case i have a user with a running server (according to the hub) but with no kubernetes pod. when i click on 'delete user' i get 

    API request failed (400): blah's server is in the process of stopping, please wait.

is there a way i can force 'clean' this user? clicking on 'stop server' spits out the following in the logs:

202 DELETE /hub/api/users/blah/server (me@127.0.0.1) 32.03ms

the icon changes to 'start server', but a refresh of the admin page pops it back to 'stop server'

**Comment by GeorgianaElena** [comment]
Hi @yee379! I *think* [this issue](https://github.com/jupyterhub/jupyterhub/issues/2043) may be related.
