### ISSUE TITLE
Allowing custom errors/exception messages in JupyterHub 

### ISSUE THREAD

**Issue by sntgluca** [jupyterhub/jupyterhub#2681]
Dear all,

I wish to address a specific customisation problem I am having, hopefully staying in line with the code of conduct and the spirit of improving JupyterHub.

I am using JupyterHub to start Jupyter notebook servers on a HPC environment, via the GridEngineSpawner, which works brilliantly.

I wish I had a simple way to capture default exception messages - raised for instance in runtime by `run_command` - and return messages more meaningful for my users. For instance, I'd like to transform an internal error `sudo: unknown user` into `Please request access ... to use JupyterHub`.

I couldn't find a simple way to achieve this without mangling directly into the code, which I would like to avoid. My knowledge of tornado and Jupyter doesn't let me go that far.

Is there already any way to address my task, or can JupyterHub logic be extended to include this option?

Thanks
Gianluca

**Comment by ryogesh** [comment]
I understand your request as, you are looking to change the display/output on the notebook when an error occurs.

Here is a sample code; i.e wrap your code in a function

Sample code:
----------------
from IPython.display import display
def f():
    try:
        raise Exception('run command error: Will i be shown?, No')
    except:
        display("Please request access ... to use JupyterHub")
        
f()

OR you can refer below for additional ui controls
1)

https://ipywidgets.readthedocs.io/en/latest/examples/Output%20Widget.html

Sample code: Using code from the documentation
Cell1:
import ipywidgets as widgets
out = widgets.Output()
out

Cell2: # Your code where exception may happen 
@out.capture()
def function_with_captured_output():
    print('This and below will not able in the output widget, but the custom message from below')
    raise Exception('sudo: unknown user')

function_with_captured_output()
out.clear_output()
out.append_stderr('Please request access ... to use JupyterHub')

2) 
https://ipywidgets.readthedocs.io/en/latest/examples/Using%20Interact.html

interactive can be used

**Comment by sntgluca** [comment]
Hi @GeorgianaElena ,

thanks for your prompt answer and for offering so many alternatives. I have lost track of this request - apologies for the delay in following up.

As I suspected, I wasn't clear. 
My problem is with the GridEngineSpawner, not in a notebook itself.

Let me try to rephrase: In `batchspawner.GridEngineSpawner` (version 0.8.1) a process is starting with the `run_command` coroutine:

https://github.com/jupyterhub/batchspawner/blob/ce0729dd1ba16db62cb4e72e37a8d987dacd7007/batchspawner/batchspawner.py#L37

I wish to capture the exception generated by the coroutine, but all my attempts failed.
Ideally I'd like to write something like this, which doesn't work:

```
class MySpawner(batchspawner.GridEngineSpawner):
    def run_command(cmd, input=None, env=None):
        try:
            return super().run_command(cmd, input, env)
        except:
            <do something here>
```

Any idea?
Thanks again

**Comment by ryogesh** [comment]
run_command is not a class method. It's a module method.
Create a run_command method and change the batchspawner.run_command to your run_command method.

e.g. If your module file, lets call it functest.py has the following
from datetime import date

def run_command(cmd):
    print('Printing input', cmd)

class BSB():
    ip = '0.0.0.0'
    strt_dt = date.today()
    
    def cls_fn(self, cmd):
        print('In class', cmd)

Below, shows how to override the module function
>>> import funtest
>>> dir(funtest)
['BSB', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'date', 'run_command']
>>> funtest.run_command('change')
Printing input change
>>> def my_cmd(cmd):
...     print('New input', cmd)
...
>>> my_cmd('change')
New input change
>>> funtest.run_command = my_cmd
>>> funtest.run_command('change')
New input change

i.e. it will no longer output "Printing input change"

**Comment by sntgluca** [comment]
Thanks @ryogesh ,

I will try this!
