### ISSUE TITLE
pre_spawn_start exceptions may lead to redirect loop

### ISSUE THREAD

**Issue by clkao** [jupyterhub/jupyterhub#2683]
**Describe the bug**

if we override authenticator `pre_spawn_start` with a coroutine and throw exceptions from it, it could lead to the redirect loop issue with an eventual 500 error, instead of showing the exception.  however, exceptions `options_from_form` are rendered properly as error message.

**To Reproduce**
1. override authenticator pre_spawn_start and throw exception from it
2. try to launch user server from hub
3. gets infinite redirect
4. reload and see 500 error

**Expected behavior**

errors are displayed in the spawner page

cc/@aar0nTw

**Comment by aar0nTw** [comment]
#2684 fix this problem, @GeorgianaElena 👍 
cc/@clkao
