### ISSUE TITLE
Reliability of RUNNING_SERVERS metric

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#2685]
# UPDATE

This issue started out with me confused about RUNNING_SERVERS showing the wrong number, but that related to my use of JupyterHub 1.0.0 where [a bugfix](https://github.com/jupyterhub/jupyterhub/pull/2629) had not been implemented yet. Now this issue tracks if the metric is reliable enough.

@GeorgianaElena wrote:
> I'm still not very convinced that RUNNING_SERVERS works properly in the cases where an error occurs while adding the server to the proxy thinking.

---

I found that running_servers reported by the /hub/metrics endpoint were incorrect. My value was in reality 7 but the endpoint reported 3. So, I looked into this by [searching for `RUNNING_SERVERS`](https://github.com/jupyterhub/jupyterhub/search?q=running_servers&unscoped_q=running_servers) in the jupyterhub code base and tried to learn more about this.

## What I learned

I learned that the RUNNING_SERVER metric is defined here...

https://github.com/jupyterhub/jupyterhub/blob/2320d59bd13af1298ac7bf68471e1e6d11ab691f/jupyterhub/metrics.py#L38-L40

... and is initially configured from init_spawners() ...

https://github.com/jupyterhub/jupyterhub/blob/9e0bb5cc71649e5fb19d07e4c72a967a72819219/jupyterhub/app.py#L1944-L1946

... and that it is set and then increased within a spawn_single_user() ...

https://github.com/jupyterhub/jupyterhub/blob/24c08292899492bb0bd5e2b7fdbf7e09cf1a4057/jupyterhub/handlers/base.py#L753-L762

... that in turns will invoke a local finish_user_spawn() function ...

https://github.com/jupyterhub/jupyterhub/blob/24c08292899492bb0bd5e2b7fdbf7e09cf1a4057/jupyterhub/handlers/base.py#L851-L870

... and it is decremented after a successful stop() without errors ...

https://github.com/jupyterhub/jupyterhub/blob/60f5ce0ff831dd3e5f5eade9eacd8b3812525bd6/jupyterhub/user.py#L763

## Conclusions
I'd like to verify if the initial value set in init_spawners() is correct. If it is, we can assume the logic of incrementing / decrementing this initially set value has an issue and focus on that. So, I did this and concluded that the metric reported by /hub/metrics were 0 after a hub restart, and that there was actually 4 servers running at that point, and that the /hub/admin listed these to be actually running. So whatever issue there is, the /hub/admin's list of running servers is out of sync with whatever is set during init_spawners() for me. I verified that I was able to go to -1 in running_servers by shutting down a currently running one.

I think we can get a faulty count in RUNNING_SERVERS by incrementing / decrementing it conditionally on start / stop, and this is kind of what we indirectly is doing by doing it within `try` blocks instead of finally blocks. Perhaps we can improve something here?

## Related
https://github.com/jupyterhub/jupyterhub/pull/2629

**Comment by GeorgianaElena** [comment]
Thanks for reporting this @consideRatio. Looking at this again, it does seem that by having the  RUNNING_SERVERS incremented in the try block, if an exception occurs, the metric will be decremented when the server is stopped without actually being increased in the first place :disappointed: . The reason why the metric is incremented in the try block is because I considered it to be the indicator that the server spawn was completed successfully.

I'm seeing two possible fixes:
* increment in the finally block, although from my perspective I think it's a bit confusing to count a server as running if an exception occurred.
* decrement in ``user.stop()`` only if the server we're stopping was actually successfully added to the proxy (maybe using PROXY_ADD_DURATION_SECONDS...)

What do you think @consideRatio? Sorry if I hadn't been very coherent with all the increments and decrements and for not fixing this correctly in the first place :(.

**Comment by consideRatio** [comment]
@GeorgianaElena ah but hey to be clear I'm very happy there is a foundation in place to get these metrics and really appreciative of the work done on this, with a bug or not somewhere!

---

I've tried to understand things further and I'm confident that the main issue I experience is with the initialization of the metric, it reports there are 0 TOTAL_USERS and 0 RUNNING_SERVERS on hub restarts.

Currently the only thing I'm confident about is my own lack of understanding :) I'll try to figure out what I think could be a good course of action, I'm in the happy learning phase at the moment. I'm new to this code base and collecting metrics in general.

**Comment by consideRatio** [comment]
Woops @GeorgianaElena I was using JupyterHub 1.0.0 released in May, which is part of the z2jh helm chart's jupyterhub. So, I didn't utilize the work you did in #2637 and other related PRs!

This is why I was initialized at 0 TOTAL_USERS for example. And while the total number of users could get out of sync, that was not my main issue.

**Comment by GeorgianaElena** [comment]
No worries @consideRatio. Does TOTAL_USERS seems to be counting accurately now?
I'm still not very convinced that RUNNING_SERVERS works properly in the cases where an error occurs while adding the server to the proxy :thinking:.
I'll try to investigate this further :female_detective:

**Comment by consideRatio** [comment]
I have not yet tested my deployment with the jupyterhub most recent version =/ But I'm confident your already merged fixes does the trick for initializing TOTAL_USERS.

> I'm still not very convinced that RUNNING_SERVERS works properly in the cases where an error occurs while adding the server to the proxy :thinking:.
I'll try to investigate this further :female_detective:

I think this could be an issue as well, but perhaps it rarely happens, and it will get corrected on the next hub restart probably. It is nice to end up with something very robust though so :heart: for investigating!

**Comment by belfhi** [comment]
Just realized this was an issue by setting up monitoring for our Jhub deployments (batchspawner on HTCondor and SLURM) and noticed the wrong numbers. Is it fixed in the master and in an upcoming minor release @consideRatio ?

**Comment by consideRatio** [comment]
It is available in master, and the next release. I'm working towards making a actual versioned release, but have been for quite a while, so I'd go with current master if you need it. It has now passed upgrade tests from 0.8.2 for example!

**Comment by belfhi** [comment]
No, as long as I can see active servers from the admin panel, it's fine. And I'm glad the fix has been already implemented. Will test it on a non-production machine!

**Comment by ianabc** [comment]
Should this metric correspond to the total user count displayed in the admin interface? In my case it doesn't (by a lot), but that would be a useful number for me to have available.

**Comment by consideRatio** [comment]
@ianabc I think it should, what version of JupyterHub are you using?

@GeorgianaElena I recall this was an issue that was fixed before, do you remember?

**Comment by ianabc** [comment]
I'm running 1.2.1, but if the number agrees in the tests and other contexts it's possible I'm doing something silly in the authenticator. I just wanted to check if I should expect those values to match. I'll dig around a bit more and see if I can spot what is going wrong in my case. Thank you!

**Comment by consideRatio** [comment]
@ianabc oh sorry, the Total user count shouldnt be the same, but the total running servers should be.

Jupyterhub remembers a username if it has logged in so it adds to the total user count even if the user's server is stopped.

**Comment by ianabc** [comment]
No, I think you were right the first time. My `running_users` metric seems to be working correctly; it always corresponds with the actual number of running containers. However, my `total_users` metric is not; I _think_ `total_users` should be equal to the number of rows of the `user` table of the database (i.e. the total number of independent users who have used the system at some point), but in my case it is substantially different. 

Interestingly the admin interface reports what I think is the correct number (the number of rows of the user table) but the `total_users` emitted as a prometheus metric is very different.

As I mentioned above it is possible something is wrong in my authenticator, but if you have time could you compare any of these numbers on your systems? (`total_users` vs. number of `user` rows vs. total in admin interface)

**Comment by consideRatio** [comment]
I assume you have a paginated list of users in the admin view, and that jupyterhub's logic to list total nr of users is using the list to deduce the tortal nr of users. This would then be just wrong, and it should instead use the same data as the metric reports.

I'll compare in a system of mine and get back to you

**Comment by ianabc** [comment]
Yep, as far as I can tell the paginated list looks correct, it reports the total as e.g. `Displaying users 1 - 100 of 2752`. In this case 2752 corresponds with the expected number of users. If I manually `SELECT COUNT(id) FROM users`, that also gives me 2752. On the other hand total_users on that machine is reporting 5492. If your numbers are consistent with each other I'll take a closer look at the authenticator.

**Comment by consideRatio** [comment]
Closing this in favor of #3280!
