### ISSUE TITLE
Single login only

### ISSUE THREAD

**Issue by sdd3** [jupyterhub/jupyterhub#2688]
Since upgrading to 1.0, my jupyterhub install will only accept the first login session and gives an invalid username or password error for any attempted subsequent login. This happens even if the initial user is logged out and attempts to log in again. 
I am not sure if there is something like permissions that need to be configured in 1.0 which was not an issue in earlier releases.
Any advice would be very welcome.

Update: Seems selinux is objecting to any authentications after the first. Disabling selinux is a workaround

**Comment by ryogesh** [comment]
Can you check the selinux audit log file?

Also, can you run jupyterhub with DEBUG enabled on  spawner, proxy... and check the log file. You may see information that might help

**Comment by sdd3** [comment]
Thanks for the suggestions. It does seem to be an selinux issue

**Comment by GeorgianaElena** [comment]
Closing this issue as it appears to be resolved :rocket:. Thanks a lot @ryogesh :four_leaf_clover: 
@sdd3, feel free to open a new issue or reopen this if you need more help.

**Comment by sdd3** [comment]
Thanks  @GeorgianaElena. 
In fairness the issue is not resolved since it is not a great idea to disable SELinux. If you wish to flag it as resolved no problem though. 
I will post here any better solution if I find one.

**Comment by GeorgianaElena** [comment]
Sorry for rushing to close it @sdd3.

**Comment by sdd3** [comment]
No worries

**Comment by manics** [comment]
@sdd3 What's the selinux error? What do `sudo audit2allow -a` `sudo audit2why -a` show?

**Comment by sdd3** [comment]
Thank you @manics. It was the jupyterhub command itself that selinux was causing the denial.
`sudo grep denied audit.log | audit2allow -M jh-module` 
`semodule -i jh-module.pp`
revises the policy (see [http://aircconline.com/ijsea/V9N2/9218ijsea01.pdf](url))
