### ISSUE TITLE
JupyterHub can't find spawned notebook

### ISSUE THREAD

**Issue by retypuj** [jupyterhub/jupyterhub#2689]
Hi,

I'm trying to get JupyterHub running on Kubernetes with KubeSpawner and external Traefik as the proxy.
JupyterHub is capable of spawning a singleuser notebook on a new pod, but fails to redirect the user to his spawned notebook with:
```
pods watcher timeout
Connecting pods watcher
events watcher timeout
```

`jupyterhub_config.py`:
```
c.JupyterHub.authenticator_class = 'jupyterhub.auth.DummyAuthenticator'
c.DummyAuthenticator.password = "test"
c.JupyterHub.bind_url = 'http://0.0.0.0:8000'
c.JupyterHub.cleanup_servers = True
c.JupyterHub.hub_ip = ''
c.JupyterHub.proxy_class = 'traefik_toml'
c.JupyterHub.spawner_class = 'kubespawner.KubeSpawner'
c.Authenticator.admin_users = set('test')

import os
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect(("8.8.8.8", 80))
host_ip = s.getsockname()[0]
s.close()
c.KubeSpawner.hub_connect_ip = host_ip
c.JupyterHub.hub_connect_ip = c.KubeSpawner.hub_connect_ip
c.JupyterHub.hub_connect_url = 'http://{host}:{port}'.format(
    host=host_ip,
    port=8000
)

c.KubeSpawner.image = 'x.net/data-science/singleuser:latest'
c.KubeSpawner.image_pull_secrets = 'data-science-kubernetes-data-science-pull-secret'
c.KubeSpawner.namespace = 'data-science'
c.KubeSpawner.privileged = False
c.KubeSpawner.uid = 1000
c.KubeSpawner.fs_gid = 1
c.KubeSpawner.start_timeout = 60 * 60  # Up to 60 minutes
c.KubeSpawner.http_timeout = 60 * 60 # Up to 60 minutes
c.TraefikTomlProxy.should_start = False
# traefik api credentials
c.TraefikTomlProxy.traefik_api_username = "x"
c.TraefikTomlProxy.traefik_api_password = "x"
c.TraefikTomlProxy.traefik_api_url = "xx"
```
Is it even possibly to use Traefik like that? It's located on a different pod in a different namespace. JupyterHub writes a rules.toml file in the own local system and not where Traefik is located..

**Comment by GeorgianaElena** [comment]
Hi @retypuj! In your traefik static config should be something like this:
```
[file]
filename = "rules.toml"
watch = true
```
where filename is the path to the file used by traefik as its routing table.
Both traefik and JupyterHub need to know where this file is located:
* traefik can be informed about the ``rules.toml`` file through the static config described above
* JupyterHub can be configured though ``c.TraefikTomlProxy.toml_dynamic_config_file`` in the config file.
  By default, JupyterHub will assume there's a ``rules.toml`` in the current directory from where it's launched and if it's not, it will create it.

I don't have Kubernetes experience and I don't know this will work if the file is in a different pod, but my suggestion is: create an empty "rules.toml" at the location specified in traefik's static config then configure ``TraefikTomlProxy.toml_dynamic_config_file`` to point to that file (making sure it's accessible by JupyterHub (I don't know how this can be achieved in a Kubernetes context :disappointed: ))

*TraefikTomlProxy* is quite new and thus, not extensively used. It would be really cool to know there are setups successfully using it :four_leaf_clover: . Please let me know how it goes and hope I was able to help.

**Comment by retypuj** [comment]
Thanks @GeorgianaElena ! We decided to use the standard proxy since Traefik is not making it easier for us
