### ISSUE TITLE
Trying to spawn singleusernotebook on multiuserhub

### ISSUE THREAD

**Issue by bindrap** [jupyterhub/jupyterhub#2690]
am trying to launch single user notebook for suer in a multi user hub that is being launched by docker

[jupyterhub_config.txt](https://github.com/jupyterhub/jupyterhub/files/3516175/jupyterhub_config.txt)
[Dockerfile.txt](https://github.com/jupyterhub/jupyterhub/files/3516176/Dockerfile.txt)
[logs.txt](https://github.com/jupyterhub/jupyterhub/files/3516182/logs.txt)

**Comment by bindrap** [comment]
@minrk

**Comment by GeorgianaElena** [comment]
Hi @bindrap! Thanks for reporting this. [This issue](https://github.com/jupyterhub/dockerspawner/issues/243) seems similar and it might help.

**Comment by bindrap** [comment]
Hey @GeorgianaElena
I tried the solution but it still did not fix the issue.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
