### ISSUE TITLE
Running Jupyterhub and kernels in different anaconda environments

### ISSUE THREAD

**Issue by akamensky** [jupyterhub/jupyterhub#2691]
I have an issue running Jupyterhub installed via Anaconda environment where some packages that users require conflict with packages that Jupyterhub requires.

Most notably conflicting package is tornado where Jupyterhub requires v5.1.1, but the one that is required by the users dependencies is 6.x (Jupyterhub simply does not work on tornado 6+).

I am wondering would it be possible to have two separate Anaconda environments -- one to run Jupterhub itself, the other one is to run kernels. I am able to setup to separate anaconda envs, but can't seem to figure out how to set this up in Jupterhub.

**Comment by ryogesh** [comment]
Say you are running Jupyterhub from conda on /opt/anaconda3, then edit the file
"/opt/anaconda3/share/jupyter/kernels/python3/kernel.json"

And try updating the kernel.json to choose the other conda python kernel, say  /opt/anaconda3-1 
so change the argv values to use /opt/anaconda3-1/bin/python
"argv": [
"/opt/anaconda3/bin/python",

I haven't tried this, but feels it may work.

**Comment by akamensky** [comment]
The thing is that our installation launches “jupyterhub-singleuser” for each logged in user, which comes from installation of jupyterhub itself. It doesn’t launch ipython kernel on the CLI. That singleuser imports ipython from what I understand.

In short - this won’t work as I can see it so far because that other environment needs to also have jupyterhub installed. Am I missing something?

**Comment by ryogesh** [comment]
You will need to build a custom docker container (on the same lines as  jupyterhub-singleuser) with additional conda environment (think as above /opt/anaconda3-1) and edits to the jupyter kernel.json
