### ISSUE TITLE
[Question] Websocket setup and customisation

### ISSUE THREAD

**Issue by sntgluca** [jupyterhub/jupyterhub#2693]
Hi,

I have a (relatively) complex JupyterHub setup which starts with a SSO service (Vordel) redirecting to nginx and then to JupyterHub.
In this configuration the instructions to use a reverse proxy in https://jupyterhub.readthedocs.io/en/stable/reference/config-proxy.html are not enough to make it work: The backend websockets end up pointing to the original Vordel service, instead of JupyterHub.

I would like to know how the backend identifies the websocket url in JupyterLab by default.
My hope is to modify the environment configuration to force the backend setup the right IP. 

Many thanks

**Comment by sntgluca** [comment]
Hi,

is there anyone out there who can help with this question? I'd be happy to give more details and clarification if this would help!

Thanks

**Comment by sntgluca** [comment]
At the end, I decided to use the workaround described in

https://github.com/jupyterlab/jupyterlab/issues/7087

to get over this issue

**Comment by sunilag** [comment]
As pointed out by @sntgluca , the wss urls built by jupyterlab and notebook server are different.
For backwards compatibility sake, i would like to have jupyterlab build websocket url the same as that of Notebook. 
How do i go about achieving this. ? 
The other reason is , if we dont specify the spawner configuration i.e. c.Spawner.websocket_url = "ws://<ADDRESS>/<BASE_URL>" , the behaviour of both Jupyterlab and Jupyter Notebook are the same with respect to how final websocket url is constructed. i.e. ws://<ADDRESS>/<BASE_URL>/user/{username}
