### ISSUE TITLE
Potential @noob -- Cannot Spawn Container Jupyterhub with Simple Configurations

### ISSUE THREAD

**Issue by andybouts** [jupyterhub/jupyterhub#2699]
Hi all, this is potential @noob issue, but I am trying to do the most basic and it's not working on my via Docker on my Mac as well as on a RHEL 7.5 host.

I have recreated this multiple times:

Reference https://hub.docker.com/r/jupyterhub/jupyterhub/#docker

1) docker run -d -p 8000:8000 --name jupyterhub jupyterhub/jupyterhub jupyterhub
2) docker ps -a  # to make sure it's running
3) docker exec -it jupyterhub bash  # to exec in
4) apt update -y; apt upgrade -y; apt dist-upgrade -y; apt-get autoremove -y   # the apt updates were required to install nano
5) conda update -n base conda   # conda was complaining to be updated
6) conda install notebook
7) apt install nano
8) jupyterhub --generate-config
9) nano jupyterhub_config.py
--- add
c.JupyterHub.authenticator_class = 'jupyterhub.auth.DummyAuthenticator'
c.DummyAuthenticator.password = "some_password"
--- add
c.JupyterHub.spawner_class = 'simple'
--- or this one instead ... both give same results
c.JupyterHub.spawner_class = 'jupyterhub.spawner.SimpleLocalProcessSpawner'

10) exit  # exit the exec
11) docker stop jupyterhub
12) docker start jupyterhub
13) login with <anyId>:"some_password"
14) auth works fine, but will not spawn

What am I doing wrong?

<img width="892" alt="Screen Shot 2019-08-22 at 6 32 19 PM" src="https://user-images.githubusercontent.com/42046759/63554341-33730980-c50b-11e9-8b18-4666cd13dff0.png">

**Comment by GeorgianaElena** [comment]
Hi @andybouts! The docker image [contains only the Hub itself with no config](https://github.com/jupyterhub/jupyterhub/blob/7d9a93ab5f33b427cd2aadeb2169409d15bd66c1/README.md#docker), making JupyterHub to ignore *jupyterhub_config.py*. If you run ``docker logs jupyterhub`` you may see that the Hub uses a different authenticator/spawner than the one specified in the config (checkout how jupyterhub it's started without passing it a configuration file [here](https://github.com/jupyterhub/jupyterhub/blob/master/Dockerfile#L60) in Dockerfile).

I believe that if you'll additionally use https://hub.docker.com/r/jupyterhub/jupyterhub-onbuild (``docker pull jupyterhub/jupyterhub-onbuild``, followed by a container restart) that ads an ONBUILD step to load  the jupyterhub_config.py into the jupyterhub/jupyterhub image, should be enough to make JupyterHub pick up the configuration file. (see [Dockerfile](https://github.com/jupyterhub/jupyterhub/blob/master/onbuild/Dockerfile) for ref)

Hope this helps.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to ask on the [discourse site](https://discourse.jupyter.org/c/jupyterhub/10) or request that we reopen this issue. Thanks! 🌻
