### ISSUE TITLE
Change proxy log format from "%H:%M:%S.%L" to "%Y-%m-%d %H:%M:%S.%L"

### ISSUE THREAD

**Issue by nimengliusha** [jupyterhub/jupyterhub#2700]
Hi! Thanks for using JupyterHub.

If you are reporting an issue with JupyterHub, please use the [GitHub issue](https://github.com/jupyterhub/jupyterhub/issues) search feature to check if your issue has been asked already. If it has, please add your comments to the existing issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

- Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.
- Running in `--debug` mode can also be helpful for troubleshooting.

**Comment by nimengliusha** [comment]
Hi! 

       we are using jupyterhub v0.9.1, proxy log format "%Y-%m-%d" is unfriendly.
       we ourself change file configurable-http-proxy, line 90, from `return strftime("%H:%M:%S.%L", new Date());` to `return strftime("%Y-%m-%d %H:%M:%S.%L", new Date());`.
       please change the fix to the newest  jupyterhub version
       Best Wishes

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
