### ISSUE TITLE
Can I use a virtual environment for each project folder?

### ISSUE THREAD

**Issue by brayanrodbajo** [jupyterhub/jupyterhub#2707]
I have some github repos in a server and I would like to run that repos but in different virtual environments in the JupyterHub installed there. Is it possible?

**Comment by ryogesh** [comment]
On each of the jupyterhub config file, set c.Spawner.notebook_dir to the different repo/folder

**Comment by brayanrodbajo** [comment]
Thanks for responding! 
Do I have to restart the jupyterhub service each time I run a different repo?
And does not the dir of the virtual envs interfere?

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
