### ISSUE TITLE
Saved notebook joins all source lines in the notebook in one string

### ISSUE THREAD

**Issue by liyinan1001** [jupyterhub/jupyterhub#2710]
**Describe the bug**
Refer to this https://youtrack.jetbrains.com/issue/PY-35246
and this https://gitlab.com/gitlab-org/gitlab-ce/issues/59070.
Creating a jupyter notebook and then downloading it. The downloaded notebook has the same behavior in the first link. The notebook can't be rendered in gitlab because of this problem.

**Comment by ryogesh** [comment]
Is this a Pycharm issue or Jupyter issue?

Try this:
1)
Create a notebook with one cell and the below code, as per PY-35246, and save 
import os
from pathlib import Path
import numpy as np

2) Open the .ipnb file in another editor e.g. Notepad++ , change os to sys, Save

3) Open the file back in Jupyter,  source lines are retained

4) Re-open the file back in Notepad++ ,  source lines are retained

**Comment by willingc** [comment]
This appears to be an issue with PyCharm or the editor which you are using.

All Jupyter notebooks follow the Jupyter notebook format specification. Refer to the note in the [Jupyter notebook format specification](https://nbformat.readthedocs.io/en/latest/format_description.html#cell-types)
