### ISSUE TITLE
How to enable ingress without config.yml

### ISSUE THREAD

**Issue by retypuj** [jupyterhub/jupyterhub#2713]
Hi,
I want JupyterHub to create a Service and Ingress in Kubernetes for every new user. According to the doc https://zero-to-jupyterhub.readthedocs.io/en/latest/advanced.html#ingress I need to enable the ingress object via the `config.yml` file. But unfortunately we aren't using helm for our JupyterHub deployment.

How can I enable the ingress feature?

Thanks!

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
