### ISSUE TITLE
Custom ContentManager integration 

### ISSUE THREAD

**Issue by maltevogl** [jupyterhub/jupyterhub#2715]
I am developing a Custom ContentManager for Jupyter Notebook based on Seafile's FileAPI [SeafileContentManager](https://github.com/computational-antiquity/SeafileContentManager) that allows users to share files and supports automatic checkpoints. 

Everything is working for a single user Jupyter Notebook and Lab, however I am lost at the point of integrating the services for JupyterHub. 

For JupyterHub the user creation itself is handled by oauthenticator's generic module, which gives me correct usernames. Some necessary variables can be predefined for the institutional setup, i.e. the API-endpoint and the folder name used for sharing. 

However, each user requires an access token for the Seafile instance, that is generated by an API call with username and password. 
The questions are therefore: 

 - How can JupyterHub check at login if a user logs in for the first time?
 - If the user is new: how can I integrate a user dialog in JupyterHub, which sends this API call to Seafile?

It would be great, if you could point me to some examples for this.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
