### ISSUE TITLE
Tabbar doesn't load

### ISSUE THREAD

**Issue by Florianchn** [jupyterhub/jupyterhub#2718]
Everytime after  i build jupyterlab. The Tabbar and Toolbar can not be loaded correctly....

I installed it by anaconda..

![scs_1](https://user-images.githubusercontent.com/16947674/64235173-16b9d700-cef8-11e9-89fe-cfe55e611333.jpg)

**Comment by willingc** [comment]
Hi @Florianchn.

This repo is for issues related to JupyterHub. I would recommend asking your question on the [JupyterLab Discourse Forum](https://discourse.jupyter.org/c/jupyterlab). Thanks.
