### ISSUE TITLE
Impossibily to run Jupyter notebook from Windows start menu and required tokens

### ISSUE THREAD

**Issue by giansoldati** [jupyterhub/jupyterhub#2720]
Dear all, 

I am a novice in the use of Python and I am using PandasBiogeme to estimate discrete choice models.

My issue is related to the Jupyter notebook. Usually when I wish to use it, I select it from the start menu of Windows 7 and automatically a new tab opens up in Chrome.

Yesterday, actually by not knowing exactly why, I logged out from Jupyter notebook and today when I launched it from the start menu the following error message appeared:

![Error](https://user-images.githubusercontent.com/44930049/64260256-d9227180-cf2a-11e9-88bc-5f57d54d8a8a.PNG)

I thus decided to reinstall Anaconda, and PandasBiogeme and to update both of them. 

Now when I wish to open Jupyter notebook from the start menu a prompt menu appears and suddenly disappears. Therefore I need to open the Anaconda Powershell and type

`jupiter notebook`

Yet, when I do this I receive the same error message I reported above

I typed in the second URL and I was then able to work again. 

Yet, when I close Jupyter notebook and try to launch it again the same problem arises and I have to insert again 'a' token. I wrote 'a' token, because if I select by chance the token reported at the following URL (which has nothing to do with my work)

[https://jupyter-notebook.readthedocs.io/en/stable/security.html](url)

namely, this one:

[http://localhost:8888/?token=c8de56fa4deed24899803e93c227592aef6538f93025fe01](url)

and then Jupyter notebook works and I can carry out my estimation.

I read different posts on the possibility to set a password to avoid problems related to tokens, but only the first time I inserted the token I had the option to insert a password in in a html page, but I decided not to do it. Now I believe it could be the case.

This is something that happened overnight, without, I believe, my doing anything specifically.

This issue is driving me crazy and I would be thankful if any of you had a potential suggestion.

Many thanks.
Marco

**Comment by willingc** [comment]
Hello @giansoldati,

This repo is for issues related to JupyterHub. This issue is focused on Jupyter notebook. Please ask for support on the Jupyter Discourse site (https://discourse.jupyter.org/c/notebook) or the Anaconda support channels. Thanks!

**Comment by giansoldati** [comment]
Thanks Carol

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno gio 19 set 2019 alle ore 16:44 Carol Willing <
notifications@github.com> ha scritto:
