### ISSUE TITLE
Relative path in kernel spec causing the use of user-specific interpreters

### ISSUE THREAD

**Issue by BoPeng** [jupyterhub/jupyterhub#2722]
We have had some problems with our JupyterHub installation, which appear to be caused by user-installed interpreters. 

For example, the `ir` kernel is installed with an `R` command
```
    "ir": {
      "resource_dir": "/server/path/to/share/jupyter/kernels/ir",
      "spec": {
        "argv": [
          "R",
          "--slave",
          "-e",
          "IRkernel::main()",
          "--args",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "R",
        "language": "R",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    },
```
so JupyterHub basically picks up whatever `R` in the `$PATH` when the kernel starts. This allows some flexibility (e.g. the kernel could be used for different versions of R) but can cause confusion if a user-installed `R` interpreter does not have `irkernel` installed.

In contrast, the `python3` kernel uses absolute path in the spec file

```
    "python3": {
      "resource_dir": "/server/path/to/share/jupyter/kernels/python3",
      "spec": {
        "argv": [
          "/server/path/to/bin/python",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    },
```
which grantees that a specific version of python will be used. This however could also be confusing if users choose `module load python/3.7` and `python 3.6` is still used for the kernel.

We could manually modify the spec files and use relative or absolute paths but we are wondering if there has been some considerations for these scenarios and what would be the best way to handle them. Many thanks in advance.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
