### ISSUE TITLE
Cannot oauth with keycloak and jupyterhub (error 500)

### ISSUE THREAD

**Issue by cleroy97** [jupyterhub/jupyterhub#2730]
Hi everybody !
I'm trying to use Jupyterhub with Keycloak (as oauth). So, I can sign in with my Keycloak user in jupyterhub but it returns an error 500 (Internal server error).

I use "stable/keycloak" chart helm and "jupyterhub/jupyterhub" chart helm -> I just modified the two files "values.yaml".  You should know that I use gke and k8s for host my jupyterhub and my keycloak.

This is my values.yaml (jupyterhub):

`hub:
  extraEnv:
    OAUTH2_AUTHORIZE_URL: http://keycloak.test.com/auth/realms/myrealm/protocol/openid-connect/auth
    OAUTH2_TOKEN_URL: http://keycloak.test.com/auth/realms/myrealm/protocol/openid-connect/token
    OAUTH_CALLBACK_URL: http://jupyterhub.test.com/hub/oauth_callback

auth:
  type: custom
  custom:
    className: oauthenticator.generic.GenericOAuthenticator
    config:
      login_service: "keycloak"
      client_id: "my_client"
      client_secret: "xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx"
      token_url: http://keycloak.test.com/auth/realms/myrealm/protocol/openid-connect/token
      userdata_url: http://keycloak.op-rate.com/auth/realms/myrealm/protocol/openid-connect/userinfo
      userdata_method: GET
      userdata_params: {'state': 'state'}
      username_key: preferred_username

proxy:
  secretToken: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...XXXXX'

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - jupyterhub.test.com
  pathSuffix: "*"`

This is my logs of my pod (hub) :

> [I 2019-09-11 12:53:28.850 JupyterHub log:158] 200 GET /hub/login (@10.28.31.1) 1.08ms
[I 2019-09-11 12:53:28.866 JupyterHub oauth2:82] OAuth redirect: 'http://jupyterhub.test.com/hub/oauth_callback'
[I 2019-09-11 12:53:28.867 JupyterHub log:158] 302 GET /hub/oauth_login?next= -> http://keycloak.test.com/auth/realms/myrealm/protocol/openid-connect/auth?response_type=code&redirect_uri=http%3A%2F%2Fjupyterhub.test.com%2Fhub%2Foauth_callback&client_id=my_client&state=[secret] (@10.132.0.35) 1.49ms
[E 2019-09-11 12:53:28.959 JupyterHub web:1788] Uncaught exception GET /hub/oauth_callback?state=eyJzdGF0ZV9pZCI6ICIwZjRiZmQ1NDllYWU0YTAxODgzYWYyODljYzRlZWUzOCIsICJuZXh0X3VybCI6ICIifQ%3D%3D&session_state=3b0060e0-a286-4fec-b542-cd0b93dfe2c9&code=765994ed-0dfb-4cd9-a913-45aec143e2ec.3b0060e0-a286-4fec-b542-cd0b93dfe2c9.b68e3737-f464-4821-a7c6-a20c0a5e5116 (10.132.0.37)
    HTTPServerRequest(protocol='http', host='jupyterhub.test.com', method='GET', uri='/hub/oauth_callback?state=eyJzdGF0ZV9pZCI6ICIwZjRiZmQ1NDllYWU0YTAxODgzYWYyODljYzRlZWUzOCIsICJuZXh0X3VybCI6ICIifQ%3D%3D&session_state=3b0060e0-a286-4fec-b542-cd0b93dfe2c9&code=765994ed-0dfb-4cd9-a913-45aec143e2ec.3b0060e0-a286-4fec-b542-cd0b93dfe2c9.b68e3737-f464-4821-a7c6-a20c0a5e5116', version='HTTP/1.1', remote_ip='10.132.0.37')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/oauth2.py", line 182, in get
        user = yield self.login_user()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 483, in login_user
        authenticated = await self.authenticate(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/auth.py", line 257, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/generic.py", line 116, in authenticate
        resp = yield http_client.fetch(req)
    **tornado.curl_httpclient.CurlError: HTTP 599: Could not resolve host: keycloak.test.com**
    
[E 2019-09-11 12:53:28.965 JupyterHub log:150] {
      "X-Forwarded-Host": "jupyterhub.test.com",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "80",
      "X-Forwarded-For": "10.132.0.37",
      "Cookie": "oauthenticator-state=\"2|1:0|10:1568206408|20:oauthenticator-state|120:ZXlKemRHRjBaVjlwWkNJNklDSXdaalJpWm1RMU5EbGxZV1UwWVRBeE9EZ3pZV1l5T0Rsall6UmxaV1V6T0NJc0lDSnVaWGgwWDNWeWJDSTZJQ0lpZlE9PQ==|8099aa71f6556648e157ea451d1619c8926e17837946dc6720f075cdc9b495bd\"",
      "Accept-Language": "en,fr;q=0.9,en-US;q=0.8",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://jupyterhub.test.com/hub/login",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "Connection": "close",
      "Host": "jupyterhub.test.com"
    }
[E 2019-09-11 12:53:28.965 JupyterHub log:158] **500 GET /hub/oauth_callback?state=[secret]&session_state=[secret]&code=[secret]** (@10.132.0.37) 40.50ms

I don't know how can I fix this issue.
Does anyone know what I can do ?

In addition, is it normal I can't access to "http://keycloak.test.com/auth/realms/jupyter/protocol/openid-connect/token" if i want to go there ?

Thanks in advance !

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
