### ISSUE TITLE
Apache2 revese proxy with basic authentication: Client sends wrong "Authorization" header

### ISSUE THREAD

**Issue by Hoeze** [jupyterhub/jupyterhub#2731]
Hi, I'm trying to get jupyterhub working again behind an Apache2 reverse proxy with BasicAuth.

Since I updated it to Jupyterhub 1.1, it spits out a number of `Invalid response: 401 Unauthorized` when loading files like `static/lab/vendors~main.52a0cabd079a8f53ed4d.js`.

The Problem is that the client sends requests with the following request header:
```
Authorization: token 0024afb0.................181548ab
```
What it should look like:
```
Authorization: Basic aG9lbH................E5OTQ=
```

Do you have any idea what this might causes?
The same configuration worked with v0.35...

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
