### ISSUE TITLE
Non-default choice to use jupyterlab 

### ISSUE THREAD

**Issue by vhaldemar** [jupyterhub/jupyterhub#2732]
Hello!
I wrote a custom spawner that spawns VM for each user and I want to give users option to use jupyterlab instead notebook.
Problem is, `Spawner.default_url` doesn't do anything for custom spawners (AFAIK) and `JupyterHub.default_url` affects all users.
I tried to modify `User.base_url` from `Spawner.spawn`, but it ended not so well.
Is there a way to do such thing?

I also consider modifying `home.html` template to add JupyterLab button for all users, with `c.JupyterHub.redirect_to_server = False` to give Lab choice to my users.

**Comment by ryogesh** [comment]
Can you adding the path to the jupyter notebook config file, /etc/jupyter/jupyter_notebook_config.py ?
e.g.
c.NotebookApp.default_url = '/tree/myfolder'

**Comment by vhaldemar** [comment]
@ryogesh , I don't want to use jupyter notebook config file to leave opportunity for users have their own config in home dir.

I will use custom `home.html` template for now:
```
{% extends "templates/home.html" %}

{% block main %}

<div class="container">
  <div class="row">
    <div class="text-center">
      {% if default_server.active %}
        <a id="stop" role="button" class="btn btn-lg btn-danger">
          Stop My Server
        </a>
      {% endif %}
      <a id="start" role="button" class="btn btn-lg btn-primary" href="{{ url }}">
      {% if default_server.active %}
         My Server (JupyterNotebook)
      {% else %}
         Start My Server
      {% endif %}
      </a>
      {% if default_server.active %}
      <a id="jupyterlab" role="button" class="btn btn-lg btn-primary" href="{{ url }}/lab">
      My Server (JupyterLab)
      </a>
      {% endif %}
    </div>
  </div>

{% endblock %}
```

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
