### ISSUE TITLE
restful API concurrency performance

### ISSUE THREAD

**Issue by xiedidan** [jupyterhub/jupyterhub#2733]
Hi everyone,  

We're doing stress test on GET /users/{name}. To stress the API, multiple requests are sent in parallel with threading pool. It looks like API have some kind of internal queue or lock, so multiple request handling time increases linear as request batch gets larger.  

**Describe the problem**
Our request batch size vs total handling time:  
```
requests    time(s)
1            0.38
5            1.22
10           2.53
20           4.76
40           9.19 
80           19.09
160          35.38
200          44.32
```

From jupyterhub log, it also looks like the requests are queuing:
```
[I 2019-09-18 06:42:14.340 JupyterHub log:158] 200 GET /hub/api/users/test (launcher@10.233.102.128) 1846.94ms
[I 2019-09-18 06:42:14.341 JupyterHub log:158] 200 GET /hub/api/users/test (launcher@10.233.102.128) 1631.53ms
[I 2019-09-18 06:42:14.342 JupyterHub log:158] 200 GET /hub/api/users/test (launcher@10.233.102.128) 1458.05ms
[I 2019-09-18 06:42:14.343 JupyterHub log:158] 200 GET /hub/api/users/test (launcher@10.233.102.128) 1270.73ms
[I 2019-09-18 06:42:14.344 JupyterHub log:158] 200 GET /hub/api/users/test (launcher@10.233.102.128) 1072.75ms
[I 2019-09-18 06:42:14.345 JupyterHub log:158] 200 GET /hub/api/users/test (launcher@10.233.102.128) 874.66ms
[I 2019-09-18 06:42:14.346 JupyterHub log:158] 200 GET /hub/api/users/test (launcher@10.233.102.128) 686.42ms
[I 2019-09-18 06:42:14.347 JupyterHub log:158] 200 GET /hub/api/users/test (launcher@10.233.102.128) 490.67ms
[I 2019-09-18 06:42:14.348 JupyterHub log:158] 200 GET /hub/api/users/test (launcher@10.233.102.128) 277.39ms
```
During the test, only ~20% of a single cpu core was used.  
Actually we found similar behavior from POST /users/{name}/server earlier, but GET /users/{name} is much easier for repoducing.  
We researched api source code, but nothing seems to be the cause. So could anyone explain why the requests are not handled in parallel?  

**To Reproduce**
Just send batches of requests to /users/{username} and record the handling time.  

**Expected behavior**
We expect the requests are handled in parallel so handling time should NOT be linear to request batch size.  

**Compute Information**
 - Operating System: CentOS Linux release 7.6.1810 (Core)  
 - JupyterHub Version 0.92, deployed in k8s cluster with helm

**Comment by sharkwang** [comment]
@minrk same question.

**Comment by eslavich** [comment]
I'm new here, but I have a guess: Tornado servers are single-threaded, which means any executing request necessarily blocks all other requests until it suspends or completes.  The code for `GET /users/{name}` doesn't suspend, so it makes sense that requests would be handled serially.

I suspect the reason why you're only seeing 20% on a single core is that SQLAlchemy operations aren't awaitable.  When the executing request queries the database for a user, it can't suspend, instead it blocks until the database responds.  It's not actually doing anything during that time so CPU usage stays low.

**Comment by minrk** [comment]
Yeah, this is likely ~100% because tornado is single-threaded and the db requests aren't async, so can't be made concurrently (unlike talking to Spawner pieces like subprocesses, kubernetes, etc.). There's a lot of concurrency in JupyterHub, but db access is the main serialization bottleneck. Allowing db access to be async without creating any race conditions is nontrivial, but likely the next major milestone for JupyterHub API performance. Performance like this is also probably sensitive to *which* API endpoints are being hit, and there could well be operations that we are doing that could be async (via threads) but aren't.

**Comment by xiedidan** [comment]
@eslavich @minrk Thank you for your replies. We observed switching from remote MySql to local sqlite gave us about 30% performance boost.
For now, launching singleuser servers with JH in a 100 person class is painful. Students have to wait minutes for all the servers to get started, so teachers have to find something to talk during that period :-P . However, JH does launch hundreds of servers and work without question. Looking forward to the API performance boost from async ops!

**Comment by minrk** [comment]
It does surprise me that API performance is a big bottleneck for spawning. Did you see a 30% improvement in actual spawn time, or just directly measuring API performance? I would expect lots of spawning to be pretty close to all waiting for servers to come up, which is in fact async for jupyterhub and should *mostly* be limited by the external resources that spawning is using. A py-spy flamegraph of this operation would be pretty handy for diagnosing possible low-hanging fruit in optimizations.

**Comment by xiedidan** [comment]
@minrk Spawn time doesn't change, switching to local db just improves GET /users/{name} performance.
You're right, spawn is async and is not the bottleneck:
```
[I 2019-10-09 02:28:23.092 JupyterHub log:158] 202 POST /hub/api/users/20190917007/servers/ (launcher@10.233.71.25) 10905.67ms
[I 2019-10-09 02:28:23.103 JupyterHub log:158] 202 POST /hub/api/users/20190917009/servers/ (launcher@10.233.71.25) 10654.68ms
[I 2019-10-09 02:28:23.107 JupyterHub log:158] 202 POST /hub/api/users/20190917002/servers/ (launcher@10.233.71.25) 10396.51ms
[I 2019-10-09 02:28:23.112 JupyterHub log:158] 202 POST /hub/api/users/20190917003/servers/ (launcher@10.233.71.25) 9874.98ms
[I 2019-10-09 02:28:23.122 JupyterHub log:158] 202 POST /hub/api/users/20190917006/servers/ (launcher@10.233.71.25) 9621.66ms
[I 2019-10-09 02:28:23.130 JupyterHub log:158] 202 POST /hub/api/users/20190917010/servers/ (launcher@10.233.71.25) 9364.00ms
[I 2019-10-09 02:28:23.138 JupyterHub log:158] 202 POST /hub/api/users/20190917005/servers/ (launcher@10.233.71.25) 9100.78ms
[I 2019-10-09 02:28:23.138 JupyterHub log:158] 202 POST /hub/api/users/20190917001/servers/ (launcher@10.233.71.25) 8835.92ms
[I 2019-10-09 02:28:23.139 JupyterHub log:158] 202 POST /hub/api/users/20190917004/servers/ (launcher@10.233.71.25) 8568.27ms
``` 
So we should try to reduce GET and other db related ops in our workflow. Actually it's partly done that and launch speed improves.
However, since it's possible for hundreds of university students to start servers almost at the same time, even 1 GET per launch becomes unaffordable...
Since server status check (with GET /users/{name}) is widely used in our workflow, we are thinking about directly get server status from K8S API to completely avoid db query (since we only use K8S spawner) for a temporary workaround.
