### ISSUE TITLE
Limit the File Mode to 600

### ISSUE THREAD

**Issue by PatrickPan2012** [jupyterhub/jupyterhub#2742]
Dear Sir or Madam,

I used Docker to deploy JupyterHub to Win 10. Obviously, I need to store the codes to host therfore I ran the docker image with the parameter "-v" and JupyterHub could be started up successfully.
However, an error could be seen when I created a Python file and it was caused by the line 105 of **connect.py** that is "**assert '0600' == oct(stat.S_IMODE(...))**" according to the log. It seems that the goal of the method is to limit the file mode to 600.
<img width="791" alt="1_Error Log" src="https://user-images.githubusercontent.com/11970478/65499328-004bdd80-def0-11e9-95e6-8c6571890d8d.PNG">
I could not get solution from Google and finally I replaced the line with "**Assert True**". As a result, everything goes smoothly.
<img width="578" alt="2_My Solution" src="https://user-images.githubusercontent.com/11970478/65499382-18bbf800-def0-11e9-8705-b3f47369155a.PNG">
I am not sure whether it is a defect or bug. In addition, does what I did have any negative effects on JupyterHub? Thanks very much.

**Comment by willingc** [comment]
Hi @PatrickPan2012. 

Sorry, this question about Windows is a bit outside of the scope of JupyterHub [see note on Platform support](https://github.com/jupyterhub/jupyterhub#a-note-about-platform-support).

As a general tip, please make sure that you have the **latest** versions of JupyterHub and all dependencies installed.
