### ISSUE TITLE
pam_loginuid Error writing /proc/self/loginuid: Operation not permitted

### ISSUE THREAD

**Issue by rebenkoy** [jupyterhub/jupyterhub#2754]
Hi,
Hosting on fedora server
after updating kernel to 5.1.19-300.fc30.x86_64 
got a persistent error:
`pam_loginuid(login:session): Error writing /proc/self/loginuid: Operation not permitted`

I have already tried to set kernel options as it is mentioned [here](https://stackoverflow.com/questions/41894621/why-pam-loginuid-module-fails-on-writing-to-proc-self-loginuid-with-eperm)

but still login does not work: session is not started. Although server lets me in my home directory. Python is not executing.

`pip3 list | grep jupyter`
```
jupyter             1.0.0    
jupyter-client      5.3.1    
jupyter-console     5.2.0    
jupyter-core        4.5.0    
jupyterhub          1.0.0
```

**Comment by willingc** [comment]
Are you running jupyterhub with sufficient permissions?

If you are still having this issue, please provide additional detail about your environment and error messages  `jupyterhub --debug`.

**Comment by arshanvit** [comment]
Hi All
facing one peculiar issue
i was trying to build jupyterhub with ground level
using ubuntu 18.04,the jupyter hub seem to run well in interactive mode with sudo user but in case of creating service as per https://jupyterhub.readthedocs.io/en/stable/installation-guide-hard.html
it is giving below error

```
May 08 10:25:59 SarafVM jupyterhub[54333]: [D 2020-05-08 10:25:59.290 JupyterHub base:832] 0/100 concurrent spawns
May 08 10:25:59 SarafVM jupyterhub[54333]: [D 2020-05-08 10:25:59.290 JupyterHub base:837] 0 active servers
May 08 10:25:59 SarafVM python3[54333]: pam_loginuid(login:session): Error writing /proc/self/loginuid: Operation not permitte
May 08 10:25:59 SarafVM python3[54333]: pam_loginuid(login:session): set_loginuid failed
May 08 10:25:59 SarafVM python3[54333]: pam_unix(login:session): session opened for user saraf by (uid=0)
May 08 10:25:59 SarafVM jupyterhub[54333]: [W 2020-05-08 10:25:59.861 JupyterHub auth:956] Failed to open PAM session for sara
May 08 10:25:59 SarafVM jupyterhub[54333]: [W 2020-05-08 10:25:59.861 JupyterHub auth:957] Disabling PAM sessions from now on.
May 08 10:25:59 SarafVM jupyterhub[54333]: [D 2020-05-08 10:25:59.881 JupyterHub user:556] Calling Spawner.start for saraf
May 08 10:25:59 SarafVM jupyterhub[54333]: [I 2020-05-08 10:25:59.882 JupyterHub spawner:1417] Spawning jupyterhub-singleuser
May 08 10:25:59 SarafVM jupyterhub[54333]: [D 2020-05-08 10:25:59.904 JupyterHub spawner:1113] Polling subprocess every 30s
```

what canm be wrong in this?
