### ISSUE TITLE
JupyterHub conflicts with user's jupyter_notebook_config.py c.NotebookApp.base_url setting

### ISSUE THREAD

**Issue by joelion** [jupyterhub/jupyterhub#2756]
I am in an enterprise, installing JupyterHub on an internal server for use within our department (potentially dozens or low hundreds of users). 

Many of the users who will use the Hub have previously run Jupyter Notebook/Lab servers on their own account, and therefore have existing `~/.jupyter/jupyter_notebook_config.py` files. 

I have found that if the user's personal config file has `c.NotebookApp.base_url` set, when that user uses Hub to start a Lab Server, when that server starts, all of the CSS and JS assets are 404'd and will not load. 

I have found the following 2 workarounds, but am wondering if there is another way to get around this that don't force user's to update their personal config's, while still allowing personal config files to be loaded. 

---- 

The two workarounds I've found are:
1. Force the user to comment-out the `c.NotebookApp.base_url='/jypyter'` line in their personal `jupyter_notebook_config.py` file. Not great, because we want our user's to be able to use JupyterHub with no set-up or modification on their side. Plus, the user's may still occasionally run Jupyter Lab servers on their own, and may use this setting. 
2. Enable `c.Spawner.disable_user_config = True` in the the hub's `jupyterhub_config.py`. Also not great, because the user's may have settings in their personal config files that they may want applied to their Hub-spawned servers. 

Here are relevant settings from `jupyterhub_config.py`
```
c.JupyterHub.bind_url = 'http://<snip>:8000'
c.JupyterHub.data_files_path = '/home/<snip>/miniconda3/envs/jupyterhub/share/jupyterhub'
c.JupyterHub.db_url = 'sqlite:////home/<snip>/jupyterhub/jupyterhub.sqlite'
c.JupyterHub.shutdown_on_logout = True
c.JupyterHub.spawner_class = 'sudospawner.SudoSpawner'
c.Spawner.default_url = '/lab'
c.Spawner.env_keep = ['PATH', 'PYTHONPATH', 'CONDA_ROOT', 'CONDA_DEFAULT_ENV', 'VIRTUAL_ENV', 'LANG', 'LC_ALL']
c.Spawner.notebook_dir = '~'
```

Here are an example user's personal `jupyter_notebook_config.py` file that **will cause errors** (removing the `base_url` line will fix the errors)
```
c.NotebookApp.base_url = '/jupyter'
c.NotebookApp.enable_mathjax = False
c.NotebookApp.ip = '0.0.0.0'
c.NotebookApp.notebook_dir = '/home/<snip>'
c.NotebookApp.open_browser = False
c.NotebookApp.password = u'sha1:<snip>'
c.NotebookApp.port = 8888
```

The settings above generate this page on the spawned server:
![image](https://user-images.githubusercontent.com/5199709/66056344-32fb6480-e4f4-11e9-9d38-114c16d66e50.png)

This is a sample of some of the logging output, showing that the CSS and JS assets are trying to be served from the user's `base_url` URL, which isn't available on the Hub. 
```
[W 2019-10-02 09:09:19.170 SingleUserNotebookApp log:174] 404 GET /user/<snip>/ (@10.109.161.183) 3.17ms
[I 2019-10-02 09:09:19.213 JupyterHub log:174] 302 GET /jupyter/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=3c2a865c832a1322285c55c6ed99abb2 -> /hub/jupyter/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=3c2a865c832a1322285c55c6ed99abb2 (@10.109.161.183) 1.33ms
[I 2019-10-02 09:09:19.222 JupyterHub log:174] 302 GET /jupyter/static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=7afb461de36accb1aa133a1710f5bc56 -> /hub/jupyter/static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=7afb461de36accb1aa133a1710f5bc56 (@10.109.161.183) 1.26ms
[I 2019-10-02 09:09:19.238 JupyterHub log:174] 302 GET /jupyter/static/style/style.min.css?v=e91a43337d7c294cc9fab2938fa723b3 -> /hub/jupyter/static/style/style.min.css?v=e91a43337d7c294cc9fab2938fa723b3 (@10.109.161.183) 1.23ms
[I 2019-10-02 09:09:19.243 JupyterHub log:174] 302 GET /jupyter/static/components/react/react.production.min.js?v=34f96ffc962a7deecc83037ccb582b58 -> /hub/jupyter/static/components/react/react.production.min.js?v=34f96ffc962a7deecc83037ccb582b58 (@10.109.161.183) 3.45ms
[I 2019-10-02 09:09:19.244 JupyterHub log:174] 302 GET /jupyter/static/components/react/react-dom.production.min.js?v=b14d91fb641317cda38dbc9dbf985ab4 -> /hub/jupyter/static/components/react/react-dom.production.min.js?v=b14d91fb641317cda38dbc9dbf985ab4 (@10.109.161.183) 3.38ms
[I 2019-10-02 09:09:19.244 JupyterHub log:174] 302 GET /jupyter/static/components/create-react-class/index.js?v=94feb9971ce6d26211729abc43f96cd2 -> /hub/jupyter/static/components/create-react-class/index.js?v=94feb9971ce6d26211729abc43f96cd2 (@10.109.161.183) 3.39ms
[I 2019-10-02 09:09:19.245 JupyterHub log:174] 302 GET /jupyter/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f -> /hub/jupyter/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f (@10.109.161.183) 3.37ms
[I 2019-10-02 09:09:19.245 JupyterHub log:174] 302 GET /jupyter/custom/custom.css -> /hub/jupyter/custom/custom.css (@10.109.161.183) 3.15ms
[W 2019-10-02 09:09:19.287 JupyterHub log:174] 404 GET /hub/jupyter/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=3c2a865c832a1322285c55c6ed99abb2 (<snip>@10.109.161.183) 40.43ms
[W 2019-10-02 09:09:19.330 JupyterHub log:174] 404 GET /hub/jupyter/static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=7afb461de36accb1aa133a1710f5bc56 (<snip>@10.109.161.183) 41.70ms
[I 2019-10-02 09:09:19.331 JupyterHub log:174] 302 GET /jupyter/static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe -> /hub/jupyter/static/components/es6-promise/promise.min.js
```

**Comment by ryogesh** [comment]
One option that could work is to use a reverse proxy (nginx/httpd). I haven't tried it.
https://jupyterhub.readthedocs.io/en/stable/reference/config-proxy.html

Add the rewrite for /hub/jupyter (or *)/static/ to /jupyter/static
