### ISSUE TITLE
Display version number in web interface

### ISSUE THREAD

**Issue by vilhelmen** [jupyterhub/jupyterhub#2757]
I know you can ask the API what version is running, but I think it'd be a quick, useful addition to show the server's version number in the admin panel somewhere. it would make it a bit easier for users to quickly find the version number without having to check container contents or use the API.

Or do we already do this? I feel like I saw it somewhere before, but I can't find it now.

**Comment by kinow** [comment]
Haven't seen that on the web UI. But if added, perhaps it would be a good idea to have a setting to disable it too, to hide the server signature. Even if there are other ways to tell what version of the hub is running.

**Comment by vilhelmen** [comment]
I was actually thinking about that. Nginx has a setting called `server_tokens` that controls whether it reports the version or not, and we could use something similar.

**Comment by kinow** [comment]
Same reference I had in mind when I wrote this. We had a request from security team some time ago, and it was super easy to handle that in Nginx, while not so easy for other Java servers we had in our stack (though we were using older versions).
