### ISSUE TITLE
Remove "base" JupyterHub kernel from kernelspec 

### ISSUE THREAD

**Issue by joelion** [jupyterhub/jupyterhub#2759]
I have created a python environment with JupyterHub, and all of its support packages, installed. My goal is to keep this environment "clean", with _only_ Jupyter/JupyterHub-related packages installed, so I carefully manage updates and deployment.

I have added a couple other kernels to the kernelspec list that are to be used by my JuptyerHub end-users for particular use-cases, particular versions of python, etc. All of these kernels are available in the Jupyter Lab launcher for the user to select, and all are listed here: 

```
jupyter kernelspec list
Available kernels:
  python3        /home/<snip>/miniconda3/envs/jupyterhub/lib/python3.7/site-packages/ipykernel/resources
  datascience    /home/<snip>/miniconda3/envs/jupyterhub/share/jupyter/kernels/datascience
  py27           /home/<snip>/miniconda3/envs/jupyterhub/share/jupyter/kernels/py27
```

I would like to **remove** the "base" `python3` kernel from the JupyterLab Launcher, since this kernel is not intended for general purpose use, and doesn't contain any useful packages for end-users. But juptyer won't let me remove that one, presumably because it's the built-in, default kernel. 

```
jupyter kernelspec remove python3
Couldn't find kernel spec(s): python3
```

Is there any way to remove this kernel from the kernelspec, or otherwise hide it in the Launcher so users can't select it?

**Comment by ryogesh** [comment]
mkdir /home/<snip>/miniconda3/envs/jupyterhub/share/jupyter/kernels/python3
cd /home/<snip>/miniconda3/envs/jupyterhub/share/jupyter/kernels/python3
cp /home/<snip>/miniconda3/envs/jupyterhub/lib/python3.7/site-packages/ipykernel/resources/*.png .

vi kernel.json with the below content, verify the python path
{
 "argv": [
  "/home/<snip>/miniconda3/bin/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3",
 "language": "python"
}

try jupyter kernelspec list and remove python3

**Comment by joelion** [comment]
Thanks, I think I see what the goal here was. After I installed the "new" python3 kernel, then my kernelspec list was as below, and I confirmed that the Launcher only showed these two kernels. 

```
jupyter kernelspec list
Available kernels:
  datascience   /home/myuser/miniconda3/envs/jupyterhub/share/jupyter/kernels/datascience
  python3       /home/myuser/miniconda3/envs/jupyterhub/share/jupyter/kernels/python3
```

However, after `jupyter kernelspec remove python3`, then the old python3 from my base jupyterhub kernel came back into the list and Launcher... 
```
jupyter kernelspec list
Available kernels:
  python3       /home/myuser/miniconda3/envs/jupyterhub/lib/python3.7/site-packages/ipykernel/resources
  datascience   /home/myuser/miniconda3/envs/jupyterhub/share/jupyter/kernels/datascience    

```

**Comment by joelion** [comment]
Ah... based on @ryogesh idea, I just renamed my `datascience` kernel directory to `python3`. 

And it works! lol... 

```
cd /home/myuser/miniconda3/envs/jupyterhub/share/jupyter/kernels/
mv datascience python3

jupyter kernelspec list
Available kernels:
  python3    /home/myuser/miniconda3/envs/jupyterhub/share/jupyter/kernels/python3
```

My DataScience kernel is now the only, and Preferred, kernel in my Hub. 
![image](https://user-images.githubusercontent.com/5199709/66166115-991ae100-e5f3-11e9-9214-00378cd9fdd8.png)

**Comment by PaleNeutron** [comment]
OK, there must be a python3.

So, why?

**Comment by joelion** [comment]
> OK, there must be a python3.
> 
> So, why?

good question... seems like a poor, undocumented requirement

**Comment by mirestrepo** [comment]
Instead of renaming, if you want to delete the default `python3` kernel, you also need to set
`c.KernelSpecManager.ensure_native_kernel = False` on the jupyter config file -- see more [here](https://github.com/jupyter/notebook/issues/3674#issuecomment-397212982)

**Comment by gfucile** [comment]
I think this might require Spawner args:

```c.Spawner.args = ["--KernelSpecManager.ensure_native_kernel=False"]```

**Comment by kamon405** [comment]
I just renamed one of my other kernel folders to python3 from python3.8  and it no longer list the base kernel as an active kernel.  This fixed it, nothing else above worked.. I am in a linux environment though.

**Comment by gianfa** [comment]
I'm from a _python:3.9-slim-bookworm_ docker image and nothing worked except the renaming trick by @joelion .
It doesn't sound very beautiful, but still 🤷

**Comment by dhirschfeld** [comment]
> I'm from a _python:3.9-slim-bookworm_ docker image and nothing worked except the renaming trick by @joelion . It doesn't sound very beautiful, but still 🤷

Possibly related:
 - https://github.com/jupyter-server/jupyter_server/issues/1461#issuecomment-2412822864
