### ISSUE TITLE
Sudospawner and enterprise gateway

### ISSUE THREAD

**Issue by leinad87** [jupyterhub/jupyterhub#2762]
I'm trying to use sudospawner with enterprise gateway but it seems that it doesn't get the gatewayurl.  The problem is that when a kernel is launched, the variables like {KERNEL_ID} are not resolved.

``
 jupyter --version
jupyter core     : 4.5.0
jupyter-notebook : 6.0.1
qtconsole        : not installed
ipython          : 7.8.0
ipykernel        : 5.1.2
jupyter client   : 5.3.3
jupyter lab      : 1.1.4
nbconvert        : 5.6.0
ipywidgets       : not installed
nbformat         : 4.4.0
traitlets        : 4.3.3
`` 
``
cat /etc/jupyter/jupyter_notebook_config.py
c.KernelSpecManager.ensure_native_kernel = False
c.MultiKernelManager.default_kernel_name = 'python_yarn_cluster'
c.KernelSpecManager.whitelist = { 'python_yarn_cluster', 'spark_python_yarn_cluster'}
c.GatewayClient.urlUnicode= http://127.0.0.1:29128

 cat /etc/arthur_datascience_workbench/jupyterhub_config.py
c.JupyterHub.spawner_class='sudospawner.SudoSpawner'
c.Spawner.default_url = '/lab'
``

**Comment by leinad87** [comment]
I've edited first line of spawn function (mediator.py:87):
``
    cmd = [singleuser] + args + ['--gateway-url=http://127.0.0.1:29128']
`` 

This passes the gateway-url to the notebook and it works, however this is not a production ready solution. One posible solution will be using some configuration file, other option should be passing the argument to ths method.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
