### ISSUE TITLE
JupyterHub on an existing nginx server

### ISSUE THREAD

**Issue by ICTSoEasy** [jupyterhub/jupyterhub#2765]
I've managed to get jupyterhub installed on an existing server (wow that was a faff!). I just want to share a few notebooks with a few students so don't want to spin up a whole new server! 
If I type `jupyterhub` then I everything seems to be running. starts proxy @ http://:8000 which it apparently proxies to http://127.0.0.1:8001/api/routes. However:

- Accessing http://myip:8000/ errors out
I have an exsiting nginx server on this server so I assume something there is blocking it? Any suggestions on how to fix? I've not tried getting ssl to work yet as one problem at a time I reckon! but ideally in the longer term I'd just love the be able to go to https://my-domain/jupyterhub

**Comment by BertR** [comment]
You could add
```
location /jupyterhub {
    proxy_pass http://localhost:8000;
}
```
to your nginx configuration. This forwards all trafic on the `/jupyterhub` path to the proxy.

https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/
