### ISSUE TITLE
Need docs guidance for authenticator / user provisioning integration

### ISSUE THREAD

**Issue by cwaldbieser** [jupyterhub/jupyterhub#2768]
I maintain the JHub CAS authenticator.  CAS is a web Single Sign-On system that has historically been popular in Higher Ed.  The CAS service acts as a broker that authenticates users to a service provider.  It does this by issuing a short lived "ticket" to authenticated users and redirecting the browser to a service provider (SP).  In this case, the SP would be Jupyterhub.

The SP accepts the ticket and validates it with the CAS service.  The CAS service responds with the user attributes.  The SP creates some kind of local authenticated session and may use the attributes for access control, personalization, etc.

A recent [issue](https://github.com/cwaldbieser/jhub_cas_authenticator/issues/13) was brought to my attention.  The CAS authenticator comes in 2 flavors-- the basic CAS authenticator, and a "Local Authenticator" which provisions local users upon login to the hub.

The issue is that because authentication happens externally, provisioning of local user accounts does not occur until the hub is restarted.

I'd like to be able to trigger the machinery so the local user is created, but it is not clear from the [documentation](https://jupyterhub.readthedocs.io/en/stable/getting-started/authenticators-users-basics.html) where/when an external authenticator ought to attempt this.  It looks like there are some event hooks (e.g. `pre_spawn_start()`), but I am not sure if those hooks are appropriate for the purpose of provisioning users. 

Any guidance would be appreciated.

**Comment by ryogesh** [comment]
Below documentation/code might be of some assistance,

https://jupyterhub.readthedocs.io/en/stable/api/auth.html#jupyterhub.auth.Authenticator.add_user

https://jupyterhub.readthedocs.io/en/stable/api/auth.html#jupyterhub.auth.PAMAuthenticator.add_user_cmd

https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/auth.py#L712

**Comment by cwaldbieser** [comment]
Thanks-- putting those items together makes sense.  I had looked at those separately, but I didn't make the leap that it was valid for me to call `self.authenticator.add_user(...)` once authentication was successful.
