### ISSUE TITLE
Should "Export Notebook As..." save the exported file onto the server that running JupyterLab? 

### ISSUE THREAD

**Issue by dclong** [jupyterhub/jupyterhub#2778]
"Export Notebook As..." saves the exported file onto the local machine (running the browser). It can be different from the server that running JupyterLab. Shall "Export Notebook As..." ave the exported file onto the server instead of the local machine?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months and I believe was mistakenly filed here instead of `jupyterlab/jupyterlab`. Please feel free to ask on the [discourse site](https://discourse.jupyter.org) or request that we reopen this issue. Thanks! 🌻
