### ISSUE TITLE
Logout API call for specific user

### ISSUE THREAD

**Issue by michielhub** [jupyterhub/jupyterhub#2779]
I see there is no API call to logout a user from JupyterHub and thus revoke all his sessions. Is there a particular reason why this doesn't exist? Are there any workarounds to logout a user using the JHub api or notebook server api?

**Comment by vpavlin** [comment]
@michielhub Hey, did you figure this out? I am trying to do something similar:-)

**Comment by michielhub** [comment]
It's some time ago but I think we didn't find a solution, sorry. 😞

**Comment by manics** [comment]
See this new issue describing an overall plan https://github.com/jupyterhub/jupyterhub/issues/3688
