### ISSUE TITLE
How to access the ipv6 address of the jupyterhub server by accessing the ipv4 address of the nginx server.

### ISSUE THREAD

**Issue by zzuzayu** [jupyterhub/jupyterhub#2780]
hello.I met a problem. I want to use nginx to forward the port to jupyterhub. The nginx server has ipv6 and ipv4.jupyterhub servers with intranet and ipv6. So I want to access the ipv6 address of the jupyterhub server by accessing the ipv4 address of the nginx server. I configured the proxy_pass of the nginx server. But every time I log in, the url is like "http://xxx.xxx.xxx.xxx:18080/hub/login?next=%2Fhub%2Fapi%2Foauth2%2Fauthorize %3Fclient_id%xxxxxxx...". I can never log in to jupyterhub.How to solve this problem.
nginx.conf:
```
server {
listen 18080;
client_max_body_size 50M;

location  / {
    proxy_pass https://[xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:8080;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # websocket headers
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
}
location ~ /.well-known {
    allow all;
}
```

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
