### ISSUE TITLE
auth.user_for_cookie(cookie_value)  not returning the user form flask app

### ISSUE THREAD

**Issue by amiralipour** [jupyterhub/jupyterhub#2781]
Hey I have the jupyterhub up and running via helm chart 0.8.2.
I am trying to validate "jupyterhhub_session_id" cookie through auth.user_for_cookie(cookie_value) from a flask session but it is returning None value.
Any idea about this issue?

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
