### ISSUE TITLE
Jupyterlab Read Only Better Error Dialog

### ISSUE THREAD

**Issue by akaszynski** [jupyterhub/jupyterhub#2784]
When attempting to open a notebook in a read only directory, the user is presented with an Invalid response: 500 dialog

![Selection_108](https://user-images.githubusercontent.com/11981631/66955848-85479400-f063-11e9-94e1-91b3f32a6898.png)

It would be better if the user had a more descriptive error dialog.

**Comment by akaszynski** [comment]
PS: Dark mode is awesome!

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
