### ISSUE TITLE
Jupyterhub Behind Load Balancer (F5)

### ISSUE THREAD

**Issue by jakepaw** [jupyterhub/jupyterhub#2791]
Hey All,

I have been asking through Gitter since i am active there but it has not received any traction. I am trying to set up Jupyterhub to utilize an F5 load balancer. I am using 4 edge nodes within my cluster that are acting as pool members, each with an instance of Jupyterhub that is inside a conda environment which is auto installed using salt. 

Whenever I access the F5 VIP (IP that is used as front facing to load balance you to one of the nodes) I am redirected to the log in screen. I am at a loss for now as I have tried a few things within my knowledge but to no luck. Here are the configs:

---- pasting from a comment ----

I am doing something similar. I have 4 servers with jupyterhub running as a service, and are inside of an F5 pool. When i contact jupyterhub.company.com I am routed to one of them to log in. Once I login i am prompted to log in again. and again. and again. Here are my configs:

import sys

c.JupyterHub.admin_access = True
c.JupyterHub.cleanup_proxy = False
c.JupyterHub.cleanup_servers = True
c.Authenticator.admin_users = {'my_user'}
c.Authenticator.enable_auth_state = False
c.Authenticator.post_auth_hook = None

c.SystemdSpawner.default_shell = '/bin/bash'
c.SystemdSpawner.mem_limit = '5G'
c.SystemdSpawner.cpu_limit = 4.0
c.SystemdSpawner.user_workingdir = '/users/{USERNAME}'
c.SystemdSpawner.unit_name_template = 'jupyter-{USERNAME}-singleuser'

c.NotebookApp.terminals_enabledBool = True
c.NotebookApp.terminado_settings= {'shell_command': ['/bin/bash']}
c.NotebookApp.shutdown_no_activity_timeout = 60 * 60

c.JupyterHub.hub_ip = 'my_server_ip'
c.JupyterHub.debug_proxy = True
c.JupyterHub.proxy_api_ip = 'my_server_ip'
c.JupyterHub.spawner_class = 'systemdspawner.SystemdSpawner'
c.JupyterHub.hub_connect_ip = 'my_server_ip'
c.JupyterHub.bind_url = 'https://hostname.company.com:8002'
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.JupyterHub.admin_access = True
c.JupyterHub.ssl_cert = 'cert.pem'
c.JupyterHub.ssl_key = 'key.pem'
c.JupyterHub.services = [
{
'name': 'cull-idle',
'admin': True,
'command': [sys.executable, 'cull_idle_servers.py', '--timeout=3600'],
}
]
c.JupyterHub.template_vars = {'announcement': 'This is a temporary Jupyterhub Instance. Send feedback to blank_blank@blank.blank'}

c.LDAPAuthenticator.server_address = 'ldaps://nhsjshshs
c.LDAPAuthenticator.server_port = 636
c.LDAPAuthenticator.bind_dn_template = ['cn={username},ou=it,ou=internal,dc=company,dc=company,dc=com', 'cn={username},ou=health,ou=internal,dc=company,dc=company,dc=com']
c.LDAPAuthenticator.valid_username_regex = '^[anAN][0-9]+$'
c.LDAPAuthenticator.escape_userdn = False
c.LDAPAuthenticator.allowed_groups = None
c.LDAPAuthenticator.attributes = ['cn', 'uidNumber']
c.LDAPAuthenticator.user_attribute = 'sAMAccountName'
c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'CN'
c.LDAPAuthenticator.allowed_groups = ['cn=hdpeng,ou=it,ou=internal,dc=company,dc=company,dc=com', 'cn=hdpruser,ou=it,ou=internal,dc=company,dc=company,dc=com', 'cn=hdpgpu,ou=it,ou=internal,dc=company,dc=company,dc=com']

**Comment by manics** [comment]
Do you have any session tracking configured on your load balancer? If you don't the backend you auth against may not be the same one you make subsequent requests to.

You might get a better response posting on https://discourse.jupyter.org/ where more of the community hang out.

**Comment by jakepaw** [comment]
@manics Thanks for the quick reply, posted it to the discourse just incase people don't watch the GitHub repo. 
And yes session tracking (persistence) is enabled. Just incase anyone runs into this issue I will post the fix here when I figure it out.

**Comment by BertR** [comment]
Hi, could you have a look at your network tab in the browser whether a login cookie is being set by Jupyterhub?

Also, could you run Jupyterhub with `--debug` and post the output of the LDAPAuthenticator here?

**Comment by jakepaw** [comment]
Got it working guys, my F5 team did not specify persistence or did not allow a long enough interval between round robbin switching the users. Changed time to 1 hour, and persistence is working as intended. Thanks for your input / directioning @BertR @manics.
