### ISSUE TITLE
Best way to change `root_dir` of ContentsManager for JupyterHub-spawned notebook?

### ISSUE THREAD

**Issue by krinsman** [jupyterhub/jupyterhub#2793]
**Note:** *I'm not sure whether this is best an issue for Jupyter Notebook or for JupyterHub. Let me know if you think it's the former, so I can close this issue, create a new issue with Jupyter Notebook, and then link to that issue here.*

We have a Jupyter Notebook server extension which uses the `.save` method of the [notebook contents manager](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/manager.py#L40) in order to save a notebook into the JupyterHub user's directory. 

Our Hub is set up in a way such that `c.Spawner.notebook_dir = '/'` and `c.Spawner.default_url = <path to user's home directory>`.

However, the [`._save_notebook` method](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/fileio.py#L291) method used by the [`.save` method of the ContentsManager](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/filemanager.py#L453) gets the save destination from [`._get_os_path`](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/fileio.py#L243), which in turn uses the [`.root_dir` attribute](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/manager.py#L59) of either the [ContentsManager](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/manager.py#L59) or of the [FileContentsManager](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/filemanager.py#L72) subclass (what the notebook actually uses, by default, for the contents manager class [appears to be the `LargeFileManager` class](https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L1137), which is a subclass of FileContentsManager, and thus by extension also of `ContentsManager`).

And, at least in `FileContentsManager`, the default value of the content manager's `.root_dir` attribute [is set to be the `notebook_dir` attribute of the running `NotebookApp` instance](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/filemanager.py#L74). As far as I can tell, this corresponds to the `c.Spawner.notebook_dir` attribute.

> **Problem:** The user's do not have write access to `'/'`, so the content manager's attempts to write to the default value of `.root_dir`, `c.Spawner.notebook_dir`, lead to 403 errors.

So, of course the easiest thing to do would be to change the value of `c.Spawner.notebook_dir` to be the user's home directory. However, our set up requires `c.Spawner.notebook_dir` to be `'/'`, so that user's can at least view/navigate the entire file system, with `c.Spawner.default_url` making their home directory the default starting location for their notebook servers.

Thus, it seems like what we have to do is change the value of either `c.ContentsManger.root_dir` or of `c.FileContentsManager.root_dir` in the users' Jupyter notebook configuration files. However, despite having made this change, the notebook servers created by the spawner do not seem to take heed of this configuration, because (as we've checked using custom logging) the `.root_dir` attribute of the content managers of the spawned notebook servers is still equal to the `.notebook_dir` attribute, i.e. `'/'` for which users don't have write access, instead of the users' home directory, which is what we had set `c.ContentsManager.root_dir` and `c.FileContentsManager.root_dir` to be in the configuration file.

> **Question:** If neither of these will work, then what is the best way to change the value of `.root_dir` of the content managers for the notebooks spawned by JupyterHub?

**Comment by ryogesh** [comment]
Can you try setting the path e.g.
c.ContentsManager.files_handler_params = {'path':'/tmp'}

Refer:
https://github.com/jupyter/notebook/blob/70d74d21ac051fbeaa81d4ef4fff9fa759de96d7/notebook/services/contents/manager.py#L153

**Comment by krinsman** [comment]
@ryogesh I will try the above suggestion, and need to debug something else first in order to do so.

Do you know of a good way in general to check whether the notebook configuration is being loaded by the notebook servers spawned by the JupyterHub spawner?

Right now it seems like this might actually be an issue with Jupyter Notebook at this point, at least this is what my attempts to debug seem to indicate.

---

OK, so as far as I can tell, the config file paths are loaded here: 
https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/singleuser.py#L386

So basically, it should be possible to get them from `NotebookApp`, however `jupyter_config_paths` does not seem to be a property of `NotebookApp`, but of `JupyterApp`
https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L567
which can be found here:
https://github.com/jupyter/jupyter_core/blob/master/jupyter_core/application.py#L81
and looking at the definition of the `jupyter_config_paths` attribute there, one sees that it is basically the output of `jupyter_config_path` in `jupyter_core.paths`, with the result of `jupyter_config_dir` appended if necessary.
[`jupyter_config_path`](https://github.com/jupyter/jupyter_core/blob/master/jupyter_core/paths.py#L182)
[`jupyter_config_dir`](https://github.com/jupyter/jupyter_core/blob/master/jupyter_core/paths.py#L51)

So opening up a Python console I ran
```
from jupyter_core.paths import jupyter_config_path, jupyter_config_dir
jupyter_config_dir()
jupyter_config_path()
```
and the results were 
```
'/home/username/.jupyter'
['/home/username/.jupyter', '/opt/anaconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter']
```
when run as the user, and 
```
'/root/.jupyter'
['/root/.jupyter', '/opt/anaconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter']
```
when run as root.

So fine, no massive surprises there. However, the main issue is that creating and editing any of `'/opt/anaconda3/etc/jupyter/jupyter_notebook_config.py'`, `'/usr/local/etc/jupyter/jupyter_notebook_config.py'`, and `/etc/jupyter/jupyter_notebook_config.py` seemed to have no effect. This is even after stopping and restarting the notebook server.

Moreover, I can confirm with `ps aux` that the `jupyterhub-singleuser` process is indeed killed upon clicking "Stop Server". So seemingly, every time the spawner activates again and the notebook server restarts, the `jupyterhub-singleuser` process should have to search for the configuration files again, and this time find the new configuration files and load them. But this does not seem to be what is happening, which is what I find confusing.

The notebook server extension is installed in editable mode, and when I edit the code to tell the subclass of IPythonHandler to log the value of `contents_manager.root_dir`, it works, i.e. the log messages show up, so this seems to mean that the `jupyterhub-singleuser` instances are genuinely being created from scratch, even to the extent of loading the notebook server extensions from scratch, but the logs always show the wrong value of `root_dir` in spite of what has been written in the config files for the users. Indeed, [the spawners are running `jupyterhub-singleuser`](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/spawner.py#L440), which [should launch an entirely new instance of `jupyterhub-singleuser`/`jupyter notebook`](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/singleuser.py#L659), so I don't know what's going on. For the record I tried `c.ContentsManager.root_dir = '~'`, `c.FileContentsManager.root_dir = '~'`, and even `c.LargeFileContentsManager.root_dir = '~'`, successively in all three of `'/opt/anaconda3/etc/jupyter/jupyter_notebook_config.py'`, `'/usr/local/etc/jupyter/jupyter_notebook_config.py'`, and `/etc/jupyter/jupyter_notebook_config.py`, with no effect.
