### ISSUE TITLE
Pass Information to Emedded Jupyter IFrame

### ISSUE THREAD

**Issue by aryeh-looker** [jupyterhub/jupyterhub#2796]
When I embed a Jupyter instance in an iframe, I am curious if there is any way to pass information (e.g. some environment variables) _from_ the iframe that is hosting Jupyter. I couldn't find any documentation that suggests that this is supported at the moment, but wanted to double-check.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
