### ISSUE TITLE
Difficulty building documentation

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/jupyterhub#2801]
Hey all - I am trying to build the documentation to demo the pandas sphinx theme, but realized that I cannot do so!

I'm getting the following error in building something with NPM after running `make html`:

```bash
npm ERR! path /mnt/c/Users/choldgraf/Dropbox/github/forks/python/jupyter/jupyterhub/jupyterhub/docs/node_modules/lodash
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/mnt/c/Users/choldgraf/Dropbox/github/forks/python/jupyter/jupyterhub/jupyterhub/docs/node_modules/lodash' -> '/mnt/c/Users/choldgraf/Dropbox/github/forks/python/jupyter/jupyterhub/jupyterhub/docs/node_modules/.lodash.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

Does anyone know if there's a way to just build the sphinx docs without building this NPM step? Alternatively, anybody know what this error could be? ~I couldn't find any docs-specific instructions in the [contributing docs](https://github.com/jupyterhub/jupyterhub/blob/master/CONTRIBUTING.md)~ ah I found some docs for this [here](https://jupyterhub.readthedocs.io/en/stable/contributing/docs.html) but unfortunately it doesn't contain the answer to my question

**Update**

I tried running `npm install -g` within the `docs/` folder, and this got a little bit 
further. But upon then running `make html` I get the following error:

```
sh: 1: bootprint: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! jupyterhub-docs-build@0.8.0 rest-api: `bootprint openapi ./rest-api.yml source/_static/rest-api`
npm ERR! spawn ENOENT
```

It's weird because it seems like `bootprint` is listed in the `package.json` file in that folder. Will investigate more...

**Comment by willingc** [comment]
@choldgraf I'm going to close this. Our docs look fabulous now :smile:
