### ISSUE TITLE
Identify notebook file being run

### ISSUE THREAD

**Issue by elgalu** [jupyterhub/jupyterhub#2805]
Hi, I'm coming from:

https://github.com/jupyter/notebook/issues/1000

Unfortunately there seems to be no way (when using JupyterHub) to fetch the currently running notebook file name nor full path. Using Python, without JS hacks.

This is something we need for an Airflow integration we had setup on top of JupyterHub.

**Comment by manics** [comment]
JupyterHub manages authentication and launching the singleuser server, then proxies everything through, so I think you'd still need to get the required information from jupyter/notebook#1000 and not JupyterHub.
