### ISSUE TITLE
Eroor with JupyterHub over HTTPS

### ISSUE THREAD

**Issue by rafelamer** [jupyterhub/jupyterhub#2807]
Hi!
I run JupyterHub in a debian 10 box installed with
`
npm install -g configurable-http-proxy
python3 -m pip install jupyterhub    
`
If a run JupyterHub with the default options, I can connect to the port 8000 and it works fine.
But, when I run it over HTTPS with the configuration
`
c.JupyterHub.bind_url = 'https://:443'
c.JupyterHub.ssl_cert = '/etc/letsencrypt/live/SERVER/fullchain.pem'
c.JupyterHub.ssl_key = '/etc/letsencrypt/live/SERVER/privkey.pem'
`
every time I try to open a notebook, I get **Server error**.

In the logs file I get the following lines
`
Nov  7 17:59:17 servername jupyterhub[1618]: [I 2019-11-07 17:59:17.324 SingleUserNotebookApp log:174] 200 GET /user/rafel.ame\
r/api/contents/Jupyter/Tutorial-Sage.ipynb?type=notebook&_=1573145956919 (rafel.amer@::ffff:88.12.36.163) 71.92ms
Nov  7 17:59:19 servername jupyterhub[1618]: [W 2019-11-07 17:59:19.672 SingleUserNotebookApp web:1667] 403 POST /user/rafel.a\
mer/api/sessions (::ffff:88.12.36.163): '_xsrf' argument missing from POST
Nov  7 17:59:19 servername jupyterhub[1618]: [W 2019-11-07 17:59:19.673 SingleUserNotebookApp handlers:608] '_xsrf' argument m\
issing from POST
`

Does anybody know how to solve the problem or how can I debug it?
Thanks

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
