### ISSUE TITLE
Jupyterhub kernel died when using pyodbc 

### ISSUE THREAD

**Issue by DimaKluchnikov** [jupyterhub/jupyterhub#2809]
I use the same env in Jupyterhub and in Jupyter notebook, but in Jupyterhub kernel dies on following line of code:
`import pyodbc` 
`conn = pyodbc.connect('DSN=mydnsname',CHARSET='UTF8')`

**Comment by ryogesh** [comment]
Do you see errors on the log file? Can you share the log file

**Comment by consideRatio** [comment]
verify you dont crash on running
```
import pyodbc
pyodbc.drivers()
```

You need to install these separate from pyodbc I recall, at least for use with for example microsoft SQL. I did this myself recently by following [these instructions](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017#ubuntu) in my case where I wanted to access a microsoft sql server from an ubuntu environment with pyodbc.
