### ISSUE TITLE
Running into CORS policy issues with x-requested-with header doing requests to spawned Jupyter servers

### ISSUE THREAD

**Issue by shibbas** [jupyterhub/jupyterhub#2813]
I'm trying to make calls from my javascript client to Jupyter APIs spawned from JupyterHub remote server using [nteract](https://nteract.io)

These are cross-origin requests so I have enabled Access-Control-Allow-Origin on the JupyterHub and Jupyter configs. However, API calls to Jupyter server still fail with the following error:

`Access to XMLHttpRequest at '<hub-jupyter-server>/api/sessions' from origin '<origin>' has been blocked by CORS policy: Request header field x-requested-with is not allowed by Access-Control-Allow-Headers in preflight response.`

I've tried updating the tornado_settings in the config for both JupyterHub and Jupyter to allow X-Requested-With header, but I still seem to get this issue. Do you know what I might be missing?

**Comment by shibbas** [comment]
For more information, I have set the following settings in the JupyterHub config for testing

```
c.JupyterHub.tornado_settings = {
    'headers': {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Headers': '*',
      'Access-Control-Allow-Methods': '*'
   },
}
```

and the following settings in the Jupyter config for the spawned servers. 

```
c.NotebookApp.allow_origin = '*'
c.NotebookApp.tornado_settings = {
   'headers': {
      'Access-Control-Allow-Headers': '*',
      'Access-Control-Allow-Methods': '*'
   },
}
```
Do I need to update the configurable-http-proxy as well?

**Comment by abhinav23484** [comment]
Do we have any update on this?
