### ISSUE TITLE
Need more info on /hub/api/users/:user/tokens API

### ISSUE THREAD

**Issue by shibbas** [jupyterhub/jupyterhub#2814]
Hi, 

I'm using the /hub/api/authorizations/token to get a token using PAM authenticator. I see in the response that this is deprecated, but the new endpoint doesn't seem to be accepting the same body and I don't see much information on what to pass to it. I get 403 using it the same way as /hub/api/authorizations/token. Do you have directions on what to put in the body? 

`Using deprecated token creation endpoint /hub/api/authorizations/token. Use /hub/api/users/:user/tokens instead.`

**Comment by manics** [comment]
Have you seen https://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyterhub/jupyterhub/master/docs/rest-api.yml#/default/post_users__name__tokens ?
It's quite useful for viewing the signatures of API methods.

**Comment by shibbas** [comment]
Thank you. Looking through the logs, it looks like I keep getting the following error on trying to use this API endpoint with the above information as well as before with just username and password:

` Error authenticating request for /hub/api/users/:user/tokens: object Future can't be used in 'await' expression` 

Around the code:
https://github.com/jupyterhub/jupyterhub/blob/703af1dd1eddb266e5fd80774e3baa413728be0c/jupyterhub/apihandlers/users.py#L253

**Comment by manics** [comment]
Can you include the code or command you're using to make the API request?

**Comment by shibbas** [comment]
I'm just trying to get this working in postman as follows. Headers are content type as json and a referer. 

```
POST [hubserver]/hub/api/users/:user/tokens
{ 
   "username": ""
   "password": ""
}
```

**Comment by estherxyz** [comment]
Hi,
I try to use like below, it will return 403 forbidden.
:user = test
`(POST) {jupyterhub}/hub/api/users/test/tokens`
request body
`{}`

Jupyterhub I set do not need login.
User can type any username and password.
