### ISSUE TITLE
LocalAuthenticator fails to create user

### ISSUE THREAD

**Issue by dimitraVrs** [jupyterhub/jupyterhub#2817]
Hello! 
I have set up a development installation of JupyterHub (in Ubuntu).
I want to create another user of the hub, apart from me (I use my system account to log in and I am an admim user). So, I've tried to add that user from the admin panel, after adding the following line to the jupyterhub_config.py file:
c.LocalAuthenticator.create_system_users = True.
The problem is that I got the following message:
API request failed (400): Failed to create user zerouser: [Errno 2] No such file or directory: 'adduser': 'adduser'
Why did I got this?

**Comment by gaebor** [comment]
I couldn't use this functionality either, but for a different reason.
However these might help:
https://jupyterhub.readthedocs.io/en/stable/getting-started/authenticators-users-basics.html#use-localauthenticator-to-create-system-users
https://jupyterhub.readthedocs.io/en/stable/api/auth.html#localauthenticator

Please post your `jupyterhub_config.py`!

**Comment by dimitraVrs** [comment]
The relevant edits to the configuration file is that I set c.Authenticator.admin_users={'my_username'} and I added the line c.LocalAuthenticator.create_system_users =True.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
