### ISSUE TITLE
How to deploy jupyterhub service on single machine while using kubernetes resource to run each user session in docker?

### ISSUE THREAD

**Issue by tobycc1990** [jupyterhub/jupyterhub#2818]
https://the-littlest-jupyterhub.readthedocs.io/en/latest/topic/whentouse.html
in this official document, Z2JH use helm to deploy jupyterhub in kubernetes and use docker to run user session, TLJH deploy jupyterhub in single machine and use local resource to run user session

but in our project, we wan't to deploy jupyterhub master service on single or serveral machine ( cloud virtual machine or real hardware) to ensure service security and scalability， but the user session run on a large unified kubernetes cluster which manage all project resource.

in jupyterhub official documents, i didn't see how to deploy jupyterhub in this scenario,  could I get some techique support?

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
