### ISSUE TITLE
Using --config with a missing config should raise an error

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#2819]
```shell
# this cause no error
jupyterhub --config /asdfasdf
```

I want the above to cause an error! If it doesn't, it cause various delayed errors. As an example in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1463, a failure to find the passed --config led to a harder to debug error. In this case, the `jupyterhub/k8s-hub` image that doesn't ship with configurable-http-proxy, but it doesn't need it either assuming the config file is passed and found.

---

I inspected the current setup, and conclude that there is a default value on a `config_file` Traitlet set to `"jupyterhub_config.py"`, so it may not be obvious if it has been set explicitly or not which is required information for us.

One idea is to try to spot if it has been explicitly set or if we rely on the default value using traitlets know-how, and then run a check very early to see if it exists or not, and error out early if it doesn't. No matter what, we should catch a provided configuration file that doesn't exist somehow!

## Relevant parts of the code base

Where I think --config translates to the JupyterHub class traitlet config_file:
https://github.com/jupyterhub/jupyterhub/blob/703af1dd1eddb266e5fd80774e3baa413728be0c/jupyterhub/app.py#L100-L105

Where the config_file traitlet is defined along with a default value:
https://github.com/jupyterhub/jupyterhub/blob/703af1dd1eddb266e5fd80774e3baa413728be0c/jupyterhub/app.py#L310-L312

Where the config_file is first used:
https://github.com/jupyterhub/jupyterhub/blob/703af1dd1eddb266e5fd80774e3baa413728be0c/jupyterhub/app.py#L2207-L2213

**Comment by consideRatio** [comment]
@minrk I could benefit from a nudge on how to fix this.

Got any general advice or ideas about this?
Is it enough to catch this issue in the `initialize` function?
Do you know if I can detect if a traitlet has been explicitly set somehow?

**Comment by minrk** [comment]
In initialize should be fine.

> Do you know if I can detect if a traitlet has been explicitly set somehow?

Yes, `@validate` handlers are called whenever a trait is set (this is called prior to completing the attribute assignment, to allow validation, errors, or coercion). This would be the most traitlet-approved way to validate a trait. Additionally, `@observe` handlers are called *after* setting, and are usually used for linking one trait to another. Errors could be raised here, but it wouldn't prevent the assignment in the first place. That wouldn't really matter if we're calling `self.exit(1)` to exit the process, for instance.
