### ISSUE TITLE
Jupyterhub Causes Server to Become Unreachable

### ISSUE THREAD

**Issue by benhg** [jupyterhub/jupyterhub#2821]
At seemingly random intervals (usually after a few weeks, minimum) our Jupyterhub server will crash, in such a way that the server itself will become completely unreachable. Unfortunately, I have no better way to describe it at the moment, other than "our server stops responding to requests of any kind"

**To Reproduce**
It's not easily reproducible, just wait until the server stops responding.

**Compute Information**
 - Ubuntu 18.04
 - JupyterHub Version 1.0.0

I'm sorry that I don't have more information, the whole thing is very confusing to me.

**Comment by ryogesh** [comment]
1) Do you see any errors, warnings on the log file? 
2) Do you see the hub or the http-proxy processes running after the crash? Using a monitoring tool (or even unix commands) on the hub, http-proxy processes and collecting resource usage metrics regularly may provide some indicators.
3) Do you see lot of user activity, API calls... before the crash happens?
4) What kind of authentication and spawners are you using? 
5) Can you try running with debug mode on for the next time?

Agreed, some of the issue are just tough to get to the bottom of the problem. Would have to be done methodically and sometime needs time.

**Comment by benhg** [comment]
Hi,

> Do you see any errors, warnings on the log file?
None

> Do you see the hub or the http-proxy processes running after the crash? Using a monitoring tool (or even unix commands) on the hub, http-proxy processes and collecting resource usage metrics regularly may provide some indicators.

I can't even reach the server over SSH when the crash happens. Later on (after rebooting the server) if I go in and look at the logs, nothing appears strange. 

> Do you see lot of user activity, API calls... before the crash happens?
There's not really a pattern that I can see. It tends to occur when there are at least a couple users logged in, but not an especially massive amount is necessary.

> What kind of authentication and spawners are you using?

PAM authentication and SudoSpawner

> Can you try running with debug mode on for the next time?

I will enable debug mode next time I restart the jupyterhub process.

Thanks for your help.
