### ISSUE TITLE
IIS Url Rewrite configuration

### ISSUE THREAD

**Issue by ioncaciula** [jupyterhub/jupyterhub#2823]
Good afternoon!

It is supported IIS reverse proxy configuration  for jupyterhub?

**Comment by pr0xxy** [comment]
I have this very same question. Is there a reverse proxy configuration on IIS for Jupyterhub published anywhere?

**Comment by manics** [comment]
You might get a better response on https://discourse.jupyter.org/ where more of the community hang out.
