### ISSUE TITLE
Making a release

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#2825]
I'd like to make a release of JupyterHub to reference form a Z2JH release. So, what can I do to help? I can start working on a CHANGELOG.md!

@minrk @GeorgianaElena do you have suggestions on what I can do to help towards making a release?

**Comment by minrk** [comment]
Let's start this process! I think we've been ready for some time, but I haven't had the time to push it through. Starting with updating `docs/source/changelog.md` is a great start! Then we can make a beta and start the process.

**Comment by rcthomas** [comment]
Just linking #2830.  Any chance pending PRs might be considered for inclusion?  For instance #2763 which looks good to go?  :)

**Comment by minrk** [comment]
Merged #2763, thanks @rcthomas!

**Comment by consideRatio** [comment]
@minrk I'd like to help towards making a final 1.1.0 release. Is there something you would like to delegate with regards to this? I aim to release z2jh 0.9.0 when we have jupyterhub 1.1.0.

Also, would you like TravisCI based PyPI packaging and uploading on git tag pushes setup for this repo like in the smaller projects like kubespawner/oauthenticator btw?

**Comment by minrk** [comment]
> would you like TravisCI based PyPI packaging and uploading on git tag pushes setup for this repo 

I'm not sure. Let's save that for after 1.1, at least.

I'd like to land #2881 and #2887, so help reviewing and merging those would be the best thing. I'm happy to cut the release immediately thereafter.

**Comment by minrk** [comment]
1.1.0 is published
