### ISSUE TITLE
Write a documentation section on "getting buy-in from your users"

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/jupyterhub#2827]
In a recent thread, @mathematicalmichael noted that it is often hard to get users to "buy in" to the idea of using the JupyterHub (as well as deploying a JupyterHub). This echoes the experience of many other people we've interacted with who are deploying JupyterHub (I think @psychemedia as well, for example).

It would be great to have a section in the docs where we can synthesize experiences around getting buy-in for deploying a JupyterHub - e.g., what kind of pain-points to identify ahead of time, what kinds of demonstrations or use-cases are particularly compelling to people, what kinds of people *within* an organization are helpful to get on-board early, etc.

What do folks think about brainstorming some ideas here, and then turning it into a page in the documentation?

**Comment by dsblank** [comment]
Also, be aware that I think we have some sections in the "Teaching and Learning with Jupyter" book that try to address the pros and cons of JupyterHub for educators: https://jupyter4edu.github.io/jupyter-edu-book/getting-going.html It might be of more general use. Steal or add! :)

**Comment by rcthomas** [comment]
@choldgraf could you link that thread you referenced?

We've learned a lot from our deployment both technically and sociologically, would be happy to get that learning documented somewhere.

**Comment by choldgraf** [comment]
@rcthomas it was a twitter thread :-) that's why I wanted to make a GH issue out of it

**Comment by mathematicalmichael** [comment]
I'd be happy to put in some cycles during my time at PyData LA on this if you want to assign it to me. 

Creating some documentation that very specifically targets this audience would be great. FAQs/Walkthroughs that are less intimidating than those of the project as a whole (perhaps as part of the deployment repos?). 

Talking about separating compute and storage I think is important. I _constantly_ get questions about backups. 

Some docs aimed at the people who are responsible for deploying about responding to concerns or limitations. 
> e.g. Authentication. LDAP is ideal, but our university IT wouldn't play nice and our department IT guy didn't care to keep pushing the issue. I used hash authenticator in its place. 
> e.g. Managing dependencies for classes, different images.
> e.g. Local vs Cloud deployment, file storage, backups.
> e.g. ephemeral vs persistent containers.

I love what dockerspawner enabled. The right mix of that plus startup scripts (pre-spawn) that pull in github gists resolved the issue of mid-semester requests (used to have to rebuild images). 

There has to be some way to aggregate the experiences of those who have done this to create a "go-to" spot for every relevant stakeholder to get the answers to their questions (as opposed to using a search engine). 

Student stakeholders: How to install a package, request it become something available to others in the class, using markdown (for the uninitiated), using the Terminal, etc.

**Comment by mathematicalmichael** [comment]
I'm also very open to feedback about what we _shouldn't_ include. What amount of information starts to become overwhelming? Can design/layout address this?

**Comment by manics** [comment]
I think this might be nicer as a Discourse post where it'll be easier to update. Perhaps there's already one?
