### ISSUE TITLE
Reconsider options for deleting non-empty folders?

### ISSUE THREAD

**Issue by LeahJB** [jupyterhub/jupyterhub#2829]
I'm running JupyterHub on Kubernetes based on the z2jh tutorial.

There is quite a bit of discussion online regarding options for deleting non-empty folders (e.g. [here](https://github.com/jupyterlab/jupyterlab/issues/835)). My understanding is that currently deleting non-empty folders works in JupyterLab if you have `send2trash` installed, but since we don't have "trash" on JupyterHub this feature is disabled and the best option is `rm -rf` when necessary (reference [here](https://github.com/berkeley-dsep-infra/datahub/issues/998)).

We've been using this approach for a while, but one of our less experienced users has just accidentally executed `rm -rf /*` in their terminal and deleted everything in their personal file space, plus most of the files on our `shared` drive! Luckily we have some `snapshots` for recovery, but I think an "_Are you **really** sure?_" warning message in the UI would actually be less dangerous than `rm -rf`, given that many JupyterHub users are not necessarily familiar with the Linux terminal.

I guess an ideal solution would be some kind of trash/recycle bin, but I guess this may be tricky to setup for JupyterHub on Kubernetes?

**Comment by Dmitry1987** [comment]
it'll work if you'll patch the notebook itself, having same problem myself, solved only yesterday 

https://github.com/jupyter/notebook/issues/4916

patch the filemanager.py by deleting send2trash related code so it goes straight to delete. i can share a diff if you want (i use notebook=6.0.3).

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
