### ISSUE TITLE
Cannot upload over 1MB file to Jupyterhub via upload button

### ISSUE THREAD

**Issue by superjoebai** [jupyterhub/jupyterhub#2831]
**Describe the bug**

**When i want to upload file, it seems that i cannot upload file over 1MB on notebook view via upload button.**

**To Reproduce**

Please share the steps to reproduce the behavior:
1. Go to 'jupyter'
2. Click on 'upload'
3.  Select local file within 1MB size, it is ok, but over 1MB size, it cannot be uploaded. it will be stuck on uploading

**Expected behavior**

Upload files over 1MB size

**Compute Information**
 - Operating System  ubuntu 16.04
 - JupyterHub Version [0.9.6]
jupyter                   1.0.0                    py36_7  
jupyter_client            5.3.4                    py36_0  
jupyter_console           6.0.0                    py36_0  
jupyter_core              4.6.1                    py36_0  
jupyterhub                0.9.6                    py36_0  
nbconvert                 5.6.1                    py36_0  
nbformat                  4.4.0                    py36_0  
nbgrader                  0.6.0                    py36_0    conda-forge
notebook                  6.0.2                    py36_0 

c.JupyterHub.ip = 'x.x.x.x'
c.JupyterHub.port = 8000
c.Spawner.ip = '127.0.0.1'
c.PAMAuthenticator.encoding = 'utf8'
c.LocalAuthenticator.group_whitelist = {'demo','root'}
c.LocalAuthenticator.create_system_users = True
c.Authenticator.admin_users = {'xxx', 'xxx'}
c.JupyterHub.statsd_prefix = 'jupyterhub'
#c.NotebookApp.iopub_data_rate_limit = 100000000
c.JupyterHub.statsd_prefix = 'jupyterhub'
c.JupyterHub.ssl_cert = 'xxx.cer'
c.JupyterHub.ssl_key = 'xxx.key'
c.JupyterHub.base_url = '/'

**Comment by superjoebai** [comment]
Currently work around use scp command to upload, it is not convenient for students

**Comment by BertR** [comment]
Is your Jupyterhub running behind a load balancer or reverse proxy?
If so, it could be that the load balancer or reverse proxy is limiting
the client body size. Nginx, for example, sets the client body max size to 1M by default (http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size)

**Comment by superjoebai** [comment]
Thanks!
Now it works
Added client_max_body_size 500m;
