### ISSUE TITLE
static files return 404 or 301

### ISSUE THREAD

**Issue by fboerman** [jupyterhub/jupyterhub#2833]
Hi I have been trying to get my jupyterhub running but I keep getting failures on the static files.
all static files return 301 or 404. I tried to alias them to the right locations in my nginx conf, but that didnt work because of the changing urls (from /hub/ to /user/ etc)

I installed jupyter behind a reverse proxy with the standard reverse proxy config from the docs for nginx.
versions
```
jupyter core     : 4.6.1
jupyter-notebook : 6.0.1
qtconsole        : 4.5.5
ipython          : 7.9.0
ipykernel        : 5.1.3
jupyter client   : 5.3.4
jupyter lab      : not installed
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3
jupyterhub: 1.0.0
configurable-http-proxy: 4.2.0
```
jupyterhub config:
```
c.JupyterHub.spawner_class = 'systemdspawner.SystemdSpawner'
c.SystemdSpawner.dynamic_users = True
c.JupyterHub.ip = '127.0.0.1'
```
nginx conf:
```
                location / {
                proxy_pass http://127.0.0.1:8000;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Host $server_name;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                }
```

**Comment by manics** [comment]
Does your Jupyterhub work if you connect to it directly, bypassing Nginx?

**Comment by fboerman** [comment]
yes that gives the exact same problem. Its only with the statics when logged in as user. the login screen serves the static files just fine

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. I recommend updating to 1.1.0 version. Please feel free to request that we reopen this issue if the behavior persists. Thanks! 🌻

**Comment by savire** [comment]
This is still not solved with latest JupyterHub. The URL will be mapped into something like this:

https://DOMAIN.TLD/user/USER/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=fb45616eef2c454960f91fcd2a04efeda84cfacccf0c5d741ba2793dc1dbd6d3ab01aaae6485222945774c7d7a9a2e9fb87e0d8ef1ea96893aa6906147a371bb

It won't be handled by the proxy since NGINX will mark it as 404 first
