### ISSUE TITLE
Is it possible to use jupyterhub api dynamic create user?

### ISSUE THREAD

**Issue by estherxyz** [jupyterhub/jupyterhub#2837]
Hi,

We want to use jupyterhub to dynamic create jupyter notebook pod on k8s.
We use jupyterhub-kubespawner to do this.
But we connect to the jupyterhub page need to login first. We try to do not set auth, let user can create their username and any password.
Is there any method that we can request jupyterhub api directly to create pod of user?
And more, we can dynamic change jupyter server request resource?
(It seems use jupyterhub_config.py to set consistency cpu, memory param to all jupyter server?)

Thanks.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to ask on the [discourse    site](https://discourse.jupyter.org/c/jupyterhub/10) or request that we reopen this issue. Thanks! 🌻
