### ISSUE TITLE
"oauth state does not match. Try logging in again." error when using JupyterHub as an oauth provider

### ISSUE THREAD

**Issue by bitnik** [jupyterhub/jupyterhub#2841]
When I deploy binderhub (chart version 0.2.0-017.7c50358) with authentication enabled ([documentation](https://binderhub.readthedocs.io/en/latest/authentication.html)), I get error if I set `binderhub.replicas` higher than 1

```yaml
binderhub:
  pdb:
    minAvailable: 1
  replicas: 2
```

When I go to binderhub page, I am redirected to "Authorize access" page (which is okay/normal for the moment):

![Authorize access](https://user-images.githubusercontent.com/6059799/70148520-a3666380-16a6-11ea-8965-4a686052295a.png)

When I click on the "Authorize" button, I get `oauth state does not match. Try logging in again.` error and this error doesn't occur if replicas is 1:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
    result = yield result
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 296, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/types.py", line 248, in wrapped
    coro = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jupyterhub/services/auth.py", line 973, in get
    raise HTTPError(403, "oauth state does not match. Try logging in again.")
tornado.web.HTTPError: HTTP 403: Forbidden (oauth state does not match. Try logging in again.)
```

**Comment by manics** [comment]
Are your requests being round-robinned between the two binderhubs (check the logs for both pods?). If so you might be able to configure sticky/persistent sessions in the ingress or loadbalancer.

**Comment by bitnik** [comment]
@manics thanks a lot, that was quick.

> Are your requests being round-robinned between the two binderhubs (check the logs for both pods?).

Yes, it looks like that.

> If so you might be able to configure sticky/persistent sessions in the ingress or loadbalancer.

I have nginx as reverse proxy and it passes client requests to jupyterhub. And binder runs as a service in jupyterhub, so jupyterhub's proxy passes requests to binder. Does that mean I have to do something in the configuration of jupyterhub's proxy in order to have persistent sessions? If yes, do you know how?

**Comment by consideRatio** [comment]
Currently we cannot have two hub or two CHP proxy pods, is it viable to run two binder pods even though we would make sessions pod-sticky?

**Comment by bitnik** [comment]
mybinder.org (https://github.com/jupyterhub/mybinder.org-deploy/blob/master/mybinder/values.yaml#L26) and gesis binder (https://github.com/gesiscss/orc/blob/master/gesisbinder/gesisbinder/values.yaml#L33) already runs with 2 pods

**Comment by manics** [comment]
IIRC two jupyterhub/proxy pods won't work together because they both assume the DB matches their in-memory state, so if one pod updates the DB the other won't know unless it's restarted.

Since BinderHub doesn't have any persistent data I think the only issue is ensuring the session are persistent.

Kubernetes services have a `sessionAffinity` field but https://kubernetes.io/docs/concepts/services-networking/service/ only shows `ClientIP` as an option. I'm not sure if this will work, it'll depend on whether the client is redirected to binderhub (may work, though may require additional config in the ingress), or if it's proxied through JupyterHub (ClientIP will be that of the JupyterHub pod).
