### ISSUE TITLE
Hub logout does not logout single user notebook server

### ISSUE THREAD

**Issue by rabsr** [jupyterhub/jupyterhub#2845]
The JupyterHub logout from the hub control panel (/hub/home) does not logout the single user snotebook server. The single user server is still accessible from the url (/user/[id]/) even after logging out from the hub. 
However, if logout option from file menu of notebook server is used, the notebook server is not accessible.

**Steps to reproduce:** 
1. Lauch hub
2. Start single user notebook server
3. Go to hub home and logout
4. Hit hub url with /user/[id]. The server is still accessible.

**Expected Behaviour:**
The notebook server should not be accessible after logging out from the hub.

**Version:**
Jupyterhub - 1.0.0 and 1.1.0

**Comment by aliasmrchips** [comment]
I have noticed this as well. Thanks for posting an issue!

**Comment by manics** [comment]
If you're interested in digging into the problem there's a good explanation of the login/logout workflow on https://discourse.jupyter.org/t/how-to-force-re-login-for-users/1998/6

**Comment by willingc** [comment]
Hi folks, Sorry for the issue. Do you see the same behavior for release 1.1.0?

**Comment by rabsr** [comment]
@willingc Yes this issue still persists in release 1.1.0.

**Comment by robnagler** [comment]
Just discovered this, too. You can hit the back button, and you are still logged in.

**Comment by kdzhao** [comment]
Does it mean this is a confirmed bug? (From the user's point of view, they can't really log out)

**Comment by cnydw** [comment]
I also encountered this, and found out that the logout button in jupyterlab/notebook behaves correctly, while the logout button in jupyterhub doesn't.

The logout button in jupyterlab/notebook will visit `/user/user-name/logout`, which clears the cookie `jupyterhub-user-user-name` then redirects to `/hub/logout`, which clears the cookies `jupyterhub-session-id`, `jupyterhub-hub-login` and `jupyterhub-services`.

https://github.com/jupyterhub/jupyterhub/blob/639523a27c2c1c9f8617f4a1ff387fc9f7b7f108/jupyterhub/singleuser/mixins.py#L123-L129

The logout button inside JupyterHub only visits `/hub/logout`, so the cookie `jupyterhub-user-user-name` is not cleared.
And it appears just having cookie `jupyterhub-user-user-name` is sufficient to use the singleuser server without any issue.

@minrk  you mentioned in https://discourse.jupyter.org/t/how-to-force-re-login-for-users/1998/6 that 
> After this, visiting /user/name will have jupyterhub-user-name set. This cookie is not cleared by the Hub. However, since jupyterhub-session-id is cleared, the cached authentication response will not be used. The Hub will be consulted again for the validity of the token in jupyterhub-user-name, which was revoked during logout due to the session id, so authentication will fail and the cookie will be cleared and login will be prompted to start again.

However it seems this isn't the case now.

**Comment by jgato** [comment]
any news about this topic? was solved?

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/how-to-force-re-login-for-users/1998/19

**Comment by manics** [comment]
See this new issue describing an overall plan https://github.com/jupyterhub/jupyterhub/issues/3688
