### ISSUE TITLE
except me others are getting 500 error

### ISSUE THREAD

**Issue by MA322764** [jupyterhub/jupyterhub#2846]
Team,

Can somebody suggest me how to enable multi-user environment in jupyterhub as I added 3 users to the config file but except me rest others are facing issue in connecting to jupyterhub.
Below is my config file content

cat jupyterhub_config.py

Configuration file for jupyterhub.
#c.JupyterHub.ssl_key = ‘/etc/ssl/certs/jhub.key’
#c.JupyterHub.ssl_cert = ‘/etc/ssl/certs/jhub.crt’
c.Authenticator.whitelist = {‘ep_manju’, ‘ep_sharath’, ‘ep_basha’}
c.Authenticator.admin_users = {‘ep_manju’,‘ep_sharath’, ‘ep_basha’}
c.Spawner.default_url = ‘/lab’
c.JupyterHub.ip = ‘10.38.81.101’
c.JupyterHub.port = 8080
c.LocalAuthenticator.create_system_users = False
c.JupyterHub.hub_connect_ip = ‘’

Am I missing anything here anything please suggest me on this.

error other users are getting as below:
Your server is starting up.

You will be redirected automatically when it’s ready for you.

100% Complete

Spawn failed: Server at http://127.0.0.1:57903/user/ep_basha/ didn’t respond in 30 seconds

Event log

Server requested

Spawning server…

Spawn failed: Server at http://127.0.0.1:57903/user/ep_basha/ didn’t respond in 30 seconds

**Comment by manics** [comment]
Can you show us the jupyterhub logs?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue if you are still experiencing. Thanks! 🌻
