### ISSUE TITLE
Support for richer metadata for spawners

### ISSUE THREAD

**Issue by gabber12** [jupyterhub/jupyterhub#2850]
**Support for richer metadata for spawners**
Currently very limited information is displayed per spawner - `name` , `url`, `last_activity_date`, `actions`
In case of default server we dont show `last_activity_date`.

There are a bunch of information that can be really useful - 

- **Server Status** - `Running/Pending-Spawn/Stopped/Killed`
- **Kill reason** - A server might be killed due to cull-idle script or due to the underlying spawner infra. Eg in case of docker spawner the container might die arbitrarily
- **Started Timestamp** - Timestamp when server was spawned.
- **Spawner specific Params**- Different Spawner specific parameters like `cpu`, `mem`  and `image` in case of docker spawner(Especially useful for admins)

**Expected behavior**

Would like to understand if this is something in-line with community. If so i would love to discuss implementation and work on it.

**Comment by manics** [comment]
Hi! This question is best asked on the [Jupyter community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions. If there are any concrete outcomes please feel free to open a new issue or PR.
