### ISSUE TITLE
How to set storage with kubespawner jupyter server pods?

### ISSUE THREAD

**Issue by estherxyz** [jupyterhub/jupyterhub#2851]
Hi,

I run jupyterhub with kubespawner.
I follow this to build jupyterhub image with kubespawner.
https://github.com/jupyterhub/kubespawner/blob/master/SETUP.md#setting-up-jupyterhub-for-development
I try to set jupyter_config.py like to connect storage with spawner pods.
```
c.KubeSpawner.storage_pvc_ensure = True
c.KubeSpawner.storage_capacity = '2Gi'
c.KubeSpawner.storage_class = 'default'
```
But this only create PVC, do not mount storage on pods.
How could I modify this config file to create storage and mount to pods?
And It is possible make jupyter server file store on blob store directly? (maybe do not use PVC?)

Thanks.

**Comment by manics** [comment]
Have you tried the https://zero-to-jupyterhub.readthedocs.io/en/latest/ helm chart? That should be an easier way to deploy JupyterHub on Kubernetes, and includes configuration of user storage.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to ask on the [discourse site](https://discourse.jupyter.org/c/jupyterhub/10) or request that we reopen this issue. Thanks! 🌻
