### ISSUE TITLE
Auto-generate docs for prometheus metrics

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#2856]
It would probably be good to generate a doc with a list of prometheus metrics (like #2855). A bit of code like this to walk the metrics module can collect the relevant info:

```python
import jupyterhub.metrics

for name in dir(jupyterhub.metrics):
    obj = getattr(metrics, name)
    if obj.__class__.__module__.startswith('prometheus_client.'):
        for metric in obj.describe():
            print(metric.type, metric.name, metric.documentation)
```

**Comment by rajat404** [comment]
@minrk I'd like to pick this 🤚

**Comment by consideRatio** [comment]
@rajat404 wiee go for it! I'd appreciate this overview of the metrics myself I'm very happy about your help!

:heart: :star2:
