### ISSUE TITLE
login_url is hardcode

### ISSUE THREAD

**Issue by louis-she** [jupyterhub/jupyterhub#2865]
**Describe the bug**

The `login_url` is hardcode since this commit: https://github.com/jupyterhub/jupyterhub/commit/6b22f80ead47790798707c6e73a8cd7dc4ad865b#diff-a9c49d54d1416c0a6f0a70bc047bb72dL1178-R1180
Before that, this is configurable via `Authenticator`.

**Expected behavior**
`login_url` being configurable

**Comment by minrk** [comment]
Closed folowing rationale in #2872 - this is already configurable via `Authenticator.auto_login = True`
