### ISSUE TITLE
Support for Python 3.5/3.6 on bionic ?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#2870]
Do we want to support Python 3.5-3.6 on bionic that comes with 3.7 by default?

I noted while working on #2868 that we don't manage to complete the tests by default when we use dist:bionic and Python 3.6 or Python 3.5.

Here are test failures of bionic with use of:
- python 3.6: https://travis-ci.org/jupyterhub/jupyterhub/jobs/630344822
- python 3.5: https://travis-ci.org/jupyterhub/jupyterhub/jobs/630344818

Here is a relevant comment guessing that the issue is about the OpenSSL version somehow, but not by itself though as I know it works as long as we have Python 3.7 along with the newer OpenSSL version... It only doesn't work with a new OpenSSL version with a Python 3.6 installation. See: https://github.com/jupyterhub/jupyterhub/pull/2868#issuecomment-569425868

**Comment by minrk** [comment]
I don't think it's a question of "support," rather of likely improperly configured installs on Travis. We "support" these in general, but it looks like on Travis they don't have working SSL without additional help. JupyterHub works fine when I install it with conda Python 3.6 on bionic, for instance.

Like with #2869 for Python 3.8, test failures and/or coverage on Travis != lack of support.
