### ISSUE TITLE
PAM authentication POST leads to null 302 redirect /hub/login?next= -> /hub/spawn

### ISSUE THREAD

**Issue by ltcarendt** [jupyterhub/jupyterhub#2871]
I'm trying to serve jupyterhub v 1.0.0 with CHP v 4.0.1 on a Databricks cluster:
Databricks proxies to cluster services using the following URL parsing:
https://[host.tld]/driver-proxy/o/[orgId]/[clusterId]/[driverPort]/[proxyPath]
proxies to
localhost:[driverPort]/[proxyPath]

So, for jupyterhub with public port 8000, if I set c.JupyterHub.bind_url = 'http://:8000/driver-proxy/o/[orgId]/[clusterId]/8000/', I would expect to reach the hub login page when I navigate to https://[host.tld]/driver-proxy/o/[orgId]/[clusterId]/8000/hub/login
However, that results in a bunch of 404 errors.

As a result, I inserted NginX between the Databricks driver-proxy and the jupyterhub CHP.
So now, NginX listens on port 3636 and proxies traffic from https://[host.tld]/driver-proxy/o/[orgId]/[clusterId]/3636/ to the jupyterhub CHP:
NginX config:
server {
    listen 3636;
    location / {
      proxy_pass http://127.0.0.1:8000/driver-proxy/o/[orgId]/[clusterId]/3636/;      
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-NginX-Proxy true;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_connect_timeout 3h;
      proxy_send_timeout 3h;
      proxy_read_timeout 3h;
    }
}
Jupyterhub config:
c.JupyterHub.bind_url = 'http://127.0.0.1:8000/driver-proxy/o/[orgId]/[clusterId]/3636/'

Now, when I navigate to https://[host.tld]/driver-proxy/o/[orgId]/[clusterId]/3636/hub/login I get the jupyterhub login screen.
However, when I try to log in, the I get a 302 redirect response:.
The jupyterhub log shows:
[ … JupyterHub log:174] 302 POST /driver-proxy/o/[orgId]/[clusterId]/3636/hug/login?next= -> /driver-proxy/o/[orgId]/[clusterId]/3636/hub/spawn
The browser shows Response Headers:
Location: null://[host.tld]/driver-proxy/o/[orgId]/[clusterId]/3636/driver-proxy/o/[orgId]/[clusterId]/3636/hub/spawn

The redirect seems to be appending the redirect url to the base-url defined by JupyterHub.bind_url

Anyway, I'm not sure where to go from here; I've tried adjusting the bind_url, but that usually breaks everything, so the login screen doesn't even load. I've tried setting "proxy_redirect off;" in NginX, but that has no effect. The configs above is the closest I've been able to get.

I know it's an unusual setup, but I'd appreciate any tips.
Thanks.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to ask on the [discourse site](https://discourse.jupyter.org/c/jupyterhub/10) or request that we reopen this issue. Thanks! 🌻
