### ISSUE TITLE
Jupyterhub using Referer to check cross origin

### ISSUE THREAD

**Issue by louis-she** [jupyterhub/jupyterhub#2873]
**Describe the bug**

https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/apihandlers/base.py#L35-L63

**Expected behavior**

`Referer` is not the right header to do Cross-Origin check instead of `Origin`.

**Comment by minrk** [comment]
Origin is already checked by the underlying tornado framework. Referrer is an additional check to mitigate within-jupyterhub cross-user requests that come from the same origin.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Thanks to all!
