### ISSUE TITLE
I didn't find Image, CPU, etc resource configuration in spawn.html file？

### ISSUE THREAD

**Issue by liudonggang** [jupyterhub/jupyterhub#2874]
When I check the source code, I ca n’t find information about the configuration resources such as Image, CPU, etc. in the spawn.html file, but there are configuration resource information displayed on the page. Where can I view the source code of these configuration resources?

**Comment by minrk** [comment]
If they are displayed on your spawn page, they are coming from a custom options_form in the deployment configuration, not the jupyterhub source itself. How have you deployed jupyterhub?

**Comment by liudonggang** [comment]
I deployed via kubeflow, which file is the options_form for custom deployment? I didn't find the options_form for custom deployment in the .py file?

**Comment by willingc** [comment]
@liudonggang Kubeflow is a project separate from JupyterHub. Please follow up with Kubeflow for suggestions. Thanks.
