### ISSUE TITLE
bug in auth.py

### ISSUE THREAD

**Issue by narnish** [jupyterhub/jupyterhub#2875]
Function 'normalize_username' of class 'PAMAuthenticator'
does not return 'username' if pam_normalize_username is True.

```
def normalize_username(self, username):
        """Round-trip the username to normalize it with PAM
        PAM can accept multiple usernames as the same user, normalize them."""
        if self.pam_normalize_username:
            import pwd

            uid = pwd.getpwnam(username).pw_uid
            username = pwd.getpwuid(uid).pw_name
            username = self.username_map.get(username, username)
            **return username**
        else:
            return super().normalize_username(username)

```

**Comment by rkdarst** [comment]
Thanks for reporting this!  It was caused by my last change to the PR
that made this, combined with the fact that we didn't know how to test
the PAM case.  I guess it just goes to show that yes, there really is
nothing too small to test...

Fix in #2876.
