### ISSUE TITLE
JupyterHub documentation assumes users are all locally defined

### ISSUE THREAD

**Issue by rpural** [jupyterhub/jupyterhub#2878]
**Describe the bug**

In the documentation on https://github.com/jupyterhub/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges, a procedure is described for allowing JupyterHub to read the /etc/shadow file in order to have access to validate passwords. This would assume that the users were defined locally on the system. If the users are defined via LDAP and accessed via sssd, there would be no entry in the shadow file. If the users are defined in some other access management system (i.e. Active Directory and Centrify), again, there'd be no entries in /etc/shadow. How does the product handle this, if at all?

**To Reproduce**

This is a basic product oversight; there's nothing to reproduce.

**Expected behavior**

I would expect the product to use standard system interfaces to authenticate users, which would go through whatever method was in place in PAM to authenticate the account, rather than directly reading the shadow file.

**Compute Information**
 - Red Hat RHEL 7
 - JupyterHub Version - assumed current. I'm a system administrator attempting to debug this issue for my user, and I don't actually have access to the Jupyter system installed.

**Comment by ryogesh** [comment]
The default PAM authenticator works for sssd (with AD/LDAP) 
https://jupyterhub.readthedocs.io/en/stable/getting-started/authenticators-users-basics.html

If you want to go against other mgmt systems like AD, you can try LDAPauthenticator
https://github.com/jupyterhub/ldapauthenticator

There are other authenticators that might support your needs.
https://github.com/jupyterhub/jupyterhub/wiki/Authenticators

**Comment by minrk** [comment]
> I would expect the product to use standard system interfaces to authenticate users, which would go through whatever method was in place in PAM to authenticate the account, rather than directly reading the shadow file.

Your expectation is exactly what happens. The default JupyterHub PAMAuthenticator does go through the PAM API, so if PAM doesn't need to touch /etc/shadow, then that step likely doesn't need to be taken. The default for PAM is to read this file, hence the required permissions. What's needed is for PAM API calls to succeed (specifically, for the Hub user to be able to call `pam_authenticate` for *other* users), so whatever your underlying PAM system needs for this is what JupyterHub needs.

It may be that the [LDAPAuthenticator](https://github.com/jupyterhub/ldapauthenticator) is the right choice for you.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave a comment requesting this issue be reopened. Thanks to all!
