### ISSUE TITLE
Can't sign in as admin to JupyterHub-OAuth GitHub

### ISSUE THREAD

**Issue by amihal01** [jupyterhub/jupyterhub#2884]
I installed JupyterHub on my server and wanted to do OAuth with GitHub.
Made mistake by writing Authorization Callback URL (wrote https instead of http) and did log out from JupyterHub. 
Later I noticed mistake I made (https instead of http), and fixed it, but it was too late, I couldn't sign in as admin users anymore. 
OAuth with GitHub  works now, but **I am not signed in as admin user**.

My question is **how to sign in as admin again?**
I tried to change OAuth to First Use Authenticator with Ubuntu terminal but it is not possible. 
I need do that with JupyterHub terminal (as admin), but cannot access to it.

**Comment by minrk** [comment]
Did you make your github account an admin on the Hub? `c.Authenticator.admin_users = {'amihal01',}`?

**Comment by amihal01** [comment]
No, I forgot.
But I logged in with Dummy Authenticator from Ubuntu terminal.
Thank you!
