### ISSUE TITLE
JupyterHub fails on startup, when there is a pid file, but the actual pid is an unrelated process

### ISSUE THREAD

**Issue by n-a-sz** [jupyterhub/jupyterhub#2886]
**Describe the bug**

Given: a Linux server running JupyterHub among other things. Proxy is running with pid 1234
When: the server is restarted, without properly shutting down JH. A process comes up before JH with pid 1234. Then JH is started.
Then: as the pid file is there, it will try to stop the process with pid 1234, either successfully (which can cause unpredictable result) or unsuccessfully (e.g. permission denied to kill that process).

**Expected behavior**

It should check the user and the command of the running service with pid "1234". If the user is the same and the command is something related to JupyterHub then is it is okay to try to kill that process. If not then it should remove the pid file and start up.

**Compute Information**

 - JupyterHub Version 1.0.0

**Comment by minrk** [comment]
it should indeed check that it's jupyterhub! Workaround until this has occurred is to delete the pid file manually.

This situation should only occur if jupyterhub crashes hard or the machine is shutdown in an ungraceful way. Are you seeing it happen more often than that?

**Comment by n-a-sz** [comment]
Yes, that workaround is working, this is that same what I have done to solve it. 
And yes, It "only occurs if jupyterhub crashes hard or the machine is shutdown in an ungraceful way".

**Comment by alexweav** [comment]
Just ran into this. We're running the hub on Windows, and we launch/shutdown a number of processes alongside the hub. After a restart of our system, one of the other process we launched had assumed the configurable proxy PID.

I'm happy to dig into a fix. It looks like the `ConfigurableHTTPProxy` launcher knows the expected name and command line argument to launch the proxy. We could use that to verify that the process behind that PID is actually the proxy when checking for an existing process. Does that seem like a viable approach @minrk ?
