### ISSUE TITLE
run_auth_state_hook has too many selfs

### ISSUE THREAD

**Issue by athornton** [jupyterhub/jupyterhub#2890]
I think there's a bug in spawner (running from master):

```
[E 2020-01-14 17:17:12.233 spawner:run_auth_state_hook:981] auth_stop_hook faile
d with exception: <jupyterhubutils.spawner.lsstspawner.LSSTSpawner object at 0x7
ff730ab4cc0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jupyterhub/spawner.py", line 979,
 in run_auth_state_hook
    return self.auth_state_hook(self, auth_state)
TypeError: auth_state_hook() takes 2 positional arguments but 3 were given
ERROR:jupyterhubutils.utils.utils:auth_stop_hook failed with exception: <jupyterhubutils.spawner.lsstspawner.LSSTSpawner object at 0x7ff730ab4cc0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jupyterhub/spawner.py", line 979, in run_auth_state_hook
    return self.auth_state_hook(self, auth_state)
```

Specifically,

`return self.auth_state_hook(self, auth_state)` probably should either drop the `self.` from the front, or not include it as the first parameter inside the call.

**Comment by rcthomas** [comment]
Have you also seen these hooks?  I don't think it's a bug...

https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/spawner.py#L962-L973

**Comment by athornton** [comment]
Huh.  Now I am even more confused.

**Comment by athornton** [comment]
So....auth_state_hook should be called with the spawner and the auth state as two arguments even though it's also a method on the spawner?  Would you ever call it with a spawner that _wasn't_ the self object?

**Comment by manics** [comment]
It's confusing but it makes sense. `pre_spawn_hook` is a user-configurable property on the spawner that can point to a function or other callable. It's **not** a class method: https://jupyterhub.readthedocs.io/en/stable/api/spawner.html#jupyterhub.spawner.Spawner.pre_spawn_hook

**Comment by manics** [comment]
@athornton what's your config for `auth_state_hook`?

**Comment by rcthomas** [comment]
Sounds like something that should be documented more extensively.  I found it telling that the examples I could find didn't call the first argument `self` in the config.  Here's my current auth state hook, it just passes the data over.

```
def auth_state_hook(spawner, auth_state):
    spawner.userdata = auth_state["userdata"]

c.Spawner.auth_state_hook = auth_state_hook
```

I found it telling that the other hooks I could find didn't call the first argument `self`.  For instance in the config there's:

```
#  Example::
#  
#      from subprocess import check_call
#      def my_hook(spawner):
#          username = spawner.user.name
#          check_call(['./examples/bootstrap-script/bootstrap.sh', username])
#  
#      c.Spawner.pre_spawn_hook = my_hook
```

**Comment by athornton** [comment]
Yeah, after changing my call to add a first argument "spawner" (which is the same thing as "self") the errors went away.

So this was purely self-inflicted confusion.

I'll close it, but I think more explicit documentation would be helpful.
