### ISSUE TITLE
gradebook.db is not utf-8 encoded.

### ISSUE THREAD

**Issue by amihal01** [jupyterhub/jupyterhub#2893]
Hello.
I see this error when I open gradebook.db.

**Error! home/jupyter-user/gradebook.db is not utf-8 encoded.
Saving disabled. 
See console for more details**

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please file on the `jupyter/ngrader` repo if this is still an issue. Please feel free to ask on the [discourse site](https://discourse.jupyter.org/c/jupyterhub/10) too. Thanks! 🌻

**Comment by fhrt811** [comment]
Hello there,
I am having the same issue, kindly suggest me a solution for this.
(I am a new coder)
