### ISSUE TITLE
Hub spawns multiple single user servers, but does not let multiple users login

### ISSUE THREAD

**Issue by bkrishna2006** [jupyterhub/jupyterhub#2894]

**Comment by Dmitry1987** [comment]
@bkrishna2006 please add more details like logs from the hub server, what executor (spawner), which settings, etc'

**Comment by bkrishna2006** [comment]
@Dmitry1987,  @GeorgianaElena ...Thanks for the prompt response and very sorry, I should have responded earlier.  I figured out the issue, was a silly one from my end; I had not started the individual servers explicitly from the Admin console..  Now it's working fine.
