### ISSUE TITLE
JupyterHub start up error 

### ISSUE THREAD

**Issue by kedarisharath** [jupyterhub/jupyterhub#2896]
[I 2020-01-16 13:29:13.162 JupyterHub app:1673] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.6
[I 2020-01-16 13:29:13.162 JupyterHub app:1673] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.6
[I 2020-01-16 13:29:13.165 JupyterHub app:1016] Loading cookie_secret from /home/*******/anaconda3/bin/jupyterhub_cookie_secret
[I 2020-01-16 13:29:13.184 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[W 2020-01-16 13:29:13.185 JupyterHub app:1173] No admin users, admin interface will be unavailable.
[W 2020-01-16 13:29:13.185 JupyterHub app:1174] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2020-01-16 13:29:13.185 JupyterHub app:1201] Not using whitelist. Any authenticated user will be allowed.
[E 2020-01-16 13:29:13.220 JupyterHub app:1859] Failed to bind hub to http:// :8081/hub/
[E 2020-01-16 13:29:13.220 JupyterHub app:1958]
    Traceback (most recent call last):
      File "/home/*******/anaconda3/lib/python3.6/site-packages/jupyterhub/app.py", line 1956, in launch_instance_async
        await self.start()
      File "/home/*******/anaconda3/lib/python3.6/site-packages/jupyterhub/app.py", line 1854, in start
        self.http_server.listen(port, address=ip)
      File "/home/*******/anaconda3/lib/python3.6/site-packages/tornado/tcpserver.py", line 151, in listen
        sockets = bind_sockets(port, address=address)
      File "/home/*******/anaconda3/lib/python3.6/site-packages/tornado/netutil.py", line 174, in bind_sockets
        sock.bind(sockaddr)
    OSError: [Errno 98] Address already in use

**Comment by parulML** [comment]
I was getting same error yesterday So I rebooted my machine and everything started working.

**Comment by manics** [comment]
> ` OSError: [Errno 98] Address already in use`

This indicates something was already listening on the JupyterHub port. This could be because you already had JupyterHub running (as @parulML found rebooting would fix this), or some other process was using the port, in which case you'll have to track down what that process is, or alternatively configure JupyterHub to use a different port.

**Comment by dsun-ge** [comment]
Very likely nodejs is running. Run "sudo netstat -plnt" and kill the process that holds port 8081 using "sudo kill -9 processid"

**Comment by kedarisharath** [comment]
I changed port address and worked for me
