### ISSUE TITLE
OIDC access token for API calls

### ISSUE THREAD

**Issue by MatMaul** [jupyterhub/jupyterhub#2903]
Is there a way to make an API call using an OIDC access token ?
Either directly or by trading this access token with a JupyterHub token through the tokens endpoint ?

If not, would you accept a PR for that ? Any insights on a possible implementation ? Would you rather have direct support for OIDC access token or you think it's better to create a specific JupyterHub one from it ?

Thanks !

**Comment by manics** [comment]
Where is your OIDC token coming from? Is it related to https://github.com/jupyterhub/oauthenticator ?

**Comment by MatMaul** [comment]
Yes and no. I am indeed using oauthenticator to authenticate my user to JupyterHub, and the token would come from the same provider (a Keycloak server), however it is not the ticket that would have been retrieved by oauthenticator.

**Comment by MatMaul** [comment]
The flow would be:
- an access token is created by another webapp
- this app want to launch a notebook somehow

**Comment by MatMaul** [comment]
Hum I am thinking about something: can we call the API without a token if we do it from a browser that have the OIDC SSO session alive ? I haven't test but I will tomorrow.

**Comment by manics** [comment]
This post on the Jupyter login workflow might be helpful https://discourse.jupyter.org/t/how-to-force-re-login-for-users/1998/6

**Comment by MatMaul** [comment]
@manics thanks, I'll do some tests. From what I understood I think I need to go through /hub/login (in an iframe for example) first which should populate the JH cookie without user interaction if the SSO session is alive, and try to call the API afterwards.
