### ISSUE TITLE
Why does JupyterHub spawner timeout?

### ISSUE THREAD

**Issue by mokumar1202** [jupyterhub/jupyterhub#2913]
Hi All,

I have completed setting up Anaconda distribution, installed JupyterHub but when i login to the Hub, i get Spawn failed: Server at http://127.0.0.1:35990/user// didn't respond in 30 seconds.

I have tried many suggestions but nothing seems to fix it. I have also tried downgrading Tornado version to 4.5.3 but it failed as there were too many dependencies associated.

Please could someone help. I am on Conda version - 4.8.2 and Python version - 3.7.4

Just FYI, i have also reinstalled Anaconda, configured Proxy, generated jupyterhub_config.py.

**Comment by ryogesh** [comment]
Can you try increasing the spawner timeout
c.Spawner.http_timeout = 60
c.Spawner.start_timeout = 60

Refer: https://jupyterhub.readthedocs.io/en/stable/api/spawner.html

**Comment by mokumar1202** [comment]
thanks ryogesh, i tried your recommendation but the server still failed to startup and eventually timed out after 60 seconds.

More info:
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /data/anaconda3/lib/python3.7/site-packages/jupyterhub/handlers/base.py:741> exception=HTTPError()>
Traceback (most recent call last):
  File "/data/anaconda3/lib/python3.7/site-packages/jupyterhub/handlers/base.py", line 939, in spawn_single_user
    timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/anaconda3/lib/python3.7/site-packages/jupyterhub/handlers/base.py", line 972, in spawn_single_user
    % (status, spawner._log_name),
tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=1]. The logs for kumarm85 may contain details.)

**Comment by ryogesh** [comment]
Can you try updating 
c.JupyterHub.tornado_settings = {'slow_spawn_timeout': 30}

For some details on this setting refer: https://github.com/jupyterhub/jupyterhub/pull/2770
https://github.com/jupyterhub/jupyterhub/issues/2792

If the issue persists
1) can you enable debug on all components and share the logs
2) Share the config (after masking any sensitive information)

**Comment by willingc** [comment]
Closing this issue as it's been inactive for a while. Please feel free to ask on the [discourse site](https://discourse.jupyter.org/c/jupyterhub/10) or request that we reopen this issue. Thanks! 🌻

**Comment by JunaidChaudry** [comment]
@willingc  I am having a similar issue while using jupyterhub kubernetes. Should this issue be re-opened, or should I ask in the discourse site?
