### ISSUE TITLE
spawn docker notebooks bug after reboot

### ISSUE THREAD

**Issue by Dmitry1987** [jupyterhub/jupyterhub#2915]
**Describe the bug**
After a reboot, the docker spawner stopped working, getting error in logs.
**To Reproduce**
Reboot the server with the jupyterhub container, and try to use the docker spawner (start server as usual)
**Expected behavior**
A single user notebook docker starts.

**Compute Information**
ubuntu, jupyterhub 1.0.0

I am getting this error:
```
[E 2020-01-30 05:53:10.692 JupyterHub log:174] 500 GET /hub/spawn-pending/dima1987 (dima1987@162.158.59.43) 15.80ms
[W 2020-01-30 05:53:11.933 JupyterHub dockerspawner:976] Removing container that should have been cleaned up: jupyter-dima1987. (id: d1e0381)
[I 2020-01-30 05:53:11.933 JupyterHub dockerspawner:815] Removing container d1e0381a507a04dcdd0db1c6d47584407162b2f5e75e2920785f0716fc9dc93c
[I 2020-01-30 05:53:11.974 JupyterHub dockerspawner:990] Created container jupyter-dima1987. (id: c4f5470) from image xxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/evisort-jupyter-notebook:latest
[I 2020-01-30 05:53:11.974 JupyterHub dockerspawner:1013] Starting container jupyter-dima1987. (id: c4f5470)
[E 2020-01-30 05:53:12.070 JupyterHub user:626] Unhandled error starting dima1987's server: The 'ip' trait of a Server instance must be a unicode string, but a value of None <class 'NoneType'> was specified.
[I 2020-01-30 05:53:12.092 JupyterHub log:174] 302 GET /hub/spawn/dima1987 -> /hub/spawn-pending/dima1987 (dima1987@0.0.0.0) 204.61ms
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py:697> exception=TraitError("The 'ip' trait of a Server instance must be a unicode string, but a value of None <class 'NoneType'> was specified.",)>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 889, in spawn_single_user
    timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 807, in finish_user_spawn
    await spawn_future
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 642, in spawn
    raise e
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 558, in spawn
    server.ip = urlinfo.hostname
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 585, in __set__
    self.set(obj, value)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 559, in set
    new_value = self._validate(obj, value)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 591, in _validate
    value = self.validate(obj, value)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 2054, in validate
    self.error(obj, value)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 625, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'ip' trait of a Server instance must be a unicode string, but a value of None <class 'NoneType'> was specified.
[E 2020-01-30 05:53:12.209 JupyterHub pages:284] Previous spawn for dima1987 failed: The 'ip' trait of a Server instance must be a unicode string, but a value of None <class 'NoneType'> was specified.
[E 2020-01-30 05:53:12.210 JupyterHub log:166] {
      "X-Real-Ip": "xxxxx",
      "X-Forwarded-Server": "xxxxx",
      "X-Forwarded-Proto": "https",
      "X-Forwarded-Port": "443",
      "X-Forwarded-Host": "stagingvm.jjjjj.com",
      "X-Forwarded-For": "xxxxxx, xxxxx",
      "Upgrade-Insecure-Requests": "1",
      "Sec-Fetch-User": "?1",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "navigate",
      "Referer": "https://stagingvm.jjjjjjjjjj.com/hub/spawn-pending/dima1987",
      "Cookie": "jupyterhub-hub-login=[secret]; __cfduid=[secret]; _xsrf=[secret]; jupyterhub-session-id=[secret]",
      "Cf-Visitor": "{\"scheme\":\"https\"}",
      "Cf-Ray": "xxxxxx-LAX",
      "Cf-Ipcountry": "US",
      "Cf-Connecting-Ip": "xxxxx",
      "Cdn-Loop": "cloudflare",
      "Accept-Language": "en-US,en;q=0.9,ru;q=0.8",
      "Accept-Encoding": "gzip",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/xxxxxxx Safari/537.36",
      "Host": "stagingvm.jjjjjjjjj.com",
      "Connection": "close"
    }
[E 2020-01-30 05:53:12.210 JupyterHub log:174] 500 GET /hub/spawn-pending/dima1987 (dima1987@xxxxxxxxxxx) 9.75ms
[I 2020-01-30 05:57:58.129 JupyterHub proxy:319] Checking routes
[I 2020-01-30 06:02:58.129 JupyterHub proxy:319] Checking routes
[I 2020-01-30 06:07:58.129 JupyterHub proxy:319] Checking routes
[I 2020-01-30 06:12:58.130 JupyterHub proxy:319] Checking routes


```

**Comment by ryogesh** [comment]
"The 'ip' trait of a Server instance must be a unicode string, but a value of None <class 'NoneType'> was specified."

After reboot, is docker running properly? 
Sometimes /var/run/docker.sock file remains and docker fails. Delete the file, start Docker and then Jupyterhub.

**Comment by Dmitry1987** [comment]
Yeah that's what I have after the reboot:
```
root@jupyterhub-stagingvm:~# ls /var/run/docker
docker/      docker.pid   docker.sock
root@jupyterhub-stagingvm:~# ls /var/run/docker.
docker.pid   docker.sock
root@jupyterhub-stagingvm:~# ls /var/run/docker
containerd  libnetwork  metrics.sock  netns  plugins  runtime-runc  swarm
```
Does it mean docker cannot utilize the existing socket file by replacing it or something? I didn't know :O

**Comment by Dmitry1987** [comment]
nope, it didn't help. I stopped docker, deleted file, started again (jupyterhub and the reverse-proxy started automatically with docker). But it happens again. And I don't know what's the difference between this machine and all others, after reboot. that is so weird. 

Does this error propagate into the logs of jupyterhub directly from docker errors? or is it jupyterhub exception as result of bad config or passed parameter? It gets an empty field somewhere, during attempt to spawn, maybe jupyterhub sets an empty 'ip' when uses the docker SDK to spawn a container?

**Comment by ryogesh** [comment]
I don't think it's a bad config. Looks like Jupyterhub (docker module) is not able to remove the container(id: d1e0381) on restart because docker is not up properly. 

1) "But it happens again."
After you restarted docker, and launched jupyterhub, did the error happen?
or
did the error happen when you did a server restart again?

2) Can you enable debug on all components and check if you find any additional information.

3) Can you disable the config (for debug purpose) to remove the container and check the behavior.

**Comment by Dmitry1987** [comment]
@ryogesh thanks for your suggestions, I will do a full cleanup of existing containers then. 
I restarted docker, and the ansible playbook also recreates docker network and containers, so it kinda has to be idempotent. Maybe an old container was left actually, because of the restart, and was not cleaned up.

**Comment by Dmitry1987** [comment]
Does it attempt to create folders when spawns a docker container of single user?

it attempts to create a folder to mount an external target from host - it's really strange, especially because when mounting a folder to docker, paths don't need to be created in container.

Looks like the 'ip'=None issue is because single user container just crashes.

... 
[D 2020-02-03 09:02:46.922 JupyterHub dockerspawner:873] Starting host with config: {'binds': {'/opt/data/local_shared': {'bind': '/home/ds-team/shared_disk', 'mode': 'rw'}, '/opt/data/local_readonly': {'bind': '/home/ds-team/shared_readonly', 'mode': 'ro'}, '/opt/jupyter-data-share': {'bind': '/home/ds-team/bucket_jupyter-data-share', 'mode': 'rw'}, '/opt/legacy-folders-migration': {'bind': '/home/ds-team/bucket_legacy-folders-migration', 'mode': 'rw'}, '/opt/datasciencemodels': {'bind': '/home/ds-team/s3_datasciencemodels', 'mode': 'rw'}}, 'links': {}, 'mem_limit': 164282499072, 'network_mode': 'jupyter'}
[I 2020-02-03 09:02:46.951 JupyterHub dockerspawner:990] Created container jupyter-dima1987. (id: a7739b4) fromxxxxx:latest
[I 2020-02-03 09:02:46.951 JupyterHub dockerspawner:1013] Starting container jupyter-dima1987. (id: a7739b4)
[E 2020-02-03 09:02:47.061 JupyterHub user:626] Unhandled error starting dima1987's server: The 'ip' trait of a Server instance must be a unicode string, but a value of None <class 'NoneType'> was specified.
[D 2020-02-03 09:02:47.061 JupyterHub user:724] Stopping dima1987
[D 2020-02-03 09:02:47.062 JupyterHub dockerspawner:777] Getting container 'jupyter-dima1987.'
[D 2020-02-03 09:02:47.064 JupyterHub dockerspawner:762] Container a7739b4 status: {'Dead': False,
     'Error': "error while creating mount source path '/opt/jupyter-data-share': "
              'mkdir /opt/jupyter-data-share: file exists',
     'ExitCode': 128,
     'FinishedAt': '0001-01-01T00:00:00Z',
     'OOMKilled': False,
     'Paused': False,
     'Pid': 0,
     'Restarting': False,
     'Running': False,
     'StartedAt': '0001-01-01T00:00:00Z',
     'Status': 'created'}
[D 2020-02-03 09:02:47.072 JupyterHub user:752] Deleting oauth client jupyterhub-user-dima1987
[D 2020-02-03 09:02:47.077 JupyterHub user:755] Finished stopping dima1987
[I 2020-02-03 09:02:47.084 JupyterHub log:174] 302 GET /hub/spawn/dima1987 -> /hub/spawn-pending/dima1987 (dima1987@xxxxxx) 223.64ms
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py:697> exception=TraitError("The 'ip' trait of a Server instance must be a unicode string, but a value of None <class 'NoneType'> was specified.",)>

**Comment by Dmitry1987** [comment]
And on another machine that had no reboots, just fresh install, it all works as usual! totally weird, they all are deployed with ansible and have same folders, mounts, settings, config file.

```
[D 2020-02-03 09:17:08.703 JupyterHub base:780] Initiating spawn for dima1987
[D 2020-02-03 09:17:08.703 JupyterHub base:787] 0/100 concurrent spawns
[D 2020-02-03 09:17:08.703 JupyterHub base:792] 0 active servers
[D 2020-02-03 09:17:08.763 JupyterHub user:542] Calling Spawner.start for dima1987
[D 2020-02-03 09:17:08.773 JupyterHub dockerspawner:777] Getting container 'jupyter-dima1987.'
[I 2020-02-03 09:17:08.775 JupyterHub dockerspawner:784] Container 'jupyter-dima1987.' is gone
[D 2020-02-03 09:17:08.779 JupyterHub dockerspawner:873] Starting host with config: {'binds': {'/opt/data/local_shared': {'bind': '/home/ds-team/shared_disk', 'mode': 'rw'}, '/opt/data/local_readonly': {'bind': '/home/ds-team/shared_readonly', 'mode': 'ro'}, '/opt/jupyter-data-share': {'bind': '/home/ds-team/bucket_jupyter-data-share', 'mode': 'rw'}, '/opt/legacy-folders-migration': {'bind': '/home/ds-team/bucket_legacy-folders-migration', 'mode': 'rw'}, '/opt/datasciencemodels': {'bind': '/home/ds-team/s3_datasciencemodels', 'mode': 'rw'}}, 'links': {}, 'mem_limit': 164282499072, 'network_mode': 'jupyter'}
[I 2020-02-03 09:17:08.910 JupyterHub dockerspawner:990] Created container jupyter-dima1987. (id: b598a91) from image xxxxxxxx.jupyter-notebook:latest
[I 2020-02-03 09:17:08.910 JupyterHub dockerspawner:1013] Starting container jupyter-dima1987. (id: b598a91)
[D 2020-02-03 09:17:09.527 JupyterHub spawner:1084] Polling subprocess every 30s
[I 2020-02-03 09:17:10.453 JupyterHub log:174] 200 GET /hub/api (@172.18.0.4) 0.97ms
[D 2020-02-03 09:17:10.473 JupyterHub users:708] Activity for user dima1987: 2020-02-03T09:17:10.063957Z
[D 2020-02-03 09:17:10.473 JupyterHub users:729] Activity on server dima1987/: 2020-02-03T09:17:10.063957Z
[I 2020-02-03 09:17:10.480 JupyterHub log:174] 200 POST /hub/api/users/dima1987/activity (dima1987@172.18.0.4) 19.53ms
[D 2020-02-03 09:17:10.763 JupyterHub utils:218] Server at http://172.18.0.4:8888/user/dima1987/ responded with 302
[D 2020-02-03 09:17:10.763 JupyterHub _version:60] jupyterhub and jupyterhub-singleuser both on version 1.0.0
[I 2020-02-03 09:17:10.763 JupyterHub base:810] User dima1987 took 2.061 seconds to start
[I 2020-02-03 09:17:10.763 JupyterHub proxy:261] Adding user dima1987 to proxy /user/dima1987/ => http://172.18.0.4:8888
[D 2020-02-03 09:17:10.764 JupyterHub proxy:765] Proxy: Fetching POST http://127.0.0.1:8001/api/routes/user/dima1987
[I 2020-02-03 09:17:10.766 JupyterHub log:174] 201 POST /hub/api/users/dima1987/server (dima1987@xxxxxxxxxx) 2074.87ms
[D 2020-02-03 09:17:39.530 JupyterHub dockerspawner:777] Getting container 'jupyter-dima1987.'
[D 2020-02-03 09:17:39.534 JupyterHub dockerspawner:762] Container b598a91 status: {'Dead': False,
     'Error': '',
     'ExitCode': 0,
     'FinishedAt': '0001-01-01T00:00:00Z',
     'OOMKilled': False,
     'Paused': False,
     'Pid': 24165,
     'Restarting': False,
     'Running': True,
     'StartedAt': '2020-02-03T09:17:09.508386047Z',
     'Status': 'running'}

```

**Comment by ryogesh** [comment]
Are the container images the same?
I see "from image xxxxxxxx.jupyter-notebook:latest"(success) and "fromxxxxx:latest" (failed)

**Comment by Dmitry1987** [comment]
@ryogesh yes it's just my manual censorship of account ID' :D 
By the way I think this might have to do with docker volumes. Seems like the container launched in such a way that it makes docker attempt to creating some folders, despite all it needs to do is mount existing folders. Maybe you know if it's a function of the way jupyterhub creates containers? 

This is my config file:

```
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
c.DockerSpawner.image = os.environ['DOCKER_JUPYTER_CONTAINER']
c.DockerSpawner.use_internal_ip = True
c.DockerSpawner.network_name = "jupyter"
c.DockerSpawner.name_template = "{prefix}-{username}.{servername}"
c.DockerSpawner.notebook_dir = '/home/ds-team'

default_volumes = { 
    '/opt/data/user_folders/{username}': {"bind": '/home/ds-team/private_folder', "mode": "rw"}, 
    '/opt/data/local_shared': {"bind": '/home/ds-team/shared_disk', "mode": "rw"},
    '/opt/data/local_readonly': {"bind": '/home/ds-team/shared_readonly', "mode": "ro"}
}

# Parse the google storage bucket names and add them to volumes list
mount_buckets = dict()
for bucket_name in os.environ['STORAGE_BUCKETS'].split(','):
    mount_buckets["/opt/" + bucket_name] = {"bind": '/home/ds-team/bucket_' + bucket_name, "mode": "rw"}
for bucket_name in os.environ['S3_BUCKETS'].split(','):
    mount_buckets["/opt/" + bucket_name] = {"bind": '/home/ds-team/s3_' + bucket_name, "mode": "rw"}

default_volumes.update(mount_buckets)

# Mounts for the Notebook container, don't use docker volumes, only host folders (easier to manage)
c.DockerSpawner.volumes = default_volumes
c.DockerSpawner.remove_containers = True

# How notebook communicates with jupyterhub container (docker container name, routes through traefik)
c.JupyterHub.hub_ip = "jupyterhub"
c.JupyterHub.allow_named_servers = True
c.JupyterHub.named_server_limit_per_user = 5
```
