### ISSUE TITLE
JupyterHub configuration behind (two) proxy

### ISSUE THREAD

**Issue by sntgluca** [jupyterhub/jupyterhub#2916]
Hi all,

I already searched the issues track without success. There are a few similar tickets but no one was good enough for me. Hence, here's a new request :) 

I have a relatively complex setup, with two proxies before JupyterHub.
While I don't have control on the first proxy, the second one, JupyterHub and the Jupyter notebooks server configuration can be modified. 

When a user connects, the browser always points to the first proxy, which handles authentication and redirects to the second proxy, handling encryption.
I need to configure the system to **direct any internal web connection / request to the second proxy**, avoiding the first one (as in the scheme below). The reason is pretty technical: the first proxy doesn't support web-socket connections, hence dropping any web-socket attempts to use services like bokeh - i.e. from a dask dashboard.

<img width="594" alt="jupyterhub proxy setup" src="https://user-images.githubusercontent.com/10941257/73439687-51615780-4350-11ea-858c-06ccc0a80525.png">

I tried several configurations, including changing `SingleUserNotebookApp.websocket_url`, `bind_url`, `hub_api_url` and a few others.
Regardless, the bokeh server always tries to open a connection to the first proxy. Incidentally this is the address the browser is pointing to. I don't know if this is just a coincidence or a hint to the problem.
The second proxy is nginx, and it has been configured according to https://jupyterhub.readthedocs.io/en/stable/reference/config-proxy.html

Anyone would like to give a suggestion?
Thanks
Gianluca

**Comment by manics** [comment]
> When a user connects, the browser always points to the first proxy, which handles authentication and redirects to the second proxy, handling encryption

Can you clarify what you mean here? Does the browser have direct access to proxy-2 (as implied by "redirect")? The diagram implies proxy-2 can only be accessed via proxy-1. Jupyter requires a websocket connection between the browser and the server, so if proxy-1 doesn't support websockets I don't think this can work.

**Comment by sntgluca** [comment]
> Can you clarify what you mean here? Does the browser have direct access to proxy-2 
As a matter of fact, the browser - or any other web application from within our VPN, i.e. a bokeh server - could access proxy-2 directly.

For instance, I am able to point my browser to
* connect to https://proxy-1 to authenticate (cookies are setup)
* connect to https://proxy-2 to have an encrypted connection to JupyterHub

But proxy-1 is still needed for authentication, otherwise JupyterHub returns an "Unauthorized" error.

Ideally I'd want our users to **always use proxy-1 as the unique application entry point.** Our users should not know about proxy-2 and everything else behind the scene...
But given the limitations of proxy-1 I need that **everything setup by the Jupyter machinery after authentication avoids proxy-1**.

Is it clearer in any way?

**Comment by manics** [comment]
It's a bit clearer! What authenticator are you using?

**Comment by sntgluca** [comment]
Based on the recommendation from our authentication experts, we opted for the RemoteUserAuthenticator:

https://github.com/cwaldbieser/jhub_remote_user_authenticator

**Comment by ryogesh** [comment]
An interesting config problem.

Thinking out loud: 
1) Setup a unique header, so that when proxy-1 receives the websocket request, redirect to proxy-2 instead of dropping.
2) Is SAML an option? If yes, make proxy-1 redirect all Jupyterhub (without auth) calls directly to proxy-2 , which then authenticates using SAML (perhaps by proxy-1).

**Comment by sntgluca** [comment]
Thank you @ryogesh ,

I will think about these options, especially using different authentication strategies, and get back with some additional comment for the ticket.

The potential issue I might have with your suggestions is that I have no control on proxy-1.

That's why I am considering approaching the problem differently and working on proxy-2 and/or jupyterhub config.

**Comment by sntgluca** [comment]
Since there are no easy solutions to my problem I am going to close the issue.

At this moment we are testing @ryogesh 's suggestions and will comment if appropriate.
Thanks for the help!
