### ISSUE TITLE
LDAP integration is getting failed

### ISSUE THREAD

**Issue by Siddhu1096** [jupyterhub/jupyterhub#2920]
Hi all,

I tried running this command 
```docker run -d -p 8000:8000 --name jupyterhub jupyterhub/jupyterhub jupyterhub``` 
to run the docker container and after executing, the container is up and running. Now, I'm in need of integrating jupyterhub with ldap authentication. Is there an alternate way to do this?

Thanks in advance!

**Comment by manics** [comment]
Can you build your own Docker image that extends `jupyterhub/jupyterhub` with whatever additional packages you require?

**Comment by Siddhu1096** [comment]
Are there any sample documents where can I review the LDAP configuration inside the Dockerfile for Jupyter?   @manics

**Comment by manics** [comment]
Have you seen https://github.com/jupyterhub/ldapauthenticator ?
It should be as easy as `https://github.com/jupyterhub/ldapauthenticator` or the conda equivalent. See the README in the linked repo for more info and configuration instructions.

**Comment by Siddhu1096** [comment]
Thanks @manics , but you have any idea how to add this inside a dockerfile?
