### ISSUE TITLE
Jupyter terminal no longer sourcing .profile or .bashrc. 

### ISSUE THREAD

**Issue by fionnmk** [jupyterhub/jupyterhub#2923]
We upgraded our JupyterHub recently, and now terminal no longer sources .profile or .bashrc when launched. We now must enter "bash" for it to source these files.

I have issued my problem in this stackoverflow post.

https://stackoverflow.com/questions/60073276/how-to-login-to-bash-with-current-user-and-the-users-bashrc-file-in-jupyterl

I have tried all the suggestions [here](https://github.com/jupyterhub/jupyterhub/issues/1993) with no avail.

**Comment by manics** [comment]
Did you upgrade jupyter-notebook / jupyter-lab as well, or only JupyterHub?

**Comment by fionnmk** [comment]
Just Jupyter-lab to 1.2..

**Comment by fionnmk** [comment]
And now jupyter hub to 1.1.0, but it didn't help either.

**Comment by fionnmk** [comment]
Successfully installed jupyter-client-5.3.4 jupyter-core-4.6.1 notebook-6.0.3

**Comment by ryogesh** [comment]
1) Which spawner are you using?

2) Can you enable debug on all and share the log file (mask any sensitive information)
e.g.
c.JupterHub.log_level = 'DEBUG'
c.ConfigurableHTTPProxy.debug = True
c.Spawner.debug = True
#c.DockerSpawner.debug = True

3) Can you run env on check the variables when launched?

4) Can you check if you have nbconfig/terminal.json in any of the folders?
/etc/jupyter, /usr/local/etc/jupyter, /home/<userid>/.jupyter, <condaenv>/etc/jupyter/nbconfig

**Comment by sgloutnikov** [comment]
`.bashrc` stopped being sourced for me too, but `.profile` does, which sources the `.bashrc`. This is in a z2jh deployment.

**Comment by manics** [comment]
I'm closing this as it sounds like an issue with jupyter-notebook or jupyterlab.
