### ISSUE TITLE
"Start my Server" button fails to start spawner automatically

### ISSUE THREAD

**Issue by ryogesh** [jupyterhub/jupyterhub#2925]
JupyterHub Version: 1.1.0

Steps to reproduce: Using LocalSpawner and PAMAuthenticator
1) Login using local account
2) Click on control panel and "Stop My Server"
3) We get a button with "Start My Server". On click, we get a notice "Server not running" and another button to "Launch Server"

Expected Behavior:
On step 3, click of "Start My Server", spawner should automatically launch.

Alternate observation:
Instead of clicking "Start my Server" if i click "jupterhub" logo on the top left, spawner launches automatically. i.e. the behavior of /hub/ and /user/<userid>/ is different, hence the differences in UX.

Potential Solution: Change the url for "Start My Server" to /hub/

I am not sure of the implications, and not familiar with the UI code of Jupyterhub hence not submitting the solution.

**Comment by rohit2618** [comment]
@ryogesh I am also facing this issue often. Also, "Start my server" button does not work. But the behaviour is not always the same. Sometimes, the button works as expected.

**Comment by rohit2618** [comment]
On debugging, I found that the "Stop my server" button does not work until home page is completely loaded. Once the home page is loaded, the stop button works as expected.

Also, I updated my templates and data files to latest and now I am getting "Start My Server" button. But still I get "Server not running" error.

**Comment by manics** [comment]
Is this still an issue?

**Comment by rabsr** [comment]
@manics It is not an issue anymore.
