### ISSUE TITLE
Paginate users under /admin template

### ISSUE THREAD

**Issue by cbjuan** [jupyterhub/jupyterhub#2926]
**Describe the bug**
When using JupyterHub in an environment with a lot of users (example, 50K users), if I try to access the `/hub/admin` page, the website takes a long time to render every user. 

For example, when loading the URL `/hub/admin` with 50K users, the handler to serve the users for the admin view - https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/handlers/pages.py#L399-  takes about 7 seconds to retrieve the data and pass all the information to the template. Meanwhile, the rendering of the template https://github.com/jupyterhub/jupyterhub/blob/master/share/jupyterhub/templates/admin.html takes about 1 minute to complete the display of every element. Tests made using a local Postgres database.

Could it be possible to improve this behavior? Probably, paginating users or taking a similar approach could work.

**To Reproduce**

1. Have a high amount of users in JupyterHub database (my tests: 50,000)
2. After starting the JupyterHub (which takes a long time too), log in with an admin user and navigate to the admin web view (/hub/admin).
3. Wait until the webpage is fully rendered (~1 min). This is because the template renders each user individually in the table: `{% for user in users %}`.

**Expected behavior**

It would be great if admins of that kind of JupyterHubs don't need to wait so long to get the users. Probably, we can paginate users or make async rendering.

**Compute Information**
 - Operating System: OSX
 - JupyterHub Version [e.g. 22]: Last version available in GitHub https://github.com/jupyterhub/jupyterhub/tree/22f86ad76c437d37bc26c28d9fecfa5457ef5974

Thanks!

**Comment by betatim** [comment]
Sounds like a worthwhile thing to work on. I think the tricky parts will be making a nice API that is backwards compatible and doesn't require lots of JS on the webpage. Do you want to make a suggestion/draft/first attempt as a PR?

**Comment by cbjuan** [comment]
Sure, I'm already working on it.

**Comment by betatim** [comment]
Very nice! For a change like this it probably makes sense to open a PR pretty early when you have a rough sketch. That way others can give feedback and input in design decisions. Otherwise we run the risk of having weeks of work that then gets completely changed during review.

**Comment by cbjuan** [comment]
Ok, sounds good. I think early tomorrow I will have the PR open so we can begin the discussion. I'm currently polishing some details before submitting my approach  💅

**Comment by cbjuan** [comment]
Hey @betatim. I opened the WIP PR few days ago. I just assigned you as a reviewer because you were the one that answered me here but feel free to add any other people that should be reviewing it.

**Comment by mriedem** [comment]
#2929 is merged so I think this can be closed now.
