### ISSUE TITLE
SAML authentication in kubernetes  JupyterHub cluster

### ISSUE THREAD

**Issue by Subhasis180689** [jupyterhub/jupyterhub#2934]
We can see documentation for all other authentication with helm in kubernetes cluster. We are not able to find any documentation for the SAML authentication with helm in jupyterhub kubernetes cluster. We tried with custom one but its failing. Please suggest.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
