### ISSUE TITLE
User able to access another user's JupyterLab instance

### ISSUE THREAD

**Issue by rickfleming** [jupyterhub/jupyterhub#2937]
We have several JupyterHub instances setup following the Zero to Kubernetes guide, using the kubespawner and using OAuth authentication.  We're using the latest non-beta helm chart 0.8.2 (which looks like it has a 0.9.x version of JupyterHub).

Everything works great, however today we discovered a potential security issue.  I've searched through the issues for JupyterHub, OAuthenticator, Kubespawner, and the Zero to Kubernetes guide, but didn't find anything that looked similar to what we've seen.

Basically, if a user browses to another user's server instance via /user/{username} , it may ask them to authenticate with our OAuth server but then proceeds to let them into the other user's instance (based on the URL).  This happens regardless of admin status of the user (tried with both an admin and non-admin and was able to do it in both scenarios.)

So my question is, first, which repository is the proper one to ask this question in?  Which part of the codebase decides to let a user access a particular instance?  And then a followup, which might be more for the correct repository, is if there a misconfiguration on our part or is this an issue that's been resolved or needs to be resolved?

Thanks!

**Comment by betatim** [comment]
Thanks for reporting this.

Could you share some more details about your configurations/settings?

**Comment by rickfleming** [comment]
I went to collect the values from one of our deployments to respond and noticed that we have the admin access set to true.

So I created a test user that has never been an admin and it does not allow them to go to another user's URL.

However, when admin access was removed from my account for testing through the Hub Admin tab, it did allow me... so I think it's some issue in caching admins allowed to access other user's instances.  So it does look like if it is an issue it's in a limited situation (an admin that has admin taken away.)

Please let me know if I need to provide more details/config.  And thanks for pointing me to pulling the configuration, I didn't realize we had turned on admin access.

**Comment by betatim** [comment]
How did you "remove admin access" from the user?

**Comment by rickfleming** [comment]
I went to "Hub Control Panel", and then Admin tab, and selected myself and unchecked the "Admin" checkbox.  At that point the Admin tab disappeared, but it was still allowing me to enter another user's instance.

**Comment by betatim** [comment]
Can you reproduce it if you logout and login again after unchecking the admin box?

**Comment by minrk** [comment]
>  I think it's some issue in caching admins allowed to access other user's instances

Indeed, the response from jupyterhub containing the user info (including whether they are admin) is cached for [up to five minutes](https://github.com/jupyterhub/jupyterhub/blob/b4391d0f796864a5b01167701d95eafce3ad987e/jupyterhub/services/auth.py#L273-L281) by default. The jupyterhub session id is part of the cache key, so if you had logged out of jupyterhub via the logout button, this should have been invalidated immediately. As it stands, it can take five minutes for your admin status revocation to propagate to servers that you are actively visiting right now.

**Comment by manics** [comment]
Closing, as this is due to internal configurable `cache_max_age` and not a security issue.
