### ISSUE TITLE
Error in Authenticator.pre_spawn_start: KeyError "getpwnam(): name not found: 

### ISSUE THREAD

**Issue by karvox** [jupyterhub/jupyterhub#2948]
Hi all,

I finished a new JupyterHub installation, my jupyterhub_config.py is default and I added the options bellow, but jupyterhub never create unix users locally.

c.LocalAuthenticator.create_system_users = True
c.JupyterHub.authenticator_class = 'firstuseauthenticator.FirstUseAuthenticator'
c.FirstUseAuthenticator.dbm_path = '/etc/jupyterhub/passwords.dbm'

I created the "albert" user on web interface, but when  they try authenticate occurs this error: 

Feb 21 18:56:24 jupyterhub jupyterhub[1993]: [I 2020-02-21 18:56:24.416 JupyterHub log:174] 302 POST /hub/login?next= -> /hub/spawn (albert@10.6.2.163) 385.98ms
Feb 21 18:56:24 jupyterhub jupyterhub[1993]: [E 2020-02-21 18:56:24.709 JupyterHub user:640] Unhandled error starting albert's server: "getpwnam(): name not found: 'albert'"
Feb 21 18:56:24 jupyterhub jupyterhub[1993]: [W 2020-02-21 18:56:24.812 JupyterHub web:1782] 500 GET /hub/spawn (10.6.2.163): Error in Authenticator.pre_spawn_start: KeyError "getpwnam(): name not found: 'albert'"

What is missing on my config file?

**Comment by minrk** [comment]
FirstUseAuthenticator is not a LocalAuthenticator, so that config has no effect. You could create such a class:

```python
class MyAuthenticator(FirstUseAuthenticator, LocalAuthenticator):
    ...
```

**Comment by jnaranjo104** [comment]
Hi @karvox: I am having the same problem. Have you been able to fix the problem?

Thanks in advance,
Jose

**Comment by mttcnnff** [comment]
I was able to fix this for my setup by adding this to my config.

```
def pre_spawn_hook(spawner):
    username = spawner.user.name
    try:
        pwd.getpwnam(username)
    except KeyError:
        subprocess.check_call(['useradd', '-ms', '/bin/bash', username])

c.Spawner.pre_spawn_hook = pre_spawn_hook
```

In my case I was using the NativeAuthenticator and the default spawner, but I think it's the same problem. Before spawning a process to run your server on jupyterhub checks if the username you're using exists on the system, if it doesn't then it fails.

Seems like the users are added in the db but not on the linux machine itself so that's why it fails.

**Comment by rohitsanj** [comment]
@mttcnnff Thanks that worked.

**Comment by mabbasi90** [comment]
I get the same error, I'm using GenericOAuthenticator for connecting to Keycloak( which loads users from LDAP),
but the problem is that some usernames contain '.', like john.smith, and this username cannot be added to Ubuntu,
is there any config for JupyterHub for working without using Ubuntu users?

**Comment by sudi007** [comment]
@mttcnnff please would you be able to help i am having an  issue  and i saw you have a similar setup using NativeAuthenticator and the default spawner my issue is when other users log in to jupyter i get the following error  Error in Authenticator.pre_spawn_start: NameError name 'subprocess' is not defined

**Comment by mabbasi90** [comment]
@sudi007 I fixed this issue with first adding this line
`c.LocalAuthenticator.create_system_users = True`
to create users on OS automatically,
second allowing to have '.' in the usernames with this solution:
https://askubuntu.com/a/405668/745011
because I was using OAuth and some usernames had '.'

**Comment by sudi007** [comment]
@mabbasi90 that will defeat my purpose as for my project i have been told not to create a system users

**Comment by mabbasi90** [comment]
@sudi007 I searched about this and did not find any solution, JupyterHub needs somewhere on OS to store it's files for every user

**Comment by jquintana53** [comment]
@sudi007 and @mabbasi90 not sure our requirements are the same but I make it work trying a combination of things:

> pip install jupyterhub-firstuseauthenticator

```
# in jupyterhub_config.py

c.Authenticator.whitelist = {'web_user_1', 'web_user_2'}
c.Authenticator.admin_users = {web_user_1}

c.JupyterHub.authenticator_class = 'firstuseauthenticator.FirstUseAuthenticator'
c.FirstUseAuthenticator.create_users = False
# restrict access to this file !!!!
c.FirstUseAuthenticator.dbm_path = '/home/jupyterhub/app/conf/users.dbm'

# this will map the web authenticated user to a local OS user, at least you need one OS user
c.Authenticator.username_map = {'web_user_1': 'my_os_user', 'web_user_2': 'my_os_user'}
```
The **users.dbm** file can be created using this python script:

```
import bcrypt
import dbm
import sys

file = str(sys.argv[1])
# Open database, creating it if necessary.
with dbm.open(file, 'c') as db:
    usr = str(sys.argv[2])
    pwd = str(sys.argv[3])
    pwd_hash = bcrypt.hashpw(pwd.encode('utf8'), bcrypt.gensalt())

    db[usr] = pwd_hash
```
Add users like this:

`python add_user.py users.dbm web_user_1 s3cret`

Cheers.

**Comment by danbst** [comment]
I've got same error when configuring Google OAuth. It turned out I had to do this:
```
from oauthenticator.google import LocalGoogleOAuthenticator

c.JupyterHub.authenticator_class = LocalGoogleOAuthenticator
c.LocalGoogleOAuthenticator.create_system_users = True

c.LocalGoogleOAuthenticator.client_id = '...'
c.LocalGoogleOAuthenticator.client_secret = '...'
c.LocalGoogleOAuthenticator.oauth_callback_url = 'https://.../hub/oauth_callback'
c.LocalGoogleOAuthenticator.hosted_domain = [ '...e.com' ]
```

The `LocalGoogleOAuthenticator` is a tiny mix of both LocalAuthenticator (which is capable of creating new system users) and GoogleOAuthenticator (which handles OAuth). 

https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/google.py#L266-L269

**Comment by fortyMiles** [comment]
> I was able to fix this for my setup by adding this to my jupyter_config.
> 
> ```
> def pre_spawn_hook(spawner):
>     username = spawner.user.name
>     try:
>         pwd.getpwnam(username)
>     except KeyError:
>         subprocess.check_call(['useradd', '-ms', '/bin/bash', username])
> 
> c.Spawner.pre_spawn_hook = pre_spawn_hook
> ```
> 
> In my case I was using the NativeAuthenticator and the default spawner, but I think it's the same problem. Before spawning a process to run your server on jupyterhub checks if the username you're using exists on the system, if it doesn't then it fails.
> 
> Seems like the users are added in the db but not on the linux machine itself so that's why it fails.

Unhandled error starting zhaoxingrong's server: name 'pwd' is not define 😂

**Comment by minrk** [comment]
There are two separate issues here, both stemming from having a source of users other than the system:

**1** If you don't want to create system users, you need to use a Spawner that doesn't require system users. This generally means a container-based spawner such as [DockerSpawner](https://github.com/jupyterhub/dockerspawner) or [SystemdSpawner](https://github.com/jupyterhub/systemdspawner) with `SystemdSpawner.dynamic_users = True`.

**2** If you do want to create system users, but not use PAM for authentication, you need to use a `Local` variant of your authenticator. `NativeAuthenticator` and `FirstUseAuthenticator` lack these variants, which should probably be considered a missing feature for those packages:

- firstuse: https://github.com/jupyterhub/firstuseauthenticator/issues/31
- native: https://github.com/jupyterhub/nativeauthenticator/issues/105

**Comment by KamalGalrani** [comment]
If you don't want to create systme users, https://github.com/KamalGalrani/jupyterhub-nativespawner

**Comment by yumupdate** [comment]
Just use this in config file 
c.Authenticator.use_lookup_dn_username=False

**Comment by sujay37** [comment]
o
