### ISSUE TITLE
ReadTheDocs builds are failing

### ISSUE THREAD

**Issue by manics** [jupyterhub/jupyterhub#2958]
The [docs builds](https://readthedocs.org/projects/jupyterhub/builds/) have been failing since [Feb. 26, 2020. 1:05 p.m](https://readthedocs.org/projects/jupyterhub/builds/10508207/). This means https://github.com/jupyterhub/jupyterhub/pull/2956 which should've fixed https://github.com/jupyterhub/jupyterhub/issues/2955 hasn't been deployed

[Most recent failure](https://readthedocs.org/projects/jupyterhub/builds/10520408/):
```
[rtd-command-info] start-time: 2020-02-28T10:48:22.704838Z, end-time: 2020-02-28T10:48:35.821550Z, duration: 13, exit-code: 1
conda env create --quiet --name latest --file docs/environment.yml
Collecting package metadata (repodata.json): ...working... failed

CondaHTTPError: HTTP 500 CONNECTION FAILED for url <https://metachannel.conda-forge.org/conda-forge/jupyterhub,sphinx,recommonmark/noarch/repodata.json>
Elapsed: 00:00.420768
CF-RAY: 56c1d36d1d42ccd6-EWR

A remote server error occurred when trying to retrieve this URL.

A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
fulfill a valid request.  The problem may be spurious, and will resolve itself if you
try your request again.  If the problem persists, consider notifying the maintainer
of the remote server.
```

**Comment by betatim** [comment]
Locally `wget https://metachannel.conda-forge.org/conda-forge/jupyterhub,sphinx,recommonmark/linux-64/repodata.json` takes a moment (10s or so??) to start sending a reply by works (now).

Here the status 500 came very quickly (~0.4s), could it be that network access on RTD is firewalled?

**Comment by willingc** [comment]
@manics I just double-checked RTD. You are correct that there were build failures 3 weeks ago. I just checked and it is working properly. I'm going to close. Please let me know if this has persisted for you.

**Comment by willingc** [comment]
@GeorgianaElena May be the same error but unrelated. PyPI was having issues this morning which may be affecting RTD and even conda-forge.

I tried wiping the container and rebuilding. Still getting a 500 error. Do you have a RTD account? I could add you as a maintainer there.

**Comment by GeorgianaElena** [comment]
Thanks for investigating @willingc :heart:

My handle on RTD is *GeorgianaElena*

**Comment by willingc** [comment]
I've added you @GeorgianaElena. I tried wiping and rebuilding.

The erroring URL looks weird: https://metachannel.conda-forge.org/conda-forge/jupyterhub,sphinx,recommonmark/noarch/repodata.json

**Comment by GeorgianaElena** [comment]
The metachannel service is down and we might need to switch to full conda-forge.

Checkout this comment: https://github.com/regro/conda-metachannel/issues/31#issuecomment-606267515 for context.
Is there anything we can do to help :eyes: ?

**Comment by manics** [comment]
RTD recommends pip instead of conda where possible. Should we switch? https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html#use-pip-when-possible

**Comment by GeorgianaElena** [comment]
@manics, I tried switching to pip (https://github.com/jupyterhub/jupyterhub/compare/master...GeorgianaElena:pip_for_docs), but I'm getting an error: https://readthedocs.org/projects/georgiana-jh-docs/builds/10734319.

**Comment by manics** [comment]
Is it possible to disable conda completely?

**Comment by manics** [comment]
Looks like JupyterLab is an example that avoids conda:
- https://github.com/jupyterlab/jupyterlab/tree/v2.0.1/docs
- https://github.com/jupyterlab/jupyterlab/blob/v2.0.1/readthedocs.yml

**Comment by willingc** [comment]
It's totally fine to switch to pip.

**Comment by choldgraf** [comment]
+1 to using pip!

**Comment by betatim** [comment]
Note from the history books: we started using metachannel because the full conda(-forge) channel was using too much memory on RTD. Switching to pip seems like a smart move.
