### ISSUE TITLE
nbgallery support?

### ISSUE THREAD

**Issue by elgalu** [jupyterhub/jupyterhub#2964]
https://github.com/nbgallery/nbgallery

**Comment by manics** [comment]
Hi! Please could you elaborate on the steps required to support nbgallery in JupyterHub? For example, what changes need to need made? Is this purely a JupyterHub issue or does it also require changes in nbgallery?

**Comment by elgalu** [comment]
Auth, "Run in Jupyter" from nbgallery should run in JupyterHub context.

But nbgallery looks rather abandoned/low adoption right now so I'm closing this, thanks for pinging!

**Comment by manics** [comment]
@elgalu Thanks for updating us. If you want to follow this up please feel free to search or start a discussion on the community forum https://discourse.jupyter.org/, others may well be interested and there might be other projects that fit your needs.
