### ISSUE TITLE
singleuser server version check spams the logs

### ISSUE THREAD

**Issue by mriedem** [jupyterhub/jupyterhub#2970]
**Describe the bug**

We have ~277 active single user servers in our deployment right now and on restart of the hub service we see this for each one:

> Mar 4 09:20:45 hub-7bccd48cd5-mp4fk hub [W 2020-03-04 15:20:45.996 JupyterHub _version:56] jupyterhub version 1.2.0dev != jupyterhub-singleuser version 1.1.0. This could cause failure to authenticate and result in redirect loops! 

My only complaint is that logging that per server is redundant and spams the logs. Can we just log that once per restart of the hub?

**To Reproduce**

Have the jupyterhub and jupyterhub-singleuser services at different minor versions.

**Expected behavior**

Just log the warning once since there is no user/server specific context in the message.

**Compute Information**
 - 1.2.0dev - we're running with a custom build based on b4391d0f796864a5b01167701d95eafce3ad987e so that we can pick up the performance fix for issue #2928.

**Comment by betatim** [comment]
Logging for every server might be overkill but only once per hub restart isn't enough because not every single-user server has to be running the same version. If 90% of your servers are running a compatible version but 10% aren't you'd want to know about all of the ones that are somehow in need of attention.

However I've never acted on this log message or found that I needed it. So I propose finding out the history of it and then deciding what to do (change log level, remove warning, etc).

**Comment by mriedem** [comment]
> If 90% of your servers are running a compatible version but 10% aren't you'd want to know about all of the ones that are somehow in need of attention.

The issue with this is that, as written today, the log message doesn't have any context about the server in question (unless I'm missing something), so it's just a lot of redundant warnings.

Good point on the actual jupyterhub-singleuser versions potentially being different though. If we still want to log the mismatch warning then I could modify pull #2971 to log once per singleuser version.

**Comment by mriedem** [comment]
> However I've never acted on this log message or found that I needed it. So I propose finding out the history of it and then deciding what to do (change log level, remove warning, etc).

Looks like the code was added in d167e275d1a25156515707d1e70f27f8e2a76b87 via pull #1169. I don't see a related issue or forum thread so I'm not sure what prompted this, i.e. if this was added in response to some API compatibility issue at the time where the hub and notebook server apps being at different minor versions caused some problems. Maybe @minrk remembers the history there.
