### ISSUE TITLE
hub not accessible when switching from helm 0.8.2 to 0.0.0-beta.4

### ISSUE THREAD

**Issue by adi413** [jupyterhub/jupyterhub#2974]
**Issue I am facing**
I am trying to switch from helm stable version 0.8.2 of jupyterhub to beta version 0.9.0-beta.4 so that I can use the named server functionality. When I trying to do that https is not working and if I find the public-proxy ip address I am not able to access hub on https.

**Description**

If I try to directly upgrade the helm release with a different version number then I get the following ***error: kind ConfigMap with the name "traefik-proxy-config" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart***

To shift from version 0.8.2 to 0.9.0-beta.4 I need to first delete the release with version 0.8.2 and then install hub with version 0.9.0-beta.4. This deploys the changes with https enabled then I cannot access the public proxy ip address generated by hub.
I need to disable auto-https and then I can access hub.

It will be great if you can tell me why this might be happening and what can be done to fix this

**Comment by mriedem** [comment]
This issue should be reported in the helm chart repo:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s
