### ISSUE TITLE
Not able to access jupyter note book in web any  browser , getting  spawn error

### ISSUE THREAD

**Issue by mukhendra** [jupyterhub/jupyterhub#2977]
Hi Team,

While accessing  Jupyter hub link in web browser I'm getting error like 
You will be redirected automatically when it's ready for you.
Can someone please help us.
![jupyter issue](https://user-images.githubusercontent.com/40772418/76295459-a8a50100-62da-11ea-8d25-30559fe25c4f.png)

**Comment by subgero** [comment]
@mukhendra Im facing the same problem and there is no documentation about that. Please let me know if you found a solution. Thank you.
