### ISSUE TITLE
Jupyterhub Nginx Reverse Proxy WSS Connection Not Working

### ISSUE THREAD

**Issue by rmalav15** [jupyterhub/jupyterhub#2981]
Hi,

I am using [jupyterhub-deploy-docker repo](https://github.com/jupyterhub/jupyterhub-deploy-docker) for running Jupyterhub (Docker) with DockerSpawner. I have basic configurations set up for Jupyterhub:
```
# User containers will access hub by container name on the Docker network
c.JupyterHub.hub_ip = 'jupyterhub'
c.JupyterHub.hub_port = 8080
# TLS config
c.JupyterHub.port = 80
# Debug
c.DockerSpawner.debug = True
c.JupyterHub.log_level = 'DEBUG'
```
Please note that Jupyterhub is running inside docker and I am using port forwarding to connect from outside:
```
# From docker-compose file 
ports:
      - "8700:80"
```
 
This works perfectly behind Nginx proxy in a staging environment that uses only **HTTP**. Following is my very simple Nginx conf which works perfectly:
```
 server {
    listen 80;
    server_name STAGING_SERVER_IP;

    location ~ ^/(hub|user)/ {
        proxy_pass http://localhost:8700;
        proxy_set_header Host $host;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```

With the above config Both HTTP and WS request (required for kernel) works perfectly:
![image](https://user-images.githubusercontent.com/10210908/76399410-8d9ec380-63a4-11ea-8f4c-1d548d4be9f4.png)
![image](https://user-images.githubusercontent.com/10210908/76399372-8081d480-63a4-11ea-92cd-f09418a795d4.png)

However, when I move the setup in a production setting with **HTTPS Domain** (managed by aws) the above configuration failed. So I changed the configuration following [these](https://gist.github.com/zonca/08c413a37401bdc9d2a7f65a7af44462) and [these guidelines](https://jupyterhub.readthedocs.io/en/stable/reference/config-proxy.html). Now my Nginx conf is this:
```
server {
    listen 80;
    server_name PROD_DOMAIN;
   location / {
        proxy_pass http://localhost:8700;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;
   }
   location ~* /(user/[^/]*)/(api/kernels/[^/]+/channels|terminals/websocket)/? {
            proxy_pass http://localhost:8700;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-NginX-Proxy true;
            # WebSocket support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;
        }
}
```
Please note two things. First, I am not adding SSL key and cert as it is managed by AWS. Second, I am not setting "c.JupyterHub.bind_url" as Jupyterhub is running inside docker not on host network.
With this configuration, **HTTPS** requests are working perfectly but **WSS** (In staging it was **WS**) requests go into pending state and then fails. I am able to see Jupyterhub UI but not able to connect to any kernel or terminal.
![image](https://user-images.githubusercontent.com/10210908/76400937-1fa7cb80-63a7-11ea-93a6-af7b28000483.png)
![image](https://user-images.githubusercontent.com/10210908/76400860-0272fd00-63a7-11ea-9f5b-4cfa0ebe42c0.png)
![image](https://user-images.githubusercontent.com/10210908/76400867-069f1a80-63a7-11ea-9165-c7a1e93f948d.png)

I have the following two questions

1.  First is of course, how to resolve this? :)
2. Even with DEBUG setting on, I am not able to see any logs related to WebSocket in Jupyterhub. Is there conf related to WebSocket logs?

Thanks,
Ram

 PS: I tried this with two Jupyterhub version 0.9.2 and 1.0.0. Nginx version is nginx/1.14.2.
Apologies for the long question. I wanted to give the whole picture.

**Comment by kk456852** [comment]
> Hi,
> 
> I am using [jupyterhub-deploy-docker repo](https://github.com/jupyterhub/jupyterhub-deploy-docker) for running Jupyterhub (Docker) with DockerSpawner. I have basic configurations set up for Jupyterhub:
> 
> ```
> # User containers will access hub by container name on the Docker network
> c.JupyterHub.hub_ip = 'jupyterhub'
> c.JupyterHub.hub_port = 8080
> # TLS config
> c.JupyterHub.port = 80
> # Debug
> c.DockerSpawner.debug = True
> c.JupyterHub.log_level = 'DEBUG'
> ```
> 
> Please note that Jupyterhub is running inside docker and I am using port forwarding to connect from outside:
> 
> ```
> # From docker-compose file 
> ports:
>       - "8700:80"
> ```
> 
> This works perfectly behind Nginx proxy in a staging environment that uses only **HTTP**. Following is my very simple Nginx conf which works perfectly:
> 
> ```
>  server {
>     listen 80;
>     server_name STAGING_SERVER_IP;
> 
>     location ~ ^/(hub|user)/ {
>         proxy_pass http://localhost:8700;
>         proxy_set_header Host $host;
>         proxy_redirect off;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
>     }
> }
> ```
> 
> With the above config Both HTTP and WS request (required for kernel) works perfectly:
> ![image](https://user-images.githubusercontent.com/10210908/76399410-8d9ec380-63a4-11ea-8f4c-1d548d4be9f4.png)
> ![image](https://user-images.githubusercontent.com/10210908/76399372-8081d480-63a4-11ea-92cd-f09418a795d4.png)
> 
> However, when I move the setup in a production setting with **HTTPS Domain** (managed by aws) the above configuration failed. So I changed the configuration following [these](https://gist.github.com/zonca/08c413a37401bdc9d2a7f65a7af44462) and [these guidelines](https://jupyterhub.readthedocs.io/en/stable/reference/config-proxy.html). Now my Nginx conf is this:
> 
> ```
> server {
>     listen 80;
>     server_name PROD_DOMAIN;
>    location / {
>         proxy_pass http://localhost:8700;
>         proxy_set_header Host $host;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header X-NginX-Proxy true;
>    }
>    location ~* /(user/[^/]*)/(api/kernels/[^/]+/channels|terminals/websocket)/? {
>             proxy_pass http://localhost:8700;
>             proxy_set_header X-Real-IP $remote_addr;
>             proxy_set_header Host $host;
>             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>             proxy_set_header X-NginX-Proxy true;
>             # WebSocket support
>             proxy_http_version 1.1;
>             proxy_set_header Upgrade $http_upgrade;
>             proxy_set_header Connection "upgrade";
>             proxy_read_timeout 86400;
>         }
> }
> ```
> 
> Please note two things. First, I am not adding SSL key and cert as it is managed by AWS. Second, I am not setting "c.JupyterHub.bind_url" as Jupyterhub is running inside docker not on host network.
> With this configuration, **HTTPS** requests are working perfectly but **WSS** (In staging it was **WS**) requests go into pending state and then fails. I am able to see Jupyterhub UI but not able to connect to any kernel or terminal.
> ![image](https://user-images.githubusercontent.com/10210908/76400937-1fa7cb80-63a7-11ea-93a6-af7b28000483.png)
> ![image](https://user-images.githubusercontent.com/10210908/76400860-0272fd00-63a7-11ea-9f5b-4cfa0ebe42c0.png)
> ![image](https://user-images.githubusercontent.com/10210908/76400867-069f1a80-63a7-11ea-9165-c7a1e93f948d.png)
> 
> I have the following two questions
> 
> 1. First is of course, how to resolve this? :)
> 2. Even with DEBUG setting on, I am not able to see any logs related to WebSocket in Jupyterhub. Is there conf related to WebSocket logs?
> 
> Thanks,
> Ram
> 
> PS: I tried this with two Jupyterhub version 0.9.2 and 1.0.0. Nginx version is nginx/1.14.2.
> Apologies for the long question. I wanted to give the whole picture.

Has this problem been solved
Need help
