### ISSUE TITLE
Failed to find proxy ['configurable-http-proxy']

### ISSUE THREAD

**Issue by lx28110846** [jupyterhub/jupyterhub#2982]
[C 2020-03-11 19:10:10.500 JupyterHub app:2517] Failed to start proxy
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 2515, in start
        await self.proxy.start()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/proxy.py", line 656, in start
        cmd, env=env, start_new_session=True, shell=shell
      File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'configurable-http-proxy': 'configurable-http-proxy'

i am sure configurable-http-proxy has already installed !

**Comment by GeorgianaElena** [comment]
Hey @lx28110846. It might be that configurable-http-proxy is not on the PATH. Checkout [this comment](https://github.com/jupyterhub/jupyterhub/issues/930#issuecomment-444049046) about how to fix it.

**Comment by lx28110846** [comment]
> Hey @lx28110846. It might be that configurable-http-proxy is not on the PATH. Checkout [this comment](https://github.com/jupyterhub/jupyterhub/issues/930#issuecomment-444049046) about how to fix it.

thanks, i get it, it has been solved
