### ISSUE TITLE
TypeError: string.split is not a function when opening an uploaded notebook

### ISSUE THREAD

**Issue by rsbotmoo** [jupyterhub/jupyterhub#2985]
When opening an notebook (.ipynb file) that was uploaded via the upload function. I am getting following error message in a pop up.

```
Notebook failed to load
The error was:

TypeError: string.split is not a function
See the error console for details.
```
![image](https://user-images.githubusercontent.com/26330995/76535900-e68d5b00-647b-11ea-8218-cd1a23a95176.png)

When looking in the browser console I can see following error.

`
main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:54327 Notebook failed to load from JSON: TypeError: string.split is not a function
    at splitLinesAuto (main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:11351)
    at Doc.splitLines (main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:17179)
    at Doc.<anonymous> (main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:16828)
    at Doc.setValue (main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:14616)
    at CodeMirror.setValue (main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:20417)
    at CodeCell.set_text (main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:47259)
    at CodeCell.fromJSON (main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:47276)
    at Notebook.fromJSON (main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:53838)
    at Notebook.load_notebook_success (main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:54324)
    at proxy (main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316:10502)
`

![image](https://user-images.githubusercontent.com/26330995/76536002-0ae93780-647c-11ea-8245-6f5539c9039e.png)

After some debugging, it seems that inside the notebook code, the source of a cell is a string array, which the split function will fail on.

```
"cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source":[
    "# This is a test"
    ]
  }
```

Following example will pass:

```
"cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source":
    "# This is a test"
  }
```

**Compute Information**
 - Jupyter notebook version 6.0.3 running on ECS installed with conda 4.7.12
 - JupyterHub Version 1.1.0 running on EC2 installed with conda 4.8.2

**Comment by manics** [comment]
JupyterHub manages users and notebook servers, but it doesn't directly interact with notebooks. For instance, if you run Jupyter Notebook locally you should get the same error.

This is the relevant repo: https://github.com/jupyter/notebook
If you open an issue there instead it would be helpful if you can include a minimal notebook that demonstrates the bug- this will make it easier for someone to debug or verify it. It would also be useful to know how you created the notebook in case it's an error during saving instead of loading.

**Comment by rsbotmoo** [comment]
Hi @manics,

Thanks for the quick response, I have tested it locally by starting a notebook, uploading the same .ipynb file. And it works. 
I have then checked the JS assets, and those are not the same as Jupyterhub.
The Jupyerhub version has 1 big JS file, while the local notebook version has individual javascript files.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/file-save-error-in-r-notebook/3658/4

**Comment by manics** [comment]
Closing, as there have been no further reports and no examples of reproducing the problem
