### ISSUE TITLE
Manually spawn jupyter worker

### ISSUE THREAD

**Issue by Hoeze** [jupyterhub/jupyterhub#2986]
Hi, is it possible to manually spawn workers?

E.g. I'd like to run a notebook server on my local desktop, which is not in our Slurm queue.
This way, the Jupyterhub server would work as a proxy for me.

Having a single run command for a worker like:
```
jupyterhub run-worker --remote=https://cluster.com/jupyterhub/ --server_name="manually_spawned" --user=myname --[token=(.*)|ask-pass]
```
would serve two purposes:

- It would allow to manually spawn workers wherever one would like to. Jupyterhub would work as proxy for the workers and nobody has to use stupid port forwardings any more.
- Debugging would probably be easier

( This issue is taken from https://github.com/jupyterhub/batchspawner/issues/169)

**Comment by manics** [comment]
Have you come across Jupyter Enterprise Gateway? https://jupyter-enterprise-gateway.readthedocs.io/en/latest/

**Comment by Hoeze** [comment]
@manics No, I did not know this one. However, I would like to have a Jupyterlab instance running on some machine which is proxied by Jupyterhub. My target is independent of any Spark (/Dask/...) cluster.

**Comment by Hoeze** [comment]
I just noticed that there is already a solution to this issue:
https://github.com/jupyterhub/jupyterhub/pull/2727

**Comment by rkdarst** [comment]
> I just noticed that there is already a solution to this issue:
> https://github.com/jupyterhub/jupyterhub/pull/2727

That isn't intended to do this, but you are right that it could
possibly be reused for this purpose: a spawner that doesn't actually
start anything, but prints out a shell command to run somewhere of
your choosing that can connect back.  There may be unexpected
complications along the way.

There's no natural support for what you want: JH always assumes the
spawer starts from the hub.  But, another clever way to do this would
be to create a script (jupyterhub-runworker) which connects to the
hub, uses the jupyterhub API to say "please start manual worker with
these parameters: remote_ip=X, remote_port=X.", and instead manually
start it yourself.  Thing is, you need to at least get the JupyterHub
API token back to your own instance, and possibly more.  This is where
it gets interesting.  I'm not the most qualified person to give advice
on these matters, but if no one else can I can try.

If you have ssh access, I'm not sure if this is easier than using
something such as `ssh -D`.  I add in the FoxyProxy browser extension
and things work really easily.  But, for deploying to others, this
requires each person to do their own setup work which isn't that
scaleable.

**Comment by manics** [comment]
I'm closing this issue as it sounds like it's out of scope for JupyterHub. If you'd like to discuss it further please start a thread on the community forum https://discourse.jupyter.org

**Comment by Hoeze** [comment]
@manics I'd not agree that this is out of scope of Jupyterhub.
The most clean solution to this issue would be if the `jupyterhub-singleuser` binary would work as described.

I.e. instead of jupyterhub connecting to the single-user worker, I'd expect the single-user worker to connect to the Jupyterhub.
This has many important implication, the most important one is that I do not need to open the firewall on workers.

**Comment by manics** [comment]
@Hoeze Reversing the connections requries a significant refactoring of JupyterHub. You could probably put something together though by writing your own spawner that tunnels connections, though that would be an extension outside this repo.

Your use case is definitely valid, but due to it's complexity I'd strongly urge you to engage with the community on https://discourse.jupyter.org/ . A lot more people hang out there, and there's lots of experience of customising Jupyter projects for all sorts of use cases. You may well find someone who's solved your problem in a different way that requries less work than rewritign JupyterHub or a spawner!
