### ISSUE TITLE
Failed to open PAM session for <username>: [PAM Error 14] Cannot make/remove an entry for the specified session 

### ISSUE THREAD

**Issue by zainul1114** [jupyterhub/jupyterhub#2987]
Hi,
Please help me to resolve this issue

[root@master jupyterhub]# jupyterhub --ip 192.168.43.47 --ssl-key jhub.key --ssl-cert jhub.crt
[I 2020-03-15 23:23:47.821 JupyterHub app:2240] Running JupyterHub version 1.1.0
[I 2020-03-15 23:23:47.822 JupyterHub app:2271] Using Authenticator: jupyterhub.auth.PAMAuthenticator-1.1.0
[I 2020-03-15 23:23:47.822 JupyterHub app:2271] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.1.0
[I 2020-03-15 23:23:47.822 JupyterHub app:2271] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.1.0
[I 2020-03-15 23:23:47.824 JupyterHub app:1349] Loading cookie_secret from /etc/jupyterhub/jupyterhub_cookie_secret
[I 2020-03-15 23:23:47.850 JupyterHub proxy:461] Generating new CONFIGPROXY_AUTH_TOKEN
[W 2020-03-15 23:23:47.852 JupyterHub app:1624] No admin users, admin interface will be unavailable.
[W 2020-03-15 23:23:47.852 JupyterHub app:1626] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2020-03-15 23:23:47.852 JupyterHub app:1655] Not using whitelist. Any authenticated user will be allowed.
10
[I 2020-03-15 23:23:47.912 JupyterHub app:2311] Initialized 0 spawners in 0.003 seconds
[W 2020-03-15 23:23:47.918 JupyterHub proxy:517] Found proxy pid file: /etc/jupyterhub/jupyterhub-proxy.pid
[W 2020-03-15 23:23:47.920 JupyterHub proxy:529] Proxy no longer running at pid=451
[I 2020-03-15 23:23:47.922 JupyterHub proxy:646] Starting proxy @ http://192.168.43.47:8000/
23:23:48.167 [ConfigProxy] info: Proxying https://192.168.43.47:8000 to (no default)
23:23:48.170 [ConfigProxy] info: Proxy API at http://127.0.0.1:8001/api/routes
23:23:48.472 [ConfigProxy] info: 200 GET /api/routes
[I 2020-03-15 23:23:48.474 JupyterHub app:2556] Hub API listening on http://127.0.0.1:8081/hub/
23:23:48.477 [ConfigProxy] info: 200 GET /api/routes
[I 2020-03-15 23:23:48.478 JupyterHub proxy:320] Checking routes
[I 2020-03-15 23:23:48.478 JupyterHub proxy:400] Adding default route for Hub: / => http://127.0.0.1:8081
23:23:48.481 [ConfigProxy] info: Adding route / -> http://127.0.0.1:8081
23:23:48.482 [ConfigProxy] info: Route added / -> http://127.0.0.1:8081
23:23:48.482 [ConfigProxy] info: 201 POST /api/routes/
[I 2020-03-15 23:23:48.483 JupyterHub app:2631] JupyterHub is now running at http://192.168.43.47:8000/
[I 2020-03-15 23:24:28.003 JupyterHub log:174] 302 GET / -> /hub/ (@127.0.0.1) 2.21ms
[I 2020-03-15 23:24:28.017 JupyterHub log:174] 302 GET /hub/ -> /hub/login (@127.0.0.1) 1.49ms
[I 2020-03-15 23:24:28.494 JupyterHub log:174] 200 GET /hub/login (@127.0.0.1) 455.97ms
[I 2020-03-15 23:25:12.119 JupyterHub base:707] User logged in: zain
[I 2020-03-15 23:25:12.125 JupyterHub log:174] 302 POST /hub/login?next= -> /hub/spawn (zain@127.0.0.1) 992.03ms
[W 2020-03-15 23:25:12.639 JupyterHub auth:956] Failed to open PAM session for zain: [PAM Error 14] Cannot make/remove an entry for the specified session
[W 2020-03-15 23:25:12.640 JupyterHub auth:957] Disabling PAM sessions from now on.
[I 2020-03-15 23:25:12.669 JupyterHub spawner:1417] Spawning jupyterhub-singleuser --port=41201
/share/apps/platform/ai/py36/3_6_8/bin/python3: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
[I 2020-03-15 23:25:13.151 JupyterHub log:174] 302 GET /hub/spawn -> /hub/spawn-pending/zain (zain@127.0.0.1) 1019.25ms
[I 2020-03-15 23:25:13.184 JupyterHub pages:347] zain is pending spawn
[I 2020-03-15 23:25:13.255 JupyterHub log:174] 200 GET /hub/spawn-pending/zain (zain@127.0.0.1) 87.84ms
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /share/apps/platform/ai/py36/3_6_8/lib/python3.6/site-packages/jupyterhub/handlers/base.py:741> exception=HTTPError()>
Traceback (most recent call last):
  File "/share/apps/platform/ai/py36/3_6_8/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 939, in spawn_single_user
    timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/apps/platform/ai/py36/3_6_8/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 972, in spawn_single_user
    % (status, spawner._log_name),
tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=127]. The logs for zain may contain details.)
[W 2020-03-15 23:25:44.819 JupyterHub user:692] zain's server never showed up at http://127.0.0.1:41201/user/zain/ after 30 seconds. Giving up
[E 2020-03-15 23:25:44.930 JupyterHub gen:599] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /share/apps/platform/ai/py36/3_6_8/lib/python3.6/site-packages/jupyterhub/handlers/base.py:845> exception=TimeoutError("Server at http://127.0.0.1:41201/user/zain/ didn't respond in 30 seconds",)> after timeout
    Traceback (most recent call last):
      File "/share/apps/platform/ai/py36/3_6_8/lib/python3.6/site-packages/tornado/gen.py", line 593, in error_callback
        future.result()
      File "/share/apps/platform/ai/py36/3_6_8/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 852, in finish_user_spawn
        await spawn_future
      File "/share/apps/platform/ai/py36/3_6_8/lib/python3.6/site-packages/jupyterhub/user.py", line 668, in spawn
        await self._wait_up(spawner)
      File "/share/apps/platform/ai/py36/3_6_8/lib/python3.6/site-packages/jupyterhub/user.py", line 715, in _wait_up
        raise e
      File "/share/apps/platform/ai/py36/3_6_8/lib/python3.6/site-packages/jupyterhub/user.py", line 683, in _wait_up
        http=True, timeout=spawner.http_timeout, ssl_context=ssl_context
      File "/share/apps/platform/ai/py36/3_6_8/lib/python3.6/site-packages/jupyterhub/utils.py", line 234, in wait_for_http_server
        timeout=timeout,
      File "/share/apps/platform/ai/py36/3_6_8/lib/python3.6/site-packages/jupyterhub/utils.py", line 177, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:41201/user/zain/ didn't respond in 30 seconds

Regards,
Zain

**Comment by willingc** [comment]
Hi there 👋!

Can we move this discussion to http://discourse.jupyter.org/ (where most of the people who hang out here also hang out, as well as more people). We are trying to streamline the [different discussion places](https://discourse.jupyter.org/t/a-proposal-for-jupyterhub-communications/505) and want to use the issues on GitHub repos for technical discussions on how to change the contents of the repo. More general discussions should go to discourse so that they are easier to find, better indexed by google and generally more accessible than being hidden in the bowls of a GitHub repository ;)

Thanks!
