### ISSUE TITLE
Not able to log in as admin in jupyterhub Docker image

### ISSUE THREAD

**Issue by SaiAparna1** [jupyterhub/jupyterhub#2989]
What are the default admin username and password for jupyterhub image?
I thought that is 'root' ( which is mentioned in dockerfile of image) and I am also don't know the password for that user. So, I have changed the password by using command passwd as like what we do in Linux machine. But still, I am not able to log in and getting error as follows,

[W 2020-03-17 10:35:25.881 JupyterHub auth:923] PAM Authentication failed (root@::ffff:my_ip): [PAM Error 3] Error in service module
[W 2020-03-17 10:35:25.881 JupyterHub base:714] Failed login for root

Could anyone please help me how to log in as admin in jupyterhub image?

**Comment by GeorgianaElena** [comment]
Hey @SaiAparna1 :wave:
Are you using the ready-to-go docker image mentioned [here](https://jupyterhub.readthedocs.io/en/stable/quickstart-docker.html#starting-jupyterhub-with-docker)?
If yes:
* that is only an image for running the Hub service (with the default configuration) and does not have other Jupyter components (like the notebook).
* for default Hub authenticator (PAM), you can login using the credentials of the system users in the container. Checkout [this section](https://jupyterhub.readthedocs.io/en/stable/quickstart-docker.html#starting-jupyterhub-with-docker) on how to get a shell inside the container and add a system user.
* after you login using the credentials of the newly added container system user, you might also need to install the Notebook (From within the container: `pip install notebook`)

**Comment by subgero** [comment]
@GeorgianaElena Hi there, Im using the ready-to-go docker image but when start the container I get this message: Spawn failed: Server at http://127.0.0.1:33281/user/gero/ didn't respond in 30 seconds

Im missing something? Did I must run sudospawner inside in the docker container?

**Comment by SaiAparna1** [comment]
Thank you for your reply Elena. I will check the points what you have
shared with me and test that.

**Comment by SaiAparna1** [comment]
Hi Georgiana Elena,

I have done the same thing that are mention in  this section
<https://jupyterhub.readthedocs.io/en/stable/quickstart-docker.html#starting-jupyterhub-with-docker>.
Still I am not able to login as root but I can able to login as remaining
users. If I am not not able to login as root then I have to create users
along with passwords manually inside container. So, could you please let me
know how can I login as root?

**Comment by SaiAparna1** [comment]
What I mean is how to get admin access to the jupyterhub UI to create users
from that. Like users creation in jupyterhub littlest
http://tljh.jupyter.org/en/latest/install/custom-server.html.

**Comment by Tehami** [comment]
did anyone find a solution to this? My jupyterhub instance is running in a docker container but I want to use the PAM users of the host machine. I can't mount /etc/passwd volume because my host OS is CentOS whereas Jupyterhub image is based on Ubuntu

**Comment by DCMMC** [comment]
> did anyone find a solution to this? My jupyterhub instance is running in a docker container but I want to use the PAM users of the host machine. I can't mount /etc/passwd volume because my host OS is CentOS whereas Jupyterhub image is based on Ubuntu

`docker exec -it jupyterhub bash` and then `passwd root` to set the password of root.
After that, you can use username `root` and password you set above to login.

**Comment by JeongtaekLim** [comment]
I followed solution of @DCMMC.
However, root admin always returned "Spawn failed" error.
Only normal user which is created after docker installed can get spawn successfully.
It didn't work for me..

**Comment by whoareyou2021** [comment]
> I followed solution of @DCMMC. However, root admin always returned "Spawn failed" error. Only normal user which is created in docker container can get spawn successfully. It didn't work for me..

2 years late, but better late then never.
I created a user and install jupyterlabs (or you can install jupyternotebook) and it spawned a instance perfectly.
