### ISSUE TITLE
Working fine but 500 internal server error using jupyter lab extension manager 

### ISSUE THREAD

**Issue by camelator** [jupyterhub/jupyterhub#2990]
Hi,
firstly many thanks to the jupyter team.
I successfully build a docker image including jupyterhub, jupyter lab for a small  ARM server at home.
Logging, using jupyterlab work fine.
But I don't know why, I have no success using jupyter lab Extension manager
Extension Manager works fine refreshing the extension list
but I Have a 500 internal server error by installing new extension. 
I am new with jupyterhub and lab so I don't really know how to debug, etc...
I lauched jupyerhub with --debug option and here is the file content.

What can be the issue? How improve debug level to provide more information if requested?
Many thanks

11:11:08.529 [ConfigProxy] ^[[32minfo^[[39m: Proxying http://*:8000 to (no default)
11:11:08.543 [ConfigProxy] ^[[32minfo^[[39m: Proxy API at http://127.0.0.1:8001/api/routes
11:11:08.979 [ConfigProxy] ^[[32minfo^[[39m: 200 GET /api/routes
11:11:08.995 [ConfigProxy] ^[[32minfo^[[39m: 200 GET /api/routes
11:11:09.015 [ConfigProxy] ^[[32minfo^[[39m: Adding route / -> http://jupyterhub:8081
11:11:09.019 [ConfigProxy] ^[[32minfo^[[39m: Route added / -> http://jupyterhub:8081
11:11:09.023 [ConfigProxy] ^[[32minfo^[[39m: 201 POST /api/routes/
11:12:46.606 [ConfigProxy] ^[[32minfo^[[39m: Adding route /user/cvotava -> http://127.0.0.1:36815
11:12:46.637 [ConfigProxy] ^[[32minfo^[[39m: Route added /user/cvotava -> http://127.0.0.1:36815
11:12:46.639 [ConfigProxy] ^[[32minfo^[[39m: 201 POST /api/routes/user/cvotava
-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^H|^H/^H-^H\^$

**Comment by ryogesh** [comment]
Here are some of the options that you can set to get additional debug information

c.JupyterHub.log_level = 'DEBUG'
c.ConfigurableHTTPProxy.debug = True
c.DockerSpawner.debug = True
c.Spawner.debug = True

Reference:
https://jupyterhub.readthedocs.io/en/stable/api/app.html

**Comment by camelator** [comment]
Many thanks,
I discovered I have two types of errors:
**1/ a security option**
Reading the docs, I think I need to change the spawner (not sure - here are the logs), maybe with sudospawner, but not sure of the best way in my case : I am running jupyterhub in a single docker container including jupyterlab. Please any advice with regards to the log will be helpfull

[W 2020-03-22 11:03:35.895 SingleUserNotebookApp web:1786] 500 POST /user/cvotava/lab/api/extensions?1584871413575 (::ffff:192.168.2.115): [Errno 13] Permission denied: '/usr/local/share/jupyter/lab/settings',
[W 2020-03-22 11:03:35.896 SingleUserNotebookApp handlers:608] [Errno 13] Permission denied: '/usr/local/share/jupyter/lab/settings',
[E 2020-03-22 11:03:35.903 SingleUserNotebookApp log:166] {,
      "X-Forwarded-Host": "192.168.2.114:7000",,
      "X-Forwarded-Proto": "http",,
      "X-Forwarded-Port": "7000",,
      "X-Forwarded-For": "::ffff:192.168.2.115",,
      "Cache-Control": "no-cache",,
      "Pragma": "no-cache",,
      "Cookie": "jupyterhub-user-cvotava=[secret]; compact_display_state=[secret]; filter=[secret]; portainer.LOGIN_STATE_UUID=[secret];


**2/ a building issue** 
Here again, any help will be usefull as I have no results with google typing 'AppOptions' object has no attribute 'all'


[W 2020-03-22 11:03:20.834 SingleUserNotebookApp web:1786] 500 POST /user/cvotava/lab/api/build?1584871394742 (::ffff:192.168.2.115): 'AppOptions' object has no attribute 'all',
[W 2020-03-22 11:03:20.836 SingleUserNotebookApp handlers:608] 'AppOptions' object has no attribute 'all',
[E 2020-03-22 11:03:20.841 SingleUserNotebookApp log:166] {,
      "X-Forwarded-Host": "192.168.2.114:7000",,
      "X-Forwarded-Proto": "http",,
      "X-Forwarded-Port": "7000",,
      "X-Forwarded-For": "::ffff:192.168.2.115",,
      "Content-Length": "0",,
      "Cache-Control": "no-cache",,
      "Pragma": "no-cache",,
      "Cookie": "jupyterhub-user-cvotava=[secret]; compact_display_state=[secret]; filter=[secret]; portainer.LOGIN_STATE_UUID=[secret]; portainer.datatable_text_filter_home_endpoints=[secret]; portainer.datatable_settings_networks=[secret]; portainer.datatable_settings_images=[secret];
