### ISSUE TITLE
JupyterHub connect to existing [voila] server

### ISSUE THREAD

**Issue by sntgluca** [jupyterhub/jupyterhub#2998]
Hi all,

I am exploring the various possibilities to authenticate/authorise connections to a voila dashboard.
One scenario is having a dashboard up and running, on a separate process, with specified user privileges, and allow a selection of users to connect to it.

I am looking for the simplest configuration to make JupyterHub act only as a proxy, without starting a new server, and upon authentication connect directly to the dashboard server. Any suggestion?

**Comment by danlester** [comment]
We've been in touch about this directly, but for the benefit of anyone else reading, my ContainDS Dashboards project can do exactly that: take a Jupyter notebook and instantly clone it into a Voila server accessible only to other authenticated JupyterHub users.

Please take a look: https://github.com/ideonate/cdsdashboards

**Comment by sntgluca** [comment]
Hi, thanks to @danlester for his work on cdsdasboards and [jhsingle-native-proxy](https://github.com/ideonate/jhsingle-native-proxy)!
This is indeed a nice way to approach the problem.

As a reference, a longer discussion can be found in  https://github.com/voila-dashboards/voila/issues/112

I am going to close the issue.
