### ISSUE TITLE
Single-User-Server-specific configuration parameters

### ISSUE THREAD

**Issue by spitz-dan-l** [jupyterhub/jupyterhub#300]
Hello,

I have a use-case for Jupyterhub that I'm not sure how to implement.

I'm using Github Oauth to authorize users and DockerSpawner to spawn their Single User Servers. In my application, each user can be a member on multiple projects at once. I'd like to make it possible for a single user to access a different Single User Server for each project. I'd have the Spawner configure the server differently depending on which project it's for.

My question- is the above possible without creating a separate Hub for each project? Is there a way for the hub to accept a parameter - the project ID - which it passes along to the Authenticator and Spawner?

Thanks!

**Comment by minrk** [comment]
It's not possible right now, but we are investigating different collaboration models. [SageMathCloud](https://cloud.sagemath.com/) might provide the model you are after.

**Comment by spitz-dan-l** [comment]
Gotcha, thanks.

In lieu of per-(project X user) Single User Servers, I'd like to give my Single User Servers push-access via my Github Application. To do that I think I'd need to have my Spawner set the user's github access token as an environment variable in newly created containers. It looks like a recent [commit](https://github.com/jupyter/jupyterhub/commit/a451f11cd3541d0e4ae342a9c8e14e0406b24890) gives the spawner access to the authenticator, which I can use to get the access token. It looks like I'll need to extend both DockerSpawner and GitHubOAuthenticator to make it work.

Do you know if anyone else has tried to do anything like this?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
