### ISSUE TITLE
Deploying Jupyterhub on AWS EKS

### ISSUE THREAD

**Issue by vagarwal77** [jupyterhub/jupyterhub#3000]
We have spend around a week to deploy JupyterHub on AWS EKS Kubernetes and we are getting one form or another issue. 
I have tried to deployed exact below Docker file and also various combination of pip install of jupyterhub and all without much success. 
https://github.com/jupyterhub/jupyterhub/blob/master/Dockerfile

I think i am missing some thing very basic which lots of folks many have already acheived... 

Please suggest the steps to deploy JupyterHob on AWS EKS using Docker file with step by step process... I would really appreciate it!!

**Comment by manics** [comment]
There's a project dedicated to deploying JupyterHub on Kubernetes: https://zero-to-jupyterhub.readthedocs.io/
If that doesn't help would you mind asking on our [shared Discourse forum](https://discourse.jupyter.org/) instead? Thanks!
