### ISSUE TITLE
No services dropdown on the admin page

### ISSUE THREAD

**Issue by jtpio** [jupyterhub/jupyterhub#3003]
#### Expected behaviour

On the admin page, clicking on `Services` in the nav bar should show the list of services.

#### Actual behaviour

![services-admin-page](https://user-images.githubusercontent.com/591645/77754009-d0120280-702a-11ea-958d-59fb399ae651.gif)

It might be because the click event on the `Services` item in the navigation bar is being intercepted.

### How to reproduce

- Have one JupyterHub managed service running
- Go to the `Admin` page
- Click on `Services`

### Your personal set up

- OS: Ubuntu 19.10
- Version: JupyterHub 1.1.0
- Browser: Latest Firefox and Chromium 
- Configuration: Hub running with one managed service locally

**Comment by shivasheeshyadav** [comment]
Hi @jtpio @GeorgianaElena 
I would like to work on this issue. Please assign it to me.
