### ISSUE TITLE
Is api authorization after Github OAuth based login also cookie based?

### ISSUE THREAD

**Issue by episodeyang** [jupyterhub/jupyterhub#301]
Hi,

I am thinking about trying to get a web-app client to connect with JupyterHub securely. Since the app is going to be at a different domain name, cookie based authentication wouldn't work. 

The api end points are authorized after the OAuth authentication step. Are these api end points authorized with cookies the same way as the PAM? 

Thanks in advance for the answers! This will likely save me a few hours of time.

Ge

**Comment by minrk** [comment]
JupyterHub's API can be used with either an API token or a cookie. The single-user servers JuptyerHub spawns can only use cookie auth.

**Comment by rjsteinert** [comment]
> The single-user servers JuptyerHub spawns can only use cookie auth.

Is that auth requirement baked into the notebook server or configurable-http-proxy? For example, when user `mike` creates a new notebook at `/user/mike/notebooks/Untitled1.ipynb`. I can see on `netstat` that a whole bunch more ports are now claimed. Opening up an incognito window and going to `/user/mike/notebooks/Untitled1.ipynb` results in redirection to `/hub/login`. At what layer is the logic for that redirect decision happening?
