### ISSUE TITLE
Use web-hook to register when single-user servers start

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#302]
webhook callback with connection info:

``` python
{
  'port': 1234,
  'host': 'https://snet-host',
  'username': 'whoami',
}
```

**PRO:** removes the need for Spawners to know the IP of the server they are starting (can be tricky with batch services like PBS)
**CON:** removes the _ability_ for Spawners to specify the IP (can be tricky for single-user to know its own IP relative to the Hub

To get the best of both, there might be a way to let the Spawner specify the IP that the SU server will send in the callback.

/cc @Cadair 

@jhamrick @ssanderson @zonca have you encountered a case where it was annoying/inconvenient to know the IP of the server in the Spawner instead of providing that information from the SU server itself?

**Comment by rgbkrk** [comment]
For the Docker cases, we'll always know the IP, port of the server launched. The single user server won't know the IP unless we pass it in (or run it with `--net=host`, which we wouldn't want to do).

**Comment by minrk** [comment]
That's what I was afraid of. It's at least as likely that the Spawner knows what the IP should be as it is that it doesn't.

The other advantage of the webhook is that it removes a poll from the system, so the Hub is idle while it is waiting for the server to come up.

**Comment by rgbkrk** [comment]
I'm certainly a fan of it and I think we can use it even if the payload is just the user name. For both tmpnb and jupyterhub this can be used.

**Comment by zonca** [comment]
thanks @minrk, for interfacing with PBS this is very useful!

**Comment by ssanderson** [comment]
@minrk how does this interact with something like boot2docker where I have the Hub and Proxy running on my machine (e.g. on OSX), but I'm spawning containers whose IP is a VirtualBox VM on my machine?

**Comment by minrk** [comment]
@ssanderson I think you are going to have to get that information and specify it in your Spawner. It's clear that there are *at least* cases where the spawner or the nbserver know the IP and not the other, so both must be supported.

**Comment by willingc** [comment]
@minrk Leaving this issue open since it seems there is still work to be done. Correct?

**Comment by minrk** [comment]
yes

**Comment by consideRatio** [comment]
issue triage: I think this may be a relevant idea, but it hasn't been evaluated for a very long time now. Close?
