### ISSUE TITLE
Last Activity always shows time within 10 minutes

### ISSUE THREAD

**Issue by steelcup** [jupyterhub/jupyterhub#3029]
hub version: 1.1.0

manually created some bot users in the admin page, and started them.  none of the user ever logged in or has any activity.   After a few hours, the Last Activity column still shows couple minutes ago or a few seconds ago.

**Comment by steelcup** [comment]
the notebook sever is configured by using jupyterhub-yarnspawner.

**Comment by manics** [comment]
Thanks for the report. Would you mind trying to reproduce this with one of the other spawners, e.g. the ones that are built-in to JupyterHub, or DockerSpawner? Yarn adds some complexity, and this will help to narrow down whether the bug is in JupyterHub or yarnspawner.

**Comment by steelcup** [comment]
I only have the setup for yarn spawner.  This worked before on hub version 0.9x, but not any more after updated to the latest 1.1.0.  spawner versions are the same 0.4.0

**Comment by betatim** [comment]
Do you run the classic notebook or jupyterlab when you spawn users?

**Comment by steelcup** [comment]
I have jupyterlab version 1.2.11

**Comment by betatim** [comment]
Can you try with classic notebook?
