### ISSUE TITLE
hub taking lots of memory during startup

### ISSUE THREAD

**Issue by steelcup** [jupyterhub/jupyterhub#3030]
### Bug description
hub version: 1.1.0  with postgresql configured.   When there are 100 live notebook servers, kill the hub server, and start it again.   Hub consumes about 19G memory during the starting up time (within the first minute), and then back to normal (between a few hundred MB to 3GB)
and the memory seems linear to the number of live notebook servers.  (about 200MB per server)

#### Expected behaviour
hub should take normal memory usage like within couple GB regardless the number of live notebook servers.   

### How to reproduce
use admin page to create 100 users, and start them all.   kill and start the hub server to see the memory usage.

### Your personal set up
hub is running on linux centos 6.9
notebook server spawner is jupyterhub-yarnspwaner 0.4.0

**Comment by steelcup** [comment]
during the starting up, hub create 100 yarnspawner
(file app.py) f = asyncio.ensure_future(check_spawner(user, spawner.name, spawner))

each yarnspawner need to invoke yarn java libraries that took lots of memory.   We should limit the number thread/tasks used by asyncio to avoid out of memory when lots of running notebook servers.

**Comment by manics** [comment]
It sounds like this is an issue with yarnspawner. If you can reproduce it with one of the built-in JupyterHub spawners please open a new issue.
