### ISSUE TITLE
At least one item in the documentation does not render properly

### ISSUE THREAD

**Issue by 1kastner** [jupyterhub/jupyterhub#3033]
### Bug description
Visit https://jupyterhub.readthedocs.io/en/stable/getting-started/authenticators-users-basics.html#use-dummyauthenticator-for-testing and read `The :class:~jupyterhub.auth.DummyAuthenticator is a simple authenticator that allows f`

#### Expected behaviour
Beautifully rendered text.

#### Actual behaviour
Glibberish in the created documentation

**Comment by manics** [comment]
This was fixed, if you see any further problems please open a new issue (or a PR if you're able to!)
