### ISSUE TITLE
Figure out why the "request info" bot doesn't trigger in this repository

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/jupyterhub#3034]

**Comment by GeorgianaElena** [comment]
Yes, it should :confused:
Do you remember if the request you accepted was for all the repositories?

**Comment by GeorgianaElena** [comment]
Can you please click the `configure` button here https://github.com/apps/request-info from the org account to see the repositories configured?

**Comment by choldgraf** [comment]
![image](https://user-images.githubusercontent.com/1839645/80732207-d7607c00-8ac0-11ea-8129-c7b6c1018511.png)

**Comment by choldgraf** [comment]
maybe it only works for issues that don't use an issue template or something?

**Comment by manics** [comment]
I've just added it to my test-bots repo: https://github.com/manicstreetpreacher/test-bots/issues/6

**Comment by manics** [comment]
https://github.com/behaviorbot/request-info/blob/d3a5fb72f461ee43f2e664119528deac6f36f25e/lib/IssueBodyChecker.js#L53-L77
The bot checks for a missing body or an unmodified issue template.

**Comment by manics** [comment]
Do we still want this?

**Comment by choldgraf** [comment]
Good question, I'll defer to @GeorgianaElena , happy to close this if it's not something we're acting on

**Comment by manics** [comment]
Closing.....
