### ISSUE TITLE
Update published docs on readthedocs.io

### ISSUE THREAD

**Issue by holgersson32644** [jupyterhub/jupyterhub#3036]
Hi, I stumbled over a bug resp. mistake in your documentation.

### Bug description
Your setup documentation contains call of

```sudo echo something > file```

which is ..well..entirely wrong. sudo echo will write to stdout, then the redirection with ">" will write it with user rights and this will fail as this example wants to add a debian repo to a location where only root can write.

This mistake is within the step "Add Debian repo" in in https://jupyterhub.readthedocs.io/en/stable/installation-guide-hard.html.

#### Expected behaviour

Use something like
```echo | sudo tee```
or
 ```sudo sh -c "echo foo > file"```.

In case it's already fixed and I oversaw it please update the readthedocs manual.

kind regards,
Nils

**Comment by betatim** [comment]
The source of that documentation page is https://github.com/jupyterhub/jupyterhub/blob/master/docs/source/installation-guide-hard.md

A PR to fix the command would be welcome.

**Comment by holgersson32644** [comment]
Hi @betatim, 

your link shows it was fixed in January 2020 by commit b183c9773f6267ff6930af26c5f56d633cd9888, but obviously the docs aren't published yet.

Therefore I change the title.

BTW, even the edit-this-page link is broken inside the docs: https://github.com/jupyterhub/jupyterhub/edit/3663d7c8fcba2118dd469a8a4cca540cc63a39cf//installation-guide-hard.md is linked which leads to a 404 error.

**Comment by betatim** [comment]
Could this be the difference between https://jupyterhub.readthedocs.io/en/latest/installation-guide-hard.html (latest) and the stable docs? `latest` shows what is on master and `stable` shows the last release. Though off the top of my head there was a release made after January 2020.

The broken "edit on github" link should be its own issue I think. Definitely needs fixing.

**Comment by sumitmcc** [comment]
I assume this is fixed. Is there any more work required for this? 
![image](https://user-images.githubusercontent.com/21320647/81909689-93a16280-95e8-11ea-9294-17ba95f93a4a.png)

**Comment by holgersson32644** [comment]
Sorry, I lost track of this issue. As of 2021-02-18 (today) it's fixed both in stable and of course in latest, too. :-)
