### ISSUE TITLE
Make admin page a full-on react app

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#3039]
### Proposed change

JupyterHub pages started out as *extremely* basic: just a start and stop button. They are getting more <del>complex</del> feature-rich with things like named servers, profiles, options forms, etc.

I think it's probably time that we move to a real UI framework, and I think react is a really good fit since we are mostly displaying tables of simple data types (list of users and running servers on admin, list of spawners on named-servers, etc.).

The admin page is currently our most complex page, with pagination, users, sorting, etc. I think this is probably a great place to start with rewriting as a react app with data-flow of users to display. This means, among other things, that things like pagination, etc. need to move to javascript. The HTML template can be greatly simplified and the only relevant Python code is the query for the user list (likely needs pagination in the REST API user list).

### Alternative options

- Use another js framework
- Leave it alone

### Who would use this feature?

JupyterHub admins, especially those with lots of users

### How much effort will adding it take?

A moderate amount of effort to:

1. add react as a js dependency
2. rework the admin Jinja template to do much less
3. create react app from scratch to regenerate ~the same HTML we have now

### Who can do this work?

Javascript/React/frontend developers, with some REST API experience.

**Comment by twalcari** [comment]
I'm generally in favor of adding a modern frontend JS framework. The JupyterHub instance that I maintain at Ghent University has a fairly extensive Spawner options page, which is currently using jQuery for some dynamic features. Using React in other projects, it always feels like a step back when I need to _fight_ with jQuery to implement certain features.

One important note on using React is that you generally want to use Babel for transpiling the React JS code to vanilla JS for a few reasons:
- React uses JSX to define visual elements, which is not supported by browsers natively
- React is generally used with ES6 or higher, which is not supported by IE11 for instance. Otherwise your code gets unnecessarily complex, and a lot of the examples available won't work [without adapting them](https://reactjs.org/docs/react-without-es6.html).

Bringing in Babel means that we will need to bring in Webpack and the rest of the JS-ecosystem. I've already successfully integrated this with Flask by using [flask-webpack-loader](https://pypi.org/project/flask-webpack-loader/) which makes this relatively painless. My 5-second search doesn't show a one-on-one equivalent for Tornado, so we might need to implement that first.

I'm not familiar enough with Vue to do any assessment if it is usable without Babel/Webpack/etc.

**Comment by betatim** [comment]
I support the idea of making the admin page more of an "app" as a way to handle the new features.

One thing that keeps appearing on my radar more and more are libraries like https://stimulusjs.org/ (in combination with https://github.com/turbolinks/turbolinks for full "SPA feeling"). I like the idea of Stimulus as "serve plain HTML and sprinkle some JS on top". There are a few libraries like this, but I can't (re)find them in my history right now. I think one is called Adrenalie or some such.

A reason to adopt a tool like this instead of react is that it would increase the number of people who can actively work on the admin panel app. A reason not to use it is that there are so many react developers that would have to learn a new thing to contribute here. I've not used Stimulus for anything beyond "tutorial level" work. I thin pypi.org uses it though. So this is more a point for consideration/get feedback on instead of "lets use it".

**Comment by minrk** [comment]
I definitely agree that adopting react (or any framework, probably) means adopting webpack as well. I think react plus `webpack --watch` is a fairly tolerable development experience for a project with our small scope. Tornado doesn't need to know anything about it since it's just a static file. I have used in-browser babel for jsx in one project (I don't even remember which one) which I found much nicer as a Python developer who bristles at compilation steps, but presumably not the right approach for production. Switching to react components may complicate some of our template customization features, so we'll need to keep an eye on that.

I would guess the number of people who can actively work on a react/jsx project would be higher than stimulus/turbolinks or just about anything else these days, but I'm not sure. This is part of why I strongly want us to *not* pick up Typescript here, which I have found to be a major source of resistance for new contributors (nteract or jupyterlab folks may disagree here).

I went with "no framework" because for the first few years, all we did was show two buttons and one simple list and a js framework is vast overkill for that. That's not so true anymore! So the tradeoffs are different now, and admin is our most complex page with the most view/input options (sorting, pagination, grouping) so a good place to see benefits.

We could also start small and do a lighter page, like the token generation page that does close to nothing. That would shift the task to being ~all setting up the react/webpack build pipeline (and tests!), plus a token (heh) page to test on.

> Using React in other projects, it always feels like a step back when I need to fight with jQuery to implement certain features.

You should already be free to use react in your custom spawn form if you want to, I think. You just need to load the react code on the page yourself.

**Comment by manics** [comment]
Is there any scope for splitting the frontend web-UI/app from the backend JupyterHub API into a new repo? Which I guess is another way of saying could someone write an independent web-client that has all the funtionality of the current web-interface but uses only JupyterHub API calls?

**Comment by twalcari** [comment]
@minrk Your approach means that we'll need to check in a compiled version of the JS-code. The big plus for this approach is that you can still checkout the JupyterHub-repo and start the JupyterHub-process without any changes. However, we need to be careful that the sourcecode and compiled version always match each other. Maybe we should add a testsuite in Travis that compiles the sourcecode and compares this to the compiled version to verify that it's the same? While doable, we'll need to keep a close eye on potential problems with mismatched versions of NodeJS on the developers machine vs. Travis creating inconsistent end results and thus a failing test.

@manics I don't think such a big bang approach is doable nor necessary. The frontend of JupyterHub is quite limited as-is, and having potentially multiple frontends to choose from has no added value whatsoever.

**Comment by minrk** [comment]
> Your approach means that we'll need to check in a compiled version of the JS-code. 

It does not. It means we need to include the compiled js in releases, but not the repo. We already do this in other Jupyter projects with a web UI (jupyterlab, notebook, etc.). There's already a javascript build step in jupyterhub (less->css and bundling js dependencies). Adopting js compilation would not have a significant impact on that.

> Is there any scope for splitting the frontend web-UI/app from the backend JupyterHub API into a new repo?

A case can be made for creating a proper npm package to organize the js, but I wouldn't make a new repo. The trend these days, especially in js-land, is toward "monorepos" as more maintainable, even if multiple packages in the repo are versioned independently. One could do experiments this way, though. I suspect the first thing one will run into is that the paging/sorting/etc. currently implemented in admin is *not* supported by the API! So that's something we'll need to add (and should anyway), regardless.

**Comment by twalcari** [comment]
> There's already a javascript build step in jupyterhub (less->css and bundling js dependencies). Adopting js compilation would not have a significant impact on that.

Okay, I haven't had to dive into that part of the code yet, so I was unaware. After some digging around I now understand that `npm` is now already executed as part of building the `.whl` for JupyterHub, which is very neat! Thanks for explaining!

**Comment by Amran2k16** [comment]
How would one go about replacing the current JINJA templates with a REACT app. My understanding of how the Jupyterhub system works is fairly limited, what steps can I take to better understand the current process of serving HTML files to users?

**Comment by twalcari** [comment]
> How would one go about replacing the current JINJA templates with a REACT app. 

React just needs a reference to an element in the DOM to attach to. So it suffices to add an empty div and reference it in the Javascript that initializes the React-component.

eg.:

```html
<div id="xyz-container"></div>
```

and

```javascript
class Quiz extends React.Component { 
    render() {
       return (<h1>Hello world!</h1>);
    }
}
ReactDOM.render(<ComponentXYZ />, document.querySelector('#xyz-container'));
```
Tornado doesn't need to know anything about React. It just needs to output an empty ```<div>```

**Comment by Amran2k16** [comment]
Ah yes that makes alot of sense. Am I right in assuming that this JS file with the react component would have to live inside of the static/js directory? I've tried implementing per your suggestion, but facing issues  "ReactDOM" is not defined, and can't do any imports inside of the JS file either since its on the browser. 

I've tried following the react "Add React to existing projects" but can't easily see how to integrate it with this project.

**Comment by gabber12** [comment]
Also a major decision needed here would be whether to go with server-side rendering with react or not.

Wont the whole jinja templating be replaced with ajax calls?

**Comment by minrk** [comment]
> Also a major decision needed here would be whether to go with server-side rendering with react or not.

Definitely client side.

> Won't the whole jinja templating be replaced with ajax calls?

Not *entirely*, in that the basic frame will still come from a jinja template, but the main table of data will be moved to react, eliminating the iteration, macros, etc. from jinja. Yes, table data will instead come from REST (`GET /users`) which will need to support the query/sort/page parameters currently only implemented in the admin page handlers.

> what steps can I take to better understand the current process of serving HTML files to users?

The bulk of the HTML is created with a jinja template [in share/jupyterhub/templates/admin.html](https://github.com/jupyterhub/jupyterhub/blob/8a3790b01ff944c453ffcc0486149e2a58ffabea/share/jupyterhub/templates/admin.html). The user list is populated and passed to the template [in the AdminHandler](https://github.com/jupyterhub/jupyterhub/blob/8a3790b01ff944c453ffcc0486149e2a58ffabea/jupyterhub/handlers/pages.py#L469-L502).

**Comment by Amran2k16** [comment]
Whilst it does sound like a really large volume of work, perhaps Manics suggestion of splitting the front-end to its own package/repo is a good approach. This will allow more API(fication) of the central HUB and pay dividends in the long run as and when the app gets more complex. 

It also opens up this project to a huge network of additional REACT developers who can work exclusively on the front-end  (if react is the chosen framework). Without having to know all the ins and outs of tornado web apps e.t.c

**Comment by tuxsisir** [comment]
how about using Vue for the overall frontend? any thoughts with vue?

**Comment by WJY-norainu** [comment]
Hello. This seems like an interesting task but may I clarify if this means we want to entirely replace jinja template with bundled/transpiled react app or we want to embed react components into the jinja template?

**Comment by nabarber** [comment]
Hey all, I have a couple questions about this issue. Assuming the end result would be a bundled react app pulled in through the existing template HTML, how would you guys recommend handling the Jupyterhub API requests? I'm guessing we don't want to use CORS. Instead should the template rendering code in AdminHandler be transitioned into a communication layer between the React front end and the API?

While on the subject of the API, I understand that to view the admin page, a user must already have a valid session token. Will that token need to be passed into the React code for future API requests, and if so where would that transaction happen?

Also, any preferences on directory structure / where the untranspiled React code should live?

**Comment by nabarber** [comment]
Hey all, currently working on this issue and have most of the UI work / integration done. Do we want to initially wrap this up as a hub managed service until it gets merged upstream or would it be best to start a PR with it fully integrated as the `/admin` endpoint?

**Comment by naatebarber** [comment]
Hey everyone, we've developed a react based JupyterHub admin front-end that should fit this issue. Currently it's packaged as a Hub service/extension and can be enabled through the config, but it'd also be easy to implement in the hub itself with a couple edits to the templates. Feel free to check it out and recommend edits / next steps: 
[https://github.com/MetroStar/jh-admin-dashboard](https://github.com/MetroStar/jh-admin-dashboard)

I'd also be happy to open a PR to add these updates to the Hub if there's interest, please feel free to reach out and comment
[here](https://github.com/MetroStar/jh-admin-dashboard/issues/4).
