### ISSUE TITLE
Cull-idle doesn't seem to work

### ISSUE THREAD

**Issue by eosantigen** [jupyterhub/jupyterhub#3044]
### Bug description
I have followed exactly the steps [here](https://github.com/jupyterhub/jupyterhub/tree/master/examples/cull-idle) .

#### Expected behaviour
When the relevant seconds pass as defined in the jupyterhub_config.py , the cull-idle service should stop the idle server of each user. So that when going to navigate the page, no terminals should be able to be started, no notebooks etc, unless the user explicitly presses Start server . _(am I wrong?)_

#### Actual behaviour
When the relevant seconds pass, all that happens is this output in the log:
`200 GET /hub/api/users (cull-idle@127.0.0.1) 10.47ms`
And with this the server continues running normally, meaning I can start a terminal, make files etc.

### Your personal set up
 - Version: 
```
JupyterHub version 1.1.0
oauthenticator.generic.GenericOAuthenticator-0.11.0
Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.1.0
Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.1.0
```
 - Configuration:

```
import sys
c.JupyterHub.last_activity_interval = 300
c.GenericOAuthenticator.auth_refresh_age = 800
c.JupyterHub.shutdown_on_logout = True
from oauthenticator.generic import GenericOAuthenticator
c.JupyterHub.authenticator_class = GenericOAuthenticator
c.Authenticator.enable_auth_state = True
c.LocalGenericOAuthenticator.refresh_pre_spawn = True
c.LocalGenericOAuthenticator.pre_spawn_start

c.JupyterHub.services = [{
    'name': 'cull-idle',
    'admin': True,
    'command': [sys.executable, '/home/elena/cull_idle_servers.py', '--timeout=600'],
    }
]
```
_Running as root ._

**Comment by manics** [comment]
If you leave the server running without any interaction does it eventually get culled?

**Comment by betatim** [comment]
The "activity" of a notebook server does not get updated "live". It only gets refreshed every 10s (or so). This means for very short cull times you have to wait a bit longer. I don't remember the situation exactly but if you are running Jupyter Lab then JupyterHub's activity tracking can't detect "inactivity" as lab is always polling as long as the user's tab is open. So you first need to close your browser tab.

**Comment by eosantigen** [comment]
@manics That's what i'm saying, that it doesn't. It keeps running and never gets stopped. But yes, it does get culled if I close the tab! - but is this normal? The user may not always close the tab and I need it to be culled anyways, so that it  gets ome new information fetched from some server into the spawner environment. (many thanks)

**Comment by eosantigen** [comment]
Closing issue since a solution has been found and I rtfm :)
