### ISSUE TITLE
Invalid username or password

### ISSUE THREAD

**Issue by LiuChiennan** [jupyterhub/jupyterhub#3049]
I installed jupyterhub step by step following the instructions in https://jupyterhub.readthedocs.io/en/stable/installation-guide-hard.html
And after I finish the part 1, I open the link myurl:8000, it works,
![image](https://user-images.githubusercontent.com/26686108/82121689-7e336080-97c1-11ea-9fd7-9484472eaccf.png)
However, if I want to login, it always says invalid username or password, as follows, 
![image](https://user-images.githubusercontent.com/26686108/82121741-dd917080-97c1-11ea-8e93-acdc389ad636.png)
I have tried all the system users and I think my username and password are valid. I strictly follow the instructions of that link, and the Authenticator is the default PAM. 

For my system, it is centos 7.6 , anyone knows why

By the way, I login the system as root, so I execute all the instructions as root

**Comment by vavabramov** [comment]
@LiuChiennan have you managed to fix the issue?

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/aws-ec2-install-of-jupyterhub/7904/1

**Comment by StashOfCode** [comment]
@meeseeksmachine, @LiuChiennan how did you solve the issue? I don't have a password for an ssh user either
