### ISSUE TITLE
Use case for c.JupyterHub.api_tokens - service that identifies as a user

### ISSUE THREAD

**Issue by TeriForey** [jupyterhub/jupyterhub#3051]
### Proposed change

I have a use case for keeping api_tokens, and as recommended wanted to let you know. I'm building a service that embeds jupyter notebook within an iframe, and I'm using jupyterhub with dockerspawner to manage the creation of notebook servers per user. All authentication occurs within my own service and I don't wish to duplicate this within jupyterhub, not least because it means connecting to a database running on a different host that I wish to keep as secure as possible. I'm therefore creating a token for each user when they want to open a notebook file, and using that within the iframe to authenticate their request. Currently only an admin user can create tokens via the API, a service isn't able to do this. I've therefore set my service up as an admin user within JupyterHub, and my service therefore has all the permissions needed to create new users and their respective tokens. 

This functionality works really well within my context, and I wouldn't wish it to be deprecated. 

### Alternative options

The alternative would be to allow external services the permissions to create users, and tokens via the API. 

### Who would use this feature?

I'm not sure how many services are embedding Jupyter in this way so not sure how many others this would affect/apply to.

### How much effort will adding it take?

Little effort, as it just requires not deprecating api_tokens.

### Who can do this work?

Anyone should be able to do this.

**Comment by minrk** [comment]
> Currently only an admin user can create tokens via the API, a service isn't able to do this

services can be admins, too:

```python
c.JupyterHub.services = [
    {
        "name": "my-service",
        "api_token": "abc123...",
        "admin": True,
    },
]
```

This should be equivalent to:


```python
c.JupyterHub.admin_users = {'my-service',}
c.JupyterHub.api_tokens = {'abc123...': 'my-service'}
```

but will create an admin service instead of an admin user. The permissions are the same, other than the ability to start its own notebook server.

I opened #3055 to update the docs to point to how to upgrade to the services config. Can you check if it works for your use case?
