### ISSUE TITLE
Use idle culler from jupyterhub-idle-culler package 

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/jupyterhub#3052]
### Proposed change

Now that the idle culler is a [standalone package](https://github.com/jupyterhub/jupyterhub-idle-culler), we shouldn't maintain a copy of it in JupyterHub, instead use the package directly :sparkles: 

### Alternative options

Keep it as it is. This means we'll loose all the great features and fixes from https://github.com/jupyterhub/jupyterhub-idle-culler.

### Who would use this feature?

Maintainers and contributors alike as it will be easier to change and improve it for every project that uses it instead of having it split across multiple repos.

### How much effort will adding it take?

@yuvipanda's PRs in [Z2JH](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1648) and [TLJH](https://github.com/jupyterhub/the-littlest-jupyterhub/pull/559) are be a great place to start and look for guidance.

### Who can do this work?

I believe this would be a great place to start for people wanting to make their first contribution to JupyterHub and of great help for the community :heart:

**Comment by harshu1470** [comment]
Hey I'm Harshit, I want to work on it if anyone is not assigned to it

**Comment by GeorgianaElena** [comment]
Welcome @harshu1470 :wave:

> I want to work on it if anyone is not assigned to it

It would be lovely :sparkles:  I don't think anybody is working on this right now.
If you have any questions about it, don't hesitate to ask.

**Comment by GeorgianaElena** [comment]
Closed in https://github.com/jupyterhub/jupyterhub/pull/3114
