### ISSUE TITLE
Include Default Config Files and Documented CLI Options in docs

### ISSUE THREAD

**Issue by tarfeef101** [jupyterhub/jupyterhub#3066]
### Proposed change
Many people deploy this into containerized environments, and as such generating a config file to modify or running `jupyterhub --help-all` to get the options when starting the server is a time-consuming and non-trivial task depending on your environment. It would be great if the repo (or some referenced location) could host a default `jupyterhub_config.py` users could modify without having to create an environment in which to install, generate, and extract the file. Similarly, it'd be great if the docs for configuration would just list the options for starting the process rather than saying "run --help".

### Alternative options
As mentioned above, in interactive environments this is easy to deal with and a non-issue, but when writing a dockerfile, working on a thin client before deploying to a cluster that costs you money to access, etc. these are inconvenient, time-consuming, and potentially have a cost associated. Since these aren't exactly tall asks, I think this is pretty reasonable.

### Who would use this feature?
Anyone creating a configuration for their deployment as code who isn't setting it up interactively, which I have to imagine is most people.

**Comment by minrk** [comment]
Automatically including the output of `jupyterhub --generate-config` and `jupyterhub --help-all` as part of the docs build sounds like a good idea to me. We'll probably want to do some post-processing to convert some absolute paths like the cwd and home to e.g. `.` and `~` (or be fancy and define these as variables in the config file and use them appropriately)
