### ISSUE TITLE
Jupyterhub spawn fails - tornado.web.HTTPError: HTTP 500: Internal Server Error

### ISSUE THREAD

**Issue by mvignesh1990** [jupyterhub/jupyterhub#3094]
### Bug description

I have installed jupyter hub development install using the following documentation:
https://jupyterhub.readthedocs.io/en/stable/contributing/setup.html

The python3 installed is a python alt install and not a virtual env via conda. When I start the hub in a conda environment, i am able to login, do a notebook server spawn and perform python operations.
In the python3 alt install env, when i start the hub, the spawn fails with the following error:
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /home/myuser/jupyterhub/jupyterhub/handlers/base.py:741> exception=HTTPError()>
Traceback (most recent call last):
  File "/home/myuser/jupyterhub/jupyterhub/handlers/base.py", line 939, in spawn_single_user
    timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/myuser/jupyterhub/jupyterhub/handlers/base.py", line 972, in spawn_single_user
    % (status, spawner._log_name),
tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=1]. The logs for admin may contain details.)
^C[C 2020-06-17 19:12:32.290 JupyterHub app:2739] Received signal SIGINT, initiating shutdown...
[E 2020-06-17 19:12:32.292 JupyterHub user:706] Unhandled error waiting for admin's server to show up at http://127.0.0.1:60014/user/admin/:
[E 2020-06-17 19:12:32.330 JupyterHub web:1792] Uncaught exception GET /hub/api/users/admin/server/progress (10.61.51.140)
    HTTPServerRequest(protocol='http', host='10.64.17.14:8080', method='GET', uri='/hub/api/users/admin/server/progress', version='HTTP/1.1', remote_ip='10.61.51.140')
    Traceback (most recent call last):
      File "/home/myuser/.local/lib/python3.6/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/home/myuser/jupyterhub/jupyterhub/apihandlers/users.py", line 604, in get
        await asyncio.wait([spawn_future])
      File "/usr/lib64/python3.6/asyncio/tasks.py", line 313, in wait
        return (yield from _wait(fs, timeout, return_when, loop))
      File "/usr/lib64/python3.6/asyncio/tasks.py", line 396, in _wait
        yield from waiter
    concurrent.futures._base.CancelledError

#### Expected behaviour
Jupyterhub should be able to spawn the single-user servers.

#### Actual behaviour
Spawn fails with the above error.

### How to reproduce

Install jupyterhub on python3 alt install env.
Start jupyterhub as: jupyterhub --ip <ip> --port <port> -f jupyterhub_config.py
Login using a dummy user and start the server.

### Your personal set up

 - OS: RHEL
 - Version: 1.2.0dev
 - Configuration: 8 core, 64gb

**Comment by GeorgianaElena** [comment]
Hi @mvignesh1990 :wave: 

The [Discourse forum](https://discourse.jupyter.org/) is the best place to ask for guidance and exchange ideas with the community.
We are are trying to keep GitHub issues for bug reports and feature requests and encourage people to ask questions on the forum.

Thank you :heart:
