### ISSUE TITLE
node_selector ignored after failed spawn

### ISSUE THREAD

**Issue by romanzac** [jupyterhub/jupyterhub#3095]
### Bug description
Hello, I have a problem with behavior related to node_selector. 

1) When I first request a server with GPU and GPU resource is not available, spawn process will timeout/fail. This is expected.
2) When I try again to select profile without GPU requirement, my spawn process fails again even thou there are servers with resources available. 

-----
Your server is starting up.

You will be redirected automatically when it's ready for you.

100% Complete
Spawn failed: pod/jupyter-arc did not start in 30 seconds!

Event log
Server requested
2020-06-18 05:43:14+00:00 [Warning] 0/9 nodes are available: 4 Insufficient nvidia.com/gpu, 5 node(s) didn't match node selector.
Spawn failed: pod/jupyter-arc did not start in 30 seconds!
----

 
#### Expected behaviour

I wish user who cannot spawn server due to resource constraints could still spawn another server (to do something else) and wait till resource would be released.

### Your personal set up
Kubernetes: 1.16.6
deployed	jupyterhub-0.9.0  version          	1.1.0

 - Configuration:
profileList:
    - display_name: "Bioinformatics Environment"
      description: "Sample Jupyter notebooks and necessary tools for bioinformatics."
      default: true
      kubespawner_override:
        image: registry:8443/bioinf-jupyter-k8s:1.0.17
        node_selector:
          podGroup: "cpu-compute"
            
    - display_name: "Bioinformatics Environment 1x GPU"
      description: "Sample Jupyter notebooks and necessary tools for bioinformatics - GPU support."
      kubespawner_override:
        image: registry:8443/bioinf-jupyter-k8s-gpu:1.0.1
        node_selector:
          qpodGroup: "gpu-compute"
        extra_resource_limits:
          nvidia.com/gpu: "1"

**Comment by GeorgianaElena** [comment]
Hi @romanzac :wave:

The [Discourse forum](https://discourse.jupyter.org/) is the best place to ask for guidance and exchange ideas with the community.
We are are trying to keep GitHub issues for bug reports and feature requests, and encourage people to ask questions on the forum.

Thank you :heart:
