### ISSUE TITLE
Access the Jupyter Notebook by passing the credentials in URL

### ISSUE THREAD

**Issue by sharmaanku** [jupyterhub/jupyterhub#3096]
Hi ,

 I am trying to access the Jupyter Notebook with password less feature or to pass the credentials in url of Jupyter so that user will directly redirected to the notebook page instead of first hit the URL and then manually enter the Credentials .

For e.g. I have jupyter notebook available on my machine and currently it is accessible with url 

    https://localhost:8999

and after hit of URL it landing on to the credential page on which I need to manually enter the required credentials 
But what I was trying to hit the URL    `https://localhost:8999` and it will land to the home screen which containing all the notebooks 
What i was trying to do with the help of this link `https://stackoverflow.com/questions/41159797/how-to-disable-password-request-for-a-jupyter-notebook-session

But this not so much helpful because URL is not accessible and it is alywas generating the new token which tedious to manage 

Is there any simpler way to make the Jupyter notebook accessible directly without entering any manual credentials

**Comment by elgalu** [comment]
Hi! this is the place for JupyterHub issues and you seem to describe a Jupyter Notebook issue (different projects)

The proper place to open this question might be:
https://github.com/jupyter/notebook/issues

Also creating a [new StackOverflow question](https://stackoverflow.com/questions/ask) may increase your chances of an answer.

**Comment by GeorgianaElena** [comment]
Hi @sharmaanku, @elgalu  :wave:
The [Discourse forum](https://discourse.jupyter.org/) is the best place to ask for guidance and exchange ideas with the community.
We are are trying to keep GitHub issues for bug reports and feature requests, so we encourage people to ask questions on the forum.

Thank you :heart:
