### ISSUE TITLE
Text wrap in documentation tables.

### ISSUE THREAD

**Issue by Zsailer** [jupyterhub/jupyterhub#3097]
I caught this in the events schema page: 
https://jupyterhub.readthedocs.io/en/stable/events/server-actions.html

It looks like the new sphinx theme doesn't wrap text in table cells, leading to ultra-wide tables that don't fit on the page. Ideally, we could tables to the width of the page and wrap text as needed. This issue likely belongs in pydata_sphinx_theme, but opening this here to track our own pages.

@choldgraf, do you know how to fix this? I tried to do some digging quickly but didn't make much progress.

**Comment by Zsailer** [comment]
^ This is awesome. I love it. 

Also, a bit surprised this is my first issue on this repo. 😆

**Comment by choldgraf** [comment]
whoahhhh lol that's a big page...

hmmm, I am not quite sure. Can you try re-building the docs on readthedocs first to make sure this isn't a bug that's been squashed in the theme? I don't have admin rights to this repo on RTD

**Comment by choldgraf** [comment]
also ya @GeorgianaElena your bot is awesome

**Comment by Zsailer** [comment]
I also don't have admin rights on RTD. 

But, I did build these docs locally, and I see the same issue. For reference, I had to add custom CSS previously to handle text wrapping in large tables (see [this jupyter/notebook telemetry](https://github.com/yuvipanda/notebook/blob/906e3f583b5de9d5bb7378f51b3b99783b9be52d/docs/source/_static/theme_overrides.css) docs PR).

We'll probably need to add something similar to override the CSS here.

**Comment by choldgraf** [comment]
can you also open an issue in the pydata-sphinx-theme?

**Comment by Zsailer** [comment]
Done! 🚀 

https://github.com/pandas-dev/pydata-sphinx-theme/issues/205

**Comment by manics** [comment]
It looks like this was fixed at some point, https://jupyterhub.readthedocs.io/en/stable/events/server-actions.html looks fine to me:
![image](https://user-images.githubusercontent.com/1644105/169700214-dc60ee1f-4bca-41e0-965b-1046eee5bfe4.png)

(though https://github.com/pydata/pydata-sphinx-theme/issues/205 is still open)
