### ISSUE TITLE
Documentation: Setting up users’ own conda environments

### ISSUE THREAD

**Issue by viniciusferrao** [jupyterhub/jupyterhub#3112]
### Bug description

The documentation about installation per user is a little bit hard to understand for those who aren't familiar with the software and the Python environments scheme.

Specifically the multi-user support with Conda: https://jupyterhub.readthedocs.io/en/stable/installation-guide-hard.html#part-2-conda-environments

#### Expected behaviour

Would be able to follow up the installation procedures and everything works at the end.

#### Actual behaviour

The instructions are misleading so the expected results are missing, probably due to changes that aren't mapped. In my case the system is defaulting to /usr/local even without specifying it. For example:

(base)$ /opt/jupyterhub/bin/python -m ipykernel install --name 'meu-paitom' --display-name "Meu Paitom"
[Errno 13] Permission denied: '/usr/local/share/jupyter/kernels/meu-paitom'

This is following strictly the guidelines on the installation instructions.

(base)$ /opt/jupyterhub/bin/python -m ipykernel install --name 'meu-paitom' --display-name "Meu Paitom" --sys-prefix
[Errno 13] Permission denied: '/opt/jupyterhub/share/jupyter/kernels/meu-paitom'

Here I've tried to change it a little but is doesn't behave as expected.

I understood that it should create the environment on my home folder and not on /opt or /usr/local. So it's missing some information here, and I was unable to proceed.

### How to reproduce

Just follow the instructions on: https://jupyterhub.readthedocs.io/en/stable/installation-guide-hard.html#part-2-conda-environments

### Your personal set up

 - OS:
CentOS Linux 8.2
 - Version:
[root@jupyter kernels]# source /opt/jupyterhub/bin/activate
(jupyterhub) [root@jupyter kernels]# pip list
Package            Version  
------------------ ---------
alembic            1.4.2    
async-generator    1.10     
attrs              19.3.0   
backcall           0.2.0    
bleach             3.1.5    
certifi            2020.6.20
certipy            0.1.3    
cffi               1.14.0   
chardet            3.0.4    
cryptography       2.9.2    
decorator          4.4.2    
defusedxml         0.6.0    
entrypoints        0.3      
idna               2.10     
ipykernel          5.3.0    
ipython            7.16.1   
ipython-genutils   0.2.0    
ipywidgets         7.5.1    
jedi               0.17.1   
Jinja2             2.11.2   
json5              0.9.5    
jsonschema         3.2.0    
jupyter-client     6.1.5    
jupyter-core       4.6.3    
jupyter-telemetry  0.1.0    
jupyterhub         1.1.0    
jupyterlab         2.1.5    
jupyterlab-server  1.1.5    
Mako               1.1.3    
MarkupSafe         1.1.1    
mistune            0.8.4    
nbconvert          5.6.1    
nbformat           5.0.7    
notebook           6.0.3    
oauthlib           3.1.0    
packaging          20.4     
pamela             1.0.0    
pandocfilters      1.4.2    
parso              0.7.0    
pexpect            4.8.0    
pickleshare        0.7.5    
pip                19.2.3   
prometheus-client  0.8.0    
prompt-toolkit     3.0.5    
ptyprocess         0.6.0    
pycparser          2.20     
Pygments           2.6.1    
pyOpenSSL          19.1.0   
pyparsing          2.4.7    
pyrsistent         0.16.0   
python-dateutil    2.8.1    
python-editor      1.0.4    
python-json-logger 0.1.11   
pyzmq              19.0.1   
requests           2.24.0   
ruamel.yaml        0.16.10  
ruamel.yaml.clib   0.2.0    
Send2Trash         1.5.0    
setuptools         41.6.0   
six                1.15.0   
SQLAlchemy         1.3.18   
terminado          0.8.3    
testpath           0.4.4    
tornado            6.0.4    
traitlets          4.3.3    
urllib3            1.25.9   
wcwidth            0.2.5    
webencodings       0.5.1    
wheel              0.34.2   
widgetsnbextension 3.5.1    
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

 - Configuration:
Pretty default, nothing changed from the guide.

**Comment by ShechemKS** [comment]
Same issue faced. Strictly followed the guidelines. Specifically, chose the second method of making the environment visible to Jupyter by running 
`sudo /opt/conda/envs/python/bin/python -m ipykernel install --prefix /usr/local/ --name 'python' --display-name "Python (default)"`

**Comment by Michagogo** [comment]
There’s a mistake in the command - an unprivileged user needs the --user flag. See https://github.com/jupyterhub/jupyterhub-the-hard-way/pull/10

**Comment by viniciusferrao** [comment]
@Michagogo I was running as root. As today the issue still persists.

**Comment by manics** [comment]
Closing, as this now applies to a separate repo (which unfortunately has limited maintenance at the moment)
