### ISSUE TITLE
Jupyterhub is giving site can’t be reached and connection refused error when it is on idle/inactive state for few hours

### ISSUE THREAD

**Issue by Shashideep83** [jupyterhub/jupyterhub#3115]
### Bug description
Jupyterhub is giving site can’t be reached and connection refused error when it is on idle/inactive state.

Checked for these variables if they are enabled by default. But they are commented/not there

```
cull_idle_timeout
shutdown_no_activity_timeout
```

#### Expected behaviour

Jupyterhub should be running without being timed-out. 

#### Actual behaviour

When left out at idle or inactive for a few hours it is throwing connection refused error.

### How to reproduce

installed jupyterhub using this docs: https://jupyterhub.readthedocs.io/en/stable/quickstart.html#installation

Leaving out jupyterhub in idle/inactive state on AWS Ec2 instance for a few hours after launching with command `jupyterhub &`

### Your personal set up

Server Setup : 

 - OS:
 ubuntu 18 (aws ec2)
 - Version:
 1.1.0

**Comment by consideRatio** [comment]
Please verify that JupyterHub is still running and no longer responding, until then I'll go ahead and close this issue with the assumption that it was related to being started in a way (`jupyterhub &` from a shell) that ended up being terminated outside its own control.

I'm not an UNIX expert, but I guess that the way you started JupyterHub from a shell led to this issue, for example by having the shell being killed later due to inactivity or similarly.

**Comment by Shashideep83** [comment]
I can verify that process `jupyterhub` is running and when I access the landing page after a few hours it is going into inactive state. As I mentioned in the `How to reproduce` section I'm using `Jupyterhub &` for starting.

**Comment by consideRatio** [comment]
@Shashideep83 is it correct that you have verified that the JupyterHub process is still running while also giving you connection refused when you try to access it on http(s)://yourdomain.org/hub/home? Could you also clarify what you meant with inactive state?

**Comment by Shashideep83** [comment]
Yes, When I access it on http://yourdomain.org/hub/home. I'm getting connection refused with site can’t be reached error.

**Comment by Shashideep83** [comment]
@consideRatio Can it be reopened ?

**Comment by consideRatio** [comment]
> Closing the notebook tab on the browser after using it for some time and again accessing it after a gap of 4-5 hours.

To understand the issue in detail enough to figure out the issue, please clarify what you mean specifically with "accessing it again", do you mean accessing `/hub/home` again, or do you mean accessing a user session under /user/myusername? Its of technical importance for anyone to understand the issue you experience.

Please provide additional information as well
- logs from the hub for when this happens
- your jupyterhub version
- your jupyterhub configuration or state that its the default configuration without any change

**Comment by Shashideep83** [comment]
![image](https://user-images.githubusercontent.com/39345969/87691251-032dfc80-c7a8-11ea-8f25-e681799f0ce8.png)



if i give `ps -ef | grep jupyterhub` i can see the process running. Also one more error shows up 


`shashi  25260     1  0 15:30 ?        00:00:00 node /home/shashi/miniconda3/envs/jup/bin/configurable-http-proxy --ip  --port 8000 --api-ip 127.0.0.1 --api-port 8001 --error-target http://127.0.0.1:8081/hub/error`

**Comment by consideRatio** [comment]
@Shashideep83 sadly quite a bit more more information would be needed to debug an issue like this.

For example what URL you visited when you got that error, what jupyterhub configuration you have provided, what version of jupyterhub you use, what the JupyterHub logs shows etc.

I'm closing this again to reflect that I think it's too hard to help you pinpoint if this is an actual issue with JupyterHub that we can fix.

**Comment by Shashideep83** [comment]
Okay, i have been capturing the logs and every detail you have asked. Will update in  few hours
