### ISSUE TITLE
How to set the SameSite attribute for cookies

### ISSUE THREAD

**Issue by rowan-m** [jupyterhub/jupyterhub#3117]
### Proposed change

With Chrome 84 going stable, we're restricting cookies to first-party by default by applying the equivalent of `SameSite=Lax` where it's not explicitly specified. Cookies required in a cross-site context must specify `SameSite=None; Secure`. See https://www.chromium.org/updates/same-site

Unfortunately my Python is terrible, so I haven't been able to verify this, but it *looks* as if [`cookie_options`](https://jupyterhub.readthedocs.io/en/stable/api/services.auth.html#jupyterhub.services.auth.HubAuth.cookie_options) may allow you to set the `SameSite` attribute along with the `Secure` attribute.

The feature request is to verify this and just provide a small example showing how you would do this for an instance of JupyterHub running as a:

- top-level / first-party site with `SameSite=Lax`
- third-party site (e.g. embedded in a cross-site iframe) with `SameSite=None; Secure`

### Alternative options

If it's not possible to set this within JupyterHub then users may need to make use of a shim or proxy to intercept the outbound `Set-Cookie` header and add the relevant `SameSite` attribute.

### Who would use this feature?

This would be beneficial for users with Chrome, Firefox, Edge, or other Chromium-based browsers as they are likely seeing console warnings for cookies.

It will be vital for users that access JupypterHub in a cross-site context as those cookies **will be blocked** if they do not include the `SameSite=None; Secure` attributes.

### (Optional): Suggest a solution

Illustrate how to do this using `cookie_options`. I've been collating some of these in https://github.com/GoogleChromeLabs/samesite-examples if you want to contribute or I'm also happy to link from there.

**Comment by rowan-m** [comment]
Prompted by https://stackoverflow.com/questions/60831364/setting-jupyterhub-samesite-cookie-attribute/62974115

And to be clear, I don't know enough about JupyterHub to know if cookies are the issue here, but it seems possible.

**Comment by ding-kai** [comment]
via `c.JupyterHub.tornado_settings = {"cookie_options": {"SameSite": "None", "Secure": True}}`, but the SameSite is not supported in some older versions in python3, https://stackoverflow.com/questions/50813091/how-do-i-set-the-samesite-attribute-of-http-cookies-in-python

**Comment by maluhoss** [comment]
> via `c.JupyterHub.tornado_settings = {"cookie_options": {"SameSite": "None", "Secure": True}}`, but the SameSite is not supported in some older versions in python3, https://stackoverflow.com/questions/50813091/how-do-i-set-the-samesite-attribute-of-http-cookies-in-python

this doesnt work for me. says it doesnt recognize SameSite

**Comment by maluhoss** [comment]
have also tried `c.HubAuth.cookie_options = dict(samesite=None, secure=True) ` which also doesn't work.

**Comment by betatim** [comment]
Which version of Python are you using? In Python 3.7 the `samesite` keyword isn't supported yet, you need to use 3.8 for that.

**Comment by maluhoss** [comment]
Thanks, that makes sense.

seems like I get this oauthstate error on local machine. But for now, main concern is with deployed server, cookie is not being set with the samesite attribute properly on chrome vs. firefox which works. so would recommend the same as what's been suggested above - exploring cookie_options interactions with Chrome.

Reference: https://discourse.jupyter.org/t/issue-with-chrome-80-and-samesite-cookie-changes/3757/5

**Comment by SonakshiGrover** [comment]
@maluhoss were you able to solve this?  Please let me know. I am seeing the same issue on Chrome when I try to access jupyterhub via a webpage which is embedding jupyter as an iframe in it.

**Comment by jgwerner** [comment]
@SonakshiGrover @maluhoss - @netoisc helped fix this on our end (he also saved my hair follicles). [Details here](https://discourse.jupyter.org/t/issue-with-chrome-80-and-samesite-cookie-changes/3757/12?u=jgwerner).

**Comment by SonakshiGrover** [comment]
@jgwerner Thanks!! Somehow adding SameSite and Secure didn't work for me. But when I disabled xsrf cookie bool in jupyter_notebook_config.py, it worked!!

**Comment by sxpsxp12** [comment]
@betatim @jgwerner Chrome 90 dont works，Is there any solution

**Comment by esani06** [comment]
@SonakshiGrover how you resolved it ? i am using python 3.8 , jupyterhub 1.1.0 and  jupyter_config.py with below settings 
c.JupyterHub.tornado_settings = {
    'headers': {
        'Content-Security-Policy': 'frame-ancestors self http://x.x.x.x.x:4300'
    },
        'cookie_options': {'SameSite': 'None', 'Secure': True}
}

c.NotebookApp.tornado_settings = {
'headers': {
        'Content-Security-Policy': "frame-ancestors self http://x.x.x.x:4300"
    },
        'cookie_options': {'SameSite': 'None', 'Secure': True}
}
c.NotebookApp.disable_check_xsrf = True

but when opening the jupyter url , its getting redirected to login page again.

**Comment by tharwan** [comment]
Hi, we just setup Jupyter hub via zero to jupyter hub and now discovered we can not login from Chrome or Firefox. This seems to be the related issue, however I can not figure out what is the workaround or when a fix is coming. Anyone can help?

**Comment by manics** [comment]
According to https://github.com/jupyterhub/jupyterhub/issues/3117#issuecomment-678602834 the original issue was solved.

If it's not could someone please provide a self-contained minimal reproducible example? Thanks!

**Comment by tharwan** [comment]
We realised this is not only in FF or Chrome for us but all browsers. It just happened that the auth cookie was set from other logins via single sign-on in our tests with Safari or Edge.

**Comment by ErqingLi** [comment]
For jupyter notebook embedded in an iframe, besides the solution given above by @jgwerner , I also add `c.NotebookApp.cookie_options = {"SameSite": "None", "Secure": True}` in the jupyter_notebook_config.py, then it works :D
