### ISSUE TITLE
[500 : Internal Server Error] Permission failure checking authorization, I may need a new token

### ISSUE THREAD

**Issue by TuSKan** [jupyterhub/jupyterhub#3122]
### Bug description
[500 : Internal Server Error] Permission failure checking authorization, I may need a new token

### Your personal set up

 - OS:
Centos8
 - Version:
 jupyter 1.1.0
 - Configuration:
 DockerSpawner.SystemSpawner

**Comment by manics** [comment]
Hi. This sounds like an installation or configuration problem rather than a bug. Would you mind posting this as a support question on https://discourse.jupyter.org/ so that others will benefit from this discussion? Thanks!
