### ISSUE TITLE
login -> do git commit from notebook -> logout -> login -> it gives 500 internal server error with LDAP authentication

### ISSUE THREAD

**Issue by madhusudhannr** [jupyterhub/jupyterhub#3124]
Jul 22 05:57:23 testdata-80.bdlocal jupyterhub[1265]: [I 2020-07-22 05:57:23.402 JupyterHub login:43] User logged out: dev1
Jul 22 05:57:23 testdata-80.bdlocal jupyterhub[1265]: [I 2020-07-22 05:57:23.407 JupyterHub log:174] 302 GET /hub/logout -> /hub/login (@::ffff:172.18.0.6) 7.52ms
Jul 22 05:57:23 testdata-80.bdlocal jupyterhub[1265]: [I 2020-07-22 05:57:23.624 JupyterHub log:174] 200 GET /hub/login (@::ffff:172.18.0.6) 1.43ms
Jul 22 05:57:31 testdata-80.bdlocal jupyterhub[1265]: [I 2020-07-22 05:57:31.144 JupyterHub base:707] User logged in: dev1
Jul 22 05:57:31 testdata-80.bdlocal jupyterhub[1265]: [I 2020-07-22 05:57:31.145 JupyterHub log:174] 302 POST /hub/login?next= -> /user/dev1/ (dev1@::ffff:172.18.0.6) 195.44ms
Jul 22 05:57:31 testdata-80.bdlocal jupyterhub[1265]: [I 2020-07-22 05:57:31.366 SingleUserNotebookApp log:174] 302 GET /user/dev1/ -> /user/dev1/tree? (@::ffff:172.18.0.6) 0.69ms
Jul 22 05:57:31 testdata-80.bdlocal jupyterhub[1265]: [D 2020-07-22 05:57:31.586 SingleUserNotebookApp auth:501] No user identified
Jul 22 05:57:31 testdata-80.bdlocal jupyterhub[1265]: [D 2020-07-22 05:57:31.586 SingleUserNotebookApp auth:832] Redirecting to login url: /hub/api/oauth2/authorize?client_id=jupyterhub-user-dev1&redirect_uri=%2Fuser%2Fdev1%2Foauth_callback&response_type=code&state=eyJ1dWlkIjogImQ1NjExYWIyZTBlYjQ1MjU4MDExZTgyZjE5YWFiNGUyIiwgIm5leHRfdXJsIjogIi91c2VyL2RldjEvdHJlZT8ifQ
Jul 22 05:57:31 testdata-80.bdlocal jupyterhub[1265]: [I 2020-07-22 05:57:31.587 SingleUserNotebookApp log:174] 302 GET /user/dev1/tree? -> /hub/api/oauth2/authorize?client_id=jupyterhub-user-dev1&redirect_uri=%2Fuser%2Fdev1%2Foauth_callback&response_type=code&state=[secret] (@::ffff:172.18.0.6) 1.28ms
Jul 22 05:57:31 testdata-80.bdlocal jupyterhub[1265]: [I 2020-07-22 05:57:31.810 JupyterHub log:174] 302 GET /hub/api/oauth2/authorize?client_id=jupyterhub-user-dev1&redirect_uri=%2Fuser%2Fdev1%2Foauth_callback&response_type=code&state=[secret] -> /user/dev1/oauth_callback?code=[secret]&state=[secret] (dev1@::ffff:172.18.0.6) 9.10ms
Jul 22 05:57:32 testdata-80.bdlocal jupyterhub[1265]: [D 2020-07-22 05:57:32.024 SingleUserNotebookApp auth:501] No user identified
Jul 22 05:57:32 testdata-80.bdlocal jupyterhub[1265]: [E 2020-07-22 05:57:32.027 SingleUserNotebookApp auth:334] Error connecting to http://testdata-80.bdlocal:8081/hub/api: HTTPConnectionPool(host='"http', port=80): Max retries exceeded with url: http://testdata-80.bdlocal:8081/hub/api/oauth2/token (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f712b520290>: Failed to establish a new connection: [Errno -2] Name or service not known')))
Jul 22 05:57:32 testdata-80.bdlocal jupyterhub[1265]: [W 2020-07-22 05:57:32.027 SingleUserNotebookApp web:1786] 500 GET /user/dev1/oauth_callback?code=5NqRLtdgTH2u4WFu2xKrxbUdPL0R6x&state=eyJ1dWlkIjogImQ1NjExYWIyZTBlYjQ1MjU4MDExZTgyZjE5YWFiNGUyIiwgIm5leHRfdXJsIjogIi91c2VyL2RldjEvdHJlZT8ifQ (::ffff:172.18.0.6): Failed to connect to Hub API at 'http://testdata-80.bdlocal:8081/hub/api'.  Is the Hub accessible at this URL (from host: testdata-80.bdlocal)?

SingleUserNotebookApp auth:334] Error connecting to /hub/api: HTTPConnectionPool(host='"http', port=80): Max retries exceeded with url: /hub/api/oauth2/token  Failed to establish a new connection: [Errno -2] Name or service not known')))

**Comment by madhusudhannr** [comment]
it requires to do   
control panel -> stop my server -> start my server -> launch server to get notebook up again and it is logged in.

**Comment by madhusudhannr** [comment]
Installed using,
conda install -c conda-forge sudospawner  jupyterhub==1.1.0 notebook==6.0.3 psutil -y
/usr/bin/npm install -g configurable-http-proxy
curl -s https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.9.2.tar.gz | tar xvz -C  /opt && \
   cd /opt/git-2.9.2 && \
   make prefix=/usr/local/git all && \
   make prefix=/usr/local/git install && \
   rm -rf  /opt/git-2.9.2*

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
