### ISSUE TITLE
slow_spawn_timeout warning when timeout is disabled (0)

### ISSUE THREAD

**Issue by mriedem** [jupyterhub/jupyterhub#3126]
### Bug description

We're using zero-to-jupyterhub-k8s which sets `slow_spawn_timeout` to 0 [1] and that results in a warning in the hub logs, e.g.:

>Jul 23 14:09:36 hub-55d978d7cb-75lwl hub WARNING WARNING 2020-07-23T19:09:36.897Z [JupyterHub base:950] User hub-stress-test-123 is slow to start (timeout=0) 

If the `slow_spawn_timeout` is disabled we should not log a warning for that situation since we're not waiting at all.

Related to #1222 

[1] https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/b4738edc5dd5a3b7ecc117ca34c556afbf8981e6

#### Expected behaviour
We shouldn't log a warning for an expected situation where we're not waiting.

#### Actual behaviour
Don't log a warning when `slow_spawn_timeout` is 0 and we don't wait for the server to start.

### How to reproduce
Configure `slow_spawn_timeout: 0` in `c.JupyterHub.tornado_settings`, create a user and start their server then check the hub logs for the warning.

### Your personal set up

 - OS: linux
 - Version: commit 8a3790b01ff944c453ffcc0486149e2a58ffabea
 - Configuration: zero-to-jupyterhub-k8s default configuration for `slow_spawn_timeout` (0 in this case)

**Comment by consideRatio** [comment]
@mriedem I love how easy it is to read up on related topics thanks to your very thorough writeups! :heart:

**Comment by mriedem** [comment]
👍 You're too kind. 😃
