### ISSUE TITLE
basic authentication in nginx proxy works for notebooks, but not for jupyterlab?

### ISSUE THREAD

**Issue by LeoWelter** [jupyterhub/jupyterhub#3129]
I've always used jupyterhub behind a nginx proxy with basic authentication (b.a.) to run user notebooks. When I switched to using jupyterlab it fails by not loading the environment completely, looks like static files are not served properly.
accessing 127.0.0.1:8000 on the server itself give fully functional jupyterlab environment, same if I switch off basic authentication in the nginx config (which for obvious reasons I do not want to)

**with the basic authentication statements in nginx:**
works: https://jnb.example.org/user/donaldduck/tree
_does not work:: https://jnb.example.org/user/donaldduck/lab_

**without the basic authentication statements in nginx:**
works: https://jnb.example.org/user/donaldduck/tree
_works: https://jnb.example.org/user/donaldduck/lab_

Any ideas how to configure the nginx proxy for use with jupyterlab including basic http authentication?

My nginx setup with notebooks (works with b.a.), but does not work with b.a. when trying to acces jupyterlab (only texts, looks like static files are not accessible

When I turn off basic authentication, the proxy works as expected with fully functional jupyterlab.

```
map $http_upgrade $connection_upgrade {
     default  upgrade;
     '' close;
}

server {
  listen 80;
  server_name jnb.example.org;

  include snippets/ssl.conf;
  include snippets/letsencrypt.conf;
  return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name jnb.example.org;
    auth_basic "Restricted Content";
    auth_basic_user_file /etc/nginx/passwd/jupyterhub_bapass;

    ### ssl includes
    #..... left out for brevity...
    
    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    location ~ /\.ht {
        deny all;
    }

    # Actual jupyterhub configuration
    # Managing literal requests to the JupyterHub front end
    location / {
       proxy_pass http://127.0.0.1:8000;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;

    }

    # Managing WebHook/Socket requests between hub user servers and external proxy
    location ~* /(api/kernels/[^/]+/(channels|iopub|shell|stdin)|terminals/websocket)/? {
       proxy_pass http://127.0.0.1:8000;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;

       # WebSocket support
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection $connection_upgrade;

    }
}
```

**Comment by dr-br** [comment]
This bug also affects me. Any news on this??
Thanks!

**Comment by manics** [comment]
According to https://github.com/jupyterlab/jupyterlab/issues/9017 the problem also occurs without JupyterHub, so I'm closing this issue.
