### ISSUE TITLE
Spawner should stop on failed auth_state_hook

### ISSUE THREAD

**Issue by albertmichaelj** [jupyterhub/jupyterhub#3134]
### Bug description
When a custom `auth_state_hook` is implemented for a spawner, and when the hook is executed, if an exception is raised, then spawning should stop. Currently if an exception is raised, it is logged, ignored, and the spawning continues. It seems to be due to [this part of the code](https://github.com/jupyterhub/jupyterhub/blob/b11c02c6e01531702e99d60317d5691999a0a4a6/jupyterhub/spawner.py#L1021)

#### Expected behaviour
Spawning should stop if the `auth_state_hook` raises an exception.

#### Actual behaviour
The spawning continues.

### How to reproduce
``` python
def my_auth_state_hook(spawner, auth_state):
    raise Exception()
```
Then in config set:
``` python
spawner.auth_state_hook = my_auth_state_hook
```

### Your personal set up

 - OS:
Linux
 - Version:
1.1.0

**Comment by manics** [comment]
@rcthomas You added the original code in https://github.com/jupyterhub/jupyterhub/pull/2555

What are your thoughts on erroring instead of ignoring Exceptions in `run_auth_state_hook`?

**Comment by rcthomas** [comment]
The pre-spawn hook errors instead of ignores, so changing this to match sounds good to me.
