### ISSUE TITLE
Test with Traitlet 5.0b1

### ISSUE THREAD

**Issue by Carreau** [jupyterhub/jupyterhub#3141]
Hi all, 

Traitlets 5.0.0b1 is out, see https://discourse.jupyter.org/t/release-of-traitlets-5-0-0-beta-1-please-test/5594

You may want to test extensively, or enable it in ci. Use `pip install traitlets --pre` to get the beta and future RCs.

**Comment by manics** [comment]
The trailet's master dependency is still enabled (but allowed to failed) in CI
https://github.com/jupyterhub/jupyterhub/blob/e2ee18fa868b67e792e1b5627ec4487ff9a701a8/.travis.yml#L40-L43

The last build was 3 days ago and passed https://travis-ci.org/github/jupyterhub/jupyterhub/builds/716465408

Do you think we should switch from `master` to using `--pre` instead?

**Comment by Carreau** [comment]
master for now will stay close to 5.0.0b1, you could though switch to not allowing failures (at leaset until 5.0 is out), to make sure it keep functioning, otherwise it's a bug either in hub or traitlets.
