### ISSUE TITLE
Named Server names are not URL escaped

### ISSUE THREAD

**Issue by linhbngo** [jupyterhub/jupyterhub#3144]
### Bug description

A user created a named server with a name that contains a whitespace, this caused a malformed URL and subsequently crashed jupyterhub when it runs add_route()

#### Expected behaviour

JupyterHub is able to communicated with all spawned JupyterServer

#### Actual behaviour

Already started Jupyter servers remain running, but JupyterHub failed to restart. 

### How to reproduce

1. Launch a Jupyter server as normal. 
2. Launch an additional named server with white space in name. 

### Your personal set up

 - OS: CentOS 8.2
 
 - Version:
 
 - Configuration:

**Comment by stv0g** [comment]
Thanks for @linhbngo for reporting this. I can reproduce this issue!

In our case the bug appeared when a user created a named server with a space in its name.
Interestingly, the bug did not cause a hard crash of the hub as long it was running.

Only when restarted, and the hub syncs its routes with the CHP, it became stuck in a crash-loop.

**Comment by joe-eklund** [comment]
This is still happening and very easy to reproduce.
