### ISSUE TITLE
Error while starting Jupyterhub v1.1.0 in conda environment jupyter_telemetry ModuleNotFoundError: No module named 'ruamel'

### ISSUE THREAD

**Issue by sangramga** [jupyterhub/jupyterhub#3145]
### Bug description
When using conda environment to and installing jupyterhub (v1.1.0), by following instructions `pip install jupyterhub==1.1.0`. Following Error is created.
```
Traceback (most recent call last):
  File "/opt/conda/envs/testpy38/bin/jupyterhub", line 5, in <module>
    from jupyterhub.app import main
  File "/opt/conda/envs/testpy38/lib/python3.8/site-packages/jupyterhub/app.py", line 64, in <module>
    from jupyter_telemetry.eventlog import EventLog
  File "/opt/conda/envs/testpy38/lib/python3.8/site-packages/jupyter_telemetry/__init__.py", line 6, in <module>
    from .eventlog import EventLog  # noqa
  File "/opt/conda/envs/testpy38/lib/python3.8/site-packages/jupyter_telemetry/eventlog.py", line 10, in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel'
```

Issue with `jupyter_telemetry` library, unable to import `ruamel.yaml` - (which is also a dependency of `conda` package) This leads to `ModuleNotFoundError` in jupyter_telemetry.

#### Expected behaviour
jupyterhub running successfully at 127.0.0.1:8000/

### How to reproduce

1. Create a `testpy38` conda environment 
`conda create -n testpy38 -c conda-forge python=3.8.5 conda=4.8.4`
2. Install jupyterhub v1.1.0 
`pip install jupyterhub==1.1.0`

### Your personal set up

 - OS: Linux
 
 - Version: 1.1.0
 
 - Configuration: Conda and pip package  version information
 
`conda list`

_libgcc_mutex=0.1=conda_forge
_openmp_mutex=4.5=1_gnu
alembic=1.4.2=pypi_0
async-generator=1.10=pypi_0
attrs=19.3.0=pypi_0
brotlipy=0.7.0=py38h1e0a361_1000
ca-certificates=2020.6.20=hecda079_0
certifi=2020.6.20=py38h32f6830_0
certipy=0.1.3=pypi_0
cffi=1.14.1=py38h5bae8af_0
chardet=3.0.4=py38h32f6830_1006
conda=4.8.4=py38h32f6830_2
conda-package-handling=1.7.0=py38h1e0a361_4
cryptography=3.0=py38h766eaa4_0
decorator=4.4.2=pypi_0
entrypoints=0.3=pypi_0
idna=2.10=pyh9f0ad1d_0
ipython-genutils=0.2.0=pypi_0
jinja2=2.11.2=pypi_0
jsonschema=3.2.0=pypi_0
jupyter-telemetry=0.1.0=pypi_0
jupyterhub=1.1.0=pypi_0
ld_impl_linux-64=2.34=hc38a660_9
libffi=3.2.1=he1b5a44_1007
libgcc-ng=9.3.0=h24d8f2e_15
libgomp=9.3.0=h24d8f2e_15
libstdcxx-ng=9.3.0=hdf63c60_15
mako=1.1.3=pypi_0
markupsafe=1.1.1=pypi_0
ncurses=6.2=he1b5a44_1
oauthlib=3.1.0=pypi_0
openssl=1.1.1g=h516909a_1
pamela=1.0.0=pypi_0
pip=20.2.2=py_0
prometheus-client=0.8.0=pypi_0
pycosat=0.6.3=py38h1e0a361_1004
pycparser=2.20=pyh9f0ad1d_2
pyopenssl=19.1.0=py_1
pyrsistent=0.16.0=pypi_0
pysocks=1.7.1=py38h32f6830_1
python=3.8.5=h4d41432_2_cpython
python-dateutil=2.8.1=pypi_0
python-editor=1.0.4=pypi_0
python-json-logger=0.1.11=pypi_0
python_abi=3.8=1_cp38
readline=8.0=he28a2e2_2
requests=2.24.0=pyh9f0ad1d_0
ruamel_yaml=0.15.80=py38h1e0a361_1001
setuptools=49.6.0=py38h32f6830_0
six=1.15.0=pyh9f0ad1d_0
sqlalchemy=1.3.18=pypi_0
sqlite=3.32.3=h4cf870e_1
tk=8.6.10=hed695b0_0
tornado=6.0.4=pypi_0
tqdm=4.48.2=pyh9f0ad1d_0
traitlets=4.3.3=pypi_0
urllib3=1.25.10=py_0
wheel=0.35.1=pyh9f0ad1d_0
xz=5.2.5=h516909a_1
yaml=0.2.5=h516909a_0
zlib=1.2.11=h516909a_1007

**Comment by elgalu** [comment]
same issue, started just a couple of days ago, installing `ruamel.yaml` doesn't help
also happening on JupyterHub master branch.

**Comment by minrk** [comment]
Closing since this isn't a jupyerhub issue and it's open on jupyter/telemetry. But this is a bug in the `ruamel_yaml` conda package intalling the wrong metadata so pip thinks you have `ruamel.yaml` when you don't, so while the dependency is expressed, it's not actually satisfied. The workaround (not specific to Jupyter packages, but anything that depends on ruamel.yaml) if you have ruamel_yaml installed via conda is to install ruamel.yaml explicitly with conda:

```python
conda install -c conda-forge ruamel.yaml
```

then everything should work.

**Comment by CourtJesters** [comment]
Thank you so much
