### ISSUE TITLE
Vulnerability report - directed to security@ipython.org

### ISSUE THREAD

**Issue by dchirikov** [jupyterhub/jupyterhub#3148]
### Original post deleted
Thank you @dchirikov for reporting this vulnerability! Since it is a vulnerability report, I've deleted this public report of it. Do you want to submit it yourself like [described here](https://jupyterhub.readthedocs.io/en/stable/reference/websecurity.html#vulnerability-reporting) or would you like me to do it? I have saved a copy of your text etc. / @consideRatio

**Comment by consideRatio** [comment]
I think @dchirikov reported this, but I'm not part of the emailing list I think so I can't know.

@minrk did you get this?

**Comment by minrk** [comment]
Yes, this has been discussed on the Security list, and is ultimately about the issues that arise from the default amount of control and access a user has to their own server and the ability to use malicious links to their own server against other users, as discussed [in our security docs](https://jupyterhub.readthedocs.io/en/stable/reference/websecurity.html). Thank you for bringing it up, @dchirikov! If you feel there's any more caveats to add to that documentation, feel free to make a regular pull request.
