### ISSUE TITLE
File handle leak in jupyterhub

### ISSUE THREAD

**Issue by nuwang** [jupyterhub/jupyterhub#316]
Hi,

We've been experiencing some issues with jupyterhub. The initial symptom was that jupyterhub would crash randomly - with the error message: ""Proxy target missing". We later saw that the log was displaying the following message:
    OSError: [Errno 24] Too many open files

Next, we tried the following:
sudo watch "lsof -n -p 12630 | wc -l"
where 12630 is jupyterhub's pid. I observed that the number of open files was increasing at a constant rate of about 8 handles every 2 seconds, although no requests were being made to jupyterhub at all. Eventually, it hits the default soft limit of 1024 and starts throwing the "Too many open files" error.

So it appears that the hub is opening a large number of connections as shown below  (starting from port 50210), and not closing them.
```
jupyterhu 12630 root 1014u  IPv4             139100        0t0     TCP 127.0.0.1:9581->127.0.0.1:56747 (ESTABLISHED)
jupyterhu 12630 root 1015u  IPv4             139101        0t0     TCP 127.0.0.1:9581->127.0.0.1:56750 (ESTABLISHED)
jupyterhu 12630 root 1016u  IPv4             139106        0t0     TCP 127.0.0.1:9581->127.0.0.1:56753 (ESTABLISHED)
jupyterhu 12630 root 1017u  IPv4             139107        0t0     TCP 127.0.0.1:9581->127.0.0.1:56756 (ESTABLISHED)
jupyterhu 12630 root 1018u  IPv4             139143        0t0     TCP 127.0.0.1:9581->127.0.0.1:56765 (ESTABLISHED)
jupyterhu 12630 root 1019u  IPv4             139146        0t0     TCP 127.0.0.1:9581->127.0.0.1:56768 (ESTABLISHED)
jupyterhu 12630 root 1020u  IPv4             138171        0t0     TCP 127.0.0.1:9581->127.0.0.1:56771 (ESTABLISHED)
jupyterhu 12630 root 1021u  IPv4             138179        0t0     TCP 127.0.0.1:9581->127.0.0.1:56774 (ESTABLISHED)
jupyterhu 12630 root 1022u  IPv4             140355        0t0     TCP 127.0.0.1:9581->127.0.0.1:56795 (ESTABLISHED)
jupyterhu 12630 root 1023u  IPv4             140356        0t0     TCP 127.0.0.1:9581->127.0.0.1:56798 (ESTABLISHED)
```

Our jupyterhub configuration file can be found here: https://github.com/gvlproject/gvl_commandline_utilities/blob/master/roles/gvl.commandline-utilities/templates/jupyterhub_config.py

Since release 0.2 displayed this issue, we upgraded to the latest commit (498c062ee001d5926b601f67648f1993826852c5) but the issue remains.

Any insights into this would be very helpful.

**Comment by minrk** [comment]
Are any spawners running?

**Comment by nuwang** [comment]
We've left the default spawner (which is presumably LocalProcessSpawner?) as is. I'm not sure how to check whether the spawner is running, but the process list is as follows:
```
 6592 ?        Sl     0:37 /usr/bin/python3 /usr/local/bin/jupyterhub-singleuser --user=ubuntu --port=60821 --cookie-name=jupyter-hub-token-ubuntu --base-url=/jupyter/user/ubuntu --hub-prefix=/jupyter/hub/ --hub-api-url=http://127.0.0.1:9581/jupyter/hub/api --ip=127.0.0.1
 7412 ?        Sl     0:39 /usr/bin/python3 /usr/local/bin/jupyterhub-singleuser --user=researcher --port=56406 --cookie-name=jupyter-hub-token-researcher --base-url=/jupyter/user/researcher --hub-prefix=/jupyter/hub/ --hub-api-url=http://127.0.0.1:9581/jupyter/hub/api --ip=127.0.0.1
 8327 ?        Sl     0:19 /usr/bin/python3 -m ipykernel -f /mnt/galaxy/home/researcher/.local/share/jupyter/runtime/kernel-f49074e1-b01d-43f5-8127-4499cd45620b.json
 9859 ?        Sl     0:18 /usr/bin/python3 -m ipykernel -f /home/ubuntu/.local/share/jupyter/runtime/kernel-8c13d47a-7947-4291-a232-c6c0c99f3afb.json
21413 ?        Ss     0:00 /usr/bin/python3 /usr/local/bin/jupyterhub -f /etc/jupyterhub/jupyterhub_config.py
```
Our configuration is extremely basic. Apart from the jupyterhub_config.py above (in which we've only adjusted ips and ports), we have a simple Ansible script modelled on the readme to set up jupyterhub here: https://github.com/gvlproject/gvl_commandline_utilities/blob/master/roles/gvl.commandline-utilities/tasks/install_jupyterhub.yml.

**Comment by minrk** [comment]
This happens if you just start the Hub, and never visit it with a browser? Do you see anything in the log? What if you add `--debug`?

**Comment by nuwang** [comment]
Don't know why I didn't notice this before, but after trying with --debug again, I see what's going on.

The log showed the following:
```
[I 2015-10-02 16:04:02.708 JupyterHub log:100] 302 GET /jupyter/ (@127.0.0.1) 7.83ms
[I 2015-10-02 16:04:02.711 JupyterHub log:100] 302 GET /jupyter/hub (@127.0.0.1) 0.31ms
[I 2015-10-02 16:04:02.716 JupyterHub log:100] 302 GET /jupyter/hub/ (@127.0.0.1) 0.57ms
[I 2015-10-02 16:04:02.721 JupyterHub log:100] 200 GET /jupyter/hub/login (@127.0.0.1) 1.87ms
[I 2015-10-02 16:04:07.731 JupyterHub log:100] 302 GET /jupyter/ (@127.0.0.1) 0.83ms
[I 2015-10-02 16:04:07.735 JupyterHub log:100] 302 GET /jupyter/hub (@127.0.0.1) 1.95ms
[I 2015-10-02 16:04:07.739 JupyterHub log:100] 302 GET /jupyter/hub/ (@127.0.0.1) 1.76ms
[I 2015-10-02 16:04:07.768 JupyterHub log:100] 200 GET /jupyter/hub/login (@127.0.0.1) 1.53ms
```
We run Jupyter behind nginx and also have a backend health-checker component that periodically polls all running nginx apps to make sure they are ok. So every x seconds, the healthchecker pings /jupyter to check whether it's alive, which results in 3 redirects as shown above - for a total of 4 requests. This explains why the file handles were increasing at a constant rate.

So instead of going through nginx, I changed the healthchecker code to poll the JupyterHub tornado port directly - and finally! - the file handles stayed constant.

Having narrowed things down to Jupyter behind nginx, I checked on the nginx conf and I think I've found the culprit: https://github.com/gvlproject/gvl_commandline_utilities/blob/master/roles/gvl.commandline-utilities/templates/jupyterhub.locations

Removing the two lines below seems to have solved the issue.
```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```
So the http upgrade header is presumably causing Tornado to hang on to the connection?

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!
