### ISSUE TITLE
TimeoutError: Server at http://b467a9cf8f4c:39559/user/jupyterhub/ didn't respond in 60 seconds

### ISSUE THREAD

**Issue by xrdy511623** [jupyterhub/jupyterhub#3161]
### Bug description

I use dockerspawner as my spawner class.
After created and started single-user notebook container,  I received a warning saying "DEPRECATION: Spawner.start should return a url or (ip, port) tuple in JupyterHub >= 0.9". The problem is that dockerspawner.start method actually returns a tuple (ip,port), which I confirmed by debugging the code. I just can not figure out the reason of this warning. Then, I received another warning saying "jupyterhub's server never showed up at http://b467a9cf8f4c:39559/user/jupyterhub/ after 60 seconds. Giving up". After a while, I saw a strange log that the hub service is stopping container jupyter-jupyterhub- (id: 2c43702). Eventually, I received the error that exception=TimeoutError("Server at http://b467a9cf8f4c:39559/user/jupyterhub/ didn't respond in 60 seconds",)> after timeout.

 I check the logs of notebook server(jupyter-jupyterhub-),  which says "The Jupyter Notebook is running at:http://2c4370200cbb:8888/user/jupyterhub/". I do not know why this url does not math with
the url "http://b467a9cf8f4c:39559/user/jupyterhub/ ". Having checked the notbook server container, I found out the container_id of the notebook server is "2c4370200cbb". I just can not understand why this would happen. Is there anyone know why ? Any help would be appreciated.

[I 2020-09-02 03:55:36.379 JupyterHub dockerspawner:1027] Created container jupyter-jupyterhub- (id: 2c43702) from image 192.168.211.169:5000/basenotebook
[I 2020-09-02 03:55:36.380 JupyterHub dockerspawner:1050] Starting container jupyter-jupyterhub- (id: 2c43702)

172.20.0.3 8888
[W 2020-09-02 03:55:40.039 JupyterHub user:590] DEPRECATION: Spawner.start should return a url or (ip, port) tuple in JupyterHub >= 0.9
[I 2020-09-02 03:55:44.748 JupyterHub log:178] 200 GET /hub/api (@172.20.0.3) 16.47ms
[W 2020-09-02 03:56:37.220 JupyterHub user:697] jupyterhub's server never showed up at http://b467a9cf8f4c:39559/user/jupyterhub/ after 60 seconds. Giving up
[I 2020-09-02 03:56:37.229 JupyterHub dockerspawner:1157] Stopping container jupyter-jupyterhub- (id: 2c43702)
[E 2020-09-02 03:56:37.325 JupyterHub gen:599] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py:845> exception=TimeoutError("Server at http://b467a9cf8f4c:39559/user/jupyterhub/ didn't respond in 60 seconds",)> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 593, in error_callback
        future.result()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 852, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 673, in spawn
        await self._wait_up(spawner)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 720, in _wait_up
        raise e
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 688, in _wait_up
        http=True, timeout=spawner.http_timeout, ssl_context=ssl_context
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/utils.py", line 234, in wait_for_http_server
        timeout=timeout,
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/utils.py", line 177, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://b467a9cf8f4c:39559/user/jupyterhub/ didn't respond in 60 seconds

docker logs jupyter-jupyterhub- 
Set username to: jovyan
usermod: no changes
Executing the command: jupyterhub-singleuser --ip=0.0.0.0
[W 2020-09-02 03:55:41.769 SingleUserNotebookApp configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
[I 2020-09-02 03:55:44.699 SingleUserNotebookApp extension:158] JupyterLab extension loaded from /opt/conda/lib/python3.7/site-packages/jupyterlab
[I 2020-09-02 03:55:44.700 SingleUserNotebookApp extension:159] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2020-09-02 03:55:44.704 SingleUserNotebookApp singleuser:406] Starting jupyterhub-singleuser server version 0.9.6
[W 2020-09-02 03:55:44.745 SingleUserNotebookApp _version:50] jupyterhub version 1.2.0dev != jupyterhub-singleuser version 0.9.6. This could cause failure to authenticate and result in redirect loops!
[I 2020-09-02 03:55:44.746 SingleUserNotebookApp notebookapp:1924] Serving notebooks from local directory: /home/jovyan
[I 2020-09-02 03:55:44.747 SingleUserNotebookApp notebookapp:1924] The Jupyter Notebook is running at:
[I 2020-09-02 03:55:44.747 SingleUserNotebookApp notebookapp:1924] http://2c4370200cbb:8888/user/jupyterhub/
[I 2020-09-02 03:55:44.749 SingleUserNotebookApp notebookapp:1925] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2020-09-02 03:56:37.318 SingleUserNotebookApp notebookapp:1615] received signal 15, stopping
[I 2020-09-02 03:56:37.321 SingleUserNotebookApp notebookapp:1784] Shutting down 0 kernels

#### Expected behaviour

I expect the notebook server would work properly with the hub service.
#### Actual behaviour

The notebook server is started, yet it can not be recognized by hub service.
### How to reproduce

my spawner class is like this:
class CustomDockerSpawner(DockerSpawner):
    @gen.coroutine
    def start(self, image=None, extra_create_kwargs=None, extra_host_config=None):
        if image:
            self.log.warning("Specifying image via .start args is deprecated")
            self.image = image
        if extra_create_kwargs:
            self.log.warning(
                "Specifying extra_create_kwargs via .start args is deprecated"
            )
            self.extra_create_kwargs.update(extra_create_kwargs)
        if extra_host_config:
            self.log.warning(
                "Specifying extra_host_config via .start args is deprecated"
            )
            self.extra_host_config.update(extra_host_config)

            # image priority:
            # 1. user options (from spawn options form)
            # 2. self.image from config
        key = self.user_options.get("image")
        print(self.user_options)
        image_name = self.user_options.get('image').split("/")[1]
        print(image_name)
        dockerfile_option = self.image_whitelist.get(key)
        print(dockerfile_option)
        # check if the iamge exists in the private registery
        tag = self.registery_base_url + image_name
        if not self.check_image(image_name):
            # build the required image
            if self.build_image(dockerfile_option, tag):
                # push the image to the private registery
                if self.push_image(image_name):
                    yield self.pull_image(image=tag)
                    yield super().start(image=tag, extra_create_kwargs=None, extra_host_config=None)

                else:
                    print("push failed")
                    return

            else:
                print("build failed")
                return "please check your dockerfile"

        else:
            yield self.pull_image(image=tag)
            yield super().start(image=tag, extra_create_kwargs=None, extra_host_config=None)

    @gen.coroutine
    def pull_image(self, image=None):
        image = image or self.image

        try:
            yield self.docker('inspect_image', image)
        except:
            self.log.info('Image `{}` not found'.format(image))
            self.log.info('Starting to pull image `{}`'.format(image))
            yield self.docker('pull', image)
            self.log.info('Finished pulling image `{}`'.format(image))

        return None

    def check_image(self, repo):
        """
        check if the image exists in the private registery
        :param repo:
        :return:
        """
        raw = subprocess.check_output(['curl', '-XGET', self.registery_base_url + 'v2/' + repo + '/tags/list'])
        res = json.loads(raw.decode("utf-8"))
        if res.get("errors"):
            print("no such image")
            return False
        else:
            return True

    def build_image(self, dockerfile, tag):
        """
        build the required image
        :param dockerfile:
        :param tag:
        :return:
        """
        f = BytesIO(dockerfile.encode("utf-8"))
        response = [line for line in self.cli.build(fileobj=f, rm=True, tag=tag, cache_from=self.cache_from)]
        res = json.loads(bytes.decode(response[-2]))

        if res["stream"].startswith("Successfully built"):
             print("build the required image {} successfully".format(tag))
             return True

        else:
             print("build failed")
             return False

    def push_image(self, repo):
        """
        push the built image to the private registery
        :param repo:
        :return:
        """
        response = [line for line in self.cli.push(self.registery_base_url + repo, stream=True, decode=True)]
        target = [line for line in response if line.get("status") == "Pushed"]
        if target:
            print("push {} successfully".format(self.registery_base_url + repo))
            return True

        else:
            return False

    

### Your personal set up

my config.py file is like this:
import os

c = get_config()

# Application(SingletonConfigurable) configuration
# redirect user to /hub/home instead of their own single-user notebook server
# c.JupyterHub.redirect_to_server = False
# JupyterHub(Application) configuration
#  Whitlelist users and admins
c.JupyterHub.admin_access = True
c.JupyterHub.allow_named_servers = True
# use custom authenticator
c.JupyterHub.authenticator_class = 'nativeauthenticator.NativeAuthenticator'
c.JupyterHub.named_server_limit_per_user = 5
# use custom spawner
c.JupyterHub.spawner_class = 'customspawner.CustomDockerSpawner'
# User containers will access hub by container name on the Docker network
c.JupyterHub.hub_ip = 'jupyterhub'
c.JupyterHub.hub_port = 8080
# Spawner(LoggingConfigurable) configuration
# Connect containers to this Docker network
network_name = os.environ.get('DOCKER_NETWORK_NAME','jupyterhub-network')
c.CustomDockerSpawner.use_internal_ip = True
c.CustomDockerSpawner.network_name = network_name
# choose one of the following images to spawn containers
c.CustomDockerSpawner.image_whitelist = {'basic notebook image/basenotebook':'''
        FROM jupyterhub/singleuser:latest
        ARG NB_USER="jovyan"
        ENV HOME=/home/$NB_USER
        WORKDIR $HOME
        USER root
        ''',  'pyspark': 'jupyter/pyspark-singleuser'}
# JupyterHub requires a single-user instance of the Notebook server, so we
# default to using the `start-singleuser.sh` script included in the
# jupyter/docker-stacks *-notebook images as the Docker run command when
# spawning containers.  Optionally, you can override the Docker run command
# using the DOCKER_SPAWN_CMD environment variable
spawn_cmd = os.environ.get('DOCKER_SPAWN_CMD', 'start-singleuser.sh')
c.CustomDockerSpawner.extra_create_kwargs.update({'command': spawn_cmd})
# Pass the network name as argument to spawned containers
c.CustomDockerSpawner.extra_host_config = {'network_mode': network_name}
# Remove containers once they are stopped
c.CustomDockerSpawner.remove_containers = False
# For debugging arguments passed to spawned containers
c.CustomDockerSpawner.debug = True
# Explicitly set notebook directory because we'll be mounting a host volume to
# it.  Most jupyter/docker-stacks *-notebook images run the Notebook server as
# user `jovyan`, and set the notebook directory to `/home/jovyan/work`.
# We follow the same convention.
notebook_dir = os.environ.get('DOCKER_NOTEBOOK_DIR', '/home/jovyan/work')
c.CustomDockerSpawner.notebook_dir = notebook_dir
# Mount the real user's Docker volume on the host to the notebook user's
# notebook directory in the container
c.CustomDockerSpawner.volumes = {'jupyterhub-user-{username}': notebook_dir}
# c.CustomDockerSpawner.read_only_volumes = {'document': '/home/jovyan/document'}
# TLS config
c.JupyterHub.port = 443
c.JupyterHub.ssl_key = '/etc/jupyterhub/mykey.key'
c.JupyterHub.ssl_cert = '/etc/jupyterhub/mycert.pem'
# Persist hub data on volume mounted inside container
data_dir = os.environ.get('DATA_VOLUME_CONTAINER', '/data')
c.JupyterHub.cookie_secret_file = os.path.join(data_dir, 'jupyterhub_cookie_secret')
# c.Spawner.default_url = '/lab'
c.Spawner.http_timeout = 240
c.Spawner.start_timeout = 240
c.Spawner.poll_interval = 0
c.JupyterHub.tornado_settings = {'slow_spawn_timeout':120}
# Authenticator(LoggingConfigurable) configuration
# add admin user
c.Authenticator.admin_users = {'jupyterhub'}
# except for username and pwd, this asks user to provide extra email information to sign up
# c.Authenticator.ask_email_on_signup = True
# By default all users that make sign up on Native Authenticator need an admin approval so they can actually log in the system. 
# however, with the following configuration,all users that do sign up can have the access to log in the system
c.Authenticator.open_signup = True
# By default, when a user signs up through Native Authenticator there is no password strength verification, so any type of password is valid. There are two methods to increase pwd strength
# The Authenticator will verify if the password is a common password and the user won’t be able to sign up if it is. 
c.Authenticator.check_common_password = True
# add a minimum password length that the user must have.
c.Authenticator.minimum_password_length = 6
# authenticator will block user after serveal failed logins.The default is 0,which means the system will never block user
c.Authenticator.allowed_failed_logins = 5
# define the number of seconds a user must wait before trying again. The default value is 600 seconds.
c.Authenticator.seconds_before_next_try = 1200
# By default Native Authenticator allows everyone to register user accounts. the following setting will disable this function.
# c.Authenticator.enable_signup = False
# You can increase security making two factor authentication obligatory for all users. 
# Users will receive a message after signup with the two factor authentication code:xxxxxxxxx(random string)
# And login will now require the two factor authentication code as well:
c.Authenticator.allow_2fa = True
- OS:
 
 - Version:
 
 - Configuration:

**Comment by manics** [comment]
Hi @xrdy511623 :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!
