### ISSUE TITLE
cross-site requests issue with jupyterhub on chrome

### ISSUE THREAD

**Issue by SonakshiGrover** [jupyterhub/jupyterhub#3162]
I am running jupyterhub with jupyterlab on an ec2 instance. I also have a website running at another machine wherein I am embedding my instance's url in an iframe. 

The issue is that when I try to access Jupyterhub's directly from its url, it works on the Chrome and Firefox. But when I try to access Jupterhub via my website, it gives me the below 2 console messages on Chrome. 

**A cookie associated with a cross-site resource at url [of ec2 instance where jupyterhub is running] was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at [https://www.chromestatus.com/feature/5088147346030592](https://www.chromestatus.com/feature/5088147346030592) and [https://www.chromestatus.com/feature/5633521622188032](https://www.chromestatus.com/feature/5633521622188032)**

**Blocked autofocusing on a form control in a cross-origin subframe [login:140]**

On Firefox it runs fine. 

### Options I tried but didn't work:_ 
Looked at some similar issues - [3117](https://github.com/jupyterhub/jupyterhub/issues/3117) and [1087](https://github.com/jupyterhub/jupyterhub/issues/1087)

Tried c.Spawner.args = ['--NotebookApp.allow_origin=*'], didn't work for me.
Also tried setting the 'samesite' attribute in jupyterhub_config.py but that somehow I am not able to use the correct python veriosn for it. I have both 3.6.11 and 3.8 installed on my system, but how do I make sure jupyterhub runs using the 3.8 python version? Can I somehow specify the /usr/bin/python3.8 while running `jupyterhub --config 'path' command`? 
### Versions 

- installed on the ec2 instance that's running jupyterhub

Python - 3.6.11 
Jupyterhub - 2.2.2

- browser

Chrome - 84
Firefox - 80

**Comment by SonakshiGrover** [comment]
@minrk  in [1087](https://github.com/jupyterhub/jupyterhub/issues/1087), you mentioned cross origin requests can be enabled we need to provide the token first. Could you please elaborate where do we specify the token? Do we include it in the config file? Any leads/suggestions on this will be very helpful! Thanks

**Comment by SonakshiGrover** [comment]
UPDATE: created my own venv with python 3.8 and installed jupyterhub in that venv. This solved the issue of cross-site resource. But I am still getting the error: Blocked autofocusing on a form control in a cross-origin subframe [login:140]
and since adding the cookie_options 'SameSite' attribute to tornado_settings, I am getting redirected to login page everytime I login. This is similar to issue [1438](https://github.com/jupyterhub/jupyterhub/issues/1438) but couldn't find any suggestions from that issue.

**Comment by jwclark** [comment]
I've gotten this to work by adding SameSite and Secure attributes to tornado_settings 'cookie_options' as well as to the NotebookApp.cookie_settings on the notebook image. We also set tornado_settings xsrf_cookie_kwargs with Secure and samesite attributes in both hub and notebook configs.

**Comment by SonakshiGrover** [comment]
@jwclark I was missing setting the xsrf_cookie all this time. In the config file, I set c.NotebookApp.disable_check_xsrf = True and it worked. Thanks a lot!

**Comment by zitrosolrac** [comment]
@SonakshiGrover Could you tell me what config properties you used to fix this issue?
