### ISSUE TITLE
"Edit this page" URLs for stable docs broken

### ISSUE THREAD

**Issue by nguyenvulong** [jupyterhub/jupyterhub#3166]
When I want to fix the docs, I would click on "Edit this page" (top right corner)
For example: https://jupyterhub.readthedocs.io/en/stable/installation-guide-hard.html

It would take me to the broken link as follows:

![image](https://user-images.githubusercontent.com/1311412/92696706-3a262600-f385-11ea-9aa8-db51cfa6fa25.png)

**Comment by manics** [comment]
The edit link is no longer included.
