### ISSUE TITLE
Broken docs on server-actions

### ISSUE THREAD

**Issue by qTipTip** [jupyterhub/jupyterhub#3178]
Hi! :) 

Trying to figure out some telemetry, and noticed a broken doc-page.

### Bug description

The page https://jupyterhub.readthedocs.io/en/stable/events/server-actions.html looks broken. Probably something in the yaml file here: https://github.com/jupyterhub/jupyterhub/tree/master/jupyterhub/event-schemas/server-actions

**Comment by kinow** [comment]
I think this is fixed in the latest docs: https://jupyterhub.readthedocs.io/en/latest/events/server-actions.html

Once a new version is released, I think this issue will go away :+1:

**Comment by manics** [comment]
Fixed 😄
