### ISSUE TITLE
Unable to set multiple Jupyter working with single Apache Reverse Proxy 

### ISSUE THREAD

**Issue by Ashoksugu7** [jupyterhub/jupyterhub#3179]
I have two jupyter but unable to load in the single config base url

<VirtualHost *:80>
        DocumentRoot /var/www/html
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        ProxyPreserveHost On
        ProxyPass /jupyter/ http://192.168.1.40:4050/jupyter/
        ProxyPassReverse /jupyter/ http://192.168.1.40:4050/jupyter/
        ProxyPass /jupyter/ http://192.168.1.42:4050/jupyter/
        ProxyPassReverse /jupyter/ http://192.168.1.42:4050/jupyter/
        <Location "/jupyter/api/kernels">
                RequestHeader set X-SCRIPT-NAME /jupyter/
                ProxyPassReverse http:/192.168.1.40:4050/
                RewriteEngine on
                RewriteCond %{HTTP:UPGRADE} =websocket [NC]
                RewriteRule /jupyter/api/kernels/(.*) ws://192.168.1.40:4050/jupyter/api/kernels/$1 [P,L]
                RewriteCond %{HTTP:UPGRADE} !=websocket [NC]
                RewriteRule /jupyter/api/kernels/(.*) http://192.168.1.40:4050/jupyter/api/kernels/$1 [P,L]
                RewriteCond %{HTTP:UPGRADE} =websocket [NC]
                RewriteRule /jupyter/api/kernels/(.*) ws://192.168.1.42:4050/jupyter/api/kernels/$1 [P,L]
                RewriteCond %{HTTP:UPGRADE} !=websocket [NC]
                RewriteRule /jupyter/api/kernels/(.*) http://192.168.1.42:4050/jupyter/api/kernels/$1 [P,L]
        </Location>
        # Require user/password
        <Proxy *>
                Order deny,allow
                Allow from all
                Authtype Basic
                Authname "Password Required"
                AuthUserFile /etc/htpasswd
                Require valid-user
        </Proxy>
</VirtualHost>

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!
