### ISSUE TITLE
tkinter throuh jupyterhub

### ISSUE THREAD

**Issue by christineleroy** [jupyterhub/jupyterhub#3181]
### Proposed change
Actually it is not possible to use tkinter throuh jupyterhub: do you plan to make it possible throug window forwarding?

### Who would use this feature
It's to avoid rewriting all codes using tkinter

**Comment by manics** [comment]
Hi, this is something that would have to be handled by a singleuser server and not JupyterHub. The [community forum](https://discourse.jupyter.org/) is a good place to discuss issues like this.
