### ISSUE TITLE
'NoneType' object has no attribute 'updated'

### ISSUE THREAD

**Issue by bsikander** [jupyterhub/jupyterhub#3186]
### Bug description
On GCP, i launch a notebook instance which runs JupyterHub inside. Once, i open the jupyterlab UI, it gives me an option to spawn a dataproc cluster with different configurations. I have given my custom configuration. On the master node of dataproc, jupyter notebooks are running. I checked by running the command
```
ps aux | grep jupyter
``` 
with output
```
/bin/bash -c /opt/conda/anaconda/bin/jupyterhub-singleuser --port=12345 --NotebookApp.default_url=/lab --NotebookApp.disable_check_xsrf=True &> /var/log/jupyter_notebook.log
```
Now the UI of jupyter is behaving very strangely. Here are the strange issues

1- If I click on `+` to create a new notebook, the first character or notebook name is always missing. I tried to import an existing notebook and still the same behavior. As you can see `U` is missing.
<img width="392" alt="Screen Shot 2020-09-24 at 12 05 25" src="https://user-images.githubusercontent.com/4642104/94131583-68643500-fe5e-11ea-8f00-4d9202ecf78b.png">

2- When i try to download a newly created notebook, it fails
<img width="233" alt="Screen Shot 2020-09-24 at 12 05 37" src="https://user-images.githubusercontent.com/4642104/94131682-8467d680-fe5e-11ea-9b88-6ea1f0c6d8ff.png">

3- When I try to open the newly created notebook, I get the following errors
<img width="432" alt="Screen Shot 2020-09-24 at 12 05 09" src="https://user-images.githubusercontent.com/4642104/94131791-a9f4e000-fe5e-11ea-8c22-bafad5b91c73.png">
<img width="440" alt="Screen Shot 2020-09-24 at 12 05 16" src="https://user-images.githubusercontent.com/4642104/94131800-acefd080-fe5e-11ea-9d22-7b29d98e40b7.png">

Due to above, nothing works, I have tried changing configuration but nothing helps.

In the logs, I see 500 errors like but nothing concrete that I can search for
```
[D 2020-09-24 09:57:34.915 SingleUserNotebookApp auth:310] HubAuth cache miss: token:abc:def
[D 2020-09-24 09:57:34.978 SingleUserNotebookApp auth:316] Received request from Hub user {'kind': 'user', 'name': 'test.user, 'admin': False, 'groups': [], 'server': '/user/test.user/', 'pending': None, 'created': '2020-09-23T09:08:57.039282Z', 'last_activity': '2020-09-24T09:57:34.958461Z', 'servers': None}
[D 2020-09-24 09:57:34.979 SingleUserNotebookApp auth:871] Allowing whitelisted Hub user test.user
[I 2020-09-24 09:57:34.988 SingleUserNotebookApp log:174] 200 GET /user/test.user/metrics?1600941454671 (test.user@::1) 74.37ms
[D 2020-09-24 09:57:36.164 SingleUserNotebookApp auth:871] Allowing whitelisted Hub user test.user
[W 2020-09-24 09:57:36.219 SingleUserNotebookApp web:1782] 500 GET /user/test.user/api/contents/GCS/ntitled1.ipynb?type=notebook&content=1&1600941455972 (::1): Internal server error: 'NoneType' object has no attribute 'updated'
[W 2020-09-24 09:57:36.219 SingleUserNotebookApp handlers:608] Internal server error: 'NoneType' object has no attribute 'updated'
[E 2020-09-24 09:57:36.220 SingleUserNotebookApp log:166] {
      "X-Forwarded-Host": "adf-....googleusercontent.com",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "80",
      "X-Forwarded-For": "::1",
      "X-Inverting-Proxy-User-Id": "dsfs=",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "https://adf-dot-...googleusercontent.com/user/test.user/lab?authuser=0",
      "Cookie": "S=[secret]; jupyterhub-user-test.user=[secret]; jupyterhub-session-id=[secret]; _xsrf=[secret]",
      "Content-Type": "application/json",
      "Accept-Language": "en-US,en;q=0.9",
      "Accept-Encoding": "gzip, deflate, br,gzip(gfe),gzip(gfe)",
      "Accept": "*/*",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36,gzip(gfe),gzip(gfe)",
      "Host": "adf-....googleusercontent.com",
      "Connection": "close"
    }
[E 2020-09-24 09:57:36.220 SingleUserNotebookApp log:174] 500 GET /user/test.user/api/contents/GCS/ntitled1.ipynb?type=notebook&content=1&1600941455972 (test.user@::1) 57.19ms
```

JupyterLab version is 1.1.4

#### Expected behaviour
The UI should behave properly

#### Actual behaviour
Cannot download, cannot see first character, cannot open the notebook

### Your personal set up

 - OS: ubuntu
 - Version: 1.2.0dev
 - Configuration:

**Comment by manics** [comment]
In general we ask that JupyterHub GitHub issues are used for bugs and development discussions, with support being handled on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions. Hope you understand 😀.
