### ISSUE TITLE
auth state visible to self

### ISSUE THREAD

**Issue by diocas** [jupyterhub/jupyterhub#3189]
### Proposed change
Currently a normal/non admin user is unable to see its own auth state and this is on purpose, according to the comment in the code. I would like to ask if there is a possible security problem or any other particular reason for this decision and, if not, wether it will be possible to change it and make the auth state visible to the corresponding user as well.

### Who would use this feature?
In our JH deployment, we need to forward the oAuth token we obtain from the authenticator to the user container/environment (so that other processes/extensions can use it). Of course this can already be done (by injecting it via the spawner), but then the user container (or some sidecar container/process/etc) needs to be responsible for the renewal (which seems to be the way others are doing it). But, if for some reason a re-authentication is required, then that process will get stuck and the session will have to be restarted completely.

JH already has a renewal functionality baked inside and tightly coupled with everything that needs authentication. If the authenticator implements `refresh_user`, all of this will be handled automatically.  If the auth state was visible to the logged-in user, then Jupyter extensions would be able to fetch the valid token just by querying the user API.
This has the added advantage of keeping all the auth code in a single place, which would allow switching authenticators (which would have to implement the refresh) without having to worry about all of these extra sidecar containers/processes.

### Alternative options
If this information is considered sensitive and you don't think it should be public by default (especially since this field can be used by any authenticator), it would be beneficial to have an extra field in user model that allows us to inject extra public information from the authenticator or other place.

Please let me know what you think.

**Comment by manics** [comment]
`auth_state` may contain tokens and other secrets that shouldn't be visible to a user. They're available to the Spawner though, so you can inject them into a user's environment, e.g. as environment variables. Will this solve your problem?

**Comment by diocas** [comment]
Not really. As I mentioned in the ticket, I already do that. But then I need to get the **refreshed token** to continue to be able to use it (I believe that since JH already handles everything related to auth, it should be able to provide some of this info to Jupyter).
Allowing extra info to be available in some other (public) field, or making the the visibility of `auth_state` configurable, would help.

**Comment by octavd** [comment]
Hello,

I am having the same issue/question like @diocas.
I have this scenario: Each user should have an jupyterhub api token and with that i want to retreive the auth_state -> access_token / refresh_token / id_token for him - **not for other users** and update afterwards the env variables of the containers with the new tokens.
Currently this doesn't work because the user needs to be an admin and not all of them should be admins.

**Comment by chainlink** [comment]
This is covered here: https://github.com/jupyterhub/oauthenticator/issues/211#issuecomment-569637559

**Comment by diocas** [comment]
@chainlink I didn't see that ticket, but I have implemented the same workaround they suggest. But I would prefer not to have workarounds and have this properly implemented in the upstream.

I don't mind implementing it and making a PR, I just wanted to know what the Jupyter team thinks is the best idea. So far I have 3 options:
* We enable auth state for everyone in the self endpoint (which is the workaround suggested and might not be advisable as a general rule);
* We put a switch in the config to make the auth state in the self endpoint visible or not;
* We create an extra field for public information in the user state, thus allowing the authenticators to publish the tokens there.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/accessing-upstream-oauth2-token-from-python-code-within-singleuser-notebook-server/8211/2

**Comment by warwing** [comment]
> I didn't see that ticket, but I have implemented the same workaround they suggest. But I would prefer not to have workarounds and have this properly implemented in the upstream.
> 
> I don't mind implementing it and making a PR, I just wanted to know what the Jupyter team thinks is the best idea. So far I have 3 options:
> 
> * We enable auth state for everyone in the self endpoint (which is the workaround suggested and might not be advisable as a general rule);
> * We put a switch in the config to make the auth state in the self endpoint visible or not;
> * We create an extra field for public information in the user state, thus allowing the authenticators to publish the tokens there.

Hello together,

I would really love to see this enhancement - or read reasons why we shouldn't do it (for security reasons or other reasons I can't see at the moment).

From my view there is no difference in security, if we include the upstream token in the auth_state, because a logged in user may see it already, if the pre_spawn_start hook forwards it.

@diocas Could you share your workaround as patch or point me to a fork?

**Comment by diocas** [comment]
@warwing We [wrap JupyterHub](https://github.com/swan-cern/jupyterhub-extensions/blob/master/SwanHub/swanhub/app.py) (we call this wrapper SwanHub), and [replace the SelfApiHandler](https://github.com/swan-cern/jupyterhub-extensions/blob/master/SwanHub/swanhub/userapi_handler.py) with a version that always exposes the state.

**Comment by warwing** [comment]
@diocas Thanks for pointing me to this. You're wrapper pattern is very nice :)

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/get-request-cookies-from-within-notebook-container/8630/2

**Comment by minrk** [comment]
The RBAC work in #3393 allows explicit granting of users to read their own auth state. The defaults won't change, but this will become possible.

**Comment by octavd** [comment]
Hello @minrk,

Will this feature be available for the master branch as well and have an official release?

**Comment by minrk** [comment]
Hoping to land it in master by the end of May, with prereleases over the summer.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/how-to-get-the-authentication-token-current-user/9013/2
