### ISSUE TITLE
Jupyterhub behind Firewall, issue in saving large files

### ISSUE THREAD

**Issue by nsahoo1** [jupyterhub/jupyterhub#3190]
Hi Team,

We have been trying to configure JupyterHub in a private VPC with a lot of security restrictions, out of which one is that Size of the JSON content of any ingress traffic in this case the Save API cannot exceed 128kb.

So in a scenario when I would like to upload a file of size 100-500Mb to Jupyterhub and edit it and then try to save it. My Save operation fails.
![image](https://user-images.githubusercontent.com/72190452/94781301-40894a00-03e7-11eb-81c4-60f100e4ad0a.png)

The challenge is we cannot get exceptions to the security policy, and hence we are open to fork out the jupyterhub and make minor changes if possible to get this working.
I have been looking into /usr/local/lib/python3.6/dist-packages/notebook/services/contents/
to identify the logic behind the save operation in chunks but with no great progress.

Can someone from the community help me with this issue or suggest a few approach to tackle this situation.

All help would greatly be appreciated.

Regards,
Naba

**Comment by manics** [comment]
I can see you've already [started a discourse thread](https://discourse.jupyter.org/t/jupyterhub-behind-firewall-issue-in-saving-large-files/6192) which is the best place for this discussion, so I'm closing this.
