### ISSUE TITLE
Let spawners cleanup resources on user/named-server deletion

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#3197]
### Proposed change
To add a optional hook that Spawner's can implement to cleanup resources they may have created, which can be called when a named server, or user, is deleted.

We would make the Spawner base class have a valid implementation that does nothing, and then let the Spawner's that want add logic by providing their own implementation.

### Use case
@PMende describes in https://github.com/jupyterhub/kubespawner/issues/446 that pressing the red Delete button on a named server was expected to also delete a PVC created by KubeSpawner, but that doesn't happen.

The goal with the proposed change is to solve this kind of problem, but I think the way to do it is through JupyterHub's interaction with the Spawner base class.

**Comment by nsshah1288** [comment]
Hi @consideRatio @PMende I have solved this issue, when clicking red 'Delete user' button 
![image](https://user-images.githubusercontent.com/61845317/105082213-3b690d00-5a61-11eb-94e1-0b0ecc485be9.png)

The PVC of the named server is deleted. If interested in PR or code for this, please let me know. Thanks

**Comment by consideRatio** [comment]
@nsshah1288 wieee to see how you solved it would be great!

I would recommend _forking_ (GitHub concept) this GitHub repository (jupyterhub/jupyterhub) and then using git to add and commit your changes which you upload back to your GitHub fork of this repository.

Here is a guide on how to go about that: https://opensource.com/article/19/7/create-pull-request-github

If you are a beginner on git, I warmly recommend these online courses:
- https://www.pluralsight.com/courses/git-big-picture
- https://www.pluralsight.com/courses/how-git-works

**Comment by nsshah1288** [comment]
Thanks for the helpful response @consideRatio !
I made the following PRs:

- https://github.com/jupyterhub/jupyterhub/pull/3337
- https://github.com/jupyterhub/kubespawner/pull/475

@minrk has approved the first one into the jupyterhub repo. Would you know of anyone who could review the kubespawner PR?

Note: This solution only works for dynamic singleuser storage, not for static. I tested the dynamic storage with sqlite pvc and that worked well (deletes the PVC of named server when user is deleted). I tested with static storage as well (EFS) and I was still able to delete a user thru the admin console fine, but the underlying storage was not deleted.

**Comment by nsshah1288** [comment]
Hi @consideRatio @manics , would you please be able to review this PR? https://github.com/jupyterhub/kubespawner/pull/475
Thanks!

**Comment by manics** [comment]
The mentioned PRs were merged.
