### ISSUE TITLE
Question: is it possible to pass (Kube)Spawner configuration in a POST request to spawn a server

### ISSUE THREAD

**Issue by arpitsri3** [jupyterhub/jupyterhub#3198]
## Interpretation of question by @consideRatio

Is it possible to pass configuration in a POST request to /users/{name}/servers/{server_name}, which overrides configuration such as c.KubeSpawner.extra_tolerations or c.KubeSpawner.node_selector?

## Original issue

Hello !

This question is regarding configuring jupyter-hub with kubespawner on a kubernetes cluster. There was a use case where it was needed to spin up a notebook server for a user with node-selector and tolerations defined while calling the '/users/{name}/servers/{server_name}' POST API of jhub server. 
I have tried giving the 'node_selector' and 'tolerations' option (as key-value) directly in the body of the post request ('/users/{name}/servers/{server_name}) . However, it doesn't seem to work and a 'bad request' response comes up from the jhub server. As per swagger documentation spawner options should work. Requesting help on this.

**Comment by manics** [comment]
You should be able to use a combination of options_form and profiles to pass custom parameters.
