### ISSUE TITLE
single-user session URL incorrectly determined if its host is an IPv6 literal

### ISSUE THREAD

**Issue by mj-harvey** [jupyterhub/jupyterhub#3199]
### Bug description

Hello,

We have a Jupyterhub 1.0.0 environment that uses batch spawner to start single-user sessions in a cluster environment. Jupyterhub is taken from anaconda. For implementation reasons the connection betweenthe Hub and the single user session must be made using an IPv6 literal. Batch -spawner passes the IPv6 address within "[]", appropriate for URL-encoding (eg https://[aa:bb:cc::]/lab ). However, the Hub erroneously uses the address stripped of its square brackets. (eg https://aa:bb:cc::/lab). 

This happens due to the logic circa line 555 in jupyterhub/spawn.py that passes the correct batchspawner-provided URL through urlparse:
```
    url = '%s://%s:%i' % ((proto,) + url)   # url is string from batchspawner containing IPv6 in the form '[aa:bb:cc::]'
    urlinfo = urlparse(url)
    server.proto = urlinfo.scheme
    server.ip = urlinfo.hostname
```

I don't have a general fix for this, we've patched it with
```
server.ip = "[%s]" % (urlinfo.hostname,)
```

which is appropriate only for our environment.

**Comment by consideRatio** [comment]
I believe that this may very well be fixed in the jupyterhub's absolute latest version not yet released, if you can try that out it would be very relevant to the issue.

**Comment by mj-harvey** [comment]
thanks, I'll circle back and try that once I've got 1.1.0 working (with the above fix).

**Comment by consideRatio** [comment]
@mj-harvey okay! Closing this preliminary, please ping me to reopen it if this persists in the latest not-yet-released version of jupyterhub which will become 1.2.0b1!
