### ISSUE TITLE
Environment variables passed to lab changed betwen 0.9.6 and 1.1.0

### ISSUE THREAD

**Issue by mj-harvey** [jupyterhub/jupyterhub#3201]
The 0.9.6 Hub passes the following environment variables to the spawned single-user hub
```
JPY_API_TOKEN=XXXX
JUPYTERHUB_BASE_URL=/
JUPYTERHUB_HOST=
JUPYTERHUB_OAUTH_CALLBACK_URL=/user/mjharvey/oauth_callback
JUPYTERHUB_CLIENT_ID=jupyterhub-user-mjharvey
JUPYTERHUB_SERVICE_PREFIX=/user/mjharvey/
JUPYTERHUB_API_URL=http://192.168.97.33:9081/hub/api
JUPYTERHUB_USER=mjharvey
JUPYTERHUB_API_TOKEN=XXXX
```

Whereas 1.1.0 passes

```
JPY_API_TOKEN=XXXX
JUPYTERHUB_ACTIVITY_URL=http://[XXXX]:9081/hub/api/users/mjharvey/activity
JUPYTERHUB_SERVER_NAME=
JUPYTERHUB_OAUTH_CALLBACK_URL=/user/mjharvey/oauth_callback
JUPYTERHUB_CLIENT_ID=jupyterhub-user-mjharvey
JUPYTERHUB_BASE_URL=/,
JUPYTERHUB_API_URL=http://[XXXX]:9081/hub/api
JUPYTERHUB_HOST=
JUPYTERHUB_USER=mjharvey
JUPYTERHUB_API_TOKEN=XXXX
```

In particular `JUPYTERHUB_SERVICE_PREFIX` is prefix is missing.  This was causiing an authentication failure (see issue #3200 ). If I explicitly define that in the jobscript that Batchspawner submits the session starts correctly.

Is this an expected change?

**Comment by consideRatio** [comment]
To help others looking to try helping you, can you see if you get the same issue with JupyterHub v1.0.0, so the scan for the breaking chance you experience becomes more narrow?

Also, provide your jupyterhub_config.py file (while redacting passwords etc)

**Comment by kinow** [comment]
`master` branch, using the following test spawner (it won't work, but prints args + envs)

```python
#!/usr/bin/env python3

import sys
import os


if __name__ == '__main__':
    print('--- Args ---')
    print(sys.argv[1:])

    print('--- Env ---')
    for k, v in os.environ.items():
        print(f'{k}={v}')

sys.exit(0)
```

gives:

```bash
--- Args ---
['--port=36043']
--- Env ---
PATH=...
LANG=en_NZ.UTF-8
JUPYTERHUB_API_TOKEN=60ce91a4f7fe4c2e8aa0082d81bc02df
JPY_API_TOKEN=60ce91a4f7fe4c2e8aa0082d81bc02df
JUPYTERHUB_CLIENT_ID=jupyterhub-user-kinow
JUPYTERHUB_HOST=
JUPYTERHUB_OAUTH_CALLBACK_URL=/user/kinow/oauth_callback
JUPYTERHUB_USER=kinow
JUPYTERHUB_SERVER_NAME=
JUPYTERHUB_API_URL=http://127.0.0.1:8081/hub/api
JUPYTERHUB_ACTIVITY_URL=http://127.0.0.1:8081/hub/api/users/kinow/activity
JUPYTERHUB_BASE_URL=/
JUPYTERHUB_SERVICE_PREFIX=/user/kinow/
USER=kinow
HOME=/home/kinow
SHELL=/bin/bash
```

After checking out tag `1.0.0`:

```
(venv) kinow@ranma:~/Development/python/workspace/jupyterhub$ jupyterhub --version
1.1.0
(venv) kinow@ranma:~/Development/python/workspace/jupyterhub$ jupyterhub
# lots of logs... then
--- Args ---
['--port=54417']
--- Env ---
PATH=...
LANG=en_NZ.UTF-8
JUPYTERHUB_API_TOKEN=5c8ca34de5d14af9880967293db69bf6
JPY_API_TOKEN=5c8ca34de5d14af9880967293db69bf6
JUPYTERHUB_CLIENT_ID=jupyterhub-user-kinow
JUPYTERHUB_HOST=
JUPYTERHUB_OAUTH_CALLBACK_URL=/user/kinow/oauth_callback
JUPYTERHUB_USER=kinow
JUPYTERHUB_SERVER_NAME=
JUPYTERHUB_API_URL=http://127.0.0.1:8081/hub/api
JUPYTERHUB_ACTIVITY_URL=http://127.0.0.1:8081/hub/api/users/kinow/activity
JUPYTERHUB_BASE_URL=/
JUPYTERHUB_SERVICE_PREFIX=/user/kinow/
USER=kinow
HOME=/home/kinow
SHELL=/bin/bash
```

Then `1.0.0`:

```bash
(venv) kinow@ranma:~/Development/python/workspace/jupyterhub$ jupyterhub --version
1.0.0
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-1' coro=<JupyterHub.launch_instance_async() done, defined at /home/kinow/Development/python/workspace/jupyterhub/jupyterhub/app.py:2477> exception=SystemExit(0)>
# Normal exception in 1.0.0, fixed in 1.1.0, then
(venv) kinow@ranma:~/Development/python/workspace/jupyterhub$ jupyterhub
# ... again logs, and finally
--- Args ---
['--port=47673']
--- Env ---
PATH=...
LANG=en_NZ.UTF-8
JUPYTERHUB_API_TOKEN=587bb1132f664b4980a3e0240cd20ab8
JPY_API_TOKEN=587bb1132f664b4980a3e0240cd20ab8
JUPYTERHUB_CLIENT_ID=jupyterhub-user-kinow
JUPYTERHUB_HOST=
JUPYTERHUB_OAUTH_CALLBACK_URL=/user/kinow/oauth_callback
JUPYTERHUB_USER=kinow
JUPYTERHUB_SERVER_NAME=
JUPYTERHUB_API_URL=http://127.0.0.1:8081/hub/api
JUPYTERHUB_ACTIVITY_URL=http://127.0.0.1:8081/hub/api/users/kinow/activity
JUPYTERHUB_BASE_URL=/
JUPYTERHUB_SERVICE_PREFIX=/user/kinow/
USER=kinow
HOME=/home/kinow
SHELL=/bin/bash
```

So `JUPYTERHUB_SERVICE_PREFIX` is present in the three versions tested.

From the description in the issue linked, @mj-harvey , I guess it could be an issue with the authenticator, or with the configuration of the hub. Might be worth to quickly confirm there is nothing in the `jupyterhub_config.py` that is filtering env vars (there's a config for removing certain variables).

If you find nothing, test this dummy spawner above. Check if that prints the variable with the following in a test `jupyterhub_config.py`:

```
c.Spawner.args = []
c.Spawner.cmd = ['print-spawner']
c.JupyterHub.spawner_class = 'jupyterhub.spawner.LocalProcessSpawner'
```

(you need to put `print-spawner` somewhere in your `$PATH`; as I use `venv`, I simply copy it with `+x` linux permission to `venv/bin/print-spawner`).

If you see the variable in the log output when starting the Hub and logging in, then that might eliminate an issue in JupyterHub, and let you focus searching for the issue elsewhere :+1: 

Cheers
Bruno

**Comment by kinow** [comment]
I guess it could be something changed in authenticators too @mj-harvey . I don't have a lot of experience with authenticators in JupyterHub, but I know you can control what is passed down to an authenticator (see `auth_state` in the authenticators Wiki I think). Something might have changed there, in which case, you would only have to figure out which configuration key you need to update.

**Comment by manics** [comment]
It sounds like this is an issue with a spawner rather than JupyterHub, so I'm closing this issue. If you investigate this further and think it's a bug in JupyterHub please open a new issue with full instructions for reproducing your deployment. Thanks!

**Comment by metasim** [comment]
@mj-harvey We're having the same problem... did you figure out a workaround?
