### ISSUE TITLE
JupyterHub running whitout root (multi-user)

### ISSUE THREAD

**Issue by adgonz** [jupyterhub/jupyterhub#321]
Hello,

First of all i wanna say that i new in this website. I'm trying using jupyterhub to use multiple notebooks. if i start the server with root, i can login with several users. But if i start the server with not root user i only can login with this user and i want to login with more users. I leve the server trace:

```
[jupyter@python hub]$ jupyterhub --debug
[D 2015-10-14 09:58:55.564 JupyterHub application:250] Config changed:
[D 2015-10-14 09:58:55.564 JupyterHub application:251] {'JupyterHub': {'log_level': 10}}
[D 2015-10-14 09:58:55.564 JupyterHub application:528] Attempting to load config file jupyterhub_config.py in path None
[D 2015-10-14 09:58:55.565 JupyterHub application:531] Attempting to load config file jupyterhub_config.json in path None
[D 2015-10-14 09:58:55.566 JupyterHub application:548] Loaded config file: /usr/local/pr/ipython/share/jupyter/hub/jupyterhub_config.py
[D 2015-10-14 09:58:55.567 JupyterHub application:250] Config changed:
[D 2015-10-14 09:58:55.568 JupyterHub application:251] {'JupyterHub': {'log_level': 10}, 'Spawner': {'args': ['--debug', '--profile=PHYS131']}, 'Authenticator': {'admin_users': {'jupyter', 'prueba'}}}
[I 2015-10-14 09:58:55.570 JupyterHub app:518] Loading cookie_secret from /usr/local/pr/ipython/share/jupyter/hub/jupyterhub_cookie_secret
[D 2015-10-14 09:58:55.571 JupyterHub app:579] Connecting to db: sqlite:///jupyterhub.sqlite
[W 2015-10-14 09:58:55.639 JupyterHub app:257] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[I 2015-10-14 09:58:55.654 JupyterHub app:654] Not using whitelist. Any authenticated user will be allowed.
[D 2015-10-14 09:58:55.657 JupyterHub app:730] Loaded users: 
     jupyter admin
      prueba admin
[I 2015-10-14 09:58:55.668 JupyterHub app:1032] Hub API listening on http://localhost:8081/hub/
[I 2015-10-14 09:58:55.675 JupyterHub app:789] Starting proxy @ http://*:8000/
[D 2015-10-14 09:58:55.675 JupyterHub app:790] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8000', '--api-ip', 'localhost', '--api-port', '8001', '--default-target', 'http://localhost:8081']
09:58:55.996 - info: [ConfigProxy] Proxying http://*:8000 to http://localhost:8081
09:58:55.999 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
[D 2015-10-14 09:58:56.087 JupyterHub app:818] Proxy started and appears to be up
[I 2015-10-14 09:58:56.088 JupyterHub app:1055] JupyterHub is now running at http://localhost:8000/
[I 2015-10-14 09:59:05.549 JupyterHub log:100] 302 GET / (@10.20.113.47) 3.36ms
[I 2015-10-14 09:59:05.559 JupyterHub log:100] 302 GET /hub (@10.20.113.47) 0.84ms
[I 2015-10-14 09:59:05.576 JupyterHub log:100] 302 GET /hub/ (@10.20.113.47) 1.04ms
[E 2015-10-14 09:59:05.618 JupyterHub web:2584] Could not open static file '/usr/local/pr/ipython/share/jupyter/hub/static/css/style.min.css'
[E 2015-10-14 09:59:05.618 JupyterHub web:2584] Could not open static file '/usr/local/pr/ipython/share/jupyter/hub/static/components/requirejs/require.js'
[I 2015-10-14 09:59:05.631 JupyterHub log:100] 200 GET /hub/login (@10.20.113.47) 43.19ms
[W 2015-10-14 09:59:05.731 JupyterHub log:100] 404 GET /hub/static/css/style.min.css (@10.20.113.47) 5.00ms
[W 2015-10-14 09:59:05.737 JupyterHub log:100] 404 GET /hub/static/components/requirejs/require.js (@10.20.113.47) 0.98ms
[I 2015-10-14 09:59:14.802 JupyterHub spawner:365] Spawning jupyterhub-singleuser --user=prueba --port=52268 --cookie-name=jupyter-hub-token-prueba --base-url=/user/prueba --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api --ip=localhost --debug --profile=PHYS131
[E 2015-10-14 09:59:14.814 JupyterHub orm:378] Unhandled error starting prueba's server: Exception occurred in preexec_fn.
[E 2015-10-14 09:59:14.829 JupyterHub web:1496] Uncaught exception POST /hub/login?next= (10.20.113.47)
    HTTPServerRequest(protocol='http', host='10.20.113.45:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='10.20.113.47', headers={'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36', 'Referer': 'http://10.20.113.45:8000/hub/login', 'X-Forwarded-Port': '8000', 'X-Forwarded-Proto': 'http', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Content-Length': '31', 'Connection': 'close', 'X-Forwarded-For': '10.20.113.47', 'Host': '10.20.113.45:8000', 'Origin': 'http://10.20.113.45:8000', 'Upgrade-Insecure-Requests': '1', 'Accept-Language': 'es-ES,es;q=0.8', 'Cache-Control': 'max-age=0'})
    Traceback (most recent call last):
      File "/usr/local/pr/ipython/lib/python3.3/site-packages/tornado/web.py", line 1415, in _execute
        result = yield result
      File "/usr/local/pr/ipython/lib/python3.3/site-packages/jupyterhub/handlers/login.py", line 73, in post
        yield self.spawn_single_user(user)
      File "/usr/local/pr/ipython/lib/python3.3/site-packages/jupyterhub/handlers/base.py", line 285, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/usr/local/pr/ipython/lib/python3.3/site-packages/jupyterhub/orm.py", line 388, in spawn
        raise e
      File "/usr/local/pr/ipython/lib/python3.3/site-packages/jupyterhub/orm.py", line 369, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/pr/ipython/lib/python3.3/site-packages/jupyterhub/spawner.py", line 367, in start
        preexec_fn=self.make_preexec_fn(self.user.name),
      File "/usr/local/pr/ipython/lib/python3.3/subprocess.py", line 819, in __init__
        restore_signals, start_new_session)
      File "/usr/local/pr/ipython/lib/python3.3/subprocess.py", line 1449, in _execute_child
        raise child_exception_type(err_msg)
    RuntimeError: Exception occurred in preexec_fn.
    
[D 2015-10-14 09:59:14.837 JupyterHub base:400] No template for 500
[E 2015-10-14 09:59:14.853 JupyterHub log:99] {
      "Content-Type": "application/x-www-form-urlencoded", 
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36", 
      "Referer": "http://10.20.113.45:8000/hub/login", 
      "X-Forwarded-Port": "8000", 
      "X-Forwarded-Proto": "http", 
      "Accept-Encoding": "gzip, deflate", 
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", 
      "Content-Length": "31", 
      "Connection": "close", 
      "X-Forwarded-For": "10.20.113.47", 
      "Host": "10.20.113.45:8000", 
      "Origin": "http://10.20.113.45:8000", 
      "Upgrade-Insecure-Requests": "1", 
      "Accept-Language": "es-ES,es;q=0.8", 
      "Cache-Control": "max-age=0"
    }
[E 2015-10-14 09:59:14.854 JupyterHub log:100] 500 POST /hub/login?next= (@10.20.113.47) 162.18ms
[W 2015-10-14 09:59:14.924 JupyterHub log:100] 404 GET /hub/static/css/style.min.css (@10.20.113.47) 2.56ms
[W 2015-10-14 09:59:14.931 JupyterHub log:100] 404 GET /hub/static/components/requirejs/require.js (@10.20.113.47) 3.89ms
[D 2015-10-14 10:03:56.126 JupyterHub orm:157] Fetching GET http://localhost:8001/api/routes
[D 2015-10-14 10:08:56.120 JupyterHub orm:157] Fetching GET http://localhost:8001/api/routes
```

Thank you

**Comment by minrk** [comment]
To run with the default setup, the Hub needs to be root. You can use a [sudospawner](https://github.com/jupyter/sudospawner) to run as a less privileged user, but it is [a lot more work](https://github.com/jupyter/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges) to set up.

**Comment by adgonz** [comment]
Hi minrk,

How can i configure sudospawner?

**Comment by minrk** [comment]
That may mean that the sudo permissions are not set up correctly. It can be difficult to do exactly right, and there are few symptoms of incorrect configuration beyond "it doesn't work." What OS? Can you share your sudoers file?

**Comment by adgonz** [comment]
The OS is Centos 6.6 and sudoers file:

## Sudoers allows particular users to run various commands as
## the root user, without needing the root password.
##
## Examples are provided at the bottom of the file for collections
## of related commands, which can then be delegated out to particular
## users or groups.
## 
## This file must be edited with the 'visudo' command.

## Host Aliases
## Groups of machines. You may prefer to use hostnames (perhaps using 
## wildcards for entire domains) or IP addresses instead.
# Host_Alias     FILESERVERS = fs1, fs2
# Host_Alias     MAILSERVERS = smtp, smtp2

## User Aliases
## These aren't often necessary, as you can use regular groups
## (ie, from files, LDAP, NIS, etc) in this file - just use %groupname 
## rather than USERALIAS
# User_Alias ADMINS = jsmith, mikem

## Command Aliases
## These are groups of related commands...

## Networking
# Cmnd_Alias NETWORKING = /sbin/route, /sbin/ifconfig, /bin/ping, /sbin/dhclient, /usr/bin/net, /sbin/iptables, /usr/bin/rfcomm, /usr/bin/wvdial, /sbin/iwconfig, /sbin/mii-tool

## Installation and management of software
# Cmnd_Alias SOFTWARE = /bin/rpm, /usr/bin/up2date, /usr/bin/yum

## Services
# Cmnd_Alias SERVICES = /sbin/service, /sbin/chkconfig

## Updating the locate database
# Cmnd_Alias LOCATE = /usr/bin/updatedb

## Storage
# Cmnd_Alias STORAGE = /sbin/fdisk, /sbin/sfdisk, /sbin/parted, /sbin/partprobe, /bin/mount, /bin/umount

## Delegating permissions
# Cmnd_Alias DELEGATING = /usr/sbin/visudo, /bin/chown, /bin/chmod, /bin/chgrp 

## Processes
# Cmnd_Alias PROCESSES = /bin/nice, /bin/kill, /usr/bin/kill, /usr/bin/killall

## Drivers
# Cmnd_Alias DRIVERS = /sbin/modprobe

# Defaults specification

#
# Disable "ssh hostname sudo <cmd>", because it will show the password in clear. 
#         You have to run "ssh -t hostname sudo <cmd>".
#
Defaults    requiretty

#
# Refuse to run if unable to disable echo on the tty. This setting should also be
# changed in order to be able to use sudo without a tty. See requiretty above.
#
Defaults   !visiblepw

#
# Preserving HOME has security implications since many programs
# use it when searching for configuration files. Note that HOME
# is already set when the the env_reset option is enabled, so
# this option is only effective for configurations where either
# env_reset is disabled or HOME is present in the env_keep list.
#
Defaults    always_set_home

Defaults    env_reset
Defaults    env_keep =  "COLORS DISPLAY HOSTNAME HISTSIZE INPUTRC KDEDIR LS_COLORS"
Defaults    env_keep += "MAIL PS1 PS2 QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE"
Defaults    env_keep += "LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES"
Defaults    env_keep += "LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE"
Defaults    env_keep += "LC_TIME LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY"

#
# Adding HOME to env_keep may enable a user to run unrestricted
# commands via sudo.
#
# Defaults   env_keep += "HOME"

Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin

## Next comes the main part: which users can run what software on 
## which machines (the sudoers file can be shared between multiple
## systems).
## Syntax:
##
## 	user	MACHINE=COMMANDS
##
## The COMMANDS section may have other options added to it.
##
## Allow root to run any commands anywhere 
root	ALL=(ALL) 	ALL

## Allows members of the 'sys' group to run networking, software, 
## service management apps and more.
# %sys ALL = NETWORKING, SOFTWARE, SERVICES, STORAGE, DELEGATING, PROCESSES, LOCATE, DRIVERS

## Allows people in group wheel to run all commands
# %wheel	ALL=(ALL)	ALL

## Same thing without a password
# %wheel	ALL=(ALL)	NOPASSWD: ALL

## Allows members of the users group to mount and unmount the 
## cdrom as root
# %users  ALL=/sbin/mount /mnt/cdrom, /sbin/umount /mnt/cdrom

## Allows members of the users group to shutdown this system
# %users  localhost=/sbin/shutdown -h now

#########################################
##  Modificaaciones Jupyter  ############
#########################################

# comma-separated whitelist of users that can spawn single-user servers
Runas_Alias JUPYTER_USERS = jupyter, prueba

# the command(s) the Hub can run on behalf of the above users without needing a password
# the exact path my differ, depending on how sudospawner was installed
Cmnd_Alias JUPYTER_CMD = /usr/local/pr/ipython/bin/sudospawner

# actually guve the Hub user permision to run the above command on behalf
#of the above users without prompting for a password
jupyter ALL=(JUPYTER_USERS) NOPASSWD:JUPYTER_CMD

########################################
##  Modificaciones Jupyter  ############
######################################## 
## Read drop-in files from /etc/sudoers.d (the # here does not mean a comment)
#includedir /etc/sudoers.d

**Comment by minrk** [comment]
What do you get from:

    sudo -u rhea groups

and

    ls -l /etc/shadow /etc/passwd

**Comment by adgonz** [comment]
sudo -u rhea groups
rhea shadow

ls -l /etc/shadow /etc/passwd
-rw-r--r--. 1 root root    1018 oct   9 14:52  /etc/passwd
----r-----.  1 root root      980 oct   13 113:22  /etc/shadow

**Comment by minrk** [comment]
The shadow file must be readable by the shadow group, as [described in the doc](https://github.com/jupyter/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges#linux):

    sudo chgrp shadow /etc/shadow
    sudo chmod g+r /etc/shadow

**Comment by adgonz** [comment]
I just do what you tell me. Now i start the server and can login with the same user, but when i login with another user, jupyter says invalid username or password but they are both correct

**Comment by 0xABAB** [comment]
Why would the run as root option be the default and not the secure option?

**Comment by minrk** [comment]
The simple option is the default. Not all spawners and/or authenticators do. Sudospawner is the most complicated and difficult route to take, so it would not make a good default.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!
