### ISSUE TITLE
AttributeError: 'Service' object has no attribute 'groups'

### ISSUE THREAD

**Issue by m-mayran** [jupyterhub/jupyterhub#3217]
Hi,
[Running 1.2.0b1]

I am running the following code in a service to get information about my user:

```py
import requests
api_url = os.environ['JUPYTERHUB_API_URL']
api_token = os.environ['JUPYTERHUB_API_TOKEN']
r = requests.get(api_url + '/user', headers={'Authorization': 'token %s' % api_token,})
```

The request seems to authenticate ok (I would get a 403 if I put /users for example) but it returns the following:

```py
Uncaught exception GET /hub/api/user (172.17.0.2)
    HTTPServerRequest(protocol='http', host='172.17.0.2:8081', method='GET', uri='/hub/api/user', version='HTTP/1.1', remote_ip='172.17.0.2')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/apihandlers/users.py", line 38, in get
        self.write(json.dumps(self.user_model(user)))
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/apihandlers/base.py", line 193, in user_model
        'groups': [g.name for g in user.groups],
    AttributeError: 'Service' object has no attribute 'groups'
```

**Comment by Kangsan-Jeon** [comment]
I had a same issue, when I called /user GET API.
Another API(/users GET, /users/{name}/tokens GET, etc.) were operated well except above API.
In my case, users were authenticated by LDAP.

**Comment by minrk** [comment]
This should fail with 403 as it is now, but we can also make it work for services. The request being made here is asking to identify the service itself, not your user. If you want information about your users, it should send the oauth token associated with the user accessing your service, not the service's token itself.
