### ISSUE TITLE
Error while accessing jupyterhub on another machine.

### ISSUE THREAD

**Issue by darshanraikanungo** [jupyterhub/jupyterhub#3245]
I have created a JupyterHub on azure server. I am able to access it on azure server using this url 127.0.0.1:8000, but not able to access it from another machine. For another machine i am using different url like IpOfServer:800. Please guide me if anything need to add in config file or need to change anything

**Comment by manics** [comment]
In general we ask that JupyterHub GitHub issues are used for bugs and development discussions, with support being handled on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions. Hope you understand 😀.
