### ISSUE TITLE
How to spin up specific docker container using dockerspawner in docker hub

### ISSUE THREAD

**Issue by abinassahoo** [jupyterhub/jupyterhub#3248]
## Description
Hi Team,
can anyone please help with any documentation for below use case.

I want to create a specific notebook server container (elyra/nb2kg) for each user to connect to my Enterprise Gateway from jupyter hub using dockerspawner. I followed the documentation [here](https://blog.jupyter.org/on-demand-notebooks-with-jupyterhub-jupyter-enterprise-gateway-and-kubernetes-e8e423695cbf) but this is using helm, whereas I wanted to do the solution using dockerspawner.

## Environment

- Enterprise Gateway Version 2.3.0.dev1
- Platform:  Docker
- Others : Jupyterhub 1.1.0

**Comment by manics** [comment]
Hi. I noticed you've also created an issue at https://github.com/jupyter/enterprise_gateway/issues/901 which is more relevant than this repo, so I'm closing this.
In general if you create multiple issues please cross-link them, everyone's always busy so it helps to know if an issue has been partly or fully answered somewhere else. Hope you understand!

**Comment by abinassahoo** [comment]
> Hi. I noticed you've also created an issue at [jupyter/enterprise_gateway#901](https://github.com/jupyter/enterprise_gateway/issues/901) which is more relevant than this repo, so I'm closing this.
> In general if you create multiple issues please cross-link them, everyone's always busy so it helps to know if an issue has been partly or fully answered somewhere else. Hope you understand!

Hello, yes as per the suggestion from jupyter/enterprise_gateway#901 I have created this request here to get the documentation on dockerspawner, as this comes under jupyter hub. Kindly suggest some documentation .
