### ISSUE TITLE
404  Not Found error for downloading files with spaces

### ISSUE THREAD

**Issue by z3ky** [jupyterhub/jupyterhub#3249]
### Bug description

Getting "404 : Not Found" error when trying to download a file with spaces in its name 

#### Expected behaviour

Download the file

#### Actual behaviour

404 : Not Found
You are requesting a page that does not exist!

### How to reproduce

1. Go to jupyterhub
2. New -> Text File
3. Rename to My File.c
4. Go back to the hub
5. Mark the file
6. Click download

### Your personal set up

 - OS:
Server: Ubuntu 18.04 LTS
Tested on macOS 10.15 with Safari and Chrome
 
 - Version:
Jupyterhub 1.1.0
 
 - Configuration:
Using DockerSpwaner with jupyterhub/singleuser  image

**Comment by manics** [comment]
Hi :wave: This sounds like either a configuration problem or an issue with Jupyter notebook. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!
