### ISSUE TITLE
Make test of subdomain based user routes more reliable

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#3251]
Sometimes our test suite fail because a user server was a bit slow to start. We have a test that wants to spot a response like http://myuser.myhub.com rather than http://myhub.com/hub/start-pending/myuser, so it use `assert url.startswith`.

![image](https://user-images.githubusercontent.com/3837114/98830156-5c4a2c00-243a-11eb-9dc7-a32ac6479003.png)

This is something to be fixed here:

https://github.com/consideRatio/jupyterhub/blob/4a17441e5ac04bb7022515dd0e9bd0f141a95efd/jupyterhub/tests/test_pages.py#L321-L335

**Comment by minrk** [comment]
We have logic for this in another test already. Copied in #3253.
