### ISSUE TITLE
can't open file 'cull_idle_servers.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by EnziinSystem** [jupyterhub/jupyterhub#3256]
I installed jupyterhub and it works.
Now, I add the config idle-culler
```
import sys
c.JupyterHub.services = [
    {
        'name': 'cull-idle',
        'admin': True,
        'command': [sys.executable, 'cull_idle_servers.py', '--timeout=300'],
    }
]
```
Restart the service
```
sudo systemctl restart jupyterhub.service
sudo systemctl status jupyterhub.service
```
It raises an error.
```
Nov 13 08:02:14 jupyterhub jupyterhub[1491]: [I 2020-11-13 08:02:14.243 JupyterHub app:2722] JupyterHub is now running at http://:8000
Nov 13 08:02:14 jupyterhub jupyterhub[1516]: /opt/jupyterhub/bin/python3: can't open file 'cull_idle_servers.py': [Errno 2] No such file or directory
```
The file cull_idle_servers.py did not include in package jupyterhub, isn't it?

**Comment by manics** [comment]
Thanks for pointing that out, I've transferred the issue to the JupyterHub repo.

The idle culler was moved into it's own repo https://github.com/jupyterhub/jupyterhub/pull/3114
but it looks like this section of the docs wasn't updated.
