### ISSUE TITLE
Remove or disable download options in Jupyterhub

### ISSUE THREAD

**Issue by karthikmariapp** [jupyterhub/jupyterhub#3260]
Hi, I would like to know how to remove or disable download options in jupyterhub. The reason is that I wanted to restrict users in downloading any confidential data to their local environment. Jupyterhub version 1.0.0 and notebook version 6.1.1 are used.

Download options currently available and which I wanted to remove/disable are as follows:
1. Select a file (eg *.xlsx, *.csv etc) using checkbox -> click "Download" button
2. Open a file (eg: *.xlsx, *.csv etc) -> From File menu -> click "Download"
3. Open a *.ipynb notebook file -> From File menu -> click "Download as" -> select a file format to download

Kindly provide a solution for the above requirement

**Comment by manics** [comment]
In general we ask that JupyterHub GitHub issues are used for bugs and development discussions, with support being handled on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions. Hope you understand 😀.
