### ISSUE TITLE
Jupyterhub deployed with Docker behind Apache proxy, get Blocking Cross Origin API request for /jhub/user/USERNAME/api/contents.

### ISSUE THREAD

**Issue by etiennekintzler** [jupyterhub/jupyterhub#3268]
### Bug description

I can't create a file from the jupyter notebook (spawn by jupyterhub).

#### The error in the UI
![image](https://user-images.githubusercontent.com/17943873/99724853-89d74b00-2ab4-11eb-8a69-12d409e10bba.png)

#### The error in the console 
```python
[W 2020-11-19 20:49:22.157 SingleUserNotebookApp handlers:390] Blocking Cross Origin API request for /jhub/user/etienne/api/contents.  Origin: https://DOMAIN-NAME, Host: localhost:8000
[W 2020-11-19 20:49:22.158 SingleUserNotebookApp handlers:613] Not Found
[W 2020-11-19 20:49:22.159 SingleUserNotebookApp log:181] 404 POST /jhub/user/etienne/api/contents (etienne@::ffff:172.17.0.1) 3.19ms
```

The same problem arise when I create a fake notebook.ipynb (using echo): the kernel won't start (since it is launched from the same POST request on /api/sessions I guess)

### Setup

- Jupyterhub is deployed using the Docker image https://hub.docker.com/r/jupyterhub/jupyterhub/ and the following command 

`docker run -p 8000:8000  jupyterhub/jupyterhub jupyterhub  --url='http://:8000/jhub/'  --NotebookApp.allow_origin='*' --NotebookApp.token='' --debug`

- Apache used as reverse proxy config with the following config :

```
<VirtualHost *:80>
  ServerName DOMAIN-NAME
</VirtualHost>

 # For JupyterHub
 RewriteRule /jhub/(.*) ws://localhost:8000/jhub/$1 [P,L]
 RewriteRule /jhub/(.*) http://localhost:8000/jhub/$1 [P,L]
 ProxyPass /jhub/ http://localhost:8000/jhub/
 ProxyPassReverse /jhub/ http://localhost:8000/jhub/


<VirtualHost *:443>
  ServerName DOMAIN-NAME

  # Jupyterhub
  RewriteEngine On
  RewriteCond %{HTTP:Connection} Upgrade [NC]
  RewriteCond %{HTTP:Upgrade} websocket [NC]
  RewriteRule /(.*) ws://127.0.0.1:8000/$1 [P,L]

  <Location "/jhub/">
    ProxyPreserveHost on
    ProxyPass         http://127.0.0.1:8000/jhub/
    ProxyPassReverse  http://127.0.0.1:8000/jhub/
  </Location>
</VirtualHost>

```
- the bash command `sudo a2enmod ssl rewrite proxy proxy_http proxy_wstunnel` has been ran as indicated in https://jupyterhub.readthedocs.io/en/stable/reference/config-proxy.html

Also, not shown here but i tried to ass `Header set Access-Control-Allow-Origin "DOMAIN-NAME"` at various location of my apache config without any success. 

The config seems okay since it works on another VM of the same subnet but with JupyterHub installed manually (i.e not deployed using Docker).

### Your personal set up
- OS:  Ubuntu 18.04.3 LTS
- `notebook `version : 6.1.5 (installed using pip since not contains in the docker image)
- `jupyterhub` version : 1.2.1.
- user "etienne" is added after connecting to the container and running the bash command `adduser`.

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!

**Comment by etiennekintzler** [comment]
Thanks for the tip @manics, I've just posted it on discourse ! 

Just out of curiosity, why not adding the label "configuration" or "question" and let the issue open ? I've seen some issues about CORS (which ofc didn't solve mind) on this project and they weren't close immediately.

**Comment by manics** [comment]
We're pushing all new support and configuration related issues to Discourse so we can keep GitHub for discussions directly related to development. If there are issues that were opened before we brought in this policy, or which may contain a potential bug, they may remain open.

**Comment by etiennekintzler** [comment]
I found the issue.

The default site /etc/apache2/sites-available/000-default-le-ssl.conf (added by `certbot --apache` I think) was enabled and had the **same ServerName** as the config I've shown in the issue, which was creating conflict.

After disabling the website (or changing the servername) the CORS issue disappears.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/cors-error-deploy-in-docker-and-behind-apache-proxy/6835/2
