### ISSUE TITLE
how to custom login.html when i want to type in chinese charatcter in template

### ISSUE THREAD

**Issue by jindaxiang** [jupyterhub/jupyterhub#3275]
### Bug description

how to custom login.html when i want to type in chinese charatcter in template

#### Expected behaviour

show chinese character in login.html

#### Actual behaviour

500 : Internal Server Error
invalid start byte

### Your personal set up

 - OS:
 
Ubuntu 18.04
 - Version:
 
JupyterHub 1.0.0
 - Configuration:

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!
