### ISSUE TITLE
options_form bypassed when /hub/spawn receives query params in 1.2.1

### ISSUE THREAD

**Issue by dirkcgrunwald** [jupyterhub/jupyterhub#3277]
### Bug description
In a test setup of z2jh 0.10.3 using microk8s (see https://github.com/dirkcgrunwald/zero-to-jupyterhub-microk8s/tree/master/fancypants ) I use a list of profiles for students to select containers appropriate for their class. Normally when students log in, they are presented with a profile list with those options.

When I use Google Oauth and 0.10.3 the user isn't given a chance to select appropriate profile when they initially log in. If they go to the "Hub control panel", kill the server and start a new server the profile is shown.

The repo mentioned above uses CSS/js to make the display fancy but deleting that and using the plain vanilla profile list has the same behavior -- the "default" profile is used.

#### Expected behaviour
I would expect to be able to select a profile when I first authenticate using Google Oauth.

#### Actual behaviour
Profile list is not shown but is available when using the "Hub control panel" login.

### How to reproduce
The git repo above is a cookbook for deploying using microk8s. If one adds in Google oauth into the specified "fancy" configuration that has multiple profiles, it occurs. If you remove google oauth the profile list is shown on login.

### Your personal set up
Documented in the github repo above.

 - OS: Ubuntu 20.04
 - Version: 0.10.3
 - Configuration: https://github.com/dirkcgrunwald/zero-to-jupyterhub-microk8s/blob/master/fancypants/z2jh-config-fancy.yaml

with google oauth added in (not shown, but the same as I use in 0.9 in other setups)

**Comment by consideRatio** [comment]
I think I have seen this in passing, and assume it relates to some change in JupyterHub's logic so I moved it to this repository from z2jh. Z2JH 0.10.3 maps to JupyterHub 1.2.1, so if this reproduce, it is a regression between JupyterHub 1.1.0 and JupyterHub 1.2.1 somewhere.

**Comment by consideRatio** [comment]
This reproduced for me exactly like you described @dirkcgrunwald! If I logged out and then visited my hub I wasn't presented with profile_list options, which is just KubeSpawner's fancy way of the JupyterHub native Spawner's options_form (?) I think.

```
[I 2020-11-21 02:59:40.463 JupyterHub log:181] 302 GET / -> /hub/ (@192.168.0.171) 0.80ms
[I 2020-11-21 02:59:40.852 JupyterHub log:181] 302 GET /hub/ -> /hub/login (@192.168.0.171) 0.70ms
[I 2020-11-21 02:59:41.083 JupyterHub log:181] 302 GET /hub/login -> /hub/oauth_login (@192.168.0.171) 0.76ms
[I 2020-11-21 02:59:41.291 JupyterHub oauth2:104] OAuth redirect: 'https://l2l.sundellopensource.com/hub/oauth_callback'
[I 2020-11-21 02:59:41.293 JupyterHub log:181] 302 GET /hub/oauth_login -> https://github.com/login/oauth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fl2l.sundellopensource.com%2Fhub%2Foauth_callback&client_id=1eab886a3b5b6bf3151f&state=[secret] (@192.168.0.171) 1.64ms
[I 2020-11-21 02:59:42.702 JupyterHub log:181] 200 GET /hub/metrics (@192.168.20.91) 3.68ms
[I 2020-11-21 02:59:43.026 JupyterHub base:746] User logged in: consideratio
[I 2020-11-21 02:59:43.044 JupyterHub reflector:201] watching for pods with label selector='component=singleuser-server' in namespace default
[I 2020-11-21 02:59:43.074 JupyterHub reflector:201] watching for events with field selector='involvedObject.kind=Pod' in namespace default
[I 2020-11-21 02:59:43.077 JupyterHub log:181] 302 GET /hub/oauth_callback?code=[secret]&state=[secret] -> /hub/spawn?code=[secret]&state=[secret] (@192.168.0.171) 565.52ms
[I 2020-11-21 02:59:43.333 JupyterHub log:181] 302 GET /hub/spawn?code=[secret]&state=[secret] -> /hub/spawn-pending/consideratio?code=[secret]&state=[secret] (consideratio@192.168.0.171) 32.25ms
[I 2020-11-21 02:59:43.333 JupyterHub spawner:1840] Attempting to create pvc claim-consideratio, with timeout 3
[I 2020-11-21 02:59:43.358 JupyterHub spawner:1852] PVC claim-consideratio already exists, so did not create new pvc.
[I 2020-11-21 02:59:43.362 JupyterHub spawner:1805] Attempting to create pod jupyter-consideratio, with timeout 3
[I 2020-11-21 02:59:43.541 JupyterHub pages:398] consideratio is pending spawn
[I 2020-11-21 02:59:43.560 JupyterHub log:181] 200 GET /hub/spawn-pending/consideratio?code=[secret]&state=[secret] (consideratio@192.168.0.171) 20.48ms
[I 2020-11-21 03:00:04.497 JupyterHub proxy:320] Checking routes
[I 2020-11-21 03:00:05.790 JupyterHub base:893] User consideratio took 22.483 seconds to start
[I 2020-11-21 03:00:05.790 JupyterHub proxy:258] Adding user consideratio to proxy /user/consideratio/ => http://192.168.30.177:8888
```

**Comment by manics** [comment]
This sounds like https://github.com/jupyterhub/jupyterhub/issues/3247
Fixed by https://github.com/jupyterhub/oauthenticator/pull/386

**Comment by manics** [comment]
The |2JH OAuthenticator was updated in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1918
Can you try the latest dev release of this chart?

**Comment by consideRatio** [comment]
@manics thanks for identifying this! I released 0.10.4 with the oauthenticator-bump!

**Comment by dirkcgrunwald** [comment]
Yes - I used the 0.10.4 release from github (helm chart not there yet) and this fixes the problem. Thanks for the quick identification & release!

**Comment by consideRatio** [comment]
Thank you for reporting back @dirkcgrunwald :heart: :tada:! I'll close this issue with that!
