### ISSUE TITLE
Jupyterhub - docker image gives 404 if I try to shutdown a running kernel

### ISSUE THREAD

**Issue by cwaldbieser** [jupyterhub/jupyterhub#328]
I pulled the jupyter/jupyterhub image from Docker, added a user, and started testing out Jupyterhub.  I noticed that when I am in the notebook and have run a kernel, if I go back to the notebook home I can see the running kernel.  If I tick the check box and press the "shutdown" button, I get an HTTP 404 in the jupyterhub logs: 

    [W 2015-11-03 20:05:08.840 hubuser log:47] 404 DELETE /user/hubuser/api/sessions/%5Bobject%20Object%5D

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
