### ISSUE TITLE
On saving changes in one notebook reflecting same changes in the Other notebook(another directory)

### ISSUE THREAD

**Issue by Sabhrant** [jupyterhub/jupyterhub#3290]
Hello,

I am experiencing a strange issue with the JupyterHub. On saving one notebook on clicking Save and checkpoint same changes are saved/reflected in another notebook (previously created with a different name). I have tried below things to troubleshoot:

1.Restarting the service.
2.Deleting the checkpoint files
3.Deleting the Runtime sessions and restarting the service.

Any help will be appreciated.

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!
