### ISSUE TITLE
Cannot configure authentication for the JupyterLab spawned by BatchSpawner

### ISSUE THREAD

**Issue by kimchitsigai** [jupyterhub/jupyterhub#3296]
### Bug description
I'm running JupyterHub 1.2.2 + BatchSpawner for Slurm + JupyterLab 2.2.9 on Ubuntu 18.04.
The JupyterHub PAM authentication authentication works fine.
The BatchSpawner for Slurm creates the JupyterLab which runs on a different node and works fine.
For security constraints in my company, I want to configure a password authentication for JupyterLab, but I can't see how to do it or if it's possible.

#### Expected behaviour
JupyterLab displays an authentication form.

#### Actual behaviour
After a successful PAM authentication for JupyterHub, the user gets access to ,the JupyterLab main page, without being asked to enter a password. 

### Your personal set up

 - OS: Ubuntu 18.04
 
 - Configuration: JupyterHub 1.2.2 + BatchSpawner for Slurm (20.11.0) + JupyterLab 2.2.9 
 
- in jupyterhub_config.py: c.Spawner.cmd = ['jupyterhub-singleuser'] and c.Spawner.default_url = '/lab'

- in ~/.jupyter, I've configured c.NotebookApp.passwdord and I've run the 'jupyter notebook password' command.

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!
