### ISSUE TITLE
Error writing /proc/self/loginuid: Operation not permitted / set_loginuid failed

### ISSUE THREAD

**Issue by ilmoi** [jupyterhub/jupyterhub#3299]
### Bug description
After following [Install JupyterHub and JupyterLab from the ground up](https://jupyterhub.readthedocs.io/en/1.2.2/installation-guide-hard.html) line for line, I manage to navigate to JH and log in, but then I get:
```
Spawn failed: Server at http://127.0.0.1:48387/jupyter/user/ubuntu/ didn't respond in 30 seconds
```
Digging into the logs:
```
Dec 02 18:55:49 ip-172-31-16-128 python[2385]: pam_loginuid(login:session): Error writing /proc/self/loginuid: Operation not permitted
Dec 02 18:55:49 ip-172-31-16-128 python[2385]: pam_loginuid(login:session): set_loginuid failed
Dec 02 18:55:50 ip-172-31-16-128 python[2385]: pam_unix(login:session): session opened for user ubuntu by (uid=0)
Dec 02 18:55:50 ip-172-31-16-128 jupyterhub[2385]: [W 2020-12-02 18:55:50.014 JupyterHub auth:1065] Failed to open PAM session for ubuntu: [PAM Error 14] Cannot make/remove an entry for the specified session
Dec 02 18:55:50 ip-172-31-16-128 jupyterhub[2385]: [W 2020-12-02 18:55:50.014 JupyterHub auth:1066] Disabling PAM sessions from now on.
Dec 02 18:55:50 ip-172-31-16-128 jupyterhub[2385]: [I 2020-12-02 18:55:50.025 JupyterHub spawner:1455] Spawning jupyterhub-singleuser --port=48387
Dec 02 18:55:50 ip-172-31-16-128 jupyterhub[2385]: [I 2020-12-02 18:55:50.451 JupyterHub log:181] 302 GET /jupyter/hub/spawn/ubuntu -> /jupyter/hub/spawn-pending/ubuntu (ubuntu@87.110.171.29) 1004.63ms
```

#### Expected behaviour
The server should have started.

#### Actual behaviour
It seems there is an issue with the spawner / PAM / permissions? I'm completley new to this so I'm struggling to untangle on my own.

### How to reproduce
Follow [Install JupyterHub and JupyterLab from the ground up](https://jupyterhub.readthedocs.io/en/1.2.2/installation-guide-hard.html) line for line, until the very end.

### Your personal set up

 - OS: Ubuntu 18.04
 - Version:
```
jupyter==1.0.0
jupyter-client==6.1.7
jupyter-console==6.2.0
jupyter-core==4.7.0
jupyter-telemetry==0.1.0
jupyterhub==1.2.2
jupyterlab==2.2.9
jupyterlab-pygments==0.1.2
jupyterlab-server==1.2.0
```
 - Configuration: everything as per tutorial.

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!
