### ISSUE TITLE
JupyterHub switches kernel with "Python (default)" from instrucitions

### ISSUE THREAD

**Issue by WesleyTheGeolien** [jupyterhub/jupyterhub#3301]
### Bug description
I am following the [JupyterHub](https://jupyterhub.readthedocs.io/en/stable/installation-guide-hard.html) installation guide. 

In the step where we set up a new virtual (conda) enviroment to be used Hub wise as the default python interpreter the kernel gets switched back automatically to the python interpreter used to install the Hub.

Note that using a different display name to Python (default) solves the problem. As you can see in the logs I have installed the same interpreter with a different display name and this kernel works.

![Kapture 2020-12-07 at 15 53 48](https://user-images.githubusercontent.com/18068320/101365762-772a8780-38a4-11eb-84f9-726d1c3014a9.gif)

#### Expected behaviour
I would expect it to use the virtual environment specified and not revert back to the jupyterhub python interpreter

#### Actual behaviour
Reverts back to jupyterhub install python interpreter

### How to reproduce
Follow instructions in [Guide](https://jupyterhub.readthedocs.io/en/stable/installation-guide-hard.html#install-a-default-conda-environment-for-all-users)

### Your personal set up
 - OS:
 Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
 - Version(s):

- <details><summary>Logs</summary>
```
/opt/jupyterhub/share/jupyter/kernels$ /opt/jupyterhub/bin/jupyter kernelspec list
Available kernels:
  python           /opt/jupyterhub/share/jupyter/kernels/python
  python-pangeo    /opt/jupyterhub/share/jupyter/kernels/python-pangeo
  python3          /opt/jupyterhub/share/jupyter/kernels/python3
  python2          /usr/share/jupyter/kernels/python2
```

```
/opt/jupyterhub/share/jupyter/kernels$ cat /opt/jupyterhub/share/jupyter/kernels/python/kernel.json
{
 "argv": [
  "/opt/conda/envs/python/bin/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python (default)",
 "language": "python"
```

```
/opt/jupyterhub/share/jupyter/kernels$ cat /opt/jupyterhub/share/jupyter/kernels/python-pangeo/kernel.json
{
 "argv": [
  "/opt/conda/envs/python/bin/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python (pangeo)",
 "language": "python"
```
</details>

**Comment by pawsaw** [comment]
Any news on this? This issue still exists.

**Comment by manics** [comment]
Sorry for the delay in responding. JupyterHub launches your singleuser server, but it doesn't play any part in managing your kernels or other environment, that's all handled by JupyterLab or Jupyter Notebook.

You could try posting on the community forum if you need more help https://discourse.jupyter.org/

**Comment by pawsaw** [comment]
> Sorry for the delay in responding. JupyterHub launches your singleuser server, but it doesn't play any part in managing your kernels or other environment, that's all handled by JupyterLab or Jupyter Notebook.
> 
> You could try posting on the community forum if you need more help https://discourse.jupyter.org/

@manics Thanks for your response. 

Unfortunately it doesn't help at all. 

**I strictly followed the instructions from the _jupyterhub_ documentation** 

And here is the issue. How is this related to "support"?

imho **Feb 17th 2021** this issue is still **open**.

**Comment by WesleyTheGeolien** [comment]
Hi @manics and @pawsaw 

Thanks for the reply. Yeah I managed to get around it :) From my initial post: 

```
Note that using a different display name to Python (default) solves the problem. As you can see in the logs I have installed the same interpreter with a different display name and this kernel works.
```

I haven't retested though since.

I think I was more aiming and just raising the case, maybe all that needs changing is the documentation a little bit. 

I also agree the "problem" may lie deeper and not at all be a JupyterHub issue but rather a Jupyter kernel issue eg. "I can not create a kernel with the name Python (default)"
