### ISSUE TITLE
After successful LDAP authentication group ids are not assigned to the user's jupyter process

### ISSUE THREAD

**Issue by alexvorobiev** [jupyterhub/jupyterhub#331]
In our environment gids come through LDAP, the groups are not defined locally. Even after successful PAM/LDAP authentication the kernel only shows group "Staff" (which is defined locally) but none of the groups I actually need to get access to any common working directories, NFS shares, etc. The gids get assigned at https://github.com/jupyter/jupyterhub/blob/master/jupyterhub/spawner.py#L324 Is grp.getgrall() LDAP-aware?

**Comment by rsandhu1** [comment]
Can you please share your PAM/LDAP configuration steps?

**Comment by alexvorobiev** [comment]
My understanding is Jupyterhub uses PAM by default. PAM itself is configured on my system (RHEL 6.5) to use pam_sss.so (which connects to LDAP, etc) for everything which is fairly standard configuration for enterprise users. I also have RStudio Server on the same system and it has no problems launching R sessions with correct gids after PAM authentication.

**Comment by rsandhu1** [comment]
Thanks Alex. I have written to system admin to see why I am getting following error. 
PAM Error 14: 'Cannot make/remove an entry for the specified session

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
