### ISSUE TITLE
Disk I/O Error on Saving/AutoSave notebooks

### ISSUE THREAD

**Issue by Sabhrant** [jupyterhub/jupyterhub#3319]
### Bug description
On saving the notebook the following error pops out.
![image](https://user-images.githubusercontent.com/19758574/103207778-2e0aa800-4925-11eb-8375-f41eb4322fcd.png)

**Below are the error logs:**

[E 2020-12-28 04:12:33.042 SingleUserNotebookApp log:158] 500 PUT /user/pmp_user/api/contents/jupyter_notebooks/PySpark_Tutorial.ipynb (pmp_user@::ffff:10.10.42.126) 2.64ms
[I 2020-12-28 04:13:24.700 SingleUserNotebookApp log:158] 200 GET /user/pmp_user/api/contents/jupyter_notebooks/PySpark_Tutorial.ipynb?content=0&_=1609128682619 (pmp_user@::ffff:10.10.42.126) 1.56ms
[I 2020-12-28 04:13:24.709 SingleUserNotebookApp handlers:164] Saving file at /jupyter_notebooks/PySpark_Tutorial.ipynb
[E 2020-12-28 04:13:24.710 SingleUserNotebookApp filemanager:481] Error while saving file: jupyter_notebooks/PySpark_Tutorial.ipynb disk I/O error
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 466, in save
        self.check_and_sign(nb, path)
      File "/usr/local/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 492, in check_and_sign
        self.notary.sign(nb)
      File "/usr/local/lib/python3.7/site-packages/nbformat/sign.py", line 449, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/usr/local/lib/python3.7/site-packages/nbformat/sign.py", line 207, in store_signature
        if not self.check_signature(digest, algorithm):
      File "/usr/local/lib/python3.7/site-packages/nbformat/sign.py", line 239, in check_signature
        (datetime.utcnow(), algorithm, digest),
    **sqlite3.OperationalError: disk I/O error**

 - The root directory for the jupyter is on the EFS mount 
 - OS:
Amazon Linux 2
 - Version(s):
![image](https://user-images.githubusercontent.com/19758574/103208038-b9843900-4925-11eb-9718-97df541de8b3.png)

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. It's most likely due to your storage configuration rather than a bug in JupyterHub. If you're still having problems could you post this as a support question on https://discourse.jupyter.org/ instead? Thanks!
