### ISSUE TITLE
setting up jupyterhub behind shibboleth authentication

### ISSUE THREAD

**Issue by moscicki** [jupyterhub/jupyterhub#332]
We are setting up jupyterhub behind SSO (shibboleth) in our organisation. Is there a shibboleth authentication plugin available for jupyterhub?

If not,  the setup we have in mind is the following: the authentication step and authentication cookies are managed by the fronted web server (apache/mod_shib) which also acts as a reverse proxy to jupyterhub. All the traffic from reverse proxy should be trusted by the jupyterhub the user name comes in a header for each request. The unix users exist locally. What's best way to add such support (as an option) to jupyter hub? Is it in Base Handler? e.g.: https://github.com/jupyter/jupyterhub/blob/498c062ee001d5926b601f67648f1993826852c5/jupyterhub/handlers/base.py#L159

Does this approach make sense for you? If it does, would you be interested in having such an option integrated in the upstream jupyterhub codebase?

**Comment by minrk** [comment]
I don't think anyone's done a native shibboleth plugin for JupyterHub, so putting it behind Apache should work. You will probably still want to set up a custom Authenticator with a login handler that logs in automatically based on whatever headers/etc. the shibboleth system sets on its way through.

**Comment by minrk** [comment]
I've been meeting with people at CERN this week, and they actually have JupyterHub running behind Shibboleth (via Apache) *right now*. They will make the JupyterHub-related bits public soon, when they get the chance.

**Comment by mbmilligan** [comment]
@moscicki I am doing essentially this right now using the remote_user authenticator, and it was a very simple drop-in: https://github.com/cwaldbieser/jhub_remote_user_authenticator

If you need to capture additional information from the request headers that mod_shib generates, there is another open issue discussing how to do that.

**Comment by nigwil** [comment]
@minrk Any idea if CERN have released (or about to) their support for Shibboleth'd JupyterHub? thanks.

**Comment by dpiparo** [comment]
@nigwil We are working hard on the various rough angles of our distributed system, DMaaS (https://indico.cern.ch/event/397113/session/12/contribution/199). We are working hard to make our system portable and installable anywhere.

**Comment by minrk** [comment]
CERN has to do some security review before releasing their auth code, but I would recommend using the remote_user authenticator linked above for integrating with Shibboleth behind Apache.

**Comment by willingc** [comment]
@minrk Has CERN released their auth code for Shibboleth yet?

**Comment by minrk** [comment]
@dpiparo any update on the Shibboleth JupyterHub code being public?

**Comment by ksambaiah** [comment]
Any one is successful with shibboleth apache as front end? Could you please share configuration if so?

**Comment by bitnik** [comment]
based on @mbmilligan  and @minrk 's suggestion we managed to run jhub behind shibboleth login via nginx FastCGI: https://github.com/gesiscss/jhub_shibboleth_auth

the documentation still not extensive but we like to help if there are any issues. and any contribution is really appreciated.
