### ISSUE TITLE
Google Oauth Does Not Work - Err: 400 Client Id missing although it is not

### ISSUE THREAD

**Issue by drsiyarb** [jupyterhub/jupyterhub#3320]
So i am trying to deploy Jupyterhub to teach students about EEG processing. I have succesfully deployed a jupyterhub installation using this guide; https://pythonforundergradengineers.com/add-google-oauth-and-system-service-to-jupyterhub.html on https://lab.golembio.com but i am stuck at google oauth stage.

I have followed the instructions step by step, and added this code to my jupyterhub_config.py:

```
from oauthenticator.google import LocalGoogleOAuthenticator

c.JupyterHub.authenticator_class = LocalGoogleOAuthenticator

c.LocalGoogleOAuthenticator.create_system_users = True

c.LocalGoogleOAuthenticator.hosted_domain = ['https://lab.golembio.com', 'https://golembio.com']
c.LocalGoogleOAuthenticator.login_service = 'Google Login'
c.LocalGoogleOAuthenticator.oauth_callback_url = 'https://lab.golembio.com/hub/oauth_callback'
c.LocalGoogleOAuthenticator.oauth_client_id = 'xxxx'
c.LocalGoogleOAuthenticator.oauth_client_secret = 'xxxxx'
#c.JupyterHub.cookie_secret_file = '/srv/jupyterhub/jupyterhub_cookie_secret'
c.Authenticator.add_user_cmd = ['adduser', '-q', '--gecos', '""', '--disabled-password', '--force-badname']

```
ps: I copy and paste correct oauth client id and oauth client secret to the code...

Now when i open lab.golembio.com there is an option to log in with google but after i click it it returns an error:

Error 400: invalid_request Missing required parameter: client_id

I could not figure out what is the problem?

**Comment by consideRatio** [comment]
Please refer to the forum for future support.

The configuration option is named client_id, not oauth_client_id (confirmed [here](https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/oauth2.py#L290)).

**Comment by drsiyarb** [comment]
Hi, Thanks for your help!

I will use the forum for these questions...

Cheers.
