### ISSUE TITLE
Failed to use jupyterlab with jupyterhub.service on Ubuntu18.04

### ISSUE THREAD

**Issue by jet-chien** [jupyterhub/jupyterhub#3321]
### Bug description

The notebook works fine on my server:
![image](https://user-images.githubusercontent.com/67193495/103262400-c6fdf980-49df-11eb-9020-64a1988c4a1f.png)

but when I switch path from ```tree?``` to ```lab?```, I got 404 not found error:
![image](https://user-images.githubusercontent.com/67193495/103262452-f0b72080-49df-11eb-815d-68e3bc63ed3c.png)

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!
