### ISSUE TITLE
When the jupyterhub starts, how can it read the jupyterhub_config.py in real time.

### ISSUE THREAD

**Issue by Chenjingliang1** [jupyterhub/jupyterhub#3322]
If i modify jupyterhub_config.py when the jupyterhub starting ,how can jupyterhub know the changes.

**Comment by consideRatio** [comment]
When JupyterHub starts, it will read and execute the jupyterhub_config.py file, but if that file it is modified after that, it won't reload and re-execute.

Please look to the forum for answers to questions like these! Thanks for being an active member of our community =)
