### ISSUE TITLE
Shared folder not visible for existing users

### ISSUE THREAD

**Issue by yash64** [jupyterhub/jupyterhub#3331]
I have installed jupyterhub in linux servers and I have successfully logged in with all users available and everything seems to work fine. Now I have a new requirement where users have to be able to share their files/notebooks with other users.

So I have created a group with all jupyterhub users and created permissions and as suggested [here](https://tljh.jupyter.org/en/latest/howto/content/share-data.html#option-2-create-a-read-only-shared-folder-for-data) in docs I have created symbolic link and tested with new user. After logging in with new user credentials I am able to see shared folder but unable to see shared folder for already existing users. How to enable this to existing users as well.

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!

**Comment by yash64** [comment]
> Hi 👋 This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!

Thanks. I have raised this in https://discourse.jupyter.org/ the same day but unfortunately I have not received any help till now. Is there any way to tag it to someone?

**Comment by gepcel** [comment]
If I'm guessing right, a linked folder (pointed to the shared folder) was created while the user account was created. So you might try finding that and making a linked folder for existing users manually.
