### ISSUE TITLE
JupyterLab 3.0 extensions with backend server extension do not start-up

### ISSUE THREAD

**Issue by krassowski** [jupyterhub/jupyterhub#3340]
JupyterLab 3.0 transitioned to the new `jupyter_server`.

JupyterHub users who experience problems with JupyterLab 3.0 extensions such as:
- `jupyterlab-git`,
- `jupyterlab_code_formatter`,
- `jupyterlab-lsp`

(or any other extension that expects `jupyter_server` to be available) need to configure their JupyterHub to use `jupyter_server` for these extensions to work. This can be done by setting an environment variable as described in the [JupyterHub documentation](https://jupyterhub.readthedocs.io/en/latest/reference/config-user-env.html?highlight=Switching#switching-to-jupyter-server).

If you do not like environment variables, some users have reported success with adjusting their `jupyterhub_config.py` to include:

```python
c.Spawner.environment = {
    'JUPYTERHUB_SINGLEUSER_APP': "jupyter_server.serverapp.ServerApp"
}
```

**Comment by krassowski** [comment]
Dear maintainers, please feel free to remove the bug label and/or close if you feel that it does not belong here, but I believe that this should be exposed more for some time (maybe even pinned) in order to help users who transition to JupyterLab 3.0.

**Comment by manics** [comment]
Hi! We try to keep GitHub issues for recording bugs and managing development of this project. This is clearly useful information though, so would you mind writing this up on the [Jupyter community forum](https://discourse.jupyter.org/) where support for this project is handled? It also has a wider audience so it's likely more of the community will see it before they run into problems. Thanks!

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterlab-server-extension-on-jupyterhub/11531/6
