### ISSUE TITLE
PAM error in second login

### ISSUE THREAD

**Issue by victor201314** [jupyterhub/jupyterhub#3354]
When i start jupyterhub by systemctl,i can loging once by admin user.then i get "invalie username or password".in /var/log/secure,i get 'Feb  8 11:16:51 localhost passwd: pam_unix(passwd:chauthtok): password changed for xxxxx 
Feb  8 11:17:06 localhost python: pam_unix(login:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=xxxxx'

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!
