### ISSUE TITLE
Replace generic 403 error message with more informative text

### ISSUE THREAD

**Issue by 1kastner** [jupyterhub/jupyterhub#3356]
### Proposed change
When a user is declined because s/he is on the block list or not on the not-block-list, then I would like to provide an informative text instead of a generic 403 error that is maybe difficult to understand for not-IT people.

**Comment by 1kastner** [comment]
the not-block-list is called `allowed_users` at https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/authentication.html#adding-a-whitelist. After a quick code search, I guess the place where it happens should be at https://github.com/jupyterhub/jupyterhub/blob/4e7936056744cdad31d608388a349207196efa56/jupyterhub/handlers/base.py#L751 - if the OAuthenticator fails, instead of the `if authenticated:` branch the else branch is entered. For the user just a simple "it failed" message is produced. In my case I would like to give them the hint that maybe they try to login at the wrong JupyterHub or that they are maybe not signed up for the course the JupyterHub was setup for. As my case is rather specific, maybe this should be some custom html in the authenticator like at https://github.com/jupyterhub/jupyterhub/blob/4e7936056744cdad31d608388a349207196efa56/jupyterhub/auth.py#L180 ?

**Comment by manics** [comment]
A customisable error message for failed logins sounds like a good usability improvement. I'm not sure if it needs to go in this repo or the oauthenticator repo though, compare
https://github.com/jupyterhub/jupyterhub/blob/f220bbca84bae96948c7db987ccd936d6bab8d3e/jupyterhub/handlers/login.py#L159-L161
with
https://github.com/jupyterhub/oauthenticator/blob/a4aac191c16cf6281f3d346615aefa75702b02d7/oauthenticator/oauth2.py#L226-L227

**Comment by 1kastner** [comment]
For my own specific case, it would be totally fine to have that in the oauthenticator repo. I just thought that maybe other authenticators could also benefit from such an optional feature? I am not sure according to which design philosophy new features are added on which level. But especially the todo you showed in the code looked very much like a good starting point!
