### ISSUE TITLE
c.JupyterHub.services.*.api_token has a minimum length required?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#3367]
### Bug description

When configuring a JupyterHub service with an api_token that is 7 characters (ddd4444) instead of 8 characters (dddd4444) or more, the JupyterHub responds with 403 when it otherwise don't.

I expected to get some warning or early error if it had a minimum length, rather than a runtime failure 403 response to REST API requests.

### How to reproduce

This was discovered in the JupyterHub Helm chart's CI system where making the dev-config.yaml specify `hub.services.test.apiToken=ddd4444` led to 403 errors accessing the REST api while it would work fine if set to an eight characters long token.

The JupyterHub configuration to reproduce without z2jh may be...

```python
c.JupyterHub.services = [
    {
        "name": test,
        "admin": true,
        "api_token": "ddd4444",
    }
]
```

And then sending a Rest API request with the oken.

### Setup

JupyterHub 1.3.0 was used in z2jh at this point in time.

**Comment by minrk** [comment]
Yup! Tokens have a minimum length which is checked, but there was a typo in handling the error when tokens are rejected causing it to be silently ignored. Fixed by #3370.
