### ISSUE TITLE
Pass OAuth access_token to the Spawner

### ISSUE THREAD

**Issue by dolfim** [jupyterhub/jupyterhub#337]
Hi,

Is it possible to pass the access_token generated during the OAuth authentication to the notebooks?

Our goal would be to authenticate the users against our API and setup the notebooks such that they don't have to authenticate again when using the API from their scripts.

**Comment by minrk** [comment]
Yes, you can specify extra env variables that the Spawner should set for the server's process. If these are user-specific, in your Spawner subclass you can override `Spawner.user_env`:

```python
def user_env(self):
    env = super().user_env()
    env['access_token'] = access_token_for_user(self.user.name)
    return env
```

**Comment by dolfim** [comment]
Thanks. This is for sure a needed step.

But if I get it right, the Authenticator will only return the username, it cannot return other things like the access_token that was obtained by the OAuth login.
In our case the function ```access_token_for_user``` would still need the full user credentials to obtain another token, but the authenticator already has a valid token.

Is it possible to pass other content than the username between the Authenticator and the Spawner? Or this would always involve some intermediate storage (db, file to disk, etc). Is maybe the ENV propagated automatically?

**Comment by minrk** [comment]
It is, when a Spawner starts, it calls `Authenticator.pre_spawn_start(user, spawner)`, which you can use to allow the Authenticator to add things to the env. This hook is new in JupyterHub 0.3.

**Comment by yuvipanda** [comment]
Hmm, so where can Authenticators store an access token so it survives restarts? Is there a getstate / savestate equivalent? I can't seem to find any...

**Comment by yuvipanda** [comment]
I tried using user.state, which doesn't work because https://github.com/jupyter/jupyterhub/blob/master/jupyterhub/spawner.py#L142 clears the state on every restart :(

**Comment by yuvipanda** [comment]
I'm using a combination of #346 and https://github.com/jupyter/oauthenticator/pull/24 to implement this, and it totally works :D \o/ :dancer: :dancers:

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved by @yuvipanda's combination. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!

**Comment by anderk57** [comment]
The solution from @yuvipanda didn't fully resolve the issue for me when jupyterhub restarts or loses its state.  The authenticate() method only runs if the jupyterhub cookie has not already been set.  If jupyterhub process restarts and the browser has a cookie from a previous jupyterhub process, then the  pre_spawn_start() context will not have the user state.  

My solution was to set a separate cookie "other_access_token" in authenticate....

`    @gen.coroutine
    def authenticate(self, handler, data=None):
        // ... fetch token using oauth                                                                                                           
        handler.set_cookie('other_access_token', resp_json['access_token'])`



The cookie will be proxied with each request to the notebook, and can be used in a custom handler 

`class HelloWorldHandler(IPythonHandler):
    def get(self):
        http_client = HTTPClient()
        url = ...
        auth_str = "Bearer "+self.get_cookie("other_access_token")
        req = HTTPRequest(url,
                          method="GET",
                          headers={"authorization": auth_str
                                  }
                          )
        resp = http_client.fetch(req)
        respstr = resp.body.decode('utf8', 'replace')
        self.finish(respstr)`

**Comment by michec81** [comment]
Sorry which is the final solution so?, I cannot get the cookie from the JupyterHub notebook console.
I simply added this portion of code but it's called only as the whole server restart.

sudo vim /usr/local/lib/python3.6/dist-packages/oauthenticator/generic.py

    #added by CINECA
    @gen.coroutine
    def pre_spawn_start(self, user, spawner):
        auth_state = yield user.get_auth_state()
        if not auth_state:
             return
        spawner.environment['OAUTH2_AUTHORIZE_TOKEN'] = auth_state['access_token']
        self.log.info("pre_spawn_start executing...")
        self.log.info("Passing access token variable to user spawn process %s", auth_state['access_token'])
    #----------------

from the web console:

import os
os.environ


bearer = os.environ["OAUTH2_AUTHORIZE_TOKEN"]
bearer -> is the old bearer until I do not restart the whole Jupyter server

--

I also added:

handler.set_cookie('OAUTH2_AUTHORIZE_TOKEN_NEW', resp_json['access_token'])

in the authenticate() method (generic.py) and I find the token in the browser console, however I am not able to read it from the jupyter notebook.

So which method should I modify in the JupyterHub modules, or which one I need to call from the notebook console?

thanks

**Comment by ltalirz** [comment]
I guess the recommended way is now explained here:
https://jupyterhub.readthedocs.io/en/stable/reference/authenticators.html#authentication-state

**Comment by betatim** [comment]
To deal with renewing and all that we built https://github.com/OpenHumans/jhoauth-refresh which is a notebook extension for periodically fetching a [token from a service](https://github.com/wildtreetech/ohjh/tree/master/images/refresher) that takes care of refreshing the token and keeping the auth_state of the user up to date.

**Comment by inviscid** [comment]
Hi.  Sorry to chime in so late on this issue but there seems to be a supported way of injecting the auth_token into the pod but we cannot figure out how to actually make it work.  This is exactly what we want to do:

> Inject an auth token from GitHub authenticator into user pod

It is listed as an option using the extraConfig parameter here: [schema.yaml](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/schema.yaml#L328)

We have tried setting it using c.Spawner.environment but the value never shows up in the pod.

I know the other way to handle this is to extend the Authenticator class but that requires forking the repo.  This then requires updates to helm charts and such, basically knocking us off the main development path.  We would really not like to fork and this extraConfig looks like the right way to do this but we cannot get it to work.

Any help, hints, or examples would be greatly appreciated.

**Comment by michec81** [comment]
Many thanks, if I get any way to solve it I'll let you know

Regards,
M

**Comment by inviscid** [comment]
This is a more detailed explanation of the issue: https://discourse.jupyter.org/t/arguments-passed-to-spawner-do-not-seem-to-propagate-to-user-pods/1387

**Comment by scivm** [comment]
I solved this z2j in case anyone is curious.  I updated the discussion at https://discourse.jupyter.org/t/arguments-passed-to-spawner-do-not-seem-to-propagate-to-user-pods/1387

**Comment by michec81** [comment]
thanks I will check this!

**Comment by scivm** [comment]
I guess there is still the issue of the token expiring.  For my needs I am using the token to check groups and then mounting volumes to the user pods based on those so I only need it at the server start when it is still active.   I know some have implemented refresh tokens but I am not that far yet.
