### ISSUE TITLE
'invalid frame header' error

### ISSUE THREAD

**Issue by juyiwang7** [jupyterhub/jupyterhub#3372]
### 'invalid frame header' error

I use iframe to embed a jupyterhub and use jupyterlab as the default editor. But I can't forward my command to terminal through websocket request. Has anyone ever encountered such a problem?

The URL request in question is: 'websocket : /user/xx/terminals/websocket/1?token=xxx  '

![](https://i.loli.net/2021/03/03/b5y6BjZ8cGfzJR2.png)

### About configuration:

Jupyterhub is installed with helm. Some configuration files are as follows:

```
values.yaml


configuration about hub:
extraConfig: 
    hub: |
      c.JupyterHub.tornado_settings = { 'headers': { 'Content-Security-Policy': "frame-ancestors * self  http://127.0.0.1:3000 http://localhost:3000"}}
    spawner: |
      c.Spawner.args = ["--NotebookApp.tornado_settings={'headers':{'Content-Security-Policy': 'frame-ancestors * slef http://localhost:3000 http://127.0.0.1:3000'}}"]
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']

```

The following is my request forwarding process. I don't think there is a problem in nginx or FRP forwarding process, because it can be used normally when it is not in iframe

![](https://i.loli.net/2021/03/03/JzODq56X7Trh3j4.png)

The front end uses' HTTP proxy middleware 'for forwarding

If someone has encountered similar problems, please don't hesitate to let me know，Thanks♪(･ω･)ﾉ

**Comment by juyiwang7** [comment]
```
server {
        listen 5687;
        location /{
                proxy_pass http://10.96.211.100;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header Access-Control-Allow-Origin '*';
	        proxy_set_header Host $http_host;
		#proxy_set_header Host $host;
        	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_http_version      1.1;
		proxy_set_header 	X-Scheme $scheme;
                proxy_set_header        Upgrade $http_upgrade;
                proxy_set_header        Connection $connection_upgrade;
		#proxy_set_header	Origin '';
		proxy_buffering 	off;
		proxy_send_timeout      90;
		proxy_read_timeout      90;

        }
   }

```
This is nginx config. I use nodeport to forward all requests to the cluster and forward this nodeport to the external service through nginx.

**Comment by wkinglin** [comment]
how to fix it
