### ISSUE TITLE
failure, during installation of jupyter hub as system service

### ISSUE THREAD

**Issue by EgorSemenov** [jupyterhub/jupyterhub#3379]
RHEL 7.9
**I am able to run manually with `jupyterhub`**
Also, I have this:
` [root@user bin]# cat /lib/systemd/system/jupyterhub.service
[Unit]
Description=Jupyterhub

[Service]
Environment="PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/lib/node_modules/configurable-http-proxy/bin"
ExecStart=/usr/local/bin/jupyterhub --JupyterHub.spawner_class=sudospawner.SudoSpawner
WorkingDirectory=/etc/jupyterhub

[Install]
WantedBy=multi-user.target`

**When executing the following commands:**
`systemctl daemon-reload
systemctl start jupyterhub.service
systemctl status jupyterhub.service
`
**get this:**
`(base) [root@oppscoring bin]# systemctl status jupyterhub.service
● jupyterhub.service - Jupyterhub
   Loaded: loaded (/usr/lib/systemd/system/jupyterhub.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2021-03-10 08:29:54 CST; 5s ago
  Process: 10051 ExecStart=/usr/local/bin/jupyterhub --JupyterHub.spawner_class=sudospawner.SudoSpawner (code=exited, status=1/FAILURE)
 Main PID: 10051 (code=exited, status=1/FAILURE)

Mar 10 08:29:54 oppscoring.sl.bluecloud.ibm.com jupyterhub[10051]: To see all available configurables, use `--help-all`
Mar 10 08:29:54 oppscoring.sl.bluecloud.ibm.com jupyterhub[10051]: Examples
Mar 10 08:29:54 oppscoring.sl.bluecloud.ibm.com jupyterhub[10051]: --------
Mar 10 08:29:54 oppscoring.sl.bluecloud.ibm.com jupyterhub[10051]: generate default config file:
Mar 10 08:29:54 oppscoring.sl.bluecloud.ibm.com jupyterhub[10051]: jupyterhub --generate-config -f /etc/jupyterhub/jupyterhub_config.py
Mar 10 08:29:54 oppscoring.sl.bluecloud.ibm.com jupyterhub[10051]: spawn the server on 10.0.1.2:443 with https:
Mar 10 08:29:54 oppscoring.sl.bluecloud.ibm.com jupyterhub[10051]: jupyterhub --ip 10.0.1.2 --port 443 --ssl-key my_ssl.key --ssl-cert my_ssl.cert
Mar 10 08:29:54 oppscoring.sl.bluecloud.ibm.com systemd[1]: jupyterhub.service: main process exited, code=exited, status=1/FAILURE
Mar 10 08:29:54 oppscoring.sl.bluecloud.ibm.com systemd[1]: Unit jupyterhub.service entered failed state.
Mar 10 08:29:54 oppscoring.sl.bluecloud.ibm.com systemd[1]: jupyterhub.service failed.`
**Found that this error usually connected with incorrect variables for jupyterhub and configurable-http-proxy in the environment. Added them - get the same. 
Any suggestions?**

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/install-jupyterhub-as-system-service/8273/1

**Comment by manics** [comment]
I'm going to close this since it's a support issue, and as you've probably realised these are best handled on the Discourse forum
