### ISSUE TITLE
Publish container image to Amazon ECR Public Gallery

### ISSUE THREAD

**Issue by jakob-keller** [jupyterhub/jupyterhub#3390]
### Proposed change

Currently, the CI/CD pipeline pushes container images to Docker Hub for public consumption. I propose to also push the container images to Amazon ECR Public Gallery.

### Alternative options

Official container images are already available at [Docker hub](https://hub.docker.com/r/jupyterhub/jupyterhub), being subject to recently introduced [download rate limits](https://docs.docker.com/docker-hub/download-rate-limit/). To work around rate limits, a Docker Hub account may be used, which complicates any automated deployment or CI/CD pipeline that relies on jupyterhub container images.

### Who would use this feature?

Potentially anyone, in particular those who use official jupyterhub container images directly or as base images within an AWS environment.

### (Optional): Suggest a solution

The resulting container images need to be tagged and pushed to Amazon ECR Public Gallery as part of the CI/CD pipeline. AWS provides [documentation](https://docs.aws.amazon.com/AmazonECR/latest/public/getting-started-cli.html).

I am unfamiliar with this project's CI/CD pipeline, but could look into it and provide a PR, if that helps. There would need to be someone to provide official AWS credentials at some point, as environment variables or else.

**Comment by manics** [comment]
I had a quick look at the docs, I couldn't see anything about it having a completely free option Docker Hub. As far as I can tell it requires a billable account for storage- is that correct?

I think it'd be nice to switch to using the Docker GitHub Action to build and push images, it's something I've been meaning to investigate but haven't gotten round to. It'd certainly make pushing to other repos easier though, and perhaps deal with https://github.com/jupyterhub/jupyterhub/issues/2848

**Comment by jakob-keller** [comment]
> I had a quick look at the docs, I couldn't see anything about it having a completely free option Docker Hub. As far as I can tell it requires a billable account for storage- is that correct?

That is correct, however there is a [free tier](https://aws.amazon.com/ecr/pricing/) that applies to public repositories:

> [...] Amazon ECR offers you 50 GB-month of always-free storage for your public repositories.

That should be plenty to start with, shouldn't it? Also AWS might be willing to offer a discount or similar to ensure your container images are easily accessible to other (paying) AWS customers.

**Comment by jakob-keller** [comment]
There is also an option to show a [Verified badge](https://docs.amazonaws.cn/en_us/AmazonECR/latest/public/public-gallery.html), which would signal authenticity:

> AWS accounts that publish popular or commonly used images can request a Verified account badge by contacting support.

**Comment by yuvipanda** [comment]
Given that the JupyterHub DockerHub org now has a 'verified OSS' badge, which exempts us from download limits, I think we should close this one. For additional repositories, I personally prefer quay.io as well, given it has a much better free tier than AWS.
