### ISSUE TITLE
Newly create user group information not reflected in JupyterHub / terminal

### ISSUE THREAD

**Issue by kdzhao** [jupyterhub/jupyterhub#3391]
### Bug description

It seems when jupyterhub-singleuser starts, it reads in the user's group information (only) at that time. If user is added to new groups after that, the new groups won't take effect. 

### How to reproduce

1. On any Linux like environment, start the JupyterHub, login as a regular user. Open a terminal, in the terminal, type "id". Write down the groups it returns. 

2. In a separate session (ssh to the same host), create a new local group, and add the user to the new group. Like: 
groupadd -g 50000 my_new_group
usermod -a -G my_new_group myself

3. Now, in the JupyterHub, open a new terminal, in the terminal, type "id". 

#### Expected behaviour

I expect "my_new_group" will show up. 

#### Actual behaviour

"my_new_group" does not show up. 

But if I do "id myself", then "my_new_group" shows up. 

This prevent the user from using this new group. For example, if you do something like: 
chgrp my_new_group myFile
It will fail. 

#### Work around

If I kill my own server (basically force it to re-spawn) so it restarts, after it, it works as expected. 

"kill my own server" means, either use ps command to find my process and kill it, or go to menu -> file -> Hub Control Panel, to stop and restart my server. 

### Your personal set up
On Cent OS 7. 
jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : 4.7.7
ipython          : 7.16.1
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.8
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3

The Spawner command is like: 
c.Spawner.cmd = ['/opt/jupyterhub/bin/jupyterhub-singleuser']

**Comment by manics** [comment]
Hi! JupyterHub starts the singleuser servers, but it has no influence on what happens within those servers. For example the terminals you start are managed by Jupyter Notebook, JupyterLab, or whatever interface you're using.

In general Linux systems won't pick up a new group without logging in/out (it's actually a bit more complicated,
see for example https://superuser.com/questions/272061/reload-a-linux-users-group-assignments-without-logging-out).

If you need more help please ask on the [community forum](https://discourse.jupyter.org/).
