### ISSUE TITLE
JupyterHub Not allowing to delete non empty directory

### ISSUE THREAD

**Issue by pawanfalak** [jupyterhub/jupyterhub#3395]
I installed JupyterHub with latest version(1.3.0) but when I try to delete the non-empty directory it flashes error with Directory not empty. I also tried changing my jupyterhub_config.py file by setting both True and False to c.FileContentsManager.delete_to_trash , as mentioned here(https://github.com/jupyter/notebook/issues/4916), but it does not work. I also notice when I run the jupyter notebook and try deleting non-empty directory, it works there but I only encounter this when I run jupyterhub and try deleting non-empty directory.
Please let me know if any more information is needed or if there is any change in configuration needed on jupyterhub through which it allows to delete non-empty directory.

**Comment by manics** [comment]
Hi! JupyterHub starts the singleuser servers, but it has limited influence on what happens within those servers. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterhub-not-allowing-to-delete-non-empty-directory/8539/1
