### ISSUE TITLE
@-sign in username causes missing fonts for ipywidgets, the @-sign in the font URLs is replaced by %40

### ISSUE THREAD

**Issue by mariobuikhuizen** [jupyterhub/jupyterhub#3399]
### Bug description
@-sign in username causes missing fonts for ipywidgets, the @-sign in the font URLs is replaced by `%40`

For font files the @-sign is replaced by `%40`: http://localhost:8000/user/test%40test/nbextensions/jupyter-vuetify/d0066537ab6a4c6f8285a5aeb3ba5f09.woff2

For .js files the URL is correct: http://localhost:8000/user/test@test/nbextensions/jupyter-vuetify/index.js?v=20210406084436

Also, replacing `%40` with `@` of a font URL in the address bar of the browser downloads the font

### How to reproduce
Dockerfile:
```
FROM jupyterhub/jupyterhub

RUN pip install jupyter ipyvuetify

RUN useradd -m test@test -p "$(openssl passwd -1 test)"

RUN echo '\
{\n\
 "cells": [\n\
  {\n\
   "cell_type": "code",\n\
   "execution_count": null,\n\
   "id": "20861218",\n\
   "metadata": {},\n\
   "outputs": [],\n\
   "source": [\n\
     "import ipyvuetify as v\\n",\n\
     "\\n",\n\
     "v.Icon(children=[\\"mdi-thumb-up\\"])"\n\
   ]\n\
  }\n\
 ],\n\
 "metadata": {\n\
  "kernelspec": {\n\
   "display_name": "Python 3",\n\
   "language": "python",\n\
   "name": "python3"\n\
  },\n\
  "language_info": {\n\
   "codemirror_mode": {\n\
    "name": "ipython",\n\
    "version": 3\n\
   },\n\
   "file_extension": ".py",\n\
   "mimetype": "text/x-python",\n\
   "name": "python",\n\
   "nbconvert_exporter": "python",\n\
   "pygments_lexer": "ipython3",\n\
   "version": "3.8.2"\n\
  }\n\
 },\n\
 "nbformat": 4,\n\
 "nbformat_minor": 5\n\
}' > /home/test@test/fonts.ipynb &&\
 chown test@test /home/test@test/fonts.ipynb
```
1. `docker build -t atsign .`
2. `docker run -ti --rm -p 8000:8000 --name jupyterhub atsign jupyterhub`
3. Go to http://localhost:8000 in the browser
4. Login with `test@test` password: `test`
5. Open notebook fonts.ipynb
6. Open network tab in dev-tools in the browser
7. Reload page
8. Execute notebook
9. Find 404 status on the fonts being loaded  .woff2, .woff and ttf)

**Comment by mariobuikhuizen** [comment]
Maybe related to: https://github.com/jupyterhub/jupyterhub/issues/345?

**Comment by manics** [comment]
Hi! JupyterHub handles authentication and proxies the singleuser server, it doesn't interact with the notebook server. For example it won't distinguish between js files and font files in your notebook server, nor will it modify HTML contents returned by the notebook server. This suggests it may be a bug in the notebook or ipywidgets. Are you able to investigate this further?

**Comment by mariobuikhuizen** [comment]
Right, running ` jupyter notebook --NotebookApp.base_url='/test@test'` produces this issue.
