### ISSUE TITLE
Make the logging function configurable

### ISSUE THREAD

**Issue by Cadair** [jupyterhub/jupyterhub#340]
I have an instance of the JupyterHub running behind a load balancer / SSL off loader. I would like to change the logging function to log some extra headers from the requests, primarily the client IP which is added to a special header by the load balancer. I have hacked this to work by modifying `jupyterhub/log.py`, but I have had to do that in the source and it is very specific to me.

I looked into making the logging function configurable inside the Hub app, i.e. here: https://github.com/jupyter/jupyterhub/blob/master/jupyterhub/app.py#L850 but I could not work out how to use traitlets to specify a function name.

Is that a sensible approach?

**Comment by minrk** [comment]
We can use `traitlets.utils.importstring.import_item` to allow configurable values to be arbitrary functions:

```python
from traitlets.utils.importstring import import_item

class JupyterHub:
    ...
    log_function = Any(default_log_function)
    def _log_function_validate(self, value, obj):
        if isinstance(value, str):
            value = import_item(value)
        return value
```

**Comment by captainsafia** [comment]
I'd like to give this a go at some point this week or next.

**Comment by consideRatio** [comment]
Issue triage: I think JupyterHub's logging system supports some configuration at this point, closing this.
