### ISSUE TITLE
/usr/local/bin/[before-notebook.d/|start-notebook.d/]" causes: Spawn failed: The 'ip' trait of a Server instance expected a unicode string, not the NoneType None.

### ISSUE THREAD

**Issue by nmvega** [jupyterhub/jupyterhub#3404]
Dear Friends:

If a `DockerSpawned` notebook includes anything other than `zero-length` files, or no files at all in it's `script-hook` directories:

```
/usr/local/bin/before-notebook.d/
/usr/local/bin/start-notebook.d/
```

the following error occurs at Notebook `launch-time`:

```
Spawn failed: The 'ip' trait of a Server instance
expected a unicode string, not the NoneType None. 
```

Consider that even these trivial scripts cause this error:

```
root# cat /usr/local/bin/before-notebook.d/start-custom-services.sh
env     > /root/env_before-notebook.txt
ps -ef >> /root/env_before-notebook.txt

root# cat /usr/local/bin/start-notebook.d/start-custom-services.sh
env     > /root/env_start-notebook.txt
ps -ef >> /root/env_start-notebook.txt

Permissions for them are: 0x0755
```

If I delete the above files or zero them out, the problem disappears; but that isn't helpful for customizing notebooks at `launch-time`.

**Software versions**: Using `Dockerfile`s, I rebuilt my `JupyterHub` as well as my `JupyterLab` docker images today, so I'm using the `latest version` of everything. With apologies for not having the versions on hand to cite them here; they're all whatever `pip` and `conda` have in their repositories today (latest).

Any ideas? Thank you in advance.

**Comment by manics** [comment]
Hi :wave: This sounds like a problem with your notebook Docker image rather than a bug in JupyterHub. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? It would be helpful if you included your full Dockerfile there.

Thanks!

**Comment by nmvega** [comment]
@manics To be honest, I never have luck there. Why does it sound like an image problem rather than a bug?

**Comment by nmvega** [comment]
@manics I tried the `all-spark-notebook` which has a small script in `/usr/local/bin/before-notebook.d/`, and it doesn't cause the `launch-time` issue. While this may suggest a problem with my `notebook server image` as opposed to the `jupyterhub` image, we can't be sure (strange things happen).

The question remains how to debut this? Where the log files on `jupyterhub` or other ways to instrument this failure.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/dockerspawner-emits-spawn-failed-the-ip-trait-of-a-server-instance-expected-a-unicode-string-not-the-nonetype-none-on-a-docker-image-that-is-cloned-with-zero-changes-via-docker-1-commit/8897/1
