### ISSUE TITLE
Support pagination in the REST API

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#3405]
### Proposed change

Currently, our REST API does not support pagination. This blocks a number of features:

- Replacing our admin interface with a React app (https://github.com/jupyterhub/jupyterhub/pull/3398, https://github.com/jupyterhub/jupyterhub/issues/3039)
- Performance with large number of users (https://github.com/jupyterhub/jupyterhub/issues/2954)

To fix these, we should support pagination in the REST API

### Who would use this feature?

Anyone using the API, including core JupyterHub itself (with the React admin interface)

### (Optional): Suggest a solution

The following handlers seem the only ones needing pagination support:

1. Listing all users - https://github.com/jupyterhub/jupyterhub/blob/c5bfd2800542f977528720c0cc8c56684f0da380/jupyterhub/apihandlers/users.py#L56
2. List all groups - https://github.com/jupyterhub/jupyterhub/blob/c5bfd2800542f977528720c0cc8c56684f0da380/jupyterhub/apihandlers/groups.py#L38
3. List users in group - https://github.com/jupyterhub/jupyterhub/blob/c5bfd2800542f977528720c0cc8c56684f0da380/jupyterhub/apihandlers/groups.py#L77
4. List routes in proxy - https://github.com/jupyterhub/jupyterhub/blob/c5bfd2800542f977528720c0cc8c56684f0da380/jupyterhub/apihandlers/proxy.py#L15

SQLAlchemy should be fairly straightforward to paginate for 1-3, and 4 is just returning an in-memory datastructure, so should be easy to paginate as well.

**Comment by minrk** [comment]
Thanks for opening this! I thought we had an Issue already, but I realize after searching it was only discussed in related issues like #2954. It's been on my mental todo list for some time...

**Comment by minrk** [comment]
oops, closed by #3413
