### ISSUE TITLE
Add list of stopped named servers in /users/{name} API response

### ISSUE THREAD

**Issue by sidujjain** [jupyterhub/jupyterhub#3406]
### Proposed change

Stopped named servers are counted towards `named_server_limit_per_user` in the JupyterHub. Currently `GET /users/{name}` API only returns running servers list. This means there's no way to delete old named servers using the `DELETE /users/{name}/servers/{server_name}` API.

### Alternative options

The user needs to go to JupyterHub Control Panel and manually delete old named servers. 

### Who would use this feature?

Anyone who is relying on JupyterHub API for user/notebook management. This would include custom BinderHub/JupyterHub deployments.

### (Optional): Suggest a solution

Add a list of stopped named servers in the API response.

**Comment by OwlWisdom** [comment]
I have the same problem, my requirement is: delete only the specific server of the specified user, not all servers under that user name.I still don't know how to implement this requirement, please help analyze it and give some suggestions, thanks.

**Comment by sidujjain** [comment]
Right now it seems that the only way to do it is to maintain a separate DB table for servers spawned using the API. Although, it won't handle the case where the user directly goes to the hub and starts a server. 

I'll be happy to raise a PR if maintainers are fine with this.

**Comment by minrk** [comment]
closed by #3909
