### ISSUE TITLE
Discussion: User control panel for Spawner config

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#341]
For some cases we want to allow users to exert some control over how their servers are spawned, and probably allow users to have multiple servers per user. For example: resource allocations, target clusters, etc.

At the same time, we want this all to be able to be disabled, so existing classroom cases can continue to hide the Hub as much as possible from users, such that it appears as little more than a login page for their notebook server.

Discussion of specific use cases, relevant features can be done here. cc @Cadair @zonca.

**Comment by Cadair** [comment]
My specific requirement for this is to be able to specific extra arguments to my [`SGESpawner`](https://github.com/Cadair/sgespawner/blob/master/sgespawner/spawner.py#L89) i.e. to be able to request more memory for intensive jobs.

**Comment by zonca** [comment]
Thanks @minrk, same for me, would like to specify all parameters of a SLURM job, e.g. duration, queue, account, partition, memory.

An interesting addition, but not necessary, would be to specify also the Spawner itself, so I can either use DockerSpawner locally or RemoteSpawner on a Supercomputer.

**Comment by Cadair** [comment]
I assume we would need a way of having the spawner define the parameters that the user could set. I would not want it to be all the configurable options to the Spawner class, because some of those should not be user configurable.

**Comment by minrk** [comment]
Yup, it would definitely have to be a separate set of options from the general config, either a subset of configurable traits or a separate system altogether.

**Comment by zonca** [comment]
@minrk do you have an estimate when a first implementation of this could be available for testing? thanks!

**Comment by mbmilligan** [comment]
I've started playing with the user options form for my batchspawner and I'm trying to come up with a fairly general mechanism for handling the options so I can support the various Torque/Slurm/etc subclasses. Opening Spawner config values to user input has immediately raised the issue of input validation. I can put whatever I want in the form to help guide the user, but what is the recommended way for the spawner to pass a failure message back to the user if their inputs don't work? Raising an exception in the spawner produces log messages, but nothing user visible that I can see.

**Comment by minrk** [comment]
@mbmilligan good point, I'll add an Exception class to raise for invalid form data so that you can provide a message that gets displayed for the user.

**Comment by minrk** [comment]
@mbmilligan if `Spawner.start` fails with an exception, the exception's message will be shown to the user in #391

**Comment by mbmilligan** [comment]
@minrk Beautiful, I'll be sure to give that a try soon. Is this going to be included in the 0.4 release?

**Comment by minrk** [comment]
Yup, it will. We're just figuring out if the multiple servers per user should be part of this release or not. If not, we should get 0.4 out pretty soon, I think.

**Comment by mbmilligan** [comment]
Oh, interesting, I wasn't aware that multi-server was actively being worked
on. Where is that happening? My experiments with the options form are
evolving in the direction of a meta-spawner that would allow the user to
make a (administrator-constrained) choice of Spawner classes and
parameters. I'd like to see what's happening on this front to make sure I'm
not reinventing any wheels.

Thanks,
Michael

On Fri, Jan 22, 2016 at 3:57 PM, Min RK <notifications@github.com> wrote:

> Yup, it will. We're just figuring out if the multiple servers per user
> should be part of this release or not. If not, we should get 0.4 out pretty
> soon, I think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyterhub/issues/341#issuecomment-174065738>.
>



-- 
Michael Milligan, Ph.D.         | Supercomputing Institute
Scientific Computing Consultant | University of Minnesota
Application Software Manager    | milligan@msi.umn.edu
www.msi.umn.edu/users/milligan  | Phone: 612-624-8857

**Comment by minrk** [comment]
It's not happening anywhere at the moment other than in my head. It will be a somewhat substantial undertaking, just because it means a change to the database schema, and we want to make sure that doesn't require everyone destroying their databases and starting over. Largely for this reason, I think it will probably make sense to ship 0.4 before adding multi-server support, and then start work on that shortly thereafter.

**Comment by consideRatio** [comment]
This discussion relates to the discussion of profile_list in KubeSpawner, and upstreaming such ideas the the base Spawner class.

I'll close this and refer to discussion in https://github.com/jupyterhub/jupyterhub/issues/2724
