### ISSUE TITLE
[RFC] Login page customization requires full HTML replacement

### ISSUE THREAD

**Issue by olifre** [jupyterhub/jupyterhub#3414]
Currently, the login page can not be easily customized, since the full `main` or `login` block needs to be replaced. 
A common use case (in my opinion) is to keep the login box and add additional information, e.g. some news, logos, changelogs, usage details etc. 

Keeping the login box and addings things "around" it currently is not possible in a good way, since the`container` is part of the `login` block:
https://github.com/jupyterhub/jupyterhub/blob/2ff6d2b36c855e86dfab188dc62b31c8738b07a5/share/jupyterhub/templates/login.html#L9-L12
Since `container` can not be put inside `container` in `bootstrap`, this means one has to replace the full HTML. 

I'm currently using a template customization such as this to work around the issue:
```HTML
{% extends "templates/login.html" %} {% block main %} 
<div id="login-main" class="container">
        <div class="row">
                {{ super() }}
                <div class="col-sm-9">
                       <!-- my custom content here, to be shown right of the login box -->
                </div>
        </div>
</div>
{% endblock %}

{% block login %}
<div class="col-sm-3">
{% set lines=super().split('\n') %}
{% for line in lines %}
{% if line.find("login-main") > 0 and line.find("container") > 0 %}
<div>
{% else %}
{{ line }}
{% endif %}
{% endfor %}
</div>
{% endblock %}
```
This takes the base template, and replaces the line containing `login-main` and `container` with a simple `<div>` to allow defining your own `container` for the page by overriding the `main` block. But that feels like a dirty hack. 

Side-note: I somehow could not get:
```HTML
{{ super()|replace(' id="login-main" class="container"', "") }}
```
to work, which would be slightly less of a dirty hack, somehow quotation mark matching fails, even when escaping them. 

My idea for cleaning this up would be to pull out the:
```HTML
<div id="login-main" class="container">
```
into the `main` block to allow for easier customization, reusing as much as possible from the base template, so the customization is more stable upon upgrades. 

Any comments / further ideas?

**Comment by minrk** [comment]
I think adding a new block id inside the container is a good idea, which should make it easier to add things within the container.

I think it would have been right to define login inside the container from the start, but to avoid compatibility issues with anyone overriding login already, let's pick a new name for the inner block, e.g. `login-container`.

Would you like to try a PR?

**Comment by olifre** [comment]
> I think it would have been right to define login inside the container from the start, but to avoid compatibility issues with anyone overriding login already, let's pick a new name for the inner block, e.g. `login-container`.

Indeed, backwards compatibility is an important point to go for the new block instead of just moving the container. 

> Would you like to try a PR?

Certainly, I hope I can address this tomorrow (want to also give it some testing).
