### ISSUE TITLE
Implementation details about the delete_forever hook optionally on a Spawner object

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#3451]
#3337 introduced a `delete_forever` hook for the Spawner base class and I want to deliberate around some details.

The only change besides a test case is the following lines of code.

https://github.com/jupyterhub/jupyterhub/blob/3fec19d191119e4203c243f44c43e74c8fe62f04/jupyterhub/apihandlers/users.py#L241-L245

## Question 1

Do we want the Spawner base class to implement a placeholder function that only have `pass` in it? It would become an entrypoint to write documentation

## Question 2

If not a yes on Question 1, do we want this check added? Now we will write an error message for all Spawners no matter if they have this functionality.

```diff
# allow the spawner to cleanup any persistent resources associated with the user 
try: 
+   if user.spawner.delete_forever:
        await user.spawner.delete_forever() 
    except Exception as e: 
        self.log.error("Error cleaning up persistent resources: %s" % e) 
```

**Comment by minrk** [comment]
> Do we want the Spawner base class to implement a placeholder function that only have pass in it? It would become an entrypoint to write documentation

I thought we had this! Oops! I missed in review that the `delete_forever` method addd in #3337 was defined in the tests, and not in the base class. It should definitely be in the base class. I'll do a PR cleaning up a bit of the logic that I see isn't quite correct.
