### ISSUE TITLE
[rbac] vertical filters for group, services

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#3455]
We have field-filters for users that filter the user model in API results [here](https://github.com/jupyterhub/jupyterhub/blob/3d3c84a2b35633ac820f8f445253c4145ca61dff/jupyterhub/apihandlers/base.py#L236-L252). We should have similar subscopes that do field filtering for services and groups in `service_model` and `group_model`:

- read:groups:name <- name only
- read:groups:roles
- read:services:name <- name, admin only
- read:services:roles

where `read:services` should return the full service model [here](https://github.com/jupyterhub/jupyterhub/blob/rbac/jupyterhub/apihandlers/services.py#L16-L28), and we can do away with the separate service models for the two endpoints

**Comment by 0mar** [comment]
Closed with #3492
