### ISSUE TITLE
it can't start when i use dockerSpawner to start notebook server

### ISSUE THREAD

**Issue by zqszzs** [jupyterhub/jupyterhub#3465]
### Bug description
I use the dockerSpawner start single user server, but failed 

#### Expected behaviour
the single user server can launch normally

#### Actual behaviour
single user server launch failed, I view notebook server logs in docker containers as below:
 
[I 2021-05-12 12:16:04.146 SingleUserNotebookApp notebookapp:1593] Authentication of /metrics is OFF, since other authentication is disabled.
Executing the command: jupyterhub-singleuser --ip=0.0.0.0 --port=8888 --SingleUserNotebookApp.default_url=lab
[W 2021-05-12 12:23:14.993 SingleUserNotebookApp configurable:190] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
[I 2021-05-12 12:23:15.091 SingleUserNotebookApp notebookapp:1593] Authentication of /metrics is OFF, since other authentication is disabled.

### How to reproduce
my local jupyter_config.py config file as below:

c = get_config()  # noqa

from jupyterhub.auth import DummyAuthenticator

c.JupyterHub.authenticator_class = DummyAuthenticator

from dockerspawner.dockerspawner import DockerSpawner

c.JupyterHub.spawner_class = DockerSpawner

c.DockerSpawner.image ='jupyter/base-notebook'
c.DockerSpawner.host_ip ="0.0.0.0"

c.Spawner.default_url = 'lab'
c.Spawner.mem_limit = '100M'
c.JupyterHub.init_spawners_timeout = 30
c.Spawner.start_timeout = 30
c.Spawner.http_timeout = 30
c.Spawner.poll_interval = 30

c.NotebookApp.open_browser = False

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Please include as much information as you can such as how you setup your system, how you're running JupyterHub, details of your system, and also debug logs from JupyterHub and your singleuser server. Thanks!
