### ISSUE TITLE
Run terminal extension in a chroot jail

### ISSUE THREAD

**Issue by vickumar1981** [jupyterhub/jupyterhub#3468]
### Proposed change
When starting a terminal in Jupyter, have some documented flag which would allow terminal sessions to launch in a chroot jail - https://unix.stackexchange.com/questions/105/chroot-jail-what-is-it-and-how-do-i-use-it

i.e. if i am user `user`, and i use terminal, i should not have access to anything higher than the `/home/user` in my terminal, and that would be mapped as `/` to the user.

### Alternative options
When creating new users via the REST API, make the default directory permissions `700` instead of `755`.  i.e., turn off the execute bit, so that users can't just browse into other user's home folders.

### Who would use this feature?
Users who use the terminal extension in Jupyterhub.

**Comment by manics** [comment]
Hi! JupyterHub just starts your singleuser server (e.g. JupyterLab or notebook), so any changes to the terminal app would have to be done there. You could perhaps implement it as an extension?
