### ISSUE TITLE
Websocket 400 connection failed

### ISSUE THREAD

**Issue by alison199** [jupyterhub/jupyterhub#3473]
Hi,

I have created a python application that uses Jupyterhub and has been deployed to Kubernetes

The JupyterHub setup is a combination of KubeSpawner and SAML authentication.

1) I want to deploy the same exact application to multiple Kubernetes clusters (each Kubernetes cluster represents a different data environment - DEV / UAT / Staging / Production). To access these different Kubernetes clusters, the only difference in the code is the SAML metadata file (the internal kubernetes to external https:// mapping has a different base url). Let's say for example we use the following to access the application externally:

- DEV url ->  https://www.hello-dev.com/jupyterhub
- UAT url -> https://www.hello-uat.com/jupyterhub
- STG url -> https://www.hello-stg.com/jupyterhub
- PRD url -> https://www.hello-prd.com/jupyterhub

2) My setup works without any issues when I log in via the DEV url above. This means that I can log in and see my single user pod in the DEV Kubernetes cluster. I can also do the following without any issues and use my application:

- New -> Terminal
- New -> Python3 kernel

3) When I try with any of the other urls (UAT/STG/PRD) I can also login and see my single user pod in the correct Kubernetes cluster. However when I try the following, the Terminal shows a grey screen and the Python3 kernel will not connect 

- New -> Terminal
- New -> Python3 kernel

4) When I look at the webpage, right click, inspect - console I see the following for the Terminal and Python3 kernel (for example for the UAT url):

- Terminal -> Websocket connection to 'wss://hello-uat.com/jupyterhub/user/XXXid/terminals/websocket/1' .... Uncaught TypeError: Cannot read property 'parentElement' of undefined
- Python3 -> Websocket connection failed to 'wss://hello-uat.com/jupyterhub/user/XXXid/api/kernels/numbers/channels?session_id=numbers failed:  kernel.start_channels'

5) When I compare the launched single-user pod logs for the DEV/UAT urls, the only difference I see is when it tries to use the kernel (one is HTTP 101 and the other 400).

DEV -> 101 GET /jupyterhub/user/XXXid/api/kernels/numbers/channels?session_id=numbers
UAT -> 400 GET /jupyterhub/user/XXXid/api/kernels/numbers/channels?session_id=numbers

6) I've checked with Proxy/AVI/Network/Kubernetes/SAML-SSO team members and they say that they cannot find anything strange

Can you think of anything from a JupyterHub perspective ? Is it not possible to use the same JupyterHub configuration from different Kubernetes machines ? Is there any additional configuration that I need to add to my code so that it doesn't only work from the DEV url (but it can also work from UAT/STG/PRD) ?

Thank you very much

Alison

**Comment by manics** [comment]
This is being handled on https://discourse.jupyter.org/t/websocket-400-connection-failed/9289
