### ISSUE TITLE
Improve UI styling

### ISSUE THREAD

**Issue by droctothorpe** [jupyterhub/jupyterhub#3479]
### Proposed change
My team is using JupyterHub for an internal ML platform. 

We plan to make some style enhancements to the native UI and I'm interested in generalizing and contributing those enhancements to the upstream. 

Is that a contribution that the core maintainers would welcome? If not, no worries. We can always just use it internally, but we love JupyterHub and would be happy to contribute the enhancements upstream. 

### Who would use this feature?
Everyone. The default UI would be enhanced by the proposed changes.

**Comment by minrk** [comment]
Yeah, in general we are happy to have improvements like that. I can't say for sure without more detail on what kind of changes you are referring to, but refinements are always welcome.

**Comment by manics** [comment]
@droctothorpe Do you have a concrete description of the changes you'd like to make?

**Comment by droctothorpe** [comment]
Going to close this, Simon. Thanks! Pivoted to other work streams.
