### ISSUE TITLE
About jupyterhub stress testing

### ISSUE THREAD

**Issue by icankeep** [jupyterhub/jupyterhub#3483]
Hello, does JupyterHub have a good way of concurrency stress testing?
I don't know if it's appropriate to ask this here

**Comment by minrk** [comment]
The folks at IBM have some [stress test tools](https://github.com/IBM/jupyter-tools/blob/master/scripts/hub-stress-test.py) There is also @yuvipanda's [hubtraf](https://github.com/yuvipanda/hubtraf).

> I don't know if it's appropriate to ask this here

The [Jupyter forum](https://discourse.jupyter.org/c/jupyterhub/10) is perhaps a better destination for discussions about things like stress testing. I'm going to close this here, but feel free to continue the discussion on the forum if you are interested.
