### ISSUE TITLE
Get Current Notebook Name

### ISSUE THREAD

**Issue by corymaklin** [jupyterhub/jupyterhub#3486]
I don't appear to be able to retrieve the notebook's name + path. Is this currently supported?

### Proposed change
Functionality to retrieve the current notebook name & path

**Comment by manics** [comment]
Hi! JupyterHub manages authentication and runs the singleuser server, but after that everything is handled by the singleuser server, e.g. Jupyter notebook or JupyterLab. JupyterHub doesn't really care what's going on in that server, you could e.g. run your own application that has nothing to do with notebooks 😃.

If you're interested in discussing this further please start a thread on the Jupyter community forum https://discourse.jupyter.org/
