### ISSUE TITLE
Best practice for resource management

### ISSUE THREAD

**Issue by K1LLUM1N471** [jupyterhub/jupyterhub#3491]
Hello! 

We are using JupyterHub and nbgrader on a server with 72 CPU cores, 768GB RAM and  four RTX 2080 Ti.

Does a best practice for resource management already exist?
We are looking for a solution to limit the resources per user, e.g. 4 CPU cores, 8 GB RAM and % GPU RAM.

Kind regards, 
K1LLUM1N471

**Comment by icankeep** [comment]
you can refer to this wiki: https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-resources.html#set-user-memory-and-cpu-guarantees-limits.

You can also customize a Spawner
