### ISSUE TITLE
Pure python alternative to configurable-http-proxy

### ISSUE THREAD

**Issue by AbdealiJK** [jupyterhub/jupyterhub#3528]
### Proposed change

I'm looking to understand if there is a pure python alternative for configurable-http-proxy ?
I have found deploying jupyterhub difficult in some of my setups because while I will always have python installed, I many a times don't have nodejs installed.
I'm just wondering if it makes sense for there to be a pure-python alternative for configurable-http-proxy which could be used/provided.

### Alternative options

If there is some way for me to just disable the http-proxy and just use Jupyterhub's routing system to manage what the proxy does as described in: https://github.com/jupyterhub/jupyterhub/blob/6be3160d7487bb362df7095f24454ef2814951fc/docs/source/reference/separate-proxy.md
That would be great too!

### Who would use this feature?

I think it would be awesome to have this for users who are just looking to get up and running quickly.
I'm not sure about any performance issues - but atleast for me, even if the performance is 70-80% - I think I would be happy with the ease of deployment it could provide

### (Optional): Suggest a solution

I guess this could be a parallel to configurable-http-proxy that could be community maintained or jupyterhub maintained (Sadly I don't have the time to do this though :( )

**Comment by mapsacosta** [comment]
I've been on this same boat for a while, there's a discourse topic [*] I started about something similar.. marking myself as interested in case I can help.

[*] https://discourse.jupyter.org/t/disable-proxy-pod/9348

**Comment by manics** [comment]
JupyterHub _requires_ a proxy for managing routing to the singleruser servers. By default it manages a local `configurable-http-proxy` server but that's not mandatory, you can disable it and run the proxy service yourself.

You can also use alternative proxies such as Traefik with the help of https://github.com/jupyterhub/traefik-proxy

It's definitely possible to write a pure Python implementation, but that would be done outside this repository. I'm going to close this since there's no action to be taken here, but please feel free to start a [Discourse](https://discourse.jupyter.org/) topic to see if anyone else is interested in helping, and please open a docs PR on this repo if you or someone else writes a new Python proxy!

**Comment by AbdealiJK** [comment]
For anyone looking for something similar or wanting to help on this:

I spent some time this week on it, and have a working proxy created at:
https://github.com/AbdealiJK/configurable-http-proxy
It is using tornado and has atleast the basic capabilities available

**Comment by AbdealiJK** [comment]
@manics The python implementation I mentioned above is now being used in our application servers, and we haven't seen any issues. It still doesn't support everything like client-ssl, etc.
But it is quite functional and works for the basic setup that jupyterhub uses configurable-http-proxy for.

Could you point me to where I can add this in the docs ? In case it helps someone else

**Comment by manics** [comment]
A couple of potential places, though neither seem ideal as they're a bit hidden away:
- https://jupyterhub.readthedocs.io/en/stable/reference/proxy.html
  - Source: https://github.com/jupyterhub/jupyterhub/blob/main/docs/source/reference/proxy.md
- https://jupyterhub.readthedocs.io/en/stable/reference/separate-proxy.html
  - Source: https://github.com/jupyterhub/jupyterhub/blob/main/docs/source/reference/separate-proxy.md

Would you mind opening a PR to add the link to one of those and cross-reference this comment, then we can get some input from other team members about where the best place is? It looks like something we should improve, especially as we have other fully supported proxies such as https://github.com/jupyterhub/traefik-proxy that aren't mentioned.

More importantly please share your work on https://discourse.jupyter.org/ ! People are much more likely to see it there than if they're just in these docs, and you'll hopefully get a lot more feedback.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/pure-python-implementation-for-configurable-http-proxy/10075/1
