### ISSUE TITLE
Cull Timeout parameters doesn’t work.

### ISSUE THREAD

**Issue by sameergithub5** [jupyterhub/jupyterhub#3534]
Cull time out parameter does not work in jupyterHub

### Your personal set up

 - OS:
 
 - Version(s):
 

- <details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by sameergithub5** [comment]
![Uploading C5161186-D20E-4622-A3C4-C5364A31FD1D.jpeg…]()

**Comment by sameergithub5** [comment]
I have attched the pic of config file as i am not able copy paste for some reason. 

We also have cull interval , cull connected and cull idle timeout parameter configured. Still idle kernel session are not getting culled

**Comment by manics** [comment]
I can't see your config.

In any case this is likely to be a configuration issue, for example see https://discourse.jupyter.org/t/which-is-the-correct-way-to-cull-idle-kernels-and-notebook/8123
