### ISSUE TITLE
admin shutdown panel does not shutdown proxy/servers

### ISSUE THREAD

**Issue by rvalieris** [jupyterhub/jupyterhub#3540]
### Bug description
jupyterhub does not shutdown the proxy/servers as requested from the admin panel. 
this might be related to https://github.com/jupyterhub/jupyterhub/issues/3297

#### Expected behaviour
proxy and servers are killed with jupyterhub

#### Actual behaviour
only jupyterhub stops, the proxy and servers keep running.

log:
```
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-30' coro=<HTTP1ServerConnection._server_request_loop() running at /home/fox/conda/envs/jupyter/lib/python3.9/site-packages/tornado/http1connection.py:840> cb=[IOLoop.add_future.<locals>.<lambda>() at /home/fox/conda/envs/jupyter/lib/python3.9/site-packages/tornado/ioloop.py:688]>
```

### How to reproduce

from the admin panel -> Shutdown Hub -> check proxy and servers -> shutdown
verify that the proxy and jupyter servers are still running

### Your personal set up

jupyterhub 1.4.1
python 3.9
linux

**Comment by manics** [comment]
Fixed by https://github.com/jupyterhub/jupyterhub/pull/3886
