### ISSUE TITLE
cull timeout settings in config does not work

### ISSUE THREAD

**Issue by sameergithub5** [jupyterhub/jupyterhub#3549]
### Bug description

The issue is even after following official jupyterhub doc cull time out setting and implementing them still  idle spark session or opened notebook session are not getting killed 

#### Expected behaviour

They should be killed if are found idle in 20 mins
#### Actual behaviour

All mentioned settings have been implemented but does not work at all.
### How to reproduce

I am attaching the config file snap, you can start jupyterhub with this config and reproduce the issue
### Your personal set up

We have jupyterhub  installed using python 3.6.10 pip . jupyterhub version is 1.1.0 , jupyterhub-idle-culler version 1.1
 - OS:
 
RHEL 7
 - Version(s):
 
jupyterhub version is 1.1.0 , jupyterhub-idle-culler version 1.1

- <details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by sameergithub5** [comment]
![WhatsApp Image 2021-07-23 at 8 26 12 PM](https://user-images.githubusercontent.com/21688051/126803477-6d6757ce-22df-4a0b-9833-ee53b01c5701.jpeg)

**Comment by sameergithub5** [comment]
Please find atttached config.py.

**Comment by consideRatio** [comment]
@sameergithub5 i think the "how it works" section in https://github.com/jupyterhub/jupyterhub-idle-culler#readme may clarify whats wrong.

Also, i could not see the flags passed to the idle culler service from your picture, they were truncated. Could you please refer to discourse.jupyter.org for help instead?

**Comment by sameergithub5** [comment]
Thanks @consideRatio for reply.
The truncated is not much part its just '--timeout=1200'.

Yes i will follow as you have mentioned  http://discourse.jupyter.org/ forum.
