### ISSUE TITLE
JupyterHub Multi-Node setup

### ISSUE THREAD

**Issue by ashishkshukla** [jupyterhub/jupyterhub#3551]
Hi Team,

I am trying to see the possibility of having support of multi-node jupyterhub. 
Gone through the docs but could not find if hub does provide this feature.

Just wanted to check if it is possible to have multi-node setup where end user will have single entry point and notebooks will be served on one of the hub nodes based on the request.

**Comment by consideRatio** [comment]
@ashishkshukla this is a question for discourse.jupyter.org as it is not a concrete action point on how to make this repo better somehow - but, if you install k8s on your nodes, you can use z2jh.jupyter.org to accomplish that.
