### ISSUE TITLE
Error in Authenticator.pre_spawn_start: CalledProcessError Command

### ISSUE THREAD

**Issue by ranjiGT** [jupyterhub/jupyterhub#3554]
Hello all,

I am new to JupyterHub and trying to integrate it with LTI as an authenticator. We have our own course provider platform like edX and Canvas so we are doing custom configuration in the `jupyterhub_config.py`.  However, I am partially successful in doing so because when I launch my JupyterHub from our course provider I encounter the following error:

```
Error in Authenticator.pre_spawn_start: CalledProcessError Command '['useradd', '-ms', '/bin/bash', '6063f23f-0df6-41fc-a2e9-6f806de1b529']' returned non-zero exit status 3.
```
where **6063f23f-0df6-41fc-a2e9-6f806de1b529** is the default spawnner ID. 

I have come from this solution and tried this:
<https://github.com/jupyterhub/jupyterhub/issues/2948>

But in the above, the authenticator was **NativeAuthenticator** in my case I use the LTIAuthenticator. 

Following is the code part:
```
c.JupyterHub.authenticator_class = 'ltiauthenticator.LTIAuthenticator'
c.LTIAuthenticator.consumers = {
    os.environ['LTI_CLIENT_KEY']: os.environ['LTI_CLIENT_SECRET']
}


def pre_spawn_hook(spawner):
    username = spawner.user.name
    try:
        pwd.getpwnam(username)
    except KeyError:
        subprocess.check_call(['useradd', '-ms', '/bin/bash', username])

c.Spawner.pre_spawn_hook = pre_spawn_hook
```

I'm not sure if I have configured something wrong or should I make my changes in the `jupyterhub_config.py`

**Comment by manics** [comment]
Hi :wave: This sounds like an issue with your deployment- do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Please include full details of how you've deployed JupyterHub as it's likely that will be important in solving your problem. Thanks!
