### ISSUE TITLE
Add Services

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#357]
We've discussed the concept of adding Services for the Hub to manage.

A Service is:

- another process for the Hub to start/restart/monitor
- optionally, another webserver to sit behind the proxy
- optionally, another candidate for authenticating with the Hub

A logical test case for the services mechanism is nbgrader. It is likely the proxy itself should be treated as a Service as well, when it is run by the Hub, rather than managed externally.

Questions likely to come up:

- Are single-user notebook servers just special cases of Services? If we *really nail* the abstractions, this is attractive, since in theory we could re-use the code for process launching already in Spawners. But at the same time it is extremely convenient to be able to assume that we are building a *notebook server*, and if we have to build everything with a generic process abstraction, it gets more complicated. I'd be inclined to start with them as a completely separate bit of code, even though they may share a lot, conceptually.

@ssanderson said he could take a stab at a proposal, but if he's too busy I may give it a go.

**Comment by willingc** [comment]
@minrk and @ssanderson Do you mind if I shadow both of you on this issue?

**Comment by minrk** [comment]
@willingc Not at all!

**Comment by willingc** [comment]
@minrk Cool :)

**Comment by ellisonbg** [comment]
I am really excited about this. There are a number of different services
that could fit into this abstraction:

* nbgrader's formgrade
* static sharing of notebooks with other people.
* As a mechanism to launch "project" that are a single user notebook server
that multiple users have access to.
* Dashboard deployments.

Not sure about the design needed to fit all of these things in, but the
idea is really exciting. My work is going to slow this week with Christmas,
but I am willing to help think about the design.

On Mon, Dec 21, 2015 at 8:26 AM, Carol Willing <notifications@github.com>
wrote:

> @minrk <https://github.com/minrk> Cool :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyterhub/issues/357#issuecomment-166349953>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
My expectation is that services would:

- always run while the Hub is running
- require Hub restart to add/remove services
- generally not change for the lifetime of a given Hub deployment

I think static sharing might be doable as a service, in that it could be a separate webserver that the Hub knows little about, but is added as a single-user extension. I think we can do better if we actually teach the Hub about sharing, though.

I don't think services as described would work for the project users, since that would necessarily have to include all of the single-user spawner logic. I think that's actually a simpler/smaller task, given what we already have, since it's really just defining a new class of user.

Can you describe your dashboard idea in more depth? I don't quite know what that's referring to. Do you think users should be able to spawn their own? If so, it may be that this part should actually warrant a proposal for the single-user server, rather than here, since it seems like the Hub wouldn't need to be aware of that.

I think to cover all of these things, we are probably talking about at least two or three fairly orthogonal proposals.

**Comment by yuvipanda** [comment]
I'm already doing this with nbserver (which I'll replace with nbviewer soon, hopefully) for our install. I just call the proxy myself and register (https://github.com/yuvipanda/nbserve/blob/master/nbserver/app.py#L111). All the actual processes are separate containers/pods managed by kubernetes (aka hub doesn't start the proxy nor nbserver). It provides views like https://tools.wmflabs.org/paws/public/EpochFail/examples/mwxml.py.ipynb. The code wasn't hard to write at all.

I do agree that the hub should ultimately know about sharing - nbserver (and nbviewer) is just publisihng, and any sharing will require hacks. If these services can somehow access current-user information and be able to interact with the running kernel, we can do things like implement 'fork' or 'run a copy of this in my kernel'. Not sure how exactly to easily do this while not leaking cookies into arbitrary JS...

**Comment by minrk** [comment]
@jhamrick and I are talking about what we want from services in nbgrader:

- services registering links to themselves
- user groups for 'grader' auth
- API-only users so service users don't need to map to users with notebook servers
- create API token for the service
- registering services with the CHP

- Maybe we don't abstract process starting like we do with Spawners, but instead have managed vs non-managed like we have for the proxy, where services are started via subprocesses or not, but JupyterHub wouldn't generally manage services run with docker, etc.
- non-managed services would still be able to specify URLs, user info, etc.
- if we go managed/non-managed, we would still need to solve the API token issue, which we could do by allowing explicit loading of API tokens during startup.

I will sketch out what I have so far for services, and @jhamrick can see what nbgrader would look like as a service, so we know how well we are doing.

**Comment by willingc** [comment]
Cool @minrk and @jhamrick. Looking forward to seeing how it goes.

**Comment by willingc** [comment]
@minrk Should we close this now that #705 has been merged? :smile:

**Comment by minrk** [comment]
yes, indeed
