### ISSUE TITLE
Upload large files on JupyterHub

### ISSUE THREAD

**Issue by oharach1** [jupyterhub/jupyterhub#3570]
Hi, we are facing an issue to upload large files on JupyterHub, seems in some point the connection is reset while trying to upload files >9MB.

Using the Webconsole we are getting API request failed (0):error and also PUT https://jupyterhub-our-instance/user/userID/api/contest/filetest430MB.zip net::ERR_CONNECTION_RESET

We are not using a reverse proxy such as NGINX, our setup is using configurable-http-proxy to manage all the internal traffic between the hub and individual pods.

Is very curious we we are facing this issue on classic notebook view and not by using the lab view.

there is a constrain about timeout or proxy-timeout for configurable-http-proxy? based on technical pages for configurable-http-proxy there are some parameters for this CHP but I am note sure how I should set these parameters.

I will appreciated any insight for this issue.

Thanks,

**Comment by manics** [comment]
See https://github.com/jupyterhub/configurable-http-proxy/issues/311
