### ISSUE TITLE
passing collaborative flag

### ISSUE THREAD

**Issue by steverweber** [jupyterhub/jupyterhub#3578]
I'm running jupyterhub and its shelling out to `jupyterhub-singleuser` for the user sessions.
I don't see any place in the code to slide in the `--collaborative` flag for the `jupyterhub-singleuser` script.

slapping `c.LabApp.collaborative = True` into a global config like `/usr/local/etc/jupyter` also doe not seem to work

Is `collaborative` a supported feature when using jupyterhub?

Thanks!

**Comment by consideRatio** [comment]
You can do `jupyterhub-singleuser --LabApp.collaborative=True` to configure a traitlet like `c.LabApp.collaborative` during startup for example if you want.

I think it should also be fine to add such configuration to a config file read by the jupyter server started. The server may be `jupyter_server` or `notebook` depending on your setup.

**Comment by steverweber** [comment]
Ah; so it is working however there is no `token=` in the url to bypass auth in my case PAMAuthenticator so the "shared link" is not too helpful. Is that the expected state of `collaborative`?

**Comment by steverweber** [comment]
After reading some of the bug reports in https://github.com/jupyterlab-contrib/jupyterlab-link-share I assume my jupyterhub instance is over due for an update. I'll give that a try.

**Comment by consideRatio** [comment]
@steverweber nice okay!

https://github.com/jupyterlab-contrib/jupyterlab-link-share/issues/10 is worth tracking, but I'll go for a close on this issue.

**Comment by steverweber** [comment]
I just clued in that you reported the issue that im having. So looks like I'll be waiting :)

**Comment by nickmcintyre** [comment]
@consideRatio any advice as to how I might set the `--collaborative` flag on an instance of TLJH using `tljh-config`?

**Comment by WilliamJudge94** [comment]
Hello everyone,

I have found an easier way than passing in the --collaborative flag into jupyterhub instances, but it requires editing one piece of jupyterlab source code. 

1. Find where your jupyterlab is installed to. 

- If you (username) installed jupyterlab with anaconda3, with virutal environment named test_env, with python=3.9 jupyterlab will have installed to this /home/username/anaconda3/envs/test_env/lib/python3.9/site-packages/jupyterlab/

2. Open the labapp.py file inside of your text editor of choice

3. Scroll down to ~line 614. It should read     

```
  collaborative = Bool(False, config=True,
          help="Whether to enable collaborative mode.")
```

4. Change the False to a True:

```
    collaborative = Bool(True, config=True,
        help="Whether to enable collaborative mode.")
```


Every time you start this jupyterlab instance within your set conda environment it will automatically pass the `--collaborative` flag to jupyter. This also works for staring jupyterlab instances through jupyterhub as well!!!
