### ISSUE TITLE
Allow stop while spawn is pending

### ISSUE THREAD

**Issue by icankeep** [jupyterhub/jupyterhub#3597]
### Proposed change

We have made some customizations based on jupyterhub, including the customization of spawner. Our spawner usually takes a long time (3mins ~ 5mins). When the user selects the wrong configuration, it also needs to wait for such a long time. Therefore, I hope jupyterhub can provide a pending state termination button to stop startup

**Comment by manics** [comment]
This is a duplicate of https://github.com/jupyterhub/jupyterhub/issues/2975
