### ISSUE TITLE
error handling in react admin UI

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#3606]
requests from the admin UI may fail, either being malformed (e.g. creating an invalid username), or permissions (while a user may have permission to access the admin page, they may not have permission to take every action, e.g. creating groups or shutting down the hub).

As it is now, errors are only logged to the console, there is no feedback to the user

**Comment by naatebarber** [comment]
Good catch, will take a look at this.

**Comment by naatebarber** [comment]
Addressed in https://github.com/jupyterhub/jupyterhub/pull/3697 🚀
