### ISSUE TITLE
delete:users|servers|groups scope ?

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#3608]
Currently, add/delete permissions are represented as a single scope - `admin:users`, `admin:groups`, `servers`, `tokens`, etc. I.e. you have to have permission to *create* something in order to delete it.

The practical consequence: the cull-idle service must be granted permission to *start* servers in order to have permission to stop them, though it will only ever use the stop function. Same goes for culling idle users - it must have permission to *create* users if it wants permission to delete them.

More scopes is more complex, so we have to think of where the boundary is for when a scope makes sense to add. But this should probably be consistent across all resources, whether we add it or not.

### Proposed change

We could add a `delete:` subscope on users, groups, tokens, and servers to allow services only permission to delete resources, without needing permission to start servers, issue tokens, create users, etc.

### Alternative options

Keep it as-is, and bundle creation and deletion in one scope. It's always possible to add more finer-grained scopes, it's harder to remove them.

### Who would use this feature?

deployments of the cull-idle service (most deployments!) who want limited permissions.

**Comment by consideRatio** [comment]
With `create` you can do a lot more than with `delete` in this case. I think it is a quite relevant distinction. I'm :+1: inclined.

**Comment by 0mar** [comment]
I think it makes sense as well. Is there a use case for a separate `create` sub-scope as well?
