### ISSUE TITLE
Should we bundle nullauthenticator in this repository?

### ISSUE THREAD

**Issue by manics** [jupyterhub/jupyterhub#3609]
### Proposed change
`nullauthenticator` is a very small JupyterHub authenticator used by BinderHub:
https://github.com/jupyterhub/nullauthenticator/blob/master/nullauthenticator.py

Is it worth bundling it in this repo? For example [`DummyAuthenticator` is already included](https://github.com/jupyterhub/jupyterhub/blob/4f6ef54b50ea577bb67f2726bc98a5ce909ebc92/jupyterhub/auth.py#L1150).

This is the only BinderHub dependency (aside from BinderHub) that's not on conda-forge.

### Alternative options
Keep https://github.com/jupyterhub/nullauthenticator in its own repo. Consider creating a conda-forge package for it.

### Who would use this feature?
Anyone wanting to install all BinderHub's dependencies from conda-forge.

**Comment by minrk** [comment]
Seems reasonable, given that we've added other 'api-only' features. Disabling JupyterHub's own auth is part of such deployments.
