### ISSUE TITLE
Cannot list users with 'all' scope

### ISSUE THREAD

**Issue by ktaletsk** [jupyterhub/jupyterhub#3630]
### Bug description

I am overriding the default server role to enable JupyterHub API access with KEY as described in https://jupyterhub.readthedocs.io/en/latest/rbac/roles.html#overriding-default-roles. However, after recent commit (somewhere between 7533cb76021f0ceda5102f9316746fa326a30246 and fb1e81212fa967eef36332090b7818a4ec97c3be, probably 8603723dbbabef8a50182ec4d6d4ddd522a46b44) I cannot list users with that token, as it requires to have `list:users` scope. Currently, tokens with `all` scope does not contain `list:users` scope.

#### Expected behaviour
My understanding is that `all` scope should include `list:users` scope, as it is now required to list users.

#### Actual behaviour
`all` scope does not contain `list:users` scope

### How to reproduce
1a. Override the default role with `all` scope 
```py
c.JupyterHub.load_roles = [
  {
    "name": "server",
    "scopes": ["all"],
  }
]
```

*or*

1b. create a role for service token with `all` scope:
```py
c.JupyterHub.services = [
  {
    "name": "test-token",
    "api_token": "<token>",
  }
]

c.JupyterHub.load_roles = [
  {
    "name": "test-role",
    "scopes": ["all"],
    "services": ["test-token"]
  }
]
```

2. Start JupyterHub
3. Make an API request to `/hub/api/users` from (1a) user server or (1b) from outside JupyterHub using the predefined service token.
4. Observe error in request
```
{"status": 403, "message": "Action is not authorized with current scopes; requires any of [list:users]"} 
```

### Possible fixes

I attempted to circumvent the issue by appending `list:users` to the list of scopes in 1a and 1b.

1a.
```py
c.JupyterHub.load_roles = [
  {
    "name": "server",
    "scopes": ["all", "list:users"],
  }
]
```

However, this leads to an error while spawning the notebook server
```
[D 2021-09-28 14:19:07.643 JupyterHub roles:470] Checking token permissions against requested role server
[W 2021-09-28 14:19:07.643 JupyterHub roles:434] Token requesting scopes exceeding owner ktaletsk: {'list:users'}
[W 2021-09-28 14:19:07.655 JupyterHub web:1787] 500 GET /hub/spawn/ktaletsk (::ffff:172.18.208.1): Error in Authenticator.pre_spawn_start: ValueError Requested token role server of <APIToken('3b13...', user='ktaletsk', client_id='jupyterhub')> has more permissions than the token owner
```

1b. 
```py
c.JupyterHub.load_roles = [
  {
    "name": "test-role",
    "scopes": ["all", "list:users"],
    "services": ["test-token"]
  }
]
```
Works in this case

### Your personal set up

 - OS: ubuntu 20.04 in WSL2
 - Version(s): 2.0.0b1, [this commit]
- Conda environment
```
name: jupyterhub-rtc
channels:
  - conda-forge
dependencies:
  - alembic
  - async_generator
  - certipy
  - configurable-http-proxy=4
  - entrypoints
  - jinja2
  - jupyter_telemetry
  - jupyterlab=3.1
  - nodejs=14
  - oauthlib
  - pamela
  - pip
  - prometheus_client
  - psutil
  - pycurl
  - python=3.9
  - python-dateutil
  - requests
  - sqlalchemy
  - tornado=6
  - traitlets=5
  - pip:
    - git+https://github.com/jupyterhub/jupyterhub.git@fb1e81212fa967eef36332090b7818a4ec97c3be#egg=jupyterhub
    - escapism
    - jupyterlab-rtc-hub-settings==0.1.1
    - jupyterlab-link-share==0.2.0
```

**Comment by minrk** [comment]
> My understanding is that all scope should include list:users scope, as it is now required to list users.

The 'all' scope means a token issued with this scope is expanded to all of the permissions *of its owner*. So if its owner doesn't have permission to list users, the token won't either.

Perhaps `owner` is a better name for this metascope?

> However, this leads to an error while spawning the notebook server

Tokens may not have more permissions than their owners, because if the token had those permissions, the user might as well since it's their token.

To grant all user servers access to list users, you must also grant all *users* the same permission:

```python
c.JupyterHub.load_roles = [
  # all users can list all other users
  {
    "name": "user",
    "scopes": ["self", "list:users"],
  },
  # server tokens can do anything the server's owner can do
  {
    "name": "server",
    "scopes": ["all"],
  },
]
```

**Comment by consideRatio** [comment]
> Perhaps owner is a better name for this metascope?

Ahh, i like this suggestion!

**Comment by consideRatio** [comment]
Min hmmm what makes your example function? You don't assign the role to any user/token/service etc. Are you changing a default role assigned by default? Is this documented already?

**Comment by ktaletsk** [comment]
Thanks @minrk for explanation and a fix! I adding the `"list:users" to the owner's scope worked. 

I also realized that my issue was with a [different role](https://github.com/ktaletsk/jupyterhub-rtc-config-wrapper/blob/690640b5d28487f13f0f651a03b587894bfdc4b8/jupyterhub_config.py#L56) in my config, which is essentially doing the same (allowing users to read the list of users). It was still using the old `"read:users:name"` scope:
```
{
  'name': f'usernames_reading_{user}_role',
  'description': 'Usernames reading group',
  'scopes': ['read:users:name'],
  'users': [f'{user}']
}
```
Changing it to 
```
{
  'name': f'usernames_reading_{user}_role',
  'description': 'Usernames reading group',
  'scopes': ['list:users'],
  'users': [f'{user}']
}
```
fixes the issue for me without needing to override the `"user"` scope. 

I'm sorry, should have been more attentive in my debugging. Feel free to close this issue.

============
@consideRatio I think @minrk is referring to overriding the default roles here, which was recently documented: https://jupyterhub.readthedocs.io/en/latest/rbac/roles.html#overriding-default-roles
