### ISSUE TITLE
Spawner self.user dont have updated information

### ISSUE THREAD

**Issue by ayush-san** [jupyterhub/jupyterhub#3634]
We are using a custom spawner where according to the groups mapped to a user different configurations will be shown as options. But we are noticing that self.user.groups and self.user.admin is not updated as I can see by hitting the API for that particular user.

Is there a way to refresh the state of the user object available inside the spawner?

In handler/base.py, I can see we are refreshing the state using the below code

```
auth_user = await self.refresh_auth(user, force=True)
```

Can we do something similar inside the spawner too?

Here is the sample spawner code where I am facing the issue
```
class EcsTaskSpawner(Spawner):
    """
    ECS Task Spawner
    """

    form_template = """
        {hint_para}
        </select>
        <label for="notebook_type">Select notebook type:</label>
        <select class="form-control" name="notebook_type" required autofocus>
        {notebook_types}
        </select>
        """

    input_template = """
        <option value="{key}" {first}>{display}</option>
        """
    
    def _options_form_default(self):
        # Here I am getting old groups list
        user_groups = [group.name for group in self.user.groups]
        # Here I am getting old boolean value
        is_admin = self.user.admin
        return "string_form_html"
```

**Comment by ayush-san** [comment]
yes I moved it to callable and also added session refresh to get the updated information
```
def _options_form_default(self):
        def _wrapper_form(spawner):
            user = orm.User.find(spawner.user.db, name=spawner.user.name)
            spawner.user.db.refresh(user)
            ....
```

**Comment by minrk** [comment]
I think I must be misunderstanding, then. If the information in the latest state of the database is not correct, where is the correct information?

Can you add a log statement or print to your render function to ensure it's called when you expect it to be?

**Comment by joglekara** [comment]
@ayush-san were you able to get this working? Looking to implement something similar myself

**Comment by ayush-san** [comment]
@minrk The correct information is in the database only but the session object didn't have the latest data which I just updated using the API - [StackOverflow Link](https://stackoverflow.com/questions/19143345/about-refreshing-objects-in-sqlalchemy-session). So I had to call refresh so that all the attributes of the user object will get updated with the latest value 

@joglekara Yes I was able to get this working

**Comment by manics** [comment]
Sounds like this was resolved
