### ISSUE TITLE
Deadlock when using REST API from Authenticator.post_auth_hook

### ISSUE THREAD

**Issue by ykazakov** [jupyterhub/jupyterhub#3654]
### Bug description

I want to post-process authenticated users, e.g., adding them to JupyterHub groups based on the information provided by the authenticator (we use LTI11Authenticator, but it is not really important). As far as I understand, the only documented way to do so is through [REST API](https://jupyterhub.readthedocs.io/en/stable/reference/rest.html). However, REST API requests called from the hook functions, such as `c.Authenticator.post_auth_hook` seem to deadlock.

#### Expected behaviour

I expect REST API request to return results.

#### Actual behaviour

As soon as the user is authenticated, JupyterHub hangs.

### How to reproduce

1. Create the following `jupyterhub_config.py`:

```
import requests

# see https://jupyterhub.readthedocs.io/en/stable/reference/authenticators.html#the-dummy-authenticator
c.JupyterHub.authenticator_class = 'jupyterhub.auth.DummyAuthenticator'

# see https://jupyterhub.readthedocs.io/en/stable/reference/authenticators.html#pre-spawn-start-and-post-spawn-stop-hooks
def my_hook(authenticator, handler, authentication):
    # see https://jupyterhub.readthedocs.io/en/stable/reference/rest.html#make-an-api-request
    api_url = 'http://127.0.0.1:8081/hub/api'
    r = requests.get(api_url + '/')
    r.raise_for_status()
    authenticator.log.info(r.json())
    authentication

c.Authenticator.post_auth_hook = my_hook
```

2. Run `jupyterhub -f /etc/jupyterhub/jupyterhub_config.py`

OR use the following `Dockerfile`:
```
FROM jupyterhub/jupyterhub:1.4.2

COPY jupyterhub_config.py /etc/jupyterhub/

CMD jupyterhub -f /etc/jupyterhub/jupyterhub_config.py
```

And run:

```
docker build -t jupyterhub-test . 
docker run -it -p 8000:8000 jupyterhub-test
```

3. Open the browser on `http://127.0.0.1:8000`
4. Add Username `test` and press `Sign in`
5. Observe that the browser gets stuck.

### Your personal set up

 - OS: MacOS 11.6
 - Docker: version 20.10.8, build 3967b7d
 - Jupyterhub: version 1.4.2 (in Docker)
 - Docker image: jupyterhub/jupyterhub:1.4.2

<details><summary>Logs</summary>

```
% docker run -it -p 8000:8000 jupyterhub-test
[I 2021-10-15 15:31:22.150 JupyterHub app:2459] Running JupyterHub version 1.4.2
[I 2021-10-15 15:31:22.152 JupyterHub app:2489] Using Authenticator: jupyterhub.auth.DummyAuthenticator-1.4.2
[I 2021-10-15 15:31:22.155 JupyterHub app:2489] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.4.2
[I 2021-10-15 15:31:22.156 JupyterHub app:2489] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.4.2
[I 2021-10-15 15:31:22.182 JupyterHub app:1579] Writing cookie_secret to /srv/jupyterhub/jupyterhub_cookie_secret
[I 2021-10-15 15:31:22.269 alembic.runtime.migration migration:164] Context impl SQLiteImpl.
[I 2021-10-15 15:31:22.269 alembic.runtime.migration migration:167] Will assume non-transactional DDL.
[I 2021-10-15 15:31:22.294 alembic.runtime.migration migration:556] Running stamp_revision  -> 4dc2d5a8c53c
[I 2021-10-15 15:31:22.416 JupyterHub proxy:497] Generating new CONFIGPROXY_AUTH_TOKEN
[W 2021-10-15 15:31:22.431 JupyterHub app:1808] No admin users, admin interface will be unavailable.
[W 2021-10-15 15:31:22.431 JupyterHub app:1809] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2021-10-15 15:31:22.431 JupyterHub app:1838] Not using allowed_users. Any authenticated user will be allowed.
[I 2021-10-15 15:31:22.517 JupyterHub app:2526] Initialized 0 spawners in 0.003 seconds
[W 2021-10-15 15:31:22.527 JupyterHub proxy:699] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2021-10-15 15:31:22.527 JupyterHub proxy:703] Starting proxy @ http://:8000
15:31:23.313 [ConfigProxy] info: Proxying http://*:8000 to (no default)
15:31:23.320 [ConfigProxy] info: Proxy API at http://127.0.0.1:8001/api/routes
15:31:23.565 [ConfigProxy] info: 200 GET /api/routes 
[I 2021-10-15 15:31:23.565 JupyterHub app:2774] Hub API listening on http://127.0.0.1:8081/hub/
15:31:23.585 [ConfigProxy] info: 200 GET /api/routes 
[I 2021-10-15 15:31:23.590 JupyterHub proxy:347] Checking routes
[I 2021-10-15 15:31:23.590 JupyterHub proxy:432] Adding route for Hub: / => http://127.0.0.1:8081
15:31:23.617 [ConfigProxy] info: Adding route / -> http://127.0.0.1:8081
15:31:23.628 [ConfigProxy] info: Route added / -> http://127.0.0.1:8081
15:31:23.630 [ConfigProxy] info: 201 POST /api/routes/ 
[I 2021-10-15 15:31:23.640 JupyterHub app:2849] JupyterHub is now running at http://:8000
[I 2021-10-15 15:31:28.257 JupyterHub log:189] 302 GET / -> /hub/ (@::ffff:172.17.0.1) 2.30ms
[I 2021-10-15 15:31:28.294 JupyterHub log:189] 302 GET /hub/ -> /hub/login?next=%2Fhub%2F (@::ffff:172.17.0.1) 1.32ms
[I 2021-10-15 15:31:28.385 JupyterHub log:189] 200 GET /hub/login?next=%2Fhub%2F (@::ffff:172.17.0.1) 67.64ms
15:32:06.705 [ConfigProxy] error: 503 GET /hub/static/components/font-awesome/fonts/fontawesome-webfont.woff2 socket hang up
[I 2021-10-15 15:32:06.725 JupyterHub log:189] 200 GET /hub/error/503?url=%2Fhub%2Fstatic%2Fcomponents%2Ffont-awesome%2Ffonts%2Ffontawesome-webfont.woff2%3Fv%3D4.7.0 (@127.0.0.1) 11.30ms
```

</details>

The code for REST API ran from python after GitHub stats up but before the user is authenticated:
```
% docker ps                                                                                                                                         
CONTAINER ID   IMAGE             COMMAND                  CREATED          STATUS          PORTS                    NAMES
1e5d12e6765e   jupyterhub-test   "/bin/sh -c 'jupyter…"   17 seconds ago   Up 16 seconds   0.0.0.0:8000->8000/tcp   angry_cerf
% docker exec -it angry_cerf /bin/bash
root@1e5d12e6765e:/srv/jupyterhub# python3
python3    python3.8  
root@1e5d12e6765e:/srv/jupyterhub# python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> api_url = 'http://127.0.0.1:8081/hub/api'
>>> r = requests.get(api_url + '/')
>>> r.raise_for_status()
>>> r.json()
{'version': '1.4.2'}
>>> 
```

**Comment by minrk** [comment]
> wouldn't it be all redundant had there been direct API functions for everything provided by the REST API?

It could be seen that way. It depends on what the Authenticator's responsibilities are. Providing those APIs means the Authenticator needs access to the database (something it *technically* has, but is undocumented and actually needs to be removed).

As the design is currently, the Authenticator's only responsibilities are supposed to be: retrieve information from an external source, and 'shape' it into a standard form for JupyterHub (username, admin, black box auth_state for extra stuff JupyterHub doesn't need to understand). A group list is a logical addition here, since it is often sourced from outside (e.g. GitHub team membership, system groups, etc.). Authenticators explicitly should not need to know anything about JupyterHub's internals (does the user exist in the database already, etc.).

Another design would have been to grant the Authenticator permission to do a lot more with the database, exposing a lot more functionality. This would give Authenticators a lot more power, but also dramatically increase the API surface JupyterHub needs to support, and potentially require more work for Authenticators to do. Not an unreasonable choice! Just not the direction I went long ago.

**Comment by ykazakov** [comment]
I do not suggest giving access to the hub database *for the Authenticator*. I agree that the Authenticator should be agnostic as of where and how exactly hub uses the provided information. In this regards, I think passing the admin flag or the (hub) groups *separately* from the auth_state is already overstepping the responsibility of the Authenticator. Why not also to pass other things separately, e.g., the userid and the groupid to be used for the Spawner?

Instead, my idea was to add the API functions for the hub itself (is there such a class Hub?) so that they can be conveniently used in various hooks, such as `c.Authenticator.post_auth_hook` or `c.Spawner.pre_spawn_hook`. Or, if these hooks are assumed to "belong" to the Authenticator and Spawner respectively (which is not the way I understand their purpose), rename them or add new hooks like `c.Hub.post_auth_hook` and `c.Hub.pre_spawn_hook`.

Also, why the "API surface" of that Hub should increases if to add just the functions that are *already* provided by the REST API?

**Comment by minrk** [comment]
> Also, why the "API surface" of the Hub should increases if to add just the functions that are already provided by the REST API?

Two APIs is still more than one, even if they ultimately do the same thing. A Python API is a bigger issue, because it includes things like assumptions of the database state during, before, and after.

**Comment by ykazakov** [comment]
> A Python API is a bigger issue, because it includes things like assumptions of the database state during, before, and after.

I see, I did not think about this. Of course, access to the database should be properly synchronised using locks and things like that. But I guess the database can be already accessed / modified from several places, so there is probably already some synchronisation in place.

**Comment by minrk** [comment]
>  But I guess the database can be already accessed / modified from several places

Yes! And these have all been a problem, are undocumented, and I hope to remove them all eventually. Spawners and Authenticators should not need or have direct access to the db.

**Comment by ykazakov** [comment]
Sorry, a few follow up question: 

1. Is it currently (as of version 1.5) possible to process an authenticated user *after* the user has been added to the database but *before* spawning a single-user server? As mentioned, I am trying to add a user (via REST API) to a particular group based on the information passed from the external authenticator. However, I can only add a user to a group if the user already *exists* in the hub database.

As I understand, the hook `c.Authenticator.post_auth_hook` is executed *before* the user is added to the database. The hook `c.Spawner.pre_spawn_hook` is executed after, but it may never be triggered if, for example, the user does not start a single-user server at all. As mentioned, I am trying to restrict using this group access to a *shared* notebook server as in [this example](https://github.com/jupyterhub/jupyterhub/tree/1.4.x/examples/service-notebook).

2. I also noticed that even after adding a user to the `shared` group (via REST API), the shared notebook started with the `--group=shared` option like [in the same example](https://github.com/jupyterhub/jupyterhub/blob/1.4.x/examples/service-notebook/managed/jupyterhub_config.py) remains inaccessible for the user (status error: 500) if the user tried to access it before he was added to the `shared` group. I seems that the authentication information is not requested again from the hub for some time. Probably until some cookie expires? Is it possible to somehow force requesting authentication information by a single-user server? What kind of cache is missed in the log below? Is it possible to invalidate this cache manually?

```
[D 2021-10-29 15:54:12.916 SingleUserNotebookApp auth:310] HubAuth cache miss: token:9add966a798e41d5b2d368489eabc091:wr4IDYCtz6xIo2upcBhNJWXPhAo1Us
[I 2021-10-29 15:54:12.971 JupyterHub log:189] 200 GET /hub/api/authorizations/token/[secret] (shared-notebook@127.0.0.1) 45.97ms
[D 2021-10-29 15:54:12.978 SingleUserNotebookApp auth:316] Received request from Hub user {'kind': 'user', 'name': 'ellisonbg', 'admin': False, 'groups': ['shared'], 'server': None, 'pending': None, 'created': '2021-10-29T15:53:53.836177Z', 'last_activity': '2021-10-29T15:54:12.950473Z', 'servers': None}
[I 2021-10-29 15:54:12.979 SingleUserNotebookApp auth:992] Logged-in user {'kind': 'user', 'name': 'ellisonbg', 'admin': False, 'groups': ['shared'], 'server': None, 'pending': None, 'created': '2021-10-29T15:53:53.836177Z', 'last_activity': '2021-10-29T15:54:12.950473Z', 'servers': None}
```

My apologies for asking so many questions and thanks @minrk for your valuable replies!

**Comment by minrk** [comment]
The short answer is that authenticator-managed groups is a feature we don't have that I want to land in 2.1, so if you can wait, I do hope to land it soon, in which case you should be able to return group info from `authenticate()` and be done.

However, if you need a workaround now, I think what you need is a custom handler that calls your code after `login_user`.

If you're using LTI, that handler is [here](https://github.com/jupyterhub/ltiauthenticator/blob/50688aa06ea35678c64f34666acdf348b585e33d/ltiauthenticator/lti11/handlers.py#L24-L51) where `user = yield self.login_user()` will return the actual User object, and you can add it to groups before completing the request.

**Comment by ykazakov** [comment]
@minrk thanks for the hint and sorry for a late reply! I now looked at the function `login_user()` in `BaseHandler`, and it seems that the user is added to the database by `auth_to_user(authenticated)` after the authenticated user is returned. So, my current workaround (until version 2.1 is released) is to add a user to a group after this function is called.:

```
async def post_auth_hook(authenticator, handler, authentication):
    old_auth_to_user = handler.auth_to_user
    async def auth_to_user(self, authenticated, user=None):
        self.auth_to_user = old_auth_to_user
        user = await self.auth_to_user(authenticated, user)
        # here the user should be added to the database and is available for REST API
        return user
    # overriding the handler method
    # see https://stackoverflow.com/a/46757134
    from jupyterhub.handlers import BaseHandler    
    handler.auth_to_user = auth_to_user.__get__(handler, BaseHandler)
    return authentication   

c.Authenticator.post_auth_hook = post_auth_hook
```

I look forward to version 2.1, which, hopefully, should make lot's of this code obsolete.

**Comment by minrk** [comment]
> I look forward to version 2.1, which, hopefully, should make lot's of this code obsolete.

That's my goal! Having. existing use cases like this should help ensure we make something useful.
