### ISSUE TITLE
Unable to get Jupyter working with Apache Reverse Proxy for my Domain

### ISSUE THREAD

**Issue by chandragaajula** [jupyterhub/jupyterhub#367]
I have the following entry in "/etc/apache2/sites-enabled" on my Ubuntu 15.10

```
<VirtualHost *:80>
        ServerName "jupyter.xxxxxxxxxxxx.com"
        ProxyPass / http://192.168.254.23:8888/
        ProxyPassReverse / http://192.168.254.23:8888/
        Header edit Origin "jupyter.xxxxxxxxxxxx.com" 192.168.254.23:8888
        RequestHeader edit Origin "jupyter.xxxxxxxxxxxx.com" 192.168.254.23:8888

        Header edit Referer "jupyter.xxxxxxxxxxxx.com" 192.168.254.23:8888
        RequestHeader edit Referer "jupyter.xxxxxxxxxxxx.com" 192.168.254.23:8888
        <Location ~ "/(user/[^/]*)/(api/kernels/[^/]+/channels|terminals/websocket)/?">
                ProxyPass ws://192.168.254.23:8888
                ProxyPassReverse ws://192.168.254.23:8888
        </Location>
</VirtualHost>
```

After making the above entry I restarted apache: "sudo service apache2 restart"

When I attempt to run my script the Kernel is unable to connect.
![jupyterreverseproxy](https://cloud.githubusercontent.com/assets/2474552/12107469/7261f1a2-b320-11e5-9d7e-fd630e60c1b2.png)

Console Logs:
![jupyterlogs](https://cloud.githubusercontent.com/assets/2474552/12129784/c1f2ef88-b3ba-11e5-955d-3dee1e5f66f3.JPG)

The same works when I specify the IP Address though:
![jupyterwithipaddressandport](https://cloud.githubusercontent.com/assets/2474552/12107534/35c6a886-b321-11e5-84bf-8adf9287ff77.png)

How do I get this to work with the domain name?

**Comment by minrk** [comment]
Apache is not correctly proxying the websocket. I'm not sure what the exact correct config for that is, but that's the root of the problem.

**Comment by andreaslang** [comment]
I just compared it with my configuration, could you try and add a slash at the end of your ws urls? Like this:

```
<Location ~ "/(user/[^/]*)/(api/kernels/[^/]+/channels|terminals/websocket)/?">
                ProxyPass ws://192.168.254.23:8888/
                ProxyPassReverse ws://192.168.254.23:8888/
</Location>
```

Otherwise I don't see any differences. According to the apache docs the slash should be there if it is present in Location (or the first parameter of ProxyPass), I am not entirely sure about the regex behaviour with the optional slash.

In case this doesn't work, are you sure there is no other proxy in the way? For example one of your hosting provider?

**Comment by chandragaajula** [comment]
@minrk / @andreaslang - Thanks for the input. However, the changes recommended did not solve the problem.

Here's more info on my setup:
* Apache is running on Server A (Ubuntu 15.4)
* Jupyter installed on Server B (Centos 7) as a Docker Image (https://www.dataquest.io/blog/data-science-quickstart-with-docker/)

Does that make a difference is your recommendation for the setup?

**Comment by chandragaajula** [comment]
Identified the Solution:

    <VirtualHost *:80>
            ServerName "jupyter.xxxxxxxxxxx.com"
            ProxyPreserveHost On
            ProxyRequests off
    
            ProxyPass /api/kernels/ ws://192.168.254.23:8888/api/kernels/
            ProxyPassReverse /api/kernels/ http://192.168.254.23:8888/api/kernels/
    
            ProxyPass / http://192.168.254.23:8888/
            ProxyPassReverse / http://192.168.254.23:8888/
    </VirtualHost>

Important thing to note: The entry for WebSockets should be in the beginning.

**Comment by minrk** [comment]
@chandragaajula glad you figured it out, and thanks for posting the solution!

**Comment by quanghoc** [comment]
Does this solution still work?

This is what I had:

<img width="601" alt="screen shot 2016-02-13 at 1 16 28 am" src="https://cloud.githubusercontent.com/assets/2769972/13026928/8c1abe24-d1ef-11e5-9a32-c7c7a7a2a1c6.png">


And I still got error that it cannot communicate to `ws://user1.jupyer.local/api/kernels`. Any idea?

<img width="1212" alt="screen shot 2016-02-13 at 1 15 57 am" src="https://cloud.githubusercontent.com/assets/2769972/13026929/9094210c-d1ef-11e5-9e5d-fbfcd7ab4bf1.png">

**Comment by willingc** [comment]
@

**Comment by jorditg** [comment]
@quanghoc did you solved the problem? I'm stuck in the same. Not able to get it working with reverse proxy over localhost.

**Comment by quanghoc** [comment]
@jorditg I gave up because there are more than one websockets to deal with.

**Comment by andgan** [comment]
Hi, I still have the same problem, any solution?

**Comment by willingc** [comment]
I've just reopened this issue about configuration of a reverse proxy for Apache.

cc/ @minrk

**Comment by willingc** [comment]
### Checklist of tips from community members in #219

- [ ] Review working configurations in https://github.com/jupyterhub/jupyterhub/issues/219
- [ ] Review Apache version.
     * Apache 2.4 or higher
     * 2.2.x does not provide WebSocket support.
     * 2.2 on CentOS will work with wstunnel backport patches (See https://gist.github.com/vitkin/6661683).
- [ ] have you enabled `mod_proxy_wstunnel`?
- [ ] enable proxy, proxy_http, headers and proxy_wstunnel.
- [ ] Checked Apache logs?
- [ ] Check for mispellings in config (i.e. notebook vs notebooks). Be consistent.
- [ ] May need to be configure the Hub to listen to an external interface rather than localhost
- [ ] Note: recent versions of JupyterHub and single user notebook servers will complain if started without SSL, so if you are terminating SSL at your proxy server (which is the common thing to do here) you may need to add the --no-ssl option

**Comment by sean-abbott** [comment]
I get 
"A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration."

When trying to connect to an existing notebook.  It says "connecting to kernel" in the upper right.  

mod_proxy_wstunnel is enabled.

I can get to jupyter in general with the /api/kernels/ proxy pass stanza.

The location match on the regex seems to make no difference either way.

I am not proxying to localhost but rather to another server.

**Comment by willingc** [comment]
There have been several months since this issue has been mentioned. We've released JupyterHub 0.7. I'm going to go ahead and close this. We can reopen or create a new issue should further issues arise.

**Comment by remidebette** [comment]
https://github.com/jupyterhub/jupyterhub/issues/219

**Comment by jondoesntgit** [comment]
This works when mod_proxy_wstunnel is enabled on my machine:

bashrc_Apple_Terminal                 find.codes                            irbrc                                 manpaths.d                            ntp_opendirectory.conf                php.ini.default                       resolv.conf                           ssl
     <VirtualHost *:80>
            ServerName      jupyter.localhost
             ProxyPreserveHost On
            ProxyRequests off

            ProxyPass /api/kernels/ ws://localhost:8888/api/kernels/
            ProxyPassReverse /api/kernels/ http://localhost:8888/api/kernels/

            ProxyPass       / http://localhost:8888/
            ProxyPassReverse        / http://localhost:8888/
    </VirtualHost>

**Comment by gerroon** [comment]
Does anyone have workign examples of running this under subfolder instead of on the whole domain?

**Comment by cb1986ster** [comment]
This works for my:
```
<VirtualHost *:80>
        DocumentRoot /var/www/html
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        ProxyPreserveHost On
        ProxyPass /jupyter/ http://192.168.1.40:4050/jupyter/
        ProxyPassReverse /jupyter/ http://192.168.1.40:4050/jupyter/
        <Location "/jupyter/api/kernels">
                RequestHeader set X-SCRIPT-NAME /jupyter/
                ProxyPassReverse http:/192.168.1.40:4050/
                RewriteEngine on
                RewriteCond %{HTTP:UPGRADE} =websocket [NC]
                RewriteRule /jupyter/api/kernels/(.*) ws://192.168.1.40:4050/jupyter/api/kernels/$1 [P,L]
                RewriteCond %{HTTP:UPGRADE} !=websocket [NC]
                RewriteRule /jupyter/api/kernels/(.*) http://192.168.1.40:4050/jupyter/api/kernels/$1 [P,L]
        </Location>
        # Require user/password
        <Proxy *>
                Order deny,allow
                Allow from all
                Authtype Basic
                Authname "Password Required"
                AuthUserFile /etc/htpasswd
                Require valid-user
        </Proxy>
</VirtualHost>
```

**Comment by gerroon** [comment]
@cb1986ster thanks I will try it

**Comment by Ex-Origin** [comment]
It works well,

```
<VirtualHost *:80>
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
    ProxyPreserveHost On
    ProxyRequests off
    
    # a2enmod proxy_wstunnel  # debian-ubuntu
    # a2enmod rewrite         # debian-ubuntu
    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket
    RewriteRule /(.*)           ws://localhost:8888/$1 [P,L]
    RewriteCond %{HTTP:Upgrade} !=websocket
    RewriteRule /(.*)           http://localhost:8888/$1 [P,L]

</VirtualHost>
```
