### ISSUE TITLE
Conda forge package for 1.5.0

### ISSUE THREAD

**Issue by gramakri** [jupyterhub/jupyterhub#3680]
### Bug description
JupyterHub 1.5.0 was tagged but I don't see a release in https://anaconda.org/conda-forge/jupyterhub

#### Expected behaviour
Expecing 1.5.0 release to be available.

#### Actual behaviour

```
PackagesNotFoundError: The following packages are not available from current channels:

  - jupyterhub=1.5.0

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

### How to reproduce

`conda install --yes -c conda-forge jupyterhub=1.5.0`

### Your personal set up

I am the maintainer of the Cloudron package - https://git.cloudron.io/cloudron/jupyterhub-app/ , so I am unable to update it to the latest release.

**Comment by manics** [comment]
This was delayed due to a mysterious change in setuptools which broke the conda build, it's now released https://github.com/conda-forge/jupyterhub-feedstock/pull/46

**Comment by gramakri** [comment]
Thanks, can confirm it's published now.

**Comment by gramakri** [comment]
@manics It seems 2.0.0 is not published now.

**Comment by minrk** [comment]
2.0 was published a few days ago: https://anaconda.org/conda-forge/jupyterhub/files?version=2.0.0

**Comment by gramakri** [comment]
Ah thanks, it is not listed in https://anaconda.org/conda-forge/jupyterhub for some reason. It still says 1.5, maybe I am not reading that page properly...

![image](https://user-images.githubusercontent.com/82041/144646461-ddbf6684-f2e6-4b80-8672-1a7148b1c031.png)

**Comment by minrk** [comment]
It is there in the screenshot - the 2.0 package also made the switch to `noarch`. I'm not sure why it still lists them all when there's a newer noarch build.
