### ISSUE TITLE
Unauthenticated requests in managed services in jupyterhub 2.0

### ISSUE THREAD

**Issue by djangoliv** [jupyterhub/jupyterhub#3691]
### Bug description

After upgrading to jupyterhub 2.0rc4 , requests made to my jupyterhub managed service are not authenticated (get_current_user() return None) even if I am authenticated.

My service handlers inherit from `jupyterhub.services.auth.HubAuthenticated` and `tornado.web.RequestHandler`.

My service is declared like this:
```
c.JupyterHub.services = [
    {
        'name': 'myservice',
        'url': 'http://127.0.0.1:8887',
        'command': [sys.executable, str(HERE.joinpath("my_service.py"))],
        'admin': True,
        'environment': dict(os.environ),
    }]
```

My python handler like this
```
class MyHandler(HubAuthenticated, web.RequestHandler):

    def get(self):
        self.write({'data': str(self.get_current_user())})

```
Is it a bug or should I update my handlers ?

Regards,

**Comment by minrk** [comment]
Can you describe how the requests are made? It's possible they are made with insufficient credentials, now that there are scopes controlling access to services.

If they are browser requests, you probably want to make sure you use `HubOAuthenticated` instead of `HubAuthenticated` which only accepts token-in-header requests.

Who is making the request, how are they making it (token-authenticated or via a browser), and what are their permissions?

Logs from the service around the rejected request would also be helpful.

**Comment by djangoliv** [comment]
Hi @minrk 

The requests are made by browser with an admin user.

I tried to change `HubOAuthenticated` to `HubOAuthenticated` and I have the following Exception:

`Exception: You must define the 'cookie_secret' setting in your application to use secure cookies`

So, I add

`c.JupyterHub.cookie_secret = bytes.fromhex('6951d95beedde4df9fc402450f6ebe607298e9917289f2a85eb59b591cbee728')`

to my jupyterhub_config.py but I still have this exception.

I also try to pass the environment variable JPY_COOKIE_SECRET to the environment of the service without no success.
Still have the same exception...

**Comment by minrk** [comment]
The cookie secret must be set for the service, which is why setting it in jupyterhub doesn't have the desired effect. It's not a Jupyter thing, it's a configuration on your [tornado application](https://www.tornadoweb.org/en/stable/guide/security.html#cookies-and-secure-cookies), however you instantiate that:

```python
app = tornado.web.Application(handlers, cookie_secret="...")
```

**Comment by djangoliv** [comment]
OK, thanks @minrk . I passed the cookie_secret to my application but I fall back into the same situation (like with HubAuthenticated).

Here the logs:
```

13:40:04.732 [ConfigProxy] info: 200 GET /api/routes 
[I 2021-11-26 13:40:29.251 JupyterHub log:189] 302 GET / -> /hub/ (@172.17.17.56) 1.67ms
[I 2021-11-26 13:40:29.274 JupyterHub log:189] 302 GET /hub/ -> /hub/app/ (@172.17.17.56) 1.25ms
[I 2021-11-26 13:40:29.317 JupyterHub log:189] 302 GET /hub/app/ -> /hub/login?next=%2Fhub%2Fapp%2F (@172.17.17.56) 1.83ms
[I 2021-11-26 13:40:29.370 JupyterHub log:189] 200 GET /hub/login?next=%2Fhub%2Fapp%2F (@172.17.17.56) 2.95ms
[W 2021-11-26 13:40:33.460 JupyterHub scopes:298] Authenticated with token <APIToken('4af3...', service='myservice', client_id='jupyterhub')>
[I 2021-11-26 13:40:33.501 JupyterHub log:189] 200 GET /hub/api/users/jupyter (myservice@127.0.0.1) 84.25ms
[W 2021-11-26 13:41:03.878 JupyterHub scopes:298] Authenticated with token <APIToken('4af3...', service='myservice', client_id='jupyterhub')>
[I 2021-11-26 13:41:03.913 JupyterHub log:189] 200 GET /hub/api/users/jupyter (myservice@127.0.0.1) 148.63ms
13:41:04.728 [ConfigProxy] info: 200 GET /api/routes 
WARNING:tornado.access:404 GET /services/myservice/ (127.0.0.1) 1.36ms


```

**Comment by minrk** [comment]
You don't need to override `get_current_user` if you are using HubOAuthenticated. And HubOAuthenticated should come first in the inheritance, since it overrides RequestHandler methods (specifically, get_current_user):


```python
class BaseHandler(HubOAuthenticated, tornado.web.RequestHandler):
    pass
```

You'll also need to register the `HubOAuthCallbackHandler` in your app at a callback URL to complete oauth.

**Comment by djangoliv** [comment]
thanks but I still have errors :(

I change my baseHandler with yours and then I have:

`WARNING:tornado.application:Detected unused OAuth state cookies`

and the same problem:

`get_current_user()` returns `None`

Thanks a lot for your help @minrk

**Comment by minrk** [comment]
Sorry, I'm not sure what's left that could be wrong. [here is a minimal example](https://github.com/jupyterhub/jupyterhub/blob/2.0.0rc5/examples/service-whoami/whoami-oauth.py) of setting up oauth for a tornado service.

**Comment by djangoliv** [comment]
@minrk : Thanks a lot, I managed to implement your suggestion but with this solution the user has to first go to an authorization page to be able to use my service.

Before (with jupyterhub 1.5 and HubAuthenticated), I suppose that we were relying on shared cookie authentication witch was removed in https://github.com/jupyterhub/jupyterhub/commit/863b4c7d50c00617ff5c7a67b176aa8ea0727317 .

Is it possible to remove the authorization step with HubOAuthenticated ? I would like that once the user has logged on jupyterhub, he can access my service without having to authorize it explicitly.

Thanks again for your support

**Comment by minrk** [comment]
> Is it possible to remove the authorization step with HubOAuthenticated

Yes! This is now an explicit, opt-in property. You can declare this with the `oauth_no_confirm` attribute in your service:

```python
c.JupyterHub.services = [
    {
        'name': 'myservice',
        'url': 'http://127.0.0.1:8887',
        'command': [sys.executable, str(HERE.joinpath("my_service.py"))],
        'oauth_no_confirm': True, # <--------
    },
]
```

**Comment by djangoliv** [comment]
:partying_face:  It works. Thanks a lot @minrk .
