### ISSUE TITLE
ingressClassName error 

### ISSUE THREAD

**Issue by chenshap** [jupyterhub/jupyterhub#3694]
### Bug description
upgrade jupyterhub version in order to use the new field ```ingressClassName``` replacing ```kubernetes.io/ingress.class``` and got an error

#### Actual behaviour
```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
jupyterhub:
- ingress: Additional property ingressClassName is not allowed
 ```
### How to reproduce
```
helm template jupyterhub/jupyterhub --version 1.2.0 --set ingress.enabled=true --set ingress.ingressClassName=someClassName
```

### Your personal set up

 - Version(s):
jupyterhub --version 1.2.0,
eks --version 1.2.1
ingress --version 1.19

is it a bug , or am I missing something?
regards,

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!

**Comment by consideRatio** [comment]
(Its not yet a released feature)
