### ISSUE TITLE
JupyterHub Admin page as React app does not respect bind_url

### ISSUE THREAD

**Issue by amoshche** [jupyterhub/jupyterhub#3729]
### Bug description
When hub runs binded not at the root but at some additional path for example /jupyter Admin UI is not working

#### Expected behaviour
Admin UI works
#### Actual behaviour
No UI rendered

In devtools in browser it is seen that admin-react.js /hub/api/users and /hub/api/users instead of /jupyter/hub/api/users /jupyter/hub/api/groups

### How to reproduce
set c.JupyterHub.bind_url to http://localhost:8000/jupyter
start JupyterHub
goto http://localhost:8000/jupyter/hub/admin

### Details
 - OS:
irrelevant
 - Version(s):
JupyterHub 2.0.0 20211217173434

**Comment by naatebarber** [comment]
This bug should be fixed in issue https://github.com/jupyterhub/jupyterhub/issues/3711.

**Comment by manics** [comment]
This will be fixed in the next release https://github.com/jupyterhub/jupyterhub/pull/3715
