### ISSUE TITLE
can not start jupyterhub due to configurable-http-proxy  unexpected keyword argument 'case_sensitive'

### ISSUE THREAD

**Issue by bestathena** [jupyterhub/jupyterhub#3742]
### Bug description

root@ubuntu01:~# configurable-http-proxy -h
Traceback (most recent call last):
  File "/usr/local/bin/configurable-http-proxy", line 5, in <module>
    from configurable_http_proxy.cli import main
  File "/usr/local/lib/python3.6/dist-packages/configurable_http_proxy/cli.py", line 130, in <module>
    case_sensitive=False,
TypeError: __init__() got an unexpected keyword argument 'case_sensitive'

root@ubuntu01:~# jupyterhub
[I 2021-12-31 02:42:59.580 JupyterHub app:2766] Running JupyterHub version 2.0.1
[I 2021-12-31 02:42:59.582 JupyterHub app:2797] Using Authenticator: jupyterhub.auth.PAMAuthenticator-2.0.1
[I 2021-12-31 02:42:59.582 JupyterHub app:2797] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-2.0.1
[I 2021-12-31 02:42:59.582 JupyterHub app:2797] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-2.0.1
[I 2021-12-31 02:42:59.597 JupyterHub app:1651] Writing cookie_secret to /root/jupyterhub_cookie_secret
[I 2021-12-31 02:42:59.742 alembic.runtime.migration migration:201] Context impl SQLiteImpl.
[I 2021-12-31 02:42:59.743 alembic.runtime.migration migration:208] Will assume non-transactional DDL.
[I 2021-12-31 02:42:59.767 alembic.runtime.migration migration:615] Running stamp_revision  -> 833da8570507
[I 2021-12-31 02:43:00.198 JupyterHub proxy:496] Generating new CONFIGPROXY_AUTH_TOKEN
[I 2021-12-31 02:43:00.239 JupyterHub app:1925] Not using allowed_users. Any authenticated user will be allowed.
[I 2021-12-31 02:43:00.265 JupyterHub app:2838] Initialized 0 spawners in 0.003 seconds
[W 2021-12-31 02:43:00.268 JupyterHub proxy:688] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2021-12-31 02:43:00.268 JupyterHub proxy:691] Starting proxy @ http://:8000
Traceback (most recent call last):
  File "/usr/local/bin/configurable-http-proxy", line 5, in <module>
    from configurable_http_proxy.cli import main
  File "/usr/local/lib/python3.6/dist-packages/configurable_http_proxy/cli.py", line 130, in <module>
    case_sensitive=False,
TypeError: __init__() got an unexpected keyword argument 'case_sensitive'
[C 2021-12-31 02:43:01.297 JupyterHub app:3045] Failed to start proxy
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 3043, in start
        await self.proxy.start()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/proxy.py", line 719, in start
        _check_process()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/proxy.py", line 715, in _check_process
        raise e from None
    RuntimeError: Proxy failed to start with exit code 1

### How to reproduce 

1. install configurable_http_proxy
pip3  install  configurable_http_proxy  --find_links=./      ( offline from pypi )    
2. install nodejs
node-v17.3.0-linux-x64.tar.gz  download from https://nodejs.org/en/download/current
3. install jupyterlab and jupyterhub
jupyterlab  can work

### Your personal set up

 - OS: ubuntu 18.04
 - root@ubuntu01:~# cat /proc/version
Linux version 4.15.0-162-generic (buildd@lcy01-amd64-007) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu118.04))

 - root@ubuntu01:~# python3 --version
Python 3.6.9
 - root@ubuntu01:~# node -v
v17.3.0
 - Version(s):
 - root@ubuntu01:~# jupyterhub --version
2.0.1
 

- <details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by manics** [comment]
The official configurable-http-proxy is an NPM package: https://www.npmjs.com/package/configurable-http-proxy

It looks like you're using a Python alternative: https://github.com/corridor/configurable-http-proxy

**Comment by bestathena** [comment]
> The official configurable-http-proxy is an NPM package: https://www.npmjs.com/package/configurable-http-proxy
> 
> It looks like you're using a Python alternative so please open an issue there: https://github.com/corridor/configurable-http-proxy

thank your for your reply. I used the Python configurable-http-proxy because ' npm install  configurable-http-proxy  ' shows  node version is too low.  now I  update   nodejs   by
curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -
sudo apt-get install -y nodejs
and install  configurable-http-proxy successfully!
