### ISSUE TITLE
jupyterhub2.01 root用户可正常使用，其他用户打开ipynb时提示500错误

### ISSUE THREAD

**Issue by ytattn009** [jupyterhub/jupyterhub#3743]
jupyterhub2.01 root用户可正常使用，其他用户打开ipynb时提示500错误，可否告知如何解决此问题，谢谢！

**Comment by consideRatio** [comment]
Hi! We need issues to be written in english. For questions about jupyterhub, use discourse.jupyter.org instead of creating an issue here.
