### ISSUE TITLE
What is the consensus to get the query parameters of a URL of a notebook rendered with voila in a jupyter Hub?

### ISSUE THREAD

**Issue by joseberlines** [jupyterhub/jupyterhub#3753]
Problem:
When rendering a notebook with voila in a JupyterHub environement we are parsing the URL in order to pass default variables into the rendered notebook, including for example "autorun=True that fires (autoclick) some of the buttons. This allows for opening and rendering notebooks from other notebooks and run them practically on the fly.

Use case:
When designing a GUI in a notebook with ipywidgets (@jasongrout https://github.com/jupyter-widgets/ipywidgets) or ipyvuetify (@mariobuikhuizen https://github.com/mariobuikhuizen/ipyvuetify) it is oftentimes very interesting to pass default variables into the URL to fill in default values into input text widgets or checkboxes or whatever input fields, including the possibility of passing variables that will automatically click and fire a particular process. This allows for dashboards with buttons that render instances of other notebooks in new tabs of the browser following user interactions with a notebook. This issue is also very much related to voila (@jtpio in https://github.com/voila-dashboards/voila).
This is a use case that somehow looks to me very normal but I dont know exactly in with which one of the mentioned repos is related.

Solution right now:
The solution entails the use of the following code:
```
    from urllib.parse import urlparse, parse_qs
    import os    
    URL_BASE = os.environ.get('SCRIPT_NAME')
    PARAMETERS = os.environ.get("QUERY_STRING")
    print(f'{URL_BASE=}')
    print(f'{PARAMETERS=}')
    captured_values = parse_qs(PARAMETERS)
    print('here parse_qs of query:',captured_values)
```

Is this the way it is supposed to be done? Is there a more Jupyter way to do it?
This approach has a problem, os.environ does not seem to offer the possibility to query the fragment of the url after the symbol #
See stackoverflow: 
https://stackoverflow.com/questions/70423180/python-getting-the-complete-url-with-os-environ

I have been reading quite a bit about this in different issues of voila & JupyterHub:
https://github.com/voila-dashboards/voila/issues/410#issue-504866187
https://discourse.jupyter.org/t/automatically-loading-external-data-into-jupyterhub-instances/5502
https://github.com/voila-dashboards/voila/pull/201
https://github.com/voila-dashboards/voila/pull/835

Somehow all those solutions/proposals/discussions do not seem to have a clear single most recommended solution for accesing the URL parameters in the context of a jupyterHub solution running in house (not using Binder).

### Proposed change
Add to the documentation of jupyterLab a recommended way to access all the parameters of an URL, iincluding the so called "fragment", i.e. parameters of the url after the # symbol

### Alternative options
Instead of os.environ other possibility is using the cgi module. Somehow I was not able to parse the complete URL but it seems to be possible and preferred by some people (

### Who would use this feature?
This feature/solution would be used by a community coding in a jupyter Hub server based in house solution where different users rendered notebooks of other users passing personal parameters (for instance the name of a document to be accessed in a database)

### (Optional): Suggest a solution
The solution ideally should not involve hacking around with jupyter Lab or extensions in Jupyter Hub since so far the users do not have the rights to install extensions, and the amount and different kind of parameters depends very much on the use case.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/method-to-access-query-string-in-voila-notebook/5387/5

**Comment by joseberlines** [comment]
It was me mentioning in Jupyter Coummunity Forum. I never now where things are happening more often, there or here in github

**Comment by manics** [comment]
Hi! In almost all cases Discourse is the right place for discussions and questions. GitHub issues are for bugs, and development/feature discussions (though even for these Discourse is often better since many new features/changes have an impact on the Jupyter community and benefit from more general discussions).

**Comment by joseberlines** [comment]
But Should I just copy/paste this whole text there?
