### ISSUE TITLE
JupyterHub caching files , will update once hub is restarted

### ISSUE THREAD

**Issue by Niru563** [jupyterhub/jupyterhub#3755]
### Bug description
I am having an issue with Jupyterhub caching user related files , it won't update unless I restart hub.I need to limit number of users who can login and start the single-user containers, I created 2 directories: active_user_directory and waiting_user_directory on shares NFS. I drop a json file for each active user in active_dir, when the limit is reached, the user json files are created in waiting_directory. Hub is not able to recognize that the user limit has reached unless I restart the jupyterhub process. 

### Your personal set up

 - OS:
 
 - Version(s):
 

- <details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!
