### ISSUE TITLE
GitHub CI tests are failing

### ISSUE THREAD

**Issue by manics** [jupyterhub/jupyterhub#3758]
### Bug description
GitHub CI tests are failing:
https://github.com/jupyterhub/jupyterhub/actions/runs/1675063992

This is unrelated to the [most recently merged PR](https://github.com/jupyterhub/jupyterhub/pull/3757), I've pushed the 2.0.1 tag to a temporary branch and it's also failing:
https://github.com/manics/jupyterhub/runs/4755478141?check_suite_focus=true

**Comment by consideRatio** [comment]
There seems to be a big difference between what was installed in the test run for the previously successfully merged commit compared to this one.

```diff
 backcall==0.2.0
 beautifulsoup4==4.10.0
 bleach==4.1.0
-certifi==2021.10.8
-certipy==0.1.3
-cffi==1.15.0
-cfgv==3.3.1
-charset-normalizer==2.0.10
-cli-ui==0.16.0
-codecov==2.1.12
-colorama==0.4.4
-contextlib2==21.6.0
-coverage==6.2
-cryptography==36.0.1
-debugpy==1.5.1
-decorator==5.1.1
-defusedxml==0.7.1
-distlib==0.3.4
-docopt==0.6.2
-entrypoints==0.3
-filelock==3.4.2
-greenlet==1.1.2
-html5lib==1.1
-identify==2.4.2
-idna==3.3
-importlib-metadata==4.10.0
-importlib-resources==5.4.0
-iniconfig==1.1.1
-ipykernel==6.6.1
-ipython==7.31.0
-ipython-genutils==0.2.0
-jedi==0.18.1
-Jinja2==3.0.3
-json5==0.9.6
-jsonschema==4.3.3
-jupyter-client==7.1.0
-jupyter-core==4.9.1
-jupyter-server==1.13.1
-jupyter-telemetry==0.1.0
-jupyterhub @ file:///home/runner/work/jupyterhub/jupyterhub
-jupyterlab==3.2.6
-jupyterlab-pygments==0.1.2
-jupyterlab-server==2.10.3
-Mako==1.1.6
-MarkupSafe==2.0.1
-matplotlib-inline==0.1.3
-mistune==0.8.4
-mock==4.0.3
-nbclassic==0.3.4
-nbclient==0.5.9
-nbconvert==6.4.0
-nbformat==5.1.3
-nest-asyncio==1.5.4
 nodeenv==1.6.0
 notebook==6.4.6
 oauthlib==3.1.1
```

**Comment by consideRatio** [comment]
Actually @manics, it seems like re-running the test that failed now works as well!

So, perhaps something was wrong with the runners for a while?

**Comment by minrk** [comment]
I think it might have been an intermittent problem with GHA itself. All dependencies are identical versions for [this passing run](https://github.com/jupyterhub/jupyterhub/runs/4757237185) and [this failing run](https://github.com/manics/jupyterhub/runs/4755478188). If you look at the failing output, it's a garbled mess:
<img width="1186" alt="Screen Shot 2022-01-10 at 09 24 13" src="https://user-images.githubusercontent.com/151929/148736371-bbe5a067-993a-4514-aab9-c7fef54656bd.png">

**Comment by manics** [comment]
Do we have faker.js or color.js anywhere in our stacks?
https://www.theverge.com/2022/1/9/22874949/developer-corrupts-open-source-libraries-projects-affected
