### ISSUE TITLE
Better handling of spawner failures

### ISSUE THREAD

**Issue by twalcari** [jupyterhub/jupyterhub#3761]
### Proposed change

Currently, when a Spawner fails to launch the Jupyter server, there is no good way in which it can inform the user of the cause.

I propose we define a "SpawnException" class that the spawner can throw, and which enables the spawner to pass an html_message that is used to display a nicely formatted exception (include some formatting, links to status pages of underlying systems, ...)

### Who would use this feature?

Advanced JupyterHub deployments can provide better error messages to inform the user about why their request failed: have they requested an invalid setup? Have they run out of quota? Is there a maintenance going on in the underlying system?

### Suggest a solution

Spawner class definition:

```
class SpawnException(Exception):
    def __init__(self, *args, html_message=None, **kwargs):
        super(SpawnException, self).__init__(*args, **kwargs)

        self.html_message = html_message
```

Add handling of this exception class in [SpawnProgressApiHandler](https://github.com/jupyterhub/jupyterhub/blob/e540d143bb8d219aca6023f104e3dbe76ca12bb8/jupyterhub/apihandlers/users.py#L716)

```
            if f and f.done() and f.exception():
                if isinstance(f.exception(), SpawnException) and f.exception().html_message is not None:
                   failed_event['html_message'] = f.exception().html_message
                failed_event['message'] = "Spawn failed: %s" % f.exception()
                await self.send_event(failed_event)

```

Log spawn failure as a warning/info instead of as an error in [user.py](https://github.com/jupyterhub/jupyterhub/blob/e540d143bb8d219aca6023f104e3dbe76ca12bb8/jupyterhub/user.py#L748), improve graceful handling of the SpawnException elsewhere.

**Comment by minrk** [comment]
Good idea! Spawners can already provide a custom failure message to users if they set [exception.jupyterhub_message](https://github.com/jupyterhub/jupyterhub/blob/e58cf0670690d11631f9dc6e1ab702c60f7bfd13/jupyterhub/handlers/pages.py?plain=1#L390), which is shown on the "server not running" page. We can extend support for this to the progress API as well. #3764
