### ISSUE TITLE
Have to install Notebook before starting JupyterHub successfully

### ISSUE THREAD

**Issue by GuanglinDu** [jupyterhub/jupyterhub#3771]
### Bug description

Jupyter Notebook is a prerequisite to run JupyterHub successfully. But the doc seems to indicate that `conda install -c conda-forge jupyterhub` will do all the installation magic.

#### Expected behaviour

After running `conda install jupyterhub` , I thought that executing `sudo env "PATH=$PATH" jupyterhub` would start JupyterHub without a hitch.

#### Actual behaviour

Actually, Jupyterhub failed starting with some error messages output, instead.

### How to reproduce

1. conda create -n env38 python=3.8
2. conda activate env38
3. conda install jupyterhub (Note: .condarc preconfigured to use local mirrors)
4. sudo  env "PATH=$PATH" jupyterhub

### Your personal set up

 - OS:
 
 An LXC container of Ubuntu 20.04, which is hosted on a Ubuntu 20.04 server installed on a bare metal IBM x3650 M3.
 - Version(s):
 
 Python 3.8.12, JupyterHub 2.0.2.

- <summary>Fix</summary>
```
conda install notebook
```

**Comment by manics** [comment]
JupyterHub is very configurable, and can run singleuser servers in many ways including locally or in remote containers. The readme already mentions needing to install notebook/jupyterlab separately:
https://github.com/jupyterhub/jupyterhub#using-conda

**Comment by GuanglinDu** [comment]
Thank you, @manics  & @github-actions, for your reply. I did hesitate for days before raising this question as I didn't know where to discuss such a question. @manics, I'm afraid the part your URL directs to is the very confusing part.
