### ISSUE TITLE
Getting "Failed to check authorization: invalid_client"

### ISSUE THREAD

**Issue by suhasadhav** [jupyterhub/jupyterhub#3783]
### Bug description
I am launching SingleNotebook server with Jupyterhub on Kubernetes. After launching the user server while redirecting with oauth_callback am getting 500 error saying "Failed to check authorization: invalid_client"

#### Expected behaviour
After authentication it should load single user notebook server page.

#### Actual behaviour
Getting 500 error saying "Failed to check authorization: invalid_client"

![image](https://user-images.githubusercontent.com/9277450/151792891-ba51129e-cd7a-4c8b-bbe1-9ef0c1e3ff7a.png)

### Your personal set up
Env: Kubernetes, KubeSpawner
Authenticator: Dummy

Jupyterlab: Version 2.2.8

- <details><summary>Full environment</summary>

```
bash-4.4$ pip3 freeze
alembic==1.7.5
argon2-cffi==21.1.0
async-generator==1.10
attrs==21.2.0
backcall==0.2.0
bleach==4.1.0
certifi==2021.10.8
certipy==0.1.3
cffi==1.15.0
charset-normalizer==2.0.8
colorama==0.4.4
cryptography==36.0.0
debugpy==1.5.1
decorator==5.1.0
defusedxml==0.7.1
entrypoints==0.3
findspark==1.4.2
gitdb==4.0.9
GitPython==3.1.24
greenlet==1.1.2
idna==3.3
ipykernel==6.5.1
ipython==7.30.0
ipython-genutils==0.2.0
ipywidgets==7.6.5
jedi==0.18.1
Jinja2==3.0.3
json5==0.9.6
jsonschema==4.2.1
jupyter-client==7.1.0
jupyter-core==4.9.1
jupyter-telemetry==0.1.0
jupyterhub==1.2.1
jupyterlab==2.2.8
jupyterlab-git==0.22.2
jupyterlab-pygments==0.1.2
jupyterlab-server==1.2.0
jupyterlab-widgets==1.0.2
Mako==1.1.6
MarkupSafe==2.0.1
matplotlib-inline==0.1.3
metakernel==0.28.1
mistune==0.8.4
nbclient==0.5.9
nbconvert==6.3.0
nbdime==2.1.1
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.1.5
numpy==1.21.4
oauthlib==3.1.1
packaging==21.3
pamela==1.0.0
pandas==1.3.4
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
prometheus-client==0.12.0
prompt-toolkit==3.0.23
ptyprocess==0.7.0
py4j==0.10.9.2
pyarrow==6.0.1
pycparser==2.21
Pygments==2.10.0
pyOpenSSL==21.0.0
pyparsing==3.0.6
pyrsistent==0.18.0
pyspark==3.2.0
python-dateutil==2.8.2
python-json-logger==2.0.2
pytz==2021.3
PyYAML==6.0
pyzmq==22.3.0
requests==2.26.0
ruamel.yaml==0.17.17
ruamel.yaml.clib==0.2.6
Send2Trash==1.8.0
six==1.16.0
smmap==5.0.0
spylon==0.3.0
spylon-kernel==0.4.1
SQLAlchemy==1.4.27
terminado==0.12.1
testpath==0.5.0
tornado==6.1
traitlets==5.1.1
typing-extensions==4.0.1
urllib3==1.26.7
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.2
```
</details>

- <details><summary>Configuration</summary>

```python
c.ConfigurableHTTPProxy.should_start = False
c.ConfigurableHTTPProxy.api_url = f"http://jupyter-hub-proxy-api:8001"

c.JupyterHub.hub_bind_url = f'http://:8080'
c.JupyterHub.hub_connect_url = f"http://jupyter-hub:8080"

c.JupyterHub.spawner_class = 'kubespawner.KubeSpawner'
c.KubeSpawner.cmd = ["start.sh", "--SingleUserNotebookApp.default_url=/lab"]
c.Spawner.http_timeout = 1800
c.Spawner.start_timeout = 1800

c.KubeSpawner.storage_capacity = "300M"
c.KubeSpawner.delete_pvc = False
c.KubeSpawner.pvc_name_template = 'claim-{username}--{servername}'
c.KubeSpawner.storage_pvc_ensure = True
c.KubeSpawner.working_dir = "/home/admin"
c.KubeSpawner.cpu_guarantee = 0.1
c.KubeSpawner.mem_guarantee = "0.5G"
c.KubeSpawner.cpu_limit = 2
c.KubeSpawner.mem_limit = "4G"
c.KubeSpawner.namespace = "jupyterhub-qa"
c.KubeSpawner.image_pull_policy='Always'

c.KubeSpawner.image = 'artifactorycn.suhas.com:17014/product/pyspark-jupyterhub_build:0.1-2'

c.KubeSpawner.environment.update({
        "HADOOP_CONF_DIR": "/etc/hadoop/conf",
        "SPARK_CONF_DIR": "/home/admin/conf",
        "PYSPARK_PYTHON": "/usr/local/bin/python3.9",
        "PYSPARK_DRIVER_PYTHON": "/usr/local/bin/python3.9",
        "JUPYTERHUB_API_URL": "http://jupyter.jupyterhub-qa.datahub2-suhas.cloud/hub/api",
        "JUPYTERHUB_ACTIVITY_URL": "http://jupyter.jupyterhub-qa.datahub2-suhas.cloud/hub/api/users/{username}/activity"
})
c.KubeSpawner.volume_mounts = [{
          "name": "get-hadoop-conf",
          "mountPath": "/scripts/get_hadoop_conf.sh",
          "subPath": "get_hadoop_conf.sh"
},{
          "name": "clean-hive-config",
          "mountPath": "/scripts/clean_hive_config.py",
          "subPath": "clean_hive_config.py"
},{
          "name": "claim-{username}--{servername}",
          "mountPath": "/home/admin",
          "subPath": "value"
},{
          "name": "spark-conf",
          "mountPath": "/tmp/spark-defaults.conf",
          "subPath": "spark-defaults.conf"
},{
          "name": "pyspark-init-configmap",
          "mountPath": "/scripts/pyspark-init.sh",
          "subPath": "pyspark-init.sh"
}]

c.KubeSpawner.volumes = [{
        "name": "claim-{username}--{servername}",
        "persistentVolumeClaim": {
          "claimName": "claim-{username}--{servername}"
        }
        },{
        "name": "get-hadoop-conf",
        "configMap": {
          "name": "get-hadoop-conf",
          "defaultMode": 0o0777
        }
        },{
        "name": "clean-hive-config",
        "configMap": {
          "name": "clean-hive-config",
          "defaultMode": 0o0777
        }
        },{
        "name": "spark-conf",
        "configMap": {
          "name": "spark-conf",
          "defaultMode": 0o0777
        }
        },{
        "name": "pyspark-init-configmap",
        "configMap": {
          "name": "pyspark-init-configmap",
          "defaultMode": 0o0777
        }
        }
]
c.KubeSpawner.extra_labels = {
"username": "{username}",
"spark": "{username}-driver"
}
c.KubeSpawner.service_account = "jupyter-hub"
c.JupyterHub.authenticator_class = "jupyterhub.auth.DummyAuthenticator"
c.Authenticator.whitelist = ['user']
c.DummyAuthenticator.password = "useruser"
c.KubeSpawner.extra_container_config = {
  "ports": [
    {
      "name": "http",
      "containerPort": 8080,
      "protocol": "TCP"
    },
    {
      "name": "blockmanager",
      "containerPort": 7777,
      "protocol": "TCP"
    },
    {
      "name": "driver",
      "containerPort": 2222,
      "protocol": "TCP"
    }
  ],
  "securityContext": {
    "runAsUser": 1000
  }
}
c.KubeSpawner.lifecycle_hooks = {
  "postStart": {
    "exec": {
        "command": ["/bin/bash", "-c", "/scripts/pyspark-init.sh"]
    }
  }
}
c.KubeSpawner.extra_pod_config = {
  "hostNetwork": True
}```
</details>


```
# paste relevant logs here, if any
**JupyterHub Logs:**
[D 2022-01-31 12:27:00.762 JupyterHub application:730] Looking for /etc/jupyterhub/jupyterhub_config in /srv/jupyterhub
[D 2022-01-31 12:27:00.763 JupyterHub application:752] Loaded config file: /etc/jupyterhub/jupyterhub_config.py
[I 2022-01-31 12:27:01.085 JupyterHub app:2332] Running JupyterHub version 1.2.1
[I 2022-01-31 12:27:01.086 JupyterHub app:2362] Using Authenticator: jupyterhub.auth.DummyAuthenticator-1.2.1
[I 2022-01-31 12:27:01.086 JupyterHub app:2362] Using Spawner: kubespawner.spawner.KubeSpawner-0.14.1
[I 2022-01-31 12:27:01.086 JupyterHub app:2362] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.2.1
[D 2022-01-31 12:27:01.099 JupyterHub app:1452] Generating new cookie_secret
[I 2022-01-31 12:27:01.100 JupyterHub app:1457] Writing cookie_secret to /srv/jupyterhub/jupyterhub_cookie_secret
[D 2022-01-31 12:27:01.101 JupyterHub app:1579] Connecting to db: sqlite:///jupyterhub.sqlite
[D 2022-01-31 12:27:01.119 JupyterHub orm:784] Stamping empty database with alembic revision 4dc2d5a8c53c
[I 2022-01-31 12:27:01.125 alembic.runtime.migration migration:155] Context impl SQLiteImpl.
[I 2022-01-31 12:27:01.125 alembic.runtime.migration migration:158] Will assume non-transactional DDL.
[I 2022-01-31 12:27:01.140 alembic.runtime.migration migration:517] Running stamp_revision  -> 4dc2d5a8c53c
[D 2022-01-31 12:27:01.141 alembic.runtime.migration migration:727] new branch insert 4dc2d5a8c53c
[W 2022-01-31 12:27:01.297 JupyterHub auth:153] DummyAuthenticator.whitelist is deprecated in JupyterHub 1.2, use DummyAuthenticator.allowed_users instead
[W 2022-01-31 12:27:01.297 JupyterHub app:1687] No admin users, admin interface will be unavailable.
[W 2022-01-31 12:27:01.297 JupyterHub app:1688] Add any administrative users to `c.Authenticator.admin_users` in config.
[D 2022-01-31 12:27:01.354 JupyterHub app:1869] Purging expired APITokens
[D 2022-01-31 12:27:01.357 JupyterHub app:1869] Purging expired OAuthAccessTokens
[D 2022-01-31 12:27:01.359 JupyterHub app:1869] Purging expired OAuthCodes
[D 2022-01-31 12:27:01.367 JupyterHub app:1996] Initializing spawners
[D 2022-01-31 12:27:01.369 JupyterHub app:2129] Loaded users:
    
[I 2022-01-31 12:27:01.369 JupyterHub app:2399] Initialized 0 spawners in 0.003 seconds
[I 2022-01-31 12:27:01.371 JupyterHub app:2611] Not starting proxy
[D 2022-01-31 12:27:01.372 JupyterHub proxy:766] Proxy: Fetching GET http://jupyter-hub-proxy-api:8001/api/routes
[I 2022-01-31 12:27:01.379 JupyterHub app:2647] Hub API listening on http://:8080/hub/
[I 2022-01-31 12:27:01.379 JupyterHub app:2649] Private Hub API connect url http://jupyter-hub:8080/hub/
[D 2022-01-31 12:27:01.379 JupyterHub proxy:315] Fetching routes to check
[D 2022-01-31 12:27:01.379 JupyterHub proxy:766] Proxy: Fetching GET http://jupyter-hub-proxy-api:8001/api/routes
[I 2022-01-31 12:27:01.382 JupyterHub proxy:320] Checking routes
[W 2022-01-31 12:27:01.382 JupyterHub proxy:391] Deleting stale route /user/nikolay/
[D 2022-01-31 12:27:01.382 JupyterHub proxy:766] Proxy: Fetching DELETE http://jupyter-hub-proxy-api:8001/api/routes/user/nikolay
[I 2022-01-31 12:27:01.384 JupyterHub app:2722] JupyterHub is now running at http://:8000
[D 2022-01-31 12:27:01.385 JupyterHub app:2325] It took 0.628 seconds for the Hub to start
[I 2022-01-31 12:27:38.227 JupyterHub log:181] 302 GET / -> /hub/ (@192.168.0.18) 1.26ms
[W 2022-01-31 12:27:38.596 JupyterHub base:389] Invalid or expired cookie token
[I 2022-01-31 12:27:38.597 JupyterHub log:181] 302 GET /hub/ -> /hub/login (@192.168.0.18) 1.70ms
[I 2022-01-31 12:27:39.033 JupyterHub log:181] 200 GET /hub/login (@192.168.0.18) 34.19ms
[D 2022-01-31 12:27:49.686 JupyterHub base:523] Setting cookie for nikolay: jupyterhub-hub-login
[D 2022-01-31 12:27:49.686 JupyterHub base:519] Setting cookie jupyterhub-hub-login: {'httponly': True, 'path': '/hub/'}
[I 2022-01-31 12:27:49.687 JupyterHub base:746] User logged in: nikolay
[D 2022-01-31 12:27:49.687 JupyterHub user:289] Creating <class 'kubespawner.spawner.KubeSpawner'> for nikolay:
[W 2022-01-31 12:27:49.690 JupyterHub configurable:190] Config option `delete_pvc` not recognized by `KubeSpawner`.
[D 2022-01-31 12:27:49.690 JupyterHub spawner:172] Starting executor thread pool with 20 workers
[I 2022-01-31 12:27:49.705 JupyterHub reflector:201] watching for pods with label selector='component=singleuser-server' in namespace jupyterhub-qa
[D 2022-01-31 12:27:49.705 JupyterHub reflector:206] Connecting pods watcher
[I 2022-01-31 12:27:49.724 JupyterHub reflector:201] watching for events with field selector='involvedObject.kind=Pod' in namespace jupyterhub-qa
[D 2022-01-31 12:27:49.724 JupyterHub reflector:206] Connecting events watcher
[I 2022-01-31 12:27:49.727 JupyterHub log:181] 302 POST /hub/login?next= -> /hub/spawn (nikolay@192.168.0.18) 60.87ms
[D 2022-01-31 12:27:50.104 JupyterHub base:282] Recording first activity for <User(nikolay 0/1 running)>
[D 2022-01-31 12:27:50.115 JupyterHub pages:213] Triggering spawn with default options for nikolay
[D 2022-01-31 12:27:50.116 JupyterHub base:864] Initiating spawn for nikolay
[D 2022-01-31 12:27:50.116 JupyterHub base:868] 0/100 concurrent spawns
[D 2022-01-31 12:27:50.116 JupyterHub base:873] 0 active servers
[D 2022-01-31 12:27:50.170 JupyterHub user:603] Calling Spawner.start for nikolay
[I 2022-01-31 12:27:50.171 JupyterHub spawner:1840] Attempting to create pvc claim-nikolay, with timeout 3
[I 2022-01-31 12:27:50.190 JupyterHub spawner:1852] PVC claim-nikolay already exists, so did not create new pvc.
[W 2022-01-31 12:27:50.194 JupyterHub utils:70] 'notebook_container.ports' current value: '[{'container_port': 8888,
     'host_ip': None,
     'host_port': None,
     'name': 'notebook-port',
     'protocol': None}]' is overridden with '[{'name': 'http', 'containerPort': 8080, 'protocol': 'TCP'}, {'name': 'blockmanager', 'containerPort': 7777, 'protocol': 'TCP'}, {'name': 'driver', 'containerPort': 2222, 'protocol': 'TCP'}]', which is the value of 'extra_container_config.ports'.
[W 2022-01-31 12:27:50.194 JupyterHub utils:70] 'notebook_container.security_context' current value: '{'allow_privilege_escalation': None,
     'capabilities': None,
     'privileged': None,
     'proc_mount': None,
     'read_only_root_filesystem': None,
     'run_as_group': 0,
     'run_as_non_root': None,
     'run_as_user': 0,
     'se_linux_options': None,
     'windows_options': None}' is overridden with '{'runAsUser': 1000}', which is the value of 'extra_container_config.security_context'.
[I 2022-01-31 12:27:50.195 JupyterHub spawner:1805] Attempting to create pod jupyter-nikolay, with timeout 3
[I 2022-01-31 12:27:51.117 JupyterHub log:181] 302 GET /hub/spawn -> /hub/spawn-pending/nikolay (nikolay@192.168.0.18) 1014.96ms
[I 2022-01-31 12:27:51.509 JupyterHub pages:398] nikolay is pending spawn
[I 2022-01-31 12:27:51.514 JupyterHub log:181] 200 GET /hub/spawn-pending/nikolay (nikolay@192.168.0.18) 8.05ms
[D 2022-01-31 12:27:54.795 JupyterHub spawner:1676] progress generator: jupyter-nikolay
[D 2022-01-31 12:27:59.715 JupyterHub reflector:275] pods watcher timeout
[D 2022-01-31 12:27:59.715 JupyterHub reflector:206] Connecting pods watcher
[D 2022-01-31 12:27:59.734 JupyterHub reflector:275] events watcher timeout
[D 2022-01-31 12:27:59.734 JupyterHub reflector:206] Connecting events watcher
[W 2022-01-31 12:28:00.118 JupyterHub base:992] User nikolay is slow to start (timeout=10)
[D 2022-01-31 12:28:09.723 JupyterHub reflector:275] pods watcher timeout
[D 2022-01-31 12:28:09.723 JupyterHub reflector:206] Connecting pods watcher
[D 2022-01-31 12:28:09.748 JupyterHub reflector:275] events watcher timeout
[D 2022-01-31 12:28:09.748 JupyterHub reflector:206] Connecting events watcher
[D 2022-01-31 12:28:10.796 JupyterHub spawner:1936] pod jupyter-nikolay events before launch: 2022-01-31T12:27:50.208424Z [Normal] Successfully assigned jupyterhub-qa/jupyter-nikolay to worker3-datahub-msk8s
    2022-01-31T12:27:55Z [Normal] AttachVolume.Attach succeeded for volume "pvc-cebd6c00-1e4b-4309-b4e2-ac80770377b7" 
    2022-01-31T12:28:06Z [Normal] Pulling image "artifactorycn.suhas.com:17014/product/pyspark-jupyterhub_build:0.1-2"
    2022-01-31T12:28:07Z [Normal] Successfully pulled image "artifactorycn.suhas.com:17014/product/pyspark-jupyterhub_build:0.1-2" in 283.848368ms
    2022-01-31T12:28:07Z [Normal] Created container notebook
    2022-01-31T12:28:07Z [Normal] Started container notebook
[D 2022-01-31 12:28:10.806 JupyterHub spawner:1151] Polling subprocess every 30s
[D 2022-01-31 12:28:10.822 JupyterHub utils:220] Server at http://192.168.0.19:8888/user/nikolay/ responded with 302
[D 2022-01-31 12:28:10.823 JupyterHub _version:76] jupyterhub and jupyterhub-singleuser both on version 1.2.1
[I 2022-01-31 12:28:10.823 JupyterHub base:893] User nikolay took 20.707 seconds to start
[I 2022-01-31 12:28:10.823 JupyterHub proxy:258] Adding user nikolay to proxy /user/nikolay/ => http://192.168.0.19:8888
[D 2022-01-31 12:28:10.823 JupyterHub proxy:766] Proxy: Fetching POST http://jupyter-hub-proxy-api:8001/api/routes/user/nikolay
[I 2022-01-31 12:28:10.827 JupyterHub users:609] Server nikolay is ready
[I 2022-01-31 12:28:10.828 JupyterHub log:181] 200 GET /hub/api/users/nikolay/server/progress (nikolay@192.168.0.18) 16037.70ms
[I 2022-01-31 12:28:11.284 JupyterHub log:181] 302 GET /hub/spawn-pending/nikolay -> /user/nikolay/ (nikolay@192.168.0.18) 3.65ms
[D 2022-01-31 12:28:12.438 JupyterHub provider:409] Validating client id jupyterhub-user-nikolay
[D 2022-01-31 12:28:12.439 JupyterHub provider:484] validate_redirect_uri: client_id=jupyterhub-user-nikolay, redirect_uri=/user/nikolay/oauth_callback
[D 2022-01-31 12:28:12.443 JupyterHub auth:244] Skipping oauth confirmation for <User(nikolay 1/1 running)> accessing Server at /user/nikolay/
[D 2022-01-31 12:28:12.444 JupyterHub provider:409] Validating client id jupyterhub-user-nikolay
[D 2022-01-31 12:28:12.445 JupyterHub provider:484] validate_redirect_uri: client_id=jupyterhub-user-nikolay, redirect_uri=/user/nikolay/oauth_callback
[D 2022-01-31 12:28:12.447 JupyterHub provider:231] Saving authorization code jupyterhub-user-nikolay, NTr..., (), {}
[I 2022-01-31 12:28:12.459 JupyterHub log:181] 302 GET /hub/api/oauth2/authorize?client_id=jupyterhub-user-nikolay&redirect_uri=%2Fuser%2Fnikolay%2Foauth_callback&response_type=code&state=[secret] -> /user/nikolay/oauth_callback?code=[secret]&state=[secret] (nikolay@192.168.0.18) 24.79ms

**SingleNotebook Logs:**
[W 2022-01-31 12:28:08.047 SingleUserNotebookApp configurable:193] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
[D 2022-01-31 12:28:08.051 SingleUserNotebookApp config_manager:97] Paths used for configuration of jupyter_notebook_config: 
    	/etc/jupyter/jupyter_notebook_config.json
[D 2022-01-31 12:28:08.052 SingleUserNotebookApp config_manager:97] Paths used for configuration of jupyter_notebook_config: 
    	/usr/local/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
    	/usr/local/etc/jupyter/jupyter_notebook_config.d/jupyterlab_git.json
    	/usr/local/etc/jupyter/jupyter_notebook_config.d/nbdime.json
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 2022-01-31 12:28:08.053 SingleUserNotebookApp config_manager:97] Paths used for configuration of jupyter_notebook_config: 
    	/usr/etc/jupyter/jupyter_notebook_config.json
[D 2022-01-31 12:28:08.053 SingleUserNotebookApp config_manager:97] Paths used for configuration of jupyter_notebook_config: 
    	/home/admin/.local/etc/jupyter/jupyter_notebook_config.json
[D 2022-01-31 12:28:08.053 SingleUserNotebookApp config_manager:97] Paths used for configuration of jupyter_notebook_config: 
    	/home/admin/.jupyter/jupyter_notebook_config.json
[I 2022-01-31 12:28:08.852 SingleUserNotebookApp extension:162] JupyterLab extension loaded from /usr/local/lib/python3.9/site-packages/jupyterlab
[I 2022-01-31 12:28:08.852 SingleUserNotebookApp extension:163] JupyterLab application directory is /usr/local/share/jupyter/lab
[D 2022-01-31 12:28:08.945 SingleUserNotebookApp loader:499] Using default logger
[D 2022-01-31 12:28:08.945 SingleUserNotebookApp loader:499] Using default logger
[D 2022-01-31 12:28:08.946 SingleUserNotebookApp loader:499] Using default logger
[D 2022-01-31 12:28:08.946 SingleUserNotebookApp loader:499] Using default logger
[D 2022-01-31 12:28:08.946 SingleUserNotebookApp loader:499] Using default logger
[D 2022-01-31 12:28:08.946 SingleUserNotebookApp loader:499] Using default logger
[I 2022-01-31 12:28:08.948 SingleUserNotebookApp mixins:558] Starting jupyterhub-singleuser server version 1.2.1
[I 2022-01-31 12:28:10.822 SingleUserNotebookApp log:181] 302 GET /user/nikolay/ -> /user/nikolay/lab? (@192.168.0.6) 1.41ms
[I 2022-01-31 12:28:11.663 SingleUserNotebookApp log:181] 302 GET /user/nikolay/ -> /user/nikolay/lab? (@192.168.0.18) 1.19ms
[D 2022-01-31 12:28:11.978 SingleUserNotebookApp _version:76] jupyterhub and jupyterhub-singleuser both on version 1.2.1
[I 2022-01-31 12:28:11.979 SingleUserNotebookApp notebookapp:2209] Serving notebooks from local directory: /home/admin
[I 2022-01-31 12:28:11.979 SingleUserNotebookApp notebookapp:2209] Jupyter Notebook 6.1.5 is running at:
[I 2022-01-31 12:28:11.979 SingleUserNotebookApp notebookapp:2209] http://worker3-datahub-msk8s:8888/user/nikolay/
[I 2022-01-31 12:28:11.979 SingleUserNotebookApp notebookapp:2210] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2022-01-31 12:28:11.984 SingleUserNotebookApp mixins:538] Updating Hub with activity every 300 seconds
[D 2022-01-31 12:28:11.984 SingleUserNotebookApp mixins:500] Notifying Hub of activity 2022-01-31T12:28:08.064737Z
[E 2022-01-31 12:28:12.003 SingleUserNotebookApp mixins:520] Error notifying Hub of activity
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/jupyterhub/singleuser/mixins.py", line 518, in notify
        await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
[D 2022-01-31 12:28:12.042 SingleUserNotebookApp auth:505] No user identified
[D 2022-01-31 12:28:12.044 SingleUserNotebookApp auth:836] Redirecting to login url: /hub/api/oauth2/authorize?client_id=jupyterhub-user-nikolay&redirect_uri=%2Fuser%2Fnikolay%2Foauth_callback&response_type=code&state=eyJ1dWlkIjogImYxNWE3Y2VjNTUyNDQ0ZTJhMjc1ZDEwZGQ5M2VlZTIyIiwgIm5leHRfdXJsIjogIi91c2VyL25pa29sYXkvbGFiPyJ9
**[I 2022-01-31 12:28:12.045 SingleUserNotebookApp log:181] 302 GET /user/nikolay/lab? -> /hub/api/oauth2/authorize?client_id=jupyterhub-user-nikolay&redirect_uri=%2Fuser%2Fnikolay%2Foauth_callback&response_type=code&state=[secret] (@192.168.0.18) 3.72ms
[D 2022-01-31 12:28:12.838 SingleUserNotebookApp auth:505] No user identified
[W 2022-01-31 12:28:12.863 SingleUserNotebookApp auth:369] Failed to check authorization: [401] Unauthorized
[W 2022-01-31 12:28:12.863 SingleUserNotebookApp auth:372] {"error": "invalid_client"}
[W 2022-01-31 12:28:12.863 SingleUserNotebookApp web:1787] 500 GET /user/nikolay/oauth_callback?code=NTreocWmFXzSk7ar24ZK7OzTjdaSfE&state=eyJ1dWlkIjogImYxNWE3Y2VjNTUyNDQ0ZTJhMjc1ZDEwZGQ5M2VlZTIyIiwgIm5leHRfdXJsIjogIi91c2VyL25pa29sYXkvbGFiPyJ9 (192.168.0.18): Failed to check authorization: invalid_client**
[D 2022-01-31 12:28:12.864 SingleUserNotebookApp handlers:251] Using contents: services/contents
[D 2022-01-31 12:28:12.865 SingleUserNotebookApp handlers:251] Using contents: services/contents
```

**Comment by consideRatio** [comment]
I'm not sure about the issue, but it is a lot of custom configuration and its therefore very likely that this is a configuration error rather than a bug in the jupyterhub. Due to that, and because its too hard to investigate further given the large amount of custom configuration to reproduce it, I'd ask that you request help at discourse.jupyter.org.

If you want a functional example on installing a jupyterhub with kubespawner in k8s, see z2jh.jupyter.org and the official Helm chart at https://github.com/jupyterhub/zero-to-jupyterhub-k8s.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/getting-failed-to-check-authorization-invalid-client/12818/1
