### ISSUE TITLE
Named servers aren't listed on admin page

### ISSUE THREAD

**Issue by manics** [jupyterhub/jupyterhub#3788]
### Bug description
Reported at https://discourse.jupyter.org/t/named-servers-do-not-show-up-in-admin-console-after-2-0-upgrade/12928

Named servers aren't listed on the hub admin page

#### Expected behaviour
JupyterHub 1.5.0 shows servers `test` and `test/named` for user `test`:
![image](https://user-images.githubusercontent.com/1644105/153070145-2c107946-64fa-4a82-9797-d60076ae330c.png)

#### Actual behaviour
JupyterHub 2.1.1 does not show server `test/named`:
![image](https://user-images.githubusercontent.com/1644105/153070240-def26f7e-5138-4824-9650-43d84b74df13.png)

### How to reproduce
Start a named server as a non-admin:
![image](https://user-images.githubusercontent.com/1644105/153070410-68845fed-e6f7-4a2e-a3f0-959c5786f41d.png)
Log on separately as an admin and go to `/hub/admin`

### Your personal set up
`jupyterhub_config.py`:
```py
c = get_config()
c.JupyterHub.spawner_class = "simple"
c.JupyterHub.authenticator_class = "dummy"
c.Authenticator.admin_users = {'demo'}
c.JupyterHub.allow_named_servers = True
c.JupyterHub.named_server_limit_per_user = 2
```

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/named-servers-do-not-show-up-in-admin-console-after-2-0-upgrade/12928/2

**Comment by manics** [comment]
The backend API call `http://localhost:8000/hub/api/users?offset=0&limit=50` contains the named servers, so the issue is with the UI.

**Comment by manics** [comment]
It looks like
https://github.com/jupyterhub/jupyterhub/blob/3ed345f4960f083b2d35c72b330254aa3cf31fe9/jsx/src/components/ServerDashboard/ServerDashboard.jsx#L230-L238
iterates through the list of users and only looks at `e.server`, when instead it should iterate through `e.servers[]` which includes the default and named servers.

**Comment by NarekA** [comment]
@manics that seems to fix the issue. I drafted a PR fixing this and other admin console fixes here: https://github.com/jupyterhub/jupyterhub/pull/379
![Screen Shot 2022-02-09 at 11 52 36 AM](https://user-images.githubusercontent.com/737367/153280694-b366d277-a6f5-4e85-ab83-e1b89303b500.png)
0
