### ISSUE TITLE
No attribute 'cookie_name' on HubAuth in JupyterHub 1.4.2

### ISSUE THREAD

**Issue by nhp002** [jupyterhub/jupyterhub#3796]
#### Expected behaviour

Authentication method in Flask example should run without issues.

#### Actual behaviour

Authentication method fails because of an error that says: <code>'HubAuth' object has no attribute 'cookie_name'</code>

### How to reproduce

1. Use [JupyterHub 1.4.2 Flask Example](https://jupyterhub.readthedocs.io/en/1.4.2/reference/services.html#flask-example)
2. Start JupyterHub and externally managed Flask app
```bash
docker-compose up --build
```
3. Launch JupyterHub Flask service through JupyterHub website running on <code>localhost:8000</code>
4. There will be an error in the 'authenticated' method of the Flask example on this line:
```python
cookie = request.cookies.get(auth.cookie_name)
```

Error displayed on JupyterHub: <code>AttributeError: 'HubAuth' object has no attribute 'cookie_name'</code>

### Your personal set up

 - OS: Windows 11
 
 - Version(s): JupyterHub 1.4.2, Python 3.8.7
 

### Full environment
JupyterHub Dockerfile
```Dockerfile
FROM jupyterhub/jupyterhub:1.4.2

RUN pip install notebook

RUN useradd -m admin

COPY jupyterhub_config.py /app/jupyterhub_config.py

WORKDIR /app
```

Flask Dockerfile
```Dockerfile
FROM python:3.8.7

COPY . /app

ENV FLASK_APP=server.py

RUN pip install flask 
RUN pip install requests
RUN pip install jupyterhub
RUN pip install Jinja2


RUN export CONFIGPROXY_AUTH_TOKEN=$(openssl rand -hex 32)


WORKDIR /app

CMD flask run --host 0.0.0.0 --port 5000
```
docker-compose.yml
```Dockerfile
version: '3.2'
services:
  server:
    build: ./server
    ports:
      - '5000:5000'
    depends_on:
      - jupyterhub
    volumes:
      - ./server:/app
    environment:
      - WEB_APIKEY=<WEB_APIKEY>
      - BACKENDURL=web
      - BACKENDPORT=3000
      - JUPYTER_ADDR=jupyterhub
      - PORT=8000
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - JUPYTERHUB_API_TOKEN=<JUPYTERHUB_API_TOKEN>
      - HOME_ADDR=localhost:8000
  jupyterhub:
    build: ./jupyterhub
    ports:
      - '8000:8000'
    volumes:
      - ./jupyterhub:/app
    environment:
      - FRONT_END_URL=server
      - PORT=5000
    command:
      - jupyterhub
      - -f
      - /app/jupyterhub_config.py
```

- <details><summary>Configuration</summary>

jupyterhub_config.py
```Python
import os

frontend_url = 'http://'+os.getenv('FRONT_END_URL')+':'+os.getenv('PORT')+'/'
c.JupyterHub.services = [
    {
        'name': 'flask-example-service',
        'url': frontend_url,
        'api_token': '<api_token>'
    },
]
# dummy authenticator used for development. Need to remove this line in production
c.JupyterHub.authenticator_class = 'jupyterhub.auth.DummyAuthenticator'
c.JupyterHub.hub_ip = '0.0.0.0'
```
</details>

- <details><summary>Logs</summary>

```
AttributeError: 'HubAuth' object has no attribute 'cookie_name'
```
</details>

**Comment by manics** [comment]
The current version of JupyterHub is 2.1.1. Are you seeing the same problem with that version?

**Comment by nhp002** [comment]
I believe the <code>cookie_name</code> HubAuth attribute is deprecated in newer versions. However, it appears to be broken for the older versions that should support it.

**Comment by minrk** [comment]
From those Dockerfiles, it looks like you probably have jupyterhub 2.1.1 in your service, since the install of jupyterhub doesn't specify a version, unlike the pin of 1.4.2 in the jupyterhub image. Can you run `pip list` in your `server` image? You can pin with `pip install jupyterhub==1.4.2` in your Dockerfile (or use requirements.txt / requirements.in).

**Comment by nhp002** [comment]
Specifying the package version solved the problem. Thank you!
