### ISSUE TITLE
Autosave Failed

### ISSUE THREAD

**Issue by IILolitaII** [jupyterhub/jupyterhub#3836]
### Bug description

When I have the word '''coalesce()''' in any cell, a save bug occurs

**Comment by consideRatio** [comment]
Hi @IILolitaII!

I hope it is alright if I ask you to ask a question about this in discourse.jupyter.org instead even if you experience this issue in a JupyterHub context, it is not clear that this is a bug in the software JupyterHub that needs to be resolved.

For someone to help out track down what this is about, more information will be required. You could come a long way by providing screenshots and writing down some more about what you observe and what environment you are using. Perhaps it is using a tool like JupyterLab or another user interface, perhaps it is Jupyter server started on your computer or via a JupyterHub you have started on your own computer etc?

I'm sorry I couldn't be of more help but I hope the broader Jupyter community can help you onwards in the https://discourse.jupyter.org forum.

**Comment by IILolitaII** [comment]
Hi [consideRatio](https://github.com/consideRatio)!

I tested it with different JupyterHub's and had the same issue. But ok, I will ask a community, thanks!
