### ISSUE TITLE
Running applications in a multiuser environment

### ISSUE THREAD

**Issue by Streeter220** [jupyterhub/jupyterhub#3838]
Hi, i have jupyterhub/lab running in docker, and using dockerspawner for notebooks. I am having a problem where users are using the same port for web applications. User A is using port 5000 for his application in his notebook container, then user B does the same using port 5000 but then the port is already in use. Is there a way to use server-proxy or something similar to allow containers to use same port, but forwards the request to the users notebook container instead of exposing the port to the server running jupyter? 

Any help is appreciated!

**Comment by manics** [comment]
In general we ask that JupyterHub GitHub issues are used for bugs and development discussions, with support being handled on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions. Hope you understand 😀.
