### ISSUE TITLE
Admin page still blank by updating from jupyterhub=2.0.0 to jupyterhub=2.2.2

### ISSUE THREAD

**Issue by muh-hassani** [jupyterhub/jupyterhub#3844]
When I upgraded to jupyterhub=2.0.0, I had a proper restart of the jupyterhub and changes to the database schema were applied. By jupyterhub=2.0.0, the admin panel is available, and showing the users' activity, but when I update jupyterhub to 2.2.2, the admin panel becomes almost blank. Strangely, after the update, the admin panel includes only a gray bar which states jupyterhub 2.0.0. 
The jupyterhub uses sudospawner and no reverse proxy. I would be grateful if anyone could help me, so I can update jupyterhub and still have the admin panel working.

**Comment by scbarton** [comment]
I was able to fix this by stopping the jupyterhub server, deleting `jupyterhub.sqlite`, and then restarting the server.

**Comment by manics** [comment]
Closing, as this sounds like a caching or installation issue. If you still have problems please post on the [community forum](https://discourse.jupyter.org/).
