### ISSUE TITLE
Spawner  support for nomad

### ISSUE THREAD

**Issue by chenjpu** [jupyterhub/jupyterhub#3860]
### Proposed change
NoamdSpawner

**Comment by manics** [comment]
Hi! JupyterHub is designed to be extensible and highly customisable. Anyone can write and publish their own spawner, see https://jupyterhub.readthedocs.io/en/stable/reference/spawners.html

If you want to try and find others who are interested in working with you on this try posting on https://discourse.jupyter.org/

**Comment by mxab** [comment]
Hi,
I started to work on a Jupyter Spawner for Nomad here: https://github.com/mxab/jupyterhub-nomad-spawner :)
