### ISSUE TITLE
spawn failed for user after jupyterhub restart, received signal 15, stopping

### ISSUE THREAD

**Issue by whisere** [jupyterhub/jupyterhub#3861]
### spawn failed for user after jupyterhub restart, log shows 
received signal 15, stopping
SingleUserLabApp notebookapp:2052] Shutting down 0 kernels
SingleUserLabApp notebookapp:2067] Shutting down 0 terminals

### Your personal set up

 - OS: Redhat 8.5
 
 - Version(s): Jupyterhub 1.1.0 
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by whisere** [comment]
restarting the user's container and the spawn process shut it down again.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/spawn-failed-for-user-after-jupyterhub-restart-received-signal-15-stopping/13799/1
