### ISSUE TITLE
Admin Interface "Spawn Page" and "Access Server" button do not include base_url

### ISSUE THREAD

**Issue by jbaksta** [jupyterhub/jupyterhub#3868]
### Bug description
I've updated my dev instance of JupyterHub to the latest 'JupyterHub 2.2.2 20220414152639' that was in the conda-forge repos at the time, but noticed that the Spawn Page button doesn't render the link with base_url and therefore gives a 404 message (at least when behind nginx reverse proxy.

#### Expected behaviour
Include the base_url in the rendering for the button.

#### Actual behaviour

404 page when clicking Spawn Page

### How to reproduce

1. Go to 'Admin' page
2. Click on 'Spawn Page' for a user
4. Get 404

### Your personal set up

Conda installed (conda-forge) JupyterHub and no additional templating on the admin page.

 - OS:
 SLES12 SP4 (doesn't matter)
 - Version(s):
Python 3.9.12

**Comment by minrk** [comment]
I believe this was fixed by #3827 which has not yet been included in a release

**Comment by jbaksta** [comment]
Thanks. As it's merged, do we know the timeline for next release when it'll be included?

**Comment by minrk** [comment]
I think by the end of the month

**Comment by minrk** [comment]
Working on release with this fix: https://github.com/jupyterhub/jupyterhub/pull/3887
