### ISSUE TITLE
Version 2.2.0 redirect issue with proxy

### ISSUE THREAD

**Issue by keith6014** [jupyterhub/jupyterhub#3870]
### Bug description

Able to authenticate fine with proxy (nginx). In the jupyterhub-logs I see
Authenticated with token <APIToken...>

Then I see
[SingleUserLabApp log:189] 302 GET /user/USER/oauth_callback?code=[secret]&state=[secret] -> /user/USER/lab? 

Starting from 2.2.0 release when using remote_user plugin (https://github.com/cwaldbieser/jhub_remote_user_authenticator) web browser is giving a redirect. Was able to confirm in 2.2.2 also. 
Confirmed with version 2.1.1, 2.1.0 this problem does not exist. 

#### Expected behaviour
I expect to immediate login similar to version 2.1.1 and 2.1.0 
#### Actual behaviour
I get a Sigin prompt on browser (Chrome).

**Comment by manics** [comment]
It looks like someone has posted a similar issue on the Jupyter forum
https://discourse.jupyter.org/t/changes-in-proxy-from-2-1-1-to-2-2-2/13914
I'll therefore close this issue to avoid duplicating effort.
