### ISSUE TITLE
Manage jupyterlab image

### ISSUE THREAD

**Issue by fxheng** [jupyterhub/jupyterhub#3879]
Hi all,
I'm currently using jupyterhub on a swarm platform and will be soon migrating on K8s.
Currently I 'm managing my jupyterlab image separatly from jupyterlab instance. I Make some evolution on my labs(I have different version of them, each dedicated to different users, and i managing many version per lab(so if a new lib version screw someone works, he can keeps it old version to finish his task). Where it start to be trouble some is there, each time I'm publishing a new container I need to update the jupyterhub_config.py and I don't think it is a valid reason to do so. 

So first thing i though about was:
"Dude, create a database and just do the right request."
But just after came the questions:
"Yeah but I need some rights managements, no?"
"I can also have some container specs that i wanna specify per image, for sure!"
 No I have plant the decorum, the change.

### Proposed change

We have now in the admin section a groups featur, I think we need to build up(I'm not god at web thing, but I'm ready to healp more experts developpers) a image feature. 
There will be a page were you will be able to see all images and create new one.
There will be a page were you will be able to manage one image specifying:

- image name
- image adresss 
- who can use the image(groups and/otr users)
- spawner options required by this specific image:
    - c.SwarmSpawner.extra_container_spec
    - c.SwarmSpawner.cmd
    - c.SwarmSpawner.default_url
    - c.SwarmSpawner.extra_placement_spec
    - c.SwarmSpawner.start_timeout
    - c.SwarmSpawner.environment

### Who would use this feature?

Jupyterhub admins managing maning many grous using the lab for different purpose will find this handy.
Admins wanting to deploy image with new features too.

### (Optional): Suggest a solution

I think a good way to do this is to build a dedicated service or extends the group service.
Then the Spawners need to be updated to take these paramters in account.

Thank you for your time.

**Comment by consideRatio** [comment]
I think its out of scope for JupyterHub to be aware about images in general, but it doesn't mean your ideas are bad or so, just that it can't be developed as part of this project.

If you want to discuss a feature idea like this to develop in a new project, which could make sense to develop open source for everyone to use, please refer to the discourse.jupyter.org forum.

Thanks for being an active member of the Jupyter ecosystem!

**Comment by fxheng** [comment]
Initially I though it is my own issue and was ready to handle it separatly. 
But considering that the image configuration thing are currently are, from my point of view badly handle by the spawner class, I think it can be interresing to rework it a bit and swpawner class aware of a by image configuration.

Here is a part of my configuration :
```
  c.JupyterHub.spawner_class = 'dockerspawner.SwarmSpawner'
  c.SwarmSpawner.debug = True
  def CreateCustomList(spawner):
      return {"DataScience 0.1" :                  "myserver:5043/jupyterlab3:2022_02_08",
                  "DataScience-experimental" : "myserver:5043/jupyterlab3:latest"}	
  c.SwarmSpawner.allowed_images = CreateCustomList

  # Define container specs
  c.SwarmSpawner.extra_container_spec={'user':'root' }
  c.SwarmSpawner.cmd = f"start-singleuser.sh"
  c.SwarmSpawner.default_url = "/lab"
  c.SwarmSpawner.extra_placement_spec = {"constraints":["node.hostname==muserver"]}
  c.SwarmSpawner.start_timeout = 300
        
  c.SwarmSpawner.notebook_dir = notebook_dir

  datalake_path = os.environ['DATALAKE_PATH']
  c.SwarmSpawner.volumes = { f'{userspaces_path}/jupyterhub-user-{{username}}': f'{notebook_dir}' ,
                                                  f'{datalake_path}': {'bind': f'{notebook_dir}/storage', 'mode': 'ro'}}
  
  # set env for container
  # Configure env for users
  def GrantSudo(spawner):
      if(spawner.user.admin):
          return '1'
      return '0'
  
  c.SwarmSpawner.environment = { 
          'GRANT_SUDO'         : GrantSudo,
          'UID'                : '0', # workaround https://github.com/jupyter/docker-stacks/pull/420
          'JUPYTER_ENABLE_LAB' : '1',
          'NB_USER'            : lambda spawner : spawner.escaped_name
      }
   
  # Other stuff
  c.SwarmSpawner.cpu_limit = 6
  c.SwarmSpawner.mem_limit = '10G'
```
It's a simple case where i'm offering the users 2 version of my  container. One stable version and an experimental version.
I have also write a little something so only admins ca sudo in their containers.
=> First issu, Each time I want to update the stable release I need to update by hand this configuration and restart the hub.
=> Second. What I really wanna do is that admin should only have sudo in experimental image and not in stable release.
Now let go further, I have some demande to have a Vision Lab and an Optimisation Lab and I need to restrict their access. 
I can do this updating the CreateCustomList and using spawner.user, but I cannot
=> add dedicated volumes per image (Vision lab should have a mount to access the disk share with the pictures)
=> add a specific CPU or memory restrictions to the users (Vision Lab should have more memory and Optimisation lab more CPU)
=> add extra_placement_spec (Vision lab should run on a host with a GPU)
=> add specifics sets of environment variables.
