### ISSUE TITLE
sqlite DB URI error check shows incorrect path

### ISSUE THREAD

**Issue by mcornella** [jupyterhub/jupyterhub#3913]
When jupyterhub is configured with a sqlite DB URI (e.g. on Google Cloud's Dataproc Hub), if the sqlite DB connection fails, jupyterhub tries to detect DB path errors. The code below does a split on `:///`, which removes the root `/` character, so the check will incorrectly look for a relative path.

https://github.com/jupyterhub/jupyterhub/blob/9649a57e3457757d3a081c12fabb5fa6b712b67a/jupyterhub/app.py#L1801

I don't have a screenshot at the moment but this is an easy fix: split by `://` instead of `:///`, so that the correct absolute path is checked instead of an inexistent relative path.

**Comment by minrk** [comment]
`:///path` is a [_relative_ path](https://docs.sqlalchemy.org/en/20/dialects/sqlite.html#connect-strings). An absolute path has four slashes: `sqlite:////var/run/db/...`.

(I do not know why!)

**Comment by minrk** [comment]
Actually, why is explained in the link:

> The file specification for the SQLite database is taken as the “database” portion of the URL. Note that the format of a SQLAlchemy url is:
>
> `driver://user:pass@host/database`
>
> This means that the actual filename to be used __starts with the characters to the right of the third slash__

**Comment by mcornella** [comment]
Here's the error output from DataprocHub:
```
Running on AI Notebook.
No Dataproc default subnet specified in environment, trying to get subnet URI from instance metadata
Inferred subnet from metadata: https://www.googleapis.com/compute/v1/projects/<project>/regions/us-west1/subnetworks/default
Default name pattern not specified. Setting default name pattern to hub-working-hub-{}
Jupyter already configured, skipping appending to config.
[I 2022-05-24 14:55:25.620 DataprocHub app:2332] Running JupyterHub version 1.2.2
[I 2022-05-24 14:55:25.620 DataprocHub app:2363] Using Authenticator: jupyterhub.auth.PAMAuthenticator-1.2.2
[I 2022-05-24 14:55:25.620 DataprocHub app:2363] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.2.2
[I 2022-05-24 14:55:25.621 DataprocHub app:2363] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.2.2
[I 2022-05-24 14:55:25.628 DataprocHub app:1412] Loading cookie_secret from /home/jupyter/jupyterhub_cookie_secret
[E 2022-05-24 14:55:25.637 DataprocHub app:1589] Failed to connect to db: sqlite:///home/jupyter/.jupyterhub/jupyterhub.sqlite
[E 2022-05-24 14:55:25.638 DataprocHub app:1391] Directory /home/jupyter/home/jupyter/.jupyterhub does not exist
[C 2022-05-24 14:55:25.638 DataprocHub app:1598] If you recently upgraded JupyterHub, try running
        jupyterhub upgrade-db
    to upgrade your JupyterHub database schema
```
as you can see, the sqlite database is configured to be in `sqlite:///home/jupyter/.jupyterhub/jupyterhub.sqlite` and the help error message incorrectly assumes it to be at `/home/jupyter/home/jupyter/.jupyterhub/jupyterhub.sqlite`.

**Comment by mcornella** [comment]
Confirmed to have been an error in DataprocHub. Now the `jupyterhub_config.py` file has the correct format:
```py
c.JupyterHub.db_url = 'sqlite:////home/jupyter/.jupyterhub/jupyterhub.sqlite'
```
Closing as not a bug in JupyterHub.
