### ISSUE TITLE
 403 : Forbidden  Action is not authorized with current scopes; requires any of [admin:users]

### ISSUE THREAD

**Issue by ryansczarny** [jupyterhub/jupyterhub#3929]
I am attempting to setup users for our JupyterHub and am running into issues. 

Hub version = 2.3.0
Python 3.6.8
Running in a Python venv, not in Anaconda 

I have tried a couple of different things to get this up and working:
1. Adding the users to admin_users and setting admin_access to true 
```
#c.Authenticator.admin_users = ['user1','user2']
#c.JupyterHub.admin_access = True
```
2. Creating roles for the admins (using and expanding upon what is in the Roles [page](https://jupyterhub.readthedocs.io/en/latest/rbac/roles.html#define-role-target))
```
#c.JupyterHub.load_roles = [
# {
#   'name': 'server-rights',
#   'description': 'Allows parties to start and stop user servers',
#   'scopes': ['servers','admin:users','admin:uservers'],
#   'users': ['user1', 'user2'],
#   'services': ['idle-culler'],
#   'groups': ['admin-group'],
# }
#]
```
After restarting the server I am still getting the error that the user doesn't have access. 
```
JupyterHub scopes:501] Not authorizing access to /hub/admin. Requires any of [admin:users], not derived from scopes [users:activity!user=user1, read:users!user=user1, read:users:activity!user=user1, read:users:groups!user=user1, servers!user=user1, tokens!user=user1, read:servers!user=user1, read:tokens!user=user1, access:servers!user=user1, delete:servers!user=user1, read:users:name!user=user1]
```
I am new to JH, so any help figuring this out would be greatly appreciated. Thanks!

**Comment by minrk** [comment]
The above config granting the roles is commented out - make sure the config lines are actually executed:

```python
c.JupyterHub.load_roles = [
    {
        'name': 'server-rights',
        'description': 'Allows parties to start and stop user servers',
        'scopes': ['servers', 'admin:users', 'admin:servers'],
        'users': ['user1', 'user2'],
        'services': ['idle-culler'],
        'groups': ['admin-group'],
    }
]
```

Note that this is granting the permissions to 3 kinds of entities:

- the _users_ user1 and user2
- the idle-culler service, which is perhaps overkill, and
- the group `admin-group`, which I suspect makes the individual user assignments redundant (are they in this group?)

Check the [idle culler readme](https://github.com/jupyterhub/jupyterhub-idle-culler#permissions) for what permission it needs, because it doesn't need full admin.

**Comment by yashali** [comment]
@minrk Please help me understand how to apply & fix  these rbac and scopes
* single-user jupyterhub==3.0.0 jupyter_server==1.23.1
* hub's jupyterhub version==3.0.0
* z2jhub helm chart version == 2.0.0

1) I am in the list under Authenticator.admin_users. But I do not see the admin UI nor am I able to start/stop user servers (not even my own). When click on the Admin tab I get 
```
JupyterHub base:89] Blocking Cross Origin API request.  Referer: https://dev.com/myenv/hub/admin, Host: dev.com, Host URL: http://dev.com/myenv/hub/
[W 2023-02-02 05:00:43.682 JupyterHub scopes:804] Not authorizing access to /myenv/hub/api/users. Requires any of [list:users], not derived from scopes []
[W 2023-02-02 05:00:43.682 JupyterHub web:1796] 403 GET /myenv/hub/api/users?include_stopped_servers&offset=0&limit=50&name_filter= (10.97.11.164): Action is not authorized with current scopes; requires any of [list:users]
[W 2023-02-02 05:00:43.683 JupyterHub log:186] 403 GET /myenv/hub/api/users?include_stopped_servers&offset=0&limit=50&name_filter= (@10.97.11.164) 5.06ms
```

2) Why do I get warnings like these? I think we will need it to cull idle terminals
```
base:1409] Failing suspected API request to not-running server: /myenv/hub/user/username/api/terminals
[W 2023-02-02 05:00:40.339 JupyterHub log:186] 424 GET /myenv/hub/user/username/api/terminals?1675314039247 (username@10.97.11.170) 4.47ms
```

3) I am unable to read the user-server spawn progress. I think this is also causing the redirection to /lab (that I see in the 
 single user server logs) never happen and the hub shows that the operation timed out. But actually, the single-user server is up and running as expected. This is the error that I see for spawn progress: 
```
JupyterHub scopes:804] Not authorizing access to /myenv/hub/api/users/username/server/progress. Requires any of [read:servers], not derived from scopes []
[W 2023-02-02 05:04:26.817 JupyterHub web:1796] 403 GET /myenv/hub/api/users/username/server/progress (172.16.0.1): Action is not authorized with current scopes; requires any of [read:servers]
```

4) How do I make sure : a) All users are able to list start and stop their own servers. b) The hub is able to view spawn progress. The hub doesnt see the warnings that I mentioned above c) Admin users are able to do what they are supposed to do
