### ISSUE TITLE
A new search at /hub/admin should initialize page to 0

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/jupyterhub#3957]
### Bug description

If I navigate to the second page of users (`/hub/admin#/?page=1`), then use the search field to try to find someone, search returns empty results. If I navigate back to the first page then initiate a search, it returns results matching the search term.

Search will return _some_ results on page > 0 if I use a short search time like `a`. So if I start the search while viewing page X, then I see page X of the search results.

#### Expected behaviour

I expected that when I initiate at search, it should always start at page=0.

#### Actual behaviour

Search returns no results, even if I know there to be a user matching the search term. It appears that search results are being paginated too and the initial page= offset is hiding results when the count of matching users is less than `limit`. For example if I search for "a" which matches more than 50 users on this particular hub, and if I'm starting out on the second page, then I do see some results. So search is working but the initial page offset was surprising and gives a false impression for non-pathological search terms.

### How to reproduce

1. Go to the first page of /hub/admin on a hub which has more than a page's worth of users (50 is the default?). Note the name of any user.
2. Click on Next to go to the next page.
3. Search for the user you noted in the first step. Alternatively search for any other user that you know to exist.
4. Observe empty results.

### Your personal set up

https://github.com/berkeley-dsep-infra/datahub

helm chart 1.1.3-n554.hfa81c67f
jupyterhub 2.3.0

<details><summary>Full environment</summary>

```
authenticator==14.2.0
oauthlib==3.2.0
onetimepass==1.0.1
packaging==21.3
pamela==1.0.0
pem==21.2.0
prometheus-client==0.14.1
psycopg2-binary==2.9.3
py-spy==0.3.12
pyasn1==0.4.8
pycparser==2.21
pycryptodome==3.14.1
pycryptodomex @ file:///tmp/pre-built-wheels/pycryptodomex-3.14.1-cp35-abi3-manylinux2010_x86_64.whl
pycurl @ file:///tmp/pre-built-wheels/pycurl-7.45.1-cp39-cp39-linux_x86_64.whl
pyjwkest==1.4.2
PyJWT==1.7.1
PyMySQL==1.0.2
pyOpenSSL==22.0.0
pyparsing==3.0.9
pyrsistent==0.18.1
python-dateutil==2.8.2
python-json-logger==2.0.2
python-slugify==6.1.2
PyYAML==6.0
requests==2.27.1
requests-oauthlib==1.3.1
ruamel.yaml==0.17.21
ruamel.yaml.clib @ file:///tmp/pre-built-wheels/ruamel.yaml.clib-0.2.6-cp39-cp39-manylinux1_x86_64.whl
six==1.16.0
SQLAlchemy==1.4.36
sqlalchemy-cockroachdb==1.4.3
statsd==3.3.0
text-unidecode==1.3
tornado==6.1
traitlets==5.2.1.post0
urllib3==1.26.9
wrapt==1.14.1
yarl==1.7.2```
</details>

<details><summary>Configuration</summary>
<!--
For JupyterHub, especially include information such as what Spawner and Authenticator are being used.
Be careful not to share any sensitive information.
You can paste jupyterhub_config.py below.
To exclude lots of comments and empty lines from auto-generated jupyterhub_config.py, you can do:
    grep -v '\(^#\|^[[:space:]]*$\)' jupyterhub_config.py
-->

```

[kubespawner](https://github.com/berkeley-dsep-infra/datahub/blob/staging/hub/values.yaml#L301)
[canvasauthenticator](https://github.com/berkeley-dsep-infra/datahub/tree/staging/images/hub/canvasauthenticator)```

</details>

**Comment by minrk** [comment]
Yes, indeed the search is currently purely an in-page filter when you are looking at the users. It should instead probably be moved to the server-side.

The users-per-page should probably also be exposed somewhere in the UI

**Comment by minrk** [comment]
I was wrong about how the name filter is updated. It's a server API request, so this should be quite doable.

@naatebarber can you update the name filter so that offset is also reset to 0 when the name filter changes?
