### ISSUE TITLE
[admin-ui] bootstrap

### ISSUE THREAD

**Issue by djangoliv** [jupyterhub/jupyterhub#3963]
In the jsx/package.json file, I think there are some inconsistencies:

"react-bootstrap": "^2.1.1",  # is compatible with bootstrap 5
 "bootstrap": "^4.5.3", # is compatible with react-bootstrap 4

and if I'm not mistaken, the bootstrap used is the one embedded by jupyterhub which is v3.4.1 ...

I know react-bootstrap is very little used but the situation is quite confusing.

It would be nice to use bootstrap as a dependency rather than embed it but I don't know how difficult that is. 
In any case it would limit this kind of inconsistency.

Regards

**Comment by manics** [comment]
> and if I'm not mistaken, the bootstrap used is the one embedded by jupyterhub which is v3.4.1 ...

This part is fine, there are two web interfaces bundled with JupyterHub:
- The original UI seen by users https://github.com/jupyterhub/jupyterhub/blob/2.3.1/package.json which uses v3.4.1
- A new admin app built as a separate react app (https://github.com/jupyterhub/jupyterhub/tree/2.3.1/jsx which uses the newer bootstrap

We should probably update the latter to bootstrap 5.

**Comment by minrk** [comment]
We should also update the main pages to bs5. I've actually put a little time into it, but it's a bit of a pain because we need to migrate to SCSS, etc.

**Comment by yuvipanda** [comment]
Closing, as upgrade to bs5 is tracked in #4437
