### ISSUE TITLE
`announcement_login` etc can't be set falsy to override `announcement`

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#3965]
My expectation was that I could set the `c.JupyterHub.template_vars` named `announcement_login` explicitly to a falsy value to disable an announcement for a specific page. It seems that the code is that only if `announcement_login` is Truthy, its value will override `announcement`.

The value of being able to do so, is to easily configure `announcement` in one place and set `announcement_login` to something falsy to disable it - practically declaring an annoncement in a single place for all authenticated pages.

https://github.com/jupyterhub/jupyterhub/blob/f22203f50e277b0aae89b079f59b24591547e914/share/jupyterhub/templates/login.html#L1-L4

If possible in a jinja template, I suggest the change like this, even though I assume it must be tweaked to match Jinja syntax.

```diff
  {% extends "page.html" %} 
- {% if announcement_login %} 
+ {% if announcement_login is not None %} 
    {% set announcement = announcement_login %} 
  {% endif %} 
```

**Comment by minrk** [comment]
Makes sense! Want to take a stab at it?
