### ISSUE TITLE
Should we test our lower required version bounds with an old or modern python version?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#3973]
We have a test against the oldest dependencies we declare support for, given this, we test against them. But, we only do it for the oldest version of Python we support currently.

Should we instead test the oldest versions supported together with the latest python version, or stick with oldest deps + oldest python?

**Comment by minrk** [comment]
I think it makes sense to have a single 'oldest of everything' entry. The oldest versions of some dependencies may not work with the latest versions of Python. I think that's not our problem, though, and shouldn't be something we have to debug in our tests. We don't anywhere claim that the oldest supported sqlalchemy works with the latest Python, and we shouldn't require our oldest sqlalchemy to work work with the latest Python.

**Comment by consideRatio** [comment]
Thanks okay! I figure it depended on how we see the intent of the lower version bound in our requirements.txt - lowest possible for oldest python supported is the current meaning - that is fine!
