### ISSUE TITLE
Issue Users Log In

### ISSUE THREAD

**Issue by socraDrk** [jupyterhub/jupyterhub#398]
Hi.

I'm testing JupyterHub and installed with a user which spawns other users notebooks according to the documentation in https://github.com/jupyter/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges. To start the Hub in background I run the command:
$ jupyterhub &

Everything works fine (users can log in and out as many times as they want) as long as the terminal where I run the command to start the Hub remains open.

When I exit the terminal, all the process remains up (JupyterHub, the proxy and the notebooks of the current logged users) but if a user tries to log in (new user or some other which log out and then log in) the page returns a 500 Internal Server Error.

I need to restart the Hub (and keep the terminal open) in order to let the users log in again.

Here is the log when I close the terminal, a user (drk123) logs out and tries to log in again

[I 2016-01-25 09:38:53.442 JupyterHub login:17] User drk123 server took 20.500 seconds to start
[I 2016-01-25 09:38:49.527 JupyterHub orm:170] Adding user drk123 to proxy /user/drk123 => http://localhost:35817
[D 2016-01-25 09:38:49.532 JupyterHub orm:157] Fetching POST http://127.0.0.1:8790/api/routes/user/drk123
[I 2016-01-25 09:38:50.476 JupyterHub log:100] 302 GET /hub/user/drk123 (drk123@150.100.213.25) 313.59ms
[I 2016-01-25 09:38:50.538 JupyterHub log:100] 200 GET /hub/api/authorizations/cookie/jupyter-hub-token-drk123/secret 18.08ms
[I 2016-01-25 09:38:53.442 JupyterHub login:17] User logged out: drk123
[I 2016-01-25 09:38:53.451 JupyterHub log:100] 302 GET /hub/logout (drk123@150.100.213.25) 12.11ms
[I 2016-01-25 09:38:53.457 JupyterHub log:100] 302 GET /hub/ (@150.100.213.25) 0.92ms
[I 2016-01-25 09:38:53.482 JupyterHub log:100] 200 GET /hub/login (@150.100.213.25) 16.45ms
[E 2016-01-25 09:38:59.443 JupyterHub ioloop:588] Exception in callback functools.partial(.null_wrapper at 0x7fd3a78fed08>, )
Traceback (most recent call last):
File "/python3/bin/lib/python3.4/site-packages/tornado/ioloop.py", line 568, in run_callback
ret = callback()
File "/python3/bin/lib/python3.4/site-packages/tornado/stack_context.py", line 275, in null_wrapper
return fn(args, *kwargs)
File "/python3/bin/lib/python3.4/site-packages/tornado/ioloop.py", line 574, in 
self.add_future(ret, lambda f: f.result())
File "/python3/bin/lib/python3.4/site-packages/jupyterhub/spawner.py", line 234, in poll_and_notify
status = yield self.poll()
File "/python3/bin/lib/python3.4/site-packages/jupyterhub/spawner.py", line 390, in poll
alive = yield self.signal(0)
File "/usr/local/anaconda/sudospawner-master/sudospawner/spawner.py", line 61, in _signal
reply = yield self.do('kill', pid=self.pid, signal=sig)
File "/usr/local/anaconda/sudospawner-master/sudospawner/spawner.py", line 48, in do
return json.loads(data.decode('utf8'))
File "/python3/bin/lib/python3.4/json/__init.py", line 318, in loads
return _default_decoder.decode(s)
File "/python3/bin/lib/python3.4/json/decoder.py", line 343, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/python3/bin/lib/python3.4/json/decoder.py", line 361, in raw_decode
raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

[E 2016-01-25 09:39:04.466 JupyterHub web:1421] Uncaught exception POST /hub/login?next= (150.100.213.25)
HTTPServerRequest(protocol='https', host='192.168.1.106:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='150.100.213.25', headers={'Accept-Language': 'en-US,en;q=0.8,es;q=0.6,de;q=0.4', 'Origin': 'https://192.168.1.106:8000', 'X-Forwarded-For': '150.100.213.25', 'Host': '192.168.1.106:8000', 'Upgrade-Insecure-Requests': '1', 'Connection': 'close', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,/;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'X-Forwarded-Port': '8000', 'Cookie': 'username-192.168.1.106-8788="2|1:0|10:1451935344|28:username-192.168.1.106-8788|48:MjdmMGU1NGUtMjI0Zi00NTQ2LTlkM2EtNzRhZmU5Y2ExOGI4|3e3945a923e83cd49938b86c94cd59a7dbcb72c834a99deac1f60454aeaa4b2d"', 'Cache-Control': 'max-age=0', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36', 'Referer': 'https://192.168.1.106:8000/hub/login', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '34', 'X-Forwarded-Proto': 'https'})
Traceback (most recent call last):
File "/python3/bin/lib/python3.4/site-packages/tornado/web.py", line 1348, in execute
result = yield result
File "/python3/bin/lib/python3.4/site-packages/jupyterhub/handlers/login.py", line 69, in post
status = yield user.spawner.poll()
File "/python3/bin/lib/python3.4/site-packages/jupyterhub/spawner.py", line 390, in poll
alive = yield self.signal(0)
File "/usr/local/anaconda/sudospawner-master/sudospawner/spawner.py", line 61, in _signal
reply = yield self.do('kill', pid=self.pid, signal=sig)
File "/usr/local/anaconda/sudospawner-master/sudospawner/spawner.py", line 48, in do
return json.loads(data.decode('utf8'))
File "/python3/bin/lib/python3.4/json/__init.py", line 318, in loads
return _default_decoder.decode(s)
File "/python3/bin/lib/python3.4/json/decoder.py", line 343, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/python3/bin/lib/python3.4/json/decoder.py", line 361, in raw_decode
raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

[D 2016-01-25 09:39:04.471 JupyterHub base:401] No template for 500
[E 2016-01-25 09:39:04.483 JupyterHub log:99] {
"Accept-Language": "en-US,en;q=0.8,es;q=0.6,de;q=0.4",
"Origin": "https://192.168.1.106:8000",
"X-Forwarded-For": "150.100.213.25",
"Host": "192.168.1.106:8000",
"Upgrade-Insecure-Requests": "1",
"Connection": "close",
"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,/;q=0.8",
"Accept-Encoding": "gzip, deflate",
"X-Forwarded-Port": "8000",
"Cookie": "username-192.168.1.106-8788=\"2|1:0|10:1451935344|28:username-192.168.1.106-8788|48:MjdmMGU1NGUtMjI0Zi00NTQ2LTlkM2EtNzRhZmU5Y2ExOGI4|3e3945a923e83cd49938b86c94cd59a7dbcb72c834a99deac1f60454aeaa4b2d\"",
"Cache-Control": "max-age=0",
"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36",
"Referer": "https://192.168.1.106:8000/hub/login",
"Content-Type": "application/x-www-form-urlencoded",
"Content-Length": "34",
"X-Forwarded-Proto": "https"
}
[E 2016-01-25 09:39:04.483 JupyterHub log:100] 500 POST /hub/login?next= (@150.100.213.25) 423.97ms

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or leave a comment to reopen this issue. Thanks! :sunflower:
