### ISSUE TITLE
Add "Last seen" column in admin page

### ISSUE THREAD

**Issue by EmericT** [jupyterhub/jupyterhub#3981]
### Proposed change

I just updated jupyterhub. There used to be a Last seen column in the admin panel, and this was a feature I used a lot. Now there is a "Last activity" column instead, which show "Never" if no server is running. As I use the culling system anyway, this column is rarely of any use. 

I would like to have the "Last seen" column back. 

### (Optional): Suggest a solution
I'm not fluent enough with the jupyterhub project to test a solution. I understand that the file to modify is probably this one https://github.com/jupyterhub/jupyterhub/blob/main/jsx/src/components/ServerDashboard/ServerDashboard.jsx around the line 261. Maybe switching "server.last_activity" to "user.last_activity" would do ? I couldn't find out how to test this.

**Comment by EmericT** [comment]
I managed to apply the patch by hand, it seems it does what I want. I'm still wondering why anyone would prefer have the "server last activity" instead of "user last activity" on a user table. If this is a bug, the patch is easy and I can now confidently submit a pull request if this helps.

**Comment by minrk** [comment]
@EmericT I think it's just a bug, if you'd like to make a PR that would be great!

**Comment by EmericT** [comment]
I just did : https://github.com/jupyterhub/jupyterhub/pull/3995

**Comment by consideRatio** [comment]
@EmericT thanks for helping us out with this! Since the fix is not yet merged, you can leave this open and in the PR looking to fix this, you can update your PR description to include `fixes #3981` or `closes #3981` and once its merged - it will close this issue.
