### ISSUE TITLE
Jupyter Hub stalls when choosing "Restart Kernel and Run All Cells" for R notebooks (IRKernel)

### ISSUE THREAD

**Issue by sarathsund** [jupyterhub/jupyterhub#3990]
Describe the bug
After the manul kernel restart in the existing notebook session, the notebooks freeze and become inaccessible

To Reproduce

Go to Kernel
Click on ‘Restart’
Accept the prompt message
The notebook stalls/halts with no access

Expected behavior
The notebook should re -establish connection after kernel restart

R : 4.1.0
jupyterhub : 1.5.0
IPython : 8.4.0
ipykernel : 6.15.1
ipywidgets : not installed
jupyter_client : 7.3.4
jupyter_core : 4.11.1
jupyter_server : not installed
jupyterlab : not installed
nbclient : 0.6.6
nbconvert : 6.5.0
nbformat : 5.4.0
notebook : 6.4.11
qtconsole : not installed
traitlets : 5.3.0
packageVersion(‘IRkernel’)
[1] ‘1.3’

chrome Version 103.0.5060.114 (Official Build) (64-bit)
Architecture - (zero to k8s jupyterhub) / docker-stacks / jupyterhub

notebook logs

`notebook [I 2022-07-15 19:05:05.267 SingleUserNotebookApp handlers:202] Creating new notebook in                                                                                                                                          
 notebook [I 2022-07-15 19:05:05.686 SingleUserNotebookApp log:189] 201 POST /user/cb193632088/api/contents (cb193632088@10.169.120.18) 558.51ms                                                                                           
 notebook [I 2022-07-15 19:05:06.311 SingleUserNotebookApp log:189] 200 GET /user/cb193632088/notebooks/Untitled3.ipynb?kernel_name=ir (cb193632088@10.169.120.18) 557.92ms                                                                
 notebook [I 2022-07-15 19:05:09.598 SingleUserNotebookApp log:189] 200 GET /user/cb193632088/api/config/common?_=1657911909397 (cb193632088@10.169.120.18) 2.67ms                                                                         
 notebook [I 2022-07-15 19:05:09.611 SingleUserNotebookApp log:189] 200 GET /user/cb193632088/api/config/notebook?_=1657911909396 (cb193632088@10.169.120.18) 12.95ms                                                                      
 notebook [I 2022-07-15 19:05:09.793 SingleUserNotebookApp log:189] 200 GET /user/cb193632088/api/contents/Untitled3.ipynb?type=notebook&_=1657911909398 (cb193632088@10.169.120.18) 129.47ms                                              
 notebook [I 2022-07-15 19:05:10.001 SingleUserNotebookApp log:189] 200 GET /user/cb193632088/api/contents/Untitled3.ipynb/checkpoints?_=1657911909399 (cb193632088@10.169.120.18) 19.12ms                                                 
 notebook [I 2022-07-15 19:05:10.005 SingleUserNotebookApp log:189] 200 GET /user/cb193632088/api/metrics/v1 (cb193632088@10.169.120.18) 22.06ms                                                                                           
 notebook [I 2022-07-15 19:05:10.009 SingleUserNotebookApp kernelmanager:179] Kernel started: 35bdd0fe-f412-4cc5-acf9-8e30a92b12bb, name: ir                                                                                               
 notebook [I 2022-07-15 19:05:10.011 SingleUserNotebookApp log:189] 201 POST /user/cb193632088/api/sessions (cb193632088@10.169.120.18) 106.00ms                                                                                           
 notebook [I 2022-07-15 19:05:10.690 SingleUserNotebookApp log:189] 101 GET /user/cb193632088/api/kernels/35bdd0fe-f412-4cc5-acf9-8e30a92b12bb/channels?session_id=9d5cd2433d2c46939296aac0ea104a03 (cb193632088@10.169.120.80) 225.45ms   
 notebook [I 2022-07-15 19:05:14.969 SingleUserNotebookApp log:189] 200 GET /user/cb193632088/api/metrics/v1 (cb193632088@10.169.120.18) 1.45ms                                                                                            
 notebook [I 2022-07-15 19:05:34.956 SingleUserNotebookApp log:189] 200 GET /user/cb193632088/api/metrics/v1 (cb193632088@10.169.120.18) 1.29ms                                                                                            
 notebook [I 2022-07-15 19:06:24.946 SingleUserNotebookApp log:189] 200 GET /user/cb193632088/api/metrics/v1 (cb193632088@10.169.120.18) 1.34ms                                                                                            
 notebook [I 2022-07-15 19:07:09.973 SingleUserNotebookApp log:189] 200 GET /user/cb193632088/api/contents/Untitled3.ipynb?content=0&_=1657911909400 (cb193632088@10.169.120.18) 2.79ms                                                    
 notebook [I 2022-07-15 19:07:10.050 SingleUserNotebookApp handlers:213] Saving file at /Untitled3.ipynb                                                                                                                                   
 notebook [I 2022-07-15 19:07:10.249 SingleUserNotebookApp log:189] 200 PUT /user/cb193632088/api/contents/Untitled3.ipynb (cb193632088@10.169.120.18) 199.70ms                                                                            
 notebook [I 2022-07-15 19:07:17.352 SingleUserNotebookApp log:189] 200 GET /user/cb193632088/api/metrics/v1 (cb193632088@10.169.120.18) 1.44ms                                                                                            
 notebook [I 2022-07-15 19:08:00.095 SingleUserNotebookApp kernelmanager:222] Starting buffering for 35bdd0fe-f412-4cc5-acf9-8e30a92b12bb:9d5cd2433d2c46939296aac0ea104a03                                                                 
 notebook [I 2022-07-15 19:08:00.265 SingleUserNotebookApp multikernelmanager:378] Kernel restarted: 35bdd0fe-f412-4cc5-acf9-8e30a92b12bb                                                                                                  
 notebook [I 2022-07-15 19:08:00.268 SingleUserNotebookApp log:189] 200 POST /user/cb193632088/api/kernels/35bdd0fe-f412-4cc5-acf9-8e30a92b12bb/restart (cb193632088@10.169.120.18) 156.94ms                                               
 notebook [I 2022-07-15 19:08:00.631 SingleUserNotebookApp log:189] 101 GET /user/cb193632088/api/kernels/35bdd0fe-f412-4cc5-acf9-8e30a92b12bb/channels?session_id=9d5cd2433d2c46939296aac0ea104a03 (cb193632088@10.169.120.18) 3.72ms     
 notebook [I 2022-07-15 19:08:00.631 SingleUserNotebookApp handlers:403] Restoring connection for 35bdd0fe-f412-4cc5-acf9-8e30a92b12bb:9d5cd2433d2c46939296aac0ea104a03 `

I can see a same issue with jupyterlab but we are still in hub version, is there any compatible irkernel & R version to be used for this functionality to work?

**Comment by sarathsund** [comment]
Hello @minrk  can you help to have a look at this? I wanted to know if this bug actually exists or something very specific to my installation?

**Comment by consideRatio** [comment]
@sarathsund please ask a general question like this on https://discourse.jupyter.org.

**Comment by sarathsund** [comment]
sure noted. thanks
