### ISSUE TITLE
admin ui should use pagination API

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#3999]
### Proposed change

The admin UI is the main place where we consume probably-paginated data, but it doesn't opt-in to the paginated API by sending the `Accept: "application/jupyterhub-pagination+json"` header.

### Who would use this feature?

The admin UI.

### (Optional): Suggest a solution

1. add `Accept: "application/jupyterhub-pagination+json"` [here](https://github.com/jupyterhub/jupyterhub/blob/9b2e6b1c1d26b65764aeb193fc60e478f3b35546/jsx/src/util/jhapiUtil.js#L8)
2. handle the user/group lists being in `data.items` instead of `data`
3. use `data._pagination` info for PaginationFooter instead of reconstructing from page number and API limit
4. switch URL params from `page` to `offset` and `limit` to match pagination inputs

@NarekA or @naatebarber is this something you can explore?

**Comment by naatebarber** [comment]
I can look into this :+1:

**Comment by naatebarber** [comment]
Would also like to take this as an opportunity to simplify the handling of pagination on the FE. Previously we had pagination state stored in both Redux and url params. I think we should pick one source of truth if possible. 
Redux seems to have a couple libraries that help it save state on window reload, maybe worth looking into?

**Comment by minrk** [comment]
Sure! URLs should generally have priority top priority over everything, since you want to be able to type in a URL and have that do what was requested. Loading stale, invisible state over explicit values in the URL is generally a recipe for frustration.

**Comment by naatebarber** [comment]
Sounds good, I'll work on moving the majority of our pagination state handling to react router in that case.

**Comment by minrk** [comment]
closed by #4002, thanks @naatebarber!
