### ISSUE TITLE
Trusted JupyterHub services: would bypass an authorize prompt

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#4007]
When a JupyterHub registered service interacts with JupyterHub to verify the identity of the user, the user must first confirm to JupyterHub that its acceptable. At least that is how I understand this screen when visiting `/services/configurator/` at the moment.

![image](https://user-images.githubusercontent.com/3837114/183615257-b90e912b-0bb9-4f2c-9305-e9f63bea3b73.png)

## Question / feature request

Can a JupyterHub admin pre-configure a service, such as https://github.com/yuvipanda/jupyterhub-configurator to not need this consent via `c.JupyterHub.services`? If not, does this sound reasonable towards implementing?

## Background

I've seen this practice in other places. For example [in GitLab you can](https://docs.gitlab.com/ee/integration/oauth_provider.html#instance-wide-applications) declare a registered OAuth2 application as "trusted" to not end up asking users for consent. I've also seen it when managing Microsoft related permissions in portal.azure.com.

**Comment by minrk** [comment]
@consideRatio we have this feature! ([since 1.1](https://jupyterhub.readthedocs.io/en/2.3.1/changelog.html?highlight=oauth_no_confirm#id97)) #4012 should improve its visibility.
