### ISSUE TITLE
How to handle kernels that fail to prefix /user/$USER in script URLs?

### ISSUE THREAD

**Issue by cruegge** [jupyterhub/jupyterhub#401]
I'm trying to use a SageMath kernel inside JupyterHub and run into a problem with the JSmol applet. The applet works by creating an iframe inside which a script is loaded which then does fancy but for this issue non-essential stuff. The problem is that the script is expected under `/nbextensions/jsmol/JSmol.min.js`, which works nicely in Jupyter itself, but for JupyterHub fails to prefix `/user/$USER` properly. I asked at the SageMath mailing list and was told that it is not easily possible for the kernel to know whether it is running under JupyterHub. Is there maybe anything that can be done about this problem on the hub side, like automatically redirecting such requests to the appropriate user instances?

**Comment by minrk** [comment]
The script is loading nbextensions wrong if it's hardcoding an absolute path. Using `require('nbextensions/jsmol...')` should load correctly regardless of the URL prefix.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!

**Comment by williamstein** [comment]
Still a problem in sage-7.4 (but the fault of sage not jupyterhub).  Also we have an open ticket where we have exactly the same problem in SageMathCloud:  https://github.com/sagemathinc/smc/issues/159

**Comment by willingc** [comment]
Thanks for the update @williamstein and the link to the ticket.

@minrk I'm going to reopen, label "out of project scope" to signify this depends on external work, and create a milestone for items that are worthwhile to check monthly until resolved. We can rework this if you have a better alternative.

**Comment by willingc** [comment]
Reviewed this issue https://github.com/sagemathinc/smc/issues/159#issuecomment-262465870 on SageMathCloud. It looks as if this is now working. I'm going to go ahead and close this issue. @williamstein please feel free to request reopening if there is more work to be done here.
