### ISSUE TITLE
Database error when hub tries to add existing group

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/jupyterhub#4017]
We enabled groups on a hub, and they seemed to be working fine for a little while, but users started to see 500 errors on logging in. One traceback indicated that the hub attempted to add an already existing group to the ORM database. The groups are based on course enrollments which we obtain from our Canvas LMS as users login. Unfortunately I don't have other tracebacks.

Here is the traceback from one such instance:
https://github.com/berkeley-dsep-infra/datahub/issues/3556#issuecomment-1212830090

The deployment is https://github.com/berkeley-dsep-infra/datahub and our authenticator is at https://github.com/berkeley-dsep-infra/datahub/tree/staging/images/hub/canvasauthenticator. Here is a condensed version of our `authenticate` method:
```
    async def authenticate(self, handler, data=None):
        user = await super().authenticate(handler, data)
        courses = await self.get_courses(user['auth_state']['access_token'])
        user['groups'] = self.extract_course_groups(courses)
        return user
```

We've temporarily disabled the assignment to the `groups` key and that stopped the 500 errors.

We [had set](https://github.com/berkeley-dsep-infra/datahub/blob/5096d43940768a3f33dca48b9c87f2c5d7fcbf91/hub/values.yaml#L194) `Authenticator.managed_groups = True` but that is also temporarily disabled.

Our hub is `jupyterhub/k8s-hub:1.1.3-n554.hfa81c67f` and is using a customized KubeSpawner.

Under /hub/admin we can see that 35 of the 37 groups were created during this time have only one user, while two groups have two. Our students tend to cluster in the same classes so I would normally expect higher group memberships. Some people were using the hub but hadn't yet been forced to reauthenticate due to the age of their login. I don't know how two groups managed to get two users added, given the behavior.

The error from the traceback:
```
    sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: groups.name
    [SQL: INSERT INTO groups (name) VALUES (?)]
    [parameters: ('canvas::1497305::student',)]
```
occurred with the group `canvas::1497305::student`, however I see no such existing group in the hub.

**Comment by minrk** [comment]
Is there any chance `user["groups"]` could have the same group name occurring twice? Looking at the code for sync_groups, I think it would try to create a group that doesn't exist once for each occurrence in `user["groups"]`

**Comment by minrk** [comment]
The alternative is that the `orm.Group.name.in_` query isn't actually working. That would be harder to track down and deal with.

**Comment by minrk** [comment]
I was able to reproduce that exact error by making e.g. `user["groups"] = ["new-group", "new-group"]`, which is fixed by #4019. If you still have access to logs, you should see `Creating new group 'canvas::1497305::student' for user XYZ` multiple times shortly before the traceback if this is indeed the problem.

**Comment by ryanlovett** [comment]
@minrk I can confirm! In similar instance, I see a log entry of the form:
```
Adding user _the_user_ to group(s): {'canvas::1513507::student', 'canvas::1489396::student', 'canvas::1508441::student', 'canvas::1492614::student', 'canvas::1516187::student', 'canvas::1496116::student', 'canvas::1492957::student', 'canvas::1511845::student', 'canvas::1502135::student', 'canvas::1497488::student', 'canvas::1506571::student', 'canvas::1507300::student', 'canvas::1498006::student', 'canvas::1496541::student', 'canvas::1502503::student', 'canvas::1512317::student', 'canvas::1494701::student'}
```

Followed by:
```
Creating new group canvas::1496541::student for user _the_user_
Creating new group canvas::1497488::student for user _the_user_
Creating new group canvas::1502503::student for user _the_user_
Creating new group canvas::1516187::student for user _the_user_
Creating new group canvas::1516187::student for user _the_user_
Creating new group canvas::1506571::student for user _the_user_
Creating new group canvas::1506571::student for user _the_user_
Creating new group canvas::1489396::student for user _the_user_
Creating new group canvas::1496116::student for user _the_user_
Creating new group canvas::1492614::student for user _the_user_
Creating new group canvas::1513507::student for user _the_user_
Creating new group canvas::1511845::student for user _the_user_
Creating new group canvas::1502135::student for user _the_user_
Creating new group canvas::1502135::student for user _the_user_
Creating new group canvas::1492957::student for user _the_user_
Creating new group canvas::1508441::student for user _the_user_
Creating new group canvas::1512317::student for user _the_user_
Creating new group canvas::1512317::student for user _the_user_
Creating new group canvas::1507300::student for user _the_user_
Creating new group canvas::1507300::student for user _the_user_
Creating new group canvas::1498006::student for user _the_user_
Creating new group canvas::1498006::student for user _the_user_
Creating new group canvas::1498006::student for user _the_user_
Creating new group canvas::1494701::student for user _the_user_
Creating new group canvas::1494701::student for user _the_user_
```

Ten with one entry, six with two entries, and one with three.

We will apply the fix soon, except the first week of class is next week so we'll wait for a more quiet time to do it.

Thanks!

**Comment by minrk** [comment]
Great! that means you can apply the same fix in your custom hook by calling the same `sorted(set(group_names))` before returning it, so that JupyterHub doesn't get new groups twice.
