### ISSUE TITLE
Documentation issue: c.JupyterHub.port is deprecated but not indicated in doc

### ISSUE THREAD

**Issue by ebebpl** [jupyterhub/jupyterhub#4020]
### Bug description

In the docs in url: https://jupyterhub.readthedocs.io/en/stable/getting-started/networking-basics.html
it states that: 
```
Or by placing the following lines in a configuration file, jupyterhub_config.py:
c.JupyterHub.ip = '192.168.1.2'
c.JupyterHub.port = 443
```
But in the latest Jupyterhub 2.x.x the generated config file states the above property is deprecated:
```
## The public facing port of the proxy.
#
#          This is the port on which the proxy will listen.
#          This is the only port through which JupyterHub
#          should be accessed by users.
#
#          .. deprecated: 0.9
#              Use JupyterHub.bind_url
#  Default: 8000
# c.JupyterHub.port = 8000
```

#### Expected behaviour

The readthedocs document should mention the non-deprecated property not the deprecated property.

**Comment by GeorgianaElena** [comment]
Thanks for catching and reporting this @ebebpl! The docs should be indeed updated with latest info.

A PR to fix this issue would be very appreciated and a great [first JupyterHub contribution](https://github.com/jupyterhub/jupyterhub/blob/main/CONTRIBUTING.md) ✨ 
The source of that docs page is this file https://github.com/jupyterhub/jupyterhub/blob/main/docs/source/getting-started/networking-basics.md

**Comment by hsadia538** [comment]
Hi,
I would like to work on this issue.

**Comment by ebebpl** [comment]
Thanks @hsadia538 you can work on it.

**Comment by shubham0473** [comment]
I have submitted a PR that closes this issue #4022. Please review and accept.

**Comment by BhavyaT-135** [comment]
Hey @ebebpl, if no one is working on this issue at the moment, could I give it a try?😊

**Comment by ebebpl** [comment]
@BhavyaT-135 you can go ahead if no pending fix or PRs.

**Comment by BhavyaT-135** [comment]
Hi @ebebpl, I have created a pull request addressing the mentioned issue. Kindly take a look and suggest any changes if required. 😊

**Comment by akashthedeveloper** [comment]
Hey, @ebebpl I would like to work on this issue, can you please help me to understand this issue and assign it to me?

**Comment by ebebpl** [comment]
@akashthedeveloper this issue already fixed by another user so no longer need further work.

**Comment by akashthedeveloper** [comment]
Thanks, @ebebpl for clarifying but can you please close this issue if it is solved?

**Comment by minrk** [comment]
@akashthedeveloper The pull requests are open, it will be closed when they have been reviewed and merged. You can see the links on the right hand side:

![Screen Shot 2022-10-10 at 09 26 04](https://user-images.githubusercontent.com/151929/194816395-e6211599-0d53-429e-b484-b13112b359be.png)

and linked in the conversation:

![Screen Shot 2022-10-10 at 09 26 35](https://user-images.githubusercontent.com/151929/194816452-99ab924a-0748-48aa-a6ef-a374cee85447.png)

**Comment by Achele** [comment]
hi @ebebpl i would like to work on this issue

**Comment by ebebpl** [comment]
@Achele please read earlier comments this is already done by others.

**Comment by Achele** [comment]
my bad,  @ebebpl thanks for the clarification.
