### ISSUE TITLE
Spawn failed

### ISSUE THREAD

**Issue by metoru** [jupyterhub/jupyterhub#4023]
I’m running Jupyterhub on K8s cluster . the error “Spawn failed: Server didn’t respond in 30 seconds” occurs when logging in as a user. and This problem only occurs in a specific image, but this image was used normally before.

error
![image](https://user-images.githubusercontent.com/46242303/187068987-39b9db7b-0cfa-4c48-9cde-c744a4ac355c.png)
log
![image](https://user-images.githubusercontent.com/46242303/187069000-2a00957c-0458-4afb-8136-bf13c837d239.png)
What am I doing wrong?

**Comment by metoru** [comment]
您好，我已经收到你的邮件

**Comment by consideRatio** [comment]
@metoru please raise this request for help in discourse.jupyter.org, its likely not a bug to be tracked for developers of the jupyterhub software itself, but a configuration issue with regards to how you have deployed your jupyterhub.

For others to help you, include as much details about your installation as you can.

**Comment by metoru** [comment]
您好，我已经收到你的邮件
