### ISSUE TITLE
Users unable to restart their own server

### ISSUE THREAD

**Issue by blair-anson** [jupyterhub/jupyterhub#4024]
Hi, recently upgraded JupyterHub from 1.1.0 to 2.3.1. After upgrading our users are no longer able to use
File -> Hub Control Panel -> Stop My Server
the following error is shown
```
API request failed (403): Action is not authorized with current scopes; requires any of [delete:servers]
```

Looks like I might have to add a role to the jupyterhub_config.py to bestow "delete:servers" but I don't understand how to write one to apply to all users. Can you please help?

**Comment by ajcollett** [comment]
Hello, I am seeing the same on my deployment. 

There seems to be a change in the way certain bit of the UI query the backend. 

I am using helm to deploy my instances, and when comparing stable and beta deployments (roughly correspond to your hub versions) I see the web UI in the beta deployment does queries the API directly, whereas the previous stable webUI does not use the /API. 

I am not sure why users authenticated on the browser cannot use the API, but that seems to be the main issue I am facing. I cannot query anything other than the root /api/, with the admin user.

**Comment by ajcollett** [comment]
Hello again, 

Okay I know what my trouble is. I set `hub.baseUrl` to a sub path for my instances. 

The API doesn't seem to like that, as when I deploy to a '/' path, it works happily. So my "/some_sub_path/" is causing my issues. 

Do you run your Jupyterhub instance on a sub path?

**Comment by blair-anson** [comment]
Thanks for looking into this @ajcollett. 
I do not set `hub.baseUrl`. But you did give me an idea though. I run a CDN (CloudFront) in front of the jupyter server, it acts like a proxy and it handles https termination etc. I just tried accessing the jupyter server directly and when using the Hub Control Panel to restart the server the error does not appear.
So something in the new jupyterhub/lab version must be conflicting with CloudFront. I will try analysing the http requests to see how the auth permissions are sent from the browser to the server as CloudFront must be interfering with it.

**Comment by ajcollett** [comment]
@blair-anson this is actually the case with my situation too. 

I tested removing the path without going through out reverse proxy, Pomerium. 

When I test **with** the path, but bypassing Pomerium, then it works. 

So this is probably a headers thing. I'll also look into this.

**Comment by ajcollett** [comment]
So, my issue seems to stem from here:
https://github.com/jupyterhub/jupyterhub/blob/7a48da1916cad8668c8d9aa5f2019b236354cb94/jupyterhub/utils.py#L743

I see `Blocking Cross Origin API request. Referer: https://myhost/hub/admin, X-Forwarded-Host: myhost, Host URL: http://myhost/hub/`

In the hub logs, but I don't know where to convince jhub it's actually https. The browser is at https, and so are all the reverse proxies in-between.

**Comment by ajcollett** [comment]
Okay, I managed to get things working in my case. 

I had to set the nginx ingress on K8s to use ssl as well as Jupyterhub, then my reverse proxy via Pomerium would work. So somewhere in the chain the wrong scheme was being passed down. 

For your case, maybe you need to use HTTPS between your server and CloudFlare?

You may need to set CloudFlare SSL to strict, see here: https://stackoverflow.com/questions/23121800/nginx-redirect-loop-with-ssl

**Comment by manfuin** [comment]
I have this issue on k8s. In my case it comes down to the fact that Nginx Ingress does not respect the X-Forwarded-* headers coming from upstream proxy. 
The fix is to enable this option: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-forwarded-headers

**Comment by julietKiloRomeo** [comment]
I agree that #4032 will fix this. Until then we are using a patch in apihandlers/base.py that fixes the stopping of servers and also the progress bar + redirect during spawn. You can see the patch in the comments for #4032 .

We are running behind apache and the problem comes from some internal traffic being upgraded to https and then hitting the `Blocking Cross Origin API request` because the host was https and the referrer is now https.
