### ISSUE TITLE
Jupyterhub Docker Container, PATH and LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by spalkovits** [jupyterhub/jupyterhub#403]
Hello,

I am right now trying to use Jupyterhub as a Docker container and combine it with the CUDA Docker container.To do so I start with the Jupyterhub image and add the commands from the CUDA container.

When I do an "docker exec -it **container** /bin/bash" everything works fine and I get a correct PATH and LD_LIBRARY_PATH by **printenv** leading to a proper output e.g. of **nvidia-smi**.

When I login to Jupyterhub and start a new terminal the shared libraries for CUDA where not found although they live inside the container.

How can I correct this? Any suggestions would be highly welcome.

Regards,

Stefan

**Comment by minrk** [comment]
Do you have your Dockerfile? A full shell session is probably not being started, so any settings in, for instance, bashrc, won't be loaded.

You can address this by changing the entrypoint to be a bash script that does:

```bash
source ~/.bashrc
exec jupyterhub-singleuser $@
```

The `exec` is important, because it replaces the running process rather than starting a new one.

**Comment by spalkovits** [comment]
FROM jupyter/jupyterhub:latest
    
    # ADD ssl files
    ADD /ssl/server.key /srv/jupyterhub/server.key
    ADD /ssl/server.crt /srv/jupyterhub/server.crt

    # Migrate local users
    WORKDIR /opt

    ADD /migrate/restore.sh /opt/restore.sh
    ADD /migrate/passwd.mig /opt/passwd.mig
    ADD /migrate/shadow.mig /opt/shadow.mig
    ADD /migrate/group.mig /opt/group.mig
    ADD /migrate/gshadow.mig /opt/gshadow.mig

    RUN ["sh", "/opt/restore.sh"]

    RUN rm -r /opt/*

    RUN adduser **myusername** sudo

    # Add lecture users

    ADD /user/userlist.txt /opt/userlist.txt
    RUN newusers /opt/userlist.txt
    RUN rm -r /opt/*

    # Install packages

    RUN apt-get update
    RUN apt-get install -y -q python-numpy python-scipy python-matplotlib python-pandas ipython python-     sklearn
    #RUN apt-get install -y -q python-sympy python-nose

    # Install ffmpeg

    RUN apt-get install -y -q software-properties-common
    RUN add-apt-repository ppa:mc3man/trusty-media -y
    RUN apt-get update
    RUN apt-get dist-upgrade -y

    RUN apt-get install -y -q ffmpeg

    # Add CUDA capabilities

    LABEL com.nvidia.volumes.needed="nvidia_driver"

    ENV NVIDIA_GPGKEY_SUM    bd841d59a27a406e513db7d405550894188a4c1cd96bf8aa4f82f1b39e0b5c1c
    ENV NVIDIA_GPGKEY_FPR 889bee522da690103c4b085ed88c3d385c37d3be

    RUN apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY && \
    apt-key adv --export --no-emit-version -a $NVIDIA_GPGKEY_FPR | tail -n +2 > cudasign.pub && \
    echo "$NVIDIA_GPGKEY_SUM  cudasign.pub" | sha256sum -c --strict - && rm cudasign.pub && \
    echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64 /" > /etc/apt/sources.list.d/cuda.list

    ENV CUDA_VERSION 7.5
    LABEL com.nvidia.cuda.version="7.5"

    ENV CUDA_PKG_VERSION 7-5=7.5-18
    RUN apt-get update && apt-get install -y --no-install-recommends --force-yes \
            cuda-nvrtc-$CUDA_PKG_VERSION \
            cuda-cusolver-$CUDA_PKG_VERSION \
            cuda-cublas-$CUDA_PKG_VERSION \
            cuda-cufft-$CUDA_PKG_VERSION \
            cuda-curand-$CUDA_PKG_VERSION \
            cuda-cusparse-$CUDA_PKG_VERSION \
            cuda-npp-$CUDA_PKG_VERSION \
            cuda-cudart-$CUDA_PKG_VERSION && \
        ln -s cuda-$CUDA_VERSION /usr/local/cuda && \
        rm -rf /var/lib/apt/lists/*

    RUN echo "/usr/local/cuda/lib" >> /etc/ld.so.conf.d/cuda.conf && \
        echo "/usr/local/cuda/lib64" >> /etc/ld.so.conf.d/cuda.conf && \
        ldconfig

    RUN echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf && \
        echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf

    ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
    ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}

     # Correcting PATH for the CUDA environment

    ENV PATH /usr/local/cuda/bin:${PATH}
    ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}

    # Set Working directory

    WORKDIR /srv/jupyterhub/

**Comment by spalkovits** [comment]
Hello,

I first post the Dockerfile because it messed up with the Markdown I wanted to add.

My basic idea was to start from a Jupyterhub and add CUDA capabilities, that my users and me can use e.g. PyCUDA. The Dockerfile looks like this:

* First I use project jupyters image as a start
* Then I migrate the users from the host to the container for convenience
* Then I make my user sudo
* Next I add some additional users (for purposes of a lecture)
* Now I add Python packages and ffmpeg
* The next block is a 1:1 copy of Nvidias CUDA Dockerfile
* Now I tried to adjust the PATH and the LD_LIBRARY_PATH
* And reset the the working directory

In principle everything works OK. When I do an **docker exec -it *container-name* /bin/bash** things like **nvidia-smi** work like expected. When I try in Jupyterhubs terminal it fails.

I tried the **source ~/.bashrc** but there is no **.bashrc** in my home folder. Maybe it would be an idea to create one and use it to correct the paths?

Regards,

Stefan

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:

**Comment by bernochoa** [comment]
For anyone still running into this issue, it seems that the container startup script resets the environment in a way that doesn't preserve the LD_LIBRARY_PATH variable when the container is run as root.

I fixed this by adding the following line to the Dockerfile:

`RUN sed -i 's/exec sudo -E -H -u $NB_USER/exec sudo -E -H -u $NB_USER LD_LIBRARY_PATH=$LD_LIBRARY_PATH/' /usr/local/bin/start.sh`

**Comment by rryoung98** [comment]
@ryanhill1
