### ISSUE TITLE
Named server limit per user indeed

### ISSUE THREAD

**Issue by danilopeixoto** [jupyterhub/jupyterhub#4038]
Would it be doable to set `named_server_limit_per_user` type as Callable as well?

```python
def named_server_limit_per_user(user):
    if user.name == 'user':
        return 10

    return 0


c.JupyterHub.named_server_limit_per_user = named_server_limit_per_user
```

### Proposed change

Open to discussion.

### Alternative options

- Introduce `named_server_limit_hook`
- Introduce `named_server_limit` attribute per user
- Introduce general quota service

### Who would use this feature?

Administrator needs to set how much server each user is limited to spawn simultaneously.

**Comment by minrk** [comment]
Yes, allowing a Callable here should be just fine.
