### ISSUE TITLE
Since jupyterhub3, We can no longer call app.main with arguments

### ISSUE THREAD

**Issue by djangoliv** [jupyterhub/jupyterhub#4040]
I call jupyterhub programmatically like this

```
from jupyterhub.app import main
main(argv=["-f", "jupyterhub_config.py"])
```
It works fine in jupyterhub2, but not with jupyterhub3

Since commit b0b7378e2, argv is passed in loop.run_sync. But loop.run_sync take `time out` for argument, not argv.

`task = asyncio.ensure_future(self.launch_instance_async(argv))`
became
`loop.run_sync(self.launch_instance_async, argv)`

Maybe, it should be something like this:

`loop.run_sync(lambda: self.launch_instance_async(argv))`

Regards,

**Comment by minrk** [comment]
closed by #4039
