### ISSUE TITLE
Request for accuracy: Rename "Delete" to "Move to Trash"

### ISSUE THREAD

**Issue by nicobasile** [jupyterhub/jupyterhub#4052]
### Bug description

In the Jupyterhub UI, the user has the option to "Delete" the file the have selected. 
However, the actual behavior of "Delete" is to move the file to $HOME/.local/share/files/Trash

This caused some problems for my team when we wondered why storage space wasn't being cleared after "Delete"ing a file. Renaming this option to "Move to Trash" would be more accurate and mimic what MacOS/Windows names this identical feature. 

![Screen Shot 2022-09-22 at 4 21 36 PM](https://user-images.githubusercontent.com/53441157/191867910-72f1f927-d34c-4a13-a5e1-3b8cafd36a47.png)

#### Expected behaviour

We expected "Delete" to delete and clear the storage space that the file once occupied.

#### Actual behaviour

"Delete" moves the file to a different location without actually deleting it.

**Comment by manics** [comment]
The deletion behaviour and UI is controlled by the singleuser server (e.g. JupyterLab or notebook), and the underlying operating system. JupyterHub doesn't have any influence on it.

**Comment by nicobasile** [comment]
whoops, i'll post the issue there instead
