### ISSUE TITLE
Disable CORS scheme and port validation inside JupyterHub

### ISSUE THREAD

**Issue by maciejkul** [jupyterhub/jupyterhub#4056]
### Proposed change
In base.py, line 83 is code for Cross Origin API request validation:
```        
if (
      referer_url.scheme != host_url.scheme
      or referer_url.hostname != host_url.hostname
      or referer_port != host_port
      or not (referer_url.path + "/").startswith(host_url.path)
   ):
```
It's very strict, validation cover scheme, port, hostname and URL path. It's cause issue if people use passive load balancing with SSL termination.  Issue is:
```
[W 2022-09-29 09:59:50.349 JupyterHub base:94] Blocking Cross Origin API request.  Referer: https://jupyter.local/hub/home, Host: jupyter.local, Host URL: http://jupyter.local/hub/
``` 
Request headers ORIGIN and REFERER are  **https://jupyter.local** , when expected is **http://jupyter.local**. There is no possibility to change or add headers due to passive load balancing limitations. The idea is to add flag(f.e `--no-cors-scheme-check`) which will disable port and scheme validation.

### Who would use this feature?

People with passive load balancing (F.e Virtual  IP address) with termination SSL. There isn't possibility to modify HTTP headers as we use passive load balancer.

**Comment by manics** [comment]
Hi! This is being removed in
https://github.com/jupyterhub/jupyterhub/pull/4032

Would you mind looking at that PR and giving your feedback there? Thanks!
