### ISSUE TITLE
capture proxy log in Hub log when the proxy is started by the Hub

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#414]
When the proxy is started by the Hub, the logs are interleaved in the terminal, but if the Hub's log is sent to a file, the proxy log may be left out (I think this is the source of missing information in #327).

If we capture the subprocess output and forward it to the Hub's own logger, then they should always be found together, at least.

**Comment by zoltan-fedor** [comment]
I just wanted to file a bug report to the same.

When I run Jupyterhub from the command line ("jupyterhub -f jupyterhub_config.py") the subprocess logs (like the logs of connecting to Apache Spark) are interleaved and displayed in the terminal.

When I run Jupyterhub as service and send its logs to a file using c.JupyterHub.extra_log_file, then the logs from the subprocess are left out, doesn't matter the logging level set (even debug).

**Comment by minrk** [comment]
I'm not a huge fan of extra_log_file, since redirecting stdout/stderr at a higher level (as done by docker, supervisor, or any other process management tool) will always be more robust. Is there a reason you use extra_log_file instead of redirecting the output?

**Comment by zoltan-fedor** [comment]
Yes, because I run jupyterhub as a service and can't redirect the stdout and stderr of the service.

Tried:
```
[Unit]
Description=Jupyterhub

[Service]
User=root
ExecStart=/usr/bin/jupyterhub -f /etc/jupyterhub_config.py
StandardOutput=/apps/logs/jupyterhub/jupyterhub_stdout.log
StandardError=/apps/logs/jupyterhub/jupyterhub_stderr.log

[Install]
WantedBy=multi-user.target

```

And:
```
[Unit]
Description=Jupyterhub

[Service]
User=root
ExecStart=/usr/bin/jupyterhub -f /etc/jupyterhub_config.py >> /apps/logs/jupyterhub/jupyterhub_stdout.log 2>> /apps/logs/jupyterhub/jupyterhub_stderr.log

[Install]
WantedBy=multi-user.target
```


But if I run directly from command line, then it works:
`sudo /usr/bin/jupyterhub -f /etc/jupyterhub_config.py >> /apps/logs/jupyterhub/jupyterhub_stdout.log 2>> /apps/logs/jupyterhub/jupyterhub_stderr.log`


Both of the above service definitons should log, but they don't, so I can only conclude that something must be in the jupyterhub code which shuts down stdout and stderr when not running from command line or when certain env settings are not done.

Do you have a working example of how to log stdout and stderr from the jupyterhub service?

**Comment by minrk** [comment]
> I can only conclude that something must be in the jupyterhub code which shuts down stdout and stderr when not running from command line or when certain env settings are not done.

There aren't any that I'm aware of, so they would have to be in the Python logging module, I think. 

> Do you have a working example of how to log stdout and stderr from the jupyterhub service?

With supervisor, this works to send stdout and stderr to /var/log/jupyterhub.log (only the lines containing stdout and stderr are relevant):

```ini
[program:jupyterhub]
command=/usr/bin/python3 -m jupyterhub
directory=/srv/jupyterhub
autostart=true
autorestart=true
startretries=3
exitcodes=0,2
stopsignal=TERM
redirect_stderr=true
stdout_logfile=/var/log/jupyterhub.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
user=root
```

I haven't tried running JupyterHub with systemd yet, but I will give that a go and see if I can figure out why systemd wouldn't properly capture stderr.

**Comment by zoltan-fedor** [comment]
Thanks, I might switch to running jupyterhun in supervisord then, but first will wait for your findings re systemd.
I have tried multiple options in systemd - nothing. It seems that as soon as juptyerhub is running in systemd it does not generated stdout or stderr.

**Comment by consideRatio** [comment]
Issue triage: is this still an issue?

**Comment by manics** [comment]
They are, and have been for a while :smile:
