### ISSUE TITLE
Using `Juno` iOS app on JupyterHub endpoint cause redirect loop or 404: Not Found

### ISSUE THREAD

**Issue by anhdle14** [jupyterhub/jupyterhub#4165]
### Bug description

1. Deploying JupyterHub on local server (ArchLinux + SystemdSpawner + OAuthenticator)
2. Using Tailscale and Proxy to advertise local server via direct connection with HTTPS and OAuth (<https://jupyter.example.com>)
3. Using Juno on iOS to connect to the JupyterHub endpoint (<https://jupyter.example.com>)
4. Able to sign in but can't open notebook or lab.

> NOTE: Have tried to play around with `# c.Spawner.default_url = ''"`.  Tried `/`, `/tree`, `/lab` but none work.

#### Expected behaviour

Redirect on Juno should work and open a Notebook.

#### Actual behaviour

Juno tried to connect to: <https://jupyter.example.com>.

1. Setup <https://jupyter.example.com>
2. Sign In with GitHub (but it could be local user as well, it is just for my setup)
3. OAuth2 GitHub flow
4. Juno shows 404: Not Found.

> NOTE: The URL after redirect for Juno is: <https://jupyter.example.com/user/anhdle14/tree?> which resolve to `404: Not Found`

### How to reproduce

1. Install Juno on iOS
2. Deploy JupyterHub on any server
3. Connect to JupyterHub via Juno

### Your personal set up

1. `yay -S jupyterhub` running on Arch Linux.
2. Using Tailscale and Kubernetes to route things via 443 and VPN instead of direct communication.
3. Jupyterhub using `LocalGitHubOauthenticator` and `SystemdSpawner`

> I can provide more information but this doesn't seem like an OS specific issue so I will be lazy for this.

</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
# jupyterhub --generate-config
import os

c = get_config()

c.JupyterHub.hub_ip = '0.0.0.0'

# Switch to systemdspawner
c.JupyterHub.spawner_class = 'systemdspawner.SystemdSpawner'
c.SystemdSpawner.default_shell = '/usr/bin/zsh'
c.SystemdSpawner.readonly_paths = ['/']
c.SystemdSpawner.readwrite_paths = ['/home/{USERNAME}']
c.SystemdSpawner.disable_user_sudo = True
c.SystemdSpawner.extra_paths = ['/home/{USERNAME}/.virtualenvs/jupyterhub/bin']
c.SystemdSpawner.default_url = '/lab'

c.JupyterHub.authenticator_class = 'oauthenticator.LocalGitHubOAuthenticator'
c.GitHubOAuthenticator.client_id = '${JUPYTERHUB_GH_CLIENT_ID}'
c.GitHubOAuthenticator.client_secret = '${JUPYTERHUB_GH_CLIENT_SECRET}'
c.GitHubOAuthenticator.oauth_callback_url = '${JUPYTERHUB_GH_CALLBACK_URL}'

# create system users that don't exist yet
c.LocalAuthenticator.create_system_users = True

# specify users and admin
c.Authenticator.admin_users = {'anhdle14'}
```

**Comment by minrk** [comment]
This looks like the single-user server is expecting the classic notebook but it isn't available. You might be missing the `notebook` package and/or `jupyterlab` if that's what you expect. Can you share `pip list` in the single-user environment?

**Comment by anhdle14** [comment]
```
$ pip freeze | grep jupyterlab
jupyterlab==3.4.8
jupyterlab-pygments==0.2.2
jupyterlab_server==2.16.1
$ pip freeze | grep note
notebook_shim==0.2.0
```

**Comment by minrk** [comment]
And setting `c.Spawner.default_url = '/lab'` doesn't work? With that, you wouldn't get sent to `/tree/`.

You can `pip install nbclassic` to get the classic notebook handlers registered.

**Comment by anhdle14** [comment]
will close the issue now, that being said maybe we should include `nbclassic` into the bundle of jupyterhub as well?

**Comment by minrk** [comment]
No, we definitely shouldn't include nbclassic as a dependency in jupyterhub, since that's only for single-user environments are there are many different options. It does work with just jupyterlab, without nbclassic.

`/tree/` is not required for jupyterhub, that's specific to nbclassic (or the older `notebook` package). If you have jupyterlab or retrolab, or any other jupyter-server-based single-user application, it will work.

If Juno is making some assumptions about the presence of `/tree/`, that would be a Juno issue.
