### ISSUE TITLE
No more delete server button on admin page

### ISSUE THREAD

**Issue by djangoliv** [jupyterhub/jupyterhub#4174]
### Bug description

Since react admin page there is no more "delete server" button on stopped server.

![servers](https://user-images.githubusercontent.com/13416971/197997999-58f78132-f7e6-499d-86e1-e791403e1086.png)

#### Expected behaviour

As admin, I need the possibility to delete stopped servers.

#### Actual behaviour

Can't delete stopped servers in UI.

**Comment by minrk** [comment]
@naatebarber @NarekA can you have a look?

**Comment by hegdeashwin** [comment]
I would like to contribute on this. Any initial guideline to follow before I start working on this feature?

**Comment by manics** [comment]
There's a mix of Javascript build systems in this repo as parts of the UI have been refactored separately.

The Admin UI is a newer React app, instructions are in https://github.com/jupyterhub/jupyterhub/tree/main/jsx
