### ISSUE TITLE
stateless and High Availability of jupyterhub in kubernetes

### ISSUE THREAD

**Issue by kabanala** [jupyterhub/jupyterhub#4183]
### Proposed change
We want to Scale Jupyter Hub from a single instance into multiple instances , as traffic / user activity increases.
We want users to switch between multiple instances / pods of the Jupyter Hub deployment.
When jupyter Hub pods goes down or crash , User should not see any disruption for their work  
Our scope and goal is to only implement the above enhancements for Kubernetes based deployment. 

### Who would use this feature?
who ever needs a large scale deployments 

#### Goal 
We want to Scale Jupyter Hub from a single instance into multiple instances , as traffic / user activity increases.
We want users to switch between multiple instances / pods of the Jupyter Hub deployment.
When jupyter Hub pods goes down or crash , User should not see any disruption for their work  
Our scope and goal is to only implement the above enhancements for Kubernetes based deployment. 
#### Challenges 
JupyterHub is stateful. They manage the user sessions and their state in the application cache . This means the architecture needs to be sticky , so we need to route users to respective jupyter hub instances when we scale to multiple instances.
We can only scale it up to X users based on the resource available on the node. 
#### Proposed Architecture 
The proposed architecture tries to address our challenges to  make  JupyterHub scalable and  have High availability .
![Screen Shot 2022-10-27 at 1 40 06 PM](https://user-images.githubusercontent.com/48365516/198395705-fd62499a-1904-4fd0-912b-5fbd92eb5db6.png)

 #### Persist Proxy state and decouple from JupyterHub 

  ####  Move proxy into a separate service from JupyterHub
  ####  Persist the routing table information from sqlite database to a shared database . 
          
    Scenarios Addressed 

     Users who have already  running jupyterlab servers are always redirected to the server even when one of the proxy goes down / crashes since routing tables are persisted and shared among the proxy pods.

     No impact for users already running jupyterlab servers 

 #### Persist the  users cached state in memory state in jupyterhub and mySQLite into a distributed cache like Redis , etc , backed with shared database like MySQL DB.

     Scenarios Addressed 

      When Jhub pod goes down , we route the user to another pod which will check if the user state and session in the distributed cache and still route the user to the Jupyterlab server without losing the state or data since it is persisted 

By making the proposed changes in the architecture , JupyterHub will become scalable and have High availability. 

@srinivasanmanoharan

**Comment by kabanala** [comment]
@srinivasanmanoharan

**Comment by manics** [comment]
Hi! Please could you add your ideas to this existing issue: https://github.com/jupyterhub/jupyterhub/issues/1932
Thanks!
