### ISSUE TITLE
Print spark dataframe more friendly for reading

### ISSUE THREAD

**Issue by FukoH** [jupyterhub/jupyterhub#4184]
### Proposed change

I come across this problem with pyspark.
When I call foo.show(),if the foo dataframe contains too many columns, the result won't be printed in a single row in jupyter notebook.Instead it will be splitted into two rows,and not easy to read for human.How can I solve this problem?Could it be printed more friendly for reading?

[stackoverflow](https://stackoverflow.com/questions/74219583/how-to-make-table-result-not-to-show-up-in-two-rows-in-jupyter-notebook-when-cal/74223262#74223262)
### Who would use this feature?

People who need to explore unknown data set need to compare  data set between many columns

### (Optional): Suggest a solution

May be I can drag side bar inside the result cell to see full result

**Comment by minrk** [comment]
I'm not quite sure what the issue is, but display of Spark dataframes is handled by pyspark, not any Jupyter package.

If the issue is more generally very wide terminal output in jupyterlab, I believe that is open at https://github.com/jupyterlab/jupyterlab/issues/4208
