### ISSUE TITLE
Unaligned Text Blocks on JupyterHub REST API Page (Mobile View)

### ISSUE THREAD

**Issue by 3qiu** [jupyterhub/jupyterhub#4197]
### Bug description

The webpage was not built to fit the mobile view
#### Expected behaviour
The texts should be clear and aligned within the text border

#### Actual behaviour
Text Blocks on JupyterHub REST API Page are not unaligned and some texts are blocked when viewing the webpage on mobile phones.

### How to reproduce
Need to update the styling file to make it mobile friendly.

1. Go to https://jupyterhub.readthedocs.io/en/3.0.0/reference/rest-api.html#/default/get_users

2. See error (img attached)
3. ![1151667488683_ pic](https://user-images.githubusercontent.com/73413308/199761762-8293c19d-e31e-4259-9114-1bc089bf7e37.jpg)
![1141667488683_ pic](https://user-images.githubusercontent.com/73413308/199761743-380ac43b-2e12-4802-b14b-1841f71817d5.jpg)

### Your personal set up

 - OS:
 
android phone
 - Version(s):
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by bl-aire** [comment]
Hello @3qiu, are you working on this?

**Comment by bl-aire** [comment]
@minrk @sgibson91 

Hello, I would love to work on this if it hasn't been assigned to anyone.

**Comment by 3qiu** [comment]
> Hello @3qiu, are you working on this?

No, please go ahead to solve it.  Thank you!

**Comment by bl-aire** [comment]
> No, please go ahead to solve it.

Okay. Thanks

**Comment by bl-aire** [comment]
Thank you @sgibson91 , I will go through it now

**Comment by minrk** [comment]
I think this is fixed by our switch to redoc: https://jupyterhub.readthedocs.io/en/latest/reference/rest-api.html#operation/get-current-user
