### ISSUE TITLE
Jupyter logo link behavior change

### ISSUE THREAD

**Issue by Harlool** [jupyterhub/jupyterhub#4220]
Hello,

After upgrading JupyterHub from 1.4.2 to 3.0.0, the behavior of the JupyterHub logo (in the banner) has changed when using the combination of below parameters that allow users to navigate the whole filesystem from their notebook server but still start in their home directory:

c.Spawner.default_url = '/tree/home/{username}'
c.Spawner.notebook_dir = '/'

In JupyterHub 1.4.2, the JupyterHub logo redirects the user to his home directory.
In JupyterHub 3.0.0, the JupyterHub logo redirects the user to the root.

Is this the expected behavior for 3.0.0 or is it a bug ?

**Comment by minrk** [comment]
This could be a bug, or it could be a version mismatch between the Hub and user environments.

Can you share the startup logs for the user environment where this happens? Also, `pip freeze` and/or `conda env export` for the user environment will help.

**Comment by Harlool** [comment]
The upgrade has been done in a sandbox server where JupyterHub is installed in a conda environment and started by a system account. Then users just logs in JupyterHub and clicks on the logo for testing purpose. Users don't have any personal conda environment at this point. I can only share the conda env export of the JupyterHub environment: [jupyterhub conda env.txt](https://github.com/jupyterhub/jupyterhub/files/10039391/jupyterhub.conda.env.txt)

These are the logs when a user log in jupyterhub and when he clicks on the jupyterhub logo (username and ipaddress have been changed for privacy reason) : 
[user startup logs.txt](https://github.com/jupyterhub/jupyterhub/files/10039255/user.startup.logs.txt)
[user click logo.txt](https://github.com/jupyterhub/jupyterhub/files/10039254/user.click.logo.txt)

In 3.0.0;
When a user log in jupyterhub, he's redirected to his home directory as it should, no issue there.
It's when clicking the logo that he's redirected to the root (as opposed to his home directory in 1.4.2).

Another observation (parameters c.Spawner.default_url and c.Spawner.notebook_dir are used in both versions) ;
In 1.4.2, the link of the jupyterhub logo is http://<servername>:<port>/user/<username>/tree/home/<username>
In 3.0.0, the link of the jupyterhub logo is http://<servername>:<port>/user/<username>/tree
Considering the link in 3.0.0, it's seems normal that it redirects to the root. Using the same link http://<servername>:<port>/user/<username>/tree in 1.4.2 also redirects to the root.

So could it be just that the link of the logo in 3.0.0 is not 'build' the same way as in 1.4.2 which could explain why they are different although using the same parameters in both versions ?

**Comment by minrk** [comment]
There are a lot of moving parts! This is apparently a change in nbclassic, which has made it so the logo URL is no longer controlled by default_url, which I think is a bug: https://github.com/jupyter/nbclassic/issues/182

**Comment by consideRatio** [comment]
This seems to be tracked now in jupyter/nbclassic#182, so I'll go for a close of this issue here in jupyterhub. If this was incorrect we can just reopen it!
