### ISSUE TITLE
ci: intermittent selenium test

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#4224]
As seen [in this github workflow run failure](https://github.com/jupyterhub/jupyterhub/actions/runs/3515164623/jobs/5890079884#step:12:115), a test is failing. But it does so intermittently.

```python-traceback
async def test_open_url_login(
        # ...
        else:
            if next_url.endswith(f"/user/{user}/") == False:
                await webdriver_wait(
                    browser, EC.url_to_be(ujoin(public_url(app), f"/user/{user}/"))
                )
>           assert next_url.endswith(f"/user/{user}/")
E           AssertionError: assert False
E            +  where False = <built-in method endswith of str object at 0x7f5445c9c530>('/user/test_user/')
E            +    where <built-in method endswith of str object at 0x7f5445c9c530> = 'http://127.0.0.1:33[92](https://github.com/jupyterhub/jupyterhub/actions/runs/3515164623/jobs/5890079884#step:12:93)7/@/space%20word/hub/spawn-pending/test_user'.endswith
```

I'm not sure what the fix is for this test, but perhaps its relates to a configuration option to automatically spawn a server after logging in or not? Where we end up getting redirected to the spawn pending page.

**Comment by manics** [comment]
Sounds like a race condition? Sometimes the singleuser server starts quickly, sometimes it's slightly slower so the pending page temporarily shows before going to the final page. It should be possible to update the test to be robustly handle both cases.

**Comment by minrk** [comment]
Yup, I think we need a more detailed wait or a longer timeout
