### ISSUE TITLE
Custom route for localhost H2O UI screen

### ISSUE THREAD

**Issue by somnath0796** [jupyterhub/jupyterhub#4235]
I am looking for implementation where post user authentication using a certain kernel, I want to let the user access localhost:54321 UI page  for H2O flow. It should be accessible from https://hostname/hub/user/username/lab/abc.ipynb/h2o that should be routing to localhost:54321. This server will be running in the background on base system.

If anyone has implemented a similar approach, looking for help on this.

**Comment by manics** [comment]
Have a look at https://github.com/jupyterhub/jupyter-server-proxy/ 

If you need more help please use https://discourse.jupyter.org/
Thanks!
