### ISSUE TITLE
docs: 3.1.0 vs 3.0.0 has different layout in api/index.html

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#4254]
I'm not sure what caused this, but the index looks better like in 3.0.0 I think.

3.0.0|3.1.0
-|-
![image](https://user-images.githubusercontent.com/3837114/206219702-84500155-c44a-43cd-a75c-3df30e928faa.png)|![image](https://user-images.githubusercontent.com/3837114/206219750-4e640aa4-e62e-4f06-aab6-bce070c74fa3.png)

**Comment by minrk** [comment]
I think this is toctree maxdepth. The depth is [unspecified](https://github.com/jupyterhub/jupyterhub/blob/24506888ea4904be97197426e42083a4769789c2/docs/source/api/index.rst?plain=1), and the file [unchanged](https://github.com/jupyterhub/jupyterhub/compare/3.0.0...3.1.0/docs/source/api/index.rst), so my guess is a change in the sphinx default, or somewhere else in sphinx config?
