### ISSUE TITLE
Shutdown servers missing from `GET /users/:username` endpoint

### ISSUE THREAD

**Issue by wudstrand** [jupyterhub/jupyterhub#4275]
### Bug description

I am using the jupyterhub backend to build a in browser coding environment, and I interface with the jupyterhub API through a custom hub service. In my jupyterhub configuration I have enabled named servers with a limit of three servers per user.  I have enabled the functionality to both shutdown and remove the servers through my custom service by using the hubs `DELETE /users/:name/servers/:server_name` endpoint (NOTE: removing the server adds `{'remove': true}` to the body of the request). I want to allow user to shutdown a server, and only remove it only when they reach their limit. I am running into an issue when trying to get a list of all the servers (i.e. running and shutdown) for a user. The only way I know to get the server for a user is through the `GET /users/:username` endpoint, but this only shows the running servers. Is there a way to get it to show the shutdown servers as well? Or is there another endpoint I can leverage? If not I would like to request an enhancement to the hub's API to handle this use case.

#### Expected behaviour

Here are a list of acceptable behaviors

- An endpoint for getting all servers for a user (running and shutdown).
- Enhancing the current user endpoint to include servers that are shutdown in the response.
- Enhancing the current user endpoint to have a flag that would include servers that are shutdown in the response.

#### Actual behaviour

Servers that are shutdown but not explicitly removed effect the number of named servers a user is allowed to create. Additionally there in no way via the jupyterhub API to get a list of all the servers (i.e. running and shutdown) for a user.

### How to reproduce

1. [Enable named servers](https://jupyterhub.readthedocs.io/en/stable/reference/config-user-env.html#named-servers).
2. Limit the number of named servers for a single user to three.
3. Create three servers for a single user via the API
4. Delete one of the three server with the `DELETE /users/:name/servers/:server_name` endpoint and exclude `{'remove': true}` from the body of the request
5. Try to create another server with a different name from the previous three.
    - Notice the request errors out
6. Make a request to the `GET /users/:username` endpoint and notice only the two servers running show up in the response.
    - Desired: The name of the shutdown server shows up here, so you can programmatically get the name of the server to delete it.

### Your personal set up
 
I am running jupyterhub on k8s using the [ztjh](https://z2jh.jupyter.org/en/stable/#zero-to-jupyterhub-with-kubernetes)

**Comment by minrk** [comment]
This (specifically option 3) was added in #3909 (jupyterhub 3.0). Including stopped servers is opt-in with the `?include_stopped_servers=1` url parameter.
