### ISSUE TITLE
Dot should not be an allowed domain name character

### ISSUE THREAD

**Issue by akhmerov** [jupyterhub/jupyterhub#4282]
### Bug description

If a username contains a period and subdomains are enabled, they will get a sub-subdomain now because this code doesn't mind sub-subdomains:

https://github.com/jupyterhub/jupyterhub/blob/49c518940bbdedbaf9037d463bcf455c794e5e3f/jupyterhub/user.py#L58-L60

I believe, however, that this doesn't match a common use case. For example, wildcard certificates don't support multilevel nesting, if I understand correctly.

#### Expected behaviour

Dot isn't considered a `_dns_safe` character.

**Comment by minrk** [comment]
Interesting! It definitely _is_ valid sometimes, so I guess it needs to be configurable? But you're right that 'regular' wildcard SSL won't be sufficient (nested subdomains can be added via SAN, but I imagine that's pretty unusual).

**Comment by akhmerov** [comment]
Would it perhaps be a reasonable idea to consider other pathways for providing a more complex subdomain structure than accidentally via the username? Deeper nested domains are a reasonable niche application, but arbitrary level domains aren't. Plus I'm not even sure if `one...two.example.com` is a legitimate domain name.

**Comment by minrk** [comment]
> Would it perhaps be a reasonable idea to consider other pathways for providing a more complex subdomain structure than accidentally via the username? 

I definitely think a custom hook to totally override domain-for-user makes sense.

>  Plus I'm not even sure if one...two.example.com is a legitimate domain name.

I'm pretty sure it's not.

There's a comment that we should really be using idna encoding for full DNS-safe labels. There's a [package for that](https://pypi.org/project/idna/), but it doesn't handle the ASCII part of it (escape `.`, can't start or end with `-`, etc.).
