### ISSUE TITLE
Spawn page customisation

### ISSUE THREAD

**Issue by nelsonct7** [jupyterhub/jupyterhub#4285]
### Proposed change

allow custom design option for spaw page, currently all available servers are listed in the spawn page, as options with a radio button to select the server, the user wanted, then click the orange start server button, I suggest for another option which allows the user to start the server with a button that attached with the individual server options, 

### Alternative options

the form page is so simple so we want to update the ui for a better experience along with the functionality.

### Who would use this feature?

the users could easily select  the respective server that they want, and can avoid the situation in which the unwanted server to initialise accidentally or by mistakenly.

### (Optional): Suggest a solution

The label field in the spawner_option_form should be customisble and there should be options to add much more input elements.
![62269722-830f6980-b466-11e9-9209-c16fc369f8af](https://user-images.githubusercontent.com/102008327/210070805-c854757a-73db-4cab-915c-7f6ac3b42ac5.png)

**Comment by minrk** [comment]
In JupyterHub, the options form is already a fully arbitrary HTML form. JupyterHub doesn't dictate anything here, other than it'll look most natural if you use bootstrap form-control css classes. You'll also have to implement `options_from_form` to translate from form data to and load `self.user_options` in your `spawner.start()`.

- [documentation of spawner forms](https://jupyterhub.readthedocs.io/en/stable/reference/spawners.html#spawner-options-form)
- [complete example](https://github.com/jupyterhub/jupyterhub/blob/3.1.0/examples/spawn-form/jupyterhub_config.py)

Some _spawners_ (kubespawner, profilespawner) allow generation of an options form from a list of profiles, so you don't need to do as much, but you can always skip that and specify the form input / loading directly.
