### ISSUE TITLE
The jupyterhub container fails to restart. How can I avoid this problem

### ISSUE THREAD

**Issue by 1014TaoTao** [jupyterhub/jupyterhub#4289]
jupyterhub image version: jupyterhub/jupyterhub:latest

After the container is started, update the jupyterhub, jupyterlab, and notebook in the container, add the users, and set jupyterhub admin. The jupyterhub is running properly on both web terminals. Run the jupyterhub upward-db command before exiting the container, and then run the docker restart jupyterhub container command after exiting. The container cannot be restarted。

The restart log is：
[I 2023-01-05 14:32:39.065 JupyterHub app:2810] Running JupyterHub version 3.1.0
[I 2023-01-05 14:32:39.065 JupyterHub app:2840] Using Authenticator: jupyterhub.auth.PAMAuthenticator-3.1.0
[I 2023-01-05 14:32:39.065 JupyterHub app:2840] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-3.1.0
[I 2023-01-05 14:32:39.065 JupyterHub app:2840] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-3.1.0
[I 2023-01-05 14:32:39.079 JupyterHub app:1649] Loading cookie_secret from /srv/jupyterhub/jupyterhub_cookie_secret
Found database schema version 833da8570507 != 651f5419b74d. Backup your database and run `jupyterhub upgrade-db` to upgrade to the latest schema.

**Comment by manics** [comment]
If you look at the last line of your logs:
> `Backup your database and run jupyterhub upgrade-db to upgrade to the latest schema.`

You can see your database is out of date, so try running that command.
