### ISSUE TITLE
Broken JupyterHub PDF documentation link from README.md

### ISSUE THREAD

**Issue by pnasrat** [jupyterhub/jupyterhub#4320]
### Bug description

Documentation for JupyterHub links to both PDF latest and stable are broken in `README.md`

Note the Documentation for Project Jupyter PDF works so not a readthedocs general issue. 

### How to reproduce

1. Got to Help & Resources section of README.md hhttps://github.com/jupyterhub/jupyterhub/blob/main/README.md#help-and-resources
2. Click on eiither stable or latest PDF links https://media.readthedocs.org/pdf/jupyterhub/latest/jupyterhub.pdf
3. Redirected to n: https://buildmedia.readthedocs.org/media/pdf/jupyterhub/latest/jupyterhub.pdf

`curl https://buildmedia.readthedocs.org/media/pdf/jupyterhub/latest/jupyterhub.pdf`

#### Actual behaviour

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <Key>pdf/jupyterhub/latest/jupyterhub.pdf</Key>
  <RequestId>DMPVJGPCQ8358NZ1</RequestId>
  <HostId>
    5dkr9PDZqgnRtZg+3Bsbj1QfRCeJomT2NkniReJnrWqMbrlxbNn/sbMfL9yHBkMXevAa4gaRekECIGqOXZ0fgw==
  </HostId>
</Error>
```

<details>
<summary>curl -I output</summary>
<p>
<pre>
HTTP/2 404
date: Sat, 28 Jan 2023 12:22:02 GMT
content-type: application/xml
vary: Accept-Encoding
x-amz-request-id: T7TPJM5CBTD0SY4X
x-amz-id-2: 7pyknvRDsd500tgtSOi+Y0jcOapSmospKY5bnbR0B0jJlSUldSQ3Tcft2mjEx3hh0MX/Nvi6tQs=
x-backend: web-i-0d350a49cade79f4b
cf-cache-status: MISS
expires: Sat, 28 Jan 2023 16:22:02 GMT
cache-control: public, max-age=14400
set-cookie: __cf_bm=Y2Kvg8vAOdo.hIE7fEAo4wn12xXj_9iUPOSJsXgJEkc-1674908522-0-ASP6Fi/Z9mBxfHniNj9Y1COQ4M1e7Clz/wevwjW/VfHiAVpkT9pIWDU2rQXGYCZ2EzQt6YNdkKgFrgbriCSXrU8=; path=/; expires=Sat, 28-Jan-23 12:52:02 GMT; domain=.readthedocs.org; HttpOnly; Secure; SameSite=None
server: cloudflare
cf-ray: 7909b0f9efb3c35e-EWR
</pre>
</p></details>

**Comment by pnasrat** [comment]
It looks like the pdf targets were removed from the doc makefile in commit a9b6d7e51ce71afcfc747f4ab9183603e16ca18f so this might just need removing the links like jupyter/notebook#6648

**Comment by minrk** [comment]
@pnasrat you're right! Want to remove the link? Our docs increasingly rely on HTML-only features of sphinx, so I don't think it makes sense to have PDF docs anymore (and htmlzip download would make more sense)
