### ISSUE TITLE
How to resolve broken links while writing redirects 

### ISSUE THREAD

**Issue by alwasega** [jupyterhub/jupyterhub#4335]
@GeorgianaElena, 

I am moving some of the documentation but after running `make html`, I am encountering the following warnings. This is after we used rediraffe to write redirects to the `redirects.txt` file. 
 
<img width="1067" alt="Screenshot 2023-02-02 at 15 42 48" src="https://user-images.githubusercontent.com/26059722/216330494-fa557894-d91f-4225-905e-260d8bc24add.png">

All the listed files are  presently contained in the `redirects.txt` file. 

<img width="813" alt="Screenshot 2023-02-02 at 15 58 14" src="https://user-images.githubusercontent.com/26059722/216330888-7fa465af-ce21-46d1-a5c9-9c46a8c746fa.png">

Please advise on how to resolve this.

**Comment by alwasega** [comment]
@sgibson91 , would you happen to know how to resolve this issue?

**Comment by minrk** [comment]
@alwasega try running `make clean` first. It may be that you have leftovers from a previous build.

**Comment by alwasega** [comment]
Thank @minrk. 
Yes, `make clean` resolves the issue.
