### ISSUE TITLE
User-initiated sharing, distinct from roles

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#4349]
### Proposed change

Introduce a first-class concept of a 'share', as distinct from general 'roles', to address the use case of "I want to easily grant someone access to my server and then maybe revoke it later".

For users granting access, I've long had in mind #3858 as the solution, which would allow users to create roles and role assignments at runtime, _one_ application of which could be granting someone else access to their server. But after testing out sharing and RTC use cases, I increasingly think that's not going to be enough. Even when we get to that (and I think we should still do that), we're probably going to want 'share' as a first-class concept.

### Alternative options

Implement fully generic roles, as described in #3858. This will _technically_ enable the same thing (likely _more_ things), but because it's a generic permissions-granting system, it may be complicated to implement a simple sharing access UI on top.

### Who would use this feature?

JupyterHub deployments where _users_ are in control of granting other users' access to their servers.

### (Optional): Suggest a solution

Introduce a first-class `share` entity in the JupyterHub, with REST API for create/delete/list.

Shares would:

- be owned by a specific user
- target a single, specific server
- be listable and revocable
- expire
- implementation-wise, ultimately be a restricted and runtime-defined role assignment
- grant the minimal `access:servers!server=...` permission
- (maybe) optionally grant additional `!server=`-filtered permissions. This will be necessary for e.g. read-only access. It's unclear to me what level of control will be needed on that.
- (maybe) optionally apply on wider filters, such as `!user`. I plan to go with "not in the first implementation" on this one.

Implementation-wise, this would effectively be a runtime role assignment, but with a higher-level API for creating/managing them, because they would be specifically used for accessing services (i.e. a 'share' couldn't be used to grant admin access). In addition to the new APIs and database entries for managing share objects themselves, the only change should be in resolving the permissions for a specific user to add Shares, which will be treated identically to Roles.

Features could include:

- 'share with link' where a special link could be used to _claim_ sharing access without the sharer needing to invite users by name (this would be the exact jupyterlab-link-share experience but with full JupyterHub permission controls)
- expiration, for short-lived one-time sharing session
- revoke sharing permissions by multiple keys, such as:
    - all shares for this server
    - a specific sharing link, and any access granted thereby
    - individual sharing permissions

**Comment by ktaletsk** [comment]
I support this change. Especially, as I mentioned in #3858, we are have to restart Hub to create new roles through configuration file. 
Please, let me know if I can help in any way

**Comment by minrk** [comment]
@ktaletsk thanks! Do you only use that for granting access, not general-purpose runtime-defined roles? If so, you'll be a perfect tester for the APIs as they develop.

**Comment by minrk** [comment]
https://github.com/jupyterhub/jupyterhub/pull/4594 is ready for testing and feedback
