### ISSUE TITLE
Provided metrics for server_spawn_duration_seconds are incorrect, maxing out at 2 minutes

### ISSUE THREAD

**Issue by shaneknapp** [jupyterhub/jupyterhub#4351]
### Bug description

the current grafana dashboard view for [server startup time](https://github.com/jupyterhub/grafana-dashboards/blob/main/dashboards/jupyterhub.jsonnet#L242) shows the max start up time to be 2m.

this is absolutely not true.  :)

we've had reports of start times of 4-5m, but looking at our graphs, again:  two minutes, max!

i created a local issue w/some more context [here](https://github.com/berkeley-dsep-infra/datahub/issues/4237), and added a delay to server launch by hacking our `hub/values.yaml`.  that pr is here:  https://github.com/berkeley-dsep-infra/datahub/pull/4241

for my test, i set the delay to be 3m, pushed that config to one of our staging hubs and patiently waited.  after 3m, the server launched, but grafana (surprise surprise) showed that the 99th percentile of start time was only 2m!

![image](https://user-images.githubusercontent.com/1606572/218195077-78e66640-9258-49e2-8939-0b0a0ec1e81b.png)

this hub had no other users logged on at the time.

#### Expected behaviour

if server launches take longer than 2m, then i would expect to see that on the grafana panel.

#### Actual behaviour

omg!  all servers show a max of 2m for launch *no matter what*!

### How to reproduce

1. hack your kubespawner method `async def start(self)` and add  `await asyncio.sleep(180)`
2. launch a server on that hub
3. wait 3 minutes
4. check grafana

### Your personal set up

UC Berkeley datahub:  https://data.berkeley.edu/datahub
running on GCP/GKE
z2h installation
grafana dashboards from the jupyterhub repo
grafana v9.0.5
jupyterhub v3.1.0

pinging @yuvipanda as this was his baby, and i recently inherited it.  XD

**Comment by yuvipanda** [comment]
(And I moved this issue into the JupyterHub repo as i think that's the right place for it)

**Comment by shaneknapp** [comment]
https://github.com/jupyterhub/jupyterhub/pull/4352

**Comment by shaneknapp** [comment]
quick Q, @yuvipanda ...  any idea when this change will be released?  we're planning on upgrading our JH version over spring break and it'd be super to get this change live.  :)

thanks!
