### ISSUE TITLE
admin page shows stop/access links for stopped servers

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#4361]
It appears that JupyterHub has arrived to a faulty state about active servers in a jupyterhub 3.1.1 installation I manage (z2jh based, latest dev release of helm chart).

There may be a need to protect for this happening, and/or recovering from it happening. I hope this issue report can help as a clue to fixing a small bug that this is, as it doesn't seem to cause much issues.

Since the metrics gets it right, and the /hub/admin gets it wrong, it seems reasonable that JupyterHub could figure that the state is incosistent by itself.

### Logs from hub startup one day ago

```
[I 2023-02-19 22:52:56.478 JupyterHub app:2539] redacted-user-a still running
[I 2023-02-19 22:52:56.478 JupyterHub app:2539] redacted-user-b still running
[I 2023-02-19 22:52:56.479 JupyterHub app:2879] Initialized 2 spawners in 0.055 seconds
```

### Incorrect state reported

![image](https://user-images.githubusercontent.com/3837114/219983065-b21faaca-9a09-4062-aa3e-8eec2d8ac95f.png)

### Access server presents this

![image](https://user-images.githubusercontent.com/3837114/219983309-6449fd49-4e92-44d5-886e-70f0be371f50.png)

### Metrics of `jupyterhub_running_servers` is correct

```
# HELP jupyterhub_running_servers the number of user servers currently running
# TYPE jupyterhub_running_servers gauge
jupyterhub_running_servers 2.0
```

### Starting server works

![image](https://user-images.githubusercontent.com/3837114/219983503-9240ec3b-49fd-409b-a7ba-15a955251686.png)

### Stopping started server works

![image](https://user-images.githubusercontent.com/3837114/219983542-13ec0451-e770-4d66-8996-b9d9c220189f.png)

**Comment by minrk** [comment]
Thanks for reporting! I'm not quite sure what state is inconsistent from the report so far. Can you be more specific about what you expect to see and what you see instead? Is it the last_activity time in the admin panel? Or is the server not running when it claims to be running?

**Comment by consideRatio** [comment]
@minrk there wasn't a server running for `@GeorgianaElena` (who also is reported last seen months ago) - there was no such pod, the metrics reports 2 users, the hub logs reported two running users, but the admin UI presented 3 servers to be started.

**Comment by minrk** [comment]
Thanks for clarifying! That tells me the condition for which buttons to show isn't correct, and indeed it wasn't! #4365 should fix it.
