### ISSUE TITLE
jupyterhub fails after restarting configurable-http-proxy

### ISSUE THREAD

**Issue by Frank-Steiner** [jupyterhub/jupyterhub#4369]
### Bug description
We've setup chp as separate proxy according to https://jupyterhub.readthedocs.io/en/stable/reference/separate-proxy.html

That works, users can connect and start their kernels etc. But when we restart the proxy, jupyterhub starts logging these 302/404 messages over and over again:
```
Feb 22 12:08:54 abel configurable-http-proxy[6717]: 12:08:54.412 [ConfigProxy] warn: Terminated
Feb 22 12:08:54 abel configurable-http-proxy[7974]: 12:08:54.601 [ConfigProxy] info: Adding route / -> http://localhost:8081
Feb 22 12:08:54 abel configurable-http-proxy[7974]: 12:08:54.606 [ConfigProxy] info: Proxying http://*:8790 to http://localhost:8081
Feb 22 12:08:54 abel configurable-http-proxy[7974]: 12:08:54.606 [ConfigProxy] info: Proxy API at http://127.0.0.1:8791/api/routes
Feb 22 12:08:54 abel configurable-http-proxy[7974]: 12:08:54.606 [ConfigProxy] info: Writing pid 7974 to /run/chp/chp.pid
Feb 22 12:08:54 abel configurable-http-proxy[7974]: 12:08:54.608 [ConfigProxy] info: Route added / -> http://localhost:8081

Feb 22 12:08:57 abel start_jhub[7862]: [I 2023-02-22 12:08:57.553 JupyterHub log:186] 302 GET /user/tester/api/kernels/02cce631-2ade-4b6d-a9ba-955f0f3ece9a/channels?session_id=f77768fe-50b4-43be-bac4-175b6b2792b1 -> /hub/user/tester/api/kernels/02cce631-2ade-4b6d-a9ba-955f0f3ece9a/channels?session_id=f77768fe-50b4-43be-bac4-175b6b2792b1 (@2001:...) 0.74ms
Feb 22 12:08:57 abel start_jhub[7862]: [I 2023-02-22 12:08:57.589 JupyterHub log:186] 302 GET /user/tester/api/kernels/02cce631-2ade-4b6d-a9ba-955f0f3ece9a?1677064137567 -> /hub/user/tester/api/kernels/02cce631-2ade-4b6d-a9ba-955f0f3ece9a?1677064137567 (@2001:...) 0.57ms
Feb 22 12:08:57 abel start_jhub[7862]: [W 2023-02-22 12:08:57.629 JupyterHub web:1796] 404 GET /hub/user/tester/api/kernels/02cce631-2ade-4b6d-a9ba-955f0f3ece9a?1677064137567 (2001:...: No access to resources or resources not found
Feb 22 12:08:57 abel start_jhub[7862]: [W 2023-02-22 12:08:57.653 JupyterHub log:186] 404 GET /hub/user/tester/api/kernels/02cce631-2ade-4b6d-a9ba-955f0f3ece9a?1677064137567 (tester@2001:...) 34.49ms
...
```
In the browser window, several errors occur, sometimes "405 not allowed" when trying to spawn a new kernel, or 'Directory not found: ""' etc.

The only way to recover is to restart the jupyterhub process, too.

Is that how it should be? Why can't jupyterhub access the running singleuser processes without being restarted itself?

chp is running as
```
configurable-http-proxy --pid-file /run/chp/chp.pid --ip  --port 8790 --api-ip 127.0.0.1 --api-port 8791 --default-target http://localhost:8081 --error-target http://localhost:8081/hub/error
```
cu,
Frank

### Your personal set up

 - OS: SuSE Linux Enterprise 15 SP4
 
 - Version(s):
 
jupyterhub 3.1.1, configurable-http-proxy 4.5.4

```
# jupyterhub_config.py
c.Spawner.default_url = '/lab'
c.JupyterHub.cleanup_servers = False
c.ConfigurableHTTPProxy.should_start = False
c.JupyterHub.cookie_secret_file = '/etc/jhub/jupyterhub_cookie_secret'
c.ConfigurableHTTPProxy.api_url = 'http://localhost:8791'
c.JupyterHub.pid_file = '/run/jhub/jhub.pid'
c.JupyterHub.spawner_class = 'sudospawner.SudoSpawner'
c.SudoSpawner.sudospawner_path = '/opt/jhub/bin/sudospawner'
c.JupyterHub.db_url = 'mysql+mysqlconnector://{}:{}@{}:{}/{}{}'.format("jhub","<pw>","<server>","<port>","jhub","")
c.JupyterHub.db_kwargs = {"pool_recycle":300}
```

**Comment by minrk** [comment]
When CHP restarts without JupyterHub noticing, it takes a finite amount of time to rebuild the routing table. This is currently governed by `c.JupyterHub.last_activity_interval`. You can force a re-sync with a request to `POST /hub/api/proxy`.

**Comment by Frank-Steiner** [comment]
Yes, executing `curl -X POST -H "Authorization: token xxx" "http://127.0.0.1:8081/hub/api/proxy"` indeed helps, thanks a lot!
Our first fix was to bind our .service files for jhub and chp so that restarting/starting/stopping would restart/start/stop jhub, too. I wonder if there is any drawback to that solution, because if chp doesn't run there seems to be no need for jhub to run as it can't be reached by users anyway (the spawned singleuser servers continue running).
Is it ok to (re)start/stop jhub together with chp or should we avoid that and use the POST solution instead?
Thanks!

**Comment by minrk** [comment]
I think it's okay to restart the Hub if the proxy restarts. You don't want to restart the proxy when the Hub restarts, because that disrupts users. The proxy in general shouldn't need to restart often.

**Comment by Frank-Steiner** [comment]
Thanks a lot!
