### ISSUE TITLE
Redirect when idle session is logged out

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/jupyterhub#437]
We are seeing the hub log errors approximately every two minutes:
```
22:44:16.377 - error: [ConfigProxy] 503 GET /user/user1/api/contents/subdir1/untitled.ipynb?content=0&_=1455920914722
22:44:16.426 - error: [ConfigProxy] 503 PUT /user/user1/api/contents/subdir1/untitled.ipynb
22:46:16.243 - error: [ConfigProxy] 503 GET /user/user1/api/contents/subdir1/untitled.ipynb?content=0&_=1455920914723
22:46:16.314 - error: [ConfigProxy] 503 PUT /user/user1/api/contents/subdir1/untitled.ipynb
22:48:16.241 - error: [ConfigProxy] 503 GET /user/user1/api/contents/subdir1/untitled.ipynb?content=0&_=1455920914724
22:48:16.320 - error: [ConfigProxy] 503 PUT /user/user1/api/contents/subdir1/untitled.ipynb
22:50:16.285 - error: [ConfigProxy] 503 GET /user/user1/api/contents/subdir1/untitled.ipynb?content=0&_=1455920914725
22:50:16.328 - error: [ConfigProxy] 503 PUT /user/user1/api/contents/subdir1/untitled.ipynb
22:52:16.233 - error: [ConfigProxy] 503 GET /user/user1/api/contents/subdir1/untitled.ipynb?content=0&_=1455920914726
22:52:16.296 - error: [ConfigProxy] 503 PUT /user/user1/api/contents/subdir1/untitled.ipynb
22:54:16.249 - error: [ConfigProxy] 503 GET /user/user1/api/contents/subdir1/untitled.ipynb?content=0&_=1455920914727
22:54:16.317 - error: [ConfigProxy] 503 PUT /user/user1/api/contents/subdir1/untitled.ipynb
22:56:16.231 - error: [ConfigProxy] 503 GET /user/user1/api/contents/subdir1/untitled.ipynb?content=0&_=1455920914728
22:56:16.276 - error: [ConfigProxy] 503 PUT /user/user1/api/contents/subdir1/untitled.ipynb
22:58:16.221 - error: [ConfigProxy] 503 GET /user/user1/api/contents/subdir1/untitled.ipynb?content=0&_=1455920914729
22:58:16.283 - error: [ConfigProxy] 503 PUT /user/user1/api/contents/subdir1/untitled.ipynb
23:00:16.225 - error: [ConfigProxy] 503 GET /user/user1/api/contents/subdir1/untitled.ipynb?content=0&_=1455920914730
23:00:16.298 - error: [ConfigProxy] 503 PUT /user/user1/api/contents/subdir1/untitled.ipynb
23:08:21.843 - error: [ConfigProxy] 503 GET /user/user1/api/contents/subdir1/untitled.ipynb?content=0&_=1455920914732
23:08:21.911 - error: [ConfigProxy] 503 PUT /user/user1/api/contents/subdir1/untitled.ipynb
23:10:21.812 - error: [ConfigProxy] 503 GET /user/user1/api/contents/subdir1/untitled.ipynb?content=0&_=1455920914733
23:10:21.883 - error: [ConfigProxy] 503 PUT /user/user1/api/contents/subdir1/untitled.ipynb
23:12:22.179 - error: [ConfigProxy] 503 GET /user/user1/api/contents/subdir1/untitled.ipynb?content=0&_=1455920914734
23:12:22.228 - error: [ConfigProxy] 503 PUT /user/user1/api/contents/subdir1/untitled.ipynb
23:14:21.860 - error: [ConfigProxy] 503 GET /user/user1/api/contents/subdir1/untitled.ipynb?content=0&_=1455920914735
23:14:21.928 - error: [ConfigProxy] 503 PUT /user/user1/api/contents/subdir1/untitled.ipynb
```

She has a container_id in her state but no server, and her container is not running.
```
>>> for user in db.query(User).filter(User.name == 'user1'):
...     print(user, user.server, user._server_id, user.state)
...
<User(user1 [unconfigured])> None None {'user_id': 1213, 'container_id': 'b7643974e8517da6f2b276b65d34cb5d562d9243cac52775ee9e30ee197644f2'}
```

I suspect that she has an idle browser somewhere and that it is trying to access her notebook even though her server was stopped a while ago. Would it be appropriate to have the hub redirect to a "you have no active server" page under such conditions?

**Comment by rgbkrk** [comment]
We run into the same thing on tmpnb, from people with tabs open on desktops and in mobile. Certainly need a way to redirect somewhere.

**Comment by minrk** [comment]
There is definitely a bug here, because CHP shouldn't have a route to a non-running server. Either

- The Hub never noticed that the server stopped, or
- The Hub failed to remove it from the proxy for some reason.

Since the database suggests that the user's server isn't running, it would seem to be the latter.

The Hub does already have a periodic check on the proxy to ensure that all running users have their routes set up. It does *not* have a check for the inverse: that stopped users do not have a route to their nonexistent server. While I could add that and it would eventually fix this error, it would hide whatever bug is happening here.

@ryanlovett sorry to keep asking for your logs, but could I get a copy of them to sift through? I'll be looking for what happened around the time when the user's server stopped (how the Hub noticed, if it did, and any errors, etc.).

@rgbkrk tmpnb could do what JupyterHub *should* be doing, and remove routes to stopped servers. Then the default route could handle the request and show an error page of some sort.

**Comment by rgbkrk** [comment]
That's our current behavior iirc. My statement was more about the interesting things you see from devices, unbeknownst to users.

**Comment by ryanlovett** [comment]
@minrk Its no trouble at all to send you our logs. Thanks for taking a look. Since they're student accounts I don't want to upload to github though. I'll send via email, but let me know if you prefer another way.

**Comment by willingc** [comment]
@ryanlovett 

Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
