### ISSUE TITLE
(Question) How do I make an account created in a specific group

### ISSUE THREAD

**Issue by kimkihoon0515** [jupyterhub/jupyterhub#4372]
When you create an account or log in, you are added to a group called local. Can you change this to the 1337 group?

**Comment by minrk** [comment]
What Authenticator are you using? If it's the default PAMAuthenticator, you can set the [add_user_cmd](https://jupyterhub.readthedocs.io/en/stable/api/auth.html#jupyterhub.auth.LocalAuthenticator.add_user_cmd) to be whatever add-user command you want to use to create your users.

**Comment by kimkihoon0515** [comment]
@minrk Solved the problem thx anyways!
