### ISSUE TITLE
How to increase the Number of pySpark Executors on YARN

### ISSUE THREAD

**Issue by afritzler** [jupyterhub/jupyterhub#438]
Hi,

I installed JupyterHub and configured a kernel to spawn a pySpark instance on my YARN cluster (running HDP 2.3).

My `~/.ipython/kernels/pyspark/kernel.json` looks like this:
```
{
 "display_name": "pySpark",
 "language": "python",
 "argv": [
  "/opt/anaconda/bin/python2",
  "-m",
  "IPython.kernel",
  "-f",
  "{connection_file}"
 ],
 "env": {
  "HADOOP_CONF_DIR": "/etc/hadoop/conf",
  "SPARK_HOME": "/usr/hdp/current/spark-client",
  "PYTHONPATH": "/usr/hdp/current/spark-client/python/:/usr/hdp/current/spark-client/python/lib/py4j-0.8.2.1-src.zip",
  "PYTHONSTARTUP": "/usr/hdp/current/spark-client/python/pyspark/shell.py",
  "PYSPARK_SUBMIT_ARGS": "pyspark --master yarn-client --num-executors 5 --executor-memory 10g --executor-cores 5"

 }
}
```
Even though I tried to create 5 executors (`--num-executors 5`) I only ended up with 2! What am I missing here?

Running
```
pyspark --master yarn-client --num-executors 5 --executor-memory 10g --executor-cores 5
```
from the shell does the trick. However the `num-executor` parameter doesn't seem get passed when I spawn it from Jupyter.

Thanks,
Andreas

**Comment by chicagobuss** [comment]
I'm having the exact same problem but in reverse - my notebook kernels are taking all available cores regardless of what I put in the pyspark_submit_args.. meaning I can't run any other jobs while a notebook is running!

Here's my kernel.json file:
```
{
 "display_name": "pySpark 2-cores (Spark 1.6.0)",
 "language": "python",
 "argv": [
  "/bin/python2",
  "-m",
  "IPython.kernel",
  "-f",
  "{connection_file}"
 ],
 "env": {
  "SPARK_HOME": "/usr/lib/spark",
  "PYTHONPATH": "/usr/lib/spark/python/:/usr/lib/spark/python/lib/py4j-0.9-src.zip",
  "PYTHONSTARTUP": "/usr/lib/spark/python/pyspark/shell.py",
  "PYSPARK_SUBMIT_ARGS": "--executor-cores 2 --num-executors 1 --master spark://spark-master-1:7077,spark-master-2:7077 pyspark-shell"
 }
}
```

**Comment by afritzler** [comment]
I was kind of successful: setting the cores and executor setting globally in the `spark-defaults.conf` did the trick. However, that is not a scalable solution moving forward, since I want the user to decide how many resources they need. (and not set them upfront globally via the spark-defaults)

**Comment by minrk** [comment]
I'm guessing the PYSPARK_SUBMIT_ARGS env isn't taking effect properly. I'm not sure exactly what code is meant to be affected by that env, though.

**Comment by pthongtra** [comment]
How to set number of executors, number of cores per notebook? Is it possible?

**Comment by tartavull** [comment]
+1

**Comment by kitsirota** [comment]
+1 I am really struggling with this also.  For some reason our environment spawns 120 executors for every user.   It would be great if users could specify how many executors they needed on a per-notebook-basis.

**Comment by fazil-osman** [comment]
Ran into this issue with my notebooks on Cloudera. After banging my head a few times I eventually found the following solution: 

-> pyspark --total-executor-cores 2 --executor-memory 1G

My problem was initially that all 24x cores were allocated to a single session leaving nothing free to additional running notebooks. I know its not exactly what y'all are looking for but thought it may help.

**Comment by ATidmore** [comment]
@fazil-osman setting "total-executor-cores" is an interesting approach. I have an Azure HDI Spark cluster with 190 GB of total memory. If I look at the current YARN utlization, there are a few things running but plenty of memory and vCores remaining. No matter what I set "total-executor-cores" to (2,4,6..) I get an error that "not enough memory is available to create the Spark context." 

I'm using Jupyter but using "%%config" I should be able to pass through property changes like you have from the CLI.
