### ISSUE TITLE
How can I switch the default singleuser application to notebook, not lab?

### ISSUE THREAD

**Issue by huleiyu** [jupyterhub/jupyterhub#4389]
How can I switch the default singleuser application to notebook, not lab?

**Comment by minrk** [comment]
You can set:

```python
c.Spawner.environment.update({
  "JUPYTERHUB_SINGLEUSER_APP": "notebook.notebookapp.NotebookApp",
})
```

More info [in the docs](https://jupyterhub.readthedocs.io/en/3.1.1/reference/config-user-env.html#switching-back-to-the-classic-notebook).
