### ISSUE TITLE
3.1.1 -> 4.0: upgrade-db just reports "run jupyterhub upgrade-db" again and again

### ISSUE THREAD

**Issue by Frank-Steiner** [jupyterhub/jupyterhub#4436]
### Bug description
After updating from 3.1.1 to 4.0.0 I get (as expected) the message:
```
Found database schema version 651f5419b74d != 0eee8c825d24. Backup your database and run `jupyterhub upgrade-db` to upgrade to the latest schema.
```
So I do that, but the result is just telling the me exact same message again:
```
abel:/opt/jhub # bin/jupyterhub --pid-file /tmp/jhub.pid  --config /etc/jhub/jupyterhub_config.py upgrade-db
Found database schema version 651f5419b74d != 0eee8c825d24. Backup your database and run "jupyterhub upgrade-db" to upgrade to the latest schema.
```

The db_url in  /etc/jhub/jupyterhub_config.py  is this (values masked in <>):
```
abel:/opt/jhub # grep db_url /etc/jhub/jupyterhub_config.py
c.JupyterHub.db_url = 'mysql+mysqlconnector://{}:{}@{}:{}/{}{}'.format("<username>","<pw>","<servername>","<port>","<dbname>","")
```
So I'm a little bit lost... Are there additional steps for upgrading the db from 3.1.1 to 4.0.0? The changelog doesn't mention anything...

### Your personal set up

 - OS: SuSE Linux Enterprise 15 SP4
 - Version(s): jupyterhub 4.0.0, Python 3.10.10, mariadb 10.6.12
 

cu,
Frank

**Comment by minrk** [comment]
Sorry for leaving this hanging, but the subcommand argument should come first, or it won't be recognized:


```
jupyterhub upgrade-db --config /etc/jhub/jupyterhub_config.py
```

**Comment by Frank-Steiner** [comment]
Yes, that worked, many thanks :)

**Comment by X11tpro** [comment]
Great lord
