### ISSUE TITLE
Jupyterhub always defaulting to the home directory inspite of defining in the jupyterhub_config 

### ISSUE THREAD

**Issue by eldhosemjoy** [jupyterhub/jupyterhub#4459]
I am trying to make the Jupyterlab directory to /help.  I have tried all the below options.  No luck.  The are defaulting to my /home/user directory despite giving various combinations of these.

c.Spawner.default_url = '/help'
c.Spawner.notebook_dir = '/help'

# c.LabApp.root_dir = '/storage_disk/'

# c.LabApp.app_dir = '/storage_disk/'

# c.NotebookApp.notebook_dir = '/help/'
# c.ServerApp.notebook_dir = '/help/'

The version for hub and lab is 4.0.0

**Comment by manics** [comment]
The singleuser config is separate from the hub config. If you're still stuck please post on the [Jupyter community forum](https://discourse.jupyter.org/), and include full details of your deployment.
