### ISSUE TITLE
Add some community deployment examples to documentation

### ISSUE THREAD

**Issue by willingc** [jupyterhub/jupyterhub#446]
Let's add a section to the documentation about Deployments - Community examples.

Based on a gitter post by @minrk:

>You can check out some existing JupyterHub ansible deployments:
https://github.com/compmodels/jupyterhub-deploy
(Docker Hub + Docker Swarm for ~200 users)
A variant of that: https://github.com/data-8/jupyterhub-deploy
A significantly different deployment: (local users, GitHub auth, no docker) https://github.com/calpolydatascience/jupyterhub-deploy-data301

**Comment by willingc** [comment]
Another good example at wikimedia from @yuvipanda:

https://github.com/yuvipanda/paws

**Comment by minrk** [comment]
:+1: great idea.

**Comment by willingc** [comment]
Since we have reference deployments now, I'm going to go ahead and close this.
