### ISSUE TITLE
Jupyterhub file browser folders disappear constantly

### ISSUE THREAD

**Issue by Helderterrein** [jupyterhub/jupyterhub#4462]
### Bug description

JupyterHub has been installed on ubuntu 22.04 and connected to the active directory with sssd. A user account will automatically be created whena windows user logs in onto the jupyterhub. A symbolic link will automatically be made from the user home folder tot the mounted volume. The mounted volume is a CIFS share. Now when a user logins in on the JupyterHub server everything is fine and usable, except for the 'visual part' of the folder structure that will occasionally disappear, only when running `ls -l` it appears again.

#### Expected behaviour

It is expected that the file browser keeps the projects share visually available.

#### Actual behaviour

Only top-level maps are visually available when a underlying file/folder is used.

### How to reproduce

1. create a symbolic link between home folder of a user and the /mnt/name
2. launch jupyterhub server from url
3. If the server has restarted recently or ls -l is run you will see the folders in the left pane
4. After approx. 30 minutes the folders will dissapear

### Your personal set up

Operating System and version: Linux Ubuntu 22.04
Browser and version: 113.0.5672.127
JupyterLab version: 3.4.7
Windows server version: 2019 Distributed file system/ CIFS 2.0 share
### Configuration for spawner and authenticator:
```
Spawner:
import os
import pwd
import shutil
def create_dir_hook(spawner):
    username = spawner.user.name # get the username
    username1 = username.replace(".com", ".local")
    home_path = os.path.join('/home', username1)
    projecten = "projecten"
    dir = os.path.join(home_path,projecten)
    dst = "/mnt/projecten"
    if not os.path.exists(home_path):
        os.umask(0)
        os.mkdir(home_path, 0o777)
        pass
# attach the hook function to the spawner
c.Spawner.pre_spawn_hook = create_dir_hook

Authenticator: Default (PAM) with SSSD

**Comment by consideRatio** [comment]
This doesn't sound like a jupyterhub bug in behavior. What you describe is something observed in JupyterLab running in a user server started by JupyterHub. So if you see issues via `/user/<your username>` rather than `/hub/<something>`, its likeley related to your user servers software rather than JupyterHub's software.
