### ISSUE TITLE
A configured Authenticator.allowed_users set is appended with users in the databases - make it opt-in?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#4483]
There is a default behavior when `Authenticator.allowed_users` is configured truthy that I suggest we change - the behavior of adding all users in the jupyterhub user database to that list!

Currently, if `allowed_users` is truthy, all existing users of the database is appended to that list during startup (see [`JupyterHub.init_users`](https://github.com/jupyterhub/jupyterhub/blob/4.0.0/jupyterhub/app.py#L1928-L2005) and [`Authenticator.add_user`](https://github.com/jupyterhub/jupyterhub/blob/4.0.0/jupyterhub/auth.py#L625-L648)). This makes all users in the jupyterhub database is allowed when `allowed_users` is configured truthy.

Consider for example a jupyterhub admin starting up a jupyterhub, then making a few users test it by linking to it, and then later declaring `Authenticator.allowed_users`. Would that admin realize that they would need to inspect the jupyterhub database and remove users added during the period before allowed_users was set? Would that admin realize that reducing the list of `allowed_users` wouldn't restrict access later? I don't think so. This is why I think its critical that we introduce a toggle for this behavior, and that we allow users to retain it as it can also be quite a relevant functionality.

I figure this could be configured in the Authenticator base class, influencing the behavior of `Authenticator.add_user` function.

An initial name suggestion for such config option could be `Authenticator.allow_existing_users`. Further, I figure we should let it accept `None`, `False`, and `True`, where `None` preserves the existing behavior, and `False` never adds existing users, and `True` always adds no matter if `allowed_users` is set or not.

### Action points

- Comment if you think this makes sense
- Comment if you have ideas on where and how to configure this

**Comment by manics** [comment]
It's potentially confusing, but I think the current behaviour is required to support adding users via the JupyterHub API, otherwise those users would be lost on every hub restart. Adding this new switch therefore implies those user API methods should be disabled to avoid even more confusion.

I think the documentation should be improved (and maybe a warning in the logs?) but my initial thoughts are I don't think the complexity introduced by a new option is justified.

**Comment by consideRatio** [comment]
> I think the current behaviour is required to support adding users via the JupyterHub API, otherwise those users would be lost on every hub restart. 

If you add users via REST API, then they are created and added to the database, and then `Authenticator.add_user` is called just like it has been when `JupyterHub.init_users` is called during jupyterhub startup and it finds users in `allowed_users` not already added to the database.

> Adding this new switch therefore implies those user API methods should be disabled to avoid even more confusion.

If you want to use the REST API to create a user and make that user get access as part of it, then you must have configured `Authenticator.allowed_users` truthy, otherwise existing users in the database won't be added to the allowed_user set! Should we disable those REST APIs to create users if `Authenticator.allowed_users` isn't configured truthy as well?

I suggest we make the logic of adding users something that can be made explicitly via configuration instead of implicit via `allowed_users` contained either 0 or 1+ users. So practically, defining `Authenticator.allow_existing_users`, where we initially let it take on the value `None` representing the current behavior of letting that be decided by if `allowed_users` is truthy or not.

### Practically

Current `Authenticator.add_user` logic

https://github.com/jupyterhub/jupyterhub/blob/10e7ab96e5f09db0731e535b22984e2743846fa2/jupyterhub/auth.py#L647-L648

New idea of `Authenticator.add_user` logic

```python
    if (self.allow_existing_users is None and self.allowed_users) or self.allow_existing_users:
        self.allowed_users.add(user.name)
```

**Comment by consideRatio** [comment]
@manics I would say that I haven't understood the details of this myself until yesterday via in depth code inspection focused on understanding this logic (#4461). Even if the docs were great, I don't think it would help us as much as a more explicit config option could.

I think docs are mainly read when you are doing something for the first time or have reason to look up something because it didn't work as you expected. In this case, that may be when you realize you've had unauthrozed access, for example because you initially didn't configure allowed_users, but then did, and existing users also gained access and those included users that showed up while no access control was in place etc.

**Comment by minrk** [comment]
The change of state from both config and API is a huge pain, and why roles still don't have a REST API, specifically so this issue can't come up.

With the addition of roles, it also can now make sense for a user to be in the database with no permissions, which couldn't happen before (a user in the database was necessarily allowed, though the _Authenticator_ could prevent subsequent logins). There are 

I think `allow_existing_users` as opt-in (possibly deprecating leaving it unspecified so we can make it opt-out in the future) sounds pretty good for the simple case. Where it gets complicated is cases like https://github.com/jupyterhub/oauthenticator/pull/546 where `allowed_users` is only a _subset_ of the allowed users, so `allow_existing_users = False` could end up revoking access from all users explicitly allowed via group if we're not careful. We have to think through all the combinations of:

- added to allowed_users
- removed from allowed_users
- added via API
- removed via API
- allowed via group/org/etc.
- allowed via group previously but not in the group anymore

and consider what folks might want and how best to express that in configuration.

**Comment by consideRatio** [comment]
> With the addition of roles, it also can now make sense for a user to be in the database with no permissions

I've considered this also. Would it be a problem to require that kind of no-permission user to register as a service instead?

> Where it gets complicated is cases like [jupyterhub/oauthenticator#546](https://github.com/jupyterhub/oauthenticator/pull/546) where `allowed_users` is only a _subset_ of the allowed users, so `allow_existing_users = False` could end up revoking access from all users explicitly allowed via group if we're not careful.

I don't follow what you mean so well above yet. I'm thinking that configuring `allow_existing_users = False` correctly should revoke the ability to login for users not explicitly allowed via config such as `allowed_users` or `allowed_organizations`.

### Related but off topic

It would be great if we could refactor so that `allowed_users` wasn't maniplated to add database users. The strategy adopted in [oauthenticator #594](https://github.com/jupyterhub/oauthenticator/pull/594/files#diff-92f281a58f69a09cf3c9eae4a65ddcb625276b28f8afb30cb876259a0a19b27aR140-R170) overriding `check_allowed` makes us able to allow users in for example `allowed_organizations` without adding them to `allowed_users`, while the strategy adopted in [oauthenticator #546](https://github.com/jupyterhub/oauthenticator/pull/546/files) needs to do so because otherwise the default `allowed_users` would reject group users.

For me, it was a major aha moment to realize that `Authenticator.add_user` was influencing `allowed_users`, but only when `allowed_users` contained one or more users. I have the expectation overall that user config isn't manipulated after its initially set and validated.

**Comment by consideRatio** [comment]
## Research summary - use of `Authenticator.add_user`

I wanted to understand how `add_user` is used in detail, and have concluded its only called for existing users on startup when new users are created.

<details>

### Helper functions

These functions are used by other functions to call `add_user`.

- `JupyterHub._get_or_create_user` calls add_user if the user isn't in the database
- `BaseHandler.auth_to_user` calls add_user if the user isn't in the database

### JupyterHub initialization

- `init_users` calls `add_user` for each user in the database
- `init_groups` calls `add_user` for each created user by being referenced by `load_groups` (via `_get_or_create_user`)
- `init_role_assignment` calls `add_user` for each user created by being referenced by `load_roles` (via `_get_or_create_user`)

### REST API

- `/api/users/` and `/api/users/<username>` accepts POST requests to create new users, `add_user` is called for each user created

### UI

- `BaseHandler.login_user` calls `add_user` (via `auth_to_user`)
- `BaseHandler.refresh_auth` calls `add_user` (via `auth_to_user`)

</details>

**Comment by consideRatio** [comment]
If possible I'd love to chat about this tricky topic! You added the label breaking, but I'm currently thinking that there is a way to do something in a non-breaking way. I'll specify my config idea below for reference, and to help me review my own belief that it wouldn't be breaking.

## New config proposal

A new Authenticator config is added, my placeholder name of this config is `allow_existing_users`.

It should always resolve to True or False, but accepts a "if-allowed-users-is-truthy" which validates to True if `allowed_users` is truthy and otherwise to False. This would then represent the current behavior, and should be the default.

The impact of this config would be to adjust `Authenticator.add_user` to add to `allowed_users` if its True or false, instead of doing it based on checking if `allowed_users` is truthy.

## Discussion

### `allow_existing_user` set to "if-allowed-users-is-truthy"

I think this preserves existing behavior exactly, so let's consider if its JupyterHub would function as expected if its explicitly configured to True or False instead

### `allow_existing_user` set to True or False

Let's consider setting `allow_existing_user = False` with `allowed_users = `{"erik"}`, and lets consider setting `allow_existing_users = True` with `allowed_users = {}` - in these two situations we get new behavior. In the first situation, the set of `allowed_users` doesn't grow from `{"erik"}` during startup and when users are created to include all existing users. In the second situation, the set of `allowed_users` grows from `{}` during startup and when users are created to include all existing users.

Since `allowed_users` is referenced from a few places, lets consider how that logic is impacted.

- [`init_users`](https://github.com/jupyterhub/jupyterhub/blob/161cdcd7e711845d2c4c157c150f251261a5f925/jupyterhub/app.py#L1974-L2040) - OK I think
- [`init_role_assignment`](https://github.com/jupyterhub/jupyterhub/blob/161cdcd7e711845d2c4c157c150f251261a5f925/jupyterhub/app.py#L2252-L2260) - OK I think, but is the existing behavior OK?

  Here users found in `allowed_users`, which may or may not include all existing users, are granted the role `user`. I don't understand why that should be done for `allowed_users` specifically. Also, if a user is created via `load_groups`, `load_roles`, or via the REST API, they won't be granted that role directly, but after jupyterhub restarts if existing users are added to the `allowed_users` set, which depends if its initially set truthy or not.

  https://github.com/jupyterhub/jupyterhub/blob/161cdcd7e711845d2c4c157c150f251261a5f925/jupyterhub/app.py#L2252-L2260
- [`Authenticator.check_allowed`](https://github.com/jupyterhub/jupyterhub/blob/161cdcd7e711845d2c4c157c150f251261a5f925/jupyterhub/auth.py#L474-L491) - OK I think
- [`Authenticator.add_user`](https://github.com/jupyterhub/jupyterhub/blob/161cdcd7e711845d2c4c157c150f251261a5f925/jupyterhub/auth.py#L625-L648) - OK I think
- [`Authenticator.delete_user`](https://github.com/jupyterhub/jupyterhub/blob/161cdcd7e711845d2c4c157c150f251261a5f925/jupyterhub/auth.py#L650-L659) - OK I think, but is the existing behavior OK?

## My takeaway

- I think adding `allow_existing_users` to be a non-breaking change as long it defaults to True or False depending on if `allowed_users` is configured truthy or not.
- I'm considering if a new config like `allow_existing_users` should be split in two: `allow_users_when_they_are_created` and `allow_users_already_created_on_startup`. I suspect it could be relevant to distinguish those, but so far I'm not sure when so maybe not.

**Comment by minrk** [comment]
> I think adding allow_existing_users to be a non-breaking change as long it defaults to True or False depending on if allowed_users is configured truthy or not.

It's only non-breaking if `allow_existing_users` defaults to True. If it's False, this will revoke permission from users who previously had permission without opt-in configuration. It's a _small_ change (and a good one!), but a breaking one if this value can ever be False without user input specifically on this behavior.

**Comment by minrk** [comment]
Summarizing a bit from our discussion today before I log off, where I think you and I have been missing each other is I've been talking about a higher level "should this user be allowed" True/False, and I think you were talking about specifically "should this user be added to authenticator.allowed_users" which has the additional `True if allowed_users is truthy` state. I think the configuration will be clearest if we express configuration at the "should they be allowed" level, and we'll hash out the details of the best way to express and implement that intention in both oauthenticator which has other sources of 'allow' like teams, groups after we've described the configuration we want users to be able to express.

I think this may turn out to be a small breaking change in some cases in order to have fully consistent behavior for authenticator subclasses, but we'll see what we come up with (e.g. if allow_existing_users defaults to True in my definition, that could change the behavior of a user being removed from a group in oauthenticator - they may no longer lose their permission, depending on how we implement this).

**Comment by minrk** [comment]
> Are there any general high-level patterns we can define to prevent too much complexity as more of the configuration becomes modifiable at runtime?

I think the pattern in #4381 of prohibiting modifying things at runtime that are defined in config by explicitly tracking where they came from with a new column is a good one to follow, at least for roles and probably groups. That resolves the ambiguity because then we can know that whenever something is loaded from config it can _only_ be updated from config, there is no "this is different from config, possibly because of a runtime change". Will need to think carefully about users, but I think the proposal here addresses it for the most part.
