### ISSUE TITLE
'_xsrf' argument missing from POST while calling INFO - GET METHOD REST API

### ISSUE THREAD

**Issue by NISHANTSHRIVASTAV** [jupyterhub/jupyterhub#4488]
### Bug description

Hi Team, 

I have set up JupyterHub using the below latest _docker_ image command:

`docker run -p 8000:8000 -d --name jupyterhub jupyterhub/jupyterhub jupyterhub
`
While calling the get Info GET method API using the Postman tool getting the below error:

**API Endpoint**: http://localhost:8000/hub/api/info

**Error Response:** 

```
{
    "status": 403,
    "message": "'_xsrf' argument missing from POST"
} 
```

**Additional Logs:** 

2023-06-23 12:24:21 [W 2023-06-23 06:54:21.430 JupyterHub web:1869] 403 GET /hub/api/info (::ffff:172.17.0.1): '_xsrf' argument missing from POST

Can you please let me know which token is required here and how to call the other API in the case of GET and POST API methods?

Please let me know if you need more information.

**Comment by consideRatio** [comment]
Closing as a question rather than a bug, I'll respond in https://discourse.jupyter.org/t/xsrf-argument-missing-from-post-while-calling-info-get-method-rest-api/20083

**Comment by consideRatio** [comment]
Hmmm, reopening because I think one thing is off at least in jupyterhub's behavior.

Making a GET request shouldn't error with a message like `{"status": 403, "message": "'_xsrf' argument missing from POST"}`, but like `{"status": 403, "message": "'_xsrf' argument missing from query parameters"}` I think

**Comment by consideRatio** [comment]
> Can you please let me know which token is required here and how to call the other API in the case of GET and POST API methods?

When accessing the jupyterhub REST API, you need to authorize your requests. I think you need to use an API token passed in the header, like described in https://jupyterhub.readthedocs.io/en/stable/howto/rest.html.

**Comment by minrk** [comment]
#4489 should improve the error message in a few cases, most importantly the case here where a request is made without any credentials.
