### ISSUE TITLE
cull_idle_servers.py limited to 20 server spree

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/jupyterhub#449]
Our cull process was crashing until we caught the async client fetch call. It showed that the first 20 servers were culled successfully but the remaining batch would fail with HTTP 599.

Example:
`tornado.httpclient.HTTPError: HTTP 599: Timeout
[E 160301 23:42:19 concurrent:319] Future <tornado.concurrent.Future object at 0x7f99880c5048> exception was never retrieved: tornado.httpclient.HTTPError: HTTP 599: Timeout`

Traceback from the cull process:

```
Traceback (most recent call last):
 File "cull_idle_servers.py", line 76, in <module>
   loop.run_sync(cull)
 File "/usr/local/lib/python3.4/site-packages/tornado/ioloop.py", line 445, in run_sync
   return future_cell[0].result()
 File "/usr/local/lib/python3.4/site-packages/tornado/concurrent.py", line 215, in result
   raise_exc_info(self._exc_info)
 File "<string>", line 3, in raise_exc_info
 File "/usr/local/lib/python3.4/site-packages/tornado/gen.py", line 876, in run
   yielded = self.gen.throw(*exc_info)
 File "cull_idle_servers.py", line 59, in cull_idle
   yield f
 File "/usr/local/lib/python3.4/site-packages/tornado/gen.py", line 870, in run
   value = future.result()
 File "/usr/local/lib/python3.4/site-packages/tornado/concurrent.py", line 215, in result
   raise_exc_info(self._exc_info)
 File "<string>", line 3, in raise_exc_info
```

Patch to the culler:

```
--- cull_idle_servers.py.orig   2016-03-02 23:39:09.758545799 +0000
+++ cull_idle_servers.py    2016-03-02 23:41:13.506545799 +0000
@@ -56,8 +56,12 @@
             app_log.debug("Not culling %s (active since %s)", user['name'], last_activity)

     for (name, f) in futures:
-        yield f
-        app_log.debug("Finished culling %s", name)
+        try:
+            yield f
+        except:
+            app_log.info("Could not cull %s", name)
+        else:
+            app_log.info("Culled %s", name)

 if __name__ == '__main__':
     define('url', default='http://127.0.0.1:8081/hub', help="The JupyterHub API URL")
@@ -81,4 +85,4 @@
         loop.start()
     except KeyboardInterrupt:
         pass
```

After applying this we'd see the first 20 go through but the ones at the back would fail. At the next scheduled cull, the next 20 would be culled. And so on.

**Comment by minrk** [comment]
I'm guessing this is because of how long the docker/swarm spawners take to shutdown. We handle slow startup by responding with `202: Accepted`. Perhaps we should do the same for slow shutdown.

**Comment by ryanlovett** [comment]
It looks like slow shutdown already responds with 202, https://github.com/jupyter/jupyterhub/blob/master/jupyterhub/apihandlers/users.py#L187.

**Comment by minrk** [comment]
Oh, interesting. Then it's probably because docker serializes the stop calls - we start them all at once, starting all their timers, but docker actually starts them one after the other, so the delay gets stacked up and later shutdowns hit their timeouts. I'm not sure what the best way to get the right timeout behavior, since serializing the shutdowns is exactly what I want to avoid for cases that don't have a bottleneck like this. Perhaps a flag on the Spawner class that indicates whether it can perform concurrent operations would help.

**Comment by willingc** [comment]
I'm retagging this issue as an enhancement request.

**Comment by consideRatio** [comment]
Closing as outdated. This may still be relevant in https://github.com/jupyterhub/jupyterhub-idle-culler but as it is such and old issue I'll just go ahead and close it.
