### ISSUE TITLE
Expanding `server` role slightly

### ISSUE THREAD

**Issue by tuncbkose** [jupyterhub/jupyterhub#4517]
As far as I understand, the `server` role is allowed to "Post activity only", and the default `$JUPYTERHUB_API_TOKEN`s are given this role. I think it might be desirable for this role to be expanded to be able to read its own state, for example by adding the `read:servers!server` scope. Would there be any downsides to such a change?

My motivation for this is writing a JupyterLab extension that might want to query the API for server specific information like `started` and `last_activity`. It seems to me like the default API token should have sufficient permissions to do this, but I don't know what implications this might have.

Also, if there is a better mechanism to get this server information, please let me know.

**Comment by minrk** [comment]
It is definitely appropriate to grant the `server` role additional permissions if you want to deploy extensions that use permissions the default scopes don't allow.

Putting `read:servers!server=my/server` in that scope by default does seem reasonable, and I don't think there's any risk involved that I can think of.

**Comment by tuncbkose** [comment]
Thank you for the response!
