### ISSUE TITLE
Fix JUPYTERHUB_SINGLEUSER_APP after Notebook 7 release

### ISSUE THREAD

**Issue by mathbunnyru** [jupyterhub/jupyterhub#4518]
### Bug description

With `notebook 6.5.4` it was possible to specify JUPYTERHUB_SINGLEUSER_APP='notebook' to run `Jupyter Notebook` instead of `JupyterLab`.

#### Expected behaviour

Jupyter Notebook is run in singleuser

#### Actual behaviour

`jupyterhub-singleuser` fails

### How to reproduce

Working image: `jupyter/base-notebook:notebook-6.5.4`
Failing image: `jupyter/base-notebook:notebook-7.0.0`

1. Run image: `docker run -it --rm jupyter/base-notebook:notebook-7.0.0 bash`
2. Run: `JUPYTERHUB_SINGLEUSER_APP='notebook' JUPYTERHUB_SERVICE_URL="127.0.0.1" jupyterhub-singleuser`

JupyterHub is not running inside the image, but I don't think that's the problem.

Output with Jupyter Notebook 7:
```
Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 6, in <module>
    from jupyterhub.singleuser import main
  File "/opt/conda/lib/python3.11/site-packages/jupyterhub/singleuser/__init__.py", line 67, in <module>
    from .app import SingleUserNotebookApp, main
  File "/opt/conda/lib/python3.11/site-packages/jupyterhub/singleuser/app.py", line 31, in <module>
    App = import_item(JUPYTERHUB_SINGLEUSER_APP)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/traitlets/utils/importstring.py", line 30, in import_item
    module = __import__(package, fromlist=[obj])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'notebook.notebookapp'
```

Output with Jupyter Notebook 6:
```
[I 2023-07-25 20:59:48.574 SingleUserNotebookApp mixins:547] Starting jupyterhub single-user server version 4.0.1
[I 2023-07-25 20:59:48.574 SingleUserNotebookApp mixins:561] Extending notebook.notebookapp.NotebookApp from notebook 6.5.4
[W 2023-07-25 20:59:48.578 SingleUserNotebookApp configurable:200] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
JUPYTERHUB_API_TOKEN env is required to run jupyterhub-singleuser. Did you launch it manually?
```

### Your personal set up

 - OS:
 
 - Version(s):
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by mathbunnyru** [comment]
I've tried setting `export JUPYTERHUB_SINGLEUSER_APP='notebook.notebookapp.NotebookApp'` (as in [docs](https://jupyterhub.readthedocs.io/en/stable/howto/configuration/config-user-env.html#switching-back-to-the-classic-notebook)), the error stays the same (there is an internal map which allows to use short `notebook` when setting this env variable).

**Comment by manics** [comment]
https://github.com/jupyterhub/jupyterhub/blob/3fbdf02cc5c6574432dd28710ed2fc64b2353081/jupyterhub/singleuser/app.py#L17-L24

Do you know what the correct import is for notebook 7?

**Comment by mathbunnyru** [comment]
It seems to be `JUPYTERHUB_SINGLEUSER_APP='notebook.app.JupyterNotebookApp'`
Here is the source code:
https://github.com/jupyter/notebook/blob/main/notebook/app.py#L227

I tried to launch it. It fails with this error: `AttributeError: 'JupyterNotebookApp' object has no attribute 'login_handler_class'`.

An example of such a field in a `jupyter_server.serverapp.ServerApp`
https://github.com/jupyter-server/jupyter_server/blob/main/jupyter_server/serverapp.py#L1534

**Comment by manics** [comment]
@jtpio Is this something we need to fix in JupyterHub, notebook, or both?

**Comment by jtpio** [comment]
Normally Notebook 7 should work with `jupyter labhub` according to the discussion in https://github.com/jupyter/notebook/issues/6904.

Otherwise maybe the mapping should be `"notebook": "jupyter_server.serverapp.ServerApp"` since Notebook 7 is based on Jupyter Server?

**Comment by minrk** [comment]
notebook v7 is a jupyter-server ExtensionApp like JupyterLab, and not a server application anymore. To use notebook v7, the server app should be the default jupyter-server ServerApp, so the right value to use with v7 is `jupyter-server` (or the new `extension`), aka the default, the same as should be used with jupyterlab.

Essentially, the `notebook` value is only relevant for notebook <v7 and is effectively deprecated now that v7 is out, and the default (or opt-in to jupyter-server) is the only real valid value, including for notebook v7. The only config you need to use notebook v7 is:

```python
c.Spawner.default_url = "/tree/" # default to notebook URL
```

If there is anything to do in jupyterhub, it would probably be a better error (or warning) when requesting the classic notebook server when there is no classic notebook server app installed.

#4522 improves the error message, pointing to the correct configuration, and adds docs to the same effect.

**Comment by mathbunnyru** [comment]
Thank you @minrk!
I will add the link to JupyterHub docs pags in Docker Stacks, to make sure our users are aware how to change the defaults.
