### ISSUE TITLE
Behavior if server has stopped while hub was down (no Spawner.stop call)

### ISSUE THREAD

**Issue by kreuzert** [jupyterhub/jupyterhub#4519]
Hi everyone,

JupyterHub checks during the startup if a server is still running. If this is not the case, JupyterHub does not [call](https://github.com/jupyterhub/jupyterhub/blob/3fbdf02cc5c6574432dd28710ed2fc64b2353081/jupyterhub/app.py#L2607) `user.stop(name)` . The server will be set to `None` and removed from the database.  
  
This can cause problems, because `Spawner.post_stop_hook` will never be called in this scenario. One might want to use the configurable `post_stop_hook` as a custom cleanup function, to revert things done previously in `Spawner.pre_spawn_hook`. Or is there a better place to do some cleanup afterwards?  
  
An alternative would be to implement the cleanup in `Spawner.poll` (for `Spawner` subclasses), since this is the only function called during the startup check.

**Comment by minrk** [comment]
I'd need to check the documentation on stop to ensure we require it be able to be called for an already stopped server, but I think this is already the case, and we do call it when start has _failed_. I think calling stop and post-stop hooks in these situations is the right thing to do to be consistent.

**Comment by minrk** [comment]
#4562 should do it. We already make similar assumptions plenty of other places (e.g. calling `user.stop` after Spawners notify the Hub that they've exited on their own), so this should purely improve things. Thanks for catching this @kreuzert!

**Comment by kreuzert** [comment]
Thanks for the fix 👍
