### ISSUE TITLE
/hub/api/users?include_stopped_servers doesn't include ?include_stopped_servers in the next_url when paginating

### ISSUE THREAD

**Issue by jabbera** [jupyterhub/jupyterhub#4524]
### Bug description

/hub/api/users?include_stopped_servers doesn't include ?include_stopped_servers in the next_url when paginating. This means the first page has stopped servers, but no subsequent pages do. I'd assume that all query params aside from offset should be replicated to the next_url.

#### Expected behaviour

?include_stopped_servers should be in the pagination url

#### Actual behaviour

?include_stopped_servers is not in the url so only the first page has stopped servers

### How to reproduce

1. On 2 different users create 2 stopped named servers.
2. Make an API Request: /hub/api/users?include_stopped_servers&limit=1
3. Follow the pagination url: /hub/api/users?limit=1&offset=1
4. No servers are listed for second user

### Your personal set up

Zero 2 jupyterhub 2.0.

**Comment by manics** [comment]
You're using an old version of JupyterHub/Z2JH. Can you check if this bug is still present in the latest version of JupyterHub (4.0.1), which is included in Z2JH `3.0.0-beta.3` and later?
https://hub.jupyter.org/helm-chart/#development-releases-jupyterhub

**Comment by jabbera** [comment]
I'm waiting for the stable release of the chart. Will let you know when it comes out and I upgrade.

**Comment by jabbera** [comment]
@manics this is confirmed still a bug on 4.0.2 using the 3.0.2 helm chart.
