### ISSUE TITLE
Missing api endpoints

### ISSUE THREAD

**Issue by CarlosDominguezBecerril** [jupyterhub/jupyterhub#4527]
### Bug description

In my workplace we are currently using jupyterhub with k8s to assign servers to our employees. Unfortunately, looks like some api endpoints such as /api/me and /api/events/subscribe are missing and these are being used by jupyterlab.

Examples:
`Failed to load resource: the server responded with a status of 404 (Not Found) - api/me?1690792071338:1`

`WebSocket connection to 'ws://mycompanyurl/user/my-username/api/events/subscribe?token=tzARtKshtYpLPEboUBdyto4tulBVVE' failed: jlab_core.0faecc546c73b7263d33.js?v=0faecc546c73b7263d33:1`

(The websocket issue is because I'm getting a 404, I think.)

Note that if I use only jupyterlab  on my laptop (without jupyterhub) the api endpoints exist and work

#### Expected behaviour

The api endpoints should return the expected values according to the api behaviour

#### Actual behaviour

Getting 404, the endpoints don't exist.

### How to reproduce

1 - Create a new server using jupyterhub
2 - search for `myurl/user/my-username/api/me` and you get the 404

### Your personal set up

Currently I’m using jupyterhub==4.0.1 and for the single user servers I'm using jupyterhub==4.0.1, jupyterlab==4.0.3, jupyter-server==2.7.0 and jupyterlab-server==2.24.0 (we provide both user interfaces).

For the dependencies, I'm using the most recent ones except Notebook which is 6.5.3.

**Comment by minrk** [comment]
Clsoing this one in favor of duplicate support question [on the forum](https://discourse.jupyter.org/t/websocket-and-404-api-me-error-on-jupyterlab/20700)
