### ISSUE TITLE
Links to UC Berkeley Jupyter Course are broken

### ISSUE THREAD

**Issue by ParamThakkar123** [jupyterhub/jupyterhub#4540]
Here's the link for the course: 
https://bids.berkeley.edu/resources/videos/teaching-ipythonjupyter-notebooks-and-jupyterhub

**Comment by balajialg** [comment]
Hey @ParamThakkar123 Thanks for reporting this issue. Unfortunately, This is the wrong place to post this issue. You could send an email to bids@berkeley.edu and report this issue. (The link you shared is 7 years old)

**Comment by ParamThakkar123** [comment]
sorry @balajialg for reporting this issue at the wrong place. I honestly didn't know about this. Actually I noticed this issue when I started a pull request on this repository 2 days ago. My pull request check failed and it pointed to this link.
