### ISSUE TITLE
Environments/kernels are ignored with running !some_exe

### ISSUE THREAD

**Issue by eusebiu** [jupyterhub/jupyterhub#4547]
### Bug description

Running some_exe using !some_exe syntax is not considering the kernel associated with that session.

#### Expected behaviour

Running some_exe using !some_exe syntax must consider the kernel associated with that session and any tools, env variables that are present in that environment.

### How to reproduce

1. Open hub, login
2. Create a terminal session and create a python environment (with other version of python, e.g. 3.7)
3. Install that environment in hub
4. Create a notebook and change the kernel in for the notebook to use that environment
5. Execute: ```!which python``` in a node which will display the OS python and not the one in the environment

### Your personal set up

Installed JupyterHub using on Docker:
```
RUN python3 -m pip install jupyterhub jupyter notebook
```

 - OS:
ubuntu 22.04
 - Version(s):
 jupyterhub, latest, python 3.10

**Comment by manics** [comment]
The shell environment is managed by the single-user server (e.g. JupyterLab) not JupyterHub, and usually defaults to the users/system shell unless overridden.

**Comment by eusebiu** [comment]
@manics So, are you telling me that I should open this at JupyterLab?

As I see it, if I activate that environment in a terminal, the python is correctly found from that environment.
