### ISSUE TITLE
admin view: sorting users does not consider the whole dataset

### ISSUE THREAD

**Issue by lahwaacz** [jupyterhub/jupyterhub#4581]
The sorting functionality on the `/hub/admin` view does not consider the whole dataset. The view is paginated, showing only 50 users per page, and sorting seems to operate only on each page. So when you sort e.g. by Last Activity, you get just one page sorted, and not the 50 users with the latest activity on the entire hub. Likewise, when you sort by Running, you get only the users on the current page with running server at the top, even though there could be other users with running server on other pages. This functionality seems pretty useless.

**Comment by ryanlovett** [comment]
I believe this is a duplicate of #3816.

**Comment by lahwaacz** [comment]
@ryanlovett Right, closing.
