### ISSUE TITLE
Show more specific authentication errors on the login page

### ISSUE THREAD

**Issue by lahwaacz** [jupyterhub/jupyterhub#4582]
PAM may be configured with the [pam_faillock](https://man.archlinux.org/man/pam_faillock.8) module which temporarily locks a user account after a series of failed logins. On a Linux console, this may be accompanied by an explanatory message such as
```
examplesystem login: exampleuser
The account is locked due to 3 failed logins.
(10 minutes left to unlock)
Password:
```
However, JupyterHub's login page always shows only the [Invalid username or password](https://github.com/jupyterhub/jupyterhub/blob/f5baa7b55c910fbfbbefebb6dc91734995bf2416/jupyterhub/handlers/login.py#L172) error.

I think authenticators should be extended to provide a better error message that could be shown on the login page in order to avoid confused users. It can be done at least in some cases with the PAMAuthenticator.

**Comment by mahendrapaipuri** [comment]
Related #4421

**Comment by manics** [comment]
Closing as a duplicate
