### ISSUE TITLE
Track metrics via statsd

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#459]
[StatsD](https://github.com/etsy/statsd) is a server / protocol for collecting useful metrics of different types: counters (number of users active), timing (time taken to spawn a user server), etc.

https://github.com/minrk/chpbench/issues/1#issuecomment-191405430 has more info from @minrk about things we can track easily with this.

This will be very useful for operational visibility into JupyterHub performance over time. 

I'll start working on a patch and we can also suggest other useful things to add to this. It'll be turned off by default, and you'll have to supply your own statsd endpoint (could be internal, or an external commercial service) for it to send stats to.

**Comment by yuvipanda** [comment]
https://github.com/jupyter/configurable-http-proxy/pull/51 for CHP btw.

**Comment by yuvipanda** [comment]
#496 is the beginnings of it here.

**Comment by willingc** [comment]
@yuvipanda Can this be closed? Hope you are doing well 😄

**Comment by minrk** [comment]
Yup, I think we've got enough to call this good. There's always room for improvement.

Thanks for staying on top of these, @willingc!
