### ISSUE TITLE
Launching multiple notebooks in jupyterhub with different jwt tokens loads the first spawned notebook

### ISSUE THREAD

**Issue by adhithya71** [jupyterhub/jupyterhub#4600]
Problem description :

I am using jupyterhub with custom authentication where a userId is extracted from jwt , and a notebook is spawned on that userId . But when I launch multiple notebooks with different userId from the same browser , it loads the first notebook .

The new userId has been passed correctly in the logs , but somewhere it changes and the previous values are loaded .

This works fine when I launch each unique notebook in different browsers

In the logs , I am getting

[I 2023-10-03 18:17:53.016 JupyterHub base:837] User logged in: b372 ->2nd persons userId

But in the next line , it is taking first spawned notebook’s userId
[I 2023-10-03 18:17:53.020 JupyterHub log:191] 302 GET /hub/login?token=[secret] → /hub/spawn?token=[secret] (1563) ->Previous userId
[I 2023-10-03 18:17:53.615 JupyterHub pages:168] Server 1563 is already active
I am using Jupyterhub 4.0.2 and Jupyterlab 4.0.6

**Comment by manics** [comment]
Looks identical to this forum post https://discourse.jupyter.org/t/launching-multiple-notebooks-in-jupyterhub-with-different-jwt-tokens-loads-the-first-spawned-notebook/21735

**Comment by adhithya71** [comment]
> Looks identical to this forum post https://discourse.jupyter.org/t/launching-multiple-notebooks-in-jupyterhub-with-different-jwt-tokens-loads-the-first-spawned-notebook/21735
 I raised that issue here seeing as it had no response . This issue is a more detailed version of https://github.com/jupyterhub/oauthenticator/issues/689 . Why don't we keep this issue open , as we have no meaningful answers yet ?
