### ISSUE TITLE
Tool gets killed at login

### ISSUE THREAD

**Issue by Dom-nik** [jupyterhub/jupyterhub#462]
I run Jupyterhub 0.4.1 on CentOS 6.2 with Python 3.5.1 and use the root account (**but with su from a non-root account user1**, no direct login possibility).
The tool enables to login and starts the single-user process only for the non-root user **user1**
For all other users it gets killed and the configurable-http-proxy returns 503 error (The upstream service is unavailable). 

I tried su-ing with another non-root account user2 and the situation is exactly the same.

The last messages I find in the console:
> error: [ConfigProxy] Proxy error:  code=ECONNRESET
> error: [ConfigProxy] 503 POST /hub/login?next=

Nothing regarding this appears in the logs (even with --debug).

**Comment by minrk** [comment]
There should be some log statements about the other single-user processes attempting to start. Can you perhaps include more of the log? The CONNRESET message comes from the proxy, telling us that there is no server there, but it doesn't help us find any information about why it's gone.

**Comment by Dom-nik** [comment]
**The way I run jupyterhub:**
jupyterhub --debug --log-file=jupyterhub.log

# the logging attempt
# => 503 error

**The log:**
cat jupyterhub.log
# cat jupyterhub.log.file
[I 2016-03-07 11:31:35.612 JupyterHub app:523] Loading cookie_secret from /root/jupyterhub_cookie_secret
[D 2016-03-07 11:31:35.613 JupyterHub app:584] Connecting to db: sqlite:///jupyterhub.sqlite
[W 2016-03-07 11:31:35.645 JupyterHub app:258]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[W 2016-03-07 11:31:35.651 JupyterHub app:642] No admin users, admin interface will be unavailable.
[W 2016-03-07 11:31:35.651 JupyterHub app:643] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2016-03-07 11:31:35.651 JupyterHub app:669] Not using whitelist. Any authenticated user will be allowed.
[D 2016-03-07 11:31:35.665 JupyterHub app:727] Loading state for cq2627 from db
[I 2016-03-07 11:31:35.666 JupyterHub app:731] cq2627 still running
[D 2016-03-07 11:31:35.667 JupyterHub spawner:261] Polling subprocess every 30s
[D 2016-03-07 11:31:35.677 JupyterHub app:744] Loaded users:
      cw5193
      cq2627 running at <Server(localhost:42937)>
      bx9746
       knime
[I 2016-03-07 11:31:35.696 JupyterHub app:1052] Hub API listening on http://localhost:8081/hub/
[I 2016-03-07 11:31:35.701 JupyterHub app:803] Starting proxy @ http://*:8000/
[D 2016-03-07 11:31:35.701 JupyterHub app:804] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8000', '--api-ip', 'localhost', '--api-port', '8001', '--default-target', 'http://localhost:8081']
[D 2016-03-07 11:31:35.908 JupyterHub app:832] Proxy started and appears to be up
[I 2016-03-07 11:31:35.909 JupyterHub app:1075] JupyterHub is now running at http://localhost:8000/
[I 2016-03-07 11:31:35.912 JupyterHub orm:179] Adding user cq2627 to proxy /user/cq2627 => http://localhost:42937
[D 2016-03-07 11:31:35.915 JupyterHub orm:166] Fetching POST http://localhost:8001/api/routes/user/cq2627
[I 2016-03-07 11:31:57.030 JupyterHub log:100] 302 GET / (@143.28.230.170) 1.28ms
[I 2016-03-07 11:31:57.186 JupyterHub log:100] 302 GET /hub (@143.28.230.170) 0.51ms
[I 2016-03-07 11:31:57.345 JupyterHub log:100] 302 GET /hub/ (@143.28.230.170) 1.11ms
[I 2016-03-07 11:31:57.532 JupyterHub log:100] 200 GET /hub/login (@143.28.230.170) 31.30ms


I understand that the proxy logs don't bring much information, but there seems to be nothing in the logs of jupyterhub itself. Is there another place to look for the logs anywhere?

**Comment by Dom-nik** [comment]
Is there any way to get help in this case or should I start analyzing the code?

**Comment by minrk** [comment]
I would expect a lot more logging about the failure to run servers when the users log in. Is it really silent when it's going wrong? One thing you can do is increase the amount of logging by adding `--debug`.

**Comment by minrk** [comment]
When only one user works, the most common problem is a permission error, that other users cannot see the files they need to run their servers. Often this is caused by one user doing `pip install -e` of a package, which typically results in files only they can read, but everyone needs.

**Comment by Dom-nik** [comment]
I was running jupyterhub with --debug all the way:
> jupyterhub --debug --log-file=jupyterhub.log

I'm also very surprised, but the only message I find in the console is 'Killed'.

I explicitly changed the permissions of all the packages in /usr/local/lib/python3.5/site-packages to readable and executable for all:
chmod +rx * -R

This didn't bring any change.

I have multiple python installs on my box, if that's any interesting.

**Comment by minrk** [comment]
Can you share the logs surrounding when the users login and the spawners start (Ideally not the jupyterhub.log, but the stderr from the process)?

**Comment by Dom-nik** [comment]
I didn't find any logs, to be honest, the child process doesn't event start.
However, I used strace:
`strace jupyterhub`
and noted that the jupyterhub process gets killed at a particular moment:
> setreuid(336, 4294967295 <unfinished ...>
> +++ killed by SIGKILL +++

[setreuid](http://linux.die.net/man/2/setreuid) is a command that switches the effective user ID, so I'm 99% sure that jupyterhub gets killed, because I run it as a non-root user (I mean, I run it after `su - root`, but I'm not allowed to `su` to any other user, as I'm not really logged as root).
I'll talk to our OS security team to confirm, but I guess that must be the case.

Thanks for your help, you actually made me think harder about log viewing possibilities that lead me to strace! :]

**Comment by minrk** [comment]
The fact that it's killed from the outside does sound like it might be a security service objecting to the user switching.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or leave a comment to reopen this issue. Thanks! :sunflower:
