### ISSUE TITLE
Navbar in admin page has wrong links

### ISSUE THREAD

**Issue by elferherrera** [jupyterhub/jupyterhub#4622]
### Bug description
When entering the admin page, the navbar has the wrong links and the Jupyterhub logo is missing

![image](https://github.com/jupyterhub/jupyterhub/assets/6942205/36414d40-7230-45ab-bfda-9cdb4a9f97bb)

The links for home, token and admin are also broken. They are missing the `/hub` part in the url

### How to reproduce

I'm using the helm chart 3.1.0 with jupyterhub image `jupyterhub/k8s-hub:3.1.0`

**Comment by consideRatio** [comment]
I'm looking at an installation of the jupyterhub chart 3.1.0 and it presents itself correctly there. Inspecting the HTML I see this:

```html
<img src="/hub/logo" alt="JupyterHub logo" class="jpy-logo" title="Home">
```

The full URL looks like `https://my-hub.org/hub/logo` for me.

What is your full URL?

**Comment by elferherrera** [comment]
I see this in the tree
![image](https://github.com/jupyterhub/jupyterhub/assets/6942205/129e7fcc-de23-488c-b48c-7deaf1c022d0)

![image](https://github.com/jupyterhub/jupyterhub/assets/6942205/619e4b7a-dec0-4146-b116-9430a23066be)

**Comment by consideRatio** [comment]
@elferherrera is there an configuration you have made to influence this is what I'm thinking mostly of. What configuration are you passing when installing the helm chart that overrides the default values?

**Comment by elferherrera** [comment]
No extra configuration on my side. The only configuration for hub is the GenericOAuthenticator definition

**Comment by consideRatio** [comment]
Is the hub exposed directly so you can see it when visiting `https://<your domain>/hub/home`?

**Comment by elferherrera** [comment]
Yeap. That's how it is exposed. It is weird that as soon as I click on the admin page, the links change. I was checking the templates and all the pages use the same nav template. So I dont know why it would change

**Comment by consideRatio** [comment]
> Yeap. That's how it is exposed. It is weird that as soon as I click on the admin page, the links change. I was checking the templates and all the pages use the same nav template. So I dont know why it would change

Did the links work, and then no longer work in the admin panel?

**Comment by elferherrera** [comment]
since I did the updated to the latest chart the link stopped working

**Comment by marcelovilla** [comment]
I can reproduce this locally using JupyterHub 4.0.2—check the lower left corner where the URLs appear:

https://github.com/nebari-dev/nebari/assets/36754005/f5039655-ef57-4205-9c96-a257d43002ed

While the links are correctly redirected in JupyterHub, I am not sure this behavior is intended. I found out about this by deploying JupyterHub in k8s and getting `404: Not found` errors when trying to access any of the items in the navbar after visiting the Admin dashboard.

**Comment by manics** [comment]
This bug is only present on the `/admin/` pages, not the other pages.
