### ISSUE TITLE
Access services on behalf of the user with extra scope

### ISSUE THREAD

**Issue by Ph0tonic** [jupyterhub/jupyterhub#4635]
### Proposed change
I would like user token provided injected when accessing services to have additional scopes rather than just the `access:services!service=myservice-1`, I would it to also have `access:services!service=myservice-2` such has to be able to request another service on behalf of the user.

### Who would use this feature?
Services accessing others services on the behalf of the users.

### (Optional): Suggest a solution
I took quite some time to read the doc to see if this was possible but I wasn't able to find any documentation (sorry if I missed it). The idea would be to have something like `KubeSpawner.server_token_scopes` which allows to configure which scopes the spawner gets, but for the user token injected in services if they have the right scopes configured.

**Comment by minrk** [comment]
This is governed by the `service.oauth_client_allowed_scopes` option, which defaults to `access:services!service`, but can include any number of scope. These will be the _requested_ scopes of the user's oauth token, though the _granted_ scopes will be the subset that the user actually holds.

```python
c.JupyterHub.services = [
    {
        'name': 'my-service',
        'oauth_client_allowed_scopes': [
            'access:services!service=service1',
            'access:services!service=service2',
        ],
    },
]
```

Some more info [in the latest build of the docs](https://jupyterhub.readthedocs.io/en/latest/reference/services.html#service-credentials).
