### ISSUE TITLE
Minor broken docs: reference to wiki

### ISSUE THREAD

**Issue by benjimin** [jupyterhub/jupyterhub#4653]
Minor broken docs: [this page](https://jupyterhub.readthedocs.io/en/stable/reference/spawners.html#examples) has a link titled "Jupyterhub Wiki", but it directs to GitHub, _not_ to any wiki. 

(I think the docs should be changed to update either the url or label used by the link, but I'm not sure which.. does a wiki exist?)

**Comment by minrk** [comment]
Thanks, it does link to the wiki, but since we stopped using the wiki and a disabled wiki link redirects back to the original repo. I think this link can just be removed.

**Comment by rizz-sd** [comment]
Hi fellow members.
I am new to Open source community. Given that wiki link doesn't exist anymore and we just need to remove the link reference and modify some text, this looks like an easy fix. Can I take this up?

**Comment by minrk** [comment]
@rizz-sd yes, please go ahead!
