### ISSUE TITLE
try redoc for REST API

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#4669]
Updating the openapi spec in #4594, I noticed our generated spec doesn't display any of the auth info, which led me to poke around, looking for another way to render the openapi spec.

That led me to [redocly-cli](https://redocly.com/redocly-cli/), which can build a single static HTML page from openapi pretty easily:

```
npx @redocly/cli build-docs docs/source/_static/rest-api.yml
```

and it looks like this:

<img width="1224" alt="Screenshot 2024-01-08 at 12 08 23" src="https://github.com/jupyterhub/jupyterhub/assets/151929/4d93c287-d27e-4a26-a22e-c27dfabb10d6">

being a static HTML page, rather than an on-the-fly javascript render should make anchor links, etc. more reliable. Downside is that we'd be back to a javascript build step for the docs, like we had with bootprint (removed in #3665).

Apparently redoc can also [run in-page](https://redocly.com/docs/redoc/deployment/html/), which would change very little from what we have now. That's less likely to fix anchor links, but easy to check.

**Comment by manics** [comment]
Sounds good to me! I've found it frustrating trying to link to the API when answering support posts. I [tried sphinx-openapi a few months ago](https://github.com/manics/jupyterhub/commit/5b16a52e46b0db265e7fef5ac05978abb6e718e5) but it didn't render properly.

I think we could make the choice of embedding in the page vs a standalone page once we try it based on what's clearest and most usable.

**Comment by minrk** [comment]
I've been this to test changes in, #4594, and I like it so far. I don't want to add too much to that huge PR, but I'll do a standalone one for redocly after that lands.
