### ISSUE TITLE
"Stop My Server" red button does not trigger anything

### ISSUE THREAD

**Issue by dpiparo** [jupyterhub/jupyterhub#469]
Hi,

I was wondering what would be the best way to trigger the stop coroutine of a spawner via the jupyterhub web interface. Unfortunately I did not mange to make the red button "Stop My Server" working. After having a closer look to the code, I stumbled in the home template here
https://github.com/jupyter/jupyterhub/blob/0fbd69be9bfc584e6c7d7613f517886ae7993b51/share/jupyter/hub/templates/home.html
it seems that there is no url linked to the button: was this done on purpose?

Cheers,
       Danilo

**Comment by betatim** [comment]
I think the button is powered by JS, do you have `home.js`?

**Comment by minrk** [comment]
Yeah, the action is added by js. What version are you running, and do you see anything in the js console?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or add a comment to reopen this issue. Thanks! :sunflower:
