### ISSUE TITLE
Can Jupyterhub access Anaconda packages?

### ISSUE THREAD

**Issue by cenveoanalyst** [jupyterhub/jupyterhub#470]
I installed python3 using Anaconda, but Jupyterhub using pip3 after installing conda per the getting started document. I notice I can import packages installed with Anaconda in the regular python interpreter but I can't import them into a notebook spawned with Jupyterhub. I can also import the package when I access the same notebook run as a local notebook server. I can only access packages installed with pip (pip3 in my Ubuntu VM) in a jupyterhub spawned notebook. Is there anyway I can access Conda packages with a Jupyterhub notebook? Or do all imports need to reference the package installed with pip?

**Comment by minrk** [comment]
JupyterHub does not affect how packages are imported or what is available. If you are seeing results different from what you expect, this probably means that you have installed the anaconda packages and JupyterHub with different Pythons. You can check this by looking at `head $(which pip3)`. If that doesn't point to your Anaconda Python, then JupyterHub is installed with a different Python.

Your choices are either to ensure JupyterHub is installed with the same Python (requires that your conda env is Python 3):

    /path/to/conda/bin/python -m pip install jupyterhub

Or to register the anaconda kernel *explicitly* with Jupyter:

```bash
# install JupyterHub
pip3 install jupyterhub
# install conda packages
conda install anaconda
# register conda IPython kernel with Jupyter:
/path/to/conda/bin/python -m ipykernel install
```

**Comment by cenveoanalyst** [comment]
Min RK,

Thanks for the help! I ended up downloading the packages I needed separately and they work; but it appears when I installed Anaconda I didn’t use it to install Jupyterhub so it missed the packages. I’ll have to try registering  the Anaconda kernel with Jupyterhub and see what happens.

**Comment by bartaelterman** [comment]
There is also a [conda jupyterhub package](https://anaconda.org/timcera/jupyterhub) so you can also install jupyter directly in conda. Do `conda install jupyterhub`. That way, you don't need to register the conda python in jupyterhub.

Since there is now a chance that you have installed jupyterhub twice, you should check which jupyterhub you are launching with `which jupyterhub`. If that points to the non-conda installation, add the conda binary to your PATH. (assuming it is in something like `~/conda/bin/jupyterhub`, do `echo "export PATH=~/conda/bin/jupyterhub:$PATH >> ~/.bashrc"`

**Comment by willingc** [comment]
I'm closing this issue as resolved. I'm also labeling as "reference" to help future users. Thanks everyone!

**Comment by rtruxal** [comment]
https://anaconda.org/timcera/jupyterhub is gone.  

`conda install jupyterhub` seems not to work on a first-pass.

**Comment by rtruxal** [comment]
### `~$ conda install -c conda-forge jupyterhub` works.

**Comment by go-bears** [comment]
does this solution work for all jupyterhub users? or would each user have to register the anaconda kernel separately? I had installed anaconda for all users in the /opt folder before installing jupyterhub.
