### ISSUE TITLE
modifyable api_page_default_limit variable on the admin page

### ISSUE THREAD

**Issue by szazs89** [jupyterhub/jupyterhub#4709]
### Proposed change

It is rather annoying that the number of the listed servers (`api_page_default_limit`?) cannot be changed on the admin page,
but only use the number fixed in `jupyterhub_config.py`.

It would help the administration of jupyter HUB very much if this number could be changed on the admin page.

### Alternative options

The variable `api_page_default_limit` can be changed in `jupyterhub_config.py`, however, this requires restarting the server.

### Who would use this feature?

Most of the users with _admin_ access.

### (Optional): Suggest a solution

Completing the admin page template(?) with a choice box (50|100|200|500) or input box.

**Comment by minrk** [comment]
The admin pages should definitely have control for selecting the number of items on the page. This should probably be able to come from the URL. In fact, all input parameters should be in the URL so refreshing the page doesn't result in a change of view.

Existing API parameters that should be supported in UI:

- state (not settable at all)
- limit (not persisted)
- offset (in UI via pager, not persisted)
- name_filter (in UI, not persisted)

and `order_by` should be in the UI if/when #3816 is implemented on the API side.

I don't think the admin page should be able to modify the Hub's _internal_ API limits, which would affect other requests and not persist across hub restarts, but it should certainly be able to control the current browser's view.
