### ISSUE TITLE
failed to start a jupyterhub image on an arm machine with a Proxy error

### ISSUE THREAD

**Issue by luha000** [jupyterhub/jupyterhub#4715]
### Bug description

I started the jupyterhub image on an arm architecture machine, but there was an error about the proxy and it could not be started

![image](https://github.com/jupyterhub/jupyterhub/assets/8275017/4ca4b456-ba7c-4764-9b0a-c6161bdadd5d)

the system is Linux version 4.19.90-17.5.ky10.aarch64，and Configured as 8-core CPU and 32g memory

this docker version is 20.10.5 and I also tried 25.0.3，all failed

**Comment by minrk** [comment]
Looks like "Fatal process OOM in insufficient memory to create an Isolate" is the issue, which would be something outside JupyterHub.

Try running `configurable-http-proxy` on its own to figure out what's stopping it.
