### ISSUE TITLE
Jupyterhub/Jupyterlab make CORS preflight request to Shibboleth

### ISSUE THREAD

**Issue by guyq1997** [jupyterhub/jupyterhub#4760]
### Bug description
Currently I use Apache2 as reverse proxy and Shibboleth as authentication method. Error occurs after logging into Single User Server. 
![image](https://github.com/jupyterhub/jupyterhub/assets/111009031/0c3615cb-acdd-4385-9e4f-f3ccd5aa9e05)
Figure above shows the error message after user login. This error occurs very often, that the user cannot programme correctly. After several restarts, this error message does not disappear. 
On browser side, it is also an error regarding Preflight Request was rejected by Shibboleth IdP. No "Access-Control-Allow-Origin" header is in the request. (Missing Header) See Browser Log.

> Access to fetch at 'https://saml.xxx/idp/profile/SAML2/Redirect/SSO?… (redirected from 'https://123.org/jupyterhub/) from origin ‘https://123.org/’ has been blocked by CORS policy: Response to preflight request doesn’t pass access control check: No ‘Access-Control-Allow-Origin’ header is present on the requested resource. If an opaque response serves your needs, set the request’s mode to ‘no-cors’ to fetch the resource with CORS disabled

### The Key Problem:
While using Jupyterhub, Jupyterhub always sends requests to Shibboleth IdP. This request comes from the following address/URL:
https://xxx.org/jupyterhub/user/yuqiang/lab/api/workspaces/default?1711659013860
or /jupyterhub/user/yuqiang/lab/api/kernel such similar sources.
So it seems jupyterhub API wants to send a request to check the user status? Now comes the question, what is this URL and why does it want to send request?

### How to reproduce

1. use Apache2 as reverproxy and web server
2. use Shibboleth Service Provider to protect Jupyterhub
3. user Shibboleth Authenticator
4. Login 

#### Expected behaviour
Users recive no more Restart Error, and can normally program

#### Actual behaviour
Single user Server always restart. Programming is not possible

### Your personal set up

 - OS: Ubuntu 22.04
 
 - Version(s):Jupyterhub: 4.0.2 Jupyterlab: 4.0.7
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
c.Spawner.cmd = “jupyterhub-singleuser”

c.Spawner.debug = True
c.ConfigurableHTTPProxy.debug = True
c.DockerSpawmer.use_internal_ip = True

c.JupyterHub.spawner_class = DockerSpawner
c.DockerSpawner.image = “guyq1997/jupyterlab-dhbw”
c.JupyterHub.hub_ip = “jupyterhub”
c.JupyterHub.bind_url = ‘http://jupyterhub:8000/jupyterhub’

c.DockerSpawner.network_name = os.environ[“DOCKER_NETWORK_NAME”]
c.DockerSpawner.extra_host_config = { ‘network_mode’: os.environ[“DOCKER_NETWORK_NAME”] }
c.DockerSpawner.start_timeout = 120
c.DockerSpawner.remove = False
c.JupyterHub.authenticator_class = ShibbolethAuthenticator
c.ShibbolethAuthenticator.headers = [“Givenname”]
c.Authenticator.shibboleth_logout_url = “https://example.org/Shibboleth.sso/Logout”
```
Apache2 Configuration:
```python
#Listen 80
<VirtualHost *:80>
  ServerName**
  Redirect / https://**/
</VirtualHost>
 
#Listen 443
<VirtualHost *:443>
  ServerName **
 
  ServerSignature Off
  SSLProxyEngine on
  # Enable HTTP/2, if available
  Protocols h2 http/1.1
 
  # HTTP Strict Transport Security (mod_headers is required) (63072000 seconds)
  Header always set Strict-Transport-Security "max-age=63072000"
 
  # Configure SSL
  SSLEngine on
  SSLCertificateFile /etc/letsencrypt/live/**/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/**/privkey.pem
  SSLOpenSSLConfCmd DHParameters /etc/ssl/certs/dhparams.pem
  # Intermediate configuration from SSL-config.mozilla.org (2022-03-03)
  # Please note, that this configuration might be outdated - please update it accordingly using https://ssl-config.mozilla.>  SSLProtocol TLSv1.2
  SSLCipherSuite          ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA>  SSLHonorCipherOrder     on
  SSLSessionTickets       Off
  SSLCompression          Off
 
#----------------------Shibboleth-------------------------------
  UseCanonicalName On
  Include /etc/shibboleth-ds/shibboleth-ds.conf
  Redirect seeother /shibboleth https://**/Shibboleth.sso/Metada>  RedirectMatch /start-session$ /Shibboleth.sso/Login
 
  <Location /Shibboleth.sso>
    AuthType None
    Require all granted
  </Location>
 
  <Location /shibboleth-sp>
    AuthType None
    Require all granted
  </Location>
 
  Alias /shibboleth-sp/main.css /usr/share/shibboleth/main.css
#----------------------Jupyterhub-------------------------------
  RewriteEngine On
 
  RewriteCond %{HTTP:Connection} Upgrade [NC]
  RewriteCond %{HTTP:Upgrade} websocket [NC]
  RewriteRule /jupyterhub/(.*) ws://jupyterhub:8000/jupyterhub/$1 [P,L]
  RewriteRule /jupyterhub/(.*) http://jupyterhub:8000/jupyterhub/$1 [P,L]
 
  <Location /jupyterhub>
 
    RequestHeader unset Accept-Encoding
#    ProxyPass         http://jupyterhub:8000/jupyterhub
#    ProxyPassReverse  http://jupyterhub:8000/jupyterhub
 
    RewriteEngine On
    ProxyPreserveHost on
 
    AuthType shibboleth
    ShibRequestSetting requireSession 1
    Require valid-user
    ShibUseHeaders On
    RequestHeader set X-Remote-User %{REMOTE_USER}s
    ProxyPass        http://jupyterhub:8000/jupyterhub
    ProxyPassReverse http://jupyterhub:8000/jupyterhub
  </Location>
</VirtualHost>
```

</details>

<details><summary>Logs</summary>

```
# Access to fetch at 'https://saml.xxx/idp/profile/SAML2/Redirect/SSO?SAMLRequest=r' (redirected from 'https://myvm/jupyterhub/user/yuqiang/lab/api/workspaces/auto-Z?1711703114703') from origin 'https://myvm' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

jlab_core.975ecba59e6dfbddeb44.js?v=975ecba59e6dfbddeb44:1 
        
PUT/GET https://saml.xxx/idp/profile/SAML2/Redirect/SSO?SAMLRequest=r:ERR_FAILED
```
</details>

**Comment by manics** [comment]
There's already an active discussion on this issue in https://discourse.jupyter.org/t/jupyterhub-try-to-make-preflight-request-to-shibboleth-idp/24853 so I'll close this to avoid duplication of effort.

**Comment by guyq1997** [comment]
Some Updates, incase others search for same question and land on this page. : )

I found a not-so-great way to solve it, and it only works in Firefox.

Jupyterhub runs in `/jupyterhub` subpage. In `/jupyterhub` shibboleth session is deactivated, it only needs the user data/http headers for identifying Users. This means that `/jupyterhub` is not protected by Shibboleth. Shibboleth Headers come from `/secure` subpage. `/secure` is for user login. As long as user is logged into `/secure`, the user data is stored in browser. Subpath `/jupyterhub` can therefore also read the user data/http headers.

The requests (to GET or PUT data into Single User Server) can therefore be sent directly to the single user server (Jupyterlab). Without sending to Shibboleth and check CORS premission first. **However, this approach only works with Firefox.**

**Here is Apache Configuration:**
>   <Location /secure>
>     AuthType shibboleth
>     ShibRequireSession On
>     Require valid-user
>     ShibUseHeaders On
>   </Location>
>   <Location /jupyterhub>
> 
>     RewriteEngine On
>     ProxyPreserveHost on
>     AuthType shibboleth
>     Require valid-user
>     ShibRequestSetting requireSession off
>     ShibUseHeaders On
> 
>     ProxyPass        http://jupyterhub:8000/jupyterhub
>     ProxyPassReverse http://jupyterhub:8000/jupyterhub
>   </Location>

With Chrome, a 401 Unauthorized error occurs in Browser Log after spawning User Server.
