### ISSUE TITLE
JupyterHub 5.0

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#4788]
With #4748 and #4701 landed, the last thing I want to do before making 5.0 is #4774 .

Tasks:

- [x] land bootstrap 5 #4774
- [x] migrating to v5 doc #4787
- [x] changelog PR
- [x] release jupyterhub 5b1

**Comment by erkin98** [comment]
@minrk what is the release date for stable v5?

**Comment by minrk** [comment]
That will depend on feedback from prerelease testing, but probably in a few weeks.
