### ISSUE TITLE
Feature request: Launch server from CLI

### ISSUE THREAD

**Issue by blackliner** [jupyterhub/jupyterhub#4791]
### Proposed change
I would like to be able to run a command inside a client terminal and start the jupyterhub server.

### Who would use this feature?
Developers as well as automation can utilize this feature to spin up a server on-demand

### (Optional): Suggest a solution
Provide an API plus a CLI to spin up servers

**Comment by minrk** [comment]
We do have an [extensive API](https://jupyterhub.readthedocs.io/en/latest/reference/rest-api.html) covering everything needed for this.

For example, starting a server is:

```bash
curl -H "Authorization: Bearer $JUPYTERHUB_API_TOKEN" -X POST https://hub.example.org/hub/api/users/$USER/servers/
```

I don't think maintaining a CLI is in-scope at the moment. But there is [this jupyterhub Python client](https://github.com/americandatascience/jh-client) generated from our OpenAPI spec, which you might use.
