### ISSUE TITLE
Migrate from jupyter_telemetry to jupyter_events?

### ISSUE THREAD

**Issue by lahwaacz** [jupyterhub/jupyterhub#4803]
The `jupyter_telemetry` package is [said to be unmaintained](https://github.com/jupyter/telemetry/pull/69) and it test suite does not work with Python 3.12. It does not seem to be used heavily in JupyterHub, can you migrate to [jupyter_events](https://github.com/jupyter/jupyter_events) instead?

**Comment by minrk** [comment]
Yes, we should do that. Thanks for bringing it up!
