### ISSUE TITLE
Admin UI glitch - double pressing on "Next" page button causes bugged state

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#4810]
In the GIF animation below, you see me first click once, move the cursor away, and then press twice in fast succession. Only three clicks are made, but after the double click it gets stuck going back and forth between page 100-150 and page 150-200.

![click-then-doubleclick](https://github.com/jupyterhub/jupyterhub/assets/3837114/cb60cee6-1994-4b6e-a505-f8e2cc6c1fcf)

Observed in JupyterHub 4.1.5 20240508073043

**Comment by minrk** [comment]
Can you test this in 5.0b1? The admin page got lots of changes with the bootstrap 5 update, so it would be nice if this happened to get fixed along the way 🤞

**Comment by minrk** [comment]
Thanks, I can reproduce it easily with 5.0b2 easily by adding `time.sleep(0.25)` to GET /users.

I think I have a rough idea - if two page fetches are outstanding at the same time, they cycle state changed between them:

- click next - setOfset(10) - sets state offset=10, triggers updateUsers(offset: 10)
- click next - setOfset(20) - sets state offset=20, triggers updateUsers(offset: 20)
- first response comes in - sets offset(10), which is different from offset=20, triggers updateUsers

The problem ultimately stems from the fact that setting the offset state is what triggers the request, but the response _also_ sets the offset state.

If clicking hte pagination button triggered the request without setting the state, I think this wouldn't happen.
