### ISSUE TITLE
Unable to restrict admins to their own resources

### ISSUE THREAD

**Issue by ibh1127** [jupyterhub/jupyterhub#4826]
### Bug description

From what I understand in the RBAC documentation, I should be able to set the scope of the 'server' role to 'self' and this should prevent admins from accessing other users' single-user servers. 

Documentation: https://jupyterhub.readthedocs.io/en/stable/rbac/roles.html#overriding-default-roles

```
c.JupyterHub.load_roles = [
 {
   'name': 'server',
   'scopes': ['self'],
 }
]
```

#### Expected behaviour

I expect that admins would be unable to Access Other users single-user servers
#### Actual behaviour

admins are still able to start other users's servers, access them, etc.

Is this the expected behavior or am I misunderstanding the documentation?

Thanks!

**Comment by manics** [comment]
The `server` role applies to the permissions of the singleuser server application, and is intended to improve security by _not_ giving the server the same permissions as the user (so the server API token does not have the same permissions as the user).

If you want to modify the `admin` permissions you can redefine the role
https://github.com/jupyterhub/jupyterhub/blob/5.0.0/jupyterhub/roles.py#L31-L52
but it's better to define a new role, and not assign the admin role to users in the first place.
