### ISSUE TITLE
Migrate some community authored documentation about JupyterHub configuration

### ISSUE THREAD

**Issue by willingc** [jupyterhub/jupyterhub#483]
Hello JupyterHub community,

If you have use cases that you have implemented that you would like to share with others, please let us know. We are expanding the Community section of our JupyterHub docs to help share knowledge about deployments.

Ideas for future content:
- [ ]  'Cookbook: Parallel IPython config for jupyterhub' @cekees
- [x]  Existing JupyterHub wiki content

**Comment by rushgeo** [comment]
Just to clarify, do you mean the [gallery of deployments](https://jupyterhub.readthedocs.io/en/latest/gallery-jhub-deployments.html), another new section labeled "community," or just bringing in contributions wherever they fit?

**Comment by willingc** [comment]
Gallery of deployments. Thanks for asking 👍

**Comment by willingc** [comment]
I'm going to close this issue as we've expanded the community docs quite a bit since this initial issue was filed.
