### ISSUE TITLE
v5: Constant CPU usage of at least 1.9%

### ISSUE THREAD

**Issue by benz0li** [jupyterhub/jupyterhub#4834]
### Bug description

JupyterHub 5.0 consistently uses at least 1.9% CPU – even when *idle*.

#### Expected behaviour

JupyterHub 4.1 has a CPU usage of 0.05% when *idle*.

### Your personal set up

JupyterHub: [`glcr.b-data.ch/jupyterhub/jupyterhub:5.0-oauth-docker`](https://gitlab.b-data.ch/jupyterhub/jupyterhub/container_registry)

**Comment by minrk** [comment]
I do not, we'll need to do some profiling to figure out what's going on. Is JupyterHub the only upgraded package?

**Comment by benz0li** [comment]
> I do not, we'll need to do some profiling to figure out what's going on. Is JupyterHub the only upgraded package?

This projects' [`jupyterhub/jupyterhub`](https://hub.docker.com/r/jupyterhub/jupyterhub) image plus `dockerspawner`, `jupyterhub-idle-culler`, `oauthenticator` and `psycopg2` installed on top.

👉 It is `/usr/bin/python3 /usr/local/bin/jupyterhub` that is consistently using at least 1.9% CPU.

**Comment by benz0li** [comment]
To reproduce with this projects' docker image:

```bash
docker run --name jupyterhub-idle --rm -ti jupyterhub/jupyterhub
```

```bash
docker stats jupyterhub-idle
```

```
CONTAINER ID   NAME              CPU %     ...
c0398c58f7e1   jupyterhub-idle   1.92%     ...
```

**Comment by manics** [comment]
Running JupyterHub under py-spy, but not connecting to it in a browser, uses around 3% CPU continuously on my system
`py-spy record -o profile-x.svg -- jupyterhub --JupyterHub.authenticator_class=dummy --JupyterHub.spawner_class=simple --Authenticator.admin_users=test`:
![profile.svg](https://github.com/jupyterhub/jupyterhub/assets/1644105/97cad099-908d-4c83-999c-f2b00ae7288a)

If I disable `PeriodicMetricsCollector`:
```diff
diff --git a/jupyterhub/app.py b/jupyterhub/app.py
index 8bc5b937..8295bd48 100644
--- a/jupyterhub/app.py
+++ b/jupyterhub/app.py
@@ -3414,7 +3414,7 @@ class JupyterHub(Application):
         metrics_collector = self.metrics_collector = PeriodicMetricsCollector(
             parent=self, db=self.db
         )
-        metrics_collector.start()
+        # metrics_collector.start()
 
     async def cleanup(self):
         """Shutdown managed services and various subprocesses. Cleanup runtime files."""
```
CPU usage is <1%

**Comment by manics** [comment]
https://github.com/jupyterhub/jupyterhub/pull/4615
Increasing `PeriodicMetricsCollector.event_loop_interval_resolution` from the default 0.02 to a larger number brings down the CPU usage, but obviously makes the metric less useful.

**Comment by benz0li** [comment]
IMHO there should be an option to disable metrics (default: enabled).

**Comment by minrk** [comment]
>IMHO there should be an option to disable metrics (default: enabled).

Definitely! There is exactly that:

```python
c.PeriodicMetricsCollector.event_loop_interval_enabled = False
```

but the default behavior shouldn't be this expensive, we should explore that. Possibly making the metric more efficient somehow, or if there isn't something particularly inefficient there, just make the default sensitivity longer, e.g. 100ms, 200ms or even 500ms.

FWIW, with this metric disabled, an idle JupyterHub uses < 0.1% CPU. On my machine with an idle JupyterHub doing nothing else:

| interval | % CPU |
| --- | --- |
| disabled | < 0.1% |
| .02 | ~2% |
| .05 | ~1% |
| 0.1 | ~0.7% |
| 0.2 | ~0.5% |
| 0.5 | ~0.1% |

So I think the default interval probably shouldn't be lower than 100ms.

**Comment by minrk** [comment]
I think a simpler measurer that is just

```python
while True:
    tick
    await asyncio.sleep(interval)
    tock
```

will be a bit more efficient than PeriodicCallback, which involves a number of function calls, which is a relevant fraction on this timescale.

**Comment by benz0li** [comment]
> > IMHO there should be an option to disable metrics (default: enabled).
> 
> Definitely! There is exactly that:
> 
> ```python
> c.PeriodicMetricsCollector.event_loop_interval_enabled = False
> ```

That is what I was looking for. I could not find it in the documentation...

**Comment by benz0li** [comment]
Now, the CPU usage of v5.0.0 is the same as v4.1.5:

```
CONTAINER ID   NAME              CPU %     ...
abf075e95af2   jupyterhub-idle   0.05%     ...
```
