### ISSUE TITLE
Ability to log the file details when we upload a file to notebook

### ISSUE THREAD

**Issue by rahulsayini** [jupyterhub/jupyterhub#4841]
### Proposed change

Ability to log the file details when we upload a file to notebook

we want the user who uploaded the file, file type, file size and file name details

### Alternative options

we want to capture the file details for auditing purpose

### Who would use this feature?

All the analysts and the auditing teams would benefit, since we will have the eyes on who is getting what type of data

### (Optional): Suggest a solution

Put a logger on file details and have an ability for the jupyter hub users

**Comment by manics** [comment]
JupyterHub manages the singleuser server (e.g. starting/stopping Jupyter server/notebook/lab), but doesn't control what the singleuser server can do. Additional logging would have to be added in one of those components.
