### ISSUE TITLE
*/tree - 404 : Not Found 

### ISSUE THREAD

**Issue by jelmd** [jupyterhub/jupyterhub#4851]
### Bug description
We currently use jupyterhub with sudospawner on Ubuntu 20.04 with python3.8 without any problem:
```
jupyter core     : 4.7.1
jupyter-notebook : 6.4.3
qtconsole        : 5.1.1
ipython          : 7.27.0
ipykernel        : 6.3.1
jupyter client   : 7.0.2
jupyter lab      : not installed
nbconvert        : 6.1.0
ipywidgets       : 7.6.4
nbformat         : 5.1.3
traitlets        : 5.1.0
```
However, since this seems to be very outdated, I tried to install on Ubuntu 22.04 with python3.10 the recent versions:
```
IPython          : 8.25.0
ipykernel        : 6.29.4
ipywidgets       : not installed
jupyter_client   : 8.6.2
jupyter_core     : 5.7.2
jupyter_server   : 2.14.1
jupyterlab       : 4.2.3
nbclient         : 0.10.0
nbconvert        : 7.16.4
nbformat         : 5.10.4
notebook         : 7.2.1
qtconsole        : not installed
traitlets        : 5.14.3
```
Replaced the `NotebookApp` with `ServerApp` in the config file and kept all other things as is.

Unfortunately if one now connects to the hub  (e.g. `http://localhost:8000/jupyter/n05-08/hub/home` ) he can stop/start the server, but after the server got started, one gets redirected to the `/tree` URL and jupyterhub comes up with a `404: : Not Found - You are requesting a page that does not exist!` page. Same thing if one tries to navigate to the `/lab` page. Turned on debugging for everything, but logs are pretty quiet. The only thing I can see is `[D 2024-07-08 17:24:02.509 ServerApp] No user identified`. So something seems to be broken, since jupyterhub is now not usable anymore :(.

### How to reproduce
Executed as user `admin`:
```sh
PU_BASE='/usr/local/jupyter'
PIP='pip3' PYTHON='python3' PY_VERS='3.10' APP='ServerApp' JHUB_RUNNER='juppy'

export PYTHONUSERBASE=${PU_BASE} PATH="${PU_BASE}/bin:${PATH}"
export PYTHONPATH=${PU_BASE}/lib/python${PY_VERS}/site-packages
export NPM_CONFIG_GLOBALCONFIG=${PU_BASE}/npmrc

sudo mkdir -p ${PU_BASE}
sudo chown ${LOGNAME}:staff ${PU_BASE}
rm -rf ~/{.local,.cache/pip,node_modules}

${PYTHON} -m pip install --upgrade pip
${PIP} install jupyter
${PYTHON} -m ipykernel install --prefix=${PU_BASE}
# normalize path
sed -i -e "s|^\s*\"python\",|  \"/usr/bin/${PYTHON}\",|" \
        ${PU_BASE}/share/jupyter/kernels/${PYTHON}/kernel.json
${PIP} install jupyterlab
${PIP} install git+https://github.com/jupyter/sudospawner
# fix "does not pass PYTHONPATH"
sed -i.orig -e "/self.sudo_args/ a\        if 'PYTHONPATH' in os.environ:\n            cmd.append('='.join(['PYTHONPATH', os.environ['PYTHONPATH']]))" \
        ${PU_BASE}/lib/python${PY_VERS}/site-packages/sudospawner/spawner.py
sed -i.orig -e "/'PYTHONPATH' in env:/ s/:/ and 'NO_PYTHONPATH' in env:/"\
        ${PU_BASE}/lib/python${PY_VERS}/site-packages/sudospawner/mediator.py

sudo ln -sf ${PU_BASE}/share/jupyter /usr/share/jupyter
${PU_BASE}/bin/jupyter-kernelspec list

apt-get install nodejs
echo "prefix=${PU_BASE}" >${NPM_CONFIG_GLOBALCONFIG}
npm install --omit=dev --omit=optional --global configurable-http-proxy

F=/usr/local/etc/jhub_cfg.py
cat >$F<<EOF
import os

c = get_config()

c.JupyterHub.base_url = '/'.join([ '/jupyter', os.environ['HOST'] ]) 
c.JupyterHub.spawner_class = 'sudospawner.SudoSpawner'
c.JupyterHub.shutdown_on_logout = True

c.Spawner.debug = True
#c.Spawner.env_keep = [ 'PYTHONPATH', 'CUDA_PATH' ]
c.Spawner.args = ['--${APP}.allow_origin=*','--log-level=DEBUG','--debug']
c.Spawner.notebook_dir = '~/'

c.Authenticator.admin_users = {'admin'}
c.Authenticator.admin_groups = {'staff'}
# defaults for backward compat < 5.0
c.Authenticator.allow_all = True
c.Authenticator.allow_existing_users = True

c.ConfigurableHTTPProxy.debug = True
EOF

F=/usr/local/etc/run-jhub.sh
printf '#!/bin/ksh93
# Simple script to run jupyterhub, usually used on unattended [re]boot.
if (( ${ id -u ; } == 0 )); then
    print -u2 'This script should not be run as root!'
    exit 99
fi
cd ~ && pwd || exit 1
export JUPYTER_PATH='"${PU_BASE}"'
export PATH=${JUPYTER_PATH}/bin:${PATH}
export PYTHONPATH=${JUPYTER_PATH}/lib/python3.10/site-packages
export NPM_CONFIG_GLOBALCONFIG='"${NPM_CONFIG_GLOBALCONFIG}"'
export HOST=${ uname -n; }
#env

[[ ${LOGLEVEL} =~ ^(DEBUG|INFO|WARN|ERROR|CRITICAL)$ ]] || LOGLEVEL='WARN'

exec "${JUPYTER_PATH}/bin/jupyterhub" \
    -f "${JUPYTER_PATH%/*}/etc/jhub_cfg.py" \
    --log-level=${LOGLEVEL} \
    >~${LOGNAME}/jupyterhub.log 2>&1 &
'       >$F
chmod 0755 $F

F=${PU_BASE}/bin/sudospawner-singleuser
printf '#!/bin/bash -l

unset HTTP_PROXY HTTPS_PROXY
case "$( lsb_release -rs )" in
    22.04) export PY_VERSION=3.10 ;;
    20.04) export PY_VERSION=3.8 ;;
    18.04) export PY_VERSION=3.6 ;;
esac


PYTHONPATH="${PYTHONPATH}:'"${PU_BASE}"'/lib/python${PY_VERSION}/site-packages"
exec '"${PU_BASE}"'/bin/jupyterhub-singleuser "$@"
'           >$F
chmod 0755 $F

F=/etc/systemd/system/jhub.service
printf '[Unit]
Description=Jupyterhub
After=network.target auditd.service

[Service]
Type=forking
User='"${JHUB_RUNNER}"'
WorkingDirectory=~
Environment='LOGLEVEL=WARN'
# Allow to overwrite LOGLEVEL
EnvironmentFile=-/etc/default/jhub
RuntimeDirectory=jhub
ExecStart=/usr/local/etc/run-jhub.sh ${LOGLEVEL}

StartLimitBurst=5
StartLimitInterval=10
Restart=always
RestartSec=1

ExecStop=/bin/kill -s SIGHUP $MAINPID
TimeoutSec=10

[Install]
WantedBy=multi-user.target
'       >/tmp/svc
sudo cp svc $F

typeset F=/etc/sudoers.d/jupyterHub
printf '# /etc/sudoers.d/jupyterhub
# Allow user "juppy" to run on any host "sudospawner" without
# asking for a password as any user who is part of the group "jupyter".
# Check "/etc/nsswitch.conf" - usually the ldap based sudo roles are used.
'"${JHUB_RUNNER}"' ALL=(%jupyter) NOPASSWD:SETENV: '"${PU_BASE}"'/bin/sudospawner
'       >/tmp/jhub.sudo
sudo cp /tmp/jhub.sudo $F

sudo useradd -u 123 -g 2 -c 'JupiterHub Service' -m -r ${JHUB_RUNNER}
sudo systemctl daemon-reload
sudo systemctl enable jhub
sudo systemctl start jhub
```

#### Expected behaviour
The user should see the Notebook UI page.

#### Actual behaviour
The user sees a '404: Not found' page.

### Your personal set up
 - Setup: see `How to reproduce`

 - OS: Ubuntu 22.04 (jammy)
 - Version(s): Python 3.10 minimal as shipped with Ubuntu
```
alembic==1.13.2
annotated-types==0.7.0
anyio==4.4.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
attrs==23.2.0
Babel==2.15.0
beautifulsoup4==4.12.3
bleach==6.1.0
certifi==2024.6.2
certipy==0.1.3
cffi==1.16.0
charset-normalizer==3.3.2
comm==0.2.2
cryptography==42.0.8
dbus-python==1.2.18
debugpy==1.8.2
decorator==5.1.1
defusedxml==0.7.1
exceptiongroup==1.2.1
executing==2.0.1
fastjsonschema==2.20.0
fqdn==1.5.1
greenlet==3.0.3
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
idna==3.7
ipykernel==6.29.4
ipython==8.25.0
ipywidgets==8.1.3
isoduration==20.11.0
jedi==0.19.1
Jinja2==3.1.4
json5==0.9.25
jsonpointer==3.0.0
jsonschema==4.22.0
jsonschema-specifications==2023.12.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client==8.6.2
jupyter_core==5.7.2
jupyter_server==2.14.1
jupyter_server_terminals==0.5.3
jupyterhub==5.0.0
jupyterlab==4.2.3
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.2
jupyterlab_widgets==3.0.11
Mako==1.3.5
MarkupSafe==2.1.5
matplotlib-inline==0.1.7
mistune==3.0.2
nbclient==0.10.0
nbconvert==7.16.4
nbformat==5.10.4
nest-asyncio==1.6.0
netifaces==0.11.0
notebook==7.2.1
notebook_shim==0.2.4
oauthlib==3.2.2
overrides==7.7.0
packaging==24.1
pamela==1.1.0
pandocfilters==1.5.1
parso==0.8.4
pexpect==4.9.0
platformdirs==4.2.2
prometheus_client==0.20.0
prompt_toolkit==3.0.47
psutil==6.0.0
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.22
pydantic==2.7.4
pydantic_core==2.18.4
Pygments==2.18.0
PyGObject==3.42.1
pyOpenSSL==24.1.0
python-apt==2.4.0+ubuntu2
python-dateutil==2.9.0.post0
python-json-logger==2.0.7
PyYAML==5.4.1
pyzmq==26.0.3
qtconsole==5.5.2
QtPy==2.4.1
referencing==0.35.1
requests==2.32.3
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.18.1
Send2Trash==1.8.3
six==1.16.0
sniffio==1.3.1
soupsieve==2.5
SQLAlchemy==2.0.31
stack-data==0.6.3
sudospawner @ git+https://github.com/jupyter/sudospawner@adc6298ddf2329bf50161178c91c87c54c637568
systemd-python==234
terminado==0.18.1
tinycss2==1.3.0
tomli==2.0.1
tornado==6.4.1
traitlets==5.14.3
types-python-dateutil==2.9.0.20240316
typing_extensions==4.12.2
ubuntu-advantage-tools==8001
uri-template==1.3.0
urllib3==2.2.2
wcwidth==0.2.13
webcolors==24.6.0
webencodings==0.5.1
websocket-client==1.8.0
widgetsnbextension==4.0.11
```

#### Configuration
```python
c = get_config()

c.JupyterHub.base_url = '/'.join([ '/jupyter', os.environ['HOST'] ]) 
c.JupyterHub.shutdown_on_logout = True
c.JupyterHub.spawner_class = 'sudospawner.SudoSpawner'

c.Spawner.debug = True
c.Spawner.notebook_dir = '~/'
c.Spawner.args = ['--ServerApp.allow_origin=*','--log-level=DEBUG','--debug']
#c.Spawner.env_keep = [ 'PYTHONPATH', 'CUDA_PATH' ]

# defaults for backward compat &lt; 5.0
c.Authenticator.allow_all = True
c.Authenticator.allow_existing_users = True
c.Authenticator.admin_users = {'admin'}
c.Authenticator.admin_groups = {'staff'}
```
</details>

<details><summary>Logs</summary>
No errors in logs :-(
</details>

**Comment by manics** [comment]
Does this only occur with sudospawner, or can you reproduce it with either the default or `simple` spawners? 
https://jupyterhub.readthedocs.io/en/stable/contributing/setup.html#using-dummyauthenticator-simplelocalprocessspawner

**Comment by jelmd** [comment]
Haven't tried, yet. It would exec as unprivileged user (`juppy` in this case) and thus no-one is able to login (expect juppy if one gives him a valid password)?

Anyway, if a casual user starts `jupyter` by himself via CLI and e.g. connects via ssh tunnel, it works as expected, i.e. sees no 404 page but the notebook UI.

**Comment by jelmd** [comment]
Tried with `c.JupyterHub.spawner_class = 'simple'` - same thing. To verify I removed the whole /usr/local/jupyter and re-installed it using the attached script. No change except that now  after launching the server the user lands on `http://localhost:8000/jupyter/${hostname}/user/${username}/` (trailing `tree` is missing) where `A Jupyter Server is running.` gets displayed. If one appends the missing `tree` to the URL, one gets back the 404 error page.

[jhub-install.txt](https://github.com/user-attachments/files/16164484/jhub-install.txt)

**Comment by manics** [comment]
I've tried to run your installation script in a clean environment using Docker:
```
docker run -it --rm ubuntu:22.04
```
```
apt-get install npm python3 python3-pip wget curl sudo ksh93u+m lsb-core

useradd -m jupyter 
echo 'jupyter ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/jupyter

su - jupyter
```
```
wget https://github.com/user-attachments/files/16164484/jhub-install.txt
ksh93 jhub-install.txt
```
But the script fails with this error:
```
### installJsProxy ###############################################
jhub-install.txt[394]: doMain[336]: installJsProxy: line 78: usr/bin/node: divide by zero
### installConfig ###############################################
jhub-install.txt[394]: doMain[336]: installConfig[116]: G: not found
jhub-install.txt[394]: doMain[336]: installConfig[128]: /usr/local/etc/jhub4_cfg.py: cannot create [Permission denied]
jhub-install.txt[394]: doMain[336]: installConfig[153]: /usr/local/etc/run-jhub.sh: cannot create [Permission denied]
```
Presumably you've got other dependencies or configuration already setup on your system- do you have instructions for those?

**Comment by jelmd** [comment]
Hmmm, thanx for trying it out. Because I'm still trying out things, the script is in the flux and some errors sometimes sneak in ... I've attached a new version, which gives you a little bit more flexibility and have the errors fixed (AFAICS).

So to install the software and the service on the same container/zone, run as admin user (it calls sudo if needed):
```
wget -O /tmp/jhub-install.sh https://github.com/user-attachments/files/16325285/jhub-install.txt
chmod 0755 /tmp/jhub-install.sh
# adjust JHUB_RUNNER, ADMINGRPS, ADD_ADMINS. E.g.
sed -i -e '/^JHUB_RUNNER=/ s/=.*/="jupyter"/' /tmp/jhub-install.sh
/tmp/jhub-install.sh
/tmp/jhub-install.sh -S
sudo systemctl start jhub
```
If in doubt, add option `-n` (this just prints out, what it would do) or `-h` to see add. options.

[jhub-install.txt](https://github.com/user-attachments/files/16325285/jhub-install.txt)

**Comment by jelmd** [comment]
OMG, found the reason: jupyterhub uses dumb hard coded values ([SYSTEM_CONFIG_PATH](https://github.com/jupyter/jupyter_core/blob/v5.7.2/jupyter_core/paths.py#L304) and [SYSTEM_JUPYTER_PATH](https://github.com/jupyter/jupyter_core/blob/v5.7.2/jupyter_core/paths.py#L225)) to lookup "apps" like notebook etc. and related resources instead of being smart and use `${INSTALLDIR}/etc/jupyter` and `${INSTALLDIR}/share/jupyter` respectively.

So if it is too hard to determine jupyter[-server]'s INSTALLDIR on startup and adjust the mentioned vars, there should be at least a real config option (i.e. not just env vars) to be able to tell it the truth and avoid looking up stuff within wrong directories.

**Comment by minrk** [comment]
The system-wide paths are not related to installation because they are the system-wide paths. I think that's a red herring. Jupyter uses `sys.prefix` and [site.getuserbase](https://docs.python.org/3/library/site.html#site.getuserbase) (aka PYTHONUSERBASE) to look for installation-specific paths. It doesn't use ${INSTALLDIR}, because that's not a thing in Python. What are the outputs of:

```
python3 -m site
```

and 

```
jupyter --paths
```

in your user environment (when run via sudo, etc.)? Reading through, I would expect the $PYTHONUSERBASE env that you've set to have the desired effect, but is that env still set in the sudo user's environment?

Some unusual installation schemes don't reliably put files in standard locations, and Python doesn't reliably record these things. Those unusual situations are what the configuration options (i.e. environment variables) are for. So if you install to an unrecognized prefix, just like you might have to tell Python about it with $PYTHONPATH, you can tell Jupyter about them with `JUPYTER_PATH=$PREFIX/share/jupyter` (for data files) and `JUPYTER_CONFIG_PATH=$PREFIX/etc/jupyter` (for config files).

**Comment by jelmd** [comment]
> The system-wide paths are not related to installation because they are the system-wide paths.

Not sure what this means, but if an app gets installed in `/x/y` it should lookup its extension beneath this or in explicitly configured/named directories, only - and nowhere else. The only exception is `/etc/name{/|.extension}` if INSTALLDIR == /usr or it is explicitly documented. Looking up stuff in unrelated directories is dangerous and may have an severe impact on security as well as the environment of the users (causing their apps to behave in a very strange manner/unpredictable/...)-

> I think that's a red herring. Jupyter uses `sys.prefix` and [site.getuserbase](https://docs.python.org/3/library/site.html#site.getuserbase) (aka PYTHONUSERBASE) to look for installation-specific paths. It doesn't use ${INSTALLDIR}, because that's not a thing in Python.

But we do not talk about python but an application (which is written in a language, which imposes more or less unwanted side effects to its users, yes). And the application gets installed in ${INSTALLDIR}. Blaming the interpreter/language for breaking security/functionality of an app is not fair, because it just does [not], what the app programmer instructed it to [not] do.

In ksh93 scripts one may use the `${.sh.file}` to determine the script's INSTALLDIR on the fly.

In app written in C or C++ one may instruct the loader via the Symbol `$ORIGIN` where to lookup required libraries, e.g.
```
# readelf -d /usr/lib/x86_64-linux-gnu/libLLVM-15.so |grep RUNPATH
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib]
```
or one may use something like `int olen = readlink("/proc/self/exe", my_origin, sizeof(my_origin));` to determine its installdir on the fly.

This does of course not work for python scripts, but since the interpreter loads the files, it should know their location and so I guess, there is probably a way for the app to find out the pathname of the "running" file, too. Unfortunately I'm almost clueless wrt. python, so can't really help with it. 

> What are the outputs of:

```
admin ~ > python3 -m site
sys.path = [
    '/local/home/admin',
    '/usr/lib/python310.zip',
    '/usr/lib/python3.10',
    '/usr/lib/python3.10/lib-dynload',
    '/usr/lib/python3/dist-packages',
]
USER_BASE: '/local/home/admin/.local' (exists)
USER_SITE: '/local/home/admin/.local/lib/python3.10/site-packages' (doesn't exist)
ENABLE_USER_SITE: True
```

> and

```
admin ~ > jupyter --paths
jupyter: Command not found.

setenv JUPYTER_PATH /usr/local/jupyter
set path = ( ${JUPYTER_PATH}/bin $path )
setenv PYTHONPATH ${JUPYTER_PATH}/lib/python3.10/site-packages
setenv NPM_CONFIG_GLOBALCONFIG ${JUPYTER_PATH}/npmrc

admin ~ > jupyter --paths
config:
    /local/home/admin/.jupyter
    /local/home/admin/.local/etc/jupyter
    /usr/etc/jupyter
    /usr/local/jupyter/etc/jupyter
    /etc/jupyter
data:
    /usr/local/jupyter
    /local/home/admin/.local/share/jupyter
    /usr/local/jupyter/share/jupyter
    /usr/share/jupyter
runtime:
    /local/home/admin/.local/share/jupyter/runtime
```
This is obviously the already quick and dirty patched variant, i.e. `/usr/local` replaced with `/usr/local/jupyter`.

> in your user environment (when run via sudo, etc.)?

Same but `/local/home/admin/` replaced with `~${LOGNAME}`. Because client (alias notebooks, terminals, etc.) are not properly separated from the server environment, we patch the mediator.py to pass PYTHONPATH env var, otherwise it would not work.

> Reading through, I would expect the $PYTHONUSERBASE env that you've set to have the desired effect, but is that env still set in the sudo user's environment?

No, PYTHONUSERBASE is not set at all, because this would have a negative impact on user experience. Most of our students have never touched a *x system and thus their env needs to be as clean as possible to be able to get re-producible staff no matter, whether jupyter* is installed or not.  

> Some unusual installation schemes don't reliably put files in standard locations, and Python doesn't reliably record these things.

The language [interpreter] should not take care of it, but the application should! Also `unusual installation schemes` is probably the view of a windows user. On *x systems it is quite common to separate application by installing them side-by-side in separate directories and thus keeping the system clean, unaffected and provide its users the opportunity to really have the control and not being a slave of their system. E.g. just have a look at `/usr/lib/` or `/usr/lib/jvm/`. Also see [Linux FHS](https:// [refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#usrlibLibrariesForProgrammingAndPa). And yes, it is a more or less severe security problem to blindly read and execute stuff from directories, where the app is actually not installed ...

> Those unusual situations are what the configuration options (i.e. environment variables) are for. So if you install to an unrecognized prefix, just like you might have to tell Python about it with $PYTHONPATH, you can tell Jupyter about them with `JUPYTER_PATH=$PREFIX/share/jupyter` (for data files) and `JUPYTER_CONFIG_PATH=$PREFIX/etc/jupyter` (for config files).

If I read the source correctly, setting JUPYTER_PATH and JUPYTER_CONFIG_PATH is not the same because they would be used as 1st place to lookup in contrast to SYSTEM_JUPYTER_PATH and SYSTEM_CONFIG_PATH. Also Python/the app would still lookup things in the wrong directories (i.e. /usr/local/, /usr/share) and may have a negative impact on the app's stability, security, ..., right?

**Comment by minrk** [comment]
>But we do not talk about python but an application

This is I think the key point of misunderstanding, because I disagree. Jupyter is a Python package and installed with Python packaging tools, so it only has access to the information the Python packaging tools provide during installation. _No_ Jupyter-controlled code executes whatsoever at install time thanks to Python wheels. There is no Jupyter installer, there is no ${INSTALLDIR} available to Jupyter. The closest equivalent of ${INSTALLDIR} available _is_ sys.prefix (and $PYTHONUSERBASE), so that's what Jupyter uses, but in your situation you've specified one environment at install time in a way that is _not available_ at runtime. Isolating Jupyter should not be considered different to isolating numpy or matplotlib or sphinx or any other Python package.

The standard way to isolate a Jupyter installation is the same as it is for all Python packages: virtualenvs. I don't think you'd need any environment variables, PYTHONPATH, etc. if you did `python3 -m venv $PREFIX` and `$PREFIX/bin/pip install ...` to create the isolated installation. This would ensure `sys.prefix` is set appropriately, so Jupyter would find support files (in `ENV_CONFIG_PATH`, etc.).

**Comment by jelmd** [comment]
> > But we do not talk about python but an application
> 
> This is I think the key point of misunderstanding, because I disagree.
Probably.
> Jupyter is a Python package and installed with Python packaging tools, so it only has access to the information the Python packaging tools provide during installation.

Wait: Who instructs the interpreter to load extensions? Who introduces a notion of "config dir" at all? Who decides, which paths will be used to lookup extensions? I think [jupyter_path()](https://github.com/jupyter/jupyter_core/blob/v5.7.2/jupyter_core/paths.py#L232) answers it w/o any doubt. So it is clearly application behavior and it doesn't matter at all, which tools or package manager got used to install it.

> _No_ Jupyter-controlled code executes whatsoever at install time thanks to Python wheels. There is no Jupyter installer, there is no ${INSTALLDIR} available to Jupyter.

As already said: it doesn't matter at all, what is used to install it (BTW: sys global packages usually get installed by the distro package manager, which might be apt, rpm, ... and not python tools).  Not sure about what python package installers do (whether they have/use post-install, etc. scripts), but there is no need to modify a package because an application should be able to find out its installdir on the fly by itself (sysadmins call such software relocatable BTW)!

E.g. try out this little ksh script - just copy it wherever you want, it will always tell you the path, where it got called from:
```sh
#!/bin/ksh93

print "My origin is: ${.sh.file%/*}"
```
Why should any install tool need to modify it? It works out of the box. Same thing in C - have a look at the attached [c_origin.jsonc](https://github.com/user-attachments/files/16602137/c_origin.jsonc) (just replace the extension `json` with `c` - github does not allow to attach files with extension `c`). Compile it on Linux with `gcc -O -o c_origin c_origin.c -lbsd`, copy c_origin wherever you want and execute it. So there is no need to hard code arbitrary paths.

> The closest equivalent of ${INSTALLDIR} available _is_ sys.prefix (and $PYTHONUSERBASE), so that's what Jupyter uses, but in your situation you've specified one environment at install time in a way that is _not available_ at runtime. Isolating Jupyter should not be considered different to isolating numpy or matplotlib or sphinx or any other Python package.

PYTHONUSERBASE has a severe impact on the users trying to write python apps. It is quite different to SYSTEM_CONFIG_PATH and SYSTEM_JUPYTER_PATH, right? And the name implies, it is a user related setting, doesn't it?

> The standard way to isolate a Jupyter installation is the same as it is for all Python packages: virtualenvs. I don't think you'd need any environment variables, PYTHONPATH, etc. if you did `python3 -m venv $PREFIX` and `$PREFIX/bin/pip install ...` to create the isolated installation. This would ensure `sys.prefix` is set appropriately, so Jupyter would find support files (in `ENV_CONFIG_PATH`, etc.).

Well, last time I had a look at venv (several years ago), it just adjusts env vars and starts the user's SHELL with it. Beside the sugar around it, it is finally equivalent to this one-liner:
```sh
APPDIR=/tmp/foo/bar PATH="${APPDIR}/bin PYTHONPATH="${APPDIR}/lib/python3.10/site-packages:${PYTHONPATH} PYTHONUSERBASE="${APPDIR}" LD_LIBRARY_PATH="${APPDIR}/lib[/64]:${LD_LIBRARY_PATH}" /bin/bash
```
So there is no need at all to install or run venv. However, for people which do not know the tools they use, it may make their life easier - so I do not really care, what they use, the result is the same. Anyway, these are env vars to help the language interpreter to lookup stuff like imports, etc.. If an application uses "plugins" or "extension" or whatever one calls it, it is IMHO pretty risky to just rely on env vars and hard coded paths, only.

So conclusion is still, that any app (incl. jupyterhub) should determine its INSTALLDIR on the fly and use it to find its own "plugins" instead of blindly using unrelated dirs like /usr/[local/]etc/jupyter and /usr/[local/]share/jupyter.

**Comment by manics** [comment]
This is out of the control of JupyterHub. JupyterHub launches singleuser servers such as JupyterLab/server/notebook, but it doesn't control how they pick-up their configuration.

Although there are "standards" every software vendor has their own interpretation of the standard. This might be intentional because the standard didn't fit, or because a standard didn't exist at the time, or a standard has changed, or that the developers weren't aware, or that a piece of software has changed and applies to multiple disciplines with different expectations.

You've brought up some good points, and it's a worthwhile discussion, but I think it should be brought up in a place where the maintainers of JupyterLab/server, and the wider community since they'll be affected by any change, will see it. How about if we move the discussion to the [Jupyter community forum](https://discourse.jupyter.org/) and close this issue?
https://discourse.jupyter.org/

**Comment by minrk** [comment]
Agreed. There is not anything actionable for JupyterHub here since this is a general Jupyter topic.

I'll just restate that I believe venvs address this situation entirely, because they set the (Python) variables that tools like pip install to _and_ that Python packages like Jupyter use to find things, and they are the standard way to do these things for all Python packages, Jupyter included. It is not the case that a venv is equivalent to setting some env vars (no env vars are required).

**Comment by jelmd** [comment]
> This is out of the control of JupyterHub. JupyterHub launches singleuser servers such as JupyterLab/server/notebook, but it doesn't control how they pick-up their configuration.

Ehmm, as mentioned above it is jupyterhub which dictates, where to lookup "extensions". And as shown in this [patch](https://github.com/jelmd/jsd-helper/blob/main/syspath.patch) it can be fixed in a dirty way, or a python expert could probably find a smart way to determine the right directory on the fly and use this one (like I do in my [jsd-helper](https://github.com/jelmd/jsd-helper/blob/main/jsd-helper.c#L209) which BTW allows one to run the jupyterhub service incl. systemdSpawner as an unprivileged user without any sudo or similar pain).

If python does not have a way to determine the file, whose code gets currently executed, one may write a little utility in C (code already provided above) side-by-side of the jupyterhub script and call this to obtain the directory, which should be used. 

> Although there are "standards" every software vendor has their own interpretation of the standard.

Exactly! And for Python packages it seems to be ${BASEDIR}/{bin,etc,share/${APPNAME},lib/${PYTHON_VERSION}/site-packages/${MODULE}}. So damn easy to determine them on the fly.

> This might be intentional because the standard didn't fit, or because a standard didn't exist at the time, or a standard has changed, or that the developers weren't aware, or that a piece of software has changed and applies to multiple disciplines with different expectations.

Doesn't matter. The app developer dictates, how the software gets packaged and thus installed on the system, and therefore the app knows where the bundled files can be found, once it has its BASEDIR alias INSTALLDIR properly determined. If it uses the wrong/dangerous way/API to do that, it is clearly the app's fault and hence a bug which needs to be fixed.

> You've brought up some good points, and it's a worthwhile discussion, but I think it should be brought up in a place where the maintainers of JupyterLab/server, and the wider community since they'll be affected by any change, will see it.

I think most users would probably not notice this change, because if fixed it does the right thing and will find the bundle extension by default, no matter where it got installed. The only change might be, that now users having it installed in a "non-default" location do not need to pollute the user's environment anymore by setting env vars to questionable values. So I'm not sure, what one should need to discuss there.

> How about if we move the discussion to the [Jupyter community forum](https://discourse.jupyter.org/) and close this issue? https://discourse.jupyter.org/

Discussion - hmm, not sure, whether it is worth the time (because I think, everything has already been said, examples/fixes shown), but ok. Closing this Issue is IMHO not an option because it is a bug/security problem and needs to be fixed. Perhaps renaming it to something like "SYSTEM_JUPYTER_PATH and SYSTEM_CONFIG_PATH should be determined on the fly" is probably ok.

**Comment by manics** [comment]
> Ehmm, as mentioned above it is jupyterhub which dictates, where to lookup "extensions". And as shown in this patch it can be fixed in a dirty way

JupyterHub runs a singleuser server for each user, which is a minimal wrapper around jupyter-server. The patch you've linked to is for jupyter-core, which is used by jupyter-server, not JupyterHub. Can you point to where you think JupyterHub is overriding how jupyter-server behaves?

**Comment by jelmd** [comment]
> Agreed. There is not anything actionable for JupyterHub here since this is a general Jupyter topic.

Not sure, where the `lib/python3.10/site-packages/jupyter_core/paths.py` comes from. I just installed jupyterhub and this has obviously a problem ... ;-)


> I'll just restate that I believe venvs address this situation entirely, because they set the (Python) variables that tools like pip install to _and_ that Python packages like Jupyter use to find things, and they are the standard way to do these things for all Python packages, Jupyter included.

And it is the right way to pollute the user's environment. Again, if an app uses the wrong/questionable tools/APIs to determine sensible data, it is the fault of the application, and not the problem of the tool/API ... 

> It is not the case that a venv is equivalent to setting some env vars (no env vars are required).

If one gets picky yes, venv creates/modifies just scripts and only when the users starts one/"activates" its "virtual environment", the related script sets the mentioned env vars and starts the desired shell. Or has it been changed within the last couple of years?

**Comment by minrk** [comment]
`jupyter_core`, which defines these paths and where Jupyter Server looks for extensions, is not part of JupyterHub, it is part of [Jupyter Core](https://github.com/jupyter/jupyter_core). This relationship between these projects is not always clear, but JupyterHub does not generally dictate how Jupyter behaves, as we've been trying to communicate. If you want to open an Issue about how Jupyter locates files, you may do it [there](https://github.com/jupyter/jupyter_core) (unfortunately we can't migrate GitHub Issues across different orgs). I will point out that the System paths are _not_ the paths related to the installation (that would be `ENV_`), but specifically the paths meant to be shared across environments on a system. Adding an option to disable them is reasonable (and proposed [here](https://github.com/jupyter/jupyter_core/issues/212)), but they should not be made sensitive to the installation path, since insensitivity to the install is the point of them. The `ENV_` paths are what are meant to be relative to the installation, using standard methods like sys.prefix, etc.., but nowadays we might be able to use tools like `importlib.metadata`, which were not available when this was first implemented (and are still not _always_ available, but increasingly so).

> And it is the right way to pollute the user's environment.

The opposite is true. It is the right way to install Python things _without touching_ the user's environment.

> the related script sets the mentioned env vars and starts the desired shell. Or has it been changed within the last couple of years?

I'm not sure when that was, but at least not since `venv` was added to Python 3.3, 12 years ago. If you `/path/to/env/bin/some-executable`, everything works and no environment variables are set, no scripts are modified by the env. 'Activating' an env is not required. If you activate an env via `source $env/bin/activate`, only two environment variables are set:

1. `$VIRTUAL_ENV` - a convenience variable, not actually used by Python for anything. Sometimes used to decorate shell prompts
2. `$PATH` - adds $env/bin to front. not relevant if you launch things with absolute paths, or have inserted the env anywhere on your PATH by other means

neither of which are necessary to use applications installed in an env.

In real-world Python usage, virtualenvs have replaced approximately all custom Python installation, in part because they solve the exact problems you are having. Paths are resolved relative to the installation, just like you want. Envs are the Python way to do it. Not just for Jupyter, but for _all_ Python applications. I strongly recommend you consider trying installation with a virtualenv instead of using some environment variables set during installation but not at runtime.

I'm closing this as off topic for jupyterhub. I'll finish with a reminder of Jupyter's [Code of Conduct](https://jupyter.org/governance/conduct/code_of_conduct.html).
