### ISSUE TITLE
PAM Authentication failing after upgrading from 22.04 to 24.04

### ISSUE THREAD

**Issue by johnbarney** [jupyterhub/jupyterhub#4854]
### Bug description

I am testing JupyterHub upgrades from Ubuntu 22.04 to 24.04. On my test machine my PAM authentication for all users seems to not work. I did get an error message about pam_lastlog but I was able to modify /etc/pam.d/login and comment out `session    optional   pam_lastlog.so` to solve this issue to verify it was not the problem. I am logged into the machine via SSH as my user using my password by disabling temporarily renaming my privatekey so I can validate PAM is working properly on the machine. The user table is handled by an agent running on the machine, but I have verified a manually added user also cannot log in to rule out some strange interaction with the accounts the agent is managing. None of the logs seem to give any hints. It seems like Python has lost track of how to communicate with PAM on the machine despite Hub running as root.

### How to reproduce

Login and fail

#### Expected behaviour

I expect to login

#### Actual behaviour

Unable to login

### Your personal set up

I install JupyterHub on these nodes by switching to root, creating a venv for Python3 in /opt/jupyterhub then pip installing JupyterHub, IdleCuller and DockerSpawner to the venv. I then invoke the JupyterHub binary via a script /etc/init.d/jupyterhub which is done at boot. The init script puts the venv bin first in PATH.

 - OS: Ubuntu 24.04
 - Version(s):

```
$ /opt/jupyterhub/bin# ./python -m jupyterhub --version
5.0.0
$ /opt/jupyterhub/bin# ./python --version
Python 3.12.3
```

<details><summary>Full environment</summary>

```
/opt/jupyterhub/bin# ./pip list
Package                   Version
------------------------- --------------
alembic                   1.13.2
annotated-types           0.7.0
arrow                     1.3.0
attrs                     23.2.0
certifi                   2024.7.4
certipy                   0.1.3
cffi                      1.16.0
charset-normalizer        3.3.2
cryptography              43.0.0
docker                    7.1.0
dockerspawner             13.0.0
escapism                  1.0.1
fqdn                      1.5.1
greenlet                  3.0.3
idna                      3.7
isoduration               20.11.0
Jinja2                    3.1.4
jsonpointer               3.0.0
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
jupyter-events            0.10.0
jupyterhub                5.0.0
jupyterhub-idle-culler    1.3.1
Mako                      1.3.5
MarkupSafe                2.1.5
oauthlib                  3.2.2
packaging                 24.1
pamela                    1.1.0
pip                       24.0
prometheus_client         0.20.0
pycparser                 2.22
pydantic                  2.8.2
pydantic_core             2.20.1
pyOpenSSL                 24.2.1
python-dateutil           2.9.0.post0
python-json-logger        2.0.7
PyYAML                    6.0.1
referencing               0.35.1
requests                  2.32.3
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.19.0
six                       1.16.0
SQLAlchemy                2.0.31
tornado                   6.4.1
traitlets                 5.14.3
types-python-dateutil     2.9.0.20240316
typing_extensions         4.12.2
uri-template              1.3.0
urllib3                   2.2.2
webcolors                 24.6.0
```
</details>

<details><summary>Configuration</summary>

```python
# JupyterHub Configuration File
import sys
import docker


c.JupyterHub.ip = '<snip>'
c.JupyterHub.hub_ip = '<snip>'
c.JupyterHub.port = 443
c.JupyterHub.ssl_key = '<snip>'
c.JupyterHub.ssl_cert = '<snip>'

# JupyterHub Spawner Configuration
c.JupyterHub.spawner_class = 'dockerspawner.SystemUserSpawner'

c.Spawner.mem_limit = '60G'
c.Spawner.default_url = '/lab'

c.DockerSpawner.image = 'jupyterhub-nvidia'
c.DockerSpawner.remove_containers = True
c.DockerSpawner.run_as_root = True

c.DockerSpawner.extra_host_config = {
    "device_requests": [
        docker.types.DeviceRequest(
            count=-1,
            capabilities=[["gpu"]],
        ),
    ],
}

c.DockerSpawner.volumes = {
    '/media/datasets' : '/media/datasets',
    '/media/engineering' : '/media/engineering',
}

# Persisting conda envs
def pre_spawn_hook(spawner):
  import logging
  from pathlib import Path
  user = spawner.user.name
  home_dir = f'/home/{user}'
  condarc_path = f'{home_dir}/.condarc'
  logging.info(f"Generating .condarc file in {condarc_path}")
  with open(condarc_path, 'w') as f:
    f.write('envs_dirs:\n')
    f.write(f'  - {home_dir}/my-conda-envs/\n')
  jupyter_config_path = f'{c.Spawner.env.to_dict().get("JUPYTER_CONFIG_DIR", f"{home_dir}/.jupyter")}/jupyter_config.json'
  logging.info(f"Generating jupyer_config.json file in {jupyter_config_path}")
  Path(jupyter_config_path).parent.mkdir(parents=True, exist_ok=True)
  with open(jupyter_config_path , 'w') as f:
    f.write('{"CondaKernelSpecManager": {"kernelspec_path": "--user"}}')
c.Spawner.pre_spawn_hook = pre_spawn_hook

# JupyterHub Services
c.JupyterHub.services = [
    {
        'name': 'idle-culler',
        'admin': True,
        'command': [sys.executable, '-m', 'jupyterhub_idle_culler', '--timeout=259200'],
    } # Three day timeout
]
```
</details>

<details><summary>Logs</summary>

I've also verified no entries appear in /var/log/auth.log after a login attempt.

```
Jul 22 11:26:19 <snip> jupyterhub[23777]: [W 2024-07-22 11:26:19.889 JupyterHub auth:705] User 'john' not allowed.
Jul 22 11:26:19 <snip> jupyterhub[23777]: [W 2024-07-22 11:26:19.889 JupyterHub base:979] Failed login for john
```

</details>

**Comment by buti1021** [comment]
Hi @johnbarney, looks like we are having the same issue. Any infos on how to resolve/workaround? Thanks!

**Comment by johnbarney** [comment]
Our issue was unrelated to 22.04 to 24.04. It only seemed to be related because we also happened to do a Jhub update at the same time.

https://jupyterhub.readthedocs.io/en/latest/tutorial/getting-started/authenticators-users-basics.html

> Changed in version 5.0: If no allow config is specified, then by default nobody will have access to your Hub. Prior to 5.0, the opposite was true; effectively allow_all = True if no other allow config was specified.

I hope this helps in your case as well.

**Comment by buti1021** [comment]
Just tried downgrading as well and the first thing I saw in the logs afterwards was the information about that change. Thank you very much for your fast reply :)
