### ISSUE TITLE
Adding a user to Authenticator.blocked_users does not affect existing sessions

### ISSUE THREAD

**Issue by lahwaacz** [jupyterhub/jupyterhub#4861]
Consider this scenario:

- Some user account on JupyterHub gets breached and the admin decides to block this user account.
- The admin adds the username to `c.Authenticator.blocked_users`.
- This correctly blocks attempts to start a new session: the user gets `403 : Forbidden Sorry, you are not currently authorized to use this hub. Please contact the hub administrator.`
- However, this does not terminate existing sessions of the user and an intruder may happily keep them open for a long time.

Am I missing something? What is the expected mitigation path for this scenario?

**Comment by minrk** [comment]
It's true that `blocked_users` only affects login, not the underlying permission of the User. After blocking login, you can delete the user from the database via the admin page or API, which truly revokes all of their permissions, invalidates tokens, etc.

There is currently no _practical_ mechanism by which a user can exist in the database without default user permissions. It is technically _possible_ in that things should work correctly if a User has no permissions, but there is no official way for you to actually revoke those permissions except for user deletion. It is technically possible if you clear the user's `roles` via a dbutil shell (or script):

```
> python3 -m jupyterhub.dbutil shell
In [1]: user = db.query(orm.User).filter_by(name=name).one()
In [2]: user.admin = False # make sure they aren't a superuser
In [3]: user.roles = [] # revoke permissions
In [4]: user.groups = [] # revoke possible permission grants via group membership
In [5]: db.commit()
```

They shouldn't get any of these back except via explicit config or successful login.

I think it probably is appropriate for JupyterHub to revoke permissions and stop servers for blocked users on startup.
