### ISSUE TITLE
Tag Docker image as "onbuild" and create non-onbuild version

### ISSUE THREAD

**Issue by jlowin** [jupyterhub/jupyterhub#491]
Building a container that inherits from the JupyterHub dockerfile fails if `jupyterhub_config.py` is not available in the top-level directory. That's because the Dockerfile includes an `ONBUILD` instruction that copies the file from that location. While I totally understand (and need!) the ability to provide custom configurations, requiring `jupyterhub_config.py` to be in a fixed location seems overly restrictive. I would prefer, for example, to be able to stick it in a `config/` directory.

The dockerfile best practices document [recommends](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#onbuild) that images including an `ONBUILD` instruction add `-onbuild` to the image tag so that they can be told apart from a non-ONBUILD version.

I understand that creating a separate, non-ONBUILD dockerfile could create a little confusion for users at first, but I think the complexity is minimal compared to the surprise when the current image fails (and total lack of understanding unless one goes and reads the parent Dockerfile). If there were two versions, users could inherit the Dockerfile in a few ways, depending on their preferences:

1. The current approach with the config file at the top level, just adding "-onbuild" to the image

    ```docker
    FROM jupyter/jupyterhub-onbuild
    ...
    ```
1. Explicitly copying the file from an arbitrary location to the expected location

    ```docker
    FROM jupyter/jupyterhub
    COPY /path/to/jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py
    ...
    ```
1. Explicitly copying the file from an arbitrary location to an arbitrary location

    ```docker
    FROM jupyter/jupyterhub
    COPY /path/to/jupyterhub_config.py /other/path/to/jupyterhub_config.py
    ...
    CMD ["jupyterhub", "-f", "/other/path/to/jupyterhub_config.py"]
    ```

**Comment by minrk** [comment]
#521 moves onbuild to a derivative image.

**Comment by minrk** [comment]
@jlowin do you have any idea for how to make the onbuild container have the proper tags? I want jupyterhub-onbuild to inherit from jupyterhub, but always to have the *same* tag. I don't quite see how to make jupyterhub-onbuild:0.5 avoid building against jupyterhub:latest.

**Comment by jlowin** [comment]
@minrk I'm very sorry, I'm not sure!

**Comment by robnagler** [comment]
+1 

I would recommend using a build script, e.g.

```bash
set -e
if [[ ! $1 ]]: then
fi
version=$1
tag=jupyter/jupyterhub:$version
git clone https://github.com/juypter/juypterhub
cd jupyterhub
docker build -t $tag .
docker push jupyter/jupyterhub:$version
cat >> OEF
FROM $tag
ONBUILD ADD jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py
docker build -f Dockerfile.onbulid -t jupyter/jupyterhub-onbuild:$version .

**Comment by minrk** [comment]
@robnagler thanks, that's useful! I would much rather use Docker Hub automated builds than add another buildbot to keep track of, but I'll look into getting circle-ci to tag and push the onbuild images.

**Comment by robnagler** [comment]
Travis can [run docker builds and test them](http://bencane.com/2016/01/11/using-travis-ci-to-test-docker-builds/). It might be useful to build the images and then run your tests in containers. If the tests pass, you can then push to Docker Hub.

We tend to [use tox explicitly](https://github.com/radiasoft/pykern/blob/339ea8bfa043ba982978f569c2f1d2b7f02ae42c/pykern/pksetup.py#L115) to build and deploy. This keeps our travis.yml files quite short, and allows use alternative CI tools or run them from the command line easily.

We also [encapsulate image builds](https://github.com/radiasoft/containers) so that we can build Docker and Vagrant images from the same scripts.
