### ISSUE TITLE
Missing error message from lifecycle_hooks postStart (gitpuller)

### ISSUE THREAD

**Issue by BigFlagBurito** [jupyterhub/jupyterhub#4914]
### Bug description

The error message is missing in `spawn-pending` if something goes wrong in `lifecycle_hooks`.

### How to reproduce

1. Have a pulled git directory
2. Remove the .git in the directory (so that an extra error is generated)
3. Start a profile with a `lifecycle_hooks`
```
lifecycle_hooks:
  postStart:
    exec:
      command:
        - "sh"
        - "-c"
        - >
          mkdir -p "{dir}";
          chmod 755 "{dir}";
          cd "{dir}";
          gitpuller {url} main "{name}";
```

#### Expected behaviour

The `spawn-pending` should contain the exact error message from gitpuller or git.

#### Actual behaviour

Only the following is displayed:
- [Warning] PostStartHook failed
- [Normal] FailedPostStartHook

### Your personal set up

 - OS:
ubuntu 22.04
 - Version(s):
jupyterhub 4.1.5

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

Log from the user pod:

```
Entered start.sh with args: jupyterhub-singleuser
Running hooks in: /usr/local/bin/start-notebook.d as uid: 1000 gid: 100
Done running hooks in: /usr/local/bin/start-notebook.d
Running hooks in: /usr/local/bin/before-notebook.d as uid: 1000 gid: 100
Sourcing shell script: /usr/local/bin/before-notebook.d/10activate-conda-env.sh
Done running hooks in: /usr/local/bin/before-notebook.d
Executing the command: jupyterhub-singleuser
```

</body>
</html>

</details>

**Comment by consideRatio** [comment]
This is a k8s thing, i recall these hooks dont leave you in-logs-errors, but provide a k8s event or similar. / From mobile.

I rhink its not a bug or so with this project, but a k8s thing
