### ISSUE TITLE
Release 5.2.0 to flush out whats merged?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#4917]
@benz0li asked in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/3406#issuecomment-2385231233 for a release with dark mode toggle. We currently have z2jh and tljh beta releases out - is flushing 5.2.0 (with dark mode toggle, and more?) ok to do @minrk?

**Comment by benz0li** [comment]
> and more?

* https://github.com/jupyterhub/jupyterhub/pull/4904

**Comment by minrk** [comment]
While I think it's fine to make a release with what we have, I really want to push back very hard on the amount of work we are creating for ourselves in making these distribution releases. I feel very strongly that preparing a release for a distribution should not trigger a bunch of work to release dependencies as well. Either they are ready (i.e. already released) or they are not and should wait for the next distribution release.
