### ISSUE TITLE
Metrics conveying a distribution of spawned server lifetimes

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#4924]
I figure it could make sense to have a way to overview the distribution of server lifetimes in a JupyterHub native way.

In jupyterhub/grafana-dashboards, we have the panel looking like this:

![image](https://github.com/user-attachments/assets/6a9ac380-9eb6-4a36-83ab-cb8e18785a5a)

The query looks like this, and relies on kubernetes pod metrics rather than JupyterHub metrics.

```
(
  time()
  - (
    kube_pod_created
    * on (namespace, pod)  
  group(
    kube_pod_labels{label_app="jupyterhub", label_component="singleuser-server", namespace=~"$hub"}
  ) by (label_component, pod, namespace)
  )
)
```

**Comment by consideRatio** [comment]
This is showing "current server's" age, but its not showing a distribution of session lifetimes over a months time or similar - which was what I initially was thinking about.

Maybe a prometheus metric isn't suitable for providing a summary of server lifetime distributions though - because its a summary of separate events over a long duration of time (server start -> end would be one event).

I think for this, we need to process a set of events.

I'll go for a close for now.

**Comment by minrk** [comment]
If I've understood the goal correctly, if there is a prometheus metric that would be useful for this, it might be _on server stop_ add to a histogram with the full lifetime of the server. It wouldn't have a record of any active servers, so wouldn't replace the current metric, but would be a metric for historical information. It would be the same type of data as the start/stop metrics, which give us charts like [this](https://prometheus.ovh2.mybinder.org/graph?g0.expr=sum(increase(jupyterhub_server_spawn_duration_seconds_bucket%7Bstatus%3D%22success%22%7D%5B1h%5D))%20by%20(le)&g0.tab=0&g0.display_mode=heatmap&g0.show_exemplars=0&g0.range_input=6h):

<img width="1273" alt="Screenshot 2024-10-09 at 08 58 47" src="https://github.com/user-attachments/assets/3d9b4de9-e520-4d13-b168-712673c858e8">

 or [this](https://grafana.mybinder.org/d/hub-dashboard/jupyterhub-dashboard?orgId=1&var-PROMETHEUS_DS=b67087d4-25bd-41aa-8ecd-940252a85e24&var-hub=curvenote&viewPanel=8&from=now-12h&to=now):

<img width="966" alt="Screenshot 2024-10-09 at 08 59 33" src="https://github.com/user-attachments/assets/880ce4b0-7f96-41b4-9a14-69e7f3c27d02">

The only challenge I see with a histogram metric is that data is summarized into buckets and which buckets are sensible are going to be highly deployment specific. Allowing deployments to configure prometheus metric buckets is a bit of a pain, but not impossible.
