### ISSUE TITLE
Admin `Stop All` does not stop named servers

### ISSUE THREAD

**Issue by manics** [jupyterhub/jupyterhub#4926]
### Bug description

Admin `Stop All` does not stop named servers

### How to reproduce

1. Configure a hub with named servers
2. Login as an admin
3. Start the default singleuser server, and one or more named servers
4. Go to `/hub/admin`
5. See that multiple servers including named servers are running
6. Click `Stop All`
7. Default servers will be stopped, but named servers continue running.

Running servers:
![image](https://github.com/user-attachments/assets/feae7af5-3bf5-4c4d-b205-e2a6b892f1c9)
Named servers running after clicking `Stop All`:
![image](https://github.com/user-attachments/assets/c1773d43-34dd-4a83-bc8f-cfe59344f94f)

#### Expected behaviour

All servers including named servers should be stopped

#### Actual behaviour

Named servers aren't stopped

### Your personal set up

Dummy authenticator and SimpleLocalProcessSpawner, `main` branch.

**Comment by manics** [comment]
One option is to change the button to be a dropdown with two options:
- `Stop all servers`
- `Stop default servers only`
and similarly for the `Start ...` button.

Another option is to have the buttons behave differently. `Stop all` should stop _all_ servers, and I can't think of a reason for not wanting to stop named servers. On the other hand having `Start all` only start named servers could make sense for teaching, but if we go this route we should rename to to something like `Start all default servers`.

**Comment by minrk** [comment]
Yeah, I think this is just a bug where it's not quite iterating over the right thing. I don't think we need an option for the current accidental behavior.
