### ISSUE TITLE
?token=... is still visible on websockets

### ISSUE THREAD

**Issue by SarunasAzna** [jupyterhub/jupyterhub#4945]
Since version 5.0.0 we have ?token removed from url but it seems to be still visble on websocket requests.

First I found them at [jupyter-ai](https://github.com/jupyterlab/jupyter-ai) socket requests, but after little investigation it seems that the extension itself does not have anything to do with it.

In fact [jupyterhub/services/auth.py](https://github.com/jupyterhub/jupyterhub/blame/886ce6cbdfc00b66b45ac769e5ab2270abca3ef1/jupyterhub/services/auth.py#L727) has an exception for websockets:
```python
        ...
        if self.allow_token_in_url or fetch_mode == "websocket":
            return handler.get_argument("token", "")
       ....
```
Can we avoid this websocket exception or are there some specifics limitations for websockets?

**Comment by manics** [comment]
The docstring for `allow_token_in_url` explains
> Has no effect on websocket requests, which can only reliably authenticate via token in the URL, as recommended by browser Websocket implementations.
https://github.com/jupyterhub/jupyterhub/blob/886ce6cbdfc00b66b45ac769e5ab2270abca3ef1/jupyterhub/services/auth.py#L369-L390

There's a Jupyter Enhancement Proposal for how to avoid this:
https://github.com/jupyter/enhancement-proposals/pull/121

**Comment by SarunasAzna** [comment]
Thanks! sorry for bothering before reading docs...
