### ISSUE TITLE
Move last_activity tracking from the proxy to the notebook singleuser servers

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#502]
For a variety of reasons:
1. Allows notebooks to report themselves as busy if they have kernels that are blocked running code. This allows for the (common in our install so far) use case where people run multi-day computations on jupyterhub unattended and wouldn't want to be culled in the meantime.
2. Allows turning off last_activity_tracking from  proxy, which would improve performance in the short term and make distributed implementations easy in the long term.

**Comment by minrk** [comment]
Related: https://github.com/jupyter/notebook/issues/1241

**Comment by consideRatio** [comment]
I believe the Jupyter ecosystem now manages user activity sensibly, closing.
