### ISSUE TITLE
How to get an authorization token/cookie for making calls to JupyterHub API?

### ISSUE THREAD

**Issue by dominicfollett** [jupyterhub/jupyterhub#506]
I've been looking through the [API](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyter/jupyterhub/master/docs/rest-api.yml#!/default/post_users_name) and it notice it uses an API key for authorization. Is this the API key specified in the config? e.g.

```
c.JupyterHub.proxy_auth_token = '0bc02bede919e99a26de1e2a7a5aadfaf6228de836ec39a05a6c6942831d8fe5'
```

If it is, how is that set in the header when making an API call?
...
Currently I have only been able to make  calls to the API by pulling out the admin cookie from my browser session, and setting the call's header with: 

```
'referer': "127.0.0.1:8081/hub/",
'cache-control': "no-cache",
'cookie': "jupyter-hub-token=\"2|1:0|10:1460464624|17:jupyter-hub-token|44:ZjZmYzUzMTRlMjgzNDE0MzkzYjcwODQ2YjEyN2I4YjY=|9f2e40c810b8fb1744cb4e203bec24ea94f3cb82d75b3d097419aade3dbd10a7\""

```

What I am trying to do is get an access token/cookie for an admin user. Looking through the API spec I don't see any option to get an access token/cookie by supplying username & password.

**Comment by minrk** [comment]
proxy_auth_token is actually what JupyterHub uses to talk to the configurable-http-proxy API, not what you would use to talk to the Hub API. You can get a Hub token by running:

    jupyterhub token [username]

in the shell.

You can check out the [cull-idle example](https://github.com/jupyter/jupyterhub/blob/0.5.0/examples/cull-idle/cull_idle_servers.py#L35), but we use the Authorization header:

    Authorization: token SECRETTOKENHERE

**Comment by dominicfollett** [comment]
Thanks. Is there any chance that in future it will be possible to get a token for the Authorization header via an API call?

Is this something we can develop on a fork and contribute back to Hub, or do you have other plans for Hub?

**Comment by minrk** [comment]
The API call itself must be authorized, so you would need a token to get that token. The pluggable auth makes this tricky to do generally, except from a browser, where the existing auth mechanism could be used to authenticate the request to produce tokens.

As part of the services work (my current project, and the main milestone for 0.7), I will make it possible to pre-load auth tokens so that they can be generated and specified ahead of time, without having to create the Hub database and get tokens from that entrypoint.

**Comment by dominicfollett** [comment]
I was thinking of something along the lines of the following:

````py
    @gen.coroutine
    def post(self):
        data = self.get_json_body()
        if self.authenticator is not None:
          username = yield self.authenticator.authenticate(self, data)
          if username is None:
            raise web.HTTPError(403)
          user = self.find_user(username)
          api_token = user.new_api_token()
          self.write(json.dumps({"Authentication":api_token}))
        else:
          raise web.HTTPError(404)
```

kind of like bypassing the Authorization header, by using PAM auth, much like the browser log in. Thereafter API calls can use the the Authorization token. We need this for our services' architecture, but I suspect it is not the spirit what you guys are trying to achieve. Thanks anyway.

**Comment by minrk** [comment]
It's the OAuth-style authenticators that get in the way there, where you can't use username+password data to login. We could have such a handler that only works for form-based auth, though.

**Comment by dominicfollett** [comment]
We have something working great our side, would you like me to submit a pull request for you to have a look at?

**Comment by minrk** [comment]
Sure, that would be great.

**Comment by GeorgianaElena** [comment]
Solved by https://github.com/jupyterhub/jupyterhub/pull/515 :four_leaf_clover:
