### ISSUE TITLE
JupyterHub does not ask for authentication once you have created a notebook server for a user 

### ISSUE THREAD

**Issue by pawannrao-ebay** [jupyterhub/jupyterhub#507]
For the purpose of discussion lets say JupyterHub running in this URL:

http://10.x.y.z:8080

For first time login, the chrome browser would show the login page and set cookie for the active user once login is completed.

At jupyterhub end if there is no Notebook server for that user, it would create an entry in the database and call Spawner to create new Notebook server.

The next time you hit the site it would send 302 redirect to user specific URL, for example:
http://10.x.y.z:8080/user/userx/notebooks/Demo-Spark.ipynb

Now if you delete the cookies associated with jupyterhub, the hub-token and the user token but start use the notebook server url directly no authentication is seeked for. Once the Notebook server is created, hitting directly to that URL (http://10.x.y.z:8080/user/userx/notebooks/Demo-Spark.ipynb) from browser with no cookie does not redirect back to login page. This is insecure and unexpected.

*IMPORTANT* : This happens when notebookserver is running remotely, if the notebook server is running locally this is not seen. So you need to use some remote spawners available out there to try this out and not with LocalSpawner.

**Comment by minrk** [comment]
The "running remotely" certainly does seem important. What remote spawner are you using? If this is sensitive to the spawner, it seems like a problem in the Spawner. I can't come up with an example where this happens.

**Comment by pawannrao-ebay** [comment]
I am using kubernetes spawner to spawn the notebook. But I wasnt expecting this problem since all request still go through proxy and if I have deleted the cookies from my browser, it should have asked for auth again. Enabling debug statements of proxy wasnt useful so far. So if you can point me so other way of debugging this let me know.

**Comment by pawannrao-ebay** [comment]
Any means of debugging this cookie issue? Enabling debug statement for configurable http proxy didnt help. Not sure where the cookie is coming from and where is it getting authenticated.

**Comment by minrk** [comment]
Cookie is in the browser, and the cookie check is initiated in the single-user server [here](https://github.com/jupyter/jupyterhub/blob/0.5.0/scripts/jupyterhub-singleuser#L95). There aren't debug statements there, but you can add a log statement that dumps the headers or cookies there.

**Comment by pawannrao-ebay** [comment]
How is cookie getting in there despite the deletion from browser is the question. Thanks for the pointers..

**Comment by minrk** [comment]
How did you delete the cookies? Single-user cookies are set on a different path from the Hub cookie, so you will probably want to be looking at a single-user page when you go to the cookie-edit dialog. The easier way to clear this cookie is to click the logout button (clearing these cookies is all logout does).

**Comment by pawannrao-ebay** [comment]
I am deleting both "jupyter-hub-token" and "jupyter-hub-token-username" cookies. I do not see any cookies for the notebook server IP as such... am I missing something?. Btw the logout button also doesnt work for remote notebook server cases, when I logout and reload the url the notebook page re-appears without any need of authentication!

**Comment by minrk** [comment]
If the behavior is different for launching with Kubernetes and local processes, something is wrong with the Kubernetes setup.

When you are checking for single-user cookies, you must be looking at the single-user page. Is that where you are looking?

**Comment by pawannrao-ebay** [comment]
Yeah I dont see any other cookies getting set.Even single uset page starts with proxy ip so I dont think I missed anything wrt searching for cookies.

**Comment by minrk** [comment]
It's not the IP, everything uses the same IP, it's the cookie *path*, since the single-user server cookies are set on a different path from the Hub, so the cookies are not shared. Can you dump the cookie header received by the single-user server to confirm that there is in fact a cookie received by the server?

**Comment by pawannrao-ebay** [comment]
I added debug statement in get_user(), but something strange is happening and there in lies the cause I feel. So these debug statements in get_user() gets called for LocalSpawner and not for the remote spawner, so its clear for remote spawners the control path is something different. So there in lies the issue I feel. I will add some more debug statements to see why is that.

**Comment by pawannrao-ebay** [comment]
I added some more debug statements in base.py, the cookie gets set in a neat fashion, but after cookies are deleted from browser its not quite sure where user check is being skipped. I need to identify the exact  path were 'cached_session' users authentication is being skipped.

**Comment by minrk** [comment]
cached_session requires getting the cookie from the current request, and seeing if that cookie has been validated with the Hub recently. It will not be relevant if the cookie has been cleared.

**Comment by pawannrao-ebay** [comment]
But As I mentioned earlier, I m not able to log cookies in jupyterhub-singleuser for remote spawners. Not sure where the check is done.

**Comment by minrk** [comment]
User check is performed [here](https://github.com/jupyterhub/jupyterhub/blob/0.6.0/scripts/jupyterhub-singleuser#L83) in the jupyterhub-singleuser script. You could also add logging to the notebook application, so that it logs headers on every request. How to add it will depend how you build your single-user images.

**Comment by minrk** [comment]
That is called by [get_current_user here](https://github.com/jupyter/notebook/blob/4.2.0/notebook/base/handlers.py#L79) in the notebook application.

**Comment by pawannrao-ebay** [comment]
Hi. In the Dockerspawner version, https://github.com/jupyterhub/dockerspawner, I see that you use jupyterhub-singleuser exec to run the notebook server. The way I am running my notebookserver in kubertnetes launch is via the normal method of 'jupyter notebook' command.

jupyterhub-singleuser \
  --port=8888 \
  --ip=0.0.0.0 \
  --user=$JPY_USER \
  --cookie-name=$JPY_COOKIE_NAME \
  --base-url=$JPY_BASE_URL \
  --hub-prefix=$JPY_HUB_PREFIX \
  --hub-api-url=$JPY_HUB_API_URL \

and jupyter notebook doesnt accept cookie_name as an option. Do you see any problem in not running via jupyterhub-singleuser command, without any cookiename option and taking the simple jupyter notebook channel?

I did try to run jupyterhub-singleuser command, I encountered this problem:
requests.exceptions.MissingSchema: Invalid URL 'authorizations/cookie/jupyter-hub-token-krylov/2%7C1%3A0%7C10%3A1462574847%7C24%3Ajupyter-hub-token-krylov%7C44%3AYjU3MjdjMmJiOWM3NGE1ZGJkOTc2NTA2YmI0ZDg2Yjk%3D%7C3ec02b0a95990de81b43d683c70725610d74182df6293e3eb684e4c017e941e9': No schema supplied. Perhaps you meant http://authorizations/cookie/jupyter-hub-token-krylov/2%7C1%3A0%7C10%3A1462574847%7C24%3Ajupyter-hub-token-krylov%7C44%3AYjU3MjdjMmJiOWM3NGE1ZGJkOTc2NTA2YmI0ZDg2Yjk%3D%7C3ec02b0a95990de81b43d683c70725610d74182df6293e3eb684e4c017e941e9?
[E 2016-05-06 22:47:28.044 SingleUserNotebookApp log:46] {
"X-Forwarded-Port": "30195",
"Accept-Language": "en-US,en;q=0.8",
"Upgrade-Insecure-Requests": "1",
"Cookie": "jupyter-hub-token-krylov=\"2|1:0|10:1462574847|24:jupyter-hub-token-krylov|44:YjU3MjdjMmJiOWM3NGE1ZGJkOTc2NTA2YmI0ZDg2Yjk=|3ec02b0a95990de81b43d683c70725610d74182df6293e3eb684e4c017e941e9\"",
"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,/;q=0.8",
"Accept-Encoding": "gzip, deflate, sdch",
"X-Forwarded-Proto": "http",
"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36",
"Referer": "<jupyterhub_ip>/hub/login",
"X-Forwarded-For": "::ffff:172.20.185.2",
"Host": "kubernetes-minion-105-4040.slc01.dev.ebayc3.com:30195",
"Cache-Control": "max-age=0",
"Connection": "close"
}

**Comment by minrk** [comment]
@pawannrao-ebay you cannot start notebooks with `jupyter notebook` for use with JupyterHub. You **must** use `jupyterhub-singleuser`. The Hub authentication resides in `jupyterhub-singleuser`, so launching with `jupyter notebook` is effectively turning off all authentication to the notebook server.

It looks like the `jupyterhub-singleuser` command is not getting passed required arguments. Witht he command:

```
jupyterhub-singleuser \
  --port=8888 \
  --ip=0.0.0.0 \
  --user=$JPY_USER \
  --cookie-name=$JPY_COOKIE_NAME \
  --base-url=$JPY_BASE_URL \
  --hub-prefix=$JPY_HUB_PREFIX \
  --hub-api-url=$JPY_HUB_API_URL \
```

You must make sure in your Spawner that all of those environment variables are being defined. Are you using @yuvipanda's [jupyterhub-kubernetes-spawner](https://github.com/yuvipanda/jupyterhub-kubernetes-spawner), or your own Kubernetes Spawner?

**Comment by pawannrao-ebay** [comment]
Yeah I was planning to try that. Its my own spwaner. I do want to ask whether proxy is expected to run on public IP.

**Comment by minrk** [comment]
Yes, the proxy is expected to run publicly by default. You can tell it to listen on a different ip with `--ip=...`.

**Comment by pawannrao-ebay** [comment]
I am now running proxy at public ip. Still I am getting Invalid URL issue. Looks like hub_api should also be run on public ip. 

[E 2016-05-12 18:33:15.470 krylov web:1524] Uncaught exception GET /user/krylov/tree (10.65.63.39)
    HTTPServerRequest(protocol='http', host='10.65.15.250:8080', method='GET', uri='/user/krylov/tree', version='HTTP/1.1', remote_ip='10.65.63.39', headers={'Accept-Encoding': 'gzip, deflate, sdch', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36', 'X-Forwarded-For': '10.65.63.39', 'Referer': 'http://10.65.15.250:8080/hub/home', 'X-Forwarded-Port': '8080', 'Host': '10.65.15.250:8080', 'Upgrade-Insecure-Requests': '1', 'X-Forwarded-Proto': 'http', 'Cookie': 'jupyter-hub-token-krylov="2|1:0|10:1463077995|24:jupyter-hub-token-krylov|44:ZjQ4ZjM2NWQ0ZWU3NDMxNWEyYTc5ZTU5OGNkMmE0YWE=|8979e8a2475c83b4d1bce13b97af8eb1915088c2332420c04eb531e653287f7e"', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Connection': 'close', 'Accept-Language': 'en-US,en;q=0.8'})
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/web.py", line 1443, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/conda/lib/python3.5/site-packages/tornado/web.py", line 2787, in wrapper
        if not self.current_user:
      File "/opt/conda/lib/python3.5/site-packages/tornado/web.py", line 1095, in current_user
        self._current_user = self.get_current_user()
      File "/opt/conda/lib/python3.5/site-packages/notebook/base/handlers.py", line 82, in get_current_user
        return self.login_handler.get_user(self)
      File "/usr/local/bin/jupyterhub-singleuser", line 95, in get_user
        auth_data = JupyterHubLoginHandler.verify_token(self, self.cookie_name, encrypted_cookie)
      File "/usr/local/bin/jupyterhub-singleuser", line 64, in verify_token
        headers = {'Authorization' : 'token %s' % hub_api_key},
      File "/opt/conda/lib/python3.5/site-packages/requests/api.py", line 67, in get
        return request('get', url, params=params, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/requests/api.py", line 53, in request
        return session.request(method=method, url=url, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/requests/sessions.py", line 454, in request
        prep = self.prepare_request(req)
      File "/opt/conda/lib/python3.5/site-packages/requests/sessions.py", line 388, in prepare_request
        hooks=merge_hooks(request.hooks, self.hooks),
      File "/opt/conda/lib/python3.5/site-packages/requests/models.py", line 293, in prepare
        self.prepare_url(url, params)
      File "/opt/conda/lib/python3.5/site-packages/requests/models.py", line 353, in prepare_url
        raise MissingSchema(error)
    requests.exceptions.MissingSchema: Invalid URL '/hub/api/authorizations/cookie/jupyter-hub-token-krylov/2%7C1%3A0%7C10%3A1463077995%7C24%3Ajupyter-hub-token-krylov%7C44%3AZjQ4ZjM2NWQ0ZWU3NDMxNWEyYTc5ZTU5OGNkMmE0YWE%3D%7C8979e8a2475c83b4d1bce13b97af8eb1915088c2332420c04eb531e653287f7e': No schema supplied. Perhaps you meant http:///hub/api/authorizations/cookie/jupyter-hub-token-krylov/2%7C1%3A0%7C10%3A1463077995%7C24%3Ajupyter-hub-token-krylov%7C44%3AZjQ4ZjM2NWQ0ZWU3NDMxNWEyYTc5ZTU5OGNkMmE0YWE%3D%7C8979e8a2475c83b4d1bce13b97af8eb1915088c2332420c04eb531e653287f7e?

**Comment by minrk** [comment]
The hub's API needs to be accessible to the single-user containers, so that depends on what you mean by 'public'.

That error, however, indicates that the single-user server isn't getting the information needed, because the hub_api_url is incorrect - it should be the *full* URL of the hub ('https://hub-api-ip:hub-api-port/hub/api').

**Comment by willingc** [comment]
> Are you using @yuvipanda's jupyterhub-kubernetes-spawner, or your own Kubernetes Spawner?

@minrk: Added @yuvipanda's jupyterhub-kubernetes-spawner to [jupyterhub wiki](https://github.com/jupyterhub/jupyterhub/wiki/Spawners)

**Comment by pawannrao-ebay** [comment]
I ran jupyterhub on public ip where jupyter notebooks can connect. But I am constantly hitting this error seen in jupyterhub-single user code:

Log
=====
r.status_code == 403:
            self.log.error("I don't have permission to verify cookies, my auth token may have expired: [%i] %s", r.status_code, r.reason)
            raise HTTPError(500, "Permission failure checking authorization, I may need to be restarted")
"Permission failure checking authorization, I may need to be restarted"

Jupyterhub
-----------------
I am running the Jupytehrub without ssl. That may be a issue but wondering why should cookie check depend on that.

[W 2016-05-21 00:05:48.044 JupyterHub log:100] 403 GET /hub/api/authorizations/cookie/jupyter-hub-token-krylov/[secret] (@172.17.0.5) 7.69ms

Jupyterhub-singleuser
-------------------------------
These are the variables I am passing to jupyterhub-singleuser run:
 
JPY_USER:userx JPY_COOKIE_NAME:jupyter-hub-token-userx, JPY_BASE_URL:/user/userx, JPY_HUB_PREFIX:http://<hubip>:8081/hub/,JPY_HUB_API_URL=http://<hubip>:8081/hub/api,

Jupyterhub-singleuser is running on /user/userx.

Jupyterhub API is running on http://<hubip>:8081/hub/api for sure. Even when I access Jupyterhub-singleuser  independent of hub itself.I get the same 403 error.  Note sure except for ssl factor.

**Comment by minrk** [comment]
Running without SSL won't be the issue here, but if your server is publicly accessible SSL should always be used.

Make sure to set the `JPY_API_TOKEN` env variable, too. The base Spawner class sets this in `.get_env()`, so if you are calling that, it should be okay. If you are setting this variable correctly, it could be invalidated at a later point by the Hub's database being cleared, which necessitates generating a new API token and restarting the single-user server(s). This is what the error message is meant to indicate.

Is your Spawner online somewhere?

**Comment by pawannrao-ebay** [comment]
Thanks I too though SSL is independent of cookie checks.

I am setting JPY_API_TOKEN to random value at notebook servers end. May be it should be uniform on hub and notebookserver as well?. Whats the correct way to set it? Currently its being set in notebook server, I am not really using this variable in hub as such.

**Comment by pawannrao-ebay** [comment]
I m modifying # c.JupyterHub.ip = '' # c.JupyterHub.hub_ip = '' variables to listen to IP where Notebook Servers can connect.  @yuvipanda's introduces some variable called hub_ip_connect which I am not sure is needed.

My Notebook Server run script
-----------------------------------------

export JPY_API_TOKEN='aaa'
export JPY_USER='userx'
export JPY_COOKIE_NAME='jupyter-hub-token-userx'
export JPY_BASE_URL='/user/userx/'
export JPY_HUB_PREFIX='http://<hubip>:8081/hub/'
export JPY_HUB_API_URL='http://<hubip>:8081/hub/api/'


/opt/krylov/jupyter/jupyterhub-singleuser \
            --port=8888 \
            --config=/home/krylov/.jupyter/jupyter_notebook_config.py \
            --user=$JPY_USER \
            --cookie-name=$JPY_COOKIE_NAME \
            --base-url=$JPY_BASE_URL \
            --hub-prefix=$JPY_HUB_PREFIX \
            --hub-api-url=$JPY_HUB_API_URL

**Comment by minrk** [comment]
> I am setting JPY_API_TOKEN to random value at notebook servers end. May be it should be uniform on hub and notebookserver as well?. Whats the correct way to set it? 

JupyterHub has already generated the token for you, and it is accessible as `self.api_token` in your spawner. This is the value that must be used, and it will be different for every user. In general, you shouldn't need to do this directly, because your spawner should be starting from a default environment with:

```python
def start(self):
    env = self.get_env()
    ....
    start_with_env(env)
```

which will include the correct value for the API token, user, urls, etc. Any additional environment variables you want to set can be added in your own `.get_env()`, which may look like this:

```python
def get_env(self):
    env = super().get_env()
    env['mykey'] = myvalue
    return env
```

to build the environment variables used to spawn your single-user servers.

**Comment by pawannrao-ebay** [comment]
Fine, the token will be different for every session as well or will remain same for a given user across multiple restarts, logins?

**Comment by pawannrao-ebay** [comment]
Great. Things work fine with proper token being passed. Now I want to know if this token is generated a fresh across Jupyterhub launches. It looks like token works for multiple logins of same user.

**Comment by pawannrao-ebay** [comment]
I am closing this issue. May be some documentation related to jupyterhub-singleuser needs to be updated.

Thanks a lot for walking me through it. Appreciate your effort on this.

**Comment by willingc** [comment]
@pawannrao-ebay Thanks. Expanding the docs on this topic is a good suggestion. PRs welcome too ;-)

**Comment by minrk** [comment]
> the token will be different for every session as well or will remain same for a given user across multiple restarts, logins?

Generally, each time a notebook server is started, the Hub generates a new API token. The Hub takes care of this and the Spawner should only be responsible for passing through the content from `.get_env()` from the base class.

**Comment by akx** [comment]
For people here in 2019 trying to figure out what the command line parameter is to change Jupyter's cookie name, this works for me:

```python
tornado_settings = {"cookie_name": cookie_name}
args = [
    # ... 
    f"--NotebookApp.tornado_settings={json.dumps(tornado_settings)}",
]
```
