### ISSUE TITLE
Add configuration info re: specific use case with nginx to docs 

### ISSUE THREAD

**Issue by willingc** [jupyterhub/jupyterhub#509]
Based on a mailing list discussion between Edward Leonard Jr and @minrk, @fperez requested adding portions of the conversation to the JupyterHub docs.

https://groups.google.com/forum/#!msg/jupyter/tPcQKr8bznY/D_DoVXE0AQAJ

**Comment by iamed18** [comment]
I'd be happy to help with this. I'm still doing some testing but once the dust settles I can check out the docs and see how I might be able to contribute.

**Comment by willingc** [comment]
@iamed18 Great! I'm happy to pair with you as well. Thanks, and go badgers.

**Comment by fperez** [comment]
@iamed18, thanks so much for willing to help out, we really appreciate it!

**Comment by minrk** [comment]
Great, thanks for helping out!

We'll probably want to include Apache in a general "Running JupyterHub behind a traditional webserver" doc. I think more people have been able to figure out nginx than Apache, at this point.

**Comment by iamed18** [comment]
Finally tried a stab at this.

https://github.com/jupyterhub/jupyterhub/pull/602

**Comment by willingc** [comment]
Thanks for the PR @iamed18 👍
