### ISSUE TITLE
Create reference deployment documents

### ISSUE THREAD

**Issue by willingc** [jupyterhub/jupyterhub#516]
As mentioned by @minrk on the mailing list, we are working on creating reference documents to ease deployment of JupyterHub.

Some of the identified reference needs are:
- [x] JupyterHub on a single server
- [x] JupyterHub and Containers (Docker, Carina, ...)
- [x] JupyterHub and nbgrader for a class/course 
- [ ] JupyterHub in a multiserver environment
- [ ] JupyterHub and tmpnb

Other topics needing expanded reference documents or better curation/structure:
- [ ] Security - SSL and Authentication
- [ ] Capacity planning

**Comment by yuvipanda** [comment]
Me and @aculich are now working on https://github.com/yuvipanda/jupyterhub-simplest-k8s which documents progressively more complex ways of running JupyterHub on kubernetes. Currently we only have stuff on GCE, will hopefully eventually expand to AWS and what not.

**Comment by minrk** [comment]
That's great!

**Comment by willingc** [comment]
Update: there are currently 3 reference deployments as checked in the original issue.

I'm going to close since I believe that new reference deployments will be released as needed or contributed by the community. @yuvipanda @minrk feel free to reopen if desired.
