### ISSUE TITLE
REST API call to upload a notebook.ipynb to a user's server.

### ISSUE THREAD

**Issue by dominicfollett** [jupyterhub/jupyterhub#518]
I noticed there is no option to upload a file to a user's server, except by an administrator(or user) logging in and explicitly doing so. Would Jupyterhub be interested in having such a call? In our systems that interface with Edx, its advantageous to have a user's notebook already loaded with the required course materials.

**Comment by minrk** [comment]
We are working on a sharing system that should allow something like this. It likely won't be an endpoint on JuptyerHub itself, but an additional service next to JupyterHub, like nbgrader can be.

**Comment by dominicfollett** [comment]
That would be quite cool. For the meantime I'm going to see if I can just use the Notebook server's upload method. We've also considered using Rsynced S3 buckets for file upload and sharing.

**Comment by JoshuaC3** [comment]
@dominicfollett you said `I noticed there is no option to upload a file to a user's server, *except by an administrator(or user) logging in and explicitly doing so*` . How did you do this?

**Comment by dominicfollett** [comment]
Hi Josh

yeah I think that is what I meant. You should be able to do it through the interface. It has been some time since I've looked at this, though.

**Comment by consideRatio** [comment]
I'm trying to evaluate if this is a reasonable feature request in scope of JupyterHub without forcing it to become aware of assumptions made in the user environments.
