### ISSUE TITLE
Update the wiki for better navigation

### ISSUE THREAD

**Issue by willingc** [jupyterhub/jupyterhub#519]
@minrk @jhamrick I've updated the JupyterHub wiki to have better navigation and discoverability. I have loosely based the design and layout on the d3.js GitHub wiki since it was one of the top rated wikis on GitHub. If you see something missing or would like additional changes, please let me know.

FYI. The notes section of the wiki has an outline of all submitted pages that are not authenticators or spawners.

**Comment by minrk** [comment]
Terrific, thanks!
