### ISSUE TITLE
How to best write a utility class used by the authenticator and spawner?

### ISSUE THREAD

**Issue by carolynvs** [jupyterhub/jupyterhub#524]
I have written the CarinaAuthenticator, CarinaSpawner and a shared utility class, CarinaClient, which handles all the calls to Carina to authenticate, create Docker Swarm clusters, etc. I would like to submit these back upstream to the jupyter/oauthenticator and jupyter/dockerspawner. My question is about the shared class.

I was leaning towards making the helper a separate PyPI package, e.g. carina-python-sdk, so that the authenticator and spawner could just pull that in and reuse it. The awkward part though is that currently the helper uses tornado's AsyncHTTPClient directly, and that doesn't seem very ... helpful... to distribute a library that is tied to tornado.

@rgbkrk [ran into something similar with docker-py](https://github.com/docker/docker-py/issues/327), and he ended up writing a wrapper that spawns threads to run the blocking calls. But based on that issue, it sounds like I could do better by using python 3.5's native async/await. It seems like tornado can handle working with those too?

I haven't worked with tornado or async in python to know if I am going down a good path, that you would be willing to accept in a PR, or digging myself into a hole. :smile: 

Any feedback and suggestions would be much appreciated!

**Comment by willingc** [comment]
> I would like to submit these back upstream to the jupyter/oauthenticator and jupyter/dockerspawner.
Cool!

@minrk would be well suited for explaining the technical tradeoffs with the shared class.

**Comment by minrk** [comment]
@carolynvs sounds great! What does a CarinaAuthenticator do? And what is CarinaClient beyond DockerClient? Is it mainly a Python translation of the Go client?

A generic asyncio implementation should be usable from a tornado application. I haven't tried it to see exactly what steps are needed to make sure that all the eventloops are cooperating, but tornado can sit on top of the asyncio loop, so I know it can work in at least one way. If you are just spawning threads like @rgbkrk did, you would not need asyncio at all, just Futures, in which case it will work just about everywhere.

You would only require Python 3.5 if you used the `async/await` *syntax*, though you can still use asyncio, futures, and `yield from` in earlier versions of Python 3, if compatibility is a concern.

**Comment by rgbkrk** [comment]
:+1: to only Python 3 support.

**Comment by carolynvs** [comment]
Should I submit these two as PR's to jupyter/oauthenticator and jupyter/dockerspawner? I wasn't sure if it would be easier to figure this out in a single location (here) or hammer it out in PRs. Whatever is easier for you, just let me know.

[CarinaAuthenticator](https://github.com/carolynvs/howtowhale/blob/master/howtowhale-hub/lib/jupyterhub_carina/CarinaAuthenticator.py) is a subclass of `jupyterhub.Authenticator`, following the same patterns used for github or google auth in jupyter/oauthenticator, and handles authenticating via OAuth2 to Carina. This allows users to log into JupyterHub via a "Sign in with Carina" button.

[CarinaSpawner](https://github.com/carolynvs/howtowhale/blob/master/howtowhale-hub/lib/jupyterhub_carina/CarinaSpawner.py) is a subclass of `jupyterhub.Spawner`, specifically the `DockerSpawner` in jupyter/dockerspawner, and handles creating a Docker Swarm cluster for the user on their Carina account, then running a Jupyter server in a container on the cluster. This spawner is meant to be used in conjunction with the CarinaAuthenticator, so that they can coordinate handing off the credentials retrieved when the user signed-in.

[CarinaOAuthClient](https://github.com/carolynvs/howtowhale/blob/master/howtowhale-hub/lib/jupyterhub_carina/CarinaOAuthClient.py) is written in python, and is a common helper used by the authenticator/spawner to talk to Carina. I talked a bit with @rgbkrk about making it into a python package, since it is useful outside of Jupyter.

I will try your suggestion of using asyncio and see if that "just works" or would require a config change in JupyterHub's `app.py`.

**Comment by rgbkrk** [comment]
The bigger question here is whether we allow provider specific components here. I'm certainly a fan, including others, so long as the maintainers stick around.

/cc @parente @jtyberg for thoughts (as folks with a different platform than Carolyn and I work on).

**Comment by minrk** [comment]
I'm fine either way. I don't have a good way to define the scope of OAuthenticator in terms of providers, so if you make a PR and agree to support it, it's in. The case for carina inside dockerspawner is a little tougher, but as long as there's someone to maintain it, it's all okay. Another option would be to make a single `jupyterhub-carina` package that provides both, and I'd be extra happy to have you in charge of that one, and for it to be here on the jupyterhub org.

**Comment by carolynvs** [comment]
I like the idea of making a vendor specific package that is still under the Jupyter org. That way there aren't any worries about introducing new dependencies into the main project, and it's just a quick `pip install jupyterhub-carina` to get up and running.

If that is agreeable, just let me know how to move forward and I'll get the code into its new home. :heart:

**Comment by minrk** [comment]
@carolynvs great! Have at it: https://github.com/jupyterhub/jupyterhub-carina

**Comment by willingc** [comment]
@carolynvs Excellent! Looking forward to jupyterhub-carina :sunny:

**Comment by carolynvs** [comment]
Sweet, thanks!
