### ISSUE TITLE
add user in whitelist doesn't work

### ISSUE THREAD

**Issue by ccoolmans** [jupyterhub/jupyterhub#529]
I am currently setting up the JupyterHub in Ubuntu for a project for only 5 of my team members to use and share the files on   Jupyterhub, when I want to add new user to test on my server, I add it as in 

c.Authenticator.whitelist = set()
c.Authenticator.whitelist = {'ccoolmans','test1','test2'}

However, when I go to Jupyterhub login page, and login with the username 'test1', it requires password which I never set before and don't know how to set. Can anybody help? Thank you in advance.
@minrk

**Comment by minrk** [comment]
You can use `passwd` to give the user a password:

    sudo passwd test1

**Comment by ccoolmans** [comment]
Thank you for your quick reply. After giving the passwd command, it showed as following when I want to login using 'test1' account:
API request failed (500): Spawner failed to start [status=1]

Do you know how to solve this issue?

**Comment by minrk** [comment]
What do you see in the jupyterhub logs?

**Comment by ccoolmans** [comment]
[I 2016-04-20 01:56:25.431 JupyterHub spawner:436] Spawning jupyterhub-singleuser --user=test1 --port=45040 --cookie-name=jupyter-hub-token-test1 --base-url=/user/test1 --hub-host= --hub-prefix=/hub/ --hub-api-url=http://127.0.0.1:8081/hub/api --ip=127.0.0.1 '--notebook-dir=~/anaconda3'
The Jupyter HTML Notebook.

This launches a Tornado based HTML Notebook Server that serves up an
HTML5/Javascript Notebook client.

Subcommands
-----------

Subcommands are launched as `jupyter-notebook cmd [args]`. For information on
using subcommand 'cmd', do: `jupyter-notebook cmd -h`.

list
    List currently running notebook servers.

Options
-------

Arguments that take values are actually convenience aliases to full
Configurables, whose aliases are listed on the help line. For more information
on full configurables, see '--help-all'.

--pylab
    DISABLED: use %pylab or %matplotlib in the notebook to enable matplotlib.
--no-script
    DEPRECATED, IGNORED
--no-browser
    Don't open the notebook in a browser after startup.
--debug
    set log level to logging.DEBUG (maximize logging output)
--generate-config
    generate default config file
-y
    Answer yes to any questions instead of prompting.
--disable-user-config
    Disable user-controlled configuration of the notebook server.
--no-mathjax
    Disable MathJax
    
    MathJax is the javascript library Jupyter uses to render math/LaTeX. It is
    very large, so you may want to disable it if you have a slow internet
    connection, or for offline use of the notebook.
    
    When disabled, equations etc. will appear as their untransformed TeX source.
--script
    DEPRECATED, IGNORED
--pylab=<Unicode> (NotebookApp.pylab)
    Default: 'disabled'
    DISABLED: use %pylab or %matplotlib in the notebook to enable matplotlib.
--cookie-name=<Unicode> (SingleUserNotebookApp.cookie_name)
    Default: ''
--hub-prefix=<Unicode> (SingleUserNotebookApp.hub_prefix)
    Default: ''
--browser=<Unicode> (NotebookApp.browser)
    Default: ''
    Specify what command to use to invoke a web browser when opening the
    notebook. If not specified, the default browser will be determined by the
    `webbrowser` standard library module, which allows setting of the BROWSER
    environment variable to override it.
--client-ca=<Unicode> (NotebookApp.client_ca)
    Default: ''
    The full path to a certificate authority certifificate for SSL/TLS client
    authentication.
--keyfile=<Unicode> (NotebookApp.keyfile)
    Default: ''
    The full path to a private key file for usage with SSL/TLS.
--hub-api-url=<Unicode> (SingleUserNotebookApp.hub_api_url)
    Default: ''
--config=<Unicode> (JupyterApp.config_file)
    Default: ''
    Full path of a config file.
--certfile=<Unicode> (NotebookApp.certfile)
    Default: ''
    The full path to an SSL/TLS certificate file.
--port-retries=<Int> (NotebookApp.port_retries)
    Default: 50
    The number of additional ports to try if the specified port is not
    available.
--transport=<CaselessStrEnum> (KernelManager.transport)
    Default: 'tcp'
    Choices: ['tcp', 'ipc']
--base-url=<Unicode> (SingleUserNotebookApp.base_url)
    Default: '/'
    The base URL for the notebook server.
    Leading and trailing slashes can be omitted, and will automatically be
    added.
--log-level=<Enum> (Application.log_level)
    Default: 30
    Choices: (0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL')
    Set the log level by value or name.
--ip=<Unicode> (NotebookApp.ip)
    Default: 'localhost'
    The IP address the notebook server will listen on.
--hub-host=<Unicode> (SingleUserNotebookApp.hub_host)
    Default: ''
--notebook-dir=<Unicode> (NotebookApp.notebook_dir)
    Default: ''
    The directory to use for notebooks and kernels.
--user=<CUnicode> (SingleUserNotebookApp.user)
    Default: ''
--port=<Int> (NotebookApp.port)
    Default: 8888
    The port the notebook server will listen on.

To see all available configurables, use `--help-all`

Examples
--------

    jupyter notebook                       # start the notebook
    jupyter notebook --certfile=mycert.pem # use SSL/TLS certificate

[C 2016-04-20 01:56:26.013 SingleUserNotebookApp application:77] Bad config encountered during initialization:
[C 2016-04-20 01:56:26.014 SingleUserNotebookApp application:78] No such notebook dir: '/home/test1/anaconda3'
[W 2016-04-20 01:56:35.515 JupyterHub web:1521] 500 POST /hub/login?next= (192.168.1.1): Spawner failed to start [status=1]
[E 2016-04-20 01:56:35.572 JupyterHub log:99] {
      "Accept-Language": "en,zh-CN;q=0.8,zh;q=0.6",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Cache-Control": "max-age=0",
      "Origin": "http://192.168.1.1:8001",
      "Upgrade-Insecure-Requests": "1",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://192.168.1.1:8001/hub/login",
      "Connection": "close",
      "Host": "192.168.1.1:8001",
      "X-Forwarded-For": "192.168.1.1",
      "X-Forwarded-Proto": "http",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36",
      "X-Forwarded-Port": "8001",
      "Content-Type": "application/x-www-form-urlencoded",
      "Content-Length": "32"
    }
[E 2016-04-20 01:56:35.576 JupyterHub log:100] 500 POST /hub/login?next= (@192.168.1.1) 10365.84ms
[W 2016-04-20 01:56:55.612 JupyterHub user:262] test1's server never showed up at http://127.0.0.1:45040/user/test1 after 30 seconds. Giving up
[E 2016-04-20 01:56:55.634 JupyterHub gen:871] Exception in Future <tornado.concurrent.Future object at 0x7f441d1a6668> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 867, in error_callback
        future.result()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/user.py", line 278, in spawn
        raise e
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/user.py", line 254, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/orm.py", line 108, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/utils.py", line 94, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://127.0.0.1:45040/user/test1 didn't respond in 30 seconds

**Comment by minrk** [comment]
The directory `/home/test1/anaconda3` doesn't exist, and you've asked it to run there. Perhaps you didn't make the user's home directory when you made the user?

**Comment by ccoolmans** [comment]
yes, i didn't make the home directory for test1, where and how can i make the change?

**Comment by minrk** [comment]
Normally this is done when you create users with `adduser <name>`. You can do this after the fact with

    mkhomedir_helper <name>

**Comment by ccoolmans** [comment]
Hi, i can see from /etc/passwd file as follows:

ccoolmans:x:1000:1000:,,,:/home/ccoolmans:/bin/bash
guest-yPttfd:x:116:125:Guest,,,:/tmp/guest-yPttfd:/bin/bash
user1:x:1001:1001::/home/user1:
guest-mPfoSx:x:117:126:Guest,,,:/tmp/guest-mPfoSx:/bin/bash
test1:x:1002:1002:jupyterhubtest,,,,:/home/test1:/bin/bash
test2:x:1003:1003:,,,:/home/test2:/bin/bash
rhea:x:1004:1004::/home/rhea:
newuser:x:1005:1005::/home/newuser:
apple:x:1006:1006:,,,:/home/apple:/bin/bash

where ccoolmans is the username of myself who configure all the server settings(and i can login with this account to see the files in anaconda3 folder). however, when i login in with test1 with the similar path shown above, it still showed the error:

API request failed (500): Spawner failed to start [status=1]

one thing i observed is that in jupyterhub_config.py file, it showed the notebook dir is: 
c.Spawner.notebook_dir = '~/anaconda3'

when running as 'ccoolmans', the notebook dir is correct as home/ccoolmans/anaconda3
while running as 'test1', the notebook dir is wroing which is home/test1/anaconda3
how can i change the notebook dir for 'test1' to home/ccoolmans/anaconda3 so that i can correctly login using 'test1' account?

**Comment by minrk** [comment]
`~` is the home directory of the user running the server, so it should be `/home/test1` for test1, `/home/test2` for test2, etc. If you really want run the `test1` user in `ccoolmans` home directory, then you should use the full path `/home/ccoolmans/anaconda3/`, instead of `~/`.

**Comment by ccoolmans** [comment]
Thank you so much! I can login use test1 now. One more thing that when i login use 'test1', the file is only read-only. what shall i do to make it able to write the file?

**Comment by ccoolmans** [comment]
Thanks a million. Issue solved!!!
