### ISSUE TITLE
Proxy fails to start

### ISSUE THREAD

**Issue by bartaelterman** [jupyterhub/jupyterhub#530]
I'm sorry for logging another issue about the proxy that fails to start, but the answers in other issues/topics did not help for me so far.

I've installed jupyterhub before, and documented that process [here](https://github.com/LifeWatchINBO/lifewatch-jupyterhub/wiki/Install-Jupyter-without-conda). So you can exactly follow the steps I took.

However, I now want to do a fresh install but the hub won't start. The error message I get is:

```
root@ip-172-28-3-77:~# jupyterhub --no-ssl --ip=0.0.0.0 --port=443
[I 2016-04-20 11:38:59.568 JupyterHub app:558] Loading cookie_secret from /root/jupyterhub_cookie_secret
[W 2016-04-20 11:38:59.594 JupyterHub app:292] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[W 2016-04-20 11:38:59.607 JupyterHub app:685] No admin users, admin interface will be unavailable.
[W 2016-04-20 11:38:59.607 JupyterHub app:686] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2016-04-20 11:38:59.607 JupyterHub app:712] Not using whitelist. Any authenticated user will be allowed.
[I 2016-04-20 11:38:59.617 JupyterHub app:1113] Hub API listening on http://127.0.0.1:8081/hub/
[W 2016-04-20 11:38:59.621 JupyterHub app:851] Running JupyterHub without SSL. There better be SSL termination happening somewhere else...
[I 2016-04-20 11:38:59.621 JupyterHub app:860] Starting proxy @ http://0.0.0.0:443/
[C 2016-04-20 11:39:00.629 JupyterHub app:1119] Failed to start proxy
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 1117, in start
        yield self.start_proxy()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 881, in start_proxy
        _check()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 877, in _check
        raise e
    RuntimeError: Proxy failed to start with exit code 1
```

I've come across several related issues, but they don't resolve my issue:

* [missing node](http://stackoverflow.com/questions/36142099/jupyterhub-not-running-on-ubuntu-14-04) but I fixed that by installing node.
* I missed configurable-http-proxy before (as mentioned [here](https://github.com/jupyterhub/jupyterhub/issues/237)) but installed that with `npm install -g configurable-http-proxy`. This changed the exit code of the proxy startup process (to 1, what it's now)

Any ideas on how I could get the proxy to work?

---

As requested in the [contribution guidelines](https://github.com/ipython/ipython/blob/master/CONTRIBUTING.md), here is the output of `python -c "import IPython; print(IPython.sys_info())"`

```
{'commit_hash': 'b573435',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python3.4/dist-packages/IPython',
 'ipython_version': '4.1.2',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-74-generic-x86_64-with-Ubuntu-14.04-trusty',
 'sys_executable': '/usr/bin/python3',
 'sys_platform': 'linux',
 'sys_version': '3.4.3 (default, Oct 14 2015, 20:28:29) \n[GCC 4.8.4]'}
```

This is also interesting:

```
~# jupyterhub --version
0.5.0
~# npm --version
1.3.10
```

**Comment by minrk** [comment]
First things first, it's a bit odd to start the proxy on port 443 *without SSL*, because that port is reserved for HTTPS.

Can you start by just running the proxy:

    configurable-http-proxy

Then run it on the requested port, ip:

    configurable-http-proxy --ip 0.0.0.0 --port 443

?

**Comment by bartaelterman** [comment]
Thanks. I'll drop the `--port=443` setting then.

Neither `configurable-http-proxy` command returns any output. I don't know whether that is intended behaviour or not, but it does not change anything to the jupyterhub startup.

**Comment by minrk** [comment]
That's definitely not expected. what do you get from `which -a configurable-http-proxy` and `head $(which configurable-http-proxy)`?

**Comment by bartaelterman** [comment]
```
~# which -a configurable-http-proxy
/usr/local/bin/configurable-http-proxy
```

and

```
~# head $(which configurable-http-proxy)
#!/usr/bin/env node
//
// cli entrypoint for starting a Configurable Proxy
//
// Copyright (c) Jupyter Development Team.
// Distributed under the terms of the Modified BSD License.
//

"use strict";

```

**Comment by minrk** [comment]
And what do you get for `which node` and `node --version`?

**Comment by bartaelterman** [comment]
`which node` gives `/usr/sbin/node` but `node --version` returns nothing.

That seems odd, I installed node with `apt-get install node`. I went to the [nodejs documentation](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) and found a different way to install nodejs:

```
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
```

`which node` now points to `/usr/bin/node` instead of `/usr/sbin/node`. However, running `node --version` now returns an error `-bash: /usr/sbin/node: No such file or directory`

Cleared my bash cache for node:

```
hash -d node
```

Now, `node --version` returns `v4.4.3`.

`configurable-http-proxy` now indeed returns some output. Looks like some server is running. Killed it again and tried running jupyterhub again:

```
jupyterhub --no-ssl
```

Great! The hub is now running! I can't access it yet, but I'm suspecting that's a firewall issue. I changed the port to `80` and now I can access it.

Thanks for your help!

**Comment by minrk** [comment]
Great, glad you found it! Looks like your `node` wasn't `nodejs`. This may mean that you were missing the `nodejs-legacy` package, which is typically needed if you are getting node from apt.

**Comment by willingc** [comment]
Glad it's working :-) 

Tagging with documentation for future troubleshooting doc.

**Comment by burgerga** [comment]
Had a similar issue and installing nodejs via https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions indeed solved the issue
