### ISSUE TITLE
can jupyterhub merge change from different user?

### ISSUE THREAD

**Issue by hitanvil** [jupyterhub/jupyterhub#533]
Jupyterhub gives each user one server. If different user make changes on the same document, can juypterhub merge those change into the original document? If so, it greatly simplifies version control.

**Comment by minrk** [comment]
Sorry, no. That's well out of scope for JupyterHub. JupyterHub performs no operations at all on files in the single-user servers. Real-time collaboration is being developed in the single-user server, which will eventually address collaboration on a single file.
