### ISSUE TITLE
Enable Docker container to use host's PAM authentication

### ISSUE THREAD

**Issue by warrenson** [jupyterhub/jupyterhub#535]
Is it possible to start the container with the volume mount `-v /etc/pam.d:/etc/pam.d` to allow the docker container to use the host's PAM authentication?

This is failing for me with 'PAM Error 3', but maybe I'm missing something simple?

**Comment by minrk** [comment]
I'm not sure if `/etc/pam.d` is enough for that, but I'm guessing if it didn't work that it isn't. You may need to do more than mount just that directory.

**Comment by daviddiazvico** [comment]
I think you also need `-v /etc/passwd:/etc/passwd -v /etc/shadow:/etc/shadow`. It worked for me.

**Comment by willingc** [comment]
I'm going to close this issue since @daviddiazvico has provided a way to mount using the host's PAM authorization.

**Comment by hannesdgts2** [comment]
The direct "mount" (<code>-v /etc/passwd:/etc/passwd -v /etc/shadow:/etc/shadow</code>) of the authentication files only works if you have a non-changing set of users. If you like to perform a <code>useradd</code> or <code>passwd</code> without needing to restart the jupyterhub docker container, i propose the following workaround:
1. mount the whole /etc/ foldert into the container, e.g. <code>-v /etc/:/jup_etc/</code>
1. create a copy_script that copies the files into the <code>/etc</code> folder in the container <code>cp -f /jup_etc/passwd /etc/passwd; cp -f /jup_etc/shadow /etc/shadow; cp -f /jup_etc/group /etc/group </code>
1. run the copy_script at startup of the jupyerhub docker container and every time when <code>/etc/passwd, /etc/group, /etc/shadow</code> have changed (inside the container with  <code>docker exec -it "containername" bash</code>)

**Comment by hannesdgithub** [comment]
The direct "mount" (<code>-v /etc/passwd:/etc/passwd -v /etc/shadow:/etc/shadow</code>) of the authentication files only works if you have a non-changing set of users. If you like to perform a <code>useradd</code> or <code>passwd</code> without needing to restart the jupyterhub docker container, i propose the following workaround:
1. mount the whole /etc/ foldert into the container, e.g. <code>-v /etc/:/jup_etc/</code>
1. create a copy_script that copies the files into the <code>/etc</code> folder in the container <code>cp -f /jup_etc/passwd /etc/passwd; cp -f /jup_etc/shadow /etc/shadow; cp -f /jup_etc/group /etc/group </code>
1. run the copy_script at startup of the jupyerhub docker container and every time when <code>/etc/passwd, /etc/group, /etc/shadow</code> have changed (inside the container with  <code>docker exec -it "containername" bash</code>)

**Comment by ashok-andal** [comment]
> I think you also need `-v /etc/passwd:/etc/passwd -v /etc/shadow:/etc/shadow`. It worked for me.

I think this will not update the new users created on the host machines. So, if you just want to work with the existing docker host users inside the container, this works fine.

**Comment by gsmari** [comment]
I also needed to install sssd in my Dockerfile and do
`-v /var/lib/sss/pipes/:/var/lib/sss/pipes/`

Source: https://github.com/arcenik/docker-authfromhost/blob/63df5e63fcb92cd5fa26755e144e53a7678e803f/debian-buster-slim/Dockerfile#L13
