### ISSUE TITLE
ip = '*' causes proxy start to fail.

### ISSUE THREAD

**Issue by rawrgulmuffins** [jupyterhub/jupyterhub#545]
I'm attempting to create a puppet module that builds a Jupyterhub server automatically. For a single machine when I ran a static IP 

    c.JupyterHub.ip = '192.0.0.1'

my Jupyterhub server started without a hitch. But

    c.JupyterHub.ip = '*'

causes

```
[I 2016-04-26 02:27:07.705 JupyterHub app:969] Starting proxy @ http://*:8000/
02:27:07.799 - info: [ConfigProxy] Proxying http://*:8000 to http://127.0.0.1:8081
02:27:07.801 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
[C 2016-04-26 02:27:08.714 JupyterHub app:1238] Failed to start proxy
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 1236, in start
        yield self.start_proxy()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 990, in start_proxy
        _check()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 986, in _check
        raise e
    RuntimeError: Proxy failed to start with exit code 8

```

and I'm wondering why.

**Comment by minrk** [comment]
'*' isn't a valid IP, and the proxy doesn't accept it (jupyter notebook converts `'*'` to `''`, but the proxy we use doesn't do this). You can use `''` or `'0.0.0.0'` to communicate the same thing, or leave it out because this is the default behavior.

**Comment by rawrgulmuffins** [comment]
I'm pretty sure configurable-http-proxy accepted it when I manually entered it (at least, didn't error out). I'll double check when I get into work.

Should `*` throw a custom error regardless since just `Error: getaddrinfo ENOTFOUND` is potentially not clear?

**Comment by minrk** [comment]
configurable-http-proxy doesn't accept `'*'`:

```
.../configurable-http-proxy (master) $ configurable-http-proxy --ip='*'
12:34:14.789 - warn: [ConfigProxy] REST API is not authenticated.
12:34:14.794 - info: [ConfigProxy] Proxying http://*:8000 to (no default)
12:34:14.794 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND *
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

jupyterhub/configurable-http-proxy#55 handles this in the proxy and instructs the correct way to specify this IP with a warning.

**Comment by rawrgulmuffins** [comment]
You are totally right. Ran it on my end and I'm full of shit.

**Comment by minrk** [comment]
No problem.
