### ISSUE TITLE
Make JupyterHub an OAuth provider

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#553]
When discussing deploying services and things, we need to provide a mechanism for services to authenticate with the Hub.

nbgrader [has an implementation of this](https://github.com/jupyter/nbgrader/blob/v0.2.2/nbgrader/auth/hubauth.py) with the current JupyterHub scheme. We're planning to make an importable implementation in JupyterHub for use in tornado-based apps, which should cover many cases. However, if we just made JupyterHub an OAuth provider then services written in many different ways could more easily "authenticate with JupyterHub" using standard libraries for whatever toolkit they use.

I'm not planning to do this any time soon, but writing it down here, just in case.

**Comment by willingc** [comment]
In Progress. See PR #938.
