### ISSUE TITLE
Question: Is the individual Jupyter Session protected ? 

### ISSUE THREAD

**Issue by kwotuveang3k4bk** [jupyterhub/jupyterhub#555]
Jupyter Hub seems to be the perfect solution, I just have one question: If we start the other Jupyter sessions on the same system, is it than possible for a user with shell access to identify the session an access it ? 

For example user1 uses the weblogin to start his session in server:~/user1 - as it is the first jupyter server it spawns at Port 8888. Is it now possible for user2 logged in at server using ssh to access the jupyter session startet by user1 ? 

I guess it should be simple to prevent this behaviour by setting custom passwords for each individual user, but I am not exactly sure if that is already the case. http://jupyter-notebook.readthedocs.io/en/latest/public_server.html

**Comment by minrk** [comment]
>  Is it now possible for user2 logged in at server using ssh to access the jupyter session startet by user1?

No.

JupyterHub uses its own cookie authentication for all requests to single-user servers. Login happens directly with the Hub, which sets a cookie on the single-user servers. The single-user servers don't use a password themselves at any point, they just use cookies set by the Hub.

**Comment by kwotuveang3k4bk** [comment]
Ok, just for clarification: There is no way for user2, who has ssh access to the server which is running the jupyterhub as well as the local jupyter sessions to enter a jupyter notebook or jupyter session created by user1 in his user space.

**Comment by minrk** [comment]
Assuming user2 and user1 are running as different users on the system, they should be protected from each other by the system. The notebook server is protected by cookie-authentication with the Hub, and kernels are protected with a key stored in a user-private directory (typically ~/.local/jupyter/runtime).
