### ISSUE TITLE
Add documentation on api_tokens

### ISSUE THREAD

**Issue by willingc** [jupyterhub/jupyterhub#557]
Based on the mailing list comment:

> Okay I struggled for an hour after to find that the key->value in api_tokens is 'token' : 'username' not 'username': 'token' :)) 

The only place that mentions this (and it is correctly written) in the documentation is [the 0.6 changelog](https://jupyterhub.readthedocs.io/en/latest/changelog.html?highlight=api_tokens). We should add a more detailed section on `api_tokens`.

**Comment by ozancaglayan** [comment]
Hi,

As the struggler of the main discussion I can send a PR to update the documentation after setting up a local deployment stuff for doc building.

**Comment by willingc** [comment]
@ozancaglayan That would be great! Please let me know if you have any issues with building the docs.

**Comment by willingc** [comment]
Thanks @ozancaglayan for the documentation addition. 👍
