### ISSUE TITLE
Possible problems still with GitHub user ids

### ISSUE THREAD

**Issue by ellisonbg** [jupyterhub/jupyterhub#558]
Hi,

I am running jupyterhub with the default jupyterhub-deploy scripts (the ansible ones). Here is the config file:

https://github.com/jupyterhub/jupyterhub-deploy-teaching/blob/master/roles/jupyterhub/templates/jupyterhub_config.py.j2

I am still running into problems with GitHub ids that have some uppercase chars and other chars such as `-`. Not sure if this is a config issue, or otherwise. Looks like we are lowercasing the ids, but GitHub may not be consistent in how they handle user id casing. Would be good to do some actual tests with crazy GtiHub ids.

@willingc

**Comment by minrk** [comment]
I'll look into it. It's possible there are a few gaps in our username normalization (it may be in OAuthenticator, as well).

**Comment by willingc** [comment]
We now have additional tests for usernames ([example](https://github.com/jupyterhub/jupyterhub/blob/18c65453fd8cbae4f9a86a18f7b6dad3719ce9aa/jupyterhub/tests/test_proxy.py#L138)). I'm going to close this issue.
