### ISSUE TITLE
Refine step-by-step installation for inexperienced user 

### ISSUE THREAD

**Issue by stefanoborini** [jupyterhub/jupyterhub#561]
I can't say I am an expert in docker and jupyterhub. I want to try it out.

I start it from kitematic, and I get:

```
[I 2016-05-09 09:26:33.484 JupyterHub app:1231](B Hub API listening on http://127.0.0.1:8081/hub/
[E 2016-05-09 09:26:33.488 JupyterHub app:963](B Refusing to run JuptyterHub without SSL. If you are terminating SSL in another layer, pass --no-ssl to tell JupyterHub to allow the proxy to listen on HTTP.
```

So I struggle to find out how to pass this option in the kitematic client, and fail.
Search and search and I find that I can pass the option

```
docker run jupyter/jupyterhub jupyterhub --no-ssl
```

which finally starts

```
[W 2016-05-09 09:45:06.985 JupyterHub app:952] Running JupyterHub without SSL. There better be SSL termination happening somewhere else...
[I 2016-05-09 09:45:06.985 JupyterHub app:961] Starting proxy @ http://*:8000/
09:45:07.056 - info: [ConfigProxy] Proxying http://*:8000 to http://127.0.0.1:8081
09:45:07.057 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[I 2016-05-09 09:45:07.090 JupyterHub app:1247] JupyterHub is now running at http://127.0.0.1:8000/
```

So I try to open my browser and connect to 127.0.0.1:8000. Connection refused.
So maybe I have to specify the IP address of the docker VM? there's an --ip option.

```
[I 2016-05-09 09:42:26.982 JupyterHub app:961] Starting proxy @ http://192.168.99.100:5000/
09:42:27.051 - info: [ConfigProxy] Proxying http://192.168.99.100:5000 to http://127.0.0.1:8081
09:42:27.054 - info: [ConfigProxy] Proxy API at http://127.0.0.1:5001/api/routes

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRNOTAVAIL
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1023:19)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at dns.js:72:18
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
[C 2016-05-09 09:42:28.002 JupyterHub app:1230] Failed to start proxy
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/app.py", line 1228, in start
        yield self.start_proxy()
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/app.py", line 982, in start_proxy
        _check()
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/app.py", line 978, in _check
        raise e
    RuntimeError: Proxy failed to start with exit code 8
```

Nope... and here is where I give up. 

My point is that the basic installation should work out of the box, which clearly does not, at least on OSX.

**Comment by willingc** [comment]
@stefanoborini I'm sorry that the JupyterHub installation didn't meet your needs. Please know that we are working diligently to simplify the instructions for users wishing to trying out JupyterHub. 

We have recently begun to post "reference" deployments for common use cases. These reference deployments may be found in the JupyterHub organization as repos that begin with "jupyterhub-deploy-".

The "jupyterhub-deploy-docker" is the recommended "reference" deployment for a JupyterHub demo environment that you can spin up *relatively* quickly. We will continue to refine the documentation and user experience as we go forward.

Respectfully,
Carol

**Comment by stefanoborini** [comment]
> I'm sorry that the JupyterHub installation didn't meet your needs.

@willingc on the contrary. It's just great stuff. I spent the last 4 hours playing with it and scouting the code to hack it for my needs. Confirmed amazing. I just wanted to report a barrier to new adopters and the point where they might be more likely to struggle or give up if there are any problems with the docker container.

**Comment by willingc** [comment]
@stefanoborini Thanks for the enthusiasm about JupyterHub. Please keep sending us suggestions or tips that you think may help a new adopter. We are committed to making it a pleasant experience :smile:

**Comment by minrk** [comment]
@stefanoborini thanks for the feedback! I just presented [a tutorial](https://github.com/minrk/jupyterhub-pydata-2016) on deploying JupyterHub, and I plan to pull some of that information together into the JupyterHub docs as a step-by-step setup, explaining the basics of getting from zero-to-hub. From there, we can point to the reference deployments as more full-fledged examples.

**Comment by willingc** [comment]
@minrk Any thoughts on moving the whole repo over to the JupyterHub org as the initial tutorial for community members. Scanning through it, it's wonderful as is. We can perhaps iterate on it formally here.

**Comment by minrk** [comment]
I'd like to clean it up a bit for bringing it over here. I like to use dedicated personal repos for any given presentation, but you are right that most of that content really should be here somewhere. In particular, I don't think a Keynote presentation is entirely appropriate for one of our official repos.

**Comment by willingc** [comment]
@minrk I'm going to file an issue on your repo with a few thoughts. Frankly, it's the best end user doc/video on JHub that I've seen :tada:

**Comment by willingc** [comment]
Closing this issue since we now have a [jupyterhub tutorial](https://github.com/jupyterhub/jupyterhub-tutorial) and will continue to iterate on it as the project evolves.

Thanks @stefanoborini and @minrk. :cake:
