### ISSUE TITLE
Maintenance: Review issues prior to 2016-01-01 and close as appropriate

### ISSUE THREAD

**Issue by willingc** [jupyterhub/jupyterhub#562]
There are a number of open issues that have been resolved through user support or releases since the issues were filed. We should revisit these issues and close as appropriate.

**Comment by minrk** [comment]
That's certainly true, thanks!

**Comment by willingc** [comment]
In progress.

**Comment by willingc** [comment]
Triaged all of the open issues. Closed 42 issues. 53 remaining issues.

**Comment by minrk** [comment]
That's awesome, thanks @willingc! 🍰
