### ISSUE TITLE
Can't connect to Kernel anymore

### ISSUE THREAD

**Issue by precicely** [jupyterhub/jupyterhub#563]
Hi,

I can no longer connect to ipython kernels while using Jupyterhub and I was hoping someone could give me some pointers, my log is below:

> (py35)root@XXX:~# jupyterhub --ip 10.2.3.110 --port 80 --no-ssl --debug
> [D 2016-05-10 18:29:48.813 JupyterHub application:529] Looking for jupyterhub_config in None
> [I 2016-05-10 18:29:48.815 JupyterHub app:622] Loading cookie_secret from /home/ci/jupyterhub_cookie_secret
> [D 2016-05-10 18:29:48.815 JupyterHub app:694] Connecting to db: sqlite:///jupyterhub.sqlite
> [W 2016-05-10 18:29:48.863 JupyterHub app:304]
>     Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
>     Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
> 
> [W 2016-05-10 18:29:48.869 JupyterHub app:757] No admin users, admin interface will be unavailable.
> [W 2016-05-10 18:29:48.869 JupyterHub app:758] Add any administrative users to `c.Authenticator.admin_users` in config.
> [I 2016-05-10 18:29:48.870 JupyterHub app:785] Not using whitelist. Any authenticated user will be allowed.
> [D 2016-05-10 18:29:48.883 JupyterHub app:888] Loaded users:
>           ci
> [I 2016-05-10 18:29:48.893 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
> [W 2016-05-10 18:29:48.898 JupyterHub app:959] Running JupyterHub without SSL. There better be SSL termination happening somewhere else...
> [I 2016-05-10 18:29:48.898 JupyterHub app:968] Starting proxy @ http://10.2.3.110:80/
> [D 2016-05-10 18:29:48.898 JupyterHub app:969] Proxy cmd: ['configurable-http-proxy', '--ip', '10.2.3.110', '--port', '80', '--api-ip', '127.0.0.1', '--api-port', '81', '--default-target', 'http://127.0.0.1:8081', '--error-target', 'http://127.0.0.1:8081/hub/error']
> 18:29:49.129 - info: [ConfigProxy] Proxying http://10.2.3.110:80 to http://127.0.0.1:8081
> 18:29:49.133 - info: [ConfigProxy] Proxy API at http://127.0.0.1:81/api/routes
> [D 2016-05-10 18:29:49.207 JupyterHub app:997] Proxy started and appears to be up
> [I 2016-05-10 18:29:49.207 JupyterHub app:1254] JupyterHub is now running at http://10.2.3.110:80/
> [I 2016-05-10 18:30:05.406 JupyterHub log:100] 302 GET / (@10.2.3.1) 5.79ms
> [I 2016-05-10 18:30:05.424 JupyterHub log:100] 302 GET /hub (@10.2.3.1) 0.80ms
> [D 2016-05-10 18:30:05.449 JupyterHub pages:35] User is not running: /hub/home
> [I 2016-05-10 18:30:05.457 JupyterHub log:100] 302 GET /hub/ (ci@10.2.3.1) 6.55ms
> [I 2016-05-10 18:30:05.537 JupyterHub log:100] 200 GET /hub/home (ci@10.2.3.1) 62.71ms
> [D 2016-05-10 18:30:05.629 JupyterHub log:100] 304 GET /hub/logo (@10.2.3.1) 6.84ms
> [I 2016-05-10 18:30:11.289 JupyterHub log:100] 302 GET /hub/spawn (ci@10.2.3.1) 6.37ms
> [I 2016-05-10 18:30:11.309 JupyterHub log:100] 302 GET /user/ci (@10.2.3.1) 1.22ms
> Last login: Tue May 10 18:14:48 BST 2016
> Welcome to Ubuntu 12.04.5 LTS (GNU/Linux 3.11.0-15-generic x86_64)
> 
> 
> 
> [I 2016-05-10 18:30:11.955 JupyterHub spawner:467] Spawning jupyterhub-singleuser --user=ci --port=55872 --cookie-name=jupyter-hub-token-ci --base-url=/user/ci --hub-host= --hub-prefix=/hub/ --hub-api-url=http://127.0.0.1:8081/hub/api --ip=127.0.0.1
> [D 2016-05-10 18:30:11.990 JupyterHub spawner:316] Polling subprocess every 30s
> [I 2016-05-10 18:30:12.951 ci notebookapp:1116] Serving notebooks from local directory: /home/ci
> [I 2016-05-10 18:30:12.951 ci notebookapp:1116] 0 active kernels
> [I 2016-05-10 18:30:12.951 ci notebookapp:1116] The Jupyter Notebook is running at: http://127.0.0.1:55872/user/ci/
> [I 2016-05-10 18:30:12.952 ci notebookapp:1117] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
> [I 2016-05-10 18:30:12.981 ci log:47] 302 GET /user/ci (127.0.0.1) 1.50ms
> [D 2016-05-10 18:30:12.983 JupyterHub utils:84] Server at http://127.0.0.1:55872/user/ci responded with 302
> [I 2016-05-10 18:30:12.983 JupyterHub base:306] User ci server took 1.650 seconds to start
> [I 2016-05-10 18:30:12.984 JupyterHub orm:159] Adding user ci to proxy /user/ci => http://127.0.0.1:55872
> [D 2016-05-10 18:30:12.988 JupyterHub orm:146] Fetching POST http://127.0.0.1:81/api/routes/user/ci
> [D 2016-05-10 18:30:12.999 JupyterHub base:231] Setting cookie for ci: jupyter-hub-token-ci, {}
> [I 2016-05-10 18:30:13.014 JupyterHub log:100] 302 GET /hub/user/ci (ci@10.2.3.1) 1678.33ms
> [I 2016-05-10 18:30:13.050 ci log:47] 302 GET /user/ci (10.2.3.1) 0.56ms
> [I 2016-05-10 18:30:13.109 JupyterHub log:100] 200 GET /hub/api/authorizations/cookie/jupyter-hub-token-ci/[secret] (ci@127.0.0.1) 14.27ms
> [I 2016-05-10 18:30:18.678 ci kernelmanager:89] Kernel started: bfe7c636-5e7e-4308-81f8-a634717139ee
> [W 2016-05-10 18:30:19.553 ci log:47] 400 GET /user/ci/api/kernels/bfe7c636-5e7e-4308-81f8-a634717139ee/channels?session_id=6CE2C42B62F943D5A8B8D973DD48A176 (10.2.3.1) 724.85ms referer=None
> [W 2016-05-10 18:30:20.607 ci log:47] 400 GET /user/ci/api/kernels/bfe7c636-5e7e-4308-81f8-a634717139ee/channels?session_id=6CE2C42B62F943D5A8B8D973DD48A176 (10.2.3.1) 10.02ms referer=None
> [W 2016-05-10 18:30:22.719 ci log:47] 400 GET /user/ci/api/kernels/bfe7c636-5e7e-4308-81f8-a634717139ee/channels?session_id=6CE2C42B62F943D5A8B8D973DD48A176 (10.2.3.1) 10.25ms referer=None

The bizarre thing is that it was running just last week, and somehow, over the weekend when it was left idle, it broke itself. I'm guessing there must be a configuration problem but I'm just not familiar enough with the Jupyter-Jupyterhub stack to figure it all out. 

Here's a screen grab:
![jupyter](https://cloud.githubusercontent.com/assets/10998175/15156358/8b78d88c-16de-11e6-8dcb-16b241968219.png)

Furthermore, when I just run a Jupyter instance everything works as expected.

Any help would be appreciated. For example, where can i inspect/find the the following: "user/ci/api/kernels/bfe7c636-5e7e-4308-81f8-a634717139ee"

Cheers

**Comment by minrk** [comment]
If it's only kernels that don't work, this is typically a proxy/firewall issue. Do you have any AV, proxy, or firewall software running?

**Comment by precicely** [comment]
I've killed all those things and still it's not working. Is there a way to see if the kernel actually exists? Or is it perhaps a messaging problem?

**Comment by minrk** [comment]
You can look for processes loading `ipykernel` (`ps aux | grep ipykernel`). The notebook server should notice if a kernel died, so you would get different error messages from the failure to connect. One option is to try to open a terminal (New > Terminal from the dashboard). If it's websocket filtering that's going wrong, then it is likely that the websocket proxying is the issue. The 400 error you are seeing in the logs also points to the proxying problem.

You could also try a different browser and/or a Private tab, to see if any extensions are causing the problem. There was a recent issue where the `uBlock` ad blocker broke all websocket connections to any website.

**Comment by precicely** [comment]
So, as it stands:

Here are the results from "ps aux | grep ipykernel":

> (py35)root@XXX:~# ps aux | grep ipykernel
> root     21955  0.0  0.0   9388   932 pts/2    S+   09:32   0:00 grep --color=auto ipykernel
> (py35)root@XXX:~# ps aux | grep ipykernel
> ci       21960  0.7  0.0 624084 28896 ?        Ssl  09:36   0:00 /opt/anaconda3/envs/py27/bin/python -m ipykernel -f /home/ci/.local/share/jupyter/runtime/kernel-5580015a-3ba5-4827-8e02-49888c815d6e.json
> root     21977  0.0  0.0   9388   936 pts/2    S+   09:38   0:00 grep --color=auto ipykernel

Which if I'm honest, I don't really understand (especially why it differs the second time, but then again my linux-foo is weak).

Also, and more interesting I think, is when I go to the URL indicated by the 400 message I get the following message: Can "Upgrade" only to "WebSocket". e.g.:
![websocket](https://cloud.githubusercontent.com/assets/10998175/15243182/003687ea-18f2-11e6-8394-7e9e939e7aea.png)

And finally, when trying to launch a terminal, it fails once more, here's a screen grab from Chrome where the console says: "WebSocket connection to 'ws://10.2.3.110/user/ci/terminals/websocket/2' failed: Error during WebSocket handshake: Unexpected response code: 400" (similar story with Firefox). e.g.:

![google-websocket](https://cloud.githubusercontent.com/assets/10998175/15243388/299f109c-18f3-11e6-992b-cf64572b5e87.png)

So that where I'm at at the moment and I have sneaking suspicion it's got to do with proxies and the like but again, I'm way out of my depth.

Thanks for your tireless work minrk.

P.S. My package list just in case:
 > (py35)root@XXX:~# conda list
> \# packages in environment at /opt/anaconda3/envs/py35:
> #
> backports                 1.0                      py35_0    defaults
> backports.shutil-get-terminal-size 1.0.0                     <pip>
> decorator                 4.0.9                    py35_0    defaults
> entrypoints               0.2                      py35_1    defaults
> fontconfig                2.11.1                        5    defaults
> freetype                  2.5.5                         0    defaults
> get_terminal_size         1.0.0                    py35_0    defaults
> ipykernel                 4.3.1                    py35_0    defaults
> ipython                   4.2.0                    py35_0    defaults
> ipython-genutils          0.1.0                     <pip>
> ipython_genutils          0.1.0                    py35_0    defaults
> ipywidgets                4.1.1                    py35_0    defaults
> jinja2                    2.8                      py35_0    defaults
> jsonschema                2.5.1                    py35_0    defaults
> jupyter                   1.0.0                    py35_2    defaults
> jupyter-client            4.2.2                     <pip>
> jupyter-console           4.1.1                     <pip>
> jupyter-core              4.1.0                     <pip>
> jupyter_client            4.2.2                    py35_0    defaults
> jupyter_console           4.1.1                    py35_0    defaults
> jupyter_core              4.1.0                    py35_0    defaults
> jupyterhub                0.6.1                     <pip>
> libpng                    1.6.17                        0    <unknown>
> libsodium                 1.0.3                         0    defaults
> libxml2                   2.9.2                         0    <unknown>
> markupsafe                0.23                     py35_0    defaults
> mistune                   0.7.2                    py35_0    defaults
> nbconvert                 4.2.0                    py35_0    defaults
> nbformat                  4.0.1                    py35_0    defaults
> notebook                  4.2.0                    py35_0    defaults
> openssl                   1.0.2h                        0    defaults
> pamela                    0.2.1                     <pip>
> path.py                   8.2.1                    py35_0    defaults
> pexpect                   4.0.1                    py35_0    defaults
> pickleshare               0.5                      py35_0    defaults
> pip                       8.1.1                    py35_1    defaults
> ptyprocess                0.5                      py35_0    defaults
> pygments                  2.1.3                    py35_0    defaults
> pyqt                      4.11.4                   py35_1    defaults
> python                    3.5.1                         0    defaults
> pyzmq                     15.2.0                   py35_0    defaults
> qt                        4.8.7                         1    defaults
> qtconsole                 4.2.1                    py35_0    defaults
> readline                  6.2                           2    <unknown>
> requests                  2.10.0                    <pip>
> setuptools                20.7.0                   py35_0    defaults
> simplegeneric             0.8.1                    py35_0    defaults
> sip                       4.16.9                   py35_0    defaults
> sqlalchemy                1.0.12                    <pip>
> sqlite                    3.9.2                         0    defaults
> terminado                 0.5                      py35_1    defaults
> tk                        8.5.18                        0    <unknown>
> tornado                   4.3                      py35_0    defaults
> traitlets                 4.2.1                    py35_0    defaults
> wheel                     0.29.0                   py35_0    defaults
> widgetsnbextension        1.2.2                     <pip>
> xz                        5.0.5                         1    defaults
> zeromq                    4.1.3                         0    defaults
> zlib                      1.2.8                         0    <unknown>

**Comment by minrk** [comment]
That *really* sounds like the proxy/firewall issues that many people have seen on Windows, which break websockets. Have you tried other browsers and/or connecting from other machines?

**Comment by willingc** [comment]
@precicely Perhaps Firefox would be a good browser to try as you can set the proxy conditions. [Reference issue](https://github.com/jupyter/notebook/issues/1380#issuecomment-214230981)

**Comment by willingc** [comment]
Closing this issue. If additional help is needed, please comment and we can reopen the issue. Thanks!

**Comment by msvolenski** [comment]
I have had this same issue on macOS. The proposed solution did work, the kernel started when running the notebook on Firefox instead of Chrome, without any additional changes, so it really appears to be a proxy issue.
However, my questions are:

- Why does the kernel connect properly (in other browsers, besides Firefox) when running `jupyter notebook`, but not when running `jupyterhub`?
- Is there anything to be done about it to allow me to run `jupyterhub` in the same way as `jupyter notebook`, so I don't have to mess with my system's proxy config?

**Comment by minrk** [comment]
@msvolenski what are the ip and port used when it works and when it doesn't? Is one `127.0.0.1` and the other `localhost`? If so, that might be the key. We have seen AV/proxy tools that block one but not the other *in both directions*, so there doesn't appear to be a single, perfect solution.
