### ISSUE TITLE
How to set up jupyterhub for use with pyspark without interfering with the rest of your system

### ISSUE THREAD

**Issue by maxgrenderjones** [jupyterhub/jupyterhub#564]
### Problems we want to solve:
- I don't want to install jupyterhub to the general environment - I want it isolated  
- Jupyterhub only works with python3, I want to use python2
- I want my notebooks to spawn within a `virtualenv` initialised environment
- I want to have access to `pyspark` from within my notebooks

### Solution:
Install the dependencies:
 - install npm (`yum install npm`)
 - install python3 (`yum install python34`)
 - install zmq libraries (`yum install czmq-devel`)

Install Jupyterhub:
 - Create a virtualenv (`virtualenv --python=python3 /path/to/jupyterhub`)
 - Create the SSL keys and otherwise configure jupyterhub. 
 - Create the file that sets up the environment - note that it's running in python3 so you need to force it to use python2:
```
#!/usr/bin/env bash
source /path/to/env/bin/activate
# exec is important!
exec python2 /path/to/jupyterhub-singleuser $@
``` 
 - Tell jupyterhub to run this script `c.Spawner.cmd = '/path/to/your-script'`
 - Create a launcher script that activates the jupyterhub virtualenv, then launches jupyterhub.
```
#!/usr/bin/env bash
source /path/to/jupyterhub/bin/activate
jupyterhub -f /path/to/jupyterhub/config/jupyterhub_config.py
```
- Run the script (`sudo /path/to/launcher.sh`)

To get pyspark working in your notebook (note that you will need to `pip install findspark` within your notebook's virtualenv):
```python
get_sql_context(appName)
	if 'sqlContext' not in globals(): # You can't have more than one sqlContext running at a time
		global sqlContext
		import findspark
		findspark.init()
		from pyspark import SparkContext
		from pyspark.sql import HiveContext
		sqlContext = HiveContext(SparkContext(appName=appName))
	return sqlContext
```

**Comment by willingc** [comment]
@maxgrenderjones Thanks for sharing this with others. I'm going to close this as an issue but I will label it as "reference". Nicely done.
