### ISSUE TITLE
PEM_read_bio:no start line

### ISSUE THREAD

**Issue by LMtx** [jupyterhub/jupyterhub#570]
How can I configure Jupyterhub to work with chain certificates? I have my certs from Entrust:
my_name.key
> -----BEGIN CERTIFICATE-----
....
-----END CERTIFICATE-----

Entrust_Root.txt
> -----BEGIN CERTIFICATE-----
....
-----END CERTIFICATE-----

Entrust_L1Kroot.txt
> -----BEGIN CERTIFICATE-----
....
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
....
-----END CERTIFICATE-----

When I try to start Jupyterhub I get following error:

> crypto.js:131

      c.context.setKey(options.key);
                ^
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.exports.createCredentials (crypto.js:131:17)
    at Server (tls.js:1128:28)
    at new Server (https.js:35:14)
    at Object.exports.createServer (https.js:54:10)
    at new ConfigurableProxy (/usr/lib/node_modules/configurable-http-proxy/lib/configproxy.js:158:35)
    at Object.<anonymous> (/usr/lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy:171:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
[C 2016-05-13 15:44:24.633 JupyterHub app:1119] Failed to start proxy
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/jupyterhub/app.py", line 1117, in start
        yield self.start_proxy()
      File "/usr/local/lib/python3.5/site-packages/jupyterhub/app.py", line 881, in start_proxy
        _check()
      File "/usr/local/lib/python3.5/site-packages/jupyterhub/app.py", line 877, in _check
        raise e
    RuntimeError: Proxy failed to start with exit code 8

When I check certificates they look ok:
> openssl x509 -text -inform PEM -in my_name.key
openssl x509 -text -inform PEM -in Entrust_Root.txt
openssl x509 -text -inform PEM -in Entrust_L1Kroot.txt

**Comment by ryanlovett** [comment]
I saw something similar when I accidentally reversed the certificate and key arguments.

**Comment by LMtx** [comment]
Ok, but I have 3 files for chain certificate so which should I point as
>c.JupyterHub.ssl_key
c.JupyterHub.ssl_cert

**Comment by ryanlovett** [comment]
I believe you should append the chain and root certs to your host cert, e.g.

```cat your_name.crt Entrust_L1Kroot.txt Entrust_Root.txt > your_name-chained.crt```

and set `ssl_cert` to your_name-chained.crt and `ssl_key` to your private key.

**Comment by LMtx** [comment]
I have tried:

>cat my_name.key Entrust_L1Kroot.txt Entrust_Root.txt > your_name-chained.crt

and set:

>c.JupyterHub.ssl_cert = u'/path/to/your_name-chained.crt'
c.JupyterHub.ssl_key = u'/path/to/my_name.key'

But it did not worked.

Then I tried:

>cat Entrust_L1Kroot.txt Entrust_Root.txt > your_name-chained.crt

and set:

>c.JupyterHub.ssl_cert = u'/path/to/your_name-chained.crt'
c.JupyterHub.ssl_key = u'/path/to/my_name.key'

But that did not work neither.

Are you sure that Jupyterhub is able to work with chain certificates? Maybe it will only work witch pair of public/private key?

**Comment by LMtx** [comment]
Maybe there is another problem. I generated key and certificate to verify if jupyterhub will work and I got following error:

    sudo -u jupyterhub jupyterhub -f /tmp/jupyter/conf/jupyterhub_config.py
    [I 2016-05-17 14:38:53.254 JupyterHub app:558] Loading cookie_secret from /tmp/jupyter/srv/cookie_secret
    [W 2016-05-17 14:38:53.305 JupyterHub app:685] No admin users, admin interface will be unavailable.
    [W 2016-05-17 14:38:53.305 JupyterHub app:686] Add any administrative users to `c.Authenticator.admin_users` in config.
    [I 2016-05-17 14:38:53.305 JupyterHub app:712] Not using whitelist. Any authenticated user will be allowed.
    [I 2016-05-17 14:38:53.367 JupyterHub app:1113] Hub API listening on http://127.0.0.1:8081/hub/
    [I 2016-05-17 14:38:53.373 JupyterHub app:860] Starting proxy @ http://*:443/
    14:38:53.543 - info: [ConfigProxy] Proxying https://*:443 to http://127.0.0.1:8081
    14:38:53.547 - info: [ConfigProxy] Proxy API at http://127.0.0.1:444/api/routes

    events.js:72
    throw er; // Unhandled 'error' event
          ^
    Error: listen EACCES
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:448:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:935:3
    [C 2016-05-17 14:38:54.387 JupyterHub app:1119] Failed to start proxy
    Traceback (most recent call last):
    File "/usr/local/lib/python3.5/site-packages/jupyterhub/app.py", line 1117, in start
    yield self.start_proxy()
    File "/usr/local/lib/python3.5/site-packages/jupyterhub/app.py", line 881, in start_proxy
    _check()
    File "/usr/local/lib/python3.5/site-packages/jupyterhub/app.py", line 877, in _check
    raise e
    RuntimeError: Proxy failed to start with exit code 8

My config file:

    c.JupyterHub.cookie_secret_file = '/tmp/jupyter/srv/cookie_secret'
    c.JupyterHub.db_url = 'sqlite:////etc/jupyterhub/jupyterhub.sqlite'
    c.JupyterHub.port = 443
    c.JupyterHub.proxy_auth_token = '...'
    c.JupyterHub.spawner_class = 'sudospawner.SudoSpawner'
    c.JupyterHub.ssl_cert = '/tmp/jupyter/srv/ssl/ssl.cert'
    c.JupyterHub.ssl_key = '/tmp/jupyter/srv/ssl/ssl.key'

Any idea what is wrong?

**Comment by willingc** [comment]
@rgbkrk @minrk Any thoughts on chained certs beyond @ryanlovett's helpful suggestions?

**Comment by willingc** [comment]
@LMtx The [jupyterhub tutorial](https://github.com/jupyterhub/jupyterhub-tutorial/blob/master/JupyterHub.pdf) has an example using Let's Encrypt with a chained certificate in pem files. The [jupyterhub documentation](https://github.com/jupyterhub/jupyterhub-tutorial/blob/master/JupyterHub.pdf) also gives the same example (perhaps in a more easily readable format). If you have the ``.pem`` files, you might wish to try setting the key and cert to those.

**Comment by ryanlovett** [comment]
@LMtx You appended the intermediate and root to the private key, not the certificate. The vendor should have provided you with the host cert in addition to the intermediate and root certs.

@willingc Looks like the doc link in https://github.com/jupyterhub/jupyterhub/issues/570#issuecomment-219741251 goes to the tutorial too. (but if it is the same example then I guess it doesn't matter too much :)

**Comment by willingc** [comment]
@ryanlovett Thanks. Copy-pasta error :( I've fixed the link so it goes to the docs now. Thanks for the heads up.

**Comment by LMtx** [comment]
@ryanlovett You are right - I concatenated private key instead of certificate and that was why it wasn't working. Thank you so much for help!

@willingc I read documentation you pointed before posting the issue. For me it wasn't clear that I have to join all the certs in one file. I think that @ryanlovett example should be included in the docs to make it clear for everyone.

Thank you one more time!

**Comment by willingc** [comment]
@LMtx I agree about adding to the docs @ryanlovett's example. I'll ping you both for review once I incorporate it into the docs. Thanks!
