### ISSUE TITLE
How to add kernel.json file common to all users?

### ISSUE THREAD

**Issue by Balajideivam** [jupyterhub/jupyterhub#575]
I have added under /usr/local/share/jupyter/kernels but it is not able to load for all users. IS there anywhere else have to change the configuration? I am using Python3.5 with jupyterhub.

**Comment by minrk** [comment]
How does it fail to load? That location should be found by all users. Did you check the permissions on the directory, to ensure that all users can read the file? Also check the contents, to be sure that the kernelspec points to an executable that all users can run.

**Comment by Balajideivam** [comment]
Somehow it resolved by itself. I checked perm as well but everything looks good, stil that time it was not loaded.

**Comment by willingc** [comment]
Closing since it appears that this is resolved.
