### ISSUE TITLE
How to set up jupyterhub for multiple users on EC2?

### ISSUE THREAD

**Issue by theNewFlesh** [jupyterhub/jupyterhub#576]
I am trying to set up jupyterhub on an EC2 instance with ansible.  I can get it to run with --no-ssl and as the user the hub spawns under.  However, I cannot login as a different user.  

I have a "devops" user who is part of the sudo group who sshes in via ansible, becomes root when necessary and installs everything.  That works fine.  

After that I have an ansible role I've written that sshes in as a user ("devops" in this case), and generates a private key, public key and certificate.  Then it adds that public key to all the users' authorized_keys files (~/.ssh/authorized_keys) listed in the ansible playbook.  Then it writes the jupyterhub_config.py file.  

I mostly get PAM errors when I try to login as a different user, say "alex".
However, I also tried the sudoless user trick listed here: https://github.com/jupyterhub/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges, with the user and group "jupyterhub".  Same deal, it doesn't work for any user but "devops".

My ansible role can be found here:
https://github.com/theNewFlesh/ansible-role-jupyterhub-config

Help would be much appreciated.

**Comment by minrk** [comment]
What PAM errors do you get? Can you include logs? Are you using SudoSpawner or the default spawner?

**Comment by theNewFlesh** [comment]
PAM authentication error.  I've tried both.

**Comment by theNewFlesh** [comment]
My guess is that I do not understand the proper way to set it up with ssh keys and ssl certificates.  I was generating a private key, public key and certificate in the server user's .ssh folder.  Then adding that public key to all the other users ~/.ssh/authorized_keys files.  I was able to run jupyterhub process with this configuration but only was ever able to login to the user who owned that process.  I tried the same thing with sudoless but got the same results.

**Comment by theNewFlesh** [comment]
**When I run:**
`ubuntu@ip-172-31-10-242:~/.jupyterhub:        sudo jupyterhub --config jupyterhub_config.py`

**I get**
`[I 2016-05-18 23:26:10.576 JupyterHub app:622] Loading cookie_secret from /home/ubuntu/.ssh/jupyterhub_cookie_secret
[W 2016-05-18 23:26:10.604 JupyterHub app:757] No admin users, admin interface will be unavailable.
[W 2016-05-18 23:26:10.605 JupyterHub app:758] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2016-05-18 23:26:10.605 JupyterHub app:785] Not using whitelist. Any authenticated user will be allowed.
[I 2016-05-18 23:26:10.615 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
[I 2016-05-18 23:26:10.619 JupyterHub app:968] Starting proxy @ http://*:443/
23:26:10.714 - warn: [ConfigProxy] REST API is not authenticated.
23:26:10.728 - info: [ConfigProxy] Proxying https://*:443 to http://127.0.0.1:8081
23:26:10.728 - info: [ConfigProxy] Proxy API at http://127.0.0.1:444/api/routes
[I 2016-05-18 23:26:10.823 JupyterHub app:1254] JupyterHub is now running at http://127.0.0.1:443/
[I 2016-05-18 23:27:04.506 JupyterHub log:100] 302 GET / (@216.38.138.30) 1.17ms
[I 2016-05-18 23:27:04.641 JupyterHub log:100] 302 GET /hub (@216.38.138.30) 0.39ms
[I 2016-05-18 23:27:04.675 JupyterHub log:100] 302 GET /hub/ (@216.38.138.30) 0.88ms
[I 2016-05-18 23:27:04.879 JupyterHub log:100] 200 GET /hub/login (@216.38.138.30) 30.90ms
[W 2016-05-18 23:27:05.499 JupyterHub web:1521] 403 GET /hub/logo (216.38.138.30):  is not a file
[W 2016-05-18 23:27:05.499 JupyterHub log:100] 403 GET /hub/logo (@216.38.138.30) 1.03ms`

**When I try to login as a user I get this:**
`PAM Authentication failed (test01@216.38.138.30): [PAM Error 7] Authentication failure`

**Comment by theNewFlesh** [comment]
Also I'de enabled passwordless sudo for users in the sudo group.

**Comment by theNewFlesh** [comment]
**When I run the same command without sudo, I get:**
```
[I 2016-05-18 23:39:00.831 JupyterHub app:968] Starting proxy @ http://*:443/
23:39:00.924 - warn: [ConfigProxy] REST API is not authenticated.
23:39:00.937 - info: [ConfigProxy] Proxying https://*:443 to http://127.0.0.1:8081
23:39:00.938 - info: [ConfigProxy] Proxy API at http://127.0.0.1:444/api/routes

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1020:19)
    at listen (net.js:1061:10)
    at net.js:1143:9
    at dns.js:72:18
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:902:3
[C 2016-05-18 23:39:01.839 JupyterHub app:1237] Failed to start proxy
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 1235, in start
        yield self.start_proxy()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 989, in start_proxy
        _check()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 985, in _check
        raise e
    RuntimeError: Proxy failed to start with exit code 8
```

**Comment by minrk** [comment]
Can you test login with:

    sudo python3 -m pamela -a [username]

?

**Comment by theNewFlesh** [comment]
That gives me:
`[PAM Error 7] Authentication failure`

**Comment by theNewFlesh** [comment]
I was able to get Jupyterhub up and running last night via ansible.  However, the notebooks will not launch/connect to ipython kernels.  

Turns out I needed to use an SSL key instead of and SSH key, change a bunch of settings and fix some bugs in the templating.  It's all in my repo.

**Comment by theNewFlesh** [comment]
That seems to work

**Comment by theNewFlesh** [comment]
I ran pamela on a bunch of my users and this is these are the responses.

`$ python3`

```
>>> import pamela
>>> import getpass
```
**jupyter user**
```
>>> print(pamela.authenticate('jupyter', getpass.getpass()))
Password:
None
```
** alex user**
```
>>> print(pamela.authenticate('alex', getpass.getpass()))
Password:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/pamela.py", line 272, in authenticate
    return pam_end(handle, retval)
  File "/usr/local/lib/python3.4/dist-packages/pamela.py", line 220, in pam_end
    raise PAMError(errno=retval)
pamela.PAMError: [PAM Error 7] Authentication failure
```
**root user**
```
>>> print(pamela.authenticate('root', getpass.getpass()))
Password:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/pamela.py", line 272, in authenticate
    return pam_end(handle, retval)
  File "/usr/local/lib/python3.4/dist-packages/pamela.py", line 220, in pam_end
    raise PAMError(errno=retval)
pamela.PAMError: [PAM Error 3] Error in service module
```
**devops user**
```
>>> print(pamela.authenticate('devops', getpass.getpass()))
Password:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/pamela.py", line 272, in authenticate
    return pam_end(handle, retval)
  File "/usr/local/lib/python3.4/dist-packages/pamela.py", line 220, in pam_end
    raise PAMError(errno=retval)
pamela.PAMError: [PAM Error 7] Authentication failure
```

**Comment by theNewFlesh** [comment]
I've given up on running jupyterhub under a non-root user.

Now I just need the Kernel to connect.

When I run it under root, I can start up a server, login and open a notebook, but the notebook will not connect to its iPython Kernel.

```
IPKernelApp] WARNING | Unknown error in handling startup files:
```

**Comment by minrk** [comment]
If you set `c.Spawner.debug = True` in config, it will enable debug-logging of single-user servers, as well. That might point us in the right direction. It's *very* strange that the kernel's error-logging doesn't log the error.

**Comment by theNewFlesh** [comment]
When I run a kernel with c.spawner.debug = True, I get:

```
[I 2016-05-24 19:52:48.194 jupyter handlers:170] Creating new notebook in
[D 2016-05-24 19:52:48.195 jupyter filemanager:388] Saving /home/jupyter/Documents/jupyter/notebooks/Untitled3.ipynb
[D 2016-05-24 19:52:48.205 jupyter log:47] 201 POST /user/jupyter/api/contents (216.38.138.30) 11.78ms
[D 2016-05-24 19:52:48.256 jupyter handlers:178] Using contents: services/contents
[D 2016-05-24 19:52:48.257 jupyter log:47] 200 GET /user/jupyter/notebooks/Untitled3.ipynb?kernel_name=python3 (216.38.138.30) 1.64ms
[D 2016-05-24 19:52:48.346 jupyter log:47] 304 GET /user/jupyter/static/components/MathJax/MathJax.js?config=TeX-AMS_HTML-full,Safe&delayStartupUntil=configured (216.38.138.30) 0.64ms
[D 2016-05-24 19:52:48.347 jupyter log:47] 304 GET /user/jupyter/custom/custom.css (216.38.138.30) 0.53ms
[D 2016-05-24 19:52:48.369 jupyter log:47] 200 GET /user/jupyter/static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe (216.38.138.30) 0.66ms
[D 2016-05-24 19:52:48.378 jupyter log:47] 304 GET /user/jupyter/static/components/MathJax/config/TeX-AMS_HTML-full.js?rev=2.6.0 (216.38.138.30) 0.49ms
[D 2016-05-24 19:52:48.655 jupyter log:47] 200 GET /user/jupyter/custom/custom.js?v=20160524195151 (216.38.138.30) 0.78ms
[D 2016-05-24 19:52:48.668 jupyter log:47] 304 GET /user/jupyter/static/components/MathJax/config/Safe.js?rev=2.6.0 (216.38.138.30) 0.49ms
[D 2016-05-24 19:52:48.680 jupyter log:47] 200 GET /user/jupyter/api/config/notebook?_=1464119573546 (216.38.138.30) 1.97ms
[D 2016-05-24 19:52:48.682 jupyter log:47] 200 GET /user/jupyter/api/config/common?_=1464119573547 (216.38.138.30) 1.78ms
[D 2016-05-24 19:52:48.701 jupyter kernelspec:139] Native kernel (python3) available from /usr/local/lib/python3.4/dist-packages/ipykernel/resources
[D 2016-05-24 19:52:48.701 jupyter kernelspec:139] Native kernel (python3) available from /usr/local/lib/python3.4/dist-packages/ipykernel/resources
[D 2016-05-24 19:52:48.702 jupyter log:47] 200 GET /user/jupyter/api/kernelspecs (216.38.138.30) 1.19ms
[D 2016-05-24 19:52:48.721 jupyter log:47] 200 GET /user/jupyter/api/contents/Untitled3.ipynb?type=notebook&_=1464119573548 (216.38.138.30) 9.01ms
[D 2016-05-24 19:52:48.772 jupyter log:47] 304 GET /user/jupyter/static/components/MathJax/jax/output/HTML-CSS/fonts/STIX-Web/fontdata.js?rev=2.6.0 (216.38.138.30) 0.56ms
[D 2016-05-24 19:52:48.814 jupyter kernelspec:139] Native kernel (python3) available from /usr/local/lib/python3.4/dist-packages/ipykernel/resources
[D 2016-05-24 19:52:48.814 jupyter manager:241] Starting kernel: ['/usr/bin/python3', '-m', 'ipykernel', '-f', '/home/jupyter/.local/share/jupyter/runtime/kernel-51a3f313-e6f8-4ce2-95f3-2b2d28bd07d2.json']
[D 2016-05-24 19:52:48.817 jupyter connect:451] Connecting to: tcp://127.0.0.1:50993
[I 2016-05-24 19:52:48.818 jupyter kernelmanager:89] Kernel started: 51a3f313-e6f8-4ce2-95f3-2b2d28bd07d2
[D 2016-05-24 19:52:48.818 jupyter kernelmanager:90] Kernel args: {'kernel_name': 'python3', 'cwd': '/home/jupyter/Documents/jupyter/notebooks'}
[D 2016-05-24 19:52:48.819 jupyter log:47] 201 POST /user/jupyter/api/sessions (216.38.138.30) 11.17ms
[D 2016-05-24 19:52:48.820 jupyter kernelspec:139] Native kernel (python3) available from /usr/local/lib/python3.4/dist-packages/ipykernel/resources
[D 2016-05-24 19:52:48.820 jupyter handlers:18] Serving kernel resource from: /usr/local/lib/python3.4/dist-packages/ipykernel/resources
[D 2016-05-24 19:52:48.820 jupyter log:47] 200 GET /user/jupyter/kernelspecs/python3/logo-64x64.png (216.38.138.30) 1.24ms
[D 2016-05-24 19:52:48.821 jupyter log:47] 200 GET /user/jupyter/api/contents/Untitled3.ipynb/checkpoints?_=1464119573549 (216.38.138.30) 0.62ms
[D 2016-05-24 19:52:48.845 jupyter handlers:178] Using contents: services/contents
[W 2016-05-24 19:52:48.846 jupyter log:47] 404 GET /user/jupyter/nbextensions/widgets/notebook/js/extension.js?v=20160524195151 (216.38.138.30) 1.46ms referer=https://52.53.173.62/user/jupyter/notebooks/Untitled3.ipynb?kernel_name=python3
[D 2016-05-24 19:52:48.850 jupyter log:47] 200 GET /user/jupyter/static/components/MathJax/extensions/Safe.js?rev=2.6.0 (216.38.138.30) 0.57ms
[D 2016-05-24 19:52:48.872 jupyter log:47] 304 GET /user/jupyter/static/components/jquery-ui/themes/smoothness/images/ui-icons_222222_256x240.png (216.38.138.30) 0.88ms
[D 2016-05-24 19:52:48.920 jupyter log:47] 200 GET /user/jupyter/api/kernels/51a3f313-e6f8-4ce2-95f3-2b2d28bd07d2?_=1464119573550 (216.38.138.30) 0.60ms
[IPKernelApp] WARNING | Unknown error in handling startup files:
[D 2016-05-24 19:52:49.980 jupyter log:47] 200 GET /user/jupyter/api/kernels/51a3f313-e6f8-4ce2-95f3-2b2d28bd07d2?_=1464119573551 (216.38.138.30) 0.61ms
[D 2016-05-24 19:52:52.033 jupyter log:47] 200 GET /user/jupyter/api/kernels/51a3f313-e6f8-4ce2-95f3-2b2d28bd07d2?_=1464119573552 (216.38.138.30) 0.61ms
[D 2016-05-24 19:52:56.087 jupyter log:47] 200 GET /user/jupyter/api/kernels/51a3f313-e6f8-4ce2-95f3-2b2d28bd07d2?_=1464119573553 (216.38.138.30) 0.63ms
```

**Comment by minrk** [comment]
Do you see anything in the javascript console of your browser when it's trying to connect?

**Comment by theNewFlesh** [comment]
This is the only interesting thing I get:
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (underscore-min.map;, line 0)

https://52.53.173.62/user/jupyter/static/tree/js/underscore-min.map;
```

**Comment by willingc** [comment]
Passing along info about the Docker for AWS beta (https://blog.docker.com/2016/06/azure-aws-beta/) as an FYI. Although the original question talks about Ansible and credentials, the Docker for AWS beta sounds from the DockerCon talk that it will have reasonable security defaults included.

**Comment by willingc** [comment]
Closing issue.

**Resolution**
This information written by @jtyberg on our reference docker deployment provides information on deploying on EC2. jupyterhub/jupyterhub-deploy-docker#1 (comment)

Additional documentation will be added by https://github.com/jupyterhub/jupyterhub/issues/708  as well.
