### ISSUE TITLE
Issue with starting pyspark from jupyterhub

### ISSUE THREAD

**Issue by Balajideivam** [jupyterhub/jupyterhub#579]
HI, I have installed pyspark 1.6.1 which is working fine from the command prompt. I am trying to add the same pyspark into jupyerhub notebook, but it is throwing some error as below. 

Please suggest me if anything needs to be changed or how to troubleshoot from here. 

```
**ERROR:**
Exception in thread "main" java.lang.IllegalArgumentException: pyspark does not support any application options.
        at org.apache.spark.launcher.CommandBuilderUtils.checkArgument(CommandBuilderUtils.java:242)
        at org.apache.spark.launcher.SparkSubmitCommandBuilder.buildPySparkShellCommand(SparkSubmitCommandBuilder.java:241)
        at org.apache.spark.launcher.SparkSubmitCommandBuilder.buildCommand(SparkSubmitCommandBuilder.java:117)
        at org.apache.spark.launcher.Main.main(Main.java:86)





**pyspark kernel.json file:**

{
"display_name": "Spark 1.5.1 (Scala 2.10.4)",
"language_info": { "name": "scala" },
"argv":[
  "/hadoop/spark1.6.1/spark-1.6.1-bin-without-hadoop/bin/pyspark",
  "-profile",
  "{connection_file}"
 ],
"codemirror_mode": "scala",
 "env": {
"MASTER":"yarn",
"HADOOP_CONF_DIR":"/etc/hadoop/conf/",
"SPARK_DIST_CLASSPATH":"/etc/hadoop/conf/:/usr/iop/4.1.0.0/hadoop/lib/*:/usr/iop/4.1.0.0/hadoop/.//*:/usr/iop/4.1.0.0/hadoop-hdfs/./:/usr/iop/4.1.0.0/hadoop-hdfs/lib/*:/usr/iop/4.1.0.0/hadoop-hdfs/.//*:/usr/iop/4.1.0.0/hadoop-yarn/lib/*:/usr/iop/4.1.0.0/hadoop-yarn/.//*:/usr/iop/4.1.0.0/hadoop-mapreduce/lib/*:/usr/iop/4.1.0.0/hadoop-mapreduce/.//*::/usr/share/java/mysql-connector-java-5.1.17.jar:/usr/share/java/mysql-connector-java.jar:/usr/iop/current/hadoop-mapreduce-client/*",
"PATH": "/hadoop/jupyterhub/anaconda2/bin:/usr/lib64/qt-3.3/bin:/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/sysbin",
"SPARK_HOME": "/hadoop/spark1.6.1/spark-1.6.1-bin-without-hadoop",
"PYSPARK_SUBMIT_ARGS": "--master spark://127.0.0.1:7077 pyspark-shell",
 "PYTHONPATH": "/hadoop/spark1.6.1/spark-1.6.1-bin-without-hadoop/python/:/hadoop/spark1.6.1/spark-1.6.1-bin-without-hadoop/python/lib/py4j-0.9-src.zip:/hadoop/spark1.6.1/spark-1.6.1-bin-without-hadoop/bin",
 "PYTHONSTARTUP": "/hadoop/spark1.6.1/spark-1.6.1-bin-without-hadoop/bin/pyspark"
 }
}
```

**Comment by Balajideivam** [comment]
Can someone help me out?

**Comment by minrk** [comment]
Where did you get this kernelspec? It is strange that it starts pyspark directly and then uses `-profile {jupyter-connection-file}`.

Generally, when using pyspark you would use the regular IPython kernel and load pyspark as a library.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:

**Comment by BhagyasriYella** [comment]
Hi I am getting the same error when I am trying to run  Analytics Zoo Object Detection example.

These are the steps that are given to run with jupyter notebook:

> - Run export SPARK_HOME=the root directory of Spark.
> - Run export ANALYTICS_ZOO_HOME=the dist directory under the Analytics Zoo project.
> - Run pip install moviepy.
> - Prepare the video in YouTube-8M to detect. (YouTube-8M and The video).
> - Run $ANALYTICS_ZOO_HOME/apps/object-detection/download_model.sh to download the pretrained model.
> - Run the following bash command to start the jupyter notebook. Change parameter settings as you need, ie MASTER = local[physcial_core_number].
> 
> MASTER=local[*]
> ${ANALYTICS_ZOO_HOME}/bin/jupyter-with-zoo.sh \
>     --master ${MASTER} \
>     --driver-cores 2  \
>     --driver-memory 8g  \
>     --total-executor-cores 2  \
>     --executor-cores 2  \
>     --executor-memory 8g




So I have tried doing the above as following:
export SPARK_HOME=/opt/cloudera/parcels/CDH-5.13.2-1.cdh5.13.2.p0.3/lib/spark
export ANALYTICS_ZOO_HOME=/root/Desktop/analytics-zoo/dist
$ANALYTICS_ZOO_HOME/apps/object-detection/download_model.sh
MASTER=local[*]
${ANALYTICS_ZOO_HOME}/bin/jupyter-with-zoo.sh \
--master ${MASTER} \
--driver-cores 2  \
--driver-memory 8g  \
--total-executor-cores 2  \
--executor-cores 2  \
--executor-memory 8g

but when I am getting the following error:
Exception in thread "main" java.lang.IllegalArgumentException: pyspark does not support any application options.
        at org.apache.spark.launcher.CommandBuilderUtils.checkArgument(CommandBuilderUtils.java:242)
        at org.apache.spark.launcher.SparkSubmitCommandBuilder.buildPySparkShellCommand(SparkSubmitCommandBuilder.java:241)
        at org.apache.spark.launcher.SparkSubmitCommandBuilder.buildCommand(SparkSubmitCommandBuilder.java:117)
        at org.apache.spark.launcher.Main.main(Main.java:86)

Please help me out with this .
