### ISSUE TITLE
Logs http url even when https is used

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#580]
When JupyterHub starts up, it logs something like:

```
JupyterHub is now running at http://127.0.0.1:8000
```

even if https is used, so attempts to copy/paste will fail to connect.

**Comment by willingc** [comment]
@minrk Do you want me to label this contributor friendly?

**Comment by prasadkatti** [comment]
Hi. This looks like it is already fixed! :)

`JupyterHub is now running at https://0.0.0.0:8000/`

Seems to have been fixed by - minrk@be8f847

**Comment by willingc** [comment]
Good catch @prasadkatti. Happy to close :smile:
