### ISSUE TITLE
Cluster for JupyterHub

### ISSUE THREAD

**Issue by amuktharao** [jupyterhub/jupyterhub#581]
Hi,

Could you please let me know if we have the option to have a cluster for JupyterHub, we would like to use multiple servers for JupyterHub.

Thanks,
Amuktha

**Comment by minrk** [comment]
It is up to the Spawner how to start each notebook server. This may be locally, as is the default, or distributed across a cluster. One way to do this is to use [dockerspawner](https://github.com/jupyterhub/dockerspawner) with Docker Swarm. Another is to use PBS or other cluster job launcher with [batchspawner](https://github.com/mbmilligan/batchspawner).

**Comment by willingc** [comment]
I'm going to close this issue. I'm also going to label this as "reference" to help future users with a similar question.
