### ISSUE TITLE
Opening JupyterHub to outside connections

### ISSUE THREAD

**Issue by bjlange** [jupyterhub/jupyterhub#588]
I've followed the instructions [here](https://github.com/jupyterhub/jupyterhub/wiki/Installation-of-Jupyterhub-on-remote-server) and [here](https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service) to install and run JupyterHub as a service on an Ubuntu server, at 127.0.0.1:8000. The service runs, and if I `wget 127.0.0.1:8000` it downloads the login page, so it seems the JupyterHub server is running. However, if I try to go to <my server's IP address>:8000 to access it, it hangs for a while (saying "Connecting..." in the bottom right in Chrome) and ultimately fails.

What's missing here? Do I need to configure some kind of forwarding, or something like `nginx` to forward outside requests to the server? Do I need to run it on a differen port/IP and how would I determine which one? Looking for the simplest solution, only needs to serve 4 or 5 people at a time at most.

**Comment by jochym** [comment]
127.0.0.1 is the localhost address. If your service listens on localhost it is unreachable from the outside. To have outside-reachable server you need to listen on 0.0.0.0:8000 or on your ip:8000. But - be sure you are ready to have the service on public address. The internet is a hostile place. I am running my server in the closed VPN behind the firewall and I am not thinking about exposing it to the internet. And I have over two decades of system administration experience... so think before acting. I am sure the developers take security seriously but the project did not have the exposure to security audits like apache or other projects intended for public internet exposure.

**Comment by minrk** [comment]
JupyterHub listens on all ports by default, so no configuration is needed if your server is publicly accessible. You can specify a particular IP with `--ip=a.b.c.d`, and then it will listen only on that IP. What happens when you enter a particular interface IP and try to connect?

**Comment by bjlange** [comment]
Re: outside connections, this is on an internal network behind a firewall, so I don't mean the whole public internet. I realize the peril of that, but glad you put it here for people who stumble across this in the future.

It seems to start up just fine:
```bash
$ sudo jupyterhub --no-ssl
[I 2016-05-31 17:30:48.472 JupyterHub app:622] Loading cookie_secret from /home/ubuntu/data-games/jupyterhub_cookie_secret
[W 2016-05-31 17:30:48.546 JupyterHub app:304]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[W 2016-05-31 17:30:48.587 JupyterHub app:757] No admin users, admin interface will be unavailable.
[W 2016-05-31 17:30:48.587 JupyterHub app:758] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2016-05-31 17:30:48.587 JupyterHub app:785] Not using whitelist. Any authenticated user will be allowed.
[I 2016-05-31 17:30:48.598 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
[W 2016-05-31 17:30:48.602 JupyterHub app:959] Running JupyterHub without SSL. There better be SSL termination happening somewhere else...
[I 2016-05-31 17:30:48.602 JupyterHub app:968] Starting proxy @ http://*:8000/
17:30:48.698 - info: [ConfigProxy] Proxying http://*:8000 to http://127.0.0.1:8081
17:30:48.700 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[I 2016-05-31 17:30:48.706 JupyterHub app:1254] JupyterHub is now running at http://127.0.0.1:8000/
```
But when I try to go to {public address of server}:8000 in my browser I don't see anything, and nothing prints in the terminal. That server is also running Apache and a Flask app, so maybe it's related to that?

**Comment by minrk** [comment]
It could be related to that. Have you tried running on a different port? Can you connect from the machine itself (still on a public IP) in case there's something on the local network preventing inter-machine connections?

**Comment by bjlange** [comment]
Finally cracked it. I'm running the server on an Amazon EC2 instance that was configured with a security group, and needed to allow inbound connections on the port via Amazon. Thanks for your help!
