### ISSUE TITLE
[DOC] FAQ entry on configuration of JupyterHub for Theano

### ISSUE THREAD

**Issue by willingc** [jupyterhub/jupyterhub#592]
Determine if this should be added to the FAQ for JupyterHub or if a patch should be sent to Theano docs.

**Problem statement**
From Ben on [Jupyter Google Group](https://groups.google.com/forum/#!msg/jupyter/p850c_7nFMU/YH0gPZSOGAAJ) 

How is `LD_LIBRARY_PATH` properly set in Jupyter when using Theano?

**Solution**
Thanks for your replies, which led me to a solution -- I added the
following to `jupyterhub_config_global.py`:

```
import os
c = get_config()
os.environ['LD_LIBRARY_PATH'] = '/usr/local/cuda-7.5/lib64'
c.Spawner.env.update('LD_LIBRARY_PATH')
c.Spawner.env_keep.append('LD_LIBRARY_PATH')
```

**Comment by willingc** [comment]
@ellisonbg FYI

**Comment by willingc** [comment]
Link to Theano docs and settings for LD_LIBRARY_PATH: http://deeplearning.net/software/theano/install.html?highlight=ld_library_path#using-the-gpu

**Comment by willingc** [comment]
A question and answer should be added to the `troubleshooting.md` file in the `docs/source` directory.  

- Point out that when the CUDA driver is needed for using the GPU the environment variable `LD_LIBRARY_PATH` should be set to the `cuda/lib` or `cuda/lib64` path.
- Additional information is available in the Theano docs
- You can also give Ben's additions to `jupyterhub_config_global.py` as an example of how to configure.

**Comment by willingc** [comment]
Closing without adding to docs since this is not getting user support questions. Marking as reference.

**Comment by stevendbrown** [comment]
I found this helpful.

**Comment by matthieuheitz** [comment]
Can someone explain what is the role of these two lines?
```
c.Spawner.env.update('LD_LIBRARY_PATH')
c.Spawner.env_keep.append('LD_LIBRARY_PATH')
``` 
I find that if I comment them but keep the line `os.environ['LD_LIBRARY_PATH'] = '/usr/local/cuda-7.5/lib64'`, then it still works, the variable appears in `os.environ` in the notebook.

Thanks!
