### ISSUE TITLE
cannot run on network

### ISSUE THREAD

**Issue by ObadaM** [jupyterhub/jupyterhub#594]
I have several questions regarding the installation, 

1-  I have Anoconda3, so should it be at root level or it is ok to stay under my default user folder ?

I am following this link: 
https://github.com/jupyterhub/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges
2- This command is not working even I performed the previous steps 
` sudo -u rhea sudo -n -u $USER sudospawner --help` 

3- I do not have this folder in my machine, should I create it ? or it should be generated by sudospawner 

`Cmnd_Alias JUPYTER_CMD = /usr/local/bin/sudospawner`

Thanks in advance,

**Comment by minrk** [comment]
> 1- I have Anaconda3, so should it be at root level or it is ok to stay under my default user folder ?

It should be a system-wide install that all users can run code with. They do not need write permissions, but they do need read/execute permissions.

For the others, make sure that JUPYTER_CMD corresponds to the actual `sudospawner` executable. See `which -a sudospawner` for where it is.

**Comment by ObadaM** [comment]
1-  that is why we give the new user the sudo privilege, right ?
2- I found it in my anaconda/bin folder 
I change the /etc/sudoers but I got the same error 

```
sudo -u rhea sudo -n -u $USER sudospawner --help
sudo: a password is required
```

**Comment by ObadaM** [comment]
it works now, I just added to sudoers

> rhea    ALL=(ALL:ALL) ALL 

I can run apply the following command now from rhea 
`sudo -u rhea jupyterhub --JupyterHub.spawner_class=sudospawner.SudoSpawner`
But I get an error 

> Refusing to run JuptyterHub without SSL. If you are terminating SSL in another layer, pass --no-ssl to tell JupyterHub to allow the proxy to listen on HTTP.

so I added --no-ssl but I do not know what is the sequences for this. 
it run after this but when I try to log in to the server I got this error

```
sudo: a password is required
[E 2016-05-31 11:14:21.074 JupyterHub user:237] Unhandled error starting l-01-314's server: substring not found
[E 2016-05-31 11:14:21.173 JupyterHub web:1524] Uncaught exception POST /hub/login?next= (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Content-Type': 'application/x-www-form-urlencoded', 'Accept-Language': 'en-US,en;q=0.8,ar;q=0.6', 'X-Forwarded-Port': '8000', 'Referer': 'http://127.0.0.1:8000/hub/login', 'Connection': 'close', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36', 'X-Forwarded-For': '127.0.0.1', 'Origin': 'http://127.0.0.1:8000', 'Content-Length': '30', 'Host': '127.0.0.1:8000', 'X-Forwarded-Proto': 'http'})
    Traceback (most recent call last):
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 79, in post
        yield self.spawn_single_user(user)
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 312, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/jupyterhub/user.py", line 247, in spawn
        raise e
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/jupyterhub/user.py", line 228, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/sudospawner/spawner.py", line 80, in start
        reply = yield self.do(action='spawn', args=self.get_args(), env=self.get_env())
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/sudospawner/spawner.py", line 69, in do
        data_str = data_str[data_str.index('{'):data_str.rindex('}')+1]
    ValueError: substring not found
    
[E 2016-05-31 11:14:21.214 JupyterHub log:99] {
      "Content-Type": "application/x-www-form-urlencoded",
      "Accept-Language": "en-US,en;q=0.8,ar;q=0.6",
      "X-Forwarded-Port": "8000",
      "Referer": "http://127.0.0.1:8000/hub/login",
      "Connection": "close",
      "Accept-Encoding": "gzip, deflate",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Cache-Control": "max-age=0",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36",
      "X-Forwarded-For": "127.0.0.1",
      "Origin": "http://127.0.0.1:8000",
      "Content-Length": "30",
      "Host": "127.0.0.1:8000",
      "X-Forwarded-Proto": "http"
    }
[E 2016-05-31 11:14:21.214 JupyterHub log:100] 500 POST /hub/login?next= (@127.0.0.1) 754.51ms
```
Is their any idea why ?

**Comment by minrk** [comment]
This is probably the key, from your logs:

> sudo: a password is required

indicating that the sudo permissions are not set correctly. Make sure that you can run the

    sudo -u rhea sudo -n -u $USER sudospawner --help

command for every user who might login to the Hub.

**Comment by ObadaM** [comment]
I should run this command from rhea terminal, right ?

**Comment by ObadaM** [comment]
it is working,

```
Usage: /home/l-01-314/anaconda3/bin/sudospawner [OPTIONS]

Options:

  --help                           show this help information

/home/l-01-314/anaconda3/lib/python3.5/site-packages/tornado/log.py options:

  --log-file-max-size              max size of log files before rollover
                                   (default 100000000)
  --log-file-num-backups           number of log files to keep (default 10)
  --log-file-prefix=PATH           Path prefix for log files. Note that if you
                                   are running multiple tornado processes,
                                   log_file_prefix must be different for each
                                   of them (e.g. include the port number)
  --log-rotate-interval            The interval value of timed rotating
                                   (default 1)
  --log-rotate-mode                The mode of rotating files(time or size)
                                   (default size)
  --log-rotate-when                specify the type of TimedRotatingFileHandler
                                   interval other options:('S', 'M', 'H', 'D',
                                   'W0'-'W6') (default midnight)
  --log-to-stderr                  Send log output to stderr (colorized if
                                   possible). By default use stderr if
                                   --log_file_prefix is not set and no other
                                   logging is configured.
  --logging=debug|info|warning|error|none 
                                   Set the Python log level. If 'none', tornado
                                   won't touch the logging configuration.
                                   (default info)

```

**Comment by minrk** [comment]
Can you post the complete log of `sudo -u rhea jupyterhub --debug` when this fails?

**Comment by ObadaM** [comment]
Here it is, 

```
rhea@l01314-Precision-Tower-3620:/etc/jupyterhub$ sudo -u rhea jupyterhub --no-ssl --debug
[D 2016-05-31 11:51:50.073 JupyterHub application:529] Looking for jupyterhub_config in None
[I 2016-05-31 11:51:50.073 JupyterHub app:622] Loading cookie_secret from /etc/jupyterhub/jupyterhub_cookie_secret
[D 2016-05-31 11:51:50.074 JupyterHub app:694] Connecting to db: sqlite:///jupyterhub.sqlite
[W 2016-05-31 11:51:50.093 JupyterHub app:304] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[W 2016-05-31 11:51:50.095 JupyterHub app:757] No admin users, admin interface will be unavailable.
[W 2016-05-31 11:51:50.095 JupyterHub app:758] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2016-05-31 11:51:50.095 JupyterHub app:785] Not using whitelist. Any authenticated user will be allowed.
[D 2016-05-31 11:51:50.101 JupyterHub app:888] Loaded users: 
    l-01-314
[I 2016-05-31 11:51:50.107 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
[W 2016-05-31 11:51:50.110 JupyterHub app:959] Running JupyterHub without SSL. There better be SSL termination happening somewhere else...
[I 2016-05-31 11:51:50.110 JupyterHub app:968] Starting proxy @ http://*:8000/
[D 2016-05-31 11:51:50.110 JupyterHub app:969] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--default-target', 'http://127.0.0.1:8081', '--error-target', 'http://127.0.0.1:8081/hub/error']
11:51:50.169 - info: [ConfigProxy] Proxying http://*:8000 to http://127.0.0.1:8081
11:51:50.171 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[D 2016-05-31 11:51:50.213 JupyterHub app:997] Proxy started and appears to be up
[I 2016-05-31 11:51:50.213 JupyterHub app:1254] JupyterHub is now running at http://127.0.0.1:8000/
[I 2016-05-31 11:52:03.661 JupyterHub log:100] 302 GET / (@127.0.0.1) 1.06ms
[I 2016-05-31 11:52:03.668 JupyterHub log:100] 302 GET /hub (@127.0.0.1) 0.32ms
[I 2016-05-31 11:52:03.674 JupyterHub log:100] 302 GET /hub/ (@127.0.0.1) 0.55ms
[I 2016-05-31 11:52:03.699 JupyterHub log:100] 200 GET /hub/login (@127.0.0.1) 18.08ms
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 4.2.0-36-generic x86_64)

 * Documentation:  https://help.ubuntu.com/


The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

sh: 1: cannot create /run/motd.dynamic.new: Permission denied

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

[I 2016-05-31 11:52:16.142 JupyterHub spawner:467] Spawning jupyterhub-singleuser --user=l-01-314 --port=44921 --cookie-name=jupyter-hub-token-l-01-314 --base-url=/user/l-01-314 --hub-host= --hub-prefix=/hub/ --hub-api-url=http://127.0.0.1:8081/hub/api --ip=127.0.0.1
[E 2016-05-31 11:52:16.214 JupyterHub user:237] Unhandled error starting l-01-314's server: Exception occurred in preexec_fn.
[E 2016-05-31 11:52:16.272 JupyterHub web:1524] Uncaught exception POST /hub/login?next= (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'en-US,en;q=0.8,ar;q=0.6', 'X-Forwarded-Port': '8000', 'X-Forwarded-For': '127.0.0.1', 'Origin': 'http://127.0.0.1:8000', 'X-Forwarded-Proto': 'http', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '30', 'Accept-Encoding': 'gzip, deflate', 'Referer': 'http://127.0.0.1:8000/hub/login', 'Cache-Control': 'max-age=0', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36', 'Connection': 'close', 'Upgrade-Insecure-Requests': '1', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Host': '127.0.0.1:8000'})
    Traceback (most recent call last):
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 79, in post
        yield self.spawn_single_user(user)
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 312, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/jupyterhub/user.py", line 247, in spawn
        raise e
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/jupyterhub/user.py", line 228, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/home/l-01-314/anaconda3/lib/python3.5/types.py", line 243, in wrapped
        coro = func(*args, **kwargs)
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/jupyterhub/spawner.py", line 470, in start
        start_new_session=True, # don't forward signals
      File "/home/l-01-314/anaconda3/lib/python3.5/subprocess.py", line 950, in __init__
        restore_signals, start_new_session)
      File "/home/l-01-314/anaconda3/lib/python3.5/subprocess.py", line 1545, in _execute_child
        raise child_exception_type(err_msg)
    subprocess.SubprocessError: Exception occurred in preexec_fn.
    
[D 2016-05-31 11:52:16.286 JupyterHub base:441] No template for 500
[E 2016-05-31 11:52:16.293 JupyterHub log:99] {
      "Accept-Language": "en-US,en;q=0.8,ar;q=0.6",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "127.0.0.1",
      "Origin": "http://127.0.0.1:8000",
      "X-Forwarded-Proto": "http",
      "Content-Type": "application/x-www-form-urlencoded",
      "Content-Length": "30",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://127.0.0.1:8000/hub/login",
      "Cache-Control": "max-age=0",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36",
      "Connection": "close",
      "Upgrade-Insecure-Requests": "1",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Host": "127.0.0.1:8000"
    }
[E 2016-05-31 11:52:16.293 JupyterHub log:100] 500 POST /hub/login?next= (@127.0.0.1) 446.76ms
```

**Comment by minrk** [comment]
@ObadaM sorry, can you run it again with the sudospawner enabled?

**Comment by ObadaM** [comment]
No problem, Here it is: 

`rhea@l01314-Precision-Tower-3620:/etc/jupyterhub$ sudo -u rhea jupyterhub --no-ssl --JupyterHub.spawner_class=sudospawner.SudoSpawner
[I 2016-05-31 13:51:16.489 JupyterHub app:622] Loading cookie_secret from /etc/jupyterhub/jupyterhub_cookie_secret
[W 2016-05-31 13:51:16.508 JupyterHub app:304] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[W 2016-05-31 13:51:16.511 JupyterHub app:757] No admin users, admin interface will be unavailable.
[W 2016-05-31 13:51:16.511 JupyterHub app:758] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2016-05-31 13:51:16.511 JupyterHub app:785] Not using whitelist. Any authenticated user will be allowed.
[I 2016-05-31 13:51:16.522 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
[W 2016-05-31 13:51:16.525 JupyterHub app:959] Running JupyterHub without SSL. There better be SSL termination happening somewhere else...
[I 2016-05-31 13:51:16.525 JupyterHub app:968] Starting proxy @ http://*:8000/
13:51:17.016 - info: [ConfigProxy] Proxying http://*:8000 to http://127.0.0.1:8081
13:51:17.018 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[I 2016-05-31 13:51:17.106 JupyterHub app:1254] JupyterHub is now running at http://127.0.0.1:8000/
[I 2016-05-31 13:51:27.304 JupyterHub log:100] 302 GET / (@127.0.0.1) 0.97ms
[I 2016-05-31 13:51:27.352 JupyterHub log:100] 302 GET /hub (@127.0.0.1) 0.31ms
[W 2016-05-31 13:51:27.411 JupyterHub base:161] Invalid or expired cookie token
[W 2016-05-31 13:51:27.413 JupyterHub base:161] Invalid or expired cookie token
[I 2016-05-31 13:51:27.414 JupyterHub log:100] 302 GET /hub/ (@127.0.0.1) 1.03ms
[I 2016-05-31 13:51:27.747 JupyterHub log:100] 200 GET /hub/login (@127.0.0.1) 300.39ms
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 4.2.0-36-generic x86_64)

 * Documentation:  https://help.ubuntu.com/


The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

sh: 1: cannot create /run/motd.dynamic.new: Permission denied

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

sudo: a password is required
[E 2016-05-31 13:51:30.333 JupyterHub user:237] Unhandled error starting l-01-314's server: substring not found
[E 2016-05-31 13:51:30.416 JupyterHub web:1524] Uncaught exception POST /hub/login?next= (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Cache-Control': 'max-age=0', 'X-Forwarded-Proto': 'http', 'X-Forwarded-Port': '8000', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36', 'Accept-Language': 'en-US,en;q=0.8,ar;q=0.6', 'X-Forwarded-For': '127.0.0.1', 'Accept-Encoding': 'gzip, deflate', 'Host': '127.0.0.1:8000', 'Connection': 'close', 'Content-Type': 'application/x-www-form-urlencoded', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Origin': 'http://127.0.0.1:8000', 'Referer': 'http://127.0.0.1:8000/hub/login', 'Content-Length': '30'})
    Traceback (most recent call last):
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 79, in post
        yield self.spawn_single_user(user)
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 312, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/jupyterhub/user.py", line 247, in spawn
        raise e
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/jupyterhub/user.py", line 228, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/sudospawner/spawner.py", line 80, in start
        reply = yield self.do(action='spawn', args=self.get_args(), env=self.get_env())
      File "/home/l-01-314/anaconda3/lib/python3.5/site-packages/sudospawner/spawner.py", line 69, in do
        data_str = data_str[data_str.index('{'):data_str.rindex('}')+1]
    ValueError: substring not found
    
[E 2016-05-31 13:51:30.456 JupyterHub log:99] {
      "Cache-Control": "max-age=0",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "8000",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36",
      "Accept-Language": "en-US,en;q=0.8,ar;q=0.6",
      "X-Forwarded-For": "127.0.0.1",
      "Accept-Encoding": "gzip, deflate",
      "Host": "127.0.0.1:8000",
      "Connection": "close",
      "Content-Type": "application/x-www-form-urlencoded",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Upgrade-Insecure-Requests": "1",
      "Origin": "http://127.0.0.1:8000",
      "Referer": "http://127.0.0.1:8000/hub/login",
      "Content-Length": "30"
    }
[E 2016-05-31 13:51:30.456 JupyterHub log:100] 500 POST /hub/login?next= (@127.0.0.1) 627.52ms
`

**Comment by minrk** [comment]
I'm not sure why it is causing the `sudo: a password is required` if the permissions are correct. Perhaps there is more than one `sudospawner`? It is also a bit strange that it is seeing the `motd` messages. That may be related, but I am not sure how or why those are being displayed.

**Comment by ObadaM** [comment]
I will go back and check everything, maybe I am missing something. 
Thanks for your try anyway!!

**Comment by willingc** [comment]
@ObadaM I hope that you were able to get this up and running with Min's feedback. Do you have additional questions or should this issue be closed?

**Comment by ObadaM** [comment]
@willingc Please close the issue, Thanks!

**Comment by mconigliaro** [comment]
I had the same error. The key was that I could only run the sudospawner command with the full path:

    sudo -u rhea sudo -n -u $USER /opt/anaconda3/bin/sudospawner --help

The problem was that `/opt/anaconda3/bin` was not in `/etc/sudoers`'s `safe_path`, so I just made a symlink:

    ln -s /opt/anaconda3/bin/sudospawner /usr/local/bin

Then the command worked as expected:

    sudo -u rhea sudo -n -u $USER sudospawner --help

**Comment by willingc** [comment]
@mconigliaro thanks for the info on how you solved the issue. 👍 

Going to relabel this as a documentation issue to add @mconigliaro's solution into the FAQ section of the JupyterHub docs. Thanks @ObadaM for the update too.

**Comment by martinclaus** [comment]
@willingc @mconigliaro I think a better solution to the problem if the `sudospawner` script is not in the path is to specify its absolute path in the jupyter config, i.e. start the jupyterhub with
```shell
jupyterhub --SudoSpawner.sudospawner_path='/absolute/path/to/sudospawner'
```
or add
```python
c.SudoSpawner.sudospawner_path = '/absolute/path/to/sudospawner'
```
to your `jupyterhub_config.py`.

**Comment by willingc** [comment]
Thanks @martinclaus. Great suggestion. 

Note to contributor or myself to add @martinclaus' suggested approach to the docs.

**Comment by myidealab** [comment]
> I had the same error. The key was that I could only run the `sudospawner` command with the full path:
> 
> ```
> sudo -u rhea sudo -n -u $USER /opt/anaconda3/bin/sudospawner --help
> ```
> 
> The problem was that `/opt/anaconda3/bin` was not in `/etc/sudoers`'s `safe_path`, so I just made a symlink:
> 
> ```
> ln -s /opt/anaconda3/bin/sudospawner /usr/local/bin
> ```
> 
> Then the command worked as expected:
> 
> ```
> sudo -u rhea sudo -n -u $USER sudospawner --help
> ```

Do you have to be logged in as rhea to get the --help output?
