### ISSUE TITLE
`hub_prefix` option does not work

### ISSUE THREAD

**Issue by Milly** [jupyterhub/jupyterhub#595]
Set `JupyterHub.hub_prefix` option, and error occurred.

    TypeError: _hub_prefix_changed() missing 2 required positional arguments: 'old' and 'new'

Update `_hub_prefix_changed()`.

```diff
--- old/jupyterhub/app.py▸     2016-05-31 18:01:49.633124540 +0900
+++ new/jupyterhub/app.py▸     2016-05-31 18:01:49.661125012 +0900
@@ -332,7 +332,8 @@
         return url_path_join(self.base_url, '/hub/')
 
     @observe('hub_prefix')
-    def _hub_prefix_changed(self, name, old, new):
+    def _hub_prefix_changed(self, change):
+        new = change['new']
         if new == '/':
             raise TraitError("'/' is not a valid hub prefix")
         if not new.startswith(self.base_url):
```

**Comment by minrk** [comment]
Thanks, fixed by #596. Are you sure you want to set `hub_prefix` and not `base_url`? Setting hub_prefix only changes the `/hub/` part, and probably shouldn't even be configurable.
