### ISSUE TITLE
Issues with jupyterhub : can not launch : no such file or directory 'jupyterhub-singleuser'

### ISSUE THREAD

**Issue by YannBrrd** [jupyterhub/jupyterhub#598]
Hi,

I'm reinstalling jupyterhub on VMs, and I can not launch users notebooks. I have this error. Following the same steps 

```python
[E 2016-05-31 15:28:04.746 JupyterHub user:237] Unhandled error starting yann's server: [Errno 2] No such file or directory: 'jupyterhub-singleuser'
```

What did I do wrong ? 

Thanks.

Yann

**Comment by minrk** [comment]
How are you starting JupyterHub? What is PATH when you launch it? Where is jupyterhub-singleuser?

**Comment by YannBrrd** [comment]
sudo /anaconda3/bin/jupyterhub -f /etc/jupyterhub/jupyterhub_config.py

Which user has to have jupyter_singleuser in path ?

How do I specify absolute path ? All setup in /anaconda3

Le mar. 31 mai 2016 18:23, Min RK <notifications@github.com> a écrit :

> How are you starting JupyterHub? What is PATH when you launch it? Where is
> jupyterhub-singleuser?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyterhub/jupyterhub/issues/598#issuecomment-222742075>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACsHwsw8Whe5WTgd2lSvR2OyYyv2lsbeks5qHGCNgaJpZM4IqqVM>
> .
>
-- 
Cordialement,
Yann Barraud

**Comment by minrk** [comment]
Try doing it in two steps with `sudo -s`:

```
> sudo -s
> env
PATH=....
> which jupyterhub
/anaconda3/bin/jupyterhub
> which jupyterhub-singleuser
/anaconda3/bin/jupyterhub-singleuser
> jupyterhub -f /etc/jupyterhub/jupyterhub_config.py
```

If that still doesn't work for some reason, you can tell it to use the absolute-path for jupyterhub-singleuser in your config, rather than relying on PATH:

```python
c.Spawner.cmd = '/anaconda3/bin/jupyterhub-singleuser'
```

**Comment by YannBrrd** [comment]
👍 Will test and let you know

Le mar. 31 mai 2016 20:13, Min RK <notifications@github.com> a écrit :

> Try doing it in two steps with sudo -s:
>
> > sudo -s
> > env
> PATH=....
> > which jupyterhub
> /anaconda3/bin/jupyterhub
> > which jupyterhub-singleuser
> /anaconda3/bin/jupyterhub-singleuser
> > jupyterhub -f /etc/jupyterhub/jupyterhub_config.py
>
> If that still doesn't work for some reason, you can tell it to use the
> absolute-path for jupyterhub-singleuser in your config, rather than relying
> on PATH:
>
> c.Spawner.cmd = '/anaconda3/bin/jupyterhub-singleuser'
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyterhub/jupyterhub/issues/598#issuecomment-222773068>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACsHwvZEzCBrX1pWVY0qug8R2pyXSFqtks5qHHo-gaJpZM4IqqVM>
> .
>
-- 
Cordialement,
Yann Barraud

**Comment by YannBrrd** [comment]
Fixed by setting absolute path thanks a lot !!

**Comment by ssackett** [comment]
In version 0.8 I found it necessary to add brackets to the command, see below.  I am running JupyterHub as a service by using systemd and in the subdomain configuration.  OS is RHEL 7.

c.Spawner.cmd = ['/anaconda3/bin/jupyterhub-singleuser']
