### ISSUE TITLE
jupyter-sing segfault

### ISSUE THREAD

**Issue by alexanderhaensch** [jupyterhub/jupyterhub#600]
If i try to open a terminal, a new tab opens and closes immediately.

In the logfile i see:

> Jun 02 10:52:00 io jupyterhub[6652]: 10:52:00.950 - debug: [ConfigProxy] PROXY WEB /user/username/api/terminals to http://127.0.0.1:35937
> Jun 02 10:52:00 io kernel: jupyterhub-sing[32535]: segfault at 0 ip           (null) sp 00007ffdfb8f5858 error 14 in python3.4[55c831822000+2000]
> Jun 02 10:52:00 io jupyterhub[6652]: 10:52:00.959 - error: [ConfigProxy] Proxy error:  code=ECONNRESET
> Jun 02 10:52:00 io jupyterhub[6652]: 10:52:00.959 - error: [ConfigProxy] 503 POST /user/username/api/terminals

How can i debug the problem?

**Comment by minrk** [comment]
How did you install Python and/or JupyterHub? What spawner are you using? That seems like a low-level error in the Python interpreter itself.

Can you run a regular `jupyter notebook` server as the same user on the same system with the same Python (env if applicable)?

**Comment by alexanderhaensch** [comment]
Thanks for the quick info.
I use the packaged install from gentoo. Jupyterhub is installed with pip. I am not quite sure about the spawner. I am not using a docker env or something. 
The user can start jupyter and gets the segfault too. So its clearly in jupyter not in jupyterhub.
The segfault is happening as root too.

**Comment by minrk** [comment]
It's likely in Python itself, and not Jupyter because Jupyter contains no compiled code. My guess is that perhaps some DLL has been updated and Python (or possibly an extension) may need to be recompiled.

**Comment by alexanderhaensch** [comment]
I was trying to rebuild python but its still happens, with py2.7 and py3.4.
I think it happens while opening the /dev/pts file

**Comment by alexanderhaensch** [comment]
strace gives me:

ioctl(16, TIOCSPTLCK, [0])              = 0
ioctl(16, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(16, TIOCGPTN, [10])               = 0
stat("/dev/pts/10", {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 10), ...}) = 0
open("/dev/pts/10", O_RDWR|O_NOCTTY)    = 17
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
+++ killed by SIGSEGV +++
Segmentation fault

**Comment by minrk** [comment]
I'm not sure what library is initiating the calls, but the root of the problem is likely in how Python itself or one of its C dependencies is built.
