### ISSUE TITLE
add auth-by-group to HubAuth

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#603]
we have groups now, we should add config for HubAuth to allow access to members of a group

**Comment by gliptak** [comment]
https://github.com/jupyterhub/jupyterhub/pull/2117

**Comment by consideRatio** [comment]
I'm closing this as it is an issue that I think is a bit too vaguely documented, which cause it to become stale.

I don't understand us to have groups in JupyterHub other than the concept of users with admin rights and normal users.
