### ISSUE TITLE
julia with jupyterhub

### ISSUE THREAD

**Issue by davidp123** [jupyterhub/jupyterhub#61]
Hi all, 

I am interested in using jupyterhub principally as a Julia environment for a small group. I have installed on our machine IJulia and jupyterhub successfully just by following the instructions, but I can't seem to figure out how to set jupyterhub to work in Julia.

I have installed Python 2.7.6, Ipython 2.3.0, Julia 0.3.1.

I also have python3, ipython3 installed but the normal python/ipython commands are for python 2.

If anybody can offer some instruction it would be most appreciated.

Thanks
David

**Comment by yhtang** [comment]
Hi all,
I was trying to add the IJulia kernel to my jupyterhub docker image but was unsuccessful. What I did was:
```
julia> Pkg.add("IJulia")
INFO: Installing BinDeps v0.4.7
INFO: Installing Compat v0.24.0
INFO: Installing Conda v0.5.3
INFO: Installing IJulia v1.5.0
INFO: Installing JSON v0.9.1
INFO: Installing MbedTLS v0.4.5
INFO: Installing SHA v0.3.2
INFO: Installing URIParser v0.1.8
INFO: Installing ZMQ v0.4.2
INFO: Building Conda
INFO: Building MbedTLS
Using system libraries...
INFO: Building ZMQ
INFO: Building IJulia
INFO: Found Jupyter version 4.3.0: /usr/bin/jupyter
Writing IJulia kernelspec to /root/.julia/v0.5/IJulia/deps/julia-0.5/kernel.json ...
Installing julia kernelspec julia-0.5
[InstallKernelSpec] Removing existing kernelspec in /root/.local/share/jupyter/kernels/julia-0.5
[InstallKernelSpec] Installed kernelspec julia-0.5 in /root/.local/share/jupyter/kernels/julia-0.5
INFO: Package database updated
```
and then restart the jupyterhub application. However I can still only see the Python 3 option once logged in. The same procedure could give me the Julia option when combined with `jupyter notebook` on my laptop.

**Comment by minrk** [comment]
IJulia installs to a user-specific location by default, not system-wide (`/root/.local/share/jupyter/kernels/julia-0.5` above). You will need to make sure that you have a system-wide install of Julia packages, which don't quite recall how to do (maybe JULIA_PKGDIR env?). You will also have to move the kernelspec from `/root/.local/share/jupyter/kernels/` to `/usr/local/share/jupyter/kernels/` after it's created.
