### ISSUE TITLE
PySpark kernel for Jupyterhub creates file “???????e?” in working directory

### ISSUE THREAD

**Issue by LMtx** [jupyterhub/jupyterhub#610]
On CentOS 6 I use JupyterHUB 0.6.1 with PySpark kernel (Spark 1.5.0 + Python 2.7).

When I start PySpark kernel JupyterHUB creates file named "????????????????????????????????????????????????????????????????????????????????????????????????????????????????????e?" in my working directory.

Mirror server with JupyterHUB 0.5.0 does not have this issue.

Please see details on http://stackoverflow.com/questions/37808659/pyspark-kernel-for-jupyterhub-creates-file-e-in-working-directory

**Comment by minrk** [comment]
Duplicate issue opened at ipython/ipython/issues/9613
