### ISSUE TITLE
Is there any way to share my notebook interactively with someone? And add someone's notebook to mine?

### ISSUE THREAD

**Issue by Arya766** [jupyterhub/jupyterhub#614]
Is there any way to share my notebook interactively with someone?

And add someone's notebook to mine?

(I doubt should I have opened two issues.)

**Comment by willingc** [comment]
Hi @Arya766, 

Currently, you may share a copy of notebook (`.ipynb`) file with other individuals. Two individuals can not currently interactively edit a notebook at the same time. It is possible to collaborate on a notebook file asynchronously by placing the notebook under version control in GitHub.

If you would like to add someone's notebook to your notebook, you would have to copy the cell contents from the source notebook to the destination notebook and taking care to make sure the destination notebook has the necessary dependencies and data sources.
