### ISSUE TITLE
Best method to store associated session data

### ISSUE THREAD

**Issue by scanon** [jupyterhub/jupyterhub#624]
Greetings,

We are trying out some alternate auth methods.  We would like to be able to store some associated data with a session.  Is there a clean, extensible way to do this?

**Comment by minrk** [comment]
The Authenticator can pass information to the user's context via [Authenticator.pre_spawn_start](http://jupyterhub.readthedocs.io/en/latest/api/auth.html#jupyterhub.auth.Authenticator.pre_spawn_start) and [Authenticator.post_spawn_stop](http://jupyterhub.readthedocs.io/en/latest/api/auth.html#jupyterhub.auth.Authenticator.post_spawn_stop).

**Comment by mbmilligan** [comment]
@scanon I'm looking into this too right now. Talking with @minrk the other day he says the `auth_state` field in the `User` object is also a good place to do this. It has an associated column in the ORM so it can be persisted across sessions, but that doesn't happen automatically right now; your authenticator will have to do that itself.

**Comment by manics** [comment]
`auth_state` is documented here: https://jupyterhub.readthedocs.io/en/1.1.0/reference/authenticators.html#authentication-state
