### ISSUE TITLE
Custom Authenticator, Docker and Env variables

### ISSUE THREAD

**Issue by gwincr11** [jupyterhub/jupyterhub#629]
Hello,

I am building a custom authenticator that will use python environment variables in side the docker environment.

I have built my authenticator and tested it against a local version of Jupyterhub, everything works as expected. I am able to get my env variable in the script. However when I use it inside the docker container it does not work, the env variables come back as empty.

Heres is part of the script:
```python
import json
import os
import urllib
import urllib.parse

from tornado.auth import OAuth2Mixin
from tornado import gen, web

from tornado.httputil import url_concat
from tornado.httpclient import HTTPRequest, AsyncHTTPClient

from jupyterhub.auth import LocalAuthenticator
from jupyterhub import orm
from jupyterhub.handlers import BaseHandler
from jupyterhub.user import User

from traitlets import Unicode, Dict

from oauthenticator import OAuthLoginHandler, OAuthenticator
import logging
logging.basicConfig()
from tornado.log import enable_pretty_logging
enable_pretty_logging()
#logging.getLogger('sqlalchemy.engine').setLevel(logging.INFO)

# Support github.com and github enterprise installations
HOST = os.environ.get('HOST', 'localhost:3000')
API = HOST + '/api/v1/'
HUB_URL = os.environ.get('HUB_URL', 'http://127.0.0.1:8000')

print(HOST)

class AuthMixin(OAuth2Mixin):
    _OAUTH_AUTHORIZE_URL = "https://%s/oauth/authorize" % HOST
    _OAUTH_ACCESS_TOKEN_URL = "https://%s/oauth/token" % HOST

class AuthLoginHandler(OAuthLoginHandler, AuthMixin):
    pass

class AuthOAuthenticator(OAuthenticator, BaseHandler):
    login_service = "Test"

    client_id = os.environ.get('CLIENT_ID')  
    client_secret =  os.environ.get('CLIENT_SECRET') 
```

Here is the relevant parts of the Docker file:
```python
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM jupyterhub/jupyterhub-onbuild:0.6.1

# Install dockerspawner and its dependencies
RUN /opt/conda/bin/pip install \
    jupyterhub==0.6.* \
    oauthenticator==0.4.* \
    dockerspawner==0.3.*

# Postgres connection dependencies
    RUN apt-get update \
        && apt-get install -y libpq-dev \
        && apt-get autoremove -y \
        && apt-get clean -y \
        && pip install psycopg2

# Docker environment
ENV DOCKER_MACHINE_NAME=jupyterhub
ENV DOCKER_NETWORK_NAME=jupyterhub-network
ENV DOCKER_NOTEBOOK_DIR=/home/jovyan/work
ENV DOCKER_SPAWN_CMD=start-singleuser.sh
ENV DATA_VOLUME_HOST=jupyterhub-data
ENV DATA_VOLUME_CONTAINER=/data

# OAuth Cred
ENV CLIENT_ID=blah
ENV CLIENT_SECRET=bleh
ENV HOST=0.0.0.0:3000
ENV HUB_URL=192.168.99.100

COPY ./auth.py /srv/jupyterhub/auth.py

CMD ["jupyterhub", "-f", "/srv/jupyterhub/jupyterhub_config.py"]
```

When I open the Python environment inside the docker container all the env variables are present. But the script shows them all as empty. What am I missing?

Thanks,
Cory

**Comment by minrk** [comment]
I'm not sure what could be wrong. I built your Dockerfile, and I do see all of the environment variables defined in the JupyterHub process. How are you checking them?

**Comment by gwincr11** [comment]
The link that is provided as the login is blank.

**Comment by willingc** [comment]
@minrk I wonder if localhost is causing an issue between these two statements (I seem to recall on some OS localhost, 127.0.0.1 and 0.0.0.0 did not play nicely together):

``HOST = os.environ.get('HOST', 'localhost:3000')`` in custom authenticator script

``ENV HOST=0.0.0.0:3000`` in the Dockerfile

**Comment by gwincr11** [comment]
Thanks for taking a look. I got the link to work, Woot, I had to rebuild without cache for some reason. However the callback url is always just https:///hub/oauth_callback

My auth code looks like this:

```python
  @gen.coroutine
    def authenticate(self, handler, data=None):
        code = handler.get_argument("code", False)
        self.log.debug('code: %s', str(code))
        if not code:
            raise web.HTTPError(400, "oauth callback made without a token")
        # TODO: Configure the curl_httpclient for tornado
        http_client = AsyncHTTPClient()

        # Exchange the OAuth code for a Access Token
        #
        callback_url = ("%s/hub/oauth_callback" % HUB_URL)
        self.log.debug(callback_url)
        params = dict(
            client_id=self.client_id,
            client_secret=self.client_secret,
            code=code,
            grant_type="authorization_code",
            redirect_uri=callback_url
        )
        url = url_concat("https://%s/oauth/token" % MURS_HOST, '')

        body = urllib.parse.urlencode(params)
        req = HTTPRequest(url,
                          method="POST",
                          headers={"Accept": "application/json"},
                          validate_cert=False,
                          body=body # Body is required for a POST...
                          )

        print('authenticate')
```

I even went as far as hardcoding the redirect_uri instead of using a variable. I also completely deleted the authenticate function and their was no difference. I know that jupyter hub is using part of my class because the button name is correct and it goes to the right site to start the authentication process.

Any thoughts?

Thanks a bunch,
Cory

**Comment by gwincr11** [comment]
as an aside, how can I get logging to show up on the docker version?

**Comment by gwincr11** [comment]
So I dropped die() into my authenticate method, it never gets hit. Is there somewhere before this happens that I need to define the callback url?

**Comment by gwincr11** [comment]
Found the culprit. Thanks!

**Comment by willingc** [comment]
@gwincr11 Just out of curiousity (and possibly to help others), what was the culprit? I might be able to clarify in the docs. Thanks.

**Comment by gwincr11** [comment]
Oh it was super particular to my setup. I have a docker-compose file that was reseting the env variables in a way I was not suspecting.

**Comment by willingc** [comment]
Thanks for the info @gwincr11 and I'm glad that you worked out the issue 👍
