### ISSUE TITLE
500 : Internal Server Error

### ISSUE THREAD

**Issue by harishcj** [jupyterhub/jupyterhub#638]
one of the users when he tries to login to jupyetrhub, he gets the error message - '500 : Internal Server Error'. Other users are able to login to jupyterhub without any issues. Please help!!

**Comment by andf1** [comment]
Fellow deployment engineer here. I ran into a bunch of 500s myself deploying JupyterHub; here's what I'd recommend looking into:

- Does the user's home directory exist? I ran into a race condition where our user account + home directory creation scripts took long enough to execute that JupyterHub deemed the process to spawn the user kernel timedout. If the user 500s their first login, do they succeed on their second? Maybe try adjusting some of the timeout parameters in your jupyterhub_config.py file.
- Is the user's home directory properly permissioned? Does the user have a valid shell defined? Do they have anything crazy in their ~/.bashrc (etc) files that might be interfering?
- Can they SSH to the box itself?
- Is the user over their storage quota for ~ ?
- 500 means the user passed authentication (via LDAP, AD, /etc/passwd, etc), so you can largely disregard that.

Hope this helps!

**Comment by harishcj** [comment]
Hi andf1, thanks for the reply.

1. users home directory exists. user was able to login before. he restarted his session and ever since he is unable to login.
2. user's home directory has proper permissions. he has a valid shell defined.
3. user can ssh to the box
4. user is under the quota
5. he is using the right password and he is able to login to other applications using the same password.

**Comment by harishcj** [comment]
looks like the user has stopped his jupyter server, how can we start it ?

**Comment by matteoipri** [comment]
Which spawner are you running? I get that message sometimes using the DockerSpawner when I upgrade JuoyterHub or single user Jupyter Notebook image but don't delete the old user container.

**Comment by harishcj** [comment]
how will i check which spawner the user is using ? i am the admin and the issue is with a user. he has shutdown his jupyter/notebook server it looks like. is there a way that i can bring them up as a root user from the server?

**Comment by matteoipri** [comment]
You can check which spawner you are using looking at the `jupyterhub_config.py` and look for the strings that looks like this `c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'`.
The user can just log out and log back in to respwan its own server. The user can even restart the server without logging out and in, by going to his/her control panel with the button in the top right corner of the JupyterHub page once logged in.

**Comment by harishcj** [comment]
c.JupyterHub.spawner_class = <class 'jupyterhub.spawner.LocalProcessSpawner'>.
when the user logs in, he just gets an error message 500:internal server error. there are no other buttons on the page. please see the attachment
![jupy](https://cloud.githubusercontent.com/assets/16937146/16872760/7c6fbe58-4aac-11e6-9d64-0a1daa40b3e2.png)

**Comment by matteoipri** [comment]
I guess, but am not sure, you're using the default PAM system user spawner.
Can you show me your full url of the above screenshot?
What do you see if you go to the page `https://example.com/hub/home`?
If you log in as admin, what do you see here `https://example.com/hub/admin`?

**Comment by harishcj** [comment]
the URL that we are using is given below. it works for everyone except for the affected user
![jup login](https://cloud.githubusercontent.com/assets/16937146/16873168/164392f0-4aaf-11e6-8934-174e42b8f1c0.png)

What do you see if you go to the page https://example.com/hub/home?

![jup home](https://cloud.githubusercontent.com/assets/16937146/16873185/2b1c0568-4aaf-11e6-978b-c84578ea6d14.png)

If you log in as admin, what do you see here https://example.com/hub/admin?

![jup admin](https://cloud.githubusercontent.com/assets/16937146/16873191/3da63ce4-4aaf-11e6-8954-be98efcbbc5e.png)

**Comment by matteoipri** [comment]
You should go to `/hub/home/` after logging in as the affected user. Try again.
More over, it seems you did not log in as an admin when you went to `/hub/admin/`.

**Comment by harishcj** [comment]
when i go to /hub/home as affected user, it goes back to login page where it asks for credentials again.
i have logged in as admin when i tried /hub/admin. the user mentioned that he shutdown some server after he logged in to jupyterhub(could be jupyter/notebook server). is there any way we can bring it up. when he logs in now, he only gets an error message, there are no other buttons. i am the admin and i have the access to the server. is there some command that i can use to bring up his session again ?

**Comment by matteoipri** [comment]
I really don't know what it could be. Maybe the log can help diagnose what's happening. When I encountered things like this, I deleted the cookie secret and the user database, but maybe this is not advisable in your case.

**Comment by harishcj** [comment]
where can i find the user's cookie secret and the user's database ? there is nothing under his home directory.

**Comment by harishcj** [comment]
restarting jupyterhub service on the server using the command - sudo jupyterhub solved this issue.

**Comment by dmceballosg** [comment]
Hi, harishcj i'm having the same problem with one user, how you solve the issue because i restarted the jupyterhub service and still the problem.
