### ISSUE TITLE
Deleting a user account and then restarting hub triggers a JSON parsing error

### ISSUE THREAD

**Issue by danielballan** [jupyterhub/jupyterhub#641]
I'll report back later with a more detailed report (after scipy) but I wanted to leave this here:

With jupyterhub + sudospawner, if a user:

1. A user logs in to the hub and starts a server
2. That user deletes their account
3. The hub is later restarted

then

1. the warning "jupyter : unknown user: <username>" is logged
2. the hub startup process dies on a JSON-parsing error

**Comment by minrk** [comment]
Thanks for recording this. Sounds like PAMAuth needs to add a check if users exist that fires during startup, rather than the warning.

It's not super surprising that deleting a user on the System without telling JupyterHub leaves things a bit confused.

**Comment by danielballan** [comment]
It looks like #687 is the same problem. Closed by #689.

**Comment by willingc** [comment]
Thanks for following up @danielballan. 🏄
