### ISSUE TITLE
How can I run jupyterhub as daemon using non root user

### ISSUE THREAD

**Issue by jai11** [jupyterhub/jupyterhub#642]
Here I want to run jupyterhub as non root user without sudo spawner. Either by daemon/service or any other way without any spawner.

Please let me know if you have any way to run jupyterhub as less privileged user.

Please let me know the exact steps if you have.

**Comment by minrk** [comment]
If you want to run JupyterHub, you must use either:

1. run Hub as root
2. run sudospawner
3. use a different Spawner that doesn't need privileges to launch notebook servers

One such Spawner is DockerSpawner, if docker is configured to allow access to a less privileged user. I'm not sure what you mean by "without any spawner" since JupyterHub must always use a Spawner.

**Comment by jai11** [comment]
Thanks , sorry for late reply .. was doing some more testing. i meant that I don't want to use any public spawner over here . I have my own customized spawner. But yes I am still testing the stuff.

**Comment by minrk** [comment]
Then it's up to you to make sure your custom spawner doesn't need to run as root. There's nothing inherent in JupyterHub that requires it to be root. In the default configuration, there are two activities that JupyterHub has that may require root permissions:

1. using the PAM service for the default Authenticator. This doesn't require root, but it does require permission to access the PAM service. On most standard linux systems, adding the Hub user to the `shadow` group is enough permissions for the PAM service. Most (all?) other Authenticators do not need any extra permissions.
2. The default spawner uses `setuid` to switch users when spawning single-user servers. If your custom Spawner does not need root permissions, then the Hub doesn't need root permissions.

**Comment by GISDev01** [comment]
@jai11 Which OS are you using? I actually had some trouble getting an /etc/init.d/ service up and running on Ubuntu 14.04, where it would use a service account with limited sudo rights (per the docs on how to run it as non-Sudo and using the SudoSpawner). I'd be interested in hearing if you figured this out.

**Comment by jai11** [comment]
Hi GISDev01 .. no I did not worked more on that ... as started jupyterhub as another user .. it was staright forward as per @minrk comment.

**Comment by jai11** [comment]
@minrk I need more info how I can run jupyterhub as root but simgle user server as other user.. in my case we can stick to a single user not the login users.

I can see dockerspawner do that . running single user server as cloud-user .. but I cant figure it how.. can you please help..

**Comment by minrk** [comment]
@jai11 here is a spawner that spawns local processes always as the Hub user, rather than using setuid to become the system user:

```python
from jupyterhub.spawner import LocalProcessSpawner
class SelfSpawner(LocalProcessSpawner):
    """Spawn notebook servers as subprocesses without setting the user

    avoids switching users when spawning single-user servers
    
    all users will be able to read/write/delete each others files,
    including the Hub's own configuration.
    """

    def make_preexec_fn(self, name):
        # disable setuid
        return lambda : None
    
    def user_env(self, env):
        # disable getting user env variables
        return env
```

**Comment by jai11** [comment]
@minrk 

Actually i want that JH will run as root but spawner will run as my dedicated OS user .. not the users which are logged in from JH . I want to run spawner for all logged in users as my dedicated user for running spawner only 


def set_user_setuid(username,notebookdir):
    """return a preexec_fn for setting the user (via setuid) of a spawned process"""
    user = pwd.getpwnam(username)
    uid = user.pw_uid
    gid = user.pw_gid
    home = user.pw_dir
    gids = [ g.gr_gid for g in grp.getgrall() if username in g.gr_mem ]
    def preexec():
        # set the user and group
        os.setgid(gid)
        try:
            os.setgroups(gids)
        except Exception as e:
            print('Failed to set groups %s' % e, file=sys.stderr)
        os.setuid(uid)
        # start in the user's home dir
        #_try_setcwd(notebookdir)
        
    return preexec

When I commented the line _try_setcwd(notebookdir) the spawner started as my user , but notebooks cant be loaded got 404 not found.

When I un comment  the line _try_setcwd(notebookdir) , got 505 server error on JH.

**Comment by jai11** [comment]
@minrk  say JH will run as 'root' and spawner will run as 'spawn' user irrespective of logged in users from JH.

So how I can set notebooks path to server.

**Comment by jai11** [comment]
@minrk  I am able to solve it thanks

**Comment by willingc** [comment]
Closing as resolved by @minrk's comments.
