### ISSUE TITLE
Deleting user who has a running server is creating a warning message

### ISSUE THREAD

**Issue by SruthiBhavanam** [jupyterhub/jupyterhub#647]
From the jupyterhub admin page, the delete user button is working only if the user has no server running,

If admin tries to delete the user who has a server running, It is printing the following warning message and not actually deleting the user.

Result :API request failed (400): usertest's server is in the process of stopping, please wait.

**Comment by Amerterasu** [comment]
Can you specify more about what exactly is running on that user's server? I tried replicating this myself, but did  not get any warnings and the user was successfully deleted.

**Comment by SruthiBhavanam** [comment]
Only jupyterhub-singleuser is running on the server.No jobs are launched.

Attached are the images of the error and the final state where the user is not deleted.

<img width="974" alt="screen shot 2016-07-28 at 3 14 16 pm" src="https://cloud.githubusercontent.com/assets/20524648/17231437/ba88d358-54d6-11e6-8a07-f985b172fdd4.png">
<img width="601" alt="screen shot 2016-07-28 at 3 15 01 pm" src="https://cloud.githubusercontent.com/assets/20524648/17231456/cf6bcbd6-54d6-11e6-91ae-810463042783.png">
<img width="954" alt="screen shot 2016-07-28 at 3 15 45 pm" src="https://cloud.githubusercontent.com/assets/20524648/17231464/d8b417b6-54d6-11e6-98dc-7371f1d4a662.png">

**Comment by SruthiBhavanam** [comment]
Amerterasu , Do you have any update on this?

**Comment by Amerterasu** [comment]
Sorry for the late response. I can't seem to find how this problem is caused. A core developer will probably know more about this.

**Comment by minrk** [comment]
Can you stop the server and then delete the user?

**Comment by SruthiBhavanam** [comment]
Yes, I can stop the server and delete the user with no issues.

**Comment by willingc** [comment]
Closing this issue as resolved.
