### ISSUE TITLE
Install from a source without pip and condainstall

### ISSUE THREAD

**Issue by sudipto84goswami** [jupyterhub/jupyterhub#648]
Hi Team,

My server are behind internet. Is there any way, I can download the tar ball for the Jupyterhub source and install it in my environment,

If so, can you please share the details.

**Comment by mbmilligan** [comment]
You could do that, but then you'd also need to get all the relevant dependencies onto your server too. The easiest thing to do would be to use pip on some machine that **does** have internet access to download jupyterhub and its dependencies, then move the downloaded files to your server and install them there. This is described [in the pip manual](https://pip.pypa.io/en/latest/user_guide/#installing-from-local-packages).

**Comment by willingc** [comment]
@sudipto84goswami Issue #661 also provides information, similar to the info suggested by @mbmilligan, on how to install without network access. PR #730 adds this information to the JupyterHub documentation.
