### ISSUE TITLE
Review documentation or add docs re: default_url

### ISSUE THREAD

**Issue by willingc** [jupyterhub/jupyterhub#654]
Check if ``Enable default_url to pass in to notebook server`` #457 is adequately documented.

Full filesystem navigation.

**Comment by minrk** [comment]
The answer is probably no. A FAQ entry for "I want access to the whole filesystem, but still default users to their home directory" that sets:

```python
c.Spawner.notebook_dir = '/'
c.Spawner.default_url = '/home/%U' # %U will be replaced with the username
```

is a good idea.

**Comment by willingc** [comment]
Sounds good. Thanks @minrk
