### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by mattwg** [jupyterhub/jupyterhub#66]
I am trying to install Jupyter Hub on an Ubuntu 14.04 server.  I followed exact instructions in the README.

I get this error when running "pip install ."

```
moment#2.7.0 share/jupyter/static/components/moment

running css

error: [Errno 2] No such file or directory

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-3k3Avh-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-jqPTEE-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-3k3Avh-build
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4: ordinal not in range(128)
```

My pip version is:

```
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
```

and my bower version is

```
1.3.12
```

and my python version is

```
Python 2.7.6
```

Any idea what is going on?  What should I try?  Thanks in advance!
Matt

**Comment by guotong1988** [comment]
same question , hope ` npm install -g bower` helps

**Comment by guotong1988** [comment]
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 304, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1235, in prepare_files
    req_to_install.assert_source_matches_version()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 465, in assert_source_matches_version
    % (display_path(self.source_dir), version, self))
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 71, in display_path
    if path.startswith(os.getcwd() + os.path.sep):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 9: ordinal not in range(128)

Storing debug log for failure in /home/gt/.pip/pip.log

**Comment by guotong1988** [comment]
`npm install -g bower ` doesn't work...

**Comment by minrk** [comment]
@guotong1988 this is a bug in pip, and I believe fixed in relatively recent versions. Make sure you have a reasonably current `pip` (at least 8.0):

    pip install --upgrade pip

The old comment about `npm install -g bower` is out-of-date. You no longer need to do global installs of bower or less.
