### ISSUE TITLE
Multiple Node Environment for Jupyterhub

### ISSUE THREAD

**Issue by sudipto84goswami** [jupyterhub/jupyterhub#663]
I am having two hosts over which I am planning to build up an environment with Jupyterhub running on 2 nodes. Out of this, one node will be a docker server and the other to be base jupyerhub server. The main idea behind configuring this, is to establish a load balancing mechanism as well as clustering. Based on average load on the server, the user will be routed to a dedicated host for routing.

Can you please guide me on this configuration.

Is this on one host, I shall be configuring docker spawner and on the other node normal Jupyerhub server. If so how the configuration will be define. Also do I need to define Clustering at Unix OS level also?

Please suggest on this.

Regards,
Sudipta.

**Comment by sudipto84goswami** [comment]
Can you please share your thoughts on this. We need to adopt this in our organisation as there are many users who will be using this. We need to define a multinode environment with clustering, scalability and load balancing features.

**Comment by minrk** [comment]
We don't need to have this same conversation both on GitHub and on the mailing list. I am closing this in favor of the same conversation [already ongoing on the mailing list](https://groups.google.com/d/msg/jupyter/IBjkeMVLlGE/XDxzQS5uBQAJ).
