### ISSUE TITLE
Proxy does not stay open after exiting hub

### ISSUE THREAD

**Issue by vilhelmen** [jupyterhub/jupyterhub#665]
Not sure if it's my setup (CentOS 7, JupyterHub 6.1), but when shutting down the hub (via SIGINT), the proxy is always terminated, regardless what the value of c.JupyterHub.cleanup_proxy is. However, if you shut the hub down through the web interface, the proxy will stay up if you uncheck the box for it.

I poked through the code and verified that cleanup_proxy was false in both cases, so I'm not sure what would cause the process to be killed. I did some light googling and it was suggested that the child process may be receiving the hub's SIGINT as well. Adding "preexec_fn=os.setpgrp" to the Popen call, as shown here http://stackoverflow.com/a/16928558/6521809 fixed the issue.

**Comment by minrk** [comment]
@vilhelmen adding preexec sounds like the right thing to do. Do you want to send a PR?

**Comment by vilhelmen** [comment]
Can do!

**Comment by guoxiangyang12** [comment]
when i want to re-login after logout,there will be a mistake "[PAM Error 7] Authentication failure  ",why?
