### ISSUE TITLE
Error while running cull_idle_servers.py

### ISSUE THREAD

**Issue by dvigneshwer** [jupyterhub/jupyterhub#666]
```
Traceback (most recent call last):
  File "cull_idle_servers.py", line 76, in <module>
    loop.run_sync(cull)
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 453, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "cull_idle_servers.py", line 43, in cull_idle
    resp = yield client.fetch(req)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info

```
I had created an environmental variable for ./log_activity and ran the code, got the error above.

```
export JPY_API_TOKEN=jupyterhub token [iot]
python cull_idle_servers.py [--timeout=900] [--url=http://127.0.0.1:8000/hub]
```

Also tried `export JPY_API_TOKEN=jupyterhub token` got the same error.

**Comment by minrk** [comment]
It needs to be

    export JPY_API_TOKEN=`jupyterhub token`

not 

    export JPY_API_TOKEN=jupyterhub token

That is, JPY_API_TOKEN should be the token itself, which is the *output* of the `jupyterhub token` command.

**Comment by dvigneshwer** [comment]
Above I just copy pasted the output from `printenv | grep JPY` 

While creating the environmental variable I had followed `export JPY_API_TOKEN="jupyterhub token" `

**Comment by minrk** [comment]
`"` is not the same as \`. The backtick chacter (\`) means "run this command and return its output," whereas the quotation mark means "use this string exactly."

You can achieve the same result by running the `jupyterhub token` command by hand, and then copying and pasting the result into JPY_API_TOKEN:

```
$ jupyterhub token
97c56c20880649a98b1ca69638602ca1
$ export JPY_API_TOKEN=97c56c20880649a98b1ca69638602ca1
```

This is equivalent to

```bash
export JPY_API_TOKEN=`jupyterhub token`
```

but not equivalent to

```bash
export JPY_API_TOKEN="jupyterhub token"
```

**Comment by dvigneshwer** [comment]
I generated the token and thanks for the clarification on backtick chacter (`) 

For example:

`JPY_API_TOKEN=76aaea18e2d34acf9e7a370a06a19566`
- I generated it by setting c.Authenticator.admin_users = {'root'}

Its working, thanks
