### ISSUE TITLE
API responses may not conform to Swagger spec

### ISSUE THREAD

**Issue by vilhelmen** [jupyterhub/jupyterhub#672]
Either the API responses are not conforming to swagger specs, or the Bravado library is just being overzealous with type checking. When querying the user list (all I've tested so far), Bravado raises and complains that the null returned for the server field isn't a valid string. Looks like the null is transformed to None, which isn't a string.
```
ValidationError: None is not of type 'string'

Failed validating 'type' in schema['items']['properties']['server']:
    {'description': "The user's server's base URL, if running; null if "
                    'not.',
     'type': 'string'}

On instance[0]['server']:
    None
```
I'm not very familiar with any of this, so there may be something in the Swagger spec to mark it as optional. It can be done with arguments, but I'm not sure if it can be done with response parts. The response from the hub could be changed, I suppose, but that sounds like a lot of work. Ideas?

**Comment by vilhelmen** [comment]
I've been looking over the [spec](http://swagger.io/specification/#definitionsObject) for the last few days, and I don't think there's a nullable/optional type for results.

I've never used a generated API either, but I thought it was a pretty neat idea and got excited that there was one for JH since I didn't see a python client. I've been avoiding requests and trying to use libraries in the hope that they're easier to use than trying to manually speak the API for others I'm working with (GitLab/LDAP).

But it works... after fighting with it a bit. Here's an example if anyone ever happens to go that route and has issues. You have to dump the token into the client header and, at least for now, you want to turn off the response validation. Turning off models makes the responses a dict, which is nice.
```python
from bravado.client import SwaggerClient
from bravado.requests_client import RequestsClient

http_client = RequestsClient()
http_client.session.headers['Authorization'] = ('token ' + token)
jh_api = SwaggerClient.from_url('file:///path/to/yaml',
                                http_client=http_client,
                                config={'use_models': False,'validate_responses': False})

users = jh_api.users.get_users().result()
```
You also need to specify the host in the yaml if you load the yaml from a file, like this
```yaml
host: localhost:8081
```

After writing all that I'm having regrets not just using requests.

**Comment by willingc** [comment]
Closing this issue and tagging it as "Reference".

Thanks @vilhelmen and @minrk.
