### ISSUE TITLE
Remove user not working from Admin Panel

### ISSUE THREAD

**Issue by simtos** [jupyterhub/jupyterhub#674]
Hi,

I created new user in Linux and set password for it. I logged into jupyterhub with admin user and tried to add user from admin panel. I could successfully add it. When I tried to remove user by click on delete its giving error (API request failed (404): error). There is nothing logged in jupyterhub logs even ran service with DEBUG option.
This look to be an issue. Attached is the jupyterhub config file. I am using PAM authenticator

**Comment by minrk** [comment]
Can you post the surrounding debug logs as well? The config file you mentioned does not appear to be attached.

**Comment by simtos** [comment]
Thank you for the quick response. PFA the log file and the config file. I have configured the jupyterhub as a service like below
============================================
[Unit]
Description=Jupyterhub
After=network-online.target

[Service]
User=jupyterhubusr
ExecStart=/usr/bin/jupyterhub --config /etc/jupyterhub/jupyterhub.py --JupyterHub.spawner_class=sudospawner.SudoSpawner --no-ssl --log-level=DEBUG --PAMAuthenticator.open_sessions=False --JupyterHub.extra_log_file='/var/log/jupyterhub.log'
WorkingDirectory=/etc/jupyterhub

[Install]
WantedBy=multi-user.target
===========================================
[jupyterhub.zip](https://github.com/jupyterhub/jupyterhub/files/395280/jupyterhub.zip)

**Comment by simtos** [comment]
Hi Min RK, do you see any issues with configuration, please suggest how we can get this working.. there is nothing logged about this error in  logs :(

**Comment by minrk** [comment]
The log doesn't show the 404, which means that it's not including the logs from the actual time of the request. Can you double check that you included these logs? JupyterHub with `--debug` logs every request with its response status, so there will be a 404 in the logs.

**Comment by simtos** [comment]
I checked multiple times with debug log level. The 404 error only being shown on UI.. not getting logged to jupyterhub. This could be another issue.
Can you please tell what can be done here as nothing is logged related to this error

**Comment by minrk** [comment]
If nothing is being logged, no request is being made to the Hub. Can you check the javascript console for a clue? You might also add the config:

```python
JupyterHub.debug_proxy = True
```

to your jupyterhub_config.py to get extra debugging info out of the HTTP proxy

**Comment by willingc** [comment]
@simtos I'm closing this issue since it's been a couple of weeks. If you still need assistance, please feel free to reopen and share the information requested by @minrk. Thanks!
