### ISSUE TITLE
Uncaught exception GET /hub/oauth_callback

### ISSUE THREAD

**Issue by aidaph** [jupyterhub/jupyterhub#677]
Hi, 

I'm having problems while authenticating from JupyterHub with an shibboleth IDP server.
I have another JupyterHub server which just works fine, but I can't figure out the problem... This server prints out the user once you are authenticated, but it doesn't in the one I'm having problems with, and gives error after a while.

This is the error message, it stays 20 seconds waiting and finally gives timeout error:
```
[I 2016-08-03 10:47:44.990 JupyterHub log:100] 302 GET /hub/oauth_login (@127.0.0.1) 2.44ms

[E 2016-08-03 10:48:10.145 JupyterHub web:1549] Uncaught exception GET /hub/oauth_callback?return=https%3A%2F%2F193.146.75.224%2FShibboleth.sso%2FSAML2%2FPOST%3Fhook%3D1%26target%3Dss%253Amem%253Af050269b2e9faf2fb1b454c50cbeb9f8618a7cbaa32131abb07e16505733b2ca&target=https%3A%2F%2F193.146.75.224%2Fsecure%2F%3Fresponse_type%3Dcode%26client_id%3D%26redirect_uri%3Dhttps%253A%252F%252F192.168.1.33%252Fhub%252Foauth_callback (127.0.0.1)
    HTTPServerRequest(protocol='http', host='192.168.1.33', method='GET', uri='/hub/oauth_callback?return=https%3A%2F%2F192.168.1.33%2FShibboleth.sso%2FSAML2%2FPOST%3Fhook%3D1%26target%3Dss%253Amem%253Af050269b2e9faf2fb1b454c50cbeb9f8618a7cbaa32131abb07e16505733b2ca&target=https%3A%2F%2F192.168.1.33%2Fsecure%2F%3Fresponse_type%3Dcode%26client_id%3D%26redirect_uri%3Dhttps%253A%252F%252F192.168.1.33%252Fhub%252Foauth_callback', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Referer': 'https://idp.ifca.es/idp/profile/SAML2/Redirect/SSO;jsessionid=132414225260C7C510FF10F9D0AC36B7?execution=e1s1&_eventId_proceed=1', 'Connection': 'close', 'X-Forwarded-Port': '80', 'X-Forwarded-Server': 'jupyterhub.privatevlan.cloud.ifca.es', 'Accept-Encoding': 'gzip, deflate, br', 'X-Forwarded-For': '192.168.1.34,127.0.0.1', 'Accept-Language': 'en-US,en;q=0.5', 'X-Forwarded-Proto': 'http', 'Host': '192.168.1.33', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0', 'Cookie': '_saml_idp=aHR0cHM6Ly9pZHAuaWZjYS5lcy9pZHAvc2hpYmJvbGV0aA%3D%3D; _shibsession_64656661756c7468747470733a2f2f3139332e3134362e37352e3232342f53686962626f6c6574682e73736f=_2461c4be751e7905d456f2b788ac40fa', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'X-Forwarded-Host': '192.168.1.33'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1470, in _execute
        result = yield result
      File "/home/ubuntu/oauthenticator/oauthenticator/oauth2.py", line 50, in get
        username = yield self.authenticator.authenticate(self)
      File "/home/ubuntu/oauthenticator/oauthenticator/shibd.py", line 65, in authenticate
        resp = yield http_client.fetch(req)
      File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/tornado/simple_httpclient.py", line 307, in _on_timeout
        raise HTTPError(599, error_message)
    tornado.httpclient.HTTPError: HTTP 599: Timeout while connecting

```

If you need more info or config files don't hesitate to contact me :)

Thanks!!

Aida

**Comment by minrk** [comment]
That suggests that the Hub cannot establish a connection to the oauth server. Are you sure the hosts and ports are correct there? Can you make a manual connection to the same URL?

**Comment by aidaph** [comment]
Thanks for answering!

I've executed the following command (did you mean this by manual connection?):
curl localhost:8000/oauth_callback

And the result is the same, it gives the exact same errors on JupyterHub.

**Comment by minrk** [comment]
Sorry, I meant connecting directly to the OAuth server - the action that the Hub is taking that is failing.

**Comment by pcarazo** [comment]
I think that yes, and there is visibility between the IDP server and Hub&Oauth server (JupyterHub and Oauth server are on the same machine).

It works fine if I change the authentication system to sudospawner in the jupyterhub_config.py file:

`# The base URL of the entire application
c.JupyterHub.base_url = ''
#c.JupyterHub.base_url= '/hub'
c.Authenticator.create_system_users = True

c = get_config()

# These environment variables are automatically supplied by the linked postgres
# container.
import os
import sys

c.JupyterHub.log_level = 10
c.JupyterHub.authenticator_class = 'oauthenticator.LocalShibdOAuthenticator'
c.LocalShibdOAuthenticator.create_system_users = True

c.Authenticator.whitelist = whitelist = set()
c.JupyterHub.admin_users = admin = set()

c.LocalShibdOAuthenticator.oauth_callback_url = 'https://IP/hub/oauth_callback'
#c.LocalShibdOAuthenticator.redirect_uri = 'https://IP/hub/oauth_callback'

c.NotebookApp.notebook_dir = os.path.expanduser('~/notebooks/')

#SSL
#c.JupyterHub.ssl_key = '/etc/ssl/private/hostkey.pem'
#c.JupyterHub.ssl_cert = '/etc/ssl/certs/hostcert.pem'

#token for hub and proxy
#c.JupyterHub.proxy_auth_token = ''

#######################################

#c.SudoSpawner.sudospawner_path = '/usr/local/bin/sudospawner'
#c.Spawner.notebook_dir = 'notebooks/'
#c.Spawner.args = ['--NotebookApp.default_url=']
#c.JupyterHub.spawner_class='sudospawner.SudoSpawner'
                                                     `

**Comment by willingc** [comment]
@aidaph Do you still need assistance with this? Or did @minrk and @pcarazo's information resolve your issue?

**Comment by aidaph** [comment]
I'm still having the same issue, sorry.

**Comment by willingc** [comment]
@aidaph Feel free to share more specifics and error messages. The community may be able to help solve your configuration questions. Thanks!

**Comment by willingc** [comment]
Hi @aidaph,

I hope you are doing well and that you have resolved this.

Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:

**Comment by limeicao** [comment]
have you solved the problems,i meet the same questions, it bother me
