### ISSUE TITLE
custom PYTHONPATH in docker container in singleuser mode

### ISSUE THREAD

**Issue by patricxu** [jupyterhub/jupyterhub#679]
I am using a spawner to create a container for the single user in docker. I have add the PYTHONPATH env to ~/.bashrc and it works when I do this:
docker exec -it <container_id> python 
`import sys`
`sys.path`
It outputs the lib path that I set with PYTHONPATH env.
However, when I use jupyter notebook from web, the lib path is not included.
I don't know why is that. If the lib path is configurable for the web user, how?  I don't want to use sys.path.append() every time.

Thanks!

**Comment by minrk** [comment]
I don't believe .bashrc is sourced normally when launching a docker container with a given command. You may want to change the command in your docker container to launch a script with a login shell, then `exec jupyterhub-singleuser ...`.

Alternately, you can put the `export PYTHONPATH` in the launch script itself.

**Comment by patricxu** [comment]
![ubuntu 64 -2016-08-04-18-12-28](https://cloud.githubusercontent.com/assets/9252137/17398471/980d8c80-5a6f-11e6-818f-8563ca829584.png)
![default](https://cloud.githubusercontent.com/assets/9252137/17398605/31318fce-5a70-11e6-94ce-2b408f0543ba.png)

Hi Minrk,

The environment variable does take effect. It's weird the sys.path are not the same.  All I want is to add the my own path "/.iwind" to the web interface.

Thank you in any case!

Patrick

**Comment by minrk** [comment]
Can you show PYTHONPATH in `%env` output in the notebook?

**Comment by patricxu** [comment]
These are what I got from web access.

CLICOLOR='1'
CONDA_DIR='/opt/conda'
DEBIAN_FRONTEND='noninteractive'
GIT_PAGER='cat'
HOME='/home/jovyan'
HOSTNAME='6d3459a8eb03'
IFS=' 	
'
JPY_BASE_URL='/user/qxu'
JPY_COOKIE_NAME='jupyter-hub-token-qxu'
JPY_HUB_API_URL='http://192.168.40.141:8081/hub/api'
JPY_HUB_PREFIX='/hub/'
JPY_PARENT_PID='5'
JPY_USER='qxu'
LANG='en_US.UTF-8'
LANGUAGE='en_US.UTF-8'
LC_ALL='en_US.UTF-8'
NB_UID='1000'
NB_USER='jovyan'
OPTIND='1'
PAGER='cat'
PATH='/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
PPID='35'
PS1='$ '
PS2='> '
PS4='+ '
PWD='/home/jovyan/work'
SHELL='/bin/bash'
TERM='xterm-color'

using `os.popen("set")`. Note that the PYTHONPATH env is no included. The outcome is very different from those I got from the console within the container.

**Comment by minrk** [comment]
That's because the notebook isn't started by a full bash terminal session, so `.bashrc` doesn't affect the notebook environment. When you do `exec -it bash`, it does start a bash session, so `.bashrc` is sourced. This is what I was alluding to above - you can change the CMD for the image to run a full bash shell and `exec jupyterhub-singleuser` in order to inherit configuration in .bashrc, or more directly you can set PYTHONPATH in the launch script for the notebook directly.

**Comment by patricxu** [comment]
Thanks! I found this
# Environment variables to load for the Spawner.
# 
# Value could be a string or a callable. If it is a callable, it will be called
# with one parameter, which will be the instance of the spawner in use. It
# should quickly (without doing much blocking operations) return a string that
# will be used as the value for the environment variable.
# c.Spawner.environment = {}

It works!

**Comment by vesskov** [comment]
You could also run your docker container with a python path variable specified:
docker run -dti -e PYTHONPATH=/usr/local/lib/python2.7/dist-packages/ imagename:version bash
