### ISSUE TITLE
how to redesign jupyterhub frontend?

### ISSUE THREAD

**Issue by zjeagleeye** [jupyterhub/jupyterhub#682]
Hello everyone, I'm a new coming boy. I want to redesign jupyterhub frontend. However, I don't know how to do it from scratch. There's no detailed description from Jupyterhub documentation. 

Thank you for help

**Comment by minrk** [comment]
JupyterHub doesn't really support theming, but if you modify the templates and LESS in `share/jupyter/hub` you can change how it looks.

**Comment by AbdealiJK** [comment]
I'm looking for this feature too and am wondering if you are open to contributions here ?
