### ISSUE TITLE
PAM-configured TMPDIR not respected

### ISSUE THREAD

**Issue by cruegge** [jupyterhub/jupyterhub#683]
I'm using `pam_tmpdir` to set up the `TMPDIR` environment variable. However, the setting does not end up in the running Jupyter instances or kernels, even when putting it into `env_keep`. This is in particular a problem with the IHaskell kernel, which for some graphics operations writes temporary files to `TMPDIR`, causing collisions between users when falling back to the default `/tmp`.

I managed to work around the problem by implementing a custom spawner which sets the variable in the same way `pam_tmpdir` would, but there should be a cleaner way.

**Comment by willingc** [comment]
@cruegge I'm glad that you created a workaround using a custom spawner.

Pinging @gibiansky for additional thoughts related to temp directories and files when using IHaskell.

cc/ @minrk

**Comment by gibiansky** [comment]
I'm not really sure what I can offer here; as @cruegge indicated, IHaskell uses a temporary directory as a place to write graphics file (some libraries cannot just write a PNG directly to memory for example, only to disk, so IHaskell lets them write it to disk and then loads it to display to the user). To do so I use whatever temporary directory is available -- at the moment I believe it tries to find a TMPDIR environment variable, and, if that doesn't exist, uses /tmp.

If there's anything that IHaskell should be doing better to support use within jupyterhub, please let me know, but for the time being, this looks like just a jupyterhub issue to me. (Please correct me if it seems like there is a different behaviour on IHaskell's side that would make more sense.)

(To be clear though: @willingc thanks for pinging me! Even if I can't necessarily be directly helpful I am happy to chime in whenever necessary or potentially helpful.)

**Comment by willingc** [comment]
Thanks @gibiansky for chiming in and for being open to doing so in the future too. :cookie: Thanks for the additional context re: graphics, writing, and display.

I'm going to leave this labeled as a JupyterHub enhancement.

**Comment by minrk** [comment]
@cruegge where exactly are you setting the tmpdir? It might be the lack of shell initialization in the single-user contexts that's preventing it from happening. `env_keep` only affects which environment variables in the Hub process should be inherited by the single-user servers, and presumably that should not be shared by all users in this case, right?

**Comment by cruegge** [comment]
The temp directory is actually set up by the PAM stack using the [`pam_tmpdir`](https://launchpad.net/ubuntu/+source/pam-tmpdir) module. So it's not shell init and should in principle be available from the PAM session.

I did some digging around, and if I see it correctly, the hub would have to pull out environment variables from the PAM session and add them to the Jupyter instance right before spawning.

The undelying problem is that the `pamela` library does not seem to support this. In fact, its API functions are behaving somewhat oddly in that most of them start a new PAM transaction for only a single operation and then directly close the transaction. Now I don't really understand how PAM is supposed to be used, but in order to get the environment, one would either need to get the not-yet-closed transaction handle from `pamela`, or make it return the environment e.g. from the `open_session` call.

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!
