### ISSUE TITLE
Unable to display Tkinter GUI on non-server computer

### ISSUE THREAD

**Issue by alexjlam** [jupyterhub/jupyterhub#684]
Hello everyone

I want to be able to use the Tkinter to create a GUI for browsing and selecting folders within a Notebook on JupyterHub. If I login to my JupyterHub on a separate computer that's not running the server, and I try to use my Tkinter GUI code in the Notebook, I get the following error.

`TclError: no display name and no $DISPLAY environment variable tkinter`

I know this is coming from my DISPLAY environment variable being empty, so I tried changing the DISPLAY variable on the non-server computer using "DISPLAY=:0", but doing that makes the GUI pop up on the server computer.

I know this is a problem related to forwarding the Tkinter GUI display from the server to the other computer, but I can't find a way to fix this problem within JupyterHub. Do you guys have any suggestions?

Also I've already googled the above error and found many results related to setting "matplotlib.use('Agg')" but the Tkinter code that I'm using does not have anything to do with matplotlib.

**Comment by minrk** [comment]
JupyterHub doesn't and can't do any window forwarding (this is not generally available). If you do have full access, you can forward X with an ssh session:

    ssh -X host

then your DISPLAY variable will likely want to be a differen value from `:0` (e.g. `:1`). You can see the `DISPLAY` variable in the ssh session for the value.

I've never tried forwarding X from commands not started inside the ssh session that set up the forwarding, but I *think* it should work.

**Comment by alexjlam** [comment]
Thanks for the reply. I actually figured out a workaround for this using ipywidgets instead of the Tkinter GUI.

**Comment by willingc** [comment]
@alexjlam You are very welcome. We're happy that you were able to use ipywidgets to accomplish your task.
