### ISSUE TITLE
Getting error: "Permission failure checking authorization, I may need a new token"

### ISSUE THREAD

**Issue by rs2** [jupyterhub/jupyterhub#688]
See [demohub](https://demohub.jupyter.org/user/rs2/tree).

**Comment by willingc** [comment]
@rs2 Your issue doesn't provide much detail. Based on what you have written, I would suggest that you look at this troubleshooting documentation: https://jupyterhub.readthedocs.io/en/latest/troubleshooting.html#error-after-spawning-my-single-user-server

Looking at your logs as recommended in the troubleshooting section of the documentation will provide helpful details too. Please feel free to provide us with additional information if you are unable to resolve your issue. Thanks.

**Comment by rs2** [comment]
I'd love to provide more information, but the instance in question is hosted on [demohub](https://demohub.jupyter.org/). Is it not something where you have access to the logs? Over to you.

**Comment by willingc** [comment]
@rs2 Quick question: what resource led you to demohub.jupyter.org?

I believe that demohub was used as part of an old workshop done by the team. @minrk, do you have the history on this? Is this for pubic use? FYI, I am seeing the same as @rs2.

**Comment by willingc** [comment]
Closing as demohub is for internal training use and is not supported for general public use.
