### ISSUE TITLE
Add ability to launch jupyterlab from jupyterhub

### ISSUE THREAD

**Issue by maxgrenderjones** [jupyterhub/jupyterhub#690]
[jupyterlab](https://github.com/jupyter/jupyterlab) is now minimally usable. It would be great if there was a way of launching it from jupyterhub to enable experimentation in multi-user environements.

(Apologies if this is already possible, but I didn't see anything on google or the docs, and it wasn't obvious how you could change what `jupyterhub-singleuser` actually launches)

**Comment by willingc** [comment]
@maxgrenderjones Thanks for the question. Although JupyterLab is not ready for running production tasks as it is still in alpha, experimentation is a very reasonable request :-)

You may find this helpful: https://github.com/jupyter/docker-stacks/wiki/Docker-Recipes#run-jupyter-lab

Also pinging @mirnk @parente for additional thoughts on using jupyterlab easily for experimentation on jupyterhub.

**Comment by parente** [comment]
The docker-stacks images can now trivially spawn Jupyter lab in containers. Coupled with the fact that the stack images already support Jupyter Hub, it should all just work pretty easily if you're willing to use docker. (It's probably also possible without docker but I'm not as familiar with that path.)

I'm mobile. Will link when at a real keyboard.

**Comment by maxgrenderjones** [comment]
I'm not using docker, so would need something different (I think I'd need a version of [SingleUserNotebookApp]
(https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/singleuser.py)  that inherited from [LabApp](https://github.com/jupyter/jupyterlab/blob/master/jupyterlab/labapp.py), or maybe just a way of setting `default_url` within JupyterHub.

All of which is a long winded way of saying that so long as jupyterlab is installed, it's there once you launch your notebook, so `https://<myhost>/user/<myusername>/lab` lands me on jupyterlab :clap:

**Comment by minrk** [comment]
You can set default_url in your spawner config:

```python
c.Spawner.default_url = '/user/%U/lab/'
```

which ought to be enough to send your users to lab by default.

**Comment by sofianeh** [comment]
I've added 'lab' to the c.Spawner.cmd property and it's now working:

```
# The command used for starting notebooks.
c.Spawner.cmd = ['jupyterhub-singleuser lab']
```

**Comment by willingc** [comment]
From @minrk in https://github.com/jupyterhub/jupyterhub/issues/725#issuecomment-245584865:

Yes, it's possible. You need to install and enable the JupyterLab extension system-wide, then you can change the default URL to `/lab`. For instance:

```bash
pip install jupyterlab
jupyter serverextension enable --py jupyterlab --sys-prefix
```

The important thing is that jupyterlab is installed and enabled in the *single-user* environment. For system users, this means system-wide, as indicated above. For docker containers, it means inside the single-user docker image, etc.

In jupyterhub_config.py, tell single-user servers to default to JupyterLab:

```python
c.Spawner.default_url = '/lab'
```

**Comment by natbusa** [comment]
This is how I solved it

```
c.Spawner.notebook_dir = '/'
c.Spawner.default_url = '/lab'
c.Spawner.cmd = ['jupyterhub-singleuser']
c.Spawner.args = ['lab', '--debug']
```

caveat: although notebook_dir is set to '/' it still looks for a lab directory in the file system. Other than that it works ok.

**Comment by lachlancampbell** [comment]
I have a working hub after mostly following Andrea Zonca's prescription (https://zonca.github.io/2016/04/jupyterhub-sdsc-cloud.html), and I've also been able to get jupyterlab running in the docker containers based on this page. The only problem is the default url is still coming up as /tree. The following output is listed when I start up the hub:

{'trait': <traitlets.traitlets.Unicode object at 0x7fc266925f28>, 'value': '/user/{username}/lab', 'owner': <dockerspawner.systemuserspawner.SystemUserSpawner object at 0x7fc2632bee48>}

Any advice appreciated :)

**Comment by ZelphirKaltstahl** [comment]
This is not working at the moment with `DockerSpawner`.

I've got the following in my `jupyterhub_config.py`:

    c.Spawner.cmd = ['jupyterhub-singleuser lab']
    c.DockerSpawner.cmd = ['jupyterhub-singleuser lab']
    c.Spawner.default_url = '/lab'
    c.DockerSpawner.default_url = '/lab'

Still `jupyterhub` directs to `/tree?`.

What can I change in `DockerSpawner` to make it redirect to `/lab`?

**Comment by minrk** [comment]
Assuming that you have current versions of DockerSpawner (0.9) and JupyterHub (0.8), this is all of the configuration you need:

```python
c.Spawner.default_url = '/lab'
```

If you change your DockerSpawner configuration, make sure that you delete any existing containers. These changes only take effect when containers are created.

If you set:

```python
c.DockerSpawner.remove_containers = True
```

Note that doing this means that when user servers stop, their containers are deleted, so if their files should persist, make sure their home directory is mounted somewhere.

**Comment by ZelphirKaltstahl** [comment]
@minrk Ah I did not update DockerSpawner. Just one architectural question: What does DockerSpawner have to do with the application inside the Docker container? Isn't it JupyterHub's job to do the routing of requests and would it not make more sense to have changes regarding that inside JupyterHub only?

**Comment by lachlancampbell** [comment]
Thank you, removing the containers worked :)
