### ISSUE TITLE
Installation of Table of Contents extension

### ISSUE THREAD

**Issue by sudipto84goswami** [jupyterhub/jupyterhub#691]
Hi Team,

I followed the installation of extensions through - https://github.com/ipython-contrib/jupyter_contrib_nbextensions. 

My requirement is to us Table of Content extension in the Jupyterhub. After installation i restarted the hub, still the extensions are not getting loaded.

I already have the installation done. I am having the below two files also present under - .ipython/nbextensions/
toc.js 
toc.css

Please let me know on how to proceed on this. And if this feature is applicable at Hub environment,

**Comment by willingc** [comment]
Hi @sudipto84goswami,

Thanks for the question. Could you please provide us a bit more information about the versions that you are using?

**Comment by sudipto84goswami** [comment]
Hi Carol,

You can mark this as closed. This is working now.

**Comment by willingc** [comment]
Glad you got it working @sudipto84goswami.
