### ISSUE TITLE
How to set the port range for single user notebook server

### ISSUE THREAD

**Issue by kishorchintal** [jupyterhub/jupyterhub#692]
I would like to control the port ranges which jupyterhub can use to spawn the single user notebook server. Is it possible?

**Comment by minrk** [comment]
@kishorchintal yes, with a custom Spawner you can limit the port range. Can I ask why you want to do this, and what spawner you are using?

**Comment by kishorchintal** [comment]
@minrk I am using DockerSpawner.  Whenever I log in, it spawns the docker container for me but if I try to create a notebook it is not able to connect to the kernel (see below message). I am doing it in AWS and I suspect it is due to the security groups which does not allow tcp connection on those ports(for ex. port 32830, where I do not have connectivity).

"A connection to the notebook server could not be established. The notebook will continue trying to reconnect, but until it does, you will NOT be able to run code. Check your network connection or notebook server configuration"

**Comment by kishorchintal** [comment]
@minrk I tried to read through the documentation. I found that Jupyter notebook server uses the ZeroMQ libraries and the kernel it starts when I ask it to create a Python2/3 notebook uses different sockets. I realized that it is able to talk to the docker container and saves the content of my notebook but it cannot run. This confirms that the security groups are not the problem here but the kernel level communication is causing this issue. I am not sure how does it work when I use port forwarding to my hub instance.

**Comment by minrk** [comment]
The ports of the notebook servers are only needed to be accessible to the Hub itself, they do not need to be accessible to the outside world. In the case of a single server, these only need to be accessible on localhost / the docker virtual network. There is only one external port needed for all of JupyterHub.

The message you describe indicates a failure to establish a websocket connection, not a connection to the notebook server as a whole (which is required to display that message). That may be due to a proxy running on your AWS instance that's preventing websocket connections.

**Comment by kishorchintal** [comment]
I see the below error when I try to create a notebook. Is there a configuration I need to do for web sockets to get past this problem? 

`WebSocket connection to 'ws://<IP Address>:8000/user/tom/api/kernels/3ab582cd-9502-45c3-a993-e4e750771608/channels?session_id=B9DAC9AE905848DBBCABA21F014646C5' failed: HTTP Authentication failed; no valid credentials available`

**Comment by minrk** [comment]
That is strange. If there's an additional proxy, it may not be proxying websocket connections correctly. Can you tell if there is a proxy in front of the Hub application (in front of the configurable-http-proxy instance)?

**Comment by kishorchintal** [comment]
The problem is resolved now. I was running it in no-ssl mode, once I applied the certificates, the kernel is able to connect.

**Comment by willingc** [comment]
@kishorchintal We're glad you have gotten this resolved and the kernel is connecting. 👍 

**Resolution:** Apply SSL certificate when error message displays `no valid credentials available`.

**Comment by kishorchintal** [comment]
Addition to Resolution: When you are behind a proxy customize the notebook server config file to include http_proxy and https_proxy
