### ISSUE TITLE
JupyterHub not starting with self signed certificate.

### ISSUE THREAD

**Issue by TrigonaMinima** [jupyterhub/jupyterhub#694]
JupyterHub is running if I specify the ```--no-ssl``` tag, but its not working when I specify the self signed certificate in the config. I generated the cert using:

    openssl req -x509 -newkey rsa:1024 -keyout jhub.key -out jhub.crt -days 365 -nodes

My config file is:

```
c.JupyterHub.ssl_key = 'jhub.key'
c.JupyterHub.ssl_cert = 'jhub.crt'
c.JupyterHub.port = 8000
```
The browser just throws 

> The 127.0.0.1 page isn’t working
> 127.0.0.1 didn’t send any data.
> ERR_EMPTY_RESPONSE

I tried this on both Chrome and Firefox. I cant find the solution regarding this anywhere.

**Comment by willingc** [comment]
@TrigonaMinima Would you try setting the port to 443 in the config file? Hopefully that will solve your connection when using https. ``c.JupyterHub.port = 443``

**Comment by TrigonaMinima** [comment]
@willingc It's still giving me the same response. Also, if it was going to run on port 443 then shouldn't it also run on port 8000? I am asking this because on linux to use any port less than 1024 you need to run the program as root otherwise it was giving me ```EACCES``` error. And, I don't want to use ```sudo``` to run JupyterHub. So, the problem is still unsolved.

One more thing I noticed was when I ran ```sudo jupyterhub``` terminal gave me ```Command not found``` error. I had to run it by giving the full path to the binary. So, I guess there was no such file on the sudo ```PATH```. One possible solution for this might be - create a soft link to the jupyterub executable into ```/usr/local/bin``` or any such directory included in the sudo PATH.

**Comment by minrk** [comment]
@TrigonaMinima make sure you connect to `https://127.0.0.1:8000`, not `http://127.0.0.1:8000`. You will get an error similar to what you have reported if you make an HTTP request to an HTTPS server.

**Comment by TrigonaMinima** [comment]
@minrk thanks. That solved the problem. I was clicking on the url printed (```http://127.0.0.1:8000```) on the terminal after running ```jupyterhub``` command.
