### ISSUE TITLE
Admin screen start server and stop server color does not change

### ISSUE THREAD

**Issue by dvigneshwer** [jupyterhub/jupyterhub#695]
I was running cull service in the background, the notebook server start/stop button does not change color after the notebook server being culled ie It stay stop server only (Red color) even after being culled , it should bascially turn into start server (green color)

The admin screen returns a alert message "**API request failed (400): root's server is not running**"

![image](https://cloud.githubusercontent.com/assets/5075497/17779705/35a2dfd8-6586-11e6-9add-15aecc5a2650.png)

**Comment by minrk** [comment]
It's true that the admin page doesn't live-update, but I don't see this as a big problem. The user can refresh the page to get a fresh view if something has changed since the page was loaded.

**Comment by dvigneshwer** [comment]
Yeah I agree that it does not cause any big problem just show api request failed notification as above in case server not running and the button is still green.

I raised this issue, even after cull service being stopped the particular notebook server is showing the green button.

Can we intergrate a web socket to these buttons and request api for the users status from which we can modify them in the admin dashboard.

Just a suggestion, I am just starting to go through the jupyterhub code base.

This will help in better monitoring and going ahead I am planning to implement cull service for each notebook server session based on user activity (ref #680 ) for better culling.

**Comment by minrk** [comment]
I don't think we should add a websocket or live state monitoring to the admin page. That adds unnecessary load to the Hub, and I don't think it is worth the complexity, given how the current admin page works.

I have considered switching the admin page to use react, in which case this might become more feasible.

**Comment by dvigneshwer** [comment]
okay keep me in loop with that repo, I am closing this issue now.

**Comment by alivcor** [comment]
Not sure if this is the right place to ask, but is there a way to display an alert message on client browser window through the `poll()` function ?

**Comment by alivcor** [comment]
@minrk @dvigneshwer Can we do this using API ?

_Is there a way to display an alert message on client browser window through the `poll()` function ?_

**Comment by minrk** [comment]
@alivcor there is no such method to display alert messages.

**Comment by alivcor** [comment]
Thank you @minrk ! While writing a custom spawner, is there an alternate way to display a JS alert message on client browser window through the `poll()` function (willing to do a few patches locally) ?

Any help is highly appreciated ! Thanks for you time :)

**Comment by minrk** [comment]
poll wouldn't be a place to do it. poll should only check if a server is running. Such functionality would primarily be an extension to jupyter/notebook. You would need a server-side extension for publishing the messages and a javascript extension for handling and displaying them. Once you have built that mechanism, you would need to figure out when such messages should be produced and figure out how to deliver them to your servers. It's likely that JupyterHub wouldn't be involved at any point, other than in your custom Spawner making sure that the extension is installed and hooked up to whatever your message source is.
