### ISSUE TITLE
adduser fails with default config

### ISSUE THREAD

**Issue by SeanHealy33** [jupyterhub/jupyterhub#696]
OS: Amazon Linux AMI

When you attempt to create a user from the admin control panel. It fails returning a 400 error to the client

```
[E 2016-08-18 15:27:09.590 JupyterHub concurrent:341] Future <tornado.concurrent.Future object at 0x7f2567ca1ef0> exception was never retrieved: Traceback (most recent call last):
      File "/usr/local/lib64/python3.4/site-packages/tornado/gen.py", line 1024, in run
        yielded = self.gen.send(value)
      File "/tmp/packer-provisioner-ansible-local/jupyterhub/jupyterhub/auth.py", line 326, in add_user
        yield gen.maybe_future(self.add_system_user(user))
      File "/tmp/packer-provisioner-ansible-local/jupyterhub/jupyterhub/auth.py", line 351, in add_system_user
        raise RuntimeError("Failed to create system user %s: %s" % (name, err))
    RuntimeError: Failed to create system user adsf: adduser: invalid option -- 'q'
    Usage: useradd [options] LOGIN
``` 

This appears to be caused by https://github.com/jupyterhub/jupyterhub/blob/f1bdf6247abe3f41d571ea94116cf64ec7ed45df/jupyterhub/auth.py#L286 

As most of the flags in the command are not valid adduser flags in linux. http://linux.die.net/man/8/adduser

I found adding something like this to my config resolves the issue: 
```
c.Authenticator.add_user_cmd =  ['adduser', '--home', '/home/USERNAME']
```

to avoid unusual failings like this we should update the `auth.py` file to account for correct linux flags

**Comment by SeanHealy33** [comment]
It appears on further checking that 
`return ['adduser', '-q', '--gecos', '""', '--disabled-password']`

is a FreeBSD `adduser` command: http://www.freebsd.org/cgi/man.cgi?adduser(8)

considering the linux way is `adduser -m <username>`

**Comment by minrk** [comment]
I've tested and verified that the default command does indeed work on Debian and Ubuntu, so it's not a FreeBSD-specific command, and valid on tested Linux distros. What's the base distro for your AMI?

I haven't seen a command that does the right thing everywhere, which is why this command is configurable.

**Comment by SeanHealy33** [comment]
Sorry for the delay our AMI seems to be based off `centos 5`. But I'd misunderstood that these commands can have variance over multiple distros (I figured they were consistent though it makes sense they are not) so I'm happy to close this. I've also verified that the default works on debian 😄

**Comment by willingc** [comment]
@SeanHealy33 We're glad that you have this up and running. Thanks for the update verifying the default works on Debian. :sunny:
