### ISSUE TITLE
support Windows

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#7]

**Comment by denfromufa** [comment]
MSFT (@smortaz) may provide support, if there is enough demand for this feature:

https://news.ycombinator.com/item?id=13109546

**Comment by minrk** [comment]
Cool, thanks @denfromufa! FWIW, a custom Authenticator and custom Spawner could work on Windows. The main things that are out of scope are support for Windows in the *default* Authenticator (PAM) and Spawner (LocalProcess via setuid). If you ran JupyterHub with GitHub auth and DockerSpawner, for instance, it may well work on Windows, with either no, or very little modifications.
