### ISSUE TITLE
Multiple jupyterhub servers with same users

### ISSUE THREAD

**Issue by katsar0v** [jupyterhub/jupyterhub#700]
As I haven't seen this in the documentation, just wanted to ask is it possible to have x amount of jupyterhub servers working with the same users, if yes, what configuration could help me achieving this.

**Comment by minrk** [comment]
Not at the moment, no. JupyterHub currently enforces one server per Hub user. If you created multiple Hub users per human, you could achieve this.

**Comment by katsar0v** [comment]
My idea is rather having x amount of jupyterhub servers behind load balancer

**Comment by minrk** [comment]
Sorry, I misunderstood the question. Multiple Hubs behind a load-balancer may work, but it will work best if you route users deterministically to the same Hub.

**Comment by katsar0v** [comment]
Yes that makes sense, but what if one of the hub behind the load balancer fails and another hub needs to continue its work? But this with routing sounds interesting, would be really helpful if you could give some more info

**Comment by minrk** [comment]
If one hub fails, another should be able to pick up where it left off (in-memory state of running notebooks would be lost, of course). The only issue should be if two hubs are actively trying to manage the same user at the same time. If it moves from one Hub to another in a semi-permanent way (i.e. coinciding with starting a new single-user server), that should be fine.

**Comment by katsar0v** [comment]
Yes, this should be the case, unfortunately a lot of error refusing happens, as well redirect loop + 500 internal server errors. Has someone already done this, as I am trying to get what @minrk commented working. 

Do the hubs need to have the same cookie secret, as well what else is required for the flawless work of multiple jupyterhubs. Thanks in advance to anyone joining this discussion.

**Comment by katsar0v** [comment]
How about routing and fixing the refused connections errors

**Comment by katsar0v** [comment]
When having multiple jupyterhubs behind nginx in the same docker network, the following error occurs:

`[I 2016-08-24 08:48:05.953 JupyterHub orm:159] Adding user test to proxy /user/test => http://172.18.0.4:8888
[E 2016-08-24 08:48:05.958 JupyterHub web:1524] Uncaught exception POST /hub/login?next= (172.18.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='172.18.0.1', headers={'X-Forwarded-For': '172.18.0.1', 'Referer': 'http://localhost:8000/hub/login', 'Upgrade-Insecure-Requests': '1', 'Content-Length': '27', 'Connection': 'close', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36', 'Origin': 'http://localhost:8000', 'X-Forwarded-Proto': 'http', 'Content-Type': 'application/x-www-form-urlencoded', 'Accept-Language': 'en-US,en;q=0.8,bg;q=0.6', 'X-Forwarded-Port': '8000', 'Host': 'localhost:8000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Cache-Control': 'max-age=0', 'Accept-Encoding': 'gzip, deflate'})
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 79, in post
        yield self.spawn_single_user(user)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 335, in spawn_single_user
        yield finish_user_spawn()
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 308, in finish_user_spawn
        yield self.proxy.add_user(user)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/orm.py", line 172, in add_user
        client=client,
    ConnectionRefusedError: [Errno 111] Connection refused`

**Comment by katsar0v** [comment]
The issue is resolved, the different hubs need to have different DB, while a common authenticator is possible.

**Comment by willingc** [comment]
@katsar0v Thanks for following up. I glad that you resolved the issue. Thanks again for taking the time to pass along the resolution:

> the different hubs need to have different DB, while a common authenticator is possible.
