### ISSUE TITLE
sudospawner failure - [PAM Error 14] cannot make/remove an entry

### ISSUE THREAD

**Issue by hani1814** [jupyterhub/jupyterhub#704]
Hi,

I've successfully installed jupyter hub and it works fine when launched from root.

I've then installed sudospawner (as in https://github.com/jupyterhub/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges) but now I get the following error when launching the hub:

[ConfigurationProxy] PROXY WEB /hub/login?next= to http://localhost:9998

Failed to create home directory

[jupyterhub auth:383] Failed to open PAM session for d3849648: [PAM Error 14] cannot make/remove an entry for the specified session sudo: sorry, a password is required to run sudo

Worth noting that i do get authorization failure if I enter the wrong password, so clearly it is getting a response form PAM. 

and the following works

$ sudo -u jupyterserv python -c "import pamela, getpass; print(pamela.authenticate('$USER', getpass.getpass()))"
Password: [enter your unix password]

Please help

**Comment by minrk** [comment]
Does it work if you add:

```python
c.PAMAuthenticator.open_sessions = False
```

to your jupyterhub_config.py?

**Comment by hani1814** [comment]
Hi, I have added the above but it is throwing an error:

HDP1-230-2:/var/opt/teradata/anaconda3 # su jupytersrv
jupytersrv@XXUKHDP1-230-2:/var/opt/teradata/anaconda3> jupyterhub --JupyterHub.spawner_class=sudospawner.SudoSpawner --ssl-key mykey.pem --ssl-cert mycert.pem --debug
[D 2016-08-26 16:44:45.921 JupyterHub application:529] Looking for jupyterhub_config in None
[D 2016-08-26 16:44:45.921 JupyterHub application:549] Loaded config file: /var/opt/teradata/anaconda3/jupyterhub_config.py
[I 2016-08-26 16:44:45.924 JupyterHub app:558] Loading cookie_secret from /var/opt/teradata/anaconda3/jupyterhub_cookie_secret
[D 2016-08-26 16:44:45.924 JupyterHub app:623] Connecting to db: sqlite:///jupyterhub.sqlite
[W 2016-08-26 16:44:45.958 JupyterHub configurable:169] ***Config option `open_sessions` not recognized by `PAMAuthenticator`.**
[I 2016-08-26 16:44:45.961 JupyterHub app:712] Not using whitelist. Any authenticated user will be allowed.
[D 2016-08-26 16:44:46.012 JupyterHub app:787] Loaded users:
           d admin
           6 admin
           4 admin
           3 admin
           9 admin
           8 admin
    43849648
    d3849648 admin
      hadoop
    43784957
    43967688
[I 2016-08-26 16:44:46.019 JupyterHub app:1113] Hub API listening on http://localhost:9998/hub/
[I 2016-08-26 16:44:46.022 JupyterHub app:860] Starting proxy @ http://*:9996/
[D 2016-08-26 16:44:46.022 JupyterHub app:861] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '9996', '--api-ip', '127.0.0.1', '--api-port', '9997', '--default-target', 'http://localhost:9998' (http://localhost:9998%27), '--log-level', 'debug', '--ssl-key', 'mykey.pem', '--ssl-cert', 'mycert.pem']
16:44:46.162 - info: [ConfigProxy] Proxying https://*:9996 to http://localhost:9998
16:44:46.165 - info: [ConfigProxy] Proxy API at http://127.0.0.1:9997/api/routes
[D 2016-08-26 16:44:46.227 JupyterHub app:889] Proxy started and appears to be up
[I 2016-08-26 16:44:46.227 JupyterHub app:1136] JupyterHub is now running at http://127.0.0.1:9996/

**Comment by petrbalek** [comment]
Hi,
I have some problem "PAM Error 14".
Version 0.7.1 is working without problem, but 0.7.2 fail with error:

W 2017-06-22 09:14:49.975 JupyterHub auth:484] Failed to open PAM session for x0521019: [PAM Error 14] Cannot make/remove an entry for the specified sess
ion

I am runing on SUSE:
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 3

**Comment by SergeyK1** [comment]
It work for my

**Comment by thongnnguyen** [comment]
I confirm that the following helps resolved the `PAM` issues.

> Does it work if you add:
> 
> ```python
> c.PAMAuthenticator.open_sessions = False
> ```
> 
> to your jupyterhub_config.py?

But now I'm hit with error from `preexec_fn`

```
[E 2018-10-11 10:14:24.682 JupyterHub user:477] Unhandled error starting user1's server: Exception occurred in preexec_fn.
[E 2018-10-11 10:14:24.748 JupyterHub web:1670] Uncaught exception GET /hub/user/user1/ (::ffff:98.222.52.43)
    HTTPServerRequest(protocol='https', host='XXXX', method='GET', uri='/hub/user/user1/', version='HTTP/1.1', remote_ip='::ffff:98.222.52.43')
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 1052, in get
        await self.spawn_single_user(user)
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 705, in spawn_single_user
        timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
        await spawn_future
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 489, in spawn
        raise e
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 409, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/spawner.py", line 1110, in start
        self.proc = Popen(cmd, **popen_kwargs)
      File "/opt/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/opt/anaconda3/lib/python3.6/subprocess.py", line 1345, in _execute_child
        raise child_exception_type(err_msg)
    subprocess.SubprocessError: Exception occurred in preexec_fn.

```

**Comment by gabefair** [comment]
Were you ever able to fix this? Is there anything I can provide to help troubleshoot this? I'm in the exact same boat

**Comment by jml6m** [comment]
`c.PAMAuthenticator.open_sessions = False` doesn't work for me. The user's server won't start and I'll have to restart it by clicking the "Start My Server" button but then I just get the Permission Denied error again.

It has something to do with JupyterHub not having access to /home/{user} directory?
