### ISSUE TITLE
Improve 'Deploying JupyterHub on AWS' documentation

### ISSUE THREAD

**Issue by Winterflower** [jupyterhub/jupyterhub#708]
Hi JupyterHub team!
I'm in the process of creating a JupyterHub for PyLadies London on an EC2 instance and I've hit a few snags with the 'Deploying JupyterHub on AWS' documentation. I'll keep track of the changes I'm making on the wiki in this issue. 

_Current Issues_
- mention that JupyterHub may need to be started as sudo [complete]
- documentation takes the user through Docker installation, but it isn't clear if the final spawner actually uses Docker. Might be hard for a complete Docker newbie to follow. [in-progress]
- it seems that there is a custom Jupyterhub docker image ([see here](https://github.com/jupyterhub/jupyterhub)) which is not mentioned in the documentation at all.

**Comment by minrk** [comment]
Thanks for working on this!

**Comment by willingc** [comment]
@Winterflower 🌻 Thanks!

**Comment by willingc** [comment]
@Winterflower You may also find this information written by @jtyberg on our reference docker deployment helpful too.  https://github.com/jupyterhub/jupyterhub-deploy-docker/pull/1#issuecomment-210625602

**Comment by FalseProtagonist** [comment]
Stupid question - why does this page say to install docker? It seems to be using the ProcessSpawner. Sorry I'm new to this.

**Comment by Winterflower** [comment]
@FalseProtagonist good question -  it's been a while since I looked at this doc, but it doesn't seem to mention anything about configuring Docker Spawner (which is why I assume they include the install Docker part ). I'm not the original author, so not sure why the Docker section was originally included, but feel free to improve the doc if you would like to clarify! :)

**Comment by FalseProtagonist** [comment]
Thanks for the quick reply!

Sorry, I don't know enough to be writing documents about this. I found this document by looking for something that had described setting up a dockerspawner on AWS, to see if I could get that running.

**Comment by Winterflower** [comment]
@FalseProtagonist  have you looked at the README on the tmpnb pproject?
https://github.com/jupyter/tmpnb 
It runs an on-demand Jupyter notebook per user and launches them inside Docker containers.

**Comment by FalseProtagonist** [comment]
Thanks a lot, I'll take a look.

**Comment by willingc** [comment]
Hi @Winterflower and @FalseProtagonist, Another good reference (though it is still a work in progress) is https://zero-to-jupyterhub.readthedocs.io and AWS in this PR https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/129.

**Comment by willingc** [comment]
Closing this issue now that the [docs on Zero to JupyterHub for AWS](https://zero-to-jupyterhub.readthedocs.io/en/latest/create-k8s-cluster.html#setting-up-kubernetes-on-amazon-web-services-aws) have improved.
