### ISSUE TITLE
Jupyterhub and nbviewer - need some guidance

### ISSUE THREAD

**Issue by mattwg** [jupyterhub/jupyterhub#71]
So I now have Jupyterhub running internally at eBay.  That is cool - thanks @dsblank for help getting install issues sorted.  I will keep testing with my small team and see how we get on.

I also installed nbviewer - another mini-adventure since it turns out there is a bug in pip that ships with 14.04 ;-)

I would like to be able to publish notebooks from the jupyterhub to nbviewer - is this possible? It appears that the jupyterhub URL is not publicly visible and I get a 404 error in nbviewer - is the best workaround to create a publicly visible www directory for each user and just copy the notebooks over when I want to publish to nbviewer?  Or is there some easier way to achieve this from within nbviewer?  

Any plans to have git integration in Jupyterhub? 

Thanks in advance,
Matt

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. I'm marking this as "reference" so the information is discoverable and may be included in future documentation. Nice work @dsblank. Thanks to all!
