### ISSUE TITLE
What's the password of users created in control panel?

### ISSUE THREAD

**Issue by inkrement** [jupyterhub/jupyterhub#710]
Notebook works like a charm, and I am able to create new users (seems like it uses adduser in the background). But what's the password of new created users? Do I have to open the terminal and set it manually with `passwd`? If this is the case, would it be possible to set a "default" password for each new user? I know this would be *very* unsecure, but I want to use it for teaching purposes and it would be a pain in the ass if I have to call passwd for each user.

**Comment by minrk** [comment]
Adding users via the admin interface is mainly useful if you have an external authentication system, such as LDAP or OAuth. If it's a local system user and you are using PAM authenticator, then the user will have no password set until you call `passwd`.

The best way to add users if you are using normal system users is to use normal system user commands, such as `adduser`. If this is for a class, external authentication mechanisms such as OAuth have the benefit of not having to distribute usernames and passwords.

You can script user and password generation without too much trouble, given a list of usernames:

```bash
for user in $users; do
    useradd -m $user # make the user
    pass=`openssl rand -hex 8` # generate random password
    echo "$user:$pass" | chpasswd # set the password
    echo "$user $pass" # or `>> passwords` to create a file recording your passwords
done
```

**Comment by inkrement** [comment]
Thanks!

**Comment by Casyfill** [comment]
Is there a way to do that via helm/k8s?
