### ISSUE TITLE
Start jupyter notebook with more memory

### ISSUE THREAD

**Issue by hani1814** [jupyterhub/jupyterhub#713]
I am using jupyter notebook and hub. When I start a pyspark session, it is constrained to three containers and a small amount of memory.

How can I configure the jupyter pyspark kernel in notebook to start with more memory.

Can this be done in a notebook session / individual rather than a global default?

Thank you

**Comment by minrk** [comment]
I believe these are influenced by environment variables. You can check the pyspark kernelspec `kernel.json` file, where you can specify additional environment variables to pass to the kernel.

**Comment by hani1814** [comment]
Yes that works but unfortunately it is applied to all the users. Can these be applied to individual users?

**Comment by minrk** [comment]
To apply it for individual users, you would need to have a kernelspec for each user (i.e. copy the kernelspec to ~/.local/share/jupyter/kernels/), or set the environment variable in the notebook process instead (this would require relaunching the notebook server on change).

If there are only a few values that you want, you could have a few copies of the pyspark kernelspec with different values - small, medium, large, for instance - and then users could pick from a dropdown which they want to use for any individual notebook.

**Comment by hani1814** [comment]
thank you for the tip. 

-Jupyter  appears to ignore the content of ~/.local/share/jupyter/kernels/

-I created a copy of the kernel (from /usr/local/share/jupyter/kernels/pyspark) and called it pysparktest. The good news is that it appears in the drop down but pyspark fails as soon as parameters are added to it such as:

**"PYSPARK_SUBMIT_ARGS": "--master yarn --num_executors 8 --executor-memory 10g pyspark-shell",**

**"PYSPARK_SUBMIT_ARGS": "--master yarn pyspark-shell",** works

running the above configuration from the command line works perfectly. There is a very similar issue which does not appear to have been addressed - [438](https://github.com/jupyterhub/jupyterhub/issues/438 )

Any ideas?

**Comment by minrk** [comment]
> -Jupyter appears to ignore the content of ~/.local/share/jupyter/kernels/

What platform? What do you see in `jupyter kernelspec list` and `jupyter --paths`?

I think asking the pyspark-kernel authors the best way to pass arguments to their kernel is the thing to do. The issue doesn't appear to have to do with JupyterHub, and I've not used pyspark much, so I can't help much with configuring it.

**Comment by hani1814** [comment]
Hi,

As requested - pyspark1 is my test one

jupyter kernelspec list
Available kernels:
  python2     /var/opt/teradata/anaconda/lib/python2.7/site-packages/ipykernel/resources
  pyspark     /usr/local/share/jupyter/kernels/pyspark
  pyspark1    /usr/local/share/jupyter/kernels/pyspark1


jupyter --paths
config:
    /root/.jupyter
    /var/opt/teradata/anaconda/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /root/.local/share/jupyter
    /var/opt/teradata/anaconda/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /root/.local/share/jupyter/runtime

**Comment by willingc** [comment]
@hani1814 I just came across this issue. FYI. I've added some documentation in a PR about configuring pySpark executors on YARN applications https://github.com/jupyterhub/jupyterhub/pull/737.

**Comment by willingc** [comment]
@hani1814 This blog post may be useful to you as well http://thepowerofdata.io/configuring-jupyteripython-notebook-to-work-with-pyspark-1-4-0/

I'm going to close this issue as I agree with @minrk that consulting the pyspark devs/users would be helpful. Please do let us know what you find out from them since it may help future users. Thanks! :cookie:

**Comment by TMorville** [comment]
I have similar issues, however, I start Pyspark with findspark

```
import findspark
findspark.init()

import pyspark
import random

sc = pyspark.SparkContext(appName="Pi")
```

and parsing a csv file of ~ 700000 rows, it runs out of memory:` java.lang.OutOfMemoryError: Java heap space`.

Any ideas how to 1) print what spark.driver.memory is set to and 2) increase the amount for a single notebook?

**Comment by hani1814** [comment]
example kernel

{
   "display_name":"Pyspark TEST",
   "language" : "python",
   "argv": [
       "/usr/local/bin/python2.7",

       "-m",
       "ipykernel",
       "-f",
       "{connection_file}"
   ],
   "env" : {
       "SPARK_HOME":"/usr/hdp/2.4.2.0-258/spark/",
       "PYTHONPATH" : "/usr/hdp/2.4.2.0-258/spark/python/:/usr/hdp/2.4.2.0-258/spark/python/lib/py4j-0.9-src.zip",
       "PYTHONSTARTUP" : "/usr/hdp/2.4.2.0-258/spark/python/pyspark/shell.py",
       "PYSPARK_SUBMIT_ARGS": "--master yarn  **--num-executors 8** pyspark-shell",
       "PYSPARK_PYTHON": "/usr/local/bin/python2.7",
       "PYSPARK_DRIVER_PYTHON": "/usr/local/bin/python2.7"
}
}

**Comment by TMorville** [comment]
@hani1814 

Thanks for this. I've been googling custom kernels, however, [it seems that might be a bit of hassle to implement them in jupyter?](https://github.com/Microsoft/AzureNotebooks/issues/59).

Do you have any links to doc that might easen this for me?
