### ISSUE TITLE
Add docs on upgrading JupyterHub

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#723]
Especially when db fields are added / changed, upgrading requires manually. I think we use alembic for this, but we don't have any specific docs on how to do this.

We should have those docs!

**Comment by minrk** [comment]
Indeed we should! Where I expect this error to occur (connecting to the db in the first place), there is [an informative error](https://github.com/jupyterhub/jupyterhub/blob/acb49adfea7d3923310e5bed02d55014632a654f/jupyterhub/app.py#L761) message pointing to:

    jupyterhub upgrade-db

I'm surprised by the recent debugging chat that an error occurred at such a later time.

It certainly should be added to the docs, probably including the fact that sqlite doesn't allow for all of the operations (ALTER TABLE being the key missing operation) that may be necessary for upgrading the db, so upgrade may only be available on postgres, etc.

**Comment by willingc** [comment]
Great suggestion @yuvipanda 👍 

Some topics to cover:

- Upgrading JupyterHub reference deployments
- Upgrading JupyterHub when no database changes are being made (i.e. no new fields)
- Upgrading JupyterHub when adding a new db field (sqllite vs. postgres...)
- Informative message to user as mentioned by @minrk prompting the user to run `jupyterhub upgrade-db` after upgrading jupyterhub.

**Comment by willingc** [comment]
Here's a pass at some ideas for upgrading doc. Possibly more questions than answers currently re: our support:

## Definitions
db type: sqlite, postgres, mysql, others???
db fields: individual fields in a database table

## Basic use cases
- [ ] Simple upgrade - no database fields changed; no db type change
- [ ] Field changes  - database fields added, deleted or changed by a new JHub release/functionality; no db type change

## More complex use cases
- [ ] Field changes - database fields added, deleted or changed by user; no db type change
- [ ] db type change (i.e. sqlite to postgres) - fields may or may not change; db type does change

## Process
- Remind admins to back up Hub databases
- Possibly remind admins to make sure single user notebook data is saved/backed up
- Admin notify users (if desired) of planned upgrade

**Multi-step upgrade vs all at once**??
- Migrate database type (Hub at same release level) user-initiated
- Add/change/delete fields (Hub at same release level) user-initiated
- Add/change/delete files (Hub initiated - in prep for JHub release upgrade)
- Upgrade Hub to 0.7 after

- Upgrade/changes to: CHP, authenticators, spawners

## Other topics
- limitations of sqlite upgrade
- upgrade hub first or upgrade db first???

## Tools
- alembic
- scripts
- sqlalchemy?
- db tools

**Comment by minrk** [comment]
Shall we call this addressed by #767?
