### ISSUE TITLE
Proxy Stops working in Jupyter Hub

### ISSUE THREAD

**Issue by hani1814** [jupyterhub/jupyterhub#724]
Hi,

I am using jupyerhub with sudospawner (https://github.com/jupyterhub). All works well but after a few hours, it just stops working with the following error (taken around the time it stopped).

Looks like the proxy just stopped (exit code 7) and jupyter was not able to restart it. 

Any idea what the issue may be?

```
The server was started at 930am
[34m[D 2016-09-05 15:05:15.237 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-05 15:10:15.236 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-05 15:15:15.236 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-05 15:20:15.237 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[31m[E 2016-09-05 15:25:15.233 JupyterHub app:896](B[m **Proxy stopped with exit code 7**
[32m[I 2016-09-05 15:25:15.240 JupyterHub app:860](B[m Starting proxy @ http://*:9996/
[34m[D 2016-09-05 15:25:15.240 JupyterHub app:861](B[m Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '9996', '--api-ip', '127.0.0.1', '--api-port', '9997', '--default-target', 'http://localhost:9998', '--log-level', 'debug', '--ssl-key', 'mykey.pem', '--ssl-cert', 'mycert.pem']
[34m[D 2016-09-05 15:25:15.244 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[31m[E 2016-09-05 15:25:15.245 JupyterHub ioloop:629](B[m Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f605bb47ea0>, <tornado.concurrent.Future object at 0x7f605bb3ae48>)
    Traceback (most recent call last):
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 600, in _run_callback
        ret = callback()
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 615, in <lambda>
        self.add_future(ret, lambda f: f.result())
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/jupyterhub/app.py", line 1072, in update_last_activity
        routes = yield self.proxy.get_routes()
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/jupyterhub/orm.py", line 187, in get_routes
        resp = yield self.api_request('', client=client)
    ConnectionRefusedError: [Errno 111] Connection refused
    
[31m[E 2016-09-05 15:25:16.247 JupyterHub ioloop:629](B[m Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f605bb47598>, <tornado.concurrent.Future object at 0x7f605bb6ceb8>)
    Traceback (most recent call last):
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 600, in _run_callback
        ret = callback()
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 615, in <lambda>
        self.add_future(ret, lambda f: f.result())
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/jupyterhub/app.py", line 898, in check_proxy
        yield self.start_proxy()
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/jupyterhub/app.py", line 881, in start_proxy
        _check()
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/jupyterhub/app.py", line 877, in _check
        raise e
    RuntimeError: Proxy failed to start with exit code 1
    
[31m[E 2016-09-05 15:25:45.230 JupyterHub app:896](B[m Proxy stopped with exit code 1
[32m[I 2016-09-05 15:25:45.231 JupyterHub app:860](B[m Starting proxy @ http://*:9996/
[34m[D 2016-09-05 15:25:45.232 JupyterHub app:861](B[m Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '9996', '--api-ip', '127.0.0.1', '--api-port', '9997', '--default-target', 'http://localhost:9998', '--log-level', 'debug', '--ssl-key', 'mykey.pem', '--ssl-cert', 'mycert.pem']
[31m[E 2016-09-05 15:25:46.240 JupyterHub ioloop:629](B[m Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f605bb458c8>, <tornado.concurrent.Future object at 0x7f605bb43c88>)
    Traceback (most recent call last):
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 600, in _run_callback
        ret = callback()
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 615, in <lambda>
        self.add_future(ret, lambda f: f.result())
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/jupyterhub/app.py", line 898, in check_proxy
        yield self.start_proxy()
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/jupyterhub/app.py", line 881, in start_proxy
        _check()
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/jupyterhub/app.py", line 877, in _check
        raise e
    RuntimeError: Proxy failed to start with exit code 1
```

**Comment by minrk** [comment]
If the proxy fails to start, it should produce output. How are you capturing the output of jupyterhub? The best thing to do is to forward stdout/stderr to a log file. You can use Python logging to send it to a file, but this will only include the output of the Hub process itself, while we need the proxy's output to debug this issue.

**Comment by hani1814** [comment]
The proxy starts and runs for a while but then appears to die.

I am getting the above output from the jupyterhub.log file

any idea how to forward the stdout / stderr

**Comment by minrk** [comment]
How are you starting JupyterHub, and how are you capturing the output?

The simplest way to capture JupyterHub and any subprocess output (the same is true for all processes) when started from a shell is:

```bash
jupyterhub &>> /var/log/jupyterhub.log
```

If you are using a service tool like supervisor, there will be options for forwarding stdout/err to files.

**Comment by hani1814** [comment]
I am starting the hub as follows

jupyterhub --JupyterHub.spawner_class=sudospawner.SudoSpawner --ssl-key mykey.pem --ssl-cert mycert.pem --debug&

and retrieving the log from jupyterhub.log

Restarted yesterday so a bit more info from the above log

[32m[I 2016-09-06 12:44:41.738 JupyterHub app:558](B[m Loading cookie_secret from /var/opt/teradata/anaconda3/jupyterhub_cookie_secret
[34m[D 2016-09-06 12:44:41.739 JupyterHub app:623](B[m Connecting to db: sqlite:///jupyterhub.sqlite
[32m[I 2016-09-06 12:44:41.773 JupyterHub app:712](B[m Not using whitelist. Any authenticated user will be allowed.
[34m[D 2016-09-06 12:44:41.783 JupyterHub app:770](B[m Loading state for d3849648 from db
[33m[W 2016-09-06 12:44:42.037 JupyterHub app:782](B[m d3849648 not running.
[34m[D 2016-09-06 12:44:42.043 JupyterHub app:770](B[m Loading state for 43784957 from db
[34m[D 2016-09-06 12:44:42.576 JupyterHub app:782](B[m 43784957 not running.
[34m[D 2016-09-06 12:44:42.577 JupyterHub app:787](B[m Loaded users: 
    d3849648 admin
    43784957
[32m[I 2016-09-06 12:44:42.662 JupyterHub app:1113](B[m Hub API listening on http://localhost:9998/hub/
[32m[I 2016-09-06 12:44:42.666 JupyterHub app:860](B[m Starting proxy @ http://*:9996/
[34m[D 2016-09-06 12:44:42.666 JupyterHub app:861](B[m Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '9996', '--api-ip', '127.0.0.1', '--api-port', '9997', '--default-target', 'http://localhost:9998', '--log-level', 'debug', '--ssl-key', 'mykey.pem', '--ssl-cert', 'mycert.pem']
[34m[D 2016-09-06 12:44:42.871 JupyterHub app:889](B[m Proxy started and appears to be up
[32m[I 2016-09-06 12:44:42.871 JupyterHub app:1136](B[m JupyterHub is now running at http://127.0.0.1:9996/
[34m[D 2016-09-06 12:49:42.901 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 12:54:42.896 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[32m[I 2016-09-06 12:54:54.384 JupyterHub log:100](B[m 302 GET / (@127.0.0.1) 3.05ms
[32m[I 2016-09-06 12:54:54.629 JupyterHub log:100](B[m 302 GET /hub (@127.0.0.1) 0.33ms
[32m[I 2016-09-06 12:54:54.669 JupyterHub log:100](B[m 302 GET /hub/ (@127.0.0.1) 0.58ms
[32m[I 2016-09-06 12:54:54.738 JupyterHub log:100](B[m 200 GET /hub/login (@127.0.0.1) 27.72ms
[34m[D 2016-09-06 12:54:54.872 JupyterHub log:100](B[m 200 GET /hub/static/css/style.min.css?v=807166c81ded9672f91872a576572dcd (@127.0.0.1) 6.65ms
[34m[D 2016-09-06 12:54:55.057 JupyterHub log:100](B[m 200 GET /hub/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce (@127.0.0.1) 0.78ms
[34m[D 2016-09-06 12:54:55.105 JupyterHub log:100](B[m 200 GET /hub/logo (@127.0.0.1) 0.67ms
[33m[W 2016-09-06 12:55:02.292 JupyterHub auth:383](B[m Failed to open PAM session for d3849648: [PAM Error 14] Cannot make/remove an entry for the specified session
[34m[D 2016-09-06 12:55:03.752 JupyterHub spawner:287](B[m Polling subprocess every 30s
[34m[D 2016-09-06 12:55:03.832 JupyterHub utils:84](B[m Server at http://127.0.0.1:38020/user/d3849648 responded with 302
[32m[I 2016-09-06 12:55:03.833 JupyterHub base:301](B[m User d3849648 server took 1.663 seconds to start
[32m[I 2016-09-06 12:55:03.833 JupyterHub orm:159](B[m Adding user d3849648 to proxy /user/d3849648 => http://127.0.0.1:38020
[34m[D 2016-09-06 12:55:03.835 JupyterHub orm:146](B[m Fetching POST http://127.0.0.1:9997/api/routes/user/d3849648
[34m[D 2016-09-06 12:55:03.838 JupyterHub base:226](B[m Setting cookie for d3849648: jupyter-hub-token-d3849648, {}
[34m[D 2016-09-06 12:55:03.840 JupyterHub base:226](B[m Setting cookie for d3849648: jupyter-hub-token, {}
[32m[I 2016-09-06 12:55:03.843 JupyterHub log:100](B[m 302 POST /hub/login?next= (@127.0.0.1) 1757.62ms
[32m[I 2016-09-06 12:55:03.843 JupyterHub login:79](B[m User logged in: d3849648
[34m[D 2016-09-06 12:55:03.900 JupyterHub pages:29](B[m User is running: /user/d3849648
[32m[I 2016-09-06 12:55:03.904 JupyterHub log:100](B[m 302 GET /hub/ (d3849648@127.0.0.1) 16.02ms
[32m[I 2016-09-06 12:55:04.008 JupyterHub log:100](B[m 200 GET /hub/api/authorizations/cookie/jupyter-hub-token-d3849648/[secret] (d3849648@127.0.0.1) 9.63ms
[32m[I 2016-09-06 12:57:45.471 JupyterHub login:17](B[m User logged out: d3849648
[32m[I 2016-09-06 12:57:45.477 JupyterHub log:100](B[m 302 GET /hub/logout (d3849648@127.0.0.1) 8.42ms
[32m[I 2016-09-06 12:57:45.516 JupyterHub log:100](B[m 302 GET /hub/ (@127.0.0.1) 0.58ms
[32m[I 2016-09-06 12:57:45.584 JupyterHub log:100](B[m 200 GET /hub/login (@127.0.0.1) 1.24ms
[34m[D 2016-09-06 12:57:45.664 JupyterHub log:100](B[m 200 GET /hub/static/css/style.min.css?v=807166c81ded9672f91872a576572dcd (@127.0.0.1) 1.10ms
[34m[D 2016-09-06 12:59:42.884 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 13:04:42.884 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 13:09:42.884 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 13:10:20.614 JupyterHub base:226](B[m Setting cookie for d3849648: jupyter-hub-token-d3849648, {}
[34m[D 2016-09-06 13:10:20.615 JupyterHub base:226](B[m Setting cookie for d3849648: jupyter-hub-token, {}
[32m[I 2016-09-06 13:10:20.619 JupyterHub log:100](B[m 302 POST /hub/login?next= (@127.0.0.1) 330.66ms
[32m[I 2016-09-06 13:10:20.619 JupyterHub login:79](B[m User logged in: d3849648
[34m[D 2016-09-06 13:10:20.663 JupyterHub pages:29](B[m User is running: /user/d3849648
[32m[I 2016-09-06 13:10:20.668 JupyterHub log:100](B[m 302 GET /hub/ (d3849648@127.0.0.1) 3.39ms
[32m[I 2016-09-06 13:10:20.768 JupyterHub log:100](B[m 200 GET /hub/api/authorizations/cookie/jupyter-hub-token-d3849648/[secret] (d3849648@127.0.0.1) 9.65ms
[32m[I 2016-09-06 13:10:25.575 JupyterHub login:17](B[m User logged out: d3849648
[32m[I 2016-09-06 13:10:25.582 JupyterHub log:100](B[m 302 GET /hub/logout (d3849648@127.0.0.1) 7.38ms
[32m[I 2016-09-06 13:10:25.649 JupyterHub login:17](B[m User logged out: d3849648
[32m[I 2016-09-06 13:10:25.655 JupyterHub log:100](B[m 302 GET /hub/logout (d3849648@127.0.0.1) 4.45ms
[32m[I 2016-09-06 13:10:25.705 JupyterHub log:100](B[m 302 GET /hub/ (@127.0.0.1) 0.57ms
[32m[I 2016-09-06 13:10:25.744 JupyterHub log:100](B[m 200 GET /hub/login (@127.0.0.1) 1.24ms
[34m[D 2016-09-06 13:14:42.885 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 13:19:42.884 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 13:24:42.884 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 13:29:42.884 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 13:34:42.884 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 13:39:42.885 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 13:44:42.876 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 13:49:42.884 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 13:54:42.878 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 13:59:42.884 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 14:04:42.883 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 14:09:42.885 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[32m[I 2016-09-06 14:14:24.325 JupyterHub log:100](B[m 302 GET / (@127.0.0.1) 3.75ms
[32m[I 2016-09-06 14:14:24.830 JupyterHub log:100](B[m 302 GET /hub (@127.0.0.1) 0.40ms
[32m[I 2016-09-06 14:14:25.071 JupyterHub log:100](B[m 302 GET /hub/ (@127.0.0.1) 0.69ms
[32m[I 2016-09-06 14:14:25.383 JupyterHub log:100](B[m 200 GET /hub/login (@127.0.0.1) 1.33ms
[34m[D 2016-09-06 14:14:25.501 JupyterHub log:100](B[m 200 GET /hub/static/css/style.min.css?v=807166c81ded9672f91872a576572dcd (@127.0.0.1) 1.10ms
[34m[D 2016-09-06 14:14:26.490 JupyterHub log:100](B[m 200 GET /hub/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce (@127.0.0.1) 1.02ms
[34m[D 2016-09-06 14:14:26.527 JupyterHub log:100](B[m 200 GET /hub/logo (@127.0.0.1) 0.61ms
[33m[W 2016-09-06 14:14:34.882 JupyterHub auth:372](B[m PAM Authentication failed (@127.0.0.1): [PAM Error 7] Authentication failure
[34m[D 2016-09-06 14:14:34.883 JupyterHub login:81](B[m Failed login for None
[32m[I 2016-09-06 14:14:34.888 JupyterHub log:100](B[m 200 POST /hub/login?next= (@127.0.0.1) 108.29ms
[34m[D 2016-09-06 14:14:41.441 JupyterHub base:226](B[m Setting cookie for d3849648: jupyter-hub-token-d3849648, {}
[34m[D 2016-09-06 14:14:41.441 JupyterHub base:226](B[m Setting cookie for d3849648: jupyter-hub-token, {}
[32m[I 2016-09-06 14:14:41.445 JupyterHub log:100](B[m 302 POST /hub/login?next= (@127.0.0.1) 336.65ms
[32m[I 2016-09-06 14:14:41.445 JupyterHub login:79](B[m User logged in: d3849648
[34m[D 2016-09-06 14:14:41.492 JupyterHub pages:29](B[m User is running: /user/d3849648
[32m[I 2016-09-06 14:14:41.496 JupyterHub log:100](B[m 302 GET /hub/ (d3849648@127.0.0.1) 3.32ms
[32m[I 2016-09-06 14:14:41.603 JupyterHub log:100](B[m 200 GET /hub/api/authorizations/cookie/jupyter-hub-token-d3849648/[secret] (d3849648@127.0.0.1) 9.35ms
[34m[D 2016-09-06 14:14:42.875 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[32m[I 2016-09-06 14:14:47.868 JupyterHub login:17](B[m User logged out: d3849648
[32m[I 2016-09-06 14:14:47.873 JupyterHub log:100](B[m 302 GET /hub/logout (d3849648@127.0.0.1) 6.61ms
[32m[I 2016-09-06 14:14:47.917 JupyterHub log:100](B[m 302 GET /hub/ (@127.0.0.1) 0.57ms
[32m[I 2016-09-06 14:14:47.960 JupyterHub log:100](B[m 200 GET /hub/login (@127.0.0.1) 1.24ms
[34m[D 2016-09-06 14:19:42.884 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 14:24:42.883 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 14:29:42.885 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 14:34:42.881 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 14:39:42.881 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 14:44:42.883 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 14:49:42.883 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 14:54:42.884 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 14:59:42.885 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 15:04:42.884 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 15:09:42.884 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 15:14:42.883 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 15:19:42.883 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 15:24:42.886 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 15:29:42.883 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 15:34:42.884 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[32m[I 2016-09-06 15:35:35.993 JupyterHub log:100](B[m 302 GET / (@127.0.0.1) 4.24ms
[32m[I 2016-09-06 15:35:36.391 JupyterHub log:100](B[m 302 GET /hub (@127.0.0.1) 0.35ms
[32m[I 2016-09-06 15:35:36.467 JupyterHub log:100](B[m 302 GET /hub/ (@127.0.0.1) 0.61ms
[32m[I 2016-09-06 15:35:36.552 JupyterHub log:100](B[m 200 GET /hub/login (@127.0.0.1) 1.28ms
[34m[D 2016-09-06 15:35:36.746 JupyterHub log:100](B[m 200 GET /hub/static/css/style.min.css?v=807166c81ded9672f91872a576572dcd (@127.0.0.1) 1.15ms
[34m[D 2016-09-06 15:35:37.058 JupyterHub log:100](B[m 200 GET /hub/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce (@127.0.0.1) 0.98ms
[34m[D 2016-09-06 15:35:37.342 JupyterHub log:100](B[m 200 GET /hub/logo (@127.0.0.1) 0.65ms
[34m[D 2016-09-06 15:39:42.881 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 15:44:42.878 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-06 15:49:42.884 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes

**then same as above every 5 min until it failed this morning**

[34m[D 2016-09-07 09:09:42.876 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[34m[D 2016-09-07 09:14:42.881 JupyterHub orm:146](B[m Fetching GET http://127.0.0.1:9997/api/routes
[31m[E 2016-09-07 09:17:12.881 JupyterHub app:896](B[m Proxy stopped with exit code 7

[32m[I 2016-09-07 09:17:12.887 JupyterHub app:860](B[m Starting proxy @ http://*:9996/
[34m[D 2016-09-07 09:17:12.888 JupyterHub app:861](B[m Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '9996', '--api-ip', '127.0.0.1', '--api-port', '9997', '--default-target', 'http://localhost:9998', '--log-level', 'debug', '--ssl-key', 'mykey.pem', '--ssl-cert', 'mycert.pem']
[31m[E 2016-09-07 09:17:13.894 JupyterHub ioloop:629](B[m Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fd1b8a11730>, <tornado.concurrent.Future object at 0x7fd1b4133b38>)
    Traceback (most recent call last):
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 600, in _run_callback
        ret = callback()
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 615, in <lambda>
        self.add_future(ret, lambda f: f.result())
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/jupyterhub/app.py", line 898, in check_proxy
        yield self.start_proxy()
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/jupyterhub/app.py", line 881, in start_proxy
        _check()
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/jupyterhub/app.py", line 877, in _check
        raise e
    RuntimeError: Proxy failed to start with exit code 1
    
[31m[E 2016-09-07 09:17:42.878 JupyterHub app:896](B[m Proxy stopped with exit code 1
[32m[I 2016-09-07 09:17:42.879 JupyterHub app:860](B[m Starting proxy @ http://*:9996/
[34m[D 2016-09-07 09:17:42.879 JupyterHub app:861](B[m Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '9996', '--api-ip', '127.0.0.1', '--api-port', '9997', '--default-target', 'http://localhost:9998', '--log-level', 'debug', '--ssl-key', 'mykey.pem', '--ssl-cert', 'mycert.pem']
[31m[E 2016-09-07 09:17:43.886 JupyterHub ioloop:629](B[m Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fd1b40c3400>, <tornado.concurrent.Future object at 0x7fd1b4927a58>)
    Traceback (most recent call last):
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 600, in _run_callback
        ret = callback()
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 615, in <lambda>
        self.add_future(ret, lambda f: f.result())
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/jupyterhub/app.py", line 898, in check_proxy
        yield self.start_proxy()
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/jupyterhub/app.py", line 881, in start_proxy
        _check()
      File "/var/opt/teradata/anaconda3/lib/python3.5/site-packages/jupyterhub/app.py", line 877, in _check
        raise e
    RuntimeError: Proxy failed to start with exit code 1

**Comment by minrk** [comment]
@hani1814 try the `&>> /var/log/jupyterhub.log` command above, and remove any `extra_log_file` config you may have in `jupyterhub_config.py`.

**Comment by hani1814** [comment]
tried the following (account has got write access), hub works, but the log file has a size of 0 for the last hour. Is this normal?

`jupyterhub --JupyterHub.spawner_class=sudospawner.SudoSpawner --ssl-key mykey.pem --ssl-cert mycert.pem --debug& >> jupyterhub.log`

**Comment by dsblank** [comment]
No, that command is not right. In general it is:

command1 >> log_file 2>&1

For more info, see
http://stackoverflow.com/questions/7526971/how-to-redirect-both-stdout-and-stderr-to-a-file

**Comment by hani1814** [comment]
Hi,

The problem has been solved as we had a notebook running as well as jupyter hub. By stopping the notebook, jupyerhub has been running for over a week now.

Thank you

**Comment by AnirudhVyas** [comment]
What does that mean - notebook running as well as jupyter hub - off course a notebook will be in running state while running jupyterhub right?
I ask because my proxy fails to restart when jupyterhub runs check_process( )

**Comment by dnapier** [comment]
I think he means that there was a jupyter instance started separate from the instances created by Jupyterhub.  I'm also seeing this issue, and am shooting in the dark as to fixing it.

**Comment by AnirudhVyas** [comment]
My issue was fixed by using screen and running the jupyter from there ... I do not know why a tty/pty is required but it was - atleast in our case - I am ok with it, not sure if this can be removed as a requirement or perhaps it isnt ...
