### ISSUE TITLE
Integration with JupyterLab

### ISSUE THREAD

**Issue by zer0n** [jupyterhub/jupyterhub#725]
Is it possible to configure JupyterHub and/or JupyterLab so that I can Lab within Hub?

[Same issue posted on Jupyter Lab](https://github.com/jupyter/jupyterlab/issues/850)

**Comment by minrk** [comment]
Yes, it's possible. You need to install and enable the JupyterLab extension system-wide, then you can change the default URL to `/lab`. For instance:

```bash
pip install jupyterlab
jupyter serverextension enable --py jupyterlab --sys-prefix
```

The important thing is that jupyterlab is installed and enabled in the *single-user* environment. For system users, this means system-wide, as indicated above. For docker containers, it means inside the single-user docker image, etc.

In jupyterhub_config.py, tell single-user servers to default to JupyterLab:

```python
c.Spawner.default_url = '/lab'
```

**Comment by willingc** [comment]
@zer0n I'm closing this issue as a duplicate of #690. In addition to @minrk's response, you may find the discussion on #690 helpful too. Thanks for your interest in JupyterLab and JupyterHub :smile:

**Comment by zer0n** [comment]
Fantastic. Thanks @minrk and @willingc .
