### ISSUE TITLE
Jupyterhub Proxy silently fails to connect.

### ISSUE THREAD

**Issue by cmcneil** [jupyterhub/jupyterhub#729]
Hello,
 I am running jupyterhub with 
`jupyterhub --port 7777 --ssl-key /etc/letsencrypt/live/convox.org/privkey.pem --ssl-cert /etc/letsencrypt/live/convox.org/fullchain.pem`
 It returns no errors, and everything appears to work correctly as you can see below:

```
[I 2016-09-07 14:13:58.962 JupyterHub app:518] Loading cookie_secret from /root/jupyter/jupyterhub_cookie_secret
[W 2016-09-07 14:13:58.982 JupyterHub app:631] No admin users, admin interface will be unavailable.
[W 2016-09-07 14:13:58.982 JupyterHub app:632] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2016-09-07 14:13:58.982 JupyterHub app:652] Not using whitelist. Any authenticated user will be allowed.
[I 2016-09-07 14:13:58.992 JupyterHub app:1031] Hub API listening on http://localhost:8081/hub/
[I 2016-09-07 14:13:58.994 JupyterHub app:788] Starting proxy @ http://*:7777/
14:13:59.074 - info: [ConfigProxy] Proxying https://*:7777 to http://localhost:8081
14:13:59.076 - info: [ConfigProxy] Proxy API at http://localhost:7778/api/routes
[I 2016-09-07 14:13:59.097 JupyterHub app:1054] JupyterHub is now running at http://localhost:7777/
```

However, while I CAN connect to the server without the proxy on localhost (for example via `lynx localhost:8081`), I cannot connect through the proxy. No errors (or any additional messages at all), reported on the command line or in the logs, just a timeout. (This is the behavior whether I try to connect to 7777 locally OR remotely)

**Comment by cmcneil** [comment]
Note also that everything was working perfectly for the last year or two on exactly this machine. I recently restarted the process after getting renewed SSL certs, and now I get this behavior :(

**Comment by willingc** [comment]
@cmcneil Let's see if we can isolate what is happening with new let's encrypt cert, jupyterhub config, and proxy config. 

- [ ] You mention that you have been running things for the past year or two. Please check that you are using a recent version jupyterhub and http-configurable-proxy.
- [ ] When you restarted jupyterhub, did you also restart the proxy? The [Proxy Authentication token](https://jupyterhub.readthedocs.io/en/latest/getting-started.html#proxy-authentication-token) is shared by both the hub and the proxy. If you haven't manually set the Proxy Authentication token in the config file or via command line, you will need to restart both jupyterhub and the proxy.

@minrk, other thoughts?

**Comment by cmcneil** [comment]
DEEERRRRP. My http-configurable-proxy was current, but I updated jupyterhub, and this fixed the issue. So whatever it was, it's fixed now :)

**Comment by willingc** [comment]
@cmcneil You are very welcome. I'm glad updating jupyterhub fixed it 👍
