### ISSUE TITLE
Run a jupyter notebook on startup in a single user notebooks server on Jupyterhub?

### ISSUE THREAD

**Issue by mrinmoyprasad** [jupyterhub/jupyterhub#743]
I have a jupyter notebook, which provides abstract implementation of SQL queries, for users to use in other cells.

I want the context of this notebook in other notebooks (user's work directory) when a user logs in to Jupyterhub. So users can directly use its context to fire their queries using methods of the python notebook I want to run on startup. Also, can I hide this notebook (place it somewhere other than work folder?), so that users do not see this wrapper notebook?

I am using Dockerspawner to launch single user notebook servers in separate containers.

Thanks
Mrinmoy

**Comment by minrk** [comment]
IPython startup files, placed in `~/.ipython/profile_default/startup` will be executed. These can be Python scripts (.py) or IPython scripts (.ipy with `%magic` commands). Notebooks aren't supported as startup files, but if it really needs to be a notebook, you can use `%run /path/to/notebook.ipynb` in a `.ipy` startup file.

**Comment by mrinmoyprasad** [comment]
@minrk Thanks! This worked. I placed my notebook with .ipy extension and I am able to call object of that script from newly created notebooks.
