### ISSUE TITLE
Authenticator.admin_users set BUT no Admin interface available

### ISSUE THREAD

**Issue by bourguig** [jupyterhub/jupyterhub#744]
Hi ,
I'm pulling my hair with the **Authenticator.admin_users** parameter on the configuration file. Even when it's set as {'user1', 'user2'}, JupyterHub doesn't recognize the set, and the Admin Interface remains unavailable.
Thanks for reading, and any help/pointing is much appreciated.

**Comment by minrk** [comment]
What do you see in the logs? Can you run with `--debug`? Can you also include `pip3 list` or `conda list` for the environment?

**Comment by bourguig** [comment]
Hi minrk, Thanks for your reply ;)
Installing jupterhub package using pip3 leaded me to the issue, but when I cloned it from github, the problem is gone and the **Authenticator.admin_users** is now set as expected.
Here are the result of `pip3 list` command:
`
backports-abc (0.4)
chardet (2.3.0)
colorama (0.3.2)
decorator (4.0.10)
entrypoints (0.2.2)
html5lib (0.999)
ipykernel (4.5.0)
ipython (5.1.0)
ipython-genutils (0.1.0)
ipywidgets (5.2.2)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.0.0)
jupyter-core (4.1.1)
jupyterhub (0.6.1)
MarkupSafe (0.23)
mistune (0.7.3)
nbconvert (4.2.0)
nbformat (4.1.0)
notebook (4.2.2)
pamela (0.2.1)
pexpect (4.2.1)
pickleshare (0.7.4)
pip (1.5.6)
prompt-toolkit (1.0.7)
ptyprocess (0.5.1)
Pygments (2.1.3)
pyzmq (15.4.0)
qtconsole (4.2.1)
requests (2.4.3)
setuptools (27.1.2)
simplegeneric (0.8.1)
six (1.10.0)
SQLAlchemy (1.0.15)
terminado (0.6)
tornado (4.4.1)
traitlets (4.3.0)
urllib3 (1.9.1)
wcwidth (0.1.7)
wheel (0.24.0)
widgetsnbextension (1.2.6)
`
_anaconda_ is not installed on the environnement
Here is the result of the `jupyterhub --no-ssl --debug` command:
`
[D 2016-09-15 11:31:06.038 JupyterHub application:550] Looking for jupyterhub_config in None
[I 2016-09-15 11:31:06.040 JupyterHub app:622] Loading cookie_secret from /home/user00/jupyterhub_cookie_secret
[D 2016-09-15 11:31:06.048 JupyterHub app:694] Connecting to db: sqlite:///jupyterhub.sqlite
[W 2016-09-15 11:31:06.198 JupyterHub app:304] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[W 2016-09-15 11:31:06.206 JupyterHub app:757] No admin users, admin interface will be unavailable.
[W 2016-09-15 11:31:06.207 JupyterHub app:758] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2016-09-15 11:31:06.207 JupyterHub app:785] Not using whitelist. Any authenticated user will be allowed.
[D 2016-09-15 11:31:06.222 JupyterHub app:888] Loaded users: 
      user00
      user01
[I 2016-09-15 11:31:06.236 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
[W 2016-09-15 11:31:06.241 JupyterHub app:959] Running JupyterHub without SSL. There better be SSL termination happening somewhere else...
[I 2016-09-15 11:31:06.241 JupyterHub app:968] Starting proxy @ http://*:8000/
[D 2016-09-15 11:31:06.242 JupyterHub app:969] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--default-target', 'http://127.0.0.1:8081', '--error-target', 'http://127.0.0.1:8081/hub/error']
11:31:06.790 - info: [ConfigProxy] Proxying http://*:8000 to http://127.0.0.1:8081
11:31:06.795 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[D 2016-09-15 11:31:06.893 JupyterHub app:997] Proxy started and appears to be up
[I 2016-09-15 11:31:06.899 JupyterHub app:1254] JupyterHub is now running at http://127.0.0.1:8000/

`

**Comment by minrk** [comment]
Where is your jupyterhub_config.py? The default place to look is in the CWD. If it's somewhere else, you will need:

    jupyterhub -f /path/to/jupyterhub_config.py

**Comment by bourguig** [comment]
jupyterhub_config.py is effectively in the CWD, but your command semms to solve the problem definitly, even if I launch jupyterhub again without -f option.

Thank you very much the Admin Interface works like a charm now !

By the way,
What directory shall the CurrentWorkingDirectory be relative to, the one where the jupyterhub is launched (maybe as $PATH variable from $HOME), or where it's installed (/usr/local/lib/...) ?

**Comment by minrk** [comment]
current working directory is what you get when you type `pwd` in the shell when you are about to launch jupyterhub. In Python, this is `os.getcwd()`. You should see `jupyterhub_config.py` in the output of `ls`.

**Comment by bourguig** [comment]
Thanks a lot minrk.

**Comment by sudi007** [comment]
Hello Minrk 
am having couple of issues i am trying to setup jupyterhub server on redhat linux  with NativeAuthenticator in the jupyterconfig.py file but when i run the jupyterhub it allows me to create a username and password but when i try to log in it does not log in and even when i try to log in with root user , the other thing is am not able to access the admin page too there is no admin button i can see would you be able to guide me please 
 Thanks 
sudi
