### ISSUE TITLE
Persist user data when using GitHub Oauth + DockerContainer?

### ISSUE THREAD

**Issue by zer0n** [jupyterhub/jupyterhub#747]
1. How can I map `/home/user` in the container to `some_directory/user`
in the host server?
2. How to automatically create `some_directory/user` and run some init
script when a user first signs in?

**Comment by minrk** [comment]
Continuing discussion in earlier thread [on the list](https://groups.google.com/forum/#!topic/jupyter/E_EW_kpYIks)
