### ISSUE TITLE
jupyterhub docker does not seem to work

### ISSUE THREAD

**Issue by smartinsightsfromdata** [jupyterhub/jupyterhub#751]
I've just installed `Docker for MAC on my laptop.

I've tested the installation using NGINX and all worked with no problem.

I've installed the `official` docker for `jupyterhub` and launched  `jupyterhub` with the suggested command:
```
docker run -d --name jupyterhub jupyterhub/jupyterhub jupyterhub --no-ssl
```
And I can see with `docker ps` the container up and running.

The problem is that when I get to `localhost:8000` I just get `Problem Loading page` or similar -browser-dependent message.

The container log (thanks to Kinematic) is as follows:
```
[I 2016-09-17 10:03:43.200 JupyterHub app:726] Writing cookie_secret to /srv/jupyterhub/jupyterhub_cookie_secret
[W 2016-09-17 10:03:43.537 JupyterHub app:346] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[W 2016-09-17 10:03:43.562 JupyterHub app:845] No admin users, admin interface will be unavailable.
[W 2016-09-17 10:03:43.562 JupyterHub app:846] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2016-09-17 10:03:43.563 JupyterHub app:873] Not using whitelist. Any authenticated user will be allowed.
[I 2016-09-17 10:03:43.577 JupyterHub app:1431] Hub API listening on http://127.0.0.1:8081/hub/
[W 2016-09-17 10:03:43.580 JupyterHub app:1157] Running JupyterHub without SSL. There better be SSL termination happening somewhere else...
[I 2016-09-17 10:03:43.581 JupyterHub app:1166] Starting proxy @ http://*:8000/
10:03:43.849 - info: [ConfigProxy] Proxying http://*:8000 to http://127.0.0.1:8081
10:03:43.850 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[I 2016-09-17 10:03:43.894 JupyterHub app:1461] JupyterHub is now running at http://127.0.0.1:8000/
```
Any suggestion please??

**Comment by srujun** [comment]
When running the command without any ports published (like you did above), you can only view the Hub using `localhost:8000` from within your container. To publish the ports, add the `-P` flag like so `docker run -dP --name jupyterhub jupyterhub/jupyterhub jupyterhub --no-ssl`. And then 8000 on localhost will be mapped to 8000 within the container.

**Comment by smartinsightsfromdata** [comment]
The suggested change did work. on the other had `docker ps` gives the following:
```
CONTAINER ID        IMAGE                   COMMAND                 CREATED             STATUS              PORTS                     NAMES
a6a05829b74d        jupyterhub/jupyterhub   "jupyterhub --no-ssl"   5 minutes ago       Up 5 minutes        0.0.0.0:32769->8000/tcp   jupyterhub
```
And the screen was accessible using `localhost:32769`.

As I was following the info on the main github page of the project, may I suggest to add the above docker command to the page?

Many thanks to @srujun !

**Comment by stratosgear** [comment]
So is this really the way to access Jupyterhub? From localhost:32768? (Yes, that's the port `docker ps` gives me when I follow the above procedure)

**Comment by mjbright** [comment]
If you specify -p 8000 then Docker will assign an external port for you (32768 in your case).

If you specify, for example -p 8000:8000, then you can access using localhost:8000

**Comment by stratosgear** [comment]
Thanks for taking the time to reply. It works as you specified.
