### ISSUE TITLE
[DockerSpawner] Failed to get port info

### ISSUE THREAD

**Issue by zer0n** [jupyterhub/jupyterhub#754]
I followed [this example](https://github.com/jupyterhub/dockerspawner/blob/master/examples/oauth/jupyterhub_config.py). I was able to get the Hub running and GitHub authentication working. However, I ran into this error when trying to start a single notebook server.

![image](https://cloud.githubusercontent.com/assets/3055719/18613016/c19bf876-7d23-11e6-9223-a95612c6c7b2.png)

[This line](https://github.com/jupyterhub/dockerspawner/blob/master/examples/oauth/jupyterhub_config.py#L8) suggests that the default loopback port doesn't work. However, I don't see the port setting anywhere.

**Comment by zer0n** [comment]
@minrk, do you know what the issue is? Do you need any extra information to understand the problem? Thanks.

**Comment by willingc** [comment]
@zer0n You might wish to take a look at the example configuration with DockerSpawner in the jupyterhub-deploy-docker repo https://github.com/jupyterhub/jupyterhub-deploy-docker/blob/master/jupyterhub_config.py

**Comment by zer0n** [comment]
It seems like something was wrong with the Docker service. The problem is gone after I did the following
- Stop and remove all containers `docker rm $(docker ps -a -q)`
- Restart JupyterHub

Closing the issue now. However, if someone has insights to what caused Docker failing to [get the port info of a container](https://github.com/jupyterhub/dockerspawner/blob/master/dockerspawner/dockerspawner.py#L458), I would like to know.

**Comment by willingc** [comment]
@zer0n I'm glad that you got it working. Which command were you using to start the docker containers?

**Comment by zer0n** [comment]
@willingc I didn't start the containers manually. I used the JupyterHub interface to start the notebook server, which starts a container under the hood.

**Comment by willingc** [comment]
@zer0n Just to clarify when you started the Hub itself were you running it in a docker container as described here https://github.com/jupyterhub/jupyterhub#docker or were you running the Hub directly on a server/vm instead of a Docker container?

**Comment by zer0n** [comment]
@willingc I ran the Hub directly on the server.

**Comment by willingc** [comment]
@zer0n Great. Thanks. I'll give it a test tomorrow when I'm in the office. If I see the same behavior, I'll reopen. Please do reopen if the behavior happens again. :cake:

**Comment by zer0n** [comment]
@willingc I think I have figured out the cause. Will update this comment in a few minutes/hours.

**Comment by acelere** [comment]
I had the exact same problem as Zer0n described.
Using DockerSpawner, with local user authentication.
After many tries with the following errors:
I 2018-02-16 10:45:08.161 JupyterHub dockerspawner:545] Found existing container 'jupyter-acelere' (id: bd20334)
[I 2018-02-16 10:45:08.162 JupyterHub dockerspawner:557] Starting container 'jupyter-acelere' (id: bd20334)
[E 2018-02-16 10:45:09.956 JupyterHub user:427] Unhandled error starting acelere's server: Failed to get port info for bd20334cd37a52570c5a02eb3bac87e0ddd7a30120619427a30c1928619c004d
[E 2018-02-16 10:45:10.057 JupyterHub web:1591] Uncaught exception GET /hub/user/acelere/ (::ffff:192.168.2.38)

I could get it to work by following what Zer0n suggested:

    Stop and remove all containers docker rm $(docker ps -a -q)
    Restart JupyterHub

Tks.

**Comment by zoltan-fedor** [comment]
I too am having the same issue.
I do use the standard images from docker-stacks - and those work fine, but the custom-created images don't, they throws this error (see https://github.com/jupyterhub/dockerspawner/issues/241).

In my case too, the `EXPOSE 8888` wasn't added first, but now it is and the error is still there.
Removing all containers, dropping the `jupyterhub.sqlite` doesn't solve it.

Creating a brand new image with a different name and `EXPOSE 8888` included from the start still generates the issue, so it can't just be a simple caching problem.

Docker (`docker ps -a`) shows the port 8888 correctly mapped, just like the other containers from docker-stacks.

**Comment by zoltan-fedor** [comment]
I have figured it out.
Basically if the container doesn't start for ANY reason, then this is the error you get (`Failed to get port info`).
Just go and try to start the container manually and you will see the error printed by Docker - errors which are fully independent from this port thingy.

It would be a good idea if dockerspawner would log general startup errors from the container or at least modify this port error message pointing out the possibility that there might be some general issues with the container.
