### ISSUE TITLE
DockerSpawner socket hang up errors when spawning user servers

### ISSUE THREAD

**Issue by Loulybob** [jupyterhub/jupyterhub#760]
I had DockerSpawner working on my local machine (more specifically SystemUserSpawner but DockerSpawner also worked) but when I've been trying to set up on my server I keep getting socket hang up errors even though my config is the same as the stuff that worked on my local machine apart from changing the ip addresses to point to the server's ip instead of my local machine's. I can get Jupyterhub working with the default spawner on my server, it's just DockerSpawner that's not working. I've tried checking various versions of the programs required but the versions match up between my local machine and my server and are all up to date...

I keep getting errors like this when trying to access a user's server:

```
[14:42:53.130 - error: [ConfigProxy] Proxy error:  Error: socket hang up
    at createHangUpError (_http_client.js:202:15)
    at Socket.socketCloseListener (_http_client.js:234:23)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
14:42:53.131 - error: [ConfigProxy] 503 POST /hub/login?next=
[I 2016-09-19 14:48:54.930 JupyterHub log:100] 200 GET /hub/error/503?url=%2Fhub%2Flogin%3Fnext%3D (@xx.xx.xx.xx) 8.63ms
[W 2016-09-19 14:48:58.683 JupyterHub web:1545] 500 POST /hub/login?next= (xx.xx.xx.xx): Spawner failed to start [status=ExitCode=1, Error='', FinishedAt=2016-09-19T13:48:48.864634863Z]
[E 2016-09-19 14:48:58.687 JupyterHub log:99] {
      "Accept-Encoding": "gzip, deflate, br",
      "Content-Type": "application/x-www-form-urlencoded",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0",
      "Referer": "https://127.0.0.1/hub/login",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Connection": "close",
      "Accept-Language": "en-US,en;q=0.5",
      "Upgrade-Insecure-Requests": "1",
      "Host": "127.0.0.1",
      "Content-Length": "36"
    }
[E 2016-09-19 14:48:58.687 JupyterHub log:100] 500 POST /hub/login?next= (@xx.xx.xx.xx) 10311.53ms
[W 2016-09-19 14:49:18.841 JupyterHub user:264] tests's server never showed up at http://127.0.0.1:32790/user/test after 30 seconds. Giving up
[E 2016-09-19 14:49:18.850 JupyterHub gen:878] Exception in Future <tornado.concurrent.Future object at 0x7fa2f3c6d9b0> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 874, in error_callback
        future.result()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/user.py", line 280, in spawn
        raise e
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/user.py", line 256, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/orm.py", line 108, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/utils.py", line 94, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://127.0.0.1:32790/user/test didn't respond in 30 seconds

```

My config file:

```
# Configuration file for jupyterhub.
c = get_config()
c.JupyterHub.authenticator_class = 'jupyterhub.auth.PAMAuthenticator'

c.JupyterHub.spawner_class = 'dockerspawner.SystemUserSpawner'
c.DockerSpawner.container_image = 'jupyter/systemuser'
c.SystemUserSpawner.host_homedir_format_string = '/home/{username}'
c.DockerSpawner.remove_containers = True
c.DockerSpawner.hub_ip_connect = 'xx.xx.xx.xx'
c.DockerSpawner.extra_host_config = {
    'mem_limit': '1024m',
    'pids_limit': 100
}
c.JupyterHub.hub_ip = 'xx.xx.xx.xx'
c.JupyterHub.logo_file='/etc/jupyterhub/logo.png'
c.JupyterHub.data_files_path = '/usr/local/share/jupyter/hub'

c.JupyterHub.ssl_cert = 'mycert.pem'
c.JupyterHub.ssl_key = 'mykey.key'
c.JupyterHub.cookie_secret_file = '/srv/jupyterhub/jupyterhub_cookie_secret'
c.JupyterHub.config_file = '/etc/jupyterhub/jupyterhub_config.py'

c.JupyterHub.port = 443
```

Any help would be greatly appreciated!

**Comment by whitead** [comment]
I've been working a lot with the DockerSpawner lately and I've found that often the errors are in the container and won't show-up in the hub log. You can use `docker ps -a` to see your docker containers and then `docker logs [container-id]` to see the relevant logs. Do you see any errors there?

Another thing to check is the networking. Run `docker exec -u root -it [container-id] bash` to drop to a shell in a container. Make sure you're able to ping your hub_ip.

**Comment by Loulybob** [comment]
Accessing the log I get this error repeated a bunch of times (probably for all the times I've been trying to run it):
```
 () exists
sudo: unrecognized option '--port=8888'
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-u user] file ...
```
Nosying around, I get the same error when using the command `docker run jupyterhub/systemuser`, so I feel as though it's somthing to do with that. I do get this same error when doing `docker run jupyterhub/systemuser` on my local machine but it does not affect jupyterhub's ability to start containers on that machine.

My container stops running pretty much as soon as I run the jupyterhub command so to check the networking I had to commit it as a new image and run it with bash as a new entry point via `docker run -it entrypoint=bash testimage`. This container can ping my server's ip.

**Comment by whitead** [comment]
If you check the web browser console (F12/dev tools/inspect element), is there any more information?

**Comment by Loulybob** [comment]
Not from what I can see. There's nothing in the dev tools console and it is the same html as the login page. It seems like it wants to fetch an error but it's unhandled and so it just hangs and stays on the login page.

**Comment by Loulybob** [comment]
Since it seems to be a problem with the proxy, I've set c.JupyterHub.debug_proxy = True and I've been comparing my successful setup with my unsuccessful one.

When pressing the start my server button, my working machine logs this:

```
[I 2016-09-22 10:22:47.299 JupyterHub dockerspawner:333] Container 'jupyter-test' is gone
[I 2016-09-22 10:22:47.390 JupyterHub dockerspawner:395] Created container 'jupyter-test' (id: f79094a) from image jupyter/systemuser
[I 2016-09-22 10:22:47.390 JupyterHub dockerspawner:405] Starting container 'jupyter-test' (id: f79094a)
[I 2016-09-22 10:22:49.635 JupyterHub base:306] User test server took 2.805 seconds to start
[I 2016-09-22 10:22:49.635 JupyterHub orm:159] Adding user test to proxy /user/test => http://127.0.0.1:32770
10:22:49.643 - debug: [ConfigProxy] POST /user/test user=test, target=http://127.0.0.1:32770
10:22:49.661 - debug: [ConfigProxy] PROXY WEB /user/test to http://127.0.0.1:32770
[I 2016-09-22 10:22:49.686 JupyterHub log:100] 302 GET /hub/user/test (test@xx.xx.xx.xx) 2856.84ms
10:22:49.699 - debug: [ConfigProxy] PROXY WEB /user/test/tree to http://127.0.0.1:32770
[I 2016-09-22 10:22:49.758 JupyterHub log:100] 200 GET /hub/api/authorizations/cookie/jupyter-hub-token-test/[secret] (test@172.17.0.2) 31.75ms

```
Along with proxying some static assets as well.

Meanwhile, my bugged machine logs this:
```
[I 2016-09-22 10:22:45.647 JupyterHub dockerspawner:333] Container 'jupyter-test' is gone
[I 2016-09-22 10:22:45.704 JupyterHub dockerspawner:395] Created container 'jupyter-test' (id: 2b6d598) from image jupyter/systemuser
[I 2016-09-22 10:22:45.704 JupyterHub dockerspawner:405] Starting container 'jupyter-test' (id: 2b6d598)
[I 2016-09-22 10:22:46.878 JupyterHub base:306] User mnf98541 server took 1.541 seconds to start
[I 2016-09-22 10:22:46.878 JupyterHub orm:159] Adding user test to proxy /user/test => http://127.0.0.1:32780
10:22:46.882 - debug: [ConfigProxy] POST /user/test target=http://127.0.0.1:32780, user=test
[I 2016-09-22 10:22:46.890 JupyterHub log:100] 302 GET /hub/user/test (test@xx.xx.xx.xx) 1555.21ms
10:22:47.020 - debug: [ConfigProxy] PROXY WEB /user/test to http://127.0.0.1:32780
10:22:47.028 - debug: [ConfigProxy] PROXY WEB /user/test/tree to http://127.0.0.1:32780
10:22:53.024 - error: [ConfigProxy] Proxy error:  Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketCloseListener (http.js:1522:23)
    at Socket.EventEmitter.emit (events.js:95:17)
    at TCP.close (net.js:466:12)
10:22:53.026 - error: [ConfigProxy] 503 GET /user/test/tree
[I 2016-09-22 10:22:53.038 JupyterHub log:100] 200 GET /hub/error/503?url=%2Fuser%2Ftest%2Ftree (@xx.xx.xx.xx) 6.89ms

```
The only part I can see is different is the ordering. On my working machine it does the 302 GET of /hub/user/test after the proxy proxies /user/test whilst on my server it proxies after the 302 request. I don't know if this is significant though.

Setting all the other debug options to true doesn't illuminate any more differences. Setting both machines to use the default spawner works and both show the same log.

**Comment by minrk** [comment]
In general JuptyerHub doesn't capture the logs of spawners launched with docker or other tools. You probably want to check the logs of the container:

    docker logs jupyter-test

I expect you will see something there that indicates it's not starting correctly.

**Comment by willingc** [comment]
> In general JuptyerHub doesn't capture the logs of spawners launched with docker or other tools. 

Documentation note: check docs on logging for JHub and add there or in the FAQ/Troubleshooting section.

**Comment by Loulybob** [comment]
The docker container logs look relatively benign to me, which is what is confusing me as docker is the problem since it works fine with the default spawner.

```
test@mrcdss01:~$ docker logs jupyter-test
Creating user test (1007)
[I 2016-09-22 12:31:03.736 test notebookapp:1079] Serving notebooks from local directory: /home/test
[I 2016-09-22 12:31:03.736 test notebookapp:1079] 0 active kernels 
[I 2016-09-22 12:31:03.736 test notebookapp:1079] The Jupyter Notebook is running at: http://0.0.0.0:8888/user/test/
[I 2016-09-22 12:31:03.736 test notebookapp:1080] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2016-09-22 12:31:03.831 test log:47] 302 GET /user/test (172.17.0.1) 0.86ms
[I 2016-09-22 12:31:03.848 test log:47] 302 GET /user/test (172.17.0.1) 0.50ms
``` 
This is the exact same log that I find when I run with DockerSpawner on my local machine

**Comment by minrk** [comment]
That looks like docker-networking. Make sure to set `c.JupyterHub.hub_ip` to an IP address that the containers can access. If the Hub is on the host, one option is the docker virtual interface (sometimes called `docker0`)

**Comment by Loulybob** [comment]
I get the same error when I've set `c.JupyterHub.hub_ip` to the same IP as `docker0` and I can successfully ping both `docker0` and my server's actual IP from the spawned container.

**Comment by minrk** [comment]
And you can verify that the "Host" in the logged headers is the hub_ip value that you set and are pinging manually?

**Comment by Loulybob** [comment]
Yes. I just rechecked and `hup_ip` is 172.17.0.1 (docker ip), every reference to host in the docker log is to my 172.17.0.1 and that's the address I can ping.

**Comment by minrk** [comment]
Can you connect to port 8081, e.g. `curl -v http://172.17.0.1:8081`?

**Comment by Loulybob** [comment]
Yes, I can connect via port 8081

```
test@mrcdss01:~$ curl -v http://172.17.0.1:8081
* Rebuilt URL to: http://172.17.0.1:8081/
* Hostname was NOT found in DNS cache
*   Trying 172.17.0.1...
* Connected to 172.17.0.1 (172.17.0.1) port 8081 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 172.17.0.1:8081
> Accept: */*
> 
< HTTP/1.1 302 Found
< Location: /hub
< Content-Type: text/html; charset=UTF-8
< Date: Thu, 22 Sep 2016 15:34:41 GMT
< Content-Length: 0
< Content-Security-Policy: frame-ancestors 'self'; report-uri /hub/security/csp-report
* Server TornadoServer/4.4.1 is not blacklisted
< Server: TornadoServer/4.4.1
< 
* Connection #0 to host 172.17.0.1 left intact
```

**Comment by minrk** [comment]
Then I really cannot explain why `curl` in the same container can make connections to the same ip, address than `requests` in that exact container cannot. That makes no sense to me.

**Comment by willingc** [comment]
@minrk looking back at the logs [here](https://github.com/jupyterhub/jupyterhub/issues/760#issuecomment-248866609), I think that the second system does not have a suitable cookie_secret set while the first system does. Perhaps adding or changing the cookie_secret on the second system would resolve.

**Comment by Loulybob** [comment]
I've tried deleting the cookie secret and letting the hub regenerate one and also creating one myself and in both cases the same problem occurs. As for the container image I've been using `jupyter/systemuser` and I don't believe that would be causing this kind of problem?

**Comment by minrk** [comment]
Can you install and run curl or wget in the container? Or run ping in the container? I'm trying to establish whether the container can connect to the Hub. This is usually due to having the wrong value for hub_ip. You can try other values, as well.

**Comment by Loulybob** [comment]
I can run ping and wget but not curl. Ping works for both the external ip and the docker0 ip. wget hangs when trying to connect the external ip and the docker0 address over the port I'm using. I'm changing hub_ip between my docker0 and eth0 addresses but I can't think of any other ip addresses I can use other than these two as 127.0.0.1 doesn't work period (web browser refuses to connect). I don't have hub_ip_connect anymore because I don't really understand which IP I should be setting that to and it didn't seem to help...

**Comment by minrk** [comment]
What OS/distro and docker version? What do you get from `conda list` or `pip list` on the host?

`hub_ip` tells the hub what IP to listen on. `hub_ip_connect` is only to be used if the ip containers should use to connect is different from `hub_ip` (e.g. fancy virtual network things, or NAT going on, or `hub_ip = '0.0.0.0'`, which is 'all interfaces' when binding, but doesn't tell you how to connect). This is unlikely to be the case for single machine docker, so it's good to leave `hub_ip_connect` out.

**Comment by minrk** [comment]
Are you running your browser on the same machine as the Hub? If so, can you try visiting `http://<hub_ip>:8081/hub/api/`? You should get a reasonable HTTP 403 error page.

**Comment by Loulybob** [comment]
I eventually figured out what was wrong because I found out I couldn't make ANY server (tried a simple python server). Asked my boss about it and it turned out that the machine I was given to test on had a firewall up and no one told me. If anyone in the future has similar problems - check that you don't have a firewall blocking all the ports JupyterHub is trying to use ;)

Thanks for all your help and troubleshooting hints!

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!

**Comment by reinierpost** [comment]
I'm having the same issue right now, with JupyterHub 1.0.0 spun up from docker-compose, using DockerSpawner and the current jupyter/datascience-notebook. It happens when the notebook hasn't been pulled yet and DockerSpawner is configured to pull it. After login, when starting the server, spawning the server times out. It turns out that the pull is happening in the background, and after some 15 minutes, the notebook can be served, but nothing in the interface indicates that this is the case. This should be fixed. I'm happy to create an new issue for this if desired.

For us this is no longer a pressing issue; we just set `c.DockerSpawner.pull_policy = "Never"` and pull the desired image(s) in advance.
