### ISSUE TITLE
Create JupyterLab extension to show hub-related navigation links in lab.

### ISSUE THREAD

**Issue by danielballan** [jupyterhub/jupyterhub#764]
I plan to work on this if no one else gets to it first. It looks like the lab extension system is settling into final form now.

**Comment by willingc** [comment]
Please do! Thanks 👍

**Comment by willingc** [comment]
@minrk FYI...just merged updated docs for [jupyterlab-extension-builder](https://github.com/jupyter/jupyterlab-extension-builder/blob/master/README.md)

**Comment by manics** [comment]
This is built into JupyterLab: https://github.com/jupyterlab/jupyterlab/tree/master/packages/hub-extension
