### ISSUE TITLE
Unhandled error starting server: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by hani1814** [jupyterhub/jupyterhub#770]
I have created a new install of jupyter hub using anaconda3. I have successfully started the server and managed to login. It get the following error after my credentials are verified.

Started hub with
/opt/app/anaconda3/bin/jupyterhub --no-ssl --debug

`[D 2016-09-22 15:50:28.246 JupyterHub application:529] Looking for jupyterhub_config in None
[D 2016-09-22 15:50:28.246 JupyterHub application:549] Loaded config file: /spare/app/anaconda3/jupyterhub_config.py
[I 2016-09-22 15:50:28.249 JupyterHub app:622] Loading cookie_secret from /spare/app/anaconda3/jupyterhub_cookie_secret
[D 2016-09-22 15:50:28.249 JupyterHub app:694] Connecting to db: sqlite:///jupyterhub.sqlite
[W 2016-09-22 15:50:28.279 JupyterHub app:304]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[W 2016-09-22 15:50:28.282 JupyterHub app:757] No admin users, admin interface will be unavailable.
[W 2016-09-22 15:50:28.282 JupyterHub app:758] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2016-09-22 15:50:28.283 JupyterHub app:785] Not using whitelist. Any authenticated user will be allowed.
[D 2016-09-22 15:50:28.291 JupyterHub app:888] Loaded users:
        hani
[I 2016-09-22 15:50:28.298 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
[W 2016-09-22 15:50:28.301 JupyterHub app:959] Running JupyterHub without SSL. There better be SSL termination happening somewhere else...
[I 2016-09-22 15:50:28.301 JupyterHub app:968] Starting proxy @ http://_:9996/
[D 2016-09-22 15:50:28.301 JupyterHub app:969] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '9996', '--api-ip', '127.0.0.1', '--api-port', '9997', '--default-target', 'http://127.0.0.1:8081', '--error-target', 'http://127.0.0.1:8081/hub/error']
15:50:28.429 - info: [ConfigProxy] Proxying http://_:9996 to http://127.0.0.1:8081
15:50:28.433 - info: [ConfigProxy] Proxy API at http://127.0.0.1:9997/api/routes
[D 2016-09-22 15:50:28.505 JupyterHub app:997] Proxy started and appears to be up
[I 2016-09-22 15:50:28.506 JupyterHub app:1254] JupyterHub is now running at http://127.0.0.1:9996/
[I 2016-09-22 15:50:40.493 JupyterHub log:100] 302 GET / (@127.0.0.1) 1.84ms
[I 2016-09-22 15:50:40.721 JupyterHub log:100] 302 GET /hub (@127.0.0.1) 0.43ms
[I 2016-09-22 15:50:40.951 JupyterHub log:100] 302 GET /hub/ (@127.0.0.1) 0.92ms
[I 2016-09-22 15:50:41.206 JupyterHub log:100] 200 GET /hub/login (@127.0.0.1) 28.20ms
[D 2016-09-22 15:50:41.802 JupyterHub log:100] 304 GET /favicon.ico (@127.0.0.1) 5.45ms
[I 2016-09-22 15:50:44.534 JupyterHub spawner:467] Spawning jupyterhub-singleuser --user=hani --port=41157 --cookie-name=jupyter-hub-token-hani --base-url=/user/hani --hub-host= --hub-prefix=/hub/ --hub-api-url=http://127.0.0.1:8081/hub/api --ip=127.0.0.1
[E 2016-09-22 15:50:44.548 JupyterHub user:237] Unhandled error starting hani's server: [Errno 13] Permission denied
[E 2016-09-22 15:50:44.564 JupyterHub web:1524] Uncaught exception POST /hub/login?next= (127.0.0.1)
    HTTPServerRequest(protocol='http', host='XX:9996', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Referer': 'http://XX:9996/hub/login', 'Content-Type': 'application/x-www-form-urlencoded', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8', 'Host': 'XX:9996', 'Content-Length': '27', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.48 Safari/537.36', 'Accept-Encoding': 'gzip,deflate,sdch', 'Connection': 'close', 'Dnt': '1', 'Cache-Control': 'max-age=0', 'Accept-Language': 'en-GB,en-US;q=0.8,en;q=0.6', 'Origin': 'http://XX:9996'})
    Traceback (most recent call last):
      File "/opt/app/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/opt/app/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 79, in post
        yield self.spawn_single_user(user)
      File "/opt/app/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 312, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/opt/app/anaconda3/lib/python3.5/site-packages/jupyterhub/user.py", line 247, in spawn
        raise e
      File "/opt/app/anaconda3/lib/python3.5/site-packages/jupyterhub/user.py", line 228, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/app/anaconda3/lib/python3.5/types.py", line 243, in wrapped
        coro = func(_args, *_kwargs)
      File "/opt/app/anaconda3/lib/python3.5/site-packages/jupyterhub/spawner.py", line 470, in start
        start_new_session=True, # don't forward signals
      File "/opt/app/anaconda3/lib/python3.5/subprocess.py", line 947, in __init__
        restore_signals, start_new_session)
      File "/opt/app/anaconda3/lib/python3.5/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    PermissionError: [Errno 13] Permission denied`

**Comment by hani1814** [comment]
By coincidence I entered 

 export PATH="/opt/app/anaconda3/bin:$PATH"

and it now works

**Comment by willingc** [comment]
@hani1814 Is there a particular reason that this was reopened now?
