### ISSUE TITLE
500 : Internal Server Error (Spawner failed to start)

### ISSUE THREAD

**Issue by olyerickson** [jupyterhub/jupyterhub#772]
Immediately after user login (we're using PAM) we see the following:
```
500 : Internal Server Error
Spawner failed to start [status=1]
```

Based on the documentation, we don't know where even to begin to diagnose the problem. Looking for some basic, fine-grained advice...Thanks!

**Comment by willingc** [comment]
Hi @olyerickson,

This troubleshooting FAQ section may help http://jupyterhub.readthedocs.io/en/latest/troubleshooting.html#error-after-spawning-my-single-user-server

If you could provide some of the information logged when starting JupyterHub with `--debug` that would be helpful. Thanks!

**Comment by olyerickson** [comment]
Our sysadmin fixed by modifying the config file to point to shared places. Added a couple configuration sections to /etc/apache2/sites-enabled/000-default.conf for /jupyter, /hub and /user

**Comment by willingc** [comment]
Great! Thanks for the update @olyerickson. Feel free to ping us with questions in the future, if needed.

**Comment by jacknlliu** [comment]
I got this error from the [jupyterhub docker image](https://hub.docker.com/r/jupyterhub/jupyterhub/), and I followed the [instruction](https://github.com/jupyterhub/jupyterhub#docker) .

I want to know if anyone really tested this docker image usage with step by step.

**Comment by minrk** [comment]
@jacknlliu The `jupyterhub/jupyterhub` image contains only the Hub itself, with no configuration. In general, one needs to make a derivative image, with at least a `jupyterhub_config.py` setting up an Authenticator and/or Spawner.

**Comment by jacknlliu** [comment]
@minrk I followed the [configuration instruction](http://jupyterhub-tutorial.readthedocs.io/en/latest/timeline.html#configuring-jupyterhub), but the docker image still got the error, why not provide a basic default configuration to proof the docker image/jupyterhub could work just like [jupyter-notebook](https://github.com/jupyter/docker-stacks/tree/master/minimal-notebook)?

**Comment by DrSpatula** [comment]
@olyerickson Could you be more specific about what configuration options were added to your Apache conf?
