### ISSUE TITLE
JupyterHub "sees" R and Py3 kernels but can't connect

### ISSUE THREAD

**Issue by olyerickson** [jupyterhub/jupyterhub#773]
After launching the user's notebook server, Jupyter "sees" that the R and Python3 kernels are available (via the drop-down) but times out when trying to connect to the kernel.

**Comment by willingc** [comment]
Which error are you seeing? 500? If you provide part of the debug log, that would be helpful.

I suspect that there are one of two things that may be causing this:

1. the `cookie_secret` key is not valid. This could happen if the hub was changed and restarted. http://jupyterhub.readthedocs.io/en/latest/getting-started.html#cookie-secret If the `cookie_secret` is changed on the hub, all the single user notebook server's need to be restarted.

2. the proxy is not properly configured or a firewall is preventing communication over the web socket.

**Comment by olyerickson** [comment]
We weren't seeing an error _per se_; we saw "Connecting to kernel" in the upper-right of the notebook, to the left of the kernel indicator and the kernel status.  

Our sysadmin fixed it; he said, "The JavaScript was trying to connect to the server using Websockets. Had to add some configuration to allow that to happen. There were some widgets that needed to be installed and enabled as well...."

FWIW, we also have RStudio Server running on this machine and his first attempt to fix the kernel issue messed up RSS. Easily fixed, however. 

There is a lot of support for JupyterHub, but I feel like there needs to be more direction as to which install path people should follow. pip3? Anaconda? Ansible? Docker? VERY confusing.

**Comment by willingc** [comment]
> There is a lot of support for JupyterHub, but I feel like there needs to be more direction as to which install path people should follow. pip3? Anaconda? Ansible? Docker? VERY confusing.

We recognize that there is a lot of variability in both the options that can be set for JupyterHub as well as the environments that it is deployed. We've recently added a few things to help the user:
- reference deployment repos for teaching, hpc, and docker
- tutorial repo that walks a user through deploying a "vanilla" jupyterhub system on bare metal
We are working on a flow chart to guide users through the decisions on configuration as well as some additional reference deployments.

If there is anything specific that you think should be added, either now or in the future, please let us know.

**Comment by jgerardsimcock** [comment]
I was having this problem on an HPC jupyterhub install. It could see my envs and I had a correctly configured ipykernel. While I could launch terminal sessions from jupyter, I was unable to initialize the env in the notebook. It just kept timing out. I realized that I had never installed jupyter in this environment. After installing jupyter it worked immediately.

**Comment by willingc** [comment]
@jgerardsimcock Thanks for the update and I'm glad you got it working. If you have any specific suggestions to improve the experience, please do share. Thanks.
