### ISSUE TITLE
nginx configuration $connection_upgrade variable

### ISSUE THREAD

**Issue by mkgilbert** [jupyterhub/jupyterhub#781]
Going through the nginx reverse proxy configuration using nginx version 1.10.1 (docs/source/config-examples.md), $connection_upgrade throws an error and won't allow nginx to start. If this is variable is changed to the string "upgrade", it starts without issue.

**Comment by willingc** [comment]
@mkgilbert When you look at your nginx config file, do you see the following?

```
map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }
```

See item 6 in the nginx doc https://www.nginx.com/blog/websocket-nginx/

I suspect that this was omitted in the doc you reference as it was a partial listing of the config file focused more on HTTPS and SSL. We should loop back and include the entire file to the docs.

Please let me know if the above resolves your issue. Thanks!

cc/ @minrk

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:

**Comment by Siecje** [comment]
I just ran into this, follow this https://github.com/jupyterhub/jupyterhub/blob/ccb29167dd61a951a0e2fc86772c802fa888e11c/docs/source/reference/config-examples.md. It should use the values instead of the variables which may not exist.

**Comment by dwaltrip** [comment]
I just hit this issue as well, (roughly) following the docs: https://jupyterhub.readthedocs.io/en/stable/reference/config-proxy.html

The error is:
```
Apr 15 20:32:24 ip-172-31-11-135 nginx[24846]: nginx: [emerg] unknown "connection_upgrade" variable
Apr 15 20:32:24 ip-172-31-11-135 nginx[24846]: nginx: configuration file /etc/nginx/nginx.conf test failed
Apr 15 20:32:24 ip-172-31-11-135 systemd[1]: nginx.service: Control process exited, code=exited status=1
Apr 15 20:32:24 ip-172-31-11-135 systemd[1]: nginx.service: Failed with result 'exit-code'.
Apr 15 20:32:24 ip-172-31-11-135 systemd[1]: Failed to start A high performance web server and a reverse proxy server.
```

To solve this issue, I hardcoded `"upgrade"`, instead of using the variable `$connection_upgrade`.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/nginx-reverser-proxy-error-in-configuration-template/3648/1

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/nginx-reverser-proxy-error-in-configuration-template/3648/3

**Comment by nguyenvulong** [comment]
it's still not documented here https://jupyterhub.readthedocs.io/en/stable/installation-guide-hard.html
Also, the link to edit in the readthedocs website above is not correct.

**Comment by jsuag** [comment]
Before de server section add this:

**map $http_upgrade $connection_upgrade {
	default upgrade;
	'' close;
}**

server {...

**Comment by OnlyBelter** [comment]
These 3 lines should be added at the very beginning!
