### ISSUE TITLE
Supervisor can't find proxy

### ISSUE THREAD

**Issue by yourinoelnelson** [jupyterhub/jupyterhub#786]
When I run jupyterhub outside of supervisor it works great but when I use supervisor I get this:

[E 2016-09-28 11:37:16.978 JupyterHub app:976] Failed to find proxy ['configurable-http-proxy']
    The proxy can be installed with `npm install -g configurable-http-proxy`
[I 2016-09-28 11:37:18.965 JupyterHub app:622] Loading cookie_secret from /srv/jupyterhub/cookie_secret
[W 2016-09-28 11:37:19.008 JupyterHub app:304]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[I 2016-09-28 11:37:19.088 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
[I 2016-09-28 11:37:19.094 JupyterHub app:968] Starting proxy @ http://*:443/
[E 2016-09-28 11:37:19.097 JupyterHub app:976] Failed to find proxy ['configurable-http-proxy']
    The proxy can be installed with `npm install -g configurable-http-proxy`
[I 2016-09-28 11:37:21.028 JupyterHub app:622] Loading cookie_secret from /srv/jupyterhub/cookie_secret
[W 2016-09-28 11:37:21.081 JupyterHub app:304]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[I 2016-09-28 11:37:21.171 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
[I 2016-09-28 11:37:21.177 JupyterHub app:968] Starting proxy @ http://*:443/
[E 2016-09-28 11:37:21.180 JupyterHub app:976] Failed to find proxy ['configurable-http-proxy']
    The proxy can be installed with `npm install -g configurable-http-proxy`

Not sure why it's not finding the proxy. thoughts?

**Comment by willingc** [comment]
Hi @yourinoelnelson, Would you mind providing some additional information about how you are configuring and running jupyterhub in your environment?

Are you using [configurable-http-proxy](https://github.com/jupyterhub/configurable-http-proxy) when trying to run with or without supervisor?

cc @minrk for any insights

**Comment by yourinoelnelson** [comment]
I have installed everything following the remote server install that is linked in the wiki. When I run it without supervisor jupyterhub is calling configurable-http-proxy without issue.

My config goes as follow:

```
##LDAP Authenticator - Making the connection to Active Directory
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_address = '10.231.211.5'
c.LDAPAuthenticator.bind_dn_template = 'Domain\\{username}'
c.LDAPAuthenticator.lookup_dn = False
c.LDAPAuthenticator.user_search_base = 'OU=Users,OU=office,DC=Domain,DC=local'
c.LDAPAuthenticator.user_attribute = 'sAMAccountName'
c.LDAPAuthenticator.allowed_groups = []


##Spawner --  Creation of single-use server

c.LocalAuthenticator.create_system_users = True
c.Authenticator.whitelist = {'youri'}
c.Authenticator.admin_users = {'youri'}
c.Spawner.notebook_dir = '~/notebooks'

##Security
c.JupyterHub.cookie_secret_file = '/srv/jupyterhub/cookie_secret'
c.JupyterHub.ssl_cert = '/srv/jupyterhub/ssl.crt'
c.JupyterHub.ssl_key = '/srv/jupyterhub/ssl.key'
c.JupyterHub.port = 443


##Logs
c.JupyterHub.debug_proxy = True
```
JupyterHub is run without docker, straight onto the server. Each user have an account.
I am running it at the root level. 
To me it seems as if supervisor does not load the path to configurable-http-proxy  but why?

**Comment by yourinoelnelson** [comment]
Should I configure the line below for the absolute path?

`c.JupyterHub.proxy_cmd = ['configurable-http-proxy']`

**Comment by yourinoelnelson** [comment]
I tried this:
c.JupyterHub.proxy_cmd = ['/opt/miniconda3/bin/configurable-http-proxy']

And that seemed to take care of the proxy issue but now I have this issue:

I 2016-09-28 13:18:55.063 JupyterHub ldapauthenticator:149] LOGIN SUCCESSFUL!
[I 2016-09-28 13:18:55.129 JupyterHub spawner:467] Spawning jupyterhub-singleuser --user=youri --port=51208 --cookie-name=jupyter-hub-token-youri --base-url=/user/youri --hub-host= --hub-prefix=/hub/ --hub-api-url=http://127.0.0.1:8081/hub/api --ip=$
[E 2016-09-28 13:18:55.184 JupyterHub user:237] Unhandled error starting youri's server: [Errno 2] No such file or directory: 'jupyterhub-singleuser'
[E 2016-09-28 13:18:55.198 JupyterHub web:1524] Uncaught exception POST /hub/login?next= (127.0.0.1)
    HTTPServerRequest(protocol='http', host='jupyterhub.domain.com', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Connection': 'cl$
    Traceback (most recent call last):
      File "/opt/miniconda3/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/opt/miniconda3/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 79, in post
        yield self.spawn_single_user(user)
      File "/opt/miniconda3/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 312, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/opt/miniconda3/lib/python3.5/site-packages/jupyterhub/user.py", line 247, in spawn
        raise e
      File "/opt/miniconda3/lib/python3.5/site-packages/jupyterhub/user.py", line 228, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/miniconda3/lib/python3.5/types.py", line 243, in wrapped
        coro = func(*args, **kwargs)
      File "/opt/miniconda3/lib/python3.5/site-packages/jupyterhub/spawner.py", line 470, in start
        start_new_session=True, # don't forward signals
      File "/opt/miniconda3/lib/python3.5/subprocess.py", line 947, in __init__
        restore_signals, start_new_session)
      File "/opt/miniconda3/lib/python3.5/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'jupyterhub-singleuser'

**Comment by yourinoelnelson** [comment]
I think I narrowed down all these issue to the fact I setup supervisord to get started on reboot and there must be some issue with the PATH being loaded. If I launch supervisord by itself not through the `service supervisord start` cmd it spins up jupyterhub without issue.
I guess the real question is what do I need to do edit in the` /etc/init.d/supervisord` so that it has the correct PATH dependencies? 

`#! /bin/sh
### BEGIN INIT INFO
# Provides:          supervisord
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Author: Dan MacKinlay <danielm@phm.gov.au>
# Based on instructions by Bertrand Mathieu
# http://zebert.blogspot.com/2009/05/installing-django-solr-varnish-and.html

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Description of the service"
NAME=supervisord
DAEMON=/usr/local/bin/supervisord
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
		|| return 1
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
		$DAEMON_ARGS \
		|| return 2
	# Add code here, if necessary, that waits for the process to be ready
	# to handle requests from services started subsequently which depend
	# on this one.  As a last resort, sleep for some time.
}

#
# Function that stops the daemon/service
#
do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
	RETVAL="$?"
	[ "$RETVAL" = 2 ] && return 2
	# Wait for children to finish too if this is a daemon that forks
	# and if the daemon is only ever run from this initscript.
	# If the above conditions are not satisfied then add some other code
	# that waits for the process to drop all resources that could be
	# needed by services started subsequently.  A last resort is to
	# sleep for some time.
	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
	[ "$?" = 2 ] && return 2
	# Many daemons don't delete their pidfiles when they exit.
	rm -f $PIDFILE
	return "$RETVAL"
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
	#
	# If the daemon can reload its configuration without
	# restarting (for example, when it is sent a SIGHUP),
	# then implement that here.
	#
	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
	return 0
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  #reload|force-reload)
	#
	# If do_reload() is not implemented then leave this commented out
	# and leave 'force-reload' as an alias for 'restart'.
	#
	#log_daemon_msg "Reloading $DESC" "$NAME"
	#do_reload
	#log_end_msg $?
	#;;
  restart|force-reload)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
	  	# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

:`

**Comment by minrk** [comment]
Most service tools start with an extremely bare environment by default. For this reason, I often have my supervisor (or other service-launching tool) jupyterhub.conf actually run a `launch.sh`, in which I ensure that a full shell environment is loaded.

You can also set PATH in the environment part of your jupyterhub.conf:

    environment=PATH=/usr/local/bin:/usr/bin:....

**Comment by yourinoelnelson** [comment]
I used your suggestion for the jupyterhub.conf already and it works pretty well. It is just when I try to have supervisor get launched on any system restart, to make sure jupyterhub is always up and running. I think the .init script I used (the one posted above) is somehow not loading the full environment even though if have the  `PATH=/usr/local/bin:/usr/bin:....` as you have mentionned.

**Comment by minrk** [comment]
There's a PATH in your init.d/supervisord, which you can edit. But if you set the PATH in the jupyterhub.conf, it should take precedence over anything inherited from supervisor.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!

**Comment by AvivBes** [comment]
Very important article for online user. Advert networks use Luminati to anonymously view their advertisers' touchdown pages to make sure they do not comprise malware, or improper promoting.luminati is the biggest proxy community on the planet that is present <a href="https://luminati.io/">proxy service</a>, shared proxy,residential proxy extra then 223 Сountries,26,846 Cities. If advert networks used a daily server primarily based popular  shared proxy community, the malicious advertiser would know he is being checked, and will cloak them with a special message.One easy interface to entry Luminati's Residential IP community, Datacenter Shared Proxies, Non-public Proxies, and Cell proxy community.Retailers worth their merchandise algorithmically relative to competitor’s pricing.I know about set default proxy enable the code is <defaultProxy enabled="true"They use the Luminati proxy to scrape this information with out being blocked or deceived.Advert networks use Luminati to anonymously view their advertisers' touchdown pages to make sure they do not comprise malware, or improper promoting. If advert networks used a daily server primarily based popular community, the malicious advertiser would know he is being checked, and will cloak them with a special message.
