### ISSUE TITLE
No module named pyspark

### ISSUE THREAD

**Issue by hani1814** [jupyterhub/jupyterhub#787]
I''ve done a fresh install of jupyterhub only to notice that spark-kernel has been replaced by toree. I've hit an issue with submitting jobs and would be grateful if you could assist

`When I run the code, I get the following error

Error from python worker:
  /usr/local/bin/python2.7: No module named pyspark

the kernel is set-up as follows:

{
  "language": "python",
  "display_name": "Apache Toree - PySpark",
  "env": {
    "**TOREE_SPARK_OPTS**": " --master yarn",
    "SPARK_HOME": "/usr/hdp/2.4.2.0-258/spark",
    "**TOREE_OPTS**": "",
    "DEFAULT_INTERPRETER": "PySpark",
    "PYTHONPATH": "/usr/hdp/2.4.2.0-258/spark/python:/usr/hdp/2.4.2.0-258/spark/python/lib/py4j-0.9-src.zip",
    "PYTHON_EXEC": "python",
 "PYTHONSTARTUP": "/usr/hdp/2.4.2.0-258/spark/python/pyspark/shell.py",
 "PYSPARK_PYTHON": "/usr/local/bin/python2.7",
       "PYSPARK_DRIVER_PYTHON": "/usr/local/bin/python2.7"

  },
  "argv": [
    "/usr/local/share/jupyter/kernels/apache_toree_pyspark/bin/run.sh",
    "--profile",
    "{connection_file}"
  ]
}
`

**Comment by minrk** [comment]
You might check on your system where pyspark has been installed, and make sure that's on the PYTHONPATH env in the kernelspec. This should probably happen as part of the toree installation, but it's possible that the underlying spark has been upgraded/changed.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
