### ISSUE TITLE
Jupyter and Kerberos Cluster

### ISSUE THREAD

**Issue by hani1814** [jupyterhub/jupyterhub#792]
Hi,

I've got a kerborised hadoop cluster that requires a kerberos ticket to run jobs. 

-Does jupyter support kerberos authentication and passing on tickets to the cluster?

-Alternatively, we can have a proxy kerberorised account that can impersonate users on the cluster with some form of whitelist

Look forward to your feedback

Hani

**Comment by willingc** [comment]
Hi @hani1814,

In issue https://github.com/jupyterhub/jupyterhub/issues/681, @steverweber did quite a bit of work this summer on kerberos. You may wish to follow the progress https://github.com/jupyterhub/jupyterhub/issues/681#issuecomment-251697186

You may also ask on the jupyter mailing list for others that may have implemented something similar to what you are looking for. Thanks!

**Comment by parente** [comment]
I'm trying to put together an educational docker setup with KDC, JupyterHub host, and (hopefully, a bit later on) YARN/Spark master containers to see what problems are encountered end-to-end with JupyterHub and Kerberos. I'll post a link here once there's an initial repo with the sample. #856 is one issue I've found so far.

**Comment by willingc** [comment]
There is now a https://github.com/jupyterhub/jupyterhub-example-kerberos repo. Thanks @parente. I'm going to close this issue.
