### ISSUE TITLE
raise KeyError("User %s does not exist." % user.name)

### ISSUE THREAD

**Issue by vhp1360** [jupyterhub/jupyterhub#795]
Hi developers,
i encountered very confusable error, i tried to create jupyterhub.service but after start , it return

>raise KeyError("User %s does not exist." % user.name)

the complete messages are:

>● jupyterhub.service - Jupyterhub
   Loaded: loaded (/usr/lib/systemd/system/jupyterhub.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2016-10-05 17:39:28 IRST; 5s ago
  Process: 1538 ExecStart=/usr/bin/jupyterhub --JupyterHub.spawner_class=sudospawner.SudoSpawner (code=exited, status=1/FAILURE)
 Main PID: 1538 (code=exited, status=1/FAILURE)
>
Oct 05 17:39:28 cloud.shomara jupyterhub[1538]: File "/usr/lib/python3.4/site-packages/jupyterhub/app.py", line 1102, in initialize
Oct 05 17:39:28 cloud.shomara jupyterhub[1538]: yield self.init_users()
Oct 05 17:39:28 cloud.shomara jupyterhub[1538]: File "/usr/lib/python3.4/site-packages/jupyterhub/app.py", line 803, in init_users
Oct 05 17:39:28 cloud.shomara jupyterhub[1538]: yield gen.maybe_future(self.authenticator.add_user(user))
Oct 05 17:39:28 cloud.shomara jupyterhub[1538]: File "/usr/lib/python3.4/site-packages/jupyterhub/auth.py", line 328, in add_user
Oct 05 17:39:28 cloud.shomara jupyterhub[1538]: raise KeyError("User %s does not exist." % user.name)
Oct 05 17:39:28 cloud.shomara jupyterhub[1538]: KeyError: 'User t does not exist.'
Oct 05 17:39:28 cloud.shomara systemd[1]: jupyterhub.service: main process exited, code=exited, status=1/FAILURE
Oct 05 17:39:28 cloud.shomara systemd[1]: Unit jupyterhub.service entered failed state.
Oct 05 17:39:28 cloud.shomara systemd[1]: jupyterhub.service failed.

and more , my /usr/lib/systemd/system/jupyterhub.service file is:
```
[Unit]
Description=Jupyterhub
After=network-online.target

[Service]
User=jupyterhub
Group=jupyterhub
ExecStart=/usr/bin/jupyterhub --JupyterHub.spawner_class=sudospawner.SudoSpawner
WorkingDirectory=/etc/jupyterhub

[Install]
WantedBy=multi-user.target

```
and there is not any *t* user
I'm wondering if any one guide me.
Thanks

**Comment by amuthuku** [comment]
I am facing same problem.. thinking of using fresh jupyterhub_oreo file

**Comment by zeronicyber** [comment]
1. Delete the jupyterhub.sqlite file and have it blank.. (vi jupyterhub.sqlite -> wq!)
2. Run the configurablae http proxy scripts
3. Invoke jupyetrhub now.

Problem is , you might have copied or retained existing jupyterhub.sqlite file that has user entry which is not available in new environment. Hence when you start with blank sqlite , will build the user list and state of hub...  Let me know if it helped your issue.

**Comment by dacresni** [comment]
what "configurable http proxy scripts" ?
