### ISSUE TITLE
case insensetive

### ISSUE THREAD

**Issue by vhp1360** [jupyterhub/jupyterhub#796]
Hi developers,
there is a bug,
i defined *Test* user and add it in jupyterhub_config.py file like `c.Authenticator.whitelist = {'Test'}` but when i tried to run `/usr/bin/jupyterhub -f /etc/jupyterhub/jupyterhub_config.py --debug` it raised below:

>[D 2016-10-05 19:38:38.104 JupyterHub application:555] Looking for /etc/jupyterhub/jupyterhub_config in /etc/jupyterhub
[D 2016-10-05 19:38:38.105 JupyterHub application:577] Loaded config file: /etc/jupyterhub/jupyterhub_config.py
[I 2016-10-05 19:38:38.108 JupyterHub app:622] Loading cookie_secret from /etc/jupyterhub/jupyterhub_cookie_secret
[D 2016-10-05 19:38:38.108 JupyterHub app:694] Connecting to db: sqlite:///jupyterhub.sqlite
[W 2016-10-05 19:38:38.143 JupyterHub app:304] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
>    
[E 2016-10-05 19:38:38.158 JupyterHub app:1296]
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/jupyterhub/app.py", line 1293, in launch_instance_async
        yield self.initialize(argv)
      File "/usr/lib/python3.4/site-packages/jupyterhub/app.py", line 1102, in initialize
        yield self.init_users()
      File "/usr/lib/python3.4/site-packages/jupyterhub/app.py", line 803, in init_users
        yield gen.maybe_future(self.authenticator.add_user(user))
      File "/usr/lib/python3.4/site-packages/jupyterhub/auth.py", line 328, in add_user
        raise KeyError("User %s does not exist." % user.name)
    KeyError: 'User test does not exist.'

Thanks.

**Comment by minrk** [comment]
I think username normalization is not being applied consistently. I'll have to double-check. Are you running master or 0.6.1?

**Comment by vhp1360** [comment]
sorry for late,
unfortunately could not understand what did you write, but as you see in last line , python generate 
> KeyError: 'User test does not exist.'
message as there was not 'test' user. i created 'Test' user.
