### ISSUE TITLE
R plots not showing up

### ISSUE THREAD

**Issue by iagomez** [jupyterhub/jupyterhub#800]
I'll prefix this description by saying thank you! The works you guys have done is awesome!

This is most likely just a question, but after days on google I have not been able to figure it out. The question is simple, graphs generated with R code are not being displayed in the notebook

**This is my setup**
* OS: RHEL 7
* python --version: Python 3.5.2 :: Anaconda 4.1.1 (64-bit) 
* jupyterhub --version: 0.6.1

If I launch `jupyter notebook`, the following code generates a barplot as expected:
![image](https://cloud.githubusercontent.com/assets/2080150/19160752/165ed848-8bbf-11e6-96bc-73f1f72fe227.png)

But if I access the same notebook through jupyterhub I see the following:
![image](https://cloud.githubusercontent.com/assets/2080150/19160826/512ceee2-8bbf-11e6-9be4-beea322ad826.png)

I can see `Rplots.pdf` files being created in my home directory the following lines in the console, but the images do not show up in the notebook.
```
dev.new(): using pdf(file="Rplots9.pdf")
dev.new(): using pdf(file="Rplots10.pdf")
```

Any help is greatly appreciated

**Comment by willingc** [comment]
@iagomez You are very welcome :smile: Thank you for sending a very kind and thoughtful issue report!

Let's see if we can get this sorted out for you. Pinging @takluyver @minrk since I haven't seen this behavior and perhaps they have some ideas on the root cause.

**Comment by iagomez** [comment]
Thanks @willingc!

Here is also my `R.Version()` in case it helps:

```perl
$platform
'x86_64-pc-linux-gnu'
$arch
'x86_64'
$os
'linux-gnu'
$system
'x86_64, linux-gnu'
$status
''
$major
'3'
$minor
'3.1'
$year
'2016'
$month
'06'
$day
'21'
$`svn rev`
'70800'
$language
'R'
$version.string
'R version 3.3.1 (2016-06-21)'
$nickname
'Bug in Your Hair'
``` 

I compared the output of `options()` in both notebooks and they are identical.

**Comment by takluyver** [comment]
Is your IRkernel installation up to date.

Pinging @flying-sheep too - another plotting issue :-(

**Comment by iagomez** [comment]
I just updated the irkernel and now it really broke :(

```
conda update r-irkernel
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /gpfs/grid/anaconda/python3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    r-irdisplay-0.4.3          |         r3.3.1_2          27 KB  r
    r-memoise-1.0.0            |         r3.3.1_0          23 KB  r
    r-crayon-1.3.1             |         r3.3.1_0         599 KB  r
    r-irkernel-0.7             |         r3.3.1_2         109 KB  r
    ------------------------------------------------------------
                                           Total:         758 KB

The following NEW packages will be INSTALLED:

    r-crayon:    1.3.1-r3.3.1_0 r
    r-memoise:   1.0.0-r3.3.1_0 r

The following packages will be UPDATED:

    conda:       4.1.11-py35_0    --> 4.2.9-py35_0
    conda-env:   2.5.2-py35_0     --> 2.6.0-0
    r-irdisplay: 0.3-r3.3.1_2   r --> 0.4.3-r3.3.1_2 r
    r-irkernel:  0.7-r3.3.1_0   r --> 0.7-r3.3.1_2   r
```

Running R code in `jupyter notebook` still works, but running any code (`cat("Hello world")`) from jupyterhub results in the following banner:
![image](https://cloud.githubusercontent.com/assets/2080150/19163239/3621a0a2-8bc9-11e6-9392-87ca7c387559.png)

And these messages now show up in the console:
```
[I 2016-10-06 13:27:20.326 igomez multikernelmanager:198] Kernel restarted: 602d1778-cbe8-4399-bff7-450d2dd18c8f
Error in .External2(C_X11, paste("png::", filename, sep = ""), g$width,  :
  unable to start device PNG
Calls: <Anonymous> ... evaluate -> dev.new -> do.call -> <Anonymous> -> ok_device
In addition: Warning message:
In ok_device(filename, ...) : unable to open connection to X11 display ''
Execution halted
```

I can see that the process running jupyterhub has DISPLAY set:
```
$ sudo ps -ef | grep '[j]upyterhub --no-ssl'
igomez   28904 28369  0 13:23 pts/1    00:00:00 /python3/bin/python /python3/bin/jupyterhub --no-ssl
$ sudo cat /proc/28904/environ | tr '\0' "\n" | grep DISPLAY
DISPLAY=10.102.10.160:13.0
```

However, this variable is not set for the processes running the singleuser notebook or the IRKernel.
The error message I'm seeing is the same as https://github.com/IRkernel/IRkernel/issues/388 so let me go down that rabbit hole and get back to you.

Also, if it matters, I'm running jupyterhub on a headless server

**Comment by ianabc** [comment]
I think this might be https://github.com/jupyter/docker-stacks/issues/210

**Comment by willingc** [comment]
Perhaps installing from conda-forge might be a good option:

```
conda uninstall r-irkernel
conda install r-ikernel -c conda-forge
```

where `-c conda-forge` just indicates to pull the package from conda-forge instead of Anaconda.

**Comment by ianabc** [comment]
@iagomez I just realized that you didn't say you were running from docker-stacks. As @willingc says you might have better luck with conda-forge or you can try pinning the r-base version to "r-base=3.3.1 1" that seems to have fixed it in the docker images (https://github.com/jupyter/docker-stacks/commit/54552d36cf0a4b06b6466b6ad4fbb167161e7a29).

**Comment by iagomez** [comment]
@ianabc Right, I'm not running from docker-stacks. 
I'm going to try those 2 options as soon as I can connect to my server again and I'll let you know (not on the network right now).

**Comment by willingc** [comment]
@iagomez Well, in a bit of further investigation, conda-forge does not appear to have the r kernel :(

I did go ahead and try this install instruction from Anaconda:

```
conda install -c r r-irkernel=0.7
```

On OS X, this installs the following:

<img width="566" alt="screen shot 2016-10-07 at 06 49 49" src="https://cloud.githubusercontent.com/assets/2680980/19192215/637e165c-8c5a-11e6-9b93-b03cc1a3229d.png">

**Comment by ianabc** [comment]
Just for reference, this seems to be the right issue in anaconda: https://github.com/ContinuumIO/anaconda-issues/issues/1063

Following along with some of the they do in that issue, you can check which version of r-base you're running with `conda list r-base`. The build is in the third column and 3.3.1 build 3 seems to be broken, which you can confirm by running `R -e 'capabilities()'`
```
$ conda install --quiet -c r "r-base=3.3.1 1"

$ conda list r-base
# packages in environment at /home/iana/miniconda3/envs/cairobug:
#
r-base                    3.3.1                         3    r

$ R --quiet -e 'capabilities()'
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
      FALSE       FALSE       FALSE        TRUE       FALSE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE       FALSE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE        TRUE       FALSE        TRUE        TRUE        TRUE 
```
Looking at the values under CAIRO, it's FALSE so you won't see any graphics output.

The last known good build for r-base seems to be 3.3.1 build 1, which you can force with
```
$ conda install --quiet -c r "r-base=3.3.1 1"

$ conda list r-base
# packages in environment at /home/iana/miniconda3/envs/cairobug:
#
r-base                    3.3.1                         1    r

$ R --quiet -e 'capabilities()'
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
       TRUE        TRUE        TRUE        TRUE       FALSE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE       FALSE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE       FALSE        TRUE        TRUE        TRUE        TRUE 
```
With that I get the graphics capability back for my R plots.

**Comment by iagomez** [comment]
![image](https://lifeconfusions.files.wordpress.com/2014/09/super-excited.gif)

Installing `r-base=3.3.1 1` fixed it. I don't think seen a barplot has ever made me happier.
Sorry I posted the question in the wrong project. With so many layers it's hard to figure out where to ask. 

Thank you so much for your help @everyone. I really appreciate your time and effort!

Have a great weekend!

**Comment by iagomez** [comment]
I'm closing this issue now. Thanks again!

**Comment by takluyver** [comment]
Thanks @iagomez , glad you got it working.

**Comment by willingc** [comment]
Excellent! Great help @ianabc :-)
