### ISSUE TITLE
Initial Login, Home directory creation

### ISSUE THREAD

**Issue by techzilla** [jupyterhub/jupyterhub#806]
Is their any reason the initial user dir creation doesn't work?  It appears you must login the box via SSH, the system would then autocreate your home directory, then you can get jupyterhub to issue the user a notebook.

**Comment by willingc** [comment]
Hi @techzilla,

I'm not quite sure from your description what "initial user dir creation" means. Please provide a bit more context on what you have set up: os, versions, etc. You may also run `jupyterhub --debug` for additional information when running JupyterHub. Thanks.

**Comment by yuvipanda** [comment]
https://github.com/wikimedia/operations-puppet/blob/production/modules/jupyterhub/files/jupyterhub_config.py#L57 is what we use at wikimedia's private installation for something similar.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
