### ISSUE TITLE
Generate config file with a path produces error

### ISSUE THREAD

**Issue by willingc** [jupyterhub/jupyterhub#812]
`jupyterhub --generate-config -f /etc/jupyterhub/jupyterhub_config.py` produces the following error.

<img width="753" alt="screen shot 2016-10-12 at 22 34 56" src="https://cloud.githubusercontent.com/assets/2680980/19337689/2d05ef52-90cc-11e6-9700-b81deb7071c5.png">

Looking at the tests, it seems as if we are only testing the filename not the path+filename.

The docstring seems to indicate that the above command is valid:

<img width="790" alt="screen shot 2016-10-12 at 22 42 11" src="https://cloud.githubusercontent.com/assets/2680980/19337839/6a96207a-90cd-11e6-9821-c568b30e52e7.png">

**Comment by minrk** [comment]
Does `/etc/jupyterhub` exist? This is an error you get when trying to create a file in a directory that is not present.

**Comment by willingc** [comment]
Ahh...got it. Works when directory is present. Opened a PR to emit a more helpful error message.

**Comment by robmarkcole** [comment]
Just got this error with jupyterhub==0.8.1

**Comment by willingc** [comment]
@robmarkcole Would you open a new issue with a bit more detail? Thanks!

**Comment by robmarkcole** [comment]
MacOS High Sierra 10.13.3
jupyterhub --version 0.8.1
```
Robins-MacBook-Air:~ robincole$ jupyterhub
Start a multi-user Jupyter Notebook server
.
.
.
[C 2018-03-01 09:10:57.653 JupyterHub application:90] Bad config encountered during initialization:
[C 2018-03-01 09:10:57.653 JupyterHub application:91] The 'authenticator_class' trait of <jupyterhub.app.JupyterHub object at 0x105b82320> instance must be a type, but 'dummyauthenticator.DummyAuthenticator' could not be imported
Robins-MacBook-Air:~ robincole$ jupyterhub --generate-config -f /etc/jupyterhub/jupyterhub_config.py
/etc/jupyterhub does not exist. The destination directory must exist before generating config file.
```
I would expect ```/etc/jupyterhub/``` to be created, or should I create manually?

**Comment by willingc** [comment]
Yes, you will need to create the directory `/etc/jupyterhub` manually.

**Comment by robmarkcole** [comment]
Thanks @willingc have created in the user home but still get the error (`/Users/robincole/etc`)..
I note that I have a link to an `etc` dir in private below:

![image](https://user-images.githubusercontent.com/11855322/36857140-a9d00a1e-1d6f-11e8-9b47-33b402edf795.png)

**Comment by willingc** [comment]
Typically, /etc will be at the root of the entire filesystem instead of within a user's home directory.
