### ISSUE TITLE
Jupyterhub cant initialize R in Jupyter

### ISSUE THREAD

**Issue by Lawiet** [jupyterhub/jupyterhub#814]
Good day!

I tried initialize jupyter with jupyterhub in SuSE 11 but trow this exeption
![image](https://cloud.githubusercontent.com/assets/11633133/19355779/8da04d22-9139-11e6-881c-0786ffee33d0.png)

I researched the error is generated by not initialize X11 but he put the "xvfb" command and remains the same

**Comment by minrk** [comment]
Hm, it is a bit strange that X11 is being loaded immediately. Is this happening *immediately*, or is it happening only when you run certain commands? The most likely thing I can think of is loading a library that expects X, e.g. `import matplotlib.pyplot`. If it's matplotlib, you may need to do:

    %matplotlib inline

before importing matplotlib, to ensure that a GUI backend that needs windows isn't selected.

**Comment by Lawiet** [comment]
This Jupyter with jupyter
![image](https://cloud.githubusercontent.com/assets/11633133/19386911/1601be48-91e5-11e6-8b19-da47825944b4.png)

and this in R 

![image](https://cloud.githubusercontent.com/assets/11633133/19386987/62495e5a-91e5-11e6-9d83-dc9a66a5295a.png)

**Comment by minrk** [comment]
Oops, I missed the R part. @takluyver do you know how to avoid R trying to connect to an X display?

**Comment by takluyver** [comment]
*Sigh*, that's been a recurring problem. The plotting device can work in different ways, some of which need an X display and some of which don't. Unfortunately, R sometimes seems to lie about its capabilities, leading us to believe it can do things that it can't. @flying-sheep understands this stuff better than me.

**Comment by flying-sheep** [comment]
anaconda ships a broken R ATM. downgrading to 3.3.1-1 works. ContinuumIO/anaconda-issues#1063

**Comment by takluyver** [comment]
Thanks Philipp :-)

**Comment by Lawiet** [comment]
@flying-sheep this version is running but throw error

![image](https://cloud.githubusercontent.com/assets/11633133/19390250/410a1634-91f5-11e6-9341-9d5b40941767.png)

In Suse 11.4 i have not found how to install the package cairo

![image](https://cloud.githubusercontent.com/assets/11633133/19390651/01bd4ee0-91f7-11e6-9438-f05d42ed8cd6.png)

**Comment by Lawiet** [comment]
Thank the solution:
Install 
conda install --quiet -c r r=3.3.1
conda install --quiet -c r r-cairo

but that action uninstall the package ROracle

**Comment by flying-sheep** [comment]
3.3.1 isnt necessarilay 3.3.1-1!

**Comment by willingc** [comment]
Thanks @flying-sheep and others for helping with @Lawiet's R issue. I'm going to go ahead and close this issue as I think it's **resolved by R version 3.3.1-1**.
