### ISSUE TITLE
Remove "Writing a Custom Authenticator" title

### ISSUE THREAD

**Issue by willingc** [jupyterhub/jupyterhub#821]
In http://jupyterhub.readthedocs.io/en/latest/authenticators.html, the heading exists with no content. Please remove.

**Comment by willingc** [comment]
Correction: Add a sentence and a link to tutorial http://jupyterhub-tutorial.readthedocs.io/en/latest/authenticators.html

**Comment by Scrypy** [comment]
Looking to solve this one. The `spawners.md` doc still needs a period. Should I fix both files and then do one commit for each one of them in a single pull request? Something like:
`git add docs/source/spawners.md`
`git commit -m "Updated spawners docs"`
`git add docs/source/authenticators.md`
`git commit -m "Updated authenticators docs"`
Or just one commit for both of them?

**Comment by willingc** [comment]
@Scrypy Which ever you feel most confident with is fine with me. The method that you have written here is fine. Thanks.

**Comment by Scrypy** [comment]
I just realized @kwkerstein started a PR before me on this issue. Sorry about that!

**Comment by willingc** [comment]
@kwkerstein If you want to pair on a different issue, please let me know.
