### ISSUE TITLE
An active Jupyterhub session locks Postgres tables from writes.

### ISSUE THREAD

**Issue by ssanderson** [jupyterhub/jupyterhub#84]
Noticed while testing permissions issues on #83.  It looks like maintaining a single open session for the entire lifetime of the App results in transactions never being closed, which causes Postgres to write-lock any tables being used by Jupyterhub.  From reading the SQLAlchemy docs, it looks like the expected pattern for webapps is to create a `Session` class at global scope, but create and tear down instances of the session on each request.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/confusion-of-the-db-instance/3878/4
