### ISSUE TITLE
Functional Changes: Copy Folder

### ISSUE THREAD

**Issue by mrinmoyprasad** [jupyterhub/jupyterhub#841]
Hi,

I need some help understanding the front end for JupyterHub. I would like to add 'Copy Folder' button that will copy an entire folder (with its contents) on the same user notebook directory. I am running JupyterHub as a container and I am using Dockerspawner for spawning single user notebook servers.

I tried to change a html file in /share/jupyter/hub/ by building the image for JupyterHub. But the changes were not reflected when I ran JupyterHub as a docker container again. The files I had changed were rewritten to defaults again.

Can someone throw light on this? Also, if I can get some direction in implementing 'Copy Folder' functionality.

Thanks
Mrinmoy

**Comment by minrk** [comment]
This wouldn't be a JupyterHub feature. Once you are looking at your notebook server, JupyterHub is no longer involved (almost), it's all the single-user notebook server at https://github.com/jupyter/notebook. That's where you will want to do you work. You will also need to add server-side functionality to support copying folders in the ContentsManager, which is the class representing file management.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
