### ISSUE TITLE
Add info on db backends and how to use them to docs

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#845]
someone was asking about this on Gitter today. This info is scattered in the sqlalchemy docs and rest of the web (for example, you must set pool_recycle for mysql). Let's collect it in a doc!

**Comment by minrk** [comment]
+ 💯

**Comment by yuvipanda** [comment]
For MySQL, I know you need to use the pymysql sqlalchemy provider (the other one, MySQLdb, isn't available for py3). You also need to set pool_recycle to some value depending on your mysql setup (60 - 300 is a decent sane guess) - mysql kills connections serverside if they've been idle for a while, and the connection from the hub will be idle for longer than most. This will lead to frustrating 'the connection has gone away' errors from sqlalchemy, if we don't set pool_recycle.

I haven't touched postgres tho.

We should also tell people to not put the sqlite db on NFS :)
