### ISSUE TITLE
Make JUPYTERHUB_URL available to services

### ISSUE THREAD

**Issue by parente** [jupyterhub/jupyterhub#846]
In https://github.com/jupyter/nbviewer/pull/639, I'd like to redirect unauthenticated users to the hub login page when they try to access a service. At present, the public facing URL is not made available to services in an env var (unless I missed it.)

**Comment by willingc** [comment]
Is this what you are looking for: 

https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/services/auth.py#L96

or specifically an env var?

**Comment by parente** [comment]
Hmm, maybe. How does that traitlet get set properly for a service to use?

**Comment by parente** [comment]
Duh. Nevermind. The login path is all that is needed when a user is visiting the service via the hub-proxied path. I was testing a service at its unproxied, direct URL and wondering how I could get it to route to hub login. Buts that's a degenerate case.
