### ISSUE TITLE
Allow alternate implementations of proxy at the JupyterHub level

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#848]
Currently, implementing an alternate proxy requires the following things to happen:

1. Mirror the [Swagger Spec](https://github.com/jupyterhub/configurable-http-proxy/blob/master/doc/rest-api.yml) in the new proxy
2. Mirror the commandline params of CHP (so JupyterHub can start the proxy when it is managing it).

This also requires that the new proxy keeps up with all the changes to CHP, which isn't ideal.

What I'd like instead is a way to specify a proxy class, similar to what we have for authenticators / spawners. The proxy class would have a python API that it'll need to implement, and we'll provide a default implementation that talks to the CHP API.

Things this would enable:
1. Much easier integration with nchp
2. Integration with things like Kubernetes' [Ingress API](http://kubernetes.io/docs/user-guide/ingress/)
3. Maybe a default Tornado based proxy

I'd like the new spec to *not* include last_modified_since tracking proxy-side.

**Comment by yuvipanda** [comment]
API for this class could be:

```python
add_route(url_prefix, target)
fetch_all_routes() -> return a dict of (url_prefix -> target)
add_routes(dict) -> add a mass set of routes from a dictionary of url_prefixes to targets
delete_route(url_prefix)
```

That's it, I guess? Do we need to support arbitrary payloads to be associated with each route?

**Comment by yuvipanda** [comment]
We decided to add an opaque JSONable dict that must be associated with each route.

**Comment by barrachri** [comment]
there is a way to disable the proxy in Jupyterhub ?

like overwriting the proxy_cmd ?

**Comment by minrk** [comment]
You cannot disable the proxy. JupyterHub does not work at all without a proxy.

**Comment by barrachri** [comment]
I would use a proxy but not one controlled by JupyterHub.
It will be an external service with the same API of http-proxy.

Like this: https://github.com/yuvipanda/jupyterhub-nginx-chp

**Comment by minrk** [comment]
Ah. Then start the proxy outside JupyterHub and tell JupyterHub where it is. The Hub will only start the proxy if it's not already running. If you start the proxy with the default ports, you don't need to tell the Hub anything.

**Comment by barrachri** [comment]
the proxy will be nginx running inside docker.
I will give only the address of the api to JupyterHub.

`# Proxy is not controlled by JupyterHub
c.JupyterHub.proxy_cmd = ''`

**Comment by minrk** [comment]
This works now via the Proxy API!

You can now cross it out on your slide, @ryanlovett
