### ISSUE TITLE
Add support for writing EnvironmentFile for service API discovery

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#849]
JupyterHub services require a bunch of environment variables to be able to communicate back with the Hub API. When the hub manages the services, it passes these in via environment variables. For externally managed services, this is a little more difficult - and requires some amount of external secret management. 

If we instead have JupyterHub write out an [EnvironmentFile](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile=), these could be read by other services (systemd or not) to be able to access the Hub's API. This makes it much easier for services to start. This is also the setup used by services like [Flannel](https://github.com/coreos/flannel) and works out quite well.

**Comment by manics** [comment]
Shall we close this?
