### ISSUE TITLE
Setup a pylintrc for CI checks

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#851]
Setting a pylintrc that does error checks rather than style checks would be really useful. I've been doing it for kubespawner and it's really nice and helped me find a bunch of bugs.

Only style enforcement I might like is docstring enforcement :D

**Comment by yuvipanda** [comment]
I'd like to have something like https://github.com/ipython/ipynb/blob/master/.pylintrc in here. It would require that we fix all the errors listed, which mostly means writing a ton of docstrings. I might take a stab at it.

**Comment by manics** [comment]
We've got [pre-commit with multiple hooks](https://github.com/jupyterhub/jupyterhub/blob/c3ca924ba896bf2da40cab29e2a08784850a945b/.pre-commit-config.yaml).
