### ISSUE TITLE
can not spawn server if logged in via Google OAuth

### ISSUE THREAD

**Issue by otzy** [jupyterhub/jupyterhub#853]
Hi, thanks for the great software.

I faced a small issue trying to start server after being authenticated via Google OAuth.
Apparently jupyterhub needs user's home directory and since it does not exist, exception is thrown.

So I had to add new user to OS with the the same name as email address at google. Now I'm able to start server but for every jupyter user I have to add OS user.

This the error from console:

    Traceback (most recent call last):
      File "/var/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 1469, in _execute
        result = yield result
      File "/var/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 494, in get
        yield self.spawn_single_user(current_user)
      File "/var/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 312, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/var/anaconda3/lib/python3.5/site-packages/jupyterhub/user.py", line 247, in spawn
        raise e
      File "/var/anaconda3/lib/python3.5/site-packages/jupyterhub/user.py", line 228, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/var/anaconda3/lib/python3.5/types.py", line 243, in wrapped
        coro = func(*args, **kwargs)
      File "/var/anaconda3/lib/python3.5/site-packages/jupyterhub/spawner.py", line 462, in start
        env = self.get_env()
      File "/var/anaconda3/lib/python3.5/site-packages/jupyterhub/spawner.py", line 452, in get_env
        env = self.user_env(env)
      File "/var/anaconda3/lib/python3.5/site-packages/jupyterhub/spawner.py", line 439, in user_env
        home = pwd.getpwnam(self.user.name).pw_dir
    KeyError: 'getpwnam(): name not found: my@email.address

**Comment by willingc** [comment]
@otzy Sorry that we didn't answer this sooner. I'm hoping that you received an answer to your question on one of our other communication channels such as Gitter or the Jupyter mailing list. Please let us know if you still have questions. I'm very sorry for the delay.

**Comment by otzy** [comment]
@willingc actually I found the work around, as I mentioned in my comment.
This is simply a wish to have jupyterhub users not dependent on OS users.

**Comment by minrk** [comment]
It's up to the Spawner to decide how to start the single-user servers, including picking the user to run as. For the local (default) case, local users are used. For containerized servers (e.g. DockerSpawner), local users aren't needed.

A Spawner can choose to run all single-user servers as the same user. I don't believe any public deployments do this, but a small subclass would work:

```python
# in jupyterhub_config.py
from jupyterhub.spawner import LocalProcessSpawner

class SameUserSpawner(LocalProcessSpawner):
    """Local spawner that runs single-user servers as the same user as the Hub itself.

    Overrides user-specific env setup with no-ops.
    """
    
    def make_preexec_fn(self, name):
        """no-op to avoid setuid"""
        return lambda : None
    
    def user_env(self, env):
        """no-op to avoid setting HOME dir, etc.""" 
        return env

c.JupyterHub.spawner_class = SameUserSpawner
```

Alternately, the `make_preexec_fn` could call setuid to a specific user other than the hub, but independent of the `name` argument.

**Comment by otzy** [comment]
thanks a lot, I'll try that

**Comment by dmvieira** [comment]
I did a project for simple integration: https://github.com/globocom/jupyterhub_oauth_spawner
