### ISSUE TITLE
Proposal: Discovery of resource limits in singleuser servers

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#854]
We have several spawners that now offer setting resource limits (CPU, RAM, etc) on single user servers. However, there's no easy way for the user to discover what these limits are programatically. This is important for extensions like https://github.com/yuvipanda/nbresuse/ too, which can't really tell what the resource limits are.

I'd like to propose that we have a standard way for spawners to expose this info to single user servers, via environment variables. 

LIMIT_MEM -> Maximum amount of memory (units: bytes) that's available to this single user server. If it goes over this limit, it'll be denied memory access.
LIMIT_CPU -> Maximum amount of CPU (units: float of virtual CPU cores) that's available to this single user server

We can add more LIMIT_ env variables in the future if need be.

Some spawners also support resource guarantees, so we should also for them support:

GUARANTEE_MEM -> Minimum amount of memory (units: bytes) that's guaranteed to be available for this single user server.
GUARANTEE_CPU -> Minimum amount of CPU (units: float of virtual CPU cores) that's guaranteed to be available for this single user server.

If ok, I'll send PRs to all known spawners that support limits to add support for this.

**Comment by yuvipanda** [comment]
https://github.com/jupyterhub/jupyterhub/issues/343 is vaguely related.

**Comment by yuvipanda** [comment]
https://github.com/jupyterhub/systemdspawner/pull/12 is the sample implementation for systemd spawner.

**Comment by yuvipanda** [comment]
https://github.com/yuvipanda/nbresuse/pull/3 for the notebook extension. Users can also simply look at the env variable to figure out what their limits are.

**Comment by minrk** [comment]
Along with this, do you think we should expect a mechanism for returning current usage?

**Comment by yuvipanda** [comment]
That seems like a larger issue to me, since there are so many kinds of 'resources' that can have 'usage' (but not limits). We could probably adopt something like the Prometheus metrics format (https://prometheus.io/docs/instrumenting/exposition_formats/) and standardize on names that jupyterhub looks for? If JupyterHub even wants to expose those somewhere.

**Comment by yuvipanda** [comment]
One of the reasons I want to tackle tracking separately is that there are already nice ways of doing this separate from JupterHub (we use prometheus, `systemd-cgtop` works for systemd, etc). But there's no other way of discovering this limit info...

**Comment by minrk** [comment]
Sure. Just the first thing I think of when we surface an API for limits is wanting to view the current status of usage of those limits.

But +1 on the principle, if you want to start your PRs.

**Comment by yuvipanda** [comment]
Yeah, I can open a separate PR / proposal for current status after. I'm worried about duplicating that work between JupyterHub vs other systems that do this (Prometheus / Graphite / etc). We can scope that nicely tho, to make that not happen.

**Comment by yuvipanda** [comment]
https://github.com/jupyterhub/jupyterhub/pull/855 adds the convention to docs.

**Comment by yuvipanda** [comment]
I'm going to keep this open until we merge the k8s / systemdspawner / dockerspawner patches.

**Comment by yuvipanda** [comment]
k8s spawner is merged.

**Comment by yuvipanda** [comment]
(I set milestone to 0.7 since this code already made it into the beta)

**Comment by yuvipanda** [comment]
dockerspawner is done too.

**Comment by yuvipanda** [comment]
systemdspawner is done too. @willingc @minrk any other spawners that enforce resource limits I should try to patch? Or is this good to close now?

**Comment by willingc** [comment]
@minrk Do you want to close this as completed with 0.7? It doesn't appear to me that there is additional work for 0.8. Thanks.

**Comment by yuvipanda** [comment]
Yup, all done!

**Comment by Yensan** [comment]
If I must deploy a jupyterHub server for many user, and they want environment be isolated(shell ENV, python virtual env, jupyter kernel process). What should I do?
