### ISSUE TITLE
Proposal: Resource usage discovery of the single-user notebook servers

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#857]
Once #854 is implemented, it'll be nice to have a way to discover how much resources each single-user notebook server is using. There are plenty of other tools that make this possible already (Prometheus, Graphite/Diamond, Ganglia, etc), but it'll be nice to have a way to expose this in a standardized way that is accessible both to the JupyterHub admin interface and other sysadmin tools.

In that I propose that we add a [Prometheus Text Format](https://prometheus.io/docs/instrumenting/exposition_formats/) end point to either the notebook server or the single-user wrapper, to expose at least CPU and memory usage (and probably more later on). JupyterHub can pick up this info, and so can other tools as they see fit.

This is the 'pull' model of metrics, where the process being instrumented exposes them via an endpoint that could be consumed by multiple different clients (such as JupyterHub, Prometheus, or even [Graphite](https://www.robustperception.io/exporting-to-graphite-with-the-prometheus-python-client/)). This is better than the statsd 'push' model for this use case, since the push model requires metrics to be sent to only one place.

We could also possibly expose last_modified_time via this setup.

We would use the [python prometheus client](https://github.com/prometheus/client_python) library to do this. We could make this be an optional dependency too, similar to statsd now. It's a fairly small dependency though, and I'd be happy if it was made a non-optional dependency.

**Comment by yuvipanda** [comment]
I think the place for this to go is in the notebook repo, but JupyterHub would be the motivating use case. Things like nbresuse can also use this natively.

**Comment by yuvipanda** [comment]
If we do this, we'll also need to figure out our statsd story, to make sure it isn't too complicated for people to understand when to use statsd vs prometheus.

**Comment by yuvipanda** [comment]
Note that there are [bridges](https://github.com/prometheus/client_python#bridges) that directly push to graphite and what not, so this doesn't lock people into using prometheus.

**Comment by minrk** [comment]
I think there's a relatively clear separation, at list right now, in that usage (and last activity) is a current state query, whereas statsd is being used for event notifications.

I agree that this is a logical proposal for the base notebook, but if we want we can prototype it here in the singleuser wrapper and push it upstream after we are happy with it.

**Comment by minrk** [comment]
If this is a fetch operation, I don't *quite* get the benefit of prometheus over JSON via the existing REST API. What's the gain, there? It would be more consistent to fit with the rest of the API.

**Comment by minrk** [comment]
From in-person discussion: prometheus is a bit like statsd in reverse. A central service is told about 'endpoints' and can fetch data from them as desired. By using prometheus, we shouldn't need to write additional translators for JSON to whatever. We can still make this and any other data available via our existing REST API, as desired.

**Comment by rgbkrk** [comment]
Oooh, this is right in line with the cluster/computational context I want to provide in the UI. Loving `nbresuse`.

**Comment by manics** [comment]
I'm pretty sure we've got telemetry added somewhere so I'll close this, feel free to reopen if I'm mistaken
