### ISSUE TITLE
Release 0.7b1

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#862]
- [x] Upgrade Docs prior to Release

    - [x] Change log
    - [x] New features documented
    - [x] Update the contributor list - thank you page

- [x] Upgrade and test Reference Deployments

- [ ] Release software

    - [ ] Make sure 0 issues in milestone
    - [ ] Follow release process steps
    - [ ] Send builds to PyPI (Warehouse) and Conda Forge

- [ ] Blog post and/or release note

- [ ] Notify users of release

    - [ ] Email Jupyter and Jupyter In Education mailing lists
    - [ ] Tweet (optional)

- [ ] Increment the version number for the next release

- [x] Update roadmap

**Comment by minrk** [comment]
Draft announcement to send to mailing list, etc.:

We have just released the first beta of JupyterHub 0.7. Please take it for a spin:

    pip install --upgrade --pre jupyterhub

Main new features:

- A Services API for JupyterHub to manage adding additional processes with API access to the Hub, including running additional web services behind the Hub's proxy. See [the docs]() for more details.
- You can now import some utilities to authenticate your services with JupyterHub.
- You can now share links for users with `/hub/user-redirect/...` to link to files served by users' own servers. This avoids the need for complicated redirects when sharing links to each others' servers.

Other changes:

- The single-user server is now provided by the jupyterhub package, rather than a wrapper script around jupyter notebook. This means that single-user servers must have the jupyterhub package.
- The database schema has changed, so you will need to run `jupyterhub upgrade-db` to upgrade an existing instance. Make sure to backup first!

Plus lots of accumulated bugfixes, of course.

**Comment by willingc** [comment]
Looks good on the announcement. Thanks @minrk.

**Comment by willingc** [comment]
Closing since release is out :cake:
