### ISSUE TITLE
Dead Kernel: ImportError: No module named 'IPython.paths'

### ISSUE THREAD

**Issue by MikeDacre** [jupyterhub/jupyterhub#875]
I am getting this error when creating a new Jupyter session in JupyterHub:

![image](https://cloud.githubusercontent.com/assets/77714/20416690/5504981a-acf5-11e6-971b-b9232c356a08.png)

The `jupyterhub` console output is:

```
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/anaconda3/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/anaconda3/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/anaconda3/lib/python3.5/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/local/anaconda3/lib/python3.5/site-packages/ipykernel/connect.py", line 14, in <module>
    from IPython.paths import get_ipython_dir
ImportError: No module named 'IPython.paths'
```

I have found this issue reported elsewhere, but I can't find a resolution. The kernel dies immediately upon opening a new notebook.

This is an issue with my environment somewhere, the issue only happens with my user account. When I add a new user account the issue is not present. Also, I have an almost identical JupyterHub install running on a different system, and this issue does not happen there either.

I have deleted everything from my `~/.local` folder, running `find . -type f | grep ".*\.pth$"` returns:

```
./my_packages/MACS2/MACS2-2.1.1.20160309/vbuild/lib/python2.7/site-packages/easy-install.pth
./my_packages/MACS2/MACS2-2.1.1.20160309/build/lib/python2.7/site-packages/easy-install.pth
./.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/test/test_evaluate/sample_venvs/venv27/lib/python2.7/site-packages/import_smth.pth
./.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/test/test_evaluate/sample_venvs/venv27/lib/python2.7/site-packages/foo.pth
./.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/test/test_evaluate/sample_venvs/venv34/lib/python3.4/site-packages/import_smth.pth
./.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/test/test_evaluate/sample_venvs/venv34/lib/python3.4/site-packages/foo.pth
./.vim/bundle/python-mode/pymode/libs/logilab_common-1.0.2-py2.7-nspkg.pth
./.temp/undo/%home%dacre%.local%lib%python3.5%site-packages%easy-install.pth
./pyenvold/versions/3.5.2/envs/fyrd/lib/python3.5/site-packages/easy-install.pth
./pyenvold/versions/3.5.2/lib/python3.5/site-packages/matplotlib-1.5.3-py3.5-nspkg.pth
./pyenvold/versions/2.7.12/lib/python2.7/site-packages/matplotlib-1.5.3-py2.7-nspkg.pth
./pyenvold/versions/2.7.12/lib/python2.7/site-packages/backports.functools_lru_cache-1.3-py3.5-nspkg.pth
./pyenvold/versions/2.7.12/lib/python2.7/site-packages/configparser-3.5.0-py2.7-nspkg.pth
```

My `$PYTHONPATH` is empty, so nothing there.

JupyterHub is installed in an anconda environment, I recently created it and updated all of the software using `conda update --all`, so the most recent versions available in anaconda are there.

If I run `ipython` at the console from my user account I can do this:

```
In [1]: import IPython

In [2]: IPython?
Type:        module
String form: <module 'IPython' from '/usr/local/anaconda3/lib/python3.5/site-packages/IPython/__init__.py'>
File:        /usr/local/anaconda3/lib/python3.5/site-packages/IPython/__init__.py
Docstring:  
IPython: tools for interactive and parallel computing in Python.

http://ipython.org

In [3]: from IPython.paths import get_ipython_dir
```

That causes no errors.

My jupyter version is 4.2.0, jupyterhub version is 0.6.1.

`jupyter troubleshoot`:

https://gist.github.com/MikeDacre/7cd48c830d0ad5bb6f505df6820d5f24

Any help would be appreciated, I can't think of what to do next.

**Comment by willingc** [comment]
Hi @MikeDacre,

Let's try uninstaling `ipykernel` and `pyzmq` and then reinstall them. Please try

```
conda uninstall jupyter

conda install -c conda-forge jupyter
```

I hope that helps.

**Comment by MikeDacre** [comment]
Hi @willingc,

Thanks for the message, I tried that but it didn't work. Instead I cleaned out my home directory, which it really needed anyway, and that fixed the problem. It is strange though, do you have any idea what could cause that in my home directory? `.local` and `.jupyter` were already deleted. Maybe `.ipython`?

Thanks for your help,

Mike

**Comment by willingc** [comment]
Hi @MikeDacre,

It's possible that there was something in the `.conda` or another directory. Hard to know. I'm glad you got it working. Please let us know how your work on JupyterHub goes. Thanks. Feel free to close the issue when you are ready to do so. - Carol

**Comment by MikeDacre** [comment]
OK, closing now, I will keep fiddling, if I can nail down what caused the problem I will post here. Thanks for all your help.

**Comment by rafmesal** [comment]
Hi, I has the same problem today and I solved with this, as willingc commented on 17 Nov 2016:

> Hi @MikeDacre,

Let's try uninstalling ipykernel and pyzmq and then reinstall them. Please try

conda uninstall jupyter

conda install -c conda-forge jupyter
I hope that helps.
