### ISSUE TITLE
Listen on a UNIX-domain socket

### ISSUE THREAD

**Issue by lengau** [jupyterhub/jupyterhub#883]
I'd like to set up JupyterHub to be able to listen on a given UNIX-domain socket, so I can proxy jupyterhub behind nginx. Right now, it seems the only way in the configuration to listen is on a TCP socket. Any chance we could get the ability to make a UNIX domain socket instead?

**Comment by minrk** [comment]
I'm honestly not sure. [configurable-http-proxy](https://github.com/jupyterhub/configurable-http-proxy) is the frontmost piece of JupyterHub, so that's the place where it would need unix socket support. It is perhaps unlikely that we will be able to get *all* of the pieces listening only on unix sockets.

I should say that you don't *need* unix sockets to put it behind nginx - it's pretty common practice to put JupyterHub behind nginx as it is today.

**Comment by lengau** [comment]
I do already have it running behind nginx, but I'd rather have things on UNIX sockets if at all possible. 

node-http-proxy is able to listen on UNIX sockets (so I'd imagine configurable-http-proxy can as well), but I couldn't figure out a way to configure jupyterhub to use this functionality. It would probably require a change in the settings module to be able to do so (it may be as simple as giving the ability to send a socket URL rather than an address and port number). 

So far, I know of the following places in a complete JupyterHub deployment where something listens on a TCP socket:

1. The actual front-end deployment (configurable-http-proxy)
2. Two ports are opened for talking between jupyterhub and configurable-http-proxy
3. Each single-user server listens on a port
4. Each notebook appears to open 6 ports (I'm unclear as to what precisely opens each of these).

Any suggestions about where to look for more details about those last ones would be greatly appreciated, as I've been wanting to start contributing to more open source projects, so I might take up the challenge of seeing what I can do here over the holidays.

**Comment by minrk** [comment]
There are *a lot* of ports to deal with if you want absolutely everything to be on bsd sockets, and there isn't configuration for most of it. The only part of this that does exist at the moment is the communication between the notebook server and its kernels, which you can set with:

```python
c.KernelManager.transport = 'ipc'
```

But the Hub, the notebook server itself, and CHP don't have options to listen on BSD sockets at this point.

**Comment by willingc** [comment]
Hi @minrk @lengau,

I'm going to go ahead and close this issue as currently out of the project scope. Please feel free to reopen if you believe that I have closed this in error. Thanks!
