### ISSUE TITLE
Question: integration of the scripts from Jupyterhub in Github

### ISSUE THREAD

**Issue by pcarazo** [jupyterhub/jupyterhub#884]
Hello!

First of all sorry for the question, since it is not actually an issue, but I didn't find other way:

I am wondering if there is any way of saving the scripts you run into the notebooks, in Github, so that you can develop your scripts and keep a control of versions and update them easily.

Thanks

**Comment by minrk** [comment]
There's no direct GitHub integration, but you can definitely use git and GitHub in JupyterHub. You can open a terminal from the dashboard (New > Terminal) and use git from there, and push/pull files to/from GitHub.

**Comment by willingc** [comment]
Closing this issue as resolved.
