### ISSUE TITLE
Restrict admin groups to an AD group

### ISSUE THREAD

**Issue by hani1814** [jupyterhub/jupyterhub#888]
Hi,

is it possible to restrict the admin to an AD group rather than list them in the config file such as 

c.Authenticator.admin_users = {'mal', 'zoe'}

ideally something along the line = c.Authenticator.admin_users = AD_group_myaccess

Thank you

**Comment by minrk** [comment]
There isn't currently a way to query the Authenticator for admin users. The admin flag is stored directly in the Hub database at the moment. We could consider adding such functionality, if needed.

**Comment by hani1814** [comment]
Yes please - this would be very useful to make it enterprise strong

**Comment by jkinkead** [comment]
This would be fantastic to have.

What about adding an `admin` field to the dict returned from `authenticate`?

**Comment by yuvipanda** [comment]
This has been implemented in #1564.
