### ISSUE TITLE
Toree Integration causes issues with Ambari rack awareness scripts

### ISSUE THREAD

**Issue by rachmaninovquartet** [jupyterhub/jupyterhub#889]
Hi,

I've setup jupyterhub in a Hortonworks cluster. Everything works fine, until I add the Apache Toree kernel. As soon as I start a notebook, with that, it prints to the logs something like this once per second:

```
16/11/29 16:24:20 WARN ScriptBasedMapping: Exception running /etc/hadoop/conf/topology_script.py some.ip.address
ExitCodeException exitCode=1:   File "/etc/hadoop/conf/topology_script.py", line 63
    print rack
             ^
SyntaxError: Missing parentheses in call to 'print'

	at `org.apache.hadoop.util.Shell.runCommand(Shell.java:576)`
```

It is calling the Ambari generated rack awareness scripts, which have /usr/bin/env python at the top of them. Using jupyterhub, this needs to be python 3. Unfortunately, the scripts only work with python 2.

This occurs in the latest jupyterhub, available via pip (11/29/16). I've asked the user groups of both Ambari and Toree for help, but neither have come up with anything actionable. 

Any potential work arounds?

Thanks,

Ian

**Comment by mariusvniekerk** [comment]
So that is caused by your 

`/etc/hadoop/conf/topology_script.py` being run with the python environment used by jupyterhub (which is python3) and that script not being python 2/3 compatible.

If you modify script to use `print(rack)` instead you should be fine.

**Comment by mariusvniekerk** [comment]
So the one workaround that you try that would not involve modifying the ambari generated files would be to have is to have the script you run to launch the toree kernel alter the `$PATH` so that a python2 kernel will be found by `/usr/bin/env python`.

You'll very likely run into the same issue if you have other python 3 kernels that get run, which activate a python3 conda environment/virtualenv.

**Comment by rachmaninovquartet** [comment]
@mariusvniekerk Do you have any documentation, you would suggest looking into for this "to have the script you run to launch the toree kernel alter the $PATH so that a python2 kernel will be found by /usr/bin/env python"
That sounds like a strong solution.

**Comment by beeva-gerardovazquez** [comment]
Hi,
I have found the same behaviour trying to run pyspark as kernel or loading it from a python2 kernel.
pyspark on console works fine

Regards

**Comment by rachmaninovquartet** [comment]
I did find a fix, but will have to look up exactly what I changed. I
believe I used a custom file and updated an HDFS conf or two, in order to
keep it from getting overwritten. I'll try to look it up later today.

**Comment by rachmaninovquartet** [comment]
@beeva-gerardovazquez 
I updated hdfs core-site.xml to include the value "/etc/hadoop/conf/custom_topology_script.py" for "net.topology.script.file.name". I copied /etc/hadoop/conf/topology_script.py and replaced the python path at the top of the file with one hard coded to my ambari's python and saved it as "/etc/hadoop/conf/custom_topology_script.py"

**Comment by beeva-gerardovazquez** [comment]
@rachmaninovquartet Thanks! I found another workaround, setting the path to add python2 in spark-env.sh as /opt/anaconda/bin/python2.7 with:
export PATH=/opt/anaconda2/bin:$PATH

**Comment by willingc** [comment]
@rachmaninovquartet @beeva-gerardovazquez @mariusvniekerk It looks like this issue can be closed now. Correct?

If anyone would like to write a brief summary for the troubleshooting FAQ in the docs, we would welcome a PR. Please ping me if you are interested in doing so.

**Comment by rachmaninovquartet** [comment]
@willingc I'd say it's fine to close. We have two options for fixing.

**Comment by rachmaninovquartet** [comment]
@willingc I'd be happy to add to the docs, but I'm not sure how to ping you

**Comment by willingc** [comment]
@rachmaninovquartet Just @ mention me like you just did if you have any questions on adding to the docs either here or on a WIP PR. Thanks! :cake:
