### ISSUE TITLE
Support token auth in single-user servers

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#891]
The default LoginHandler will support token auth in 4.3: https://github.com/jupyter/notebook/pull/1831 . Since JupyterHub replaces the LoginHandler, token auth won't work with JupyterHub without modifications. We should add support for the Authorization header in the single-user server so that JupyterHub tokens can be used to access single-user servers via the Authorization header.

This will also likely drive demand for creation of new API tokens via UI, but that can be a separate step.

cf https://github.com/jupyterhub/jupyterhub-deploy-docker/issues/30

**Comment by Analect** [comment]
@minrk ... is there anything I might be able to help with here, in order to be able to get the notebook API working against user servers running under Jupyterhub?

**Comment by minrk** [comment]
If you'd like to make a PR, that would be great! The first thing to do is get the token auth from [here](https://github.com/jupyter/notebook/blob/4.x/notebook/auth/login.py#L100) and include the token checking (Authorization header and possibly `?token` parameter) in the single-user auth [here](https://github.com/jupyterhub/jupyterhub/blob/0.7.0/jupyterhub/services/auth.py#L192). It will need to check the *token* auth endpoint, rather than cookie.

**Comment by Analect** [comment]
@minrk .... not unwilling to help ... but I'm not sure my python skills are up to that!

**Comment by minrk** [comment]
If you'd like, I can help you through it if you want to start a PR and ask questions (feel free to open a PR early and ask for help!). If you think it's too much, don't worry; we can take care of it, too.

**Comment by Analect** [comment]
@minrk ... I'm being a bit lame, I realise ... but I expect you are able to implement this more expeditiously than I could manage!

**Comment by minrk** [comment]
Not at all! Feel free to tackle a problem you are more comfortable with. We got this covered. And don't hesitate to ask for help.

**Comment by barrachri** [comment]
Question:

Jupyter notebooks offered through JupyterHub are already "secured" using the hub for the login and the cookie.

What is the point to add this support ?

is not easier to set 

`c.NotebookApp.token = ''`

`c.NotebookApp.password = ''`

?

**Comment by minrk** [comment]
[This comment above](https://github.com/jupyterhub/jupyterhub/issues/891#issuecomment-265150188) is the main thing to implement. Everything's in place in that JupyterHub has tokens, and an API for asking the Hub who a token corresponds to (`GET /authorizations/token/:token`). What's needed is for the HubAuthenticated wrapper to look for tokens in the Authorization header and url parameters, in addition to the cookie it supports now. Everything else ought to be set.

Right now, we have:

- `HubAuth.get_user` which calls `HubAuth.user_for_cookie` to identify the user

We need to add checking for tokens to `HubAuth.get_user`, with:

```python
class HubAuth():
    def _get_token(self, handler):
        """Return the token from the Authorization header or ?token url query parameter

        returns None if no token found
        """

    def user_for_token(self, token):
        """Ask the Hub for the user identified by a token

        returns user model (dict) if a user is identified, None otherwise
        """
        # same as user_for_cookie, but use the token API instead of the cookie API
```

**Comment by willingc** [comment]
Thanks @minrk.
