### ISSUE TITLE
You must log out and log back in to use new kernels installed via the web UI

### ISSUE THREAD

**Issue by mconigliaro** [jupyterhub/jupyterhub#898]
Like the title says, after installing a new kernel via the 0.7.0 web UI, you must log out and log back in before it will let you create new notebooks with the new kernel.

**Comment by minrk** [comment]
continuing discussion of the nb_conda_kernels extension in #899

**Comment by mconigliaro** [comment]
Never mind. I just realized that refreshing the page makes the kernels show up. I guess it didn't occur to me that clicking on the different tabs *wasn't* reloading the page.

**Comment by willingc** [comment]
No problem @mconigliaro. I'm glad that you did get it to work. 👍
