### ISSUE TITLE
jupyterhub github oauth behind internet proxy

### ISSUE THREAD

**Issue by jaketbouma** [jupyterhub/jupyterhub#903]
Hi there

We have a squid internet proxy blocking our internet access.  The usual configuration is to set the environment variables `https_proxy`, `http_proxy` and `no_proxy` accordingly.
Jupyterhub with local authentication is working correctly.

Using `GithubOAuthenticator` gets through the first steps:
 - user redirected to github to log in
 - user sends code to `/hub/oauth_callback?code=<code>`
 - fails, the hub cannot communicate with github.com

The error:
```
    HTTPServerRequest(protocol='http', host='<IP>:8890', method='GET', uri='/hub/oauth_callback?code=<code>', version='HTTP/1.1', remote_ip='<IP>', headers={'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0', 'Upgrade-Insecure-Requests': '1', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Dnt': '1', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate, br', 'Host': '<IP>:8890', 'Connection': 'close'})
    Traceback (most recent call last):
      File "/conda/lib/python3.5/site-packages/tornado/web.py", line 1469, in _execute
        result = yield result
      File "/conda/lib/python3.5/site-packages/oauthenticator/oauth2.py", line 51, in get
        username = yield self.authenticator.get_authenticated_user(self, None)
      File "/conda/lib/python3.5/site-packages/jupyterhub/auth.py", line 160, in get_authenticated_user
        username = yield self.authenticate(handler, data)
      File "/conda/lib/python3.5/site-packages/oauthenticator/github.py", line 85, in authenticate
        resp = yield http_client.fetch(req)
      File "/conda/lib/python3.5/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/conda/lib/python3.5/site-packages/tornado/simple_httpclient.py", line 307, in _on_timeout
        raise HTTPError(599, error_message)
    tornado.httpclient.HTTPError: HTTP 599: Timeout while connecting
```
appears to be produced by 
[these lines in `oauthenicator/github.py`](https://github.com/jupyterhub/oauthenticator/blob/0.5.1/oauthenticator/github.py#L63-L99)

which seems to boil down to the `tornado.httpclient.AsyncHTTPClient` declared at
```
        # TODO: Configure the curl_httpclient for tornado
        http_client = AsyncHTTPClient()
```
not respecting the environment variable `https_proxy`.  This seems to be a expected (see [SO post here](http://stackoverflow.com/questions/22187031/does-tornado-httpclient-asynchttpclient-support-using-http-proxy-in-python3-x)).

**My question is**; how to configure Tornado / Jupyterhub so that it uses the environment variable `https_proxy` to talk to github.com?  Or is there another way for me to tell the authenticator to use the proxy?

Running jupyterhub 0.7.0 with oauthenticator 0.5.1.
`jupyter troubleshoot` available at [this gist](https://gist.github.com/jaketbouma/8756230d8f390bb023221f240172dbe2#file-jupyter-troubleshoot)

**Comment by minrk** [comment]
@jaketbouma from the SO question, can you run:

```python
tornado.httpclient.AsyncHTTPClient.configure("tornado.curl_httpclient.CurlAsyncHTTPClient")
```

in your `jupyterhub_config.py`?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:

**Comment by jaketbouma** [comment]
Apologies, had to turn to AD to get this going and left the github config behind.

**Comment by hpbieker** [comment]
I am experiencing the same problem. The tornado asynchttpclient requires the proxy to be manually configured, unfortunately it looks like it is not possible to set this in the config file. Any suggestions?
