### ISSUE TITLE
Dockerspawner with Github Oauth breaks in 0.7.0 (works in 0.6.1)

### ISSUE THREAD

**Issue by jdavidheiser** [jupyterhub/jupyterhub#905]
I set dockerspawner with the oauth example provided in the repository, using the pre-built singleuser image (`docker pull jupyter/singleuser`), and everything works when using jupyterhub 0.6.1.  However, if I switch to 0.7.0, the following break:

* logging out - it just redirects back to `/hub/home#` without logging out
* shutting down a server, then trying to launch it again - can no longer connect to the docker image, with a 500 error: `Permission failure checking authorization, I may need to be restarted`

If I rm -f the docker container, it starts back up again fine, but has the same problem if I shut down my server or the jupyterhub server.

With debug mode logging, when logging out, this is the output:

```
[I 2016-12-16 16:34:58.647 JupyterHub login:19] User logged out: X@Y.com
[I 2016-12-16 16:34:58.653 JupyterHub log:100] 302 GET /hub/logout (X@Y.com@50.202.79.166) 5.50ms
[W 2016-12-16 16:34:58.734 JupyterHub pages:32] Disallowing redirect outside JupyterHub: ''
[I 2016-12-16 16:34:58.738 JupyterHub log:100] 302 GET /hub/ (@50.xxxxxx) 1.73ms
[I 2016-12-16 16:34:58.821 JupyterHub log:100] 302 GET /oauth_login (@50.xxxxxx) 1.95ms
[I 2016-12-16 16:34:58.899 JupyterHub google:35] redirect_uri: 'http://ec2-xxxxx:8000/hub/oauth_callback'
[I 2016-12-16 16:34:58.902 JupyterHub log:100] 302 GET /hub/oauth_login (@50.x)
```

**Comment by minrk** [comment]
Indeed, this is #901. We need a way to tell JupyterHub that it shouldn't cleanup API tokens when stopping servers. In the meantime, if you set `DockerSpawner.remove_containers = True`, stopping a server will cleanup the container, and the next start will get a new token and connect successfully.

**Comment by minrk** [comment]
#910 plus https://github.com/jupyterhub/dockerspawner/pull/131 should fix this.

**Comment by minrk** [comment]
JupyterHub 0.7.1 and DockerSpawner 0.6 should fix this, which should both be out in the next day or two.
