### ISSUE TITLE
Cannot get Jupyterhub to work within Docker Image: Econn Error

### ISSUE THREAD

**Issue by thornhale** [jupyterhub/jupyterhub#906]
Configuation:
We are trying to get Jupyterhub 0.7.0 to run from within a docker image (see link):
https://hub.docker.com/r/jupyter/jupyterhub/

After initial PAM authentication 3 errors, we decided to use the host PAM authentication system and used the following command to get Jupyterhub to run:

docker run  -p 8000:8000 -v /etc/pam.d:/etc/pam.d -v /etc/passwd:/etc/passwd -v /etc/shadow:/etc/shadow jupyterhub/jupyter jupyter --no-ssl

(We are leaving SSL out of the configuration for now just to get the hub to run.)

Now, when we enter the credentials, we no longer encounter the PAM 3 error, but after 10-20 seconds we get another error:

```
Proxy error: code=ECONNECT
503 GET /hub/login?next=
```

This is run on RHEL 7.0 on a VMWare machine.
Does anyone have an idea what could be causing this error?

**Comment by minrk** [comment]
That suggests that maybe the Hub process is going away, or otherwise getting stuck in a weird way. I haven't mounted PAM files into a docker container, but perhaps this is not quite enough. You might try running with `--debug` to get more information.

**Comment by thornhale** [comment]
We are only mounting PAM files in a docker container to avoid the PAM authentication errors because we were not able to resolve those PAM authentication errors encountered earlier. Doing so it seems led us down a different path of difficulties. My colleague will try that later and report back here.

**Comment by thornhale** [comment]
My colleague tried running Jupyterhub with the debug option. 

Unfortunately, no further information is returned. I ended up following your JupyterHub tutorial which you gave in London this year. Maybe not as elegant as Jupyter in a Docker container, but at this point, we were able to get JupyterHub to run in our virtual network using your tutorial. Thank you for that!

Trying to make this service available to more people within a cooperate environment, lead to the exact same issues described [here](https://github.com/jupyterhub/jupyterhub/issues/563) and [here](https://github.com/jupyter/notebook/issues/1380#issuecomment-214230981) (<- This is the exact same issue I have right now with just regular JupyterNotebooks; hence I had to move to my own virtual machine to make it work...).

**Comment by willingc** [comment]
Hi @thornhale and @minrk,

Should we continue to leave this issue open? I'm wondering if the recent JupyterHub 0.7.2 would have the same behavior or if it would resolve the issue. Please let me know your thoughts about the status of the issue.

Thanks!

**Comment by minrk** [comment]
I think it's unlikely that the patch releases since 0.7 would fix whatever the cause here might be, but I still don't know what the root cause is. My *guess* is that it's outside JupyterHub, and a matter of configuration the many moving parts in docker, etc.

**Comment by willingc** [comment]
I'm going to close this issue as a configuration case that would be difficult to troubleshoot without direct access to the original config. We'll have this documented discussion available via issue search if the same error is seen in the future. Thanks @thornhale and @minrk.

**Comment by thornhale** [comment]
Hi Carol,

We found that our firewall blocks any websocket connection attempts. We are working with the security team to create a new rule and hope that this will fix the issue. I will keep you updated.

Anthony

On 1/10/2017 7:20 PM, Carol Willing wrote:

Hi @thornhale<https://github.com/thornhale> and @minrk<https://github.com/minrk>,

Should we continue to leave this issue open? I'm wondering if the recent JupyterHub 0.7.2 would have the same behavior or if it would resolve the issue. Please let me know your thoughts about the status of the issue.

Thanks!

**Comment by willingc** [comment]
Hi @thornhale,

Thanks! Please feel free to ping us as needed here or on the Gitter channel. :sunny:
