### ISSUE TITLE
Jupyterhub Daemon encounters 500 error

### ISSUE THREAD

**Issue by yizhexu** [jupyterhub/jupyterhub#917]
Hello! I encountered a jupyterhub 500 internal server error after trying to configure it run as start in centos 7. 

I followed the instruction here: https://goo.gl/Y0GMpd after installing jupyterhub through pip3 install. 

**How to reproduce the issue**
1. Generate config 
`sudo jupyterhub --generate-config -f /etc/jupyterhub/jupyterhub_config.py`
changed c.JupyterHub.hub_ip = '192.168.xx.xxx' 
Also changed spawner_class to sudospawner: `c.JupyterHub.spawner_class='sudospawner.SudoSpawner'`

Installed sudospawner from github: sudo pip3 install git+https://github.com/jupyter/sudospawner

2. If just run jupyterhub 
`sudo jupyterhub -f  /etc/jupyterhub/jupyterhub_config.py`
everything works properly

3. created /lib/systemd/system/jupyterhub.service as the [wiki](https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service#centosfedorageneric-systemd). Changed `User=jupyterhub` to `User=root`
Then: 
sudo systemctl daemon-reload
sudo systemctl start jupyterhub
sudo systemctl status jupyterhub -l

It shows jupyterhub.service is running. 

4. Then go 192.168.xx.xxx:8000, the ip I specified in config file. Use a system user & password to log in, get 500 error: 

> 500 : Internal Server Error
> Failed to start your server. Please contact admin.

5. Look at the status again and find: 
jupyterhub[19807]: [I 2016-12-28 19:21:17.098 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.9.0.22) 2.62ms
python3[19807]: pam_unix(login:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=yizhexu

6. If instead of using `sudo jupyterhub`, run 
`sudo jupyterhub --JupyterHub.spawner_class=sudospawner.SudoSpawner --debug`
I get the same 500 error with the following information: 

```

[D 2016-12-28 19:28:22.910 JupyterHub log:100] 304 GET /hub/login (@::ffff:10.9.0.22) 2.66ms
[E 2016-12-28 19:28:24.439 JupyterHub user:245] Unhandled error starting yizhexu's server: [Errno 13] Permission denied
[E 2016-12-28 19:28:24.484 JupyterHub web:1548] Uncaught exception POST /hub/login?next= (::ffff:10.9.0.22)
    HTTPServerRequest(protocol='http', host='192.168.xx.xxx:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::ffff:10.9.0.22', headers={'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'X-Forwarded-Proto': 'http', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36', 'Connection': 'close', 'Content-Length': '43', 'Content-Type': 'application/x-www-form-urlencoded', 'Upgrade-Insecure-Requests': '1', 'Accept-Language': 'en-US,en;q=0.8', 'Host': '192.168.xx.xxx:8000', 'Accept-Encoding': 'gzip, deflate', 'Origin': 'http://192.168.xx.xxx:8000', 'Cookie': 'username-192-168-50-141-8888="2|1:0|10:1482952349|28:username-192-168-xx-xxx-8888|44:ZGRmMWQ0YjIxM2YwNGU1YWJhOTI0Zjg3NTA4YjEzYzI=|b1711d00b5ce7369c75ce0ab46c7abc1a4df64abb62e6e9c40cb948bd1e9af27"; username-192-168-50-141-8889="2|1:0|10:1482961570|28:username-192-168-xx-xxx-8889|44:ZmEwNGJmNTMwNDA2NGYwYmI3MGU4ZDIyNzUyNjI3Y2M=|cc1c288aa35b24c00de5b14d1fc01a53d39fe4678874f35c9c5b73515cb09439"', 'X-Forwarded-Port': '8000', 'X-Forwarded-Host': '192.168.xx.xxx:8000', 'X-Forwarded-For': '::ffff:10.9.0.22', 'Cache-Control': 'max-age=0', 'Referer': 'http://192.168.50.141:8000/hub/login'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 1469, in _execute
        result = yield result
      File "/usr/local/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 84, in post
        yield self.spawn_single_user(user)
      File "/usr/local/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 328, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/usr/local/lib/python3.5/site-packages/jupyterhub/user.py", line 255, in spawn
        raise e
      File "/usr/local/lib/python3.5/site-packages/jupyterhub/user.py", line 229, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.5/site-packages/sudospawner/spawner.py", line 83, in start
        reply = yield self.do(action='spawn', args=self.get_args(), env=self.get_env())
      File "/usr/local/lib/python3.5/site-packages/sudospawner/spawner.py", line 58, in do
        p = Subprocess(cmd, stdin=Subprocess.STREAM, stdout=Subprocess.STREAM, stderr=Subprocess.STREAM)
      File "/usr/local/lib/python3.5/site-packages/tornado/process.py", line 244, in __init__
        self.proc = subprocess.Popen(*args, **kwargs)
      File "/usr/local/lib/python3.5/subprocess.py", line 950, in __init__
        restore_signals, start_new_session)
      File "/usr/local/lib/python3.5/subprocess.py", line 1540, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    PermissionError: [Errno 13] Permission denied
    
[D 2016-12-28 19:28:24.490 JupyterHub base:462] No template for 500
[E 2016-12-28 19:28:24.496 JupyterHub log:99] {
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "X-Forwarded-Proto": "http",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36",
      "Connection": "close",
      "Content-Length": "43",
      "Content-Type": "application/x-www-form-urlencoded",
      "Upgrade-Insecure-Requests": "1",
      "Accept-Language": "en-US,en;q=0.8",
      "Host": "192.168.xx.xxx:8000",
      "Accept-Encoding": "gzip, deflate",
      "Origin": "http://192.168.xx.xxx:8000",
      "Cookie": "username-192-168-50-141-8888=\"2|1:0|10:1482952349|28:username-192-168-xx-xxx-8888|44:ZGRmMWQ0YjIxM2YwNGU1YWJhOTI0Zjg3NTA4YjEzYzI=|b1711d00b5ce7369c75ce0ab46c7abc1a4df64abb62e6e9c40cb948bd1e9af27\"; username-192-168-50-141-8889=\"2|1:0|10:1482961570|28:username-192-168-50-141-8889|44:ZmEwNGJmNTMwNDA2NGYwYmI3MGU4ZDIyNzUyNjI3Y2M=|cc1c288aa35b24c00de5b14d1fc01a53d39fe4678874f35c9c5b73515cb09439\"",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-Host": "192.168.xx.xxx:8000",
      "X-Forwarded-For": "::ffff:10.9.0.22",
      "Cache-Control": "max-age=0",
      "Referer": "http://192.168.xx.xxx:8000/hub/login"
    }
[E 2016-12-28 19:28:24.496 JupyterHub log:100] 500 POST /hub/login?next= (@::ffff:10.9.0.22) 576.64ms


```

**Comment by minrk** [comment]
Something's wrong, because using sudospawner should mean that the Hub is *not* running as root, but if I understood your description correctly, you are running JupyterHub as root.

What do you get for `which -a sudospawner`? And `sudo which -a sudospawner`? What are the permissions on the `sudospawner` executable that you find?

**Comment by pacosoplas** [comment]
I am trying start jupyterhub as not root user, but when I type user y pass and click on Sign in button i receive this error.

I did everything from this page: https://github.com/jupyterhub/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges

[E 2017-01-02 16:43:07.215 JupyterHub user:245] Unhandled error starting u029550's server: substring not found
[E 2017-01-02 16:43:07.228 JupyterHub web:1548] Uncaught exception POST /hub/login?next= (10.11.14.86)
    HTTPServerRequest(protocol='http', host='10.11.14.201:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='10.11.14.86', headers={'Accept-Encoding': 'gzip, deflate', 'X-Forwarded-Port': '8000', 'X-Forwarded-Host': '10.11.14.201:8000', 'X-Forwarded-For': '10.11.14.86', 'Origin': 'http://10.11.14.201:8000', 'Upgrade-Insecure-Requests': '1', 'Referer': 'http://10.11.14.201:8000/hub/login?next=', 'X-Forwarded-Proto': 'http', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Accept-Language': 'es-ES,es;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36', 'Cache-Control': 'max-age=0', 'Content-Type': 'application/x-www-form-urlencoded', 'Connection': 'close', 'Host': '10.11.14.201:8000', 'Content-Length': '33'})
    Traceback (most recent call last):
      File "/opt/Python-3.5.2/lib/python3.5/site-packages/tornado/web.py", line 1469, in _execute
        result = yield result
      File "/opt/Python-3.5.2/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 84, in post
        yield self.spawn_single_user(user)
      File "/opt/Python-3.5.2/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 327, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/opt/Python-3.5.2/lib/python3.5/site-packages/jupyterhub/user.py", line 255, in spawn
        raise e
      File "/opt/Python-3.5.2/lib/python3.5/site-packages/jupyterhub/user.py", line 229, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/Python-3.5.2/lib/python3.5/site-packages/sudospawner/spawner.py", line 83, in start
        reply = yield self.do(action='spawn', args=self.get_args(), env=self.get_env())
      File "/opt/Python-3.5.2/lib/python3.5/site-packages/sudospawner/spawner.py", line 69, in do
        data_str = data_str[data_str.index('{'):data_str.rindex('}')+1]
    ValueError: substring not found
    
[D 2017-01-02 16:43:07.232 JupyterHub base:461] No template for 500
[E 2017-01-02 16:43:07.238 JupyterHub log:99] {
      "Accept-Encoding": "gzip, deflate",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-Host": "10.11.14.201:8000",
      "X-Forwarded-For": "10.11.14.86",
      "Origin": "http://10.11.14.201:8000",
      "Upgrade-Insecure-Requests": "1",
      "Referer": "http://10.11.14.201:8000/hub/login?next=",
      "X-Forwarded-Proto": "http",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Accept-Language": "es-ES,es;q=0.8",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36",
      "Cache-Control": "max-age=0",
      "Content-Type": "application/x-www-form-urlencoded",
      "Connection": "close",
      "Host": "10.11.14.201:8000",
      "Content-Length": "33"
    }
[E 2017-01-02 16:43:07.238 JupyterHub log:100] 500 POST /hub/login?next= (@10.11.14.86) 91.59ms
16:43:07.267 - debug: [ConfigProxy] PROXY WEB /favicon.ico to http://10.11.14.201:8081
[D 2017-01-02 16:43:07.269 JupyterHub log:100] 304 GET /favicon.ico (@10.11.14.86) 0.81ms


please any suggestions??

**Comment by yizhexu** [comment]
@minrk Thanks for your response. I got the following
```
which -a sudospawner
/bin/sudospawner
/usr/bin/sudospawner
# sudo which -a sudospawner
/bin/sudospawner
/usr/bin/sudospawner
# ls -al /bin/sudospawner 
-rwxr-xr-x. 2 root root 65 Dec 28 14:15 /bin/sudospawner
# ls -al /usr/bin/sudospawner 
-rwxr-xr-x. 2 root root 65 Dec 28 14:15 /usr/bin/sudospawner
```

**Comment by minrk** [comment]
@yizhexu it's a bit odd to have one in `/bin`. I would have expected these to go in `/usr/local/bin`. How did you install sudospawner?

which executable did you give sudo permissions to? It must be the exact full path of the `sudospawner` executable that will be run. Other sudospawner executables will not have the necessary elevated permissions.

**Comment by yizhexu** [comment]
@minrk Thank you for your response. sudospawner and jupyterhub are in `/bin` was because I created a link manually. I have them removed and still get the same 500 error. The actual sudospawner path is in `/usr/local/bin` because I installed it with `sudo pip3 install git+https://github.com/jupyter/sudospawner`. 

One thing that I don't understand is you said 
> using sudospawner should mean that the Hub is not running as root

If you want to do `systemctl start jupyterhub`, it will has to be sudo. Then since the `--JupyterHub.spawner_class=sudospawner.SudoSpawner` argument is in jupyterhub.service file according to this [wiki](https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service#centosfedorageneric-systemd) page, then wouldn't it has to be run as root? Or I should be stating something else in jupyterhub.service file?

**Comment by minrk** [comment]
@yizhexu Yes, that jupyterhub service example does run the Hub as root. The point I'm trying to reach is that if you are running the Hub as root, there is no reason to use the sudospawner. sudospawner is only useful when you are running the Hub as a restricted user, because it adds extra steps to gain *specific* elevated permissions, rather than assuming root permissions. If you are already running the Hub as root, it is best to use the default spawner, rather than trying to use sudospawner.
