### ISSUE TITLE
Failed to find proxy ['configurable-http-proxy']

### ISSUE THREAD

**Issue by ermakovpetr** [jupyterhub/jupyterhub#930]
➜  npm install -g configurable-http-proxy

> (node:26788) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
> /usr/local/bin/configurable-http-proxy -> /usr/local/lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy
> /usr/local/lib
> └── configurable-http-proxy@1.3.1

➜  /usr/local/python35/bin/jupyterhub --version

> 0.7.1

➜  /usr/local/python35/bin/python --version

> Python 3.5.1

➜ /usr/local/python35/bin/jupyterhub --ip=0.0.0.0 --port=80 --no-ssl

> [I 2017-01-10 16:38:16.003 JupyterHub app:724] Loading cookie_secret from /home/p.ermakov/jupyterhub_cookie_secret
> [W 2017-01-10 16:38:16.077 JupyterHub app:365]
>     Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
>     Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
> 
> [W 2017-01-10 16:38:16.083 JupyterHub app:864] No admin users, admin interface will be unavailable.
> [W 2017-01-10 16:38:16.083 JupyterHub app:865] Add any administrative users to `c.Authenticator.admin_users` in config.
> [I 2017-01-10 16:38:16.083 JupyterHub app:892] Not using whitelist. Any authenticated user will be allowed.
> [I 2017-01-10 16:38:16.105 JupyterHub app:1453] Hub API listening on http://127.0.0.1:8081/hub/
> [W 2017-01-10 16:38:16.110 JupyterHub app:1174] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
> [I 2017-01-10 16:38:16.110 JupyterHub app:1176] Starting proxy @ http://0.0.0.0:80/
> [E 2017-01-10 16:38:16.114 JupyterHub app:1184] Failed to find proxy ['configurable-http-proxy']
>     The proxy can be installed with `npm install -g configurable-http-proxy`

➜  rpm --query centos-release

> centos-release-6-8.el6.centos.12.3.x86_64

:(

**Comment by ermakovpetr** [comment]
> ln -s /usr/local/bin/configurable-http-proxy /usr/bin/configurable-http-proxy
:)

**Comment by jbrant** [comment]
I simply can't get this working as a service on RHEL 7.3.

Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: [I 2018-02-07 23:02:53.560 JupyterHub app:834] Loading cookie_secret from /etc/jupyterhub/jupyterhub_cookie_secret
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: [W 2018-02-07 23:02:53.581 JupyterHub app:955] No admin users, admin interface will be unavailable.
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: [W 2018-02-07 23:02:53.581 JupyterHub app:956] Add any administrative users to `c.Authenticator.admin_users` in config.
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: [I 2018-02-07 23:02:53.581 JupyterHub app:983] Not using whitelist. Any authenticated user will be allowed.
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: [I 2018-02-07 23:02:53.610 JupyterHub app:1528] Hub API listening on http://127.0.0.1:8081/hub/
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: [W 2018-02-07 23:02:53.611 JupyterHub proxy:415]
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: [W 2018-02-07 23:02:53.611 JupyterHub proxy:456] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: [I 2018-02-07 23:02:53.612 JupyterHub proxy:458] Starting proxy @ http://*:8000/
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: [E 2018-02-07 23:02:53.614 JupyterHub proxy:467] Failed to find proxy ['configurable-http-proxy']
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: The proxy can be installed with `npm install -g configurable-http-proxy`
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: [C 2018-02-07 23:02:53.614 JupyterHub app:1535] Failed to start proxy
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: Traceback (most recent call last):
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/app.py", line 1533, in start
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: yield self.proxy.start()
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/proxy.py", line 462, in start
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: self.proxy_process = Popen(cmd, env=env, start_new_session=True, shell=shell)
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: File "/opt/anaconda3/lib/python3.6/subprocess.py", line 707, in __init__
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: restore_signals, start_new_session)
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: File "/opt/anaconda3/lib/python3.6/subprocess.py", line 1326, in _execute_child
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: raise child_exception_type(errno_num, err_msg)
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com jupyterhub[20034]: FileNotFoundError: [Errno 2] No such file or directory: 'configurable-http-proxy'
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com systemd[1]: jupyterhub.service: main process exited, code=exited, status=1/FAILURE
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com systemd[1]: Unit jupyterhub.service entered failed state.
Feb 07 23:02:53 ocd04-160-205-232-102.ltn.us.lmco.com systemd[1]: jupyterhub.service failed.

**Comment by tony-tian** [comment]
wondering if it's solved? cuz I met the problem, too. Now configurable-http-proxy has reached 4.0.1...but I still could not get it work

**Comment by neffo** [comment]
Creating the symlink (ermakovpetr's post above) fixed it for me, but adding a path should also work. (I think.)

**Comment by mghatiy** [comment]
I fixed the same issue by setting up environment as suggested above as well.
**ENV PATH=/opt/abc-username/bin:$PATH**

/opt/conda/bin/conda install --quiet --yes notebook jupyterhub \
     nodejs configurable-http-proxy

/opt/abc-username/bin is the path where I installed conda.

**Comment by prakhar987** [comment]
To preserve paths when using sudo, try 
sudo env "PATH=$PATH" jupyterhub

**Comment by byomkesh99** [comment]
Thanks minrk. You are awesome. Because of you, I was able to solve many Traceback from JH. Thanks again Man....

**Comment by Abdelrahman-Mahareek** [comment]
First you need to install node 
using brew install node
