### ISSUE TITLE
LocalAuthenticator.create_system_users not working

### ISSUE THREAD

**Issue by Habulinec** [jupyterhub/jupyterhub#932]
Hi all,

I have an issue with the LocalAuthenticator.create_system_users.
According the [documentation](http://jupyterhub.readthedocs.io/en/latest/config-examples.html) (at least as far as I've understood), the parameter c.LocalAuthenticator.create_system_users should create the OS user in case the user doesn't exist, correct?

We are using the LDAPAuthenticator, which is working, but if the user doesn't exist on the OS level, the jupyterhub returns a 500 page with the following info from the debug session:

```
[E 2017-01-11 15:19:50.042 JupyterHub user:245] Unhandled error starting habulinec's server: 'getpwnam(): name not found: habulinec'
[E 2017-01-11 15:19:50.063 JupyterHub web:1548] Uncaught exception POST /hub/login?next= (::ffff:10.181.13.226)
    HTTPServerRequest(protocol='https', host='hostname', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::ffff:10.181.13.226', headers={'Content-Type': 'application/x-www-form-urlencoded', 'Referer': 'https://hostname/hub/login', 'Content-Length': '37', 'X-Forwarded-Proto': 'https', 'X-Forwarded-Port': '443', 'Cache-Control': 'no-cache', 'X-Forwarded-For': '::ffff:10.181.13.226', 'Accept-Language': 'cs,en-GB;q=0.7,en;q=0.3', 'X-Forwarded-Host': 'hostname', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'close', 'Cookie': 'shpuvid=CmEGNVgYnnekfo2SBV7tAg==; _xsrf=2|4b73199f|2e606c0f0544ec2f03327b58fdcf4c8f|1482911792', 'Accept': 'text/html, application/xhtml+xml, image/jxr, */*', 'Host': 'hostname'})
    Traceback (most recent call last):
      File "/usr/lib64/python3.4/site-packages/tornado/web.py", line 1469, in _execute
        result = yield result
      File "/usr/lib/python3.4/site-packages/jupyterhub/handlers/login.py", line 84, in post
        yield self.spawn_single_user(user)
      File "/usr/lib/python3.4/site-packages/jupyterhub/handlers/base.py", line 328, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/usr/lib/python3.4/site-packages/jupyterhub/user.py", line 255, in spawn
        raise e
      File "/usr/lib/python3.4/site-packages/jupyterhub/user.py", line 229, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/lib/python3.4/site-packages/jupyterhub/spawner.py", line 765, in start
        env = self.get_env()
      File "/usr/lib/python3.4/site-packages/jupyterhub/spawner.py", line 757, in get_env
        env = self.user_env(env)
      File "/usr/lib/python3.4/site-packages/jupyterhub/spawner.py", line 744, in user_env
        home = pwd.getpwnam(self.user.name).pw_dir
    KeyError: 'getpwnam(): name not found: habulinec'
```

Following two lines have been added in the jupyterhub_config.py:

c.LocalAuthenticator.add_user_cmd = ['adduser {username}']
c.LocalAuthenticator.create_system_users = True

I've tried various examples of adduser commands and arguments, but none was working. The user won't be created.

Here's the rest of the jupyterhub_config.py:

c.JupyterHub.ssl_key = 'jupyterhub.key'
c.JupyterHub.ssl_cert = 'jupyterhub.crt'
c.JupyterHub.port = 443

c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_address = 'dns.site'
c.LDAPAuthenticator.bind_dn_template = 'CN={username},OU={username[0]},OU=Identities,DC=domain,DC=comp,DC=abc'
c.LDAPAuthenticator.valid_username_regex = '^[a-z][.a-z0-9_-]*$'
c.JupyterHub.pid_file = 'jupyter_pid'

And here's the output from the jupyter troubleshoot:

```

DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
$PATH:
        /usr/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /root/bin

sys.path:
        /usr/bin
        /usr/lib64/python34.zip
        /usr/lib64/python3.4
        /usr/lib64/python3.4/plat-linux
        /usr/lib64/python3.4/lib-dynload
        /usr/lib64/python3.4/site-packages
        /usr/lib/python3.4/site-packages

sys.executable:
        /bin/python3.4

sys.version:
        3.4.5 (default, Nov  9 2016, 16:24:59)
        [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

platform.platform():
        Linux-3.10.0-327.10.1.el7.x86_64-x86_64-with-redhat-7.2-Maipo

which -a jupyter:
        /usr/bin/jupyter
        /usr/bin/jupyter

pip list:
        alembic (0.8.9)
        backports-abc (0.5)
        bleach (1.5.0)
        decorator (4.0.10)
        entrypoints (0.2.2)
        html5lib (0.9999999)
        ipykernel (4.5.2)
        ipython (5.1.0)
        ipython-genutils (0.1.0)
        ipywidgets (5.2.2)
        Jinja2 (2.8)
        jsonschema (2.5.1)
        jupyter (1.0.0)
        jupyter-client (4.4.0)
        jupyter-console (5.0.0)
        jupyter-core (4.2.1)
        jupyterhub (0.7.0)
        jupyterhub-ldapauthenticator (1.1)
        ldap3 (2.1.1)
        Mako (1.0.6)
        MarkupSafe (0.23)
        mistune (0.7.3)
        nbconvert (5.0.0)
        nbformat (4.2.0)
        notebook (4.3.1)
        pamela (0.3.0)
        pandocfilters (1.4.1)
        pexpect (4.2.1)
        pickleshare (0.7.4)
        pip (9.0.1)
        prompt-toolkit (1.0.9)
        ptyprocess (0.5.1)
        pyasn1 (0.1.9)
        Pygments (2.1.3)
        python-editor (1.0.3)
        pyzmq (16.0.2)
        qtconsole (4.2.1)
        requests (2.12.4)
        setuptools (32.3.0)
        simplegeneric (0.8.1)
        six (1.10.0)
        SQLAlchemy (1.1.4)
        terminado (0.6)
        testpath (0.3)
        tornado (4.4.2)
        traitlets (4.3.1)
        wcwidth (0.1.7)
        wheel (0.29.0)
        widgetsnbextension (1.2.6)



```
Or am doing something wrong or I'm missing something?

Thanks a lot for help in advance.

With best regards

- Habu

**Comment by minrk** [comment]
Does `adduser username` result in creating a working user who can be inspected at the terminal?

**Comment by Habulinec** [comment]
Of course:
```
[root@hostname ~]# adduser habulinec
[root@hostname ~]# cat /etc/passwd | grep habulinec
habulinec:x:2005:2005::/home/habulinec:/bin/bash
```

**Comment by willingc** [comment]
@minrk It doesn't appear that the add user is handled in the LDAP_Authenticator https://github.com/jupyterhub/ldapauthenticator/blob/master/ldapauthenticator/ldapauthenticator.py#L124. 

I may be wrong, but doesn't `ldapadd` need to be used for adding the new user to the LDAP directory. See item 11 here: http://www.openldap.org/doc/admin24/quickstart.html

**Comment by Habulinec** [comment]
@willingc I don't think I need to add a new LDAP user. My LDAP user is present. It's the local user on the linux OS level, who's missing. Once I create the OS user with adduser, everything works fine - with the LDAP credentials.

**Comment by minrk** [comment]
@Habulinec once you've done that, can you do in Python:

```python
import pwd
print(pwd.getpwnam('habulinec').pw_dir
```

**Comment by willingc** [comment]
@Habulinec Ah... got it. Thanks. Let's see what @mirnk comes up with :-)

**Comment by minrk** [comment]
I think I see the issue. The `create_system_user` isn't getting triggered because the LDAPAuthenticator doesn't check for this.

I think the ldapauthenticator package needs to include a `LocalLDAPAuthenticator` for the case where:

1. LDAP is the authenticator, and 
2. PAM is *not* set up to talk to LDAP

which is not yet implemented, it looks like.

**Comment by willingc** [comment]
Now that I'm looking at the issues for the LDAPAuthenticator, it looks like there is also an open issue for create user there https://github.com/jupyterhub/ldapauthenticator/issues/29.

**Comment by Habulinec** [comment]
@minrk 
> 2.PAM is not set up to talk to LDAP

Correct. I forgot to mention that. I was trying to persuade our server guys to implement the ldap pam option for the OS level as well, but that didn't happen yet. 

End of story - enabling the LDAP in PAM on the OS level would most probably solve my issue, right?

**Comment by willingc** [comment]
@Habulinec Were you able to resolve your configuration issue with your server support team?

**Comment by Habulinec** [comment]
@willingc Sadly not. :-/ I'm busy with something else and haven't got the time to make sure the server is LDAP enabled.

Btw. how does it look with the implementation of the inclusion of the LocalLDAPAuthenticator into the ldapauthenticator? :)

**Comment by willingc** [comment]
Hi @Habulinec,

Closing this issue as it's been inactive for several months and LDAPLocalAuthenticator has been added to ldapauthenticator. Please feel free leave a message if you would like us to reopen this issue. Thanks! :sunflower:

**Comment by pmazzuca** [comment]
I am encountering the same issue as initially reported, but with a custom OAuthenticator.  It appears that the 'adduser' command is not being executed, though everything works fine when I manually create the user.  
   
    #from my jupyterhub_config.py
    c.LocalAuthenticator.add_user_cmd = ['adduser', '-q', '--gecos', '""', '--home', '/myhub/USERNAME', '--disabled-password']
    c.LocalAuthenticator.create_system_users = True

I am running jupyterhub inside a container and using the default spawner.

```
   FROM jupyterhub/jupyterhub:0.8.1

   RUN pip install oauthenticator pyjwt notebook

   RUN mkdir -p /etc/jupyterhub
   RUN mkdir -p /myhub
   #works when uncommented
   #RUN adduser -q --gecos "" --home /myhub/my_user_name --disabled-password my_user_name

   COPY custom_oauth_for_active_dir.py /srv/jupyterhub
   COPY jupyterhub_config.py /etc/jupyterhub

   ENV PYTHONPATH /srv/jupyterhub
   ENV OAUTH2_AUTHORIZE_URL https://login.microsoftonline.com/common/oauth2/authorize
   ENV OAUTH2_TOKEN_URL=https://login.microsoftonline.com/common/oauth2/token

   ENTRYPOINT jupyterhub --debug -f /etc/jupyterhub/jupyterhub_config.py
```

When using OAuthenticator, is there another step that must be taken in order to trigger the local user creation?

**Comment by pmazzuca** [comment]
I discovered that my issue was related to how I was importing my GenericAuthenticator in the jupyterhub_config.py.  The solution for me was to import the LOCAL version of the GenericAuthenticator.  So the first line in my jupyterhub_config file is
```
from my_package_name import LocalGenericOAuthenticator
```

Hope that helps others facing the similar issue.

**Comment by siralfbaez** [comment]
Hello Geeks,
New to JupyterHub and stressed/discouraged to the core. Is there any proven cases to show  jupyterhub that has been implemented on production with ssl/tls running on port 443?
I mean I was told this is easily implemented in 1 hour or so. I have over a week working through errors and undocumented and unsupported parameters on the jupyterhub-config.py file it's all confusing. At this point I'm seeking guidance to help resolve lates errors is greatly appreciated.
<<<
(base) [root@ip-172-30-1-140 hjupyter]# jupyterhub -f /root/jhub/jupyterhub_config.py
...
58.880 [ConfigProxy] error: Uncaught Exception
[C 2019-09-15 06:48:09.461 JupyterHub app:2349] Failed to start proxy
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.7/site-packages/jupyterhub/app.py", line 2347, in start
        await self.proxy.start()
      File "/opt/anaconda3/lib/python3.7/site-packages/jupyterhub/proxy.py", line 679, in start
        await server.wait_up(1)
      File "/opt/anaconda3/lib/python3.7/site-packages/jupyterhub/utils.py", line 189, in wait_for_server
        timeout=timeout,
      File "/opt/anaconda3/lib/python3.7/site-packages/jupyterhub/utils.py", line 177, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at 52.7.110.58:443 didn't respond in 1 seconds
'ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<JupyterHub.launch_instance_async() done, defined at /opt/anaconda3/lib/python3.7/site-packages/jupyterhub/app.py:2477> exception=SystemExit(1)>
Traceback (most recent call last):
>>>

**Comment by gaebor** [comment]
I have an even bigger issue, the `LocalAuthenticator` does not work at all:

```
FROM ubuntu:18.04

RUN apt update && apt -y upgrade

RUN apt -y install python3-pip npm libopenblas-dev \ 
&& npm install -g configurable-http-proxy \
&& pip3 install --no-cache notebook jupyterhub \
&& jupyterhub --generate-config

RUN echo 'test\ntest\n' | adduser test \
&& echo 'c.JupyterHub.authenticator_class = "jupyterhub.auth.LocalGenericAuthenticator"' > jupyterhub_config.py

CMD ["jupyterhub", "--debug"]
```
After running `docker run -it -p 8000:8000` on it, I cannot log in with `test` user :(

logs:
```
[I 2019-11-09 21:20:06.491 JupyterHub app:2120] Using Authenticator: jupyterhub.auth.LocalAuthenticator-1.0.0
[I 2019-11-09 21:20:06.492 JupyterHub app:2120] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.0.0
[I 2019-11-09 21:20:06.501 JupyterHub app:1302] Writing cookie_secret to /jupyterhub_cookie_secret
[I 2019-11-09 21:20:06.557 alembic.runtime.migration migration:154] Context impl SQLiteImpl.
[I 2019-11-09 21:20:06.559 alembic.runtime.migration migration:161] Will assume non-transactional DDL.
[I 2019-11-09 21:20:06.798 alembic.runtime.migration migration:513] Running stamp_revision  -> 4dc2d5a8c53c
[I 2019-11-09 21:20:09.618 JupyterHub proxy:460] Generating new CONFIGPROXY_AUTH_TOKEN
[W 2019-11-09 21:20:09.627 JupyterHub app:1532] No admin users, admin interface will be unavailable.
[W 2019-11-09 21:20:09.628 JupyterHub app:1534] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2019-11-09 21:20:09.630 JupyterHub app:1563] Not using whitelist. Any authenticated user will be allowed.
[I 2019-11-09 21:20:09.762 JupyterHub app:2337] Hub API listening on http://127.0.0.1:8081/hub/
[W 2019-11-09 21:20:09.768 JupyterHub proxy:642] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2019-11-09 21:20:09.768 JupyterHub proxy:645] Starting proxy @ http://:8000
21:20:10.942 [ConfigProxy] info: Proxying http://*:8000 to (no default)
21:20:10.953 [ConfigProxy] info: Proxy API at http://127.0.0.1:8001/api/routes
21:20:11.015 [ConfigProxy] info: 200 GET /api/routes
[I 2019-11-09 21:20:11.016 JupyterHub proxy:319] Checking routes
[I 2019-11-09 21:20:11.018 JupyterHub proxy:399] Adding default route for Hub: / => http://127.0.0.1:8081
21:20:11.032 [ConfigProxy] info: Adding route / -> http://127.0.0.1:8081
21:20:11.037 [ConfigProxy] info: Route added / -> http://127.0.0.1:8081
[I 2019-11-09 21:20:11.043 JupyterHub app:2422] JupyterHub is now running at http://:8000
21:20:11.045 [ConfigProxy] info: 201 POST /api/routes/

[I 2019-11-09 21:20:17.141 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.17.0.1) 8.23ms
[I 2019-11-09 21:20:17.197 JupyterHub log:174] 302 GET /hub/ -> /hub/login (@::ffff:172.17.0.1) 3.12ms
[I 2019-11-09 21:20:17.311 JupyterHub log:174] 200 GET /hub/login (@::ffff:172.17.0.1) 81.72ms
[W 2019-11-09 21:20:30.766 JupyterHub base:670] Failed login for test
[I 2019-11-09 21:20:30.779 JupyterHub log:174] 200 POST /hub/login?next= (@::ffff:172.17.0.1) 6.14ms

[C 2019-11-09 21:20:37.576 JupyterHub app:2448] Received signal SIGINT, initiating shutdown...
[I 2019-11-09 21:20:37.578 JupyterHub app:2155] Cleaning up single-user servers...
[I 2019-11-09 21:20:37.579 JupyterHub proxy:705] Cleaning up proxy[29]...
[I 2019-11-09 21:20:37.585 JupyterHub app:2187] ...done

```

**Comment by coden-ata** [comment]
I'm running into this issue running Jupyterhub in a Docker container under non-root privileges (under jovyan). I think that this happens because jovyan does not have rights to run useradd. I'm investigating workarounds, but would be happy to use a solution anyone else has come up with.

**Comment by nikita-balyschew-db** [comment]
I have the same issue, I want to run the LocalGitLabOAuthenticator and let the local user being created locally with luseradd, because it exists in LDAP, if it doesn't exist and give control to SudoSpawner but SudoSpawner can't run because the user isn't created and added to the group which allows issuing the sudo command. I would be glad if someone could help.

**Comment by EasonC13** [comment]
Found the solution here, and it works!
https://github.com/jupyterhub/ldapauthenticator/issues/107#issuecomment-771731193

Adding the following code to `jupyterhub_config.py`

```
from subprocess import check_call

def pre_spawn_hook(spawner):
    username = spawner.user.name
    try:
        check_call(['useradd', '-ms', '/bin/bash', username])
    except Exception as e:
        print(f'{e}')
c.Spawner.pre_spawn_hook = pre_spawn_hook
```

**Comment by HYBG-1126** [comment]
@gaebor did you resolve it?

**Comment by gaebor** [comment]
the (now default) PAM authenticator seems to be working:
```dockerfile
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt -y upgrade

RUN apt -y install python3-pip npm && npm install -g configurable-http-proxy
RUN python3 -m pip install jupyter jupyterhub

RUN echo 'test\ntest\n' | adduser test

CMD ["jupyterhub", "--debug"]
```
I haven't tried admin access, but it's fine 🎉
