### ISSUE TITLE
Improve logging information for services

### ISSUE THREAD

**Issue by ellisonbg** [jupyterhub/jupyterhub#934]
**How to reproduce the issue**

Configure a managed service, but forget to include the `command` argument (or other important ones, such as the URL)/

**What you expected to happen**

It would be nice is JupyterHub gave more information in the logging to indicate that a managed service had started or not and warned the admin if he service appears to not be working as expected. One option would be to have services implement a "health" endpoint that the hub and hit to make sure the service is running as expected.

**What actually happens**

JupyterHub fails to start the managed service, but the logs don't say that. When you go to access the service it fails.

**Share what version of JupyterHub you are using**

0.7.2.

**Comment by willingc** [comment]
@ellisonbg Good suggestion 👍

**Comment by minrk** [comment]
#939 should add more logging to startup, as well as some health checks, both at startup and periodically
