### ISSUE TITLE
API /user/{name} ambiguous

### ISSUE THREAD

**Issue by barrachri** [jupyterhub/jupyterhub#941]
Both PATCH and POST method accept this json body:

{
  "name":  "nameOFtheuser",
  "admin": true
}

The hub will use the {name} inside the URL but if you try to call the endpoint with a PATCH method and different names (body and url) you will get 

 sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush.]

I think it would better to accept only one name and not both.

I propose to remove the name from the json body and return an error in case is provided.

https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/apihandlers/users.py#L152
https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/apihandlers/base.py#L141
https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/apihandlers/base.py#L112

**Comment by minrk** [comment]
PATCH must accept the name, because that's how users are renamed. The name field looks to be ignored in POST, but it would be okay to add a failure if it's defined.

I think the rollback error here might be misleading, and could point to a different issue.

**Comment by barrachri** [comment]
https://github.com/jupyterhub/jupyterhub/pull/944
