### ISSUE TITLE
how to link jupter of anaconda between emacs

### ISSUE THREAD

**Issue by jameswq** [jupyterhub/jupyterhub#945]
hi , i dont know how to link jupyter of anaconda with emacs 25,thanks advanced.

**Comment by willingc** [comment]
Hi @jameswq,

Looking at the question, are you having trouble installing Jupyter Notebook using Anaconda? If you could provide more detail on your question, I can help guide you to the best place to ask your question. Thanks!

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
