### ISSUE TITLE
Config file doesn't load

### ISSUE THREAD

**Issue by rsinha25** [jupyterhub/jupyterhub#946]
Hi ,

I have written a config file for jupyter, and I would like it to be loaded when notebook is spawned through hub, but that isn't working for me. I have created a conda env, installed hub and lab in it through pip. Using Mac with Chrome. Hub spawns notebook but doesn't load the config which essentially does a couple of things along with redirecting to /lab. I have supplied the config file for notebook in the following way in Jhub config.

`c.Spawner.args = ['--config=/path/to/config']`

Could you help me with this?

Note: The config does get loaded when I start notebook in the following fashion:
`jupyter notebook --config=/path/to/config`

or lab similarly.

**Comment by minrk** [comment]
What Spawner are you using? Can you add `--debug` to the args and show the output of the command?

**Comment by rsinha25** [comment]
Hi, closing this. It was an issue with lab.
Thanks.
