### ISSUE TITLE
Using SASGSUB in SAS Kernel

### ISSUE THREAD

**Issue by sudipto84goswami** [jupyterhub/jupyterhub#947]
Hi Team,

Just wanted to check on the following things if possible : - 

1. Can we invoke SASGSUB utility from Jupyterhub. We do have SAS Kernel in our setup. Need the details on doing this.

2. We are having a clustered SAS Computational nodes. So as per current configuration we allow users to explicitly select the available node and submit there processes. Is there any process we can remove this dependency and allow the request from Jupyterhub to go through any of the available SAS Nodes.

Please let us know on this.

**Comment by willingc** [comment]
Hi @sudipto84goswami,

Good questions. We do not have a configuration that supports this out of the box. You would likely have to write something custom and/or extend one of the existing spawners, perhaps batchspawner.

> Can we invoke SASGSUB utility from Jupyterhub. We do have SAS Kernel in our setup.

This [recent issue](https://github.com/sassoftware/sas_kernel/issues/27) from [SAS kernel repo](https://github.com/sassoftware/sas_kernel) indicates that this is not yet implemented and supported by SAS.

> We are having a clustered SAS Computational nodes. So as per current configuration we allow users to explicitly select the available node and submit there processes.

Deferring to @minrk on what would be the approach to send processes to a particular node, my understanding is that this functionality does not exist in the current JupyterHub release.

As an FYI, you could also try asking on the Jupyter mailing list or Jupyter in HPC mailing list as there may be others in the community that have investigated this in more depth at their sites. Thanks.

**Comment by minrk** [comment]
> We are having a clustered SAS Computational nodes. So as per current configuration we allow users to explicitly select the available node and submit there processes. Is there any process we can remove this dependency and allow the request from Jupyterhub to go through any of the available SAS Nodes.

I'm not familiar with SAS and I don't fully understand how this is working, but the Spawner determines how notebook servers are started, and you could write a custom Spawner that changes how resources are allocated to use the SAS nodes.

**Comment by sudipto84goswami** [comment]
Thanks Benjamin for looking in my question. 

We have configured the saspy cfg with the connection information for our 5 computational SAS nodes. The saspy cfg resides at the Jupyter server and we have done both way key exchanges from SAS and Jupyter nodes. So when we open the notebook for SAS kernel and submit any of the SAS processes, it explicitly asks us to select on which SAS node the request is supposed to be routed.

The users over here, prefers that the request should be routed to any of the existing available SAS nodes. 

So just wanted to check if this is at all feasible!

**Comment by willingc** [comment]
Hi @sudipto84goswami,

Here's a link to documentation about how you could create a custom Spawner to meet your needs: https://jupyterhub.readthedocs.io/en/latest/spawners.html#writing-a-custom-spawner

Feel free to ask for help on the Gitter channel if you choose to do so. I'm going to close this issue as resolved.
