### ISSUE TITLE
HubAuth does not work with service tokens

### ISSUE THREAD

**Issue by DeepHorizons** [jupyterhub/jupyterhub#954]
It is currently not possible to authenticate a service using the HubAuth class.
When attempting to use a service token to authenticate a service via `/api/authorizations/token/{token}`,
 it returns a 404.

**How to reproduce the issue**
Take a service token and make a request to `/api/authorizations/token/{token}` using the token and the proper authorization header.

**What you expected to happen**
A User model is returned about the service, with a `name` and `admin` field.

**What actually happens**
The request returns with a 404

**Share what version of JupyterHub you are using**
0.7.2

**Comment by minrk** [comment]
#966 should implement service support in HubAuth
