### ISSUE TITLE
Using Nginx instead of http-proxy

### ISSUE THREAD

**Issue by barrachri** [jupyterhub/jupyterhub#957]
Sometimes when you deploy JupyterHub you use Nginx in front of everything.

Is there the possibility to use Nginx instead of http-proxy ?

Nginx + Lua + Redis should almost do the same job.

**Comment by ryanlovett** [comment]
https://github.com/yuvipanda/jupyterhub-nginx-chp/

It works well.

**Comment by willingc** [comment]
@barrachri Should this be closed now?

**Comment by minrk** [comment]
Yup, this is doable now.
