### ISSUE TITLE
Unreadable Notebook NotJSONError

### ISSUE THREAD

**Issue by mrinmoyprasad** [jupyterhub/jupyterhub#963]
Hi! 

I tried searching for this issue here https://github.com/jupyter/notebook/issues but could not find one. Since I am getting this error for almost all the users using JupyterHub-spawned single user notebook servers, I considered logging this issue here.

Notebook Version on Single User Notebook Server: 4.1.1
Python Version on Single User Notebook Server: Python 3.5.2 :: Continuum Analytics, Inc.
JupyterHub Version: 0.7.0.dev

I am using dockerspawner for spawning single user servers and also using docker image for jupyterhub itself to launch jupyterhub.

Thanks
Mrinmoy

**Comment by willingc** [comment]
Hi @mrinmoyprasad,

You are using an older development of JupyterHub. I recommend updating to the stable version 0.7.2. Also check that you are using the current dockerspawner release. I hope that helps.

**Comment by mrinmoyprasad** [comment]
Hi @willingc ,

Thank you for your quick reply! Can you point me to the more recent version of "JupyterHub" and "SingeUserServer for DockerSpawner" images?

Thanks
Mrinmoy

**Comment by willingc** [comment]
The process for upgrades of JupyterHub is [here](https://jupyterhub.readthedocs.io/en/latest/upgrading.html#). The DockerSpawner is found [here](https://github.com/jupyterhub/dockerspawner). And single user server images can be found in the [docker-stacks repo](https://github.com/jupyter/docker-stacks).

**Comment by minrk** [comment]
NotJSONError generally means that a file is not JSON when it's being opened. Can you show the full error message? Can you share one of the notebooks that fails to be opened?

**Comment by mrinmoyprasad** [comment]
Sorry for the late reply. Here is a screenshot of the error received. Unfortunately, I do not have the notebook, as I created another JupyterHub server and terminated the previous one.

Let me know if it helps

Thanks
Mrinmoy
![image001](https://cloud.githubusercontent.com/assets/8716532/22903019/284b99c2-f205-11e6-9ec1-667a6a0e005e.png)

**Comment by willingc** [comment]
Hi @mrinmoyprasad,

Thanks for the update. Although I can't be completely sure since you don't have the notebook still, I agree with Min that the notebook is not saved as valid JSON. One way that this happens is if the user saves the notebook using the browser's save feature instead of using Jupyter's user interface for saving. 

I'm going to close this issue. If you see it again, please let us know on the Gitter channel. Thanks!

**Comment by HuangHenghua** [comment]
Thanks for helping! The .ipynb file should be a json file rather than a html file. When I get it on Github, I should to view raw file or just git clone it .

**Comment by payalbhatia** [comment]
I am facing similar issue and while uploading the file on git, it shows the file is empty
