### ISSUE TITLE
Ability to perform an action on behalf of a user

### ISSUE THREAD

**Issue by DeepHorizons** [jupyterhub/jupyterhub#964]
There should exist a way to talk to a service pretending to be a user. This would enable two things:

1. Chaining services together, where all the responses would be as if the user was making it directly.
2. Have other parts of JupyterHub make requests to services and have any data filtering done on the service end rather than where the request was made.

This should be able to be done even if we are not inside a Tornado RequestHandler.

**Comment by minrk** [comment]
It's technically possible for a service to use the same token and/or cookie that it received to authenticate any further requests that it sends. I'm not sure stealing credentials like that is a good practice, though.

I think the only really decent way of supporting things like this is using proper OAuth in the Hub, where the service can ask for permission to take actions on behalf of the user.

Can you give some specific examples of use cases?

**Comment by DeepHorizons** [comment]
My specific use case is that I am making a spawner that will present a list of docker images that a user can choose to spawn into. Images are dynamically added using a service and viewing the list of available images can be filtered by user or by group. The spawner will grab the list and create the form for them. Ideally the list should already be filtered when the spawner gets it.

Another example I can foresee in the near future is having one service call another with the same filtering going on. Each service can be used by itself, filtering based on the user or group, in addition of another service calling it and getting the data.

**Comment by manics** [comment]
JupyterHub has support for OAuth in services
