### ISSUE TITLE
Cannot sign out when using Google OAuth

### ISSUE THREAD

**Issue by bdelwood** [jupyterhub/jupyterhub#967]
Torubleshoot:

> [I 2017-01-30 11:51:07.771 JupyterHub app:1528] JupyterHub is now running at http://127.0.0.1:8000/jupyterhub/
> [I 2017-01-30 11:51:09.586 JupyterHub log:100] 302 GET /jupyterhub/hub/ (bdelwood@::ffff:127.0.0.1) 4.44ms
> [I 2017-01-30 11:51:09.799 JupyterHub log:100] 200 GET /jupyterhub/hub/home (bdelwood@::ffff:127.0.0.1) 51.62ms
> [I 2017-01-30 11:51:14.976 JupyterHub login:19] User logged out: bdelwood
> [I 2017-01-30 11:51:14.985 JupyterHub log:100] 302 GET /jupyterhub/hub/logout (bdelwood@::ffff:127.0.0.1) 6.62ms
> [I 2017-01-30 11:51:15.008 JupyterHub log:100] 302 GET /jupyterhub/hub/ (@::ffff:127.0.0.1) 1.16ms
> [I 2017-01-30 11:51:15.028 JupyterHub log:100] 302 GET /jupyterhub/oauth_login (@::ffff:127.0.0.1) 1.07ms
> [I 2017-01-30 11:51:15.043 JupyterHub google:35] redirect_uri: 'https://my.domain/jupyterhub/hub/oauth_callback'
> [I 2017-01-30 11:51:15.048 JupyterHub log:100] 302 GET /jupyterhub/hub/oauth_login (@::ffff:127.0.0.1) 1.47ms
> [I 2017-01-30 11:51:15.653 JupyterHub google:57] google: username: "bdelwood"
> [I 2017-01-30 11:51:15.664 JupyterHub log:100] 302 GET /jupyterhub/hub/oauth_callback?code=<authcode> (@::ffff:127.0.0.1) 336.78ms

I am using the LocalGoogleOAuth, and authorization works fine. I have my gmail mapped to a local user. However, signing out does not work. Looking at the console when signing out, jupyterhub uses PAM to correctly sign out of the user, but then redirects the browser to the login page, which then automatically redirects to Google, and since the token is still valid, logs me right back in.  It appears that the logout button does not revoke the token from Google, so the local user signs out but Google authenticates the login automatically. 

Snippet of relevant config file:

> import os
> c.JupyterHub.authenticator_class = 'oauthenticator.google.LocalGoogleOAuthenticator'
> c.GoogleOAuthenticator.client_id = os.environ['OAUTH_CLIENT_ID']
> c.GoogleOAuthenticator.client_secret = os.environ['OAUTH_CLIENT_SECRET']
> c.GoogleOAuthenticator.oauth_callback_url = os.environ['OAUTH_CALLBACK_URL']
> ...
> c.Authenticator.username_map = {'username@gmail.com':'user'}
> 

Additionally, although I don't think this is the issue, I am running jupyterhub behind apache2.4.7 using reverse proxy. Here is a snippit of the conf file for the site:
```

<Location /jupyterhub/>
           ProxyPass http://localhost:8000/jupyterhub/
         ProxyPassReverse http://localhost:8000/jupyterhub/
</Location>


<LocationMatch "/jupyterhub/(user/[^/]*)/(api/kernels/[^/]+/channels|terminals/websocket)(.*)">
         ProxyPassMatch ws://localhost:8000/jupyterhub/$1/$2$3
         ProxyPassReverse ws://localhost:8000/jupyterhub/$1/$2$3
</LocationMatch>
```

**Comment by willingc** [comment]
@minrk Do you have any idea why the logout doesn't seem to be happening? It's working fine with GitHubOAuth on my instance. Are there additional steps needed for the GoogleOAuth?

**Comment by willingc** [comment]
Hi @bdelwood,

Hmm...I haven't seen this with logout before. Yet, I'm sure that we'll figure it out. Which version of JupyterHub `jupyterhub --version` are you using?

**Comment by bdelwood** [comment]
0..8.0.dev
Didn't realize I had the dev version.

**Comment by minrk** [comment]
This affects all OAuthenticators, I think (I just tested GitHub, and see the same thing).

I think this is rough sequence of events:

1. first authentication sends you through Google OAuth
2. on completed authentication, a cookie is used thereafter to authenticate with the Hub
3. Logout clears the cookie, but does not revoke the OAuth permission with Google
4. on next visit, we get the following sequence of events:
    - logout redirects
    - no cookie is found, redirect to login URL (/hub/oauth_login)
    - login URL redirects to Google OAuth
    - Google OAuth sees that authorization is already allowed, redirects back to Hub
    - Hub gets OAuth callback, logs you in by setting a new cookie

So I think it's not precisely that logout fails to log you out, but that after logging out, you end up logging right back in again through a series of redirects.

Ensuring that logout doesn't redirect to the Authenticator's login URL should do the trick.

**Comment by minrk** [comment]
#969 should do it.

**Comment by willingc** [comment]
@bdelwood I've just merged @minrk's fix into master. Please let us know if you have any issues now.

**Comment by bdelwood** [comment]
@willingc Fix works great.

**Comment by willingc** [comment]
Thanks for letting us know @bdelwood. @minrk is awesome.

**Comment by pgeez** [comment]
@willingc Is there any plan to release an Jupyterhub 0.7.3 image on DockerHub? I would like to pick up this fix but the lastest 0.7.x release on Docker is 0.7.2.

**Comment by rahulswimmer** [comment]
Ouath just makes the Google instance null, hence it  you out of Google. Now that's how the architecture is made. Logging out of Google, if you Logout of your app is a dirty work, but can't help if the requirement stipulates the same. Hence add the following to your signOut() function. My project was an Angular 6 app:

document.location.href = "https://www.google.com/accounts/Logout?continue=https://appengine.google.com/_ah/logout?continue=http://localhost:4200";

Here localhost:4200 is the URL of my app. If your login page is xyz.com then input that.

**Comment by MsDotNetRaja** [comment]
hi rahulswimmer, 
return Redirect("https://www.google.com/accounts/Logout?continue=https://appengine.google.com/_ah/logout?continue=http://localhost:12362");
it is not working for me to redirect to my local mvc application. please help me.
Anybody, please suggest. It is redirecting & signing off from google and local application, but bot redirecting to login page as given in link. Throwing error.
