### ISSUE TITLE
As a developer wanted to know , Why we need jupyter terminal

### ISSUE THREAD

**Issue by jai11** [jupyterhub/jupyterhub#979]
Hi! Thanks for using JupyterHub.

If you are reporting an issue with JupyterHub:

- Please use the [GitHub issue](https://github.com/jupyterhub/jupyterhub/issues)
  search feature to check if your issue has been asked already. If it has,
  please add your comments to the existing issue.

- Where applicable, please fill out the details below to help us troubleshoot
  the issue that you are facing. Please be as thorough as you are able to
  provide details on the issue.

**How to reproduce the issue**

**What you expected to happen**

**What actually happens**

**Share what version of JupyterHub you are using**

Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.

```

Insert jupyter troubleshoot output here


```

**Comment by jai11** [comment]
As a developer wanted to know why jupyter terminal will be required.

Ans what are the use cases of it.

**Comment by willingc** [comment]
Hi @jai11,

I'm not sure that I understand your specific question. It seems as if you are asking how to secure JupyterHub when used on a network. Here's the security section from the documentation: https://jupyterhub.readthedocs.io/en/latest/getting-started.html#security

**Comment by jai11** [comment]
Thanks ,

My question was about the uses of jupyter terminal as a user of Jupyter .

Why I need jupyter terminal. What are the use cases or conditions where I really need terminal to use.

As might the jupyter is giving you a feature a terminal one. So jupyter team have thought of the use cases around it , why really a user needs it.

**Comment by minrk** [comment]
@jai11 are you referring to the terminal you see in the notebook web interface? This is useful when the notebook server is the only access point for a given environment. It lets you run shell commands more conveniently than in the notebook, such as `git`, `vi`, etc. This is the same reason there is the plain text editor as well. 

If you want to force disconnects, the best way is to restart the user's server.

**Comment by jai11** [comment]
Thanks Minsk as always.. 

Just wanted to make sure any other use case apart from OS commands..  We require Jupiter terminal..
