### ISSUE TITLE
Hub doesn't source /etc/profile for notebooks/lab spawned by it.

### ISSUE THREAD

**Issue by rsinha25** [jupyterhub/jupyterhub#981]
I am using the default spawner with JupyterHub and it does not seem to be loading the /etc/profile. Is there some setting that needs to be added to the hub config file? Opening Notebooks by default loads the /etc/profile properly.

**Comment by minrk** [comment]
The default behavior of the Spawner is to `exec jupyterhub-singleuser` which does not initialize a shell. Right now, this can be changed to instantiate a shell by changing `c.Spawner.cmd` to point to a script, such as:

```bash
#!/bin/bash -l
exec /path/to/jupyterhub-singleuser $@
```

```python
c.Spawner.cmd = '/path/to/my-launch-script
```

but we could also expose options to instantiate a shell in the LocalProcessSpawner.

**Comment by manics** [comment]
Closing this as it's been open a while and there's a solution
