### ISSUE TITLE
Full value of cookie_secret not used as cookie_secret

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#986]
**How to reproduce the issue**

Changing the cookie_secret and restarting the hub process should log all users out (when their single-user servers are not running). So changing a random character towards the end of the cookie_secret should help.

**What you expected to happen**

Users are logged out.

**What actually happens**

No users are logged out, and everyone seems to continue to be logged in! Changing a character towards the beginning of the cookie_secret seems to do the trick, however.

**Share what version of JupyterHub you are using**

0.7.2

**Comment by yuvipanda** [comment]
I looked through the source code of tornado and can't seem to figure out if this is really happening (it just seems to be using a normal hmac value).

**Comment by minrk** [comment]
I can update the code to use 32B easily enough (#988). But what's strange to me is that changing a very long cookie secret *does* log users out in my experience. The whole secret is indeed taken into account, even though it's wasteful (#526).
