### ISSUE TITLE
Errors getting JupyterHub to launch

### ISSUE THREAD

**Issue by SteveFelker** [jupyterhub/jupyterhub#991]
Hi All,

  Hoping you can help me with errors getting JupyterHub to launch.  I have compiled and installed a fresh copy of Python3.6 on RHEL 6, then used pip to install jupyterhub (version jupyterhub-0.7.2).  When I try to start JupyterHub as root, I get the following error:

# jupyterhub
[I 2017-02-15 17:57:57.687 JupyterHub app:745] Writing cookie_secret to /usr/local/bin/jupyterhub_cookie_secret
[E 2017-02-15 17:57:57.696 JupyterHub app:1527]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 1524, in launch_instance_async
        yield self.initialize(argv)
      File "/usr/local/lib/python3.6/types.py", line 204, in __next__
        return next(self.__wrapped)
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 1307, in initialize
        self.init_db()
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 802, in init_db
        **self.db_kwargs
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/orm.py", line 572, in new_session_factory
        engine = create_engine(url, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine
        return strategy.create(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
        dbapi = dialect_cls.dbapi(**dbapi_args)
      File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
        raise e
      File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 334, in dbapi
        from pysqlite2 import dbapi2 as sqlite
    ModuleNotFoundError: No module named 'pysqlite2'

Reviewing other solutions to this issue, I have installed sqlite-devel.x86_64 with no improvement.

I have also tried replacing `from _sqlite3 import *` with `import sqlite3` in /usr/local/lib/python3.6/sqlite3/dbapi2.py, but that simply moves the error:

<...>
      File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
        from sqlite3.dbapi2 import *
      File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 51, in <module>
        version_info = tuple([int(x) for x in version.split(".")])
    NameError: name 'version' is not defined

Based on another post, I recompiled Python with the configure option --enable-loadable-sqlite-extensions, but again, it didn't help.

I'm running out of ideas.  Any recommendations?
Thanks!
Steve

**Comment by willingc** [comment]
Hi @SteveFelker,

We would be happy to help. If you could post the output of `jupyter troubleshoot` after running it from the command line, that would help us. Thanks.

**Comment by SteveFelker** [comment]
Thank you!  Here is the output from `jupyter troubleshoot`:

# jupyter troubleshoot 
Traceback (most recent call last):
  File "/usr/bin/jupyter-troubleshoot", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.6/site-packages/jupyter_core/troubleshoot.py", line 59, in main
    environment_data = get_data()
  File "/usr/lib/python2.6/site-packages/jupyter_core/troubleshoot.py", line 46, in get_data
    env['which'] = subs(['which', '-a', 'jupyter'])
  File "/usr/lib/python2.6/site-packages/jupyter_core/troubleshoot.py", line 25, in subs
    stdout = subprocess.check_output(cmd)
AttributeError: 'module' object has no attribute 'check_output'

Thanks,
Steve

**Comment by willingc** [comment]
Thanks @SteveFelker. It looks like you are getting a conflict between Python 2.6 (see troubleshooting output) and Python 3.6 (see original issue output). JupyterHub only runs on recent versions of Python 3. What were the specific commands that you used when installing Python and then JupyterHub?

I would recommend trying:

`python3 -m pip install -U jupyterhub`

**Comment by SteveFelker** [comment]
Hi Carol,

  Yes, I see that now.  How strange.  I am having flashbacks to perl library paths!

I downloaded the Python 3.6.0 source directly from python.org.  I tried a plain configure and also a configure --enable-loadable-sqlite-extensions.  Normal make, and then a make installalt so it ended up in /usr/local/bin.

For jupyterhub, I used:  
  python3.6 -m pip install jupyterhub

I ran the command you specified and it reported everything was up to date.  One odd thing that I noticed is that it installed jupyterhub in /usr/local/bin (likely because that is where python3.6 is), but it installed jupyter in /usr/bin.  At least I think it did.  I am not 100% sure that this was not already installed by someone else.   I will try the whole installation on another server just to rule out a conflict between old versions.  The version of jupyter in /usr/bin on this server appears to be 4.1.0:
jupyter --version
4.1.0

Thanks for the help,
Steve

**Comment by SteveFelker** [comment]
Hi Carol,

  A quick update.  It appears that an older version jupyter was already installed on the original server.  I performed a clean installation of python (no configure options), jupyter, and jupyterhub on a different server.  jupyterhub still fails with the same error:

jupyterhub
[I 2017-02-17 09:06:04.648 JupyterHub app:745] Writing cookie_secret to /usr/local/bin/jupyterhub_cookie_secret
[E 2017-02-17 09:06:04.655 JupyterHub app:1527]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 1524, in launch_instance_async
        yield self.initialize(argv)
      File "/usr/local/lib/python3.6/types.py", line 204, in __next__
        return next(self.__wrapped)
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 1307, in initialize
        self.init_db()
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 802, in init_db
        **self.db_kwargs
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/orm.py", line 572, in new_session_factory
        engine = create_engine(url, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine
        return strategy.create(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
        dbapi = dialect_cls.dbapi(**dbapi_args)
      File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
        raise e
      File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 334, in dbapi
        from pysqlite2 import dbapi2 as sqlite
    ModuleNotFoundError: No module named 'pysqlite2'

however, jupyter troubleshoot works:

jupyter troubleshoot
$PATH:
        /usr/local/bin
        /usr/local/bin
        /usr/local/sbin
        /sbin
        /bin
        /usr/sbin
        /usr/bin
        /root/bin

sys.path:
        /usr/local/bin
        /usr/local/lib/python36.zip
        /usr/local/lib/python3.6
        /usr/local/lib/python3.6/lib-dynload
        /usr/local/lib/python3.6/site-packages

sys.executable:
        /usr/local/bin/python3.6

sys.version:
        3.6.0 (default, Feb 17 2017, 08:52:48) 
        [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]

platform.platform():
        Linux-2.6.32-573.26.1.el6

Any idea what is going wrong?
Thanks again,
Steve

**Comment by minrk** [comment]
@SteveFelker this is a common issue when building Python yourself. `sqlite3` is part of the standard library, and normally used by JupyterHub. However, if sqlite3 is not found, Python will build and install without this part of the stdlib instead of raising an error. The best thing to do is make sure that you have libsqlite3 when building Python. If you can't get stdlib sqlite3 to work, you can install an alternate implementation of sqlite3 called `pysqlite2` as a normal package:

    pip install pysqlite2

That's why you are seeing it in the error. It's not an automatic dependency of JupyterHub because Python doesn't have a way of expressing "depend on this if the stdlib doesn't work".

**Comment by willingc** [comment]
Thanks @minrk. You beat me to this.

**Comment by SteveFelker** [comment]
Thanks guys,
  Being new to python, how would I make sure that `sqlite3` is present and recognized, and if not, get it and enable it?  I see this folder: /usr/local/lib/python3.6/sqlite3, so I am inclined to believe it is at least partially installed.

  I attempted to install `pysqlite2` but got the following error:

python3.6 -m pip install pysqlite2
Collecting pysqlite2
  Could not find a version that satisfies the requirement pysqlite2 (from versions: )
No matching distribution found for pysqlite2

Where should I go from here?
Thanks,
Steve

**Comment by willingc** [comment]
What happens if you execute:

```
python3 -m sqlite3 --version
```

**Comment by willingc** [comment]
You could also install the Anaconda distribution that includes Python 3.6 which would avoid having to build Python from source: https://www.continuum.io/downloads#linux

**Comment by SteveFelker** [comment]
Not good:

python3.6 -m sqlite3 --version 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

-- 

Yes, we have Anaconda installed, but it has python version 2.7.11, and I can't upgrade it at this point for fear of breaking other things that people are using.

Steve

**Comment by willingc** [comment]
@SteveFelker Sorry I gave you the wrong command initially. Please try these:

```
sqlite3 --version
```
or

```
cd /usr/local/lib/python3.6
sqlite3 --version
```

**Comment by SteveFelker** [comment]
Hi Carol,

  That worked better:

sqlite3 --version
3.6.20

which sqlite3
/usr/bin/sqlite3

find /usr -name sqlite3 -print
/usr/bin/sqlite3
/usr/lib64/python2.6/sqlite3          <-- could this be causing me a problem?
/usr/local/lib/python3.6/sqlite3

Steve

**Comment by willingc** [comment]
I think what is happening is that the location of sqlite3 for python3 is not in your PATH. Adding it to the path might help.

**Comment by minrk** [comment]
@SteveFelker sorry, that should have been `pip install pysqlite` not `pysqlite2`.

**Comment by willingc** [comment]
@minrk The docs (and error message) on pysqlite say that Python3 is not supported. Message when running pip:

```
pysqlite is not supported on Python 3. When using Python 3, use the sqlite3 module from the standard library.
```

**Comment by SteveFelker** [comment]
Yes Carol, you are correct.  I had previously tried to install pysqlite after pysqlite2 failed and got the same warning to use sqlite3.

As for my path, sqlite3 is in /usr/bin which is in my command path ($PATH).  I have no variable called $PYTHONPATH defined.  I put /usr/bin in it, but it didn't help.  I am guessing that $PYTHONPATH is for python libraries outside the default location (like with perl), and not for /usr/bin or similar binaries.

How do I make sure sqlite3 is in my python path?

Thanks,
Steve

**Comment by willingc** [comment]
Please post output these commands:
```
echo $PATH
echo $PYTHONPATH
```


For example on my system:

My $PATH contains `/usr/local/bin:/usr/bin` where python3 is found in `/usr/local/bin` and sqlite3 in `/usr/bin/sqlite3`. My $PYTHONPATH is empty.

```
[12:37:42] carol@cw-pro in ~ $ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin
[12:37:50] carol@cw-pro in ~ $ echo $PYTHONPATH

[12:38:03] carol@cw-pro in ~ $ which -a sqlite3
/usr/bin/sqlite3
[12:38:16] carol@cw-pro in ~ $ sqlite3 --version
3.14.0 2016-07-26 15:17:14 91e811f51e611a37372875e96a4c51bbed2dfdea
[12:38:28] carol@cw-pro in ~ $ python3
Python 3.6.0 (default, Dec 24 2016, 08:01:42)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.
sqlite3.Binary(                      sqlite3.SQLITE_DROP_TEMP_VIEW
sqlite3.Cache(                       sqlite3.SQLITE_DROP_TRIGGER
sqlite3.Connection(                  sqlite3.SQLITE_DROP_VIEW
sqlite3.Cursor(                      sqlite3.SQLITE_IGNORE
sqlite3.DataError(                   sqlite3.SQLITE_INSERT
sqlite3.DatabaseError(               sqlite3.SQLITE_OK
sqlite3.Date(                        sqlite3.SQLITE_PRAGMA
sqlite3.DateFromTicks(               sqlite3.SQLITE_READ
sqlite3.Error(                       sqlite3.SQLITE_REINDEX
sqlite3.IntegrityError(              sqlite3.SQLITE_SELECT
sqlite3.InterfaceError(              sqlite3.SQLITE_TRANSACTION
sqlite3.InternalError(               sqlite3.SQLITE_UPDATE
sqlite3.NotSupportedError(           sqlite3.Statement(
sqlite3.OperationalError(            sqlite3.Time(
sqlite3.OptimizedUnicode(            sqlite3.TimeFromTicks(
sqlite3.PARSE_COLNAMES               sqlite3.Timestamp(
sqlite3.PARSE_DECLTYPES              sqlite3.TimestampFromTicks(
sqlite3.PrepareProtocol(             sqlite3.Warning(
sqlite3.ProgrammingError(            sqlite3.adapt(
sqlite3.Row(                         sqlite3.adapters
sqlite3.SQLITE_ALTER_TABLE           sqlite3.apilevel
sqlite3.SQLITE_ANALYZE               sqlite3.collections
sqlite3.SQLITE_ATTACH                sqlite3.complete_statement(
sqlite3.SQLITE_CREATE_INDEX          sqlite3.connect(
sqlite3.SQLITE_CREATE_TABLE          sqlite3.converters
sqlite3.SQLITE_CREATE_TEMP_INDEX     sqlite3.datetime
sqlite3.SQLITE_CREATE_TEMP_TABLE     sqlite3.dbapi2
sqlite3.SQLITE_CREATE_TEMP_TRIGGER   sqlite3.enable_callback_tracebacks(
sqlite3.SQLITE_CREATE_TEMP_VIEW      sqlite3.enable_shared_cache(
sqlite3.SQLITE_CREATE_TRIGGER        sqlite3.paramstyle
sqlite3.SQLITE_CREATE_VIEW           sqlite3.register_adapter(
sqlite3.SQLITE_DELETE                sqlite3.register_converter(
sqlite3.SQLITE_DENY                  sqlite3.sqlite_version
sqlite3.SQLITE_DETACH                sqlite3.sqlite_version_info
sqlite3.SQLITE_DROP_INDEX            sqlite3.threadsafety
sqlite3.SQLITE_DROP_TABLE            sqlite3.time
sqlite3.SQLITE_DROP_TEMP_INDEX       sqlite3.version
sqlite3.SQLITE_DROP_TEMP_TABLE       sqlite3.version_info
sqlite3.SQLITE_DROP_TEMP_TRIGGER
>>> sqlite3.version_info
(2, 6, 0)
>>> sqlite3.sqlite_version
'3.17.0'
>>> sqlite3.dbapi2
<module 'sqlite3.dbapi2' from '/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sqlite3/dbapi2.py'>
>>> exit()

```

**Comment by SteveFelker** [comment]
Hi Carol,

My output up until trying to using sqlite3 in python is almost identical to yours.  My python is in /usr/local/bin, and sqlite3 is in /usr/bin.

echo $PATH
/usr/local/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin

echo $PYTHONPATH

which -a sqlite3
/usr/bin/sqlite3

sqlite3 --version
3.6.20

python3.6
Python 3.6.0 (default, Feb 16 2017, 10:46:02) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
>>> 

I had tried putting /usr/bin in my PYTHONPATH, but it didn't make any difference, so I took it out.

Thanks,
Steve

**Comment by minrk** [comment]
@willingc good catch, I hadn't seen that pysqlite doesn't support Python 3.

Then the issue really is to rebuild Python with sqlite support. Python will warn that it is not building sqlite, but it produces a lot of output during build, so it is easy to miss. Make sure you have the `sqlite-devel` (possibly sqlite3-devel) package installed before building Python, and save the Python build output so you can check and verify that it is indeed building with sqlite support.

At the end of build, there will be a message like this:

```
The necessary bits to build these optional modules were not found:
_sqlite3               ossaudiodev           spwd
```

telling you what modules it couldn't build due to missing dependencies. Ideally, that list should be just about empty, but it must not have sqlite3 in it.

**Comment by minrk** [comment]
> Yes, we have Anaconda installed, but it has python version 2.7.11, and I can't upgrade it at this point for fear of breaking other things that people are using.

Conda can use environments, so you don't have to modify the existing install to install additional versions of packages in new environments. This includes Python itself. For instance, you should be able to do:

    conda create -n jupyterhub -c conda-forge jupyterhub

to install Python 3 and JupyterHub in a conda environment called `jupyterhub`. Then you should be able to launch JupyterHub with:

    source activate jupyterhub # activate the jupyterhub environment
    jupyterhub # launch jupyterhub

**Comment by SteveFelker** [comment]
@minrk, thank you for the tips.  If possible, I would like to avoid using Conda, even with a different environment, because it is part of a package that we get from another company and can be upgraded or reinstalled, which would require me to keep reinstalling jupyterhub.  If that becomes the only option, I will deal with it, of course, but I would like to exhaust other options first.

I had installed sqlite-devel.x86_64 on the server I started with, and since it didn't help, I didn't install it on this server.  Now, I have installed it and re-built Python 3.6.0.  As you suspected there were warning messages hiding in the output.  Specifically:

`...../Python-3.6.0/Modules/_sqlite/cursor.c:517: warning: implicit declaration of function âsqlite3_stmt_readonlyâ`

`*** WARNING: renaming "_sqlite3" since importing it failed: build/lib.linux-x86_64-3.6/_sqlite3.cpython-36m-x86_64-linux-gnu.so: undefined symbol: sqlite3_stmt_readonly`

and

`Following modules built successfully but were removed because they could not be imported:
_sqlite3`

I realize that I have strayed from jupyterhub support at this point, but any suggestions you might have to resolve this issue would be greatly appreciated.

Thanks,
Steve

**Comment by willingc** [comment]
Hi @SteveFelker,

@minrk There is an open bug on sqlite, Python3.6 and RHEL6 (https://bugs.python.org/issue29355).

A few things to try:

- Try building Python using the instructions in the Python Developers Guide (https://docs.python.org/devguide/index.html)
- Make sure to run `make clean` before rebuilding Python.
- If the above does not help, you could try to run `make altinstall` instead of `make install`. `make altinstall` https://docs.python.org/3/using/unix.html#building-python
- If all else fails, ask on #python IRC channel.

**Comment by SteveFelker** [comment]
@willingc,  I am not sure that my problem is the same as issue29355.  It appears that issue was resolved in sqlite3 version 3.7.4, so installed the latest version (3.17.0), replacing my old version (3.6.20), then I tried to recompile Python 3.6.0.  I got exactly the same compile error as before.

Steve

**Comment by willingc** [comment]
See the code in the last link. It seems as if building against a newer version of sqlite should help.

https://github.com/pypa/manylinux/issues/90
https://github.com/pypa/manylinux/pull/93
https://github.com/pypa/manylinux/pull/93/commits/f8d94804838c00993700811cd8b50e6a10ab83da

**Comment by animalize** [comment]
@SteveFelker , you may try to build CPython in this way:
http://stackoverflow.com/questions/26261080/compile-python-3-4-with-sqlite3
I installed SQLite 3.16.2 on a Debian-based system with tzot's method, no idea whether it will work on RHEL 6.

**Comment by SteveFelker** [comment]
@willingc, I have already installed the latest version of sqlite3 (version 3.17.0), and I am getting the same errors trying to compile Python.  Which is why I mentioned above that I don't think issue 29355 is the cause.

@animalize, I am not having a problem with Python running the wrong version of sqlite3, I have only 1 version installed.  It's just refusing to include it in the build.

**Comment by animalize** [comment]
>  It appears that issue was resolved in sqlite3 version 3.7.4, so installed the latest version (3.17.0), replacing my old version (3.6.20), then I tried to recompile Python 3.6.0. I got exactly the same compile error as before.

I removed old SQLite, then compiled & installed a new version of SQLite. 
But it seems the old SQLite still stay in somewhere of my system, and CPython still try to link the old one during compilling.
I guess you are facing the same problem, otherwise you won't see "the same compile error as before". So try tzot's method in that stackoverflow question.

**Comment by SteveFelker** [comment]
@animalize, I was becoming tired of compiling things from source, so I just grabbed a pre-compiled copy of sqlist3.  It consisted of 1 file only: sqlite3.  There were no libraries, so I wouldn't even know what to change in my LD_RUN_PATH.  I gzipped the old version of sqlist3 so that nothing could find or use it, and put the new version in the same location (/usr/bin).  The new sqlite3 does work despite not having any associated libraries:

`sqlite3 --version
3.17.0 2017-02-13 16:02:40 ada05cfa86ad7f5645450ac7a2a21c9aa6e57d2c`

Worried that you might be right about it finding a different copy that someone else had installed, I searched the entire filesystem.  I found another copy of sqlite3 elsewhere, but it's not in my path, and it is version 3.9.2, which is also newer than the version with the fix (v3.7.4) so even if it did find that one during compiling, I shouldn't get the error I am seeing if it really is attributable to issue 29355.

**Comment by animalize** [comment]
@SteveFelker 

> a pre-compiled copy of sqlist3. It consisted of 1 file only: sqlite3

Not this one, `sqlite3.h` is required for building CPython.

Anyway, it seems sqlite3_stmt_readonly() can be removed in CPython 3.6.1 ([issue29355](http://bugs.python.org/issue29355)), schedule:

- 3.6.1 candidate: 2017-02-27
- 3.6.1 final: 2017-03-13

If you don't mind using a release candidate, just wait a few days.  
And [a topic FYI](http://stackoverflow.com/questions/6014332/issue-with-gem-install-sqlite3-ruby-on-rhel6).

**Comment by willingc** [comment]
@animalize Thanks for following up. I did see the discussion on bugs.python.org about removing in 3.6.1. Thanks for your help here. :sunny:

@SteveFelker I would recommend using 3.6.1 either the release candidate or the final version.

I'm going to close this. If CPython 3.6.1 does not resolve this, please feel free to reopen. Thanks!

**Comment by SteveFelker** [comment]
Will test compiling sqlite3 from source, and if that still doesn't help, I'll wait for python 3.6.1.

Thanks everybody for the help.

**Comment by SteveFelker** [comment]
Not sure if this thread will take anything else since it's been closed, but I have an update that I'll try to post...

I grabbed the latest sqlite3 source and compiled it, then installed it in /usr/local/.
I then set my LD_LIBRARY_PATH to point to /usr/local:
export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/include

Then I configured it using:
./configure --with-pydebug --enable-loadable-sqlite-extensions

And it built!  With no mention of sqlite3 being excluded!
Then make altinstall
And voila!

jupyterhub
[I 2017-02-23 14:48:45.032 JupyterHub app:745] Writing cookie_secret to /tmp/jupyterhub_cookie_secret
[W 2017-02-23 14:48:45.223 JupyterHub app:365] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[W 2017-02-23 14:48:45.242 JupyterHub app:864] No admin users, admin interface will be unavailable.
[W 2017-02-23 14:48:45.242 JupyterHub app:865] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2017-02-23 14:48:45.243 JupyterHub app:892] Not using whitelist. Any authenticated user will be allowed.
[I 2017-02-23 14:48:45.288 JupyterHub app:1453] Hub API listening on http://127.0.0.1:8081/hub/
[W 2017-02-23 14:48:45.298 JupyterHub app:1174] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2017-02-23 14:48:45.298 JupyterHub app:1176] Starting proxy @ http://*:8000/
[E 2017-02-23 14:48:45.304 JupyterHub app:1184] Failed to find proxy ['configurable-http-proxy']
    The proxy can be installed with `npm install -g configurable-http-proxy`

Thanks again for getting me pointed in the right direction!
Steve

**Comment by willingc** [comment]
Thanks @SteveFelker. Glad you are up and running. Thanks for passing along the details.

As a GitHub FYI, you can comment on closed issues as long as the maintainer has not locked the issue which prevents future comments. We don't typically lock our closed issues.

**Comment by SteveFelker** [comment]
@willingc, well, I wouldn't say I'm up and running, but at least it isn't dying from library issues.  Now I have moved on to trying to figure out how to configure it so it actually starts.  Fortunately, it seems to be well documented, so I suspect that won't be too bad.  But if I run into trouble, I know where to come for help! :)
Steve

**Comment by willingc** [comment]
Thanks @SteveFelker. Feel free to ask questions on the Gitter channel for JupyterHub too. If something is missing or confusing in the documentation, please leave us an issue (or PR :smile:) too since we're open to improving it for our users.

**Comment by yechangyao** [comment]
Hi I met exactly the same problems and after reinstalling python 3.6.1 the problem solved.
Just for information sharing.

**Comment by meranamvarun** [comment]
I am on centos 6 and this worked for me 
ln -s /usr/lib64/python2.6/lib-dynload/_sqlite3.so /usr/local/lib/python2.7/lib-dynload/
