### ISSUE TITLE
[Question] Is there real-time sharing support in Jupyterhub?

### ISSUE THREAD

**Issue by v3ss0n** [jupyterhub/jupyterhub#992]
Please feel free to close. I read a few years ago that this has been worked on. Jupyterhub have it now?

**Comment by willingc** [comment]
Hi @v3ss0n,

You can refer to [this issue](https://github.com/jupyterhub/jupyterhub/issues/394) about the current state of notebook sharing and real time collaboration in a notebook.

[JupyterHub's roadmap](https://github.com/jupyter/roadmap/blob/master/jupyterhub.md) also gives additional information.

I'm going to close this as a duplicate of #394

**Comment by v3ss0n** [comment]
thank you very much , so it is planned in 0.8 of jupyterhub ?

**Comment by willingc** [comment]
Yes, as described in the roadmap. cc @minrk
