### ISSUE TITLE
The right Access to Jupyter  

### ISSUE THREAD

**Issue by bloodymind** [jupyterhub/jupyterhub#993]
Hi ,

i guess i'm the only who stacked on this :

![image](https://cloud.githubusercontent.com/assets/4992012/23139814/401765bc-f7a6-11e6-9ea2-c8c35a0cb8bc.png)

**Comment by willingc** [comment]
Hi @bloodymind,

Would you mind clarifying your question? Also, what version of JupyterHub are you running? `jupyterhub --version`

Thanks!

**Comment by qingzhouzhen** [comment]
help! I am really confused what is the usename and password, I entered the username and password of my Linux, but is show me PAM authenticated failed? how could login? I just installed the jupyterhub

**Comment by minrk** [comment]
@qingzhouzhen if jupyterhub is run as you, then it will be your username and password. Other users will not be able to login by default. If it is run as root, it can be any username and password on the system. If it is run as any other user, jupyterhub will need to be given permission to check passwords (such as adding it to the `shadow` group on Ubuntu).

**Comment by qingzhouzhen** [comment]
Thanks a lot, I logined my remote Linux through  Mobaxterm as root, and installed jupyterhub, I add root user and some other users to the whitelist of  jupyterhub_config.py, now other users added to the whitelist can login but root, how can root user login remotely? @minrk

**Comment by minrk** [comment]
> how can root user login remotely?

if there is a root password, root can login. I probably wouldn't recommend allowing users to login to JupyterHub as root, though.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!

**Comment by qingzhouzhen** [comment]
I still got that problem, The root user can not login from browser login page, but when I login the Control Panel through other users, I can start server of the root user, this is my jupyterhub_config.py
 c.JupyterHub.admin_access = True
c.Authenticator.admin_users = {'root','jupyterhubuser1', 'jupyterhubuser2', 'jupyterhubuser4'}
c.Authenticator.whitelist = {'root',  'jupyterhubuser1', 'jupyterhubuser2','jupyterhubuser4','jupyterhubnoadmin'}
c.LocalAuthenticator.create_system_users = True
other config is default
The log said: PAM Authentication failed (root@xxx.xxxx.xxxx.xxxx): [PAM Error 3] Error in service module

**Comment by willingc** [comment]
Hi @qingzhouzhen,

I'm reopening this issue. 

As @minrk stated, I wouldn't recommend allowing users to login as root. Instead, I would recommend setting up the `jupyterhub_config.py` to:

```
c.JupyterHub.admin_access = True
c.Authenticator.admin_users = {'jupyterhubuser1', 'jupyterhubuser2', 'jupyterhubuser4'}
c.Authenticator.whitelist = {'jupyterhubuser1', 'jupyterhubuser2','jupyterhubuser4','jupyterhubnoadmin'}
c.LocalAuthenticator.create_system_users = True
```

and use passwordless SSH key based access to the server for the admin users that need root access to the server. These users would have 'root' access through their SSH keys. [Ubuntu reference re: Disable password authentication](https://help.ubuntu.com/community/SSH/OpenSSH/Configuring#disable-password-authentication)

**Comment by qingzhouzhen** [comment]
Why others can but me, I will keep looking for the answer, If you have any advice, tell me please

**Comment by willingc** [comment]
What are you using for your server @qingzhouzhen? Server type (bare metal or vm)? Operating system?

**Comment by qingzhouzhen** [comment]
Ubuntu 14.04.5 LTS,  and it is assigned by my company, every employee will get a root account and password, it uses just like bare metal, I think it is something like VPS of AWS

**Comment by myidealab** [comment]
@willingc I seem to have similar user authentication issues as others. My SSL cert is working and I added the admin_access and create_system_users settings that were suggested above. However, I have not been able to successfully login with other users. I've seen reference to shadow group and [sudospawner](https://github.com/jupyterhub/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges), so I am in the process of diving deeper into the process of creating users after installing sudospawner. Any additional tips or suggestions are greatly appreciated.
