### ISSUE TITLE
Launch a jupyterHub server while running a standard jupyter server

### ISSUE THREAD

**Issue by billgreenwald** [jupyterhub/jupyterhub#995]
Hi!

I currently have a jupyterHub server set up, as well as a local jupyter install that I can run via "jupyter notebook."

They both appear to use the same ".jupyter" directory in my home folder to store their settings.  To launch a jupyterHub server, I have to renamed my .jupyter directory, and then rename my .jupyter Hub directory to .jupyter.

Similarly, if I wish to launch a local server, I need to rename my .jupyter Hub directory and then rename my .jupyter Server directory to .jupyter.

Is there a way to have these programs not look in the same folder?

My exact code I use to fix this problem is as follows (assume that my personal server folder is .jupyterSelf and my jupyterHub config is in .jupyterHub.

To run a server myself:
```
mv .jupyterSelf .jupyter
jupyter notebook
```

To launch a Hub server:
```
mv .jupyter .jupyterSelf
mv .jupyterHub .jupyter
```

**Comment by minrk** [comment]
You can set the JUPYTER_CONFIG_DIR environment variable in one environment or the other to make sure the env is different.

**Comment by billgreenwald** [comment]
Thanks!

Just for reference to anyone else that sees this, and to check that I didn't do something odd, since we are using the batchSpawner and passing -V to use our personal environment variables, I had to wrap the setting of JUPYTER_CONFIG_DIR in an if statement to make sure it was only set during the jupyterHub sessions, and not my local notebook sessions.

**Comment by minrk** [comment]
For future reference, what were the particular settings that you wanted to be different, if you can share?

**Comment by billgreenwald** [comment]
We used to have each person in our group running their own personal jupyter notebook server on a head node in our cluster.  Each person set up their own port for use, and personal login information for their notebook session.  

We recently installed the jupyterhub so that we could launch notebooks onto our compute nodes for interactive jobs.  However, sometimes we have batch jobs that use up all the cores in our cluster.  For these situations, it is useful to be able to launch our jupyter notebooks on the head node and free up the compute nodes for people to use.

As the batchspawner launches jobs as the user that is logged in to the hub, it sources that users .jupyter folder for config files.  However, these files were set up for specific ports, and our own SSL certs, so something in the config file didn't play nicely with the jupyterHub configuration requirements.

By separating our configuration folders into two folders (one for jupyterHub and one for personal servers), we no longer have a conflict and can easily swap between notebooks on the head node or notebooks on the cluster.

Let me know if you need more information

**Comment by minrk** [comment]
Thanks! Most options that can conflict with the single-user server setup should perhaps be disabled in the SingleUser subclass of NotebookApp, which is why I asked. While the environment variables should allow you to opt-in to different configurations, I don't want you to have to do it just to get it working at all.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. If the issue still exists, please leave a comment requesting this issue be reopened. Thanks to all!

Labeling the issue for Reference.
