### ISSUE TITLE
Create a gallery of interesting JupyterHub deployments

### ISSUE THREAD

**Issue by willingc** [jupyterhub/jupyterhub#999]
Create a wiki page for JupyterHub deployments similar to the Jupyter and IPython galleries (https://github.com/jupyter/jupyter/wiki/A-gallery-of-interesting-Jupyter-Notebooks) to highlight actual deployments of JupyterHub.

**Comment by whitead** [comment]
How do you imagine highlighting a deployment? Like a description of how it's used and how it's deployed? I can't think of any compelling screenshots.

**Comment by willingc** [comment]
@whitead I think text, scripts, and architecture diagrams would all be valuable. Screenshots would not be necessary. @zonca recently put a [deployment example in the HPC repo](https://github.com/jupyterhub/jupyterhub-deploy-hpc/tree/master/batchspawner-xsedeoauth-sshtunnel-sdsccomet). I've also been culling resources this past week which I hope to get in a more presentable state ([WIP doc](https://github.com/willingc/jupyterhub-deploy-hpc/blob/resources/jhub_deployments.md). At this point, I think any deployment examples are helpful to others :smile:

**Comment by johannjc** [comment]
At the University of Rochester, we've modified batchspawner to allow for independent selections of memory, cores, time, etc... instead of the simple drop down list for use on our slurm cluster.

**Comment by whitead** [comment]
@johannjc The interface is very nice, you should get a screenshot of it.

I'm also at UR and made a deployment for Chemical Engineering. We do nginx reverse proxy, dockerspawner, google oauth/google drive, and supervisord. Pretty standard deployment, but I'll see if I can put together a few relevant config files. There is no public facing website for ours though that can be linked.

**Comment by willingc** [comment]
Closed by #1014
